### ISSUE TITLE
Practical bug: HUE color unjustly changed by Homey + Homey UI not reflecting changed color from other source

### ISSUE THREAD

**Issue by athomey** [athombv/homey#10]
My girlfriend uses an app to change color of a light. VeraEdge updates the bulb to the correct color (but even when not updated YET, when doing on/off in Vera the color my girlfriend chose is left alone). Also Philips native app, and also the popular Lights Control app also update correctly and function correctly as expected with chosing on/off.  Bug 1 Homey UI does not get updated...

...Bug 2 then when doing on/off from Homey from a flow for example, explicitly NOT chosing to change the color (if that were the case I would have added the change-color card), the color gets unjustly changed by Homey, being reset to the last color Homey knew (or has set on the device card under devices I imagine?), instead of leaving the color of the bulb as it was (already changed by a different source). 

The latter is expected in real life, so now my girlfriend is unhappy. :-)

**Comment by WeeJeWel** [comment]
Unfortunately, Philips does not provide a realtime API, so this issue cannot be fixed.

**Comment by athomey** [comment]
You only responded to issue 1. About that: Would it technically be an option to get it fixed, by polling the status for example? The Hue apps seem to be able to do this, and 90% sure that the VeraEdge does the same. 

About issue 2, you looked over that I think, could you reread. It looks like a bug when triggering on/off in a flow, ALSO the color is changed. This is a bug. Please reopen?

**Comment by WeeJeWel** [comment]
I'm not a fan of polling - will investigate if there's a better option.

Issue 2 is known, will keep it open until fixed, thanks.

**Comment by athomey** [comment]
Thx! Understandable that you don't want to poll. Too much load if you have too much polled devices. But I think you have to find SOME solution, cause your competitors provide this and people use this.

Issue 2: Wonderful. I'll be patient.

**Comment by WeeJeWel** [comment]
Issue 2 should be fixed, please check by re-installing https://apps.athom.com/app/nl.philips.hue.

Issue 1 can be fixed by getting a new girlfriend.

**Comment by mverleun** [comment]
Issue 1 would be a show stopper for me as well. I understand the pro's and con's off polling but if it is the only way... Please consider it in the name of WAF. ;-)

**Comment by freemann** [comment]
no WAF, no Homey :smiling_imp:

**Comment by AndreSomers** [comment]
I agree with the assessment of mverleun and freeman: this needs to work. Polling is not nice, but if that's the only way to get this to work, then so be it until Philips adds some API to get notifications of changes. I think even Philips themselves are polling: you can see the Philips controller apps lagging when you change the lights by some other means as well.

**Comment by Fire69** [comment]
Actually, I think lots of apps use polling.
If you look at this screenshot of a php-script I'm using to get info from the bridge:
http://static.tweakers.net/ext/f/gXgrPhIDWxBw5nK6onu1a7dt/full.png

4 apps have a 'Last use date' that is constantly updated when I do a refresh of the page, even when the apps aren't use at the moment, so those are polling the bridge all the time.

**Comment by freemann** [comment]
Any ideas how to solve this?

**Comment by WeeJeWel** [comment]
Added polling in nl.philips.hue@0.9.10
