### ISSUE TITLE
"Add zone" get replaces by "Delete zone", but never turns back

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#100]
When dragging a zone it replaces the add zone button. Releasing it won't turn back to "add zone".
Needs a refresh to get the add button back.

**Comment by TedTolboom** [comment]
I also noticed the same behavior. Refreshing the page brought back the add zone.
Second remark, it is not clear how to delete a zone (how to select it)

**Comment by AndreSomers** [comment]
I found it unclear how to ensure the grouping. Spend some time fiddling adding a Second Floor and the rooms on there (it is not an attic in my house).

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
