### ISSUE TITLE
Flows cannot be selected on touchscreens

### ISSUE THREAD

**Issue by scanno** [athombv/homey#1000]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**
Select / create a flow from the flow menu. 

_Please include detailed steps how we can reproduce the issue_

Go to the flow menu in an Android tablet or phone and try to select an existing flow or folder. 

**What was the result?**

Nothing, the menu does not react on touching one of the items. 

**What did you expect as result?**

I expected as result that I would be able to select a flow or folder or create a new flow. 

**Any other remarks**

This used to work fine on firmwares below 0.10.x

**Comment by bvdbos** [comment]
Creating a new flow works on my phone. But with really bad real estate, the desktop-version of Homey isn't really made for phones... On the mobile version of the site you can't do anything with flows...

**Comment by scanno** [comment]
@bvdbos  well i am using a 10.1 inch tablet and it was working prettynwell in desktop mode. i even could create flows dragging cards. And since i am 99% of the time using my tablet, this is bugging me big time.

**Comment by Inversion-NL** [comment]
Yes, have been using that also on both my phone and tablet but since the flow drag re-write I'm unable to select current flows.

**Comment by WeeJeWel** [comment]
While tablets aren't officially supported, I'll take a look at this soon :-)

**Comment by WeeJeWel** [comment]
Should work as of v1.3.0

**Comment by ICT22** [comment]
I've just tried this as part of 1.3 RC7 and I notice no difference on my iPad Pro using Chrome. I can't select any of the flows.

**Comment by DeefK** [comment]
It does open a folder but does not open the flow.

**Comment by bvdbos** [comment]
On my laptop with chrome I need to doubleclick the flow...

**Comment by WeeJeWel** [comment]
On mobile, try touch and hold. It works on my Android phone in Chrome.

**Comment by scanno** [comment]
It works on my android phone

Try longpressing a flow. It opens a submenu and the is an option "open flow"

**Comment by scanno** [comment]
@WeeJeWel LOL... Same moment

**Comment by ICT22** [comment]
Touch and hold works, however it creates two events as also the browsers own popup menu appears.
![img_0004](https://cloud.githubusercontent.com/assets/3747226/26094415/d2eb3f32-3a11-11e7-8c67-f070bc4f31b0.PNG)
