### ISSUE TITLE
[App Store] Use APPSTORE.md if available

### ISSUE THREAD

**Issue by casperboone** [athombv/homey#1002]
Not really the correct repo I guess, but there is not really a better alternative.

---

I would like to put some information for developers in the README of my app, just some general instructions etc. Also, if others check out my GitHub profile I would like to have some general info on Homey and the workings of the app in the README. Both would not make sense to put in the App Store description. (and there are probably more examples)

Maybe it's a good idea to check if an `APPSTORE.md` file is present, and if it is, use that file instead of the README for the app description.

**Comment by WeeJeWel** [comment]
This is a very good suggestion. We'll implement it, thank you very much!

**Comment by joachimroeleveld** [comment]
Staged for the new release of the App store!

**Comment by casperboone** [comment]
Cool, thanks guys 😄 .
