### ISSUE TITLE
[Enhancement] force trigger flow

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1003]
I know there's many ways to force trigger a flow but apparently it's still not clear for people. Therefore I'd like to suggest a new action card which forces a flow to run as if it was triggered... #539 was about that too and probably a few more...

**Comment by bvdbos** [comment]
This makes it easier for people to understand. Another advantage is that it's easier to make sequential actions...

**Comment by markaswift** [comment]
I'm not sure an action card is the way, it's not intuitive. 

I'd suggest an option with minimal UI impact, such as an option located near the test flow button.

**Comment by caseda** [comment]
how is triggering another flow with an action card not intuitive?
a lot of people already try to do that with the "activate/deactivate flow" action cards
just add one more card to this one.. "Run Flow" action card

**Comment by markaswift** [comment]
Perhaps I didn't understand the translation.

So we're talking about a flow trigger action card? (ignoring the flow trigger).

If so then this makes sense, it's been asked before previously hasn't it?

**Comment by caseda** [comment]
that is exactly what we is talking about, and yeah, has been asked/talked about many times already :p

**Comment by bvdbos** [comment]
Then there's the problem: What if the card (i.e. date) from the trigger is used in the action? That won't work then... But I think the flow should then fail silently (or perhaps flashing red ring).

**Comment by WeeJeWel** [comment]
Added in 0.10.8!

![screen shot 2016-11-01 at 14 27 35](https://cloud.githubusercontent.com/assets/319873/19891793/0168afc6-a042-11e6-95e2-1025c8ac5ed2.png)
![screen shot 2016-11-01 at 14 27 48](https://cloud.githubusercontent.com/assets/319873/19891794/02bb7836-a042-11e6-922f-f257f90ac098.png)
![screen shot 2016-11-01 at 14 28 08](https://cloud.githubusercontent.com/assets/319873/19891796/03c7c34c-a042-11e6-92ff-c8f56b9a5243.png)

**Comment by WeeJeWel** [comment]
I'm closing this issue as it's fixed :)
