### ISSUE TITLE
When try to manual update I get a popup:  Invalid_sn

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1004]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve

Auto update is disabled and I try to manual update by clicking on Zoeken naar updates.
**What was the result?**
The circle in the update button keeps spinning, when there normal was a message if there was no update.
...

Not this popup. Now I don't know if there is really a problem. 

...

With help of Jeroen I had to debug my Home because of bug #905 

...

**Comment by bvdbos** [comment]
yep, for me too and I didn't (don't) suffer from 905...

**Comment by nattlip** [comment]
me too , but are we able to update then in due time ?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by nattlip** [comment]
@jeroenvollenbrock i checked it 2 hours ago

**Comment by jeroenvollenbrock** [comment]
@nattlip I know, but i asked for a confirmation 2 minutes ago :)

**Comment by nattlip** [comment]
@jeroenvollenbrock indeed it is gone, i thought it was a homey problem.

**Comment by jeroenvollenbrock** [comment]
It was a server problem and has now been resolved.

**Comment by Inversion-NL** [comment]
Confirmed the message is gone!
