### ISSUE TITLE
Update error 

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#1005]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**
Check for updates 

*Please include detailed steps how we can reproduce the issue*
press check for update 

**What was the result?**
see pic 
...

**What did you expect as result?**

...

**Any other remarks**
Log 9395DF0AAB 
...
![sn](https://cloud.githubusercontent.com/assets/17300121/19468155/29b6739c-9515-11e6-8b5a-6ebfe28fe165.PNG)

**Comment by caseda** [comment]
please at least try to read a few bug reports before you post your own one, the one before yours does already mention this bug, (it's even in the titel)

duplicate #1004

**Comment by djeskoswe** [comment]
need coffee !   :)
