### ISSUE TITLE
[App store] [Bug] Clicking the categorie button on the app page filters wrong

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#1006]
While on the page of an app you able to click the category the app is in (i.e. Music for Squeezebox app).
While clicking on this link does show the correct categorie title at the top, it looks like all apps are shown.

**Steps to reproduce
- Go to https://apps.athom.com
- Click on a app (doesn't matter which one)
- Click on one of the black buttons for which category the app is in
- Store shows all available apps instead of the right category

**Any remarks
Clicking the category while on the start page of the store (https://apps.athom.com) works like expected

**Comment by joachimroeleveld** [comment]
You're right. A fix has just been deployed.

**Comment by Inversion-NL** [comment]
Confirmed!
Quick fix!
