### ISSUE TITLE
[App store] [Enhancement] The app description 'show more' text hard to read

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#1007]
While on the page of an app only a portion of the app's description is shown.
There is a 'show more' button but it's kind of hard to read.

**Image
![image](https://cloud.githubusercontent.com/assets/15921016/19478075/577b81ce-9541-11e6-8224-548de3c69989.png)

**Comment by joachimroeleveld** [comment]
I adjusted the gradient. It should be easier to read now. Thanks!

**Comment by Inversion-NL** [comment]
Much better now!
Although I think the text, not collapsed, is really short for a description...

![image](https://cloud.githubusercontent.com/assets/15921016/19484232/395c2624-9557-11e6-9f79-d3a3664e099c.png)
