### ISSUE TITLE
[App store] [Bug] no contributors seen on app page

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1008]
**What is your Homey version (Settings → System)?**

does not apply

app store the new one

**What did you try to achieve?**

see the contributors of app on app page

open appstore, choose an app and look at the lower right corner at the contributot part

**What was the result?**

no contributors
...

**What did you expect as result?**

contributors

...

**Any other remarks**

looks like the devices div makes the developers div smaller

hln headlines doesnt have devices , then the contributor part is shown well , but if there are devices the contributor part is smaller.

it ssems to do with if there is email address present which is known by athom

**Comment by joachimroeleveld** [comment]
This is now fixed, thanks.
