### ISSUE TITLE
App crashes without stack trace info

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1009]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**

Keep my Magister app running over a longer period (days/weeks)

_Please include detailed steps how we can reproduce the issue_

**What was the result?**

I get an occasional app crash every few days. The stack trace does not show any information.

![2016-10-18](https://cloud.githubusercontent.com/assets/19174120/19490059/e63f4f86-956d-11e6-86e6-fa88eb49f17b.png)

**What did you expect as result?**

When the app crashes, that I get a stack trace so I can fix the problem in the app

**Any other remarks**

I also do not get the usual email that my Magister app crashes.

I sent a crash log to Athom with ID: 62FBEAD8AD

**Comment by gruijter** [comment]
Just found out that also Weather Underground app (v0.2.5) had crashed, also with stack trace: false

**Comment by gruijter** [comment]
Now also my Philips Hue app (v1.0.5)...

**Comment by jeroenvollenbrock** [comment]
Can you send me a screenshot of your stuff-for-geeks section as well as a log?

**Comment by gruijter** [comment]
Wow, still working this late :) 👍 I sent you a PM via slack

**Comment by jeroenvollenbrock** [comment]
Does this issue still occur on 0.10.7?

**Comment by gruijter** [comment]
I didn't see it happening since the 0.10.7 update :)
