### ISSUE TITLE
RFXcom not working anymore

### ISSUE THREAD

**Issue by hschenkelaars** [athombv/homey#101]
Hi,

Yesterday I unpacked my Homey and the setup was easy. Hue worked within a few minutes. Added GreenWave PowerNodes and they worked. Alsa added my RFXcom (KAKU) devices and the worked but now they stopped working. I rebooted Homey but without any result. My KAKU devices won’t work anymore. I also am not able to add new KAKU devices. And I know these devices work because they are also used within Domoticz.

Is there a way to figure out if the RFXcom transceiver is working ? Maybe through SSH ?

**Comment by bvdbos** [comment]
I had to disconnect from power to get kaku back to work...

**Comment by hschenkelaars** [comment]
Hi bvdbos, that did the trick. Should have thought of that..  
Many Thx.

Is the RFXcom working stable when you powered off/on ?  
I will see if it keeps working at my side.

**Comment by hschenkelaars** [comment]
Just rebooted Homey for a voice change and guess what.. RFXcom Not working anymore....
A power off / on solved the issue.

This is a bug. After a reboot RFXcom should work normally.

**Comment by nattlip** [comment]
your rfxcom not working anymore ?  you mean the rfxcom transmitter ?

**Comment by hschenkelaars** [comment]
Your correct my RFXcom transmitter, from homey, not working anymore. Hope they fix this bug.
When I need to reboot I must proceed with a powercycle for homey to startup completely and for the RFXcom transmitter to function. I know now so I can live with it, for now.....

**Comment by Dennishacq** [comment]
We are working on a way to solve this problem. We are hoping to have it fixed in the next update.

**Comment by bvdbos** [comment]
"We are hoping to have it fixed in the next update" means this bug should stay open till the fix is confirmed?

**Comment by freemann** [comment]
+2 for bvdbos.

Its very strange to close issues when the are not really fixed.

**Comment by bvdbos** [comment]
@Dennishacq : it's unclear now whether this will is fixed in the next upgrade or not? Bug is closed so I guess it's fixed?
