### ISSUE TITLE
[App store] New app store does not scale well on an iPad

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#1010]
The new App store looks slick but does not scale well on an iPad. 

![img_0398](https://cloud.githubusercontent.com/assets/16610696/19491408/209194b4-9573-11e6-805e-e543980116e1.PNG)

I know Athom favors Chrome, but lets not forget a lot of users want to be able to make their own choice.

**Comment by KroontjesPen** [comment]
May I also point to no horizontal scrolling on a PC.

**Comment by joachimroeleveld** [comment]
The App Store is indeed not yet built responsively. This will happen in the future, but for the time being it has been postponed. I will close this issue for now, as it is on the planning, but I can't say when we have time for it.

**Comment by joachimroeleveld** [comment]
Wanted to let you know that the app store is responsive now!
