### ISSUE TITLE
[App Store] Faulty handling of partial tiles in appstore

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#1011]
At certain screen resolutions, the right-most tiles are shown partially. If you click the right-arrow, you expect the new set of tiles to start with the partial tile but the next (previously) invisible tile is shown instead.

Start:
![appstore-issue-1](https://cloud.githubusercontent.com/assets/570302/19493296/5b3df218-957a-11e6-98a4-38ea2a8b5f33.png)

After click:
![appstore-issue-2](https://cloud.githubusercontent.com/assets/570302/19493301/615a467e-957a-11e6-8f36-30f02bffe257.png)

I expected to see the Milight app tile completely in the second image.

Remark:
Sidescrolling in this way is not very user-friendly on PC.

**Comment by joachimroeleveld** [comment]
Sharply noticed! This is now fixed.
