### ISSUE TITLE
[App Store] Not able to publish new update

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1012]
**What is your Homey version (Settings → System)?**
0.10.5

**What did you try to achieve?**
Publish update of app to the (new) app store after it has been accepted for publish-ment

*Please include detailed steps how we can reproduce the issue*
Press the [Publish] button when the app has been accepted for publish-ment

**What was the result?**
Got a popup "something went wrong" and then the update was completely gone, no option for re-trying.

**What did you expect as result?**
The update to be published to the appstore

**Any other remarks**

...

**Comment by irritanterik** [comment]
On approved new app there is no button to publish.

**Comment by caseda** [comment]
there was when i did it, maybe they removed it because of the bug :)

**Comment by irritanterik** [comment]
Hmm.. maybe there is too much delay between backend and frontend. A few minutes after I received the e-mail about approval the status in app store developer panel changed (with me doing a lot of refreshing)

**Comment by caseda** [comment]
Has been fixed already :D must have been a small error in the coding

**Comment by irritanterik** [comment]
Can you reopen @caseda ? I just updated an app and clicked 'submit'. After that the screen refreshed and buttons dissapeared:

![image](https://cloud.githubusercontent.com/assets/15232724/19539016/4c0870d8-9657-11e6-812b-ed633f316fa1.png)

**Comment by caseda** [comment]
hmm, nice and inconsistent ❤️

**Comment by joachimroeleveld** [comment]
Can you confirm whether this is still happening? A bug fix was just deployed which may be related to this.

**Comment by caseda** [comment]
For me it was already fixed, was able to updated an app a few times already.
@irritanterik what's your status?

**Comment by joachimroeleveld** [comment]
I'm closing this issue for now; feel free to reopen if it persists.

**Comment by irritanterik** [comment]
Works great now, thanks.
