### ISSUE TITLE
[App store] Readme not shown on unpublished new app

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1015]
**What did you try to achieve?**

Read readme before publish an approved new app.

**What was the result?**
Undefined:

![image](https://cloud.githubusercontent.com/assets/15232724/19515909/c8be1ba4-95f9-11e6-8628-6fe7c5aff82e.png)

**What did you expect as result?**
Readme.md content as available on github.
...

**Comment by joachimroeleveld** [comment]
This is now fixed. With the new version of the App store, you can use APPSTORE.md separately from README.md if you like. You can then use README.md for developers and other info you don't want to show a regular App store visitor.
