### ISSUE TITLE
[App store] No refresh/result visable after sending comment during app review

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1016]
**What did you try to achieve?**
Send a funny reply after a funny comment from Athom and click 'Send' button.

**What was the result?**
Nothing. I clicked again. Then came to senses and refreshed the page, now my message was showed twice. 

...

**What did you expect as result?**
Refresh/confirm that message was send
...

**Comment by joachimroeleveld** [comment]
Can you verify whether this issue persists?

**Comment by irritanterik** [comment]
Solved!
