### ISSUE TITLE
[App store] Request for new category: mobility / localization + news

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1017]
I'm now using app store category 'tools' for GPS trace, Vodafone GPS and Tesla App. 

I think there should be a 'mobility/localisation' category or something, for apps like better presence, 9292ov, GPS tracking, geofencing etc.

Can this be added to the app store?

**Comment by irritanterik** [comment]
And while you're at it:
Also for 'news' perhaps? So HLN, NOS, Huffpo etc can go together in a category.

**Comment by DiedB** [comment]
Also 'energy'.

YouLess, Solar Panels, Plugwise Smile, and more.

**Comment by Fiek1** [comment]
Can you also the category 'Recently updated'?

**Comment by WeeJeWel** [comment]
@IvoDerksen Please create two icons for:
- Energy
- Localization

@joachimroeleveld Please add these two categories as allowed categories in the App Store

**Comment by joachimroeleveld** [comment]
The app store is prepared for these categories. It's now waiting for the icons.

**Comment by IvoDerksen** [comment]
Energy and location icons!
[energy_location.zip](https://github.com/athombv/homey/files/583793/energy_location.zip)

**Comment by joachimroeleveld** [comment]
Hi guys, I added the categories 'Energy' and 'Location', but I cannot yet show them at the front page. We should have at least a few apps per category. Therefore, please add the categories to your apps.

**Comment by irritanterik** [comment]
@joachimroeleveld Thanks! I will submit my apps as soon as the cli allows these new categories on the `--validate-app-store` command.

**Comment by WeeJeWel** [comment]
It should already, simply install athom-cli again :)

**Comment by irritanterik** [comment]
3 app updates submitted now for localization category.

**Comment by joachimroeleveld** [comment]
@DiedB, could you update your app to include the Energy category too?

**Comment by DiedB** [comment]
@joachimroeleveld Already did last week.

**Comment by irritanterik** [comment]
localization apps published

**Comment by irritanterik** [comment]
Icon is missing on app details page for new category:
![image](https://cloud.githubusercontent.com/assets/15232724/20544917/a8ee1346-b10c-11e6-9d03-71ac2e610fd1.png)

**Comment by joachimroeleveld** [comment]
That is because the new category has been named "location", which is less ambiguous and also a broader definition. Apologies for not making this more explicit earlier this conversation.

**Comment by irritanterik** [comment]
So [homey-lib](https://github.com/athombv/node-homey-lib/commit/bea4f023d6c62dcd38c4d78ca1ee00ef053cc67a) has to changed first now? And after that I must resubmit my apps?

**Comment by joachimroeleveld** [comment]
No, homey-lib already has the category "location". Updating your app should suffice.

**Comment by irritanterik** [comment]
@joachimroeleveld check this: https://github.com/athombv/node-homey-lib/blob/master/lib/app/index.js#L12

**Comment by joachimroeleveld** [comment]
Ah wow, quite some miscommunication occurred here. You're completely right. You should see the icon now.

**Comment by IvoDerksen** [comment]
Localization is not shown correctly (missing point).
Could you update the app icon with this one:
[location_icon.svg.zip](https://github.com/athombv/homey/files/614860/location_icon.svg.zip)

**Comment by irritanterik** [comment]
@joachimroeleveld Any update? The new categories are not shown on the front page yet.

**Comment by joachimroeleveld** [comment]
I just added the categories, but they are almost empty. Please update your apps to have the Energy or Localization categories as *first* in the array. Only then they will be shown in the category. (This to prevent duplicate apps across categories)

**Comment by irritanterik** [comment]
Implemented:
![image](https://cloud.githubusercontent.com/assets/15232724/21691464/e8ada2c4-d378-11e6-92ea-b44141e2264b.png)

👍
