### ISSUE TITLE
[App store] Double scrolling on longer app readme

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1018]
**What did you try to achieve?**
Read the readme of an app in the app store

**What was the result?**
First have to click 'show more'. That's a pitty because readme is the most usefull info on the app page IMHO. 
After clicking 'show more' an extra vertical scrollbar appears and leads to double scrolling the readme texts.

Screenshot at full screen on my humble notebook:
![image](https://cloud.githubusercontent.com/assets/15232724/19525395/1acac2d6-9621-11e6-900d-33c285373852.png)

**Comment by joachimroeleveld** [comment]
This is unfortunately a design choice. In our view, the description section is something that users read to get to know more about the app's details. Therefore, we think, the user will click on 'Show more' if he/she needs that information. We limit the (scroll)length of the description so users are able to scroll to the comments without having to scroll past a (potentially) enormous description.
