### ISSUE TITLE
Wrong answer weather information request when using Yahoo app

### ISSUE THREAD

**Issue by Tvandongen** [athombv/homey#1019]
**What is your Homey version (Settings → System)?**

0.10.5 + 0.10.7

**What did you try to achieve?**
Request Weather information

_Please include detailed steps how we can reproduce the issue_
Ask home the weather

**What was the result?**
wait a moment please (few seonds later) something went wrong try again please.

**What did you expect as result?**
The weather information or nothing, because I do not have any weather app installed

**Any other remarks**
Homey did receive the correct question (Have also a parrot flow and that was repeating the question exact)

**Comment by WeeJeWel** [comment]
Maybe your internet was temporarily disconnected. What happens after installing a weather app?

**Comment by Tvandongen** [comment]
Tested it with version 0.10.7:
- Installed yahoo weather: Same result (homey says (in dutch): wait a moment please (few seonds later) something went wrong try again please)
- Removed yahoo weather: No response (except for parrot flow, so that is also the expected response)
- Installed weather underground with private key: Weather info is spoken almost correctly (Only wrong word is the temperature: in manager/output it was 11C --> Spoken as "Zee" (Dutch language)
Conclusion: first test looks like there was an old version of yahoo version some whcih did not cleaned up completly. As I cannot reprorudce the issue without weather app, this part of the problem looks solved. 
Only issue that remain is that yahoo weather got the wrong response.

**Comment by Tweake** [comment]
It seems like the Yahoo Weather App issue was most likely caused by server issues at Yahoo, as we have been seeing issues with their service over the past few days as well. We have updated the Yahoo Weather App to version 1.0.6 to give better feedback about what is causing the problem when weather information cannot be given. The update also includes several new stability improvements. By now will most likely be on your Homey already if you have automatic updates enabled.

As far as the Weather Underground App; I agree with you. However, this is not our app but an app developed by someone from our community so I would advise you to add your suggestion to the Github page of that app (a link to that page can be found in the App Store)

Thanks for pointing out the issue!

**Comment by Tvandongen** [comment]
@Tweake 
The error message is now giving a better feedback, but not enough information to find what is causing the error. As you can see in the attachedd image the error is now that both the google maps service and the yahoo service are not responding, but it is not mentioning which address  / ports / api they are trying to reach so I cannot check if it is a server problem (unlikely that both google maps and yahoo are both down), a problem of the homey app or an problem inside my home network.
Could you give more information about this ?
![image](https://cloud.githubusercontent.com/assets/22547301/20403059/901050c0-acff-11e6-976e-63eb3d94f4fb.png)

**Comment by Dijker** [comment]
I did not have this app installed and have no connectivity problems afaik, 
So I just downloaded the App from the store, typed the second question in speech input : "What is the weather for tomorrow?" an voila:
![image](https://cloud.githubusercontent.com/assets/12412734/20404010/5e9523dc-ad03-11e6-92c9-8156cbc31804.png)

Normal Consumer internet (Ziggo, NAT, Google Public DNS)

**Comment by RobinBol** [comment]
It is really strange, I just did some random tests on some Homeys in the wild, and none of them experience these issues. It is almost as if there is something blocking these API calls. If someone could run the app from command line and give me the logging I might be able to spot something.

**Comment by Dijker** [comment]
Robin, 
lets discuss here ;-) 
is it possible to run this app installed from the appstore? We don't have access to the git repository afaik.

athom project --run com.yahoo.weather didn't work as I don't have an APP / folder local with that name.

**Comment by mruiter** [comment]
@Dijker 

Install git. go to a dir where you want is and do 

git clone https://github.com/athombv/com.yahoo.weather.git

Go in the com.yahoo.weather.git and do athom project --run

**Comment by Dijker** [comment]
ok, thanks. 
same result:

D:\Homey\Dev\com.yahoo.weather>athom project --run com.yahoo.weather
? Select active Homey: (Use arrow keys)
? Select active Homey: BerliozHomey @ 10.1.13.107:80
1/4 - Archiving...
2/4 - Uploading to BerliozHomey @ 10.1.13.107:80...
3/4 - Running `com.yahoo.weather`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
Yahoo Weather: start listening for speech events...
Yahoo Weather: found location data, lat 52.04144805679122 and lng 5.093552470207214
Yahoo Weather: start listening for weather changes...
Yahoo Weather: incoming speech event
{ transcript: 'what is the weather for tomorrow ',
  session: 'homey',
  triggers: [ { id: 'weather', position: 12, text: 'weather' } ],
  devices: [],
  time: [ { transcript: 'tomorrow', index: 24, time: [Object] } ],
  agent: 'homey:app:com.yahoo.weather',
  say: [Function: bound ],
  ask: [Function: bound ],
  confirm: [Function: bound ] }
[ { transcript: 'tomorrow',
    index: 24,
    time:
     { second: false,
       minute: false,
       hour: false,
       fuzzyhour: true,
       day: 19,
       month: 10,
       year: 2016 } } ]
Yahoo Weather: parsing speech object done, fetching weather data information...
google

**Comment by mruiter** [comment]
Looks good, whats wrong

**Comment by Dijker** [comment]
No errors in the console, 
but that I didn't get any weather information.... ;-)

**Comment by mruiter** [comment]
Ahh, did you set location manualy or is it on auto. If in settings on auto try to set it to manual en put the dot on youre house

**Comment by RobinBol** [comment]
I think that for some users the google maps api isn't working, thats where things start te break. No clue why at the moment to be honest...

**Comment by Inversion-NL** [comment]
His latitude and longitude states he's in Nieuwegein so that should work @mruiter

**Comment by Dijker** [comment]
It was manual already and LAT/LON are correct.

**Comment by RobinBol** [comment]
So running from command line is not going to work. Not sure how to debug this with you guys.

**Comment by Dijker** [comment]
@RobinBol  Dijker at Slack.... Wil je toegang?

**Comment by mruiter** [comment]
Whaha Robin has got to give Aeotec and Fibaro pull some love first ;)

**Comment by RobinBol** [comment]
Just released com.yahoo.weather v1.0.8, with a fix confirmed by @Dijker

**Comment by Dijker** [comment]
confirmed! Appstore version also Fixed!
