### ISSUE TITLE
Using 2 (the same) capabilities gives error or not right capability

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1020]
**What is your Homey version (Settings → System)?**
0.10.5

**What did you try to achieve?**
Include a device that uses 2 of the same capabilities (in this example alarm_generic)
if you leave be and just say

```
"capabilities": [
    "alarm_generic.1",
    "alarm_generic.2"
],
```

will result in an error:
"Uncaught TypeError: Cannot read property 'toString' of undefined"

If i then create my own mobile card to put them in will result in 2 "icons" of the device (3 counting the normal icon as well), not the "generic alarm" capability icons, and won't respond to boolean results.

If i use 2 different alarm capabilities they do respond to boolean results.

**What did you expect as result?**
Be able to use 2 of the same capabilities in 1 mobile card
...

**Any other remarks**
In both cases the device also does not show up in the flows section, must be related that the capability isn't applied correctly
...

**Comment by markaswift** [comment]
I also experienced this when trying to add my in wall relay.

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by caseda** [comment]
confirmed fix, just the path of the icons left but should be fixed in next update as well.

closing issue
