### ISSUE TITLE
[Forum] Can't remove picture link.

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#1022]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Removing the link form a deleted picture

**Please include detailed steps how we can reproduce the issue**
Post a picture in the form and delete the picture

**What was the result?**
The link stays

**What did you expect as result?**
No picture link in the post.

**Any other remarks**
[https://forum.athom.com/discussion/comment/35233/#Comment_35233](url)
...

**Comment by Dijker** [comment]
imho thats by design, someone quoted your text and picture, that would break the reply. 
I have removed a picture before without problem as far as i know. ;-)

**Comment by bvdbos** [comment]
I've deleted picture-links before... You can just edit the markdown-code if you want to be sure it's really gone...

**Comment by KroontjesPen** [comment]
When I delete the lines I can't save the post. 
There is nothing else to see.

**Comment by WeeJeWel** [comment]
It should be possible, otherwise try to edit the HTML (Press the <> symbol)

**Comment by KroontjesPen** [comment]
In HTML:

> &nbsp; Sorry, wrong interpretation of a post. <br><br>Can't remove picture link below. <br>


There is no more to see.
