### ISSUE TITLE
[App store] 404 Redirect when logging in

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#1024]
404 Redirect when logging in from an url other then homepage?

Reproduce:
1. Log out
2. Go to https://apps.athom.com/developer/submit-app
   Get "Sorry, but we can't let you in!"
3. Click Sign in
4. Click on your account
    Get redirected to https://apps.athom.com/auth/~2F~2Fapps.athom.com~2Fdeveloper~2Fsubmit-app
5. Enjoy the beautiful 404 page written in stylish JSON :P

**Comment by KroontjesPen** [comment]
Status app store is maintenance. 
Here I have no problem what so ever. 
[https://apps.athom.com/](url)

**Comment by Joolee** [comment]
Just reproduced on another PC. With both Firefox and Chrome. Same result.

**Comment by bvdbos** [comment]
confirmed...

**Comment by joachimroeleveld** [comment]
This is now fixed. Thanks!
