### ISSUE TITLE
BUG: Some important sensor types (e.g. Velocity, Dew point) for SENSOR_MULTILEVEL not supported 

### ISSUE THREAD

**Issue by octopussy1** [athombv/homey#1025]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

I have a z-wave SENSOR_MULTILEVEL weather device that returns beside the Temperature, Luminance, Humidity also Velocity, Barometric, Dew point.
I'm using the ZwaveDriver in which I have defined the capabilities. For "Temperature, Luminance, Humidity" everything works OK but as soon as I add the "Velocity" or Barometric or Dew point sensor types I will get an "manager.vdevice.drivers.zwavebasic.pair.invalid_capability" error when adding the device.

Here is the code I'm using to add the velocity:

		'measure_velocity': {
			'command_class': 'COMMAND_CLASS_SENSOR_MULTILEVEL',
			'command_get_parser': () => {
				return {
					'Sensor Type': 'Velocity (version 2) ',
					'Properties1': {
						'Scale': 0
					}
				};
			},
			'command_report': 'SENSOR_MULTILEVEL_REPORT',
			'command_report_parser': report => {
				if (report['Sensor Type'] !== 'Velocity (version 2) ') return null;
				
				return report['Sensor Value (Parsed)'];
			}
		},

**What was the result?**

When adding the device after the device is detected I get "manager.vdevice.drivers.zwavebasic.pair.invalid_capability" error.

**What did you expect as result?**

Device should be added without any problems.

**Any other remarks**

Am I'm doing something work? It seem like the following sensor level types are not yet supported:
- "Velocity (version 2) "
- "Barometric pressure (version 2) "
- "Dew point (version 2) "

Supporting Velocity and dew point is very important as this is used to control allow to control to have shades been opened or closed.

BTW, it seems that is an issue with the 'Sensor Type' list you are using internally. WeeJeWel send me on yesterday the list of Sensor Type strings (https://github.com/athombv/node-homey-zwavedriver/issues/9). And I noticed that some of them have a space at the end. Not sure if this is intentional. Let me know if I should file another issue ticket for that one.
I've also tried to set the sensor type to "Velocity (version 2)" without a space. But that made no difference.

**Comment by caseda** [comment]
They are supported, you just showed us with the list emile gave you ;)
there are just no [default capabilities](https://developers.athom.com/library/drivers/capabilities/) for these sensor types, you either need to make them yourself, or ask if athom want to implement them.

the spaces at the end do not belong there indeed, and when setting the "get_parser" you will need to add the space at the end for it to give you data back.

so again, no real bug (just the unnecessary space), and a lack of reading any documentation

try reading the [developers pages](https://developers.athom.com) some time... can shed a lot of light ;)

**Comment by octopussy1** [comment]
I've figured this out later one but was not able to comment on this issue because github was down yesterday afternoon.
After reading the doc a second time I was able to figure out how to do those things. It would be good if the documentation had some more details and samples code and some kind of workflow chart on how Homey communicates with devices in the eco system.
