### ISSUE TITLE
saying or writing in speech input "all sockets on" gives all sockets off command

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1026]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

"all sockets off" or "socket three off" with speech input page

_Please include detailed steps how we can reproduce the issue_

**What was the result?**
all sockets off
...

**What did you expect as result?**

all sockets on or socket three on
...

**Any other remarks**

...

**Comment by Tweake** [comment]
The issue report is a bit confusing, but based on the title I'm assuming you are trying to turn all sockets on by sending the speech input string "all sockets on" ( using <network-address>/manager/speech-input). 

To try and reproduce this it have added 3 sockets to my Homey. I have turned 1 on and left the others switched off. I then gave Homey the command "all sockets on". The result was that the switched off sockets were switched on by Homey. The socket which was already switched on remained switched on.

So, in this case I was not able to reproduce the issue and result suggests everything is working as expected. If I misunderstood the issue you are experiencing, please provide a more detailed issue report. In addition, could you please provide a screenshot of your /manager/speech-input screen with the commands, a summary list of your all sockets you are using and a screenshot of your devices screen where these sockets can be seen? Many thanks

**Comment by nattlip** [comment]
your assumption is damn right. it doesnt matter speaking to homey or using speech imput string .

i cant reproduce it soon , i can only in a few weeks when i are at the homey this happened which is at a completely different geo location.  i am using 2 X10  app onoff sockets  not publised yet with sockets and plugwise sourse app app with 24 sockets(circles) . it was a disaster, wifi turning off homey turning off tv , amplifier setopbox , refrigurator cameras heating etc etc .  i will first think of a suitble testing environment. i didnt expect it to happen off course.  here at home with another homey i have 38 sockets . turning the sockets on off with the on off button works correct.

**Comment by nattlip** [comment]
i think i messsed up on and off i my apps
