### ISSUE TITLE
the [null] error in insights is back in 0.10.7

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1027]
**What is your Homey version (Settings → System)?**

0.10.7

see a nice curved flow

view a flow

**What was the result?**

the so called [null] error reappears after having been gone a lot of firmware's. it seems only at the start of the flow.

**What did you expect as result?**

![null error](https://cloud.githubusercontent.com/assets/7040452/19592345/92f94e98-977b-11e6-96c9-b4d3912aba24.PNG)

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Can you send me your raw log please?

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by WeeJeWel** [comment]
I'm closing this issue as it should be fixed. If it persists, please re-open.
