### ISSUE TITLE
BUG: SENSOR_MULTILEVEL sense Luminance labels in "lx" even so it is specified to be in "%"

### ISSUE THREAD

**Issue by octopussy1** [athombv/homey#1029]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

I have a weather device that returns the Luminance value in "%" and not in "lx". Here is the z-wave driver code that specifies the Luminance:

		'measure_luminance': {
			'command_class': 'COMMAND_CLASS_SENSOR_MULTILEVEL',
			'command_get_parser': () => {
				return {
					'Sensor Type': 'Luminance (version 1)',
					'Properties1': {
						'Scale': 0
					}
				};
			},
			'command_report': 'SENSOR_MULTILEVEL_REPORT',
			'command_report_parser': report => {
				if (report['Sensor Type'] !== 'Luminance (version 1)') return null;
				
				return report['Sensor Value (Parsed)'];
			}
		},

**What was the result?**

In the device view the Luminance icon has "lx" instead of "%".

**What did you expect as result?**

In the device view the Luminance icon should display "%". if "Scale" is defined as 0.

**Any other remarks**

Screenshot attached
![screenshot](https://cloud.githubusercontent.com/assets/8056852/19597761/d428b3ca-9796-11e6-84f9-af4312eca8b8.png)

**Comment by caseda** [comment]
Change the scale to 1,then it will give back lux instead of percentage

**Comment by octopussy1** [comment]
The device delivers the Luminance in % but Homey displays them in "lx" instead of "%". This is the bug. AFAIK scale:0 defines the result from the device is in %.

**Comment by caseda** [comment]
The device can deliver 2 luminance values, percentage (scale 0) and lux (scale 1), you don't want to work with percentage in luminance, that's why you need to use scale 1

**Comment by octopussy1** [comment]
The device I'm trying add support for in Homey does deliver the luminance only in %. Unfortunately I have no control over the type of scale that is returned. It was up to the HW device vendor to pick on the type of value.
The reason for have the % values is that when you want to decide when the day changes from night to day or from day to night the lx value is not useful as the lx value will be different depending on the season of the year. This is need to control shades and shutters.

**Comment by caseda** [comment]
You do have control over your value that gets reported back :)
and you can choose which scale:
```
        'command_get_parser': () => {
            return {
                'Sensor Type': 'Luminance (version 1)',
                'Properties1': {
                    'Scale': 0 <===========================================
                }
            };
        },
```
look it's right there in the Properties1 object...
and its right in the official documentation that the CC "Multi Level" sensor you can choose.

it's _**not** up to the HW manufacturer_, it's up to the **Z-Wave Alliance** if it should be implemented or not

Here is the little snippet of the documentation:
```
Luminance (v1) 0x03 Byte 1 Bit 2
Percentage value 0x00
Lux 0x01
Reserved 0x02-0x03
```
[Source](http://z-wave.sigmadesigns.com/wp-content/uploads/2016/08/SDS12657-12-Z-Wave-Command-Class-Specification-A-M.pdf) Page 508, chapter 4.91.87, Table 113

Trust me, i do know what i am talking about ;)

**Comment by octopussy1** [comment]
Hi,

Sorry, if I came across questioning your answer;-)

I agree with you that lx is a value that does usually makes more sense. I did talk with the HW manufacturer and explained that the main reason for this device (Z-Weather, http://www.pepper1.net/zwavedb/device/751) is to control shutters and shades and for this the lx is not appropriate enough as explained above.
I like to understand where the problems are extending Homey to support % as this is something that is supported in the z-wave documentation.

Martin

**Comment by caseda** [comment]
if you want a separate trigger for the percentage you should create your own flow card, the luminescence capability is fully specialized with flow cards etc to be a lux number,

it's not just the mobile card value that's get specified by a capability, it's also all the trigger, condition and action flow cards, even though the lux capability doesn't have action cards, it does have trigger and condition cards

i can give you an example for that, it's just not the best option to set the capability to percentage.

**Comment by octopussy1** [comment]
An example would be awesome. As really this sensor value is used as a potential trigger.

**Comment by caseda** [comment]
i actually never tried it this way, but in theorie it should work.
needed to find the most efficient way because of the GET parser.

driver.js:
```
	'measure_luminance': [
		{ // Get's the lux value and reports it back to mobile card
			'command_class': 'COMMAND_CLASS_SENSOR_MULTILEVEL',
			'command_get_parser': () => {
				return {
					'Sensor Type': 'Luminance (version 1)',
					'Properties1': {
						'Scale': 1
					}
				};
			},
			'command_report': 'SENSOR_MULTILEVEL_REPORT',
			'command_report_parser': report => {
				
				// make sure the right sensor type and scale gets here
				if (report['Sensor Type'] === 'Luminance (version 1)' &&
				  report.hasOwnProperty('Properties1') &&
				  report.Properties1.hasOwnProperty('Scale') &&
				  report.Properties1.Scale === 1) 
					return report['Sensor Value (Parsed)'];
				
				return null;
			}
		},
		{ // Gets the Percentage and sends it to a flow trigger
			'command_class': 'COMMAND_CLASS_SENSOR_MULTILEVEL',
			'command_get_parser': () => {
				return {
					'Sensor Type': 'Luminance (version 1)',
					'Properties1': {
						'Scale': 0
					}
				};
			},
			'command_report': 'SENSOR_MULTILEVEL_REPORT',
			'command_report_parser': report => {
				
				 // make sure the right sensor type and scale gets here
				if (report['Sensor Type'] === 'Luminance (version 1)' &&
				  report.hasOwnProperty('Properties1') &&
				  report.Properties1.hasOwnProperty('Scale') &&
				  report.Properties1.Scale === 0) {
					
					// put the percentage value into a tag
					const data = {
						'lux_percentage': report['Sensor Value (Parsed)']
					}
					
					// if data is present, trigger the device flow card
					if (data) {
						Homey.manager('flow').triggerDevice('DEVICE_FLOW_ID', data, null, node.device_data);
					}
				}
				return;
			}
		}
	],
```

app.json:
```
{
	"flow": {
		"triggers": [
			{
				"id": "DEVICE_FLOW_ID",
				"title": {
					"en": "Lux Percentage has changed"
				},
				"tokens": [
					{
						"name": "lux_percentage",
						"title": {
							"en": "lux %"
						},
						"example": {
							"en": "50"
						}
					}
				],
				"args": [
					{
						"name": "DEVICE_ID",
						"type": "device",
						"filter": "driver_id=DEVICE_ID"
					}
				]
			}
		]
	},
	"drivers": [
		...
	]
};
```

**Comment by WeeJeWel** [comment]
Thanks for your helpfulness @caseda! I'll close this issue as it's not a Homey issue.

It's best to create a custom capability `measure_luminance_percent` or so.
