### ISSUE TITLE
Homey stuck after update

### ISSUE THREAD

**Issue by mvunen** [athombv/homey#103]
Homey doesn't boot anymore after software update.

Starting normal: orange ring after one minute red ring.... 
Starting up side down: endless purple ring (14+ hours)

Multiple users affected!

**Comment by WeeJeWel** [comment]
Please help me isolate the issue:

1. When booting normally (orange ring), does it seem to 'flicker' once?

2. Does Homey go to recovery (plug it in, turn Homey on it's head áfter 10s)?

**Comment by Bumblez** [comment]
@WeeJeWel See also the forum, which has several reports of this issue. And according to them, the answer to (2) is a definite No.

**Comment by freemann** [comment]
for option 2 and to be 100% clear, do you mean;

- Plug homey's power

- let homey boot for 10 secs 

- then turn it upside down

?

**Comment by mvunen** [comment]
Together with Jeroen I tested a solution for this problem... It looks like it fixes this "bug"... The solution can be found on the Athom forum... Sticky thread "[HELP] My Homey is not responding after an update"...

For me this bug report can be closed...
