### ISSUE TITLE
Zwave devices not reacting

### ISSUE THREAD

**Issue by gajdur** [athombv/homey#1030]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

I have a Sunset Flow to close my Roller Shutters, Combination from Wifi Switches for 4 Shutters and 4 fibaro roller shutters 2. Using the http App for the wifi devices. 

**What was the result?**

After Sunset only my http devices are going down, the zwave is not reacting. Same with other fibaro switch relais, but not using it atm in flows. After reboot, the zwave devices are reacting.

**What did you expect as result?**

Wenn i use the roller shutters or switches in flows to react/execute the command.

**Any other remarks**

no

**Comment by caseda** [comment]
do they still work after the reboot? or do they stop working when you trigger them by a flow.

**Comment by WeeJeWel** [comment]
Do they work by controlling them manually?

**Comment by gajdur** [comment]
No. Even manualy over devices not working. Switches in wall working

**Comment by gajdur** [comment]
With switches i mean the roller shutter toggle switches.

**Comment by RobinBol** [comment]
What is the distance between Homey and the roller shutters? Thick concrete walls or something might block the signal from reaching the roller shutters. If possible try the same thing with Homey placed next to the roller shutters, then please report back if the problem still exists.

**Comment by AJediIAm** [comment]
Greetings, I experienced a similar issue yesterday on 0.10.9. I do not know if my issue is related to this one, but I thought I'd let you guys know about it. 

What is your Homey version (Settings → System)?

0.10.9

What did you try to achieve?

I tried to close my roller shutters (Via flow, voice command and manually)

What was the result?

The time-triggered flow did not close the roller shutters. 
The voice command was received correctly. Homey responded with a spoken confirmation, but the roller shutters did not close. 
Controlling the roller shutters individually via the web interface did not work.  

What did you expect as result?

Roller shutters should have closed.

Any other remarks

I have 4 roller shutters which are located 2-4 meters (open air) from Homey.
After a reboot of Homey, everything worked again as expected.

**Comment by gajdur** [comment]
Distance is no problem, i think the chip is busy. Still having the same issues with sunset flows, http requests to wifi devices working normal, zwave devices reacting after 30sek or longer even up to 10min.

**Comment by WeeJeWel** [comment]
@gajdur Is this still happening?

**Comment by gajdur** [comment]
No, atm is working. Tnx.
