### ISSUE TITLE
listeners not working on multiChannelNode[2] and scene activation (FGD-212)

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1033]
**What is your Homey version (Settings → System)?**
0.10.7

**What did you try to achieve?**
add a listener to Dimmer 2 (FGD-212) for the CC MultiLevel Switch for multiChannelEndnode[2],
or in human language, S2 / Switch 2
And add scene activation control for the Dimmer 2

_Please include detailed steps how we can reproduce the issue_
Add a simpele listener to Endnode 2 to see what homey gets on the multichannel 2 CC's and scene activation
and/or add a simpel listener to scene activation -> activation_set

**What was the result?**
Homey does not receive any values from the sensor when switched on the hardware.
No Basic CC and no MultiLevel Switch CC get received by homey.

Neither for scene id's that get's send by the dimmer 2, this might be because there can also be a dimming duration value send in the scene activation object.

**What did you expect as result?**
Be able to add an generic S2 input for when people don't want to use scene activation.

add scene activation for all the scenes that are there

**Any other remarks**

**Comment by WeeJeWel** [comment]
Fixed in 1.0.2

**Comment by swttt** [comment]
Can confirm it works, might close some issues on the fibaro github as well ;)
