### ISSUE TITLE
All (app) devices get deleted on reboot with --run of the current app still active

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1035]
**What is your Homey version (Settings → System)?**
0.10.7

**What did you try to achieve?**
reboot homey because it was needed, "forget" to stop the --run
re --run the app when done rebooting and continue with the current device(s) still there

**Please include detailed steps how we can reproduce the issue**
--run an app with devices installed (even installed when not in --run session)
reboot you homey with the --run still running.

**What was the result?**
come back into homey after reboot with all devices that are connected to the app deleted, because the --run app gets uninstalled, including all it's devices

**What did you expect as result?**
either have the devices still as unavailable devices until the app is --run again, or --install/app-store installed again
or even let the devices be there for an hour or so, and then the devices to be deleted, but not immediately.

**Any other remarks**

**Comment by WeeJeWel** [comment]
This is intended behavior. Maybe we simply should not delete the app at all? Your opinions please :-)

**Comment by SergeRegoor** [comment]
Personally I think it's good behaviour to keep the "run" option volatile.

However it would be nice to be able to install an app, but still have access to the debug console/info.
When testing your app for a longer time, you could install it and check the debug info.

Would also be great if we could optionally keep the app's settings and devices when removing the app, otherwise the "install with debug" idea has no added value :-)

**Comment by caseda** [comment]
my opinion still stands, remove the app on reboot.

but devices either installed before --run was activated leave installed. <= quiet hard to implement)

and/or devices that have been installed in(/before) --run session remove after +/- 5-10 minutes so the developer can still re-install the app-store version, --install command, or re-run the app.

**Comment by WeeJeWel** [comment]
Fixed! The app will now be rebooted but the settings (devices, insights etc) will remain.

**Comment by caseda** [comment]
woohoo, no losing all my fibaro devices any more when adding functionality to the app
