### ISSUE TITLE
speech-output.ask fails with multiple questions

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#1037]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

I'm currently building an App that needs to ask the user several questions before it can act. So what I did is the following

Homey.manager('speech-input').ask('Vraag 1',function(err,result){
   Homey.log('asking first question');
   Homey.log(result); 
   if(result != ""){
      Homey.manager('speech-input').ask('vraag 2',function(err,result){ 
        Homey.log('Answer to second question');
        Homey.log(result); 

```
 });
```

   }
});

**What was the result?**

The first question callback is called correctly. So I do get answer in the result property. The second question is asked thereafter but instead of waiting fot the input of the user it's callback is directly called with result empty and no error returned

**What did you expect as result?**

I was expecting that the second question was threatened as the first. So wait for the user to react and call the callback with that answer. 

**Any other remarks**

**Comment by WeeJeWel** [comment]
Fixed! Tested with the following sample:

```
Homey.manager('speech-input').ask('Question 1', { timeout: 1000 }, function(err, result) {
		if( err ) console.error( 'Q1', err );

		console.log('Q1:', result);

		Homey.manager('speech-input').ask('Question 2', { timeout: 1000 }, function(err, result) {
			if( err ) console.error( 'Q2', err );
			console.log('Q2:', result);
		});
	});
```

**Comment by jjtbsomhorst** [comment]
Great!  Looking forward testing it

**Comment by jjtbsomhorst** [comment]
will this be released in 0.10.8?

**Comment by WeeJeWel** [comment]
Yes, or 0.11, whichever comes first :)

**Comment by WeeJeWel** [comment]
Can you confirm that this is fixed now?

**Comment by jjtbsomhorst** [comment]
I have to install the experimental firmware for that first. Is it already possible to undo experimental firmware when you don't want it anymore?

**Comment by WeeJeWel** [comment]
With the new Wi-Fi Recovery we're launching this week you can yes :-)

**Comment by WeeJeWel** [comment]
I'm closing this issue as it should be fixed. If it persists, please re-open.

**Comment by jjtbsomhorst** [comment]
Just did a first test with firmware 0.10.9. Seems to be working indeed.
