### ISSUE TITLE
[KaKu app] Please include ACDB-6500AC as a input device.

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#1039]
What the title already says. 
With apps like Better Logic you can used this button for a variety of project.

...

**Comment by BasKiers** [comment]
Hi,

It is already possible to add the ACDB-6500AC button as an input device using the ACDB-7000C driver. Just pair the doorbell and use the flow trigger card. When there is time I will look into adding more kaku devices to the kaku app.

Regards,
Bas

**Comment by KroontjesPen** [comment]
Perfect! Thanks :+1:
