### ISSUE TITLE
How to test 'if a signal is received or sent by homey in the user interface or log file'

### ISSUE THREAD

**Issue by pkonings** [athombv/homey#104]
I would like test if my signals are even recognized by homey. For example I press a button on a (KaKu) remote and have no idea yet if homey sees it, interprets it and is going to do something with it. 

Suggest to look at Domoticz where automatic scanning of devices is done and a continuous LOG file shows whats happening.
In flow editor it would pretty much help if the device icon flashes, change color for example. Likewise in the devices add procedure.

**Comment by bvdbos** [comment]
I'd like to extend this with ie logging of the interpreted voice-commands...

**Comment by WeeJeWel** [comment]
You could make Homey say something in a flow? If it's a device, just open the device card.

**Comment by pkonings** [comment]
not working :(
![image](https://cloud.githubusercontent.com/assets/10164680/12979479/c8057334-d0d7-11e5-83aa-b3d162b85862.png)

**Comment by irritanterik** [comment]
Logging would be very nice in the browser console or near 'stuff for geeks'.

**Comment by AndreSomers** [comment]
Actually, I would like some form of feedback in the Flows screen as well. Switching back and forth when creating a flow between your flow and some log of signals that were processed would be annoying, and it would be really handy to have. Like, when you want to add a command based on an RFC tag, it would be nice to see the tag ID and just be able to put into the "specific tag" box easily. When creating a voice command, it would be good to see how the command was interpretted, so you can think of something else or work on your pronounciation. If are adding a remote, it would be good to see the button you just pressed as button names are not always obvious.

**Comment by WeeJeWel** [comment]
It's a good suggestion. I'll think of how to implement this in a good way :)

**Comment by evad1st** [comment]
I use this always but still not reliable, for some reason no speech commands can be added .... And most of the time when I experience this even the time and date can not be accessed ...  I can only assume that the server can not be reached .... (How to check?)
Ps I did a full reset, soft reset, restart and power off and on (and every time I reteach my voice (now I can get all five check marks at the first try :-) )

**Comment by athomey** [comment]
See also: https://forum.athom.com/discussion/732/request-please-show-timestamp-last-run-of-a-flow-and-optionally-a-log-of-all-of-them-0-8-17

**Comment by WeeJeWel** [comment]
This should work by now so I'm closing this issue.
