### ISSUE TITLE
App store update's not getting to Homey

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1040]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

I've noticed that Homey doesn't update apps (even though) Automatically update is activated. This also applies for when Automatically update is de-activated, the update available button doesn't appear.

For example. I'm still using KaKu 2.6.2 while 2.6.4 is out and the update available button isn't appearing. Had the same with ANWB app, updated manually.

**What was the result?**

Apps stay outdated.

**Comment by mike9011** [comment]
Same issue here on 0.10.7

**Comment by timk1990** [comment]
The store also gives an error that something went wrong with the version. Maybe connected to this issue

**Comment by WeeJeWel** [comment]
We're working on this :)

**Comment by joachimroeleveld** [comment]
This problem should now be resolved. Feel free to reopen if it still persists.
