### ISSUE TITLE
Kaku sending signals dont work without a delay of 2 sec

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#1041]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?

Make a AMST-606 put on a ACM-1000

*Please include detailed steps how we can reproduce the issue

Made a flow:
![slk](https://cloud.githubusercontent.com/assets/19249884/19732695/e598a4b2-9ba1-11e6-866f-e80d51ee3b25.png)

**What was the result?**

Without the delay of 2 seconds the flow dont work.

**What did you expect as result?**

That the flow works without the delay.

**Any other remarks**

Kaku app v2.6.2

**Comment by BasKiers** [comment]
To add to this issue. It is suspected that the 2 second delay is needed to be sure the air is "clear" before sending the signal. Homey does have safeguards for this but this should be verified.

**Comment by KroontjesPen** [comment]
It is indeed needed. When I forget this after a while to do, I also get direct problems.

**Comment by mike9011** [comment]
I don't have this issue with my APA3-1500R. I have a flow which turns on/off two devices at the sime time.

**Comment by KroontjesPen** [comment]
Also the APIR-2150 don't need a delay, if Homey can pick-up the signal.
That distant is short.

**Comment by jjtbsomhorst** [comment]
For what it's worth. I also don't have this issue. No need for delay's.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
