### ISSUE TITLE
Room feedback when asking to turn off the lights in certain room

### ISSUE THREAD

**Issue by PandaNL** [athombv/homey#1044]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Ask Homey to turn off the lights in a certain room.

_Please include detailed steps how we can reproduce the issue_

Ask Homey to turn off the lights in a certain room.

**What was the result?**

Homey says it will turn of the lights

**What did you expect as result?**

Let Homey say that it turns of the lights in X

**Any other remarks**

Sometimes Homey won't listen correctly and turns off the lights in the wrong room or in all rooms, to get a better feedback to actually know if Homey understand you correctly this would be very helpfull.

Btw, I posted this Idea back in March, we are 8 months further this should be very easy to implement.
(https://forum.athom.com/discussion/968/voice-command-lights-on-off-in-certain-zone)

**Comment by Tweake** [comment]
This has been on the to do list for some time now. I have added the spoken feedback for lights, other deviceclasses will follow in the near future.

**Comment by PandaNL** [comment]
Works great, thank you.
