### ISSUE TITLE
Incorrect information shown Color Temperature - hint-popup

### ISSUE THREAD

**Issue by IvoDerksen** [athombv/homey#1045]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Create warmer color on LIFX
Read instructions in hint-popup which states:

> Adjusts the temperature of the light. A lower value means a warmer color.
					
Change color temperature percentage

**What was the result?**

Lowering percentage creates a cooler color, thus the opposite happens

**What did you expect as result?**

What was hinted in the hint popup
Which is correct (thank you Caseda):
A lower K value is a warmer color.

**Any other remarks**

Adjusts the temperature of the light. A higher percentage/value means a warmer color.
Minor text edit.

Or 

Correct the working as stated in the hint

**Comment by caseda** [comment]
actually the text is correct, the working is not :) but still good find.!

**Comment by IvoDerksen** [comment]
True!
Thank you for correcting my lack of coffee morning!

**Comment by RobinBol** [comment]
Actually the hint text is incorrect. When using the mobile card and selecting a cool value the app will receive a low value (so completely cool means a value of 0, and warm a value of 1).

In the Flow editor when setting the slider to a low value it will therefore also set the temperature to a cool value and vice versa.

I assigned @WeeJeWel to change the hint text.
