### ISSUE TITLE
pressent detection range

### ISSUE THREAD

**Issue by spelbreker** [athombv/homey#1046]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

try to get pressent detection working in my home 

**What was the result?**

 have tried to set the homey location around my apartment complex. it works but my phone gps set random 3 places around the apartment. if the gps location of my phone and homey location are together than it works. 

if the phone disconnect and reconnect with the wifi and it think it moved location it detect not the pressent

**What did you expect as result?**

if the phone is connected to the wifi it wil set the user to pressent. 

**Any other remarks**

if i can set the scan range of the gps what called home that is the problem solved and wil it work better.

**Comment by joachimroeleveld** [comment]
Please refer to #1236 for further development on presence detection.
