### ISSUE TITLE
[Enhancement] Mobile device cards view in browser

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1047]
**What is your Homey version (Settings → System)?**

0..10.7

**What did you try to achieve?**
Show mobile device cards in the browser.

*Please include detailed steps how we can reproduce the issue*
Browse  to homey-ip/manager/mobile/?zone=99.....

**What was the result?**
Nice view of mobile device cards in the browser, only missing menu to change zones easily and button after login to go there.

**What did you expect as result?**
A 5th menu at the default menu to open the mobile device cards available on chrome browser on pc and tablet. Add a frame or menu to switch  zones and finished!

**Any other remarks**
I like this view  more than the default device view,  that one of only for managing zones and devices. Once configured that won't be used for weeks if I had the mobile view.

**Comment by WeeJeWel** [comment]
We won't add these views, as the web interfaces are meant to be embedded in the Homey Smartphone App.
