### ISSUE TITLE
[Enhancement] Change default triggers 

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#1048]
I would like to have an option somewhere that I can change the behavior of several built in triggers.

**Comment by Fire69** [comment]
Yes, this would be very useful, especially with commands for lights.
Now, if a command with a room in it is misunderstood, ALL the lights turn on/off, also children's bedrooms...
Also, when giving commands to turn on/off ALL lights, you should have the option to exclude some lights that are controlled in other ways.

**Comment by SilverApe** [comment]
I would like that to

**Comment by Willieku** [comment]
me too,   same problem here.
And; I expect more problems whit the voice triggers in the apps.
i have no idea yet how to prevent this, other then the possebillety to exlude every voice control, one by one.

**Comment by WesRos** [comment]
There are a lot of posibilities to make Homey more flexible with the built-in commands:

- enable/disable built-in command
- enable/disable devices reaction on voice commands
- decide with device are listen to built-in commands

The most flexible solutions could be to create all the 3 posibilities.

**Comment by skteu** [comment]
Totaly agree. As voice recognition is not always as reliable as we would like it to be, the build in commands lead to unwanted behavior.
So I definitely would like the “turn on/off lights” command to require a room or “all” in the command before it reacts.

**Comment by WesRos** [comment]
I've slept some night and this give a idea for a solution.
Created for each "Built in voice command" a drop down list with all the device's who are related to the voice command. For each voice command its possible to select the devices that should respond.

This could be included in the Microfoon - setting menu - Speech Recognition.

In the front of each voice command a checkbox to switch on/off the command.

**Comment by jjtbsomhorst** [comment]
Wouldn't it be easier to just add the list of default triggers to the 'speech'  trigger? So that when you have a flow that contains one of the default triggers it does this and if there is no flow configured it just does the default behaviour? And ofcourse an option to disable default triggers at all ;)

**Comment by WrDX** [comment]
Maybe implement the easiest solution first? A setting to disable all the default (built-in) voice triggers would solve a lot of problems users have right now. Then a more elegant and complex solution could be added later.

**Comment by WesRos** [comment]
Since Homey version 1.2.0 RC10 this issue is more imported. I cant use the most of the custom voice commands anymore.

Problem are:

- Ive a lot of devices with the same name: Livingroom --> thermostat, television, window screen, room name. This conflict the built-in commands.

- When using the word: music in a command, the built-in command is reporting Homey cant play music.

Please make the built-in command configurational.

**Comment by Steefph** [comment]
I know have a flow with the keywords "Radio" and "3fm" in it and the rule works fine except that homey Says: "Sorry I did not understand you". What's up with that?

So, Homey does execute the flow on speech input but still tells there is an error 
On 1.2.0-rc.10

I understand that Athom adds default lines for standard users but, you should allow your more advanced users to use the device as they like. Not having the option to disable the defaults is just weird ;)

**Comment by bvdbos** [comment]
Our most recent update, v1.2.0 which includes Media, improved 433 Mhz range and an improved speech parser, is still in experimental. The final bugs are now being polished and it's ready for stable any moment now.
From https://forum.athom.com/discussion/comment/49280/#Comment_49280 :
The Homey Smartphone App has been updated on iOS and Android as well, and we've seen 100% - 300% speed improvements and many bugs that have been fixed. Great work!

Note: as of Homey v1.2.0, a much requested feature was feedback when Homey did not understand what you said. That now works, with the small drawback that it requires everyone to migrate their 'When Homey said something And the text contains' cards to the 'When something specific was said' card, if that hasn't happen yet.

**Comment by jeroenski74** [comment]
Please make it possible to disable the buildin commands at least, but rather I would like to assign n devices to the internally defined words like light, tv etc. I control the tv via harmony for example and use the 'TV on' command. First this worked fine, but now I get 'I cannot find a TV to activate' and the TV is still turned on.

**Comment by Inversion-NL** [comment]
Yes, me to.
Or if we could somehow assign the device type.

**Comment by elcovb** [comment]
I have this problem too; I can't say "TV aan" anymore. Athom, please fix this!!

**Comment by jjtbsomhorst** [comment]
@jeroenvollenbrock Can you give us any update on if this change is going to be implemented and if yes a possible ETA?

**Comment by mauritsivs** [comment]
yes, would be great to have some more freedom on what homey reacts to. like a page with all current built in commands (also the ones that are added by apps), and a checkbox to turn them on/off

**Comment by Steefph** [comment]
Could anyone from Athom please comment on this? The standard sentences are getting rather annoying and are taking the fun out of creating any flow.

**Comment by bvdbos** [comment]
@WeeJeWel already commented on the duplicate bug #1260 but not what you want to hear I guess...

**Comment by mahendriks** [comment]
I have problems with this too. I bought a Fibaro wallplug especially for my Bezerra Magica Italian Espresso Group. This machine needs to heat 20 minutes before making the best espresso in the world. But Athom blocked the word "coffee". Now that is sour espresso. No "make me some coffee", "prepare coffee" or any any variation on that one. And the thing is, why the word coffee? I don't see any example of this word on the support page with build-in commands. So I can only figure that it's someway connected to the iKettle stuff, that nobody owns in relation to all other coffee-lovers. 

Please fix this @stefanwitkamp  @WeeJeWel or at least give us the choice to enable / disable the build in options...

**Comment by Steefph** [comment]
mahendriks, yes it is still really annoying and I get sometimes the urge to throw the Homey orb out of the window but, I've resolved it in some ways by using the virtual switches. Perhaps in your case a virtual switch called coffeemaker (don't know what the build in string is looking for as this information is also not easily found)
And use the virtual switch to trigger your Fibaro plug. Hope this helps. 

Athom, why are you making such a different product as was described during Kickstarter?? Now even the desktop ability to alter the flows is going to be removed? Nothing so annoying as working on a small screen. If it would be an extra I would understand but, removing it? Working with mouse and keyboard is so much faster. Or are you also programming the core of Homey on a tablet?

**Comment by mahendriks** [comment]
@Steefph of course it is possible to use the word coffeemaker but this isn't as easy to speak as coffee. Not to be a nitpicker, but in this case it just needs the word coffee to be the wow factor I bought Homey for. And the wallswitch.

**Comment by Steefph** [comment]
@mahendriks, I know what you mean, So I mentioned creating a virtual device coffeemaker that probably get triggered by the internal syntax. So perhaps when you say: "Ok Homey make me a coffee". It actually starts looking for a device which has the word coffee in it and turn on the virtual switch which in turn triggers your actual coffeemaker using the Fibaro in the flow triggered by the Virtual switch :-P Hope it makes a bit sense. 
I wanted to have a specific rule for my TV (not only turning the TV on but everything needed to actually watch TV). I created a virtual switch called TV and this one does now a similar thing as what your coffee rule does.

**Comment by Inversion-NL** [comment]
New use case on why to disable the build in triggers.
I have several screens. Without me having created a flow to close the screens.

Now if a window is open while someone asks Homey to close the screens it'l damage my screens!
I've bought door/window sensors but since Homey doesn't check this sensor and I'm unable to disable the build in triggers leaves me no option but to remove the screens from Homey until we are able to disable or change the build in voice trigger!

**Comment by WrDX** [comment]
This is getting kinda crazy, Homey was marketed as a device that you can use in any way you want.  You can define it's behaviour completely by flows. But the developers are forcing all kinds of default flows on us now. I have to make flows with uncommon words just to bypass default behaviour.

Please make a checkbox somewhere to disable all default flows.

**Comment by mahendriks** [comment]
@jeroenvollenbrock is there any way you can provide us with some information regarding this issue? At least if it's part of an expected change? My homey becomes more and more complicated by messing around with extremely difficult and weird flows. So if I know what to expect I can let things go and sit it out...

**Comment by Nexz** [comment]
Just got a Homey and this is getting in my way too. Devs, any update to share with us?

**Comment by WeeJeWel** [comment]
We have no plans to add support for this. While it sounds simple, technically it's very complex to create and will definitely result in many bugs, which we do not want to allocate the time for.

I suggest you use different commands to circumvent the issue.
