### ISSUE TITLE
[Z-Wave] Homey doesn't recognize the device is awake properly

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1049]
**What is your Homey version (Settings → System)?**
<= 0.10.7

**What did you try to achieve?**
1. Change parameters without having to wake up a sensor manually.
2. Get measure_battery (/any other capability) when module is awake (not fully tested that this is same issue)

*Please include detailed steps how we can reproduce the issue*
1 -
  1. Change any parameter of the FGMS-001 (Fibaro Motion Sensor, LED colour is the easiest visible) and save it,
  2. activate the motion trigger before the sensor gets awake on it's own wake-up interval (maximum of 2 hours).
  3. Wait until the wake-up interval has been met (maximum 2 hours)
  4. See the parameter still has not been changed/LED colour did not change.

2 - (not fully tested)
  1. Get measure_battery capability when on('online') listener activates
  2. Can still time out because sensor is not really awake

**What was the result?**
1. Parameters are not being saved inside the module, and will not be in queue anymore because homey thought the sensor was awake.
2. time-out and thus the sensor gets null as a result

**What did you expect as result?**
1. Parameters being saved without having to manually wake-up the device, or not trigger the device for a max of 2 hours.
2. Get capabilities when sensor is awake without time-out (maybe even able to make this an option in the z-wave driver, IE: "get_on_wake": true, will look into this in the near future, or athom/anyone else wants to look into this.)

**Any other remarks**
seconds issue is probably the same issue because of time-outs (device not awake), but have not been able to fully test if this really is the issue yet.

**Comment by Tweaqer** [comment]
+1

**Comment by robertraaijmakers** [comment]
+1

**Comment by djeskoswe** [comment]
+1 just tested on a fibaro door sensor and same problem

**Comment by caseda** [comment]
confirmed fixed for online listener
