### ISSUE TITLE
Android app doesn't show devices (anymore)

### ISSUE THREAD

**Issue by pkonings** [athombv/homey#105]
I have seen devices one time yesterday after first installation. However, even after restarting the app, logging out and in again does not help.

**Comment by goldenice** [comment]
Did you put those devices in a zone other than home perhaps? You can select your current zone by using the the round button in the right bottom corner of the screen.

If you are in the same zone as your devices, but you still do not see them, please tell me your phone brand and model, and I'll try to fix it for you.

**Comment by pkonings** [comment]
I indeed played with these zones to look if that was a cause/effect. My HTC one (M7). See snapshots:


![image](https://cloud.githubusercontent.com/assets/10164680/12977974/74eea5de-d0ce-11e5-807c-c92a39e6c7a4.png)

**Comment by pkonings** [comment]
en vanaf de HTC

![Uploading Screenshot_2016-02-11-14-46-00.png…]()
![Uploading Screenshot_2016-02-11-14-46-10.png…]()

**Comment by goldenice** [comment]
Hmm, that should definitely work. What version of the app are you currently running?

**Comment by pkonings** [comment]
1.1.4-build 30

**Comment by pkonings** [comment]
![screenshot_2016-02-11-14-46-10](https://cloud.githubusercontent.com/assets/10164680/12978872/f4d6ebf8-d0d3-11e5-99fb-9ae7f9829701.png)
![screenshot_2016-02-11-14-46-00](https://cloud.githubusercontent.com/assets/10164680/12978873/f4f2abd6-d0d3-11e5-9132-45c62a5ad776.png)

![image](https://cloud.githubusercontent.com/assets/10164680/12978910/2c57db8c-d0d4-11e5-8a75-8bcda2142ba7.png)

**Comment by goldenice** [comment]
Okay, and if you close the app, remove it from your recent apps in Android (fully close it so to say), restart it, and navigate to Living Room? Perhaps the app won't update properly if a device is moved to another zone without a full restart?

**Comment by pkonings** [comment]
I have even gone one step further without success. Full reinstallation after removal...

**Comment by goldenice** [comment]
Okay, well, in that case it's definitely a bug, and definitely not something I can fix in the blink of an eye. I will look into it, but it's going to take some time.

If there are others with the same problem, please comment here with your phone brand and model number and preferably Android version as well!

**Comment by mirakels** [comment]
Yes have the same issue. Have an ir-device and homey in the living room but nothing shows up in the app. I also did not receive notifications from homey.
I removed the app completely and reinstalled it. Now notifications do work, but still no devices in the living room.

To go on a bit further:
I switched of home last night, and the app was closed.
Now I switched on homey this morning and when I start the app it says: "Sorry, this homey is not connected, automatically trying to reconnect"
No when I ask home for the time it is back at the old probelm 'Oops cannot reach the server'

Samsung Note 3, android 5.0

**Comment by goldenice** [comment]
@mirakels These are two problems. The first is not really a problem: not all devices have cards. I can't really imagine what you'd want to put on a IR-card, so we don't have one.

The second one is that Homey can't connect to your wifi or the internet, which means it can't process speech, and the app can't connect to your Homey. This is most likely solved by rebooting your Homey ("have you tried turning it off and on again?") or reconnecting your Homey to the WiFi.

**Comment by stillegenieter** [comment]
I have the same problem as pkonings. These are my devices
One Plus X, Android 5.1.1, Homey app v 1.1.5
Samsung Tab S, Android 5.1.1, Homey app v 1.1.5

**Comment by WeeJeWel** [comment]
Fixed with Homey 0.8.35 + Android app v2
