### ISSUE TITLE
Somfy pairing confirmation buttons not directly visible with Homey in Dutch

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1050]
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**
Confirm pairing was done OK

*Please include detailed steps how we can reproduce the issue*
Pair somfy sunscreen and not seeing a confirm button
<img width="607" alt="screen shot 2016-11-02 at 20 24 29" src="https://cloud.githubusercontent.com/assets/18570823/19944104/a3558568-a13a-11e6-9cc4-93d9a79cac5e.png">

**What was the result?**
Had to scroll to get to the button. First I thought it was an error, since no scrollbars are available

**What did you expect as result?**
See confirmation buttons below the question (without scrolling)

**Any other remarks**
Minor issue.

**Comment by BasKiers** [comment]
Hi, thank you for the bug report.

I am working on rewriting the whole Somfy app which will also fix this issue. 

Regards,
Bas

**Comment by BasKiers** [comment]
Version 2.0.0 of the somfy app is now published and fixes this issue. Thank you for reporting! If you experience any other problems please open a new issue.

Regards,
Bas
