### ISSUE TITLE
Add room headings to devices section of flow manager

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#1052]
Currently I add the room name to all my devices so they're easily identified.

Adding the rooms to the devices section of the flow manager would make life a lot easier ;-)

**Comment by jeroenvollenbrock** [comment]
Great suggestion!

**Comment by WeeJeWel** [comment]
![screen shot 2017-03-28 at 21 16 53](https://cloud.githubusercontent.com/assets/319873/24423015/e78c101a-13fb-11e7-8aef-8a6e93eab056.png)
![screen shot 2017-03-28 at 21 16 41](https://cloud.githubusercontent.com/assets/319873/24423018/e8fc2386-13fb-11e7-9d54-908e6665cdd2.png)

Fixed in v1.3.0!
