### ISSUE TITLE
getSettings not working anymore in 0.10.9

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1053]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

After update to 0.10.9 the smile p1 app is not receiving the device settings anymore from the driver.js

*Please include detailed steps how we can reproduce the issue*

 module.exports.getSettings( device_data, function( err, settings ){
     Homey.log(err);   
     Homey.log(settings);
  });

**What was the result?**

when I call the getSettings it just never returns with anything. Not even an error.

**What did you expect as result?**

That getSettings works as it did before 0.10.9

**Any other remarks**

...

**Comment by gruijter** [comment]
@weejewel: Found that the problem is caused because the device that is created during pairing has a second data property (readings, a json with the smile p1 meter readings during pairing). This always worked before 0.10.9. I could remove this second property in device.data, but then all app users would have to re-pair their devices and therefore losing all historic insights. Is it intentional that device.data can only have id in it?

				Homey.addDevice({
					data	: {id , readings},
					name	: "Smile_"+smileId,
					settings: settings_init

**Comment by nattlip** [comment]
i thought only constant parameters are allowed in the data of device_data. my device data contain also other parameters but there are no device settings stored in my app  , they still work in 0.10.9

**Comment by gruijter** [comment]
The readings parameter is a 'constant'. It is the reading at the time of pairing in the form of a somewhat complex / multilevel object. Maybe it is the multilevel part that cannot be handled anymore in fw 0.10.9

**Comment by WeeJeWel** [comment]
The `device_data` can have anything in it, as long as it's static and passed every time communicating with Homey. See here for more info: https://developers.athom.com/library/drivers/ (under 'The `device_data` object')

**Comment by gruijter** [comment]
@WeeJeWel Thx for confirming that indeed I should be able to have the 'at-time-of-pairing-meter-reading' in the device_data. Unfortunately this is not the case for the data I am using (a somewhat complex / multilevel object). This problem was introduced with fw 0.10.9.

**Comment by gruijter** [comment]
```
  readings:
   { modules:
      { module:
         [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
             vendor_name: [ 'Xemex', [length]: 1 ],
             vendor_model: [ 'XMX5XMXABCE0', [length]: 1 ],
             hardware_version: [ '', [length]: 1 ],
             firmware_version: [ '', [length]: 1 ],
             created_date: [ Mon Apr 08 2013 09:00:00 GMT+0200 (CEST), [length]: 1 ],
             modified_date: [ Fri Nov 04 2016 22:29:30 GMT+0100 (CET), [length]: 1 ],
             deleted_date: [ '', [length]: 1 ],
             services:
              [ { electricity_interval_meter:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       measurement:
                        [ { _: '0.000', '$': [Object] },
                          { _: '0.000', '$': [Object] },
                          { _: '0.000', '$': [Object] },
                          { _: '164.000', '$': [Object] },
                          [length]: 4 ] },
                     [length]: 1 ],
                  electricity_point_meter:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       measurement:
                        [ { _: '0.000', '$': [Object] },
                          { _: '440.000', '$': [Object] },
                          [length]: 2 ] },
                     [length]: 1 ],
                  electricity_cumulative_meter:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       measurement:
                        [ { _: '1072678.000', '$': [Object] },
                          { _: '2856067.000', '$': [Object] },
                          { _: '9172689.000', '$': [Object] },
                          { _: '6307663.000', '$': [Object] },
                          [length]: 4 ] },
                     [length]: 1 ] },
                [length]: 1 ],
             protocols:
              [ { dsmrmain:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       serial: [ 'xxxxxxxxxxxxxxxxx', [length]: 1 ],
                       dsmrmbuses: [ { dsmrgas: [Object] }, [length]: 1 ] },
                     [length]: 1 ] },
                [length]: 1 ] },
           { '$': { id: 'xxxxxxxxxxxxxxxxx' },
             vendor_name: [ '', [length]: 1 ],
             vendor_model: [ '', [length]: 1 ],
             hardware_version: [ '', [length]: 1 ],
             firmware_version: [ '', [length]: 1 ],
             created_date: [ Mon Apr 08 2013 08:00:00 GMT+0200 (CEST), [length]: 1 ],
             modified_date: [ Fri Nov 04 2016 22:29:30 GMT+0100 (CET), [length]: 1 ],
             deleted_date: [ '', [length]: 1 ],
             services:
              [ { gas_interval_meter:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       measurement: [ { _: '0.210', '$': [Object] }, [length]: 1 ] },
                     [length]: 1 ],
                  gas_cumulative_meter:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       measurement: [ { _: '4204.406', '$': [Object] }, [length]: 1 ] },
                     [length]: 1 ] },
                [length]: 1 ],
             protocols:
              [ { dsmrgas:
                   [ { '$': { id: 'xxxxxxxxxxxxxxxxx' },
                       serial: [ 'xxxxxxxxxxxxxxxxx' , [length]: 1 ],
                       dsmrmain: [ { '$': [Object] }, [length]: 1 ] },
                     [length]: 1 ] },
                [length]: 1 ] },
           [length]: 2 ] } } }
```

**Comment by gruijter** [comment]
^^ An example of the static value for 'readings'. So, could you please re-open the issue?

**Comment by WeeJeWel** [comment]
Is that entire object in your device_data object?

**Comment by gruijter** [comment]
no, I also have id.
```
            Homey.addDevice({
                data    : {id , readings},
                name    : "Smile_"+smileId,
                settings: settings_init
```

**Comment by gruijter** [comment]
Note: I haven't changed my code for this in a long time. The problem introduced itself right after updating to 0.10.9

**Comment by WeeJeWel** [comment]
Well, I'm pretty sure that object is not static. Nothing has changed (maybe your readings did? ;)) in the handling of device_data...

**Comment by gruijter** [comment]
It is the readings state at the moment of pairing and not the actual readings, so is static.

**Comment by WeeJeWel** [comment]
Hm. Could you serialize this object for me, so I can debug?

**Comment by gruijter** [comment]
Ok ,how do I do that?

**Comment by WeeJeWel** [comment]
`console.log(JSON.stringify(device_data, false, 4))`

**Comment by gruijter** [comment]
here is the readings part:
```{"modules":{"module":[{"$":{"id":"b278caf322124cf0bd4b84c0e514a295"},"vendor_name":["Xemex"],"vendor_model":["XMX5XMXABCE000021673"],"hardware_version":[""],"firmware_version":[""],"created_date":["2013-04-08T09:00:00+02:00"],"modified_date":["2016-11-07T16:08:44.156+01:00"],"deleted_date":[""],"services":[{"electricity_interval_meter":[{"$":{"id":"6765e34867314ccb886bb72455610694"},"measurement":[{"_":"0.000","$":{"log_date":"2016-11-07T16:00:00+01:00","unit":"Wh","interval":"PT300S","directionality":"produced","tariff_indicator":"nl_offpeak"}},{"_":"0.000","$":{"log_date":"2016-11-07T16:00:00+01:00","unit":"Wh","interval":"PT300S","directionality":"produced","tariff_indicator":"nl_peak"}},{"_":"0.000","$":{"log_date":"2016-11-07T16:00:00+01:00","unit":"Wh","interval":"PT300S","directionality":"consumed","tariff_indicator":"nl_offpeak"}},{"_":"40.000","$":{"log_date":"2016-11-07T16:00:00+01:00","unit":"Wh","interval":"PT300S","directionality":"consumed","tariff_indicator":"nl_peak"}}]}],"electricity_point_meter":[{"$":{"id":"c35b5cf0b4eb46c2989dba87d07b1b7b"},"measurement":[{"_":"0.000","$":{"log_date":"2016-11-07T16:08:34+01:00","unit":"W","directionality":"produced"}},{"_":"560.000","$":{"log_date":"2016-11-07T16:08:34+01:00","unit":"W","directionality":"consumed"}}]}],"electricity_cumulative_meter":[{"$":{"id":"a17aa51dda834556905f3ea1689d18f7"},"measurement":[{"_":"1074406.000","$":{"log_date":"2016-11-07T16:05:00+01:00","unit":"Wh","directionality":"produced","tariff_indicator":"nl_offpeak"}},{"_":"2856094.000","$":{"log_date":"2016-11-07T16:05:00+01:00","unit":"Wh","directionality":"produced","tariff_indicator":"nl_peak"}},{"_":"9208829.000","$":{"log_date":"2016-11-07T16:05:00+01:00","unit":"Wh","directionality":"consumed","tariff_indicator":"nl_offpeak"}},{"_":"6311007.000","$":{"log_date":"2016-11-07T16:05:00+01:00","unit":"Wh","directionality":"consumed","tariff_indicator":"nl_peak"}}]}]}],"protocols":[{"dsmrmain":[{"$":{"id":"7ce8353c44db4198bb83d446b68cec01"},"serial":["98108309        "],"dsmrmbuses":[{"dsmrgas":[{"$":{"id":"f7b2aeab9f1e43e8b4e2d37b73f96045"}}]}]}]}]},{"$":{"id":"b48aaa16b25046baa84feaa084922e8f"},"vendor_name":[""],"vendor_model":[""],"hardware_version":[""],"firmware_version":[""],"created_date":["2013-04-08T08:00:00+02:00"],"modified_date":["2016-11-07T16:08:44.156+01:00"],"deleted_date":[""],"services":[{"gas_interval_meter":[{"$":{"id":"9a438f7016734f3cb3835e8c3a9b92d5"},"measurement":[{"_":"0.379","$":{"log_date":"2016-11-07T15:00:00+01:00","unit":"m3","interval":"PT1H","directionality":"consumed"}}]}],"gas_cumulative_meter":[{"$":{"id":"44e77f7762c84cc8973a752a8128caf5"},"measurement":[{"_":"4217.251","$":{"log_date":"2016-11-07T16:00:00+01:00","unit":"m3","directionality":"consumed"}}]}]}],"protocols":[{"dsmrgas":[{"$":{"id":"f7b2aeab9f1e43e8b4e2d37b73f96045"},"serial":["28011001147026511"],"dsmrmain":[{"$":{"id":"7ce8353c44db4198bb83d446b68cec01"}}]}]}]}]}}```

**Comment by WeeJeWel** [comment]
Please send the entire device_data object :)

**Comment by gruijter** [comment]
I have removed this from the device_data object since the app hangs on getSettings when I leave it in :). Also I had to remove the Original device where I still had it in. I can try to modify the code back, and pair again to recreate the problematic device_data object. In the mean time: attached is an example of the readings part for a device I just paired.
[readings.txt](https://github.com/athombv/homey/files/575734/readings.txt)

**Comment by gruijter** [comment]
[device_data.txt](https://github.com/athombv/homey/files/575751/device_data.txt)

Here is the full device_data that makes getSettings hang...

**Comment by WeeJeWel** [comment]
I've succesfully paired a device, changed capability values and run a getSettings() on 0.10.9 with that object, so there really must be something else going wrong.

I strongly suggest you do not use such a large device_data object, it's unnecessary overhead and creates bugs like these very fast :)

**Comment by gruijter** [comment]
Ok, no big problem. I can work around this. Still strange that you are able to de getSettings without a problem. I have had other app users also report the problem to me right after the fw update.

But anyway, what would be a good practice for a Homey maximum object size?

**Comment by WeeJeWel** [comment]
Keep it to the minimum required. So an ID, Mac address or anything you need to identify it, no more :)

**Comment by gruijter** [comment]
Will do, Thx for investigating :)

**Comment by WeeJeWel** [comment]
Good luck!
