### ISSUE TITLE
Onduidelijke NL titels interne flow kaarten

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1055]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**
Gebruiken flow acties

**What was the result?**
Onduidelijkheid over welke kaart wat doet. De titels zijn gelijk:
![image](https://cloud.githubusercontent.com/assets/15232724/20033599/79c924ea-a3a4-11e6-9e47-b6313ca90fdb.png)

**What did you expect as result?**
Maak verschil tussen 'start een flow' en 'activeer een flow' duidelijker.

**Comment by WeeJeWel** [comment]
Duplicate of #1059 (and already fixed :))
