### ISSUE TITLE
FGFS-101-PLUS, Flood Sensor (Z-Wave Plus) no reaction 

### ISSUE THREAD

**Issue by glijie** [athombv/homey#1056]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 0.10.9
App Fibaro v1.0.16
Sensor Fibaro FGFS_101_v2_1 or v-3.2 eu?

**What did you try to achieve?**

after adding the FGFS-101-PLUS, Flood Sensor (Z-Wave Plus) i want to see some reaction of the sensor inside homey. temperatuur is not showing, wateralarm is not reacting and sabotagealarm is not reacting

*Please include detailed steps how we can reproduce the issue*

after resetting sensor, removing sensor and again adding sensor and pulling the plug of homey and resetting z-wave the results stay the same.
there is no-way i see changes.

It is possible to make changes of settings in homey of the sensor and the changes are saved after a wake-up of the sensor.

**What was the result?**

reslut is that i can't see the temperatuur, i can't see any reaction inside homey when flood sensor is flooded or moved. The sensor itself is giving alarm and lightsignals when flooded or moved.

...

**What did you expect as result?**

see temperatuur, flood and movement indications and after making flows that these can be triggered 

...

**Any other remarks**

this is how is showes after adding sensor en howe it stays.
Also after a waiting time of 24 hours.
![flood sensor z-wave plus](https://cloud.githubusercontent.com/assets/19786633/20037537/8c5eb8a4-a421-11e6-9c9c-44e71de633a8.JPG)

...

**Comment by glijie** [comment]
problem after latest firmware updates still there.

**Comment by glijie** [comment]
Guys i see that there was a new update of the fibaro app. I think we are almost there.
Now i only see the temperature changing, The moving alarm and flooding are not changing so still noway to make a flooding flow.

**Comment by glijie** [comment]
after update  fibaro app still only temperatuur works.
i have the feeling that i'm talking to myself :-/

**Comment by RobinBol** [comment]
Sorry, there are multiple of these issues, this one slipped through. Homey v1.0.4 will likely fix your issue (after re-pair), as many others on the experimental channel with similar issues have reported.

**Comment by glijie** [comment]
updated homey to v1.0.4 and did  re-pair the flood senor zwave + and waked up the sensor and i see only temp. changes. even when i threw te sensor in water.  No readings of tamper alarm and flooding.

**Comment by RobinBol** [comment]
Strange, will look at it first thing coming monday.

**Comment by glijie** [comment]
okay have the same with a new wall-plug i got today also z-wave +  I can turn it on and off remotly but no  reading also and also when i turn it off locally this is not shown in homey... it stays on. Do i have to make a new issue of this?

**Comment by RobinBol** [comment]
Thanks for reporting, found the issue and fixed it: https://github.com/athombv/com.fibaro/commit/a9d2ca980157cb5ce084ad4412b92cf74a5a5e05, will be updated in the app store shortly. If you encounter any further issues please let us know!

**Comment by glijie** [comment]
just want to say thx!!!!! it works great
