### ISSUE TITLE
iOS beta app 1.3 build 30 Home detection

### ISSUE THREAD

**Issue by Jovink** [athombv/homey#1057]
**What is your Homey version (Settings → System)?**

0.10.9
iOS beta 1.3 build 30

Home detection doesn't work automatically. 
Because I don't know where to post I do it here ;)

The radius is set on 150m. I was much further away but no it wasn't 
Trigger the flow that I have made. 

When i set the slide to 100 when I was away homey triggered the flow.

When I was home I turned on my wifi then homey triggered the I am home flow. 

Maybe it is an idea to create a log (ifttt to google docs) so we can see  when I  leave or enter the house. Because it isn't working with "insights"

**Comment by JPe2** [comment]
You better place this on:  https://forum.athom.com/discussion/comment/36470/#Comment_36470
more people will read it there
