### ISSUE TITLE
'Activeer een flow' card is used twice

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#1059]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

I was testing the new functionality to trigger a flow from another flow.

**What was the result?**

I noticed there are now 2 cards with 'Activeer een flow' (haven't tested it in English).
One card has an info icon, this is the card to really trigger (start/run/...) another flow.
The card without the info icon is to enable another flow (so to set the checkmark in from of a flow)

**What did you expect as result?**

Different naming for both cards

**Any other remarks**

It works and you can see the difference because of the info icon, but this is confusing.

**Comment by WeeJeWel** [comment]
Fixed in 0.11.0!
