### ISSUE TITLE
Please a 'How to instruction to change loudspeaker volume or better embed in user interface

### ISSUE THREAD

**Issue by pkonings** [athombv/homey#106]
I guess lot of people would like a volume control.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18

![screen shot 2016-02-11 at 15 30 35](https://cloud.githubusercontent.com/assets/319873/12978960/6867f72e-d0d4-11e5-98eb-05e1e5ab3d72.png)

**Comment by pkonings** [comment]
How can I force to move to 0.8.18 without a tick in the experimental box update?

**Comment by WeeJeWel** [comment]
It's not released yet :-)

**Comment by AndreSomers** [comment]
Is this a setting or something you put into a flow?

**Comment by hschenkelaars** [comment]
when will 0.8.18 be released ?

**Comment by irritanterik** [comment]
Please close issues after release and label versions.

**Comment by AndreSomers** [comment]
> when will 0.8.18 be released ?
Indeed. If you close issues with "in <someVersion>", it would be nice to have that version available.
