### ISSUE TITLE
push message device selection missing correct devices

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1060]
**What is your Homey version (Settings → System)?**
0.10.9
Homey android app 2.2.7 - Build 55

**What did you try to achieve?**
Send a push message to my device.

**What was the result?**
I cannot select my Android device. I do have 5 old devices in the list. However, I do not know how to add my current android device to the list. (did some rom updates and thus changed Device ID several times)

**What did you expect as result?**
Option to select my current device

**Any other remarks**
Some info on how to remove (or add) devices which can receive push messages would be appreciated.

**Comment by WeeJeWel** [comment]
Try removing your old devices here: https://my.athom.com/#/phones
Add your new device by logging out & in on your phone in the Homey app.

**Comment by cjvs** [comment]
Super! That works. Was not aware of the menu yet. Deleted all the old phones and added the new one by logging in and out.

Now only if my push messages would actually arrive... (which they don't).

Anyways, I am confident this will also get resolved over time as the app gets more attention. Keep up the good work!
