### ISSUE TITLE
[INSIGHTS]  Null error only appears while live following a graph keeping page open

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1061]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

watch the temperature course live in graph

*Please include detailed steps how we can reproduce the issue*

open a graph in insights which is correct  , keep watching , the new results gives a null error line what disappears refreshing the graph page again.

**What was the result?**

...

**What did you expect as result?**

keep watching 

![null1](https://cloud.githubusercontent.com/assets/7040452/20207895/affa878a-a7ea-11e6-81ca-a3ca544283ae.PNG)

after refreshing
![null2](https://cloud.githubusercontent.com/assets/7040452/20207900/b73e80fa-a7ea-11e6-807a-be8113cb91ff.PNG)

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Should be fixed :)

**Comment by nattlip** [comment]
is still alive in 1.0.1

**Comment by nattlip** [comment]
Is still alive in 0.10.4.  it is a pity because insights when it was working correctly and when the data could be accessible by api , a lot of  industrial companies here in the oil and chemical industries could use Homey for transferring data from all kind of locations to  their main servers. An example is the thunder and lightning registration fanatics all over the world who use Homeseer 3 for  transferring all their local data to the global registration  of thunder and lighting all over the world on their servers.

**Comment by WeeJeWel** [comment]
I'll look into it. Which data source are you watching?

**Comment by nattlip** [comment]
temp from weather underground and oregon scientific thermometers, doesnt matter if data come from weather underground or oregon.
![temp3](https://cloud.githubusercontent.com/assets/7040452/21286750/914a332e-c45c-11e6-919e-87185d03927a.PNG)
![temp2](https://cloud.githubusercontent.com/assets/7040452/21286751/955a62d6-c45c-11e6-95c2-0a41c0f722a1.PNG)

**Comment by WeeJeWel** [comment]
OK thx!

**Comment by WeeJeWel** [comment]
This seems to be a bug in our charting library. We're going to replace the library with the 'Better Insights' update, so then it'll be fixed automatically.

**Comment by nattlip** [comment]
i havent seen it for a time now i think with 1.5.0. somewhere it disappeared.
