### ISSUE TITLE
Unable to add Z-Wave devices

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#1063]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

I tried to add any z-wave device, clicked the type/model and then a blank screen. 

![error](https://cloud.githubusercontent.com/assets/18025163/20236803/1083de7c-a8c1-11e6-8488-f2e9297a71f4.PNG)
![zwave](https://cloud.githubusercontent.com/assets/18025163/20236805/15c2b822-a8c1-11e6-8c4b-de51baeaede3.PNG)

Steps i made:
- Reboot
- PTP
- Cleared Cache
- Updated Chrome

Had contact with Jeroen Vollenbrock, he gave me a url xxxx.homey.athom.com via that way it works perfectly. 

Version of Chrome 54.0.2840.99 m
Log send 45A8B2BDC3

*Please include detailed steps how we can reproduce the issue*
Log send 45A8B2BDC3

**What was the result?**
Not able to add any z-wave device.

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Do you have a firewall running that might prevent local socket connections? Try disabling that!

**Comment by WeeJeWel** [comment]
Using a proxy server could also be the cause of this happening.

**Comment by mike9011** [comment]
I can confirm it's blocked by Avecto.  It's installed with a GPO on my company laptop.
You can close the ticket! :+1:
