### ISSUE TITLE
Motion sensors (Smartwares and kaku) wont go off (again)

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1064]
Motion sensors wont go off again, My sensors send the off signal after 5 sec's but Homey keeps it on and never defect motion anymore. I'm having this problem with Smartwares motion detection but on slack I see a lot of people having this problem with both Smartwares and kaku motion detectors. I'm on 0.10.9 now.

It was fixed 2 times before but its back again. Seems to be a re-occuring thing.

Athom please fix!! Maybe posible to add a default time to force go off if off signal was not received (for example after 10 sec). Think this Will solve it once and for all...

**Comment by Anamatronic** [comment]
Homey Firmware Versie: 0.10.9
Sensor: AWST-6000
Bug: Sensors signal for motion is detected but after set time they are also will no go off in homey

**Comment by Phunkay** [comment]
I have a similar (but in my opinion) not related issue. The status of my sensors (a AMST-606 door sensor and APIR-2150 motion sensor) sometimes works flawlessly and sometimes I don't get any status back at all. They are only a couple meters away from Homey, though there is a concrete floor in between. As it sometimes works I have always contributed it to poor reception or interference. When I reboot my Homey the sensors are always off, so it looks like it simply doesn't receive the status. To test the sensors I have made some flows that send a notification to my phone when the status changes. Some moments I get every single status change, sometimes none....

**Comment by timk1990** [comment]
My kaku sensor doesn't work either. But in my case the detection was always on. Even after a reboot. 
I thought the batterys where empty and the device was Just sending signals. So i pulled the batterys out of the device. I had no new ones at that time so i forgot about it. But is still detects movement. Even after reboot.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Phunkay** [comment]
Jeroen, here it very much seems like a reception (noise?) issue. Sometimes Homey receives the sensors' status perfectly and then other times it gets the open or motion status but never changes back. Been tracking the status for quite some time now by sending push notifications to my phone on every status change. Don't find any outside cause or consistency in it....

**Comment by jeroenvollenbrock** [comment]
Did 1.2.2 resolve this issue?

**Comment by jeroenbos22** [comment]
Yes, I dont have the issue anymore
