### ISSUE TITLE
Flow dragging

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1065]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

Drag a flow to a new position.

**What was the result?**

The 'drop zone' was well below where I was holding the flow and I couldn't move it to the first position in the folder.

![image](https://cloud.githubusercontent.com/assets/22442908/20248687/5781c4fa-a9e9-11e6-9ec3-31950496414e.png)

**What did you expect as result?**

That the flow drops wherever you release it.

**Any other remarks**

...

**Comment by corvdniet** [comment]
Same here. Not always possible to drop the flow where you want it to be.

**Comment by acefed** [comment]
Issue confirmed for Windows10 Pro 64bit EN + Homey desktop app v.1.0.3.

Good job on the screenshot mr. @Phunkay. Adding your OS as wellvwould give Athom a chance to reproduce and fix this issue.

**Comment by WeeJeWel** [comment]
Fixed in 1.3.0
