### ISSUE TITLE
Philips Hue App crashes

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1068]
**What is your Homey version (Settings → System)?**

0.10.9
Hue app 2.0.1

**What did you try to achieve?**
Turning on and off hue lights with a flow (voice) 

*Please include detailed steps how we can reproduce the issue*
Make a flow which responce on a word and turn on the light.
Make a flow which responce on a word and turn off the light.

**What was the result?**

Lights go in the first flow, than the second flow does not go well and the hue app is crashed..

**What did you expect as result?**

turn on off hue lamps with no problems.

**Any other remarks**
Crashlog hue app

Stack trace:

TypeError: Cannot read property 'toLowerCase' of undefined
at App.getBridge (/app.js:80:33)
at App._onFlowActionAllOff (/app.js:165:21)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:211
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

Exit code: 1

**Comment by WeeJeWel** [comment]
Fixed in nl.philips.hue@2.0.2 :)
