### ISSUE TITLE
Unable to control devices outside LAN

### ISSUE THREAD

**Issue by elgenioNL** [athombv/homey#107]
through my.athom.com the device is displayed in the correct zone but clicking on the "settings" icon that opens the card it keeps stop at a loading wheel. 
Same behavior in the Android App.

when i go to the ip address of homey i can see the devices and also control them.

no errors in console.

![homey](https://cloud.githubusercontent.com/assets/16634297/12979938/58ad1d54-d0da-11e5-95c2-8f84ccb579e9.png)

**Comment by WeeJeWel** [comment]
Can you post a screenshot of your console while running this?

**Comment by elgenioNL** [comment]
![image](https://cloud.githubusercontent.com/assets/16634297/12994752/08dbaebe-d123-11e5-8c1f-3e59d949f3bb.png)

It's working at the moment, but really slow (4,5 seconds).

**Comment by WeeJeWel** [comment]
Roger. This will be made a lot faster in the future, but the issue is resolved.
