### ISSUE TITLE
AEOTEC Multisensor Gen 5 Model ZW074-C is not supported

### ISSUE THREAD

**Issue by Anamatronic** [athombv/homey#1070]
Aeotec v1.1.1 app
Homey Firmware Versie: 0.10.9

**What did you try to achieve?**

Pare AEOTEC Multisensor Gen 5 Model ZW074-C with homey

**What was the result?**

Will not pair!

**What did you expect as result?**

That Homey can 'talk' with it :)

**Any other remarks**

Seems that more people want this, https://apps.athom.com/app/com.aeotec

**Comment by caseda** [comment]
Actually, now looking in the app-store on this app, and you are the only 1 wanting
Multi Sensor 4-in-1 Gen 5 (ZW074).

the rest is
Multi Sensor 6 Gen 5 (ZW100, all old post, already supported)

But nonetheless, think it will get supported fast enough.

**Comment by caseda** [comment]
Driver is awaiting approval for getting in the app, no clue when it will be added, but it think/hope pretty soon for you

**Comment by RobinBol** [comment]
@Anamatronic caseda added support for this device, however it seems we can not buy the device anymore, and I am quite opposed to pushing this driver to the app store without it being tested first. If you manage to pull the app from caseda from this branch: https://github.com/caseda/com.aeotec/tree/zw074 and test it thoroughly then I will merge his PR and publish the driver, do you think you can manage this?

**Comment by RobinBol** [comment]
Support for this device has been added.
