### ISSUE TITLE
Sun 500 (kaku)

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey#1071]
**What is your Homey version (Settings → System)?**
0.10.9

**What did you try to achieve?**
Use Sun-500 for opening roller-shutters

*Please include detailed steps how we can reproduce the issue*
The sun500 has 2 wheels to set the frequentie of the unit. Not all frequenties seem to work.
And working frequenties on 1 unit do not seem to work on other units. 

**What was the result?**
Not all frequenties work, so roller-shutter stays closed
...

**What did you expect as result?**
Roller shutters opening and closing
...

**Any other remarks**

...

**Comment by BasKiers** [comment]
Hi,

Thank you for your bug report! I've fixed the code wheels and tested it with the SUN-500 and now all codes should work. This issue is fixed in v2.7.1 of the kaku app.

Regards,
Bas
