### ISSUE TITLE
Checksum error on first Homey update attempt.

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey#1072]
**What is your Homey version (Settings → System)?**

0.10.9

**What did you try to achieve?**

Click the update button in settings to update.

**What was the result?**

It started downloading the update and after less than a minute a "checksum invalid" error popped up. Second time worked without a problem.

**What did you expect as result?**

That it would update without a problem the first time.

**Any other remarks**

None

**Comment by Inversion-NL** [comment]
I believe it was reported on Slack and is fixed in next firmware update.

**Comment by DieterKoblenz** [comment]
I know ;) I reported it there as well

**Comment by DieterKoblenz** [comment]
Updating from 1.0.0RC to 1.0.0 resulted in invalid_checksum

**Comment by corvdniet** [comment]
+1

**Comment by Dijker** [comment]
Same here, 
from 0.10.9 to 1.0.1
Download took long (couple of minutes?)
invalid _checksum

![image](https://cloud.githubusercontent.com/assets/12412734/20443739/6220873c-adce-11e6-8eae-a268d1020c66.png)

Second attempt... It Works!!

**Comment by WeeJeWel** [comment]
Fixed in Homey v1.0.3.
