### ISSUE TITLE
Memory Graph miss calculation / displaying wrong graph

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#1073]
**What is your Homey version (Settings → System)?**

1.0.0-rc.1.

**What did you try to achieve?**

To display the app memory in use

*Please include detailed steps how we can reproduce the issue*

System info - > Memory graph

**What was the result?**

Other (1.07 GB)

See screenshot : 
![hombug](https://cloud.githubusercontent.com/assets/17739535/20350385/0317b50a-ac0f-11e6-920f-255f3a679086.JPG)

**What did you expect as result?**

Correct values and not just a grey system memory usage bar
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Hi Marco, thank you for reporting this issue. We have found a bug in the way Homey calculates the size of "other", and resolved this in the final 1.0.0 version.
