### ISSUE TITLE
iOS app crash 

### ISSUE THREAD

**Issue by Tvandongen** [athombv/homey#1074]
**What is your Homey version (Settings → System)?**
Homey 0.10.9
iOS version 9.3.5 iPhone 4S
Homey app 1.3.0

**What did you try to achieve?**
Start the new released app version 1.3

*Please include detailed steps how we can reproduce the issue*
Start the app on iPhone 4S with iOS version 9.3.5

**What was the result?**
App crash

**What did you expect as result?**
The app should start

**Any other remarks**
on iPad 2 with same iOS version 9.3.5 the app is starting normal
2 small notes:
- Most of the times the devices in a room are not shown
- if the devices are shown, there is no description

I have mailed some app crash logging to support@athom.com with a reference to this issue

**Comment by jeroenvollenbrock** [comment]
Homey version 1.0.1 resolves the issues that you mention regarding device cards. I'll ask our support staff to send you an iOS beta invite, so you can get your hands on the next release of the app more quickly.

**Comment by Tvandongen** [comment]
@jeroenvollenbrock 
I assume you mean version 1.0.2, because I am running 1.0.1 at the moment with the same issues as version  0.10.9

**Comment by Tvandongen** [comment]
Issue could be closed (after releasing new iOS app version)
- App crash is solved in app version 1.3.1. build 57
- Showing devices is solved in Homey version 1.0.4
