### ISSUE TITLE
[Homey Desktop App Windows]

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1075]
**What is your Homey version (Settings → System)?**

0.1.0

**What did you try to achieve?**

reinstall plugwise source after update homey firmware

*Please include detailed steps how we can reproduce the issue*

install an app with an app settings page

**What was the result?**

the app settings menu item on the left doesn't appear after installing the app, it has to be refreshed by going to the devices menu item page and back to settingspage,v the homey desktop app doesn't has an refresh button like chrome. it is hidden in the menu. without manually refreshing the page

...

**What did you expect as result?**

that the menu item settingspage of the installed app appared on the left menu of the settingspage
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
@nattlip Does this still occur?

**Comment by nattlip** [comment]
no ,
