### ISSUE TITLE
Repeatedly sending signals crashes 433

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#1076]
**What is your Homey version (Settings → System)?**

1.0.1 (and earlier versions)

**What did you try to achieve?**

Repeatedly send a signal on 433.

```signal = new HomeySignal('Mertik');
var count = 25;
timer = setInterval(function() {
		signal.tx([ 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0], Homey.log);
		count--;
		if (count == 0) {
			clearInterval(timer);
		}
	}, 150);
```
and
```	"signals": {
		"433": {
			"Mertik": {
				"sof": [ 320, 400 ],
				"eof": [],
				"words": [
					[ 800, 360 ],
					[ 450, 710 ]
				],
				"interval": 18000,
				"repetitions": 10,
				"sensitivity": 0.9,
				"minimalLength": 12,
				"maximalLength": 12
			}
		}
```

**What was the result?**

No more signals could be sent or received on 433. Needed to reboot Homey (restarting the micro controller did not help).

**What did you expect as result?**

433 continues to operate.

**Any other remarks**

It would be much nicer if the number of tx repetitions would be part of the send function instead of the json!

**Comment by nattlip** [comment]
it would be much nicer if the whole signal definition returned to the app iso the json. for testing which is the best signal definition , it would be a lot easier to get the best signal definiton

**Comment by jeroenvollenbrock** [comment]
@nattlip Unfortunately, this is not possible due to the way signals are registered with the driver.

@nlrb Can you please let me know whether this issue persists or not?

**Comment by nlrb** [comment]
@jeroenvollenbrock No, I cannot reproduce it anymore. Will close the issue.
