### ISSUE TITLE
Homey stating he is beta after asking (in version 1.0.1)

### ISSUE THREAD

**Issue by yellowmousy** [athombv/homey#1077]
**What is your Homey version (Settings → System)?**

1.0.1
Dutch

**What did you try to achieve?**
Ask Homey what version he is running in Dutch: "Ok Homey, welke versie ben jij?"

*Please include detailed steps how we can reproduce the issue*
Ask Homey version in Dutch (not tested in English)

**What was the result?**
Homey saying he is Beta:
"Momenteel heb ik software versie 1.0.1, denk ik. Maar ik kan me vergissen want dit is wel beta software"

**What did you expect as result?**
"Momenteel heb ik software versie 1.0.1. No more Beta"

**Any other remarks**
Thanks for the new version. Keep up the good work!

**Comment by Dijker** [comment]
Look like this isn't an issue on English ;-) but nice  sharp in finding this minor bug....

**Comment by Phunkay** [comment]
Doesn't say it's beta here in dutch. Remote fix?

**Comment by yellowmousy** [comment]
Just tested it again. Still says: "_Momenteel heb ik software versie 1.0.1, denk ik. Maar ik kan me vergissen want dit is wel beta software_".

Maybe it is fixed in newly downloaded updates? The settings menu reports that there are no newer versions.

**Comment by WeeJeWel** [comment]
Do you have experimental updates enabled? If so, then this will occur :)

**Comment by yellowmousy** [comment]
No, never subscribed to experimental updates. 
I did force the 1.0.1 update by disabling automatic updates and push the button to search for new updates (_Zoek naar updates_). Couldn't wait for automatic update :)
System information says: "Homey Firmware Versie: 1.0.1"

Never used experimental updates.

**Comment by WeeJeWel** [comment]
I've found the issue and fixed it :-)
