### ISSUE TITLE
[Insights] Hover-over values don't work after loading template

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1078]
**What is your Homey version (Settings → System)?**
1.0.1 / Homey Desktop App for Windows 1.0.1

**What did you try to achieve?**
View Insights

*Please include detailed steps how we can reproduce the issue*
Open a saved Template

**What was the result?**
Hove-over didn't work until I toggled one measurement in the left bar.
after that it functioned normal. (See picture WITH Hove-over working!)
![image](https://cloud.githubusercontent.com/assets/12412734/20446600/cc6d655e-adda-11e6-8070-5d466ac9dc5b.png)

**What did you expect as result?**
Hove-over to work direct after loading Insights. 

**Any other remarks**
Same in Chrome on Windows, didn't see this behavior before 1.0.1

**Comment by mirakels** [comment]
would be nice if hovering-over not only show the metric name and value, but also the time stamp of the measurement

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue. Please let me know if it persists.

**Comment by Dijker** [comment]
Can't reproduce anymore.... but even then with the new Mobile App coming ;-)
