### ISSUE TITLE
Mobile card scrollbar too short

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1079]
**What is your Homey version (Settings → System)?**
1.0.1

**What did you try to achieve?**
Look at mobile card with a set Temperature and 2 sensors

**Please include detailed steps how we can reproduce the issue**
Look at a mobile card with 2 sensors and a set temperature (for example Nest Thermostat)

**What was the result?**
![screenie](https://cloud.githubusercontent.com/assets/2565450/20447473/50823f5a-addf-11e6-952e-64fdd9757c74.jpg)
It's a very cute scrollbar, but not even needed.
But even if it was, it's a little bit too small

**Comment by Phunkay** [comment]
Same issue in the Homey Desktop App.

**Comment by WeeJeWel** [comment]
This is fixed in 1.0.4
