### ISSUE TITLE
Homey.manager( 'insights' ).createLog CALLBACK never called

### ISSUE THREAD

**Issue by coldshivery** [athombv/homey#108]
After creating a log for insights the callback never gets called it seems.
But if i call .getLogs i will see my created log returned. So creation works, but the callback does not.
```
Homey.manager( 'insights' ).createLog( 'mylog' , {'en':'mylog'} , 'metric' , function callback(err , success){ console.log('never called')});
```
In this example code snippet the log message will never appear in the CLI debug console.

**Comment by WeeJeWel** [comment]
Oops, the documentation was outdated for that function.

The 4th parameter should be 'number' (or 'string' or 'boolean'). The docs have been updated!
