### ISSUE TITLE
[upgrade] Time one hour off after upgrade to 1.0.1 from 0.10.9

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1081]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**
Checked date_human at settings

*Please include detailed steps how we can reproduce the issue*
Upgaded yesterday from 0.10.9 to 1.0.1 and now I checked the time.

**What was the result?**
Time (date_human ) was 1 hour behind, 
![image](https://cloud.githubusercontent.com/assets/12412734/20455217/eb1a0436-ae56-11e6-92df-87ab3076eafd.png)

**What did you expect as result?**
Time to be correct

**Any other remarks**
My location was manual set before te upgrade, 
I moved my Location a couple of meters, 
Now my time is correct....
just to inform to fix for next upgrades ;-)

**Comment by corvdniet** [comment]
Thank you Dijker. "_I moved my Location a couple of meters,_" worked for me as well.

**Comment by Tweaqer** [comment]
+1 for this issue

**Comment by KrielkipNL** [comment]
+1 issue too here (found it out that my lights went on & off one hour late ;))

**Comment by bvdbos** [comment]
I think everybody had this but this was a one-time event? Athom, did you find the cause and can you prevent this from happening again?

**Comment by jghaanstra** [comment]
This might be related to: https://github.com/PatrickSannes/BetterLogic/issues/6

BetterLogic app displays UTC time as lastChanged date for variables since Homey firmware 1.0.1

**Comment by Dijker** [comment]
@WeeJeWel 
Did you find and fix something?
Didn't have this problem upgrading to 1.0.2 and 1.0.3 so guess it was  a problem for for once and is fixed?

**Comment by Dijker** [comment]
Upgrade to 1.0.4 worked fine, will close it!
