### ISSUE TITLE
Wifi setup minor errors / bug

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1083]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**
Setup wifi (which dit work...)

**What was the result?**
typo: dutch selected, some english in between
![screen shot 2016-11-19 at 20 02 54](https://cloud.githubusercontent.com/assets/18570823/20457817/c7d92dca-ae93-11e6-9ba9-6d35a6ac8000.png)

followed by error text in steps thereafter:
![screen shot 2016-11-19 at 20 03 26](https://cloud.githubusercontent.com/assets/18570823/20457821/e82bda82-ae93-11e6-9fd4-af89e3fbb2ae.png)

Homey did connect... so that was OK

**What did you expect as result?**
spell check was done :)

**Any other remarks**
none

**Comment by WeeJeWel** [comment]
Fixed!
