### ISSUE TITLE
cannot pair fibaro FGK-10x, Door/Window Sensor (Z-Wave Plus)

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1084]
**What is your Homey version (Settings → System)?**
1.0.1

**What did you try to achieve?**
Pair a FGK-10x, Door/Window Sensor (Z-Wave Plus)with Homey

**What was the result?**
Sensor could not be connected. It is not found during the pairing process

**What did you expect as result?**
Sensor pair

**Any other remarks**
Did a full reset (including data wipe), installed the fibaro app (noting else yet), tried to pair the sensor... :(

The sensor was able to be paired in the previous version 0.10.9

**Comment by caseda** [comment]
Did you reset the sensor as well? Either from within homey (Homey 's settings -> Z-wave -> [remove device]) 
Or with within the sensor itself (look that up in the manual)

**Comment by cjvs** [comment]
Yes, Both... Removing was not possible from the device itself (three clicks). So removed from z-wave menu. Which could not find any devices. Then reset sensor (multiple times). Then reset Z-wave to factory settings, and finally fully reset homey and sensors.... After a fresh install it could not find the sensors either...

**Comment by cjvs** [comment]
Guess some sleep did homey well... Removed the device again this morning from the z-wave menu. and this did result in it being removed. Subsequently I could reconnect it again
