### ISSUE TITLE
[Enhancement] More filters for flow cards

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#1086]
Flow cards have a filter option since the beginning. As far as the documentation tells us, it's only possible to use this filter: driver_id=my_driver. To support devices with dynamic capabilities in a driver, it would be nice if more filter are supported.

I suggest to filter based on a device setting or something from it's 'data' object.

**Comment by caseda** [comment]
there is one more filter that i know off:
`capabilities=`
it's used in the HUE app
but would be awesome to have more options indeed

**Comment by WeeJeWel** [comment]
What filters would you need? There are already many available, yet
undocumented

**Comment by Joolee** [comment]
Well, documenting the ones available would be a start...

**Comment by WeeJeWel** [comment]
Well, documenting them means freezing them, which I rather don't do unless there's a use case. Please provide what you need :)

**Comment by caseda** [comment]
the one i was really looking for is one that is setting reliant.

if this setting is value = 1, only those corresponding flow cards show up

Example, Switch Type = Toggle, only toggle switch scene cards can be used

**Comment by Joolee** [comment]
The app I'm writing with Mark Swift will have some flow cards depending on the devices firmware version/support. So creating two different drivers isn't practical. A filter to be able to use a setting would be acceptable. Also, I don't think it would be a problem to freeze that possibility by documenting it.

**Comment by WeeJeWel** [comment]
I've thought about it, but filters based on settings won't happen. This would be very confusing to the user, because after checking a checkbox their Flow's can go broken.

Other filter requests are of course welcome :)
