### ISSUE TITLE
Windows application is stuck after reboot of Homey

### ISSUE THREAD

**Issue by WimHe** [athombv/homey#1089]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

Switch between English and Dutch and vise versa

*Please include detailed steps how we can reproduce the issue*
Using the Windows desktop application 
Switch to the other language
Homey Reboots

**What was the result?**
The Desktop shows it is rebooting Homey, Homey is rebooted correctly but the desktop app is stuck showing the reboot is still in progress.

**What did you expect as result?**

The desktop would show the startup screen after Homey is successfully rebooted.

**Any other remarks**
Windows version is WIndows 10 Home fully up to date.

**Comment by bvdbos** [comment]
If you use the browser the same happens for some reason but that's no problem as you can refresh the page...

**Comment by WeeJeWel** [comment]
I'll look into it. As a workaround, use View -> Reload

**Comment by WeeJeWel** [comment]
Fixed in 1.0.2
