### ISSUE TITLE
[Windows App] Tags can't be dragged 

### ISSUE THREAD

**Issue by SailingDuck** [athombv/homey#1090]
**What is your Homey version (Settings → System)?**

1.0.1 + Windows app

**What did you try to achieve?**

Tried using the tags like date/time in other cards

*Please include detailed steps how we can reproduce the issue*

Create new flow
Add Datetime card in first column
Add Logic card to second (and) column
Try to drag logic tag date or time

**What was the result?**

Tag is turning based on the mouse over but not dragged

**What did you expect as result?**

Tags can be dragged

**Any other remarks**

This is working on my.athom.com and Google Chrome 54.0.2840.99 m (Windows)

**Comment by WeeJeWel** [comment]
Which version of Windows are you running?

**Comment by SailingDuck** [comment]
Windows 10

**Comment by WeeJeWel** [comment]
I can't seem to reproduce the issue using Windows 10 & Homey Desktop 1.0.1. Do you maybe have an exotic mouse/touchpad or so?

It would help greatly if you could record a video of the issue happening.

**Comment by Inversion-NL** [comment]
I'm also unable to reproduce.
Also using Windows 10 and Homey app v1.0.1 and when I create a new flow and drag the date or time tag to the phone action card all is working like intended.

**Comment by SailingDuck** [comment]
@WeeJeWel I was using a touchpad, retried with a mouse tonight but still no luck.

Is it possible it is screen size related? I have a Surface Pro 4 which has everything scaled to 200% (2736*1824). I seem to be able to drag one label sometimes after I minimize and maximize the homey app.

**Comment by Dijker** [comment]
@WeeJeWel , @SailingDuck 

Reluctant as I am, I still use the Chrome Browser daily!

On my Surface Pro 4 with Windows 10 (1607) I use most of the time a external Screen (Full HD, normal 100%)  on both screens this works OK for me. 

In response to your suggestion: YES in the Homey APP this is undoubted a problem that occurs on a Scaled HD screen. Trying to pick up the TAG and put it in a box is working in Chrome 5 out of 5 times for me. Tried that on both screens in the Homey App more then 10 times. The Tag "Wiggles" hovering over it but cant be picked up....  0 times success! Both with the App on the Full HD on 100%  or the approx ~QWXGA+~ on 175% This doesn't work. 

Setting the ~QWXGA+~ as primary screen scaled to 100%, putting on my glasses, Starting the Homey App again I Tried and this worked as expected again. It works then on both screens.

**Comment by chrisboer** [comment]
I have the same issue with the Homey App on Windows 10, I can reproduce it with both my touchpad as well as my mouse.
So cannot drag the TAG towards a speech box of Homey for instance the temperature TEMP tag towards the action Homey to tell me what the temperature is.

**Comment by WeeJeWel** [comment]
@TheMSB Can you investigate? When I try it scaled (175%) in Windows 10, tags dragging do work but it looks horrible:

![screen shot 2016-12-27 at 16 16 12](https://cloud.githubusercontent.com/assets/319873/21502426/e63bb4a2-cc4f-11e6-8edf-fbdb22932cb5.png)

@chrisboer @Dijker Do you both have a high-res screen? Say '2x' resolution, e.g. 3840x2160?

**Comment by chrisboer** [comment]
Yes I have a 4k screen indeed, 3200x1800 but I now use a bypass by pressing F11 in the desktop app, still same format but I can drag and drop the tags.

**Comment by carel** [comment]
I have the same issue (can not drag/drop tags) on a 4K Dell XPS-15 screen (Windows 10, 200% scaled).
F11 works for one drag, but has to be pressed again for every drag/drop.

**Comment by chrisboer** [comment]
Issue is now resolved when you have your desktop app in full screen mode no issues anymore with drag and drop tags

**Comment by TheMSB** [comment]
@chrisboer Could you be so kind as to let me know if you still experience these issues with Homey Desktop 1.0.3?

**Comment by Dijker** [comment]
Almost never use the app, only Chrome on Surface Pro 4 with Windows 10 (1607) with High Res Screen 175 %  and classic monitor at 100%.  

Just started the App 1.0.2 app, 
- not-full-screen, opened Flow - Reproduced the problem.  
- Changed to Full-screen  - No problem, 
- Changed to not-full-screen, No Problem.
- re-opened the same flow not-full-screen, - Reproduced the problem.  

Restarted to update to 1.0.3
- not-fullscreen, opened Flow - No Problem !!! 

This one looks fixed, Thanks!!

**Comment by TheMSB** [comment]
@Dijker glad to be of service!

**Comment by chrisboer** [comment]
Works indeed, thanks that is a lot of keypressing F11 I don't have to use anymore....
