### ISSUE TITLE
RROD after updating to stable

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1091]
**What is your Homey version (Settings → System)?**
I came from all previous experimental firmware and am still on that channel. Homey auto updated to v1.0.1

**What did you try to achieve?**
Well, not much. I have woken up twice to see Homey have a RROD. A PTP solves the issue

*Please include detailed steps how we can reproduce the issue*
No idea. I came from the latest experimental and am now on the latest firmware. After the auto update, nothing was altered in Homey; no new Apps of Flows. 

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**
Hoemy has never given me a RROD. This is completely new.
...

**Comment by bvdbos** [comment]
updating should be withour RROD's or PROUD's now...

**Comment by WeeJeWel** [comment]
Should be fixed!
