### ISSUE TITLE
[Windows App] have to login homey athom github and slack in app

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1092]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

login the links in the homey app under help   

*Please include detailed steps how we can reproduce the issue*

i didnt expet to login AGAIN at ll the athom websites 

**What was the result?**

have to enter all the credentials for all lwebsites, i know enough websites which have automated  login  links to all links

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by joachimroeleveld** [comment]
Unfortunately we don't have any influence on how Github and Slack implement their login systems.
