### ISSUE TITLE
Can't scroll in devices screen

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1096]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

Added multiple devices and now with the 29th device, i've come to the conclusion that it is impossible to scroll over the devices page (Homey App and Google Chrome). Therefore I can't read the information from the device starting from device 29.

![schermafbeelding 2016-11-22 om 22 21 47](https://cloud.githubusercontent.com/assets/17526110/20542721/24c2746c-b103-11e6-82c3-f3e5d65f6b46.png)

**What was the result?**

Scrolling not possible

**What did you expect as result?**

Scrolling

**Comment by djeskoswe** [comment]
Off-topic: how did you get the binary sensor to work?   From what git repo?  Thanks

**Comment by Arjanvde** [comment]
@djeskoswe 

From the wizzard: https://github.com/caseda/com.fibaro/tree/fgbs 

Not sure if the flow cards do work.

**Comment by bvdbos** [comment]
Is this fixed?

**Comment by Arjanvde** [comment]
Nope, still active.

**Comment by WeeJeWel** [comment]
Closing for now as this will be solved in the new Homey Smartphone App.
