### ISSUE TITLE
capabilitiesOptions not working

### ISSUE THREAD

**Issue by ajterpstra** [athombv/homey#1098]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

Try with capabilitiesOptions to create a title

*Please include detailed steps how we can reproduce the issue*

App.json

> {
>    "id": "com.benext",
>   "name": {
>     "en": "BeNext",
>     "nl": "BeNext"
>   },
>     "description": {
> 	    "en": "Drivers for BeNext devices",
> 		"nl": "Drivers for BeNext devices"
>     },
>     "category": [ "appliances", "security" ],
>     "images": {
> 	    "large": "/assets/images/large.png",
> 	    "small": "/assets/images/small.png"
>     },	    
>     "version": "0.0.1",
>     "compatibility": ">=0.9.3",
>     "author": {
>     },
>     "drivers": [
> 	    {
> 		    "id": "p1-dongle",
> 		    "name": {
> 			    "en": "BeNext P1 Dongle",
> 				"nl": "BeNext P1 Dongle"
> 		    },
> 		    "zwave": {
>         	"manufacturerId": 138,
>          	 "productTypeId": 47,
>           		"productId": 256,
> 			    "learnmode": {
> 				    "image": "/drivers/p1-dongle/assets/wakeup.svg",
> 				    "instruction": {
>                         "en": "Press and hold the button on your BeNext P1 Dongle for three seconds",
> 						"nl": "Druk en hou de knop op de BeNext P1 Dongle vast voor drie seconden"
> 				    }
> 				},
> 			    "associationGroups": [ 1 ]
> 		    },
> 		    "class": "sensor",
> 		    "capabilities": [ 
> 		    	"measure_power",
>         		"meter_power.normal",
> 				"meter_power.low",
>         		"meter_gas"
>         	],
> 			"capabilitiesOptions": {
> 				"meter_power.normal": {
> 					"title":{
> 						"en":"Power Meter Normal",
> 						"nl":"Stroommeter normaal"
> 					}
> 				},
> 				"meter_power.low": {
> 					"title":{
> 						"en":"Power Meter low",
> 						"nl":"Stroommeter laag"
> 					}
> 				},
> 			},
> 		    "images": {
> 			    "large": "/drivers/psm02/assets/images/large.jpg",
> 			    "small": "/drivers/psm02/assets/images/small.jpg"
> 		    },
> 		    "settings": [{
> 					"id": "baud_rate",
> 					"type": "dropdown",
> 					"label": {
> 						"en": "Default Baud rate",
> 						"nl": "Standaard Baud rate"
> 					},
> 					"hint": {
> 						"en": "Kamstrup and Iskra = BAUD rate 9600   Kaifa, Landis, Gyr = BAUD rate 115200",
> 						"nl": "Kamstrup en Iskra = BAUD rate 9600   Kaifa, Landis, Gyr = BAUD rate 115200"
> 					},
> 					"value": "1152",
> 					"values": [
> 						{
> 							"id": "1152",
> 							"label": {
> 								"en": "115200 (DSMR 4.0)"
> 							}
> 						},
> 						{
> 							"id": "96",
> 							"label": {
> 								"en": "9600 (DMSR 2.2)"							}
> 						}
> 					]
> 				}
>               ]
> 	    }
>     ]
> }

Driver.js
```

'use strict';

const path = require('path');
const ZwaveDriver = require('homey-zwavedriver');

// http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/340

module.exports = new ZwaveDriver(path.basename(__dirname), {
debug: true,
    capabilities: {
        measure_power: {
                command_class: 'COMMAND_CLASS_METER',
                command_get: 'METER_GET',
                command_get_parser: function () {
                    return {
                        Properties1: {
                            'Rate Type': 'Import',
                            'Scale': 2
                        },
                        'Scale 2': 0
                    };
                },
                command_report: 'METER_REPORT',
                command_report_parser: report => {
                    if (report.hasOwnProperty('Properties2')
                    && report.Properties2.hasOwnProperty('Scale bits 10')
                    && report.Properties2['Scale bits 10'] === 2) {
                        return report['Meter Value (Parsed)'];
                    } return null;
                },
        },
		meter_power.normal: {
			multiChannelNodeId: 1,
            command_class: 'COMMAND_CLASS_METER',
            command_get: 'METER_GET',
            command_get_parser: function () {
                return {
                    Properties1: {
                        'Rate Type': 'Import',
                        'Scale': 0
                    },
                'Scale 2': 0,
                };
            },
            command_report: 'METER_REPORT',
            command_report_parser: report => {
                if (report.hasOwnProperty('Properties2')
                && report.Properties2.hasOwnProperty('Scale bits 10')
                && report.Properties2['Scale bits 10'] === 0) {
                    return report['Meter Value (Parsed)'];
                } return null;
            },
        },
        meter_power.low: {
			multiChannelNodeId: 2,
            command_class: 'COMMAND_CLASS_METER',
            command_get: 'METER_GET',
            command_get_parser: function () {
                return {
                    Properties1: {
                        'Rate Type': 'Import',
                        'Scale': 0
                    },
                'Scale 2': 0,
                };
            },
            command_report: 'METER_REPORT',
            command_report_parser: report => {
                if (report.hasOwnProperty('Properties2')
                && report.Properties2.hasOwnProperty('Scale bits 10')
                && report.Properties2['Scale bits 10'] === 0) {
                    return report['Meter Value (Parsed)'];
                } return null;
            },
        },

        meter_gas: {
            multiChannelNodeId: 3,
            command_class: 'COMMAND_CLASS_METER',
            command_get: 'METER_GET',
            command_get_parser: function () {
                return {
                    Properties1: {
                        'Rate Type': 'Import',
                        'Scale': 0,
                    },
                'Scale 2': 0
                };
            },
            command_report: 'METER_REPORT',
            command_report_parser: report => {
                if (report.hasOwnProperty('Properties2')
                && report.Properties2.hasOwnProperty('Scale bits 10')
                && report.Properties2['Scale bits 10'] === 0) {
                    return report['Meter Value (Parsed)'];
                } return null;
            },
        },
    },

    settings: {
        "baud_rate": {
            "index": 2,
            "size": 2,
        },
    }
});
```

**What was the result?**

Invalid JSON in app.json [SyntaxError: Unexpected token }]

**Comment by caseda** [comment]
there is 1 , (comma) to many in the code, between meter_power.low and images

**Comment by ajterpstra** [comment]
Oh dear, now I feel a bit silly.
It did work, I can now install the app
Then I just need to adjust the driver. apparently wants to not quite work

> Stack trace:
> 
> SyntaxError: Unexpected token .
> at exports.runInThisContext (vm.js:53:16)
> at Module._compile (module.js:373:25)
> at Object.Module._extensions..js (module.js:416:10)
> at Module.load (module.js:343:32)
> at Function.Module._load (module.js:300:12)
> at Module.require (module.js:353:17)
> at require (internal/module.js:12:17)
> at /homey-app/manager/drivers.js:74:27
> at Array.forEach (native)
> at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
> 
> Exit code: 1

**Comment by caseda** [comment]
in the driver you also need to encapsulate your capability.sub =>
`meter_power.normal` => `'meter_power.normal'`
`meter_power.low` => `'meter_power.low'`

**Comment by ajterpstra** [comment]
Yes, thank you.
everything is working again.
I found out just now even myself, could not find what was reason.

Then I do only the settings of the appartaat itself.
I expect no problems with it.

The message can be closed again
