### ISSUE TITLE
Showstopper for Flow Fibaro wall-plug switched ON >> Hue light unjustly does NOT switch on 

### ISSUE THREAD

**Issue by athomey** [athombv/homey#11]
Use case: In many places we use use Fibaro Wall Plugs as an easy-access switch to DIRECTLY switch something on, and then VeraEdge has a flow triggering on the state-change, and doing all kinds of things with Hue lights and such.

Reproduction: I added one Fibaro Wall Plug and a HUE light through the bridge and native HUE app to Homey. Both devices work well (((though UI doesn't update to reflect changes in the device, you have to re-open the pop-up with details, I reported that to Emile before I was redirected to Github, so I expect that to be fixed))). 

Bug: When I toggle the Fibaro Wall Plug, the Hue light does not get changed to on/off accordingly. This is a problem, cause in my house I have these usefull set-ups on more than one place.

**Comment by ocatie** [comment]
The capability isn't updated because no status updates from the device are received. Assign Homey's device id to association group 3 of the Fibaro door sensor after next update.

**Comment by athomey** [comment]
Will try. Thx.

**Comment by athomey** [comment]
@ocatie  I've had very little time, but trying it a bit now. When I open zwave settings, it says I can add max. 0 number of nodes to group 3. So, that is a "lie" OR I cannot follow your instructions. I will try it anyway, but you should know this.

**Comment by athomey** [comment]
@ocatie I Tried your suggestion, and now it works AND updates in the UI. Very nice. So this ticket is closed correctly. Only the cosmetic error saying "maximum 0 your can add" is a "lie" in your displayed text and to be fixed by you. :-)

**Comment by ocatie** [comment]
Thats a number that is read from your device. No hard action is taken upon this number. Maybe in the future the interface will force you to enter no more then "max_nodes_supported" node id's.
