### ISSUE TITLE
App Store Developer dashboard is not responsive

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1101]
**What is your Homey version (Settings → System)?**

None

**What did you try to achieve?**

I'm trying to publish an app to the appstore

**What was the result?**

The banner to publish an app is hidden on Smartphones

**What did you expect as result?**

Button to publish an app

**Any other remarks**

See video for responsiveness

[Developer Dashboard.mp4.zip](https://github.com/athombv/homey/files/612095/Developer.Dashboard.mp4.zip)

**Comment by WeeJeWel** [comment]
The App Store developer dashboard has not been made responsive, because it's a view where usually a desktop is required.

**Comment by WeeJeWel** [comment]
This won't be fixed. Developer Tools and App Store developer will require a desktop in the future.
