### ISSUE TITLE
Unsubscribe from experimental updates

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1102]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

Uncheck the checkbox of beta's

**What was the result?**

None, it's disables

**What did you expect as result?**

I can unsubscribe from beta's because I don't want surprises anymore now it's working ok.

**Any other remarks**

![schermafbeelding 2016-11-24 om 21 00 56](https://cloud.githubusercontent.com/assets/13370203/20609154/4f776226-b289-11e6-91d1-7de08fda6f89.png)

**Comment by WeeJeWel** [comment]
Please refer to our Support Knowledge Base: https://www.athom.com/en/support/KB000041/
