### ISSUE TITLE
Homey reports strange temperature  (The outside temperature is 32 degrees Celsius in the living room) 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1104]
**What is your Homey version (Settings → System)?**

1.0.1 English 

**What did you try to achieve?**
Ask Homey for the Temperature

*Please include detailed steps how we can reproduce the issue*
Living In Then Netherlands Utrecht, NOT Curaçao ;-)
Installed devices measuring temperatures: 
- ThermoSmart (Set = Current = ~21 grC)
- NetAtmo (Inside = ~21 grC, Module Slaapkamer ~18 gr C, Buiten ~2 grC )

Asked:
1) what s the temperature
2) what s the temperature in the living room
3) what s the temperature in the bedroom

**What was the result?**
1) The outside temperature is 1 degrees Celsius
2) The outside temperature is 32 degrees Celsius in the living room
3) In the bedroom the outside temperature is 25 degrees Celsius 

Realtime Homey logger
2016-11-25T06:50:50.368Z	SpeechOutput: speech	{"text":"The outside temperature is 1 degrees Celsius","session":"mobile8940"....
2016-11-25T06:50:46.540Z	SpeechInput: speech	{"transcript":"what s the temperature","session":"mobile8940"}

2016-11-25T06:40:38.103Z	SpeechOutput: speech	{"text":"The outside temperature is 32 degrees Celsius in the living room","session":"mobile36982","counter":2,"audio":.....
2016-11-25T06:40:35.416Z	SpeechInput: speech	{"transcript":"what s the temperature in the living room","session":"mobile36982"}

2016-11-25T08:13:07.630Z	SpeechOutput: speech	{"text":"In the bedroom the outside temperature is 25 degrees Celsius",
2016-11-25T08:13:04.035Z	SpeechInput: speech	{"transcript":"what s the temperature in the bedroom"

**What did you expect as result?**
something like: its 20 degrees in the living ???

**Any other remarks**
I used my phone to ask using the Homey App, but that shouldn't matter.

**Comment by Dijker** [comment]
I guess (Yahoo) Weather App was answering  all Q. Disabled it
Now I get an average of outside, bedroom and livingroom (not that usefull)

**Comment by Tweake** [comment]
As @Dijker said these responses were coming from the Yahoo Weather App. I have made some changes to the priority of apps and Homey's own speech functionality which should have fixed your problem. These fixes were included in Homey version 1.0.3. Thanks for reporting the issue!

**Comment by Dijker** [comment]
Robert, @Tweake 
Already better I think, but with Yahoo enabled some questions don't reach the NetAtmo App, 
Where the same Q. work perfect with Yahoo disabled. 

fe: 
Wat is de temperatuur in de slaapkamer?
Wat is de temperatuur in de tuin?

Work perfect with the two NetAtmo modules in these two Zones, 
but enabling Yahoo makes these silly. 

I get an Yahoo answer "de huidige temperatuur is 5 graden Celsius in de tuin" where I Expected "Het is 5.6 graden" (From NetAtmo!)
and Get "ik kan geen weersinformatie vinden voor die locatie" for the Slaapkamer.....

Can you look at the Priorities of the NetAtmo App and Align these with Yahoo and the other apps?

**Comment by Tweake** [comment]
I have changed the way voice commands are assigned to an App or to Homeys built-in commands in Homey version 1.2.0. As long as you include the name of the Zone in your request the temperature sensors should get priority over the yahoo weather app. (unless you name your Zone is named Amsterdam ;) )

**Comment by Dijker** [comment]
Fixed for me in 1.2.0-rc8 Thanks!!
