### ISSUE TITLE
Page titles not translated

### ISSUE THREAD

**Issue by swttt** [athombv/homey#1106]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Page title in Dutch language

**What was the result?**

Page title is still in English (insights, settings etc.)

**What did you expect as result?**

That they would be translated as well.

**Comment by bvdbos** [comment]
![2017-05-02 22_24_20- 626 settings - homey](https://cloud.githubusercontent.com/assets/1064079/25637689/20bffa9a-2f86-11e7-87ec-6c122dbd077a.png)
close me fixed?

**Comment by bvdbos** [comment]
<title>Settings</title> isn't translated though...

**Comment by WeeJeWel** [comment]
Closing this as we're moving to the Homey Smartphone App
