### ISSUE TITLE
Homey doesn't remember zone order

### ISSUE THREAD

**Issue by moekdegroot** [athombv/homey#1108]
**What is your Homey version (Settings → System)?**

10.0.2

**What did you try to achieve?**
Have Homey save the zone order

*Please include detailed steps how we can reproduce the issue*
After updating to 10.0.2 all zones were in a wrong order.
If I put them back in the right order, switch to another page and then switch back again
the order is screwed up again.

**What was the result?**
ordering zones doesn't stick
...

**What did you expect as result?**
For it to stick
...

**Any other remarks**
This is how they showed up after updating:
![wrong order](https://cloud.githubusercontent.com/assets/16590284/20639054/2d86cedc-b3b9-11e6-89f3-2b228d18bac7.png)
This is how I want them
![right order](https://cloud.githubusercontent.com/assets/16590284/20639059/3a0064fc-b3b9-11e6-9198-632f18de25f1.png)
The ios app however still has the right order
![ios](https://cloud.githubusercontent.com/assets/16590284/20639062/41c1629a-b3b9-11e6-8c9c-16dbdbf0ed58.png)

...

**Comment by WeeJeWel** [comment]
I cannot reproduce unfortunately. Can you invite me on your Homey at emile@athom.nl ?

**Comment by moekdegroot** [comment]
Sure. 
Just cleared cache to be sure but didn't help. 
Thx alvast!

**Comment by moekdegroot** [comment]
Done. 
Using chrome on a macbook btw.

**Comment by WeeJeWel** [comment]
![zonesdrag](https://cloud.githubusercontent.com/assets/319873/20680977/c543d5aa-b5a1-11e6-981f-dc86e6288e55.gif)

It really seems to work fine on your Homey when I try it...

**Comment by moekdegroot** [comment]
I think you misunderstood. 
I can change the order of the zones but as soon as I go to another page (flows,insights or settings) and go back to the device page the order is messed up again.

**Comment by WeeJeWel** [comment]
I did the same by refreshing the page :-)

**Comment by moekdegroot** [comment]
Yeah, I saw you did but wasn't sure a refresh is the same as switching pages homey-wise ;)
Anyway, upgraded chrome, downloaded the homey app and both keep loosing zone-positioning. 
Both after refresh and switching pages. 
Really weird you can't reproduce. 
I'll try a couple of computers at work tomorrow and report back. 
Thx for checking!

**Comment by moekdegroot** [comment]
Well, my mac at work shows the same symptoms (different os and different chrome version).
The ios app also now shows the zones in the wrong order but not in the order chrome is showing.
No idea what's going on.

**Comment by WeeJeWel** [comment]
Try opening the Zones & Devices view in Google Chrome and open the Inspector, tab Network. Any red requests?

**Comment by moekdegroot** [comment]
You mean like this?
![screen shot 2016-11-29 at 14 46 44](https://cloud.githubusercontent.com/assets/16590284/20712041/b7a20600-b642-11e6-9c07-e714693bc52a.png)

**Comment by WeeJeWel** [comment]
Yeah, but then drag some zones to other positions. If they don't turn up red, their position should be saved.

**Comment by moekdegroot** [comment]
I dont't see anything red but scrolling down I saw a bar with pending.
Not sure if that was there already
![screen shot 2016-11-29 at 14 50 22](https://cloud.githubusercontent.com/assets/16590284/20712200/6b7707b6-b643-11e6-9223-3c51d35135cd.png)

**Comment by WeeJeWel** [comment]
Can you make a screenshot of that as well? And how long does it stay at pending?

**Comment by moekdegroot** [comment]
It's still pending
![screen shot 2016-11-29 at 14 53 56](https://cloud.githubusercontent.com/assets/16590284/20712311/c65beb06-b643-11e6-906a-8afb25203315.png)
Is the (40) in the tab some indication of whats going on?
![screen shot 2016-11-29 at 14 53 19](https://cloud.githubusercontent.com/assets/16590284/20712347/eca97422-b643-11e6-9222-58a4b7be98ac.png)

**Comment by WeeJeWel** [comment]
Ah, it's okay that the request is pending (it's a socket). (40) means that you have 40 unread notifications.

**Comment by moekdegroot** [comment]
Ah gotya.
So no clue from the screen shots?

**Comment by WeeJeWel** [comment]
Nope... all seems to be good, and when I try it also works fine. Maybe you can create a screencast where you demo the bug?

**Comment by moekdegroot** [comment]
Sure.
https://www.dropbox.com/s/wbeybg9d91iy5hd/IMG_3031-desktop.m4v?dl=0

**Comment by moekdegroot** [comment]
Quick update: the issue is gone after upgrading to 1.0.3.
Closing the issue.
