### ISSUE TITLE
Time trigger

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1109]
Just a short/small thingie: if you ask homey the time in dutch you would have to ask: "wat is de tijd?" but most people would use: "hoelaat is het?" . Would it be possible to add this as a build in command?

**Comment by glijie** [comment]
strange, when is ask "hoe laat is het" homey respons with the time.
If i ask "wat is de tijd" homey respons alse with the time.

**Comment by Tweaqer** [comment]
you are right, hoelaat doesn't work but hoe laat does, my bad
