### ISSUE TITLE
Homey.manager( 'insights' ).log CALLBACK never gets called

### ISSUE THREAD

**Issue by coldshivery** [athombv/homey#111]
Same thing as the previous issue probably, the function has changed? but the documentation is outdated?

When trying to log using the example code nothing happens and callback is never called.
```
Homey.manager('insights').log('mylog' ,  5 , null //date 
        , function callback(err , success){
            console.log('never gets called');
        }
    );
```

Also my created logs do not show up in homey web interface. Is that because there is no data logged yet? or should it always show all logs even if they are empty ?

Goodluck and thanks !

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18.

Note: Homey.manager('insights').log() is now called Homey.manager('insights').createEntry()
