### ISSUE TITLE
Standard capability title cannot be changed for insights or device cards

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1110]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Add multiple capabilities of the same type, and change the title for insights and device cards

*Please include detailed steps how we can reproduce the issue*

I'm using multiple capabilities of the same type
```        "meter_power",
        "meter_power.peak",
        "meter_power.offPeak",
        "meter_power.producedPeak",
        "meter_power.producedOffPeak"
```

But the title of these capabilities are the same for each one in insights and the device card. I want to change the title to something different for each subtype. I tried the following in app.json without success:
```    "meter_power.peak": {
      "type": "number",
      "title": {
        "en": "Powermeter peak",
        "nl": "Stroommeter piek"
      },
      "desc": {
        "en": "Power usage in KiloWattHour (kWh)",
        "nl": "Stroomverbruik in KiloWattUur (kWh)"
      },
      "units": {
        "en": "kWh",
        "nl": "kWh"
      },
      "getable": true,
      "setable": false
    }
  }
```

and also tried:
```
  "capabilitiesOptions": {
    "meter_power.peak": {
      "title": {
        "en": "Power meter peak",
        "nl": "Stroommeter piek"
      }
    }
  }
```

**What was the result?**

The title in the device card and insights always remain the default one
...

**What did you expect as result?**

to be able to set a custom title for each subtype of meter_power
...

**Any other remarks**

...

**Comment by caseda** [comment]
i got it working with the fibaro binary sensor, take a look at that code

**Comment by gruijter** [comment]
@caseda Yes, you are right (as always). Needed to put your code example in the right place in app.json. The Athom documentation could be a bit more clear about when and where to use capabilityOptions, but I glad it works. Thx!
