### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1111]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

Install the apps I needed without worrying about memory limits
If I install apps of 1 or 2 MB why the use 25MB of RAM? 

**What was the result?**

I have to remove apps because there is no memory left.
My Homey crashes sometimes when there is no memory left (I guess)
Sometimes all apps where killed.

**What did you expect as result?**

Store some memory to a swap file (if the storage chip is capable, not like a broken SD card on a high reads and writes Raspberry Pi)
My Homey will wake me up, instead of crashing during the night.

**Any other remarks**

<img width="994" alt="schermafbeelding 2016-11-26 om 19 06 46" src="https://cloud.githubusercontent.com/assets/13370203/20642319/6255c610-b40c-11e6-852d-ed89fe332ba8.png">

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/2134/memory-homey
Like fire96 says: _"In short, your apps cache as much as they can. When extra memory is needed, it's freed."_

**Comment by kerkenit** [comment]
But why can I have more than 12 apps.
Is there a limit on automatization?
Should I buy all my switching hardware from one vendor?
Can I buy my automated coffee machine?
Or can Athom limit the app memory? Not by memory limitation but with efficacy programing.

Overall I'm very happy with Athom/Homey. I read some threads where some folks dislike Athom/Homey but I'm not one of those kinds. I'm like my Homey, and overtime it went better and better.
Right now at version 1.x.x the Homey is out of beta, but they know they can't lay down on the backs.

**Comment by bvdbos** [comment]
No, you can just add more apps. Then linux will take some of the cached memory of the other apps for the new one...

**Comment by kerkenit** [comment]
But why are all my apps crashed when I woke up? All apps, also witch I don't used often are crashed

**Comment by bvdbos** [comment]
Are you on experimental? Disabeling all apps is part of the FW-update-procedure... If not, send a log to athom and file an issue. Memory isn't the cause of the crash:
https://forum.athom.com/search?q=memory

**Comment by kerkenit** [comment]
O, I see.
Auto update was enabled, and I guess Homey tries to install 1.0.2 this night at 04:13.
Around that time it was the last log entry of Weather Underground.
I'm still unable to unsubscribe from experimental updates see #1102 so I disabled mostly the update process. My log is 54832D7B93

**Comment by bvdbos** [comment]
This issue can be closed imho...
