### ISSUE TITLE
Translation error on setup.athom.com

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1112]
![image](https://cloud.githubusercontent.com/assets/15232724/20643075/0c59bc5e-b41f-11e6-8fd7-708916c65c6b.png)

'your' in plaats van 'uw' of 'je'

**Comment by caseda** [comment]
vind dat ervoor ook niet nederlands
"dit kan tot een minuutje duren"
=> "Dit kan tot een minuut duren"

device nou ook niet bepaald nederlands => apparaat

**Comment by bvdbos** [comment]
Lol: Windows Device -> what if I use another OS, do I have to buy a laptop with windows for setting up?

**Comment by WeeJeWel** [comment]
Fixed!

@bvdbos the message differs from your OS. Mac users will see 'Your Mac', for example.
