### ISSUE TITLE
Cannot trigger flow with Fibaro dimmer 2 (FGD-212) S2 switch

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1113]
**What is your Homey version (Settings → System)?**
homey 1.0.2
fibaro 1.1.0

**What did you try to achieve?**
Use a momentary switch on the S2 of a FGD-212 to trigger an action / flow

<img width="991" alt="screen shot 2016-11-26 at 21 25 15" src="https://cloud.githubusercontent.com/assets/18570823/20643079/1058ff86-b41f-11e6-90c6-dc224bb2979b.png">

**What was the result?**
Nothing happened

**What did you expect as result?**
S2 switch of dimmer 2 to trigger homey and thus the action / flow

**Any other remarks**
Trigger in homey does not work. Triggering one dimmer with another through changing associations does work (implying that the S2 connections are working).

**Comment by nattlip** [comment]
fw 1.0.2 or 10.0.2 ?

**Comment by cjvs** [comment]
oops. 1.0.2... updated it... 10.0.2 is probably still a long way to go...

**Comment by swttt** [comment]
That device card was a simple work around that needed some other settings to be set as well. 
Not the best way to use the S2 but it worked back then.

Tested Caseda his code, and on 1.0.2 scene activation is working for the dimmer 2. We just need to wait to get the PR's into the main fibaro git 😄

**Comment by RobinBol** [comment]
This is fixed in the latest update of the Fibaro app. To use the S1/S2 trigger functionality you need to re-pair your device.

**Comment by cjvs** [comment]
Thanks. It works. There is still a delay of a 2 seconds between S2 press and my Philips Hue lights being triggered by the flow. However, can live with that :). 

Keep up the good work!
