### ISSUE TITLE
Fibaro multisensor (FGMS-001)

### ISSUE THREAD

**Issue by PeterBox** [athombv/homey#1114]
**What is your Homey version (Settings → System)?**

1.0.2 & 1.0.3

**What did you try to achieve?**

I wanted my fibaro sensors  to work again.

*Please include detailed steps how we can reproduce the issue*

Removed  the sensors in the zwave settings, added them again, The sensors distance is at about 25 cm 

**What was the result?**

...After the last update version 1.0.2 I can install fibaro multi sensor, but homey doesn't  give me any readings anymore.

**What did you expect as result?**

After 24 hours  I did not get any readings from homey. I want to use fibaro sensors with the right  readings

...

**Any other remarks**

...

**Comment by dhanstede** [comment]
I have the same problem with my fibaro multisensor (fgms-001)

**Comment by bvdbos** [comment]
Do you have the Zwave+ or non-plus version? What settings did you set? I have the non-plus version and set "42,2,600;62,2,600;64,2,600;80,1,23;22,2,10"...

**Comment by PeterBox** [comment]
@bvdbos Tried  your settings ,no response  from homey after wakeup  fibaro

**Comment by PeterBox** [comment]
Btw  it is a non-plus version

**Comment by dhanstede** [comment]
I have also the non plus version.

**Comment by bvdbos** [comment]
What associations do you have? Works for me with "1" in all three groups...

**Comment by PeterBox** [comment]
Only  group  3, I will try  all  groups

**Comment by dhanstede** [comment]
Yesterday, i have tested and set a "1" in all three groups, but it doesn't work for me. I have also re-paired the sensor. But it doesn't work.

**Comment by Rocodamelshe** [comment]
Have the same issue. All the + versions work, the non+ don't work anymore.

**Comment by swttt** [comment]
Seems i got tamper, temperature and battery working. Motion and lux still nothing...
(with using 1 in all association groups)

Noticed that this issue isn't reported on the fibaro github. Someone should create one and refer to this issue. (or i'll create it when i get home).

**Comment by Rocodamelshe** [comment]
Strange thing is that when i put the node number 2 in group 1 (2=wallplug) then the motionsensor works and is switching on and off the waalplug

**Comment by PeterBox** [comment]
Tested 1 in all  tree groups  still no response

**Comment by djeskoswe** [comment]
Any update on this ?

**Comment by RobinBol** [comment]
We are currently looking into this issue, which we managed to reproduce. Stay tuned.

**Comment by RobinBol** [comment]
Probably related: #752

**Comment by PeterBox** [comment]
Looks like it , then it is time to fix it

**Comment by PeterBox** [comment]
@RobinBol  Any updates Robin?

**Comment by blackice2k3** [comment]
Same issue here since version 1.0.3 only 2 of 8 motion sensors are working as designed. Some are only reporting tamper alarm without cancel. Some are reporting alarm and tamper all time. Some are doing nothing.

**Comment by Rocodamelshe** [comment]
I solved my issues with upgrading the FW of the Fibaro motion sensor. U need a HC2 for it. But it's working again like he should. Upgraded from 2.6 to 2.8.

**Comment by PeterBox** [comment]
Maybe @RobinBol  has a HC2  for me to borrow. ..

**Comment by blackice2k3** [comment]
okay now I added all my motion sensors after doing following:
-> remove battery
-> press button 2-5 sec
-> insert battery
-> release button -> red color 
-> press again -> blinking all different colors
In some cases I had to do the normal reset described in the manual (long press->yellow->release->press again->red color fading).
I think this is like a hardware reset. After that I had to remove the device from zwave network (via settings -> zwave).

**Comment by PeterBox** [comment]
@blackice2k3 and does it work now?

**Comment by blackice2k3** [comment]
yes all sensors are now working perfectly. I don't know I tried really a lot today because before nothing worked and now with this trick everything is working again and i had no probs to add / configure them.

**Comment by djeskoswe** [comment]
@RobinBol Any updates Robin?

**Comment by RobinBol** [comment]
Yes, this is likely fixed in Homey v1.0.4.

**Comment by djeskoswe** [comment]
Nice,  thanks!

**Comment by PeterBox** [comment]
I have removed the battery's  until  this is fixed

**Comment by dhanstede** [comment]
After updating homey to firmware 1.04, my fibaro sensor is working again!

**Comment by djeskoswe** [comment]
Flood and pir all good here now

**Comment by PeterBox** [comment]
Tested fibaro motion sensor non plus and al are working again here

**Comment by PeterBox** [comment]
After last update 1.0.4
