### ISSUE TITLE
Insights behaving strange...

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1115]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
View insights on motion detected with my FGMS001 non zwave+

*Please include detailed steps how we can reproduce the issue*
View Insights motion-detected for today, went to bed at about 22.15, got up at about 7.25 and have a dog walking around sometimes at night. Data:
_Sat Nov 26 2016 22:11:56 GMT+0100 (CET),true
Sat Nov 26 2016 22:12:44 GMT+0100 (CET),false
Sat Nov 26 2016 22:12:44 GMT+0100 (CET),true
Sat Nov 26 2016 22:13:32 GMT+0100 (CET),false
Sun Nov 27 2016 01:29:18 GMT+0100 (CET),true
Sun Nov 27 2016 01:29:48 GMT+0100 (CET),false
Sun Nov 27 2016 06:34:46 GMT+0100 (CET),true
Sun Nov 27 2016 06:35:16 GMT+0100 (CET),false
Sun Nov 27 2016 07:27:12 GMT+0100 (CET),true
Sun Nov 27 2016 07:28:48 GMT+0100 (CET),false
Sun Nov 27 2016 07:29:18 GMT+0100 (CET),true
Sun Nov 27 2016 07:30:40 GMT+0100 (CET),false
Sun Nov 27 2016 07:34:45 GMT+0100 (CET),true
Sun Nov 27 2016 07:35:15 GMT+0100 (CET),false
Sun Nov 27 2016 07:37:04 GMT+0100 (CET),true
Sun Nov 27 2016 07:37:34 GMT+0100 (CET),false
Sun Nov 27 2016 07:51:56 GMT+0100 (CET),true
Sun Nov 27 2016 07:52:38 GMT+0100 (CET),false_

resulted in this Graph initially:
![fb today1](https://cloud.githubusercontent.com/assets/1064079/20646639/74111d9c-b47e-11e6-9698-e81ddf8b2560.png)
which obvioously is incorrect... but leaving the tab open and after triggering motion once the graph got redrawn:
![with new motion](https://cloud.githubusercontent.com/assets/1064079/20646641/88ccaf1c-b47e-11e6-8a5c-cfc67c709ad3.png)

**What did you expect as result?**
The second graph to begin with

**Any other remarks**
Parameters: 42,2,600;62,2,600;64,2,600;80,1,23;22,2,10 (but unlikely that's the issue here...)

**Comment by Phunkay** [comment]
This is the same/related to https://github.com/athombv/homey/issues/1080 I reported earlier. When the parameter in the graph gets trigger while open it is updated and redrawn correctly

**Comment by bvdbos** [comment]
I think it's the same issue as #1080 but my graphs aren't inverted.... So not setting duplicate yet...

**Comment by bvdbos** [comment]
they are... including the offset....
