### ISSUE TITLE
[Regression] Driver ID containing only numeric digits gives invalid_driver when adding new device

### ISSUE THREAD

**Issue by Thorarin** [athombv/homey#1117]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

I'm trying to get my Strips sensor to work after upgrading the Homey firmware to >= 1.0.0.
I wrote and published the Z-Wave driver for this device.

**What was the result?**

The existing driver no longer works properly. Devices that have already been added with previous Homey versions work as expected, but trying to add a new device with that same driver gives a popup message "invalid_driver" after clicking on the device icon from the driver list.

**What did you expect as result?**

For people to be able to add devices as before.

**Any other remarks**

We've discovered that this is a specific issue with the driver ID that was chosen at the time.
Like most other drivers, the driver ID is the model number of the device. Unfortunately in this case, the ID contains only numeric digits: "1101011" (see https://github.com/Thorarin/com.sensative).

Changing the driver ID to something else seems to fix the functionality of adding new devices (see https://github.com/mruiter/com.sensative). We therefore assume that somewhere the ID is being treated like a number because of duck typing.

Unfortunately, publishing a new version of the app where the old driver ID has disappeared will result in existing devices no longer working, which leaves me in a catch-22. I do not want to break existing flows if I can avoid it.

I've gone over the used homey-zwavedriver code, but the error does not appear to be in there. That would have been odd anyway, since the library was updated because this issue arose in the first place.

Anyway, in my opinion, "1101011" should be a perfectly valid driver ID. It was in the past, so the best solution (imo) is to fix this error on the side of the Homey firmware, so that both existing users and new users can use Strips.

**Comment by WeeJeWel** [comment]
Hm this shouldn't happen, I'll look into it

**Comment by WeeJeWel** [comment]
Fixed in 1.0.3!
