### ISSUE TITLE
[My.Athom.com] Reset password for Existing Account.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1118]
**What is your Homey version (Settings → System)?**

n.v.t 

**What did you try to achieve?**
Help a user on the forum to logon to the Homey App
https://forum.athom.com/discussion/2303 

*Please include detailed steps how we can reproduce the issue*
Open an incognito window, forget your password and search for an solution ;-) 

**What was the result?**
Couldn't find a place to reset my password when not authenticated.

**What did you expect as result?**

a simple link to reset my password eventually with an Capcha ....
https://accounts.athom.com/login?#password-forgotten

**Any other remarks**
Found the link after logging on ;-)

**Comment by joachimroeleveld** [comment]
For some reason the popup of resetting your password was not shown. That was a bug which is [fixed](http://pasteboard.co/3OwNMZacM.png) now. Thanks!
