### ISSUE TITLE
Can't connect to open WIFI network

### ISSUE THREAD

**Issue by patrickhopman** [athombv/homey#1119]
**What is your Homey version (Settings → System)?**

Can't see, error during setup

**What did you try to achieve?**

Try to connect to an open WIFI network

**What was the result?**

It says it requires a password

**What did you expect as result?**

That it just connects without giving in a password

**Any other remarks**

Saw this issue where you say it's fixed https://github.com/athombv/homey/issues/422

**Comment by chrisboer** [comment]
Why do you want to have a Homey connect to an open network that is completely unsecure ?

**Comment by patrickhopman** [comment]
That's irrelevant to the bug :) 
It's an guest network, the company network needs a username and password which homey totally doesn't support.

**Comment by WeeJeWel** [comment]
Did you change the security type in the dropdown to 'Open'?

![screen shot 2016-11-30 at 15 13 21](https://cloud.githubusercontent.com/assets/319873/20755516/8b98f9ba-b70f-11e6-8c41-9ed8a3e9e930.png)

**Comment by patrickhopman** [comment]
Yeh i did, but in the discovered network the activeNetworkObject.security is undefined when i select an network. Also in network_connect where it checks the type of security it's undefined and keeps checcking the type. See attached screenshot 
![image](https://cloud.githubusercontent.com/assets/1249642/20756421/ea6119c0-b712-11e6-8c19-e53cad10fb0c.png)

**Comment by WeeJeWel** [comment]
Thanks for the extensive debugging info! Are you sure it's an open network, and not an enterprise network or so?

**Comment by patrickhopman** [comment]
It's a guest network that is fully open. Also when I connect to it via any other device, like a phone or tablet.

**Comment by patrickhopman** [comment]
We've now got a new network specifically for the homey, so we can connect now. But the bug is still there with the open network.

**Comment by patrickhopman** [comment]
Here's some more info about this WIFI network
![image](https://cloud.githubusercontent.com/assets/1249642/20788645/eddeb900-b7b1-11e6-80eb-46b51e7b778e.png)

**Comment by WeeJeWel** [comment]
Thanks, should be fixed in the next Homey update (1.0.4)
