### ISSUE TITLE
Can remove flow - not visable, still usable

### ISSUE THREAD

**Issue by Omemanti** [athombv/homey#112]
Just removed all my flows, but when I Ask Homey to turn on my lights, he turns on my lights..

so I cant see the flow, but it is still there.

**Comment by elgenioNL** [comment]
The voice commands for lights are a system feature that runs outside the flows. It's always active and not an Issue.

**Comment by Omemanti** [comment]
but if i remove a flow,, why would it still react to my voice command? I removed it for a purpose.

btw, this was the only command that is working see [#113](https://github.com/athombv/homey/issues/113)

**Comment by bvdbos** [comment]
You could try the command "time", it's also working :-)

**Comment by Omemanti** [comment]
flows with time are also not responsive.. :-(

**Comment by goldenice** [comment]
@Omemanti There are a few 'flows' built in, such as turning on lights, asking Homey the current time, asking what version Homey is running et cetera. These 'flows' are not visible in any kind of way, as they're the core functionality of Homey. As of now there is no way to disable those.
