### ISSUE TITLE
Set capabilitytitle dynamic

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1120]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
I want the user to be able to set and change title of a capability.

If i have two onoff switches in the same device one for my lamp in the kitchen and one in living room and want to turn the lamp in the kitchen off i don't know witch it is.

One way can be if you can set the name in the mobile card in the pairing object like this.

```
mobile: { 
	components: [
		{
			id: 'toggle',
			capabilities: [ 'onoff.0' , 'onoff.1' ],
			options: { 
				showTitle: true,
				'onoff.0': {
					title: { 
						en: 'Kitchen' 
					}
				},
				'onoff.1': {
					title: { 
						en: 'Living room' 
					}
				}
			}
		}
	]
}
```

**Comment by WeeJeWel** [comment]
Check out `capabilitiesOptions`: https://developers.athom.com/library/drivers/capabilities/

**Comment by ewikner** [comment]
What i can read it decribe that it only can be set in the app.js so how can i change it when the user want to change it?
