### ISSUE TITLE
Set title on a capability dynamic, not in app.json

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1121]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
I want the user to be able to change the title of a capability as they want.
One solution can be that you can change the title in the pairing mode.

In this way the app is more dynamic and flexible.

I know that you can set the title in the capabilitiesOptions in app.json but this will not work in this case.

**Comment by markaswift** [comment]
Any news on this?

**Comment by WeeJeWel** [comment]
This is already possible. During pairing, you can override `capabilitiesOptions` in the device object, e.g.:

```javascript
socket.on('list_devices', function( data, callback ){
	
	callback( null, [
		{
			name: "My Device",
			data: {
				id: "abcdef1234"
			},
			capabilities: [ "onoff" ],
			capabilitiesOptions: {
				onoff: {
					title: "My Title"
				}
			}
		}
	]);
	
});
```
