### ISSUE TITLE
Set dimming level by variable

### ISSUE THREAD

**Issue by goyaweb** [athombv/homey#1122]
**What is your Homey version?**
v1.0.1
**What did you try to achieve?**
Set dimming level to variabe/label value
**What did you see as result?**
The set dimming level card only accepts a fixed percentage set by the slider.

**Comment by bvdbos** [comment]
? how is this fixed? Tried with KaKu and Lifx but to way to set a dimming level with a flowcard?

**Comment by caseda** [comment]
![screenie](https://cloud.githubusercontent.com/assets/2565450/21553870/5f4dd228-ce0b-11e6-8225-30e4408d2f2c.jpg)

**Comment by bvdbos** [comment]
Great, worked for me... Thanks.... confirmed for Kaku....

**Comment by goyaweb** [comment]
works for qubino and fibaro but for everspring dimmers it changes momentarily to the desired dimming level but then jumps back to 0.99.

**Comment by bvdbos** [comment]
@goyaweb that's bug #934
