### ISSUE TITLE
Homey "there is nobody home" card not working

### ISSUE THREAD

**Issue by jeroenniesen** [athombv/homey#1123]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

I am having a flow with the "there is nobody home" card in it. That card is not working. In the past situation I had two devices (android tablet and iPhone with the Homey App on it.) First I thought that the problem was caused by my tablet that was still at home; but after uninstalling the app (and removing the device from Homey) the flows are still not working.

**What was the result?**
Uninstalling the app from one of the devices did not solve the problem.

**What did you expect as result?**
The home card should work since no devices are at home.

**Any other remarks**
I was asked te report this issue in GitHub since there were more people that mentioned this issue. If you need more information, feel free to contact.

**Comment by jeroenvollenbrock** [comment]
Does explicitly using the "A specific person is not at Home" card for each person work?

**Comment by jeroenniesen** [comment]
I haven't tried the "A specific person is not at home" card. I will change the flow right now, but keep in mind that I want to have the flow working for all people in te house, not specific ones. 

Interesting to mention: I get notifications when I am leaving my home and coming home.

**Comment by jeroenniesen** [comment]
Just tested the "A specific person is not at home" card. That worked fine. I am the only person that is setup in Homey. 

Could it be possible that my deleted android device is still stuck in Homey?

To debug this issues, it would be nice to have:
- A log of flows
- A list of persons that are at home

Please let me know of you need any more information.

**Comment by WeeJeWel** [comment]
As of v1.2.0-rc.10 the presence is visible as a Tag in the Flow Editor. Can you check if those seem correct?

**Comment by jeroenniesen** [comment]
Hi @WeeJeWel 

That will be difficult for me to test. I only got version 1.1.9 installed. And that build is quite stable :-)

Will the experimental build be upgradable to a non experimental build? (without resetting Homey?)

**Comment by WeeJeWel** [comment]
Nope, that's not possible. In that case, we'll upgrade 1.2.0 to stable within one or two weeks probably, so check back then.

**Comment by jeroenvollenbrock** [comment]
1.2.2 has been released to the stable channel. Could you please report back?

**Comment by chrisboer** [comment]
I have the same issue I am home and as presence for homey is not working for iphone either homey still thinks nobody is home and closes the door ?

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25840635/cc8e557c-349c-11e7-832b-7310d6d23d16.png)

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
