### ISSUE TITLE
The word weer triggers unwanted question.

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1124]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Created a flow which will run when I say: Ik ben weer thuis.

**What was the result?**

Home starts with saying: Alles gaat goed. Lief dat je het vraagt or met mij gaat het super

**What did you expect as result?**

Not this. The word weer seems to trigger an unwanted question.

**Any other remarks**

Seems to be the problem since last update.
https://forum.athom.com/discussion/2317/homey-is-gonna-say-strange-things

**Comment by Tweake** [comment]
Silly mistake on my part, thanks for pointing this out. It will be fixed in the next Homey update
