### ISSUE TITLE
[Feature Request] Time Condition card between two Days of the Month.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1126]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
Help a Homey Owner on the forum ;-)
a trigger only on the second Saturday of the month. 
https://forum.athom.com/discussion/2326 
Now only possible by checking 26 times: not 1st, not 2nd, not 3rd, .... not 31st

*Please include detailed steps how we can reproduce the issue*
Create a condition : 1) its Saturday, 2) between the 8th and the 14th (inclusive) day of the month. 
(comparable to time between card, when first day -gt second the days across two months ;-)  ) 

**What was the result?**
There is no Time Condition card before/after or between Day of the month. 
![image](https://cloud.githubusercontent.com/assets/12412734/20826389/c3ed56ba-b86a-11e6-839a-b653dceebd9e.png)

**What did you expect as result?**
One extra card with the condition"[Not] Between [1st-30th] and [2nd-31th] day of the month (inclusive days).
imho easy to create, and a usefull valid request ;-) 

**Any other remarks**

**Comment by Fiek1** [comment]
That homey owner would be me :).. Thnx @Dijker for submitting the issue

**Comment by WeeJeWel** [comment]
![screen shot 2016-12-08 at 14 05 31](https://cloud.githubusercontent.com/assets/319873/21010991/651a6c24-bd4f-11e6-81d3-e42b268b5416.png)

There you go! Added in 1.0.4

**Comment by WeeJeWel** [comment]
For convenience, also added `day between`, `date between`, `day number between`, `month between`, `year between`

**Comment by Fiek1** [comment]
Thnx 4 the swift fix

**Comment by Dijker** [comment]
didn't test them all, I believe they wil work until we see a problem  ;-) 
Thanks!
