### ISSUE TITLE
After "Ik heb het koud" or heating specific request, Homey does not accept new voice commands

### ISSUE THREAD

**Issue by jtebbens** [athombv/homey#1127]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

I tried to give a new voice command/request to Homey (Lights off or anything else) it fails after the build in heating/verwarming command "Ik heb het koud".

*Please include detailed steps how we can reproduce the issue*
- Request Homey "Ik heb het koud" if responds to change the temp.
- Request Homey anything else "Lichten uit" or some other speech flow request.

**What was the result?**
It doesn't take any new requests after build in heater command.

**What did you expect as result?**
Accept voice commands like normal

**Any other remarks**

**Comment by Dijker** [comment]
Confirmed, same here!
Homey V1.0.2 [Dutch] / Thermosmart 1.0.6 
It doesn't respond on the question to change the Thermostat, 
and after that no responses from Homey anymore, also my  Homey Said something or ParrotFlow don't trigger anymore.... just no responses from Homey ....

Same typing at /manager/speech-input/, Homey doesn't accept new input after the input Ik heb het koud.

**Comment by Tweake** [comment]
Found and fixed the issue, thanks for reporting! The fix will be included in the next Homey update.

**Comment by Dijker** [comment]
Checked and now it works as expected for me !
Thanks!!

**Comment by Inversion-NL** [comment]
@Dijker close the issue then?

**Comment by Dijker** [comment]
only creator or Athom can close  ;-)
@jtebbens  does it work for you?
