### ISSUE TITLE
Minor lay-out imperfections on mobile cards

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1128]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Look at mobile card for tesla app

**What was the result?**

Some letters like 'g' don't show lower parts. Capabillity titles are not centered on same height:
...
![image](https://cloud.githubusercontent.com/assets/15232724/20828894/f52d7a34-b879-11e6-81f1-b1b34452a577.png)

**Any other remarks**
When i disable `line-height: 3vw;` characters like g, j, y, p, q are not cut from below

Using this spec in app.json:
```
      "mobile": {
        "components": [
          {
            "id": "icon",
            "capabilities": []
          },
          {
            "id": "sensor",
            "capabilities": ["moving", "location_human"],
            "options": {
              "icons": {
                "moving": "/assets/gauge_icon.svg",
                "location_human": "/assets/location_icon.svg"
              },
              "moving": {
                "noblink": true,
                "label": {
                  "true": {
                    "en": "Driving",
                    "nl": "Rijdt"
                  },
                  "false": {
                    "en": "Not driving",
                    "nl": "Staat stil"
                  }
                }
              }
            }
          }
        ]
      }

```
...

**Comment by WeeJeWel** [comment]
Fixed in 1.0.4, thanks for reporting!
