### ISSUE TITLE
Only response to turning lights on, every other voice command is ignored

### ISSUE THREAD

**Issue by Omemanti** [athombv/homey#113]
I made about 10 flows for testing, every command except turn the lights on(my first flow) is responsive to speach.

I recalibrated my voice a couple of times, but no matter what I try, nothing else but my lights turning on seems to work.

even tried basic worlds like "chair", "test" and "house" also easy things like "good night" none dont seem to work.
Homey hears "hey homey" starts listening (orange/yellow ring)  than starts prosessing "white" and then turns into a rainbow.

Dont know if it matters, i removed the older flows by using the crossair. (I didnt have to press yes to remove them)

Also for what its worth, yesterday I made homey play music, that worked. Then I removed that one flow. I just recreated this same flow again, this one also doenst work.

**Comment by vogon1** [comment]
I have a similar issue. Only one flow with a voice command works, all others are ignored.

**Comment by Omemanti** [comment]
Turning off a light seems to be impossible

**Comment by vogon1** [comment]
In my case I can turn off lights if it is the only flow.

**Comment by mvunen** [comment]
+1
No voice commands are executed...

**Comment by AndreSomers** [comment]
Don't make your own flows with words about "light". It clashes with existing pre-defined commands. 

The bug here is that Homey should warn you when you create such a flow.

**Comment by RuudBurger** [comment]
I don't think that's the bug. Because then you can't do thinks like "dim the light in the kitchen" or any other command that isn't the existing "all on" or "all off".

**Comment by Omemanti** [comment]
> Don't make your own flows with words about "light". It clashes with existing pre-defined commands.
The bug here is that Homey should warn you when you create such a flow. See #142

That would be rather silly. And if its a bug I should not prohibit you from making such a flow (or warn you) it should be fixed. 

Else I can turn on my lights in the living room and have to walk to the kitchen to turn those off.

also it doesn't explain why every other flow I've added so far is responsive.

**Comment by wslybkkr** [comment]
Same problem here. Made 4 flows with different words that need to trigger those flows. None of them are working. Same as the normale commands link: Is it going to rain within 15 minutes. None of the commands are responsive anymore. When i delete the flows all the pre-defined commands work again.

**Comment by Omemanti** [comment]
So I removed the only working flow to see if the others starts working.

Nope.

It respond to Hey Homey, and then it processes and thats it. even the light command do nothing (or i did something wrong... I follow the manual though.)

**Comment by peaoo** [comment]
Hey, same problem here, made a video of it.
After creating the flow with speech trigger "example" all lightswitching commands stop working.
https://youtu.be/6sWZSFzPIUE
Hope this helps

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by peaoo** [comment]
For me this was solved months ago :)
No problem here.

**Comment by jeroenvollenbrock** [comment]
Okay, in that case i'm closing this issue. If the problems still continue to persist, please reopen.
