### ISSUE TITLE
delay time wrong 

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#1130]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Turn on wall plug and the off after 15 min 

*Please include detailed steps how we can reproduce the issue*

![2016-12-03 00_38_40-untitled - paint](https://cloud.githubusercontent.com/assets/17300121/20854067/01aa9f54-b8f1-11e6-842f-fa19142d12b6.png)

**What was the result?**

timer turns off plug before time ends  ( 15min)

..

**What did you expect as result?**

... right time

**Any other remarks**

log : F60A9F0815

Sat Dec 03 2016 00:29:41 GMT+0100 (CET),true
Sat Dec 03 2016 00:33:27 GMT+0100 (CET),false

...

**Comment by djeskoswe** [comment]
works now , strange ...close

**Comment by Dijker** [comment]
I guess you tested it some water less than 15 minutes before, and that flow was still silently running. It isn't canceled if you switch manually off and on again, so it switches off before 15 minutes after the last trigger.
