### ISSUE TITLE
No trigger on Lux value 0

### ISSUE THREAD

**Issue by StraDijk** [athombv/homey#1131]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**
Turn on light when lux is < 5

*Please include detailed steps how we can reproduce the issue*
![1](https://cloud.githubusercontent.com/assets/2519741/20857655/f127086a-b932-11e6-9026-0e6ebd13d87d.PNG)
![2](https://cloud.githubusercontent.com/assets/2519741/20857661/03095092-b933-11e6-9c79-ab239190d7e6.PNG)

**What was the result?**
If the lux value is 0 the flow does not continue. When the lux value is 1,2,3 or 4 the flow continues.

**What did you expect as result?**
Flow will continue when the lux is < then 5

**Comment by Dijker** [comment]
Hi,
I don't have this multisensor so I can't test for you but I think you have a wrong expectation regarding to the test button. 
Test always  use a fake predefined  value,
Feb   testing sunrise and sunset always have value time 21:23 anytime of the day. 
You pressed test and the programmed  fake test value is higher than  5. 
The trigger only fires on changes, so probably it also triggers on changes from anything to 0

You could test the value by creating a new  flow with the same trigger, no conditions and for example an push notification  to your phonemail with in the msg the lux. 
The current screenshot of your flow looks good, don't test it with the test button but test it by changing the lux from anything to 0. If that works there is no problem with that app. 

For what I think you want to achieve:
IMHO you should trigger on motion,  with the condition the light is lower  than... 
Now the Dimmer won't turn on if there is motion but the lux doesn't change....

**Comment by StraDijk** [comment]
Hi Dijker,

Ok, didn't know about the test value..

Strange that flow works when the lux is between 1 and 4. The reason for using lux as trigger is, there is no lux condition. 

For now i solved the issue by using better logic.

**Comment by Dijker** [comment]
Probably  when you walk by the lux changes, and your flow works because there is also motion. 
But have in mind that a motion detected without changing the lux doesn't trigger the flow!
