### ISSUE TITLE
LED ring off answer repeated

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1132]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Set LED ring to off by voice. I say: "LED ring uit"

**What was the result?**

LED ring is set to off and Homey says 2 times "Ik zet de LED ring uit"

**What did you expect as result?**

Just one time the answer "Ik zet de LED ring uit"

**Any other remarks**

...

**Comment by robertraaijmakers** [comment]
Happens here as well.

**Comment by bvdbos** [comment]
https://athomcommunity.slack.com/archives/general/p1481369670002229
confirmed

**Comment by PeterBox** [comment]
Same here  to

**Comment by Tweake** [comment]
Will be fixed in the next Homey update, thanks for reporting!
