### ISSUE TITLE
Battery-empty app

### ISSUE THREAD

**Issue by LuukvD** [athombv/homey#1133]
Hello,

I would like to have an app that tells me one of my Zwave devices is empty. Right now I have to make  flow for that I guess, and to be honest.. I am not that good in making flows, so making a battery-empty-flow is already not that easy for me. And besides that.. I have 20 Zwave things. Would be 20 flows I guess? 

Well, would be great.

**Comment by bvdbos** [comment]
![accu](https://cloud.githubusercontent.com/assets/1064079/20860572/5b78fd02-b97b-11e6-85e4-fabd2e12c8e8.png)
Creating flows is a major feature in domotica (and thus in Homey too). You get so much more from Homey is you create flows... Please take a look at:
https://www.athom.com/nl/ondersteuning/KB000006/
and
https://www.athom.com/nl/ondersteuning/KB000007/

**Comment by LuukvD** [comment]
Well, good to know it's that easy to create a flow. I didn't know what to fill in at 'smaller than', but I guess it's in percentages? 

Doens't solve the problem that it's stupid to have to make 40 flows.. if you have 40 Zwave devices. An app would be much more userfriendly, and isn't that what the Homey is supposed to be?

**Comment by Inversion-NL** [comment]
Would be a nice addition to this: https://github.com/athombv/homey/issues/784

**Comment by LuukvD** [comment]
No idea how this GITHUB works.. but isn't someone supposed to answer?

**Comment by Inversion-NL** [comment]
It's a feature request so if Athom has a stable firmware base they'll start implementing new features. 
If they decided their going to implement this feature, that is

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/3470/app-blowfish-check-battery-levels-last-updates-capabilities-and-condition-for-lights-in-a-zone

**Comment by bvdbos** [comment]
So this can be considered fixed?

**Comment by swttt** [comment]
I wouldn't as long as this isn't an App Store app or even has (user-friendly) settings...

**Comment by bvdbos** [comment]
Fixed for 1.5 ?

**Comment by bvdbos** [comment]
now please close me

**Comment by WeeJeWel** [comment]
There is now indeed a generic flow card for all battery devices since some while ago.
