### ISSUE TITLE
Booleans not displayed correctly in Insights for true《》false edges

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1134]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

Show insights logging of a boolean

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

The edges for true to false and vice versa are not displayed correctly

**What did you expect as result?**

...

**Any other remarks**

see snapshot and the export of correct values/times

![2016-12-03](https://cloud.githubusercontent.com/assets/19174120/20861916/2af66ecc-b99d-11e6-9369-cd4a5ebd52ce.png)

**Comment by bvdbos** [comment]
What happens if you leave insights open a cause another trigger? see #1115 and #1080

**Comment by robiebab** [comment]
bug is still active on 1.2.2

**Comment by bvdbos** [comment]
works for me in 1.5rc6.
