### ISSUE TITLE
Do not access device before modules.exports.added is fired

### ISSUE THREAD

**Issue by vogon1** [athombv/homey#1135]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

After adding a new device, its values are fetched before module.exports.added fires

**What was the result?**

Driver crash (my not yet release FHEM driver)

**What did you expect as result?**

module.exports.added is called before device values are read.
I use module.exports.added for initialisation, but homey is trying to access values before that.

**Comment by WeeJeWel** [comment]
Fixed in Homey 1.0.4, thanks for reporting!
