### ISSUE TITLE
LED Ring Brightness changed after been set to off

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1137]
**What is your Homey version (Settings → System)?**

1.0.2

**What did you try to achieve?**

Set LED ring to off and later to on

**What was the result?**

Brightness of the LED ring was set to 100%

**What did you expect as result?**

Brightness would be as before switching off

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
How did you turn the LED Ring off? By Flow, Speech..?

**Comment by HansieNL** [comment]
I turned the LED ring off by speech.

**Comment by Tweake** [comment]
I was only able to reproduce this after setting LED ring brightness to 0% in settings first. It was in fact intended behaviour to turn on the LED ring back on when "LED ring on" is said, regardless of the stored value of 0% to prevent confusion. 

Just to be on the safe side I have added an extra check to prevent any edge cases from producing the problem you are describing. 
"LED ring on" will always return the value to what it was when you said "LED ring off", as long as the value wasn't already 0% when you said the off-command.

**Comment by HansieNL** [comment]
OK, sounds good. Than I can remove my flow to set the brightness always to 7%.
