### ISSUE TITLE
Danalock V2 not working anymore on Stable Firmwares

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#1138]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

Do something with my new danalock v2 - people buy it because theres an official Athom app for it.

**What was the result?**

Non working - Error no command class doorlock

**What did you expect as result?**

More then a broken chain

**Any other remarks**

As there is an official Athom app for this i would expect that its fixed swiftly
Also some effort to put the settings in the app would be appriciated

**Comment by mruiter** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/17739535/20900397/3da85606-bb2e-11e6-8a81-e7a056dfa7d2.JPG)

**Comment by mruiter** [comment]
debug] ------------------------------------------
[debug] Node: 4d616a97-ef80-449b-80d9-e925b8cf3c5c
[debug] - Battery: false
[debug] - CommandClass: COMMAND_CLASS_ZWAVEPLUS_INFO
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- ZWAVEPLUS_INFO_GET
[debug] --- ZWAVEPLUS_INFO_REPORT
[debug] - CommandClass: COMMAND_CLASS_MANUFACTURER_SPECIFIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- MANUFACTURER_SPECIFIC_GET
[debug] --- MANUFACTURER_SPECIFIC_REPORT
[debug] - CommandClass: COMMAND_CLASS_SECURITY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- NETWORK_KEY_SET
[debug] --- NETWORK_KEY_VERIFY
[debug] --- SECURITY_COMMANDS_SUPPORTED_GET
[debug] --- SECURITY_COMMANDS_SUPPORTED_REPORT
[debug] --- SECURITY_MESSAGE_ENCAPSULATION
[debug] --- SECURITY_MESSAGE_ENCAPSULATION_NONCE_GET
[debug] --- SECURITY_NONCE_GET
[debug] --- SECURITY_NONCE_REPORT
[debug] --- SECURITY_SCHEME_GET
[debug] --- SECURITY_SCHEME_INHERIT
[debug] --- SECURITY_SCHEME_REPORT
[debug] - CommandClass: COMMAND_CLASS_DEVICE_RESET_LOCALLY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- DEVICE_RESET_LOCALLY_NOTIFICATION
[debug] - CommandClass: COMMAND_CLASS_BATTERY
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BATTERY_GET
[debug] --- BATTERY_REPORT
[debug] - CommandClass: COMMAND_CLASS_POWERLEVEL
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- POWERLEVEL_GET
[debug] --- POWERLEVEL_REPORT
[debug] --- POWERLEVEL_SET
[debug] --- POWERLEVEL_TEST_NODE_GET
[debug] --- POWERLEVEL_TEST_NODE_REPORT
[debug] --- POWERLEVEL_TEST_NODE_SET
[debug] - CommandClass: COMMAND_CLASS_APPLICATION_STATUS
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- APPLICATION_BUSY
[debug] --- APPLICATION_REJECTED_REQUEST
[debug] - CommandClass: COMMAND_CLASS_BASIC
[debug] -- Version: 1
[debug] -- Commands:
[debug] --- BASIC_GET
[debug] --- BASIC_REPORT
[debug] --- BASIC_SET
[debug] ------------------------------------------

**Comment by mruiter** [comment]
Firmware update of the DanaLock V2 resolves the problem.

**Comment by ktecho** [comment]
@mruiter How did you do the firmware update on the V2? Thanks!
