### ISSUE TITLE
[Flowcard suggestion] Microphone --> Contains words

### ISSUE THREAD

**Issue by Qx5** [athombv/homey#114]
What I now often use in Flows is:

When: You said anything
And: {text} contains <keyword> (and: {text} contains <keyword> etc.)
Then: rest of the flow

I do this because full sentence recognition often fails while only recognizing some keywords in my sentence would be sufficient. It also enables more flexible phrasing which makes homey seem even more intelligent :wink:

To make this more user friendly I would suggest making another side on the microphone card where you can enter multiple words and homey threats these words as described in my example of the AND column.

**Comment by RuudBurger** [comment]
+1

**Comment by WeeJeWel** [comment]
These are already a 'contains', not '=='

![screen shot 2016-02-11 at 22 27 16](https://cloud.githubusercontent.com/assets/319873/12991215/9d700346-d10e-11e5-9515-94ef48de61af.png)

**Comment by Qx5** [comment]
@WeeJeWel 
I don't really think so actually. At least I don't get it to work this way and I see many other people combine the said anything card with logical contain cards because that seem to work better than the "you said: " card.
