### ISSUE TITLE
Homey loses connection with 2nd Hue Hub Lamps (1st gen)

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1140]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**
Keeping a second Hue Hub functional on the Attic

*Please include detailed steps how we can reproduce the issue*
I added a second Hue Hub (1st gen) to my homey wich i attached to the room "attic"it has a Philips hue White ambiance Lamp

**What was the result?**
It get's connected but after some time it says "Lamp onbereikbaar"
I can add the lamp through the wizzard again and it works, but after some time same result. 

**What did you expect as result?**
That the lamp stays connected with homey.

**Any other remarks**

...
![image](https://cloud.githubusercontent.com/assets/752857/20958466/11515336-bc56-11e6-8d60-2131a106b1bc.png)

![image](https://cloud.githubusercontent.com/assets/752857/20958502/4877dfb0-bc56-11e6-8cba-1cd877457e25.png)

![image](https://cloud.githubusercontent.com/assets/752857/20958515/5274d8f6-bc56-11e6-9ee1-702c90d5cad0.png)

![image](https://cloud.githubusercontent.com/assets/752857/20958522/58ba7cb6-bc56-11e6-8c14-a55f58c3a941.png)

**Comment by spoelly** [comment]
Think it was a issue with the home IOS app because after the latest beta update the problem is gone

**Comment by spoelly** [comment]
And the issue is back..

**Comment by bvdbos** [comment]
What's different in your system? Did you update one or more of the bridges? Or did you update Homey?

**Comment by spoelly** [comment]
I updated homey to 1,0,3 and the bridges to the latest firmware.

**Comment by spoelly** [comment]
Any news on this? Still have the problem

**Comment by spoelly** [comment]
Still not able to use a second bridge. The one bridge that works is randomly, sometimes hue 1 sometimes hue 2. Any news on this?

**Comment by WeeJeWel** [comment]
Yes I'm looking into this asap

**Comment by Fiek1** [comment]
Hi Weejewel,

The last few weeks I have the same issue with my hue lights (bridge 2.0). Did you find anything. I have to manually revive the connection almost every day now

**Comment by spoelly** [comment]
any progress on this issue?

**Comment by NiKoN33** [comment]
On version 1.3.0 the problem persists that one of my two Hue-bridges(2nd gen) is unreachable.
It seems totally random which one.

**Comment by spoelly** [comment]
Correct, its a random issue on which hub the connection is lost. This needs to be fixed in the hue app. Hopefully @weejewel Will have some time for it soon

**Comment by WeeJeWel** [comment]
Should be fixed - please try it first from Github. If that works, I'll update it in the App Store.

**Comment by spoelly** [comment]
Ah cool, Will test it when i am back from vacation!

**Comment by NiKoN33** [comment]
After installing version 2.2.5 (Hue App) from github, both 2nd gen bridges are reachable and all lights and sensors work for now.

**Comment by WeeJeWel** [comment]
Great!
