### ISSUE TITLE
Presence in Insights looks inverted

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#1141]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

View my presence in insights from iOS app.

**What was the result?**

My presence is inverted. So it shows a graph when I'm away and not when I'm home.

**What did you expect as result?**

I would expect this to be inverted.

**Any other remarks**

Nope.

**Comment by bvdbos** [comment]
The same as #1080 ?

**Comment by 2benl** [comment]
Yep same as #1080 I missed that one.

**Comment by chrisboer** [comment]
Same issue here, 2 people are home and still Homey thinks in a flow nobody is at home.

**Comment by JesperJanssen** [comment]
Same issue here with the bitflips (Better Logic) I use. When the bitflip is turned on it shows no color bar and when the bitflip is turned off it shows a color bar in the insights graph. Should be the other way around.

But I have more problems with the insights graph. Like not logging any information at all.

**Comment by jeroenvollenbrock** [comment]
Closed as duplicate of #1080
