### ISSUE TITLE
Show capability in insight even after you change the title.

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1142]
**What is your Homey version (Settings → System)?**
1.0.3 

**What did you try to achieve?**
This relate to #1120 and #1121
I want to change the title of a capability such as measure_humidity dynamic in the pairing mode and still get the values in the Insights as if i keep the original title of the capability.

*Please include detailed steps how we can reproduce the issue*
Change the title of a capability like in the issue #1121

**What was the result?**
Can't see the capability in the Insight.

**Any other remarks**
Please stop closing issues before you are absolutely sure the issue is resolved.

**Comment by ewikner** [comment]
Would also be nice if missing documentation is added to the docs pages when it's posted somewhere...

**Comment by bvdbos** [comment]
@ewikner The issues you described were already possible so they were correctly closed. You keep extending your question(s)... I have no problem with that BTW, see what you want to achieve and would be really good. 

About documentation : perhaps it would be better to have a wiki-like system? So we could add/alter the information ourselves?

**Comment by ewikner** [comment]
@bvdbos You have right on one thing, It was already possible. 
But there was no information about how to do it. 

The answer from @WeeJeWel that I can find it in the `capabilitiesOptions:` https://developers.athom.com/library/drivers/capabilities/ is not correct becouse there is only decribe that you can do it in app.json.
My question was how to do it dynamic so the user can change it. How can they change the app.json? So i don't agree that the issue was closed correctly.

If @WeeJeWel write that there is multiply ways to change the title and write both answers from the both issues. Then it would have been a correct.

So what i want to say is that, listen to the users and if you have a solution that is not decribe on any page. Just tell them how to do it and don't link to pages you don't have decribe it.

Yes, I keep extending my questions just because there is no other way to get any answers from the Athom team.

**Comment by markaswift** [comment]
Would appreciate an update on this, MySensors is fundamental to my continued use of Homey... @WeeJeWel, please, can you assist us?

**Comment by markaswift** [comment]
@WeeJeWel Update, please! The dev is building an app for YOUR product, to help YOUR customers. This should be easy for you to answer, or at least tell us if it's not possible. If not, perhaps @jeroenvollenbrock can help?

**Comment by WeeJeWel** [comment]
@ewikner If you provide `capabilitiesOptions` during pairing (while emitting to `list_devices` or when calling `Homey.addDevice()`, that should work. Maybe I don't understand your issue correctly?

**Comment by ewikner** [comment]
@WeeJeWel 
This is how the `capabilitiesOptions: { 'measure_temperature.0': { title: 'Test Title' } },` looks like in the object i send to `Homey.addDevice()`
If i do that i can't see the sensor/capability in the insight.

**Comment by markaswift** [comment]
@WeeJeWel Can we have a follow up, this is the last issue we need to close to get the new app version released!

**Comment by WeeJeWel** [comment]
Fixed in 1.1.3!
