### ISSUE TITLE
unfriendly / disturbing message after logging in

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1143]
**What is your Homey version (Settings → System)?**
1.0.3

**What did you try to achieve?**
log in to my.athom.com

*Please include detailed steps how we can reproduce the issue*
see startscreen:
![2016-12-10 14_14_39-homey](https://cloud.githubusercontent.com/assets/1064079/21073606/7561af08-bee3-11e6-83ea-6bafb3e8576d.png)

**What was the result?**
Unfriendly or even disturbing message "Browsers are not supported" but I run linux mint so no Homey-app for me....

**What did you expect as result?**
"Though the chrome-browser will probably work, only the desktop-app is officially supported" or something like that...

**Comment by WeeJeWel** [comment]
As of v1.1.0, create a cookie `homey_suppressbrowserwarning` with value `1` ;-)

**Comment by Dijker** [comment]
Almost There.....

clicking on the link "Homey Desktop App" in the unfriendly message from my Android tablet with Chrome I get a redirect to nuts .... ???!?!???!

![image](https://cloud.githubusercontent.com/assets/12412734/21552022/f1dd2696-cdfe-11e6-8d67-22f714f1ea8d.png)

Pls make it on Chrome on Android a Popup with an choice: 
- Agree and Disable the Waring by placing an Cookie. 

On other OS's give the choice to download (Not starting automatically) : 
- Windows App 
- Apple App

Setting the Cookie on Chrome in Windows works good, but setting an Cookie on an Android is just ehhhh.... another cookie ;-)

**Comment by WeeJeWel** [comment]
Replaced the URL to our (nicer) support article.

And I won't make a popup. People have to prove they're technie enough to understand that they're using an unsupported browser ;-) It's just a message after all.

**Comment by bvdbos** [comment]
yep, setting the cookie works.. Didn't work in the url-bar btw, used the console to enter:
javascript:document.cookie="homey_suppressbrowserwarning=1"

**Comment by Dijker** [comment]
@WeeJeWel from  Chrome on Android I am still redirected to Nuts ..... from that informational link  both on the Dutch as English Homey's Homepage. where Chrome in Windows 10 already redirects to https://www.athom.com/en/support/KB000040/

**Comment by WeeJeWel** [comment]
That's chrome's cache, it will resolve itself.

**Comment by bvdbos** [comment]
I'd vote to make this a setting from the GUI instead of having to do this through the commandline. And of course I know browsers aren't supported -> that's like saying Linux, Tablets and Mobile Phones aren't supported... So 2001 ;-)
