### ISSUE TITLE
Login button on mainpage athom.com

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1146]
**What did you try to achieve?**
Try to find a login page for my Homey on Athom.com

**What was the result?**
I couldnt find the universal address for Homey on Athom.com nor is it mentioned in any of the knowledge articles I could find searching for it. 

**What did you expect as result?**
I expected a 'login' or 'login to your homey' button on the mainpage of athom.com. It would be best if it was placed right next to 'bestel nu'. Make the same kind of button but then when you press it you go to: my.athom.com and login to homey. Makes it VERY easy to find, especially when you're not home or if you do not know the IP of your Homey.

**Any other remarks**
Please makes this happen :) 👍

**Comment by jjtbsomhorst** [comment]
This would indeed a great options. On the other hand if you go to **MY**.athom.com ;)

**Comment by WeeJeWel** [comment]
We won't add this for now, also not with the Smartphone App planned :)
