### ISSUE TITLE
app crash shows 'No stack trace available' with exit signal:SIGKILL

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1147]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

The Magister app (v0.0.15) crashed

*Please include detailed steps how we can reproduce the issue*

I do not know how to reproduce this

**What was the result?**

The crash message shows:
```
Stack trace:
No stack trace available

Exit code: null
Exit signal: SIGKILL
```

**What did you expect as result?**

a proper stack trace to help find the cause of the crash

**Any other remarks**

...

**Comment by gruijter** [comment]
Today it happened again for the Hue app.

```Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL```

log id: 9A9B1E162E

**Comment by WeeJeWel** [comment]
It looks like your Homey is out of memory when this happens!

**Comment by WeeJeWel** [comment]
@jeroenvollenbrock Maybe we can capture out-of-memory events, instead of a generic SIGKILL?

**Comment by gruijter** [comment]
I still have this issue (v1.3.0-rc2) , and also get reports from other users (v1.2.0)
