### ISSUE TITLE
433 mhz down

### ISSUE THREAD

**Issue by posthok** [athombv/homey#1149]
**What is your Homey version (Settings → System)?**

Homey 1.0.3
KaKu 2.8.3

**What did you try to achieve?
This evening the lights went on. But only z-wave devices turned on. All the 433 Mhz device's (kaku and action) did'nt react. After several reboots only z-wave is switching. Noticed some broken chains in my flows. Some kaku devices where lost.  In Devices the 433 devices did'nt react at all. 

Did uninstall the kaku app and reinstalled it. Added all the devices again and repaired my flows

System is running again,

Send a log. 2784C7234D

**Comment by chrisboer** [comment]
I think 433 Mhz has been changed towards 434 MHz frequence I got this message on Home Easy update that I had to approve this "Verzenden en ontvangen op de 434 MHz frequentie"  so logic that 433 Mhz will not work anymore after the update.

Did you also got this message on KaKu or did you not noticed this !
