### ISSUE TITLE
realtime-logging of zwave

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1152]
**What is your Homey version (Settings → System)?**
1.0.3

**What did you try to achieve?**
troubleshoot zwave by seeing the realtime log. Maybe add it to 
https://github.com/irritanterik/homey-realtime-logpage

**What was the result?**
No realtime-logging

**Any other remarks**
would make it easier to find issues with Zwave

**Comment by WeeJeWel** [comment]
What kind of things would you want to see logged? Apps can already run in debug mode with a realtime log.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
