### ISSUE TITLE
[Z-Wave] "wakeUpInterval" value isn't overwriting the default value anymore

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1153]
**What is your Homey version (Settings → System)?**
1.0.3

**What did you try to achieve?**
Change the default "Wake Up Interval" of z-wave drivers

*Please include detailed steps how we can reproduce the issue*
Set the "wakeUpInterval" setting in the "zwave" object and include a device

**What was the result?**
the default wake up interval is still being used, which can lead to the value being "0", graying out the save button.

**What did you expect as result?**
use the value specified in "wakeUpInterval"

**Any other remarks**

**Comment by TedTolboom** [comment]
@Caseda I suspect that you where trying to update it through the defaultConfiguration section... to which value?
I made a similar issue trying to update the keep_alive_time to 255 for the GreenWave powernode. Here I am only able to update to 120, otherwise your not able to complete adding the device.

See https://github.com/athombv/com.greenwavesystems/issues/24 for details

**Comment by caseda** [comment]
Wakeup interval has a huge range (Min: 30, Max: 16777215) and is a separate command class,
not just a setting in configuration command class. 
and setting it manually afterwards to that very value (different for certain devices) is also possible :wink:

**Comment by gruijter** [comment]
I have tried setting the eurotronic thermostatic valve device to a wake-up interval of 60 seconds and 30 seconds. In the settings of the devicecard this value I have set is correctly displayed. The device however never wakes up (as I can see in the debug log).

**Comment by gruijter** [comment]
Ok, I tried to set different values, and the device does wake up correctly if the interval is set to 3600s or more. So for fw 1.0.4 it seems to work correctly!

**Comment by WeeJeWel** [comment]
I cannot reproduce this bug. In Homey v1.0.5 I did fix an issue where the wakeup interval would not be applied when set manually AND the battery device was offline at that time.
