### ISSUE TITLE
Denon Heos Icon missing

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#1156]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

Open the device card to see device capabilities.

*Please include detailed steps how we can reproduce the issue*

Add Denon Heos device.

**What was the result?**

The "Play" button/icon is missing:

![heos](https://cloud.githubusercontent.com/assets/18025163/21130795/0d5f3afe-c10b-11e6-82ba-7e38c651176f.PNG)
![heos2](https://cloud.githubusercontent.com/assets/18025163/21130798/0f50f9d8-c10b-11e6-9758-b94b25de6aae.PNG)

**Comment by mike9011** [comment]
Nevermind.. probably its because i have a Heos Homecinema, which doesn't work at all.

You can close this issue.

**Comment by dnhaas** [comment]
this also appears for the heos 1

**Comment by nlrb** [comment]
The icon is missing when the app cannot determine the state (whether it is playing or not). An app restart might likely help.

**Comment by WeeJeWel** [comment]
Yes, this is expected behavior. The new Homey Smartphone App will show a better interface for media controls.
