### ISSUE TITLE
Devices not showing when having subzones

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1157]
**What is your Homey version (Settings → System)?**
1.0.3
IOS App 1.3 Build 30

**What did you try to achieve?**
See devices on my iphone app of "Buiten" with subzone "Schuur"

*Please include detailed steps how we can reproduce the issue*
Select "Apparaten"  from app menu go to zone "Buiten"

**What was the result?**
Subzone "Schuur"  is shown when just tab below : No devices are shown or when you try it again some devices are shown.
In the Homey desktop app or website app it works and shows all devices

**What did you expect as result?**
All devices in zone "Buiten" would be visible

**Any other remarks**
When removing subzone "Schuur" it works again. (Same behavior for Begane Grond and anything else with subzone)

**Comment by WeeJeWel** [comment]
Hi @chrisboer, can you post a screenshot (or better, movie!) of this happening?

**Comment by chrisboer** [comment]
Verstuurd naar je via gmail account

**Comment by WeeJeWel** [comment]
Thanks! Can you try again on firmware 1.0.4 (when it's released to stable)? We might have already fixed this bug.

**Comment by chrisboer** [comment]
It works with the 1.3.1 build 59 on IOS 10.2 again so still with 1.0.3 of Homey 
I updated to IOS 10.2 and then also the app to 1.3.1 issue resolved
