### ISSUE TITLE
wiki-pages for devices

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1158]
All zwave-devices need specific settings to work correctly (or have preferable settings). It would be helpful if we can create device-specific pages, related to the drivers on github. For that, wiki-pages would have to be enabled so under i.e. Fibaro or Greenwave there can be 20 pages with their specific device-settings but also links to the manuals etc.

**Comment by TedTolboom** [comment]
Fully support this request. 
Would appreciate if we / 'the community' could contribute to this; currently not possible / allowed.

**Comment by HansieNL** [comment]
Good idea.

**Comment by caseda** [comment]
It's up to the app developer anyway so the default settings are the best for what they do generally.
and get them to work properly in homey.
(also the reason why i leave some settings out of the settings page, so people can't f*ck it up.)

my 2 cents:
and there are NO preferable settings for all sensors, it is completely based on your situation, or even the situation the sensor itself is.
The default settings should be a midway ground for all "best" options.

It might be beneficial to create a wiki page with links to manuals, i don't think creating our own wiki with explanation of all settings isn't very viable, and prone to mistakes.
Maybe just a short explanation with examples which of scenarios to look at which settings, but not much more

**Comment by nattlip** [comment]
very good idea

**Comment by robertraaijmakers** [comment]
Very good idea! Would love to see something like this and also that it's easy to find for end users from within the store. Now only the github page is supported, but would love to see something like this added to the app.json to add extra links (all optional ofcourse):

 "links": {
        "home": {
            "uri": "https://www.mycompany.com"
        },
        "getstarted": {
            "uri": "https://www.mycompany.com/help/getstarted"
        },
        "learn": {
            "uri": "https://www.mycompany.com/features"
        },
        "support": {
            "uri": "https://www.mycompany.com/support"
        },
        "repository": {
            "uri": "https://github.com/mycompany/myextension"
        },
        "issues": {
            "uri": "https://github.com/mycompany/myextension/issues"
        }
    },
    "repository": {
        "type": "git",
        "uri": "https://github.com/mycompany/myextension"
    },

And that you see something like this in the store (but then Homey style of course):
<img width="178" alt="store-preview" src="https://cloud.githubusercontent.com/assets/1773099/21466042/5ca4d044-c9ba-11e6-89e2-382283ac21b2.png">

**Comment by nattlip** [comment]
last weekend i wrote a wikipaedia page for homey with the objective to share code snippets but it was deleted because of misuse wikipaedia as free hosting service

**Comment by robertraaijmakers** [comment]
@nattlip yes, I can understand that of Wikipedia. But you can also host a wiki on Github, or host one yourself. Wikipedia code is open source and everyone can set-up it's own 'wikipedia'.

**Comment by nattlip** [comment]
Outlook voor Android<https://aka.ms/ghei36> downloaden



On Sat, Dec 24, 2016 at 2:49 PM +0100, "Robert" <notifications@github.com<mailto:notifications@github.com>> wrote:


@nattlip<https://github.com/nattlip> yes, I can understand that of Wikipedia. But you can also host a wiki on Github, or host one yourself. Wikipedia code is open source and everyone can set-up it's own 'wikipedia'.

**Comment by WeeJeWel** [comment]
This is kind of solved with MeshDriver, featuring default Command Classes.

As for settings docs, I invite you to create an unofficial Homey wiki if there's really a need for it :)
