### ISSUE TITLE
Unreliable (fibaro?) Z-Wave / Hue

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1159]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.0.3

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*
Active 2 flows with a fibaro z-wave motion sensor:
1) to turn on the light when motion is detected
2) when the alarm cancles, turn off the light.

**What was the result?** / **What did you expect as result?**
Sometimes it works, sometimes it doesnt. It's hard to pin down but it's really annoying to come home and see that the light is still burning. Then when you walk into the room and it detects motion again, it turns off after the alarm is cancled again. 

**Any other remarks**
It's not just with the Hue, but a light that doesnt turn off is very visual so that makes it easier to notice. I also have a flow that sents an email with a picture of the front door when motion is deteced (Synology Surveillance) that also works 50/50. Please make these type of flows more reliable!
Also let me know what I can do to help debugging this if needed.

**Comment by caseda** [comment]
https://github.com/athombv/com.fibaro/issues/83 😄

**Comment by Tweaqer** [comment]
Looks a bit like that 👍 
![image](https://cloud.githubusercontent.com/assets/20989897/21194316/cae96d40-c22f-11e6-8572-26d670e8f474.png)
Here's one of my sensors with its data, see how motion is just blank but some of the other elements keep reporting

**Comment by djeskoswe** [comment]
Can this problem also affect fibaro wall plug?   sometimes don't respond on switch in gui but after Hw switch is works for a day or so.

**Comment by caseda** [comment]
@djeskoswe it's not related, your issue is with the Sending end, the issue this is talking about is about Receiving end.

Your issue looks more like a range problem, what is the distance? and does it go through other powered module(s)? (the other module closer then homey) to route to the wallplug

**Comment by djeskoswe** [comment]
It says green in range test,  and there as are one tkb switch between that works great.

Will try with a tkb switch as soon as the hw switch works on tkb ;)  use this on the coffe machine so hw switch must work.

**Comment by Tweaqer** [comment]
Issue still persists in Homey Firmware Versie: 1.0.4

Distance is about 3 meters from Homey, but other sensors are further away and do perform.
Its as if it doesnt cancel the motion sometimes.
![image](https://cloud.githubusercontent.com/assets/20989897/21289973/de5b8e26-c4aa-11e6-8e07-a5b517ee3ce2.png)

**Comment by sossienl** [comment]
Attached my screenshot, running Homey 1.0.4 and Fibaro 1.16.
The temperature of the Fibaro sensor (5 meters from Homey, without any walls), is not reporting the temperature as expected. It's the light green line. My settings are asking for an update every 180 seconds

<img width="609" alt="screen shot 2016-12-22 at 10 52 32" src="https://cloud.githubusercontent.com/assets/609650/21421837/4107937a-c835-11e6-9c60-6660c15f7afb.png">
<img width="950" alt="screen shot 2016-12-22 at 10 38 10" src="https://cloud.githubusercontent.com/assets/609650/21421838/41082c5e-c835-11e6-8829-df7c7d66cf38.png">

**Comment by RobinBol** [comment]
From the screenshot I can not accurately see what the actual reporting interval is. Could you tell me? And what did you expect exactly?

**Comment by Tweaqer** [comment]
Since the latest update I haven't had any problems, I will close it for now. Will let you know if it returns
