### ISSUE TITLE
After not giving confirmation answer, Homey does nothing

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#1161]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?

Trying to put out the lights when Homey is asking at 00.30 hours if there is any1 awake.

*Please include detailed steps how we can reproduce the issue

Made a flow with 

![confirmation-17](https://cloud.githubusercontent.com/assets/19249884/21238553/bf525a9e-c303-11e6-8dc8-0ce532774cd6.png)

**What was the result?**

![confirmation](https://cloud.githubusercontent.com/assets/19249884/21238559/c6546396-c303-11e6-8cb6-06df27a720df.png)

**What did you expect as result?**

If Homey gets no response at all he would take that as a NO

**Any other remarks**

We was talking about this at slack some time ago so was wondering if this was implemented in a soon to release FW maybe?

**Comment by bvdbos** [comment]
Is this the same issue as #997 and did it work after the fix in 0.10.6?

**Comment by Rocodamelshe** [comment]
Nope, this is not the same. 997 is solved yes.

**Comment by WeeJeWel** [comment]
Fixed in 1.0.5! Also added a 'password'-ish card:

![screen shot 2016-12-19 at 15 15 57](https://cloud.githubusercontent.com/assets/319873/21315790/1908b22a-c5fe-11e6-8b1c-9bb9cc456c50.png)

**Comment by Rocodamelshe** [comment]
Very nice, cheers

**Comment by Rocodamelshe** [comment]
Seems to me this is not fixed with the "normal" card:

![werkt-nog-niet-lijkt-het](https://cloud.githubusercontent.com/assets/19249884/21462408/53eb7e66-c95c-11e6-995a-ac616a576a5a.png)

The new card is working tho.

**Comment by Dijker** [comment]
Works as I expect, 
but maybe the description is not so intuitive!

@WeeJeWel So Maybe an information / description (i)

Tested it as follows:
If() And (Ask for  Confirmation / Vraag om bevestiging ) Then LED(Green)
Test Button!
- If I Answer Yes/ Ja => Green LEDRing
Anything els ... nothing

If() And (Don't get Confirmation / Krijg geen bevestiging ) Then LED(Green)
Test Button!
- If I Answer No/ Nee => Green LEDRing
Anything els ... nothing

As the first Card asks for Yes/Ja, the card title for an invers card (With Checkbox Checked) should be 
Ask for a No/ Vraag om een Nee.

I guess that is an other variant of implementation of the functional specification ;-)

@Rocodamelshe  
I guess with checking the Negative Checkbox on the card you expected a
NOT "Ask for  Confirmation/ Vraag om bevestiging" 
Making answering Yes/Ja => NOT (True) => False, stop execution
Anything else....  NOT (False) => True , continue execution

@WeeJeWel  I see a use case for that too...

**Comment by Rocodamelshe** [comment]
In this case u say: when u say yes or anything else.
In my case if every1 is asleep there is no anwser at all and the normal card can't handle that.
And my way of thinking is: When get no confirmation , fire the flow. So not saying anything is also no me thinks.
The newly added card is doin what i want but the old one isn't.

**Comment by Dijker** [comment]
》》And my way of thinking is: When get no confirmation , fire the flow. 
》》So not saying anything is also no me thinks.
I agree,  but that's not the way the developerror thought.

The not checkbox doesn't invert the normal working but asks for the negative answer. So the it requires you to answer  No to be true and is false in all other cases.

**Comment by Rocodamelshe** [comment]
Aha, is see what u mean now. Thnx.

**Comment by bvdbos** [comment]
@Rocodamelshe Is this fixed?

**Comment by Rocodamelshe** [comment]
Initial issue is not solved. The extra cards are doin their job somehow,
