### ISSUE TITLE
Add custom hints to Z-wave association groups (indicating purpose of group)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1162]
In order to bring the Z-wave apps to the next level, I would like to add additional remarks / hints to the association groups; basically to capture the meaning of these association groups (currently only covered in the device manual). 

Currently, the association groups and their hints are automatically generated; indicating the device limitations to add 1 or multiple amount of devices to this group.

My proposal is to still add this information but then appended to the custom description.

e.g. "Power value change reporting to main controller (Homey ID) - this group only allows 1 device to be added"

Possible structure to add this to the app.json:

```
associationGroupConfig[
    1: {
        "title": {
            "en": "own title"
        },
        "hint": {
                        "en": "Power value change",
                        "nl": "Power value change"
                    }
    }
]
```

**Comment by WeeJeWel** [comment]
Great suggestion! I've added it in Homey 1.0.5:

![screen shot 2016-12-19 at 17 12 16](https://cloud.githubusercontent.com/assets/319873/21319638/581227ca-c60e-11e6-9bae-b8ed240b428d.png)

Example usage:

```json
{
	"id": "FGK-101",
	...
	"zwave": {
		...
		"associationGroups": [
			3
		],
		"associationGroupsOptions": {
			"3": {
				"hint": {
					"en": "This is my app-specific hint"
				}
			}
		}
	}
}
```

**Comment by TedTolboom** [comment]
Good to hear! Looking forward to creating some pull requests afterwards...

**Comment by TedTolboom** [comment]
First implementation... this will help a lot! First PR will follow tomorrow.
<img width="603" alt="schermafbeelding 2016-12-20 om 23 28 17" src="https://cloud.githubusercontent.com/assets/17163431/21370469/23d79392-c70c-11e6-9f20-a63d36e54e38.png">
PS. typo is already removed...
