### ISSUE TITLE
[Feature Request] Flow actions: all on/off

### ISSUE THREAD

**Issue by MarcelAkerboom** [athombv/homey#1163]
Homey can do this all ready, "switch the lights on (in zone)".
Instead of faking speech-input, which costs computing, I think some flow actions are in order.

- SWITCH_ALL on/off (depends on your devices settings if it responds to this)
- Turn all **device_class** on/off
- Turn all **device_class** on/off in **zone**

So I can do the following for example:
- IF house_inactive is set true THEN turn everything off

**Comment by chrisboer** [comment]
Maybe something can be put in like if on holiday then disable "default"  flows.

But maybe this can be "created" with if away or date flow. 

It still is very difficult to make exceptions working with homey or any system

**Comment by bm480** [comment]
How is this implemented in 1.3.1? Is there a specific flow card that can be used to send commands to a group of related devices?

**Comment by bvdbos** [comment]
not a bug, better ask on the forum of slack first...
![2017-06-24 16_05_54- 835 flow - homey](https://user-images.githubusercontent.com/1064079/27509164-11169ca8-58f7-11e7-93a8-474baff211b2.png)
