### ISSUE TITLE
Flow with timer does'nt work anymore (1.04)

### ISSUE THREAD

**Issue by posthok** [athombv/homey#1164]
**What is your Homey version (Settings → System)?**

1.04

**What did you try to achieve?**
Turn off the light by a timer in a flow.

*Please include detailed steps how we can reproduce the issue*
Make a flow and turn a device off by  a timer.
After reboot end PTP still the sam issue.

**What was the result?**
The device turns off immediately. (timer does'nt work)

...

**What did you expect as result?**
It worked before in 1.03

...

**Any other remarks**

Log 1A108D61B5

**Comment by bvdbos** [comment]
works for me both with real trigger and with test-button

**Comment by posthok** [comment]
Issue closed after a reboot it worked again

**Comment by posthok** [comment]
This morning after a reboot i though it worked.
But afterfurther investigation of the timer issue i did a reboot and it seems alright. this evening i noticed that the gardenlight instantly turned off when i shut the door. I Pulled the plug but the problem is not solved. So i made a testflow. If date then turn on the gardenlight then if date turn off the light but wait 2 minutes. But 2 minutes are 2 seconds and the light turned off almost immediately. The device i used was a greenwave powernode 1
