### ISSUE TITLE
delay in minutes doesn't work anymore, is seconds now...

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1167]
**What is your Homey version (Settings → System)?**
1.0.4

**What did you try to achieve?**
Turn a lamp on and again off after two minutes using a delay

**What was the result?**
minutes are counted as seconds

**Any other remarks**
sprung out of #1164

**Comment by bvdbos** [comment]
`{"status":200,"result":{"id":"1df760c8-bd1a-4b20-b1b0-fe304838d5ac","title":"timed","enabled":true,"folder":false,"order":44,"broken":false,"trigger":{"id":"said_contains","uri":"homey:manager:speech-input","args":{"contains":"tafel"}},"conditions":[],"actions":[{"id":"on","uri":"homey:device:ae402362-53e9-4778-8ee2-e4ef214f2d55","args":{},"delay":{"number":"0","multiplier":"60"},"duration":false},{"id":"off","uri":"homey:device:ae402362-53e9-4778-8ee2-e4ef214f2d55","args":{},"delay":{"number":"4","multiplier":"60"},"duration":false}]}}`

also after reboot and PTP only 4 seconds instead of minutes:
![delay in sec instead of minutes](https://cloud.githubusercontent.com/assets/1064079/21289264/c492faea-c498-11e6-8b1b-7857a4ae458d.png)

**Comment by glijie** [comment]
altouch time of homey is good. The better logic app and the countdown app is 1 hour off when activated.

Homey time is f.e. 22:00 countdown app and betterlogic app is 21:00 hour when activated

**Comment by Dijker** [comment]
@glijie 
Both apps report Zulu time (GMT) these are correct, but 1 hour off to our GMT+1 we use an Humans here...
https://github.com/athombv/homey/issues/367#issuecomment-200200643
this has nothing to do with a execution delay not working. (while it worked before 1.0.4)

**Comment by glijie** [comment]
Hmmm indeed, I didn't read good, sorry

**Comment by jeroenbos22** [comment]
Yes same here since 1.0.4

**Comment by DieterKoblenz** [comment]
Same here since 1.0.4.

**Comment by dhanstede** [comment]
Same here since 1.0.4

**Comment by WeeJeWel** [comment]
Whoops! Fixed in 1.0.5

**Comment by bvdbos** [comment]
confirmed fixed in 1.0.5...
