### ISSUE TITLE
[DEVELOPER] emulate card definition 

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1168]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

Do some API calls on flow card definitions

**What was the result?**

Found out the build-in flow card argument for the emulate card is not defined as an array, but single object:
```
          {
            "id":"emulate",
            "title":{
              "en":"Emulate speech",
              "nl":"Emuleer spraak"
            },
            "hint":{
              "en":"Act as if Homey has heard something",
              "nl":"Doe alsof Homey iets heeft gehoord"
            },
            "args":{
              "name":"transcript",
              "type":"text"
            }
          }
```

**What did you expect as result?**
Consistancy
...

**Any other remarks**
Flow seems to be working though
...

**Comment by Fire69** [comment]
For some extra info:
Flow works, but using irritanterik's flow viewer does not function completely because of this.

**Comment by WeeJeWel** [comment]
Whoops! Fixed in 1.0.5

**Comment by WeeJeWel** [comment]
What are you building, by the way? 👍

**Comment by Fire69** [comment]
Flow viewer, working really well, like the fact that you can reorder the cards! :) 

https://github.com/irritanterik/homey-realtime-logpage
