### ISSUE TITLE
Smartwares Motion has big delay

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1169]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

Trigger Motion on Smartwares 

*Please include detailed steps how we can reproduce the issue*

**What was the 

It does Trigger but with a huge delay, sometimes up to a minute 

**What did you expect as result?**

To work as fast as lightning

**Any other remarks**

No skippy 😃

**Comment by BasKiers** [comment]
Hi,

This should not happen. Could you open the pairing wizard for the motion sensor in google chrome and then open the chrome developer tools by going to Menu->More Tools->Developer Tools and then clicking the tab "console". When you trigger the motion sensor a message like this should directly appear in the console: 
![image](https://cloud.githubusercontent.com/assets/6036127/23134316/9fde31c2-f794-11e6-80e5-bef28d8fab5d.png)

Could you check if this is the case and reply with a screenshot of all messages you got and what you did to trigger the messages?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment]
Does this issue persist on Homey version 1.3.0-rc.7, using the latest smartwares app version?

**Comment by jeroenbos22** [comment]
Yes fixed
