### ISSUE TITLE
Luminance change using Fibaro multisensor does not work

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#117]
If have the following simple flow

![image](https://cloud.githubusercontent.com/assets/17158826/12986158/1f9d1c82-d0f6-11e5-872c-eb422358bb73.png)

The correct values are received by homey
![image](https://cloud.githubusercontent.com/assets/17158826/12986201/47569a50-d0f6-11e5-8e0f-fcecfb099875.png)

Is does not work.

**Comment by ocatie** [comment]
Looking into it.

**Comment by ocatie** [comment]
If you test your flow, does the socket turn on?

**Comment by JohanKuster** [comment]
Nope. If I replace the socket by a Voice it still does not work. But according to Emile test cannot be used when using a token[ 49](https://github.com/athombv/homey/issues/49)

**Comment by JohanKuster** [comment]
Without the AND the test is turning on the socket

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18. Thanks for reporting!

**Comment by JohanKuster** [comment]
0.8.18 today?
