### ISSUE TITLE
devicecard target_temperature slider timeout too short, zwave queue is clogged before zwave device wakeup

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1170]
**What is your Homey version (Settings → System)?**

1.0.4

**What did you try to achieve?**

Adjust the target temperature using the slider wheel in a device card (eurotronic zwave device)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

Not only the intended target temperature is sent to the device, but also intermittent values. This clogs up the queue of the settings to be send when the zwave device wakes up. This queue seems to have a maximum of 6 values. This results in that in many cases not the intended value is set in the device.   
...

**What did you expect as result?**
That only the intended target_temperature is put in the queue

...

**Any other remarks**

It seems the slider timeout is set too short. I am using a webbrowser with mouse to move the slider in the devicecard. Especially when I want to make large changes in temperature the problem occurs.
...

**Comment by WeeJeWel** [comment]
Are you using a 'thermostat' component or a 'slider' component here?

FYI: In both cases, the debounce timeout is set at 300ms, and the timer will be reset when a change has been made inbetween, restarting the timer.

**Comment by gruijter** [comment]
it is the semi-circle. It is the default one presented for the default capability target_temperature. With a mouse 300ms is probably not long enough. It would be better to set it if the browserwindow loses focus, or make it more like 1000ms. Especially when I have to turn the wheel multiple times to get to the right setting.

**Comment by Inversion-NL** [comment]
More or less the same when setting speaker volume in Homey settings.
Intermittent values are also spoken by Homey's voice...

**Comment by markaswift** [comment]
I had the same issue with the vacuum default app. I modified it and added a 2 second debounce.

**Comment by WeeJeWel** [comment]
This should be fixed in an App itself, so please create an issue for the appropriate app.
