### ISSUE TITLE
Push messages are not expandable

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1174]
When I receive long push messages on my Sony Z5, the text is not complete. Is it possible to wrap the text so I can read the complete notification?

**Comment by Dijker** [comment]
I have seen this also on Samsung S7 Edge, would be nice to read the full msg,

**Comment by WeeJeWel** [comment]
Can you make a screenshot when this happens?

**Comment by Fiek1** [comment]
![screenshot_20161220-195941](https://cloud.githubusercontent.com/assets/18599711/21364112/badc223e-c6ef-11e6-8e78-c64e28878c2e.png)

See the screenshot. When I tap on the message it disappears end the Homey app opens.

**Comment by joachimroeleveld** [comment]
Is now in production (2.4.7)

**Comment by Inversion-NL** [comment]
I guess you mean in version 2.4.8?
Anyhow confirmed working!
