### ISSUE TITLE
iPhone app stops updating after being backgrounded

### ISSUE THREAD

**Issue by vogon1** [athombv/homey#1175]
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

- Start the iPhone app
- Press home button and do something else
- After a while, start app again
- If the app was not (yet) removed from memory, old readings are shown and will not be updated

**What was the result?**

Old values shown in the app.
Removing the app from memory, and starting it again results in getting recent readings that are automatically updated as well.

**What did you expect as result?**

Whenever the app is opened on the phone, the readings are refreshed.

**Any other remarks**

**Comment by chrisboer** [comment]
Same issue here

**Comment by Fiek1** [comment]
I have it both on on iPhone 6 and Android Sony Z5

**Comment by chrisboer** [comment]
Problem is I have to shutdown the app and restart it to react to speach

**Comment by jeroenvollenbrock** [comment]
This problem will be fixed in an upcoming Homey update (not the app).

**Comment by chrisboer** [comment]
Question will also the other issue be resolved regarding the selection of main area's in the IOS app by that Homey update ?

**Comment by bvdbos** [comment]
What issue # is that?

**Comment by vogon1** [comment]
A fix was staged for a release, but seems to be pulled. It does not work yet on 1.1.9.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
