### ISSUE TITLE
iOS push confirmation not working 

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1176]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

Get a push confirm

*Please include detailed steps how we can reproduce the issue*

Made a push confirm in a flow and both had it run by itself and used the test button

**What was the result?**

It gave a normal push notification without awnser possibility. If I test the flow I can see homey is awaiting an awnser but I cant give one.

**What did you expect as result?**

To get a push confirm on my phones

**Any other remarks**

Tested on both iPhone 5s and 6s before and after app update of 20 dec. On slack I see Many people have got it working and for Some it doenst (both iPhone and Android)

**Comment by bvdbos** [comment]
What IOS-version, what Phone-app version ?

**Comment by jeroenbos22** [comment]
Iphone 5s and 6s both on 10.0.2. Homey on 1.0.5 and App is the latest vrsion (update 20th dec). Just restarted app and rebooted Homey, no luck

**Comment by jeroenbos22** [comment]
I now notice that if I have the app open it will show the confirm. Is the app is not open I get the notification. If I then click the notification the app opens but then nothing.

**Comment by spoelly** [comment]
I have done a test on a iphone 6 with iOS 10.2.1, works like a charm. When app is open and closed

**Comment by jeroenvollenbrock** [comment]
@jeroenbos22 Does removing the app, removing the phone at my.athom.com, installing the app, logging in, and reselecting your phone in the homey flow, solve the problem for you? I suspect a bug in one of the beta builds caused your notification configuration to become corrupt.

**Comment by backslashgithub** [comment]
removing the phone at my.athom.com ?

**Comment by jeroenbos22** [comment]
Doesnt work. I did:
- removed app on both phones
- rebooted the phone
- removed phones from account
- Reinstalled app on both phones
- They showed up in the athom account after reinstall

Outcome: Same behaviour, there is no confirmation when the app opens when I click the notification. If the app is already open and I send it it works.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by backslashgithub** [comment]
hi there, is get it working by DHCP reservation on the router, after rebooting the phone it gets the IP that you want. and so its not changing for homey. did it a week ago and still going strong :-)
