### ISSUE TITLE
IR Yamaha receivers not available

### ISSUE THREAD

**Issue by posthok** [athombv/homey#1178]
**What is your Homey version (Settings → System)?**

1.05
**What did you try to achieve?**
Add my Yamaha receiver remote control. In former firmware versions it was still available but for some reason its removed. 

The former Yamaha database was working for me.

**Comment by BasKiers** [comment]
Hi,

The signal database is updated for Homey v1.5.4 and includes "Yamaha Receiver RX.RS.T-S Series All Models". I hope this is the signal you mention. You can add it when your Homey updates to 1.5.4.

Regards,
Bas

**Comment by Dutchy-** [comment]
I will test this on a Yamaha RX-V475 when 1.5.4 becomes available
