### ISSUE TITLE
Somfy Commands not working

### ISSUE THREAD

**Issue by edtst** [athombv/homey#118]
I successfully paired 3 Somfy shades. I can control them by clicking on the device and then up or down. But Homey does not respond to any command regarding somfy nor does it state in the app what I should use.

Please specify in the app what commands can be used

**Comment by Dennishacq** [comment]
Hey @edtst ,
Homey does not have any voice commands for shadings yet, this will be added in an upcomming Homey update.

**Comment by Tweake** [comment]
Has been added. Opening and closing window coverings can be done using voice commands as of version 0.8.20. Partially opening window coverings which have that capability will be added in 0.8.22. ("Close the blinds 75 percent", for example)

**Comment by chamidmedia** [comment]
In 0.8.20, which build in commands can be used for window coverings?

**Comment by Tweake** [comment]
Some English examples:

open the curtains
close the blinds in the living room
open the drapes in the bedroom
close the kitchen window covers
it would be awesome if you could open the living room curtains for me

...

And in Dutch:

open de lamellen
sluit de rolgordijnen op zolder
doe de gordijnen in de slaapkamer dicht
...

Homey is not listening for specific command phrases, but instead checks for a combination of elements to determine what you would like Homey to do. So these examples are just some of the things which will work, but I hope it gives you a sense of what you could say to Homey. :)
