### ISSUE TITLE
Presence not known to Homey after reboot

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1183]
**What is your Homey version (Settings → System)?**
1.0.3
IOS app 1.3.1 build 59 

**What did you try to achieve?**
See if the presence of accounts on homey

*Please include detailed steps how we can reproduce the issue*
Deleted all the status messages in homey desktop app and reboot the homey system

**What was the result?**
Presence of homey account users was incorrect as they were home but homey stated that these persons where not available

**What did you expect as result?**
After a reboot of homey the presence of the 2 accounts on homey as they were both at home

**Any other remarks**
Within the IOS app you have to change settings of home detection to "radius" 0 and then back to 300m to reinitiate the presence of people at home.

**Comment by WeeJeWel** [comment]
This is intentional - after a reboot, Homey could've been offline for years. Setting an 'expiration date' also is somewhat ambiguous.

Homey has not been designed to be rebooted often. If you find a need for that, please report those issues, so we can work on that!
