### ISSUE TITLE
no app-id visible in flow

### ISSUE THREAD

**Issue by Thijxx** [athombv/homey#1184]
**What is your Homey version (Settings → System)?**
1.0.3

**What did you try to achieve?**
I try to find what app/then/device is used in a flow.

After trying 3 apps to open my blinds I finally found the right one, it was late and I drank a crate of beer by then so my memory is a bit blurred. The next day there is no way to find out what device/app is used to open the blinds.

**What was the result?**
Typical angry user blaming developers for all personal dismay and evil in the world.

**What did you expect as result?**
Open Flows, click the flow for my blinds, click on the 'then' card and get **some** information. For example the app that is used.

**Any other remarks**
Overall monitoring and information is almost non-existent, this causes many questions for you to answer and that keeps you from developing cool stuff.

**Comment by WeeJeWel** [comment]
The name of the device is displayed below the icon, isn't it?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
