### ISSUE TITLE
No Log file

### ISSUE THREAD

**Issue by Thijxx** [athombv/homey#1185]
**What is your Homey version (Settings → System)?**
1.0.3

**What did you try to achieve?**
Read to log file to see what is going on

**What was the result?**
Me looking for a non-existing log file. Taking a peek at 'Insights' and noticing there are only a few functions for a few apps there and then getting confused about that screen.

**What did you expect as result?**
A log file, showing me what speech-to-text was done, the flow information, all logs for all apps etc.

**Any other remarks**

**Comment by WeeJeWel** [comment]
Hi Thijxx,

Some logs are available, some aren't. I hope the following helps:

Visit /manager/speech-input/ for a history of what Homey heard
Visit /manager/speech-output/ for an active history of what Homey said

App logs cannot be read by users due to security reasons

**Comment by Thijxx** [comment]
I understand, you may want to rewrite this page then https://www.athom.com/en/support/KB000021/ because the data is not mine and therefore I am not in control.
