### ISSUE TITLE
Danfoss / Devolo battery controlled TRV: E5 back again (from v1.0.3+)

### ISSUE THREAD

**Issue by michelderu** [athombv/homey#1187]
**What is your Homey version (Settings → System)?**

1.0.4

**What did you try to achieve?**

Use the Danfoss/Devolo TRV without the E5 issue.

**What was the result?**

On 1.0.2 the device was working perfectly. Very responsive when pressing a button on the device also and a rock solid bell + wireless icon. This was after the WAKEUP_NO_MORE_INFORMATION was implemented into the firmware. In the Devolo App I still use the pollIntervall as suggested by Robin.

On 1.0.3 according to the release notes something was changed in the WAKEUP_NO_MORE_INFORMATION implementation. I think I saw that also in the logging of the App as it seemed that all potentially possible command classes were polled. Additionally it had impact in the device. Because when pressing a button on it (like + or -) it now took a long time for the display to respond and the bell + wireless icons were blinking indicating an error in the communication!

Now after a while I'm getting the E5 error back again.

So in my mind something was changed between 1.0.2 and 1.03 and upwards impacting the WAKEUP_NO_MORE_INFORMATION implementation which leads to the device going into error mode again.

**What did you expect as result?**

Can you please have a look into the changes between 1.0.2 and 1.0.3 and upwards regarding the communication with battery operated devices?

**Comment by Rob-Houweling** [comment]
I can confirm this bug still exists on firmware version 1.1.0

**Comment by RobinBol** [comment]
We are aware of this issue and working with Danfoss to resolve it.

**Comment by jhutjens** [comment]
Same issue here with 3 danfoss lc-13's. It was working properly before the big z-wave update when there was no danfoss app yet.

**Comment by michelderu** [comment]
@RobinBol Can you please update us on the progress?

**Comment by bvdbos** [comment]
How is this running on Homey Firmware 1.1.4? There have been a number of zwave-improvements...

**Comment by RobinBol** [comment]
Sorry no update on this matter as of yet, but we sure are looking into it; takes some time to find the specific communication error causing this error on the device.

**Comment by Rob-Houweling** [comment]
Any news on this issue? This is starting to cost me a lot of batteries by now. Issue has been open for a couple of months by now. Please give this issue a higher priority.

**Comment by michelderu** [comment]
Athom, when can we expect a fix for this? It's a whole range of devices suffering from this issue. Like the Danfoss, Devolo, Popp, etc.

It was working in Homey v1.0.2 when WAKEUP_NO_MORE_INFORMATION was implemented. Can't you just bring this back? Or allow the App builder to explicitly call the WAKEUP_NO_MORE_INFORMATION after the measure_battery?

To re-iterate, previously I mentioned this:
I've been going through a thread about a driver for SmartThings. There the E5 error was fixed after a while and some help by Danfoss.

It seems the trick there was to send a WAKE_UP_NO_MORE_INFORMATION after the device sent the Wake Up Notification to the controller and all GETs and SETs have been handled.

Pseudo code from https://github.com/richdp/mysmartthings/blob/master/Danfoss%20LC13%20v0.7:

OnWakeUpEvent:

batteryGet
thermostatSetpointSet
thermostatSetpointGet
wakeUpNoMoreInformation

**Comment by RobinBol** [comment]
Well, it not like we just removed the WAKE_UP_NO_MORE_INFORMATION, it is still there. We are currently waiting for a review of the Z-Wave traffic between Homey and LC-13 by Danfoss, hopefully that will give us enough information to fix this.
