### ISSUE TITLE
Tags search for devices gives no results

### ISSUE THREAD

**Issue by lubbertkramer** [athombv/homey#1189]
**What is your Homey version (Settings → System)?**
1.1.0-rc.1

**What did you try to achieve?**
Search in the tags bar for device. Searching for tags is working

**What was the result?**
No results for the device

**What did you expect as result?**
Get all the tags for the device that i was searching for

**Any other remarks**

Devices that i was searching
![git1](https://cloud.githubusercontent.com/assets/8224586/21468061/e6fa352a-ca02-11e6-9ea3-6e4e3bdfa17a.PNG)

Search first letters
![git2](https://cloud.githubusercontent.com/assets/8224586/21468062/e87b2d82-ca02-11e6-9364-8ed7afcc46ac.PNG)

Search complete name
![git3](https://cloud.githubusercontent.com/assets/8224586/21468063/e9a59454-ca02-11e6-834f-9932e8479810.PNG)

**Comment by denniedegroot** [comment]
I encountered the same behavior and also would like to search for the device.

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by bvdbos** [comment]
confirmed, fixed...
