### ISSUE TITLE
Android App: Navigation bar not visible on Settings screen

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#119]
The UX is not optimal when navigating from the devices screen to the settings screen (nor the media screen). The menu bar is not visible on top of the screen.

**Comment by goldenice** [comment]
Why is that not optimal? It gets out of your way; the only time any useful info is up there, is when there is a zone. The only thing that's actually useful I imagine is the 'hamburger'-icon, but the left hand menu can be triggered just as well by swiping in from the left.

**Comment by irritanterik** [comment]
Never used the swipe navigation before. But that works. It was not an
intuitive experience thou. But hey, it was just my opinion / experience.
Maybe some in-app first time usage tips can improve this experience if you
don't like the menu or hamburger on the screen.

**Comment by goldenice** [comment]
I think I might add the hamburger icon without the whole bar. This would be coming in app version 1.2.x then, so a bit of patience please.
