### ISSUE TITLE
add speech-input and speech-ouput to UI

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1190]
**What is your Homey version (Settings → System)?**
1.0.5

**What did you try to achieve?**
Direct people to:
See what Homey heard on http://[homey-ip]/manager/speech-input
See what Homey said on http://[homey-ip]/manager/speech-ouput

Users claim [homey-ip] can't be found ;-) So please add a link in the settings-menu...
[edit] Also, lots of times people go to these pages without logging in correctly since the windows-app is the preferred UI...

**Comment by chrisboer** [comment]
What is your Homey version (Settings → System)?
1.0.5

indeed 
http://[homey-ip]/manager/speech-input I can see the page can type what I want but don't see anything appear on screen.

with 
http://[homey-ip]/manager/speech-ouput I get the following error message on screen
Cannot GET /manager/speech-ouput

**Comment by bvdbos** [comment]
You're not logged in correctly. First go to https://my.athom.com, login and then alter the URL...

**Comment by WeeJeWel** [comment]
There are merely tools meant for debugging, so this won't be added to the menu.
