### ISSUE TITLE
Aeontec Siren Gen 5 not visible in Devices

### ISSUE THREAD

**Issue by LeCauf** [athombv/homey#1191]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

I added the Aeotec Siren Gen 5 as a device using the Aeotec app (v1.2.4). This worked (it shows up in Devices), but the device doesn't show in Flow. 

**What was the result?**

The device was added successfully, but does not show up in Flow

**What did you expect as result?**

The device to show up in Flow so it can be used...

**Any other remarks**

...

**Comment by RobinBol** [comment]
What would you be able to do? Currently the device does not support any Flow cards, it was added by a community member. I can imagine you would like to turn the siren on/off, anything else?

**Comment by RobinBol** [comment]
Ok, I see there is already a similar issue reported at the Aeotec app repository. Perhaps a community member will pick it up, otherwise I will take a look at it. Thanks for reporting.

https://github.com/athombv/com.aeotec/issues/34

**Comment by RobinBol** [comment]
So, I went ahead and added the flow cards, but could not test it yet. I have created a branch with the changes, I you'd like you can download the app from https://github.com/athombv/com.aeotec/tree/ZW080-onoff-flow-cards and side load it on your Homey to test the flow cards, just let me know if they work then I'll release them with an update of the Aeotec app.

**Comment by LeCauf** [comment]
Hi Robin,

Not sure if this issue has progressed in the mean time, but I’m happy to test it. However, I have to admit that I don’t know how to side load apps…. How do I do this?

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/1448/how-to-cli-install-method

**Comment by RobinBol** [comment]
Hi! You can download the zip file of the aeotec app from here https://github.com/athombv/com.aeotec/tree/ZW080-onoff-flow-cards, then follow these steps to upload it to your Homey: https://developers.athom.com/library/getting-started/ (you do not have to create a project as that page says, just use the run command from inside the aeotec app folder. If you do not manage, please let me know.

**Comment by backslashgithub** [comment]
after side load it on my Homey;
Error: missing_options_capability: measure_battery
    at /node_modules/homey-zwavedriver/lib/ZwaveDriver.js:47:11
    at Array.forEach (native)
    at ZwaveDriver (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:45:28)
    at Object.<anonymous> (/drivers/ZW100/driver.js:209:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /homey-app/manager/drivers.js:74:27
    at Array.forEach (native)
    at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
    at /homey-app/manager/drivers.js:20:38
    at /homey-app/homey.js:1:1080
    at Array.forEach (native)
    at Object.<anonymous> (/homey-app/homey.js:1:1058)
    at emitNone (events.js:67:13)
    at Object.emit (events.js:166:7)
    at /bootstrap.js:226:9
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

--- INFO: com.aeotec has been killed ---
![schermafbeelding 2017-01-28 om 11 49 29](https://cloud.githubusercontent.com/assets/20621496/22396081/aeff17ee-e550-11e6-805e-badf34786587.png)
![schermafbeelding 2017-01-28 om 11 50 05](https://cloud.githubusercontent.com/assets/20621496/22396082/af005ff0-e550-11e6-9514-387c5538e245.png)

ps
after closing (ctrl +v in terminal) the app is un installed, i need to install the app again. how do i save the old app before trying a beta app? thx in advance.

**Comment by bvdbos** [comment]
If you use "athom project --install" instead of "athom project --run" it won't get de-installed and after some tests you can just re-install the appstore-version over the test-app...

**Comment by backslashgithub** [comment]
i mean, re-installing the "old" app with the set parameters and config setting etc .
