### ISSUE TITLE
Cannot pair my KaKu TMT-502 remote control

### ISSUE THREAD

**Issue by JosStultjens** [athombv/homey#1193]
**What is your Homey version (Settings → System)?**

Homey v1.0.5
Kaku App v2.8.8

**What did you try to achieve?**
I tried to pair the KaKu remote Control TMT-502 (Note: This is NOT the ATMT-502, but the older version)

*Please include detailed steps how we can reproduce the issue*
I tried to add the TMT-502, but it is not in the list of KaKu devices

**What was the result?**
I could not select the remote from the list.
...

**What did you expect as result?**
I want to be able to select this remote control from the KaKu list of decices, so I can use it to control my Kaku Lights with this remote control.
...

**Any other remarks**
Note: I tried to pair the TMT-502 by selecting Kaku device YCT-102. I was able to use the ON&OFF commands of the first 4 Units(= like buttons). But no response on units 5 to and including 16. Seems like unit 5 is not Channel 2 button 1, but channel 3 button 1. Unit 9 is channel 2, button 1. Unit 13 is channel 4, button 1. So the the YCT-102 can be mapped to the TMT-502. 
This is a workaround, but not like it should be. Please add the TMT-502 with the correct button mapping.

**Comment by BasKiers** [comment]
Hi, 

I will look into adding the TMT-502, thank your for your detailed explanation concerning the button mappings.

Regards,
Bas

**Comment by JosStultjens** [comment]
Hoi Bas,

 

Ik zie dat je in de vorige kaku release de TMT-502 toegevoegd hebt.

Sorry ik had het niet eerder opgemerkt.

Ik heb mijn TMT-502 gepaired en merk dat enkele units verkeerd gemapped zijn.

 

Unit 1 t/m 4 is ok

 

Unit 5 is mapped als 9

Unit 6 is mapped als 10

Unit 7 is mapped als 11

Unit 8 is mapped als 12

 

Unit 9 is mapped als 5

Unit 10 is mapped als 6

Unit 11 is mapped als 7

Unit 12 is mapped als 8

 

Unit 13 t/m 16 is ok

 

Moet ik hiervoor een issue aanmaken op github, of is deze mail voldoende?

 

Groeten,

Jos Stultjens

**Comment by BasKiers** [comment]
Hi,

Sorry for the late response. I've fixed this issue in version 3.0.1 of the KaKu app. Could you confirm that the flow cards do work correctly for units 5 to 12?

Regards,
Bas

**Comment by JosStultjens** [comment]
Hi,

Unfortunately I havent had time yet to check it.
Next week I will have some time to test.

I Will let you know ik all is ok.


Kind regards,
Jos Stultjens
Op ma 20 feb. 2017 om 14:21 schreef Bas Kiers <notifications@github.com>

**Comment by JosStultjens** [comment]
Hi Bas,

I have repaird the remote control TMT-502.
Now all units are mapped correctly.
Thank you.
