### ISSUE TITLE
Weird memory bar

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#1195]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

Check memory usage in Settings

**What was the result?**

Weird bar graph with only 1 color
![image](https://cloud.githubusercontent.com/assets/1757287/21518418/9c1a1a5c-cce6-11e6-955d-c087b2241eef.png)

**What did you expect as result?**

Lots of pretty colors :-P

**Any other remarks**

Here's a log if it can help: 4EB7F2F883

On Slack, @rocodamelshe reported the same issue, but additionally, his Homey reported 1GB of memory!?

**Comment by Rocodamelshe** [comment]
![memory1](https://cloud.githubusercontent.com/assets/19249884/21518583/d6db67da-cce7-11e6-956c-28dd1ef1d334.png)

Same here without any colors.
At the moment of writing this "overig" is at 739,61MB

**Comment by Fire69** [comment]
Back to normal after a reboot.

**Comment by Rocodamelshe** [comment]
Same here. Did send the logs (before----(RRod-----PTP)------and after) to @AnnemarieHuijink

**Comment by Rocodamelshe** [comment]
Almost at 400 again after 9 days uptime. Homey stops listening and is not responding at all to voice commands. @AnnemarieHuijink told me some time ago that @WeeJeWel was gonna look into it but never heard anything ever since.

**Comment by glijie** [comment]
did a reboot here and after a few days i have the same issues as mentionned here

**Comment by Dijker** [comment]
Here the same after some days nothing special done with Homey:
![image](https://cloud.githubusercontent.com/assets/12412734/21955154/77525c8e-da65-11e6-8f47-b6065a1cfb75.png)

almost 12 days uptime: 1022351 Seconds
Send Log 5CEB68131F

**Comment by bvdbos** [comment]
I suspect it's memory-management related to callig API-endpoints (Homey logger) for now...  
I have the same, send a log : AC4202D2B2
![2017-01-14 15_04_39- 229 settings - homey](https://cloud.githubusercontent.com/assets/1064079/21955404/e0ff3a4e-da6a-11e6-9a26-d2cde4b5f77b.png)
After a reboot:
![2017-01-14 15_12_45- 229 settings - homey](https://cloud.githubusercontent.com/assets/1064079/21955470/faad5c0e-da6b-11e6-98cb-47665381b0b2.png)

**Comment by corvdniet** [comment]
Maybe this helps finding out what causes this: http://forum.athom.com/discussion/2609/memory

**Comment by chrisboer** [comment]
Same here 
![memory_homey](https://cloud.githubusercontent.com/assets/23163409/22185103/7f25db4a-e0df-11e6-9bc3-dc5a6331bf0a.jpg)

**Comment by bvdbos** [comment]
System memory steady at 165 MB for me...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists in v1.1.9 or not?

**Comment by Fire69** [comment]
Seems ok for the moment, although it did do a reboot to update of course, so I don't know in the long term...

Noticed something else, don't know if this is intented behaviour.
When I hoover the memory bar, the last part changes color:
![image](https://cloud.githubusercontent.com/assets/1757287/22928956/5d983b26-f2b9-11e6-8614-8bee03250433.png)

**Comment by corvdniet** [comment]
![image](https://cloud.githubusercontent.com/assets/22527207/22964905/3be5eb8e-f35b-11e6-9be7-463ea1bfa20c.png)
Issue still persists. There are a couple of suspect apps that cause this: Homey Logger, HomeyDash (not sure), iCalendar, IFTTT and Smart Presence. With these enabled, the "system" memory increases slowly.

Here's how memory looks after a restart without these apps:
![image](https://cloud.githubusercontent.com/assets/22527207/22964978/90fabffa-f35b-11e6-8d6e-a072dfb260aa.png)

By the way: I have the same hoover behaviour with the memory bar as Fire69

**Comment by satbopper** [comment]
homey 1.1.9 
i did a test for several days according the fact that everyday the swap and memory is increasing to above 350
i closed (did not remove) the homey logger app and now it is not only stable but it is even below 200 with a swap of 300 and stable as a rock
it is not my intention to bring down someone's work but it is remarkable
if i activate the logger app again it will start to rise every day

**Comment by corvdniet** [comment]
Homey 1.2.0. 
I don't think the increasing amount of Systeem memory problem is solved in this release.

**Comment by corvdniet** [comment]
If 300 Mb Systeem and 360 Swap Mb after only a day or five is "normal" then OK. Otherwise I would ask you to re-open. (I'm on 1.2.2)

**Comment by corvdniet** [comment]
Since 1.3.0RCxx and 1.3.0 the amount of Systeem memory is increasing twice as fast as before. Really hope the memory leak(s) will be solved soon.

**Comment by corvdniet** [comment]
Since I removed iCalendar (no offence), the System memory increases not fast anymore. BUT is still gets bigger every day despite 1.5.0.RC.2

**Comment by bvdbos** [comment]
did it?

**Comment by corvdniet** [comment]
In 7 days (1.5.0-rc.5) the system memory increased from zero to 165 Mb. Don't know if the benefits go to removing iCalender or to updates in the Homey release.

**Comment by corvdniet** [comment]
Since 1.5.0-rc.9 very stable (System) memory. Never seen larger amounts than 30 Mb.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
