### ISSUE TITLE
[SOLVED] Can't Pair Thinking Cleaner

### ISSUE THREAD

**Issue by Starf0x** [athombv/homey#1197]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

Try to add the thinking cleaner after reinstalling app.
It searches the network and doesn't find it.
I did these actions because the Homey stated he was offline. I'm as I type this, connected to the thinking cleaner via its own page.

**What was the result?**

No Pairing

**What did you expect as result?**

Detection of the online roomba.

Send Log: ECF4F262A0

**Comment by bvdbos** [comment]
Did you already try rebooting Homey or Pull the Plug for a couple of minutes?

**Comment by Starf0x** [comment]
Did the reboot. Unplug? Really?

**Comment by Starf0x** [comment]
I restarted the Roomba, that did solve the issue.
It has served me for 1223 km, so she was missed :)
