### ISSUE TITLE
Homey seems not to send out any IR-signal

### ISSUE THREAD

**Issue by TimvanSteenbergen** [athombv/homey#1198]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
Install and use KPN's remote control (see https://www.kpn.com/service/televisie/installeren/afstandsbediening/gebruiken.htm) and make the tv and the settopbox respond to Homey

*Please include detailed steps how we can reproduce the issue*
- add apparaat, Homey -> IR remote
- choose none of the given one's but 'kopieren van afstandsbediening'
- press one button 15 times and give it a name
- repeat this for every button
- Press Voltooien and give the new apparaat a name
Now:
- create a new flow
- add any trigger
- add the new apparaat to the column "...dan" 
- make it send out any signal, for instance 'tv aan/uit'

**What was the result?**
Result is: no response from the tv when clicking 'tv aan/uit', nore from the settopbox with any of the other buttons.

**What did you expect as result?**
I expect the tv to respond to the pressed button (for instance 'tv aan/uit') neither does the settobbox respond to any of the buttons

**Any other remarks**
IR-light is visible using your phone's camera. Filming the Homey during running the test-flows I don't see the IR-light from anywhere.

**Comment by bvdbos** [comment]
same as #966 ?

**Comment by TimvanSteenbergen** [comment]
Indeed, it is similar to 966. unfortunately, 966 does not seem to have a solution yet. Has anyone tried the trick of recording the Homey with their phone to see if any IR-light shows up, sent out by the Homey? Mayben we are all having faulty IR-modules in our Homeys.
My tv is a Panasonic Viera, TH-37PV7F, my settopbox is a HMB2260 Arcadyan. They both don't respond.

**Comment by Rocodamelshe** [comment]
I tried the "trick" yes:
https://forum.athom.com/discussion/comment/41447/#Com ment_41447

**Comment by TimvanSteenbergen** [comment]
Thanks! Great movie, nice music too. I had some succes at last. Tried it with the remote of my 5-year old Matsui dvd player and that worked fine! The IR-signal from the Homey is only visible using my phone when the angle is exactly right. So, the good news: my Homey is able to send IR-signals. The bad news: appearently Homey can't replicate the remote of the KPN.
