### ISSUE TITLE
Sonos boxes no longer respond

### ISSUE THREAD

**Issue by TimvanSteenbergen** [athombv/homey#1199]
**What is your Homey version (Settings → System)?**
1.0.2

**What did you try to achieve?**
Make Homey press Play on any of the Sonos-boxes

*Please include detailed steps how we can reproduce the issue*
- install the available Sonos-boxes, in my case one Bridge and twice a Sonos Play:1 box
- include them in any flow making Homey press Play and start playing music on the Sonos boxes

**What was the result?**
- no sound from my boxes
- In the Homey-desktop-app a red triangle appears in the Sonos element containing this mouse-over-text
_HTTP response code 405 for "urn:schemas-upnp-org:service:AVTransport:1#Play"_

**What did you expect as result?**
Starting to play the music, like it has done so for the last couple of weeks

**Any other remarks**
- Sonos has come with an update of their app. Maybe they changed their interface.
- When instead of Play, you select Previous: same message only ending with Previous instead of Play
- When instead of Play, you select Pause: same message only 500 instead of 405 and ending with Pause instead of Play,
This partly corrected itself while typing this issue, now, Play works for both boxes. Not for the bridge though. Next only works on one of the two boxes.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
