### ISSUE TITLE
Almost unusable: Fibaro Door/Window sensor not updating in UI, cannot ever see the open/closed state.

### ISSUE THREAD

**Issue by athomey** [athombv/homey#12]
I added two Fibaro Door/Window sensors to Homey. There shows in de detail pop-up at the devices, a gauge icon, Generic Alarm Off and Battery State. So far so good.

Now when I change the state of the device, it does not change AT ALL in the UI. It should show my Windows is open/closed, but it doesn't.  Not even when refreshing, or reopening the pop-up dialog.

Comparison: I have same type devices in VeraEdge. Those do update open/closed perfectly, and scens (flows) trigger perfectly. These are same type devices, not actual same devices, I never pair them to more than one controller at the same time.

Sidenote: In both VeraEdge AND Homey I have those devices unarmed, for various reasons, so that is not the problem.

Is there a relationship with #17

**Comment by ocatie** [comment]
Hi athomey,

Did you assign the correct association groups to Homey? By default Homey makes an association with group 1 but the non-zwave Plus Fibaro devices use group 3 a lot for status reporting (refer to your manual). For battery devices you'll have to wake up the device to push the new settings after you pressed save. For the door window sensor I think you'll have to triple click the TMP button.

Assigning the correct association group upon pairing is something an app will be used for later on.

**Comment by athomey** [comment]
I have never changed any association in VeraEdge, it "just worked". So I do have a suspicion what it is meant for, I have about 0% knowledge about this. I'll try to figure out what you mean AND try to find a way to change this in Homey. I'll keep you updated!

**Comment by ocatie** [comment]
The Z-Wave Plus standard dictates a association with group 1 is made for every device. For standard Z-Wave device this group is sometimes used for different uses. Z-Wave apps will make this more plug&play but for now you have to switch the group manually. Due a bug in the device settings the saved settings aren't applied. Working on it.

**Comment by ocatie** [comment]
Fixed in next update
