### ISSUE TITLE
Token tester doesn't resolve string examples correctly

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1200]
**What is your Homey version (Settings → System)?**

1.1.0

**What did you try to achieve?**
Check token values on flow test for existing apps

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
If token type is not defined according to docs this will be handled as type: 'string'. The token test value dialog doesn't resolve the defined examples for these tokens correctly:

Example token definition:
```
          { "name":"code",
            "title":{
              "en":"TAN",
              "nl":"TAN"
            },
            "example":{
              "en":"567890"
            }
          }
```
Test dialog:
![image](https://cloud.githubusercontent.com/assets/15232724/21548133/c2fb61f8-cdea-11e6-8d22-b2e9fe743ff8.png)

Documentation:
![image](https://cloud.githubusercontent.com/assets/15232724/21548146/de4b464e-cdea-11e6-90a8-0dd4845cb42c.png)

...

**What did you expect as result?**
Act like token with type: "string".
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Great find, fixed in 1.1.1!

**Comment by irritanterik** [comment]
@WeeJeWel can you take a little look at this:
```
            "type":"string",
            "example":{
              "en":"{\"a\":1,\"b\":\"some text\"}"
            }
```
![image](https://cloud.githubusercontent.com/assets/15232724/21553718/3c0de632-ce0a-11e6-88bb-92146d888890.png)

I know objects are not supported, but working around with JSON.stringified strings. Only my example is cut on the first (escaped) ".

**Comment by WeeJeWel** [comment]
Thx! Also fixed :)

**Comment by irritanterik** [comment]
Fix confirmed!
