### ISSUE TITLE
/userdata folder not reachable from settings frontend

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1201]
**What is your Homey version (Settings → System)?**

1.1.0

**What did you try to achieve?**

I want the magister app to show an image file in the settings webpage. The app retrieves a student photograph from an external source and stores this file in /userdata

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

I cannot get to /userdata from the frontend 😞 
...

**What did you expect as result?**

to have a place where I can store imagefiles and retrieve it from the settings webpage

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Good suggestion. Added in 1.1.1!

**Comment by gruijter** [comment]
@bvdbos  yes, confirmed. I'll close the issue now.
