### ISSUE TITLE
Contrast problem Insight Slider

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1203]
**What is your Homey version (Settings → System)?**

1.1.0

**What did you try to achieve?**

I had try to slide down the InSight menu at the left side of the page.

*Please include detailed steps how we can reproduce the issue*

In the personalisation setting those the horse flower picture.
![image](https://cloud.githubusercontent.com/assets/8507396/21552505/475f0906-ce02-11e6-8a35-83f7f2fd64be.png)

In the InSight page you could hide the slider bar. I was missing him and can't find it anymore. 

**What was the result?**

You could see the slider bar not very well.
![image](https://cloud.githubusercontent.com/assets/8507396/21552522/6e14804e-ce02-11e6-9d05-7afab4479bac.png)

**What did you expect as result?**

When the contrast between the slider bar and the flower is greater, you could see the slider bar better. Take the Flow page as example: 
![image](https://cloud.githubusercontent.com/assets/8507396/21552645/50cd1aae-ce03-11e6-876e-20acc6f3c220.png)

**Any other remarks**

It a little design thing. I've tested it with all the other pictures. This one is the worstest.

**Comment by WeeJeWel** [comment]
Yep, I agree, but this is hardly fixable. I'd like to let the user decide if they prefer flowers or scrollbars :-)

**Comment by WesRos** [comment]
It's strange that the slider from Insight and the flows aren't the same. Next to that it's recommended to bring a solution, when you've planned to make its possible to upload user onw pictures.
I'm not a programmer, but I think it must be possible to calculate the base color of a picture. Then its programmable to pick a color in contrast with the Base color for the slider.

Its a very low issue, you'd better take your time for other imported things.
