### ISSUE TITLE
Placeholders missing on flow cards

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1204]
**What is your Homey version (Settings → System)?**

1.1.0

**What did you try to achieve?**

Staring at some flows

**What was the result?**

Placeholders are empty:
![image](https://cloud.githubusercontent.com/assets/15232724/21552779/3f395c34-ce04-11e6-92c4-4042e9b433bc.png)

args definition:
```
{
                "name": "text",
                "type": "text",
                "placeholder": {
                  "en": "Your question...",
                  "nl": "Stel een vraag..."
                }
              }```

**Remarks**
Only auto-completion placeholders are shown

**Comment by WeeJeWel** [comment]
You're on a streak! Fixed!

**Comment by irritanterik** [comment]
Fix confirmed!
