### ISSUE TITLE
IFTTT with second account does not work

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1205]
**What is your Homey version (Settings → System)?**
1.0.5

**What did you try to achieve?**
Setup another IFTTT trigger with a secondary account, so it seems only one homey account can be assigned to IFTTT.

*Please include detailed steps how we can reproduce the issue*
If IOS location of secondary account is within reach then open gate automaticly

**What was the result?**
The homey created IFTTT flow can not be selected, no flows are found

**What did you expect as result?**
All homey IFTTT flows to be available for selection for the secondary account

**Any other remarks**
Already have my main account working with IFTTT so this should be a walk in the park.

**Comment by RobinBol** [comment]
This is a known limitation at the moment, this feature is not very likely to be introduced anytime soon.

**Comment by chrisboer** [comment]
OK that is a pitty but I understand that there are more high priority issues to be resolved.
So this remains open and on the backlog
