### ISSUE TITLE
Token in argument conversion leaves curly braces

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1206]
**What is your Homey version (Settings → System)?**
1.1.0

**What did you try to achieve?**
Staring at my flows 

**What was the result?**
I discovered some additional curly braces left there after the 1.1.0 update upgraded the tokens:
![image](https://cloud.githubusercontent.com/assets/15232724/21557271/8b670644-ce2a-11e6-8b83-38db1ed0e04e.png)

**What did you expect as result?**
![image](https://cloud.githubusercontent.com/assets/15232724/21557280/af5f1a14-ce2a-11e6-89b0-e74c5bc0382e.png)

**Any other remarks**
I used the {{$Var}} notations when creating this flow on version 1.0.5

**Comment by WeeJeWel** [comment]
This was actually intended behavior, because it was _very_ hard to check if there was any other operator, e.g. `{{ $var * 5}}` present.
