### ISSUE TITLE
Flows - Pressence "Nobody is home" does not work

### ISSUE THREAD

**Issue by dennyexalto** [athombv/homey#1208]
**What is your Homey version (Settings → System)?**

1.1.0

**What did you try to achieve?**

Want a create a workflow for intrusion detection. 
Step 1: Create Workflow 
Step 2: If Sensor (klik aan klik uit AMST-606) is off
Step 3: And pressence is nobody is home
Step 4: Send email with picture of security camara (Synology addon)

**What was the result?**

If i am at home and i open my front door the device still triggers the flow.

**What did you expect as result?**

Nothing when i am at home

**Any other remarks**

The workflow itself works fine, it only doesn't recouldnice the command nobody is home

**Comment by WeeJeWel** [comment]
Are there more users registered with your Homey?

**Comment by dennyexalto** [comment]
Sorry for the delay in response. I am the only user. 
Allready tried to reinstall my homey app and check the home detection settings (even do they do work when i leave the house he turn of my lamps)

**Comment by chrisboer** [comment]
Can a button or switch be made in the IOS App that you can switch your presence to AT HOME when an update of Homey or a reboot is required. 
Because flows are created with "Nobody is home" as check so they will not be executed, not handy that you will be awake at 5:00 when the Alarm goes of because of a flow with Nobody is home and you walk down the stairs.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not in v1.1.9?

**Comment by chrisboer** [comment]
Hi Jeroen,

I think you mean v1.1.2 of Homey ? or if not what version v1.1.9 do you mean ?

**Comment by bvdbos** [comment]
https://firmware.athom.com
1.1.9 just got released as stable...

**Comment by chrisboer** [comment]
Ok I am installing 1.1.9 now and will check

**Comment by chrisboer** [comment]
It works perfect with 1.1.9 now
