### ISSUE TITLE
Time pronunciation does not work as expected 

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#1209]
**What is your Homey version (Settings → System)?**

1.0.5

**What did you try to achieve?**

When creating a flow that contains time or speech Homey can not pronounce the time correctly between 18:00 and 18:10. So for instance when it is 18:03 you only hear "it is 03" instead of 'it is 18:03'. 

**What was the result?**
-

**What did you expect as result?**
I would have expected to hear "it is 18:03".

**Any other remarks**

**Comment by bvdbos** [comment]
Similar was #941 before...

**Comment by harmstellinga** [comment]
Same here.

**Comment by corvdniet** [comment]
To be a tiny bit more specific ... this happens for every time (=every hour) between ..:01 and ..:09 (01 and 09 included). 

I'm on 1.1.9

**Comment by Tweake** [comment]
Which language are you using?

**Comment by corvdniet** [comment]
In my case ... Dutch.

**Comment by Tweake** [comment]
As @bvdbos said this issue is similar to #941, But I forgot to also apply the fix when a time is coming from a flow. As of version 1.2.0 it will work correctly no matter where the time is originating from. Thanks for reporting the issue!
