### ISSUE TITLE
Hue white does not work on living color

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#121]
I have a setup with 4 Hue light bulbs and 1 living color lamp connected to the bridge.
When the command "make the Hue lights red" is given, all 5 lamps turn red.
When the command "make the Hue lights green" is given, all 5 lamps turn green.
When the command "make the Hue lights white" is given, the 4 Hue bulbs turn white and the living color lamp stays green.
Problem is probably that the living color lamp does not support the extended space for whites (e.g. warm white).
Possible solutions: make lamps supporting extended colors warm white and others plain white. Or always use a plain white supported by all Hue types. (Option 1 preferred).

**Comment by WeeJeWel** [comment]
Good suggestion, will definitely do so!

**Comment by Tweake** [comment]
Fixed as of version 0.8.31, thanks for pointing it out! 
While testing this I noticed Homey's 'white' was very warm white, so I have adjusted the default white temperature and added the ability to ask Homey to set lights to cool/warm white.

**Comment by nlrb** [comment]
Cannot test due to https://github.com/athombv/nl.philips.hue/issues/6.
