### ISSUE TITLE
calculations in condition-card

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1210]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Calculate a temperature-difference with tags

*Please include detailed steps how we can reproduce the issue*
Take a random trigger and do a calculation in the condition-field

**What was the result?**
Doesn't work, "invalid variable"
![2016-12-31 14_56_06- 202 flow - homey](https://cloud.githubusercontent.com/assets/1064079/21577837/dd87d904-cf69-11e6-80fe-c8f0d3471bb0.png)

**What did you expect as result?**
Calculate condition

**Any other remarks**
Even a calculation {{2+3}} gives this error despite of https://www.athom.com/nl/ondersteuning/KB000007/

**Comment by WeeJeWel** [comment]
The first argument must be the name of the variable, so basically you're comparing variable ID `6` with value `1`.

**Comment by bvdbos** [comment]
I know, but that shouldn't give "invalid variable" but just a "not true" or, in this case the action should run as (2+3) is not equal to 1... If {{tag1-tag2}} is not possible yet in the condition, then this is a request for enhancement...

**Comment by WeeJeWel** [comment]
I could add a numeric comparator, e.g.:

`{{textfield1}} {{equal to|lt|gt|lte|gte}} {{textfield2}}`

Would that suffice?

**Comment by bvdbos** [comment]
On https://www.athom.com/nl/ondersteuning/KB000007/  it says :
> Het is zelfs mogelijk om wiskunde te gebruiken in je Flows! Omsluit een formule in {{ ... }}. Bijvoorbeeld, {{ 2 * 3 }} wordt dan 6. Natuurlijk kun je ook een tag in deze formule te slepen. Om bijvoorbeeld te berekenen hoeveel de totale energiekosten zijn, kun je je energiemeter vermenigvuldigen met 0.22, of wat op dat moment de huidige energieprijs is.

**Comment by WeeJeWel** [comment]
Yes, so the result of math is a value, not a variable name, which is requested in the first argument of the card.
