### ISSUE TITLE
Fibaro temperature report not send according to settings in devices

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#1211]
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

I want to have a data point every set time in the insights graph for the temperature (even if the temperature hasn't changed at all). For testing I'm using a send report every 600 seconds setting

**What was the result?**

I only see new data points in the insights graph for the temperature when the temperature is changing (by heating the sensor up with my hands). 

**What did you expect as result?**

It used to work when I was using the raw configuration parameters but I'm not able to set those anymore. When setting the following raw configuration parameters (40,2,50;42,2,600;60,1,5;62,2,600;66,2,65528;80,1,10;86,1,18;87,1,23) I get the message value is out of bounds. Which is not true when looking at the manual of the motion sensor.

It looks like not all fields in the device specific tab are correct.

**Any other remarks**

I'm using the Fibaro Motion sensor (Z-wave plus)

**Comment by bvdbos** [comment]
Are you on Homey 1.0.1 still? Better update to 1.0.5 (which is the current stable FW) and try again... The bug may be solved for quite some weeks already. As for the parameters, these look ok but these have been changes in the saving of configuration-parameters.

**Comment by JesperJanssen** [comment]
I have updated to version 1.1.2 and the problem is still not solved. No temperature data points every 10 minutes using the following settings:
![image](https://cloud.githubusercontent.com/assets/17165733/21601532/f7c5e652-d18b-11e6-9bb8-b39ff40512ac.png)

It seems it only records a datapoint when the temperature has changed. And this is also not done correctly because it should record a datapoint after a change of 0.1C and this is also not happening.

**Comment by bvdbos** [comment]
I wonder if this is something in Homey or something in the sensor...

**Comment by JesperJanssen** [comment]
It used to work when I had to set the settings using the raw configuration parameters.

**Comment by RobinBol** [comment]
Please see my comments over here: https://github.com/athombv/com.fibaro/issues/70
