### ISSUE TITLE
Zones not respected in speech commands

### ISSUE THREAD

**Issue by goyaweb** [athombv/homey#1214]
**What is your Homey version (Settings → System)?**
1.1.0
**What did you try to achieve?**
Change dim level of lights in particular zone
Say: "Verhoog de helderheid van de lampen in de keuken" or something similar.
**What was the result?**
Homey will change brightness of the lamps but not just in the kitchen but in the whole house. Even though it confirms that it will change brightness in the kitchen (name of the zone) specifically.
**What did you expect as result?**
Just change brightness in the zone mentioned, not in all zones.

**Comment by jeroenbos22** [comment]
Same here, title seems to be a to general. Its only the dimming (at least with me), color lights or on / off works good with zones

**Comment by Tweake** [comment]
I have done a complete rewrite of the way Homey controls devices in specific zones. Should be fixed in 1.2.0! It would be great if you could confirm after you have received Homey version 1.2.0

**Comment by goyaweb** [comment]
hope you also made the zones visible in the flow editor (request 1140).
