### ISSUE TITLE
Different background used on Mobile app.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1217]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

The selected background on the GUI isn't used by the Homey app. 

**What was the result?**

Different backgrounds used while I was expecting the new background to be used.

**What did you expect as result?**

The same backgrounds used.

**Comment by WeeJeWel** [comment]
Yup! The mobile app needs an update, we'll add this somewhere later.

**Comment by Arjanvde** [comment]
Fixed in the latest beta!
