### ISSUE TITLE
Different Background on Speech output/input.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1218]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Minor detail. the background of the Speech-output and Speech-input doesn't reflect the background set by the user.

**What was the result?**

A different background is shown.

**What did you expect as result?**

Expected the same background.

**Comment by WeeJeWel** [comment]
They're debugging panels, wont be fixed :)
