### ISSUE TITLE
Small Z-Wave In-Wall Remote Module can only turn OFF

### ISSUE THREAD

**Issue by camilleversteeg** [athombv/homey#1219]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

I added a new Z-wave device (http://products.z-wavealliance.org/products/694). Very simple device that should return if the wall-switch is used. The goal was to make my current wall-switches 'smart'. I bought the device at: https://www.e-domotica.com/nl/producten/signaleren/e-domotica-wandschakelaar-sensor. The goal is to make current wall switches smart so that I can control my Philips Hue lamps via the Homey.

I successfully paired the device with Homey. It showed as a Unknown Z-wave device and displays a on/off slider.

**What was the result?**

When I set the z-wave device in homey to "ON" and use the switch. It successfully switches to OFF.
When the z-wave device in homey is set to "OFF" and use the switch. It does not do anything. It does not matter how many times i use the switch. The slider remains "OFF". Up until I manually change it to "ON" in the Homey.

**What did you expect as result?**

When the device is set to OFF and the switch is used, its turned to ON. 

**Any other remarks**

I contacted e-domotica and looked at my set-up. They couldn't figure out anything wrong. 

This is my first and only z-wave device. I hope that I would not be required to sent this device back to e-domotica.com, they are very helpful. 

The range between my Homey and this z-wave device was less then 2 meters. 

See additional information:
![image](https://cloud.githubusercontent.com/assets/15101655/21589390/83a660de-d0f1-11e6-8e3a-9dcb007f06e1.png)
![image](https://cloud.githubusercontent.com/assets/15101655/21589404/97765d9e-d0f1-11e6-8bf1-da58ceee67be.png)
![img_0685](https://cloud.githubusercontent.com/assets/15101655/21589442/2ff41e26-d0f2-11e6-864b-26a48f2f218f.JPG)

**Comment by caseda** [comment]
You most probably need an app created for it, since a "Basic Device" implementation that is now has probably only the right check for off, but not on (on can be different values for some devices)

**Comment by camilleversteeg** [comment]
@caseda if such as basic device requires a dedicated app/driver and a community to develop it. Then its going to be impossible to support lots of z-wave devices without a huge community.

Why I report this as a bug is if you read the forum (https://forum.athom.com/discussion/219/will-homey-support-device-x-read-this-first/p1), it simply states:

Does it use Z-wave? Yes is the answer to if it will be supported.

**Comment by bvdbos** [comment]
That's an everspring device, perhaps better to ask Ralf to implement this in the everspring-app?
https://github.com/ralfvd/com.everspring/issues

**Comment by RobinBol** [comment]
I think I found what might be causing your issue, this device sends a `BASIC_SET` report with value 0 - 99 if it is on. The current basic z-wave device implementation checks for `=== 255` which will be the reason why the mobile card did react when you turned the device of manually, but not when you turned it on.

But please note, z-wave devices on Homey work best (only) when there is a driver created for them. Many have been created by ourself and our community, if you happen to have an unsupported device please contact the community to see if they could implement it for you or (if the device belongs to z-wave brand supported by Athom; see App Store) contact us.

**Comment by RobinBol** [comment]
Fix has been added and will be available in the next Homey firmware version. If you still encounter problems by then, please let us know. (Do not forgot to re-pair the device after the Homey firmware update, this might be necessary.)

**Comment by camilleversteeg** [comment]
I can confirm it works.
