### ISSUE TITLE
Updateing an App Manual popsup halfway down the frame

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1220]
**What is your Homey version (Settings → System)?**

1.1.2 (Dutch)

**What did you try to achieve?**

Update an App  manual.

*Please include detailed steps how we can reproduce the issue*

Disable Automatic updating and wait for an update of the App. Klick update.

**What was the result?**

The "Popup" was way down the HTML frame, had to scroll down to find it.... 
![image](https://cloud.githubusercontent.com/assets/12412734/21595216/b58c0524-d12b-11e6-8ac2-4ae4868b7e65.png)
(This was no issue a couple of Homey FW updates ago....) 

**What did you expect as result?**

Popup on screen visible without scrolling 

**Any other remarks**
No.

**Comment by Rocodamelshe** [comment]
same here

**Comment by WeeJeWel** [comment]
Thanks, fixed

**Comment by Rocodamelshe** [comment]
It's now popping at the top so we have to scroll up?

**Comment by Rocodamelshe** [comment]
![update-scroll-up](https://cloud.githubusercontent.com/assets/19249884/22556431/69c9b9ca-e967-11e6-82c4-b10c23fc48f1.png)

**Comment by Dijker** [comment]
At version 1.2.0-rc8 still have to scroll up ;-(

**Comment by WeeJeWel** [comment]
Fixed

**Comment by Dijker** [comment]
Confirm fixed in 1.2.0-rc.9
