### ISSUE TITLE
FEATURE REQUEST: Global and Card Volumes

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1221]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Play cards at a different volume than the global volume.

*Please include detailed steps how we can reproduce the issue*

Homey's volume gets dimmed at a certain time and even muted when it's bedtime.\
This is to avoid it waking us up in the middle of the night with messages that's it's updating or lost connection or something.

**What was the result?**

There is no easy way to playback important stuff when Homey's volume is dimmed or muted.
Currently you have to set the (global) volume in a flow that always needs to be heard (Alarm, for instance). Afterwards you need to manually set back the volume to what it was if you don't want to be disturbed by other flows.

**What did you expect as result?**

It would be really cool if each card would have an indivual volume that overrules the global volume setting. A simple slider that can be enabled or disabled (when it just follows global volume setting) 

**Any other remarks**

On top of that it would be really cool if you could set time periods for the global volume (e.g. 20:00-23:00 50%, 23:00-7:30 0%). You need one or several flows for that now but seems so basic it should be included in the volume page. Besides the page is so empty it could do with a few extra settings.. :)

**Comment by WeeJeWel** [comment]
We have no intention of adding this feature, as it's very complex to the user.
