### ISSUE TITLE
FW 1.1.2: ZWave changes break actions.

### ISSUE THREAD

**Issue by SynoUser-NL** [athombv/homey#1222]
**What is your Homey version (Settings → System)?**

Homey Firmware V1.1.0 (working correctly) and V1.1.2 (not working correctly).
TKB Home app: v1.0.0

**What did you try to achieve?**

I have a TKB Home double wall Zwave switch that has a left dimmer switch and a right dimmer switch. The app for this switch (v 1.0.0) has worked flawlessly until firmware 1.1.0 and enables a double-click flow trigger for the right switch. I use this to trigger scene flows on multiple switches.
As of firmware 1.1.2 Homey no longer recognizes the double-clicks of the right button (both on and off). Single clicks work fine.

**What was the result?**
Homey does not recognize the double-click of the right button.

**What did you expect as result?**
Homey recognizes the double-click of the right button and triggers flows.

**Any other remarks**
There has not been any other change in configuration. The TKB Home app version has not changed, only Homey firmware has.

**Comment by chrisboer** [comment]
Same issue with FGPB_101

**Comment by caseda** [comment]
Not the same issue, totally different cc has got to do with this.

I will look into this though :+1:

**Comment by SynoUser-NL** [comment]
After some playing around with Homey last night (with 433 MHz x10 stuff and Kodi), the right switch now appears to be working again as before. Not really shure why.
Do you want this issue closed?

**Comment by caseda** [comment]
If it works, of course, you can always re-open it if the issue comes back
