### ISSUE TITLE
App & Device: dimmer level not accurate

### ISSUE THREAD

**Issue by SynoUser-NL** [athombv/homey#1223]
**What is your Homey version (Settings → System)?**

Homey V1.1.2
Android App: latest

**What did you try to achieve?**
When setting the dim level on a(ny) ZWave device, the dim level of the interface displays the previously set dim level, while the device is set to the desired dim level.

Example (actions in sequence):
1) Set dim level from off to 50% -> Light is dimmed to 50% -> Display after releasing the slider is set to 0% (off)
2) Set dim level from 50% to 30% -> Light is dimmed to 30% -> Display after releasing slider is set to 50%
3) Set dim level from 30% to 75% -> Light is dimmed to 75% -> Display after releasing slider is set to 30%

**What was the result?**
See above.

**What did you expect as result?**
Expected is that the slider shows the actual (current!) dimming level of the light.

**Any other remarks**
This behaviour occurs in both the Homey Device interface and the Homey Android app and has been the case in every version of Homey and App since first release. Please fix!
...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by SynoUser-NL** [comment]
Hello @jeroenvollenbrock ,
Thanks for looking in to this. I have not yet been able to test the current situation, will do this this week and report back.
Thanks, Den

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
