### ISSUE TITLE
Fibaro FGPB_101

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1224]
**What is your Homey version (Settings → System)?**
1.1.2 

**What did you try to achieve?**
Press button does not work anymore, not regocnized

*Please include detailed steps how we can reproduce the issue*
After homey update to 1.1.2 with fibaro 1.1.8 it does not react on anything

**What was the result?**
Nothing happend

**What did you expect as result?**
Opening of gate

**Any other remarks**
Could a new release be tested better before promote it to be distributed because this is no fun if everything works perfect and the next day not anymore.

**Comment by chrisboer** [comment]
After remove and adding the device it still does not respond to anything

**Comment by caseda** [comment]
Already fixed, but the PR is not accepted yet and put into the store

**Comment by chrisboer** [comment]
OK many thanks waiting on the update then

**Comment by chrisboer** [comment]
Question what changed in the Homey OS 1.1.2 what caused this device to fail ?

**Comment by caseda** [comment]
The device uses Central Scene version 3 to send the button presses to homey. 

This was not fully implemented yet into homey (first were just the hexadecimal values converted to numbers). 

in 1.1.2 this got updated to the real signal values, along with a few extra signals/data (not really used by the button)

When creating the driver for the button I already found it kind of strange it was different from the previous 2 versions, but now makes sense

**Comment by chrisboer** [comment]
Ok lol, so you already changed it here ?
athombv/node-homey-zwavedriver

**Comment by caseda** [comment]
Naah, I apposed an update in the zwave driver for something else, it has been fixed in the app itself. 

You will have to re-pair it unfortunately

**Comment by chrisboer** [comment]
In the Homey source? I don't have access to this code or can I repair it via developer mode

**Comment by caseda** [comment]
you can download my PR (or actually the branch where i also updated the app.json) which has the fix for the button build into the app:
https://github.com/caseda/com.fibaro/tree/pre-shop-fgpb-fix

the change was indeed in homey's source itself, you won't get acces to this either ;p

**Comment by chrisboer** [comment]
When installing I get this error 

Stack trace:

Error: Cannot find module 'homey-zwavedriver'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/drivers/FGBS-001/driver.js:4:21)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at /homey-app/manager/drivers.js:74:27
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
at /homey-app/manager/drivers.js:20:38
at /homey-app/homey.js:1:1080
at Array.forEach (native)
at Object.<anonymous> (/homey-app/homey.js:1:1058)
at emitNone (events.js:67:13)
at Object.emit (events.js:166:7)
at /bootstrap.js:226:9
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

Exit code: undefined
Exit signal: undefined

**Comment by chrisboer** [comment]
Solved by update of @caseda and @RobinBol fibaro 1.1.9

**Comment by chrisboer** [comment]
FGPB_101 it stopped working suddenly and after reboot of homey it does not respond either so again issue.

**Comment by caseda** [comment]
it is probably the same as this issue:
https://forum.athom.com/discussion/comment/42455/#Comment_42455

or at least related, so no need for your debug, it is just weird

**Comment by chrisboer** [comment]
Stupid me, I changed the flows to bypass the not working FGPB_101 but you must change them back to previous mode to have them do anything again ;-) 

So closed again ;-)
