### ISSUE TITLE
Plugwise circles not available

### ISSUE THREAD

**Issue by nhassink** [athombv/homey#1225]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

After the plugwise app on homey is first started all circles are ok and switching is possible. But after a while (hours) the circles register as unavailable whilst they are available in the native plugwise app on my iPhone and also in the stretch web interface. 

I suspect that this has to do with the fact that the plugwise mesh network is not always stable which results in circles being offline for a few minutes. I suspect that the plugwise homey app then registers these circles as unavailable but fails to register them as available again once they are back.

**What was the result?**

Permanently unavailable circles until the plugwise app is restarted

**What did you expect as result?**

Available circles

**Any other remarks**

No

**Comment by nhassink** [comment]
think I fixed this bug myself after Athom made the plugwise app open source. Just submitted a pull request.

**Comment by bvdbos** [comment]
Then tomorrow I'm going to install my Stretch and do some testing !

**Comment by bvdbos** [comment]
@nhassink Did your fix work?

**Comment by nhassink** [comment]
Yes I believe so

**Comment by nieuwton** [comment]
@nhassink Do I understand right that you have solved the "Unavailable" problem and have added "measure_power" and "meter_power"? That would be very nice. When can we expect the update in the App Store?

**Comment by nhassink** [comment]
Yes i did. The app needs testing before it will be submitted to the App Store. You can download the latest version however from github. If you can test it also this would be great

**Comment by nieuwton** [comment]
OK, I have installed 2.0.8. The extra power functions were not visible. Hence, I deleted one socket and tried to re-pair it. Didn't work, because my stretch password was not recognised. So I did a PTP. After that I could re-pair all the 15 sockets without any problem. The power functions do work if I add the socket as an "other device". The 7 sockets which I added as "light bulbs" (lampen) do not show the power usage.  The on/off status is updated when I switch the sockets from outside Homey.
At this moment, all the devices are available. 
Well done.

Cheers, Ton

**Comment by nhassink** [comment]
Thanks for testing. A re-pair is necessary. I also saw that the energy measurements are not available in de light category. Will look into that but I think this is homey behavior and not fixable in the app. Keep me posted if you run into other issues

**Comment by nieuwton** [comment]
Did you see the latest crash issue.

**Comment by nhassink** [comment]
Yes solved that one in my own repository already Will submit a new pr tomorrow

**Comment by nieuwton** [comment]
@nhassink I am very happy with these improvements. It was very annoying to restart the plugwise app at least once a day. And the power metering allows nice new flows. Thanks for your effort.

**Comment by bvdbos** [comment]
@nhassink You may close this one then 👍
