### ISSUE TITLE
433 stops working after x hours

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#1228]
**What is your Homey version (Settings → System)?**

1.1.2
Kaku app 2.8.9

**What did you try to achieve?**

Use switch on my light 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
No respons from Homey when clicking the wallswitch 

**Any other remarks**

Restart app does not help,  did work great before.

The log file is send when it's not working and I have tried pressing the wallswitch sometime 

..1D5BC60A5A

Restarted and red ring

**Comment by djeskoswe** [comment]
After restart and app restart it works,

**Comment by djeskoswe** [comment]
Same problem now,  log CC400ADEBD

Before it stopped the switch in the kitchen turned on and off by it self

**Comment by djeskoswe** [comment]
Same now,  C85B063654 anyone looking here?   

Restart microcontroller does the trick

**Comment by djeskoswe** [comment]
Same,  155DD171C3.

**Comment by bvdbos** [comment]
You already updated KaKu to 2.8.10? What do you see when you have the app running through the CLI? Where does it crash (that's going to be a long log if it crashes only once in 12 hours...). Or can @BasKiers see the logs in Sentry?

**Comment by djeskoswe** [comment]
I'm on 2.9.0,  will wait for next app update and see 

They got logs now :-)

**Comment by djeskoswe** [comment]
One more log before reboot A096A905E8

**Comment by djeskoswe** [comment]
After ptp and memory got low it works for 3 days ,  can it be the memory?

**Comment by djeskoswe** [comment]
Today it's dead again,  reboot helping... When memory get full Grey and black bar the problem starts

**Comment by djeskoswe** [comment]
Any update?   needed to restart microcontroller 2 times today

**Comment by bvdbos** [comment]
That's new, twice a day? Did you change something in your home or Homey?

**Comment by djeskoswe** [comment]
No change,  after ptp it works 5 to 7 days then back to not responding.  Have most zwave but use some nexa wallswitches..

**Comment by djeskoswe** [comment]
Any update?   Latest FW and Kaku app and same problem.. Restart microcontroller now

**Comment by djeskoswe** [comment]
And again,  restart microcontroller and all good!    Any update?

**Comment by djeskoswe** [comment]
Ptp to get it working this time.. Any update?

**Comment by chrisboer** [comment]
It seems with me that only newly added AGDR-3500 don't respond anymore, so after you added them they can not be controlled or are too far from homey eventhough the distance worked with 1.1.2 and old KaKu version. 
The APA3-1500R I also reassigned but this one respons perfectly.

**Comment by djeskoswe** [comment]
works great now , dont know what update that fix the problem.
