### ISSUE TITLE
Feature request - water meter in liters vs m3

### ISSUE THREAD

**Issue by jtebbens** [athombv/homey#1229]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Tracing water usage via water meter. Although it is m3 by default its impracticable to use it like that.
Common house holds are in liters a day. For the Homewizard app we can trace it via energylink and use meter_water for this but it has a label of m3 but energylink reports liter.

*Please include detailed steps how we can reproduce the issue*
Default meter_water is in m3 but like to report it as liter instead.

**What was the result?**

...

**What did you expect as result?**
Either change the label from m3 to liter. Or via development allowance to overwrite the unit label from m3 to liter (capabilityoptions). Currently this allow title overwrite not units.

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Are you aware that the units are easily converted by dividing them by 1.000? See https://www.google.nl/search?q=1+liter+in+m^3

If you really want a Liter capability, please create a custom capability.
