### ISSUE TITLE
Flow using motion from Fibaro multisensor does not work

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#123]
I can't get this to work:

![image](https://cloud.githubusercontent.com/assets/17158826/12986770/5ce8dace-d0f9-11e5-848e-367942edc21b.png)

I also don't see the movement detection using the Insights:

![image](https://cloud.githubusercontent.com/assets/17158826/12986822/8e2a91f4-d0f9-11e5-82d5-2e53b8c9a70f.png)

**Comment by filoor** [comment]
Have the same problem also with my fibaro door sensor

**Comment by Fire69** [comment]
The Generic Alarm is not the motion sensor.
I added my sensor a couple of times, only 1 time did I get Motion in the list.

According to @ocatie it has something to do with choosing the correct association.
I hope he can explain this a little further.

**Comment by JohanKuster** [comment]
Thanks Fire69. Will try to remove and add the sensor tomorrow.

**Comment by ocatie** [comment]
Associations in non Z-Wave Plus devices have to be set manually for now. Refer to your manual to which group an association has to be made.

You can make an association by clicking the wrench icon on the device. Homeys node id can be found under Settings -> Z-Wave.

**Comment by irritanterik** [comment]
@ocatie I don't understand. Association is ok (i've set it manually, fibaro motion group 3 to node 1 (Homey), i see device values updating in Homey, but flows never triggers by these updates.

**Comment by ocatie** [comment]
Were looking into the updates not triggering flows. If the generic alarm in the device card flashes red upon movement you've setup the device correct

**Comment by irritanterik** [comment]
Device card does flashes red upon movement.

2016-02-12 12:29 GMT+01:00 Taco <notifications@github.com>:

**Comment by WeeJeWel** [comment]
Is fixed in 0.8.18
