### ISSUE TITLE
Bad translation

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#1230]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Remove a flow and a flow folder.

*Please include detailed steps how we can reproduce the issue*

Remove a flow and a folder with your Homey set on Ducth

**What was the result?**

There is the text: Verwijder dit flow en verwijder dit folder. In these sentences the dutch translation for this should be deze and not dit.

**What did you expect as result?**

Deze and not dit.

**Any other remarks**

-

**Comment by WeeJeWel** [comment]
Thanks! Fixed

**Comment by bvdbos** [comment]
confirmed fixed
