### ISSUE TITLE
Devices do not fit on my Tablet screen

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#1231]
Devices do not fit on the sreen of my Tablet SM-T520  with Android 4.4.2  app version 2.3.0. build 56

On my Phone the devices are shown good, but on my Tablet, the devices don't fit on the screen so the slider isn't visible, see attached picture;

Extra complain for both my Phone and my Tablet and many screens on the PC-App:
Devices texts are dimmed when **OFF**, also the device names, this makes it very bad readable, 
I prefere that **all text** is black, that is also good for outdoor use.

![screenshot tablet 2017-01-03 16 59 27](https://cloud.githubusercontent.com/assets/3833862/21644825/bfbf522a-d28f-11e6-983d-d14a51c11ec1.png)

**Comment by Rocodamelshe** [comment]
In my phone the slider becomes visible when u actualy slide it.

**Comment by WeeJeWel** [comment]
It looks like you're using an old version of Android. Which version is it?

**Comment by JPe2** [comment]
Samsung Tablet SM-T520 with Android 4.4.2

**Comment by WeeJeWel** [comment]
I'm afraid your Android's WebKit version is out of date. Maybe you can try updating it manually somehow? There's not much we can do unfortunately.

**Comment by bvdbos** [comment]
@JPe2 The Homey interface seems to work completely (I didn;t find any errors yet) on firefox. Can you install firefox on your android?

**Comment by JPe2** [comment]
@bvdbos   thanks Bas, but what is the influence of the browser on the Homey-app?

**Comment by bvdbos** [comment]
Well, was under de impression your webkit can't be updated but perhaps you can install the latest firefox-version? That way it might work.
