### ISSUE TITLE
Flow card hints show under next card

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1232]
**What is your Homey version (Settings → System)?**  
1.1.2

**What did you try to achieve?**  
Implement hints on my apps.

**What was the result?**  
If hints are a bit longer (i'd like to add a short explanation for every argument) and there are more cards in the column, the hint  is partly shown under the next card:

![image](https://cloud.githubusercontent.com/assets/15232724/21649236/3837053e-d2a1-11e6-85a3-46d6e1c66ea4.png)

**What did you expect as result?**
higher z-index

**Comment by WeeJeWel** [comment]
Thanks for reporting! Fixed in 1.2.0

**Comment by irritanterik** [comment]
works with 1.2.0-rc8!
