### ISSUE TITLE
Trigger won't fire

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#1237]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

I am using mySensors app. When I press the doorbell it sends a signal to the app and this will fire a boolean true. Normal state is false. In insights you will see that the state is changed from false to true and after a few seconds back to false. How ever the triggers won't fire?!

*Please include detailed steps how we can reproduce the issue*

That's hard as you need to simulate something with mySensors. The explanation is above and this did work in 1.1.1.

**What was the result?**

Triggers won't fire

**What did you expect as result?**

Trigger did fire.

**Any other remarks**

Part of insight log:
Wed Jan 04 2017 17:33:22 GMT+0100 (CET),true
Wed Jan 04 2017 17:33:28 GMT+0100 (CET),false
Wed Jan 04 2017 19:45:45 GMT+0100 (CET),true
Wed Jan 04 2017 19:45:50 GMT+0100 (CET),false
Thu Jan 05 2017 11:23:40 GMT+0100 (CET),true
Thu Jan 05 2017 11:23:51 GMT+0100 (CET),false

I have two testing flows attached.

![doorbell2](https://cloud.githubusercontent.com/assets/17949840/21678361/bb266474-d33e-11e6-8fe6-ff21a7024497.png)
![doorbell1](https://cloud.githubusercontent.com/assets/17949840/21678360/bb2014fc-d33e-11e6-9c3e-6f92ff26f646.png)

**Comment by ewikner** [comment]
You have this issue becouse the athom team have made a change for flow triggers.
#1200 

We can now not use the same "Value has changed" flowcard for all the sensors.

**Comment by irritanterik** [comment]
Can be closed. No issue for Homey, but for app dev. Token types in app definition and on trigger event are not equal.

**Comment by markaswift** [comment]
@irritanterik is this a hard fix, I have 14 nodes down now due to this change... :(
