### ISSUE TITLE
Fibaro Push Button can't be paired

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1238]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Pair Fibaro Push Button and start flow

**What was the result?**

Fibaro Push Button stopped working with Fibaro app version 1.1.8 and Homey 1.?.?
I did update to app version 1.1.9, disable / enable app. I did reset button to factory default. I also did a reset z-wave network and homey ptp. All without getting the button paired again.

**What did you expect as result?**

Pairing of the Button again.

**Any other remarks**

...

**Comment by bvdbos** [comment]
https://forum.fibaro.com/index.php?/topic/23378-fibaro-button-not-working/#comment-103640
https://forum.fibaro.com/index.php?/topic/23749-fibaro-button-randomly-dies/#comment-105988
Might well be a Fibaro-issue...

**Comment by HansieNL** [comment]
Just sent mail to Fibaro support:

Hello,

I got a push button, which worked well. Now I can't use it anymore and pairing with my Homey is not working anymore. I also reset the z-wave network of the Homey.
I also did a factory reset of the button, but pairing is still not possible.
Adding an other Push Button is no problem.
Can you tell me what I can do if a factory reset still doesn't work?

To be continued...

**Comment by chrisboer** [comment]
I had the same issue with homey 1.1.2 and fibaro 1.1.8 but I could remove the push button in a normal way from Homey and re-pair it with homey and the updated fibaro 1.1.9 version yesterday by selecting Fibaro - then the push button and then you have to press it six times. I did this about 5 meters from homey and it picked it up right away.

**Comment by RobinBol** [comment]
We had similar issues with a Push Button at the office, the z-wave sniffer showed us that the device was only sending battery reports (massively) and therefore preventing the pairing process to initiate. The solution for us was to reset the device (took about 5 times), and then the device started to behave normally and paired flawlessly.

As this issue is related to the device itself I'll close this issue.
