### ISSUE TITLE
Homey does not support temperature below zero degrees Celsius in speech output

### ISSUE THREAD

**Issue by jeroenvano** [athombv/homey#1239]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Asking Homey the outside temperature with "Hoeveel graden is het buiten"

*Please include detailed steps how we can reproduce the issue*
Created a flow triggering on words "graden" and "buiten"
"then" speech card: "Het is buiten nu #tempatuur graden." using the temp tag from the connected Netatmo Weather station. The tag shows the correct temp below 0 degrees e.g. "-1.4".

**What was the result?**
Homey responds saying that the temperature is "one point four" (1.4) degrees and does not pronounce the minus or below zero. Suggesting the temperature is above zero degrees while it is under.
...

**What did you expect as result?**
Homey to pronounce the "minus" when temperature is under zero degrees
...

**Any other remarks**

...

**Comment by OpenMindNL** [comment]
I noticed the same. It's not just temperature. Every number inbetween -1 and 0 (0.x) is missing "minus" in speech.

**Comment by Tweake** [comment]
Thanks for reporting the issue! This will be fixed in Homey version 1.2.0

**Comment by bvdbos** [comment]
works for me now....
