### ISSUE TITLE
No error feedback

### ISSUE THREAD

**Issue by KrielkipNL** [athombv/homey#124]
While playing with the homey and the flow chart player. It is unclear what kind of errors the homey is facing. 

Like i want to let my Homey only say Hello for testing. But only a small red warning comes, but no information. 

insights does show any information. 
Version: 0.8.17

![schermafbeelding 2016-02-11 om 20 42 56](https://cloud.githubusercontent.com/assets/7860594/12988279/4012776e-d100-11e5-816e-7f240a184f49.png)

**Comment by KrielkipNL** [comment]
It looks like the voice is not being installed? Or is not installed the right way? 
This was with the default voice Brian.

**Comment by WeeJeWel** [comment]
Yes, seems to be the issue. Was the voice initially downloading?

**Comment by WeeJeWel** [comment]
As of 0.8.18, when you hover the triangle, an error message is shown.

**Comment by KrielkipNL** [comment]
It was with the default voice Brian.
