### ISSUE TITLE
433 range is worse after update klikaanklikuit

### ISSUE THREAD

**Issue by Willieku** [athombv/homey#1240]
**What is your Homey version (Settings → System)?**
homey 1.1.2        klikaanklikuit  v2.8.10
x.x.x

**What did you try to achieve?**
i tryed to put on a stekkerschakelaar at the far range  about 12 meters whit 3 walls in between.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
the result was it did not respond after the updat, but whit the versie before it did. time after time.
the versie before that versie  also the plug did not respond.

...

**What did you expect as result?**
the plug to respond as before
...

**Any other remarks**
the isue came direct after the update.

...

**Comment by bvdbos** [comment]
stekker-schakelaar, is that receiving signals from Homey or sending signals to Homey?

**Comment by Willieku** [comment]
i mean   the sending signal from homey   got worse.
(the plug  is the same wall plug)

**Comment by BasKiers** [comment]
Hi, 

I did not change anything in the app that could affect the range. Could you try rebooting Homey by pulling the power?

Regards,
Bas

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/42430/#Comment_42430

**Comment by BasKiers** [comment]
Hi,

Thanks for the link. Could you, like mentioned in the topic, try to run v2.8.9 of the kaku app to ensure this is an issue with the kaku app? You can do so by downloading it from here: https://github.com/athombv/nl.klikaanklikuit/tree/5c2f84e379b0b91cce85d13f9839bd16920881e6

Instructions of how to sideload an app are explained in this youtube video: https://www.youtube.com/watch?v=lRZLvhF2sfk

Regards,
Bas

**Comment by Povlov** [comment]
Is sideloading possible using a chromebook with a stable channel release?
Versie 55.0.2883.103
Platform 8872.73.0 (Official Build) stable-channel daisy_skate
Firmware Google_Skate.3824.129.5

Is the procedure described somewere?

**Comment by Willieku** [comment]
hey Bas,
What i did;  this morning i checked the isue and the lamps still not responding. (wall plug)
then i checked other plugs and they all worked.
Then i PTP   and that did the trick. the plug that gave the troubles did it.
For what its word for you to know; the wallplug is the most far away from homey. (grensgevalletje)
But fact was it did not worked after the update. (for as far as i could cheked this all whit my knolliged)

Other issue: i have 8 x  ASUN650.     5 off them are in range of about 5 meters from homey and give trouble.   
could you tell me if this is a known fact or should it work?  i cant find anything on the forum.

**Comment by chrisboer** [comment]
Strange I did not yet update home easy but I get this message ..

Verzenden en ontvangen op de 434 MHz frequentie so no wonder 433 is not working that good after the update.

Could you please let me know if I install this update that 433 Mhz devices will still work as they should ?

**Comment by Willieku** [comment]
hey Bas,
the problem seems to be solved.    the wall plug did work when i came home.  also tested.
asun650 still the same.   must i make a new isue?     i doint want to make more isues if they are allready known by you.

**Comment by bvdbos** [comment]
close me?
