### ISSUE TITLE
Fibaro smokedector don't show all insights

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1243]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Look for smoke detection statistics

*Please include detailed steps how we can reproduce the issue*
Look under insights "Inzichten"

**What was the result?**
Options missing with one smoke detector see picture
...

**What did you expect as result?**
All sensor options visible with both smoke detectors
...

**Any other remarks**
Just by coincidence I found it out, by the way under device overview I see all options under each device

![rookmelder](https://cloud.githubusercontent.com/assets/23163409/21726155/c871eb46-d43b-11e6-9a7f-c9028e05cc80.jpg)

![rookmelder1](https://cloud.githubusercontent.com/assets/23163409/21726238/3640bba2-d43c-11e6-8867-41a243ea4d76.jpg)

**Comment by bvdbos** [comment]
What happens if you set fire in the kitchen? Or if you burn your food? Doesn't the sensor-value get send to Homey? Or, perhaps less invasive : heat the sensor with a hairdryer to trigger the heatalarm :-)

**Comment by chrisboer** [comment]
That can be done more easily @bvdbos just decrease the alert temperature

**Comment by chrisboer** [comment]
I have deleted the smokesensor and re-paired now it shows correctly, but it is strange that this happens so I don't know if you want to place this on the backlog to be checked ?
