### ISSUE TITLE
Homey Desktop App not supports window.prompt dialog

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1244]
**What is your Homey version (Settings → System)?**  
Homey v 1.1.2, desktop app v 1.0.2

**What did you try to achieve?**  
On my localization apps (tesla, gps-trace, vodafone) users can add geofences. To enter the geofence name I do a `window.prompt("Name your geofence","Default name")` on the apps settings page.

**What was the result?**  
Nothing happens. `window.prompt` seems to be diabled in the Homey Desktop App. 

**What did you expect as result?**  
A basic pop-up with input field. 
Or a `Homey.prompt()` function available, comparable to `Homey.confirm()` and `Homey.alert()`.

**Comment by chrisboer** [comment]
Hi when you do it with a browser there is a popup but the geofence is not being stored.

**Comment by irritanterik** [comment]
Not relevant for this Homey issue.

**Comment by irritanterik** [comment]
@chrisboer Can you contact me on Slack? Geofences creating / editing / updating / saving all works ok here. Steps: 
1. Click [+]
![image](https://cloud.githubusercontent.com/assets/15232724/21741954/f2ad86e6-d4e4-11e6-9a8e-881ee7b93a54.png)
2. Enter new name in popup
![image](https://cloud.githubusercontent.com/assets/15232724/21741958/09486aec-d4e5-11e6-9b34-8c837728bd47.png)
3. Choose a shape on the drawing menu:
![image](https://cloud.githubusercontent.com/assets/15232724/21741964/20b109d2-d4e5-11e6-80df-b9ef7da4b50b.png)
4. Draw!
5. A drawn geofence is saved automatically

If this is not working for you, please contact me on slack or leave a comment on the forums.

**Comment by chrisboer** [comment]
On which domain ? on slack

**Comment by irritanterik** [comment]
The athom community: https://developers.athom.com/slack/

2017-01-07 15:03 GMT+01:00 chrisboer <notifications@github.com>:

**Comment by chrisboer** [comment]
Kan me niet aanmelden op die community moet je kennelijk voor uitgenodigd worden
athomcommunity.slack.com

**Comment by bvdbos** [comment]
https://slack.athom.com/

**Comment by chrisboer** [comment]
Thanks it works now it is not that logical way of doing it but it works.

I am also on https://athomcommunity.slack.com  now so that also works now ;-)

**Comment by WeeJeWel** [comment]
We're depentent on Electron here, and it looks like this wont be fixed anytime: https://github.com/electron/electron/issues/472. Sorry!

I'd suggest you use Jquery UI (https://jqueryui.com/dialog/#modal-form) for your use case.
