### ISSUE TITLE
Boolean logical tag used in "and" section of flow does not update tag

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1245]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

update of a boolean variable in the "and" section of the flow with a tag dragged from the "tags" menu into a boolean variable card did not work. The actual name of the tag has to be typed in the card.
![screen shot 2017-01-07 at 23 05 39](https://cloud.githubusercontent.com/assets/18570823/21745498/ee533a0c-d52d-11e6-95db-8d6f8d8f4d60.png)

**What was the result?**
Tag was not recognised and a new tag named "true" was assigned with variable from the card.

**What did you expect as result?**

update of tag.

**Any other remarks**

Typing the name of the variable works.

**Comment by WeeJeWel** [comment]
Drag the tag on the checkbox, and type `afwezig` as name.
