### ISSUE TITLE
[1.1.2] Z-wave debugging + device pairing: many "Error: queue_full" messages

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1246]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Debugging issues with a Z-wave app (Neo in this case).
While going through the debug logging, I do see a lot of "Error: queue_full" messages blocking transmission / reporting of data.

Some examples
> [debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
>   Properties1: { Scale: 1 } } err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
>   Properties1: { Scale: 1 } } err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug] node.on('online') arguments: { '0': true }

> [debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
>   Properties1: { Scale: 1 } } err: { [Error: timeout] message: 'timeout' } result: null
> [debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug] node.on('online') arguments: { '0': false }
> [debug] node.on('online') arguments: { '0': false }

> [debug] get alarm_motion
> [debug] get measure_luminance
> [debug] get measure_battery
> [debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
>   Properties1: { Scale: 1 } } err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
> [debug] node.on('online') arguments: { '0': false }
> [debug] node.on('online') arguments: { '0': true }
> [debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true

**Any other remarks**
It is for me unclear which queue is referred to, yet I assume that this is the Z-wave command queue which possibly has been updated to resolve the  ProcessSendData issue

**Comment by TedTolboom** [comment]
Most likely related to this (same queue_full message) is that this is also happening during pairing of a new Z-wave device; at any given moment during the pairing process the following error message might pop-up:
<img width="595" alt="schermafbeelding 2017-01-01 om 23 38 17" src="https://cloud.githubusercontent.com/assets/17163431/21749747/87cdd242-d5a5-11e6-94fe-81e5c965aa8d.png">
No detailed error message is provided to the user.

Resolution to resolve this is to go to Z-wave settings and remove the device (apparently, the device is added) and re-try pairing. If this is failing, disable other Z-wave apps and re-do

**Comment by bvdbos** [comment]
Multiple users mentioned this...

**Comment by WeeJeWel** [comment]
When this happens, can you create a crashlog? I think I've found the issue but want to verify

**Comment by TedTolboom** [comment]
I will reproduce this evening... will start removing and re-adding Z-wave devices ;-P and add the log code to this issue.

**Comment by mruiter** [comment]
CDEA3B7F3D

**Comment by TedTolboom** [comment]
Reproduced while adding battery powered Neo motion sensor: 
<img width="595" alt="schermafbeelding 2017-01-01 om 23 38 17" src="https://cloud.githubusercontent.com/assets/17163431/21958607/4696563e-dab2-11e6-997a-e9fe6268a023.png">
Log: ECA032C67B
Sensor removed (it was added)

2nd attempt: interview expired...
<img width="605" alt="schermafbeelding 2017-01-14 om 21 05 34" src="https://cloud.githubusercontent.com/assets/17163431/21958591/f7e29f7a-dab1-11e6-9a97-b1ba17d0cf3c.png">
Log: D88CE4C8B8
Removed the Z-wave device (it was added)

Disabled remaining Z-wave apps (Fibaro and GW app)
3rd attempt was successful

**Comment by TedTolboom** [comment]
While some more testing with the Neo sensor.... ran into a similar issue:

After re-adding my sensor... the led indicating motion detection was still blinking even though this is one of the default configuration paramters (to disable it)... also manual wakeup didn't work (show a report in the debug log)

So I removed the sensor again, disabled the other Z-wave apps, and added the sensor without issues

Log: 18ED8F99E9

**Comment by Tweaqer** [comment]
I experience this while adding my z-wave.me under Homey Firmware Versie: 1.1.4. Fixed it by removing and adding again while being closer to Homey.
