### ISSUE TITLE
[Suggestion] Implement cross-reference for variables and devices

### ISSUE THREAD

**Issue by Vonkenboer** [athombv/homey#1247]
Implement in future version > 1.1.2

See also: https://forum.athom.com/discussion/1829/add-cross-reference-page-in-webgui-for-searching-and-monitoring-devices-and-variables

**What did you try to achieve?**
A variable- and device cross-reference list.

**What was the result?**
Not existing. Yet. ;)

**What did you expect as result?**
A cross-reference list where all used variables and devices are listed. Summarizing where they are used (click on it to go to the specific flow/device).

Example for variables:
Show: actual (global)name, actual value, actual type, responsible app and where it is used.(flows/devices).
Edit: (global)name, value, and type.
Link: go to specific device or flow.

Example for devices:
Show: actual ID, Device type, Devicename, Device properties, actual status etc.
Edit: Devicename, properties, status
Link: go to specific device or flow

**Any other remarks**
See how it's implemented in Siemens PLC software as a good example:
Explanation of intention: http://youtu.be/WF3fXUNeY2s
Sample how it is used: https://youtu.be/UZx5axhLO8Y

In Homey:
- Show cross-reference for specific variable by adding a link (small arrow) to the new 'Tags' button/list in the 'Flow'-screen.
- Show cross-reference for complete variable list by adding a new button next to the 'Tags'-button in 'Flow' screen.
-  Show cross-reference for specific device by adding a link (small arrow) to a device in the 'Devices'-screen.
-  Show cross-reference for all devices by adding a link (small arrow) to the Homey-device in the 'Devices'-screen.

...

**Comment by WeeJeWel** [comment]
This should be visible under 'Tags' in the Flow Editor. If that isn't sufficient, then there's the Web API to create your own overview!

**Comment by rexvdb** [comment]
I have more than 100 flows and when I want to change or optimize something then I must search all the flows to see if there is used a variable or device. It is then very helpful to use a cross reference list. And with the Tags it’s impossible to find in witch flow it is used. But please explain how I can do that with the WebAPI?  Is the a search functionality?

**Comment by bvdbos** [comment]
The new mobile app has this. You can use the preview already:
https://play.google.com/store/apps/details?id=com.athom.homey2
also see https://forum.athom.com/discussion/3992/beta-new-homey-smartphone-app/p1
