### ISSUE TITLE
triggerDevice fails with token of type number

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#1248]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
Trigger a flow of a device with a token that has a numeric value.

`Homey.manager('flow').triggerDevice('zoneTripAlarm', { zone: zone, name: name }, { state: data.state }, device, function(err, result) {
					debug('Result zoneTripAlarm triggerDevice', err, result);
				});`

(in the example `zone` is of type number)

**What was the result?**

Error {"message":"invalid_capability"}

**What did you expect as result?**

Number type tokens to be accepted, as documented in the example: https://developers.athom.com/library/flow/triggering/ (`var tokens = { 'mm_per_hour': 3 }`)

**Any other remarks**

As workaround used 'zone.toString()' to make the tigger work.

**Comment by WeeJeWel** [comment]
Can you post your relevant app.json's flow section?

**Comment by nlrb** [comment]
https://github.com/nlrb/com.visonic.powermax/blob/master/app.json (line 1095).

**Comment by WeeJeWel** [comment]
You need to add `type: 'number'` to the token in your app.json :)

**Comment by nlrb** [comment]
That makes perfect sense! Did this change or was it always like that (if so, sorry to have missed that in the docs)? BTW: in general it would be nice if the error returned could state which parameter has an issue (e.g. `"'mm_per_hour' should be of type string"` instead of `"invalid_capability"`).

**Comment by WeeJeWel** [comment]
Yeah this changed as of 1.1.2. In fact it was a bug that the type wasn't checked, it should've always happened but it didn't prior to 1.1.2.

The error message is odd. Maybe you're not passing the correct object?

**Comment by nlrb** [comment]
Ah, ok, that explains it. Will check my other apps as well then, as I guess they will fail silently now.

It is only the type that is different (hence the `.toString()` below), so indeed the error message is odd.
```
let zone = data.zone.toString(); // Homey bug #1248
Homey.manager('flow').triggerDevice('zoneBattery', { zone: zone, name: name }, { state: data.state }, device);
```
