### ISSUE TITLE
Args.req.remoteAddress in API handler empty

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#1249]
**What is your Homey version (Settings → System)?**
Homey Firmware 1.1.2 / HTTP app 1.5.2

**What did you try to achieve?**
Trigger a flow in Homey when my Doorbird Smart Doorbell is rang. You can set a notification URL in the Doorbird which is triggered with a GET command when the doorbell is rang (see API here: https://www.doorbird.com/downloads/api_lan.pdf?rev=0.15). As you can not set extra headers with the Doorbird API I'm using the whitelist functionality of the HTTP app and I have added the IP of my Doorbird in the whitelist. I'm using the HTTP app GET action card to trigger a flow. For this setup to work the HTTP app needs to match the remoteAddress from args.req.remoteAddress with the whitelist of the app. For some reason the args.req.remoteAddress is not always filled with the actual remote IP address resulting in the flow for my doorbell not triggering most of the times.

Here is some logging from the HTTP app while ringing the doorbell a couple of times. The first two times args.req.remoteAddress is empty while the third time contains the right IP.

`Logging: {}
Logging: { params: { event: 'doorbell' },
  body: {},
  query: {},
  files: {},
  req: {} }
Logging: undefined
Logging: error in checker [TypeError: Cannot read property 'match' of undefined]
Logging: {}
Logging: { params: { event: 'doorbell' },
  body: {},
  query: {},
  files: {},
  req: {} }
Logging: undefined
Logging: error in checker [TypeError: Cannot read property 'match' of undefined]
Logging: { remoteAddress: '::ffff:192.168.0.134' }
Logging: { params: { event: 'doorbell' },
  body: {},
  query: {},
  files: {},
  req: { remoteAddress: '::ffff:192.168.0.134' } }
Logging: ::ffff:192.168.0.134
16:51:13 Evaluate trigger cards with event value { args: { event: 'doorbell' }, state: { event: 'doorbell' } }`

**What did you expect as result?**
That args.req.remoteAddress would always contain the remote IP address so it can be used by the HTTP app to trigger whitelisted flows.

**Comment by WeeJeWel** [comment]
That's odd. Does the call always happen the same? Or maybe sometimes over the cloud, or over ipv6?

**Comment by jghaanstra** [comment]
Yes, the call is always the same. You have to set the notification URL through the API interface of the Doorbird and I have set it to a local IP of Homey on my LAN. It always triggers the flow with the HTTP app GET action card at the incoming request but if args.req.remoteAddress is empty the HTTP app crashes (tries to match the whitelist to the empty args.req.remoteAddress.

I have verified the traffic from the Doorbird by setting up a webserver on my laptop and use Wireshark to capture the traffic. I can see the traffic coming in locally (no cloud in between). I do see something I can not explain with my networking knowledge but that might be causing issues. It seems the Doorbird sends the GET request but does not listen for the acknowledgement (HTTP 200) which is causing a networkconnection reset. I have attached the Wireshark log, perhaps it helps.

Here is also a Homey log, taken right after the HTTP app crashed because it was missing args.req.remoteAddress: B685CA24DF

[doorbird_wireshark_headers.zip](https://github.com/athombv/homey/files/694232/doorbird_wireshark_headers.zip)

**Comment by jghaanstra** [comment]
As it seems this is somehow related to the way the Doorbird sends the GET request notification to Homey I have logged the headers of this notification request and compared it with a request from both an Android smartphone and a desktop running Windows 10.

The Doorbird only sends the HTTP_HOST requests header while Android and Windows sends more HTTP headers like HTTP_CONNECTION, HTTP_USER_AGENT, HTTP_ACCEPT, HTTP_ACCEPT_ENCODING and HTTP_ACCEPT_LANGUAGE. All requests do contain the correct REMOTE_ADDR, so it's there but perhaps it does not get picked up by Homey because of the other missing HTTP headers?

**Comment by WeeJeWel** [comment]
Yeah, that should work. I'm dependent on Node.js here though. Can you maybe create your own Node.js (4.x) webserver on a PC and try to see if it works there?

**Comment by jghaanstra** [comment]
Creating a Node.js webserver is not much of a problem. Writing a script in Node.js that logs the headers of an incoming request to a file to see what is going on is more of a challenge for me. But I'll see what I can do.

(if you have something running there in Enschede which is accessible through the internet I could also set the notification URL to point to that machine, than you know when someone rings my doorbell or triggers the motion sensor .. ;-) )

**Comment by jghaanstra** [comment]
Super fast and works like a charm (could have figured that out myself I guess).

Anyway, looks like the x-forwarded-for header is not being send but the req.connection.remoteAddress is. I have edited your script and have dumped the req.headers. It only contains the HOST header as already seen before while testing on a local apache server. This is the output I'm getting now.
`ip: ::ffff:192.168.0.134
Dump req.header {"host":"192.168.0.111:3000"}
req.connection.remoteAddress:  ::ffff:192.168.0.134`

So I do not see anything strange that could be causing the args.req.remoteAddress on Homey to be empty.

**Comment by WeeJeWel** [comment]
Always? Maybe keep it running for a day or two, because Homey did sometimes receive it as well.

**Comment by jghaanstra** [comment]
I tried a couple of times last night (it was pretty cold having to trigger the motion sensor every time :-) ).

When setting the notification URL to notify Homey most of the times it crashed the HTTP app due to empty args.req.remoteAddress and only sometimes (my guess is 1 out of 10) it did work. That's suggesting there is something weird is going on within Homey code or at least in combination with the Doorbird and it's not (only) a problem with the Doorbird.

But to make sure I'll will keep the node js server running for a day or so, and will report back here.

**Comment by jghaanstra** [comment]
I have been testing for quite some time now and my testing results make it hard to come to an exact conclusion but here is what I think might be going on (which is a bit of wild guessing).

When the notification URL of the Doorbird is set to send the notification requests to a simple node.js express server I see a hit ratio of 100% where the request.connection object always contains the remoteAddress header.

When the notification URL of the Doorbird is set to send the notification requests to Homey I see a hit ratio of 100% but where the request.connection object only contains the remoteAddress header about 10 to 15% of the time.

So the combination of Homey and Doorbird is giving issues. I have used Wireshark to sniff the traffic between my laptop and the Doorbird and I can see the Doorbird sending a RST packet (reset) to abort the connection once the initial request has been send. I'm not sure why they are not sending an FIN package to finish the connection but aborting it with RST could result in data loss. Perhaps Homey does not have enough time to process the request object and make it available as args in api.js before the connection is aborted resulting in an empty args.req object.

This would explain why it works sometimes on Homey (it just processes the request fast enough sometimes) and always on a local node.js server (which is always fast enough). I'm not sure this even makes sense but this is all I can come up with seeying the test results. 

I understand this might be something that can not be solved at Homey's side but is there any way to confirm this? Can I somehow use req.on("close", function() { ... }); to detect a closed connection for instance in api.js?

In the mean time I'm in contact with Doorbird and will ask them why they are sending a RST packet.

**Comment by jghaanstra** [comment]
This has been resolved, either by a firmware update of the Doorbird or Homey. Closing the issue.
