### ISSUE TITLE
Z-wave flow-trigger: 'Generic alarm turned on' not working 

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#125]
In the flow the z-wave card 'Generic alarm turned on' is not working for a Fibaro Multisensor. The flow is saved. In the devices-screen I see a live updated device card, so device and z-wave is all ok.

![image](https://cloud.githubusercontent.com/assets/15232724/12988503/5de7c6ee-d101-11e5-9b4d-
1d9b202f25a7.png)

**Comment by irritanterik** [comment]
duplicate of #123

**Comment by filoor** [comment]
Have the same problem also with my fibaro door sensor

**Comment by ocatie** [comment]
Associations in non Z-Wave Plus devices have to be set manually for now. Refer to your manual to which group an association has to be made.

You can make an association by clicking the wrench icon on the device. Homeys node id can be found under Settings -> Z-Wave.
