### ISSUE TITLE
Feature: Switch multiply Flows On or Off

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1250]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
I want to Switch more than one Flow On or Off in a action. 
![image](https://cloud.githubusercontent.com/assets/8507396/21780420/c8b9b9ea-d6ab-11e6-9181-eaa48fcc5dc6.png)

**What did you expect as result?**

The same posibility as a speech action card. There its posible to give more then one input.
![image](https://cloud.githubusercontent.com/assets/8507396/21780565/5d156f94-d6ac-11e6-8808-c6ac140fb4b0.png)

**Comment by WeeJeWel** [comment]
Please just add more cards :)
