### ISSUE TITLE
Feature: Clear search filter button for flows

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1251]
Im missing the "X" button in de search filter for the flows:
![image](https://cloud.githubusercontent.com/assets/8507396/21781096/4ac3613c-d6ae-11e6-9a85-a1f5bccd50ca.png)

Like the search filter for devices, systeem "things":
![image](https://cloud.githubusercontent.com/assets/8507396/21781139/784adcde-d6ae-11e6-845f-d4329a56d8ad.png)

**Comment by WeeJeWel** [comment]
Fixed in 1.1.3!
