### ISSUE TITLE
Issue: Area of the "Clear filter button" starts the Test Flow functionality

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1252]
**What is your Homey version (Settings → System)?**
1.1.2 using the HomeyDesktop App 1.0.2

**What did you try to achieve?**
When Ive selected a flow, a make a search filter in the devices list-->
![image](https://cloud.githubusercontent.com/assets/8507396/21781345/3e890b46-d6af-11e6-9009-e1b6491be224.png)

The "X" button to clear the filter doesn't work. The button start the flow, like the Test button does.
![image](https://cloud.githubusercontent.com/assets/8507396/21782041/4216c142-d6b2-11e6-91cb-572eb4ed3ec8.png)
It's not only started when a filter is active. Even when there isn't a filter active, when you click in the area of th "X" button, the Flow start in testmode

*Please include detailed steps how we can reproduce the issue*

- Select the Flow Menu
- Select a Flow (not all the flow)
- Use the filter in the device area, left site
- Clear the filter with the "X" button

**What was the result?**
The select flow is started in test mode.

**What did you expect as result?**
The search filter textbox is cleared.

I've did a lot of tests, with a lot of differents flow. I can't find with Flows are related.
It's not related to:
- Number of characters in the Flow name
- Level in the Flow organize folders
- Not only a specific Trigger

**Triggers who are related:**
- Kaku Switch
- Date / Time / Sun related trigger
- Mi Light trigger
- Better Logic trigger

**Triggers who aren't related:**
- Speech Input 
- HTTP request cards

**Comment by WeeJeWel** [comment]
Thanks! Fixed in 1.1.3
