### ISSUE TITLE
nest/homey thermostat connection

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1254]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Cannot add my Nest thermostat to Homey.The gear wheel in Homey behind 'Geef Homey toestemming voor het gebruik van je Nest apparaten!' keeps rotating and nothing else happens. Tried with the windows app, tried with Chrome, opened the link with Explorer. No result at all.
*Please include detailed steps how we can reproduce the issue*

**What was the result?**
keeps on spinning forever

**What did you expect as result?**
A firm connection

**Any other remarks**

nope

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/2406/nest-authorize-homey

**Comment by satbopper** [comment]
for me the problem is solved
i saw on my telephone app that in my account,homey was granted to work with the nest thermostat
still there was a constant spinning
for me the solution was reboot homey and yes after the reboot,automaticly it was connected
