### ISSUE TITLE
Feature: developer-preview appstore

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/homey#1257]
I would like a developer-preview / beta version of the appstore. In this way we can let people test more easy the apps we develop. Now people have to manually install it and that is not an easy process.

**Comment by joachimroeleveld** [comment]
Good suggestion. It has already been on the planning for some time. I hope to make some time for this soon.

**Comment by joachimroeleveld** [comment]
I am working on this feature currently. I will keep you up to date.

**Comment by joachimroeleveld** [comment]
This is now supported!
