### ISSUE TITLE
Insights: graph should not show future value

### ISSUE THREAD

**Issue by vogon1** [athombv/homey#1258]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Show insight of thermostat setting.
The line between two setting changes is at target temperature level, which looks weird.
E.g. when at 23:00 the thermostat is set at 13 degrees, and the next day at 18:00 set to 20 degrees, insights show a line between 23:00 and 18:00 at level 20 - but the thermostat was set at 13.

*Please include detailed steps how we can reproduce the issue*

Show graph of a thermostat.

**What was the result?**

![image](https://cloud.githubusercontent.com/assets/177368/21910921/78e6c49c-d91e-11e6-8703-61e94643fae4.png)
The yellow line is the requested temperature, the blue one the real temperature.
...

The line between 23:00 and 18:00 should be at 13 degrees.

...

**Any other remarks**

...

**Comment by bvdbos** [comment]
Could you look at the copy the log for the same timeslot? What does it say?

**Comment by daneedk** [comment]
Only changes are logged, no intermediate values at set times, so at 23:00 it is set to 13 and at 20:00 at 20, so the graph represents what is logged. The thing that is not correct is that it does not log that at 19:59:59 the setting as stil 13. This has been debated many times but still not fixed which imo makes insights unusefull.

**Comment by vogon1** [comment]
This is the log for the graph.

Mon Jan 09 2017 00:15:33 GMT+0100 (CET),13
Mon Jan 09 2017 22:38:40 GMT+0100 (CET),21
**Mon Jan 09 2017 23:26:44 GMT+0100 (CET),13**
**Tue Jan 10 2017 18:50:22 GMT+0100 (CET),20**
Tue Jan 10 2017 19:18:59 GMT+0100 (CET),16
Wed Jan 11 2017 00:45:23 GMT+0100 (CET),13
Wed Jan 11 2017 18:44:20 GMT+0100 (CET),20

It shows that the thermostat on Monday 22:38 is set to 21, at 23:26 to 13.
It stays at 13 until Tuesday 18:50, at that time the thermostat is set to 20.

Now look at the graph, the graph shows it the other way around, it looks like the thermostat is set to 20 between Mon 23:26 and Tue 18:50 which is not true.

Sietse

**Comment by Dijker** [comment]
I confirm the same Insights problem with my Thermosmart graphs.
Each Set value DOT should start a new flat line  to the right, jumping to the new set value above/below DOT when the Set Temperature changes. 
![image](https://cloud.githubusercontent.com/assets/12412734/21922795/ac2ddef6-d970-11e6-9222-259f403ab980.png)
It should flip just the other way around...
something like this.... ;-)
![image](https://cloud.githubusercontent.com/assets/12412734/21922861/1ce3e6d6-d971-11e6-9f1f-d17f0b1b742d.png)
