### ISSUE TITLE
Popup [object object] after reboot from system menu

### ISSUE THREAD

**Issue by mvunen** [athombv/homey#126]
Until Homey is back online after a reboot from the system menu a popup is displayed with the text [object object]
<img width="1418" alt="schermafbeelding 2016-02-11 om 20 58 18" src="https://cloud.githubusercontent.com/assets/17176668/12988777/ab99eea2-d102-11e5-918c-cb02f62bd7ab.png">

**Comment by JohanKuster** [comment]
Indeed

**Comment by pkonings** [comment]
Same experience but gone after browser refresh

**Comment by WeeJeWel** [comment]
Which version are you on?

**Comment by matthijsvdr** [comment]
happened to me on 8.17

**Comment by mvunen** [comment]
0.8.17

**Comment by pkonings** [comment]
0.8.17 as well

**Comment by mvunen** [comment]
But I think it has the lowest priority you can think of! :) There are much more hight prio's (never react on voice command, more then one flows breaks flow mechanism etc) (no hard feelings :-D )

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18 :)

**Comment by mvunen** [comment]
:+1:

**Comment by pkonings** [comment]
Well, every fix is one step ahead so :+1:
