### ISSUE TITLE
Please give users the possibility to disable the automatic replies.

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey#1260]
**What is your Homey version (Settings → System)?**

1.1.3

**What did you try to achieve?**

Please give users the possibility to disable the automatic replies. For example when turning lights on. All my lights are turned off and then Homey stutters "ik zet het licht uit"

Related to #1259

**Comment by Willieku** [comment]
Yes,  for me too
The isue i have is; whe i ask  "temperatuur"  homey first tells me  "ik kon geen temeratuursens oren vinden"  then my own flow start running, in wich i also ask for "temperatuur" and wich i let read from a card of weaterunderground.
I am sure there are more exemples.  Would be nice if one can switch them on/off  one by one.

**Comment by WeeJeWel** [comment]
We won't do this, it's too complex and will lead to many situations where people will say 'My Homey doesn't respond to that command!'.

What we will do is warn the user when they're typing their own command in a Flow when it interferes with a system command!

**Comment by DieterKoblenz** [comment]
Pity.. and also I am not asking to disable commands.. I am asking to disable built-in replies, is it really that difficult to add a checkbox somewhere to disable these?

**Comment by WeeJeWel** [comment]
Yes, it's very complicated. I'd advice to use words that are not used in the default system speech parser.

**Comment by Steefph** [comment]
Why not make the option available for the Geeks? When selecting the option the user gets no support on the voice input. I bought Homey to be able to create a system the way I like it and not how you demand me to use it (as it was basically described in the Kick Starter).

**Comment by HackAzz** [comment]
@WeeJeWel I think that the default speech command triggers, are part of the structure of the Homey foundation, and so you can't simply create a feature to enable/disable them.
Or you have to write the Homey software again from scratch, and I think that is not your cup of tea :-D.
Nonetheless, I find this also very annoying, not to say pretty disturbing!
