### ISSUE TITLE
No pairing message on TV with LG webOS (app has crashed)

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#1263]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Connect my OLED55E6V tv to Homey using the LG webOS app v 1.0.0

**What was the result?**

Homey detects my TV but when I click next I see the message "please accept the pairing message on your TV". But there is no pairing message visible on my TV. I then close the window without having seen the pairing request on the TV. When I check the LG webOS app in the settings menu off Homey I see the app has crashed (see crash log below)

**What did you expect as result?**

To have a pairing message on the TV

**Any other remarks**

![image](https://cloud.githubusercontent.com/assets/17165733/21957243/b405b5b8-da92-11e6-8c92-3c9eebf03813.png)

**Comment by bvdbos** [comment]
LG WebOs had a new major version. Closeme? If it still happens in the new version,. please file a bug at:
https://github.com/athombv/com.lg.webos
