### ISSUE TITLE
Date as a string error

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1267]
**What is your Homey version (Settings → System)?**
1.1.2

*What did you try to achieve?*
I try to set a date string to a custom capability with type String.
The date string looks like this: '2017-01-15 21:57:42'
I also use the value.toString() function before i call the realtime function.

When i call the module.exports.realtime function i get this error message: 
[Error: invalid_type] message: 'invalid_type'

If i change the space to an other charater its working.
'2017-01-15_21:57:42' will is working.
I need to add a space before the date to make this work ' 2017-01-15 21:57:42'

You can find more about it at slack in the developers channel.

**Comment by WeeJeWel** [comment]
Can you share your custom capability json?

**Comment by ewikner** [comment]
This is how it looks like.
`"mysensors_lastseen": {
            "type": "string",
            "title": {
                "en": "Last Seen"
            },
            "getable": true,
            "setable": true
        },
`
We are using it now in the mysensors app.
[https://github.com/ewikner/org.mysensors.homey/tree/feature/1.0.0-beta1](Mysensors app)
Here you can see the data string [https://github.com/ewikner/org.mysensors.homey/blob/feature/1.0.0-beta1/drivers/mysensors/lib/NodeClass.js#L115](lastseen)

**Comment by WeeJeWel** [comment]
Sorry, I cannot reproduce, so it must be a bug somewhere in your app.

![screen shot 2017-01-16 at 20 07 23](https://cloud.githubusercontent.com/assets/319873/21995851/6fc9b9a8-dc27-11e6-8ac0-ee1d54580e7e.png)

```
let value = (new Date()).toString();
this.realtime( device_data, 'testsuite_string_capability', value, console.log );
```

**Comment by irritanterik** [comment]
@WeeJeWel can you retry with 
```
let value = '2017-01-15 21:57:42'
this.realtime( device_data, 'testsuite_string_capability', value, console.log );
```

**Comment by WeeJeWel** [comment]
Fixed :)
