### ISSUE TITLE
[Suggestion] Insight in the mobile app

### ISSUE THREAD

**Issue by 4tetra4** [athombv/homey#1269]
**What is your Homey version (Settings → System)?**

Any

**What did you try to achieve?**

To see the movement and other alert history while on holiday. 

**What was the result?**

Insight is not available in the mobile app so can`t see if someone has entered the house or garden in a given period.

**What did you expect as result?**

To see what is happening in the house.

**Comment by WeeJeWel** [comment]
Yes, this is planned. Closing this issue now because it will be part of the new Homey Smartphone App.
