### ISSUE TITLE
[Suggestion] Mobile app - Dashboard

### ISSUE THREAD

**Issue by 4tetra4** [athombv/homey#1271]
**What is your Homey version (Settings → System)?**

Any

**What did you try to achieve?**

To have an customised overview of the status of the home (temperature, humidity, alerts, insight, etc) and some `scene` buttons.

**What did you expect as result?**

To have a dashboard like other home automation systems.

**Other notes**
https://in.pinterest.com/explore/dashboards/

**Comment by djeskoswe** [comment]
https://forum.athom.com/discussion/1736/beta-release-homeydash-a-dashboard-app-for-homey/p1

**Comment by 4tetra4** [comment]
That is not a true dashboard. It is a tablet UI for turning things on and off.

**Comment by caseda** [comment]
It will become a full fledged dashboard (that is why it is called that way) and is full in development, the (community) developer is putting a lot of time into it expanding capabilities as we speak.. Don't expect anything else within the first half year.

**Comment by 4tetra4** [comment]
As far as I know that `dashboard` a webpage. So it won`t have homey`s voice recognition integrated, can`t turn on screen when a movement is detected so on...

**Comment by WeeJeWel** [comment]
Yes, this is planned. Closing this issue for now as the idea has been noted.
