### ISSUE TITLE
[Suggestion] Add date of release/update by app info in store

### ISSUE THREAD

**Issue by Marc1979** [athombv/homey#1272]
Could it be possible to add the date of release/update on the info page of the app.
So you can see the version number and when the app is updated last time..

**Comment by TheMrCaveman** [comment]
Would like this indeed, it is very strange that some of the original athom apps have some sort of changelist. 
And some of them are just showing the app version and that's it. So with release date and a proper changelog there is better information for users and with that information we also know if issues have been fixed, 'or not' and prevents multiple issues about the same problem.

**Comment by joachimroeleveld** [comment]
The app store will get an update very soon and this feature will be included!

**Comment by TheMrCaveman** [comment]
Thanks a lot!!

**Comment by Marc1979** [comment]
Thanks!

**Comment by joachimroeleveld** [comment]
And voila :)
