### ISSUE TITLE
[Suggestion] Add firmware of device to device settings dialog

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#1273]
Can the firmware of a device (for example a z-wave device) be read from a device and shown in the device's settings dialog.

@caseda has contacted @WeeJeWel about this but has not received a response.
https://forum.athom.com/discussion/comment/43980/#Comment_43980

**Comment by caseda** [comment]
and if (easily) possible, also add it to the node array, so it's usable for example in setting changes in version updates 😃

**Comment by WeeJeWel** [comment]
Added:

![screen shot 2017-10-31 at 19 49 56](https://user-images.githubusercontent.com/319873/32243082-bd90a19e-be74-11e7-80dd-3ad6aa120c52.png)

**Comment by WeeJeWel** [comment]
@caseda `node.firmwareId` should be available in Apps

**Comment by WeeJeWel** [comment]
Please note that a re-pair of a device is necessary for this information to show up.
