### ISSUE TITLE
[Improvent] Specify device providing a Value when hove-over Token

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1274]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Check if I used the correct Token in a flow.

*Please include detailed steps how we can reproduce the issue*
Drop a Token Temperature on a action Card. Hove over to verify that I droped the correct Outside temperature and not one of the other tokens labeled Temperature. 

**What was the result?**
Hove Over mentions Temperature, 

**What did you expect as result?**
The name of the Device providing the Temperature (Berlioz:Buiten:Temperature ) 

**Any other remarks**
![image](https://cloud.githubusercontent.com/assets/12412734/22009924/67ccfe36-dc86-11e6-8b2c-a9b8c6a3a0f7.png)

**Comment by WeeJeWel** [comment]
Great suggestion! Added in 1.2.0

**Comment by Dijker** [comment]
Thanks, 
Works Great !
Confirmed!
