### ISSUE TITLE
cannot add nest devices,spinning wheels

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1275]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
i gave nest permission to work with homey - owner of the nest
on my tel app,i can see that the permission for homey is available
the result is endless spinning nest devices,so not possible to add
if i do above to a family member i get permission and the possibility to `intrekken permission´
then the devices are not spinning,if i try to add them i get ér zijn nieuwe apparaten gevonden
rebooted homey then same issue
ptp then same issue
there is a normal wifi connection from the nest thermostat to my router,with my tel app i can work with it as normal
*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by bvdbos** [comment]
So it doesn't work after all?
https://forum.athom.com/discussion/comment/43290/#Comment_43290
