### ISSUE TITLE
[Enhancement] When only one mobile device for a specific user, use that device

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#1276]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Use my new mobile phone in flows.

**What was the result?**
Had to go through all my flow and select the correct phone even though I deleted all other phones but the new one from https://my.athom.com/#/phones

**What did you expect as result?**
That Homey assumes that the only phone in https://my.athom.com/#/phones is the correct phone and uses that device instead of having the user go through all their flows and correct them.

**Any other remarks**
Really happy with my Homey!

**Comment by WesRos** [comment]
This week I had the same thing. I had to search in all the flow for a Phone action card. A solution could be to make a choice for the user in the action card, and not for a phone device. 
A search filter in the Flow page for Card would make the search filter engine better. A little dropdown list where to search: foldernames, flownames, devicename, cards, etc.

**Comment by WeeJeWel** [comment]
We've discussed this, but it's too complicated to make two different behaviors. Sorry!

**Comment by Inversion-NL** [comment]
I'm sorry but what do you mean by two different behaviors?

**Comment by WeeJeWel** [comment]
The 'when only one phone, use that device'. Features like these are very common to result in bugs. E.g. what would happen when a second phone is added? Or the first is removed?

Keeping it simple usually does improve the stability, as well as the understandability of a feature for a user. That was a hard lesson for us that took a long time to learn :-)

**Comment by Inversion-NL** [comment]
Great, thanks for your answer
