### ISSUE TITLE
Negative decimal numbers to speech

### ISSUE THREAD

**Issue by nieuwton** [athombv/homey#1277]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
I used a speech card to let Homey say a negative decimal temperature, e.g. "-1.5 degrees". Homey will say "one point five degrees".

*Please include detailed steps how we can reproduce the issue*
Use a speech card or "http://homey_address/manager/speech-output/

**What was the result?**
"-1.5" is pronounced as "one point five".
"-1,5" is pronounced as "minus one point five".
...

**What did you expect as result?**
"-1.5" is pronounced as "minus one point five".
...

**Any other remarks**
Language is Dutch, but Logic and Better Logic are giving results with a decimal point.
...

**Comment by chrisboer** [comment]
same issue with netatmo

**Comment by Tweake** [comment]
Thanks for reporting the issue! This will be fixed in Homey version 1.2.0

**Comment by bvdbos** [comment]
works for me now...
