### ISSUE TITLE
Rename device error

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1278]
**What is your Homey version (Settings → System)?**
1.1.3

**What did you try to achieve?**
When i rename a device then all values will set to default null
If i then try to update the value with the realtime function i get the error { [Error: invalid_capability] message: 'invalid_capability' }

Here is how it looks before i rename the device.
![before rename](https://cloud.githubusercontent.com/assets/17088588/22069509/00984702-dd99-11e6-9d78-7a5bb881df85.png)

Here is how it looks after i rename the device.
![after rename](https://cloud.githubusercontent.com/assets/17088588/22069515/05cc1bea-dd99-11e6-97cd-17a3371f1270.png)

@WeeJeWel said on slack, that it's fixed and will come on the next build.

**Comment by WeeJeWel** [comment]
Thanks for reporting!

**Comment by ewikner** [comment]
Thanks for fixing it fast!
