### ISSUE TITLE
Homey can only handle 1 voice command setup 

### ISSUE THREAD

**Issue by matthijsvdr** [athombv/homey#128]
So when i create a flow with a speak command, then that flow works. 
But if i then try to turn the lights off, homey does nothing.
Removing the flow with the voice command, and i can control the lights again.

Same thing when adding 2 flows, flow goes a follow:
I say something
homey repeats

Adding 2 flows
One with the word station
One with the word hello

only the first one added works, second won't, and light control also does not work

//edit//
Wikipedia/chuck norris/all other apps did not work, but it does after removing all the flows
Seems like voice commands and system + apps don't work together :)

**Comment by RuudBurger** [comment]
Thanks for this. This was it. I had one flow at the top that "stopped" everything other flow following in the list.
If I only have one flow active, it works.

**Comment by Omemanti** [comment]
[#113](https://github.com/athombv/homey/issues/113)

**Comment by peaoo** [comment]
Hey, same problem here, made a video of it.
After creating the flow with speech trigger "example" all lightswitching commands stop working.
https://youtu.be/6sWZSFzPIUE
Hope this helps

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.18. Please re-open this issue if the problem persists.

**Comment by matthijsvdr** [comment]
Sorry to report, but just updated to 8.20. And i can only get it comes to work.

Homey does understand exactly what the trigger would be for the you said something, but the flow is not executed.
1 flow + homey it self work

But creating 2 flows with the you said something breaks the system and homey does not respond to anything

**Comment by WeeJeWel** [comment]
Can you post screenshots?

**Comment by matthijsvdr** [comment]
I even used the manager/speech-input/ by copy pasting the text into the field, but homey does not respond (not even to: whats the time)


Parrot flow, pushes all text to slack
![parrot](https://cloud.githubusercontent.com/assets/1271035/13335663/705189f2-dc12-11e5-8dbe-58814207e19b.png)

Should "activate" the office at home
![activateoffice](https://cloud.githubusercontent.com/assets/1271035/13335662/702f909a-dc12-11e5-856e-1f2f0888bbea.png)

Search
![search](https://cloud.githubusercontent.com/assets/1271035/13335715/af007762-dc12-11e5-8c1b-ec74013018d6.png)

**Comment by matthijsvdr** [comment]
One small update: it now seems to respond to only 1 flow, but nothing else

**Comment by matthijsvdr** [comment]
Any updates? i havent really been using homey as there are still to many issues :)
