### ISSUE TITLE
Display of README.md

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#1280]
I have two issues with the displaying of the README.md files in the store;
 - List indentation is not supported (only 1 level of indentation)
 - Links blend in with text. They are not visible as links until the user happens to hover it

Also;
 - You might want to look into supporting/automagically self-hosting relatively linked images from the repository (like Github does)
 - Look into supporting multiple languages (Maybe something like README.nl.md, README.it.md)

**Comment by joachimroeleveld** [comment]
I updated the links to have a more distinctive color now. List indentation and multiple levels work fine for me. Your Markdown syntax may be incorrect. 

Thanks for the other suggestions, multiple languages will be supported in the future. I'm afraid self-hosting images has a lower priority for now.
