### ISSUE TITLE
Philio PST02-1C sensor door/temp/light

### ISSUE THREAD

**Issue by kennybeu** [athombv/homey#1281]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Working the pst02-1c

*Please include detailed steps how we can reproduce the issue*
Adding the sensor whit the existing app

**What was the result?**
nothing
...

**What did you expect as result?**

...perfectly workig the door/temp/light sensor

**Any other remarks**

...
![pst02-1c](https://cloud.githubusercontent.com/assets/25205719/22074997/9b4c5c5a-ddaa-11e6-923e-dd8c2d9feb25.jpg)

**Comment by bvdbos** [comment]
You'd better add an issue to the Philio-repro:
https://github.com/Inversion-NL/com.philio
