### ISSUE TITLE
[Enhancement] Info or question mark near or next to the memorybar

### ISSUE THREAD

**Issue by timk1990** [athombv/homey#1283]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Notting really. Just helpen the new kids not to get scared.

**What was the result?**
...

...

**Any other remarks**

It would help to place an info or question mark sing next to the memory bar. There are a lot of new homey user that don't get the linux memory usage. So there a lot of question about full memory. An explenation or link to: http://www.linuxatemyram.com will be help and prevent them from thinking it a problem.

**Comment by corvdniet** [comment]
Some explanation about "Other" memory would be welcome.

**Comment by WeeJeWel** [comment]
I've renamed 'Other' to 'System', hope that helps. I don't want to make the page too technical.

**Comment by WeeJeWel** [comment]
(Also added swap info)

**Comment by corvdniet** [comment]
Swap info will help ... thnx for that. 
Renaming the text "Other" to "System" does not resolve reports about more than 200 Mb's of Other memory, probably caused by memory-leaks ... only workaround = reboot.
Is Athom working on a solution for that?

**Comment by WeeJeWel** [comment]
Yes we are!
