### ISSUE TITLE
SmartAlarm issue

### ISSUE THREAD

**Issue by Mwahhh** [athombv/homey#1284]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Arm the alarm trough a flow.

*Please include detailed steps how we can reproduce the issue*

After installation and connecting the alarm try to arm the alarm. It only works once and then the error occurs.

**What was the result?**

Stack trace:

TypeError: Cannot read property 'state' of undefined
at Object.check_state (/drivers/smartalarm/driver.js:242:47)
at emitThree (events.js:97:13)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:12:37
at /homey-app/helpers/client.js:1:1077
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:1046)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

Exit code: 1
Exit signal: null

**What did you expect as result?**

Arm the alarm.

**Any other remarks**

All the available options in a flow wont work. It doenst matter what kinda action I want to do it always gives this error.

**Comment by Mwahhh** [comment]
+P2P, reinstalling the app, etc. did not work

**Comment by BasKiers** [comment]
Hi, 

Sorry for the late response. I finally got to rewriting this app since patching the original version was not helping anymore. I hope this fixes all issues! If not, please open a new issue and I will pick it up as soon as possible.

Regards,
Bas
