### ISSUE TITLE
[Z-wave] Multi Channel association not possible (input validation NOK)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1285]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Add a multi channel end-point (Light connected to one of the Greenwave Powernode-6 sockets) node ID to the association group of a Fibaro Dimmer-2 (supporting COMMAND_CLASS_MULTI_CHANNEL and COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION) to switch on the light simultaneously with the light connected to the Dimmer-2

**What was the result?**
Input validation of the association groups field does not accept non integer input (e.g. 10.1) to indicate the node ID of the multi channel end point (light connected to the greenwave powernode)
<img width="655" alt="schermafbeelding 2017-01-21 om 10 45 31" src="https://cloud.githubusercontent.com/assets/17163431/22173528/096a5f7a-dfc7-11e6-9c88-df6379bf4f6d.png">

**What did you expect as result?**
Able to add it to the association groups.

Has the COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION been fully implemented and is this only an input validation issue or is the COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION not (fully) implemented yet? 

**Any other remarks**
Work around is to create a flow within Homey to do this.
But this is not the desired situation. Specifically in case of Z-wave sensors with alarm capability (e.g. motion or smoke sensors) it should be possible to directly switch on (or off) any other Z-wave devices by creating a direct association

In addition, new Z-wave Multi-channel sockets are currently under development by different parties...

**Comment by RobinBol** [comment]
Thanks for reporting! We indeed found out that MULTI_CHANNEL_ASSOCIATION is not entirely support as of yet.

**Comment by TedTolboom** [comment]
What are the plans to support MULTI_CHANNEL_ASSOCIATION?

This currently limits the use of direct association (e.g. FGMS-001 to trigger a FGS-223 Switch-2 connected device) or full interaction of Z-wave devices (e.g. assign a FGS-223 Switch-2 connected device to the S2 of a FGD-212 Dimmer-2)

**Comment by WeeJeWel** [comment]
It's on my list

**Comment by TedTolboom** [comment]
Reminder / Pushing the issue up on your list...

**Comment by djanssen1** [comment]
Yes, this would really help me as well

**Comment by MiklerGM** [comment]
This is a necessary functionality for multi-button switches owners. Thanks

**Comment by hfaas** [comment]
This issue is open for quite a while now and also still doesn't seem to be scheduled (at least no milestone is set). Is there an estimation on when to expect this functionality?

**Comment by lurendrejer** [comment]
I really miss this functionality too. It's a key feature of z-wave - and i know homey can do well, i've seen it done horribly on other controllers before.

**Comment by lurendrejer** [comment]
Just adding, people i recommend Homey to in z-wave forums are holding off due to this functionality not being implemented.

**Comment by WeeJeWel** [comment]
Added support for this in v1.5.1.

![screen shot 2017-08-30 at 18 04 57](https://user-images.githubusercontent.com/319873/29882688-1a881140-8dae-11e7-8211-f653ea1d21f1.png)

**Comment by lurendrejer** [comment]
How many handjobs would it cost to get that version right now?

**Comment by cbho** [comment]
Is it correct, that this is actually not implemented in 1.5.1 - but will first be in 1.5.2?
Is missing the multichannelassociation so very much...

**Comment by WeeJeWel** [comment]
Yes, this will be added in 1.5.2

**Comment by lurendrejer** [comment]
Is there an expected release date?

**Comment by WeeJeWel** [comment]
Today to Developer Preview

**Comment by lurendrejer** [comment]
Anything expected for experimental? :)

**Comment by WeeJeWel** [comment]
ASAP!

**Comment by lurendrejer** [comment]
Meh :-P

**Comment by bvdbos** [comment]
https://athomcommunity.slack.com/messages/general ?
