### ISSUE TITLE
nest luchtvochtigheid

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1286]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
de luchtvochtigheid is not updated in the flow tags,so you can not use the tag in flows
both temps are working
*Please include detailed steps how we can reproduce the issue*

**What was the result?**

no updating of the tag,only for the luchtvochtigheid

**What did you expect as result?**

if on the nest the amount of the luchtvochtigheid changes,it should update the tag

**Any other remarks**

...

**Comment by RobinBol** [comment]
Hi, I just tested you issue with the latest Nest app version and the latest Homey firmware and there are no problems with the updating of the humidity tag value. Could you update to Homey firmware 1.1.9 and test if this issue is still present?

**Comment by satbopper** [comment]
in homey 1.1.9 it is ok thanks for the effort
