### ISSUE TITLE
App not installing on homey

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1287]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Install KlikAanKlikUit first from add device page with install button

*Please include detailed steps how we can reproduce the issue*
Go to add device and type in klikaanklikuit see the right install button as this app was not present on homey

**What was the result?**
Application not being installed, homey went offline.
Waited about 3 minutes and homey came online again.
Tried the same but now installed the app from the app store but same result got this error message
![klikaanklikuit](https://cloud.githubusercontent.com/assets/23163409/22185139/6a0ac6f2-e0e0-11e6-8917-6595a4c4c262.jpg)
![memory_homey](https://cloud.githubusercontent.com/assets/23163409/22185143/7a99bd20-e0e0-11e6-8487-9e252fdfb853.jpg)

**What did you expect as result?**
Correct installation of the App KlikAanKlikUit

**Any other remarks**
After a reboot off homey installed the App from the appstore which went fine again.

...

**Comment by bvdbos** [comment]
probably related to #1195

**Comment by joachimroeleveld** [comment]
I will edit the error message to be a bit more meaningful than this. Apart from this, this is a Homey client issue.

**Comment by chrisboer** [comment]
works with 1.1.9
