### ISSUE TITLE
Allow setting of optional in z-wave multiChannelNodes config

### ISSUE THREAD

**Issue by clandmeter** [athombv/homey#1288]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

Some devices (Qubino shutter) allow setting a parameter that introduces a multi channel child device.
Currently its not possible to include such device if the multi channel node is not available. 
Adding an option "optional: true" could fix this (similar like in zwave-driver).

**Comment by WeeJeWel** [comment]
@RobinBol Could you please look into this issue?

**Comment by RobinBol** [comment]
Do you have an example device that currently has this issue? (not one of the roller shutters, see: https://github.com/athombv/homey/issues/1317#issuecomment-287067832)

**Comment by clandmeter** [comment]
This is not a device issue, its a design issue. It depends how you setup the mutli-channel device in your app.

As example we can take the temperature sensor in Qubino devices. Currently they are always added as an extra capability inside the existing device and can be ignored by setting the option "optional" to true. This however keeps the mobile card available but with no data provided by homey core. I don't think its good idea to clutter the interface with devices that are optional and not enabled.

I am not sure if there are currently multi-channel devices available when it makes sense to separate the multi-channel device in its own child device, but for the Venetian blind I've seen other domotica solutions do that same, have another child device to control the slats position.

I have since then moved the multi-channel device back to its master device and have both sliders side by side, but because #1296 is still open it looks weird for users who do not want to control the slats. 

In the end, I don't think its makes sense to spend time on this issue (no current use case) but spend time on #1296 so we can hide unused/ignored capabilities.

**Comment by RobinBol** [comment]
I was just asking to see if you knew a device with which I could test this:) 

Concerning #1296 I think that in the near future we will look at these kind of enhancements as they have to be tackled generically in homey-core!

**Comment by clandmeter** [comment]
Not really, i think only Qubino have parameters to enable multi-channel features? But I guess you've seen more z-wave devices then me :)

**Comment by WeeJeWel** [comment]
This has been fixed, see the docs: https://developer.athom.com/docs/apps/tutorial-Z-Wave.html
