### ISSUE TITLE
Installation fails @ https://apps.athom.com/app/com.ring

### ISSUE THREAD

**Issue by vanderaatje** [athombv/homey#1291]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.1.2

**What did you try to achieve?**

Install ring application version 1.1.0

*Please include detailed steps how we can reproduce the issue*

Click install button in app store

**What was the result?**

error message: Homey is unreachable try again

**What did you expect as result?**

Installation finish OK

**Comment by bvdbos** [comment]
Think this works now after the login-server was back online?

**Comment by vanderaatje** [comment]
Correct
