### ISSUE TITLE
HUE Light don't turn off

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#1293]
**What is your Homey version (Settings → System)?**

Homey firmware 1.1.2 and HUE app 2.2.1

**What did you try to achieve?**

Automatic turn the hue light off after one minute.

*Please include detailed steps how we can reproduce the issue*

I made a flow, that when there is motion in the hall (hue motion sensor), and it's after sunset and before 23.00  the hue light turn on in the hall. In the same flow i use a card that turn the light off with a delay of one minute. 

**What was the result?**

The HUE light doesn't turn off. 

**What did you expect as result?**

That the HUE light will turn off after one minute.

**Any other remarks**

When i don't use the flow card for turning off the specific hue light in the hall, and i use the flow card for turning off al the lights in the hall (i have only one hue light in the hall) then it works and the hue light will turn off. :-)

**Comment by Mwahhh** [comment]
Same issue here since 2 days. Homey cannot turn the Hue lights off.

**Comment by bvdbos** [comment]
Did you install Homey logger and see if the command is sent?

**Comment by backslashgithub** [comment]
@bvdbos Homey logger; Philips Hue	Not connected	This app does not support realtime logging

**Comment by WeeJeWel** [comment]
Does this still occur with Hue version 2.2.3?

**Comment by Mwahhh** [comment]
In my case this issue is fixed!
