### ISSUE TITLE
incorrect eletric and gasmeter values in Toon device card

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1294]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Get a correct reading of gas meter and eletric meter value on Toon device card

*Please include detailed steps how we can reproduce the issue*
Go to the device card of Toon 

**What was the result?**
it shows the wrong value
...

**What did you expect as result?**
Correct values. The temperature value seems correct

**Any other remarks**
It seems that the values shows are from this morning, so the temp gets updated correctly but gas and eletricity not
I already mentioned it on Slack to @RobinBol, posting this to make it official

**Comment by RobinBol** [comment]
Thanks for reporting the issue, currently we have removed the electric/gasmeter readings from the Toon app. It caused too much instability and too many api requests. Will close this issue for now. Not sure if this functionality will come back anytime soon, first the app needs to become more reliable.
