### ISSUE TITLE
[KaKu] Not pairing anymore with APA3-1500R or AGD2-3500R

### ISSUE THREAD

**Issue by Amelsfort** [athombv/homey#1298]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

A few days ago I noticed Homey wasn't turning on one of the lights in the living room. It was the only one using KlikAanKlikUit (a APA3-1500R).
I tried re-pairing them, but that didn't work. I tried pairing using the generate signal option and copy from remote, but neither did work. I read somewhere that I might be caused by the LED-ring, but even after switching it off, I was unable to pair the outlet. Also a reboot of Homey didn't make any difference.

**Any other remarks**
I also noticed my garden lights weren't switched on either! They are connected to a AGD2-3500R. I also was unable to re-pair them using the remote to copy from.

**Comment by Amelsfort** [comment]
I just noticed that, according to my Homey Insights, none of the Kaku-switches have been switched since January 28. The other lights, from the same flows, worked fine.

**Comment by Dijker** [comment]
Hi, 
Re- pairing should not be necessary, 
Did you also try to restart the microcontroller in Settings - System ?
If that one doesn't fix a PtP by  hard powerdown waiting a minute before powering and  restarting should work.
These two are preferred imho above a restart from software  (that only restarts the Homey fw but not everything in the other microcontrollers ) and re-pairing that only adds the same device again. 

Did you recently add other apps that use that microcontroller for 433 and 868?

**Comment by Amelsfort** [comment]
I did try restarting the microcontroller first, but that didn't make a difference.
This morning I did a PtP and I noticed the lights in the garden were switched on afterwards. Using the Homey-app, I was also able to switch them on and off. 

The switch I tried re-pairing still isn't working though. But that might be because I did reset the switch yesterday, so I'll try it again this evening.

**Comment by Amelsfort** [comment]
I was able to re-pair the switch in the livingroom and everything is working fine again. Although I did restart the microcontrollers before, only the PtP seemed to have worked.
