### ISSUE TITLE
Z-Wave: Motion and Tamper Alarm of Fibaro Motion Sensor unavailable

### ISSUE THREAD

**Issue by Gand41f** [athombv/homey#1299]
**What is your Homey version (Settings → System)?**

1.1.2 Homey
1.1.9 Fibaro

**What did you try to achieve?**

I would like see the state of the motion and tamper alarm of my Fibaro Motion Sensor (Z-Wave Plus).

**What was the result?**

![motionsensorerror](https://cloud.githubusercontent.com/assets/18631286/22442931/556d77ae-e73d-11e6-933d-c11358cfd0b7.jpg)

As seen in the screenshot, I do see nothing. I already tried rebooting and waiting for a couple of hours, but nothing changes. Even if I trigger the motion alarm or the tamper alarm, nothing changes. This is for all of my 5 sensors the same. One of them is 2m away from Homey. Some of them show a temperature and lux level but not all.

Already tried a complete reset of my Z-Wave network, but it only worked then for a short time. After a reboot this afternoon nothing works again. Even then, not all motion alarms were shown in their correct state.

**What did you expect as result?**

To see the status of my motion and tamper alarm of all of my sensor, so that I can make flows with them.

**Any other remarks**

**Comment by backslashgithub** [comment]
same problem here, problem was also in other issues mentioned. but never solved.

**Comment by WeeJeWel** [comment]
Please try again on Homey v.1.1.4

**Comment by Gand41f** [comment]
Motion Alarm shows a status on all of my motion sensors (although not always the correct one). Tamper Alarm shows a dash, but when triggerd since the last reboot it changes to yes/no. Temperature and luminance seem to be working.

**Comment by WeeJeWel** [comment]
@Gand41f Please try re-pairing your device with the latest Fibaro app. That might just do the trick

**Comment by backslashgithub** [comment]
Homey v.1.1.4 ? i'm running Homey Firmware Versie: 1.1.2.

v.1.1.4 only on exp update ?

**Comment by WeeJeWel** [comment]
Yes, 1.1.4 is only on the experimental channel yet.

**Comment by Gand41f** [comment]
It seems to work expect for one sensor. The Z-wave log for the the faulty sensor (Node 16) shows:

`[2017-02-11T22:06:05.754Z] Node[16]: Received application command for an unknown Command Class, data: (removed)
[2017-02-11T22:06:36.421Z] Node[16]: Received application command for an unknown Command Class, data: (removed)`

I removed whats behind `data:`, because I do not know whether it is security relevant to my Z-wave network.

**Comment by Gand41f** [comment]
Re-pairing the faulty sensor seemed to help. Now everything works perfect. I copied the logs of the faulty sensor to a txt-file. If you need it for debugging please let me know.

**Comment by WeeJeWel** [comment]
Alright, thanks. Seems like the device just needed a reset :)
