### ISSUE TITLE
Showstopper for Fibaro Door/Window Sensor cannot be chosen in a flow

### ISSUE THREAD

**Issue by athomey** [athombv/homey#13]
Reproduction: I add 2 Fibaro Door/Window Sensors. They appear in as sensors with a gauge symbol in the Devices section. Now I create a flow, and I click on the list of Devices to choose which Sensor to in the When. 

Bug: In the devices drop-down I cannot choose one of my 2 Fibaro Door/Window Sensors. Homey says No devices found...   

Also tried: Al other devices on the left of the flow editor. I cannot choose them anywhere.

**Comment by ocatie** [comment]
Are you sure you use an Alarm Generic action card? You can switch cards with the up/down arrows on the right.
![image](https://cloud.githubusercontent.com/assets/16609932/12207492/2725356c-b647-11e5-847e-d6bd0b459000.png)

**Comment by ocatie** [comment]
Tested with door/window sensor.

**Comment by athomey** [comment]
Hey ocatie. Thx for your prompt feedback. No, I didn't try a generic alarm, I tried many of them and gave up when each time I couldn't select it. I think your intuitivity in this part has much left to be desired. It's very difficult and unclear to use and select right device. I think this should be changed. Thanks for the hint that a Door Sensor is a generic alarm, there I could select it. I will experiment further.
