### ISSUE TITLE
Toggling the option "download and install..." off and on within the updates menu causes Homey to reboot

### ISSUE THREAD

**Issue by wslybkkr** [athombv/homey#130]
When opening the updates menu and toggle the option: Download and install updates automaticlly (recommend) off and on causes my homey to reboots itself. Note: This maybe caused because my homey needed an update. But this should not happen i  may presume?

Maybe it's better tot create a button todo a forced update check instead of the behavior homey is showing now.

**Comment by WeeJeWel** [comment]
This is fixed in 0.8.17
