### ISSUE TITLE
Desktop application keeps resizing

### ISSUE THREAD

**Issue by wddeelen** [athombv/homey#1300]
## What OS is are you running?
Windows10 x64

## What webbrowser did you use to download the setup/dmg file?
Chrome

## What is the version of the setup file/ application?
ex. v1.0.2

## What did you expect to happen and what did actually happen?
If i use the desktop application on windows 10 x64 and resize the app to half of the screen (I have a big screen resolution 3440x1440) with the key combination "WINDOWS-KEY + ARROW-KEY-LEFT" it go to side of the screen like expected. But if i switch in the application from devices to flows for example the desktop application window resize itself to i gues some percentage of my screen resolution. I expect that the app stay on position like any other application does.

Hope somebody have some time to check this and can fix it.

Keep up the good work with homey!

**Comment by chrisboer** [comment]
Same issue here with 4k screen, but a known issue I think.

**Comment by TheMSB** [comment]
We are aware of the issue and are working towards a fix.

**Comment by chrisboer** [comment]
I can drag the tags without using F11 now with homey 1.1.9 so this can be closed for me !

**Comment by TheMSB** [comment]
@chrisboer @wddeelen , can either of you confirm if this issue still persists with Homey Desktop 1.0.3?

**Comment by chrisboer** [comment]
@TheMSB resizing I don't had this issue in 1.0.2 and also not in 1.0.3 but could you or somebody show on video or with multiple pictures what he means by resizing (I understand with resizing window resizing with every click or opening of a new topic or screen)

**Comment by WeeJeWel** [comment]
Closed due to inactivity. If the issue persists, please let me know.
