### ISSUE TITLE
Oeps, ik kan de server niet bereiken

### ISSUE THREAD

**Issue by StraDijk** [athombv/homey#1301]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Nothing, Homey looses wifi connection 1 or 2 times a week.

*Please include detailed steps how we can reproduce the issue*
i can't reproduce the issue

**What was the result?**

**What did you expect as result?**
That Homey keeps connected to wifi.

**Any other remarks**
- PTP solves the problem for a few days. 
- No other wifi networks in range and replaced the wireless router with another one.

**Comment by jeroenvollenbrock** [comment]
Can you send me a log please? (Settings -> System-> Send Log)

**Comment by StraDijk** [comment]
D707D15399

**Comment by WeeJeWel** [comment]
Probably a temporary cloud or wifi glitch.
