### ISSUE TITLE
reminder not returned to originating source

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1305]
**What is your Homey version (Settings → System)?**
1.1.4

**What did you try to achieve?**
Have Homey remind me in a minute
![2017-02-04 12_19_31-homey speech input](https://cloud.githubusercontent.com/assets/1064079/22618089/88e9f77a-ead4-11e6-8574-efac95341d1b.png)

**What was the result?**
![2017-02-04 12_19_55-homey speech output](https://cloud.githubusercontent.com/assets/1064079/22618091/90c6bcbc-ead4-11e6-911b-1d69021ddeb0.png)

**What did you expect as result?**
reminder sent to originating source (mobile app)

**Any other remarks**
the contents of the reminder is #1306

**Comment by Tweake** [comment]
Thanks for reporting the issue. However, depending on the context of the reminder it is not always desirable to return the reminder to the same source. Therefore we have decided to leave it unchanged for now.
