### ISSUE TITLE
reminder contents is vague

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1306]
**What is your Homey version (Settings → System)?**
1.1.4

**What did you try to achieve?**
Set a reminder
![2017-02-04 12_19_31-homey speech input](https://cloud.githubusercontent.com/assets/1064079/22618178/5c6cf61e-ead6-11e6-8601-4b323322f1ce.png)

**What was the result?**
contents of reminder is vague
![2017-02-04 12_19_55-homey speech output](https://cloud.githubusercontent.com/assets/1064079/22618180/72f9b4b2-ead6-11e6-87b7-ee78d1cd0e4f.png)

**Comment by JPe2** [comment]
(as a work around) you could use a dark background.  IMO to many texts are vague but it seems to be modern to use soft texts, and that's more important than readability 👎

**Comment by bvdbos** [comment]
LOL, sorry... Didn't mean that: I mean the  reminder was "ing" but don't know why...

**Comment by Tweake** [comment]
Thanks for reporting the issue, should be fixed with Homey version 1.2.0

**Comment by bvdbos** [comment]
fixed:
![2017-03-22 08_00_59-homey speech input](https://cloud.githubusercontent.com/assets/1064079/24185881/c56e6d50-0ed5-11e7-9f4f-92b95a7e5c7d.png)
![2017-03-22 08_00_32-homey speech output](https://cloud.githubusercontent.com/assets/1064079/24185887/cbb12ae0-0ed5-11e7-8dec-90ed16561bd4.png)
![2017-03-22 08_01_03-homey speech input](https://cloud.githubusercontent.com/assets/1064079/24185891/d1278186-0ed5-11e7-81c7-06240695b857.png)
![2017-03-22 08_00_48-homey speech output](https://cloud.githubusercontent.com/assets/1064079/24185900/da22e94c-0ed5-11e7-980a-eca99d409a01.png)
