### ISSUE TITLE
Toon disconnect

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1308]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Change toon settings

*Please include detailed steps how we can reproduce the issue*
Change temp to 20.5 degrees

**What was the result?**
Nothing happened

**What did you expect as result?**
Change to temporary temp setting 20.5 degrees

**Any other remarks**
TOON is disconnected after Homey has rebooted.

**Comment by chrisboer** [comment]
See also my added comments in the "toon" github issue log, because the disconnect seems to be an issue with username and email address (request to receive new token)

**Comment by RobinBol** [comment]
Hi Chris, again thanks for reporting your issue. We know that the Toon app is causing users a lot of problems; therefore we released the app as a 'beta' (meaning, stuff might not be working). This is unfortunately largely out of our hands as the Toon API (provided by the makers of Toon themselves) used by this app is not quite stable. I am afraid this will remain so for a while, as this is an issue out of our control.
