### ISSUE TITLE
"Ok, homey" doesn't really work..

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#131]
Tried putting it on both English and Dutch. Is just doesn't register the trigger.
And I'm sitting here like a retard saying "Ok, homey" in all the possible ways I can imagine.

Sometimes it magically works, and then I say something from a created flow, but nothing. Can I see somewhere what Homey did hear?

**Comment by wslybkkr** [comment]
Hey Ruud,

This issue is already been addressed in https://github.com/athombv/homey/issues/31
Check it out :)

**Comment by matthijsvdr** [comment]
I had the same problem make a flow as follow:

![screen shot 2016-02-11 at 19 50 37](https://cloud.githubusercontent.com/assets/1271035/12990230/8afdaf6a-d109-11e5-89c0-180c93e06f1b.png)

Homey will then day Yup + what ever you said

I got it to work after pulling the power off, letting it start and stay ok homey right away a few times. If it triggers do the voice training, then it works better (at least for me)

**Comment by RuudBurger** [comment]
Ok thanks. #128 was it. Will follow that ticket
