### ISSUE TITLE
[1.1.4] Z-wave stuff for geeks stalls GUI upon loading

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1311]
**What is your Homey version (Settings → System)?**
Homey SW 1.1.4
Z-wave driver 1.1.4
Fibaro 1.1.19, Greenwave 1.0.10, Neo 1.1.13
Macbook Pro on latest release with homey desktop app 1.0.1

Z-wave network spider for reference:
<img width="362" alt="schermafbeelding 2017-02-05 om 08 32 04" src="https://cloud.githubusercontent.com/assets/17163431/22624503/bfbb28a6-eb7d-11e6-9d31-2049eb44d231.png">

**What did you try to achieve?**
Open Z-wave stuff for geeks to look at Z-wave logging from the Homey Desktop app.

**Homey Desktop app**
GUI freezes inside the Homey Desktop app, will not respond to any input. Unable to select other options.

Reloading the page (cmd-R) does not result in a change.
Closing the desktop app and restarting will provide a responsive GUI again.
Re-opening the Z-wave stuff for geeks will provide a responsive GUI for 5 seconds after which the GUI freezes again.
<img width="1139" alt="schermafbeelding 2017-02-05 om 08 08 39" src="https://cloud.githubusercontent.com/assets/17163431/22624454/01385bb0-eb7d-11e6-8bcf-d885bac33f57.png">

Sometimes it comes back and freezes again... or the GUI responds in a stutter mode
<img width="1133" alt="schermafbeelding 2017-02-05 om 08 10 11" src="https://cloud.githubusercontent.com/assets/17163431/22624457/0c51fc7c-eb7d-11e6-88ba-d3709933c8a9.png">

Log: 7AA53F6766

**Chrome**
Opening a window in Chrome and logging into the Homey's GUI via my.athom.com provides a responsive GUI (not logging into Z-wave stuff for geeks) again (while desktop app is non responsive).

Loading the Z-wave stuff for geeks section will soon result in a timeout warning 
<img width="352" alt="schermafbeelding 2017-02-05 om 08 24 56" src="https://cloud.githubusercontent.com/assets/17163431/22624477/158d90c6-eb7d-11e6-8e9c-c706e7b05f83.png">
With below console.log error code
<img width="340" alt="schermafbeelding 2017-02-05 om 08 25 09" src="https://cloud.githubusercontent.com/assets/17163431/22624479/1d972390-eb7d-11e6-98ec-c813ff54b47a.png">
After which I get the following errors in the console.log
<img width="341" alt="schermafbeelding 2017-02-05 om 08 30 33" src="https://cloud.githubusercontent.com/assets/17163431/22624494/7e2adf26-eb7d-11e6-84c5-2c1f0b50522e.png">
And following warning:
<img width="340" alt="schermafbeelding 2017-02-05 om 08 32 43" src="https://cloud.githubusercontent.com/assets/17163431/22624508/ce6c835e-eb7d-11e6-9757-69fe14082adf.png">

**Comment by WeeJeWel** [comment]
Fixed
