### ISSUE TITLE
Feature request: cron manager add between sunset and sunrise condition

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1314]
**What is your Homey version (Settings → System)?**  
1.1.4

**What did you try to achieve?**  
Want to run some flows only during daylight or when not in daylight. But there is no 'From dusk till dawn' condition available. Combining the sunrise and sunset conditions together doesn't work:
![image](https://cloud.githubusercontent.com/assets/15232724/22628764/616a9ae0-ebda-11e6-9386-b16b4e42c49b.png)

**What did you expect as result?**  
Simple condition card card available for (not) between sunset and sunrise

**Any other remarks**  
Nope.

**Comment by WeeJeWel** [comment]
Have you seen this card?

![screen shot 2017-03-15 at 16 19 06](https://cloud.githubusercontent.com/assets/319873/23955749/224483ba-099b-11e7-9e55-c5d2037cb90f.png)

**Comment by irritanterik** [comment]
@WeeJeWel What times does this card check? When I test it this evening around 21:00 the result is false. It seems it does not check for sunset / sunrise times:
![image](https://cloud.githubusercontent.com/assets/15232724/24373585/1a5f5e68-1332-11e7-9c9a-d476fcdff50c.png)

**Comment by WeeJeWel** [comment]
According to the library we use (suncalc):

```
night starts (dark enough for astronomical observations)
```
