### ISSUE TITLE
Adding new Zwave module (Qubino DC Roller Shutter) doesn't work

### ISSUE THREAD

**Issue by lvanderree** [athombv/homey#1317]
**What is your Homey version (Settings → System)?**

1.1.4

**What did you try to achieve?**

Adding a new Zwave module(Qubino DC Roller)  to my Homey network (containing already a dozen of Fibaro Dimmer (2) modules). 

*Please include detailed steps how we can reproduce the issue*

1.  I sideloaded the latest commit from git@github.com:clandmeter/com.qubino.git (which is a fork of git@github.com:athombv/com.qubino.git which I sideloaded in a 2nd try as well)

2. I included the Qubino module, after which the interview started, and 16 Command-Classes where exchanged.

3. After the interview Homey said to gather manufacturer data ("Informatie over producent wordt opgehaald..."). Which took a long time, so probably timed-out, after which a screen appeared (with "Het interview is verlopen. Geen apparaat gevonden.") 

I tried it with commit: aa15fa67030d5485299a7ed4b76411db9df1d036 and commit 8e2b45 and even without qubino app as proposed by kasteleman https://forum.athom.com/discussion/1803/qubino-z-wave-app#Comment_45803 but all with the same result

The tail of my zwave log contains:

```
[2017-02-06T18:33:39.114Z] Node[38]: Received application command for COMMAND_CLASS_VERSION, data: 0x142001
[2017-02-06T18:33:39.119Z] command status: addNode, status: INTERVIEW_CC_16_OF_16
[2017-02-06T18:33:39.471Z] command status: addNode, status: INTERVIEW_MANUFACTURER_SPECIFIC
[2017-02-06T18:33:39.472Z] Node[38]: sendData to COMMAND_CLASS_MANUFACTURER_SPECIFIC, params 0x0404
[2017-02-06T18:33:39.472Z] Command start: sendData
[2017-02-06T18:33:40.709Z] ProcessSendData[233]: To node: 38 with data: 0x720404 and txOptions: ACK,AUTO_ROUTE,EXPLORE
[2017-02-06T18:33:40.714Z] Command end: sendData
[2017-02-06T18:33:40.741Z] Node[38]: Received application command for COMMAND_CLASS_VERSION, data: 0x142603
[2017-02-06T18:33:41.770Z] Command end: sendData
[2017-02-06T18:34:09.474Z] Command end: addNode
[2017-02-06T18:34:22.494Z] Command start: addNodeAbort
[2017-02-06T18:34:22.501Z] Command end: addNodeAbort
```

**What was the result?**

The module wasn't included

**What did you expect as result?**

The device to be visible in my homey.

A log to be able to see what caused the problem would be nice.
The only thing I can think of right now is completely reset my homey (or at least the zwave network) to see if inclusion is possible then. But I like to prevent installing all my devices and flows again.

**Comment by clandmeter** [comment]
@IvoDerksen Can you try using the cleanup branch? you can find it here https://github.com/clandmeter/com.qubino/tree/cleanup this has the latest changes excluding the venetian function.

For sure the venetian blind branch will not work if you module doesn't have this enabled with the corresponding parameter because homey does not see the new multichannel node. I've already created an issue for this and hope it can be solved in a future release.

Also make sure you have the [zwavedriver ](https://github.com/athombv/node-homey-zwavedriver)included with the app and you have debug set to true (or if you have the latest zwave driver you can also create a file called debug in the root of the app see [here](https://github.com/athombv/node-homey-zwavedriver/pull/28)).

**Comment by clandmeter** [comment]
I think i'm confusing myself here as the initial implementation was like this and the driver would crash if the multi-channel node was not available. But i changed that afterwards to have multi-channel capability instead of a a new child device. I would still try that branch as it does not change any multi-channel settings. Did you try generating a zwavedriver debug log?

**Comment by lvanderree** [comment]
Thanks for your tips @clandmeter 

However I don't know if I understand everything correctly, so please tell me if I missed something or can try something more.

I checked out your "cleanup" branch, and patched the zwavedriver (which I had installed with npm install) to enable debugging, since I did not was entirely sure where to save the debug file. 
Since you look for: if (fs.existsSync('/drivers/' + driverId + '/debug')) ... However I don't think Homey is finding the manufacturer and so driver at all. 

This is what I get:

What I see in my browser console log is:
```
VM971:1 status WAIT
VM971:1 status ADD_NODE_STATUS_LEARN_READY
VM971:1 status ADD_NODE_STATUS_NODE_FOUND
VM971:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM971:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM971:1 status ADD_NODE_STATUS_DONE
VM971:1 status INTERVIEW_CC
VM971:1 status INTERVIEW_CC_1_OF_16
VM971:1 status INTERVIEW_CC_2_OF_16
VM971:1 status INTERVIEW_CC_3_OF_16
VM971:1 status INTERVIEW_CC_4_OF_16
VM971:1 status INTERVIEW_CC_5_OF_16
VM971:1 status INTERVIEW_CC_6_OF_16
VM971:1 status INTERVIEW_CC_7_OF_16
VM971:1 status INTERVIEW_CC_8_OF_16
VM971:1 status INTERVIEW_CC_9_OF_16
VM971:1 status INTERVIEW_CC_10_OF_16
VM971:1 status INTERVIEW_CC_11_OF_16
VM971:1 status INTERVIEW_CC_12_OF_16
VM971:1 status INTERVIEW_CC_13_OF_16
VM971:1 status INTERVIEW_CC_14_OF_16
VM971:1 status INTERVIEW_CC_15_OF_16
VM971:1 status INTERVIEW_CC_16_OF_16
VM971:1 status INTERVIEW_MANUFACTURER_SPECIFIC
``` 
During step VM971:1 status INTERVIEW_MANUFACTURER_SPECIFIC I see:

![schermafdruk van 2017-02-06 19-34-01](https://cloud.githubusercontent.com/assets/206672/22707814/4a056f6a-ed74-11e6-85d2-76b55f976868.png)

which takes a while, after which I guess a timeout occurs, on which Homey gives up finding the correct driver and shows:

![schermafdruk van 2017-02-06 19-34-18](https://cloud.githubusercontent.com/assets/206672/22707813/4a02505a-ed74-11e6-84f1-cfc7152def61.png)


My console log in which I run 
`athom project --run com.qubino` shows:

```
1/4 - Archiving...
2/4 - Uploading to Homey @ 192.168.0.35:80...
3/4 - Running `com.qubino`, press CTRL+C to abort...
4/4 - Debugging...

-------------------------------------------------
com.qubino running...
```

As said, I also tried adding the Qubino without the driver sideloaded. Today I tried it again as well, via the generic Homey add *zwave* device wizard.
So my guess is Homey isn't getting to the point where it would use the driver. What do you think.
Is there anything else I can do to get more logging? And get to understand why Homey doesn't get the manufacturer details.

**Comment by clandmeter** [comment]
Right the debug log will only start ones the device is included. If you cannot get it included without the driver installed I guess there must be something more deeper in the chain going wrong which @WeeJeWel or somebody else at athom need to check. Sorry about that.

**Comment by WeeJeWel** [comment]
Seems like the device doesn't follow the spec. @RobinBol do we have the same device, and if so, can we reproduce?

**Comment by RobinBol** [comment]
Yes we have Flush Shutter (ZMNHCD1) and Flush Shutter DC (ZMNHOD1). I tried pairing them both with Homey, I did saw a nif being send but the pairing process never started. Tried multiple resets.

**Comment by WeeJeWel** [comment]
OK Thanks. I'll investigate

**Comment by clandmeter** [comment]
Just to make clear, I have two ZMNHOD1 (DC shutter) devices which I was able to pair just fine.

![image](https://cloud.githubusercontent.com/assets/52970/22887986/732ddd5c-f204-11e6-9c3d-725610b34f24.png)

**Comment by lvanderree** [comment]
I can reproduce this, tried it several times, all with the same result. 
So if there is anything I can do please let me know. 

My guess is, that it might be something introduced in a more recent Homey firmware, since @clandmeter was able to pair his devices, but probably done in an older firmware. And I am able to pair Fibaro dimmers and relays without any problem.

**Comment by lvanderree** [comment]
I noticed there is a newer Homey Firmware (1.1.9) with Zwave updates and retried pairing the roller shutter, but unfortunately still with the same result.

**Comment by kasteleman** [comment]
I had a look at the manual:
In the manual is stated that for inclusion you have to use I1 button three times or put the controller into inclusion mode and then power-up the device. Press service button only applicable for 24 V SELV supply voltage.
Same goes for exclusion: service button only applicable for 24 V SELV supply voltage.
 
You tried to include it by pressing the Service button?

**Comment by lvanderree** [comment]
@kasteleman good point, I am currently using the service button, as shown in the dialog.
When I am back home I will try to include using the l1 button

**Comment by kasteleman** [comment]
@lvanderree maybe a reset is required. Use the I1 for that.

**Comment by lvanderree** [comment]
I tried as described by @kasteleman but unfortunately again with the same result.

I read the manual again as well, but my manual doesn't mention anything about the service button is only applicable for 24 V SELV supply. I read:

```
Module Inclusion (Adding to Z-wave network)
- Connect module to power supply (with temperature sensor connected - if purchased),
- auto-inclusion (works for about 5 seconds after connected to power supply) or
- press service button S for more than 2 second or
- press push button I1 three times within 3s (3 times change switch state within 3 seconds).

NOTE1: For auto-inclusion procedure, first set main controller into inclusion mode and then connect module to power supply.
```

I now tried (each time after resetting) 
- auto inclusion this doesn't even discover the command classes
- service button
- pressing 3 times in 5 seconds
- pressing 3 times in 5 seconds in first 60 seconds after powering up

**Comment by clandmeter** [comment]
@lvanderree which module firmware do you have? Mine is H1**S1**P1

It seems there is another user who now successfully included the module as discussed on slack.

**Comment by kasteleman** [comment]
@lvanderree Seems i mixed the Manuels.
http://www.domotica-shop.nl/files/images/Qubino_Flush-Shutter-PLUS-user-manual_V1_5.pdf
That's the zmnhcd1.
Sorry About that

**Comment by lvanderree** [comment]
Now it is getting weirder. I've got my shutter module fresh from the box, since almost 2 weeks, but the firmware is unreadable. It looks like someone at the factory wrote with pen over the H1S#P1

![img_20170216_205421](https://cloud.githubusercontent.com/assets/206672/23038772/799150be-f48b-11e6-9687-ac6b5c04cdfa.jpg)

Maybe someone has seen this before, or can resolve it from the serialnumber

**Comment by clandmeter** [comment]
For which version is your manual?

**Comment by lvanderree** [comment]
@clandmeter thanks! 
user manual V1.3 Valid for module with SW version S4 HxS4Px

So now the question is, is there something in my version that doesn't work with Homey yet, or should I try to reset my Homey to see if this resolves the issue. Resetting Homey isn't on my wishlist, since I then have to reset and include 17 dimmer modules

**Comment by clandmeter** [comment]
Dont reset your Homey, I dont think it will fix anything. The changes in the FW are probably causing your issues. @WeeJeWel is going to investigate it, so you will have to wait until they get answers from Qubino and implement a fix/workaround in homey firmware.

**Comment by SkorpionNL** [comment]
I successfully paired this module (firmware H1S1P1) with my Homey and am using 2 of these modules perfectly ever since. I copied all the ZMNHOD1 files from Clandmeter's branch into the master branch, which I sideloaded. (I did this because Clandmeter's branch itself crashed on my Homey with the Z-wave driver included). My findings are that for a successful pair, you have to include the ZMNHOD1 in very close range to Homey or otherwise it will fail most likely.

Running Homey firmware 1.1.9 / Qubino firmware 1.1.2

**Comment by clandmeter** [comment]
It is common for Z-wave devices to need to be close to the controller to be able to pair. The interview needs close proximity to be able to be successful as it need direct connection and communicates much more data then regular Z-wave traffic, but i agree that for these modules I also needed to put them really close as the first try failed.

I was thinking of creating a separate module which only has this dc shutter included so you can load it together with the upstream Qubino app, but im not sure what will happen ones the Qubino app will include the shutter, it could mean it needs a re-pair (not sure about this though, didn't investigate yet).

**Comment by clandmeter** [comment]
@SkorpionNL and anybody who is listening. I moved the driver into its own app. So now you should be able to use them side by side. I didn't have time yet to test it because it needs a re-include of the module(s). If somebody can confirm is working ok I can submit it to the app store until Athom can sort things out with Qubino.

https://github.com/clandmeter/com.qubino.shutter

**Comment by lvanderree** [comment]
I tried the app yesterday with the s4 firmware, but unfortunately I still couldn't include the module (the app doesn't help in that of course), so besides side loading I couldn't test the app any further.

**Comment by WeeJeWel** [comment]
I can reproduce the behavior, but it seems to be Z-Wave-protocol related, not something we have control over. I have contacted Sigma Designs (the Z-Wave manufacturers) if they have a clue.

**Comment by lvanderree** [comment]
Thanks for the update, lets see what they can tell.

--

Met vriendelijke groet
Leon van der Ree

Mobiel:   +31 6 489 77 623

**Comment by WeeJeWel** [comment]
Update: I've found that the Qubino device doesn't behave right - I've contacted Qubino to ask for clarification.

**Comment by WeeJeWel** [comment]
Well, I've got a response...

```
Hi Emile,
 
Current modules are available for sale, but not all are certified yet. And we are currently during certification process, some modules are already certified but not all of them.
Shutters are right now during this process and should be completed sooner or later.
```

You might want to return this faulty product and choose another manufacturer.

**Comment by lvanderree** [comment]
Thanks, 
I will do so!

**Comment by clandmeter** [comment]
AFAIK, there are (currently) no other manufactures that have DC shutters. 

P.S. pretty weird the older firmware works and the newer doesn't

**Comment by lvanderree** [comment]
I've got a response from Qubino as well:

> Qubino modules are currently not fully integrated in homey gateway. But we are cooperating with them to fully integrate the modules.
Currently we are in the integration process of the shutters, but I cannot assure you when it will be finished.
>
> Meanwhile for flush shutter DC I cannot assure you when they will be ready for certification and implementation. But If it’s okay with you, I can contact you soon as we finish.
And then I will ask you to return to distributer for firmware update. And you will get the newest version of the flush shutter DC.
But this will be when we finish witch certification of flush shutter DC.

**Comment by lvanderree** [comment]
Goodnews everyone!
Looks like the Homey (1.3) updates fixed the pairing issues with my ZMNHOD1 (H1S4P1).
It first was added as a generic zwave device, so I removed it, sideloaded the project github.com:clandmeter/com.qubino.shutter.git and again successfully added it after which it got recognized!

Unfortunately moving my shutters up/down with the app isn't working yet, it makes the shutter-app on homey unresponsive, but my guess is that that is due to some mismatch between the sideloaded app and the firmware of my roller shutter. When I have more time I will look into that.

**Comment by Merlinuf** [comment]
Any update om this?

**Comment by Merlinuf** [comment]
Well same problem here, up/down crashes the app

**Comment by Merlinuf** [comment]
@clandmeter

**Comment by clandmeter** [comment]
I currently don't have the devices to test so it's up to athombv to add and test it.

**Comment by Merlinuf** [comment]
I have the s5 version

**Comment by clandmeter** [comment]
right, I dont have them. And my current modules work fine so i dont want to risk breaking my setup by testing other modules.

Somebody with a dev homey with the modules should try it (probably athombv, you or somebody else)

**Comment by Merlinuf** [comment]
Well i tested the one thats out and it crashes as soon as i press up or down


Med vänlig hälsning,

Kristoffer Persson
