### ISSUE TITLE
Hue app: Unavailable bulbs report as available

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1319]
**What is your Homey version (Settings → System)?**  
1.1.4, app v 2.2.2

**What did you try to achieve?**  
I have some Hue lights behind a fysical switch. If this switch is turned off the hue bulbs are not available. Before hue v 2.2.2 the device card went to gray-ed out state. Now the lights stay available.
Also in the logger I can see them reported available:
![image](https://cloud.githubusercontent.com/assets/15232724/22681669/bd838c12-ed0e-11e6-90e2-aca09ffb823f.png)

**Comment by Rocodamelshe** [comment]
Same here but with Hue app version 2.2.1

**Comment by WeeJeWel** [comment]
This won't be fixed because (for now) the bridge reports these states incorrectly. In the past we experienced that unavailable lights could in fact be controlled, regardless of what state the bridge thought they were in.

**Comment by irritanterik** [comment]
@WeeJeWel Is something changed in 2.2.3?
My bulbs are now reported as unavailable, while the're online and switchable with the native hue app.

![image](https://cloud.githubusercontent.com/assets/15232724/22964175/8e337216-f357-11e6-8db0-ddf9d6f874c5.png)

The unavailable report above only occurs on app init. But after that the bulbs stay unavailable forever:
![image](https://cloud.githubusercontent.com/assets/15232724/22964215/b91b31ee-f357-11e6-83c9-ad22b3ee4870.png)

**Comment by spoelly** [comment]
Got this problem also on my second hue hub.. 1st gen
But had it before 2.2.3 also

**Comment by irritanterik** [comment]
gen 1 hub here also

**Comment by irritanterik** [comment]
For me the problem was solved after 
 add hue bulb
 press pair button on hub

Seems like the api token on the hub or on homey got lost or out of sync
