### ISSUE TITLE
Aeotec Siren Gen 5 not selectable in flow

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1320]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Add Sirene to flow
<img width="960" alt="sirenegen5" src="https://cloud.githubusercontent.com/assets/23163409/22700664/b31d5670-ed5b-11e6-824c-aed892619ded.png">

*Please include detailed steps how we can reproduce the issue*
Installed the device and visable in screen can also select different sirene sounds via homey so there is a connection.
When I create a flow and want to add the device Sirene I don't see this device in the list.
<img width="1430" alt="sirene_notvisible" src="https://cloud.githubusercontent.com/assets/23163409/22700660/b1045564-ed5b-11e6-8435-0bf93f444725.png">

**What was the result?**
Device not visible

**What did you expect as result?**
Device selectable in flow

**Any other remarks**

...

**Comment by RobinBol** [comment]
Added flow and mobile functionality for the Siren Gen5 in the latest Aeotec app release.

**Comment by chrisboer** [comment]
Thanks Robin much appreciated
