### ISSUE TITLE
Voice activation not working (1.1.9)

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey#1321]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

Tried to trigger a flow by voice direct from Homey

*Please include detailed steps how we can reproduce the issue*

I Say : OK homey, --> orange spinning --> Talk... --> back to normal spinning color.
When using Telephone, voice works..

**What was the result?**

Homey playing Mute.. / Deaf.. after OK homey

**What did you expect as result?**

Homey activating my flow...

**Any other remarks**

...

**Comment by mruiter** [comment]
Confirmed I have the same

**Comment by mruiter** [comment]
But I do get the normal white spinning after the talk but then nothing

**Comment by satbopper** [comment]
confirmed i am on 1.1.4 and yesterday it happened again (1.1.2 also) by saying ok homey no spinning nothing,ptp and it is working again

**Comment by mruiter** [comment]
Ptp doesn't help on 1.1.9. Its none responsive to everything no build in what's the time and no flow or other apps with voice activation

**Comment by mruiter** [comment]
Confirmed working again after rollback on the patch athom did on the speech server.

All is good, now release that 1.2 sucker
