### ISSUE TITLE
speech-output callback method is instantly triggered when using iPhone app for communication

### ISSUE THREAD

**Issue by alphabase** [athombv/homey#1322]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

I ran into this issue when building the NU.nl news headlines app:
https://apps.athom.com/app/nl.nu.headlines

I need Homey to pause for one second between reading the headlines of two news items.
Therefore, I use the setTimeout()-function to pause before running into the next news item to be read:
https://github.com/alphabase/nl.nu.headlines/blob/master/app.js#L130

The code that makes Homey pause and run into the next news item is ran when the callback function of speech.say() is called.
Given the documentation on the speech-output API, the callback function is "Fired when Homey is done speaking".

**What was the result?**

When running the app triggered from the internal microphone and speaker of Homey, the speech output engine nicely pauses for a second between reading two news items.
However, when triggering the app from the iPhone app, it seems as if the callback function is ran immediately after the speech-ouput was triggered.
This results in Homey reading the next news item every second, instead of waiting for the reading to finish, pause for a second, and then continue.

Thus, when reading three items:
Homey speaker: [start reading]-[end reading]-[one second]-[start reading]-[end reading]-[one second]-[start reading]-[end reading]
iPhone speaker: [start reading]-[one second]-[start reading]-[one second]-[start reading]-[end reading]

**What did you expect as result?**

I expected the iPhone app to also wait for the speech to finish, wait for a second and then continue with the next news item.

**Comment by bvdbos** [comment]
see #613 for reference...
