### ISSUE TITLE
Feature request: Add HUE groups as devices

### ISSUE THREAD

**Issue by Spaapen** [athombv/homey#1324]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

The option to add HUE groups as devices.
Now we have to switch on all individual bulbs or use flows and/or bitflip devices which give some issues detecting the current state.

**What did you expect as result?**

There are no HUE group devices available, only individual bulbs

**Any other remarks**

None

**Comment by spoelly** [comment]
Would be nice if homey has a function to make groups of devices.. then Hue and other brands can be used together in groups/scenes

**Comment by bvdbos** [comment]
If this wasn't fixed yet could you file this enhancement on https://github.com/athombv/nl.philips.hue/issues and close this bug?

**Comment by Spaapen** [comment]
We are stil not able to import the grouped devices from the Hue bridge, so no it isn't fixed yet.

**Comment by WeeJeWel** [comment]
We have no plans of supporting 'virtual devices' for now.

If we were to implement it, grouping devices within Homey would be our solution.
