### ISSUE TITLE
After not giving confirmation answer, Homey fires the flow on the next action.

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#1325]
**What is your Homey version (Settings → System)?**

1.1.9 but was also on 1.1.4

**What did you try to achieve?**

Have a flow that asks at night if there is any1 awake:

![vraag-antwoord](https://cloud.githubusercontent.com/assets/19249884/22935475/fda0915e-f2d2-11e6-82e7-461a76ab30d5.png)

*Please include detailed steps how we can reproduce the issue*

Make the flow like above and say nothing when Homey ask u. Just say nothing.

**What was the result?**

Flow is not triggered but instead it is triggering on the next thing u ask Homey. If u ask Homey something 3 minutes later or 7 hours later, he will fire the above flow.

**What did you expect as result?**

That Homey would fire the flow when nothing was said like she did in 1.1.2 and fires directly.
Not 7 hours later.

**Any other remarks**

...

**Comment by camilleversteeg** [comment]
I'm experiencing the same issue (i think): 
https://forum.athom.com/discussion/comment/47842

**Comment by WeeJeWel** [comment]
So if you say, for example, 'OK Homey, what time is it?', then the actions of this flow run ('OK, dan doe ik..')?

**Comment by Rocodamelshe** [comment]
Correct!

**Comment by 2benl** [comment]
I guess this is not to strange. Looking at this flow Homey would trigger on an answer that is not "ja".
If no one is home to give an answer to Homey's question he will wait till you talk to him when you come home. When you say something when you come home, Homey compares if the answer is not "ja". If it isn't he will trigger the flow.

If you want to turn out the lights if no one is home I guess you should use the Geofence and set the "and no-one is home" condition.

Maybe an extra card should be introduced for the and condition witch is something like: When Homey gets no response.

**Comment by Rocodamelshe** [comment]
This card was introduced for this specific user case and used to work in 1.1.4 so that's why I made this issue. And geofence is not an option because we are home and in bed so it's just for putting the lights off when someone forgot to do so.

**Comment by 2benl** [comment]
Ok, the use case is logical indeed. The function might not be completely clear with the description the card has now. So a card with a "Received no answer" condition would make more sense to me.

**Comment by Rocodamelshe** [comment]
True that!

**Comment by WeeJeWel** [comment]
Hm no, the time should timeout after 30 seconds. Please try again in 1.2.0-rc.7 (released today to Developer Preview) and report back!

**Comment by Rocodamelshe** [comment]
Mesa not in dev preview.

**Comment by Rocodamelshe** [comment]
Looks solved in 1.2.0
