### ISSUE TITLE
Dimmer icon not working correctly (need to click it twice to switch the light off)

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#1326]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Switch off the light (dimmer)

**Please include detailed steps how we can reproduce the issue**
When you change the dim value with the slider the light goes on but the color of the slider stays gray. ("off" status but the light is on)
![image](https://cloud.githubusercontent.com/assets/17165733/22942898/b2223106-f2eb-11e6-9932-26db865cc612.png)

So for switching the light off I first have to click on the dimmer icon to make it solid black ("on" status and the light stays on)
![image](https://cloud.githubusercontent.com/assets/17165733/22942910/bf920528-f2eb-11e6-9117-657f865526b9.png)

And than click the icon again to turn the light off and the color of the icon and sliders changes back to gray again.

**What was the result?**
Need to click the dimmer icon twice to switch the light off when you have used the slider to change the dimmer value (which also turns the light on).

**What did you expect as result?**

- That when using the slider to change the dimmer value r and the light switches on that the dimmer icon goes into the "on" status (solid black color)
- Or when changing the dimmer value using the slider the light stays off until you click on the dimmer icon.

**Any other remarks**
I have tested this with the Duwi built-in dimmer - 05433 and the Z-Wave.Me app

**Comment by SkorpionNL** [comment]
I'm also experiencing this bug with the Qubino 0-10v flush dimmer. So this is probably related to dimming!?

https://github.com/athombv/com.qubino/issues/15

**Comment by aljoen** [comment]
Same is true for my Fibaro dimmers (since last update 1.2.2 (fibaro) and 1.1.9 (Homey). Manual using the sliders or operated by a flow to turn lights on does not result in update status. of dimmers within homey. Hence lights are on but homey sees them stiil as off . However vice versa (turning off by using a flow) works as it should and also using the actual switch on wall results in proper updating behavior, strange

**Comment by JesperJanssen** [comment]
Is there sime progress for this issue or is this something which can be fixed in the z-wave setings of the dimmer in Homey?

**Comment by jeroenvollenbrock** [comment]
These are app-specific bugs. Please report them to the respective app developers. 
Developer info: if you disable the setOnDim capability option and your device turns on when setting a dim value, the app wil have to emit a realtime event upon receiving a set dim.
