### ISSUE TITLE
2 issues in one, speech recognition not working also better voice not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1328]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Create a flow which triggers "Led vuur" flow

*Please include detailed steps how we can reproduce the issue*
Create a flow with something is being said, then say "Led vuur" homey translate this in input speech to Let Her. 
So I added "Let her"  and replaced it with "Led vuur" but still the input gave Let her.

**What was the result?**
Flow not speech activated (I did bypass this by just adapting the "Led vuur"  in "Let her" and now it works.

**What did you expect as result?**
Homey to come up with "Led vuur"  instead of "Let her"  
Better voice replace "Let her" in "Led vuur"

**Any other remarks**
Minor defect but anyway

**Comment by bvdbos** [comment]
What language is Homey on? If speech gets translated to "Led her" it looks like English? Also, what happens if you type it in : https://[homeyip]/manager/speech-input ?

**Comment by chrisboer** [comment]
It is dutch and it is translated to "Let her" not "Led her"  but anyway I used speech-input to checked what has been said.

**Comment by irritanterik** [comment]
You must report Better Voice issues on the apps repo for it is not an Athom app (https://github.com/jeroenbos22/homey.better.voice/issues)

**Comment by jeroenvollenbrock** [comment]
Please use the beter voice issue tracker for better voice issues.

**Comment by chrisboer** [comment]
Sorry Jeroen but you are a little bit to fast here in closing a homey issue !
speech recognition is not working and it also does not work with better voice.

**Comment by Dijker** [comment]
is your -not Better Voice related- problem described in #920 ? That one is still on their list!
