### ISSUE TITLE
Flow speech testing not possible anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1329]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Try to test an existing flow by filling in "Led storm" but can not fill test speech variable anymore so cannot test speech flows

*Please include detailed steps how we can reproduce the issue*
See above

**What was the result?**
Option was available in previous version of Homey.

**What did you expect as result?**
Be able to fill in a variable test field to test speech flow

**Any other remarks**
It seems to be possible when you create a new flow, so why not possible when you change a flow later.
...

**Comment by chrisboer** [comment]
I don't know what happened before but it works again

**Comment by chrisboer** [comment]
It is sometimes not working and sometimes is working so should be fixed

**Comment by irritanterik** [comment]
In my case the token input fields above the test button are not always shown. Especially when clicking between flows. After a page refresh the input fields are always shown.

**Comment by WeeJeWel** [comment]
Can you post a screenshot when this occurs?

**Comment by chrisboer** [comment]
I can but currently I don't get it anymore so like irritanterik says "not always shown" so when I see it I will take a screenshot

**Comment by chrisboer** [comment]
Not exactly a flow with speech but this also shows that I cannot put in a parameter in above the test button

<img width="1430" alt="testflow" src="https://cloud.githubusercontent.com/assets/23163409/24105605/b198c434-0d85-11e7-83d3-568960118f08.png">

**Comment by chrisboer** [comment]
Eeuh got it now for speech aswell 

<img width="1430" alt="testspraaklijn ontbreekt" src="https://cloud.githubusercontent.com/assets/23163409/24105745/246503d8-0d86-11e7-888a-85082d61e9a2.png">

**Comment by chrisboer** [comment]
And after restart of desktop app 

<img width="1430" alt="testspraaklijnaanwezig" src="https://cloud.githubusercontent.com/assets/23163409/24105839/6f80e7e2-0d86-11e7-85e5-b34f4313a0d3.png">

**Comment by chrisboer** [comment]
Not yet got this issue in v1.2 RC8 will keep you posted

**Comment by chrisboer** [comment]
Still happens in v1.2.0 rc8 so nothing changed still an issue

**Comment by chrisboer** [comment]
Still happens in v1.2.0 rc9 and new desktop app 1.0.3 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24292688/ad9cce32-108e-11e7-86d7-f3d285cb7576.png)

**Comment by WeeJeWel** [comment]
Fixed in v1.3.0. If it occurs again, please report back then

**Comment by chrisboer** [comment]
Ok thanks

**Comment by jaxc0402** [comment]
I can confirm rc10 also has this behavior..

**Comment by chrisboer** [comment]
Indeed I have the same again

**Comment by WeeJeWel** [comment]
As a workaround until Homey v1.3.0 is released, it might help to drag-n-drop the trigger card again.

**Comment by chrisboer** [comment]
Seems to work again now with v1.3.0 will close it for now

**Comment by rogierhofboer** [comment]
Please reopen. I have this in 1.5.3 with Desktop app 1.0.4
Going to another tab and back solves it, but sometimes it does not work directly.
![image](https://user-images.githubusercontent.com/6314129/34058382-2340cb8e-e1db-11e7-9d46-c022a8cff565.png)
