### ISSUE TITLE
Homey says stuff in Dunglish

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#133]
So a Dutch voice with English text.
"Turning lights off" becomes "Tuuwrning ligts of"
And the recovery is funny: "Starting rekofferie" "Rekofferie kanselet" (Recovery Canceled)

**Comment by WeeJeWel** [comment]
Dutch is not yet fully supported :)

**Comment by nattlip** [comment]
+++ I thought the dutch schools learned the young-ones nowadays to pronounce English as an Englishmen or American, but you can indeed hear that it is a Dutchman speaking english, it is not as worse as van Gaal though, but some training is still requierd. Nice term Dunglish. 

http://stuffdutchpeoplelike.com/2015/04/08/dunglish-27-funny-examples-that-will-make-you-laugh-out-loud/
