### ISSUE TITLE
Z-wave map: differentiate color of nodes with respect to routing capabilities

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1331]
**What is your Homey version (Settings → System)?**
1.1.9

**Improvement proposal**
I see a lot of questions popping up regarding the z-wave map. 

Is it possible to differentiate in node color on wether a node has routing capabilities (able to support the mesh) or not (e.g. battery powered devices without routing capability)? 

And off coarse make Homey stand out more as controller.

**Comment by WeeJeWel** [comment]
Fixed on https://developer.athom.com
