### ISSUE TITLE
Homey desktop delay in editing and drag and drop devices 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1332]
**What is your Homey version (Settings → System)?**
1.1.9
Windows 10

**What did you try to achieve?**
Edit device name and drag and drop devices in other zone

*Please include detailed steps how we can reproduce the issue*
When editing device name there seems to be a kind of delay when you type or make a change, also it suddenly jumps out of editing mode after 2 seconds or so.
Same with drag and drop a device to another zone it disappears reappears and disappears again.

**What was the result?**
It works eventually but it is not normal behavior

**What did you expect as result?**
Normal editing mode and responsive, same with drag and drop 

**Any other remarks**
Label Homey Desktop

**Comment by WeeJeWel** [comment]
I've seen this happen when Google Chrome is open as well and uses a lot of memory. Please try closing all other processes, restart Homey Desktop and report if the results are the same.

**Comment by chrisboer** [comment]
I had it this morning but I did not have Google Chrome open only firefox but restart desktop app this speed it up again.
