### ISSUE TITLE
[DEVELOPER] Device setting pattern docs is wrong

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1334]
**What is your Homey version (Settings → System)?**  
1.1.9

**What did you try to achieve?**
Validate settings with pattern. I expect this pattern value to validate values `a1`, `A2` and `B20` as valid:
`"pattern":"/[a-zA-Z][0-9]{1,2}/g"`
All values are invalid              

*Please include detailed steps how we can reproduce the issue*
Add pattern option to text type devicesetting in app.json.

**Comment by caseda** [comment]
add a ^ infront:
`/^[a-zA-Z][0-9]{1,2}/g`

**Comment by irritanterik** [comment]
Thanks @caseda 
So its a documentation issue:
![image](https://cloud.githubusercontent.com/assets/15232724/23340935/3c35e9e4-fc3f-11e6-8c74-260d1937309c.png)

**Comment by WeeJeWel** [comment]
Thanks, fixed!
