### ISSUE TITLE
[1.1.9] Z-wave logging not restricted to 500 entries

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1335]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
Debug Z-wave issues by looking into Z-wave logging

**What was the result?**
Although Z-wave logging should be restricted to the last 500 entries, in 1 hour time I already see 6898 line items... 

LOG: A89A43D23B
[Homey_Z-log.txt](https://github.com/athombv/homey/files/787679/Homey_Z-log.txt)

**What did you expect as result?**
Only 500 entries

**Any other remarks**
Issue might be that upon page loading the last 500 entries are loaded and appended by new entries... older entries (exceeding the 500 line items) are not removed.

**Comment by WeeJeWel** [comment]
After a refresh, how many lines do you see? It is intended behavior to not remove lines on the front-end.

**Comment by TedTolboom** [comment]
If it is intended behavior, I will close the issue.
