### ISSUE TITLE
Strange speech recognition when counting

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1336]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?
I want Homey to recognise numbers in spoken text.

*Please include detailed steps how we can reproduce the issue*
- Open homey-ip/manager/speech-input/
- Say; "OK Homey.... Een... twee... drie... vier"

**What was the result?**

Speech-input shows: "een 2twee 32twee drie 42twee 32twee drie vier"

**What did you expect as result?**

Speech-input should show "1 2 3 4"
...

**Any other remarks**

...

**Comment by Amelsfort** [comment]
The same thing happens when using a single number in a sentence. I tried to set an alarm for over 8 minutes and this is what Homey received:
Homey: zet een alarm over 8een alarm over acht minuten

I guess the speech processing api returns multiple results using a number in one, and the number written out in a second one and Homey isn't processing this correctly.

**Comment by OpenMindNL** [comment]
Confirmed @Amelsfort 

And when I say; "Ik wil twee emmertjes water halen", Speech-input shows exactly the same where I was expecting "Ik wil 2 emmertjes water halen"

**Comment by OpenMindNL** [comment]
Another strange one:

I say: "Fietsenrek drieentwintig"
Homey: "fietsenrek 3senrek drieentwintig"

And  yes... I say strange things to Homey while testing my software... 😁

**Comment by OpenMindNL** [comment]
I see that the bug is picked up by the devteam... great!

Nevertheless... Here's another one in case it might help tracking the bug.

I say: "Ik zie 23 varanen met 6 achterpoten"
speech-input: "Ik zie 23 met 6 8ie 23 verhalen met 6 achterpoten" 

In this case "verhalen" will be a misunderstanding, but the kind of strange number recognition seems to happen most of the times when 2 numbers are present in the same sentence.

**Comment by Tweake** [comment]
Thanks for reporting the issue! I have made an update to the number detection code. For spoken commands you should notice a difference right away, without the need for an update. The changes will not yet have taken effect if you type the phrase in http://<ip>/manager/speech-input until Homey version 1.2.0.
Please let me know if the issue has been solved so it can be closed.

**Comment by OpenMindNL** [comment]
Ok... 1 minute ago I tried "counting in Dutch: "1... 2... 3... 4..."
Result in /manager/speech-input/: "een 2twee 32twee drie 42twee 32twee drie vier"

**Comment by OpenMindNL** [comment]
I say: "Ik zie 23 varanen met 6 achterpoten"
manager/speech-input: "Ik zie 23 verhalen met 6zie 23 verhalen met zes achterpoten"

**Comment by OpenMindNL** [comment]
I notice a difference when...
I say "fietsenrek drieentwintig"
/manager/speech-input shows; "fietsenrek 23".

I noticed this same difference last night at about 3:00 AM... but a while later is showed "fietsenrek drieentwintig" again...

**Comment by OpenMindNL** [comment]
Just a brainwave... because I don't know how speech-recognition exactly works on server-side.

But... could it be that Homey is mixing up results from different sources sometimes?

I'm asking this because of the different results we got/get from speech-input for "fietsenrek 23"
- It's sometimes "fietsenrek 23" (like we want it... I think)
- Sometimes we get "fietsenrek drieentwintig"
- And then there is "fietsenrek 3senrek drieentwintig"

Looking at these results, gave me my brainwave...
Maybe it's 23 or drieentwintig when there's a substantial amount of time between receiving from one or the other source... and maybe they get mixed up when 2 are received within a certain small time-frame? ... Maybe... ?

**Comment by Tweake** [comment]
I also experienced issues with number conversion again today. I have made additional changes server-side which will finally resolve these issues permanently.

**Comment by OpenMindNL** [comment]
Thanks. In case you might be interested why I am so obsessed by numbers at the moment...

https://github.com/OpenMindNL/numcatch ... it's pending for release at this moment

**Comment by OpenMindNL** [comment]
At this moment it looks very positive!!

Me: "Ik zie 23 varanen met 6 achterpoten."
Homey: "23 varanen met 6 achterpoten"

Me: "1... 2... 3... 4..."
Homey: "1 2 3 4"

**Comment by Tweake** [comment]
Interesting! You will actually be able to greatly simplify your code as of version 1.2.0, since speech "triggers" can then include regexs, so you could just do a regex /\d+/. The documentation will be online soon, feel free to shoot me a message on slack if you would like to know more

**Comment by OpenMindNL** [comment]
Hi @Tweake ,
I just discovered one small bug in the speech-recognition concerning numbers.
I say: "Ik zie 1 boer"... speech-input: "Ik zie een boer".
It seems like Homey doesn't hear a difference between "één" and "een".

For now all the other number-troubles seem to be solved... no more text-numbers (except for 1...) and no more text-number chaos in one line. Nice!

**Comment by Tweake** [comment]
That's right, I don't have the possibility to distinguish between the difference in the way it is pronounced. I have set it up in a way where it will appear as "een" when it's most likely a particle (lidwoord) and as "1" when it is an ordinal (telwoord)

**Comment by OpenMindNL** [comment]
I noticed the difference between particle and ordinal application. Nice work!
I understand that Athom is dependent on external service providers when it comes to voice-recognition. Maybe you can put a request at the providers? At the end the difference in pronunciation is at least as big as it is with 'ei' en 'ui'. However... it wont be a dissaster when it is not possible... Not many people will ask Homey to switch on "één licht" or close "één deur" ;-)
