### ISSUE TITLE
[FEATURE REQUEST] trigger when Homey stops talking

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#1338]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

I ask Homey to read the news. I got flows that if Homey listen or speak the tv will be muted. After reading the tv will stay muted because I can't make a flow to switch to un-mute tv.

**What was the result?**

Tv sound stays muted

**What did you expect as result?**

After Homey is ready speaking it would be great that sound can be un-muted

**Any other remarks**

An end of speak trigger would be welcome

**Comment by Rocodamelshe** [comment]
Sounds like [1194](https://github.com/athombv/homey/issues/1194)

**Comment by WeeJeWel** [comment]
Duplicate of #1194
