### ISSUE TITLE
[1.1.9] Z-wave topology map update triggered each time you open Z-wave stuf for geeks

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1339]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Troubleshooting / debugging Z-wave drivers, switching back and to the Z-wave stuf for geeks section within settings

**What was the result?**
Each time you enter this section, a network topology update is triggered. 
During debugging, this can happen a lot and cannot be avoided. 
Other then leaving this section open and opening in another tab the devices overview

**What did you expect as result?**
I would recommend to request for a Z-wave topology update 1x per day (during the night) and have a button to manually trigger the network topology instead of triggering it on each page load.

**Comment by WeeJeWel** [comment]
Why, does it take so long? It has always been pretty fast here.

**Comment by TedTolboom** [comment]
Question (or misinterpretation) is wether Homey actively requests a network update from it's connected devices or only builds the graph based on available information.

**Comment by WeeJeWel** [comment]
It's a relative cheap call and prevents users from seeing an outdated graph. I'll therefore assign a wontfix label and close the issue.

**Comment by mruiter** [comment]
did you test it with 65 zwave devices and looked if its still fast 😂
