### ISSUE TITLE
The dog is not happy (Add the possibility to mute the voice during periods)

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#134]
when in the middle of the night Homey sais "Oops I'm sorry I could not reach the server. Try again later"
We woke up last night around 3 am when the dog barked because of a unfamiliar voice in the house.
It would be nice if I could mute the voice certain hours a day. system setting?

**Comment by WeeJeWel** [comment]
Fixed that error already. Volume settings is available in 0.8.18

**Comment by JohanKuster** [comment]
I know but how do I shut it off during certain periods?

**Comment by WeeJeWel** [comment]
From within the flow editor in 0.8.18!

**Comment by JohanKuster** [comment]
ok thanks! Bring it on!
