### ISSUE TITLE
Homey app crashed after trying to set location by ur self

### ISSUE THREAD

**Issue by hunter707** [athombv/homey#1340]
**What is your Homey version (Settings → System)?**

1.1.9.

**What did you try to achieve?**
Homey app crashed

*Please include detailed steps how we can reproduce the issue*
It happens when you go to settings, location and click on set location by your self.

**What was the result?**

App crashed and is gone.

**What did you expect as result?**

To set the location by my self...

**Any other remarks**

nope
![schermafbeelding 2017-02-22 om 12 42 30](https://cloud.githubusercontent.com/assets/25126272/23210586/941d3016-f8fe-11e6-8a73-256e673051f2.png)
...

**Comment by TheMSB** [comment]
@hunter707 I cannot seem to reproduce your issue, could you specify for me the following:

- What OS version are you running
- What Homey desktop app version you are running
- Additional information that you think might help me reproduce your problem.

If anyone else is experiencing this issue it would be helpful if they could be so kind as to share their experiences.

**Comment by hunter707** [comment]
Martijn, 

At the moment I click the “Laat zelf mijn lokatie kiezen” the Homey app crashed.
And I get the message “Homey is onverwacht gestopt”.
I use Homey app version 1.0.2. and OS version 10.11.6 see down under the pictures.

Kind regards,

Loek Xhofleer

**Comment by TheMSB** [comment]
After some digging I came to the conclusion that this is a bug in electron. I have made an issue there and will keep this thread updated about a potential fix.

**Comment by hunter707** [comment]
Martijn,

Thanks, glad you've also found the prlobleem and you keep me informed. Hopefully the problem will be solved quickly.

Kind regards,
Loek Xhofleer

**Comment by Heki2017** [comment]
I have exactly the same issue. Bought last week my new homey and found this issue. I use a macbook air with OSX El Captain 10.11.6. The version of the Homey app I use is 1.0.2. I would like to add that I wanted to set my location myself as I hoped the map would become more clear. Standard the map is quite blurred and it is not clear if my position is the right one.

**Comment by bvdbos** [comment]
This shouldn't happen anymore. Though possibly there's #1732 playing up now but I think this one can be closed?

**Comment by Heki2017** [comment]
Thanks Bas, can't check now as I am on holiday. Will check when back next week

Kind regards, Hedzer

Sent by iPhone, please ignore possible typos
