### ISSUE TITLE
Tool Tip for Tag

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1343]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

When I building Flow, I would see with tag I've used. 
![image](https://cloud.githubusercontent.com/assets/8507396/23317497/f38c54a6-face-11e6-8f6a-47c5da423833.png)
This Tag is named: "aangezet".
I've many many äangezet" Tags:
![image](https://cloud.githubusercontent.com/assets/8507396/23317656/9c4cc012-facf-11e6-9738-c27ad43368f2.png)

**What was the result?**

When I want to change a flow, I can't remember with Tag is used. So I have to reengineer the Flow.

**What did you expect as result?**

When tipping with the mouse pointer on the Tag, give the tooltip include the device name.

**Any other remarks**

Tags are very cool and simply. I've rebuilt the most of the Flow. Its a lot easier! Thanks for upgrade!

**Comment by Dijker** [comment]
Same as #1274

**Comment by WesRos** [comment]
Thanks for your attention, I forget to search for a issue before I created one.
