### ISSUE TITLE
Cant drop a tag in logica card

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1344]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

When I'm building a flow and use the logica card: "Exactly" in the "And" column, it isn't possible to drop a tag in the "little label" box.
![image](https://cloud.githubusercontent.com/assets/8507396/23318082/49f22616-fad1-11e6-9047-35af3721cf0a.png)

**What was the result?**

I have use another card.

**What did you expect as result?**

That it's possible to drop a Tag in the box of this card.

**Comment by Dijker** [comment]
Do you use Windows 10 with a Hig res screen scaled to anything other than 100% ? 
pls look at #1090 
Try an other screen resolution / scaling as workaround while Athom fixes it. 
Using the App fullscreen or the Chrome browser works for most users....

**Comment by WesRos** [comment]
Whahah, I tried a boolean Tag. That's not working.
