### ISSUE TITLE
On command is send on "set dim level" flowcard, when value is out_of_range

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1345]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Was checking the range workings of the action flowcard "Set Brightness"

**Please include detailed steps how we can reproduce the issue**
Use flow card with a device that still wants the on command when dimming (for example a Hue Bulb).
Push a number tag into the range slider and enter a test value that is out_of_range.

**What was the result?**
The flow card is stopped nicely (see remarks for image with the error), but the light still turns on, since the "on command" is still send

**What did you expect as result?**
If the value is out_of_range (stopping the flow card) that the "on command" also isn't send

**Any other remarks**
![out_of_range](https://cloud.githubusercontent.com/assets/2565450/23324123/46c8e3ec-faec-11e6-8c79-0d24b8c8b1c2.jpg)

**Comment by WeeJeWel** [comment]
Fixed in 1.2.0

**Comment by caseda** [comment]
Confirmed flow card is completely stopped now on out_of_range error (now a token_out_of_range error)
the same for custom flow cards.

closing issue
