### ISSUE TITLE
Homey thinks season winter is already over

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1351]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Flow with is season is not winter then execute 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Flow was activated when the winter season is not yet over, 20th of March Spring starts.

**What did you expect as result?**
Correct timeframes for each season

**Any other remarks**

...

**Comment by nieuwton** [comment]
There are astronomic and meteorologic seasons. The meteorologic winter ends on Februari 28th.

**Comment by chrisboer** [comment]
Sorry but I think the mayority of people don't work with meteorologic seasons

**Comment by nieuwton** [comment]
Maybe we need both. Let's do a poll ;-)

**Comment by OpenMindNL** [comment]
Can't you just make your flow check if the date is before the 21st of March, June, September or December? If that's the case, the astronomic season has not started yet.

**Comment by chrisboer** [comment]
I think it will be picked up by @jeroenvollenbrock

**Comment by WeeJeWel** [comment]
Yes, Homey uses the Meteorological seasons. You're of course free to create an app, or add the dates manually to your Flow.
