### ISSUE TITLE
homey offline

### ISSUE THREAD

**Issue by robertodevet** [athombv/homey#1353]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

when opening the homey desktop app , homey shows me its offline.
i can't get any further to my flows etc. ,also the android app isn't showing anything.
when homey is offline everything still works , flows and speech recognition keeps working,
so i assume it's still connected to the cloud.

*Please include detailed steps how we can reproduce the issue*

When i PTP on homey i can get through  and work on my flows, insight etc., android app is working also.
I need to do this almost every day.
Homey has its own fixed ip address in my network/router .

**What was the result?**

...

**What did you expect as result?**

...for homey to stay connected to my network.

**Any other remarks**

...

**Comment by Arjanvde** [comment]
Can you check with another router.

I sometimes experience sort of the same issue with the black Ubee Ziggo Router. Somewhere Homey disconnects from the router and might come online a day later. 

Fyi, my Homey doesn't use a static IP.

**Comment by robertodevet** [comment]
I don't have another router  , but i extended the ip pool , maybe that this will help.
i will see tomorrow if homey disconnects again.

**Comment by Dijker** [comment]
Is it only Homey that isn't connected?
How many devices do you often have online  vs what was the IP Pool? 
I have the same here a couple of times a week and sometimes one device (tablet/laptop) works and an other doesn't. I suspect my Ziggo Cisco EPC3928AD as the only thing  that always works is restarting the Ziggo Router. For what I hear from colleagues the Ziggo Wifi cause a tot of instability (in general) . 
my IP pool-l has still enough available addresses. 

beside that annoying....

**Comment by robertodevet** [comment]
Well , we are two days further and Homey is still online , so that's good.
What i did was to extend the ip pool, for my devices i use only fix addresses and organize them by product.
Homey is organised with my computers in the 192.168.1.90 range.
Whilst my computers never lost an internet connection , homey dayly went offline. 
So we will see if this was the solution.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by robertodevet** [comment]
The issue is solved.
