### ISSUE TITLE
Cannot add Homey skill to my Alexa

### ISSUE THREAD

**Issue by Gand41f** [athombv/homey#1355]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

I would like to use the Homey skill of my Alexa (https://www.amazon.com/gp/product/B01MTBIR69) with my new Echo dot. But the store says, that I need a .com account and I only have a .de account. I contacted Amazon customer support and they claim that they cannot change my account and that there is no possiblity to install the Homey skill.

**What was the result?**

I cannot use Alexa with Homey.

**What did you expect as result?**

To use Alexa with Homey.

**Any other remarks**

No.

**Comment by mruiter** [comment]
Look in the forum under the Alexa topic. I posted a link on how you can change you're country setting on you're account. Read it and do so. 
And close this github issue

**Comment by Gand41f** [comment]
Thank you, I did not see it as I do not read in the dutch forum usually ;).  However, when I now would like to connect the skill to my athom account, after logging in to athom website, it says "Your Homey skill could not be connected. Please try again later." I will try again tomorrow and hope it works by then and is not a bug.

**Comment by Gand41f** [comment]
Still does not work. Interesstingly this message is shown in German, although I have a .com account now and Homey is set to English as well.

**Comment by WeeJeWel** [comment]
This is something we can't fix because Amazon doesn't support it unfortunately.
