### ISSUE TITLE
Toon App not updated 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1356]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Toon did not work anymore, so checked the appstore and saw that a newer version was available. 
Eventhough my updates are set to automatically it did not installed the new Toon app version 1.0.13 but it was still on 1.0.6

*Please include detailed steps how we can reproduce the issue*
<img width="960" alt="toon" src="https://cloud.githubusercontent.com/assets/23163409/23708299/c67fd62c-0415-11e7-8d30-c45cbc488bea.png">

**What was the result?**

**What did you expect as result?**

**Any other remarks**

...

**Comment by bvdbos** [comment]
Probably due to switching to an app-store with beta-apps of which Toon is one?

**Comment by chrisboer** [comment]
Reboot of Homey was required to restart the update
