### ISSUE TITLE
KAKU AGDR-3500

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1357]
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Setup AGDR-3500 as a boiler device

*Please include detailed steps how we can reproduce the issue*
<img width="960" alt="agdr-3500boiler" src="https://cloud.githubusercontent.com/assets/23163409/23798303/546ae5c8-05a4-11e7-8fa8-4667383e9761.png">

**What was the result?**
Device can be used but can not be selected in a flow.
I now have attached it as a other device then it shows up in the flow device selector
...

**What did you expect as result?**
To see the device when identified as a boiler / waterheater

**Any other remarks**

**Comment by BasKiers** [comment]
Hi,

This issue occurs because there were no flow cards implemented for kettles. This has now been added since v1.2.0-RC9. When your Homey updates to this version or higher the device will become available in the flow page. For now you can fix it by selecting a different virtual device (not a kettle).

Regards,
Bas

**Comment by chrisboer** [comment]
Ok I already did bypass it as a normal "device" so hope the range is better with 1.2 RC9 because this is still on issue.

**Comment by chrisboer** [comment]
Still does not work with 1.2.0 RC9 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24429567/e5c48d36-1412-11e7-9b7c-e390174d2bf7.png)
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24429582/f95e6df8-1412-11e7-9a8a-4dc040948743.png)

**Comment by chrisboer** [comment]
Works with 1.2.0 rc10
