### ISSUE TITLE
Alexa: "There was an error talking to your Homey"

### ISSUE THREAD

**Issue by dd121** [athombv/homey#1358]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

Trying to connect Alexa to Homey with Alexa Skill
I changed my Homey Language to English
Setup the Alexa dot.
Installed Alexa skill (us account)
Tried the skill

**What was the result?**

With every question Alexa responden: "There was an error talking to your Homey"

**What did you expect as result?**

That Homey listened to Alexa

**Any other remarks**

Rebooted both Homey and Alexa a couple of times. But it didn't help.

**Comment by WeeJeWel** [comment]
Is your Homey accessible through the cloud, outside your Wi-Fi network?

**Comment by backslashgithub** [comment]
same problem here, Homey is accessible through the cloud (ios app) without wifi.

**Comment by mruiter** [comment]
Is you're homey also set to English language?

**Comment by backslashgithub** [comment]
Yes, my homey is set to English.

**Comment by dd121** [comment]
Same answers for me!

**Comment by dd121** [comment]
My first language was set to dutch... later I set it to English.

**Comment by ChrisWet** [comment]
Same here firmware v1.19
Changed from Dutch to English for Alexa
Is firmware 1.20 needed?

**Comment by WeeJeWel** [comment]
Homey v1.1.9 should work. Can you share your Homey ID?

**Comment by ChrisWet** [comment]
Is this my homey id:
Athom Cloud ID: 56ab483288a0f24a1a241c6a

**Comment by dd121** [comment]
@WeeJeWel dm't my Homey ID to you on Slack

**Comment by dd121** [comment]
Updated to 1.2.0 RC8 still same problem.

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by ChrisWet** [comment]
thnx, works!
