### ISSUE TITLE
[Request] Mark all notifications als read / delete all

### ISSUE THREAD

**Issue by DeefK** [athombv/homey#1359]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

In my.athom.com at the avatar on mouseover notifications are beeing showed. You have to click each notification to mark it as read. There is no butting for mark all as read / delete all.

**What was the result?**

-

**What did you expect as result?**

Mark all notifications as read / delete all

**Any other remarks**

...

**Comment by Arjanvde** [comment]
The delete all function is implemented if i'm correct:

![notifications](https://cloud.githubusercontent.com/assets/17526110/23954319/4353d136-0997-11e7-825b-e77c68fc30f4.JPG)

**Comment by WeeJeWel** [comment]
Yep, going to Settings -> Notifications will solve your problem.
