### ISSUE TITLE
Show 'update available' somewhere

### ISSUE THREAD

**Issue by newmedia** [athombv/homey#136]
It would be nice if you could see somewhere that an update is available in the home interface.
(perhaps with a little changelog?)

**Comment by WeeJeWel** [comment]
It is, just disable auto-updating.

**Comment by JohanKuster** [comment]
If you go to settings -> Updates and untick the 'download and install updates automatically', then go to any other item on the list. Go back to Updates again and you sould see any available versions with a possibility to install the software.
