### ISSUE TITLE
Conversation improvement

### ISSUE THREAD

**Issue by Heki2017** [athombv/homey#1360]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

Asked Homey a question (f.i. OK Homey Set a timer in 10 minutes) 

**What was the result?**

Homey did not understand and answered sometimes it did not understand or just did not respond.

**What did you expect as result?**

Homey would ask ' Can you repeat?'  This would avoid that I have to call for attention again by starting with 'OK Homey'

**Any other remarks**

Great product, great work all

**Comment by Tweake** [comment]
Hi Heki2017, thank you for your suggestion. There are some notable downsides to automatically restarting the listening process, so we have decided not to add the feature. However, it can be frustrating when Homey does not execute the command you gave, and instead returns to its screensaver without feedback. Therefore I have added better feedback when Homey did not understand what action should be taken.
