### ISSUE TITLE
Can't use random texts on speech confirmation card

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1363]
**What is your Homey version (Settings → System)?**  
1.2.0-r8

**What did you try to achieve?**  
Use random semicolon seperated text to ask a question:
![image](https://cloud.githubusercontent.com/assets/15232724/24071959/13ae27f8-0bde-11e7-820c-38b04d9391dc.png)
Purpose is that Homey randomly select one of the options equally to the speech output card.
 
**What was the result?**  
Homey doesn't select randomly, but speech whole entry. 
...

**What did you expect as result?**  
Randomly selected part, like speech output card.
...

**Comment by WeeJeWel** [comment]
Haha, good one. Fixed
