### ISSUE TITLE
1.2.0 rc8 Login Spotify does not respond (pop-up related)

### ISSUE THREAD

**Issue by dd121** [athombv/homey#1365]
**What is your Homey version (Settings → System)?**

1.2.0 rc8

**What did you try to achieve?**

get Spotify working in Homey Music
I installed the Beta Spotify app and tried to log in Spotify in the settings menu under Apps => Spotify by clicking the Login button.

**What was the result?**
Nothing happens, it maybe that the button doesn't react (gui problem) or the action behind it doesn't do anything. I got no feedback at all.

**What did you expect as result?**

I expected a Spotify login or authorization screen.

Keep up the good work!
...

**Comment by dd121** [comment]
I just tried login in Spotify in my Chrome browser (https://,id..homey.athom.com/manager/settings/#homey:app:com.spotify) 
and I got a pop-up warning (from chrome). 
I added the always allow popups from homey and I could authorize Spotify. 
And is then also shows in the app.

But if I logout and try to login again in the app it doesn't work.
It seems like an pop up setting in the app.

**Comment by TheMSB** [comment]
This issue should be fixed with the release of Homey Desktop 1.0.3. If the issue still persists please let me know.
