### ISSUE TITLE
Media volume not returned to it's original state

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1366]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**

Adjusting the volume of the speaker in the settings menu while playing music, as soon as i've set the correct value. When this setting has been set, Homey confirms the setting with (51% for example), the media volume which was muted has now been set on 51% and is not returned to it's original value of 100%.

![schermafbeelding 2017-03-20 om 18 04 28](https://cloud.githubusercontent.com/assets/17526110/24111886/2b503e8a-0d98-11e7-8f88-6d2f7aedfb61.png)

*Please include detailed steps how we can reproduce the issue*

See above.

**What was the result?**

Media  playback at a lower volume.

**What did you expect as result?**

Media volume to be back at 100%

**Comment by TheMSB** [comment]
@Arjanvde Judging by your screenshot the setting seems to be correct. Keep in mind that the adjusting the Master slider also adjusts the Media volume since the Media volume is proportional to the total output.

**Comment by Arjanvde** [comment]
@TheMSB,

Simple, start the music with the volume slider Media at 100%, move the master slider to 50%, once you've moved the master slider, the Media is played at the volume of 50%. If you restart the media, it is played at 100% again. So it is inconsistent.

**Comment by TheMSB** [comment]
@Arjanvde This and #1367 Seem to share a related cause and should be fixed with a coming release.
