### ISSUE TITLE
Speaker Volume not respected

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1367]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**
I've set the Master volume on 50%, this isn't respected by the Homey Voice once a Jack plug is used, The Homey voice will be than be played at the Media Volume (100%).

**What was the result?**

Homey Voice much louder than expected.

**What did you expect as result?**

Homey voice played on 50%.

**Comment by TheMSB** [comment]
@Arjanvde I am having troubling recognising your issue. If you would be so kind, could you please provide a video or some other kind of explanation that further illustrates your issue?

**Comment by Arjanvde** [comment]
Simple, Homey's Voice is being played at the same volume as the Media volume. I expect that once I've set the master volume Homey's Voice is played at the  that given volume., not as high as the Media Volume. So media is played at 100% and Homey's voice at 50%.
