### ISSUE TITLE
Speech preview doesn't work.

### ISSUE THREAD

**Issue by dd121** [athombv/homey#1369]
**What is your Homey version (Settings → System)?**

1.2.0-rc8

**What did you try to achieve?**

On settings page under Voices trying to Preview the different voices by clicking on the Preview button. 

**What was the result?**

No result, no feedback. Also tried in browser, but got the same result.

**What did you expect as result?**

Hearing a preview of the voices.

**Any other remarks**

First I thought is was also a popup issue, like the Spotify login issue, but it also didn't work in the browser.

**Comment by AJediIAm** [comment]
I can confirm this bug. Changing the speed slider correctly works, but the preview buttons do not work anymore. If you press a lot of preview buttons, Homey will become unresponsive (crash) and a hard reset needs to be performed.
