### ISSUE TITLE
pairing of eurodomest switch wont  work any more after update 0.8.17

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#137]
Eurodomest switch won't pair any more  after update 0.8.17

**Comment by Dennishacq** [comment]
Hey @kingdong78 
Thanks for reporting this issue, Does unplugging Homey and plugging him back in solve this problem?

**Comment by pkonings** [comment]
Same kind of experience today, also with KaKu switches and randomly working again after repowering twice.

**Comment by kingdong78** [comment]
no unplugging and plugging doesn't solve the issue

**Comment by Dennishacq** [comment]
@kingdong78 Are you still experiencing this problem?

@pkonings The bug that causes 433 devices to stop working should be fixed in 0.8.18.

**Comment by kingdong78** [comment]
I still have but i didnt updated yet to 0.8.18

Verstuurd vanaf mijn iPhone

**Comment by itsamaik** [comment]
+1, 433 MHz devices randomly started to work and after a reboot they didn't work anymore (also the paired ones). Waiting for the new update

**Comment by bvdbos** [comment]
@itsamaik that's bug #101 powering off and on should do the trick...

**Comment by Dennishacq** [comment]
@kingdong78 @itsamaik Are your problems fixed in 0.8.18?

**Comment by itsamaik** [comment]
Yes, seems to be fixed.
