### ISSUE TITLE
Z-Wave map goes berserk

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1370]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**

The Z-Wave topology map loads correctly, once loaded it starts spinning around like crazy and it seems it can't stop forever. Have around 30 Z-Wave devices, this is insane. Not really noticeable on the picture, please see the video.

![schermafbeelding 2017-03-20 om 19 23 44](https://cloud.githubusercontent.com/assets/17526110/24115273/1bc373dc-0da3-11e7-8d9f-04587b838749.png)

https://www.youtube.com/watch?v=5o6mbDt4SoY

Issue, is active since the Z-Wave map has been implented

**What was the result?**

Can't read Z-Wave map. Please note, there is a workaround to get the Z-Wave map to see:
1.full screen page,
2. Zoom out to a far maximum
3. grap one of the nodes and pull it away as far as possible (once dragged and moved The Z-wave map should come to a hold
4 Let go of the node and zoom back in, you should now have a good view.

**What did you expect as result?**

Working Z-Wave Map.

**Comment by chrisboer** [comment]
I have about 20 zwave devices but I don't have this issue with v1.2 RC8

**Comment by Arjanvde** [comment]
The issue is that they are bouncing to each other and this never stops, it goes on, and, on, and, on for ever and ever.

**Comment by chrisboer** [comment]
Don't have this issue !

**Comment by jeroenvollenbrock** [comment]
This issue is related to a third-party component. We have filed a bugreport.

**Comment by Arjanvde** [comment]
@jeroenvollenbrock ,

Any update on this since?

**Comment by Arjanvde** [comment]
Think this is solved as the Z-Wave map is now static.
