### ISSUE TITLE
can not find lamps in room x

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#1371]
**What is your Homey version (Settings → System)?**

1.2.0 rc8

**What did you try to achieve?**
switching off and on lights with speech command

*Please include detailed steps how we can reproduce the issue*
' zet lampen in woonkamer aan' 

can not find any lights in the ' woonkamer ' 

**What was the result?**

...lights were not switched

**What did you expect as result?**

...lights switching, as in older firmware

**Any other remarks**

...in the zone woonkamer the apparaten are recognized as lights (small light bulb in icon)

**Comment by chrisboer** [comment]
I have tried this but both in woonkamer as well as kantoor I still can do everything and reacts as it should with v1.2 rc8

**Comment by arno1965** [comment]
I have exactly the same problem! Light in the woonkamer are not recognized.

**Comment by Tweake** [comment]
Do you have any devices which are not lights but also have a name similar to "woonkamer"? 

Device names are prioritised over Zone names. When Homey detects a device name it only focusses on that device and ignores all other devices in the Zone with the same or similar name. 

Let's say you currently have some lights in the Zone "living room" and a Chromecast also named "living room". When you say "turn on the light in the living room" Homey detects a device name 'thinks' _I should turn on the light of this specific device which was mentioned_. After Homey starts switching on the light of your Chromecast it realises that this is not possible. So, no lights end up switching. 
To prevent this from happening, from version 1.2.0 on Homey will give a warning when you rename a device to something which conflicts with a Zone name. Previously added devices are not checked though, which is likely why you are experiencing this issue. In that case, renaming the device(s) should resolve your issue.

On the plus side, you can now reference specific devices by name!

**Comment by laurenssss** [comment]
this indeed resolves the issue for me! A smoke sensor in my woonkamer was called woonkamer, renamed it now and it looks like the voice commands are working again for the ' woonkamer '  as a whole!

**Comment by arno1965** [comment]
Yeah! That's it! I love the option controlling specific devices!
