### ISSUE TITLE
Installed App channel visible in Settings - Apps

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1372]
**What is your Homey version (Settings → System)?**
1.2.0.rc8

**What did you try to achieve?**
Check if an App is installed from Stable/Beta/Aplha channel

*Please include detailed steps how we can reproduce the issue*
![image](https://cloud.githubusercontent.com/assets/12412734/24121206/c97c3e28-0db7-11e7-8e59-d1279ab0dada.png)

**What was the result?**
![image](https://cloud.githubusercontent.com/assets/12412734/24121286/1464d620-0db8-11e7-9fba-ae3de444381b.png)
Not visible, 
Had to switch to the App Store to install the App and see which Channel I have installed.

**What did you expect as result?**

.... v2.2.3 (beta channel) 

**Any other remarks**
Keep up the good work !

**Comment by WeeJeWel** [comment]
Good suggestion, added in v1.3.0!

![screen shot 2017-05-10 at 12 38 51](https://cloud.githubusercontent.com/assets/319873/25894837/c3cb7294-357d-11e7-8df7-5adcd8d37bf6.png)

**Comment by Dijker** [comment]
Nice! Thanks!
