### ISSUE TITLE
Sonos playlist not playing

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1375]
**What is your Homey version (Settings → System)?**
1.2 RC8

**What did you try to achieve?**
Play sonos playlist Chris 

*Please include detailed steps how we can reproduce the issue*
<img width="1430" alt="sonosplaylist" src="https://cloud.githubusercontent.com/assets/23163409/24123841/7aed8122-0dc1-11e7-8c7d-f50d476e8756.png">

**What was the result?**
I got a ! error message but I did not see any error message nor in the applications or anywhere else.

**What did you expect as result?**
That the sonos speakers would start playing the preferred playlist.

**Any other remarks**

**Comment by BasKiers** [comment]
Could this be related to #1385? Could you check if this error still happens when you are sure you have the playlists available in Homey Music?

Regards,
Bas

**Comment by chrisboer** [comment]
@BasKiers I have Spotify playlists and it plays now with Sonos but the SONOS playlists are not yet visable. When I did not yet installed spotify I had the SONOS playlists on screen.

**Comment by chrisboer** [comment]
I cannot even select the SONOS playlist only Spotify playlists
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24294716/f90c94fc-1097-11e7-8b4f-681be7f92e2a.png)

**Comment by chrisboer** [comment]
Issue solved with 1.2.0 RC10
