### ISSUE TITLE
Some flows got disconnected when activating other flows with v1.2.0

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1376]
**What is your Homey version (Settings → System)?**
v1.2.0 RC8

**What did you try to achieve?**
Checked all flows

*Please include detailed steps how we can reproduce the issue*
Some flows got disconnected calling other flows

**What was the result?**
<img width="1430" alt="flowcall_disconnected" src="https://cloud.githubusercontent.com/assets/23163409/24125859/18f5dc3a-0dcb-11e7-8e06-310ad067ac9c.png">

**What did you expect as result?**
No flow disconnected

**Any other remarks**
I just saved the flows broken and they just worked fine again.
...

**Comment by kerkenit** [comment]
Same over here

**Comment by kerkenit** [comment]
@WeeJeWel could you invite for loggin in at my Homey to see a bunch of broken flows. I'm not sure whats missing. Please don't save. I'm hoping they can be restored.

**Comment by kerkenit** [comment]
@chrisboer Are you missing something? I'm not sure if and what is missing

**Comment by chrisboer** [comment]
I did not miss anything only broken flow links which after I saved them again just works as they should be working.

So from my side this issue can be closed if investigation is done.

**Comment by kerkenit** [comment]
Oke. Thanks. By the way we share the same background ;-)

**Comment by kerkenit** [comment]
I just discovered that some speech actions are gone (sparated by a semicolon)

**Comment by chrisboer** [comment]
As there were only a few flows involved I think this was because of "renames" of flows or devices which got reinitialised with the upgrade to 1.2.0 and this is why they were disconnected. 
I will close this issue then.
