### ISSUE TITLE
can't log in to google music

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1377]
**What is your Homey version (Settings → System)?**
1.2.0 rc8

**What did you try to achieve?**
add google music to Homey

*Please include detailed steps how we can reproduce the issue*
create a google music account, I have two factor authentication on (don't know if that's the issue). Try adding an app-password to the google login-screen of Homey settings. 

**What was the result?**
error: not logged in
though the login-fields appear I'm logged in and also google emails me I logged in
![2017-03-21 06_41_24- 419 settings - homey](https://cloud.githubusercontent.com/assets/1064079/24134069/1173df66-0e02-11e7-821d-c14ddc407038.png)
When I go to media, Homey says I'm not logged in (no search-results)
![2017-03-21 06_49_00-](https://cloud.githubusercontent.com/assets/1064079/24134176/b9386c12-0e02-11e7-9a0f-81eda7b93c70.png)

reloading the page gives a different error in console:
![2017-03-21 06_51_22- 419 settings - homey](https://cloud.githubusercontent.com/assets/1064079/24134194/dc278bcc-0e02-11e7-861d-9cd446c31594.png)

**Comment by Qx5** [comment]
I have exactly the same. On the forum I see that some people manage to log in with a specific app password due to 2-factor authentication. Although unlikely, I see some correlation with people having a 4 month free trial and login problems.

**Comment by BasKiers** [comment]
Hi,

This error message was incorrect. The error should be that the login was successful but the app did not find a Phone registered on your Google Play Music account. To fix this you will need to log in to the Google Play Music app on your phone and play at least 1 track. After that the login should work and you should be able to play tracks from Google Play Music. This error message is fixed as of version 1.0.3 of the app.

If this did not fix your issue, please reopen this issue or create a new one.

Regards,
Bas

**Comment by bvdbos** [comment]
not only did I have to play a song: it should be from google (not personal) or it should be playing while logging in through the Homey app...
