### ISSUE TITLE
Feature change : Locks can not be opened with speech

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1378]
**What is your Homey version (Settings → System)?**
v1.2 RC8

**What did you try to achieve?**
Open my front door with speech

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Eventually after 2 times it opened on speech
"Sloten kunnen voor de veiligheid niet met spraak worden bediend"

**What did you expect as result?**
To have the user deside themselves if they want to open their locks by speech or not

**Any other remarks**
I don't like "suppliers" to think for their users, there could be requirements they are not aware of to use it this way.
So yes you can make a warning but let it remain as is.

**Comment by WeeJeWel** [comment]
We will not enable this due to security reasons as stated. But you can make your own Flow with a custom trigger word than opens the lock.

**Comment by chrisboer** [comment]
@WeeJeWel strange that this only started as of release v1.2.0 because I did not have this issue before
