### ISSUE TITLE
Zwave: on/off not updated on multilevel change

### ISSUE THREAD

**Issue by clandmeter** [athombv/homey#1379]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

Dim fibaro dimmer 1 by interface or flow

**What was the result?**

The on/off status is not updated (it keeps listed as off)

**What did you expect as result?**

When changing the multilevel the on/off capability should update.

**Any other remarks**

It seems since setondim has been introduced we do not receive reports back. It looks like this is non zwave-plus related as others mention zwave-plus seem to work correctly?

This has been reported on slack, so this is just a reminder so it doesn't get lost.

/cc @kasteleman @caseda @RobinBol @TedTolboom

**Comment by kasteleman** [comment]
Have the same issue, but not only for the dimmer 1 also for the my Qubino HDA2 dimmer. No reports, that was not the case before 1.1.9 firmware. Currently on 1.2

**Comment by RobinBol** [comment]
Not sure why this ever worked, but I pushed an update to the Qubino and Fibaro app to fix these issues. Are there more devices that have this problem?

**Comment by RobinBol** [comment]
Yes I get that, but why did the devices suddenly stop doing that?:p

**Comment by caseda** [comment]
You tell me :tonque: you are the (semi-) master of zwave with a sniffer

**Comment by RobinBol** [comment]
Wel, I sniffed indeed, but no updates after changing dim value.. If you know of any other devices that have this issue please create a new issue, for now I'll close this one as for the reported devices it is fixed!
