### ISSUE TITLE
Cannot connect my Chromecast with Homey

### ISSUE THREAD

**Issue by wslybkkr** [athombv/homey#138]
For some reason it's not possible to connect Chromecast (2) with Homey. The screen keeps showing a loading screen. After waiting for 10 minutes, nothing happend...
Am i doing something wrong? 

Chromecast: V2
Homey software version: 0.8.17

**Comment by JohanKuster** [comment]
see closed issue [81](https://github.com/athombv/homey/issues/81)

**Comment by WeeJeWel** [comment]
Duplicate of #81
