### ISSUE TITLE
Can't select text to rename playlist

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1381]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**

Renaming the playlist is hard. I've tried to select the complete playlist name (also with double click) or a small part of the playlist but this seems to be impossible. It is not possible to select text in the playlist name, therefore renaming a playlist is though/takes some time to figure out since it is inconsistent.

Please note that on flows, the text for a new flow gets selected completely when a new flow is created, same applies for new folders.

**Comment by TheMSB** [comment]
I just tried to replicate the issue and it would seem that it is possible to select all of the text just fine but because of the dark highlighting this is not apparent.

**Comment by Arjanvde** [comment]
Can't replicate this anymore.
