### ISSUE TITLE
[Enhancement] Make delete option clearer

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1382]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**

When deleting an app i'm always nervous about selecting the wrong app, here is why.

Selecting an app to delete is clear the user selects the app he wants to delete, which is obvious clear

Select
![delete 1](https://cloud.githubusercontent.com/assets/17526110/24147345/14634f8a-0e3a-11e7-9348-132a09ebe2c1.JPG)

Once the delete button has been clicked the user now is unsure (at least I'm) which app I'm going to uninstall. That is because in the pop-up doesn't mention the app which is going to be removed and the bar with Restart, Enable, Delete (from the 1st preview) is gone. 

![delete 2](https://cloud.githubusercontent.com/assets/17526110/24147378/30a80faa-0e3a-11e7-9c24-cc572e110f83.JPG)

On a 22 inch monitor the user has to be very careful since the user is able to make a mistake quite easily.

**What was the result?**

Unsure what app is going to be uninstalled.

**What did you expect as result?**

That in the pop-up the name of the app which is going to be uninstalled is being displayed. 

Ps, Since Homey is becoming more and more important in my House I'm not waiting to delete a crucial app like Fibaro...

**Comment by WeeJeWel** [comment]
Haha, good one, fixed.

**Comment by Arjanvde** [comment]
Nice one @WeeJeWel

**Comment by Arjanvde** [comment]
Solved!

**Comment by Arjanvde** [comment]
@WeeJeWel ,

This isn't solved when the language is set to Dutch. Might be an easy fix.

**Comment by Tweake** [comment]
Also working in Dutch after the next update!

**Comment by Arjanvde** [comment]
On 1.3.0 RC7 it still doesn't work!

![image](https://cloud.githubusercontent.com/assets/17526110/26096871/ebdc052e-3a22-11e7-9f2d-a737666744a0.png)

**Comment by Arjanvde** [comment]
On  1.5.0 this still isnt Solved when Homey is set to Dutch!

![image](https://user-images.githubusercontent.com/17526110/29823265-7a1aeff0-8cce-11e7-80a6-3d9ff2ca76a0.png)

**Comment by WeeJeWel** [comment]
Fixed in v1.5.1

**Comment by Arjanvde** [comment]
Fixed!
