### ISSUE TITLE
Homey not reacting on "ok homey"

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1383]
**What is your Homey version (Settings → System)?**
v1.2 rc8

**What did you try to achieve?**
request a command with "ok homey"

*Please include detailed steps how we can reproduce the issue*
Homey does not respond, this morning I rebooted to check if this helped to increase range to KAKU devices, but after installation of v1.2 rc8 yesterday it was responsive to messages today only works via the app. 

**What was the result?**
Homey not responsive to "ok homey"

...

**What did you expect as result?**
Reaction with orange ledring
...

**Any other remarks**
Send log to Athom key is 203CBAB300
...

**Comment by chrisboer** [comment]
I have rebooted my homey and microphone is working again I send you the log so maybe you can check what happened but it is working again. (so maybe closed when you want)

**Comment by rhannink** [comment]
Same here, after upgrade to 1.2 RC8 ok homey does not work when i speak to Homey. Homey only responses to my 11 yr old son ?????

**Comment by chrisboer** [comment]
Today I have again the issue did nothing fancy, but homey does not respond to "OK HOMEY", now I waited and Homey was not responsive for about 5 minutes also offline ? which is strange because I have not network issues and homey was still pingable.

**Comment by WeeJeWel** [comment]
I'm having a hard time reproducing this issue. Have any of you find some connection when this occurs?

**Comment by WeeJeWel** [comment]
@chrisboer The log you sent, is this from a Homey where 'OK Homey' did not trigger ánd you haven't restarted the Homey yet?

**Comment by chrisboer** [comment]
I have restarted Homey after the first non responsiveness, I have not restarted Homey when de second time came. I have send you another log code 4372582C62. (0:04) 
I experience a lot of "late" responses from Homey like it is "stuck" or doing multi tasking assignments in background which doesn't enable Homey to respond more quicker. 
When I logged out of Spotify and logged in again you see slow responses occur and homey is probably regenerating playlists from Spotify.
I will investigate other scenarios tomorrow

**Comment by chrisboer** [comment]
again the issue with Homey not reacting to OK Homey I will leave it untouched I rebooted last night just before going to bed so homey does not react after reboot I will send the log

**Comment by chrisboer** [comment]
Log send code 49C12A5BC8

**Comment by chrisboer** [comment]
Powered of Homey and after 1 minuted pluged it back in. 
Still no response or reaction on "ok homey" from the Homey Device, from IOS App "ok homey" responds. 
Microphone is on ? I don't know what shuts down the microphone or why homey is non responsive

**Comment by chrisboer** [comment]
Rebooted Homey yesterday night and this morning Homey react again to "ok homey" !

**Comment by satbopper** [comment]
in 1.1.9 and also in rc9 for me again no respons on ok homey,in 1.1.9 there was a constant orange led ring,in the rc9 there is a normal led ring but no led ring respons on ok homey,please solve it,it is madness to boot homey in two or three days

**Comment by satbopper** [comment]
i  have send a log file 3974593CC3 to athom,afterwards i booted homey

**Comment by satbopper** [comment]
for me when homey does not repond to ok homey,i can work perfectly with homey,log in,listen to music etc etc,it only does not react on ok homey,after a boot,it is working again

**Comment by chrisboer** [comment]
@satbopper same here but with my system it only started after 1.2.0 RC9 and not before, but even with a disconnect from power it did not solved the issues I had to do a reboot to get it working again. Currently it is working again will check for how long.

**Comment by spoelly** [comment]
Same here! did a reboot yesterday will check if it still works.

**Comment by satbopper** [comment]
thanks guys but wat is your memory (systeem) and your swap file,here if my systeem is 350mb with a swap file of +/ 360 mb,then the troubles begin,apps crashing with no stack trace and non reactive to ok homey
it is a lot of work but will it help to start from scratch,have anyone tried that because i do not like the fact of rebooting after two or three days

**Comment by chrisboer** [comment]
Today no more non responsive with "ok homey" and after updating to 1.2.0 rc10 homey responded very quickly to the speech.

**Comment by chrisboer** [comment]
Issue is back with powerfailure homey got a cold boot and "ok homey" does not work again, I just did a warm reboot now waiting on the results 1.2.0 RC10

**Comment by satbopper** [comment]
my experience from the day rc10 came out to now no failure again with ok homey,also the memory goes up and down but not more then 370mb with a swap file of 360mb,looks like a stable situation
so still responding to ok homey,detail after install rc10 i did a ptp and waited 30 minutes before starting and then i did a normal reboot of homey (after the normal boot) suddenly my sonos playlists became visible
so it looks like that after a ptp a normal boot is important,anyway for me it works
well done guys

**Comment by chrisboer** [comment]
Tonight my KaKu devices did not respond to anything, so I rebooted homey KaKu devices work again but to  "ok homey" Homey does not respond. 

I think this is a major issue for the Homey and this issue should be solved before next stable release. Otherwise you will get a lot of questions from customers/users.

**Comment by jeroenvollenbrock** [comment]
Does this problem get resolved when you change Homey's master playback volume through the settings?

**Comment by chrisboer** [comment]
I will try when Homey will not react to "ok homey"

**Comment by chrisboer** [comment]
Again homey does not respond to "ok homey" after a reboot this afternoon 
So the log ID is 770C1619C4

**Comment by chrisboer** [comment]
Homey offline and not responding to OK HOMEY. 

Wifi is working as it should because I am on the same wifi network typing this message.

The log I can not send because I can not access homey currently.

**Comment by chrisboer** [comment]
Any updates on this issue ?

**Comment by chrisboer** [comment]
Still an issue yesterday no respons again, rebooted homey still no respons, PTP reboot then it worked. 
I noticed that a fibaro update was pushed before this I had a whole week no issues with homey not responding to "ok homey" so could it be that the fibaro update interfears with homey core functions ?

**Comment by chrisboer** [comment]
Again today an issue here is the log 06AF792707

**Comment by chrisboer** [comment]
Again reboot today, it is now even more frequent than before 
Again the log 0ADAB7012A

**Comment by runderkm** [comment]
I am having the same problem with my Homey on 1.2.2: Homey functional, but not responding to OK Homey. Problem is resolved after reboot.

**Comment by satbopper** [comment]
again not responding to ok homey,normal led ring,through the echo dot homey responds to questions
firmware 1.2.2 and reboot solves the problem

**Comment by bvdbos** [comment]
Got the same now. Changing master volume doesn't work.
log 5280F4B4BF
After a reboot speech worked again...

**Comment by satbopper** [comment]
join the club bvdbos,at least once a week i have to reboot,not necessary because homey understands perfectly through the dot,that keeps on working,it is a pitty that they can not solve it,hoping for the best

**Comment by bvdbos** [comment]
When "OK Homey" doesn't work, does the same happen as in bug #1523 for you?

**Comment by chrisboer** [comment]
No I did not have the same issue as with #1523 but yesterday I tried to shutdown the lights in the livingroom and homey did not react to "ok homey" so led orange was not showing but after 1 minute it did respond with "Ik begrijp niet wat je bedoelt?" so it had a delay

**Comment by Marc1979** [comment]
Same problem overhere, homey is not reacting on "OK homey". Everything else is working. Speech output from the flows is also working as well.

**Comment by Marc1979** [comment]
A reboot was not enough to let it work again. After PTP everything was working again

**Comment by chrisboer** [comment]
Homey none responsive to "ok homey" reboot did not do the trick and PTP also did not do the trick. I will leave it offline for the night but I think this really is getting me frustrated 

Log file : BC41D3C179

**Comment by satbopper** [comment]
after 11 days working,ok homey did not respond anymore,through the homey phone app no luck,through reverb,that is a phone echo dot app,no luck,straight to the dot alexa ask homey all is working but no change of led ring,has anyone tried with this homey behaviour to build homey up from scratch,ye i know a lot of work,a reboot and all is working again

**Comment by chrisboer** [comment]
ok homey still does not work with v1.3.0 rc7 so again the log info I already did a reboot and a PTP with 30 minutes offline. 

Nothing seems to activate "ok homey" again.   Log code E78D526917

**Comment by runderkm** [comment]
As of 1.3.0-rc.7 I am no longer having this problem.

**Comment by chrisboer** [comment]
I currently don't have the issue anymore I deleted some apps I don't use and currently disabled "magister" homey is currently stable responds to "ok homey" will test the new updated v2.0.1 once available in the store but for now I will close this issue untill it will happen again
