### ISSUE TITLE
Music removes Sonos playlists

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1385]
**What is your Homey version (Settings → System)?**
1.2.0 rc8

**What did you try to achieve?**
Look in music and play my Sonos playlist

*Please include detailed steps how we can reproduce the issue*
I added my spotify account yesterday evening and now all spotify playlists are added in music but it removed the Sonos playlist I had.

**What was the result?**
Sonos playlist not there anymore

**What did you expect as result?**
Next to the Spotify playlists also to see the Sonos playlist

**Any other remarks**

**Comment by TheMSB** [comment]
A few checks:

1. Sonos app is installed and enabled?
2. Did your homey just reboot? It is possible for media apps to take a while before fully loading.
3. Does reloading the app resolve the issue?

**Comment by chrisboer** [comment]
1. Sonos beta app installed and enabled
2. I did reboot my homey as my homey microphone was not responding anymore.
3. I removed Sonos beta app and reinstalled it no Sonos playlist yet to see only spotify playlist

**Comment by TheMSB** [comment]
@chrisboer do the playlists reappear when you sign out of Spotify?

**Comment by chrisboer** [comment]
I will try and let you know

**Comment by chrisboer** [comment]
Nope nothing happened even played something from the SONOS App but no playlist apearance on homey

**Comment by BasKiers** [comment]
Hi,

Could you check that the following things so I can reproduce this issue?
Did you change your sonos groups between having playlists and not having playlists?
Do the playlists reappear when you disable the app in settings and enable it again?
De the playlists appear in the sonos app under "Sonos Playlists"?

Regards,
Bas

**Comment by chrisboer** [comment]
Did you change your sonos groups between having playlists and not having playlists? No
Do the playlists reappear when you disable the app in settings and enable it again? No
Do the playlists appear in the sonos app under "Sonos Playlists"? Yes

**Comment by chrisboer** [comment]
Updated to 1.2.0 RC10 and here is a screenprint 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24473845/f3a58b36-14ca-11e7-8e6e-5afa646c76a2.png)
So it works ;-)
