### ISSUE TITLE
Renamed Sonos speakers and not visable in Music anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1387]
**What is your Homey version (Settings → System)?**
v1.2.0 rc8

**What did you try to achieve?**
Relocate my Sonos speakers and renamed them to their new location

*Please include detailed steps how we can reproduce the issue*
Rename the device names of the Sonos speakers

**What was the result?**
Music don't see the speakers anymore.

**What did you expect as result?**
Just a refresh of speaker names under music so I could reselect them

**Any other remarks**
I will remove and reinstall Sonos beta release and see if playlists are coming back in and also will check if speakers will again be visable under music

**Comment by chrisboer** [comment]
Also get this error message
<img width="1600" alt="sonoserror" src="https://cloud.githubusercontent.com/assets/23163409/24157328/6266ca08-0e59-11e7-8ca0-e268cfd735f3.png">

**Comment by chrisboer** [comment]
And another error

<img width="1430" alt="sonoserror2" src="https://cloud.githubusercontent.com/assets/23163409/24158025/6c11c40c-0e5b-11e7-9bd0-ebd711054f46.png">

**Comment by chrisboer** [comment]
I have done the following to correct it, remove Sonos App, removed the Sonos Sub from the group and reassigned it to the group within the Sonos IOS App. Reinstall the Sonos App in Homey and now it works again. 
I think the renaming one of the Sonos Play 5's messed up the homey control of the "Eetkamer" group together with the Sonos Sub.

**Comment by TheMSB** [comment]
@chrisboer I have verified your issue, renaming does seem to break the interface with media at the moment. We are working towards a fix for this issue. I recommend using default names until this issue is resolved.

**Comment by chrisboer** [comment]
@TheMSB I will remain on default names indeed.

**Comment by TheMSB** [comment]
@chrisboer Issue has been identified and dealt with. Expect it in the next release.
