### ISSUE TITLE
Spotify free / Sonos gives "generic_playback_error"

### ISSUE THREAD

**Issue by Tvandongen** [athombv/homey#1388]
**What is your Homey version (Settings → System)?**

 1.2.0-rc.8

**What did you try to achieve?**
Play music from Spotify free on sonos soundbar

*Please include detailed steps how we can reproduce the issue*
Create a spotify free account and try to play music from there

**What was the result?**
Sonos switched from tv source to new source, homey give popup with "generic_playback_error". No music was played.

**What did you expect as result?**
That music was played

**Any other remarks**

...

**Comment by BasKiers** [comment]
Hi,

Could you check if you are logged in on Spotify in the Sonos app? Playing Spotify tracks from Homey on Sonos depends on Sonos fetching the track from Spotify.

Regards,
Bas

**Comment by Tvandongen** [comment]
Bas,

I am logged in on the spotify app. I do not have an option to log in through the sonos app. I am using the versions:
Spotify app: 1.0.4 (beta)
Sonos app: 2.2.2 (beta)

**Comment by BasKiers** [comment]
Yes, for sure! Will add this in the future. Thanks for the feedback.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
