### ISSUE TITLE
Homey Insights: wrong graph

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#139]
This is a graph of luminance measured with a Fibaro sensor:
![schermafbeelding 2016-02-11 om 23 28 46](https://cloud.githubusercontent.com/assets/17163901/12992872/552c9672-d117-11e5-90d6-ae5432fc45b4.png)

Browser: Chrome on Mac OS X
Homey SW: 0.8.17

**Comment by Muyz** [comment]
This temperature graph is also NOK
![schermafbeelding 2016-02-11 om 23 50 23](https://cloud.githubusercontent.com/assets/17163901/12993421/4a4667b2-d11a-11e5-935e-52c8aadd99b6.png)

**Comment by bvdbos** [comment]
Seeing 212 null-value pairs should be cleaned up before storing and processing...

**Comment by Dijker** [comment]
I still have the same issue of graphs going back in time (null-value's)

**Comment by WeeJeWel** [comment]
Fixed in the next update
