### ISSUE TITLE
Z-wave range

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1390]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**
Switch on/off neo plug with distance of 6 metres in open space

*Please include detailed steps how we can reproduce the issue*
Swiching neo plug through web interface or mobile app

**What was the result?**
Nothing happenens
...

**What did you expect as result?**
To switch on or off

**Any other remarks**
I have 6 neo plugs I tried on the same place  so it is not a faulty plug. I have 3 neo plugs both on the ground floor and the first floor. Two on the ground floor work with distance < 4metres. The other one is 6 metres open space and that one doesn't work. On the first floor nothing works

In the blog Athom states that homey is tested on a 40 m range, so I find it very strange that even the one in 6 metres of open space doesnt work

**Comment by StraDijk** [comment]
Can i ask why you are still on 1.1.2?

I have several Neo plugs and one is about 9 meters away from Homey and has 2 concrete walls in between. No issues switching them on/off on 1.1.9 (stable) or 1.2.0..

**Comment by Fiek1** [comment]
Sorry that was een typo.. I am on 1.2.0 rc8

**Comment by Fiek1** [comment]
Can anyone of Athom respond please?

**Comment by Fiek1** [comment]
Everyone on Slack sayd it has to do with some kind of disturbance in my house. I will test my homey in another place this week to be certain. I will try my parents house. I will reopen this issue if the problem stays the same
