### ISSUE TITLE
Spotify : unknown_error while logged in

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1391]
**What is your Homey version (Settings → System)?**
1.2.0 rc8

**What did you try to achieve?**
Search for a Spotify number in the searchbar unautorised message with Spotify when I am logged in.

*Please include detailed steps how we can reproduce the issue*
Logout and logged in again but now all my playlist are gone ? (it came back after a few minutes)

**What was the result?**
Spotify unknown_error while I was logged in.

**What did you expect as result?**
Playlist to remain and no error

**Any other remarks**

**Comment by BasKiers** [comment]
Hi,

Could you provide some more information so I can reproduce this issue.
Are you logged in to a free or a premium spotify account?
Did you try logging out and in again?
Did you try logging in and restarting Homey?

Regards,
Bas

**Comment by chrisboer** [comment]
Please include detailed steps how we can reproduce the issue
Logout and logged in again but now all my playlist are gone ? (it came back after a few minutes)
