### ISSUE TITLE
Queue in the Media Overview is not the Waiting Queue

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1392]
**What is your Homey version (Settings → System)?**

1.2.0 RC8

**What did you try to achieve?**
For me it was a long time unclear how the Queue was filled with tracks. I've found out that the Queue only consists out of songs which are added to the favorites. It is therefore named false and should be named exactly the same as the user names his folder "favorites". This also applies when Homey is set to Dutch.

![schermafbeelding 2017-03-22 om 18 32 52](https://cloud.githubusercontent.com/assets/17526110/24212025/39dcfa14-0f2e-11e7-8f01-d0258ce468c7.png)

**What was the result?**

Not clear how this is filled.

**What did you expect as result?**

**Comment by jeroenvollenbrock** [comment]
Queue contains the songs in the last played playlist. Anything you play using "Add to up next" is prepended to this list.
