### ISSUE TITLE
Selecting radiostations on chromecast-audio

### ISSUE THREAD

**Issue by Marc1979** [athombv/homey#1395]
**What is your Homey version (Settings → System)?**
homey ->1.2.0-rc.8
App-> v2.1.2 - 20.03.17 and tried also v2.2.3 - 20.03.17

**What did you try to achieve?**
Listen to radiostations on a chromecast audio

*Please include detailed steps how we can reproduce the issue*
Select radiostations on the chromecast-audio cart

**What was the result?**
List of radiostations is not loading

**What did you expect as result?**
get a list of radiostations

**Any other remarks**
tried the following
- reboot homey -> NOK
- de-install beta app and install the stable one (reboot in between) -> NOK
- Pull the plug -> NOK

The problem started this morning, worked before without any problems..

...

**Comment by spoelly** [comment]
crashlog:

Stack trace:

SyntaxError: Unexpected token <
at Object.parse (native)
at IncomingMessage.<anonymous> (/node_modules/node-tunein/tunein.js:43:45)
at emitNone (events.js:72:20)
at IncomingMessage.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:923:12)
at nextTickCallbackWith2Args (node.js:458:9)
at process._tickCallback (node.js:372:17)

Exit code: 1
Exit signal: null

**Comment by Marc1979** [comment]
After installing homey firmware  Versie: 1.2.0-rc.9 it's working again?? Didn't do anything.
Stable APP/Beta APP chromecast both working..
