### ISSUE TITLE
Magister does not work anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1396]
**What is your Homey version (Settings → System)?**
1.2.0 rc8

**What did you try to achieve?**
Retrieve degrees from student

*Please include detailed steps how we can reproduce the issue*
Created an application issue see link below

**What was the result?**
https://github.com/gruijter/com.gruijter.magister/issues/6

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
This is an App issue. The error message is just not displayed properly. I've tried to reproduce the issue, and the invalidly displayed error message was "Invalid API key". Please contact the app developer for further assistance.
