### ISSUE TITLE
Homey Insights: no scrolling of devices possible

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#140]
The Homey Insights screen shows all devices on the left-hand side of the screen. Since it is not possible to scroll through devices (at least, I wouldn't know how), not all can be selected. 

Browser: Chrome on Mac OS X
Homey SW: 0.8.17

**Comment by AndreSomers** [comment]
Scrolling is possible, but the UI for it is too subtle. A thin, semi-transparent scrollb bar appears if you hover over the right edge of the list of devices. You can grab it to scroll.

**Comment by Muyz** [comment]
@AndreSomers : I really don't see such a scrollbar.

**Comment by AndreSomers** [comment]
Here is a screenshot. It appears for me if I bring my mouse close to it.

![scrollbar](https://cloud.githubusercontent.com/assets/10531631/13007058/b86728e4-d18d-11e5-82df-f9fd8899081d.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
