### ISSUE TITLE
[Enhancement] Allow sorting of tracks

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1400]
**What is your Homey version (Settings → System)?**

1.2.0 RC9

**What did you try to achieve?**
I've tried to sort tracks into my favorite order after adding them to a playlist.

**What was the result?**
Sorting of tracks is not possible.

**What did you expect as result?**
The the user could tracks to his own preference.

**Comment by TheMSB** [comment]
@Arjanvde If you want to re-arrange tracks then this is possible in Homey Playlists by dragging tracks from one position to another. This is however not possible with external playlists at this time.

**Comment by Arjanvde** [comment]
Missed this one, can be closed for now :)
