### ISSUE TITLE
[Enhancement] Allow ordering of the search results by source

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1401]
**What is your Homey version (Settings → System)?**

1.2.0 RC9

**What did you try to achieve?**
Would be a great addition if the user is able to select from which source results are displayed first.

![schermafbeelding 2017-03-23 om 20 24 44](https://cloud.githubusercontent.com/assets/17526110/24266408/f6b4d282-1006-11e7-9871-3a1da57d9e50.png)

In my case, Soundcloud is always displayed at the top, I would however have Youtube results are displayed as the first result and Soundcloud results second. If Spotify comes available, that should be first, Youtube second and Soundcloud Third.

**What was the result?**
The search order of the used sources could be defined by the user.

**What did you expect as result?**
That the user can order them as he prefers.

**Comment by WeeJeWel** [comment]
Sorry, but that's too complicated for a 'nice' thing :-)
