### ISSUE TITLE
[1.2.0-RC9] Z-wave node bingo tumbling in Z-wave map

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1402]
**What is your Homey version (Settings → System)?**
1.2.0-RC9

**What did you try to achieve?**

Look at the Z-wave map

**What was the result?**

All Z-wave nodes keep spinning like the balls of the bingo game (not clearly visible on below screenshot, see attached video)
<img width="1130" alt="schermafbeelding 2017-03-23 om 23 52 21" src="https://cloud.githubusercontent.com/assets/17163431/24273666/cad577da-1023-11e7-8dc7-281c5ab3c15d.png">

**What did you expect as result?**

Fixed map or at least converging

**Any other remarks**

see video
[Z-wave node ID bingo.mov.zip](https://github.com/athombv/homey/files/866392/Z-wave.node.ID.bingo.mov.zip)

**Comment by Arjanvde** [comment]
Hi @TedTolboom, think this is a duplicate of #1370

**Comment by TedTolboom** [comment]
Overlooked #1370 > duplicate > closing issue
