### ISSUE TITLE
Battery drain

### ISSUE THREAD

**Issue by StraDijk** [athombv/homey#1404]
**What is your Homey version (Settings → System)?**
1.2.0 rc9

**What did you try to achieve?**
Yesterday almost all batteries were empty. Fibaro and Aeotec devices

**What was the result?**
Some batteries went from 100% to 86 overnight.

**What did you expect as result?**
That batteries don't drain overnight.

Attached insight from the fibaro floodsensor
![2017-03-24_09-54-11](https://cloud.githubusercontent.com/assets/2519741/24287573/8048855c-107a-11e7-914e-c865e5b34533.png)

**Comment by raymondkoning** [comment]
![image](https://user-images.githubusercontent.com/26574488/28643958-dcbf9cc8-7257-11e7-9dff-4b01e26d523b.png)

**Comment by raymondkoning** [comment]
Image shows 3 times a battery drain in the last year. The last time was after 3 months (first 2 times after 1 month. 
![image](https://user-images.githubusercontent.com/26574488/28644105-7842c97c-7258-11e7-9b0d-b6ad670fa75e.png)

**Comment by WeeJeWel** [comment]
What's the device's wakeup interval setting?

**Comment by raymondkoning** [comment]
300 seconds

**Comment by WeeJeWel** [comment]
Try lowering it to a more battery-saving value, such as 1 hour.
