### ISSUE TITLE
Homey non responsive and disconnected to cloud 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1405]
**What is your Homey version (Settings → System)?**
v1.2.0 rc9

**What did you try to achieve?**
Play music with Sonos via Music

*Please include detailed steps how we can reproduce the issue*
Logout of Spotify , login to Spotify
Sonos not responsive and even disconnect from cloud 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24287655/b8c38cc4-107a-11e7-8930-a0dd024a353d.png)

**What was the result?**
Homey desktop app not responsive to anything

**What did you expect as result?**
Normal operation of Homey

**Any other remarks**

...

**Comment by chrisboer** [comment]
Waiting on further testing tomorrow

**Comment by TheMSB** [comment]
@chrisboer Is the problem still occurring for you?

**Comment by chrisboer** [comment]
Homey reacts about 3 to 4 minutes later to a request "gaat het regenen vandaag" so I call that still an non responsive issue

**Comment by TheMSB** [comment]
@chrisboer It is possible that when you have a large amount of playlist and track data that it will temporarily cost a large amount of memory to import and process these, can you verify Homey memory consumption during the interval of 'poor connectivity'?

**Comment by chrisboer** [comment]
I have on spotify about 40 play lists with an average of about 50-100 numbers in each playlist. 

With memory I don't see any issue 

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24626767/a354ab9e-18b2-11e7-9eff-1f7b1c4bb64c.png)

**Comment by jeroenvollenbrock** [comment]
Could you send us a log after/while these issues occur?

**Comment by chrisboer** [comment]
I will send a log file when it occurs again.

**Comment by chrisboer** [comment]
Homey not responsive again after adding AGDR-3500 homey did not react to ok homey only after 1 min it said that it did not understand what I meant. 

So log send code 21B3970CF5

**Comment by chrisboer** [comment]
Any update on this issue ?

**Comment by TheMSB** [comment]
> Any update on this issue ?

I have been unable to reproduce the issue as of yet.

**Comment by chrisboer** [comment]
I don't have the unresponsiveness anymore but I still have the issue that homey is not responding to "ok homey"  so I will close this one and will remain the other one open.
