### ISSUE TITLE
Sonos speakers not playing anymore after upgrade to Homey 1.2.0 RC9 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1406]
**What is your Homey version (Settings → System)?**
v1.2.0 rc9

**What did you try to achieve?**
Play music with Sonos via a flow

*Please include detailed steps how we can reproduce the issue*
Upgrade 1.2.0 RC8 to 1.2.0 RC9 during the night

**What was the result?**
Sonos speakers not playing music anymore
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24287978/f6446c66-107b-11e7-9991-3d8ecd1daa51.png)

**What did you expect as result?**
Playing of music

**Any other remarks**
...

**Comment by TheMSB** [comment]
@chrisboer We changed some code related to speakers in order to resolve an earlier issue. It is possible that flow cards have become invalidated. When you mouseover the error icon on the flow card does it provide an error message?

Does any of the following fix the issue? :

- re-adding the flow cards
- re-adding the speaker
- rebooting after doing any of the above

**Comment by chrisboer** [comment]
The error given is "generic_playback_issue" I will now remove Sonos App and reinstall the app to see if that works.

**Comment by chrisboer** [comment]
Reinstall the Sonos app and Re-adding the speakers did the trick in playing the music again ad I did not have to reboot.
It did not resolve this issue with generic_playback_issue even when I have completely recreated the flow.

**Comment by chrisboer** [comment]
Found the issue is related to youtube issue as I select "Een kopje koffie"  from Spotify it works 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24291957/75e148d6-108b-11e7-84e9-37d367db7597.png)

**Comment by TheMSB** [comment]
@chrisboer This issue is resolved then or are you still unable to play Spotify tracks through flows?

**Comment by chrisboer** [comment]
I think the issue is resolved with reinstalling Sonos App and reinstall Sonos speakers, the remaining issue is now related to #1393
