### ISSUE TITLE
Music does not work with Sonos

### ISSUE THREAD

**Issue by Schagalaah** [athombv/homey#1411]
**What is your Homey version (Settings → System)?**

1.2.0 RC9 / same with 1.2.0 RC8

**What did you try to achieve?**

Enter a song title in the search field of the music section

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

It always returns "no music found". 
...

**What did you expect as result?**

the song or a list of songs
...

**Any other remarks**

Is there anything I have to configure to get this working? 

...

**Comment by chrisboer** [comment]
You have to have spotify installed or youtube (but as youtube is not working) you can currently only play music with a spotify account.

**Comment by Schagalaah** [comment]
There is no possibility to use my own sonos library? Will this be available in future? 
I don't have spotify but 
- Local music library
- Amazon Music
- Own Plex server

**Comment by chrisboer** [comment]
They are aware of the issue #1385

**Comment by Schagalaah** [comment]
ok thanks

**Comment by Schagalaah** [comment]
sorry to mention but it is still not working. I have many sonos boxes. Music always returns "no music found".

**Comment by bvdbos** [comment]
This is working now with the latest Sonos-app?

**Comment by Schagalaah** [comment]
Yes. Looks good. Tried it once and it worked. Thanks!
