### ISSUE TITLE
Search after save

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1414]
**What is your Homey version (Settings → System)?**

1.2.0 rc.9

**What did you try to achieve?**

Search for flows, edit and go to the next.

**What was the result?**

After save the text of search still persists, but the flows arn't filtered

**What did you expect as result?**

Show only the flows that should be listened

**Any other remarks**
Quick-fix witch I forgot every time (add a random char and press backspace)

**Comment by WeeJeWel** [comment]
Fixed in v1.3.0!
