### ISSUE TITLE
[Enhancement] Search inside flows

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1415]
**What is your Homey version (Settings → System)?**

1.2.0 rc.9

**What did you try to achieve?**

I've a lot of flows like some other fellow Homey's.
I want to do something with a special device or variable. Basically everything witch is in a flow.
I want to search for all flows where for example the variable _sleeping_ is used.

**What was the result?**

No result this is a new feature

**What did you expect as result?**

When I type text in the flow search fields. I want to search for every name or description or value where that kind of card contains my search text. So basically every field witch contains text

**Any other remarks**

Thanks for your great support

**Comment by caseda** [comment]
Duplicate: https://github.com/athombv/homey/issues/658
