### ISSUE TITLE
Sonos playlist not completely imported

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1417]
**What is your Homey version (Settings → System)?**

1.2.0 rc9

**What did you try to achieve?**

I created a playlist in Sonos that contains about 1600 songs. Works fine in Sonos apps.

**What was the result?**

In Homey "Muziek" I see the playlist under Sonos, but the list only contains about 60 or 70% of the list.

**What did you expect as result?**

To see the complete list up to the end.

**Any other remarks**

Google Play only offers 1000 songs per playlist. Maybe this max is also applied to Sonos playlists?

**Comment by TheMSB** [comment]
@OpenMindNL Would you be so kind as to provide me with the following information:

- What apps are used in the playlist (on Sonos; e.g.: GooglePlay, Soundcloud, etc.)
- How many songs are exactly in the playlist
- Do the songs get cutoff at the end of the list? or are random songs missing?

**Comment by chrisboer** [comment]
@TheMSB I don't see my SONOS playlists anymore after connecting Spotify, but my playlists only contain 3 songs currently. 
So I would like to know how I get the playlists even visable under Music.

**Comment by TheMSB** [comment]
@chrisboer You already have an issue open at #1385 , responding there will help resolve the issue in a more timely manner.

**Comment by OpenMindNL** [comment]
At this moment I'm busy to re-import my complete collection to Sonos.

But I do recall that the total number of songs in the playlist was 1634 or 1637.
The number of imported/shown songs in the playlist was 989. I can still check this  number in Homey/Muziek where the playlist still exists... However. I deleted this playlist from Sonos more than 24 hours ago...

**Comment by OpenMindNL** [comment]
Ok...

- I created a new playlist in the Sonos software. It contains 1640 songs.
- After a few minutes this new playlist shows in Homey/Muziek... containing only 1000 songs
- Everytime when I reload the page, the list stops at 1000 songs.

note: When the new playlist showed in "Muziek" the old playlist (that I removed from Sonos yesterday) was removed from Homey/Muziek. Should have been done earlier I think.

**Comment by TheMSB** [comment]
@OpenMindNL Just to be clear, the number listed next to the playlist also indicates 1000 or does the actual list view just cut off at the 1000th track?

**Comment by OpenMindNL** [comment]
I didn't count the songs manualy, but indeed... The number next to the playlist seems to indicate 1000 ... It's not really clear because the number is not completely visible in the small square... I see 10 + half a 0, but above the playlist it shows: Sonos, 1000 nummers
Also... The last song I see in Homey's playlist is not the same as in Sonos playlist, althought they seem to have the same order when I compare the first songs in the list.

**Comment by OpenMindNL** [comment]
Additional: I managed to find the last songs of Homey's Sonos list while scrolling the original Sonos list.
The order for the last visible songs is still the same for both lists, and the sroll-position in the Sonos list seems ti be somewhere around 60-65%, which would match to seeing 1000 songs of 1640.

**Comment by jeroenvollenbrock** [comment]
Does this issue still occur in rc10?

**Comment by chrisboer** [comment]
For me Sonos playlist is imported now, so it works in RC10 but I only have 3 songs in one created Sonos playlist, I use spotify mostly for my playlists.

**Comment by OpenMindNL** [comment]
@chrisboer ... I really don't see why you should reply to @jeroenvollenbrock  when this issue is about a playlist with more then 1000 songs.

@jeroenvollenbrock : I'm running rc10 for a few days now. The original Sonos list still contains 1640 songs where Homey-Muziek says it's 1000 songs.
