### ISSUE TITLE
1.2.0-RC9 No connection with Toon

### ISSUE THREAD

**Issue by DeefK** [athombv/homey#1419]
**What is your Homey version (Settings → System)?**

1.2.0-RC9

**What did you try to achieve?**
Connection with Toon

*Please include detailed steps how we can reproduce the issue*
Working on 1.2.0-RC8

**What was the result?**

...

**What did you expect as result?**

Connection with Toon

**Any other remarks**

Did a reinstall of the app and readd the Toon thermostat. No result

**Comment by chrisboer** [comment]
@DeefK I had the same disconnect on Toon when upgrading to RC9 but you should remove the app and then 2 times connect to Toon with your account the second time it picked up the toon appliance again. So it should work with 1.2.0-rc9

**Comment by kasteleman** [comment]
No problems with rc9. Om rc8 i had to restart the Toon app after a reboot to get it working. With rc9 that isn't the case anymore. Works fine for me without reinstall.

**Comment by chrisboer** [comment]
I think this one can be closed @DeefK

**Comment by DeefK** [comment]
Yes. Sorry for late response

**Comment by chrisboer** [comment]
@DeefK you have to close it or athom ;-)
