### ISSUE TITLE
Time speech not nice at the hour

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1423]
**What is your Homey version (Settings → System)?**

1.2.0 rc9

**What did you try to achieve?**

Make Homey say the time at each hour by using the Time-tag

**What was the result?**

At 3 o'çlock in the morning/night Homey says; "Het is 3 uur 0"

**What did you expect as result?**

"Het is 3 uur"

**Any other remarks**

Tried to figure what happened with "Say something: [ Het is 3:00 ]"
Homey says; "Het is 3 uur"

However, the Time-tag shows: 03:00 (leading zero)

With "Say something: [ Het is 03:00 ]"
Homey says; "Het is 3 uur 0"

I also noticed this at 01:00 and 02:00

Solution: Don't use a leading zero for the time-tag (?)

**Comment by Dijker** [comment]
Looks like isue #941 is back...

**Comment by Tweake** [comment]
fixed with the next release, thanks for pointing it out

**Comment by bvdbos** [comment]
works for me now..
