### ISSUE TITLE
Small naming change in Voice Card [1.2.0-rc10]

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1426]
**What is your Homey version (Settings → System)?**
1.2.0 RC 10

**What was the result?**
Old:
![image](https://cloud.githubusercontent.com/assets/20989897/24469737/d758f822-14bc-11e7-8ea0-dea65b2f9c7b.png)

New:
![image](https://cloud.githubusercontent.com/assets/20989897/24469754/e2dc8c5e-14bc-11e7-864c-d15b66d49601.png)

(thanks @lubbertkramer for the screenies :))

**What did you expect as result?**
In English: "Something was said containing"
And in Dutch: "Een gebruiker zei iets met"

Seems more appropriate due to it allowing for wildcard use, with 'something specific' I would not have guessed it allowed for that %feature%.

**Any other remarks**
Nah, I'm good :)

Cheers!

**Comment by Tweake** [comment]
Thanks for creating the issue, sorry I forgot to follow up with you on slack. 

Just to avoid confusion; it does not exactly allow wildcards, but rather it checks the words you entered one by one without paying attention to the word order. If all words are present, the Flow is triggered.

That said, you have a good point and I'll change it in the next update :)
