### ISSUE TITLE
Homey does not understand what I mean 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1427]
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Mute my Sonos speakers via speech flow

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24474446/f842b66c-14cc-11e7-82a4-bca3f3ec2938.png)
 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Sonos speaker goes on mute but homey says "Het spijt me, maar Ik begrijp niet wat je bedoelt"

Same issue with "Sonos aan" a speech flow were I put my sonos speakers on play again.
...

**What did you expect as result?**
Just execute the command as is and not come with the remarks above

**Any other remarks**

...

**Comment by chrisboer** [comment]
@Dijker I don't agree this is a duplicate, because homey executes the "Sonos uit" command but after that he says he does not understand what I mean.

**Comment by Dijker** [comment]
@chrisboer 
What is the difference between #1425 and your problem? 
both execute a custom flow and both cases Homey  react with "Het spijt me, maar Ik begrijp niet wat je bedoelt" ?

I don't see the difference?

**Comment by chrisboer** [comment]
@Dijker no you are right it is the same indeed, but how and why is this in suddenly ?

**Comment by Dijker** [comment]
I guess Athom made the decision to change some things, new insights (voortschrijdend inzicht) 
this has some big consequences for current flows .... 
Maybe close this issue and follow the other Issue or threads on Slack where Athom responds....

**Comment by chrisboer** [comment]
Waiting on comment and resolving of #1425
