### ISSUE TITLE
Changed in tag temperature Netatmo

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1428]
**What is your Homey version (Settings → System)?**
1.2.0 rc10 

**What did you try to achieve?**
Check my Netatmo temperature and airco flow 

*Please include detailed steps how we can reproduce the issue*
Tried to test it with Temperature on 23.5 but it did not work then I looked at the tags and it seems that the tag from Netatmo was changed and not corresponding to the condition tag. 

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24475081/1745b88c-14cf-11e7-820c-5b70ca8cf1d5.png)

**What was the result?**
Test did not run

**What did you expect as result?**
Test to run as it shows in the screen

**Any other remarks**
I corrected the tag in the condition flowcard to the one from Netatmo device and saved the flow then it worked as it should

**Comment by Dijker** [comment]
Chris, 
I think your question is not clear, 
your screenshot shows the month is not correct  yesterday was not between April and September!
![image](https://cloud.githubusercontent.com/assets/12412734/24509793/a233b41a-1567-11e7-9c9e-9de4270a78df.png)

and I don't see what you mean about the token... 
Can you reproduce the problem and write step by step what go's wrong? maybe with one or more other screenshots?

**Comment by chrisboer** [comment]
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24527463/8ba2a338-15a2-11e7-87a3-e533cdac3f06.png)

The temperature TAG for test is not the same temperature as the temperature TAG for Netatmo Binnen.
So you can fill in anything but the flow will not work and yes I know that the maand is incorrect. But that was not the issue.

**Comment by Dijker** [comment]
I tried to  reproduce on Homey version 1.2.0-rc10 in Dutch , NetAtmo App v2.0.5 with the following flow:
![image](https://cloud.githubusercontent.com/assets/12412734/24537593/b60b796a-15e3-11e7-94ab-5ef48a061bb4.png)
for me it just works as expected, 

Created new flow, 
Droped a NetAtmo inside card in the trigger column, 
Droped a logic to the Condition and changed to greater than.
droped the token from the card ...
Etc. 
Tested it and it worked as expected for me, 
What is different for you?  
Where dd you select the token?

**Comment by Dijker** [comment]
Ok, Tried again and I got it.....
![image](https://cloud.githubusercontent.com/assets/12412734/24537980/96aec614-15e6-11e7-940e-a6b37edc6a98.png)

If you create the above flow and select the token from the Tags drop-down for the Logic Card... (red)
The Test still uses the Token from the droped Trigger Card! (Yellow)
That's where it goes wrong!

Users should use the token from the condition card for the test to work! (Green) 

@WeeJeWel  Nice one for you to look at?

**Comment by chrisboer** [comment]
I had indeed a flow like this ! but now I changed it to the green arrow ! and works again.

**Comment by chrisboer** [comment]
I got it again with another flow and I know for sure I used the Netatmo tempature tag

![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24544370/4fc36a8a-1603-11e7-9641-e74122caa7c2.png)

**Comment by Dijker** [comment]
This time in your Screenshot: 23.5 isn't < 19 ~ you use the card "is kleiner dan" !
So the Red X in the provided screenshot is correct imho. 


On the other side, imho keep the Issue Open so @WeeJeWel  can fix the use of tokens dragged from the Top menu  to cards  when testing...

**Comment by chrisboer** [comment]
I am so stupid sometimes ;-)
