### ISSUE TITLE
KlikAanKlikUit "StopContact" doesn't show up in Flows

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#143]
It adds fine, the test screen with the lightbulb and toggle also works, but it doesn't show up in Flows so I can't use it.
Added a KlikAanKlikUit muurschakelaar, which does show up.

**Comment by Dennishacq** [comment]
Hi @RuudBurger ,
Thank you for reporting your issue.
What aption did you select in the following screen?
![image](https://cloud.githubusercontent.com/assets/15836768/13007956/c7cd366a-d193-11e5-91fe-93ccb6544835.png)

**Comment by RuudBurger** [comment]
Fan

**Comment by Dennishacq** [comment]
@RuudBurger 
There aren't any speech commands and flow cards for the Fan yet.
You should get Flowcards when you pair your device again and select None of the above.
