### ISSUE TITLE
Toon keeps disconnected

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1433]
**What is your Homey version (Settings → System)?**
1.2.0 RC10

**What did you try to achieve?**
Reconnect to Toon as it was disconnected after update to RC10

*Please include detailed steps how we can reproduce the issue*
Try restart Toon app did not work
Removed Toon app and reinstalled the Toon beta app.
Connected Toon via add device and was found but it still gives the disconnected logo
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24541577/5aad78e2-15f8-11e7-896f-8c87164bb0b4.png)

**What was the result?**
Toon still showing as disconnected eventhough I can connect to it via the IOS App

**What did you expect as result?**
To have Toon device connected to homey again

**Any other remarks**

...

**Comment by chrisboer** [comment]
Did remove it 2x and now Toon is again connected but this is offcourse not how it should work !

**Comment by RobinBol** [comment]
This is why the app is still in beta, the toon api is causing these problems, they hope to improve the reliability in the coming month.
