### ISSUE TITLE
Can not drag TAG again on 4k screen

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1434]
**What is your Homey version (Settings → System)?**
1.2.0 RC10

**What did you try to achieve?**
Drag a temperature tag from Netatmo 

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24544530/ea99dd32-1603-11e7-83cf-f06aef7af766.png)

**What was the result?**
Have to press F11 again to enable tag dragging

**What did you expect as result?**
As it worked with 1.2.0 rc9 I don't know why it is not working again ?

**Any other remarks**

...

**Comment by camilleversteeg** [comment]
@chrisboer i have the same issue: https://github.com/athombv/homey/issues/1439

But in my case, F11 is not working. Can you explain your workaround in more detail?

**Comment by chrisboer** [comment]
There is not much to explain, you press F11 to get full screen which enables the possibility to drag the TAG again. After Desktop app is restarted it worked also but it is still sometimes not working.

**Comment by camilleversteeg** [comment]
@chrisboer tried full screen on desktop, laptop. Reload page etc. 

not making any difference. Very annoying. Due to this I can not work on my flows.

**Comment by Dijker** [comment]
@camilleversteeg I guess you use Windows on a 4k screen? 
Did you try using the chrome browser?
Or is  it possible to switch to 100% scaling to test if that works?

**Comment by camilleversteeg** [comment]
@Dijker still same issue. So now i have tried dragging the tag in:

Windows PC (4k Screen)
- in Chrome full-screen (150% scaling)
- in Chrome windowed (150% scaling)
- in Chrome full-screen (100% scaling)
- in Chrome windowed (100% scaling)
- in Homey-desktop App full-screen (150% scaling)
- in Homey-desktop App windowed (150% scaling)

Laptop Mac (unknown resolution/scaling)
- in Chrome full-screen (100% scaling)
- in Chrome windowed (100% scaling)

Tomorrow i'll try my Windows laptop (full-hd) and add that information. In any case, full-screen and scaling does not seem to influence the issue.

![image](https://cloud.githubusercontent.com/assets/15101655/24588946/46d4fc60-17d2-11e7-842c-16af1e81620c.png)

**Comment by gajdur** [comment]
Having the same problem here, taking the tag and waiting about 3-4 seconds over the "and" or "then" field helped

**Comment by chrisboer** [comment]
I also have a "lag" sometimes when dragging the "tag" then I have to keep my mouse really still to be able to release in the "and" or "then" field.

**Comment by chrisboer** [comment]
Problem seems to be resolved I did not had this issue for a while so will close it now

**Comment by chrisboer** [comment]
Same issue again with homey 1.5.5

**Comment by chrisboer** [comment]
Works but is very very slow.

**Comment by camilleversteeg** [comment]
For me in certain flows I can't add tags anymore. Doesn't matter how long I wait. It freezes.

I'm on 1.5.6-rc.7
