### ISSUE TITLE
Can not select device to send morse

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1435]
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Send morse to my phone but I can not select my phone device

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24549054/eedcea6a-1617-11e7-8e8a-8d285f0a3ac8.png)

**What was the result?**
No selectable device
...

**What did you expect as result?**
To have selectable devices

**Any other remarks**

...

**Comment by bvdbos** [comment]
![2017-03-31 13_56_41- 468 flow - homey](https://cloud.githubusercontent.com/assets/1064079/24549525/fc999d90-1619-11e7-9c20-2fbfd39d2c08.png)
works for me...

**Comment by chrisboer** [comment]
Do I have to reassign my phone, and if I have to are all the flows broken or will they pick it up again ?

**Comment by Inversion-NL** [comment]
Do you have any devices at: https://my.athom.com/#/phones

**Comment by chrisboer** [comment]
Yes you can see that in the flow above

**Comment by jeroenvollenbrock** [comment]
Push-morse is not supported on iOS due to restrictions by Apple.
