### ISSUE TITLE
Translation: Master Volume

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1437]
**What is your Homey version (Settings → System)?**

1.2.0 rc10

**What did you try to achieve?**

Repair a flow with volume adjustment in it.

**What was the result?**

The dutch volume action card says "Zet Meester Volume op"

**What did you expect as result?**

It should be "Zet Hoofdvolume op" obviously.

**Any other remarks**

While we're talking volume anyway may I plug https://github.com/athombv/homey/issues/1221 which I posted some time ago? ;)

**Comment by bvdbos** [comment]
confirmed fixed
