### ISSUE TITLE
Changing voice breaks voice recognition and voice output

### ISSUE THREAD

**Issue by edtst** [athombv/homey#144]
I changed from Brian to Amy and back to Brian. Now Brian stops talking and voice recognition no longer works. Selecting amy and rebooting makes it work with Amy but never again with Brian. I did a total reset, but Brian does not work then either.

**Comment by elgenioNL** [comment]
#53

**Comment by edtst** [comment]
Yes except that this is post 8.17

**Comment by elgenioNL** [comment]
> Confirmed fixed on downloaded voices.
> 
> Still unable to select Brian, error in console:

**Comment by edtst** [comment]
Not fixed here in 8.17, still the same issue

**Comment by YoupHulsebos** [comment]
I got the same issue. Downloaded Emma and selected it as homeys voice. Since then Homey hasn't talked (with the exception of voice previews. I have tried going back to the original voice and rebooting but the made no difference.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.18. Please reopen if issue persists.
