### ISSUE TITLE
Scroll bar Notification list isn't working.

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1440]
**What is your Homey version (Settings → System)?**

1.2.0.rc10
Desktop app 1.0.3 and in Chrome

**What did you try to achieve?**

I want to scroll down through the notification list by using the Homey Desktop app or Chrome browser. When the mouse pointer tips the scroll bar, the notification windows disappears.
![image](https://cloud.githubusercontent.com/assets/8507396/24579210/0655528e-16f1-11e7-8125-1881709ce794.png)

**What did you expect as result?**

That I could use the scroll bar.

**Comment by WeeJeWel** [comment]
Nice find! Fixed in 1.2.0-rc.11.
