### ISSUE TITLE
Homeygoshi, loses score at reboot

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey#1441]
**What is your Homey version (Settings → System)?**

1.2.0B10

**What did you try to achieve?**

Get on place no1 of leaderboard

*Please include detailed steps how we can reproduce the issue*

After an automated reboot at night, homeygoshi score is lost....

**What was the result?**

Bigcry, i was in top 10

**What did you expect as result?**

To be on the first spot, when i wake up

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
This has been resolved in version 13.3.7.
