### ISSUE TITLE
[1.2.0-RC10] New Frequent Z-wave ProcessSendData lockups block all Z-wave commands send to devices

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1442]
**What is your Homey version (Settings → System)?**
1.2.0-RC10

**Observation**
As of 1.2.0-RC10, I do no longer see any queue_full error messages which will be related to the increased priority for Z-wave. 
As of 1.2.0-RC10, I do experience several Z-wave lockups; Homey is able to receive Z-wave reports, but not able to control my Z-wave devices

**What was the result?**
Z-wave devices do not respond, three cases:

**170331 Inability to remove node**
Most likely same issue / cause as discussed last Friday with @jeroenvollenbrock where I was not able to remove a Z-wave device

Z-wave state:
> {"zw_state":{"currentProcess":"ProcessSendData","ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,30,31,33],"chip_type":5,"chip_version":0,"homeId":3756795748,"nodeId":1,"nvr":[1,2,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,20,16,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,212,14],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"5d3f09404014437e867567fbad4529c8","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes"],"currentCommand":"sendData"},"zw_ready":true,"_stateTimestamp":1490995935147}

Homey indicates to become offline:
<img width="351" alt="schermafbeelding 2017-03-31 om 23 33 18" src="https://cloud.githubusercontent.com/assets/17163431/24585367/dbaef402-1788-11e7-9b36-dc6efc53d7f1.png">

Homey log: 4A9849DA22

Z-wave log:
[170331_Z-wave_log.txt](https://github.com/athombv/homey/files/888235/170331_Z-wave_log.txt)

Reboot (temporarely solved the issue).

**170401: Inability to control any Z-wave devices**
Trying to switch of my lights yesterday evening, none of the devices responded to the Homey flows (devices were responsive with direct association).

I noticed several security commands send to my battery powered Fibaro Motion Sensor Plus devices (node 19 and 20)... 

Z-wave log:
[170401_Z-wave log.txt](https://github.com/athombv/homey/files/888237/170401_Z-wave.log.txt)

manually waking up these devices cleared the lockup and devices became responsive again (never experienced this one pre-RC10)

**170404 Inability to control any Z-wave devices**
Today again my devices become unresponsive for commands send by Homey.

Homey indicates to become offline:
<img width="1169" alt="schermafbeelding 2017-04-02 om 09 24 33" src="https://cloud.githubusercontent.com/assets/17163431/24585418/15ebcae0-178a-11e7-9394-28c5819bc565.png">

Z-wave topology map remains blank
<img width="1129" alt="schermafbeelding 2017-04-02 om 09 34 59" src="https://cloud.githubusercontent.com/assets/17163431/24585421/1fc23cd4-178a-11e7-8652-ba4a20c6cad8.png">

Z-wave state:
> {"zw_state":{"currentProcess":"ProcessSendData","ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,30,31,37],"chip_type":5,"chip_version":0,"homeId":3756795748,"nodeId":1,"nvr":[1,2,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,20,16,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,212,14],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"5d3f09404014437e867567fbad4529c8","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes"],"currentCommand":"sendData"},"zw_ready":true,"_stateTimestamp":1491119571036}

Z-wave log:
[170402_Z-wave log.txt](https://github.com/athombv/homey/files/888240/170402_Z-wave.log.txt)

Homey log:
9E01D37C7D

Even after reboot, I get the offline error / Z-wave network map is not showing.

For me RC10 is a BIG step back compared to RC9 because Z-wave is completely locking up; did not occur on RC9 and below.

**Comment by mruiter** [comment]
I can confirm the same trouble

**Comment by djeskoswe** [comment]
same problem here , 

B257743D22

**Comment by TedTolboom** [comment]
And after another day in the office... again not responsive: 
- map remains empty: check
- Homey offline: check
- unable to control a Z-wave device through Homey (possible via direct association): check
- Reports still arriving: check
- stuck at "currentProcess: ProcessSendData"

Z-wave log: [170403_Z-wave log.txt](https://github.com/athombv/homey/files/891065/170403_Z-wave.log.txt)

Z-wave state:
> {"zw_state":{"currentProcess":"ProcessSendData","ver":5,"capabilities":{"api":"controller","timerSupported":false,"controllerType":"primary"},"nodes":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,30,31,37],"chip_type":5,"chip_version":0,"homeId":3756795748,"nodeId":1,"nvr":[1,2,0,21,13,27,120,32,1,0,32,0,64,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,20,16,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,212,14],"CONTROLLER_IS_SECONDARY":false,"CONTROLLER_ON_OTHER_NETWORK":false,"CONTROLLER_NODEID_SERVER_PRESENT":true,"CONTROLLER_IS_REAL_PRIMARY":true,"CONTROLLER_IS_SUC":true,"NO_NODES_INCUDED":false,"sucId":1,"powerLevel":0,"version":"Z-Wave 3.99","networkKey":"5d3f09404014437e867567fbad4529c8","methodsAsync":["factoryReset","addNodeAbort","removeNodeAbort","replaceFailedNodeAbort","sendData","isFailedNode","getFailedNodes"],"currentCommand":"sendData"},"zw_ready":true,"_stateTimestamp":1491245788838}

LOG: B0B97F8705

**Comment by jeroenvollenbrock** [comment]
It would help us a lot if you can verify if the lockups occur when data is received just before or or after a sendData is invoked.

**Comment by WeeJeWel** [comment]
This should be fixed in 1.2.0-rc.11.

**Comment by TedTolboom** [comment]
So feedback that I received is that fix in RC11 is not working...

@jeroenvollenbrock is above question still relevant? Does it help to investigate this issue?
Can you indicate how to get this information? Based on the current (Z-wave) logging, it is quite hard to pinpoint which command is creating the blockage.... 

Any guidance is appreciated so I can provide more feedback.

**Comment by jeroenvollenbrock** [comment]
A fix for the fix is included in 1.2.0-rc.12

**Comment by TedTolboom** [comment]
Let's hope that the fix for the fix fixes the issue(s caused by previous fixes)...

I hope you recognize that, based on the extremely short responses from Athom side, that I'm a bit sceptical if the fix included into RC12 is actually solving the one or two issues I described in possibly too many words...
