### ISSUE TITLE
HomeyGotchi aged the day after he died... 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1443]
**What is your Homey version (Settings → System)?**

App v 13.3.7 (What could possibly be the next version?) 

**What did you try to achieve?**
Forget about may failure to take care of HomeyGotchi ....

*Please include detailed steps how we can reproduce the issue*
Crack an egg... and forget to give affection !

**What was the result?**

![image](https://cloud.githubusercontent.com/assets/12412734/24611085/361ef7e0-1881-11e7-8c1b-49c41d87a825.png)

**What did you expect as result?**

Noting

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Thank you for reporting this issue! Unfortunately, the HomeyGotchi app will not be actively maintained in the future, so this issue will probably not be fixed. You can however delete your dead HomeyGotchi to prevent age notifications from showing up.

**Comment by swttt** [comment]
WHAATT! Not actively maintained? This must be a nightmare :(

**Comment by mruiter** [comment]
Whahaha , must also be a joke :) The app only got 1 day support

**Comment by TedTolboom** [comment]
Time for End Of Life transfers of Athom owned apps... 
I already proposed to take over the Greenwave app, to accelerate the release of PR's to this app (estimated waiting time now is 1-2 weeks). 

Any volunteers to provide some affection for the HomeyGotchi app?
