### ISSUE TITLE
[AppStore] Order of new Apps is incorrect.

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#1444]
When looking for new Apps in the AppStore ( https://apps.athom.com/search?order_by=created,desc&title=New ) the order isn't correct (Newest -> Oldest). E.g. the April-Fools-App "HomeyGotchi" can be found near the and of the list.

Please fix it, so that the newest released Apps show up first.

**Comment by Tweaqer** [comment]
![image](https://cloud.githubusercontent.com/assets/20989897/24649526/aa904344-1927-11e7-8d10-3ff09658ba44.png)
I was about to post this also: the new apps doesnt seem to be updated. HomeyGotchi shows up in updated but not under 'new'.

**Comment by OpenMindNL** [comment]
It's like this for more than a month already. I opened a forum-topic about it, but Athom doesn't seem to be interested.

**Comment by joachimroeleveld** [comment]
Thanks for noticing. This has now been fixed. 

@OpenMindNL, I wasn't aware of the forum topic, but Github is the place to go to for these kind of issues.

**Comment by OpenMindNL** [comment]
@joachimroeleveld Good to know. I understood that Github is for the software only.
