### ISSUE TITLE
Dutch : Zonnescherm sluiten

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey#1446]
**What is your Homey version (Settings → System)?**

V1.2rc10

**What did you try to achieve?**

Zonnescherm sluiten, dmv spraak

*Please include detailed steps how we can reproduce the issue*

Zeg tegen homey 'zonnescherm sluiten'

**What was the result?**

Spraak output : 'closing' zonnescherm

**What did you expect as result?**

dat homey zegt : Zonnescherm sluiten

**Any other remarks**

...

**Comment by Tweake** [comment]
Someone pointed this out to me on Monday, so I have fixed this already in the upcoming update. Thanks for creating the issue

**Comment by jaxc0402** [comment]
if i now ask 'zonnescherm sluiten' homey says "ik zal zonnescherm dichtdoen" and it closes all sun screens... could this also be regulated by asking " wil je alle zonneschermen sluiten" ??
