### ISSUE TITLE
Flow tokens are blocking view on autocomplete list

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1448]
**What is your Homey version (Settings → System)?**

1.2.0-rc10

**What did you try to achieve?**

Make a flow card with autocomplete list, and have 5 tokens

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The list is partly blocked by the tokens

**What did you expect as result?**

To have the pulldown list fully visible

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Can you post a screenshot?

**Comment by gruijter** [comment]
![2017-04-04 1](https://cloud.githubusercontent.com/assets/19174120/24673174/a5132c7e-1977-11e7-9519-34df0e8ed4bc.png)

**Comment by WeeJeWel** [comment]
Thanks! Fixed in v1.3.0
