### ISSUE TITLE
Trigger Card "Every Hour" start a second to early

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1449]
**What is your Homey version (Settings → System)?**

1.2.0 rc10

**What did you try to achieve?**

I created a koekoeksklok. Every hour I want to play a koekoeks-sample as many times as hour there are at that moment. Therefore I use the: 
![2017-04-05 07_24_46- 11 flow - chef](https://cloud.githubusercontent.com/assets/8507396/24691022/5fad8d64-19d1-11e7-9041-cc30702f5460.png)

**What was the result?**

For example, the time is: 18:00:00 .
The trigger was started at eg. 17:59:59.
I cant see the seconds counter, I guess it is 59 seconds.

**What did you expect as result?**

The trigger should start at eg. 18:00:00
Maybe issue #1423 is related.

**Comment by WeeJeWel** [comment]
Probably Homey's clock is correct but when you observe the value, there's a delay due to network traffic.

**Comment by bvdbos** [comment]
Don't think so, think it's the same issue as described here:
https://github.com/athombv/homey/issues/290#issuecomment-282212367

**Comment by WesRos** [comment]
I've made a Test Flow:
![image](https://cloud.githubusercontent.com/assets/8507396/24699982/1f8c6b68-19f6-11e7-9ef0-27562b95ebce.png)
This issue describes that I would receive a message: 11:59.

Now waiting for 12:00:00 
Remark: It couldn't be a delay. The Trigger starts to early.

**Comment by WesRos** [comment]
Yes, its exactly the same whats described in #290 .
