### ISSUE TITLE
Using the Time tag for calculation

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1450]
**What is your Homey version (Settings → System)?**

1.2.0 rc10

**What did you try to achieve?**

I want to calculate with the time tag, to get the HH, MM or SS.
In the logica action card: "calculate a value"

**What was the result?**

In every calculation the result is the number of hours: HH

eg. time = 14:31
 {{ [[homey:manager:cron|time]] / 3600 }}    result: 14
 {{ [[homey:manager:cron|time]] + 3600 }}    result: 14
 {{ [[homey:manager:cron|time]] / 100 }}    result: 14
 {{ [[homey:manager:cron|time]] * 6 }}    result: 14

**What did you expect as result?**

The value of the Tag Time is: the number of second from midnight

**Comment by WeeJeWel** [comment]
Calculating a 'string' type token uses a `parseInt()` method. You could write an app that provides the amount of seconds since midnight.
