### ISSUE TITLE
Unneccesary doubles in Send data queue,

### ISSUE THREAD

**Issue by priknr1** [athombv/homey#1451]
**What is your Homey version (Settings → System)?**
1.2.0-RC10

**What did you try to achieve?**
Sending a target temperature to a battery operated z-wave Thermostat.

*Please include detailed steps how we can reproduce the issue*
So I am writing this driver for my Horstmann SRT321 Z-wave battery operated Thermostat.
The device wakes up every 5 mins, and the desired target temperature is sent.

I change the target temperature to 18.0 degr, than to 19.0 degr. and than to 17.0 degr, All before the device wakes up.

**What was the result?**
As soon as the device wakes up, There are 3 lines send, 
setting the target to 18.0 degr, 
setting the target to 19.0 degr, 
setting the target to 17.0 degr, 

**What did you expect as result?**
Just send, setting the target to 17.0 degr

**Any other remarks**
This gives extra load in the z-wave network, which I think is unneccesary. 
But maybe in other cases this is desired functionality?

**Comment by WeeJeWel** [comment]
This cannot be fixed, only in the App itself. Homey has no way of what you're sending and if it's overwritten or not :)

**Comment by WeeJeWel** [comment]
You might want to contribute to https://github.com/athombv/node-homey-zwavedriver to implement this feature!
