### ISSUE TITLE
speech flow echo dot-homey

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1452]
**What is your Homey version (Settings → System)?**

rc10

**What did you try to achieve?**
in every speech flow (i changed my flows to something specific was said) that i do by alexa ask homey etc etc the flow runs perfectly,but afterwards i always get homey got your message but did not respond
*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

the flow runs perfect so homey got the right message through the dot,but the message afterwards is not needed

**Any other remarks**

some other users have the same

**Comment by WeeJeWel** [comment]
Can you post a screenshot of a Flow that does this?

**Comment by satbopper** [comment]
Emile thanks for the support,yes perhaps i am doing something wrong but those flows are always on this way and perfectly executed,no problem with that but always the did not respond message
![2017-04-05_14h20_33](https://cloud.githubusercontent.com/assets/17260928/24705371/dd09c5fe-1a0b-11e7-9466-0849ef2f1149.png)

**Comment by WeeJeWel** [comment]
You should add a 'Say' card in the 'then' column, with a response, e.g. 'OK'.

**Comment by satbopper** [comment]
thanks Emile i will test it today,if it works i close this issue

**Comment by satbopper** [comment]
Emile thanks your solution solved the case,closing this issue
