### ISSUE TITLE
Deleting devices does not remove icons from Zones&Devices area

### ISSUE THREAD

**Issue by jcastrol07** [athombv/homey#1453]
**What is your Homey version (Settings → System)?**

Version: 1.1.9

**What did you try to achieve?**
I removed a Z-Wave device from Homey but the icons remain in the Zones&Devices area and when I try to delete them with the x, the system asks me to push a button on the device..which cannot be done since the device has already been removed
Node iDs for those devices no longer exist on my network
[Screens devices removed.docx](https://github.com/athombv/homey/files/895878/Screens.devices.removed.docx)

*Please include detailed steps how we can reproduce the issue*
- Add a Zwave device
- Remove a Zwave device through the Zwave settings section

**What was the result?**

 - Icon for device remains in Zones and devices
- Try to delete the icon and prompts you to push a button on a device already removed
...

**What did you expect as result?**

That icon is removed when device is removed from Zwave settings or icon can be deleted when is not available through the zones&devices screen

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
If you click remove, and wait some time (60s to 90s), the device should delete itself. Can you try that?

**Comment by jcastrol07** [comment]
It worked
Thank you very much
