### ISSUE TITLE
KaKu devices get the same activation signals

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1454]
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Activate AGDR-3500 but my APA3-1500R had already the same signal ?

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The APA3-1500R goes on the AGDR-3500 remains offline

**What did you expect as result?**
That each KaKu device would receive an unique frequency signal.

**Any other remarks*
Generated signal with the remote now

**Comment by Arjanvde** [comment]
Isn't this the same as #754

**Comment by chrisboer** [comment]
Only with different device combinations, but also APA3-1500R is included indeed.

**Comment by bvdbos** [comment]
Did you also make sure the memory of your devices is empty before pairing, like the solution was for #754?

**Comment by chrisboer** [comment]
@bvdbos the KaKu devices where "new" out of the box so there should not be any signals in memory ;-) but after the app update checked again and all works as it should work. But homey goes offline for a minute or 2 when I activate these devices ? Then after 2 minutes homey reacts again. Log 3DCC30833A

**Comment by chrisboer** [comment]
Problem solved
