### ISSUE TITLE
Seep/awake in combination with Home/Away

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1455]
**What is your Homey version (Settings → System)?**

1.2.0

**What did you try to achieve?**

Set my status to at home when I'm sleeping.
Set my status to awake when I'm away

**What was the result?**

I've to set both statuses.

**What did you expect as result?**

When I'm out of the house, my sleep status should be awake.
When I'm sleeping my status shoud be at home

**Any other remarks**

"als je dit in de a.p.p. zegt dan kan Homey je status updaten" is pretty anoying

**Comment by JPe2** [comment]
the way it is now, allows you to make an alarm for sleep-walking.

**Comment by WeeJeWel** [comment]
You might be asleep somewhere else :-)
