### ISSUE TITLE
Test flow not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1456]
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24726393/827d5ca8-1a52-11e7-8095-04ce0e61424e.png)

*Please include detailed steps how we can reproduce the issue*
Test the flow if I can open the gate again ?

**What was the result?**
Does not work anymore ?

**What did you expect as result?**
Homey saying test

**Any other remarks**

...

**Comment by Dijker** [comment]
Duplicate Issue #1097

**Comment by chrisboer** [comment]
Pending release 1.3.0
