### ISSUE TITLE
KlikAanKlikuit (KaKu) - AWMR-230 - Not receiving signal from Homey

### ISSUE THREAD

**Issue by dENNtoet** [athombv/homey#1457]
**What is your Homey version (Settings → System)?**

1.2.0-RC10

**What did you try to achieve?**

I have the AWMR-230 built in as a switch for my kitchen lights. I have a flow that does the following: If I open the door (KaKu door switch) between 1:00AM and 6:00 and the sun isn't up yet -> Say: Goodmorning & Action: Turn on kitchen lights. 

This was working until 1-2 days ago. 

**What was the result?**

I came downstairs, opened the door. Homey says goodmorning (I had the app open while I opened the door because I wanted to troubleshoot what the issue was), I see the slider of my kitchen lights turn ON but the lights stayed off. 

**What did you expect as result?**

I expected the lights to be turned on.

**Any other remarks**

When I was flipping the switch manually in the app, the lights SOMETIMES turned on/off. So that was telling me that the signal didn't reach??? the switch. 

I have not rebooted my system yet since I wanted to make an issue / send logs first. 
The log has been send with ID: 7849A87B97

I made this issue because there was someone else who had the same problem on Slack.

**Comment by kritjuu** [comment]
After the update of rc10 again the 433 mhz range is very bad again. My doorbells are about 6 meters away and do not work anymore. With rc9 al worked very well.
I have the Action doorbell. It worked flawles on rc9 with te Alecto app. 
I made a complete restart of the Homey. The bell was back again for a short time.
But now connection lost again.

**Comment by dENNtoet** [comment]
When I got home yesterday i rebooted Homey and indeed it started to work again

**Comment by jeroenvollenbrock** [comment]
Does this still occur in 1.2.0 (non-RC)?

**Comment by dENNtoet** [comment]
Can't tell for now since i am rebooting Homey daily. I will turn off reboot schedule and let you know.

**Comment by dENNtoet** [comment]
Yes does still occur. Removed the reboot schedule yesterday, and today it isn't working anymore. If I trigger the slider manually it doesn't do anything.

Running: 1.2.2

**Comment by dENNtoet** [comment]
I did send the log over to Athom at 22:06

**Comment by dENNtoet** [comment]
It looks like more people are having issues after the KlikAanKlikUit update to 3.1.0
https://github.com/athombv/nl.klikaanklikuit/issues/18

**Comment by dENNtoet** [comment]
Haven't rebooted for a few days, seems to work steady now
