### ISSUE TITLE
Date variable in speech ending with period

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1460]
**What is your Homey version (Settings → System)?**

1.2.0rc10

**What did you try to achieve?**

Have Homey say the date when executing the wake-up flow by adding the @date variable to a speech action card

**What was the result?**

When there is a period (.) directly behind the @date variable tag Homey says "06-04-2017" instead of "6 April 2017"

**What did you expect as result?**

That the variable is spoken the same regardless of the contruction of the sentence it is in. I always end any speech with a period so sounds natural. As the date was at the end of the sentence the period was directly behind the tag in this case..

**Any other remarks**
I tried several other variables but all other don't seem to be affected by the period right after the tag. And it no big issue, the tone of speech doesn't seem to change anyway when putting a period after the date variable..

**Comment by WeeJeWel** [comment]
Hm, we can't actually fix this because this is how the Speech-to-text library Homey uses behaves.
