### ISSUE TITLE
API to control the WIFI

### ISSUE THREAD

**Issue by hulluperuna** [athombv/homey#1461]
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**
It would be great if the Homey could also support this by having an API which allows controlling the power on the WIFI.
I have chosen Homey tough because it supports all the low energy radio devices in the Homeautomation. Our router turns of the Wifi half the day to avoid the unnecessary radio traffic during the night.

*Please include detailed steps how we can reproduce the issue*
**What was the result?**
**What did you expect as result?**
he User Story would be.
I as a User want to be able to turn of the Wifi on my Homey for a number of hours , so that Homey turn on the Wifi after the time I have entered and I can configure it again.
Additionally Homey turns on the Wifi again if I reboot the homey to ensure that if something went wrong one get access fast again. To protect the Homey the wifi can not be turned off in the first hour after a reboot.

**Any other remarks**
I believe that would make homey more interesting and even lower its power consumption and making it more green!

**Comment by bvdbos** [comment]
What router do you have and does it have an API?

**Comment by hulluperuna** [comment]
Hi 

I have Fritz Box from AVM the model 7362 SL.
what API are you looking for?

Sami

**Comment by Dijker** [comment]
I guess you two are on different frequencies...
@hulluperuna  wants Homey to switch  it's own WIFI  off...
@bvdbos  asks for an API of a router and i think het expects that you want to control the WiFi of the router...

I don't think Athom will put effort in this as  Homey uses when idle 5 Watt (measured) with LEDs maximum and  approximately 1.6 - 2  Watt  idle without LED ring. 

But wait until Athom answers if this will be possible in an upcoming firmware or maybe when they release a UTP -Ethernet adapter for Homey to be wired to the network. 

imho Homey is pretty helpless without network.

**Comment by bvdbos** [comment]
Ah, yes. That could also be a way to view the question :-)

I think it's a valid question. If someone doesn't have any 433 devices, why not turn off 433-radio, same for 868, BT etc etc. Minimizing possible disturbance-sources. But turning off wifi will be hard, though running Homey without internet is possible, I can also imagine there's quite some apps (weather for example) which need internet. No wifi means also logging off from athom.com etc etc. Also: what happens if you want to connect to Homey at night when something happens? The connection to the router has to stay alive even when there's no internet...

**Comment by hulluperuna** [comment]
HI @bvdbos 

in our house Homey already has no network during the night and it works fine. I actually have not done anything  (configurations) with homey the last few weeks. Homey is setup and runs like a champion doing all the automations it is set up to do.
I described in my userstory that as a safety measure to turn the wifi after a reboot for 30 min. that way rebooting always gives one access to the Homey.

Sami

**Comment by WeeJeWel** [comment]
We will not add this functionality, because there are most likely not many users in a need for it.
