### ISSUE TITLE
RROD after z-wave issues, but still rebooting [1.2.0-rc.10]

### ISSUE THREAD

**Issue by runderkm** [athombv/homey#1462]
**What is your Homey version (Settings → System)?**

1.2.0-rc.10

**What did you try to achieve?**

I am trying to reboot Homey.

*Please include detailed steps how we can reproduce the issue*

Try to reboot Homey or pull-the-plug when Homey is non responsive. I was not able to find the exact conditions to reproduce, but I have the idea it has to do with adding and removing Z-wave devices, because the non-responsivenes happened a few times after adding and removing a Fibaro Motion Sensor and I one had the warning "Wacht totdat Z-wave klaar is" that would not resolve without PTP.

**What was the result?**

Since 1.2.0-rc.09 I am experiencing issues with Homey being non-responsive or getting off-line for no apparent reason or when adding or removing Z-wave devices. When PTP I get a RROD, but after waiting a while the RROD disappears and Homey restarts. Homey than seems to be very slow for a few minutes (not showing devices or lag in speech). 

I also tried to reboot Homey using the interface (Instellingen - Systeem - Opnieuw Opstarten) but this results in Homey getting non-responsive. 

...

**What did you expect as result?**

Homey rebooting normally
...

**Any other remarks**

...

**Comment by runderkm** [comment]
As of 1.2.0 the Z-wave issues seem to be resolved, but the RROD when rebooting is still there.

**Comment by jeroenvollenbrock** [comment]
Did 1.2.1 resolve the RROD as well?

**Comment by runderkm** [comment]
I am afraid the problem still persists with 1.2.1. After pulling the plug Homey shows the orange ring, after a few minutes the red ring, again after a few minutes the red ring dissapears and after more minutes waiting Homey is up-and-running again.

**Comment by jeroenvollenbrock** [comment]
Could you send me a log after this occurs? (settings->system->send log)

**Comment by runderkm** [comment]
Ok. Log sent: 9523DC3A6C

**Comment by runderkm** [comment]
And I don't know if they are related, but I am also experiencing issue #1383.

**Comment by jeroenvollenbrock** [comment]
This issue is caused by the time it takes to load your homey apps. How many apps do you have installed?

**Comment by runderkm** [comment]
I have 24 apps installed (all of which I actually use), see screenshot.
![apps](https://cloud.githubusercontent.com/assets/23473904/26192843/7c0063a2-3bb3-11e7-997a-1f9c69f421b0.png)

**Comment by runderkm** [comment]
Just installed 1.3.0-rc.9 and issue resolved.
