### ISSUE TITLE
Milight app crashes regularly since firmware update some months ago

### ISSUE THREAD

**Issue by Thorarin** [athombv/homey#1463]
**What is your Homey version (Settings → System)?**

1.2.0-rc10
MiLight 3.0.3

**What did you try to achieve?**

For the past two months or so, I've been having a lot of problems with the Homey Milight app crashing. The app itself hasn't received any significant updates, as far as I can see. Sentry logging was added 4 months ago, that's pretty much it, so I think some Homey firmware upgrade has to do with it.

**What was the result?**

The app crashes regularly; that is, every other day or so.
My lights (2 RGBW LED strips) are sensor controlled using Homey, so they may be switched on and off several times a day automatically. Therefore I'm not sure if the app crashes when they are being controlled, or even when the app is idle.

When the app crashes, very little information is given:

> Stack trace:
> 
> No stack trace available
> 
> Exit code: null
> Exit signal: SIGABRT

**What did you expect as result?**

A stable Milight app, like it used to be some few months ago.

**Comment by jeroenvollenbrock** [comment]
This happens when your homey runs out of memory and has nothing to do with the actual app. Could you send us a screenshot of your memory usage? (settings->system), and a log? (settings->system)

**Comment by Thorarin** [comment]
You are probably right about running out of memory, but I don't agree with it having nothing to do with the actual app. I took a screenshot of the memory usage after the app had been running for a while, and the MiLight app appears to have a memory leak:

![homey-memory-milight](https://cloud.githubusercontent.com/assets/1827726/25371447/1b88b9cc-2991-11e7-93fe-e92490f8f719.png)

Here it's using 62MB; just after restarting it takes up 27MB like most apps.

Log: 6C5D7E7839
(this includes a manual restart in the end, to verify the memory usage I mentioned above)

**Comment by Thorarin** [comment]
I've noticed that turning a single light off or on directly from a device card will increase app memory usage by around 2MB. When memory usage reaches somewhere between 60MB and 70MB, a GC cycle seems to be triggered. This lowers memory usage back down, but about 2-3MB of memory is not getting reclaimed every time this happens.

The numbers do vary somewhat; I've not done enough testing yet to determine exactly by how much.

**Comment by RobinBol** [comment]
Interesting issue, I have the same setup at home (1 RGB and 1 RGBW led strip), but I have no such memory issue. It is always around 22.5MB.

These are though issues to crack, so if you have more information please let me know!

**Comment by Thorarin** [comment]
Even just after restarting, it uses more than 22.5MB here 😦

My typical usage:
- I've upgraded to firmware 1.2.2 in the meantime
- Both LED strips are RGBW but we really only use white.
- The lights are typically switched on and off maybe 4-6 times a day, triggered by a luminescence sensor. 

So, nothing out of the ordinary that I can think of really. Just before posting here the memory usage had risen to 81MB. Other apps already show a little bit of memory leakage, but no more than 4MB per app, so at least 15 times lower than the Milight app.

**Comment by djeskoswe** [comment]
Just for info 

I'm using 2 WiFi boxes and 3 e24 and two led strips boxes and using 16 mb men

**Comment by RobinBol** [comment]
Hi @Thorarin , coming back to your memory issue, is this currently still an issue? As mentioned earlier I have never had these crashes myself, nor can I reproduce. We did make a lot of improvements over time to Homey itself which could help solve this. In Homey v1.5.3 for example, apps are now automatically restarted upon infrequent crashes (which means, the app should reboot when the memory leak occurred). Please let me know if this is solved, or still an issue for you. Otherwise I will close this issue in some time.

**Comment by Thorarin** [comment]
@RobinBol I'm not sure if the underlying issue is still there, exactly because of those automatic restarts. I don't know of any way to check if a restart occurred.

I have the feeling is occurs a lot less in any case; in 1.5.1 (?) the memory usage for all apps got almost halved for me. In that same update, it seems that the memory leak was also at least partially solved. Together with the automatic restarts it works a lot more reliably now.

(I still have regular issues with the lights not turning on, but I think it's related to reception of the RF signal from the WiFi bridge that has somehow gotten worse)
