### ISSUE TITLE
Custom room (zone) disappears after ptp Homey.

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1464]
**What is your Homey version (Settings → System)?**

1.20.0-rc10

**What did you try to achieve?**

restarting homey  with a ptp after she went dead playing with HomeGotchi. no rings.

*Please include detailed steps how we can reproduce the issue*

play with HomeyGotchi buttons in device

**What was the result?**

Homey lost connection , and after ptp a whole custom room disappeared , all device in that room are now on room Home
...

**What did you expect as result?**
that custom rooms doesn't disappear after a ptp
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
It could be that by pulling the plug, the settings weren't saved yet.
