### ISSUE TITLE
Missing TAG with value of Master volume, Music Volume, LED Brightness

### ISSUE THREAD

**Issue by nklerk** [athombv/homey#1465]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.2.0-rc.10

**What did you try to achieve?**

Create a flow where the Value of  volume, Music Volume, LED Brightness is used

**What was the result?**

There are no Volume TAGs available

**Comment by jeroenvollenbrock** [comment]
Do you mean a global tag, or a card-specific tag?

**Comment by nklerk** [comment]
Oh sorry, Global tag

**Comment by WeeJeWel** [comment]
This will be added in the next release!

**Comment by bvdbos** [comment]
Could be me but on 1.5.7 these tags don't show?

**Comment by WeeJeWel** [comment]
They do here:

![screen shot 2018-02-27 at 13 01 53](https://user-images.githubusercontent.com/319873/36727658-674a45c2-1bbe-11e8-8f47-33fd0287917a.png)

Can you confirm?

**Comment by bvdbos** [comment]
You're right... Overlooked those.. :)
