### ISSUE TITLE
Device name change not working in Insights and Flows

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1466]
**What is your Homey version (Settings → System)?**

1.2.0-rc.10

**What did you try to achieve?**
Change a name of a device

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
It was changed in the devicecard, but not in Insights and Flow
...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by Dijker** [comment]
Is this the Same as #1432 with the addition it also happens to the insights¿

**Comment by gruijter** [comment]
I think it is. Thanks, I'll close this one then.
