### ISSUE TITLE
Woonveilig app not showing up in flow menu

### ISSUE THREAD

**Issue by mvunen** [athombv/homey#147]
Woonveilig app can login after its updated to 1.0.5 but it doesn't show up in the flow editing menu. It is not possible to control the alarm.

Homey is up to date with version 0.8.17

**Comment by WeeJeWel** [comment]
Yes, this will be added (hopefully) in 0.8.18

**Comment by mvunen** [comment]
Woonveilig still doesn't show up in flows!
firmware: 0.8.20

**Comment by WeeJeWel** [comment]
I didn't make the `(hopefully)`. :)

**Comment by mvunen** [comment]
Still no Woonveilig in the flow editor! Can you fix this asap.... I know you guys have more high prio's. But this is an important thing to connect to.

**Comment by WeeJeWel** [comment]
It's planned for 0.8.23 :+1:
