### ISSUE TITLE
allow media through speaker

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1471]
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
play an audiobook through the Homey-speaker

*Please include detailed steps how we can reproduce the issue*
add audiobook from google to playlist. Try to play it through Homey's speaker

**What was the result?**
Not possible

**Any other remarks**
I assume this is a deliberate choice you guys made. Line-out works (well, didn't try but with the jack plugged in the error/warning isn't showing) so processing audio isn't an issue. Homey speaker is good enough for audiobooks/radio-1 so please give users their own choice to play audio through Homey speaker. I know voice-control won't probably work, I suggest disabeling the mic for the period media plays through the speaker. I used to wake up with radio-1 until last summer when media was removed, not possible anymore....

**Comment by matjaz** [comment]
👍

**Comment by jeroenvollenbrock** [comment]
This is indeed a design choice. The audio quality is poor and interferes with the speech detection, therefore we've decided not to make this possible (for now).

**Comment by zshh** [comment]
Hopefully this possibility can be added anyway.

**Comment by TimoSoof** [comment]
I have got a amplifier (PA 100V) in my house and in each room a speaker with volume control.
For a few years now.
At first I had it connected to a pc with clock software to play a song or a koekoek on the hour.
Also the doorbel and post was connected.
Then came Homey!
He speaks everything through the system, I love it.
Now there is finally a radio app 
https://forum.athom.com/discussion/4055/beta-streaming-radio-for-homey-music
But no sound to the jack plug witch is connected to my amplifier.

So please consider making the sound also on the jack.

**Comment by bvdbos** [comment]
@TimoSoof The output of media when choosing Homey as a device is the jack. This issue wants the opposite, use Homey's internal speaker as an output. If output through the jackplug doesn't work, make sure you set the volume both on media and on settings-volume...
