### ISSUE TITLE
radio-streams

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1478]
**What is your Homey version (Settings → System)?**
1.2.0

Summer of 2016 we lost the ability to listen to radio through Homey when media was deleted. Now we have music but no radio back. Would be logical to hook radio-stations to the sources-list of the music-gui...

**Comment by bvdbos** [comment]
Or do we have an option to hook into the music-queue? So then, in an app, we can choose which radiostations we want to show in the left column...

**Comment by JPe2** [comment]
Radio via Sonos favorites not found (Sonos Radio Favorites), are they planed to be implemented?

**Comment by JPe2** [comment]
Jan Pekkeriet zien we binnenkort ook de in Sonos favoriete radiostations als keuze mogelijkheid?

https://www.facebook.com/athomnl/posts/1614947695184495?comment_id=1617398694939395&reply_comment_id=1618619011484030

Homey, by Athom Goede suggestie, we gaan kijken of we dit kunnen toevoegen! ^Stefan

**Comment by bvdbos** [comment]
https://apps.athom.com/app/com.sasteren.radio
fixed this...
