### ISSUE TITLE
Global Tags in Logic Action Card

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1479]
**What is your Homey version (Settings → System)?**

1.2.0

**What did you try to achieve?**

Change a (app) variable through its global tag by dragging it into a logic action card.

**What was the result?**

A new variable was created with the name of the content of the global tag used.
In the example screen shot ( below) the Nest Protect Battery boolean was expected to be set by the action card but instead a new logic variable named 'false' (the state of the battery tag) was created and set.
This is also the case when using a global tag with a text or number variable.

**What did you expect as result?**

If you can drag a global tag into a parameter field you would expect that variable to be affected by the value. In Betterlogic you cannot drag an app's global tag into the parameter field, only in the value field, which I assume is what the built in logic is supposed to do as well.
It would, however, be cool if you can set global tags in logic cards too so you can set a parameter that may not have a card in the app itself... :)

**Any other remarks**

![logic action card](https://cloud.githubusercontent.com/assets/22442908/25099168/78fff390-23ab-11e7-8589-3ec1f013500b.png)

**Comment by caseda** [comment]
I'm not fully sure what you are trying to do.
but if you try to change the _state of a device_, which is determined by the _device itself_, then that is not possible, and most likely will never be able to be changed by the logic card (those are purely for the logic variables/values),
state of the device is completely something else then any logic variable or better logic variable
global tags are just values/states of devices/apps

if you want a logic variable/value have the same state as the device (beats me why you'ed want that, but hé who am i to judge) you can put the boolean global tag on the checkbox part.

**Comment by Phunkay** [comment]
Oh, I was hoping I could charge the battery like that...... 😄 

No, seriously I didn't encounter it when trying to set a battery flag but rather with a numeic tag. I just used this to show the problem. When I tried to set a numeric global tag by dragging it into the logic variable name field I ended up getting a new variable with the name of the value of the numeric tag with the corresponding value.
Now I understand I may have been trying something that shouldn't be possible but it shouldn't be possible to drag the tag into the field. In Better Logic you can't drop a global tag into the name field, only the value field.
On the other hand, I wouldn't mind being able to change the value of a global tag this way... 😜

**Comment by jeroenvollenbrock** [comment]
This is not a bug, you are using the _value_ of the token as variable name to change, which is indeed Yes/No.
