### ISSUE TITLE
Unable to send IR to TV

### ISSUE THREAD

**Issue by WernerHel** [athombv/homey#148]
I've added my IR Remote and I can choose to send a command in Flow, but my TV is not receiving any signal. I've tryied different signals like On/Off, or just 1,2,3 to choose the channel. Should this already work? Can anybody send something to his TV? Or is this not supported yet?

Werner

**Comment by Qx5** [comment]
Also mentioned in #135 
Believe they are working on it :+1:

**Comment by WernerHel** [comment]
I'm going to watch #135

**Comment by rhannink** [comment]
Hello,
I run firmware version 0.8.29 and it still does not work.
I learned the power button from my Sony remote. When I use this learned button to receive as IF, it works but when I use it as a THEN action, nothing happens.

**Comment by bvdbos** [comment]
How many repeats did you set it to use?

**Comment by rhannink** [comment]
I now try it with 10X repeat. What I see now is that the first time I start a flow, it almost never works, when i start the flow directly a second time it works almost ever time. Looks like homey is busy with something else the first time when i sent the IR command (timing problem).
I also tried to send the ir command 10x, the wait 1 or 2 secs and send again the Ir command one or 10x. But that doesn't work either.

Only thing which works now is running the flow 2x, then the second time it works ??????
