### ISSUE TITLE
[Z-Wave] UNencapsulated Notification CC not being recognized

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1480]
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
in this particular case, use Power Management Notifications as possible flow triggers.
But have seen more Notification CC being addressed as Unknown CC
0x7105000000ff080c0000 <= Notification, Power Management, Battery is charging
0x7105000000ff080d0000 <= Notification, Power Management, Battery is fully charged
0x7105000000ff08000000 <=  Notification, Power Management, Event inactive
Examples of known notifications ~all have 1 byte less at the end~, and are gotten in the security cc: (added 0x71 for the command class manually)
0x71 05000000ff090100 <= Notification, System, System hardware failure
0x71 05000000ff010300 <= Notification, Smoke Alarm, Smoke Alarm Test
0x71 05000000ff080a00 <= Notification, Power Management, Replace battery soon

**Please include detailed steps how we can reproduce the issue**
device with unknown Notifications => Aeotec Wallmote (ZW130)
                                                        => Aeotec Multi Sensor 6 (ZW100) (not in the list, have seen Unknown CC)
devices with known notifications => Fibaro Smoke Sensor z-wave plus (fgsd-002)

**What was the result?**
The notification is seen as unknown command class and thus not able to be used

**Any other remarks**
almost looks like aeotec related now.
but i think it has got more to do with encapsulated (security CC) being parsed differently

**EDIT: UPDATE**
it definitely is the parser, same device but included as secure does get the notification recognized  (added 0x71 for the command class manually):
0x71 05000000ff080c0000 <= Notification, Power Management, Battery is charging

**Comment by jeroenvollenbrock** [comment]
Could you please verify if this issue persists in Homey version 1.2.1?

**Comment by caseda** [comment]
Still persists in Homey 1.2.2:
Unsecuur:
Received application command for an unknown Command Class, data: 0x7105000000ff080c0000
Secuur:
Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff080c0000

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by caseda** [comment]
Confirmed fixed in 1.3

**Comment by caseda** [comment]
Re-open until 1.3 is in stable, so people can see its fixed
