### ISSUE TITLE
updating from 1.2.0 to 1.2.2 device not shown in  insights anymore and template not loading anymore

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1483]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

to check the temperature of the last 2 hours of an oregon scientific thermometer in insights after updating homey 

after a niight rest the device shows in flows and it works .

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

device didnt show op in insights while stille there in the device section with its actual temp , baro and hygro values.  the template can still be chosen but nothing happens.
...

**What did you expect as result?**

see the insight values of the device still present

**Any other remarks**
soft reboot didnt solve the problem

on 2 other homeys this problem didnt occur with oregon devices after updating from 1.2.0 to 1.2.2

**Please attach a Homey System log (Settings -> System -> Send Log)**
8E9DCCB068

**Comment by WeeJeWel** [comment]
Can you post a screenshot?

**Comment by nattlip** [comment]
we are now on 1.3.2 and it didnt occur in the recent updates
