### ISSUE TITLE
Insert TAG in flow not possible 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1485]
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25221132/5235a664-25b4-11e7-9dac-c1c3f00abfb9.png)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
I don't get a complete content overview from the field I try to drop the tag "vak"
...

**What did you expect as result?**
Be able to put tag "vak" behind tag "cijfer"
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by JPe2** [comment]
inserting Tags is very userUnfriendly, why not making the window larger when hovering-over, so you can easy drop the Tag where ever you want?

**Comment by WeeJeWel** [comment]
Doesn't dragging them between the words work? Follow the text cursor:

![untitled](https://cloud.githubusercontent.com/assets/319873/25344599/dfae4d00-2912-11e7-9c47-75748c0faec7.png)

**Comment by chrisboer** [comment]
No not possible (maybe this has also to do with 4k screens)

**Comment by chrisboer** [comment]
Still I can not insert tag gewicht between vak and cijfer I have to redo the whole item to be sure to do it in the right order so ... drag cijfer, then drag gewicht and then drag vak. Then add the text otherwise the box is not large enough and I cannot place any tag in it.

Cijfer Frank 
vak
 
gewicht
 
cijfer

**Comment by bm480** [comment]
I've suggested a solution in #1661.

**Comment by chrisboer** [comment]
Any update/progress on this ?

**Comment by WeeJeWel** [comment]
This won't be fixed due to the new Homey Smartphone App.

**Comment by chrisboer** [comment]
What is the relation to the Smartphone app ? Because I can not execute this on the Windows Desktop App
