### ISSUE TITLE
[AppStore] New Apps don't show

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1487]
I have the feeling new apps don't show again, just like #1444
For example the new app Image Grabber didnt show up?
Please fix

**Comment by 2benl** [comment]
Addition: The new apps get added at the bottom of the oversight of the new apps in stead of the front.

**Comment by DeefK** [comment]
New apps are added to recently updated. Not new.

**Comment by joachimroeleveld** [comment]
Well, this is a stubborn issue indeed. Apparently, the previous "fix" worked only for the apps submitted until then. It should now be working for new apps as well.
