### ISSUE TITLE
[Logic] Variable changed, numeric, 0 won't trigger

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1488]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Trigger a flow by changing a numeric value to 0 (it does trigger on everything > 0)

**Please include detailed steps how we can reproduce the issue**
Create a Number Logic with any value > 0,
Add it as "a variable has changed" trigger
Change the value to 0

**What was the result?**
flow is not triggered

**What did you expect as result?**
the flow triggering

**Comment by WeeJeWel** [comment]
Thanks for finding out, fixed!

**Comment by caseda** [comment]
Confirmed fixed in 1.3
