### ISSUE TITLE
How to Use Homey, Homey voice Commands List? (ASAP please)

### ISSUE THREAD

**Issue by pkonings** [athombv/homey#149]
Please supply a list of available pre-defined commands that can be accessed.

This will avoid a lot of confusion and annoyance.

For know a KISS list is good enough. Later on this can be beautified like Siri on ipad 's for example.

**Comment by elgenioNL** [comment]
https://jsfiddle.net/zz93y0ut/

**Comment by pkonings** [comment]
I have looked at the JSON within the fiddle and tested for example "Hey Homey, turn all lights on please?"

I am succesfully using Domoticz/RFXCom for over a year now with the _Android app Tasker with Google Voice_ commands, Therefor my assumption was that just a trigger-word or couple of words are picked up by Homey to do something. So saying "_lights on_" would be enough to let homey do its work, (looking at the JSON snippet below).
I tested this using the recommendation in #150 to setup a voice flow 'repeat what I said' which works quite well as homey repeats pretty well what I said.
However, ligths on seems to be the only thing which works. For example the trigger 'weather' or _"wat s the weather like"_ does not provide anything.

So I really wonder about homey 's current capabilities to receive and act upon voice commands. I refer also to make this at least transparant in a sequential continuous running log ( so we can at least anticipate/understand bugs etc.
 
JSON:
"homey:deviceclass:light": {
      "triggers": [{
        "id": "lights",
        "importance": 0.75,
        "triggers": {
          "en": ["lamp", "light", "lights", "lamps"],
          "nl": ["lamp", "licht", "lampen"]
        }
      }, {
        "id": "on",
        "importance": 0.1,
        "triggers": {
          "en": ["on"],
          "nl": ["aan", "aandoen"]
        }
      }, {
        "id": "off",
        "importance": 0.1,
        "triggers": {
          "en": ["off"],
          "nl": ["uit", "uitdoen"]
        }
      }, {
        "id": "dim",
        "importance": 0.1,
        "triggers": {
          "en": ["dim", "brightness"],
          "nl": ["dim", "helderheid"]
        }
      }, {
        "id": "percent",
        "importance": 0.1,
        "triggers": {
          "en": ["percent"],
          "nl": ["procent"]
        }
      }, {
        "id": "white",
        "importance": 0.25,
        "triggers": {
          "en": ["white"],
          "nl": ["wit"]
        }
      }, {
        "id": "red",
        "importance": 0.25,
        "triggers": {
          "en": ["red", "rat", "rats", "rhet", "ret", "read", "reads"],
          "nl": ["rood", "rode"]
        }
      }, {
        "id": "green",
        "importance": 0.25,
        "triggers": {
          "en": ["green"],
          "nl": ["groen"]
        }
      }, {
        "id": "blue",
        "importance": 0.25,
        "triggers": {
          "en": ["blue"],
          "nl": ["blauw"]
        }
      }, {
        "id": "yellow",
        "importance": 0.25,
        "triggers": {
          "en": ["yellow"],
          "nl": ["geel"]
        }
      }, {
        "id": "cyan",
        "importance": 0.25,
        "triggers": {
          "en": ["cyan", "scion"],
          "nl": ["cyaan"]
        }
      }, {
        "id": "magenta",
        "importance": 0.25,
        "triggers": {
          "en": ["magenta"],
          "nl": ["magenta"]
        }
      }, {
        "id": "pink",
        "importance": 0.25,
        "triggers": {
          "en": ["pink"],
          "nl": ["roze", "violet"]
        }
      }, {
        "id": "purple",
        "importance": 0.25,
        "triggers": {
          "en": ["purple"],
          "nl": ["paars", "indigo"]
        }
      }, {
        "id": "orange",
        "importance": 0.25,
        "triggers": {
          "en": ["orange"],
          "nl": ["oranje"]
        }
      }]
    },
