### ISSUE TITLE
All fibaro devices offline

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1490]
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
Rebooted homey because of homey not responding to "ok homey" now all fibaro devices are not available

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25276288/bf9198b8-2699-11e7-9abd-dff486cee47e.png)

**What was the result?**

...

**What did you expect as result?**
Fibaro devices to be enabled and available
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
B20480FEC8
...

**Comment by Dijker** [comment]
Did you wait untill the Fibaro App was stated after the restart? or dit it report a crash is you look at Settings - Apps?

**Comment by chrisboer** [comment]
Neither, Fibaro was updated to 1.4.2 and no devices where visible, I restarted Fibaro App but no result.
I rebooted homey and devices came back online. So I will close this issue as you probably have to reboot the system ones Fibaro App has been updated
