### ISSUE TITLE
RFID tags not recognised on 1.2.2

### ISSUE THREAD

**Issue by Yoda99** [athombv/homey#1493]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
use our RFID-badges to start a flow

*Please include detailed steps how we can reproduce the issue*
Try any RFID-tag or smartphone to return its tag id in a message

**What was the result?**
No tags recognised, no mesages sent or no flow triggered
...

**What did you expect as result?**
exptected to start a flow or to receive the tag id
...

**Any other remarks**
I tried with 5 different tags working yesterday on previous homey version. Tried with my smartphone.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
log id:
27F1376DE9 
...

**Comment by Dijker** [comment]
Tested it with my own Homey and 10 RFID tags on v1.2.2,  no problem here...

**Comment by Yoda99** [comment]
Rebooted homey and now they work.
