### ISSUE TITLE
Facebook messenger homey integration not working from Windows PC. ( Chrome, IE11 ) 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1494]
**What is your Homey version (Settings → System)?**

independent:  ( one on 1.2.2, other on 1.3.0-rc1 )
Chrome on Windows 10 Version 57.0.2987.133 (64-bit)  2 different systems
 AND also on Incognito Chrome browser 
 AND also in IE 11 

**What did you try to achieve?**
I tried to connect my homey to Facebook messenger. 

*Please include detailed steps how we can reproduce the issue*

open facebook messenger
go to homey+messenger
connect athom account

**What was the result?**
Athom logon => redirect to FB gives
Account Linking Failed 
![image](https://cloud.githubusercontent.com/assets/12412734/25295487/ef9b88bc-26e3-11e7-935b-30ab7201a3c9.png)

**What did you expect as result?**

a Select Homey reply. 

**Any other remarks**

from Andriod tablet and phone it works, but I always get connected to the first Homey (1.2.2 Dutch), never to the 1.3.0rc0 English as it tels the time in Dutch. 

**Please attach a Homey System log (Settings -> System -> Send Log)**

**Comment by WeeJeWel** [comment]
I cannot reproduce through messenger.com or facebook.com. What webpage are you chatting from? I don't recognise the screenshot.

**Comment by Dijker** [comment]
just https://www.facebook.com/ from Chrome or IE11 on Windows 10. 
@WeeJeWel see your PM on Slack with full screenshots....

**Comment by WeeJeWel** [comment]
This is an issue from Facebook. They redirect back to messenger.com (where you're not logged in), which is the URL Facebook sends to the Bot. I'm afraid there's nothing we can do to fix this.

I'll contact them to hopefully resolve this issue.

**Comment by WeeJeWel** [comment]
It has been reported here: https://developers.facebook.com/bugs/1877744792465286/

**Comment by Dijker** [comment]
Thanks, 
Staring logged in from the messenger site works ok.

**Comment by WeeJeWel** [comment]
This should work now :)

**Comment by Dijker** [comment]
Confirmed working !
Thanks!
