### ISSUE TITLE
[bug] Homey sleep & presence after reboot

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1495]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
Reboot homey and make use of the sleep and presence functionality
*Please include detailed steps how we can reproduce the issue*
After a reboot of homey all the variable of homey's sleep and presence are cleared. For some reason the presence won't work until you disable and enable the functionality in the app.
most of the sleep functionality won't work because there is no status set (true / false)

**What was the result?**
sleep & presence won't work properly
...

**What did you expect as result?**
both of them work after a reboot and keep the variables before rebooting
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
6797098A77
...

**Comment by WeeJeWel** [comment]
Fixed! The only case when the state should be lost if after a power-loss ánd the last state change was 30 minutes ago.
