### ISSUE TITLE
[Z-Wave] Stuck on removeNode loop

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1496]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Removing a Node

**Please include detailed steps how we can reproduce the issue**
I'm not fully sure what causes it to fail on the removeNode.
It just gets  stuck, and when trying to restart the removal it will restart,
but won't continue (wait for z-wave) if you then abort you get this in the log:
[2017-04-22T13:13:02.906Z] Command[204] start: removeNodeAbort
[2017-04-22T13:13:02.912Z] Command[204] end: removeNodeAbort
[2017-04-22T13:13:02.920Z] Command[205] start: removeNode
Aborting again (the remove node buttons is still active) it will abort but nothing happens:
[2017-04-22T13:18:51.466Z] Command[206] start: removeNodeAbort
[2017-04-22T13:18:51.471Z] Command[206] end: removeNodeAbort

**What was the result?**
Not able to remove, or add a new device, a reboot is needed to get it working again

**Any other remarks**
Has been there longer, but could (and still can) never reproduce the issue consistently.
Usually happens when trying to include -> remove -> include multiple times after each other
But always stuck on the Remove Node part `currentProcess: ProcessRemoveNode`

**Please attach a Homey System log (Settings -> System -> Send Log)**
0127016A35

**Comment by SkorpionNL** [comment]
I'm also experiencing this bug. Will make a log when it happens again.

**Comment by WeeJeWel** [comment]
I cannot reproduce. Is there a path that will lead to this behavior?

**Comment by caseda** [comment]
unfortunately i have not found a stable way of triggering the bug.

I only noticed it when including a node (or multiple(?)), shortly after delete a node again, and trying to re-include it (the process then keeps hanging on removal).

Looks like a bug that was there before, that the inclusion isn't fully finished in homey's core, but the removal is activated in the mean time (or the other way around)

can try to trigger it again and send a z-wave log if that could give more information

**Comment by SkorpionNL** [comment]
In my situation it happened when I tried to remove a node from my network in the Z-wave settings tab. The node wasn't coöperating very well so I had to activate the remove node option multiple times because the node wasn't found and therefor couldn't be removed. After X times remove node it happened.

**Comment by abaretta** [comment]
I am having a zwave 'add' loop it seems. Log BA69C8EDF6.

**Comment by DeefK** [comment]
Same problem just happend here with a fibaro motion sensor. It did not receive values. Tried to delete it pot not possible. Readded but now not receiving lux  and a senddata timeout FB6D0037BB

**Comment by caseda** [comment]
Actually I do think this issue is fixed with the change to the sync'ed data.
Have not had it at all when needing to re include all my devices last week (which also included a lot of deleting/resetting

@DeefK your issue is a completely (but also present) different issue
