### ISSUE TITLE
Update to 1.2.2 introduced error in Toon app

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#1499]
**What is your Homey version (Settings → System)?**
1.2.2 

**What did you try to achieve?**
Use Toon as before the firmware upgrade.

*Please include detailed steps how we can reproduce the issue*
Try to use Toon. Remove Toon app, install it and try to add Toon.

**What was the result?**
2 errors, see https://github.com/athombv/nl.eneco.toon/issues/20 and comments here: https://apps.athom.com/app/nl.eneco.toon

**What did you expect as result?**
Using Toon without interruption when Homey receives a firmware upgrade.

**Any other remarks**
On every firmware upgrade (I'm in the experimental channel) Toon gets disconnected, rebooting, disabling app etc. does not resolve that, removing the app, reinstalling and connecting Toon usually gets it working again, but not this time.

**Please attach a Homey System log (Settings -> System -> Send Log)**
NA.

**Comment by jeroenvollenbrock** [comment]
This error was introduced due to changes in the Toon API, not the homey firmware upgrade. I'm closing this issue because there already is an issue in the Toon App repository.

**Comment by daneedk** [comment]
Nice coincidence. Would also be help full to add this information to the thread in the Toon App repository. 
Luckily all other apps connecting to Toon don't seem to be affected so it's only my Homey that suffers from the API change...
