### ISSUE TITLE
BeNext Plug-in Dimmer EU adding fails with errormessage: [object Object]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#15]
Step by step I try to add a BeNext Plug-in Dimmer EU, and everything goes well up to the point that it's looking for the zwave device and Homey is in inclusion mode. I now press zwave include button 2 seconds for the BeNext, and now after a while I get an external pop-up, AND in the Homey dialog with title " Follow the instructies..." I get the detailed message "An error occured adding your device. [object Object].  Very informative. ;-)

**Comment by athomey** [comment]
To be safe, I did a factory reset of the BeNext. (Even though the Vera said it was excluded.) That seemed to help. Now I got it included in Homey. I don't know if that helped, but your fallback exceptions/errordialogs leave room for improvement. :-)  So, that problem still exists.

**Comment by ocatie** [comment]
The Error object was emptied somewhere. Fixed in next update.
