### ISSUE TITLE
Questions to Ask Homey and How To correct pronunciation and interpretation mistakes?

### ISSUE THREAD

**Issue by pkonings** [athombv/homey#150]
I assume Homey analyses voice commands to process.

In case this fails for whatever reason I currently observe the light ring pulses but no feedback or (corrective) action is observable. 

How can we now (or in future) correct (manually or by voice) mis-interpreted words and commands?

**Comment by Qx5** [comment]
For starters I found it useful to create a flow that repeats what you say. Makes it easier to pinpoint problems.

When: You said anything
then: Voice{You said: <text>}

**Comment by JohanKuster** [comment]
Please read this also [113](https://github.com/athombv/homey/issues/113)

**Comment by JohanKuster** [comment]
and this: [149](https://github.com/athombv/homey/issues/149)

**Comment by pkonings** [comment]
Qx5 advice works indeed :)
![image](https://cloud.githubusercontent.com/assets/10164680/13008474/cce9bd28-d196-11e5-91f5-8a225f68199b.png)

**Comment by jeroenvollenbrock** [comment]
You can assign a notification sound yourself by installing the soundboard app and creating a flow that plays a sound when Homey starts listening. Leaving the ticket open as enhancement request for a default setting to do this.
