### ISSUE TITLE
Eneco Toon no connection

### ISSUE THREAD

**Issue by DeefK** [athombv/homey#1503]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

Control the Eneco Toon thermostat trough the app or webpage.

**What was the result?**

No connection with Eneco Toon thermostat

**What did you expect as result?**

Control the Eneco Thermostat

**Any other remarks**

it worked on 1.1.9? and when updated to 1.2.x it stopped working. Restarting the app does not work

**Comment by bvdbos** [comment]
bug #1499  I guess?

**Comment by bvdbos** [comment]
Also see the Toon - Repo : https://github.com/athombv/nl.eneco.toon/issues/20#issuecomment-296638765

**Comment by DeefK** [comment]
Ok. Closing this one and moving to #1499
