### ISSUE TITLE
Home Easy HE432EU and HE300EU can not be added 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1504]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Add deleted Home easy device again HE432EU 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
I press the 4 button on the remote but no reaction
also the HE300EU remote is not recognised but devices already added are still working.

**What did you expect as result?**
Home easy devices to be able to add

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
2C2B533532
...

**Comment by Dijker** [comment]
Did you try to restart bthe 433 controller?

**Comment by chrisboer** [comment]
Reboot and PTP nothing works

**Comment by chrisboer** [comment]
I removed all home easy devices and setup them completely new. Now it works but this is offcourse not the way to do things.

**Comment by chrisboer** [comment]
Solved with app update.
