### ISSUE TITLE
Unable to install app with invalid 433 signals

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#1507]
**What is your Homey version (Settings → System)?**

1.3.0-RC2

**What did you try to achieve?**

Install com.weather-sensors (v1.0.0) from the app store

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
unable to install
![2017-04-25](https://cloud.githubusercontent.com/assets/19174120/25393699/7609ade8-29dc-11e7-9d52-61c58709319e.png)

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Dijker** [comment]
Same here,. But installed on 1.2.2 without a problem

**Comment by bvdbos** [comment]
Think this belongs in homey-dp?

**Comment by gruijter** [comment]
Probably. Is there a way how to move it there?

**Comment by bvdbos** [comment]
Don't know, perhaps just close this one and file a new one on on the correct repo?

**Comment by jeroenvollenbrock** [comment]
This issue should now be resolved
