### ISSUE TITLE
IFTTT Settings

### ISSUE THREAD

**Issue by soler2000** [athombv/homey#151]
IFTTT settings are not maintained or editable after first set in the setting panel of Homey

**Comment by soler2000** [comment]
removing the app and reinstalling seamed to work to show the data again, but after retuning to the settings again the data disappears.  

Homey seams to be ok with sending the request to IFTTT but not able to receive the request

**Comment by edtst** [comment]
Same here, Homey does not register any event. I used Maker and a json as specified

**Comment by peaoo** [comment]
Same here, I made a video:
IFTTT Recipe: Android Wear Do-Button -> WebRequest
Homey Flow: WebRequest -> Switch Light on
It doesn't work (with any other IFTTT trigger its the same). But I noticed, that all IFTTT Settings in Homey vanish after a WebRequest is done. A reboot make them show again.
You can see this in the Video, hope this helps:
https://youtu.be/88EokowhkiY
Homey V: 0.8.17
IFTTT V: 1.0.2

**Comment by RobinBol** [comment]
Hi guys, sorry you are having issues with the IFTTT app. It seems something broke precisely after I tested and uploaded the app. I asked Emile about this, and he mentioned that there are some related bugs fixed in the upcoming versions! If you are still having issues on 0.8.19 please let me know.

**Comment by soler2000** [comment]
This is now working correctly
