### ISSUE TITLE
Enhancement: Show overview of missing cards in a flow

### ISSUE THREAD

**Issue by JosStultjens** [athombv/homey#1510]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
In some of my flows there is an indicator that there are cards missing,

**What did you expect as result?**
I'd like to see which cards are missing so I can take corrective actions.

**Any other remarks**
I did not have a backup or screendumps of my flows. Apparently something changed and I have to digg into my memory to determine what is missing. If Homey knows that there are missing cards, maybe Homey can tell me which cards are missing in the flow. This will make it much easier to determine what was changed and what corrective actions  need to be taken.

**Comment by WeeJeWel** [comment]
Added in v1.3.0

![screen shot 2017-05-10 at 16 16 13](https://cloud.githubusercontent.com/assets/319873/25903187/0193a3b2-359c-11e7-9544-dbad999edcbd.png)

Note that Homey only has very user-unfriendly ID's in memory, and no nice text to show.

**Comment by JosStultjens** [comment]
Is there no reference at all to what  kind of card is missing? e.g. what type of equipment it was or what the card was intended for e.g. switch on (missing) equipment

**Comment by WeeJeWel** [comment]
Unfortunately, no. This data is all stored in the app or device, which is unavailable when this card is displayed.

**Comment by JosStultjens** [comment]
Pity,
Then I need to make backups of my flows more often. 
Unfortunately the flow backup app (written by Serge Regoor) exports the data to a single line json file. This is usefull for importing it again after a Homey reset, but not for viewing a single flow to see what has changed.
So I guess I need to make a screendump archive of my flows. Or do you see another option?

**Comment by WeeJeWel** [comment]
Try a tool called a json beautifyer to make the json more readable.

**Comment by JosStultjens** [comment]
I tried the https://jsonformatter.org/ site.
Now I am able to read the json file. It shows me the following of an existing device:
   "actions": [
      {
        "id": "on",
        "uri": "homey:device:59d94d70-8dfa-43eb-8540-740fc6d60983",
        "args": {},
        "droptoken": false,
        "delay": {
          "number": "0",
          "multiplier": "1"
        },
        "duration": false
      }
    ]
At least now I am able to determine what kind of action was intended by this card. I cannot see what device it was, but this will point me in the right direction.
Best option to me still will be a screendump archive of the flows.

**Comment by Dijker** [comment]
Hi @WeeJeWel  Nice start!
Just a Question:  When is the flow-card missing?

 I guess: 
- The App Crashed, 
- The App isn't installed anymore,
- or the device is removed ? ....
Th last one is the most difficult as information is missing.

For the others: 
Some App-Specific Cards have an "readable" URI, like : "uri":  "homey:app:net.i-dev.betterlogic", 
Other like your example refer an Device ID , and that Device (also broken in the Zones )  have an readable uri referring to an app/type 

    "id":  "22353f8d-321e-4e97-a695-7817ee254d3e",
    "name":  "Afstandsbediening",
    "driver":  {
                   "uri":  "homey:app:nl.klikaanklikuit",
                   "id":  "AYCT-102",
Would it be possible to show some direct or indirect information on the broken cards to inform what App of Device is missing? 
If a card, hove over or pop-up debug shows: pls re-install (homey:app:) net.i-dev.betterlogic I know enough....
If it Refers Missing Device: (ID) => Name Afstandsbediening - App nl.klikaanklikuit - ID AYCT-102
this will be helpfully also...

Maybe put deleted Devices for some time in a graveyard to keep the information and be able to refer to or  re-add them! (and make an un-delete or Re-pair function or wizard ??? )

just my thoughts.......

**Comment by WeeJeWel** [comment]
Yep, the card is broken when the app is not running (so crashed, disabled or uninstalled). In the case of devices, when the device is removed.

Adding a title with the ID is a good idea, I will do that, thanks!
