### ISSUE TITLE
Homey Speech not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1512]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Set the lights on in the livingroom

*Please include detailed steps how we can reproduce the issue*
https://athomcommunity.slack.com/files/chrisboer/F54MP9ZAR/speech_not_working.mp4

**What was the result?**
No reaction to any speech both from IOS App as well as directly to Homey 
...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
EE0AF192FA

...

**Comment by JosStultjens** [comment]
I have the same issue since yesterday evening.

See Athom Status page.
Speech to Text:  Possible degraded performance due to issues at one of our partners.

**Comment by JosStultjens** [comment]
No message anymore on Athom status page ( https://status.athom.com ). So issue seems to be resolved. 
At the moment I'm not at home so I cannot verify myself.

**Comment by Wijkie76** [comment]
Same issue here. Stopped working wednesday evening. A 1.2.2 glitch? Voice thru App isn't working either, although I see the command being received by Homey. Via http://<homey-ip>/speech-input the command  is executed. Seems to be a bug in the speech-to-txt interface. I don't see any errors though in my logger.

**Comment by WeeJeWel** [comment]
We had some downtime on the STT server. If it still occurs, please report back.
