### ISSUE TITLE
[1.2.2][Z-wave] Z-wave not starting, error: timeout

### ISSUE THREAD

**Issue by CliffBroeren** [athombv/homey#1513]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

Look at my homey and saw all the z-wave devices was not ready 

**What was the result?**

It was dark in my house, I can't switch any light on. 

**What did you expect as result?**

I hoped homey never fails 

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

6FAAC64DD9

<img width="1280" alt="schermafbeelding 2017-04-26 om 19 05 49" src="https://cloud.githubusercontent.com/assets/28061478/25447472/9a995c24-2ab5-11e7-93fb-c67be9c520cf.png">

<img width="1280" alt="schermafbeelding 2017-04-26 om 19 05 52" src="https://cloud.githubusercontent.com/assets/28061478/25447471/9a991e62-2ab5-11e7-9926-f57b74216497.png">

 

https://forum.athom.com/discussion/3096/geen-z-wave-na-herstarten-homey#latest
(its not only myself)

**Comment by TedTolboom** [comment]
Additional notes to complement @CliffBroeren:

Both issues have been contained by the following actions:
- disabling the Z-wave apps
- PTP for more then 15 minutes
- restart of Homey
- starting the Z-wave apps one by one...

No other measures, restart of Homey or normal PTP were effective.

**Comment by TedTolboom** [comment]
Third occurence (reported): https://forum.athom.com/discussion/3100/z-wave-does-not-work-anymore awaiting log-code

**Comment by rtnartna** [comment]
88504FE843

Don't know for sure if the crash log was sent at the right moment.

**Comment by rtnartna** [comment]
The issue was solved by taking the actions @TedTolboom described above.

**Comment by rtnartna** [comment]
Problem occurred again. Report 361ACA6BD3

**Comment by chrisboer** [comment]
Same issue 38EC979DBD

**Comment by Keverjeroen** [comment]
Same issue, but not after a restart of Homey. This morning Z-wave wasn't working anymore. Log: 0CE7433F11

**Comment by jeroenvollenbrock** [comment]
Has this issue been resolved with Homey version 1.3.0-rc.7?

**Comment by chrisboer** [comment]
@jeroenvollenbrock still no issues with 1.3.0-rc7 but only one day live so give it some days

**Comment by Keverjeroen** [comment]
I had the problem only once in 1.2.2, but no problems so far in rc7..
