### ISSUE TITLE
Slow, unreliable and inconsistent Z-Wave behaviour

### ISSUE THREAD

**Issue by ClemensLR** [athombv/homey#1516]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
Execute existing working Z-Wave flows

*Please include detailed steps how we can reproduce the issue*
Executing existing flows with Fibaro switches and Aeotec smart dimmer

**What was the result?**
Slow response, unreliable and inconsistent behaviour, e.g. reported status in GUI not consistent with actual status
...

**What did you expect as result?**
Reliable flows like they behaved before 1.2.x

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
41CE78CA8E

![example](https://cloud.githubusercontent.com/assets/22732033/25559751/2c859340-2d41-11e7-82b6-42d723ed33ec.JPG)

...

**Comment by ClemensLR** [comment]
Unsuccessfully tried the approach by disabling Z-Wave apps, PTP, wait 15 min, etc.

**Comment by TedTolboom** [comment]
@ClemensLR what is the error shown when you hover your mouse pointer over the red exclamation marks?

In addition, can you post (as txt file) your Z-wave log at the moment you executed this flow?

**Comment by ClemensLR** [comment]
"Timeout"

[Flow_Log.txt](https://github.com/athombv/homey/files/966805/Flow_Log.txt)

**Comment by TedTolboom** [comment]
@clemensLR based on your description I was expecting the "timeout" as error message; double with issue #1469

Athom mentioned yesterday to look into this issue in detail next week.

**Comment by ClemensLR** [comment]
Hope it will be fixed soon. It's more than disappointing that a major release causes rather severe problems in basic Z-Wave behaviour. Ok, releases will always have bugs, but one would expect basic standard behaviour not to be broken in this way.

**Comment by djeskoswe** [comment]
haven't seen this before but today i got timeout on some lights ,  log = C565CD0169

**Comment by jaimevisser** [comment]
My homey performance is also a lot worse since 1.2 with nodes randomly taking up to 30 seconds to toggle on/off.

**Comment by CyberSponk** [comment]
Got the same like @jaimevisser and others here. Updated Homey Yesterday to 1.2.2, also Fibaro to 1.4.3 and Aetoec to 1.4.0.

**Comment by jeroenvollenbrock** [comment]
Has this issue been resolved with 1.3.0-rc.7?

**Comment by ClemensLR** [comment]
Did some testing with two flows (on/off) with a set of z-wave devices (see picture at top of thread). Improved results, but not without faults. Best test results show lightning fast never seen before performance. A lot of attempts were fine and improved, but still quite a few tests can take up to 30 seconds to terminate of which some still end successfully and some time out with a danger sign.
Good vs delayed = 70% vs 30%. <5% resulted in time out.
