### ISSUE TITLE
Activating screensaver does not override running animation.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1519]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

- Create, register and run an animation with a very long (many minutes) or an infinite duration.
- Now there's a flow that selects a LED-ring screensaver for a few seconds to inform me about something, and then it switches back to the default screensaver.

**What was the result?**

The informing screensaver does not show as long as the animation is running. 

**What did you expect as result?**

I expected the screensaver to stop the animation.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by caseda** [comment]
Quote explanation of what a Screensaver is:
> Homey has an LED Ring, consisting of 24 RGB LED's. You can control Homey's LED Ring to give visual feedback when your app is doing something. 
> It is also possible to take control of the LED Ring when Homey is **idling**, this is called a screensaver.

So when an animation is being played, homey is not idling,
but i do understand what you are trying to achieve here

**Comment by OpenMindNL** [comment]
Hmmm.... I forgot about the real purpose of a screensaver... even when Homey's screensavers are in fact screenkillers because the LEDs are only saved when they are off. :grin:

However... The importnant issue here is that Homey's animations will never (seem to) stop when they have a very long or infinite duration. They are only interupted by a animation.stop() or by starting another animation.

**Comment by WeeJeWel** [comment]
This is intended behavior. Animations take priority over screensavers, or when started after another animation.

**Comment by OpenMindNL** [comment]
But still... infinite animations will take over the LED-ring FOREVER.

**Comment by WeeJeWel** [comment]
I think this should be only possible if an app does this. And it's the responsibility of the app to stop the animation in time.

**Comment by OpenMindNL** [comment]
But if an app allows the user to set a custom created animation to a very long duration, this will also be a problem. The user has to be aware that he/she has to stop the animation manually when othr LED-ring info is needed.

**Comment by OpenMindNL** [comment]
I think an animation should be stopped automaticaly whenever an animation OR a screensaver is started manualy or from a flow. I all other cases the current behavior would be ok.

**Comment by WeeJeWel** [comment]
Animations of the same priority are played sorted by date, so that already happens. Screensavers will stay screensavers.
