### ISSUE TITLE
After update, wrong message "Setup is in progress" when clicking " Visit My Athom" (cosmetic, but confusing)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#152]
After factory reset (but think at any first start). You connect WIFI. Homey downloads update. Reboots. Website says "Your Homey is starting" (((it should indicate how long this takes, took MUCH longer than I thought 10+ minutes, I almost pulled the plug))), **after a while it says "All done! Visit My Athom" which is a hyperlink, but if you click the hyperlink it present, it incorrectly states "Setup is in progress, do you really want to abort?"** for some reason the state of the page/website still is in this mode, but the message " All done!"  says otherwise. This is a bug and confusing for new users.  I tried prior sequence twice to be sure, and can confirm that in Chrome 48 this was twice the case, so no mistake at my end (I think and hope, heh, heh...). :-)

See screenshot: https://files.slack.com/files-tmb/T04E9KJ7T-F0M3N9CJV-d279d5407a/pasted_image_at_2016_02_12_12_38_pm_480.png

**Comment by Fire69** [comment]
I had this too. 
Clicked the link, got that message, canceled. Clicked the link again, got the message, canceled. Clicked the link a third time, no more message and it opened My Athom. 
So I guess something was still running in the background.

**Comment by athomey** [comment]
Ah, that **means the message below is shown too soon**. :-)  Very well. **Nice repro**. Thx Fire69 for your addition.

**Comment by WeeJeWel** [comment]
Fixed in the new setup.
