### ISSUE TITLE
[Flow]Multiple flow triggers (branch style), Fail after first step

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1520]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Create a flow that triggers multiple flows (like a tree branch), which these flows continue onto next flows, all having a delay.
IE:
```
Flow 1 -> Flow 2.1 -> Flow 2.2 -> Flow 2.3
       -> Flow 3.1 -> Flow 3.2 -> Flow 3.3
       -> Flow 4.1 -> Flow 4.2 -> Flow 4.3
```

Flow 1 triggers 2.1, 3.1 and 4.1
Flow 2.1 triggers 2.2, 2.2 triggers 2.3
Flow 3.1 triggers 3.2, etc.

**Please include detailed steps how we can reproduce the issue**
Create flows like in the example above

**What was the result?**
Flow 1 triggers flows 2.1, 3.1 and 4.1 correctly.
After that only flows in line 2 triggers
the flows in line 3 and line 4 don't trigger anymore.

**What did you expect as result?**
That all flows get activated

**Any other remarks**
All flows trigger on a delay of 300 seconds.
Have tried using different delays to see if the flow triggers get overwritten somehow, but the result is the same.
Current situation consists of 5 branches with the 1st branch being 6 steps long (this one continues)
and the other 4 branches having 5 steps (these fail after the first step)
Tonight i will try with less branches (2), but i don't think it will change much (will edit the post with the extra information)

**Please attach a Homey System log (Settings -> System -> Send Log)**
AE713FB826
Timestamp: flow 1 triggers on 5:10 which then continues on with delays of 300 seconds (+1 second for each extra branch, done as test)

**Comment by WeeJeWel** [comment]
I hate to say this, but, can you post screenshots of all the Flows? :)

**Comment by caseda** [comment]
all of them? that's a lot of images 😅 but sure

**Comment by WeeJeWel** [comment]
I see you're using 'Schakel een Flow in', but you really want to use 'Activeer een Flow' 👍

**Comment by caseda** [comment]
:see_no_evil:

**Comment by fvhuizen** [comment]
**Activeer een flow** and **schakel een flow in** are not the most clear names for a flow and seems to be some kind of the same. I suggest to consider to replace **activeer** with **start**

**Comment by WeeJeWel** [comment]
Good suggestion! Fixed
