### ISSUE TITLE
confirmation in chrome-testbox instead of mobile

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1523]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
turn lights on

*Please include detailed steps how we can reproduce the issue*
Ask Homey to turn lights on through mobile voice. The confirmationquestion isn't sent to the mobile or Homey but instead appears in a chrome-dialog:
![2017-05-03 06_57_22-homey speech input](https://cloud.githubusercontent.com/assets/1064079/25648621/2c5a9318-2fce-11e7-8fe1-9076c763ca5e.png)

**What did you expect as result?**
return the confirmation-question to the mobile.

**Any other remarks**
At the same time, Homey doesn't react to speech anymore (not even OK Homey). Seems like the mic-process has crashed? Inputting speech through speech-input does work. Replying to the question "wil je echt dat ik alle lampen aanzet" has to be done through speech-input then. That's probably bug #1383 which more and more people are suffering from. 

**Please attach a Homey System log (Settings -> System -> Send Log)**
Memory is fine and I am connected to cloud... log F601944DAC
![2017-05-03 07_04_11- 626 settings - homey](https://cloud.githubusercontent.com/assets/1064079/25648672/c30aecc2-2fce-11e7-9135-1cc91857188e.png)

**Comment by WeeJeWel** [comment]
Actually, this dialog box is entirely for debugging purposes, and the question is also sent to mobile devices.

If you don't get the question on the smartphone, please create a separate issue describing that.
