### ISSUE TITLE
allow language to be set by action or speech-object

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1526]
**What is your Homey version (Settings → System)?**
1.2.2 Dutch

**What did you try to achieve?**
Though Homey is set to Dutch, in the morning I want to hear English news and a quote of the day like in:
https://forum.athom.com/discussion/3135/trump-quotes-app

*Please include detailed steps how we can reproduce the issue*
Have Homey speak some English text while she's set to Dutch.

**What was the result?**
Garbage...

**What would solve this?**
Would be nice if a flowcard could set the output to another language so you can have an action:
* set language to English
* output quote of the day
* set language to Dutch

The card would list the languages of the installed voices. You could even have a second flowcard to choose the voice for the language.

Another option would be that the app-developer would be able to set the language per speechobject which is outputted (like the output-device can be set):
Homey.manager('speech-output').say(__(NewsItem[i]),{ session: speech.session }, { language: dutch});

Of course there would have to be a fallback for the cases where the voices for a certain language were deleted after creating the flow or installing the app...

If you want to set Homey to another language at the moment, a reboot is required. Don't know if that's just because of the interface or also really needed for the voice output?

**Comment by OpenMindNL** [comment]
I agree! This would be a great option!

**Comment by WeeJeWel** [comment]
Sorry, this is a wontfix. It would require the user to download two (different) voices, which takes up too much disk space and just is extremely complex.

**Comment by bvdbos** [comment]
Well, diskspace is not the problem, my guess is most people have two voices from different languages already, ample space. 
![2017-05-10 13_37_20- 640 settings - homey](https://cloud.githubusercontent.com/assets/1064079/25896797/e4eb4e60-3585-11e7-875f-6b2e9d530f56.png)

Don't known about the inner complexity of using another voice though...

**Comment by OpenMindNL** [comment]
I can understand that this would be extremely difficult when it would be about speech-text recognition... but this is about text-to-speech. This is something that every computer can do offline.

**Comment by jghaanstra** [comment]
Any chance this can be reconsidered?

I can hardly believe any user running out of free space. Is this really to only valid reason to reject this feature request?

**Comment by WeeJeWel** [comment]
That's absolutely not the only reason. The complexity of a multi-language system is really horrible, and having two voices in memory will consume much RAM as well.

**Comment by bvdbos** [comment]
As real-time voice isn't necessary (my usecase is about news, who cares for a small delay...), maybe we could relay this to a third-party service? 
https://responsivevoice.org/free-text-to-speech-mp3-audio-files/
