### ISSUE TITLE
scrollbar in left window (f.e. devicewindow) desktopapp is disappearing

### ISSUE THREAD

**Issue by Posbank** [athombv/homey#1529]
Using Homey v1.2.2 and desktopapp at laptop with W10.
Following is happening, also in older SW-versions (text copied from Homey forum issue).

Not complaining but asking for a solution for my (only my?) following problem using the Homey desktop app.
When creating or editing flows I need to scroll through the options in the (most left) systemcolumn with all commands, devices etc. But every time again after making the first choice the (very tiny) scrollbar at that left column has gone and cannot be reproduced without a total restart of the app. This already happens since the desktop app had been released. It's very tiring because it costs so much time to create just one flow.
What is going wrong? Something with the laptop I am using? The app itself? Is this a known issue? I could not find anything about it at the forum. By the way, the same fenomenon is existing using the Google Chrome method.

EDIT: exactly the same problem, missing/disappearing scrollbar, is happening in the new music-chapter. So it's not possible to scroll through my Sonos-playlists.

See also screendumps scroll1 (bar disappeared) and scroll2 (bar still existing at first use of menu)

![scroll1](https://cloud.githubusercontent.com/assets/19623022/25785215/5850a060-337b-11e7-9b71-4841aef14d59.JPG)
![scroll2](https://cloud.githubusercontent.com/assets/19623022/25785220/68748704-337b-11e7-9c16-97c5a53a5a23.JPG)

**Comment by ICT22** [comment]
I can confirm this issue; especially in Chrome on a tablet where it is impossible to reach the devices for a flow.

**Comment by Posbank** [comment]
Thanks for quick response, very much appreciated. I would like to underline that the situation as described in my situation is not happening at a tablet with Chrome but at a standard Windows-laptop using the Athom desktop app.

**Comment by Posbank** [comment]
Thanks for quick response, very much appreciated. I would like to underline that the situation as described in my situation is not happening at a tablet with Chrome but at a standard Windows-laptop using the Athom desktop app.

**Comment by Posbank** [comment]
Problem with scrollbar seems to be solved since v 1.3 RC9!
