### ISSUE TITLE
Device screen: fading through red when close device-popup before it's fully loaded

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#153]
When opening the settings of a device and closing it immediatly it fades through red:

![image](https://cloud.githubusercontent.com/assets/15232724/13006105/d29f7f7e-d186-11e5-8dad-8d773e327cc5.png)

**Comment by irritanterik** [comment]
Also: pop-under

**Comment by WeeJeWel** [comment]
Oops! Fixed in 0.8.18

**Comment by irritanterik** [comment]
you're fast!
Op 12 feb. 2016 13:08 schreef "Emile Nijssen" <notifications@github.com>:
