### ISSUE TITLE
Homey presence on Iphone not working 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1531]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
See that I come home

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
App is online on the Iphone but Homey does not detect I am arriving home.
...

**What did you expect as result?**

...

**Any other remarks**
I use apple IOS

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
Do you have a working mobile data subscription, have the home detection settings in the app set-up properly, and allowed location access to the homey app?

**Comment by bvdbos** [comment]
One more thing to add: re-setting the perimeter (as in changing its settings) might work...

**Comment by laurenssss** [comment]
jeroen for me all answers I can confirm with yes, but no reliable presence detection (every now and then sporadically it sees me coming home, but that's once every 2 weeks or something, I'm home a bit more often :) )

**Comment by jeroenvollenbrock** [comment]
@laurenssss Do you use android or iOS?

**Comment by laurenssss** [comment]
@jeroenvollenbrock iOS 10

**Comment by ICT22** [comment]
+1 Same experience, I've had it recognise myself once in the last three weeks.

**Comment by robiebab** [comment]
I have the same thing, i need to disable and enable "use home detection" to make it work again

**Comment by chrisboer** [comment]
Same issues still with homey 1.3.0 rc7

**Comment by chrisboer** [comment]
With homey 1.3.0 rc12 (latest final release) it works again.
