### ISSUE TITLE
Homey does not see Brel remote for pairing brel motor for blinds

### ISSUE THREAD

**Issue by wendan20** [athombv/homey#1533]
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

A little while ago I tested the Brel app on one of my blinds with a Brel motor. This worked! I could pair the motor with homey by pushing the remote which is also paired to the blind.
I know have 8 blinds with brel motors and I started to paired them all. But know Homey does not respond to the remote to pair the blind. I used two remotes tos test it, but both do not work!

I am using the latest Brel app version 1.2.0

Hope someone can help!

Grtz

**Comment by BasKiers** [comment]
Hi, 

Thanks for the bug report. This issue should be fixed some time ago in version 1.3.0 of the app. If you still experience problems please re-open this issue or create a new one.

Regards,
Bas
