### ISSUE TITLE
Nest permission

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1535]
**What is your Homey version (Settings → System)?**

1.2.2 (Nest 2.4.0)

**What did you try to achieve?**

As Homey wasn't able to control my Nest thermostat I restarted the app after which I needed to renew the permissions which didn't work. All goes well until you press Accept on the Works with Nest permission page but getting back Homey's Nest setting it's stuck with a spinning cog.

**What was the result?**

Homey doesn't seem to process the permission granted by Nest. Each permission request adds another Athom entry to the Works with Nest list, so all seems fine on the Nest side.

**What did you expect as result?**

Full access to my Nest appliances like before. :)

**Any other remarks**

I suspected the two-factor authentication I had recently activated had something to do with the initial problem of not being able to control my thermostat. But with two-factor off the problem remains.

**Please attach a Homey System log (Settings -> System -> Send Log)**

3235ED07F7

**Comment by Phunkay** [comment]
Okay, so I tried again tonight and now all seems fine. No idea if it fixed itself or somebody did something...

**Comment by bvdbos** [comment]
Multiple people confirmed this works now. @Phunkay Can you close this bug?
