### ISSUE TITLE
No flow trigger with energy tag in Logica

### ISSUE THREAD

**Issue by Reemster** [athombv/homey#1537]
![energie kleiner dan 200](https://cloud.githubusercontent.com/assets/19860405/26013611/81ea2202-3759-11e7-8ad1-d3bb548dd535.jpg)
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

Trigger a flow, when the energy is lower then 200

**What was the result?**

no trigger. And the energy is 135.32.
...

**What did you expect as result?**

a flow trigger, and in this case every min.
...

**Any other remarks**

no

**Please attach a Homey System log (Settings -> System -> Send Log)**

142618bcbe

**Comment by Reemster** [comment]
is this fixt? or..

**Comment by Dijker** [comment]
I guess it is fixed, 
I did something like that and it works for me!

![image](https://user-images.githubusercontent.com/12412734/28694091-1862aac4-7328-11e7-8bc2-f3e558da012b.png)

Homey version 1.3.2 
Don't know if that didn't work before but imho this is comparable....
