### ISSUE TITLE
"night-time" is only between 0.00 and 3.00

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1538]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Run flows during daytime

*Please include detailed steps how we can reproduce the issue*
tested using:
![2017-05-11 17_01_44- 642 flow - homey](https://cloud.githubusercontent.com/assets/1064079/26023165/6ec74d50-37b6-11e7-9ce8-6c541ab6fcc6.png)
![2017-05-11 17_01_57- 642 flow - homey](https://cloud.githubusercontent.com/assets/1064079/26023166/71af6f84-37b6-11e7-9f24-26ec19008c3b.png)

**What was the result?**
Daytime is between 3.00 and 0.00, Night-time is between 0.00 and 3.00
![2017-05-13 08_18_54-google photos - google drive](https://cloud.githubusercontent.com/assets/1064079/26023174/b06720dc-37b6-11e7-9ae9-61273f16fb00.png)

**What did you expect as result?**
Daytime is between sunrise and sunset

**Comment by Tweake** [comment]
Thanks for reporting the issue. We were using some astronomical definition of nighttime which was not very practical. I have made an update so nighttime will be the period between dusk and dawn, in accordance to the Merriam-Webster dictionary definition of nighttime. 

The fix will be included in the next build

**Comment by RobertMe** [comment]
Seems like it's still broken, or at least doesn't match sunup/sundown (screenshot taken at about 22:30 yesterday):
![880fc650-7b94-4269-9035-c18187d63f16](https://user-images.githubusercontent.com/1102763/28176523-144bdfc2-67f8-11e7-858b-85f976e790bd.png)
