### ISSUE TITLE
Non-helpful message "noNode" when adding BeNext zwave dimmer in 0.8.17

### ISSUE THREAD

**Issue by athomey** [athombv/homey#154]
I did: Factory reset, erase data. Add Fibaro Wallplug, which was succes. Add BeNext Dimmer, Homey responds with **pop-up with "noNode" and no explanation what it means and no suggestion what to do** to fix it. This should be more user-friendly, especially foor newbies and (first) impression of stability/robustness/professional level of Homey.

See screenshot: https://files.slack.com/files-tmb/T04E9KJ7T-F0M3S8JQ7-a359f53257/pasted_image_at_2016_02_12_01_15_pm_720.png

**Comment by ocatie** [comment]
That means no node presented itself during the pairing. Refer to the device manual on how to active learnmode on the dimmer.

I'll look into making the message more user friendly.

**Comment by athomey** [comment]
Thx for both!
