### ISSUE TITLE
Scrolling in insights is stuttering

### ISSUE THREAD

**Issue by camilleversteeg** [athombv/homey#1540]
**What is your Homey version (Settings → System)?**
Homey Firmware Version: 1.2.2

**What did you try to achieve?**
Scrolling using the gestures on my touchpad (two fingers) gives a stuttering effect. Up & Down. Using the scrollbar works. I'm using an Macbook Air.

*Please include detailed steps how we can reproduce the issue*
Go to insights
Move your cursor the to left pane
Scroll using touchpad

**What was the result?**

Scrolling is impossible. Due to the stuttering it takes ages to find the device.

**What did you expect as result?**

Being able to scroll

**Any other remarks**

Look at the attached video.

**Please attach a Homey System log (Settings -> System -> Send Log)**

...
[Bug_Homey.mov.zip](https://github.com/athombv/homey/files/998725/Bug_Homey.mov.zip)

**Comment by jaimevisser** [comment]
I had this too, but didn't notice it on the 1.3.0 rc versions anymore.
