### ISSUE TITLE
Spotify for Sonos app crashes regularly and playlists do not show

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/homey#1541]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

I'm trying to get my Spotify playlists into Homey Music.

**What was the result?**
My playlists do not get loaded into Homey Music. The Spotify app crashes very often while doing nothing.

Error when crashed:

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGABRT
...

**What did you expect as result?**
To have my Spotify playlists in Homey
...

**Any other remarks**
I successfully connected my Spotify Premium account to Homey.
I added my Spotify playlist to my Sonos Favourites
Spotify for Sonos app version 1.0.6
Sonos app version 2.3.0
Searching and playing music from Spotify works till app crashes.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
E290902645
...

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
