### ISSUE TITLE
Philips hue - > card -> helderheid over tijd -> variable bug

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1542]
**What is your Homey version (Settings → System)?**
RC7 1.3.0

**What did you try to achieve?**
i tryed to set a philips hue bulb with the card - helderheid over tijd  using a variable. the variable value was 0.9, with no effect. after setting the variable to 90 i saw that the bulb was burning
*Please include detailed steps how we can reproduce the issue*
philips hue  bulb
creeate a flow with  helderheid over tijd
create a variable with the value 0.9

**What was the result?**
no light
...

**What did you expect as result?**
90% light on the philips hue bulb
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
That specific slider has a 0-100 range.
