### ISSUE TITLE
[old app] Delete "Wekker" in app not working

### ISSUE THREAD

**Issue by priknr1** [athombv/homey#1545]
**What is your Homey version (Settings → System)?**

1.3.0 RC7

**What did you try to achieve?**
Delete "wekker" in app

*Please include detailed steps how we can reproduce the issue*
I added a "wekke"r, And set it, just to test, was hoping it would go off on my phone.
(  maybe something to build)

Now pressing the "x" to delete the "Wekker" but it is staying.

**What was the result?**
"Wekker" Stays

**What did you expect as result?**

Wekker would be removed

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
Works for me for an alarm which didn't go off yet...

**Comment by priknr1** [comment]
Just tried adding a new one, set it an hour from now. But also doesn't  delete.   Now I have 2 of them that wont go. Thanks ;) :P

**Comment by bvdbos** [comment]
Also for an alarm which did go off, synched instantly between phone and UI in chrome...

**Comment by caseda** [comment]
maybe its a good information thing to know what kind of device you are using 😸

**Comment by Inversion-NL** [comment]
Just successfully delete an alarm which went off yesterday at 20:30.
Android phone was used

**Comment by bvdbos** [comment]
working ok on app version 2.3.3 build 69 (android) and fw 1.3.0 rc7

**Comment by priknr1** [comment]
not working for me  on app version 2.3.3 build 69 (android) and fw 1.3.0 rc7.  (Android 5.1.1 phone)

**Comment by caseda** [comment]
Just tested here on Android 7.0, and works just fine
App version 2.3.3

**Comment by Tweake** [comment]
I'm not yet able to reproduce this. What mobile app version are you using? And could you provide some details about what happens when you click on the X? Do you get a confirmation screen for example?

**Comment by priknr1** [comment]
`not working for me on app version 2.3.3 build 69 (android) and fw 1.3.0 rc7. (Android 5.1.1 phone)`

Nothing happens at all. So when I press X,  it is as if I haven't pressed anything at all

**Comment by bvdbos** [comment]
For me it works on android 6, depends on android 5 then? Which version of chrome-browser on android do you have? I use chrome 58.0.3029.83 on android 6.0.1

**Comment by priknr1** [comment]
But the problem is not in chrome on android, but in app on android
but to answer your question: Version 58.0.3029.83 too

**Comment by Inversion-NL** [comment]
Working for me on Android 7.1.2 with Chrome 58.0.3029.83 and Android app version 2.3.3 build 69 on a Nexus 6

**Comment by Dijker** [comment]
I was surprised by this issue as I played withe creating and removing Alarms and didn't experience it.
using: Samsung Galaxy TAB tablet, Samsung Galaxy S7 edges phone 

Until I setup a second mobile, good old HTC one and I couldn't remove an alarm that I created! 

I wanted to make a report here with a screenshot but after testing again it works again. 

I guess it is sometimes an issue, but can't point at it for now.

**Comment by priknr1** [comment]
I tried it several times, and with some restarts of my phone in between. Never works here.

For me it is not an issue, I am not going to use it, as long as I am not able to make the alarm go off on my phone in stead of the homey. Just wanted to let athom know about it.

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue, so I assume it has been fixed some time ago. If it persists, please let me know.
