### ISSUE TITLE
Maintaining actions in Flow columns DAN / ANDERS is difficult

### ISSUE THREAD

**Issue by sossienl** [athombv/homey#1547]
**What is your Homey version (Settings → System)?**

1.3.0 RC 7

**What did you try to achieve?**

I have 4 actions in DAN and 4 in ANDERS. To put the 4th in ANDERS was very difficult as it was trying to put it in the DAN piece every time. Eventually I got lucky.

But now I want to remove the first action in DAN, and it doesn't scoll to the top enough to reach the remove button

**What was the result?**

Cannot easily add multiple actions in ANDERS
Cannot remove the first action in DAN or ANDERS if there are more than 3 actions

**What did you expect as result?**

Better overall scrolling experience, better way to maintain the actions in both columns

**Any other remarks**
I don't think that my log will show anything

**Please attach a Homey System log (Settings -> System -> Send Log)**

F678D23541

**Comment by robiebab** [comment]
you have to click on the + sign otherwise it won't work:P

**Comment by sossienl** [comment]
Attached a video to explain the problem, as it seems like it's not clear enough. This video shows the issue of removing the first action in the "DAN" column if there are more than 3 actions.

As file type mp4 is not allowed, a link:  https://sossienl.stackstorage.com/s/65yboXU8BZVSNmo

**Comment by sossienl** [comment]
Attached a video to explain the second problem; Adding a new action in the "ANDERS" column. It activates the "DAN" column, and doesn't allow me to add it to the "ANDERS" column

As file type mp4 is not allowed, a link: https://sossienl.stackstorage.com/s/sXzrg40PxAk4bAU

**Comment by robiebab** [comment]
weird i only have the bug with scrolling to top ( probleem 1) i think it can be handy to give more information about :
version app
version os

**Comment by sossienl** [comment]
Version app: 1.0.3
Version OS: macOS Sierra 10.12.5 (16F73), 13,3-inch (2560 x 1600)

**Comment by Rocodamelshe** [comment]
Same here.

**Comment by WeeJeWel** [comment]
This is fixed in the next release
