### ISSUE TITLE
Apps start crashing one by one

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1548]
**What is your Homey version (Settings → System)?**
v1.3.0 rc7

**What did you try to achieve?**
Nothing

*Please include detailed steps how we can reproduce the issue*
Checked why Sonos speakers were not visable anymore and saw that app was crashed

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**What was the result?**

...

**What did you expect as result?**
All working

Magister was already crashed so disabled that one

**Any other remarks**
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/26124923/93ab338a-3a80-11e7-9ff9-780f575bf339.png)

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
B733A1A3A8

**Comment by jeroenvollenbrock** [comment]
Your homey ran out of memory, and started shutting down apps. How many apps do you currently have installed?

**Comment by chrisboer** [comment]
29 apps

**Comment by gruijter** [comment]
I have also made an issue for this in the DP section. First time I made an issue of this was in December 2016 ( #1147 ), but it seems this problem has been ignored by Athom too long now. The stability of Homey is really affected by apps crashing due to memory issues, while there is no indication what is causing the memory issues.

**Comment by bvdbos** [comment]
It seems to me your common factor is your Magistar-app?

> @gruiter I can not help it but since I disabled Magister I don't have any problems with my homey
10:53
so this issue I logged on github
Homey 1.2.2Stack trace:
No stack trace available
Exit code: null
Exit signal: SIGKILL (edited)
10:54
https://github.com/gruijter/com.gruijter.magister/issues/7
GitHub
Magister crashed · Issue #7 · gruijter/com.gruijter.magister
Homey 1.2.2 Stack trace: No stack trace available Exit code: null Exit signal: SIGKILL
10:54
is for me probably the memory leak
10:54
I don't see any changes in memory nor is text to speech disformed (edited)
10:55
so now 3 days testing and still no reboot what so ever

**Comment by gruijter** [comment]
No, I had the magister app uninstalled the past week, and still apps are shutting down because of memory. So there must be other factors involved besides the magister app....

**Comment by chrisboer** [comment]
again I had issues again with magister beta now again disabled and homey works again so will keep track on this

**Comment by chrisboer** [comment]
No issues anymore will test magister app now to see if the problem is solved
