### ISSUE TITLE
Flow card selection-descriptions are not updated after renaming

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1550]
**What is your Homey version (Settings → System)?**

1.3.0-rc7

**What did you try to achieve?**

I'm working on an app that offers the user a few presets for their settings. 
The names for these presets can be changed whenever wanted/needed, but their internal ID always stays the same.
These presets can be selected in a flow action-card... works fine... so far so good.
Now the users will change one or two names for the presets (Settings page), including the one that is selected in the flow card.

Still nothing wrong... user returns to the flow-editor and opens the flow that contains the flow card with the preset selection.

**What was the result?**

The preset still works as it should (test button) because the ID didn't change, but the old name for the preset is still visible in the flow card's selection field.
The user first has to access the autocomplete pull-down and select the preset from the (updated) list again to see the new name in the card-field.

**What did you expect as result?**

To see the new/changed name in the flow card immediatly.

**Any other remarks**

It's a minor bug that doesn't disturb the flows, but it can be confusing.

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Unfortunately this cannot be fixed, because the autocomplete value has no 'live' value.
