### ISSUE TITLE
Change status from Aan het slapen  to Thuis.

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#1551]
**What is your Homey version (Settings → System)?**

x1.2.2

**What did you try to achieve?**
Setting the status tags Using the inbuild "aanwezigheid" 
Ref. https://www.athom.com/nl/support/KB000044/ from card (i)
Slapen commando’s
De andere manier om de slaap status aan te passen is om het tegen Homey te zeggen, bijvoorbeeld met "goede morgen" of "welterusten". Als je dit via de mobiele app of Facebook Messenger zegt weet Homey van welke gebruiker de slaap status gewijzigd moet worden. 

*Please include detailed steps how we can reproduce the issue*
Say "Goedemorgen" into your iPhone (Homey app)

**What was the result?**
Homey said "Goedemorgen. Heb je goed geslapen?"

...

**What did you expect as result?**
Change in the tags from _Aan het slapen_ to _Thuis_ (screenshot of unchanging status)

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
F81BA33C37
![screenshot 2017-05-17 at 09 13 21](https://cloud.githubusercontent.com/assets/24312420/26142508/218a0388-3ae1-11e7-809c-6e051415c174.png)

...

**Comment by bvdbos** [comment]
you can also sleep somewhere else, no way on knowing that for Homey if you talk to the phone...

**Comment by Povlov** [comment]
Is that so? 
The fact that the phone is connected to the same router as homey is knowledge our little friend can have. If however you are right and Homey cannot know, what does the support text try to convey to me?
_Als je dit via de mobiele app of Facebook Messenger zegt weet Homey van welke gebruiker de slaap status gewijzigd moet worden._
Which _slaap status_ then, will it actually change?

**Comment by Tweake** [comment]
There is no relation between a user's sleep status and a user's presence status in Homey. If you are at home your presence status should already report you as being at home (when the smartphone app is installed). Whether a user is sleeping or not has no impact on that status. Sleep is managed separately, as detailed in the Knowledge Base article you already referenced.

**Comment by Povlov** [comment]
I think the description of the functionality more then suggests that the person "gaat slapen" state is actually in the home. When I am @ another location , I do not want the vacation status that I may have set to be undone when the homey app receives a "gaan slapen" state.  

Slapen
Wanneer je gaat slapen wil je dat jouw huis zich daaraan aanpast. Dat is precies waar de slaap status voor is. Slaap status kan bijvoorbeeld gebruikt worden als Flow trigger om te zorgen dat de gordijnen dicht zijn, het licht uit staat en de thermostaat een graadje lager gezet wordt.
