### ISSUE TITLE
Feature Request - Also add the nice label for installed apps through developter tools in settings>apps

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1552]
In firmware 1.3 rc7 a nice label is added when a app is installed through beta or alpha channel of the appstore. Would be nice if this is also available when installed through developer tools. for instance a "DEV" label.

![image](https://cloud.githubusercontent.com/assets/752857/26142867/c03392be-3ae2-11e7-83ed-627a1f7b4a89.png)

**Comment by caseda** [comment]
Those already say "installed via developer tools"?

**Comment by spoelly** [comment]
That's correct, but with the label it's more visable and in the same line the rest.

**Comment by WeeJeWel** [comment]
We'll keep it this way :)
