### ISSUE TITLE
To many apps?

### ISSUE THREAD

**Issue by Leliekevertje** [athombv/homey#1553]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

**What did you try to achieve?**

After the version update I got this message.
![image](https://cloud.githubusercontent.com/assets/19484735/26144948/faf096a6-3aea-11e7-870a-90b1ac301e95.png)

**What was the result?**
Dissapointment on my behalf :)

**What did you expect as result?**
I do not expect Homey to "not or slower work" with this amount of apps installed. Having said that, Homey should work allways regardless of the number of apps installed.

**Any other remarks**
1.17 GB free of 1.64 GB

**Please attach a Homey System log (Settings -> System -> Send Log)**

**Comment by spoelly** [comment]
it's just a message wroking fine over here with 26 apps installed

**Comment by Huizertaatje** [comment]
Heb er ook last sinds de nieuwe Homey versie. Had maar 22 app's op draaien, nu 6 weggegooid en hij geeft nog steeds de melding. Het interne geheugen van 511 mb blijkt dus veel te klein te zijn, en nu al helemaal als alleen Homey er 81 mb van gebruikt.

**Comment by caseda** [comment]
let me quote what it says:

> Door het aantal geïnstalleerde apps (##), kan Homey langzaam of niet meer werken.

then i want to lay the point onto 1 word in that sentence, the most important word of that sentence: 
**KAN**
just saying, it COULD happen, doesn't mean it is the case, some people have 45+ apps, and their homey still runs just fine.

**Comment by jeroenvollenbrock** [comment]
We have changed the message to be a bit less dramatic in rc8

**Comment by Leliekevertje** [comment]
Hi Jeroen, 

Thanks for the quick reply and making the message less dramatic, but what I don't understand is why the message is adjusted. Now I don't know if I my homey works fine or not so the message is in my opinion meaningless but please correct me if I'm wrong.

Either Homey works fine and the message is not necessary or Homey can have a problem with too many installed apps. If that's the case, I expect Athom will adjust Homey's software so the problem does not occure anymore.

At this moment, I think my homey works fine but who knows. Therefore I like to know what the symptoms are, how to I recognize if this message/problem is true or not. 

Keep up the good work, I really glad with Homey and it's features!

**Comment by bvdbos** [comment]
With a lot of apps and/or devices Homey will react slower but if there's really a problem you'll notice this by crashing apps... I have >35 apps running and no problems. Every situation is different, also because this is also dependent on the kind of apps (memory leaks, techniques used etc etc).
