### ISSUE TITLE
Add Enable/Disable button on top Flow editor

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1556]
**What is your Homey version (Settings → System)?**
1.3.0-rc7

**What did you try to achieve?**
Edited an disabled flow, wanted to enable

*Please include detailed steps how we can reproduce the issue*
use the Flow editor

**What was the result?**
had to click 3 or 4 times, 
Open Flow Browser - Open Folder - Right-click the disabled flow .... Enable .

**What did you expect as result?**
Just a button on top 
![image](https://cloud.githubusercontent.com/assets/12412734/26156562/fe4adbaa-3b16-11e7-95d2-7168dd093304.png)

Somewhere her up
(yes I like the new Flow broswer but mis the checkboxes.)

**Comment by WeeJeWel** [comment]
Wontfix (also due to the new Homey Smartphone App)
