### ISSUE TITLE
Remove an Alarm pops-up with unnecessary information (The page at http://1....)

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1557]
**What is your Homey version (Settings → System)?**
Homey 1.3.0-rc7 / App 2.3.3 build 69

**What did you try to achieve?**
Remove an Alarm pops-up with unnecessary information (The page at http://1....)

*Please include detailed steps how we can reproduce the issue*
Remove an alarm from the App on a mobile device.

**What was the result?**
![image](https://cloud.githubusercontent.com/assets/12412734/26161941/a21fa72a-3b25-11e7-9f9e-cfc25350a440.png)

**What did you expect as result?**
only the App Msg, not the browser popup.

**Comment by joachimroeleveld** [comment]
What exactly do you mean with "only the App Msg"? The popup is there to not accidentally remove the alarm. I agree the title is a bit irrelevant but it is triggered from a webview which is why it looks like that.

**Comment by Dijker** [comment]
For course I still want the confirmation from the app or the webpage, but the header or title of the msg "The page at http://1...."  Is imho annoying and redundant.... 
I understand the way pop-up's work on webpages, but I didn't expect them I the app and  expected  it to be easy to prevent these in the app. 
If that isn't easy possible:  so be it.

**Comment by joachimroeleveld** [comment]
Agreed. In the end this view will be implemented natively. It isn't pretty, but it's fine for the time being.
