### ISSUE TITLE
fibaro motionsensor keeps motion state

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1558]
**What is your Homey version (Settings → System)?**

1.3.0 rc7 - node 85

**What did you try to achieve?**
the sensor should turn the light out after 60 sec

*Please include detailed steps how we can reproduce the issue*
i made 2 flows: 
-1 if motion, turn light on {node85}
-2 if no motion turn light off

**What was the result?**
the sensor kept the motion state 

**What did you expect as result?**
after 60 sec without movement the sensor should set movement to no
[Untitled.txt](https://github.com/athombv/homey/files/1009020/Untitled.txt)

...

**Any other remarks**

`[2017-05-17T19:44:50.105Z] Node[85]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-05-17T19:44:50.108Z] Node[85]: sendData to COMMAND_CLASS_SECURITY, params 0x800e0ef1f351c206a7
[2017-05-17T19:44:50.171Z] Node[85]: Received application command for COMMAND_CLASS_SECURITY, data: 0x8120a14cfc3e84c888020dc40825834c9578ecc60e206a6f92d00e8d80
[2017-05-17T19:44:50.194Z] Node[85]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_NOTIFICATION, data 0x05000000ff07000108`

**Please attach a Homey System log (Settings -> System -> Send Log)**
58E91D8053
...

**Comment by caseda** [comment]
You do receive the off command after the motion was on, I'll have a look tonight what or why the off is not working, but probably not an app problem but a flow problem

Does it change on the mobile card?

**Comment by caseda** [comment]
Off command is properly received:
0x05: NOTIFICATION_REPORT
00: V1 Alarm Type
00: V1 Alarm Level
00: Reserverd
ff: Notification Status: true
07: Notification Type: 7 - Home Security
00: Event: 0 - Event inactive
01: Event Parameters Length: 1
08: Event Parameter: 8 - Event 8 (Motion Detection, Unknown Location) Went Inactive
and when looking at the code is still the same from previous updates, so should work just fine

also just checked it with my own z-wave plus version, (maybe the parser was changed, but this is not the case) and that also turns off the motion and tamper (tested both just to be sure) and both turn off like they should.
Normally don't use this one for motion/tamper, just for lux reports, but after activating it without re-pairing it works just fine.

so it most likely is your flow(s) that is not working.

**Comment by robiebab** [comment]
First off all thanks for looking into this, second i'm confused :), how can a flow be of influence, of a motion state(bewegingsactiviteit)? i don't set a motion sensor using a flow, i only read the state, that was send to homey. and use it to activate to light.

**Comment by caseda** [comment]
the state is coupled to the flow triggers, if the state changes, the corresponding flow(s) will trigger. that is how all default capabilities in homey work.

so the state changes to true, it will activate the trigger "motion turned on"

that is why i asked if the state does change in your mobile card ;)

**Comment by robiebab** [comment]
i know how homey works:P, i included a picture so we know we talk about the same :). the state was kept(in homey app and mobile app), until i revisited the toilet again. after i revisited the toilet the state went back to normal. 
<img width="958" alt="schermafbeelding 2017-05-20 om 21 34 46" src="https://cloud.githubusercontent.com/assets/18186327/26278852/7e37cece-3da4-11e7-8c8d-0f493cae5298.png">

**Comment by RobinBol** [comment]
@robiebab This issue is not reproducible by us, and the command seemed to have arrived properly. So there is unfortunately not much I can do. If this is still an issue for you (occurring often?) please let us know, for now I will close it.
