### ISSUE TITLE
Alarms use 12h AM/PM notation independently of system setting for 24h time notation

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1559]
**What is your Homey version (Settings → System)?**
Homey 1.3.0-rc7 
App 2.3.3 - b 69 / 2.4.7  b77

**What did you try to achieve?**
set and read the time for an Alarm / Wekker

*Please include detailed steps how we can reproduce the issue*
Set and rear te set alarm on my HTC one / Samsung Galaxy S7 Edge / HTC one
(or chrome emulation)

**What was the result?**
I set the alarm for 15:30 

**What did you expect as result?**
it is set for 03:30 PM in stead... 
![image](https://cloud.githubusercontent.com/assets/12412734/26205321/acc8773a-3be1-11e7-92e1-2e1e12de431e.png)

**Any other remarks**
Al my devices are configured for 24h time format, but also on Chrome for Windows you see the AM/PM notations on .... /manager/alarms/mobile/

**Comment by WeeJeWel** [comment]
Unfortunately this is an Android / Chrome issue we cannot solve on mobile.

**Comment by bvdbos** [comment]
what language is your chrome-browser, works for me with chrome-version 58.0.3029.110 (64-bit) Dutch on windows but also on my mobile...

**Comment by Dijker** [comment]
Almost everything is English, 
only one Homey (Production) in Dutch. 

Both give same result. 
My Android Tablets and phone are English with timeformat  as 24h Clock. 
Chrome on Windows 10 with Region - Format:  Dutch  (HH:mm / d-M-yyyy, etc.)

**Comment by bvdbos** [comment]
What does chrome-console on your phone show when you do:
```
var now = new Date()
console.log(now)
```
For me : Thu May 18 2017 17:35:41 GMT+0200 (West-Europa (zomertijd))

**Comment by Dijker** [comment]
For me the normal behavoir for Chome on my dekstop is OK, but goïng to the Developer Tools and select an Mobile Device on [HomeyIP] /manager/alarms/mobile/ already shows teh AM/PM time

![image](https://cloud.githubusercontent.com/assets/12412734/26211492/d5017696-3bf2-11e7-8f5f-e2a9d1972880.png)

**Comment by bvdbos** [comment]
maybe something to do with:
![2017-05-18 20_43_06-change chrome languages translate webpages - computer](https://cloud.githubusercontent.com/assets/1064079/26218263/a86891ba-3c0a-11e7-960f-eaa668a85597.png)

**Comment by Dijker** [comment]
Correct!! 
If I Change to Dutch it is Fixed!

But I Hate Dutch menu's, don't want my menu's  in Dutch!!! ;-)

maybe a difference between the default css  /manager/settings/css/style.css  and /manager/alarms/mobile/css/style.css 
guess normaly they (chrome?) use the prefered_timenotation and on mobile somethin like prefered_language_default_timenotation  ;-) 

But I cant read css ....
I guess I have to live with it, but once I get mad they in Mountain View will Remember me......
