### ISSUE TITLE
Z-Wave Settings >> Request Network Update >> SUC unknown or self

### ISSUE THREAD

**Issue by athomey** [athombv/homey#156]
As Athom expressed Homey should be easy to use and understand, also for n00bs, curiously I pressed the button "Request Network Update" (which has a totally unclear hint as help, talking about "SIS"), then I got a **pop-up "SUC unknown or self". This message is 100% unclear to me, and I'm even able to work succesfully with a Vera Edge**. ;-)  I strongly suggest making this message a lot more clear, and also the button itself, the hint only adds the word "SIS", but a lot more explanation might be needed. **Especially for your newbie users for Homey and not frustrating them.**

See screenshot: https://files.slack.com/files-tmb/T04E9KJ7T-F0M3Z6AVA-0e049625df/pasted_image_at_2016_02_12_03_07_pm_720.png

**Comment by JohanKuster** [comment]
Hi, could you just include the picture? I cannot see this because you have to have an account...I don't want one.

**Comment by athomey** [comment]
<off topic response>Sorry, no, I rather not do that. It is a lot more work. Submitting an issue takes me 2 minutes. It takes 4 minutes if I add the picture here. Using Slack I can simply PASTE a screenshot in 1 second. I hope you understand. But my descriptions are always (to be meant) sufficient for devvers/testers/repro</off topic response>

**Comment by JohanKuster** [comment]
You can also paste on github, that is what I do. Tried it?

**Comment by athomey** [comment]
OFF TOPIC >>> Thx! Mmm, strange. Remember that didn't work before. Will post them here from now on. <<< OFF TOPIC

**Comment by ocatie** [comment]
The Request Network Update is to ask the main controller in the network if there are new nodes or other protocol defined changes. Since Homey is the main controller and SUC (Static Update Controller) Id Server, this can't be requested.

You can see Homey is the SIS in your network because the id's match.

These are advanced functions and shouldn't be used if the user doesn't know what they do. Homey calls this function once a day by itself. The interface isn't final.

**Comment by athomey** [comment]
Great! Looking forward to clearer interface/texts on these and some other parts in Homey. ((I'm asking because from a B2B standpoint, I want to reduce MY support when I resell Homey with a whole domotica set-up for clients.))

**Comment by ocatie** [comment]
Please keep the interface issues comming ;)
