### ISSUE TITLE
Strange default msg for Alarms without Flows triggering, I guess for the developers?

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1560]
**What is your Homey version (Settings → System)?**
Homey 1.3.0-rc7

**What did you try to achieve?**
Trigger an Alarm and a Wekker without a flow....

*Please include detailed steps how we can reproduce the issue*
I guess the developers have an Homey in English at home and one in Dutch at the office with these alarms.....

an Alarm on Homey at home in English at 10 in the morning.
een Wekker op de Homey op de Rigtersbleek in het Nederlands  om 11 uur 58 's ochtends

Do not create an trigger for these alarms of create an generic trigger for any alarm. 

**What was the result?**
The alarm at home tels you: "Good [morning/afternoon/etc] This is your alarm, its time to wake up"
De wekker op kantoor verteld je: "Goede [morgen]! Dit is de wekker, tijd om op te staan"
**What did you expect as result?**
nothing, I didn't expect anything.... 
But I didn't expect a "time to wake up" or "Tijd om op te staan" at least not at the time I was playing with it ;-) 

**Any other remarks**
I heard the developers want to have their stand-up in the morning....
This is useful for the developers, 
for normal people it would be nice to have custom messages (and maybe melodies?)  for Alarms without creating flows and/or the use of soundboard.

Also option to execute the default Alarm Actions (play melody and let Homey Say some msg ) for Flows that are triggered by an alarm.

Something like: 
![image](https://cloud.githubusercontent.com/assets/12412734/26207843/f129b59a-3be8-11e7-9353-3ef26ab26f49.png)

and:
![image](https://cloud.githubusercontent.com/assets/12412734/26208900/92b67554-3beb-11e7-813a-c5c8d0cb76c1.png)

(Yes, actually is is some feature request and option to give you some inspiration for 1.3.1 ;-) )

**Comment by Tweake** [comment]
So, if I understand your request correctly you would like to be able to personalise what happens when an alarm goes off? Fortunately that's something you can achieve with a Flow! Just create a Flow: 
**If** the alarm _Stand-up_ is due **Then** Say _Heren Ontwikkelaars , Tijd voor de stand-up!_ and pick a nice melody you would like to hear and play it with the soundboard App

I hope this helps. Please close the issue if this resolves what you are trying to achieve.

**Comment by Dijker** [comment]
As discussed on Slack, 
Just a Feature request to personalize the text Homey speaks and/or the melody he plays when no Flows are defined that handle the Alarm. 
So Personalize from the Mobile App without creating flows!
If others also want that Vote by +ThumbsUp. and or comment....
But I will Close for now!
