### ISSUE TITLE
force reload playlists

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1562]
**What is your Homey version (Settings → System)?**
1.3.0rc7

**What did you try to achieve?**
Commemorate Chris Cornell so added songs to google and soundcloud playlists and hoped to see them in Homey. It takes a long time (hours? not there yet...) to see the changed playlists in Homey...

Would be really helpfull if there was a way to force a reload of a playlist...

**Comment by WeeJeWel** [comment]
Duplicate of #1474

**Comment by bvdbos** [comment]
Oeps 😂
