### ISSUE TITLE
Selected flow pops to the top of the list

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#1563]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

**What did you try to achieve?**

Trying to edit some flows.

*Please include detailed steps how we can reproduce the issue*

Select a flow. After that select another flow. U will see the flow u selected before is on top of the list.

**What was the result?**

I am trying to edit 5 flows in a group and need to scroll every time i select another flow.

**What did you expect as result?**

That the list stays where it was before.

**Any other remarks**

https://youtu.be/gsrye6HaHtw

**Comment by WeeJeWel** [comment]
Closing this issue due to being replaced by the new Homey Smartphone App
