### ISSUE TITLE
[Interface][Translation] Enable/Disable menu for Flows

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1564]
**What is your Homey version (Settings → System)?**
1.3.0-rc7 Dutch

**What did you try to achieve?**
een Flow uitschakelen

*Please include detailed steps how we can reproduce the issue*
![image](https://cloud.githubusercontent.com/assets/12412734/26237307/e6a834ca-3c74-11e7-9970-0d88f54ffc94.png)

**What was the result?**
Could only Disable / Enable ;-)

**What did you expect as result?**
Translate menu to: 
- Inschakelen/uitschakelen 
of eenvoudig Aan/Uit  omdat dat voor mijn gevoel het best overeenkomt met de Actie kaartjes: Schakel in / Schakel uit en voorkomt m.i. verwarring met het triggeren/activeren 

![image](https://cloud.githubusercontent.com/assets/12412734/26237558/ed59f76c-3c75-11e7-9aff-dd179a3c4908.png)
![image](https://cloud.githubusercontent.com/assets/12412734/26237619/2fac3b3e-3c76-11e7-8a9b-729e821a8fab.png)

**Any other remarks**
Would it be possible to add a Enable/Disable All flows for a folder 
of Onderliggende flows Aan/Onderliggende flows Uit

**Comment by Tweake** [comment]
Thanks for pointing this out. It will be fixed in the next update!

**Comment by Dijker** [comment]
Confirmed Fixed in RC10 (or 9?)
