### ISSUE TITLE
Show Presence for users in settings and in an Mobile Dashboard

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1567]
**What is your Homey version (Settings → System)?**
1.3.0.-rc7

**What did you try to achieve?**
View Presence information for me my GF and I ....

*Please include detailed steps how we can reproduce the issue*
Go to Flows, open a Flow, Open the Tags and scroll to the Presence boleans  (are they? Yes/No/unsure or Not Set ? ;-) ) 

**What was the result?**
Too many clicks, i thought Your mom will not like this....
I tried to make one with Better Logic Bitflips, to clumsy.... 

**What did you expect as result?**
Information for the users in the users dashboard on the Web-interface: 
- Settings- Users
something like: 
![image](https://cloud.githubusercontent.com/assets/12412734/26247547/ab294de2-3c9e-11e7-989f-52e6f49a8929.png)

And something like that as a dashboard on the mobile App like Alarms  /manage/users/mobile 

Option to toggle your @Home  or Asleep using that from the App and keep that for at least [fe 30] minutes before overridden by auto Presence ;-) 
This would help me not waking my GF when I go to bed and now have to talk to my phone. 

**Any other remarks**
just another 2 ct.

**Comment by DieterKoblenz** [comment]
Yeah +1 one for this

**Comment by WeeJeWel** [comment]
Noted! This is definitely something we're going to add in the new Homey Smartphone App.
