### ISSUE TITLE
Homey is voice activated by noise

### ISSUE THREAD

**Issue by dbonsaksen** [athombv/homey#1568]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

**What did you try to achieve?**
Homey is getting activated by noise after the experimental update.

*Please include detailed steps how we can reproduce the issue*
It has been activated when there have been noises, such as kids throwing things at the floor near Homey or yelling.

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
9479CF9660
...

**Comment by JPe2** [comment]
restart by pull the power plug, wait 5 minutes, insert the plug again solved this (most) kind of problem for me.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by JPe2** [comment]
Havn't seen it for a long time
