### ISSUE TITLE
Homey not responding to ok homey

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1569]
**What is your Homey version (Settings → System)?**

1.3.0 rc7

**What did you try to achieve?**
to communicate with homey
*Please include detailed steps how we can reproduce the issue*

**What was the result?**
saying ok homey results in no reaction,no change of led ring,no answer
saying through the dot alexa ask homey what time it is,works

**What did you expect as result?**
a reaction of homey after ok homey

**Any other remarks**
206EA4FB5D sended

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
For me the same after >5 days uptime (well, don't know about alexa but talking though the phone-app works... F21D898EDC)

**Comment by WeeJeWel** [comment]
Duplicate of #1383
