### ISSUE TITLE
HSM100 HomeSeer MultiSensor Z wave Motion sensor not reporting

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#157]
this is the first version of the homeseer multisensor.  Temparature, battery and lux works goed. But no motion status reported.

**Comment by ocatie** [comment]
Did you make an association with the device on the correct group? Refer to the device manual for the supported association groups. If this is a battery powered device you'll have to wakeup the device to push the saved settings to the device.

**Comment by ocatie** [comment]
Did you manage to get it working with the correct association?

**Comment by nattlip** [comment]
isnt woriking yet, i dont have to make any association with this device. the temp battery and luminance work correct eithout any association.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
