### ISSUE TITLE
fibaro dimmer 2 -> verander helderheid over tijd card ->startupdelay

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1571]
**What is your Homey version (Settings → System)?**

1.3.0 RC7

**What did you try to achieve?**
change light intensity over time without any delay
*Please include detailed steps how we can reproduce the issue*
fibaro dimmer 2
create a flow
card "verander helderheid over tijd"

settings card:
delay: 0
dimlevel: 90%
time: 40 sec
<img width="318" alt="schermafbeelding 2017-05-20 om 23 37 07" src="https://cloud.githubusercontent.com/assets/18186327/26279467/45d54ece-3db5-11e7-807c-3af289e242de.png">

**What was the result?**
3-4 sec delay
...

**What did you expect as result?**
no or minimal delay
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by caseda** [comment]
Your screen shot now has a 3 second delay in the card?.. Ofcourse you then have a 3 second delay

**Comment by robiebab** [comment]
indeed bad picture, i had this delay for turning off the lights and turning it on. just try it yourself without the dely. from the moment you press, test there is a noticable delay 3- 4 sec

**Comment by WeeJeWel** [comment]
That's simply how Z-Wave works: commands are queued to reduce wireless load.
