### ISSUE TITLE
every day hue app is crashing

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1573]
**What is your Homey version (Settings → System)?**

1.3.0 rc.7

**What did you try to achieve?**
no frequent crashing of the hue app

*Please include detailed steps how we can reproduce the issue*
every day the hue app is crashing with no stack trace,it is  always the hue app

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

why is it crashing,there are other users with the same issue,let the app produce a decent stack trace
statement of athom ---- yes

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Is there a red triangle visible? If so, please click on it and make a screenshot.

**Comment by satbopper** [comment]
roger will do but there is always no stack trace

**Comment by caseda** [comment]
if you mean that the connection with the bridge is lost (all bulbs etc unavailable),
then its not the app that was crashed, but the password of the bridge was lost in homey, which does happen (i believe this is the reason) when you ptp for longer period of time (password not being stored, except for in memory?)

**Comment by arno1965** [comment]
40 lamps and no crashes here..

**Comment by OpenMindNL** [comment]
Since the 1.3.0-rc7 update I have several apps crashing on a daily base (Red triangle)

- Philips Hue (most often)
- Sonos (second most often)
- Kodi (Once, today)
- LED Ring collection (sometimes)

ALL with stack trace: False

**Comment by WeeJeWel** [comment]
Please post a screenshot of the crash dialog.

**Comment by OpenMindNL** [comment]
I don't see why (unless you think I'm talking BS), but I'll send you one (or all....) as soon as it happens again.

**Comment by WeeJeWel** [comment]
The dialog contains more information than just a crashlog :)

**Comment by OpenMindNL** [comment]
The reason that I never send crash logs without stack trace is, because there is no more relevant information... Just the app that crashed without stack trace.
Nevertheless... you'll get them from now on.

**Comment by OpenMindNL** [comment]
23-05-2017, 23:01 Sonos
![20170523-2301-sonos](https://cloud.githubusercontent.com/assets/24574832/26377331/21b25b74-4010-11e7-8f5c-a837fea4e3e9.png)

**Comment by OpenMindNL** [comment]
24-05-2017, 00:15 Sonos
![20170524-0015-sonos](https://cloud.githubusercontent.com/assets/24574832/26378755/40029fc0-4016-11e7-86f6-92fa9b6e9af8.png)

**Comment by OpenMindNL** [comment]
BTW: Doing nothing is not really true...

The past week I very often work on an editor app for led ring animations.
But... 99% of the work is done in the settings-area (at my-app-name)... the index.html
There are some flow-cards available, but they have not been active for 2 weeks... however, they work flawless.

So... a few times a day I "athom project --run" the app to test.

But I guess that should not harm apps like Sonos, Philips Hue and others.

**Comment by WeeJeWel** [comment]
I'm sorry, I should've been more clear. Please make a screenshot of the dialog within the Homey interface after clicking the red triangle. It will also show an exit code and exit signal.

**Comment by OpenMindNL** [comment]
Hmmm... I clicked the link about informing the developer. Didn't now there's more info under the triangle... I expected it to be 'just' an icon... like with "beta" or "app in debug mode"...

I hope the next crash will happen soon :grin:

**Comment by OpenMindNL** [comment]
Sonos crashed again, but this time the situation was different because my internet modem went off-line a minute before.... Ziggo klusjes I guess.
Philips Hue only crashed this afternoon... since then it did not crash (yet...)

But still, here's what was available under the exlamation mark for Sonos. ( Copy / Paste )
Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by OpenMindNL** [comment]
Kodi:

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by OpenMindNL** [comment]
Philips Hue:

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by OpenMindNL** [comment]
Sonos again:

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

Gonna get some sleep now :grin:

**Comment by satbopper** [comment]
exact the same for me for the ledring app and hue app allthough yesterday none crashes

**Comment by OpenMindNL** [comment]
No crashes here since I went to sleep (06:30). 
My new day started at 13;00 and Homey has been used as a 'normal user' since then.
Now I went to developing again, so I will 'athom project --run' a few times in the next hours.... Let's see if crashes start popping up again...

**Comment by OpenMindNL** [comment]
24-05-2017, 23:01 Philips Hue

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

Surprisingly this happened at exact the same time as for Sonos yesterday.... Coincidence? (See: 'wrong' screenshots above)

**Comment by caseda** [comment]
SIGKILL, homey killed the app

another app or thing that is hogging homey's memory? (memory leak) 🤔

**Comment by OpenMindNL** [comment]
Well... my new app loads large images and manipulates them... Besides that, at some point a preview animation is created... max 200 frames of 400x400 pixels ... that's about 128MB... but it all happens in the browser part of the app... the PC/laptop memory. Homey only gets 'normal' chunks of data... the biggest one will be a complete full led-ring animation: 200 frames x 24 leds x 3 bytes + some parameters = about 14.5kB....

**Comment by OpenMindNL** [comment]
My app-settins send a led-ring animation to Homey... 2 seconds later...

Tado crashed.

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

Also an app with network connection...

**Comment by OpenMindNL** [comment]
function that saves animation from index.html to Homey.

[saveAnimation.txt](https://github.com/athombv/homey/files/1027391/saveAnimation.txt)

**Comment by OpenMindNL** [comment]
Woops... my second 'wrong' screenshot yesterday was at 00:15 (Sonos) ... and Tado just crashed at about the same time... and just like last night it was the second crash....

I hate coincidences :grin:

**Comment by bvdbos** [comment]
Had a crash of several apps (Lifx, afvalherinnering, Led-ring collection, KaKu and plugwise) after an uptime of 6 days while doing nothing with Homey. Nothing special in memory of processor with the apps still running. Total memory isn't unusual:
![2017-05-25 06_18_20- 703 settings - homey](https://cloud.githubusercontent.com/assets/1064079/26435859/89b2258a-4112-11e7-8b9b-1d1b23f7aadd.png)

Kaku had a Sigabort. Lifx, Led-ring collection and plugwise had a Sigkill and afvalherinnering had the following:
![2017-05-25 06_24_52- 703 settings - homey](https://cloud.githubusercontent.com/assets/1064079/26435894/e7889a54-4112-11e7-820a-b6321a0b5eea.png)

Afvalherinnering (0.2.5) has been crashing for some time now. As I only have one container a year, I'm going to disable that app and see if that matters... 

Log: 3D17E50683

**Comment by Marc1979** [comment]
Have had the same, only reboot will help then. Before Hue is crashing I saw that the memory using is crowing a lot (if you see the other apps are almost around the 25mb). Hue is crowing to 88mb en even larger..
![hue_88](https://cloud.githubusercontent.com/assets/19633409/26437255/401c77d6-411c-11e7-9950-3443501cb9f7.JPG)

**Comment by satbopper** [comment]
remarkable more people are comming with this issue and marc1979 that is true i kept an eye on the hue app and here from 25mb suddenly to 91mb,but a few seconds later it recovers to somewhere 25 mb
as a test here i removed the ledring app,a shame because i love the app,from now i have a uptime of 2.5 days without crashes
my last reboot of homey is 6 days ago,i want to achieve that
no crashes of apps with no stack trace
that homey keeps working when i say ok homey what is the time
at the time of crashes what i can remember that i was mostly doing nothing with homey but there were times that i was playing playlists from soundcloud
my memory at this time is (system) 416mb with a swap file of 392mb this going down and up
total amount of apps is 27
usually at this stage my homey stops working with a speach request (what is the time)
For now it is still working and no crashes,fingers crossed,i will update here

**Comment by OpenMindNL** [comment]
Philips Hue

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by OpenMindNL** [comment]
Just home from enjoying the nice weather... 
In the meantime Sonos crashed

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

@WeeJeWel , do you enjoy the reports or can we stop sending them?

**Comment by OpenMindNL** [comment]
Netatmo

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by satbopper** [comment]
and now for something completely different
exports insight
![2017-05-26_09h44_56](https://cloud.githubusercontent.com/assets/17260928/26485712/5d04c56a-41f8-11e7-90e9-dd1a2b0f9804.png)

**Comment by satbopper** [comment]
the positive thing is vocal interaction with homey still works

**Comment by OpenMindNL** [comment]
Sonos + Philips Hue

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by satbopper** [comment]
back from the beach
![2017-05-26_17h09_03](https://cloud.githubusercontent.com/assets/17260928/26500530/89d78260-4236-11e7-817a-880c894f6c31.png)

**Comment by OpenMindNL** [comment]
I can not get away from the impression that the crashes get worse when I'm in development and have to upload regularly.

**Comment by satbopper** [comment]
OpenMindNL forget it,it happens even if you are not doing anything,except drinking coffee
 this happens during coffee time
![2017-05-26_22h05_13](https://cloud.githubusercontent.com/assets/17260928/26510952/fc091460-425f-11e7-9a60-0bcc1515189d.png)

**Comment by OpenMindNL** [comment]
Yes... Sonos also crashed a few times without me asking for it.

But... There have been a few times that Sonos crashed within a few seconds after I did "athom project --run/--install"

**Comment by satbopper** [comment]
OpenMindNL do you remember a long time ago we had a conversation about the ledring app
continious crashing,at that time it started here,now here it is bad,do you think it is worth to build homey up from scratch

**Comment by OpenMindNL** [comment]
LOL... No... Every software problem can be solved. Starting over is something that you do in despair... when you don't understand your own work anymore. But as Emile is an educated programmer, his work will be modular enough to repair things. Homey is complex, so it might take some time to solve problems without creating new bugs because of internal 'software-connections'.

**Comment by OpenMindNL** [comment]
Summary of the past 24 hours:

2 x Philips Hue
2 x Sonos
2 x LED Collection

All:
Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by WeeJeWel** [comment]
Thank you all for consistently reporting, it helps a great deal in understanding this issue. How is your memory usage, and how many apps are installed (and enabled) in total?

**Comment by OpenMindNL** [comment]
At the moment I have 27 apps installed of which 2 are disabled (iTunes by Dennie de Groot & Virtuele Apparaten by Arjan Kranenburg).

Current memory (LEDitor = in development):
![homey-mem](https://cloud.githubusercontent.com/assets/24574832/26531397/8b7985c4-43e8-11e7-89f0-681c5f1eb9a1.png)

**Comment by gruijter** [comment]
This problem has been around already for many fw releases. See for instance #1147 and #1548 
also in the dp-issues: https://github.com/athombv/homey-issues-dp/issues/34

This problem really needs to be solved because it makes Homey unreliable for users!

**Comment by WeeJeWel** [comment]
It seems like Homey simply runs out of memory (notice the swap usage. Anything >0 is not good) and the Linux kernel starts killing apps to make room for more priority tasks (e.g. installing a new app).

We will definitely think about a workaround, but Homey's hardware simply has its limits - we can't push it forever.

**Comment by bvdbos** [comment]
https://stackoverflow.com/questions/726690/who-killed-my-process-and-why -> tame the OOM-killer?

**Comment by WeeJeWel** [comment]
You can't tame a hungry dog :-)

**Comment by bvdbos** [comment]
Is OOM turned on in Homey-core? I wonder why the processes (apps) don't want to give their used memory to the kernel? It seems like a lot of memory is used for simple apps which don't need that much...

**Comment by OpenMindNL** [comment]
You'll HAVE to push it as long as promises don't come true. After all it's job is to connect ALL of my devices.

**Comment by bvdbos** [comment]
![glofx-elite-360-space-whip](https://cloud.githubusercontent.com/assets/1064079/26551271/f81b4016-4481-11e7-8aea-894d02c52b24.jpg)

**Comment by gruijter** [comment]
does it come with a rubber mask?

**Comment by Inversion-NL** [comment]
Is there a way for Athom to hook into the kernel/memory manager/whatever-kills-those-apps and start warning big memory eaters like in https://developers.athom.com/library/performance/

**Comment by caseda** [comment]
athom already does that with the performance messages indeed...
but it's very hard to pinpoint what app is using what part of the memory.
That's why you most of the time see the "System" being the culprit, though it could be any app that left empty/corrupt/unassigned data in the system area.

It's not something athom can do much about (i think), that is how linux works with it's memory

**Comment by satbopper** [comment]
sonos still crashing in rc9
ptp for a half hour and reduced the app count from 27 to 23 an absolute minimum for me
system 187 mb swapfile 190 mb,if that does not work tja

**Comment by OpenMindNL** [comment]
"No message is a good message" as we say in The Netherlands... which in this case is true.

No more crashes since I updated to 1.3.0-rc.9 😎

**Comment by satbopper** [comment]
after install rc9 i had sonos crashed so i reduced my apps to 23,rebooted,since then a steady system and swappfile,how many apps do you have now

**Comment by OpenMindNL** [comment]
@satbopper , 27 apps over here.

**Comment by OpenMindNL** [comment]
Well... no complaints during version 1.3.0 .... but now with 1.3.1 it seems to be back... Not as bad (yet), but similar.

A few hours ago there was a Philips Hue crash which I considered coinsidential.
But a few minutes ago LED-Collection crashed...

Stack trace:

No stack trace available

Exit code: null
Exit signal: SIGKILL

**Comment by bvdbos** [comment]
Does this still happen?

**Comment by OpenMindNL** [comment]
No crashes for me  in the latest versions.
