### ISSUE TITLE
Tags not draggable anymore 

### ISSUE THREAD

**Issue by jasperbollen** [athombv/homey#1578]
**What is your Homey version (Settings → System)?**

1.3.0

**What did you try to achieve?**

Drag a tag from a trigger in a flow to a "And" or "Then" card.

**What was the result?**

The tag isn;t draggable anymore, so it's impossible to use tags in flows

**What did you expect as result?**

Tag should be draggable 

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

074A274B8A

**Comment by bvdbos** [comment]
works for me...

**Comment by glijie** [comment]
works in chrome browser but it does not work in the homey desktop app.

**Comment by robiebab** [comment]
duplicate: https://github.com/athombv/homey/issues/1555

**Comment by DeefK** [comment]
Same issue here in chrome and app.

**Comment by jeroenvollenbrock** [comment]
Which version of the Desktop app are you using?

**Comment by kukel** [comment]
it does work in the desktop app but you have to 'move'/'shake' the mouse cursor a little. It is certainly not 'user friendly'.  I get the impression it depends on the position of the mouse and not the label...

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #1555
