### ISSUE TITLE
IFTTT duplicated triggers

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1579]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

**What did you try to achieve?**

I want to create a shopping list from Homey to my iOS reminders.
I created several flows that trigger the same action in IFTTT.
<img width="979" alt="schermafbeelding 2017-05-22 om 19 40 09" src="https://cloud.githubusercontent.com/assets/13370203/26321290/7f7e0626-3f26-11e7-8138-5c8d0caefa71.png">

**What was the result?**

In IFTTT I see for every card I use a row. It doesn't mather witch on I select, because all actions with the same name can trigger 1. So I have on IFTTT action that put the data on my shopping list.
<img width="651" alt="schermafbeelding 2017-05-22 om 19 41 13" src="https://cloud.githubusercontent.com/assets/13370203/26321403/f4f38098-3f26-11e7-90dc-340a2552b2f5.png">

**What did you expect as result?**

To see in IFTTT a distinct list with items instead of a lot of duplicated items

**Any other remarks**

I'ts work like a charm, but it's confusing. So [I]f [T]his = a quick solution [T]han fix [T]hat else low priority

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by RobinBol** [comment]
Hi! I have given the IFTTT Homey app an update, which also fixes this issue. Currently it is released as beta in the app store as it has also been updated for SDKv2. I have tested it quite thoroughly, but would you be so kind to install the beta version and test around a bit? I'd like to push this to stable soon, but first would like some people to test this update!

**Comment by RobinBol** [comment]
For now I will close this issue, but please do test the beta version of the app (else it will not arrive in the stable channel anytime soon)!

**Comment by kerkenit** [comment]
I've tested it and I can confirm it's working correctly.
