### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by evad1st** [athombv/homey#158]
I only get replies "server down" even with time request or date request , any tips or tricks ?

**Comment by WeeJeWel** [comment]
What is your system time? (Settings -> System -> Show stuff for geeks)

**Comment by evad1st** [comment]
Seems to be off ... By one hour (dst ?) how to correct ?

**Comment by matjaz** [comment]
date is shown in utc.

**Comment by jeroenvollenbrock** [comment]
Has this issue been resolved?
