### ISSUE TITLE
Broken flow not shown as broken

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1580]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

**What did you try to achieve?**

Look why a flow no longer works.

*Please include detailed steps how we can reproduce the issue*

I notices a flow was no longer working, but Homey did not indicate the flow was broken.
When I opened the flow, I noticed that one of the tags was missing. 

**What was the result?**

The list of flows shows the flow is OK

**What did you expect as result?**

The list of flows shows the flow is broken

**Any other remarks**

<3

**Please attach a Homey System log (Settings -> System -> Send Log)**

![broken flow](https://cloud.githubusercontent.com/assets/5879533/26326893/8df1406c-3f3d-11e7-8bc0-578f453a6cf5.png)

**Comment by WeeJeWel** [comment]
Good found! Homey does indeed not check for missing Tokens yet. I will add this, thanks!

**Comment by chrisboer** [comment]
@WeeJeWel also if you changed a flow name and have used that flow name as an execution action in another the new flow name is not changed and the flow is broken but does not show broken.

**Comment by WeeJeWel** [comment]
Should be fixed.

As for changing the name, that's only cosmetic.
