### ISSUE TITLE
Day selection in Alarm/wekker broken

### ISSUE THREAD

**Issue by goyaweb** [athombv/homey#1585]
**What is your Homey version
1.3.0 RC7

**What did you try to achieve?**
Set the alarm in the mobile app to only go of Tuesdays. Regardless on Wednesday the alarm went of again waking me up unnecessary.

**What was the result?**
I woke up.

**What did you expect as result?**
More sleep

**Comment by Dijker** [comment]
Duplicate of https://github.com/athombv/homey-issues-dp/issues/31 
But I understand you didn't expect it there....

**Comment by Jovink** [comment]
It's fixt in the next build

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.9/10
