### ISSUE TITLE
Association groups cannot be assigned node numbers > 99

### ISSUE THREAD

**Issue by bm480** [athombv/homey#1586]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

I want to use my Wave.me WALLC-S switch to directly control lights using association groups. This works fine for devices having node numbers < 100. However, after already having added/removed several devices the assigned node numbers kept increasing and devices already receive node ids above 99.

**What was the result?**

Now it seems impossible to enter node numbers larger then 99 into the association groups text-boxes, a red color is shown around the box and it is impossible to save the configuration.

**What did you expect as result?**

To be able to add node numbers for any device, also devices that have ids of 100 and up.

**Any other remarks**

I also checked other devices, like the Fibaro smoke sensor which again doesn't allow node ids of 100 and up in the association group text box. Could this be a GUI-bug in the general Z-Wave library. 

**Please attach a Homey System log (Settings -> System -> Send Log)**

N/A

**Comment by caseda** [comment]
Can confirm the same behavior for 1.3 rc7

But is indeed a general bug, association groups isn't taking care of by any of the apps

**Comment by bm480** [comment]
Quick Question: Would it be possible to set association groups using Expert Parameters?

**Comment by caseda** [comment]
no, that is not possible, association groups are not parameters.

You can try with the RAW data text input in the z-wave settings, but that's a bit _More_ expert then expert parameters, not gonna explain how

**Comment by bm480** [comment]
Actually, I think I found out what the problem is. The validation pattern for the Association Group text box in the UI is not correct (it does not allow values 100-109):

^(([1-9]|1?[1-9][0-9]|2[0-4][0-9]|25[0-5])(,([1-9]|1?[1-9][0-9]|2[0-4][0-9]|25[0-5])){0,9})?$

which I think should be:

^(([1-9]|1?[**0**-9][0-9]|2[0-4][0-9]|25[0-5])(,([1-9]|1?[**0**-9][0-9]|2[0-4][0-9]|25[0-5])){0,9})?$

I tried to work around the problem by modifying the ng-pattern attribute using the Inspector of Chrome Developer tools, but for some reason the changes do not seem to have any effect.

**Comment by caseda** [comment]
it is indeed a typo, but think the regex is deeper then just trying to change the ng-pattern. that only changes it for the input, not the underlying javascript that is dynamic onLoad

**Comment by MbenzNo** [comment]
I am unable to associate more than one Node Id to any device. I expect to be able to associate several dimmes to a scene controller. As soon as I add another Node ID, the association group box turns red, and it is impossible to save. (Tried with different separators as space , ; : .)

**Comment by MbenzNo** [comment]
Yes!
For example Node ID 7 that supports 8 other nodes in group 2,
Node ID 66 that supports 5 other nodes in group 1 and 2. 
Node ID 60 that supports 5 other nodes in group 1 and 2. 
I have so far not seen any Nodes that I have been able to associate more than one Node ID to.
BTW: The associations that I have done so far does not seem to work. Motion sensors does not trigger lights when homey are offline.

**Comment by caseda** [comment]
I tested it yesterday because of the OP's issue and had no trouble.
Where are my exanples of how you added the id's to the association groups. 

And did you save the settings, and did you take into consideration that from normal zwave to zwave plus is not possible yet, and also if a device has multiple devices/end points (like relay 1 and a relay 2) that it's also not possible yet. As you need to determine which relay its needs to send to.

**Comment by MbenzNo** [comment]
![2017-05-31](https://cloud.githubusercontent.com/assets/28839112/26629566/2e041d60-4603-11e7-9fb4-991528a33c40.png)

I am not entirely sure if one or both devices are Z-Wave plus. The motion sensor is a Fibaro FGMS-001 and the dimmer (Node id 67) is a qubino ZMNHDD1 which both should be Z-Wave plus, but in Node information both is listet with "Secure: No"

**Comment by MbenzNo** [comment]
Related to https://github.com/athombv/homey/issues/1517 ?

**Comment by caseda** [comment]
And if you add just 1 more number it will remove the red border? :wink:

**Comment by MbenzNo** [comment]
Nope!

![2017-05-31 2](https://cloud.githubusercontent.com/assets/28839112/26630593/b836d1f4-4607-11e7-8300-caf709dcc8ed.png)

**Comment by caseda** [comment]
Whoops, it's comma `,`

**Comment by MbenzNo** [comment]
Ahhh! Comma it is...
![2017-05-31 4](https://cloud.githubusercontent.com/assets/28839112/26631161/1ae715fa-460a-11e7-8731-a1c20cf8788d.png)

**Comment by MbenzNo** [comment]
Another sensor. This one have only one association group, but it allows for 5 other devices to be associated. When I add the comma the association box goes red, and the red border goes away when i add the next node id. But the save button does not become active and I am unable to save...
![2017-05-31 6](https://cloud.githubusercontent.com/assets/28839112/26631613/362735e6-460c-11e7-9209-d673a2dda75e.png)

**Comment by caseda** [comment]
Don't post all your issues into the same issue.. But then one of your other settings are out of range/invalid

**Comment by caseda** [comment]
Don't post all your issues into the same issue.. But then one of your other settings are out of range/invalid

**Comment by bm480** [comment]
It would be nice if the validation issue could be fixed in a future release as well, of course.

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.11

**Comment by jeroenvollenbrock** [comment]
Please submit seperate issues for different issues, everything that is not related to the initial issue will be ignored.
