### ISSUE TITLE
KaKu stopped working after a few days

### ISSUE THREAD

**Issue by Reemster** [athombv/homey#1589]
**What is your Homey version (Settings → System)?**

1.3.0-rc.7

** isseu:

After a few days KaKu stopped working (receiving and transmitting) Before version 1.3.0-rc.7 it stopped working after 1 day, now it stopped after 2/3 days. Only rebooting Homey fix this problem

**What did you expect as result?**
working KaKu

**Please attach a Homey System log (Settings -> System -> Send Log)**

EA10A27840
...

**Comment by bvdbos** [comment]
dupe of #1228 ?

**Comment by Reemster** [comment]
I get a e-mail from Jeroen. Apparently my Homey was out of memory, and that's why my KaKu stopped working. Probably 24 apps is to much for Homey. So i go back to my old situation, and reboot Homey every night automatically.

**Comment by bvdbos** [comment]
It depends on a lot of factors such as the memory-holes in the installed apps, the number of devices etc etc. A nightly reboot will never hurt though....
