### ISSUE TITLE
[1.3.0 rc9] Homey response is strange when somebody is going to sleep card is used

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1592]
**What is your Homey version (Settings → System)?**

1.3.0 rc9

**What did you try to achieve?**
Say to homey i am going to sleep and homey should execute a flow and say something back (this is build in homey it self)

 I have don this with the folowing flows:

![sc1](https://cloud.githubusercontent.com/assets/752857/26571654/2c8b383e-4517-11e7-9ecc-f9826a961e9a.png)

![sc2](https://cloud.githubusercontent.com/assets/752857/26571666/35e22b68-4517-11e7-857e-398bf2a4bb41.png)

I use it this way because i also use a better logic button on homeydash which can execute te second flow.

**What was the result?**
Homey is turning everything off, but says a strange message:

![sc3](https://cloud.githubusercontent.com/assets/752857/26571764/93a495b0-4517-11e7-8028-ca9b0a036095.png)

**What did you expect as result?**

Is expect that homey should say something like "weltrusten" or "slaap lekker"

**Any other remarks**
It worked on 1.2 and 1.3 rc7 perfectly.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.3.0-rc.11

**Comment by spoelly** [comment]
Thank you!

**Comment by spoelly** [comment]
I can confirm it is working normal again!
