### ISSUE TITLE
fibaro motion sensor zwave plus motion and tamper alarm

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1593]
**What is your Homey version (Settings → System)?**
1.3.0 rc9

**What did you try to achieve?**
a working fibaro device

*Please include detailed steps how we can reproduce the issue*
after a reboot of homey the fibaro device start with a motion and a tamper alarm

**What was the result?**
if you trigger a motion and tamper by entering the room and knocking on the device
it will close the alarms

**What did you expect as result?**
if you do not trigger the device it will flash forever

no tamper and motion alarm from the beginning

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by caseda** [comment]
So it is working... Just not Until the first report of a sleeping device?

Also known as schrödingers cat principle, it can be on, but also off, you don't know until you look, which is impossible with a sleeping device.

**Comment by satbopper** [comment]
correct caseda,annoying when you are not at home,all i know from earlier firmware that it can work
i repaired the device,time will tell

**Comment by caseda** [comment]
Just don't restart your homey when your away, and you are all set :wink:

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not in version 1.3.1?

**Comment by satbopper** [comment]
yes i am afraid so,the reboot of homey is not that problem because i never boot when i am not at home,but if there is a new app of fibaro then you can imagine all along the flows you have that in some cases when you are not home a few bells will rinkle and the alarms here are very loud hi,if suddenly the sensor goes in motion

**Comment by satbopper** [comment]
good news guys,after install sunday of 1.3.1 i did today a reboot of homey,from start every device including the fibaro sensor starts in a perfect state.after the time for becoming the zwave stable i made several motion detection and tamper alarms and for me problem solved,i wait a couple of hours to close this issue

**Comment by satbopper** [comment]
i close this,after changing the place for the sensor,the first place was 6 meters away from homey and in between a thick concrete wall,now 3 meters away from homey with the same wall in between
it is ok now allthough i have my thoughts about the range
