### ISSUE TITLE
Homey fails to see Z-Wave device from existing network

### ISSUE THREAD

**Issue by CelticWebSolutions** [athombv/homey#1594]
**What is your Homey version (Settings → System)?**

1.3.0-rc.9

**What did you try to achieve?**

Inclusion in to existing Fibaro Home Centre 2 Z-Wave network

*Please include detailed steps how we can reproduce the issue*
In Z-Wave select include into existing network and then on Fibaro Home Centre 2 select add device

**What was the result?**

Fibaro shows a new wave controller as included although it says it's not fully configured.  Homey does not show any Existing Z-Wave Devices

**What did you expect as result?**

The same as when I add a different Z-Wave controller such as a Samsung Smarththings, I expected the existing Z-Wave devices to show as available within Homey.

**Any other remarks**

100% swapping to homey from an already fully setup Z-Wave network is not a valid option till I have tested the capabilities of Homey, I purchased Homey because teeth idea of it sounds great, integration in to existing network is definitely required to allow for proper testing before taking the plunge if Homey performs well. 

**Please attach a Homey System log (Settings -> System -> Send Log)**

EAD3163579

**Comment by Dijker** [comment]
Correct, 
Homey will not see or be able to control the other devices on the network as discussed here:
https://github.com/athombv/homey/issues/856#issuecomment-251928761 
and here: https://github.com/athombv/homey/issues/856#issuecomment-265160588

**Comment by CelticWebSolutions** [comment]
I'm not attempting to make it the secondary controller.  

On the forum, I read the following from mvdkallen

Once Homey is added to the HC2 controller as a device, you'll see a notification within the Homey UI that Homey can perform a scan on the HC2 zwave network. If you confirm this action, then Homey will add your HC2 devices into his configuration, which means you then can control your HC2 devices through Homey too :blush: 

Later in the same thread, Taco said the following 

After inclusion Homey will ask for a welcome message from alle device in the network. Devices that are awake will answer and Homey will try to add those devices. This progress happens in the background. If the interview fails no device will be added and currently the user isn't informed of the progress.

This thread is https://forum.athom.com/discussion/1199/question-integration-into-fibaro-home-center-2-environment

So this is what I'm trying to achieve,  I am not attempting to make the controller the secondary as I know that is not possible, it's not in the Z-Wave implementation within Homey.

**Comment by bvdbos** [comment]
Without digging into the issue: that thread is from april 2016, from before the rewrite of the zwave-firmware. So things might have changed...

**Comment by CelticWebSolutions** [comment]
I really do hope not, I don't see what use the "Include in existing network" option is if this doesn't work.

**Comment by jeroenvollenbrock** [comment]
@bvdbos Is right, The post you are referring to was about the old Z-Wave implementation without app support. Homey currently does not support controlling devices that are included on another controller.

**Comment by WeeJeWel** [comment]
Migrating Z-Wave networks is indeed not supported. Due to Homey's app nature, and all the benefits thereof, simply copying all nodes will not work.
