### ISSUE TITLE
Bug which makes pop-up details unusable ~50% of time for Zwave BeNext dimmer (doesn't get drawn correctly on canvas)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#16]
When I press the pop-up icon, the pop-up window sometimes gets drawn correctly,  many times not. Sometimes 7x wrong, then 3x right, etc.. You can still click and slide on it and then it redraws the whole pop-up and it is correct, without reopening it.

Is there a relationshop with #165 ?  Though it is a totally different problem in usability and problems it causes, it's both with the BeNext dimmer and in the GUI/drawing/syncing of stuff?

**Comment by athomey** [comment]
See this screenshot: https://files.slack.com/files-pri/T04E9KJ7T-F0J11QV09/pasted_image_at_2016_01_08_01_30_pm.png

**Comment by ocatie** [comment]
Happens because the card is waiting on callbacks of the get commands from the Z-Wave driver.

**Comment by athomey** [comment]
I can confirm that this drawing problem still exists today in 0.8.17

**Comment by athomey** [comment]
Is there a relationshop with #165 ?  Though it is a totally different problem in usability and problems it causes, it's both with the BeNext dimmer and in the GUI/drawing/syncing of stuff?

**Comment by WeeJeWel** [comment]
Fixed in 0.8.34
