### ISSUE TITLE
Reboot from menu shows pop-up [object Object] (minor bug)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#160]
When rebooting Homey from Settings | Stuff for Geeks | Reboot..., [wonderful option btw, missed it a LOT in earlier firmwares], I get the error message in a embedded pop-up [object Object].  Minor bug, no showstopper, but seems unpolished, gives bad impression.

![image](https://cloud.githubusercontent.com/assets/16608801/13013010/f4fddfc6-d1ad-11e5-8551-7349c47d1074.png)

**Comment by JohanKuster** [comment]
fixed in 0.8.18 see [#126](https://github.com/athombv/homey/issues/126)

**Comment by athomey** [comment]
Nice, thx, keep up the good work! :+1:
