### ISSUE TITLE
HTTP GET Fails with time elapsed

### ISSUE THREAD

**Issue by konradwalsh** [athombv/homey#1601]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 1.3.0-rc.11

**What did you try to achieve?**
FLOW
IF (18:45) THEN (HTTP GET - http local url)

A 18:45 run a HTTP GET Action to start Music on Squeeze Server. It fails to run this HTTP GET.

*Please include detailed steps how we can reproduce the issue*
If you set it for 2 mins or 10 mins from now or manually run the flow, it works. It seems after a certain time has passed, it no longer runs.

**What was the result?**
Failure to turn on music
...

**What did you expect as result?**
Music Play - Successful HTTP GET
...

**Any other remarks**

It seems that the SQUEEZEBOX plugin fails for the same reason as above if you use an action card of playlist.

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
A9670E28C2
...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
