### ISSUE TITLE
Add default onoff capability to device class vacuumcleaner

### ISSUE THREAD

**Issue by abaretta** [athombv/homey#1602]
Homey version 1.2.2.

I added an onoff capability to an app for a vacuumcleaner (using device class 'vacuumcleaner'), however Homey cannot turn it on or off through the speech interface. It seems this is due to 'onoff' not being a default capability for the device class 'vacuumcleaner'. I think the onoff capability is probably the most important capability of any vacuumcleaner, it would be nice to have it included as a default capability in the device class.

**Comment by Tweake** [comment]
A smart vacuum cleaner will usually not just have the two states "on" and "off", but will have several states like "cleaning", "docked", "charging" and "stopped". That's why the capability `vacuumcleaner_state` was created. Are you sure this capability will not suit your needs?

As far as speech you are right, there is no built-in speech for vacuum cleaners yet. I will add it in a future update and let you know the version number here.

**Comment by abaretta** [comment]
Hi Robert,

I have thought about it and discussed it with another developer, but I (we) still think it should have a simple on/off capability. The fact that it is the first thing I tried through speech ('OK Homey, zet de stofzuiger aan') illustrates that intuitively you expect a simple 'on' and 'off' action.

The fact that the vacuumcleaner has different/additional states just means that a choice has to be made as to which state to map 'on' or 'off' to (by the developer). In the case of the app in question (for the Xiaomi Mi Robot) 'start cleaning' and 'stop cleaning' make perfect sense, this is the same thing that happens when you press the button on the vacuumcleaner (which has an on/off symbol by the way ;-) ).

If you look at it from another angle, an on/off capability doesn't prevent a developer from using the vacuumcleaner_state capabilities, right? Possibly I am missing certain implications.

Great to hear speech capabilities will be added. I guess with speech you would have to make choices as well as far as mapping a command like 'stofzuiger aan' to a capability or state? Or would 'zet de stofzuiger aan' simply not be supported?

Thanks,

Regards, Anne

**Comment by Tweake** [comment]
The onoff capability has been added in version 1.5.0, along with voice commands such "start cleaning", "stop cleaning", "return to the dock" and commands related to spot cleaning.

**Comment by abaretta** [comment]
Sounds good, thanks!
:-)
Regards, Anne
