### ISSUE TITLE
Daytime card is responding falsely.

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#1609]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.2.2

**What did you try to achieve?**
Routinely get a reminder to wind up an antique clock.

*Please include detailed steps how we can reproduce the issue*
Flow is active to make an audio/visual reminder during daytime.

**What was the result?**
The flow has not executed for days.

...

**What did you expect as result?**
A succesful test of the flow to confirm it being active.
...

**Any other remarks**
Replacing the daytime card, saving and running the flow again is negarive.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...
![screenshot 2017-06-04 at 08 44 38](https://cloud.githubusercontent.com/assets/24312420/26759620/1ae37f0c-4903-11e7-862d-b98a8a18d020.png)

**Comment by Povlov** [comment]
Just in case: logcode 64448B7F5E

**Comment by Tweake** [comment]
Thanks for reporting the issue. I came across this problem as part of another issue, and it has already been fixed in a 1.3.0 release candidate. Once your Homey is updated to version 1.3.0 this condition will function correctly.
