### ISSUE TITLE
Fibaro DoorWindowSensor state not reflected, flows not triggered (think bug)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#161]
I added three Fibaro Door/Window Sensors FGK-101-107, and added 1 for group II and group III association. **But the state never changes on the card, and flows using the sensor never trigger: not when I try on/off of both tamper alarms, not when using the reed-relais magnets.** Every change/combination (8 combinations in total I tested) I give Homey time to receive the state. Every change the Fibaro sensor flashes the blue led indicating updates are transmitted. Please let me know when the bug is fixed, or what I'm doing wrong if it's my doing.

![image](https://cloud.githubusercontent.com/assets/16608801/13015856/a8bb0f04-d1bb-11e5-923d-46c110b394ed.png)

![image](https://cloud.githubusercontent.com/assets/16608801/13015915/131e56b2-d1bc-11e5-8745-fd7b21e99225.png)

**Comment by ocatie** [comment]
You only need an association on group 3. Because this is a battery powered device the settings will be applied on the next wakeup od the device. You can manually wake the device up by pressing the B button 3 times (same as in-/excluding).

**Comment by athomey** [comment]
Oké, I tried what you said. When I opened the dialog in devices for this device, it was flashing red/black: 

![image](https://cloud.githubusercontent.com/assets/16608801/13021936/40e0b550-d1de-11e5-940b-b0848a96d52e.png)

But it makes no difference if I "off" both tamper switches and the reedrelais switch, or if I "on" them. Even though it is battery operated, it keeps flashing red/black. Nothing else to do.

On a VeraEdge it is very intuitively, and I understand it's workings immediately. Also on ANY change on ANY sensor, the VeraEdge receives the immediately transmitted state change, and shows it in the UI, no polling, a nicely pushed message. 

That message is also send to Homey, but I see no state change at all, like I see with a wall plug. This UX is not very well, especially I for non-geeks/regular users I imagine.

What should I do next then? 

Second issue, the Vera Edge shows wonderfully both the value you have ASKED, and the value that was last RETRIEVED from the device, and a timestamp when it was retrieved. This helps tremendously in configuating the Vera, I miss those extra tools in Homey. Could you elaborate if you will add such tools/helping information and when? If you say no or it will take to long, I will open a thread in the forum, just to collect experiences from other users, cause I'm very curious. I can certainly not be the only one. Thanks in advance for this second answer too!

Keep op the good work! :+1:

**Comment by athomey** [comment]
Please reopen. Issue still stands as described. Thx.

**Comment by Muyz** [comment]
Agree; same problems here

**Comment by Wimstradamus** [comment]
Same issue here

**Comment by RemonBerends** [comment]
+1 Same here

**Comment by Wimstradamus** [comment]
FGK-101 working in 0.8.20
