### ISSUE TITLE
[bug][1.3.0rc11] Ok Homey not triggering voice recognition

### ISSUE THREAD

**Issue by jaimevisser** [athombv/homey#1612]
**What is your Homey version (Settings → System)?**
1.3.0rc11

**What did you try to achieve?**
Trigger voice by saying "ok homey"

*Please include detailed steps how we can reproduce the issue*
See above

**What was the result?**
Homey didn't start listening

**What did you expect as result?**
Homey starts listening (as indicated by leds)

**Any other remarks**
None

**Please attach a Homey System log (Settings -> System -> Send Log)**
0F890A32C5

**Comment by jeroenvollenbrock** [comment]
Did rc12 resolve the issue for you?

**Comment by jaimevisser** [comment]
Will check when I get home ;)

**Comment by jaimevisser** [comment]
Yep, Homey is responding again.

**Comment by satbopper** [comment]
way to fast to close this,for me in rc12 still an issue and for you jaimevisser after a few days it will be back

**Comment by jaimevisser** [comment]
Will keep an eye on it then ;)

**Comment by Marc1979** [comment]
Having same problem (leds are not reacting overhere). 
Talking to homey thru android-app / FB messenger is working, but HOMEY-IP/Manager/Speech-input is also not working.
System-file is very low (reboot yesterday) -> 163MB..

It was happening after the google-chromecast was crashed..

**Comment by jaimevisser** [comment]
My problems have not come back yet, now on 1.3.1

**Comment by kukel** [comment]
Have not experienced this either on 1.3.1 nor 1.3.2

**Comment by satbopper** [comment]
for me in 1.3.2 still an issue,one thing to mention is that after an app crash it happens always

**Comment by JerryVdV** [comment]
same here, Homey does not react to the voice trigger..
also on 1.3.2.
(log EE9DA41A19)

**Comment by Marc1979** [comment]
Again homey is not responding anymore (has a yellow ledring). 
Happend again when the system-file was above 400mb.
Everything else is still working...
(log:D5672CE1C7)

**Comment by Tweaqer** [comment]
+1 for Homey Firmware Versie: 1.3.2 log: 4F6A9F047D

**Comment by Amelsfort** [comment]
Same here this morning and yesterday. Also on version 1.3.2.
Log: 45A7CCC74B

**Comment by efriethoff** [comment]
Same here for some days on a row. Also on version 1.3.2. A reset will work for some time and it all starts over again.

**Comment by jghaanstra** [comment]
This issue still persists in 1.5.0-rc2.

**Comment by JerryVdV** [comment]
Same here.

**Comment by kukel** [comment]
I did not have this issue on 1.5.0-rc2  but do encounter it on 1.5.0-rc5

**Comment by jghaanstra** [comment]
Still present on 1.5.0-rc6. Is there some sort of quick workaround other than having to reboot Homey to get it to work again?

**Comment by jeroenvollenbrock** [comment]
Staged for rc9

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.

**Comment by powermarcel10** [comment]
I don't think that this issue is gone.. It still persist in my case.. It works for some time, and than, gone.. 

It's often after I say; Oké Homey I leave.. Than it will turn everything off, as I have configured in a flow, and after that, nothing..
