### ISSUE TITLE
[Z-Wave] Wake Up Interval value: 0 should be possible

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1613]
**What did you try to achieve?**
Have a battery device's wake-up interval on 0 but the range starts from the minimal step size (in this case (ZW074) 240 seconds, but have seen more devices use this)

**What was the result?**
The setting save button disables since 0 is not in the specified range even though 0 was the default wake up time.

**What did you expect as result?**
0 should be possible according to the specs, though it's not really a good thing, it shouldn't disable the save settings button causing confusion.

**Any other remarks**
Version 1:

> Values in the range 1..16777215 MUST indicate the time between Wake Up periods.
> The value 0 MUST indicate that the receiving node MUST Wake Up when initiated by an event
> determined by the application e.g. a pushbutton activation. 

Version 2 (and up) there is an extra addition to this rule:

> A receiving node SHOULD accept the value 0, even if the Minimum Wake Up Interval advertised by the
> Wake Up Interval Capabilities Report Command is larger than 0. If accepted, the value 0 MUST disable
> the timer-based transmission of Wake Up Notification Commands.

**Comment by WeeJeWel** [comment]
Fixed in v1.5.1

![screen shot 2017-08-30 at 18 24 09](https://user-images.githubusercontent.com/319873/29883384-6e2e6ee6-8db0-11e7-8f12-447a2dd9884e.png)

**Comment by daneedk** [comment]
This will save me some batteries in my doorsensors!
