### ISSUE TITLE
Plex app doesn't  work 

### ISSUE THREAD

**Issue by PeterBox** [athombv/homey#1615]
**What is your Homey version (Settings → System)?**

1.3.0 rc9
**What did you try to achieve?**

Installed the plex app to watch some movies locally 

*Please include detailed steps how we can reproduce the issue*

Installed  app , installed device everything so far 

**What was the result?**

The app couldn't  find the movies on the local pms
...

**What did you expect as result?**

...app to find the movies on my pas,  and I could  watch some movies

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by PeterBox** [comment]
I can't see any response  on the forum from athom,  that's why  I had to post it here

**Comment by bvdbos** [comment]
This app is not from Athom so you better post your issue at:
https://github.com/MikeOne/nl.kikkert.plex

**Comment by PeterBox** [comment]
That's not why  I post it here bvdbos. I want  response  from athom  not from you.

**Comment by PeterBox** [comment]
Read my comment in the forum regarding plex

**Comment by jeroenvollenbrock** [comment]
The plex app is not build or mantained by athom. The best place to report this issue is at https://github.com/MikeOne/nl.kikkert.plex
