### ISSUE TITLE
Homey says can't  find the tv.

### ISSUE THREAD

**Issue by PeterBox** [athombv/homey#1616]
**What is your Homey version (Settings → System)?**

1.03 rc11

**What did you try to achieve?**

 Ask homey to turn on the tv 

*Please include detailed steps how we can reproduce the issue*

Ask homey to turn on the tv,  homey response  is. 'Can't  find a television

**What was the result?**

After a few seconds the tv is turned  on, and homey's response is I have turned on the TV 

...

**What did you expect as result?**

Just turn on the TV. 

...

**Any other remarks**

...i use a flow to ask homey to turn on the tv ...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by abid-din-akqa** [comment]
Reported the same issue in the forum. This appears to have only started happening since one of the newer firmware updates.

**Comment by lubbertkramer** [comment]
@PeterBox @abid-din-akqa Did you use the logic card to find words you speak (contains)? You need to use the microphone card as stated in the update from 1.2 -> https://whatsnew.athom.com/#1.2 (card 4).  See also this post on the forum (Dutch) -> https://forum.athom.com/discussion/comment/52734/#Comment_52734

**Comment by abid-din-akqa** [comment]
Yes, flows had already been updated and the issue stick exists. Here's how my existing flow looks:
![screen shot 2017-06-05 at 4 04 55 pm](https://cloud.githubusercontent.com/assets/10119543/26807050/d2d6b9fc-4a08-11e7-95ee-31367716b419.png)

**Comment by PeterBox** [comment]
This is the Flow i use 


![juiste flow tv](https://cloud.githubusercontent.com/assets/20737747/26820677/f01c9bb2-4aa3-11e7-95f6-a60e80d621cb.png)

**Comment by bvdbos** [comment]
TV is a capability in 1.3 (so Homey knows the word without a trigger-card) but apparently there is no device as "tv" connected.... Like it's also done with lights...

**Comment by spoelly** [comment]
try "Televisie Kijken" or "zet televisie aan" than it will work

**Comment by PeterBox** [comment]
Ok , I will try it  thx

**Comment by PeterBox** [comment]
I have change my  flow,  it  did'nt  work

**Comment by harmstellinga** [comment]
You can try ( zet scherm aan ) that wil work.

**Comment by PeterBox** [comment]
OK I also  can try (zet monitor aan),but that is not the way I speak. I want to use tv or televisie.

**Comment by harmstellinga** [comment]
I agree, i have the same problem.

**Comment by swttt** [comment]
It all depends on the way how you added your tv as a device. It should get the class TV, then you are able to switch it on without using flows. I am not sure if Athom update their IR part, but it might be that if you added your IR device pre-1.3.0 it still has the wrong device class. If you add it again this maybe fixes this.

**Comment by PeterBox** [comment]
@swttt If you take a look at my flow above you see that I use harmony hub , my tv isn't added  as a device

**Comment by bvdbos** [comment]
It's logical: you have no devices with the television-class so Homey says she can't find a tv (built-in). However: then the spoken text is recognized en the actions are taken. For this to be solve you should re-add the hub and note that it's a television. However, best would be to be able to add the hub multiple times (one time for radio, one time for tv, one time for ..... (other device). Or it should be possible to turn off the tv-class...

**Comment by harmstellinga** [comment]
I have re-read my TV via infrared, but type is not recognized,UE46C6000 therefore manually press 15 times, then a new button will appear, which I renamed to TV.
But How can i see that it is added as class tv ?
For now its not working, HOMEY says ( kan geen tv vinden )

**Comment by swttt** [comment]
This is getting a long issue now...

I think it is a samsung tv, you could try brand Samsung and model just type TV. You get a result for Samsung most models. Check if this works...if not remove the buttons that don't work. Then add the buttons that aren't working/missing, and now just hope it gets added as a TV class. I am still not sure if a device from the IR database is really added as a TV class tho, but definitely worth a shot. (maybe someone from Athom can comment on this)

**Comment by PeterBox** [comment]
How does this help me ? No comment here from athom !  beetje jammer !

**Comment by swttt** [comment]
The issue is 6 days old, and can be called hardly an issue since it never has been implemented yet. Do note that the device class TV is added since 1.3.0 (might have been 1.2.0 not sure exactly).  I'll bet they will comment soon enough.

I asked Jeroen about it and they are working on this, so yeah it is helping you. Just have patience and use one of the mentioned work-arounds until they finished it.

**Comment by abid-din-akqa** [comment]
Definitely is an issue, considering the frustration that occurs. Also not clear when it'll be "officially" implemented.

I have tried adding a device in conjunction with the Samsung TV app and the issue still occurs - the samsung TV app also no longer appears to work, whereas it did before, though that's a separate issue since it's a third party app.

**Comment by PeterBox** [comment]
swtt don't call this hardly a issue. It is not for you to decide, this not a forum ! .I use speech  commands every day , and this is for me an serious issue. I  have tried  different solutions  but they don't work

**Comment by swttt** [comment]
Glad that i could help you guys trying to find work-arounds and getting an answer from Athom.

Just change it to something like "watch tv/tv kijken" then you can say "homey, i want to watch some tv" and it should work for now. Then wait until Athom implements the use of IR with the matching device classes.

 An issue is something that isn't working, this is more a feature request of something that they are working on already. But thats just my point of view.

Lets not continue to make this issue a mess, wouldn't make them finishing this sooner.

**Comment by PeterBox** [comment]
It was for me not a issue  in  homey version 1.02,  flow worked perfect and homey never said that couldn't find a tv. It became  a issue  with the newer  versions. And sorry  I'm not gonna say. "He homey ik wil wat tv kijken.

**Comment by lubbertkramer** [comment]
@PeterBox You are running experimental so don't expect support for features that are not yet released to stable and not yet completely documented. Also did they say that support is stable, experimental is for resting purpose so support will be different and not always in the speed you like it. 

For now it's weekend and Athom did let us all know 1.3 will become stable next week. So don't blame Athom for not responding when you choose too experiment but get used to use workarounds when you want to use experimental or return to stable. @swttt has given you enough options that work

**Comment by PeterBox** [comment]
Ik wacht wel op een antwoord van athom

**Comment by PeterBox** [comment]
Nee laat maar

**Comment by jeroenvollenbrock** [comment]
Homey version 1.3.2 will resolve this by disabling the error feedback "I could not find any devices to turn on/off" when flows have been triggered as well.

**Comment by PeterBox** [comment]
Ok  Jeroen thanks for the  explanation

**Comment by 2benl** [comment]
Is it also possible to disable build in status reply's when a flow is triggered? I use the sleep command to turn of lights/TV ect. I have a speech response with good night build in to the flow. Now Homey also says good night as a response to setting my status to sleep.

**Comment by swttt** [comment]
Did you try this already? It sounds like a workaround, that if A flow gets triggered it shouldnt act on build in response. But i Could understand this incorrect

**Comment by PeterBox** [comment]
Sinds 1.3.2 it works like a charm  for me

**Comment by 2benl** [comment]
When I say slapen, Homey says Welterusten and then starts my flow in wich I also let Homey say welterusten, so now it says it twice. This started when the status sleep and awake was introduced. I believe around 1.2. Off course I'm now using 1.3.2 and still experience this issue.
