### ISSUE TITLE
1.3-RC11 shown all Network-Devices

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#1617]
**What is your Homey version (Settings → System)?**
1.3-RC11

**What did you try to achieve?**
Add a new Scene with HueApp 2.2.4

**Please include detailed steps how we can reproduce the issue**
Made a new Flow and choose on the "then"-part the HueApp > No Scenes are shown. Going to Devices to add a new HueBulb > After selecting Hue and adding Bulb Homey asked for my HueBridge. Here shwon **all** Devices on my Network with their Ip-Adress. In Homey-Version 1.2.2 only the HueBridge was shown.

**What was the result?**
Couldn't select a Scene on the HueApp.

**What did you expect as result?**
Homey 1.3-RC11 didn't work anymore with HueApp 2.2.4.

**Any other remarks**
No.

**Please attach a Homey System log (Settings -> System -> Send Log)**
48D704F895

**Comment by CyberSponk** [comment]
> Here shwon all Devices on my Network with their Ip-Adress.
Need to correct this: The shown Ip-Adress is not of my Network. Didn't know what Ip's that are. For Example: My Network Ip's are 192.168.106.xxx. Looking into Homey as described above i see my HueBridge with Ip 192.168.106.30 and a lot other Devices with 192.168.1.xxx.

**Comment by bvdbos** [comment]
Is this still the case?

**Comment by CyberSponk** [comment]
Never seen since Hue 2.2.8 > So for me it's solved.
