### ISSUE TITLE
All Flows lost after updating RC12

### ISSUE THREAD

**Issue by CliffBroeren** [athombv/homey#1618]
**What is your Homey version (Settings → System)?**
1.3.0 RC12

**What did you try to achieve?**

Updated homey to Rc12

**What was the result?**

Update successful Nothing weird 
Homey wakes up and All the flows are gone. 
The devices and booleans etc. Still There

**What did you expect as result?**

I Wish I had my flows back :(

**Any other remarks**

...
<img width="1280" alt="schermafbeelding 2017-06-06 om 22 07 48" src="https://user-images.githubusercontent.com/28061478/26850576-52f95ba8-4b08-11e7-80e3-3c0f313896d6.png">

**Please attach a Homey System log (Settings -> System -> Send Log)**

59794A655C

**Comment by jeroenvollenbrock** [comment]
Your log shows the loss to have occured on rc11 (same issue as #1610, but with flows instead of user settings). Due to the corrupted settings, these flows cannot be restored. I did see you have the flowbackup app installed on your homey. Isn't it possible to use the app to restore your flows?
