### ISSUE TITLE
Somfy blinds do not respond properly.

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#1619]
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Moving RTS blinds by using existing and well working flows and devices.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The blinds move a few seconds (but longer than from a "shorter and normal signal setting) and then stop.
...

**What did you expect as result?**
The blinds to work as they used to for the past 3 months.
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
C0C3B9C8C6
(the latest executed flow is an altered version using two devices to adress one blind each; used to contain the device which has been paired to control both) 

...

**Comment by JPe2** [comment]
![image](https://user-images.githubusercontent.com/3833862/27102843-037fb0f2-5087-11e7-90c3-3d1b252ecd55.png)

**Comment by Povlov** [comment]
Thank you for thinking along!
I have been tinkering the settings and inactivating suspect flows doing repeat Short Signal commands (to change the position of the horizontal louvres) and half-travels.
The Long Signal per screen is now performing a full up or down correctly. Combined screens (paired with all leds on on the TELIS 4  remote control) tends to leave one screen behind, causing a strange stop position as if a "my" location is accidentally programmed.
I have now set up a scheme to introduce the inactive flows to find out where the problems re-occur.
My screens need app. 80 seconds to fully close/open, so to avoid overheating and extra wear it will take some days to observe the result of regular runs these flows.
Of course I will update the results here.

**Comment by JPe2** [comment]
@Povlov 
your last words were "Of course I will update the results here." Already results?

**Comment by Povlov** [comment]
One of the screens (motor closest to Homey, 3 mtrs) still is frequently not-responding, and often does not go up beyond a specific point. I expect this is a mishap in the screen. I still have 1.2.2 running, as I do not like to update with another change in functionality.
Meanwhile I made a flow with 2 cards; Up and followed with a STOP. The movement is very comparable with the step with the previous "short" signal. Two of those shots set the blade in a horizontal position, which is nice.

I am interested to learn how the latest update works for others. (it should include my "step" in the "shortest" signal again...)
