### ISSUE TITLE
Changing brightness of lights also changes colors

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#162]
I used the voice command "dim lights to 20%". That worked to my delight, but it also changed the color of the lamps from different colors to all white. That was not what I requested. I expected only a change of brightness levels, not a change of color.

**Comment by WeeJeWel** [comment]
That definitely shouldn't happen, and is a bug in the Light's app. Which app are you using?

**Comment by AndreSomers** [comment]
This is using Hue.

**Comment by WeeJeWel** [comment]
Can you try again?

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue, as it seems resolved. If it is not, please reopen.
