### ISSUE TITLE
[Feature] use tokens on 'repeatedly press a button' action card

### ISSUE THREAD

**Issue by Dom2061** [athombv/homey#1621]
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
Press a button several times using voice command and Numcatch
*Please include detailed steps how we can reproduce the issue*
Construct a flow with a voice command such as "volume up seven", so that the result is the volume up button is pressed seven times, (And, of course, the number can be any amount).

**What was the result?**
There doesn't seem to be a simple way to do this
...

**What did you expect as result?**
If the "how many times" field, (In the "repeatedly press a button" card), could accept tokens from NUMCATCH, I believe this may be simple to achieve
...

**Any other remarks**
As a disabled person, I need to be able to operate every function on my AV system by voice. This includes menus where I need to be able to move the cursor up and down by a certain number of presses, and volume et cetera.
I hope that being able to use a token in this way will provide an effective solution.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Which app or device has the `repeatedly press a button` card? If it's a number, then a number type token (blue) should be able to be dropped on it.

**Comment by Dom2061** [comment]
The device is a Sony HT IS-100 and I copied the remote manually.

I think I am probably not using NUMCATCH correctly, do you have any hints how I can make the above voice command work in the way I need it to?

Many thanks for your help.
Dom.

**Comment by Dom2061** [comment]
feedback given

**Comment by bvdbos** [comment]
Numcatch is not something from Athom itself 
https://apps.athom.com/app/openmindnl.numcatch 

but maybe @Tweake has some thoughts about this already?

**Comment by bvdbos** [comment]
This flow produces a numeric 7 on my phone so I guess the IR part works too:
![2017-06-23 18_49_28- 833 flow - homey](https://user-images.githubusercontent.com/1064079/27493145-f2abdd40-5848-11e7-99c0-567cb33063a5.png)

but you have to send the text to numcatch first:
![2017-06-23 19_11_46- 833 flow - homey](https://user-images.githubusercontent.com/1064079/27493133-e32c0246-5848-11e7-88d4-62ea1c67e6c8.png)

and you have to make sure you have numcatch translate text to number with the mark:
![2017-06-23 19_17_18- 833 settings - homey](https://user-images.githubusercontent.com/1064079/27493127-dec79558-5848-11e7-97dc-a5e84e306591.png)

**Comment by Dom2061** [comment]
Thank you very much bdvbos, I'll try and follow your screenshots as soon as I get the chance.
Yes, the issue can be closed, (mainly because there wasn't an issue with Homey at all: just my ignorance and inability to find any written instructions),
regards,
Dom
