### ISSUE TITLE
Google Chromecast crash

### ISSUE THREAD

**Issue by hnijveen** [athombv/homey#1622]
**What is your Homey version (Settings → System)?**

1.3.0-rc.11

**What did you try to achieve?**
Nothing. The app crashes multiple times per day

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...3DE725C336

**Comment by jeroenvollenbrock** [comment]
Your log does not show any crashes, did you send it right after the app crashed?

**Comment by ruudcornelisse** [comment]
bij mij het zelfde probleem app blijft crashen

**Comment by hnijveen** [comment]
I'm not sure. The app crashes at least once a day. I am not continuously monitoring the app nor Homey

**Comment by dmpcc** [comment]
I just posted a crashlog on the referenced thread (2A28294978)

**Comment by hnijveen** [comment]
What I 'm sure of: App consumes a lot of mem, crashes every day. And this is going on foor weeks (5+ already). What to do? Every day a Homey reboot or are you willing to investigate some time (with my help if needed).

**Comment by bvdbos** [comment]
Hijacking this bug: https://apps.athom.com/app/info.matjaz.candy has a card for restarting a crashed app:
https://forum.athom.com/discussion/comment/52250/#Comment_52250

**Comment by hnijveen** [comment]
Thx @bvdbos, using Candy app to reboot Homey and restart of crashed apps. But the problem is still there (ofc. the impact is low now).

**Comment by hnijveen** [comment]
Result after 11 days: 11 daily reboots and 2 crashes of Google Chromecast per day
<img width="911" alt="screen shot 2017-07-06 at 10 26 18" src="https://user-images.githubusercontent.com/16666747/27902360-cbc85216-6235-11e7-8582-b398639f69c5.png">

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by hnijveen** [comment]
No, since 1.5.x it is ok. Homekit is now the app that crashes multiple times / w.
