### ISSUE TITLE
[feature request]    more device images per driver 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1625]
making drivers a lot of devices like oregon , visonic etc have the same input and logic and 1 driver is enough for all the devices. then it would be nice to have the possibility for more images per driver selected by type device .

**Comment by ArjanKranenburg** [comment]
I could not see documentation on this, but I found out that you can actually set the icon when pairing. So when adding a device, add it like:
```
		Homey.addDevice( {
			name: "new device",
			data: {
				id: "1234-abcd-efghijklmnop-1234-5678"
			},
			icon: "../../app/drivers/<driver>/assets/<icon>.svg"
		}, function( err, result ){ /*etc /* } )

```

**Comment by nattlip** [comment]
thank you @ArjanKranenburg
