### ISSUE TITLE
[Enhancement] Visual instructions for applying settings to battery powered devices.

### ISSUE THREAD

**Issue by jaimevisser** [athombv/homey#1635]
For many battery powered (z-wave) devices you currently get a suggestion to wake up the device if it is currently asleep. Many of these devices have rather unclear ways to wake up, and sometimes the way to wake up the device is different then what is suggested by the device manual (Fibaro keyfob for example). Some users get confused and need to file bug reports/ask on the forum/slack.

A possible enhancement would be to give a device specific visual guide for waking up the device when saving settings (in the same manner as the device specific guide for adding/removing devices).

**Comment by caseda** [comment]
I already added implementation for that in the zwave driver, only needs to be added in the driver which is very easy to do (and on the top of my todo list)

**Comment by caseda** [comment]
fixed with app update 1.5.4: https://github.com/athombv/com.fibaro/commit/79deda8c280a132ece07d5773a3b3360fb304a20

**Comment by WeeJeWel** [comment]
Yes, apps can show a custom message on how to do this, and this is the recommended way.
