### ISSUE TITLE
[Suggestion] If Then Elsethen Elsethen ... flows

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1636]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Manage my flows more easily and simplify creating complex behavior for advanced users.  

**What was the result?**

At the moment, multiple flows need to be "chained" together. It is a lot of clicking and it is hard to keep the overview. At the moment, it is not very inviting to do complex stuff.

**What did you expect as result?**

As discussed on the forum, the Else functionality is already a good step in the right direction, but it can go one step further by using a THEN-ELSE construction. (See screenshot attached).
- A flow can be "upgraded" to a "complex flow", replacing the "else" with "else-then". 
- When the "else-then" is used, another "else-then" becomes available to they can be chained indefinitely. 

![else-then](https://user-images.githubusercontent.com/5879533/27178982-d909875c-51cc-11e7-85df-4f7d62042a52.png)

**Any other remarks**

<3

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bm480** [comment]
Good idea, but I think it would make more sense to use If-And-Then-ElseIf-Then-...-Else. This matches the current implementation (If-And-Then-Else) with optionally one or more ElseIf-Then rows between the already existing Then and Else rows.

This also matches existing programming language constructs, for example in Python you have the following construct:

if <expr> then:
  <statement>
{
elif <expr> then:
  <statement>
}
[
else:
  <statement>
]

**Comment by bm480** [comment]
And why not adding support for a logical OR-construct? Where you could change the AND-column to succeed if either one of the conditions is true. The AND-column should be interpreted as additional conditions that satisfy the original trigger but individual conditions could be chained together using either logical AND or logical OR.

**Comment by kukel** [comment]
And multiple triggers on the same flow would help to (or'ed')

**Comment by AJediIAm** [comment]
Thanks for the feedback guys. As bm480 correctly noticed, I meant IF ... AND ... THEN ... ELSE-THEN ... ELSE THEN

**Comment by WeeJeWel** [comment]
'or' has been added some time ago. Multiple else columns is something we are not going to support for the sake of keeping things user friendly.
