### ISSUE TITLE
Can't say alle verlichting in de slaapkamer uit.

### ISSUE THREAD

**Issue by ljsvv** [athombv/homey#1638]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Turning all the lights of with the command Zet alle verlichting uit in de slaapkamer

**What was the result?**

Homey says, kan geen lampen vinden om uit te schakelen, renaming the zone "Slaapkamer" to anything else with saying the exact same phrase will do all the lights off! When renaming the zone to Slaapkamer homey again says kan geen lampen vinden om uit te schakelen...

**What did you expect as result?**

That the lights did turn off!!

**Any other remarks**

Renaming the zone should not be the solution....
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by ljsvv** [comment]
Please close this topic! Found the problem. There was a heater called Slaapkamer which caused that Homey thought it should turn of this device as a lamp. After renaming this heater it works!

**Comment by bvdbos** [comment]
As you opened this bug, you can close it too...
