### ISSUE TITLE
[Suggestion] IF ANY Flows

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#1639]
I think it would be pretty useful if there were IF ANY flows. Perhaps in the flow editor you could choose to use either the standard "IF" or the "IF ANY". 

Why would you want this?
Well, currently I have a lot of flows that do pretty much the exact same thing, but on different devices. Then you try arrange them in folders but you have so many that it super cramped in that tiny flow organiser window...
 Ideally, you could combine all of these into a single flow. 

For example:

I have about 10x Fibaro Sensors, and for each of these I have a flow which says:
"IF deviceA battery changes AND battery < 15 THEN send notification deviceA battery low". 

Now with an IF ANY, these could all be combined (although it would probably be useful to also add a device name tags as well)
"IF ANY (deviceA, deviceB, deviceC, deviceD) battery changes AND battery < 15 THEN send notification {device} battery low. 

I could think of a number of other scenarios, such as sending notifications for doors/windows that are opened when no one is at home; tamper alarms, smoke alarms, etc.

**Comment by rnldnkp** [comment]
Would be nice if there is some kind of list function, so it is not limited to devices.
For example, you could check:
- if all tags in a list are 0
- if all people in a list are away
- if all motion sensors in a list are not triggered
etc

You could do
if any, if all, if none, if >x number

**Comment by mruiter** [comment]
1.5 will have a generic device triggers. 
It's already in dev-preview

**Comment by bvdbos** [comment]
this is fixed now?

**Comment by Veldkornet** [comment]
Yup
