### ISSUE TITLE
Speech - Turn off all lights in Room No Longer Working

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#1640]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**
Get Homey to turn off all lights in a room.

*Please include detailed steps how we can reproduce the issue*
- Stand in front of Homey an look professional
- Say: "Okay Homey, zet het licht in de woonkamer uit" / Turn off the lights in the living-room
- Wait
- Homey responds "Ik kon geen lampen vinden om uit te zetten in de woonkamer " / I can't find any lights to turn off in the living-room

**What was the result?**
Homey says that it cannot find any lights in the Woonkamer
...

**What did you expect as result?**
Homey turned off the lights in the Woonkamer, as it did on version 1.1.9
...

**Any other remarks**
Strangely, it does work per floor. So if I tell Homey to turn of all lights on the "begane grond", then it works fine. I thought maybe it was a depth issue, so I moved the woonkamer to the same level as the begane grond, but that didn't work either...
Ie, my rooms are setup as such:
Homey
 - Begane Grond
 - - Gang
 - - Keuken
 - - Woonkamer
 - Eerste etage
 - - .........
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
FD8414BFE4 and 9297EDD7A0
...

**Comment by Wimstradamus** [comment]
Had the same issue, my lights had "woonkamer" (living room) in the name. 
i removed that part and now it works again.

**Comment by Veldkornet** [comment]
I don't have the room name in the device name, although I do have the word "lamp" included in the name. 

Still find it weird though that it works if you tell it to turn off everything on the floor.

**Comment by ljsvv** [comment]
Do you have other devices that do have the name of the room. I had the exact same problem and I found out that Homey tried to act my Heater called slaapkamer as a lamp. 

After renaming the Heater the "Doe alle verlichting in kamer X uit" phrase worked again.

**Comment by Veldkornet** [comment]
Arg, I didn't think about the other devices.... It was staring at me in the face! 
I have a Netatmo Weather Station, and the indoor module was also called Woonkamer...

Changed its name, and now it's working!

**Comment by elwin23** [comment]
Same issue and solution, my Chromecast was called woonkamer as well (and Plex plugin Chromecast as well)
