### ISSUE TITLE
Defect LED Ring

### ISSUE THREAD

**Issue by leroyneels** [athombv/homey#1648]
**What is your Homey version (Settings → System)?**

1.3.2 but defect is there since the very first update from 1.01

**What did you try to achieve?**
get led Ring turned off 
*Please include detailed steps how we can reproduce the issue*
not sure if you can, because there is one single light stil on white in any setting any mode 

**What was the result?**
no matter what one white LED keeps turned on even when in listen mode update or downloading
...

**What did you expect as result?**

...a working LED Ring not having a white light on all the time

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
807E5E301A
...

**Comment by jeroenvollenbrock** [comment]
Hi! This sounds indeed like a hardware issue. Can you please contact us at support@athom.com, along with a photo of the faulty LED, so we can resolve this issue for you?
