### ISSUE TITLE
Add option 90 minutes at alarm flow card trigger

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1649]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Turn on the central heater 90 minutes before wakeup

**What was the result?**

There is only an option to turn it on 60 minutes or 120 minutes in the flow trigger so I set it to 120.

**What did you NOT expect as result?**
So in the winter my apartment is 30 minutes before I woke up already a nice temperature.
A lot of gas wasted.

**What did you expect as result?**

That at the dropdownlist an option with 90 minutes is added

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

03B877BFD3

**Comment by WeeJeWel** [comment]
You can use 120 minutes and then a delay of 30 minutes in the action column.
