### ISSUE TITLE
BeNext dimmer sometimes half-grayed out and half-working then [0.8.17] (bug)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#165]
Using e BeNext wallplug dimmer, the UI is default grayed out, though the 0%..100% slider works. However, clicking the socket symbol does NOT work, it does not switch the dimmer on off. See the first screenshot:

![image](https://cloud.githubusercontent.com/assets/16608801/13020272/be18bd9c-d1d4-11e5-814d-18a7436d1427.png)

It seems like the UI "thinks" the dimmer is off, whilst it is on. Through the GUI you cannot fix this. However, when you switch the dimmer off physically, nothing happens in de GUI, but when you switch the dimmer ON physically, _then_ the GUI gets black, and also the on/off socket-symbol functions as an on/off switch, see the next screenshot:

![image](https://cloud.githubusercontent.com/assets/16608801/13020294/dd425386-d1d4-11e5-888f-bb3fc56612ac.png)

Secondary GUI/drawing/z-order problem, as you can see in the screenshots, part of the pop-up stays BELOW the neighbouring device.

Is there a relationshop with #16 ?

**Comment by WeeJeWel** [comment]
Card will never be shown underneath in 0.8.18

**Comment by athomey** [comment]
Very nice, now the other BeNext problems. :-)  Secondary UI problem fixed. I'll wait patiently for answer on my primary #165 report.

**Comment by ocatie** [comment]
Could you retry on 0.8.20+?

**Comment by athomey** [comment]
Will try it in a few weeks. Have got little time at the moment. Thx for fixing so far.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
