### ISSUE TITLE
App store, option for downgrading to previous version

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#1653]
https://forum.athom.com/discussion/3369/app-store-option-for-downgrading-to-previous-version#latest

RuudvB Member 10:03AM in Apps
Sometimes an automatic update of an app makes things worse, like today the new version of better logic keeps crashing. Although the developer fixed it very quickly, it takes some time to be available in the app store. Some apps are very widely en intensively used which can make a crashing version a real headache. A simple downgrade option would take pressure off the developer and the users :)

In addition to the new BETA version which we can install, why not make a downgrade button to the previous (good working) version? You would just have to check off the auto-update switch and do the downgrade. After that you can relax and monitor the forum until the issue has been fixed and upgrade again.

**Comment by swttt** [comment]
A step in the right direction might be forcing apps to use the github releases (so the source code is downloadable per version release). Then at least people can downgrade easier using the CLI

**Comment by Inversion-NL** [comment]
There is always a change the developer changed something that is not compatible with an older version resulting in crashes with the previous version.

**Comment by swttt** [comment]
If you delete the app and do a fresh install it should work with older versions tho.
But i understand your point, an update might add things to your devices (or changes things etc.) so the older version can't handle your devices anymore as well. And you don't want to do a clean install for BL for example :P

**Comment by WeeJeWel** [comment]
This won't be added. Installing apps from source is always possible if you must have this functionality.

**Comment by JPe2** [comment]
Can't find the source of Forest!!
