### ISSUE TITLE
Kaku is not working properly anymore, even downgrading is not stable

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#1654]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
A stable system, without suspicious updates which are not checked well by Athom before launching to live.

*Please include detailed steps how we can reproduce the issue*
Kaku devices (more then 50 in my house) doesn't react like expected after the upgrade on june 20th, even now i downgrade it it's still not working fine. Devices are not switched (in the flow they are marked green when testing) and new devices are hard to add to Homey.

**What was the result?**

Several flows are not working anymore

**What did you expect as result?**

I expect that when a flowcard is marked green the device is working, but unfortunately thats not reliable, in this case flows got mixed-up because of the wrong information in Homey that a device is switched (but in real it wasn't).

**Any other remarks**

After downgrading i did PTP and restarted Homey. It seems that there is a delay in the signals send by Homey or a delay in Kaku to receive Homeys commands.

**Please attach a Homey System log (Settings -> System -> Send Log)**

8145B031E7

**Comment by Ziglar1** [comment]
my issues were fixes in the update that came out like ~2 hours ago

**Comment by fvhuizen** [comment]
Problems are solved for me after updating to 3.1.4
