### ISSUE TITLE
[HomeEasy] Adding HE308EU shows label for missing text and missing settings to rotate

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1657]
**What is your Homey version (Settings → System)?**
1.3.2 /  1.4.0 Alpha 3 / HomeEasy 1.5.0

**What did you try to achieve?**
Add HE308EU

*Please include detailed steps how we can reproduce the issue*
Add it using the Wizard

**What was the result?**
![image](https://user-images.githubusercontent.com/12412734/27426238-42d47da4-573b-11e7-968d-aafba4e1ed2b.png)

See the deviceClasses.wall_switch.settings.rotated.label
after  Adding the Settings option is missing to Rotate the switch...

**What did you expect as result?**
A nice text and functioning identical to AWST-8802 ;-)

**Comment by BasKiers** [comment]
Hi,

Thanks for the bug report. This should be fixed with the latest version now in the appstore.

Regards,
Bas
