### ISSUE TITLE
No_playable_tracks

### ISSUE THREAD

**Issue by Jovink** [athombv/homey#1658]
**What is your Homey version (Settings → System)?**

1.4.0-alpha.3

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
I have made a flow with "Speel afspeellijst af" but after a couple of times it doesn't work any more.
For your information it is a Spotify playlist. And I use Sonos speaker. 
During the day I use Sonos\spotify on different speakers\devices (not at the same time)
maybe that has to do with it??  

**What was the result?**
No music when starting the flow. 
If I test the flow I get this message "No_playable_tracks"

**What did you expect as result?**

Homey starts the playlist... 

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

46DF47579D
![img_0002](https://user-images.githubusercontent.com/16411340/27452573-521ff66e-5793-11e7-82f2-88a9216535ad.JPG)

**Comment by jeroenvollenbrock** [comment]
Does it work if you assign a 2 second delay to the card?

**Comment by Jovink** [comment]
I didn't get the massage anymore. 
But If I make a wake up flow with a Spotify playlist it only works one time. 

No I use a playlist made on homey and I have no problem. But now I have only one Sonos speaker added to homey. If I use more then te flow doesn't always work. 
(the flow does work only the media part not)

**Comment by BasKiers** [comment]
Hi,

The issue of starting a playlist right after changing the speaker should be fixed in the upcoming Homey Media update.

Regards,
Bas
