### ISSUE TITLE
Fibaro Dimmer v2 bug when switching on, it incorrectly states 0% [0.8.17]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#166]
Fibaro Dimmer v2 bug when toggling it on through Homey's GUI, it correctly gets black (not grayed out anymore), but it incorrectly states 0%, which you can see in the screenshot where the dimmer is 100% on, but showing 0%. It's FGD212 v3.2 (so not v1).

![image](https://cloud.githubusercontent.com/assets/16608801/13020516/22419bda-d1d6-11e5-934a-8df9fd4b9f77.png)

The other way around, when toggling to OFF, the slider doesn't go to 0%, but the pop-up does gray-out. As you can see in next screenshot:

![image](https://cloud.githubusercontent.com/assets/16608801/13020613/aec3def6-d1d6-11e5-96b7-cd6badfda300.png)

I tried associating groups 2..5 to "1" and also to "1.0" (the latter was default for group 1). Both didn't work: 
![image](https://cloud.githubusercontent.com/assets/16608801/13020681/17484e6c-d1d7-11e5-9173-ac41db8ef223.png)

When reoping the pop-up, it _does_ update the UI correctly:
![image](https://cloud.githubusercontent.com/assets/16608801/13020710/385706de-d1d7-11e5-9a2c-09ec00a75d43.png)

**Comment by ocatie** [comment]
The bug is when the device is turned off by sliding the percentage to 0% and toggling it back on by clicking the image, the percentage isn't returned to the last value greater than 0%. This will be fixed but not soon. Minor bug.

**Comment by ocatie** [comment]
Fixed in 0.8.19

**Comment by athomey** [comment]
Thank you taco! Doing great work on the z-wave front-end. Love it how you keep on running this marathon! Keep it up!

**Comment by ocatie** [comment]
Thnx!

When the percentage is > 0 and you turn the device off, the percentage doesn't change but the card will be grayed out. This is intended because the dimmer device will return to it's last non-zero value when turned back on instead of full on (100%).
