### ISSUE TITLE
ELSE flow not fired when Ask for confirmation card is negative. 

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/homey#1660]
**What is your Homey version (Settings → System)?**

1.3.1 Stable

**What did you try to achieve?**
I have a flow with an ask for confirmation card. When it is answered positive, the THEN action is triggered. When the the ask for confirmation card is answered negative, I expect the ELSE action to be triggered, but it doesn't.

![schermafbeelding 2017-06-24 om 11 51 16](https://user-images.githubusercontent.com/15034038/27507794-45811f38-58d7-11e7-8654-eb09c9c2c92a.png)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The ELSE action doesn't fire when the ask for confirmation in the AND column is negative.
...

**What did you expect as result?**
When the ask for confirmation card is negative, fire the ELSE action in stead of doing nothing.
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Wijkie76** [comment]
I think the issue is in the flow itself. Any response is still a valid  "when"- criteria, it is always met.  So it will never go to "else". 
For it to do so would be nice though.

**Comment by bvdbos** [comment]
What is the message when you click the traingle?

**Comment by SkorpionNL** [comment]
@bvdbos, clicking on the triangle doesn't do anything. (Mac OS X app)

**Comment by bvdbos** [comment]
This works perfectly for me:
![2017-06-24 19_28_35- 839 flow - homey](https://user-images.githubusercontent.com/1064079/27510552-72ce7a44-5913-11e7-83d1-a6e33ab33193.png)
The red cross appeared when I said "no", when I answer "koekje" to the question the red triangle appears, hovering over it shows "inconclusive respons".

**Comment by SkorpionNL** [comment]
Hmmm, my Homey is acting strange anyway since 1.3.1. It goes offline all the time when reordering flows or making folders. This morning I had to reboot, because when Homey asked something via a confirmation card, it only asked the question and there wasn't a moment for me to respond. I will reboot once more to check if this is solved.
