### ISSUE TITLE
Capability flow cards Hue and Saturation, deleted?

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1665]
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Change/sync the Hue and Saturation of several lights (with tokens), with the previous available set hue and set saturation cards.

**Please include detailed steps how we can reproduce the issue**
Add a light class device with the light_hue and light_saturation capabilities in the "Then" column and scroll through the cards.

**What was the result?**
The previously available Set hue and Set saturation cards are not present anymore.
This makes it impossible to sync several bulbs to the same hue and or saturation.
Only possibility now is the color selector, where you can't place tags.

**What did you expect as result?**
Set hue and set saturation cards to be available still.

**Any other remarks**
Kinda curious who made the decision to just delete/disable these 2 cards without any notice

**Comment by WeeJeWel** [comment]
That is indeed odd! I've re-added them for you.
