### ISSUE TITLE
[Feature Request] Select multiple phones to send a push message/notification to

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1667]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
I would like to send the same notification to two different phones (my self and wife) from a flow with a single card for the notification. Now i can only do that with two cards one for each phone.

**What did you expect as result?**
I would expect that you could select the phones i would like to send it to. (also multiple selections)

So it is more a feature request ;)

**Comment by chrisboer** [comment]
You only need one card for each phone. 

Use variable string like this 

![afbeelding](https://user-images.githubusercontent.com/23163409/27657978-bd25ce7e-5c4e-11e7-821e-65b13d9bead3.png)

![afbeelding](https://user-images.githubusercontent.com/23163409/27658074-0a82a692-5c4f-11e7-99f6-cc6603876a5d.png)


If this is not what you mean please let me know

**Comment by spoelly** [comment]
This is not what i ment, it would be nice if you could select multiple phones in the notification card.

**Comment by bvdbos** [comment]
The effect is the same. Also, you could say the same for all other devices, lights etc. 

I would do this flow somewhat different. Use a special var "messagetomultiplephones" for the message.
* In the first flow set the message in "messagetomultiplephones"
* In the second flow: if "messagetomultiplephones" is set (or changed) then send message(s)

**Comment by spoelly** [comment]
that's a good one @bvdbos, for now i could use that but it will still be nice if the card could support multiple phones out of it self.

**Comment by Inversion-NL** [comment]
There is another advantage of @bvdbos solution:
When you change out your phone, there is only one place to change it in the flows

**Comment by spoelly** [comment]
You are right, i will close the issue.
