### ISSUE TITLE
If variable changed trigger not working

### ISSUE THREAD

**Issue by joostma** [athombv/homey#1673]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**

Create a flow where I used a tag in the 'a variable is changed' card as a trigger for this flow.

**What was the result?**

A change of the variable did not trigger the flow

**What did you expect as result?**

A change of the variable triggers the flow

**Any other remarks**

Tried with multiple variables, non of them worked.

**Please attach a Homey System log (Settings -> System -> Send Log)**

B1130335EF

**Comment by caseda** [comment]
You can't use tags as of yet (is on the todo list) you need to type in the name of the variable.

**Comment by joostma** [comment]
Perfect, I didn't know that
