### ISSUE TITLE
Toon

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1674]
**What is your Homey version (Settings → System)?**
1.3.2 -> Now 1.5.2 rc8 still same issue

**What did you try to achieve?**
Reinstall Toon

*Please include detailed steps how we can reproduce the issue*
Toon was not available reinstalled the app

**What was the result?**
No Toon device was reinstalled
![afbeelding](https://user-images.githubusercontent.com/23163409/27765890-fe027f1a-5ebe-11e7-8ba3-80326c5e4291.png)

**What did you expect as result?**
Toon device to be added

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
4E51D62B4A

**Comment by chrisboer** [comment]
By the way I login with a userid and not with an EMAIL address

**Comment by chrisboer** [comment]
Is there any progress on this or should we all just forget about TOON due to lack of support from ENECO

**Comment by RobinBol** [comment]
There is, actually a while back i re-wrote the Toon app for SDKv2 testing purposes, in the process I did some improvements/bug fixes as well, you can already side load it from this branch (https://github.com/athombv/nl.eneco.toon/tree/apps-sdk-v2-rewrite) if you want! I will be testing how it behaves in the long term, since some bugs are related to Toon going offline every once in a while, after that it will be updated in the app store.

**Comment by chrisboer** [comment]
Ok will test it

**Comment by chrisboer** [comment]
Installed it tested it I get an error message but I cannot make an screenshot of it.

7536D3424D

**Comment by RobinBol** [comment]
I can not see anything in the log, what does the error message say? Ah wait, you are on Homey firmware 1.3.2? Then it won't work, it is an SDKv2 app, which only works from 1.5.0 and up.

**Comment by chrisboer** [comment]
No I am on 1.5.2 rc8 and as I mentioned I cannot see the error as it is so quick of the screen (I don't have to confirm)

**Comment by bvdbos** [comment]
If it's a crash you get the same error in the settings-page...

**Comment by RobinBol** [comment]
Ah, read too fast.. Indeed check the settings page, or run the app with `athom project --run` and post the resulting logging.

**Comment by chrisboer** [comment]
Pffff what is this 
![afbeelding](https://user-images.githubusercontent.com/23163409/29610259-f2ac86d8-87f9-11e7-8f99-fce1d93512cc.png)

**Comment by chrisboer** [comment]
What is homey doing ?
![afbeelding](https://user-images.githubusercontent.com/23163409/29610447-75ee31a4-87fa-11e7-9bea-626f209af902.png)

**Comment by RobinBol** [comment]
Sorry don't know, but it doesn't seem Toon related. Try a reboot.

**Comment by chrisboer** [comment]
????? when I pressed CTLR-C it gave this ?
![afbeelding](https://user-images.githubusercontent.com/23163409/29610516-b355fcb6-87fa-11e7-9a5c-8c4284a9b8a9.png)

**Comment by RobinBol** [comment]
Seems to be running now right?

**Comment by chrisboer** [comment]
![afbeelding](https://user-images.githubusercontent.com/23163409/29610629-18708030-87fb-11e7-909a-e173460115ae.png)

I get this error now not even able to enter anything so rebooting and reinstalling and than try again.

**Comment by RobinBol** [comment]
Ah, forgot the app uses environment credentials. Could you PM me athom account email address on Slack? I'll create a alpha version for you on the app store.

**Comment by chrisboer** [comment]
Send you a message on Slack

**Comment by chrisboer** [comment]
Still an issue with "no new devices found" on Toon.

**Comment by RobinBol** [comment]
Hi @chrisboer the Toon app was recently updated in the app store, I also fixed an issue which could cause your devices not to show when pairing. So if you delete the app from Homey (important, as you ran some alpha/beta version of the app) and re-install the stable version from the app store this issue should be resolved. If you agree I will close this issue for now. If you still have issues, please place a comment so we can re-open if necessary. Thanks for testing and reporting!
