### ISSUE TITLE
[FEATURE] Switch for athom-cli to upload eg 1 file to debug  an app

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1675]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

uploading eg  one file to homey to debug an app

*Please include detailed steps how we can reproduce the issue*

use athom-cli to upload and debug app with athom -project --run 

set. homeyignore  eg to one file

**What was the result?**

setting .homeyignore to one file , athom-cli logs app.js doesnt exist etc etc and quits debugging

**What did you expect as result?**

to debug the file in the app on homey with files uploaded in earlier sessions
...

...

**Comment by WeeJeWel** [comment]
This won't be implemented, as syncing files is very hard and the gain is very small.
