### ISSUE TITLE
Error: invalid_capability_id when capability is overridden and not matching mobile-components

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/homey#1679]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**
I'm trying to add a device where the user can configure the class and the capabilities. To keep it simple for now, I have only capabilities "onoff" and "dim". And classes "other", "socket", and "light".

Upon pairing, I would add a device like e.g.:
```
{
    "name":"Other_onoff",
    "data":{
        "id":"d0e07567-539a-e530-c547-96dc7e20957c"
    },
    "class":"other",
    "capabilities":["onoff"]
}
```

In order to actually use the "other" class and toggle the on-off switch, mobile-components must be set in app.json.
However, the mobile-components must match the capabilities of the device **exactly**.

So if e.g. I specify the mobile-components as:
```
            "mobile": {
	            "components": [
	                {
	                    "id": "icon",
	                    "capabilities": [ "onoff" ]
	                },
	                {
	                    "id": "slider",
	                    "capabilities": [ "dim" ]
	                },
	                {
	                    "id": "toggle",
	                    "capabilities": [ "onoff" ]
	                }	                
	            ]
	        }

```
then trying to change the onoff value of the "Other_onoff"-device above, results in:
```
mobile.js:formatted:178 Error: invalid_capability_id
    at getCapabilityObject (mobile.js:formatted:387)
    at mobile.js:formatted:176
    at Array.forEach (<anonymous>)
    at mobile.js:formatted:174
    at Array.forEach (<anonymous>)
    at i (mobile.js:formatted:141)
    at mobile.js:formatted:324
    at mobile.js:formatted:409
    at mobile.js:formatted:414
    at Array.forEach (<anonymous>) 
```

**What was the result?**

See above. The device cannot be set. 
Also, the device cannot be used in the flows.

Debugging it, shows that it calls getCapabilityObject (in mobile.js line 386) is called with all the capabilities from the mobile-components. Then it errors because "dim" is not one of the capabilities of this device.

**What did you expect as result?**

Only the mobile-component with the capabilities that is actually used in the device should be shown in the GUI.

**Any other remarks**

When I leave out the mobile-components and add a light (class) with capabilities "onoff" and "dim", only a big slider is shown, not the toggle and slider.

**Please attach a Homey System log (Settings -> System -> Send Log)**

Upon request.

**Comment by WeeJeWel** [comment]
This is intended behavior. You can also overwrite the `mobile` property upon pairing to make sure the capabilities matches the components.

When using no `mobile` property, Homey defaults to the core-mobile component, which is dynamically generated based upon the device's capabilities.

**Comment by ArjanKranenburg** [comment]
Thanks!
