### ISSUE TITLE
Fibaro Dimmer v2 adding gives errors for 2 devices [0.8.17]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#168]
During adding of Fibaro Dimmer v2 I get an error that 2 devices could not be added, see error:

![image](https://cloud.githubusercontent.com/assets/16608801/13021192/08f0f938-d1da-11e5-982d-ecd669db20d5.png)

Issue #167 was _after_ the above errors, maybe there is a connection.

((Sidenote: This smells like an atomic transaction code smell...))

**Comment by ocatie** [comment]
Known (#129), will be fixed with an app in the future.

**Comment by athomey** [comment]
Alirght, when is this future app planned? I need to know this, so I know when I can continue my Domotica experiments with Homey. This is a showstopper for using it in any way with S1 and S2 switches to start different scenes and such, which now isn't possible? At the moment it can only be used as a basic dimmer?
