### ISSUE TITLE
Upgrading from App Store fails with "No resource exists on this endpoint"

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1682]
**What is your Homey version (Settings → System)?**

1.4.0-Alpha 3

**What did you try to achieve?**
Install pending Beta App over Alpha version.

*Please include detailed steps how we can reproduce the issue*
Happens with 
- Previous installed Alpha channel app 
and/or 
- Side loaded app  installd using developer tools.
Developed an app and published as Alpha, 0.1.1  installed it on DevHomey. 

Having installed/updated/fixed the code as 0.1.2, pushed to GitHub, Published it to the Store as Alpha.
Promoted to Beta, requesting approval. 
Wanting to install this on Homey I go to Appstore, select the version  [pending] [alpha] [beta]
Click install and select Homey, 
Have to install the Beta now although I wanted to stay in Alpha !!! 
(Loosing all my settings isn't that big problem for this App, but read below!)
Click install: 

**What was the result?**
![image](https://user-images.githubusercontent.com/12412734/27945887-4963e5d2-62ef-11e7-9540-0b3dfe1c322f.png)

**What did you expect as result?**
1) a question to choose to upgrade to newer version and/or overwrite the DevToolsInstalledVersion but keep the settings and stay in the Alpha channel. 
2) the app gets installed

**Any other remarks**

I want to keep my Homey App in Aplha and keep the settings, but upgrade to the latest version, although not jet approved. 
![image](https://user-images.githubusercontent.com/12412734/27945452-64c92bcc-62ed-11e7-9a41-4b32789b6764.png)

Having someone invited to the Alpha 0.1.2 he doesn't see that version anymore after I requested approval for Beta! My invite only see's the 0.1.1 ! while 0.1.2 is available for him.

Only option (for only the developer self) is installing to previous alpha channel and let Homey upgrade. 
but that fails at the moment ( #1676 )

**Please attach a Homey System log (Settings -> System -> Send Log)**
just for sure, after trying several times: 9FA3987DC0

**Comment by Dijker** [comment]
Did a version bumb to 0.1.3 for The Alpha channel, 
Tried to upgrade the DevHomey with the 0.1.1 already installed and that worked (where I got the error above for the 0.1.2 install) right away. No restarts or anything....

**Comment by Dijker** [comment]
trying to add Alpha Participants to the v0.1.4 but after update and refresh page all pre Submit approval participants are gone.... only the participant from before submit is still in the list. 

![image](https://user-images.githubusercontent.com/12412734/27948861-a64cfb92-62fb-11e7-9aba-ca90c6840904.png)

**Comment by lubbertkramer** [comment]
Installing 0.1.4 on Homey 1.4.0-alpha.3 results in error with no information

![knipsel](https://user-images.githubusercontent.com/8224586/27949352-ae5af0ee-62fd-11e7-9113-666eb45f8874.PNG)

**Comment by Dijker** [comment]
The Alpha channel version is visible again to the invite after approving by Athom and publishing by Author of the Beta App. 
Despite that the installed lower alpha version at two Authors Homeys still do not report updates available [disabled Auto Update] or automatically update to the latest published alpha version.

**Comment by joachimroeleveld** [comment]
You should now be able to install the app without any error messages. I'm reopening the other issue as it addresses the other concern which is unfortunately still relevant.
