### ISSUE TITLE
The day between Sunday and {next week} Monday doesn't work

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1684]
**What is your Homey version (Settings → System)?**

1.4.0 Alpha 3

**What did you try to achieve?**
Today it is Sunday,  Day between Sunday and Monday should be true. 
*Please include detailed steps how we can reproduce the issue*

![image](https://user-images.githubusercontent.com/12412734/27997115-a8939b20-64f1-11e7-97db-c307bab7e1e0.png)

but it doesn't work!

**What was the result?**
We have to Work around but that's not user friendly .

**What did you expect as result?**

both true!!

**Comment by WeeJeWel** [comment]
Fixed

**Comment by mruiter** [comment]
But its between and not between and the selected day. Or am inwrong. If you select between then thursday is not between it

**Comment by irritanterik** [comment]
Same with between sunday and friday, in that case the card still results in false (while its thursday now).
