### ISSUE TITLE
new google assistant functionality not working, and unclear how it connects to Homey

### ISSUE THREAD

**Issue by RGoooGR** [athombv/homey#1686]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.3.2

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

I have tested the new google assistant functionality with Homey, which was released today.

can you please give more detailed information on how google assistant functionality works in combination with Homey for android wearables and mobile phones. I have just tried it with my android moble phone via google Allo (-google assistant) and also via my android wear watch. Both do not understand what to do
do you need to configure something in your homey app or configuration in order for google assistant and homey to work together?

**What was the result?**

no result, it did not work

**What did you expect as result?**

that google assistant works with Homey
**Any other remarks**

Does it only work for English or also for Dutch language
please create a how to video with cleat detailed instructions and some examples.

**Please attach a Homey System log (Settings -> System -> Send Log)**

D230EC772F

**Comment by swttt** [comment]
Are you using google assistant in English? If so, is your Homey set to English as well? (Just to check, you never know 😀 )

**Comment by JPe2** [comment]
where is the App?

**Comment by WeeJeWel** [comment]
From the Speech page: 

```
To start, simply say “OK Google, let me talk to Homey.”
```

That's it :)
