### ISSUE TITLE
Tags from Weather Underground are dissapeared 

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#1687]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

In a flow i use the tags from weather underground to automate the process to manage the screens.

**What was the result?**

Suddenly the tags disappeared form the flowcards and also not available anymore in the tag puldownmenu

**What did you expect as result?**

...

**Any other remarks**

App is still running and reachable in the system settings. Even after reinstallation and a fresh installation the tags did not show up

**Please attach a Homey System log (Settings -> System -> Send Log)**

1909B69D62

**Comment by jeroenvollenbrock** [comment]
@Inversion-NL Can you maybe shed some more insights on this?

**Comment by Inversion-NL** [comment]
I register the global tokens after I receive weather data. Since you also miss data in Insights my best guess is there is something with your Weather Underground API key.
Haven't received any other reports about this issue and I've check 2 different Homey and their still updating the global tags.

**Comment by fvhuizen** [comment]
i removed the app meanwhile because i use more then 18 app's and Homey seems to have some problems to operate properly
