### ISSUE TITLE
[Feature request] Add day of the week as IF trigger

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1688]
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Feature request

*Please include detailed steps how we can reproduce the issue*
To add the day of the week as a trigger card 

![afbeelding](https://user-images.githubusercontent.com/23163409/28238212-286997e4-694f-11e7-8a84-d594fa087f63.png)

So if "Sunday"  then this .... 

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
That will only trigger at 0:00 hours... So then you can use time as a trigger and use day as a condition...

**Comment by chrisboer** [comment]
No you can say if sunday and 10:00 then ... bla bla because otherwise you check every day at 10:00 which is not required.
