### ISSUE TITLE
Time not correct when used in flow

### ISSUE THREAD

**Issue by newmedia** [athombv/homey#169]
I create a flow which anounces the time using a 
'if time is'
then 'speak 'Its bed time: {time}'

The speak command is 1 hour behind!

**Comment by WeeJeWel** [comment]
Is your location correct? (Settings -> Location) If so, does a reboot help?

**Comment by newmedia** [comment]
Yup location is correct and i rebooted this evening.

**Comment by WeeJeWel** [comment]
Can you make a screenshot of 'show stuff for geeks'?

**Comment by newmedia** [comment]
Sure.
<img width="944" alt="screen shot 2016-02-12 at 23 33 36" src="https://cloud.githubusercontent.com/assets/731226/13022355/2c4cd774-d1e1-11e5-8939-58c9ce451cba.png">

**Comment by Fieldhome** [comment]
Here the same kind of problem: My Homey is one hour behind. Currently the stuff for geeks is showing time 0:11. Local time is 1:11 though.

**Comment by evad1st** [comment]
related to: item #158 Server down [https://github.com/athombv/homey/issues/158]
Just tried a full reset, no changes, still one hour off, tried to fool Homey, by changing my location to london. but when I ask for the time .... he mentioned the "dutch" time.
after another (now "reboot") ---  now displays CET +1 (=correct, but in London) ...an when asked., he responds with the UK time ......
so put back to original location: (and reboot) as before (Homy system time is 1 hour back) the given(spoken by Homey) time is correct.
so looks like Home system does not compensate for DST ?

**Comment by matjaz** [comment]
It looks like you need to update location, from which timezone is set.
every time timezone is changed it's a good to do reboot.
flow voice should output you local time
in geeks info time is in UTC. currently we'r not in DST so most of us are in CET. (+1 from UTC)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
@WeeJeWel https://www.npmjs.com/package/reset-date-cache

**Comment by WeeJeWel** [comment]
Should be fixed since 0.10.7
