### ISSUE TITLE
Deleting Notifications lets the Homey hang

### ISSUE THREAD

**Issue by nicenemo** [athombv/homey#1693]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**
As a user  I tried to delete all notifications by pressing the all notifications buttons under the notifications menu.

Homey hangs.

**What did you expect as result?**

notifications deleted.

Deleting one by one can be done at a rate of 1 per second. However if you try this from a Chrome Browser console with the developer console open you see a lot of DELETE messages return witha HTTP 404. 404 is ok for a GET request but in this case deleting one item multiple times should give a 200.
Also the browser gets very busy. I expect there is some bug in the UI code too, e.g. event handlers that leak.

**Please attach a Homey System log (Settings -> System -> Send Log)**
3CA78DDAF5

**Comment by nicenemo** [comment]
Now deleting notifications manually. I suspect besides from double deletes causing 404s there may also be some duplicate entries in the presence notifications, just by judging how the windows app behaves. Have no way of checking  that is true.

**Comment by nicenemo** [comment]
Also the notifcations panel does not get updated when deleting  notifications manually.
![Uploading Capture.PNG…]()

**Comment by nicenemo** [comment]
Deleting an empty set of notifications does not crash the homey.

**Comment by dvanp** [comment]
Same issue here, on 1.5.0rc5. Trying to clear around 3500 notifications.
Console keeps mentioning over and over:
> WebSocket connection to 'ws://[homey.ip]/socket.io/?EIO=3&transport=websocket' failed: WebSocket is closed before the connection is established.

The request keeps pending and Homey becomes unresponsive. I've let it run until something happened and after 14.3 minutes I got:

> socket.io.js:4026 WebSocket connection to 'ws://[homey.ip]/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET
WS.doOpen @ socket.io.js:4026
Transport.open @ socket.io.js:2882
Socket.open @ socket.io.js:2303
Socket @ socket.io.js:2184
Socket @ socket.io.js:2110
Manager.open.Manager.connect @ socket.io.js:309
(anonymous) @ socket.io.js:619
api.js:1 GET http://[homey.ip]/api/manager/notifications/origin?_=1502448305571 net::ERR_CONNECTION_REFUSED

After this Homey becomes responsive again and after a couple of tries all notifications are removed.

A possible solution could be to remove large quantities of notifications in smaller batches?

**Comment by dvanp** [comment]
Oh great, I had the Homey desktop open when deleting the notifications from Chrome, and they were still there in the app, even after reload. Returning to Chrome they were there again as well..

**Comment by nicenemo** [comment]
Do they go away if you try to delete them slowely as in 1 by 1? if so then not that is what i am reporting here.

**Comment by dvanp** [comment]
They seem to be gone when deleting one by one, but a lot of 404's. After reboot all 3500 notifications are back, but not immediately, only after a minute and a refresh.

 It seems the UI registers the delete command, but the notifications are not removed from the database because the request hangs.

**Comment by nicenemo** [comment]
Do you wait a second between each delete?  That did it for me.

**Comment by dvanp** [comment]
Yes, I have to, because the scrollbar gets in the way every time and UI is very slow (probably because of the many notifications) 😉   It now seems that a few actually get deleted, but most don't.

**Comment by bvdbos** [comment]
related to #1708 ?

**Comment by bvdbos** [comment]
With RC6 this works for me. Rebuild of indexes in database...

**Comment by dvanp** [comment]
Issue persists for me. "Homey not connected" error after couple of minutes. Homey back online after about 5-10 minutes, notifications gone. Few minutes later: notifications back.

**Comment by dvanp** [comment]
It seems that my Homey gets very slow due to the many notifications.
Is there any update on if/when this could be fixed?

**Comment by dvanp** [comment]
For me the problem is solved after the 1.5.0 update: all notifications are wiped 👍 . Not sure if this fixes the underlying issue as well though. Maybe someone from Athom (@jeroenvollenbrock, @WeeJeWel) can confirm?
