### ISSUE TITLE
Buienradar server can't be reached

### ISSUE THREAD

**Issue by corvdniet** [athombv/homey#1694]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?
Ask Buienradar if it will rain

*Please include detailed steps how we can reproduce the issue*
(NL) Ok Homey, gaat het regenen

**What was the result?**
The buienradar app says "Sorry, Ik kan de Buien Radar server niet bereiken. Probeer later opnieuw alstublieft."(NL)

**What did you expect as result?**
An answer which tells me if and when it will rain

**Any other remarks**
Nope

**Please attach a Homey System log (Settings -> System -> Send Log)**

**Comment by bvdbos** [comment]
confirmed. According to https://www.buienradar.nl/overbuienradar/gratis-weerdata this was changed:
`[Update 20 juli 2017]: Afgelopen dagen gaf deze widget geen data door. Dit is inmiddels verbeterd. Gebruik hiervoor de url https://gps.buienradar.nl/getrr.php?lat=51&lon=3 en niet de onderliggende url. `

while some time ago they abandoned the gps.buienradar url so according to
https://github.com/athombv/nl.buienradar/blob/master/node_modules/buienradar/lib/buienradar.js#L94
the app uses a different url..

Aargh, they keep changing the url's

**Comment by bvdbos** [comment]
Added the issue in the correct repro. This one can be closed as this is an issue for the buienradar-app...

**Comment by mruiter** [comment]
Haha. Thx bvdbot. But just before it gets closed i can confirm the buienradar app broke once again 😛

**Comment by nattlip** [comment]
isnt this somethoing for the app section , i see sometimes moderators changing deleting redirecting posts as if thy were roomser then the paus

**Comment by BasKiers** [comment]
It should now be fixed as of version 2.1.1 of the buienradar app.

**Comment by corvdniet** [comment]
Confirmed. Thanks
