### ISSUE TITLE
Removed zones reappear with adding a zone

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1695]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Add and remove zones

*Please include detailed steps how we can reproduce the issue*

1) Perform a factory reset
2) Install a few apps
3) Remove any zones which are not needed.
4) Press the "Niewe Zone" button.

**What was the result?**

The zones which I just removes reappear in the list. 
I tried it several times. The behavior is consistant. 
See screenshot for the before (left) and after (right) pressing the "nieuwe zone" button.

**What did you expect as result?**

The removed zones should stay away. Only the new zone should appear.

**Any other remarks**

<3

**Please attach a Homey System log (Settings -> System -> Send Log)**
![untitled](https://user-images.githubusercontent.com/5879533/28492937-a899c570-6f0c-11e7-8fec-8582d7cc216b.png)

4570D37C67 and D9E3ACBF6C

**Comment by WeeJeWel** [comment]
Does this also happen after a page refresh? Maybe the network request was still busy.

**Comment by AJediIAm** [comment]
Hi Emile,

My Homey is now updated to 1.5 and the issue of reappearing zones no longer seems to occur.
 
When I tested it earlier, the issue was very consistent (20 out of 20), but I'm not sure if I tried refreshing the page. At the moment, the issue occurs 0 out of 20 times. However, I did notice that the order of the zones jumped around  when pressing the new zone button repeatedly (see screenshot). Do you want me to create a new bug for this?

![new zones bug](https://user-images.githubusercontent.com/5879533/28920580-b9fe57be-7852-11e7-8976-71c23e8672c4.png)

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
