### ISSUE TITLE
Not ready error

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1696]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

When I open the devices screen or music screen, I get a popup error with "not ready" (see screenshots
![music screen error](https://user-images.githubusercontent.com/5879533/28503115-a3f1fd0e-7000-11e7-890e-7c5248ac8b54.PNG)
![devices screen error](https://user-images.githubusercontent.com/5879533/28503113-a1b00676-7000-11e7-8811-1dbce8dd7719.PNG)

**What was the result?**

an error

**What did you expect as result?**

no error

**Any other remarks**

<3

**Please attach a Homey System log (Settings -> System -> Send Log)**

09FBEC86C9

**Comment by jeroenvollenbrock** [comment]
Does this problem still occur in Homey version 1.5.0-rc.2?

**Comment by AJediIAm** [comment]
The issue is solved in 1.5.0-rc.2
