### ISSUE TITLE
Request - option to schedule 433 Microcontroller restarts

### ISSUE THREAD

**Issue by psiebe** [athombv/homey#1697]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**
Having my homey respond consistently to KaKu switches

*Please include detailed steps how we can reproduce the issue*
Homey generally responds well to my KaKu requests, though occasionally, anywhere between once per two months to two weeks, homey starts to ignore me hitting the light switch. 

**What was the result?**
I was sad

**What did you expect as result?**
Homey to respond in a consistent way, 

**Any other remarks**
Following threads on the forum, a simple workaround for this issue is to restart the micro-controller (in all honesty, sometimes I need a full restart as well) While this is a simple workaround, it's a bit annoying if you just want to turn on (or off) the lights in a room. Becomes useless when I'm not at home and my girlfriend is facing the same challenge.

Would be great if I could tell homey to restart the micro-controller every Sunday night at a given time if that keeps reliability up.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by djeskoswe** [comment]
The candy app can do this.. When 0900 then restart microcontroller..

**Comment by psiebe** [comment]
Great! installing right away.

**Comment by Reemster** [comment]
Ok, sometimes that work, but most of the time it didn't fix the problem by me. I need to power down Homey every day now for getting the 433 stuff to work again. It's very annoying.

**Comment by WeeJeWel** [comment]
We won't add this, because we'd rather focus on just making it never crash ;-)

**Comment by psiebe** [comment]
agree, with you that would be even better :) glad there is a workaround for now though.

Thanks!
