### ISSUE TITLE
subzones not supported in flowcard set <devicetype> in <zone>

### ISSUE THREAD

**Issue by Heki2017** [athombv/homey#1698]
**What is your Homey version (Settings → System)?**

1.3.1

**What did you try to achieve?**

I have devided my livingroom zone in sub zones (tv-hoek, Eettafel, keuken). I would like to make use of the flowcard set <devicetypes> in <zones> for my lights, but unfortunately the subzones are not supportd in the flowcard, only the main zones

**What was the result?**

the result is I cannot separate the different lamps based on my sub-zones

**What did you expect as result?**

I hoped the sub-zones could be used as well

**Any other remarks**

on the ipad app and the iphone app it is the otherway around. I cannot get to the devices that are in a parent zone when there are child (sub) zones with devices

**Please attach a Homey System log (Settings -> System -> Send Log)**

No added value as there is not an error occuring

**Comment by WeeJeWel** [comment]
Do you mean that you want to e.g. turn on all lights in the living room AND all lights in the subzones of living room?

**Comment by Heki2017** [comment]
Hi Emile, thanks for coming back to me. No what I meant is, I would like to switch only the lights in a subzone but those subzones are not an option on the flowcard. Only the main (1st level) zones are shown.

Kind regards, Hedzer

Sent by iPhone, please ignore possible typos

**Comment by WeeJeWel** [comment]
Can you post screenshots of your zones list in the Zones & Devices view, and one of the dropdown?

I cannot reproduce the issue here, all (sub)zones are shown.

**Comment by Heki2017** [comment]
Hi Emile, zee attached screen shots, regs Hedzer

**Comment by WeeJeWel** [comment]
@Heki2017 I can't see any screenshots, please upload them on GitHub.com instead of replying via email.

**Comment by Heki2017** [comment]
Hi Emile I just saw that not all my (main)zones are listed. Is it possible that the dropdown is restricted to 8? Could that be the reason ? I have 10 main zones and 3 sub zones for ‘kamer’, but I can only select from 8 zones,

regards Hedzer

**Comment by WeeJeWel** [comment]
Please post a screenshot first :)

**Comment by Heki2017** [comment]
Ok

Kind regards, Hedzer

Sent by iPhone, please ignore possible typos

**Comment by Heki2017** [comment]
here are the promised screenshots:

![image](https://user-images.githubusercontent.com/26427299/28922976-3ebcc1a8-782a-11e7-8c58-3bee653f51b7.png)
![image](https://user-images.githubusercontent.com/26427299/28922983-448d5796-782a-11e7-9690-defb52076441.png)

**Comment by Arjanvde** [comment]
I'm pretty sure that if you hoover your mouse over the zone's  a scrollbar should appear. Sorting is done alphabetically. 

![image](https://user-images.githubusercontent.com/17526110/28923208-833ae598-785d-11e7-9563-e35713b94897.png)

**Comment by Heki2017** [comment]
Sorry guys to have bothered you. You are right there is the tiny scrollbar and I have overlooked it. Mainly because I am used to use arrow keys and when arriving on the last visible choice, normally the box will scroll up when there are additional choices. Again I apologise for issuing this request.

**Comment by WeeJeWel** [comment]
No problem, it might've indeed been more clear :-)
