### ISSUE TITLE
BeNext Zwave dimmer doesn't reflect changes to it in the UI

### ISSUE THREAD

**Issue by athomey** [athombv/homey#17]
If you change the dimming state of the BeNext Zwave dimmer to change e.g. on/off or the percentage, then the UI in de detail-pop-up of the device, doesn't reflect the changes.  Is there a relationship with #12

**Comment by athomey** [comment]
See screenshot: https://files.slack.com/files-tmb/T04E9KJ7T-F0J12JPTQ-ed0fdf4377/pasted_image_at_2016_01_08_01_33_pm_360.png

**Comment by ocatie** [comment]
Please try association group 2. See comment issue #12

**Comment by athomey** [comment]
I changed 1 to 2. It still doesn't work. Waited for 5 minutes. Also doesn't work. ((And i'm hindered by #16, but that's I'm still able to test group 2)).  In VeraEdge, I can also GET the parameter values. Then you can see if your group-association change e.g. came through correctly. I cannot see that in Homey, this is a big miss right now for me.

**Comment by ocatie** [comment]
There is a bug where the device settings aren't applied. I'm pretty sure the change group fixes the problem but at the moment you're not able to.

**Comment by ocatie** [comment]
Device setting bug is fixed with next update. Assigning Homey's device id to group 2 should fix it.

**Comment by athomey** [comment]
Will there be a feature like Vera and HC have, that you don't only see the setting you changed, but also the last read setting FROM the device? This makes solid configuration doable, otherwise you never know anything. Especially parameters which affect small things like those for ignoring a cat and such with a Fibaro sensor?

**Comment by ocatie** [comment]
That is something we have planned for the Z-Wave apps. Which configuration parameters are used is upon the device manufacturer and are always listed in the device manual. We can't simply poll all the possibilities. It would add too much time to the interview process.

An app will be able to provide the used parameters and those values will be fetched.

**Comment by athomey** [comment]
" Will be fixed in next version".  Wonderful.  Though please next time name an explicit version. Otherwise I don't know if I've been updatet to that version or not. Thx!
