### ISSUE TITLE
Z-wave: activate or remove aeotec recessed door sensor Gen 5

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#170]
I have trouble adding and removing a z-wave [Aeotec Recessed Door Sensor Gen 5](http://products.z-wavealliance.org/MarketCertification/File?folder=&filename=MarketCertificationFiles/1183/Recessed%20Door%20Sensor%20Gen5%20-%20Manual%20MCert.pdf)
After inclusion it showed as a device (node 3 in my z-wave network. It continuously reported the state 'Generic Alarm On'.
No updates were send to Homey (or processed). I set associations on both two groups of the sensor and woke it up to synchronize without any result.  
I rebooted and restarted the z-wave chip without any result.
After this i excluded the sensor. Exclusion succeeded (sensor itself signals it's not included anymore), but the device and node are still visible in Homey.
Now it's not possible to remove the failed node in any way. Tried restarting, power cycle, refresh, etc.
I have succesfully added the sensor as a new device (node 4), but this one also keeps blinking with state 'Generic Alarm On'.

**Comment by athomey** [comment]
((I have a few of these Aeotec's too, haven't tried them yet. Could try reproduction later. The blinking forever issue I have also with Fibaro sensor, read #161  However, I never removed/excluded the device. It got added correctly, but is unusable, always "Generic Alarm On" and always flashing red... maybe there is a connection?))

**Comment by irritanterik** [comment]
Looks like #167.
Z-wave screens and driver operations are very unstable at this moment. Window refreshes brake a lot of stuff, you'll have to add some good front-/backend thinking on this. We can help you a lot with bugfixing if more logging is available.

**Comment by athomey** [comment]
Well @irritanterik   the  ghost-device looks like #167  the generic-alarm-always-on-flashing-red looks like #161.

**Comment by irritanterik** [comment]
@ocatie Is this still work-in-progress? This is issue is open for 14 days now, without a comment from athom.

**Comment by ocatie** [comment]
Could you retry on 0.8.20 

Please power cycle and try to reproduce the problem. Then send us the log using Settings - System - Send Log, and post the given code in a comment.

**Comment by ralfvd** [comment]
Some forum discussion with a solution for the generic alarm issue (at least for some users) : https://forum.athom.com/discussion/comment/13296/

**Comment by irritanterik** [comment]
It's now solved. After reincluding and setting parameters on the device according to the forum topic ralfvd mentioned.
