### ISSUE TITLE
New folder gone after replicate flow

### ISSUE THREAD

**Issue by Reemster** [athombv/homey#1700]
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
Make a folder in an already existed directory/Folder

*Please include detailed steps how we can reproduce the issue*
I make a new folder, between other folders. and rename the new folder. and replicate an flow in a other folder, to move the flow in the new folder

**What was the result?**
When the flow was replicated in an already existed folder, the new folder what i make was gone after that.
...

**What did you expect as result?**
That the folder don't get disappeared
...

**Any other remarks**
none.

**Please attach a Homey System log (Settings -> System -> Send Log)**
C766C8C256
...

**Comment by SkorpionNL** [comment]
Maybe there's a connection with the following issue?
https://github.com/athombv/homey/issues/1655

**Comment by Reemster** [comment]
I almost forget: after a couple hours i found the disappeared folder, way down in the folder list. And the name was back to '**nieuw map**' so if i must guess, it was a homey performance issue at that time..

**Comment by WeeJeWel** [comment]
OK. Closing this for now :)
