### ISSUE TITLE
[appstore] version number

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1701]
**What is your Homey version (Settings → System)?**
Latest expirmental

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*
Install KPN IR-app (https://apps.athom.com/app/nl.kpn.ir)

**What was the result?**
![image](https://user-images.githubusercontent.com/20989897/28828109-051a0ef2-76d0-11e7-9627-d7454d5223fe.png)

**What did you expect as result?**
![image](https://user-images.githubusercontent.com/20989897/28828912-79f01e4a-76d2-11e7-8d01-cf879ef17bb1.png)
Edit: replaced a picture with a spaceman and a unicorn with this

**Any other remarks**
Please set this to 1.5

...
...

**Comment by swttt** [comment]
Uuuh, this is set to 1.5.0? 😮

**Comment by Tweaqer** [comment]
It says (the way I read it, but maybe i read it wrong): 1.0.3 is required to install this app. I would expect it says 1.5 is required to install this app in the top.

**Comment by nattlip** [comment]
it is version 1.0.3 date 31.... of the app , allthe new ir apps are .15 because they need the new ir api is a thing as  their zwave api

**Comment by nattlip** [comment]
you 
didnt read my remark of a week ago athom is living in the future and need some pills to get their feed on the ground ?

**Comment by Tweaqer** [comment]
I understand all this and I'm not commenting on it not being available or anyhting else; this is just a feature request to something like this:
![image](https://user-images.githubusercontent.com/20989897/28828912-79f01e4a-76d2-11e7-8d01-cf879ef17bb1.png)

**Comment by WeeJeWel** [comment]
Thanks for your request! Unfortunately this is something technically not possible, because an app's compatibility can be very technical, e.g. `1.x || >=1.5.0`. There is no nice way of displaying this in a human-readable fashion.

Therefore we choose to display compatibility per Homey. I hope it makes sense!
