### ISSUE TITLE
App (Nuki app) gone when there was a update

### ISSUE THREAD

**Issue by Reemster** [athombv/homey#1702]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.3.2

**What did you try to achieve?**

Don't know exactly. I get a message (via telegram) that there was a new update for the Nuki app. But after that i looked the whole App was gone from Homey

**What was the result?**
No Nuki app.

**What did you expect as result?**

That the app stay, when there is a update
...
**Any other remarks**

I PTP homey, but still the app was gone 

**Please attach a Homey System log (Settings -> System -> Send Log)**

000402D953

**Comment by WeeJeWel** [comment]
That is very strange, and I don't see any errors in your log. After you've installed the app again, did you have to re-pair all devices?

**Comment by Reemster** [comment]
I have only one Nuki lock. And only what i did after re-install was to configure the IP of the bridge and token, and the lock was working again. Very strange..

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
