### ISSUE TITLE
(Feature Request  ) extra capabilities for weathersensors

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1704]
1.  humidity_state

getable  true
setable true

title Humidity state

type        enum     
values     normal             'normal'
               comfort            'comfort'
               dry                     'dry'  
               wet                    'wet'

2 forecast_state 

getable  true
setable true

title Forecast state

type enum

values 

sunny  ' Sunny' 
partly    ' Partly'
cloudy    'Cloudy'
rain        'Rain'
          
   if accorded i can make a pull request to homey lib           
        
i cant make a pull request ther isnt an object capabilities only possible capabilities for classes

**Comment by WeeJeWel** [comment]
Those are a little bit ambiguous. I recommend you to make a custom capability of type `string` that is only `getable`.
