### ISSUE TITLE
Schrijf voudtje

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1706]
**What is your Homey version (Settings → System)?**

I'm am on firmware v1.5.0-rc.1, Dutch language interface

**What did you try to achieve?**
Openend the INSTELLINGEN and the INZICHTEN page

*Please include detailed steps how we can reproduce the issue*
I wanted to find out what was new :-)

**What was the result?**
I saw a typo:

<img width="622" alt="schermafbeelding 2017-08-03 om 09 55 23" src="https://user-images.githubusercontent.com/10754229/28911937-7642c958-7832-11e7-8083-5eaf294590a0.png">

**What did you expect as result?**

**Any other remarks**
The word 'te' should be removed.

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Thanks, fixed

**Comment by Keverjeroen** [comment]
'dataretentie' is one word in Dutch. ;) In English is are two words 'data retention'.

**Comment by bvdbos** [comment]
The "te" is fixed but @Keverjeroen is right about data retention and still there in 1.5rc5...

**Comment by bvdbos** [comment]
fixed...
