### ISSUE TITLE
Unable to switch on/off devices of HUE with homey while original HUE app works fine (homey app v2.2.5)

### ISSUE THREAD

**Issue by efriethoff** [athombv/homey#1707]
**What is your Homey version (Settings → System)?**

1.5.0 rc2

**What did you try to achieve?**
Homey updated to the newest experimental release and I tried to switch on/off my hue lights

*Please include detailed steps how we can reproduce the issue*
I went to my mobile app on android and checked the app my.athom.com to see what is going on.

**What was the result?**

Homey reports my lamps "onbereikbaar" and I can't operate the lamps anymore with homey.

**What did you expect as result?**

My lamps to go on and off.

**Any other remarks**

I tried to add a new lamp, but homey reports the bridge not available. I checked it with the HUE app and that app reports no issues and I am able to operate all the lamps as expected.

I also updated the HUE app on homey to v2.2.5 but that had no solution to this behavior.

**Please attach a Homey System log (Settings -> System -> Send Log)**

41ADCD36F1

**Comment by WeeJeWel** [comment]
When you try to add a new device and select your bridge, does it ask to push a button? If so, try that, and see if your other lights come back again.

**Comment by efriethoff** [comment]
I just pressed the button on the bridge and followed the suggestions in the forum, but unfortunately nothing changed. Homey does not see my bridge, while the app of HUE sees the bridge and is able to switch everything on and off...
I just restarted the homey to see if that would make a difference, but still same status.

**Comment by Fire69** [comment]
Same problem here.
When trying to add a new light (so Homey would ask to push the button) it just says it can't find any bridges.

**Comment by rtnartna** [comment]
Same over here, with same Homey firmware version and Hues app. Also connection to all my Hue lamps are broken. When trying to add new bulb no bridge was found. Pressed button on bridge, makes no difference. Bulbs can be switched on and of with original Hue app on Android.

**Comment by robiebab** [comment]
same here can't find the bridge

**Comment by robiebab** [comment]
installed previous commit and that works so it is not related to the homey update only to the app update

**Comment by caseda** [comment]
here running the latest hue update but homey fw 1.3.2 and that still works, so it is a combination issue

**Comment by WeeJeWel** [comment]
This should be fixed with the latest version (2.2.6)!

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/55902/#Comment_55902
