### ISSUE TITLE
[1.5.0-RC2] Insights make Homey crash

### ISSUE THREAD

**Issue by marcelwolf** [athombv/homey#1708]
**What is your Homey version (Settings → System)?**

1.5.0rc2

Call Insight menu

Go to Settings -> Insight

**What was the result?**
Keeps loading and after a few minutes the homey is unreachable
...

**What did you expect as result?**
i dont know. 
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
F8910A7F4D
...

**Comment by djeskoswe** [comment]
Does have the same problem,  but starting to respond after 2 min... 

Will send log when I'm home

**Comment by pdreissen** [comment]
Same issue here: 5532C882A7

**Comment by swttt** [comment]
How quick after the update to RC2 did you tried?
Maybe the insights migration is still running..

**Comment by pdreissen** [comment]
I got the popup busy_migrating first. Upgraded more than 1 hour ago already !

**Comment by pdreissen** [comment]
Let's rephrase this: i'm not getting the busy_migrating popup anymore ;)

**Comment by marcelwolf** [comment]
I am still having the same problem

**Comment by swttt** [comment]
Curious if you still have the issue tomorrow, took a while here (migration)...
The plus side, it works better afterwards. And you are able to remove old data :P

**Comment by djeskoswe** [comment]
@swtt does your storage info under settings - insight show data?   my hangs when trying to look

**Comment by swttt** [comment]
@djeskoswe ooh no that works, but takes a while 😁 it's shows allot of data...just give it some time.

**Comment by swttt** [comment]
@marcelwolf Might be nice to edit the title tho! 😀 like `[1.5.0-RC2] Insights make Homey crash`

**Comment by Fire69** [comment]
Almost 24 hours later, still the same problem.
Don't think the migration takes that long?

**Comment by djeskoswe** [comment]
Same here,  no insight data shows under settings --> insight and homey offline popup

**Comment by bvdbos** [comment]
yep, me too... Log: 594D093DE8
Load avg now: [3.7685546875,3.53662109375,3.10205078125]
I noticed while waiting for loading settings-insights, pages take a long time waiting for available sockets. I also see this on settings-stuff for geeks : nothing happens and then suddenly the values get refreshed like 50 times in a few seconds...

**Comment by marcelwolf** [comment]
I've got 641MB on Insight data.
24 hours later Homey still crashes ;(

**Comment by djeskoswe** [comment]
570 mb insight , did try to delete the insight under settings but did not work.

Hopefully will there be a fix soon

**Comment by glijie** [comment]
from 80 MB insight before 1.5rc2 to over 400 MB data insights over here..
Deleted al insights data but  still insights takes 380 MB of my memory.

**Comment by Wijkie76** [comment]
Same issue here. Homey isn't accesable because it's offline and continiously loading... Migrating a year of insightdata takes just as long it seems.... really hope this gets fixed soon.

**Comment by homdom** [comment]
also 679 MB of data :( after migration

**Comment by bvdbos** [comment]
Guys, there's a difference between migrating and loading insights. 

During the update to 1.5 Homey migrates the sql-database which it has internally to a new format. This can take up to two hours for a >1 GB database.

There is an issue loading the data like @marcelwolf stated : Go to Settings -> Insight and Homey keeps loading while after some time you get an "Homey is offline" while it isn't... But this has nothing to do with the migrating as such, that has already finished. Also this only happens when going to "Settings -> Insight", doesn't it?

**Comment by Fire69** [comment]
Insights takes up only 275MB for me.
Still, when I go to Settings - Insights it keeps loading and after a couple of minutes Homey goes offline.

**Comment by Wijkie76** [comment]
Ran it the whole night to find Homey crashed. Had to do a reboot and now it's running again, probably for hours and hours. A fix for me would be to let homey ask if you want to keep your insights before migrating or at least a progress bar.

**Comment by bvdbos** [comment]
@Wijkie76 Do you mean while updating to 1.5 or when opening "settings-insights" ?

**Comment by Wijkie76** [comment]
@bvdbos I mean before Homey starts migrating so perhaps a warning before updating. And when you do decide to update you get a progressbar for the migrating bit. 

Now 2 hours further homey's ledring still rotates orange, but I do not know if it's really processing anything at all or in a loop. Also i do not know how long it will take.... Homey  still isn't connected. 

Don't think this "migrating" feature should be released like this in a stable version.

**Comment by Wijkie76** [comment]
@bvdbos ...it crsahed...

43E47493DB is the log

**Comment by bvdbos** [comment]
@Wijkie76 If you mean while installing 1.5 (and thus you still are on 1.3.x), could you open a separate issue for this. That's different from opening settings-insights...

I tried to open settings-insights once again, was running for a couple of hours with >3 loadavg when an error appeared:
![2017-08-05 16_55_23- 51 settings - homey](https://user-images.githubusercontent.com/1064079/28996370-71f137a8-79ff-11e7-82f1-ff6ac13a9187.png)

I wasn't at home at that time but may be the same time I got a message from the Homey-app just saying "crashed".
Log: B48B329804

**Comment by Wijkie76** [comment]
@bvdbos Nope 1.5.0rc2 is installed.... and the issue accured afterwards.

**Comment by Wijkie76** [comment]
@bvdbos could it be the zigbee driver is the problem? It doesn't seem to connect, it continues loading, as far as Homey let's me see.. ca 240 sec. If so homey loses connection, no? Then it's not a migrating problem.

**Comment by bvdbos** [comment]
Zigbee is working for me, seems to be a onetime-thing. Now on 1.5rc4 again unable to open database file and some phonemessages saying "crashed"... Log D4D64074A8

**Comment by marcelwolf** [comment]
I have installed the new version 1.5rc4 but when i go to the Insight page Homey still goes Offline.

**Comment by robertraaijmakers** [comment]
Same here, updated to 1.5rc4 but Homey still gives the following message when going to the insights settings pane (after +/- 1 minute).

![screen shot 2017-08-09 at 20 07 44](https://user-images.githubusercontent.com/1773099/29136827-b1f466c6-7d3e-11e7-8ef4-cb65ff0d186e.png)

**Comment by djeskoswe** [comment]
a friday log 12924A04EA   on 1.5rc4

**Comment by bvdbos** [comment]
I think the database of some people got corrupted or didn't get the goof update while going to 1.5rc's (me included). Don't know if the database-structure and state is send with the log's to Athom?

**Comment by Wijkie76** [comment]
I reverted to the stable channel for a day or two, then installed 1.5rc4... and it worked, finally. Lost all flows and apps on doing so, but still.  Although i think Homey is a bit sluggish...

**Comment by Fire69** [comment]
@wijkie76, wouldn't it have been easier to just delete your Insights data? 
You lost the data anyway now and you wouldn't have lost anything else :-)

**Comment by marcelwolf** [comment]
With the newest version 1.5.0 rc5 the problem is solved.

**Comment by bvdbos** [comment]
with rc6 my problems are solved.

**Comment by djeskoswe** [comment]
All good on my side now

**Comment by bvdbos** [comment]
A graph of about 200 MB of insights data (15 months energy-usage) took about 40 seconds so 👍
