### ISSUE TITLE
Development: Enable feedback logging

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#171]
I would like to have an option to enable "what homey hears" or something.
During development I can't see why Homey activates, but then doesn't do anything with the said commands. If there was a way to just see in text what he heard and other system logs, development would be much easier.

**Comment by athomey** [comment]
+1  (isn't Github for bugs only? software requests go through the forum Emile told me once, if I remember well)

**Comment by athomey** [comment]
See also feature requests in the forum: https://forum.athom.com/discussion/732/request-please-show-timestamp-last-run-of-a-flow-and-optionally-a-log-of-all-of-them-0-8-17

**Comment by WeeJeWel** [comment]
Go to http://{yourhomeyip}/manager/speech-input/

All incoming speech is logged there, and you can also input speech quickly by typing it.

**Comment by RuudBurger** [comment]
/manager/speech-input/ is empty for me.

**Comment by RuudBurger** [comment]
@WeeJeWel as a side note, that page and the speech recognition works WAY better.
Is that using the same software to detect? Because than there is something that can be improved on the microphone in the homey itself..
