### ISSUE TITLE
Sonos App Crashed

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1710]
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Nothing

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Sonos App Crashed
...

**What did you expect as result?**
App not crashing

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
3DEC9D0DC1

**Comment by satbopper** [comment]
all i can say,for me the update to 1.5.0.rc2 was the solution for the crashing apps,with all of the earlier firmware versions,after a reboot of homey the big apps like sonos hue ledring crashed within 30 min
after the install of 1.5.0 none,rock solid

**Comment by chrisboer** [comment]
Just installed 1.5.0 now waiting if @satbopper is right

**Comment by satbopper** [comment]
for me up to now i am right,it solved also that i can use the phone app again,i couldn´t speak to homey through the phone app anymore and now it works again
the question is for will it solve the issue of not reacting to ok homey,up to now yes
further my system memory is steady at a 150mb,usually after a day it went up above 250 and every day further
still no crashing apps,maybe sdk2 was the trick

**Comment by JPe2** [comment]
For me, playlist does not work anymore since 1.5.0.rc2, was working before!

**Comment by chrisboer** [comment]
Issue resolved
