### ISSUE TITLE
Water alarm missing

### ISSUE THREAD

**Issue by sjaakie33** [athombv/homey#1713]
**What is your Homey version (Settings → System)?**

1.5.0-rc.2

**What did you try to achieve?**
to use "appliance " in flow  for detection of water alarm

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
it's not installed
...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

please insert water alarm to the appliance "apparaat" at flow

**Comment by madmax75** [comment]
It's in the then column. Scoll down...

![devices_alarm](https://user-images.githubusercontent.com/29087006/28970522-24c312f2-7929-11e7-9f4f-881eea6342a9.png)

**Comment by bvdbos** [comment]
"then column"? But you're right, you have to scroll down the alarms to find it...

**Comment by madmax75** [comment]
Sorry, i meant the WHEN column..

**Comment by sjaakie33** [comment]
ok thanks guys missed that
