### ISSUE TITLE
Nefit Easy not to connect 1.5.0-rc2

### ISSUE THREAD

**Issue by homdom** [athombv/homey#1716]
**What is your Homey version (Settings → System)?**
1.5.0-rc.2

**What did you try to achieve?**
In 1.3 Nefit Easy works, Now in 1.5.0-rc.2 the icon say "NOT CONNECTED" 
I delete the Nefit Easy and try to reconnect wil give error See results

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Homey kon je Nefit Easy niet vinden, of dit apparaat is al toegevoegd, controleer of de gegevens hieronder kloppen en probeer het opnieuw.

Hint: mocht je de gegevens niet meer herinneren, kijk op de voorkant van je Nefit Easy handleiding.
...

**What did you expect as result?**
Connected Nefit Easy

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

59FC09C71C

**Comment by bvdbos** [comment]
Might be an issue for Nefit
https://github.com/athombv/nl.nefit.easy/issues

Did you reboot after deleting the device and app? And if that doesn't work, could you try PTP?

**Comment by homdom** [comment]
Sorry for de wrong place :) I Klikt bugreport.

I delete the app, reboot (ptp) and install again. Same problem :(

Is there an option to move the ticket to the Nefit place ?

**Comment by LMRM81** [comment]
Hello I have the same issue. Before the Nefit app was working properly but sinds 2 days it can't find the Nefit easy. Deleted the nefit easy and tried to pair again without any results.

**Comment by homdom** [comment]
In 1.5.0 RC5 stil the same problem Not to connect

**Comment by RobinBol** [comment]
Should be fixed in version 1.0.6 of the Nefit Easy app.
