### ISSUE TITLE
[enhancement] trigger when device comes online

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1717]
I use plugs to turn all devices off/on thus eliminating standby-usage. Devices which aren't powered are shown with the broken sign in the Homey-UI. It would be helpfull to have a trigger "when device comes online".  
![2017-08-05 08_57_29- 43 zones devices - homey](https://user-images.githubusercontent.com/1064079/28993953-6a49e870-79c2-11e7-8f82-42239e89a4c7.png)

My use-case (but there must be others): My stereo turns on in the morning. It takes 67 seconds before it has booted and gets its ip-adress. After that (delay-action) I send some IR-commands to set it to radio 1. However, I would like to set to volume through upnp (much more reliable then IR) but it's unknown when the upnp-device gets online so I can set the volume, therefore a trigger-card would really be helpful.

**Comment by WeeJeWel** [comment]
Devices actually default to online, unless the app specified that it's not. So a generic trigger would be very inconsistent. I'd rather give developers the possibility to add these cards when they feel those cards might be relevant.
