### ISSUE TITLE
issue deleting zigbee-devices

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1718]
I was stuck with a generic zigbee device (big dimmer from Ikea which isn't supported yet) which couldn't be deleted, nor by pressing the cross in devices and putting the device in pairing, nor by going to zigbee and choose "delete a device" nor by clicking the device in the graph and choose delete from therenor even by resetting the zigbee network. The device kept showing up in "devices". 

Now (while not having the ikea-app installed but don't know if that matters and after ptp which may be important) I could delete it by clicking the cross in devices, let it time out and then choose "delete anyway". 

Though disappeared from devices, the devices are still there when looking at the zigbee-info and graph:

```{"zigbee_ready":true,"zigbee_state":{"devices":[{"type":"Coordinator","ieeeAddr":"0x00124b0005f0136e","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1501912679},{"type":"Router","ieeeAddr":"0x000b57fffe24cb27","nwkAddr":29390,"manufId":4476,"epList":[1],"status":"offline","joinTime":null},{"type":"EndDevice","ieeeAddr":"0x000b57fffe213c5a","nwkAddr":10683,"manufId":4476,"epList":[1],"status":"offline","joinTime":null}],"net":{"state":"Coordinator","channel":11,"panId":"0xd2a8","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b0015f0136e","nwkAddr":0},"currentCommand":false}}```

Re-adding doesn't work (of course, it's already there in the zigbee-network). Then I tried again deleting the device from the zigbee-page with no luck. Finally, after deleting all devices from Homey-devices by letting them time-out and after that resetting the network, my network is clean again:

```{"zigbee_ready":true,"zigbee_state":{"devices":[{"type":"Coordinator","ieeeAddr":"0x00124b0005f0136e","nwkAddr":0,"manufId":0,"epList":[1,2,3,4,5,6,11],"status":"online","joinTime":1501920471}],"net":{"state":"Coordinator","channel":11,"panId":"0xd2a8","extPanId":"0xdddddddddddddddd","ieeeAddr":"0x00124b0005f0136e","nwkAddr":0},"currentCommand":false},"_stateTimestamp":1501920471603}```

Now having to come up with the exact issue ;-)

**Comment by bvdbos** [comment]
Unfortunately the dimmers are still there, no way to delete them. Tried resetting network etc multiple times.
![2017-08-06 11_32_53- 227 settings - homey](https://user-images.githubusercontent.com/1064079/29002178-09bb7240-7a9d-11e7-817d-d739f08a94a0.png)
Lights can be controlled but re-adding the dimmer isn't possible as the id already exists in the db and can't delete it...

**Comment by RobinBol** [comment]
This will be fixed in de next RC, after removal failed it will propose to force remove. If this does not solve you issue, please re-open!

**Comment by bvdbos** [comment]
confirmed fixed in 1.5rc6
