### ISSUE TITLE
Give feedback "ping" when starting listening

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#172]
The ledring is proper feedback when you can see Homey, but when I'm in the kitchen or on the dining table, my back is turned to homey. A small "ping" sound when "Ok, homey" was successful would help in proper feedback, and me not talking to myself because Homey isn't listening.

**Comment by irritanterik** [comment]
Can't you use the flow trigger 'When start listening' for this:

![image](https://cloud.githubusercontent.com/assets/15232724/13026725/94695246-d232-11e5-96e7-21bf946171f8.png)

**Comment by freemann** [comment]
Some sort of sound confirmation sound would be and perhaps could be a general setting in homey:
Do you want a sound conformation after "OK, homey"?  Checkbox

**Comment by RuudBurger** [comment]
Didn't  even think of this. But how do I get my own sound in there. Will check it out. Thanks for the tip

**Comment by domey** [comment]
Siri does this in 2 ways:
He Siri (pauze) results in a feedback indicating Siri is listening.
He Siri do action (pauze) results in a feedback indicating siri is processing the request.

(Explaining it seems to make no sense if I read it back, but in real life it works great)

**Comment by freemann** [comment]
Homey will stay next to hour TV and therefore in direct sight when watching TV. My wife is very sensitive for moving/twinkeling lights (candles) and so I think homey led ring will stay of in our livingroom. Therefore a audible confirmation of a OK heard "OK homey" would be very nice!

**Comment by pkonings** [comment]
In (#150 see screenshot) I tested the recommendation to setup a voice flow 'repeat what I said' which seems to works quite well as homey feeds back pretty well what I said.

Today I created a new flow (see below) with the same idea of voice confirmation feedback and Homey resume listening to tell what to do. Confirmation comes in (Homey: "what do you want me to do") but after that nothing happens although I get the impression Homey listens. I also used the App.

In addition, the previous separate flow repeating what I said doesn't work anymore in this testscenario.

![image](https://cloud.githubusercontent.com/assets/10164680/13027433/706673ec-d250-11e5-8ac3-3a1fa4fb00e4.png)

**Comment by jjtbsomhorst** [comment]
Would be nice to add the sound the computer from startrek TNG makes when an message is received ;)

**Comment by WeeJeWel** [comment]
Playing sounds through the Flow Editor will be supported pretty soon :)

**Comment by freemann** [comment]
that was not the question.
The question was;
"A small "ping" sound when "Ok, homey" was successful"

So after every well heared "OK, Homey", Homey give a simple "feedback" ping and the user knows he speak for a command.

**Comment by WeeJeWel** [comment]
Well, this will be possible from within the Flow Editor when you can play sounds from there :)

**Comment by freemann** [comment]
ok, so if i want my lights on when i'm standing in the kitchen;
I need to create an flow that plays a ping 
and
I want my TV on i also need a flow that plays a ping 

?

**Comment by RuudBurger** [comment]
I think you can make a global "ping" flow that get used for every other flow you create.
But i'm wondering if Homey will listen to this ping, and it interfering with the listen. As it won't be default behavior.

**Comment by bvdbos** [comment]
a "Ping" when Homey starts listening....

**Comment by WeeJeWel** [comment]
You just create a flow like this:
```
When
- Homey starts listening
Then
- Play a sound
```

So one flow for every time 'OK Homey' is heard.

**Comment by pkonings** [comment]
So why does my flow not work? It plays the 'sound' _"what do you want me to do"?_ and resume listening doesn't seem to do something...

**Comment by freemann** [comment]
I don't want to create a Flow for this, I just want to set a checkbox for a "OK, homey" ping.

**Comment by pkonings** [comment]
:+1:

**Comment by WeeJeWel** [comment]
@pkonings `Resume listening` enabled the microphone. I've renamed this card to 'Enable Microphone'

@freemann I'll consider it.

**Comment by freemann** [comment]
@WeeJeWel 
Thanx, that's highly appreciated!

**Comment by pkonings** [comment]
@WeeJeWel : Please advice your working flow in this scenario. THX in advance.

**Comment by domey** [comment]
I agree with @freemann it should be a checkbox. Thanks for considering it.

**Comment by jjtbsomhorst** [comment]
If it is gonna be a checkbox it would also be nice to have a list / upload to select which sound you want to hear..
