### ISSUE TITLE
Insights stops autoupdating in homey app and chrome after update 1.5.0   rc2

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1721]
**What is your Homey version (Settings → System)?**

1.5.0 rc2

**What did you try to achieve?**

watch the development of the temperature at home in insight

**What was the result?**

insights graph freezes instantly 

**What did you expect as result?**

watch the development of the temperature at home

is my hobby

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
Can you be a bit more specific?

**Comment by bvdbos** [comment]
What I noticed as a difference, new values seem to be written to the database while having the insights-graph open but the picture (geaph) doesn't refresh automatically (where it did before)...

**Comment by nattlip** [comment]
when i open an insight page with temperature values of a sensor, before the update , if a new value arrived in homey the insight presents the new value of the senor while watching the insights page. so the insights page is realtime liver representation of the sotred vlaues. after the update it doesnt update the time and sensor values anymore , you have to reopen the specific insight to see the new values

**Comment by jeroenvollenbrock** [comment]
fixed in rc5

**Comment by nattlip** [comment]
solved in 1.5.0 rc5
