### ISSUE TITLE
1.5 rc2 keeps loading Zigbee till reboot

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1722]
After a crash, I had to PTP. Now Zigbee keeps loading (graph en State empty). Log : 20AD01A380
Did a reboot, now Zigbee is online... Log: 35D047E0E9

**Comment by bvdbos** [comment]
If there's no interesting info in the logs, you might close this issue, don't have any more info how or why...

**Comment by Wijkie76** [comment]
My Zigbee doesn't connect it keeps loading... probably crashing my Homey the whole time

**Comment by jeroenvollenbrock** [comment]
Should be fixed in rc4

**Comment by bvdbos** [comment]
Didn't encounter it RC2 or RC4 anymore. If it works for @Wijkie76 then I'll close this one...

**Comment by bvdbos** [comment]
closing, @Wijkie76 is you still have this, please open a new issue
