### ISSUE TITLE
Unable to add Fibaro device (timeout when pairing)

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#1725]
**What is your Homey version (Settings → System)?**

1.5.0-rc2

**What did you try to achieve?**

Add a Fibaro motion sensor (FGMS-001)

*Please include detailed steps how we can reproduce the issue*

Select the Motionsensor Z-wave plus from the Fibaro app to add (homey waits for device to be paired)
Press the b-button 3 times (device goes into pairing mode)

**What was the result?**

Homey pairing times out after a while.

**What did you expect as result?**

The device and Homey should have paired.

**Any other remarks**

It is the first z-wave device I added since a factory reset.
I rebooted homey with no results.
I reset the z-wave network with no results.
I removed the device from the z-wave network. Removing procedure was successful. After that, the adding procedure was successful!

**Please attach a Homey System log (Settings -> System -> Send Log)**

0D97462354

**Comment by jeroenvollenbrock** [comment]
Pairing only works when the device is not already paired. Giving a factory reset to the Z-Wave network, does not unpair the device itself, but only resets the Z-Wave module of Homey, causing the device to think it is still paired, while Homey does not have any data of this device, therefore the removal procedure was still required. This is enforced by the Z-Wave protocol specification, so sadly there is nothing we can do to change this.

**Comment by AJediIAm** [comment]
That makes a lot of sense. Is there an FAQ for this?
