### ISSUE TITLE
It is not possible to pair KAKU Remote AYCT-102

### ISSUE THREAD

**Issue by LMRM81** [athombv/homey#1727]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.5.0-rc.2
KlikAanKlikUit app version: v3.1.5

**What did you try to achieve?**
Since the last update the KAKU remote AYCT-102 is not working anymore. I deleted the device and tried to pair it without any result. It looks like Homey doesn’t see the remote. New batteries and reinstalling the KAKU app didn’t help. Before the remote was working reliable. 

*Please include detailed steps how we can reproduce the issue*
1. install the KAKU app
2. Try to pair the KAKU Remote AYCT-102
3. Push a button on the remote

**What was the result?**
Looks like Homey doesn't "see" the remote. Green LED on the remote blinks but no Reaction from Homey. 

Moving closer with the remote to the Homey, New remote batteries, reinstalling the app, rebooting Homey ---> all did not help 
...

**What did you expect as result?**
A paired remote.
...

**Any other remarks**
Before the remote was working reliable. 
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Dijker** [comment]
Have you tried to Pull the Plug of Homey?
PTP is sometimes still necessary if the rf controller crashes.
Just un-plugg homey for 15 seconds, power up,  wait until everything is loaded and test again.

**Comment by LMRM81** [comment]
Hey Dijker,

You are right! The remote is working again. 
PTP solved this issue! 

Thank You!

Gr. Marcel
