### ISSUE TITLE
Logitech harmony hub

### ISSUE THREAD

**Issue by johansnellink** [athombv/homey#1729]
1.5.0-rc.2

**What did you try to achieve?**

I try to activate a activiteit on the harmony hub, but when i try to liust the activities, it gives error exclamation mark in red triangel and device.db.......

*Please include detailed steps how we can reproduce the issue*

Use the hub in a flow and try to activatie an actiuvity

**What was the result?**

.Error exclamation mark+code

**What did you expect as result?**

list of existing activities on hub

**Any other remarks**

.worked in older version.

**Please attach a Homey System log (Settings -> System -> Send Log)**

D1E3519CAC

**Comment by bvdbos** [comment]
This is an issue for the Harmony Hub app?
https://github.com/netactivenl/com.logitech.harmony.hub

**Comment by johansnellink** [comment]
ok i'll post it there.
