### ISSUE TITLE
Hue color card shows wrongly behind other cards (z-order bug) [0.8.17]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#173]
The card for color appears in wrong z-order, below another card. I will submit this to Github as a bug as well. Thx for the attention again and keep up the good work! :+1: 

![image](https://cloud.githubusercontent.com/assets/16608801/13026989/59f0588e-d23d-11e5-983b-c555a47847ad.png)

**Comment by soler2000** [comment]
This is also a problem for any card where you try to edit the top card it shows under the bottom card,  i.e changing the LED colour

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
