### ISSUE TITLE
Netatmo app can't connect

### ISSUE THREAD

**Issue by philsniff** [athombv/homey#1730]
**What is your Homey version (Settings → System)?**

1.5-rc2

**What did you try to achieve?**
netmao weatherstation working as before: without any problems

*Please include detailed steps how we can reproduce the issue*
just saw that my netatmo weatherstation devices are "offline" and i have to repair. (is writte on hover the device)

**What was the result?**
no repairing available, becaus when i just click to ad account nothing goes on. you can click thousand times ;-) without a reaction.

before 1.5 rc2 all went fine.

so i don't know if it is an firmeware problem or a app-problem or both?
...

**What did you expect as result?**

working weatherstation ;-)
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Dijker** [comment]
Same here but also for homey 1.3.2.
Adding myself again  reports:

getStationsDataError error: No response
You may close this window.

On both 1.3.2 as 1.5.0 rc2
Both NetAtmo App 2.1.1 and add in a new account doesn't work. 
But  looks like NetAtmo Api http://api.netatmo.net is down

**Comment by philsniff** [comment]
Ah ok. I have exact the same errors! Then we just have to wait that they fix the api on netatmo side.

**Comment by philsniff** [comment]
If the problem is on the side of Netatmo i will close this issue.

**Comment by bvdbos** [comment]
https://forum.netatmo.com/viewtopic.php?f=5&t=8702

**Comment by Dijker** [comment]
NetAtmo API is working again and both Homey's 1.3.2 and 1.5.0rc3  have a connection again after restarting the app and/or re-pairing

**Comment by philsniff** [comment]
Great. I will Test it but will close this issue because it doesn't Belong to homey. Thx @dijker
