### ISSUE TITLE
Auto-location in Homey Desktop doesn't work.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1732]
**What is your Homey version (Settings → System)?**

1.5.0-rc.2

**What did you try to achieve?**
Instellingen / Locatie / Vind mijn locatie automatisch

*Please include detailed steps how we can reproduce the issue*
Just do it.

**What was the result?**

A blurred NW-Europe map is shown and nothing happens.

**What did you expect as result?**

Zoom in to the location where I am... or at least put a label on the location.

**Any other remarks**

Tried the same in Google Chrome with Developer Tools opened.
Console shows: VM1561 util.js:222 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
should be fixed in rc4?

**Comment by OpenMindNL** [comment]
Nope, not fixed in rc4.

VM137 util.js:222 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
JB.j @ VM137 util.js:222
(anonymous) @ VM132 js?language=en:134
(anonymous) @ VM132 js?language=en:53
(anonymous) @ VM132 js?language=en:50
(anonymous) @ VM132 js?language=en:53
(anonymous) @ VM132 js?language=en:105
(anonymous) @ VM132 js?language=en:50
(anonymous) @ VM132 js?language=en:105
Sc @ VM132 js?language=en:52
Rc.jb @ VM132 js?language=en:105
(anonymous) @ VM143 stats.js:1

**Comment by bvdbos** [comment]
NoApiKeys-error is fixed for 1.5 rc6?

**Comment by WeeJeWel** [comment]
NoApiKeys is a warning that doesn't influence the behavior. The bug was on the back-end, which has been fixed.
