### ISSUE TITLE
No developers.athom anymore online

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1734]
**What is your Homey version (Settings → System)?**
1.5.0 rc2
x.x.x

**What did you try to achieve?**

open www.developers.com to do some research for programming sdk1 app

**What was the result?**

redirected to developr.athom.com sdk2 deocumentation

**What did you expect as result?**

that it was there , it is a golden rule on github and in the programmers society to see documentation for legacy sdks eg node serial port etc etc 

i hope that athom will comply to the social conventions of the programmers world

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by nattlip** [comment]
it is also a very serouos problem for programmers who want a stable system for a lot of understandable reasons , they dont have an sdk2 on their homey.

**Comment by bvdbos** [comment]
https://apps.developer.athom.com/v1/library.1.html

**Comment by nattlip** [comment]
issue resolved , it is online again .
