### ISSUE TITLE
Insights Graph fantasieses a point at time opening insights graph if no data avaible

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1737]
**What is your Homey version (Settings → System)?**
1.5.0 2rc
x.x.x
[homey-device-f3797ec6-49f5-4fa0-b63c-6ed98b17db7d.measure_temperature.txt](https://github.com/athombv/homey/files/1211178/homey-device-f3797ec6-49f5-4fa0-b63c-6ed98b17db7d.measure_temperature.txt)
![capture](https://user-images.githubusercontent.com/7040452/29118188-3649a3d4-7d01-11e7-9a47-614b2fbd30a7.PNG)

**What did you try to achieve?**
see a correct insight

*Please include detailed steps how we can reproduce the issue*

stop the stream of incoming capability values,  open insight some time after 
**What was the result?**

insights graph fantasieses a point at time opening insights graph,, in earlier versions line just stopped

**What did you expect as result?**

no p0ints if no data available
...

**Any other remarks**
the log shows last data 3 augustus 2017 , the graph shows one nowe.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
Fixed in rc5

**Comment by nattlip** [comment]
solved in 1.5.0 rc5
