### ISSUE TITLE
IR turned off

### ISSUE THREAD

**Issue by Kingster2** [athombv/homey#1738]
**What is your Homey version (Settings → System)?**

1.5.0-rc.4

**What did you try to achieve?**

After executing a flow with IR signals, I can't learn any new codes anymore. It looks like all IR is turned off since all flows with IR don't work anymore until a restart of Homey. Then new codes can be learned until a flow with IR is tested, then everything is turned off again.

**Please attach a Homey System log (Settings -> System -> Send Log)**

80D170DD74

**Comment by jeroenvollenbrock** [comment]
Your log does not show any related information. Can you send a new log right after encountering this issue?

**Comment by Kingster2** [comment]
Uiteraard: 26E3133545

**Comment by bvdbos** [comment]
going back from experimental to stable:
https://www.athom.com/nl/ondersteuning/KB000041/
but you will lose all your devices, data etc. Also, 1.5 will be in stable soon so you have to consider if  it's worth it?

**Comment by Kingster2** [comment]
Thanks. Can you replicate the ir problem, I can replicate it over and over. Please let me know if you want to contact me directly. 

It might also be a good thing to build a test button at the learning proces of a ir command. At this moment there is no way to know if the ir command was damaged because of interference, unless you test it in a flow. But at that point nothing can be done anymore other then delete the IR device and start all over again.

**Comment by janusqq** [comment]
I have the same problem, running Homey Firmware Versie: 1.5.0-rc.4.

Whenever I trigger a flow with an IR device, the IR receiving functionality of my Homey stops working. I need to restart Homey to get it working again (but after one trigger, it gets broken again)

**Comment by jeroenvollenbrock** [comment]
Staged for rc6

**Comment by Kingster2** [comment]
Thank you for the update. Is testing a IR command when learning a command also staged for rc6?

**Comment by bvdbos** [comment]
fixed in 1.5rc6, @Kingster2 could you file a new issue for your question about the test-button?
