### ISSUE TITLE
[Writing] date_human Date

### ISSUE THREAD

**Issue by DeefK** [athombv/homey#1739]
**What is your Homey version (Settings → System)?**

1.5.0 RC4

**What was the result?**

date_human | woensdag 9de augustus 2017 14:45:24

**What did you expect as result?**

date_human | woensdag 9 augustus 2017 14:45:24

or date format in english style.

Everything in stuff for geeks is in English. I think you need to rethink how to display the date.

**Comment by WeeJeWel** [comment]
It's just for debugging purposes, and automatically generated depending on your Homey's language :)
