### ISSUE TITLE
Paired Sonos speakers will not respond to flows...

### ISSUE THREAD

**Issue by HerrNovad** [athombv/homey#1740]
**What is your Homey version (Settings → System)?**

1.5.0-rc.5

**What did you try to achieve?**

Giving commands to Paired Sonos speakers (2x Play-1) like play/pause/next/previous etc.

*Please include detailed steps how we can reproduce the issue*

Pair two Sonos speakers as a stereopair and execute a flow to trigger something like a next song event or play/pause etc.

**What was the result?**

It will not do anything.. except mute/unmute.

**What did you expect as result?**

Execute the given command in the flow directly speaking to the Sonos device (not the music app!)

**Any other remarks**

Unpaired it's working (also in a grouped set), I do have to re-add the Sonos speaker in Homey for it to work though, after the unpairing.

**Please attach a Homey System log (Settings -> System -> Send Log)**

EEAB8E8A54

**Comment by JPe2** [comment]
@HerrNovad   maybe you have to select a speaker (2 seconds) before the command is given, sounds strange maybe, but at default, the Homey speaker is chosen, so by selecting a Sonos speaker, the command goes also there too.

**Comment by HerrNovad** [comment]
Tried it, but didn't work.
It responds to mute/unmute though, I can select each of the pair with it.

**Comment by jabroersen** [comment]
Hope this get's fixed in the next release...this bugs my going away flow ;). Instead of just leaving the house, I now have to remember to stop the music. So 2017...

You guys are doing great work, still really like my Homey and patiently awaiting all updates and fixes!!! #2103

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
