### ISSUE TITLE
not responding to speech anymore!!!!!!!

### ISSUE THREAD

**Issue by paulus644** [athombv/homey#1741]
**What is your Homey version (Settings → System)?**
1.3.1

didn"t do nothing ,he just does not responding anymore
...

**Comment by djeskoswe** [comment]
Add log and try a ptp,  hard for athom to debug without a log file.

**Comment by bvdbos** [comment]
It seems there was an issue with the speech-server yesterday, does it work now?

**Comment by paulus644** [comment]
it seems like it ,but i need to talk louder ......for a reaction of homey

**Comment by corvdniet** [comment]
Had this problem yesterday for a few hours. After that it worked again. Now ... same problem again: no responce on "Ok Homey"

**Comment by bvdbos** [comment]
yesterday was an issue with the speech-servers...

**Comment by bvdbos** [comment]
@corvdniet could you send a log. Then reboot and see if that works or otherwise pull the plug and see if that works after that?

**Comment by corvdniet** [comment]
Log F95F6F3F5F

**Comment by corvdniet** [comment]
Reboot did the trick. Must have been that my Homey choked in a naughty word or so.
Thnx Bas

**Comment by bvdbos** [comment]
dupe of #1612 ?

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #1612
