### ISSUE TITLE
Apps are not updated in settings list when open during reboot.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1742]
**What is your Homey version (Settings → System)?**

1.5.0-rc5

**What did you try to achieve?**
Looking at the Desktop screen when Homey is starting the apps after reboot

*Please include detailed steps how we can reproduce the issue*
Look at the screen when Homey is starting the apps after reboot

**What was the result?**

When the browser is open during reboot, the settings list is not refreshed when the apps have been started. It needs a page refresh to make all the app-settings show up in the settings-list on the left.

**What did you expect as result?**

See the apps pop up in the settings list when they have been started.... just like when developing and loading an app with 'athom project --run'.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
fixed in rc6

**Comment by bvdbos** [comment]
Might I ask the same for insights?

**Comment by bvdbos** [comment]
Doesn't work for me in rc8.

**Comment by bvdbos** [comment]
nope, not in rc9

**Comment by OpenMindNL** [comment]
In my case, Chrome opens the Log-in page after the update.

**Comment by jeroenvollenbrock** [comment]
sorry, fix got staged after rc9 got build 🙈 1.5.0 does contain it

**Comment by bvdbos** [comment]
fixed.....
