### ISSUE TITLE
z-wave resends makes homey resend commands to other devices

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1744]
**What is your Homey version (Settings → System)?**
1.5rc5 (also happens on 1.3.1 and 1.3.2-1.5rc2)
x.x.x

**What did you try to achieve?**
Anything via a z-wave device with limited reception

*Please include detailed steps how we can reproduce the issue*
Have a central scene controller send scene notifications, when the reception/coverage is bad it will resend, like so:
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03720003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03730003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03730003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03740003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003

The last four 0x0750003 are resends and so are the 0x03730003's - these all makes Homey run the flow multiple times.

**What was the result?**
Lights blinking, garagedoor slams down on top of car, etc.
...

**What did you expect as result?**
Not having the lights blink and have dents in my car roof 👍 
...

**Any other remarks**
I can repreduce this quite easy with a sartano 433 device (which has a loud relay) and a central scene controller, simply by moving them away from homey and creating bad Z-wave reception.
The scene controllers i use i mounted in walls, and doesn't have direct connection through homey, but only via the z-wave mesh.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
5DA25DD9EB
...

**Comment by lurendrejer** [comment]
Today I made a flow where homey just said "Test" when a central scene notification was sent.
What happened was that homey sometimes repeated the "Test" two or three times from a single keypress/Central scene resend event.

**Comment by RobinBol** [comment]
Hi, what z-wave device/app are you using? This looks like something that should be handled in the app/driver of your z-wave device.

**Comment by lurendrejer** [comment]
Hi.
The central scene devices are zhc5010's - http://logichome.dk/index.php/products/3-zhc5010-z-wave-switch-module-for-fuga-installations

The driver is found here: https://github.com/ktnielsen/dk.logichome

**Comment by RobinBol** [comment]
Ok thanks, do you have information for me on how quick these resends follow each other?

**Comment by lurendrejer** [comment]
Yup. :)
[2017-08-11T07:20:11.299Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03720003
[2017-08-11T07:20:47.962Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03730003
[2017-08-11T07:20:48.003Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03730003
[2017-08-11T07:21:30.232Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03740003
[2017-08-11T07:21:38.794Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
[2017-08-11T07:21:38.881Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
[2017-08-11T07:21:38.919Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003
[2017-08-11T07:21:39.197Z] Node[43]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03750003

**Comment by RobinBol** [comment]
Ok thanks, I created a PR for the App you are using (https://github.com/ktnielsen/dk.logichome/pull/2) which will debounce incoming reports for 500ms, to filter out the resends but still allow for relative quick events. I think when the app developer merges my PR and updates the app in the app store your issue will be resolved.

**Comment by lurendrejer** [comment]
I don't think i understand.
The central scene commands are send from the devices, and to the homey.

--
OOH, it hit me while i wrote the message, it is not the device, but the app that debounces.
Thank you, i'll ask the developer to publish the APP, thank you.

**Comment by lurendrejer** [comment]
Can the app be written to cancel reports with the same ID?
500ms isn't really enough as far as i can see - and anything above one second would make it seem sluggish.

**Comment by RobinBol** [comment]
500ms is exactly enough if I look at the logs, doesn't leave much room that is true, the app can not see whether reports are duplicates so this is the only way for now. If you keep having issues you could ask the developer to up the debouncer to 750ms to be certain.

**Comment by lurendrejer** [comment]
Neat, Thank you :)

Take care.

**Comment by lurendrejer** [comment]
Hi.
Could you please take a look at page 75-80 in the z-wave specifications.
http://zwavepublic.com/sites/default/files/command_class_specs_2017A/SDS13781-3%20Z-Wave%20Application%20Command%20Class%20Specification.pdf

Central scene devices does send multiple identical commands which has a sequence number, which the controller should handle - as far as i can tell, z-wave certification would require this.

Do you still follow a closed thread? :)

**Comment by bvdbos** [comment]
@lurendrejer Did you try the PR @BasKiers made in the repo? If you think the zwave-implementation is incorrect you'd better create a separate issue for that.

**Comment by lurendrejer** [comment]
I'm sorry that I have to pull the "I'm stupid card" - I've been looking through @BasKiers Repos and can't find anything related to the issue. I might misunderstand you completely.

Sorry.

**Comment by bvdbos** [comment]
You could install the version with the changes from
https://github.com/ktnielsen/dk.logichome/tree/4df4b19fc3c28a9e96ec8aab7e244ff81a913110
and install it through the CLI. If you want it through the appstore then the developer should accept the PR and publish a new version.

**Comment by lurendrejer** [comment]
Ohh - the PR in the APP was by @RobinBol, not @BasKiers.

Then you misunderstood me. :)

Making the APP wait - would work around the issue, since it has to do with Homey not handling repeats on the network layer. But if everything is solved by making everything wait, everything will eventually grind to a halt. 
Also, Programming time based waiting won't fly with the original developer.

The fix should be made as per the z-wave standards document, not through a 'hack/workaround'

**Comment by lurendrejer** [comment]
As per the standards-document:

Sequence Number (8 bits)
The sequence number MUST be incremented each time a Central Scene Notification Command is
issued. The **receiving device** uses the sequence number to ignore duplicates.

As far as i know, the z-wave plus certification is rather strict, so implementing waits instead of the "real" solution would make the product (homey) loose the certification.

**Comment by bvdbos** [comment]
Like I said :  If you think the zwave-implementation is incorrect you'd better create a separate issue for that. And please allow some time for people to read it, especially during holidays...

**Comment by RobinBol** [comment]
You are right, I was to quick with my fix;) Just updated my PR to filter out duplicate sequence numbers. It might be possible to fix in homey-core, but that will take more time and require a homey firmware update, therefore I fixed it in the app.

**Comment by lurendrejer** [comment]
Thank you 👍 
I know i can be pedantic.... my wife tell me all the time.

She is also the one complaining about the lights blinking btw.

**Comment by lurendrejer** [comment]
btw, will you inform the right people at homey?
I won't expect every z-wave based app to implement the fix. So a core fix should be implemented.

Have a nice day.

**Comment by lurendrejer** [comment]
@RobinBol 
Just an update, installed the app via homey-cli today, everything is working great.
Thank you for your hard work!

I'll hope the Homey team implements this as core functionality, all scene-controllers must have the same issue.

Again, Thank you!
