### ISSUE TITLE
Dimmer tag contains 'Non numeric value' after reboot

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1745]
**What is your Homey version (Settings → System)?**
1.5rc5

x.x.x

**What did you try to achieve?**
Dim an Ikea trådfri bulb

*Please include detailed steps how we can reproduce the issue*
Add a bulb to homey and reboot the homey.

**What was the result?**
The "Dim level" tag of the bulb contains "-" not a number
Which in turn means that flows containing "if DimLevel>0.5 then" just fails with "Non numeric value" in the AND column.

**What did you expect as result?**
That the tag always contains the right type of values

...

**Any other remarks**
Screenshot attached
![capture](https://user-images.githubusercontent.com/30922656/29210362-878253fc-7e93-11e7-962f-20802c0f8582.JPG)

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by lurendrejer** [comment]
Just tested some more, the DimLevel variable can't even be used in contexts like "contains" since it is empy and just returns "invalid variable"

**Comment by bvdbos** [comment]
Did you use the test-button or did you really trigger the flow? If you used the test-button, what happens when you trigger the flow like it's supposed to?

**Comment by lurendrejer** [comment]
Test gives the error in the screenshot.
The button does nothing (I'm guessing it fails in the and column)

Den 11. aug. 2017 12.59 PM skrev Bas van den Bosch <notifications@github.com>:

Did you use the test-button or did you really trigger the flow? If you used the test-button, what happens when you trigger the flow like it's supposed to?

**Comment by RobinBol** [comment]
Thanks for reporting, this is fixed in an update for the Ikea app. Unfortunately, I'll have to wait for the next experimental Homey firmware to update the app. So keep an eye on the experimental channel and on the Ikea app itself!

**Comment by lurendrejer** [comment]
Superb - I made a temp solution with some variable it checks instead. Great job 👍

**Comment by lurendrejer** [comment]
@RobinBol 
Hi do you mean Homey v1.6 experimental or the latest 1.5rc6?

**Comment by RobinBol** [comment]
I meant I'll have to wait for 1.5.0-rc.6 (or up) to hit the experimental channel. In the mean time you can side load the app from this branch: https://github.com/athombv/com.ikea.tradfri/tree/zigbee-light-device-implementation

**Comment by lurendrejer** [comment]
RC6 released last night :)

**Comment by lurendrejer** [comment]
@RobinBol Just installed the Ikea app through cli, everything is working - thank you, great job.
Though, it appears that every device has the "bug" - not just Ikea bulbs, my domitec z-wave bulbs and other dimmers and dimmables all carry this sickness.
