### ISSUE TITLE
Unmute Sonos and set volume in a group weird behaviour

### ISSUE THREAD

**Issue by elfrigo** [athombv/homey#1748]
First my setup:
Using Homey Firmware Version: 1.5.0-rc.5
Sonos and Spotify for Sonos app
3 Sonos devices (Play:3 Play:1 and Connect) in one group
streaming radio

I want to have Homey start playing music (radio stream) on all 3 devices using a Flow.
They all start muted. Homey's Flow turns the mute -> unmuted and sets the volume on all 3 Sonos devices at a different level (5% - 7% and 50%)

Calling the flow results in:
- all devices unmute [good]
- volume on all devices is set to 50% [not good]
or - volume on all devices is set to 7% [not good]
or - volume on 2 devices is set to 7% and 1 on 50% [not good]
etc.

I tried to insert a delay in the volume set so commands are send at some timespace between each other.
Only unmuting (not setting volume) gives a volume of either on of those 3 devices when they where muted.

Homey System log (6877690CF5)

Really hoping for a solution. Volume @50% in the kitchen and dining room is NOT funny ;)

**Comment by dennusb** [comment]
I have the same issue... would be really nice if this can be fixed!

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.

**Comment by elfrigo** [comment]
@WeeJeWel 
> Fixed in v4.0.9.
I presume you mean the Sonos app ? My Sonos app is still v3.0.1, when will this new version be released?
Thx!

**Comment by Dijker** [comment]
Version 4 is already some time as Beta available, now on 4.0.12!
depending on feedback from users testing that it will be updated or released to stable. 
Athom usually doesn't give an estimated time as it depends on feedback and what bugs or issues are found.

**Comment by WeeJeWel** [comment]
The v4.x will be released to stable when Homey v2.0 is released to stable as well. This is due to Homey Music missing in v4.x, and we do not want to force the removal on users.
