### ISSUE TITLE
Z-Wave devices unreachable

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#175]
Have encountered several times that Z-Wave devices become unresponsive all of a sudden:
![schermafbeelding 2016-02-13 om 14 47 54](https://cloud.githubusercontent.com/assets/17163901/13027956/e7939714-d260-11e5-84be-38f3689fa68b.png)
Sometimes "Refreshing" device via Settings->Z-Wave helps, but not always.
Sometimes restarting the Z-Wave chip helps, but not always. It sometimes helps for a subset of devices, i.e. some behave normally after resetting, others are still unreachable.

Fibaro dimmers are well within reach of Homey.

SW 0.8.17

**Comment by ocatie** [comment]
Could you mouse over the devices and tell me the error message?

**Comment by Muyz** [comment]
As soon as I see it again, I'll post a screenshot.

**Comment by Muyz** [comment]
It just happened again:
![schermafbeelding 2016-02-13 om 17 56 01](https://cloud.githubusercontent.com/assets/17163901/13028840/24d6d82e-d27b-11e5-927c-529276fe16b6.png)

**Comment by ocatie** [comment]
Homey tries to send a secure command to the device but the device doesn't answer. What is the device you've added?

For Homey to try and reach the device goto Settings -> Z-Wave and select the device in the dropdown and press Refresh Node. If Homey can successfully reach the device it will become available again in the zone overview.

**Comment by Muyz** [comment]
That's correct; refreshing it worked. Your suggestion to refresh the node is obviously a containment, and not a long-term solution.

It's (again) a Fibaro Dimmer 2.

**Comment by ocatie** [comment]
I'm thinking about a few features to make the communication with devices more stable.

This is expected behavior if the device isn't answering a command.

**Comment by Muyz** [comment]
I would expect Homey to automatically reestablish communication, not me manually... Looking forward to the new features. Thanks.

**Comment by Muyz** [comment]
![image](https://cloud.githubusercontent.com/assets/17163901/13042876/3e2e3b92-d3c4-11e5-996a-7010dca1bf29.png)
As promised...another screenshot

**Comment by RemonBerends** [comment]
Why this issue is closed when it is not solved? The same problem here.

**Comment by rlijkendijk86** [comment]
Also noticed the same behavior with Greenwave node 6 device. Some of the sockets became unreachable for Homey, which is weird because all the sockets are in one device... Refreshing the node sometimes helped. 

This problem has to be solved, as people are paying extra money for z-wave devices because they should be more reliable than KAKU devices (433mhz), and because z-wave reports status. 

In the current state the z-wave isn't reliable.

**Comment by Muyz** [comment]
@rlijkendijk86 How did you succeed in pairing the Greenwave node 6? Have one as well, but don't have a clue...

**Comment by rlijkendijk86** [comment]
If I'm right my friend wvderspek already helped you out at the forum right?

**Comment by Muyz** [comment]
Yes, thanks to him it's working now.

For future reference, I'll repeat his description here.

I had to reset the node 6 first and then pair it:
1. Unpower the Greenwave node 6
2. Insert power plug while holding the on/off button on the node 6 and wait for green LEDs to light up
3. Put room selector to black (turn wheel on corner)
4. Add Z-Wave device on Homey
5. Briefly press pairing button on node 6

**Comment by djeskoswe** [comment]
reboot and refresh but device wont get back , 35571BE9A1
