### ISSUE TITLE
[Request] Date&Time Card - After "The sun sets" an "The sun rises" 

### ISSUE THREAD

**Issue by madmax75** [athombv/homey#1752]
Is ist possible to add a Date&Time Card to set the Time after sunrise and after sunset as in "The sun rises in" and "The  sun sets in"?

**Comment by bvdbos** [comment]
Valid enhancement I think, just for the record you could use "the sun sets" and then put a delay on the action...
![2017-08-16 10_46_36- 453 flow - homey](https://user-images.githubusercontent.com/1064079/29365945-dd06c9c6-8298-11e7-83e5-a7e4dfad29eb.png)

**Comment by WeeJeWel** [comment]
Do you mean '<x> seconds after sunset'? If so, then no, please use the delays in the action cards!

**Comment by madmax75** [comment]
Aha. Great
