### ISSUE TITLE
Alarms screen shows incorrectly

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1755]
**What is your Homey version (Settings → System)?**

1.5.0 RC6

**What did you try to achieve?**

Alarms screen shows alarms.repetition.monday --> etc

![image](https://user-images.githubusercontent.com/17526110/29414834-4603aea8-8361-11e7-881c-d1e8dea749f6.png)

**What was the result?**

Incorrectly displayed.

**Comment by bvdbos** [comment]
yep confirmed

**Comment by jeroenvollenbrock** [comment]
fixed in rc8
