### ISSUE TITLE
not possible to put date and time every amount larger then 99

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1756]
**What is your Homey version (Settings → System)?**

1.5.0 rc6

**What did you try to achieve?**
to put in flow date and time every 150 min
*Please include detailed steps how we can reproduce the issue*
try it for yourself

**What was the result?**

it will return with a max of 99

**What did you expect as result?**
150 min as i want it

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
confirmed

**Comment by WeeJeWel** [comment]
Fixed in v1.5.1

**Comment by satbopper** [comment]
confirmed
