### ISSUE TITLE
Missing text 

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#1757]
**What is your Homey version (Settings → System)?**

1.5.0 RC6

**What did you try to achieve?**

Nothing special

*Please include detailed steps how we can reproduce the issue*

Open Alarms page

**What was the result?**

Placeholder showed: alarms.no_alarms

**What did you expect as result?**

If I'm not mistaken, earlier versions showed a text to explain no alarms were set yet.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...
![image](https://user-images.githubusercontent.com/16610696/29428241-c4d4bde6-838c-11e7-9e36-01d7024daf5a.png)

**Comment by bvdbos** [comment]
I think we can assume the cause is the same as bug #1755 ?

**Comment by jeroenvollenbrock** [comment]
fixed in rc8
