### ISSUE TITLE
Can't learn extra buttons for generic brand IR

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1758]
**What is your Homey version (Settings → System)?**
1.5rc6

**What did you try to achieve?**
Add IR buttons

*Please include detailed steps how we can reproduce the issue*
Add IR, choose philips generic device
choose add button

**What was the result?**
no response when sending from button for learning. Choose "learn" from previous screen works (so without choosing generic philips device)

**Comment by BasKiers** [comment]
Hi,

The feature of adding manually learned buttons to a signal is removed as of Homey v1.5.4. Therefore I will close this issue. If you are still experiencing issues with this after Homey v1.5.4 please open a new issue.

Regards,
Bas
