### ISSUE TITLE
Can't test or edit IR commands

### ISSUE THREAD

**Issue by Kingster2** [athombv/homey#1759]
**What is your Homey version (Settings → System)?**

10.5.0 rc6

**What did you try to achieve?**

At this moment there is no way of knowing if a IR command was damaged during learning because of interference, unless you test it in a flow. But at that point nothing can be done other then delete the IR device and start all over again (for all buttons on the remote, with no guarantee all IR commands are learned correctly this time).

A 'Edit' and 'Test IR command' at the learning stage would be very helpful.

**Comment by bvdbos** [comment]
edit : #267

**Comment by WeeJeWel** [comment]
Testing IR signals is possible in Homey v1.5.4. Can you confirm that this is now working for you?

**Comment by Kingster2** [comment]
Hello WeeJeWel. Yes, this is truly a great addition. Testing works fine here and saves a lot of time. Also a lot of IR remotes are included. Thank you for all your work (I almost gave up hope for IR on Homey).

**Comment by WeeJeWel** [comment]
All credits go to @BasKiers !
