### ISSUE TITLE
[Enhancement] Export insights

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1760]
**What is your Homey version (Settings → System)?**

1.5.o RC6

**What did you try to achieve?**

Since 1.5 I've got the feeling Insights is taking much more space compared to firmwares < 1.3.0. Therefore Insights might have to be cleared more often than before.

It would be beneficial if there is an option to export all insights, similar to the function of Delete All Insights which is currently implemented.

Please add this option.

Thanks!

**Comment by Inversion-NL** [comment]
I'm working on a app to export Insights data to a MySQL database.
Don't know when it'll be finished, however

**Comment by WeeJeWel** [comment]
There already is!

![screen shot 2017-08-30 at 18 47 37](https://user-images.githubusercontent.com/319873/29884420-b77a470c-8db3-11e7-8b95-7650597d4b9a.png)
