### ISSUE TITLE
Notification for Firmware-update not working.

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#1761]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.5.0-rc.6

**What did you try to achieve?**
I want to get a notification when Homey's firmware is updated.

*Please include detailed steps how we can reproduce the issue*
![image](https://user-images.githubusercontent.com/3833862/29460703-349fb36e-8429-11e7-9a4f-4cd42f48c6b9.png)

**What was the result?**
did not get a notification, also not with updates to the previous versions.

**What did you expect as result?**
to get a notification, in the same way as when the App's are updated.

**Any other remarks**
When the App's are updated, I do get a notification, so the notification mechanism works.

**Comment by corvdniet** [comment]
+1

**Comment by chrisboer** [comment]
+1

**Comment by WeeJeWel** [comment]
Fixed in the next release.

**Comment by bvdbos** [comment]
Did this work today?

**Comment by corvdniet** [comment]
I got the the notification that Homey was updated to 1.5.0

**Comment by JPe2** [comment]
works fine now 👍
