### ISSUE TITLE
Homey calling itself 'Ik' is too human for a machine

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1762]
**What is your Homey version (Settings → System)?**

1.5.0-rc6

**What did you try to achieve?**
I said; "OK Homey.... Alle lampen uit"

*Please include detailed steps how we can reproduce the issue*
Just do it.

**What was the result?**

Homey says; "Ik zet het licht uit" and switches of all lights.

**What did you expect as result?**

I Don't think Homey is a person (yet). It's still a machine, so it should say something like "Het licht wordt uitgeschakeld" instead of acting like a person that says 'Ik'.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by nattlip** [comment]
afraid of the machines ? , you make homey a device entity by your proposition

**Comment by rnldnkp** [comment]
Most (personal) virtual assistants like Siri or Homey use "I" when speaking to you. It makes it personal. Even worse I guess (in your opinion) you can tell Siri to call you something else, like a nickname. 

If someone plans on fulfilling this enhancement, it might be an option to disable the "I" instead of removing it from speech. 

Literally I don't think of Homey as a machine. It has no moving parts and is not some kind of tool, it just has a lot of communication channels :P . It is referenced as a virtual assistant where a great part of the deal is making it interact with and like a human.

**Comment by lubbertkramer** [comment]
Agree with above one, @Tweake don't remove the I in the speech but make it an option to switch otherwise a new issue will be openend to bring back the "I" in the thinking of Homey. I named my Homey so i don't see Homey at the device page or anywhere else, so lets keep it personal.

**Comment by OpenMindNL** [comment]
I agree. I might see Homey as a machine... which it is as long as it doesn't say; "Bless you!" when I sneeze, but other people will act like Homey is their best friend, even when it/he/she refuses to listen.

Make it an option.

**Comment by Tweake** [comment]
I understand it is possible for someone to have no emotional or personal connection with Homey. Perhaps there are people who look at Homey the same way they look at, say, a stapler. However, when someone does experience an emotional connection we think they will get more joy out of interacting with Homey. Therefore we will continue to create interactions which mimic human interactions, including using Homey's first person perspective.

Making Homey's first person optional will require a huge rewrite which will add substantial complexity, yet will not add any substantial functionality. So, that's not something we will do either.

You did raise an interesting point/discussion though! Thanks you for making the suggestion

**Comment by OpenMindNL** [comment]
I'm going to fall off my chair, when Homey at version 1.6 suddenly says "bless you!" after a sneeze. 😁

**Comment by OpenMindNL** [comment]
How about consistency?

**"Homey is aan het updaten. Schakel Homey niet uit voordat de update voltooid is"**

According the arguments above, this should be;

**"Ik ben aan het updaten. Schakel mij niet uit voordat mijn update voltooid is"**
