### ISSUE TITLE
Ikea dimmer stops working after Homey restart

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1763]
**What is your Homey version (Settings → System)?**

1.5.rc6 (testet on all the 1.5.rc's)

**What did you try to achieve?**
Dim stuff

*Please include detailed steps how we can reproduce the issue*
Add an Ikea rotating dimmer and restart Homey.

**What was the result?**
Couldn't dim stuff
...

**What did you expect as result?**
That stuff dimmed
...

**Any other remarks**
The dimmer works as expected when first adding, if I make a flow like:
If dimmer rotated then say value -> Homey speaks and tells me the value when i rotate the dimmer.
After a reboot, Homey goes silent.
Could it be that the dimmers don't have numerical value like the bulbs mentioned in another bug-report?
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by RobinBol** [comment]
Thanks for reporting this issue. This bug is fixed in the Ikea app itself, please install the latest version from the app store. If the issue persists please re-open this issue.
