### ISSUE TITLE
memory use of a specifik capability isnt freed after removing capability from insight.

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1765]
**What is your Homey version (Settings → System)?**

1.5.0 rc6

**What did you try to achieve?**

the battery of a hms  100 device is 50 percent of my memory use for insights. i deleted capability from insight more than 34 hours ago. but still now its memory use is the same

*Please include detailed steps how we can reproduce the issue*
see above

**What was the result?**
see above
...

**What did you expect as result?**
free the memory of a capability when removed from a specifik insight and not used in other insights

yesterday morning , deleting value battery from insight 

![capture](https://user-images.githubusercontent.com/7040452/29497900-194d8e78-85f1-11e7-8daf-5c49a5628f75.PNG)

this evening 
![capture](https://user-images.githubusercontent.com/7040452/29497864-762d99d6-85f0-11e7-85d2-05b711aaf85b.PNG)

...

...

**Comment by jeroenvollenbrock** [comment]
Do the values still show in insights as well?

**Comment by nattlip** [comment]
i removed the checkmark on the device battery capability so no, but if a chemark it it appears again

**Comment by nattlip** [comment]
user feedback is provided @jeroenvollenbrock

**Comment by jeroenvollenbrock** [comment]
I'm sorry, but i'm not able to reproduce this issue. Just to be sure, you selected "Delete" from the menu in the insights page, confirmed deletion, and did not see the the bar shrink in the insights settings page?

**Comment by jeroenvollenbrock** [comment]
Additionally, a bug has been resolved in rc8 that could explain this behaviour, have you tested this on rc8?

**Comment by nattlip** [comment]
no i uncheked the checkmark of the battery capabilty of device . i dont know if the problems of using the insights settings page are solved, i read a lot of problems with the introduction of it, so i dont use it . it is 5 days now ago i unchecked the battery hms checkmark

in rc 8 still 40 procent battery memory use 
![capture](https://user-images.githubusercontent.com/7040452/29689168-80f60058-8922-11e7-997f-2507a8fdd74b.PNG)

**Comment by nattlip** [comment]
@jeroenvollenbrock

**Comment by Dijker** [comment]
Checkmark before is show/ hide in graph.... it is still logged!

To stop logging, Check the Log dit niet / something like  "Do Not Log!" on the hamburger menu
To remove one delete that insight there....
![image](https://user-images.githubusercontent.com/12412734/29689518-c689b2d0-8923-11e7-9b6c-a602812c80b1.png)

**Comment by nattlip** [comment]
@Dijker , i followed your instruction, nothing happened with the memory now , look tomorrow again

**Comment by nattlip** [comment]
it is still the same 46% of insight memory use

**Comment by jeroenvollenbrock** [comment]
Just to be sure, you selected "Verwijderen" from the menu in the insights page, confirmed deletion, and did not see the the bar shrink in the insights settings page?

**Comment by bvdbos** [comment]
starting with
![2017-08-26 19_45_50- 248 settings - homey](https://user-images.githubusercontent.com/1064079/29743865-e0e42648-8a99-11e7-8ac3-a3726c0cce18.png)
and
![2017-08-26 19_46_05- 248 settings - homey](https://user-images.githubusercontent.com/1064079/29743867-e4043804-8a99-11e7-91af-2777144e650b.png)
I went to delete the virtual sleep data
![2017-08-26 19_46_23- 248 insights - homey](https://user-images.githubusercontent.com/1064079/29743871-f5cac062-8a99-11e7-9fc5-f6a50aa093ca.png)
![2017-08-26 19_46_40- 248 insights - homey](https://user-images.githubusercontent.com/1064079/29743873-f8f75ac0-8a99-11e7-806d-29cedbd3e78a.png)
after a quarter of an hour Homey became responsive again:
![2017-08-26 20_03_34- 248 settings - homey](https://user-images.githubusercontent.com/1064079/29743874-0c6569b2-8a9a-11e7-917f-733955a0c66e.png)
![2017-08-26 20_04_13- 248 settings - homey](https://user-images.githubusercontent.com/1064079/29743876-0ee4978a-8a9a-11e7-8f12-5bd34fd1ecf5.png)

**Comment by bvdbos** [comment]
![2017-08-26 20_28_53- 248 settings - homey](https://user-images.githubusercontent.com/1064079/29744069-3d305428-8a9d-11e7-832d-bc4e8dd7b5fa.png)
Ah, now available storage went up too. Not taken by swap yet...

**Comment by nattlip** [comment]
in rc 9 it is cleared from memory
