### ISSUE TITLE
[Feature request] Add homey as secondary controller

### ISSUE THREAD

**Issue by vszabang** [athombv/homey#1767]
**What is your Homey version (Settings → System)?**

1.5.0 rc6

**What did you try to achieve?**

Add the homey as a secondary controller to the fibaro HC2 controller

**Why?**

As an end user I'd like to join homey to the existing Zwave controller as a secondary controller so that homey can use my Z-wave devices as a secondary controller

*Please include detailed steps how we can reproduce the issue*

Option 1)On the HC2 controller press "add secondary controller", on the homey press "Join existing zwave network"

Option 2)On the HC2 controller press "add devices" on the homey press "Join existing zwave network"

**What was the result?**

Option 1) Nothing happens at all

Option 2)The homey is joined as a generic Z-wave device to the HC2 controller, nu that's it, nothing after that... 
...

**What did you expect as result?**

Id expected to be able to add the homey as a secondary controller to the HC2 controller and the zwave devices to appear on the homey as well.
...

**Any other remarks**

Maybe you do not have a Fibaro HC2 controller available to test with, if this is the case, please let me know, I'm able to test things for you.

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

2866D524F5

**Comment by bvdbos** [comment]
See #856 and especially:
https://github.com/athombv/homey/issues/856#issuecomment-251928761

**Comment by vszabang** [comment]
Die had ik al gelezen Bas maar wel even 1 punt:

 

-Ik geloof echt in de de homey, jullie development en de weg die bewandeld wordt echter:

 

Mijn huis bevat 137 Zwave devices, die ga ik toch echt niet 1 voor 1 allemaal tzt met het handje overzetten naar de homey, dat is niet te doen….

Dus, met het volgende:

 

Stap 1)Homey toe kunnen voegen als secondary controller, (ben ik in staat om te testen of alle zwave devices goed werke, zoals de roller shutters e.d.)

 

Stap 2)Uiteindelijk dmv een Zwave controller shift kan de homey dan de primary controller worden.

 

 

Op deze manier bieden jullie een migratie strategie voor bestaande Zwave controller, wellicht niet jullie grootste doelgroep maar wel een meerwaarde, vandaar nogmaals de feature request.

 

Van: Bas van den Bosch [mailto:notifications@github.com] 
Verzonden: dinsdag 22 augustus 2017 13:29
Aan: athombv/homey <homey@noreply.github.com>
CC: vszabang <info@techdreams.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] [Feature request] Add homey as secondary controller (#1767)

 

See #856 <https://github.com/athombv/homey/issues/856>  and especially:
#856 (comment) <https://github.com/athombv/homey/issues/856#issuecomment-251928761>

**Comment by bvdbos** [comment]
Well, I'm just an end-user but perhpas @WeeJeWel can say more about this...

**Comment by vszabang** [comment]
I hope so....

**Comment by WeeJeWel** [comment]
I'm sorry, but it is very unlikely that we will ever add this functionality. Homey's Z-Wave implementation depends on apps to provide a superior experience, and as a secondary controller that simply isn't possible.

**Comment by vszabang** [comment]
Hmm, ok, then what about focus on migration ? any plans to support that ?

 

Van: Emile Nijssen [mailto:notifications@github.com] 
Verzonden: dinsdag 22 augustus 2017 16:26
Aan: athombv/homey <homey@noreply.github.com>
CC: vszabang <info@techdreams.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] [Feature request] Add homey as secondary controller (#1767)

 

I'm sorry, but it is very unlikely that we will ever add this functionality. Homey's Z-Wave implementation depends on apps to provide a superior experience, and as a secondary controller that simply isn't possible.

**Comment by WeeJeWel** [comment]
That is definitely something we're considering!

**Comment by vszabang** [comment]
Good to hear, cause I see the potential of the homey but for now the Fibaro HC2 is far superieur to the homey (for Zwave only) but I see a future state when I will switch to the Homey…. 

 

Van: Emile Nijssen [mailto:notifications@github.com] 
Verzonden: dinsdag 22 augustus 2017 16:42
Aan: athombv/homey <homey@noreply.github.com>
CC: vszabang <info@techdreams.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] [Feature request] Add homey as secondary controller (#1767)

 

That is definitely something we're considering!

**Comment by WeeJeWel** [comment]
What exactly do you think is superior? I'm always interested to hear what
makes our competitors good.

**Comment by vszabang** [comment]
Well, there are some things that the homey doesn’t do very well (at least, not at the last stable release I tested, I’m know on the experimental build)

 

Things are (from a Fibaro point of view):

 

Pros

 

*	Support of Zwave devices, even for the ones without a template is the Fibaro able to set parameters so the device can be used
*	Controlling blinds, I use the fibaro roller switch and it is able to control the vertical position of the blinds (not only open and close, as the homey currently does) , that is a “must”
*	Zwave stability, last homey build I tried wasn’t that stable (remember, I have quite a big zwave network with over 130 devices)
*	Flexibility, the Fibaro support virtual devices and scenes written in LUA code, this makes the system very flexible (if you can write LUA language..) and makes it possible to do a lot of things in just 1 scene
*	Virtual devices, creating one device, change the button layout and assign different actions to the buttons and the lables (I saw a virtual device plugin for the homey, is this about the same ??)
*	Good status view, I can see exactly what every device is doing, if it is dead, sleeping, wake’s up, parameter settings, etc…. 
*	Good dashboard (via Imperiohome IOS app) , I like speaking to homey however, I feel more comfortable with an ipad on the wall showing status, touching buttons to launch scenes, etc…
*	Alarm panel, heating panel, etc.., this works very good, I think homey can benefit from sort of “panel” functionality for heating, cooling, alarms, etc…

 

Cons

 

*	Fibaro lacks vision, there focus is on Zwave only , there are some plugins but they are not very well designed and there are only a few of them.
*	Development, not open, lack of communications, not very fast (no CI/CD I guess….)

 

Hope this helps, If you’d like to talk more or see some things in action, that’s always possible….

 

Greetings,

 

Vincent

 

 

Van: Emile Nijssen [mailto:notifications@github.com] 
Verzonden: dinsdag 22 augustus 2017 16:45
Aan: athombv/homey <homey@noreply.github.com>
CC: vszabang <info@techdreams.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] [Feature request] Add homey as secondary controller (#1767)

 

What exactly do you think is superior? I'm always interested to hear what
makes our competitors good.

**Comment by WeeJeWel** [comment]
Thank you for the feedback! I'll make sure we include it in our decision process.

@RobinBol `*	Controlling blinds, I use the fibaro roller switch and it is able to control the vertical position of the blinds (not only open and close, as the homey currently does) , that is a “must”` I think this should work for Homey as well?
