### ISSUE TITLE
App-problem Not updating status of devices

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1768]
**What is your Homey version (Settings → System)?**

1.5rc

**What did you try to achieve?**
To have status of z-wave devices update in on Homey.

*Please include detailed steps how we can reproduce the issue*
Very hard, since the z-wave devices doesn't exist outside Denmark.

**What was the result?**
Devices doesn't update their status when physically pressed/switched. (switches, dimmers, etc.)
...

**What did you expect as result?**
The opposite of the result.
...

**Any other remarks**
The driver/app found here has had some problems since the 1.3 update of Homey.: 
 https://github.com/ktnielsen/dk.logichome
A similar issue was fixed by @RobinBol in the Fibaro app here https://github.com/athombv/com.fibaro/pull/121 

Can the same fix be implemented? I'd be happy to test and report back anything i can.

The original developer of the Hardware and Software is rather busy at the moment. So i hope that someone could find time to help him and the other users of the product.

I don't have programming skills but have been looking through the driver.js - and all i got was confused, i'm sorry that i can't do more myself.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
This is a bug for https://github.com/ktnielsen/dk.logichome and not for Athom... As for Athom helping out: there's a PR from Athom waiting already on dk.logichome (as you know) but the app-owner has to approve it and then upload the new version to the appstore. There's no issues filed on that repo btw, would be good to file issues there as maybe someone else can fix this?  You can download the already improved app on 
https://github.com/ktnielsen/dk.logichome/tree/6de017ff674d7cd93d1d9f194cb7b95b211e4dbb 
and upload it through the CLI to Homey:
https://forum.athom.com/discussion/1448/how-to-cli-install-method

**Comment by lurendrejer** [comment]
I'm already running the fixed/new version (via CLI)- and everything is working fine.
I didn't want to bother the original developer about pushing the fixed version to the app-store, but if the other problem could get fixed and pushing to the appstore isn't that much work (i have no idea what i involves), I'd be happy to give him a call.

Right now, the development of a key-product in Denmark has haltet because of time-constraints. I was just hoping that somebody was willing to help out.

**Comment by lurendrejer** [comment]
More info:
When i press a button on Node49 i get the following in the log.
I'm guessing the "BASIC, 0x0300" should update the Homey status, but doesn't.
I don't get any multilevel commands, which i guess would update the dimmers.

All buttons has Basic set, binary set, basic ON/OFF and binary ON/OFF and Multilevel (when holding the button) association groups.

Node[49]: Received application command for COMMAND_CLASS_CENTRAL_SCENE, data: 0x03c70003
Node[49]: Received application command for COMMAND_CLASS_BASIC, data: 0x0300

**Comment by lurendrejer** [comment]
Hi, can i update this: https://github.com/ktnielsen/dk.logichome/blob/master/drivers/zhc5010/driver.js
with the never driver here: https://github.com/athombv/node-homey-zwavedriver/blob/master/lib/ZwaveDriver.js ?

Without trashing my Homey?
And could this be the fix for the missing status?

**Comment by bvdbos** [comment]
No, that's really something for the ktnielsen-repo to do... If other apps/devices do work, you'd better look for the part of the code which gets the status and try to create a new driver.js in the repo.

**Comment by lurendrejer** [comment]
I would be able to make PR, change the file and test via cli - Looking through the code is way beyond me :(
Thanks for the warning though. :)

**Comment by lurendrejer** [comment]
I would guess it's in line 10, but it looks like ktnielsen does something really different than @RobinBol does here: https://github.com/athombv/com.fibaro/blob/master/drivers/FGWPx-102-PLUS/driver.js (Also line 10) - Again trying to figure this out without programming skils beyond scripting is quite a mountain to climb.

**Comment by lurendrejer** [comment]
@bvdbos : Latest pull request have been merged and sent to the appstore - the original developer would be happy if someone else would take over the driver-coding. In his own words, he developes hardware and firmware - not javascript :)

**Comment by lurendrejer** [comment]
If I generate a driver through the generator in the SDK would that actually work? Or do the output need some work before it does anything.(?)

**Comment by bvdbos** [comment]
If definitely needs some work.... You have any insights in the amount of houses which use logichome in Danmark? Is it for sale everywhere like KaKu is in the Netherlands?

**Comment by lurendrejer** [comment]
It is, every z-wave store carries them. Every installation en Denmark uses the FUGA-standard for wall mounting of devices and cabling.
They also have zhc5002 with six buttons for Gira (International standard)
I've just talked to the creator of the product, and he would gladly send you the hardware, both for the Danish fuga and gira versions. (They use the same firmware, more or less).

**Comment by lurendrejer** [comment]
As of now, 2-3000 units have been shipped of the danish zhc5010 version - everyone on danish forums are keeping their fibaro and homeseers because homey in general doesn't work well with multichannel devices and ZHC5010 functionality is limited.

**Comment by lurendrejer** [comment]
I can say, without hessitation that if these devices arent supported by a given homecontroller, it won't fly in denmark. ZHC is our only option to use z-wave - up until now only schneider/LK have had smart-house products, based on their propriatary IHC and KNX implementations for FUGA, many people are looking for z-wave based alternatives, and the ZHC fills that gap. The thing is, the ZHC costs 40-50% of what schneider/LK's solutions does.

**Comment by TedTolboom** [comment]
@lurendrejer did you already had contact with the developer of the Logichome app?

I don't mind to making the app and extending the it with support for the ZHC5010, but that would mean overtaking the current app...

Can you contact me on Slack (same user name)?

**Comment by lurendrejer** [comment]
Yes, i spoke with the creator of the hardware, firmware and driver just two hours ago.
I don't have slack - but would gladly create an account if this could get things moving.

He wouldn't mind you or anyone else taking over the ownership of the app.

**Comment by lurendrejer** [comment]
Just created a slack account. Same user name.

**Comment by TedTolboom** [comment]
I meant the athomcommunity.slack.com; can't see you with the same account...

In the meantime I contacted the app developer to see if I can be of service...

**Comment by lurendrejer** [comment]
i'm not on athomcommunity, it says that it requires an invite.

**Comment by lurendrejer** [comment]
Great, thank you :)

**Comment by bvdbos** [comment]
https://slack.athom.com/

**Comment by lurendrejer** [comment]
@bvdbos thank you.
