### ISSUE TITLE
Homey keeps crashing every few hours

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#1769]
**What is your Homey version (Settings → System)?**

1.5.0 rc6 

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
Please also send a log... Sounds like you have a flow triggering itself? Did you install Homey logger and see what it says about the flows?

**Comment by 2benl** [comment]
Homey just crashes after a few hours. Sometimes +10 hours. Sometimes after 4 hours. 

After the last crash I send a log after ptp reboot. 

Crashlog: CAFCAE35A8

**Comment by 2benl** [comment]
Nope I didn't install Homey logger yet. Will do that.

**Comment by chrisboer** [comment]
Same issue with 1.5.2 rc8 6ADC4EE584

**Comment by 2benl** [comment]
Another Crash here on 1.5.2 RC8 92E534A1E0
I also installed Homey logger. 
Is the idea that I should leave it running on a computer with the real time logging on screen?

**Comment by jeroenvollenbrock** [comment]
Unfortunately, both your log files seem to be corrupted and only contain data after the PTP. You are on slack right? Maybe you can contact me for some remote debugging. (@jeroenvollenbrock)

**Comment by bvdbos** [comment]
@2benl How is your Homey running now on the latest FW?

**Comment by 2benl** [comment]
@jeroenvollenbrock @bvdbos 
Didn't have time to contact you on Slack Jeroen. Sorry. Now running the latest 1.5.0 FW since yesterday and haven't had any freezes yet, so fingers crossed. But looking good.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
