### ISSUE TITLE
Flow search on keyword does not work anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1770]
**What is your Homey version (Settings → System)?**
1.5.2 rc6

**What did you try to achieve?**
Search for a word in a flow to find a specific flow

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://user-images.githubusercontent.com/23163409/29602546-e14c792a-87e0-11e7-9d76-52972e851fbb.png)

**What was the result?**
Flow is not displayed
...

**What did you expect as result?**
Flows with "Ria" in the flow to show in search results
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
we're on rc8 now, don't know how it was on rc6? Works for me on rc8...
![2017-08-23 09_13_03- 245 flow - homey](https://user-images.githubusercontent.com/1064079/29603168-61088238-87e3-11e7-948a-eb6346aaf368.png)

**Comment by chrisboer** [comment]
Ok will update to rc8 and try again

**Comment by chrisboer** [comment]
Still the same issue with 1.5.2 rc8

**Comment by chrisboer** [comment]
Found the issue you should not use CAPITALS in your search querry so "ria" works "Ria" will not
