### ISSUE TITLE
[How to:] How can I identify a "unknown" z-wave device or delete it

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1772]
**What is your Homey version (Settings → System)?**
1.5.0 rc8

**What did you try to achieve?**
Identify a unknown z-wave device

*Please include detailed steps how we can reproduce the issue*
<img width="1600" alt="zwave_23082017" src="https://user-images.githubusercontent.com/23163409/29609560-e8e4395e-87f7-11e7-8172-085d4794e822.png">

**What was the result?**

...

**What did you expect as result?**
- I would like to know how I know what device are the unknown devices and how I can reset these that they will be "known" again.
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Those are not connected to a device in Homey, so most likely they're results of an incomplete pairing attempt. Don't worry about them!

**Comment by elfrigo** [comment]
In [this thread Jeroen Vollenbrock](https://forum.athom.com/discussion/2709/how-to-remove-unknown-z-wave-devices) said that they will be removed automagically in a future update.
Any update on when this magic is planned to be added?

**Comment by mruiter** [comment]
allready implememted

**Comment by mruiter** [comment]
then the unknown is still powered and sending data to youre zwave network. they only go away if its unknown and isnt transmitting anymore to homey. if its still there it should be a device still active and sending data

**Comment by CyberSponk** [comment]
@mruiter so if the device exists in 1.5.11 the device is sending data and will be not deleted?

**Comment by WeeJeWel** [comment]
You can send a BASIC On/Off to them to identify them. Then remove their power, and reboot Homey. They should disappear.

**Comment by elfrigo** [comment]
What happens if you send a basis ON/OFF to a (unknown) doorsensor or smokesensor. Will you be able to indentify those?

**Comment by chixxi** [comment]
I also have two such unknown nodes. When sending basic on off commands homey says: TRANSMIT_COMPLETE_NO_ACK

Firmware is 1.5.11.

And why is this closed if there is no solution?
