### ISSUE TITLE
App installation Toon Alpha not possible

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1773]
**What is your Homey version (Settings → System)?**
1.5.0 rc8

**What did you try to achieve?**
Install Alpha version of Toon

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Toon App install says homey is unreachable while homey is online on Desktop App

**What did you expect as result?**
Homey to get the Toon app installed correctly
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
6ADC4EE584

**Comment by Dijker** [comment]
Check your version, 1.5.2 rc8 of Homey is not yet released... 
Did you try to restart Homey ?

**Comment by chrisboer** [comment]
Yes get it installed and typo on release number
