### ISSUE TITLE
Homey Offline

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1774]
**What is your Homey version (Settings → System)?**
1.5.0 rc8

**What did you try to achieve?**
Nothing

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
Homey Offline
...

**What did you expect as result?**
Homey Online

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
BA29DD8E63
...

**Comment by jeroenvollenbrock** [comment]
Could you please be a bit more specific?

**Comment by chrisboer** [comment]
I had these issues currently I don't have disconnects anymore. Also homey is responsive in the Desktop App as it should be. (So will close it for now)
