### ISSUE TITLE
Too many memwarns received SmartPresence crashes every day

### ISSUE THREAD

**Issue by corvdniet** [athombv/homey#1776]
**What is your Homey version (Settings → System)?**
1.5.0-rc.8

**What did you try to achieve?**
I use the app for months now to be informed about the presence of aprox. 15 persons (15 different IP-adresses)

*Please include detailed steps how we can reproduce the issue*
Use the app at least one day with min. 15 IP-adresses

**What was the result?**
Since 1.5.0-rc.6 the app crashes irregularly but every day

**What did you expect as result?**
The app still working

**Any other remarks**
In the past I found out that the app increases the amount of system memory.
Noticed that there also issues with Philip Hue with the same error since a couple of days. Are these issues caused to the same problem?

**Please attach a Homey System log (Settings -> System -> Send Log)**
 7F729958C8

**Comment by jeroenvollenbrock** [comment]
Does this still occur on rc9? :)

**Comment by corvdniet** [comment]
Just updated to rc9. Will let you know in a day or 2

**Comment by corvdniet** [comment]
Haven't had any memwarns crashes since last post. Seems solved :)

**Comment by corvdniet** [comment]
Updated to 1.5.0 (experimental) this morning and this issue reoccurred this evening

**Comment by corvdniet** [comment]
Log C6B823AD71 send

**Comment by brtwrs** [comment]
I have the same problem with the Virtal Devices app. Just send the log (E57ABC7C8D)

**Comment by brtwrs** [comment]
Today I had the same problem with SmartPresence. Any progress on this issue?

**Comment by jeroenvollenbrock** [comment]
RC9 contained a change in the way app memory is calculated. Previously, it was possible for apps to leak swap memory, which was contributed to 'system' instead of the app. Therefore the app did not receive the proper memory warnings. I suspect there to be a memory leak in the smart presence app, which is something the developer(s) of the smart presence app will need to resolve. I'd recommend creating an issue at the app repo instead at https://bitbucket.org/terryhendrix/homey-smartpresence/issues/new (cc: @terryhendrix)

**Comment by corvdniet** [comment]
I adressed this issue to the original creator of this app. This is his responce: "I'm sorry to say: but i dont have any time to work on hobby projects. Perhaps someone else can have a look at it, it's open source for a reason"

I will ask on Slack in de the Developers group

**Comment by corvdniet** [comment]
Call for help placed in the Developers channel on Slack

**Comment by corvdniet** [comment]
No responce so far. Even hobbyists are busy apparently :)

The workaround for now: restart Smart Presence twice a day (by the handy Candy app)
