### ISSUE TITLE
Conflicting voice commands

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1777]
**What is your Homey version (Settings → System)?**
1.5.0 rc8

**What did you try to achieve?**
Look through voice commands

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://user-images.githubusercontent.com/23163409/29709221-dfb9761a-898b-11e7-80a7-c47731d80d74.png)

**What was the result?**
Message on conflicting voice commands but I don't use the same voice command anywhere else
...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
Televisie is a build-in word for Homey!

**Comment by bvdbos** [comment]
https://github.com/athombv/homey/search?q=television&type=Issues&utf8=%E2%9C%93
