### ISSUE TITLE
Homey not responding to "OK HOMEY"

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1778]
**What is your Homey version (Settings → System)?**
1.5.0 rc8

**What did you try to achieve?**
Ask homey about the weather

*Please include detailed steps how we can reproduce the issue*
Call "OK HOMEY"

**What was the result?**
Homey not responsive
...

**What did you expect as result?**
Homey ledring to become orange to wait for the command
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
92102E3119
...

**Comment by bvdbos** [comment]
You knew that already:

 1.5.0-rc.9 experimental
    Fixed a bug that could cause "okay homey" recognition to stop working
    Fixed a bug that could prevent homey from booting when storage was full
    Fixed a bug that could cause app memory to be attributed to system.
    Various minor bugfixes and improvements

Please do a search before posting issues...

**Comment by bvdbos** [comment]
#1612

**Comment by chrisboer** [comment]
Sorry but I don't receive 1.5.0-rc9 experimental information, because there was another issue with candy that no new firmware information was send. 

So I just see it now when checking for new updates ;-)
