### ISSUE TITLE
speechMatch event is not triggered in app

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/homey#1779]
**What is your Homey version (Settings → System)?**
1.5.0.-rc9

**What did you try to achieve?**
I tried to upgrade my app to SDK v2. Therefor I need to implement the new ManagerSpeechInput (and some other stuff, but that is working fine :)).

When trying to implement the ManagerSpeechInput, it seems that de speechMatch event is not triggered in the app.

In the onInit function of the app (app.js) extending Homey.App
`// Register speech events`
`Homey.ManagerSpeechInput.on('speechEval', this.speechEvalExecute.bind(this));`
`Homey.ManagerSpeechInput.on('speechMatch', this.parseSpeechExecute.bind(this));`

The speechEval event is triggered (and executed successfully returning callback(null, true).
The speechMatch event is never triggered.

**What was the result?**
The speechMatch event is not triggered.

Response from manager/speech-input
`{"status":200,"result":{"transcript":"when is the paper trash collected ","session":"homey","language":"en","words":[{"word":"When","pos":"WRB","universal_tag":"ADV"},{"word":"is","pos":"VBZ","universal_tag":"VERB","chunks":[{"startWord":1,"endWord":4,"type":"VP","transcript":"is the paper trash"}]},{"word":"the","pos":"DT","universal_tag":"DET","chunks":[{"startWord":2,"endWord":4,"type":"NP","transcript":"the paper trash"}]},{"word":"paper","pos":"NN","universal_tag":"NOUN"},{"word":"trash","pos":"NN","universal_tag":"NOUN"},{"word":"collected","pos":"VBD","universal_tag":"VERB"},{"word":"?","pos":".","universal_tag":"."}],"chunks":[{"startWord":2,"endWord":4,"type":"NP","transcript":"the paper trash"},{"startWord":1,"endWord":4,"type":"VP","transcript":"is the paper trash"}],"locations":[],"confidence":1,"duration":32,"engine":"text","synthesize":true,"devices":[],"qualifiedAgents":{"homey:manager:speech-output":{},"homey:manager:presence":{},"homey:manager:cloud":{},"homey:manager:ledring":{},"homey:manager:updates":{},"homey:manager:alarms":{},"homey:manager:system":{},"homey:manager:speech-input":{},"homey:manager:devices":{},"homey:deviceclass:amplifier":{},"homey:deviceclass:light":{},"homey:deviceclass:lock":{},"homey:deviceclass:sensor":{},"homey:deviceclass:socket":{},"homey:deviceclass:thermostat":{},"homey:deviceclass:tv":{},"homey:deviceclass:vacuumcleaner":{},"homey:deviceclass:windowcoverings":{},"homey:manager:speaker":{},"homey:manager:media":{}},"triggers":[{"id":"trash_collected","position":18,"text":"trash collected"}],"time":false,"agent":"homey:app:com.athom.trashchecker2"}}`

No response in manager/speech-output. Also no lines in the logging (console window).

**What did you expect as result?**
That the speechMatch function should be triggered.

**Any other remarks**
Full code is on GitHub: https://github.com/robertraaijmakers/com.athom.trashchecker/ (master branch).

**Please attach a Homey System log (Settings -> System -> Send Log)**
E43A83B3E9

**Comment by robertraaijmakers** [comment]
Hi, is there any progress on this issue?
The currently up-to-date version can be found here: https://github.com/robertraaijmakers/com.trashchecker/tree/beta

**Comment by Tweake** [comment]
Hi Robert,

I've checked the log and your App code. The issue you are experiencing is caused by your speech property in the .json being a combination of the old speech model and the new one. The speech property should be an object, not an array. Please see [the documentation](https://developer.athom.com/docs/apps/tutorial-Speech.html) for an example of what the speech property should look like. Good luck!
