### ISSUE TITLE
Large amount of storage used by Insights-Statistics

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1781]
**What is your Homey version (Settings → System)?**

1.5.0-rc.9

**What did you try to achieve?**

Check out what is using up Homeys storage.

*Please include detailed steps how we can reproduce the issue*

Take a look at system and insights

**What was the result?**

I noticed that a large amount of Homeys storage is used for Insights.... and about half of the Insights-data seems to be Statistics.

**What did you expect as result?**

I expected Insights to consume some storage space. But I didn't expect that so much storage was consumed by something like Statistics... of which I don't even know what it is.

**Any other remarks**

![system](https://user-images.githubusercontent.com/24574832/29719786-e5d8c86c-89b7-11e7-9b10-858ec4e9f0a8.jpg)
![insights](https://user-images.githubusercontent.com/24574832/29719846-1d3aa87a-89b8-11e7-8e34-d7bb95ab0306.jpg)

**Please attach a Homey System log (Settings -> System -> Send Log)**

66FC79C36E

**Comment by jeroenvollenbrock** [comment]
Statistics should only consume up a very small amount of the statistics database. There was a bug in an earlier rc that caused it to add entries whenever a flow got triggered. I'll add a cleanup migration to the next update to clear those entries.

**Comment by OpenMindNL** [comment]
The large statistics-chunk disappeared after updating to 1.5.0  .... and Homey now seems to have about 250-300MB more storage space 😎
