### ISSUE TITLE
Homey offline in chrome and desktop

### ISSUE THREAD

**Issue by satbopper** [athombv/homey#1782]
**What is your Homey version (Settings → System)?**

1.5.0 rc9

**What did you try to achieve?**
after the install of rc.9 all went well but after a few hours it refused to turn on the lights (kaku sockets) then i tried to login to homey as usual through chrome and the desktop app,on screen homey offline
homey was visible in my router and pingable but could not login

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
ptp homey and i could login again,ran the flow to turn on the kaku lights and they turned on
...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by satbopper** [comment]
up to now the issue ocurred three times,so three times ptp nice

**Comment by Dijker** [comment]
Contributing is more than only complaining it doesn't work.....

pls read https://github.com/athombv/homey/blob/master/CONTRIBUTING.md 

fe with three times a hang you could have send three times a Log after PTP to give Athom some information to investigate. (apart from other investigation you could have done ...)

**Comment by satbopper** [comment]
ach jongen heb al zo veel logs gestuurd hoor je niks van ga nou geen babbeltjes vertellen  en een log sturen na een ptp heeft weinig zin

**Comment by bvdbos** [comment]
@satbopper Yes it does.... The previous log is also sent, that changed with 1.2.0 or something like that...

**Comment by satbopper** [comment]
@bvdbos ok Bas the strange thing is that i found out,after i ptp out of homey and restarted it,i can always login chrome and desktop app,i logout and always within a half an hour homey gets offline
if i leave chrome open and logged in,homey will stay online,first i looked for maybe a bad wifi connection but that is not the point,but thanks for your message

**Comment by satbopper** [comment]
i sended the log DF222AEBBA after a ptp

**Comment by Marc1979** [comment]
Same problem overhere (since RC9). Every 24 hour have to do a ptp because homey is offline. Nothing changed, problems starts after update RC9

**Comment by OpenMindNL** [comment]
Yup... After updating to rc9 I experience a disconnect/offline at least once a day. Pulling the plug is the only solution.

**Comment by bvdbos** [comment]
> 17:19 jeroenvollenbrock : zijn al gefixt
So expect a solution in a new rc soon...

**Comment by satbopper** [comment]
eureka heb me de kolere lopen zoeken hier in het netwerk,strange but only a few suffered from this

**Comment by satbopper** [comment]
from the time of release 1.5.0 up to now no more homey offline,will wait to close the issue for experiences of OpenMindNL and Marc1979
The memory management is working great here,top release well done guys

**Comment by Marc1979** [comment]
here also no problems anymore since release 1.5.0

**Comment by OpenMindNL** [comment]
Yep... no more disconnections here either since 1.5.0 has been released.
