### ISSUE TITLE
Homey hardly responding - extremely slow rc9

### ISSUE THREAD

**Issue by corvdniet** [athombv/homey#1783]
**What is your Homey version (Settings → System)?**
1.5.0-rc.9

**What did you try to achieve?**
Use Homey. After a couple of hours Homey became extreme slow. Hardly responding. "Ok Homey" took 10-15 seconds before showing the yellow ring and gives no result other then "Couldn't reach the server"after 30 seconds

*Please include detailed steps how we can reproduce the issue*
Use 1.5.0-rc.9 a couple of hours

**What was the result?**
Homey seems extreme busy (see screenprint, loadavg)

**What did you expect as result?**
A normally working load and Homey working like a charm :)

**Any other remarks**
Pressed send log. Took 17 minutes: EB2D7769AE. Hope it arrived.
Pressed restart. Took 7 minutes before Homey responded.
Afaik I only installed iCalendar in this release, nothing else changed
 

**Please attach a Homey System log (Settings -> System -> Send Log)**
Made a new log after restart: 1DC1D81D28

![system information 2017-08-27 10u46](https://user-images.githubusercontent.com/22527207/29748405-926b7ef8-8b16-11e7-80c5-000b78e618ba.jpg)

![system information 2017-08-27 10u22](https://user-images.githubusercontent.com/22527207/29748404-8b7fa308-8b16-11e7-9449-7d04bcea8f3e.jpg)
.

**Comment by corvdniet** [comment]
The screenprints show up in a strange order. The first is after the restart, the second before the restart

**Comment by bvdbos** [comment]
Booting up all apps takes longer now so the second screenshot isn't that strange. But for the first case: did you take a look at the "developers" item in the menu? That appears if you sideloaded an app once. Are there any apps behaving strangely? Might be related to #1782 ? I suspect a corrupted db @jeroenvollenbrock ?

**Comment by mruiter** [comment]
How many apps do you have installed by total ?

**Comment by corvdniet** [comment]
24 apps.
At the moment the loadavg is "normal". 
![loadavg 2017-08-27 11u10](https://user-images.githubusercontent.com/22527207/29748520-af12688a-8b18-11e7-8101-d99fa425fa23.jpg)

Will investigate some more and look into sideload an app.

**Comment by mruiter** [comment]
Also from what version did you update to rc9.

If its the 1.3 series and now you updated to 1.5 series then theres some background migration going on that could cause a high load for sevral hours.

Else is could be a app that goes crazy or a always triggering error in some flow.
Try to disable a app.. see if load goes down .. if not disable the next until you find the app that causes the load and look what goes wrong with that app

**Comment by mruiter** [comment]
If now normal and stays normal then i guess it was a migration background process for example the insights data migration to the new format

**Comment by jeroenbos22** [comment]
Same here, seems slow since rc8. App shows device-card after approx 40 secs. Was pike 5-10sec before. Also speech and other responses (for example Motion detection) very slow sometimes

**Comment by corvdniet** [comment]
Managed to sideload an app. The extra developers info is very interesting. So far system stable and low loadavg. Will keep on monitoring.
@mruiter: I migrated from 1.5.0-rc8. So no migration was to be expected I guess?

**Comment by bvdbos** [comment]
I know there were some issues with corrupted databases fixed when going from rc8 to rc9. See #1769 so probably the same for you?

**Comment by bvdbos** [comment]
Think #1776 is related too.

**Comment by corvdniet** [comment]
Maybe. You never know how a cow catches a haze (sorry Dutch humour and literally translation)

Btw. Haven't had the memwarns anymore since rc9. Also the memory use is low and stable as a rock. W
ill add comment to the corresponding issues later today.

**Comment by corvdniet** [comment]
Went OK for a couple of hours. Then extreme slow again. Trying very hard to be patient enough to wait until some info in the Developers menu will be shown

**Comment by corvdniet** [comment]
At last ...
![storage memory i](https://user-images.githubusercontent.com/22527207/29750844-489cd00c-8b47-11e7-8e8e-0cf90ce17c5f.jpg)

No apps found that use extreme CPU. Most of them are flatliners :) The picture shows the app with the most (3%) CPU.

**Comment by corvdniet** [comment]
Took a while but this is the loadavg at the moment. Clearly too high!
![loadavg 2017-08-27 18u07](https://user-images.githubusercontent.com/22527207/29751788-ae64153e-8b52-11e7-97a1-68054f28941b.jpg)

**Comment by mruiter** [comment]
Is there a app with high mem usage ?


That also causes a high load because queue processing when all gets swapped around to slow storage




Outlook voor Android downloaden







On Sun, Aug 27, 2017 at 6:08 PM +0200, "corvdniet" <notifications@github.com> wrote:












Took a while but this is the loadavg at the moment. Clearly too high!

**Comment by corvdniet** [comment]
@mruiter Checked the CPU usage of apps in both situations ("normal" and in the extreme slow + high loadavg situation): highest % CPU of an app was 4%. Most of the apps use zero % CPU

**Comment by mruiter** [comment]
But i asked mem...




Swapping and low mem causes high.load on cores that you dont see in de dev apps graphs




Outlook voor Android downloaden







On Sun, Aug 27, 2017 at 8:34 PM +0200, "corvdniet" <notifications@github.com> wrote:












@mruiter Checked the CPU usage of apps in both situations ("normal" and in the extreme slow + high loadavg situation): highest % CPU of an app was 4%. Most of the apps use zero % CPU

**Comment by corvdniet** [comment]
But I didn't read your post very well :(

Can't say that there is an app that uses extravagant amounts of Mb's (Homey excluded :) )

![memory usage 2017-08-27 21u22](https://user-images.githubusercontent.com/22527207/29753270-e749525e-8b6d-11e7-9bf1-eb18178d985a.jpg)

**Comment by mruiter** [comment]
Nope indeed. Thats neither the case.




Some other users reported some spikes in cpu (not as worse as youres )




Jeroen mentioned on slack that he will look into it on monday




Outlook voor Android downloaden







On Sun, Aug 27, 2017 at 9:23 PM +0200, "corvdniet" <notifications@github.com> wrote:












But I didn't read your post very well :(


Can't say that there is an app that uses extravagant amounts of Mb's (Homey excluded :) )

**Comment by corvdniet** [comment]
Fine with me. Thnx

**Comment by corvdniet** [comment]
Confirmed. Works fine since this morning 10:50
