### ISSUE TITLE
Homey give's 'dont understand' response but does understand and execute flow

### ISSUE THREAD

**Issue by SmilingNL** [athombv/homey#1784]
**What is your Homey version (Settings → System)?**

1.5.0-rc.9

**What did you try to achieve?**
I built some flows that are being called by the voice commande 'Radio 1' / 'Radio 2' / etc. These flows work fine. They do cast the connected radio station through the chrome cast audio.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The flow is executed just as planned. The amplifier switches to the right setting, the radio station starts playing, Homey says the name of the station as per the speak card. But first homey says, sorry, ik begrijp niet wat je bedoelt.
...

**What did you expect as result?**
Doing as it does, but without saying 'sorry, ik begrijp niet wat je bedoel' 
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
0C5CC22400
...

**Comment by bvdbos** [comment]
Could you add a screenshot of your flow? Which cards did you use?

**Comment by SmilingNL** [comment]
Screenshot in this message. Also tried without the 2nd option in the or field. Same issue. This only happens when the flow is called through a voice command to Homey, not when the flow is tested.

![flow_-_smiling](https://user-images.githubusercontent.com/31383135/29749289-6d623ac2-8b28-11e7-9777-634313213a16.gif)

**Comment by bvdbos** [comment]
You should use another card, the "something was said with". There's abundant info on the forum:
https://forum.athom.com/search?q=sorry+ik+begrijp+niet+wat+je+bedoelt
https://www.google.nl/search?q=homey+zegt+sorry+ik+begrijp+niet+wat+je+bedoelt
and on github:
https://github.com/athombv/homey/search?utf8=%E2%9C%93&q=ik+begrijp+niet+wat+je+bedoelt&type=Issues
But I understand it's confusing. @Tweake Could you delete the tag from this trigger, it only causes confusion. Or better: Make this work like in the above flow...

**Comment by SmilingNL** [comment]
Okay, thank you @bvdbos. I will change this. However, because this causes this issue the or option cannot be used in a flow for voice commands. So building a flow that accepts different voice input to execute the same actions still means having to build (copy) several flows. Too bad. Hope this will change (back) in a future release.
