### ISSUE TITLE
Homey not reachable after Hue app removing

### ISSUE THREAD

**Issue by djanssen1** [athombv/homey#1786]
**What is your Homey version (Settings → System)?**

1.5 RC9

**What did you try to achieve?**

Remove Hue app

**What was the result?**

Homey unreachable. PTP necessary

**Please attach a Homey System log (Settings -> System -> Send Log)**

After reboot; log: 313354864C

**Comment by jeroenvollenbrock** [comment]
This was most likely caused by #1783
