### ISSUE TITLE
Memory graph incorrectly displayed

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1789]
**What is your Homey version (Settings → System)?**

1.5.0 (non rc)

**What did you try to achieve?**

Might be minor, but it has come to my attention that the Memory graph is incorrectly displayed. If there is only 43mb left, why is a big part of the memory graph not filled with the correct memory usage. It now looks that there is a lot of memory available but in the end, there isn´t.

![image](https://user-images.githubusercontent.com/17526110/29864292-83668aac-8d72-11e7-9ab9-969946494f07.png)

**Comment by jeroenvollenbrock** [comment]
Removed "free RAM" number in the top right, because it is not possible to display a correct value due to linux caches, swap and tmpfs taking up freeable RAM.

**Comment by Arjanvde** [comment]
Fixed!
