### ISSUE TITLE
Storage memory got missing

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#1790]
**What is your Homey version (Settings → System)?**

1.5.0 (non rc)

**What did you try to achieve?**

After some minor calculations I've noticed that for some reason some storage got missing or to what it is assigned isn't taken displayed in the graph.

![image](https://user-images.githubusercontent.com/17526110/29864524-4c90ae08-8d73-11e7-8616-359530dbb5d6.png)

A quick calculation says that something around 800MB is currently used with the storarge (1,64GB -/- 833,03MB). If you add the displayed usage you end up with 596MB, there is a difference of 20MB (800-596) 

Leaves 1 question, where did the missing 200MB go to? With the new way of data logging, data consumes more storage. Missing this 200MB (12% of Homeys total memory) might become an issue in the future.

**Comment by bvdbos** [comment]
related to #1789 Both are swap memory, just not displayed as such anymore...

**Comment by jeroenvollenbrock** [comment]
Added "System" category

**Comment by Arjanvde** [comment]
Hi @jeroenvollenbrock, This can be closed, after an update to 1.5.2 but can you explain 200mb system memory?

Thanks!
Arjan
