### ISSUE TITLE
Device not reporting results in all devices seemingly offline

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#1791]
**What is your Homey version (Settings → System)?**

v1.5.0 (non RC)

**What did you try to achieve?**
Get notified when a device doesn't report anymore

*Please include detailed steps how we can reproduce the issue*
Add trigger card 'Device hasn't reported in' and set the time to 24hrs (although that doesn't matter)

**What was the result?**
Got reports of all devices

**What did you expect as result?**
Only the device which didn't report on 24hrs

**Please attach a Homey System log (Settings -> System -> Send Log)**

CDC490FD07

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue. Are you sure the device has at least updated a capability once?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please open a new issue if you still encounter this issue with the [latest Homey version](https://firmware.athom.com/).

Thank you!
