### ISSUE TITLE
Benext tag reader 500 can only work within 2/3 metres from homey?

### ISSUE THREAD

**Issue by rowins** [athombv/homey#1795]
Homey 1.5.0,

My benext tag reader 500 can only work within 2/3 metres from homey, I have a small appartement, but it is not small enough haha...

I have tried restart my homey, to reinstall benext app and to refresh z-wave. Nothing seems to work. Are you working on this issue?

**Comment by mruiter** [comment]
Have you tried the distances mesurement somewhere else. For example at youre work place. 

The chance is big that its releated to rhe place in youre homey. Maybee the neighbours are polluting  ether with their signals... maybee you put youre homey next to youre audio speaker .. a lot is possible . Rule out youre place first

**Comment by bvdbos** [comment]
also: https://forum.athom.com/discussion/comment/57388/#Comment_57388

**Comment by ivleth** [comment]
I have a tagreader500 as well, don't have problems with range, tried it > 10M through walls.

**Comment by rowins** [comment]
I had a defect unit, i'm getting a free new one within a few days :)
