### ISSUE TITLE
Missing Zone for Devices Feature in 1.5.0

### ISSUE THREAD

**Issue by konradwalsh** [athombv/homey#1796]
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**
Created a flow that in the AND doesnt have the zone option for All Alarms Stopped unlike All Devices Stopped

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**
Expected same as other card option
![2017-09-01_21h18_39](https://user-images.githubusercontent.com/7996482/29986588-fc04620a-8f5b-11e7-8257-073a1a2333ae.png)
![2017-09-01_21h19_19](https://user-images.githubusercontent.com/7996482/29986597-ff9aaeec-8f5b-11e7-8d03-04869bebaedd.png)

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Fixed in the next release
