### ISSUE TITLE
Poll-card or Raw z-wave card

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1797]
**What is your Homey version (Settings → System)?**

Any

**What did you try to achieve?**
Poll devices via action-cards.

*Please include detailed steps how we can reproduce the issue*
Run flow, no poll-card

**What was the result?**

...

**What did you expect as result?**
To be able to poll devices.
...

**Any other remarks**
Being able to poll a device through a flow would be nice. Maybe by just making a raw/advanced z-wave command card.

Some devices needs polling to update their status. And polling on a z-wave network should be done as little as possible. Being able to poll a device a few seconds after activation through direct association would be nice.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by jeroenvollenbrock** [comment]
This should actually be a setting in the zwave driver for the specific devices that need polling
