### ISSUE TITLE
Spotify streaming to sonos problem

### ISSUE THREAD

**Issue by hrc007** [athombv/homey#1798]
**What is your Homey version (Settings → System)?**

homey :1.5.0
spotify app: v1.1.2 (beta)
sonos app: v2.3.0

**What did you try to achieve?**
play a spotify track on sonos speaker via homey music

*Please include detailed steps how we can reproduce the issue*
In homey music select sonos speaker, then use a playlist from spotify and select a track for playback.
When i start playback via homey music a track is played on the sonos but not the track which is selected (the track which is played belongs to the local sonos speaker playlist)
It seams that streaming from spotify is not working.

**What was the result?**
Wrong track starts on sonos speaker
...

**What did you expect as result?**
playback of the selected spotify playlist track on sonos speaker
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by JPe2** [comment]
see also the problem on: https://forum.athom.com/discussion/3140/play-a-sonos-playlist-on-sonos

**Comment by bvdbos** [comment]
Better file this bug at https://github.com/athombv/com.spotify/issues

**Comment by klankbart** [comment]
Wat is de status? Het is nog niet mogelijk om via Sonos een artiest of playlist af te spelen via Homey / Muziek

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
