### ISSUE TITLE
Lights in livingroom location not found 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1799]
**What is your Homey version (Settings → System)?**
1.5.0

**What did you try to achieve?**
Put the lights on or off in the living room

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://user-images.githubusercontent.com/23163409/30005827-3da4bd14-90eb-11e7-896a-858fbc3ad03f.png)

**What was the result?**
Homey says there are no lights found in the livingroom to put on or off
...

**What did you expect as result?**
The lights to be shut off
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
548556B9E5

**Comment by Dijker** [comment]
Your sounbar should not have the same name as the zone. 
Renaming it should fix your problem.

**Comment by chrisboer** [comment]
Thanks works indeed again...
