### ISSUE TITLE
Edit window for parameters zwave too wide, gets a horizontal scrollbar

### ISSUE THREAD

**Issue by athomey** [athombv/homey#18]
The edit Window is soo wide, it gets a scroll bar, and "Save" is out of reach without scrolling. This is in latest regular Chrome, Windows 10.

See screenshot: https://files.slack.com/files-tmb/T04E9KJ7T-F0J14SMTK-1c684863cf/pasted_image_at_2016_01_08_02_30_pm_720.png

**Comment by WeeJeWel** [comment]
Fixed in 0.8.8
