### ISSUE TITLE
Flow card 'You said something' capitals matter.

### ISSUE THREAD

**Issue by HiemstraJ** [athombv/homey#180]
Just got Homey set up, trying to build flows. Apparently there is a difference in the flow card 'You said something' between '**H**ello' or '**h**ello' 

This works:
<img width="307" alt="schermafbeelding 2016-02-13 om 19 54 39" src="https://cloud.githubusercontent.com/assets/6972038/13029401/a5706c9c-d28b-11e5-9b74-10af7248c801.png">

This doesnt work:
<img width="312" alt="schermafbeelding 2016-02-13 om 19 54 50" src="https://cloud.githubusercontent.com/assets/6972038/13029408/cdbdaf98-d28b-11e5-9e28-36bcf58fb7af.png">

**Comment by HiemstraJ** [comment]
I have way more issues whit these cards, text like 'good night'  wont trigger at all.

Testing these flows does work and I have a repeat flow which says the correct phrase.

**Comment by misterpm** [comment]
no text works with the 'You said something' card. 
Only OK HOMEY, YES and NO do work.
0.8.17

**Comment by bvdbos** [comment]
"Lights off", "Lights on" and "tell me the time" don't work either?

**Comment by misterpm** [comment]
They do work indeed with me. But those are no 'you said something' card commands.

**Comment by HiemstraJ** [comment]
Apart from the 'hello' flow card I can't get much to work. Strange issue.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
