### ISSUE TITLE
Homey stating he is beta after asking (in version 1.5.0)

### ISSUE THREAD

**Issue by yellowmousy** [athombv/homey#1801]
What is your Homey version (Settings → System)?

1.5.0
Dutch

What did you try to achieve?
Ask Homey what version he is running in Dutch: "Ok Homey, welke versie ben jij?"

Please include detailed steps how we can reproduce the issue
Ask Homey version in Dutch (not tested in English)
See also issue #1077 

What was the result?
Homey saying he is Beta:
"Momenteel heb ik software versie 1.5.0, denk ik. Maar ik kan me vergissen want dit is wel beta software"

What did you expect as result?
"Momenteel heb ik software versie 1.5.0."

**Comment by bvdbos** [comment]
Did you upgrade from 1.5.0 rc's or from 1.3.1?

**Comment by yellowmousy** [comment]
@bvdbos From 1.3.1.
It looks like the same issue from #1077. Same characteristics only difference is version number.

**Comment by corvdniet** [comment]
Interesting. I'm on 1.5.1 (Experimental) and expect Homey to tell me I'm on 1.5.1 and that it's beta software. It only tells me that is is version 1.5.1 (my version is Dutch)

**Comment by bvdbos** [comment]
Both on 1.5.1 and on 1.5.2 she's stating the version without beta for me...

**Comment by WeeJeWel** [comment]
@yellowmousy Do you have experimental updates turned on?

**Comment by Sherazarde** [comment]
Just to chime in on this. I just recived my Homey two days ago with Version 1.5.3 installed. I did not enable experimental updates. If i ask "Ok Homey, what version are you running on". Homey states its 1.5.3 but its unsure because its beta software.

**Comment by jeroenvollenbrock** [comment]
Removed the entire beta notion in the next release, as its already included in the version number.
