### ISSUE TITLE
[Enhancement] Manage Notifications from iOS / Android app

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#1803]
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?
View list of / clear notifications from the iOS / Android app.

**Comment by bvdbos** [comment]
this is not possible.

**Comment by Veldkornet** [comment]
Currently not no, that’s why I was suggesting it as an enhancement as I know that you guys plan to make more things available via the app eventually.

**Comment by Inversion-NL** [comment]
Duplicate of https://github.com/athombv/homey/issues/1094 ?

**Comment by Veldkornet** [comment]
Yup, thanks. I’ll close this one.
