### ISSUE TITLE
Push notification doesn't show all devices sometimes

### ISSUE THREAD

**Issue by btwvince** [athombv/homey#1807]
**What is your Homey version (Settings → System)?**

1.5.1

**What did you try to achieve?**

Send push notification to different devices

*Please include detailed steps how we can reproduce the issue*

If I add the Push Notification card in the Then column it only shows 1 phone, but if I put this Notification card in the Else column it show me all of the phones. 

**What was the result?**
In the Then column it only shows 1 phone (the first one)
In the Else column it's showing all of the phones
...

**What did you expect as result?**

That this card always shows all the phones

**Any other remarks**

No

**Please attach a Homey System log (Settings -> System -> Send Log)**

AB1DFF83FC

**Comment by WeeJeWel** [comment]
Can you make a screenshot? Sounds like the dropdown is hidden because your screen is too small.

**Comment by btwvince** [comment]
Sorry, i've tried this on my Macbook Air and Pro and everytime I had te same error. Now I try it on my desktop pc (2560x1080) for the screenshot and here it's working perfect.

**Comment by WeeJeWel** [comment]
Closing this issue because this will be fixed anyway in the upcoming Homey Smartphone App.
