### ISSUE TITLE
Hue color lights > color changes due set "helderheid" /Brightness via TAG

### ISSUE THREAD

**Issue by nilsaw11** [athombv/homey#1811]
Homey Firmware Versie: 1.5.1

i make a slider in better logic (Variable type : number) called "Dimmer DASH"

flow:

if:
a variable changed (better logic) "Dimmer DASH"

then:
set  brightness for a hue light (iris) via tag [#dimmer dash]

**What was the result?**
the light will respond to the dimm. level but goes to a different color.
(once used, the (output)color will every time the same)

**What did you expect as result?**

keep the color setting and change **only** the brightness
...

**Any other remarks**
main coal is one dimmer slider (homey dash) that will dimm the lights even when a scene is changed.
(group dimmer)
.

**Please attach a Homey System log (Settings -> System -> Send Log)**
Stuur de volgende code naar een Athom medewerker:
C6EFACA861
...
![image](https://user-images.githubusercontent.com/31865901/30295823-45dd4f20-9742-11e7-8233-381d0cc915be.png)

**Comment by bvdbos** [comment]
What happens if you change the variable another way, i.e. with speech-input?

**Comment by WeeJeWel** [comment]
What was the initial color of the light?

**Comment by nilsaw11** [comment]
Hello guys, Sorry for the late response....

Now i found some time to investigate whats happening.

what i have seen is ; when the scene is changed , not all the values aren't updated in homey.
When the "dimmer" slider is changed the value of the brightness it's reeds the "old"color values.

In my opinion, the value should be read more often from the hue bridge. So the values ​​are always actual. 
![dimmer](https://user-images.githubusercontent.com/31865901/31892029-46983466-b808-11e7-979d-b292c4eaf1b2.jpg)

**Comment by WeeJeWel** [comment]
I've performed some tests and it seems that this is a bug in the Hue Bridge. The official app also doesn't update after setting a scene remotely (e.g. through Homey).
