### ISSUE TITLE
Multi Channel Endpoint Association, disabled for devices with custom text

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1814]
**What is your Homey version (Settings → System)?**
1.5.2

**What did you try to achieve?**
Set a Multi Channel Endpoint Association to a device that has a custom (added) Association Group text.

**Please include detailed steps how we can reproduce the issue**
Try to set a Multi Channel Endpoint Association (for example `5.1`) to a device that has a custom (added) Association Group text.

**What was the result?**
The text box gives the error of a unusable character being used ( . ) while devices that have _no_ custom text added it is possible.

**Any other remarks**
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
No log required

**Comment by WeeJeWel** [comment]
Cannot reproduce
