### ISSUE TITLE
Randomly offline since 1.5

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1815]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

Keep Homey working

**What was the result?**

Since 1.5.2 homey goes offline once in a while (no fixed times) and is usually back online within a few minutes. 

**What did you expect as result?**

...

**Any other remarks**

I noticed it happens mostly when im using the web-app or phone app (at least then I notice). Im sure its not my wifi because it is up and all other wifi-devices are up as well. Also more people complain about it on slack.

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
Can Homey be reached locally during the offline-times?

**Comment by jeroenbos22** [comment]
Nope, totally dead. Ping, web-interface etc all unreachable both locally and cloud

**Comment by bvdbos** [comment]
Even local ping? And in the meanwhile you don't see Homey performing actions with 433, IR or Zwave either? Could you send a log?

**Comment by jeroenbos22** [comment]
Not sure homey is working in that time. Will try to test that and will send a log when it happens again

**Comment by bvdbos** [comment]
@jeroenbos22 I had the same last saturday several times, Homey couldn't be reached even on it's own ip-adress. After setting up some logging, it didn't happen again though. Did you get any further?

**Comment by roelfsre** [comment]
I have the same issue. randomly Homey is off-line. Happens about once in the 2 weeks or so.  I have some flows that sends out notifications. So when this is not happening, I know homey is off-line. Not sure if I can reach Homey from local network. PTP solves the issue. 
Now happend 2 times in a row. Issue--> PTP--> working for 1 hour --> issue again.

**Comment by ruudcornelisse** [comment]
I also have the same problem. every time i add a device i get an offline message in google chrome then homey is offline for a few seconds. sometimes it's true that if i leave google chrome open and i'm going to do things else then there is a random message that homey is offline. In the making and editing of flow's, the same happens.

**Comment by ncickc** [comment]
Same issue here, Homey is completely offline for a short time since 1.5* update.

**Comment by jeroenvollenbrock** [comment]
This might be resolved by https://github.com/nodejs/node/pull/15791 and https://github.com/nodejs/node/pull/16489, which we can verify after the next Homey update.
