### ISSUE TITLE
Account verification forever pending

### ISSUE THREAD

**Issue by TonD83** [athombv/homey#1816]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

Give another person in my household access to Homey.

*Please include detailed steps how we can reproduce the issue*

Invite user by entering e-mail address in the Homey app (on MacOS). User got e-mail, created account, verified e-mail address, signed in to Homey iOS on iPhone SE.

**What was the result?**

User has no access to Homey, account stays pending (waiting for confirmation) forever.

**What did you expect as result?**

User can access Homey.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Dijker** [comment]
On the email from the system when you invited is a link. 
click on that link to accept te invite.

**Comment by TonD83** [comment]
... 
Of course we did that several times already...

**Comment by TonD83** [comment]
Somehow after retrying a few more times (also with different mail addresses) the flow is now working. Not sure what caused this. Initially tried with @hotmail.com address, later with gmail. Both didn't work, but now the gmail succeeded after another try.
