### ISSUE TITLE
Flow select another Sonos speaker

### ISSUE THREAD

**Issue by tonvos** [athombv/homey#1817]
**What is your Homey version (Settings → System)?**
Homey 1.5.2
Sonos app: 2.3.0

**What did you try to achieve?**
In a flow the sonos speaker “SleepingRoom”  is selected.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
When I run a flow the sonos speaker "LivingRoom" is started. 

**What did you expect as result?**
When I run a flow the sonos speaker " SleepingRoom " is started. 

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
815F380B70
...

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
