### ISSUE TITLE
[FEATURE] Delay time on the microphone card in the AND column

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1819]
**What is your Homey version (Settings → System)?**
1.5.2

**What did you try to achieve?**
I want to delay the confirmation question from the microphone card in the "AND column".

**Comment by bvdbos** [comment]
This is already possible quite easily, just not in the condition-column:
![2017-09-16 08_28_45- 273 flow - homey](https://user-images.githubusercontent.com/1064079/30509804-1a245228-9ab9-11e7-83ee-39ead5fd3a51.png)
![2017-09-16 08_25_35- 273 flow - homey](https://user-images.githubusercontent.com/1064079/30509806-2527ccb8-9ab9-11e7-8652-04bcdd56b809.png)

**Comment by WeeJeWel** [comment]
Delays won't be added to cards in the 'and' column. The solution @bvdbos provided is indeed the right way to do this!
