### ISSUE TITLE
Enhancement. Device link/mirror

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1822]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**
Have a zigbee bulb mirror a z-wave switch's on/off position.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**
This can be done with two flows now, maybe some type of scene+check switch status.
An action card a la device switched status and a tag called 'status' would be a neat solution.
...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
Device Groups is on the roadmap!
