### ISSUE TITLE
ZigBee network graph time-out

### ISSUE THREAD

**Issue by rogro82** [athombv/homey#1823]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

View the ZigBee Network Graph

*Please include detailed steps how we can reproduce the issue*

I have added 19 lamps and 2 dimmer switches (Hue) as ZigBee devices to Homey. While including lamps I kept checking the network graph, but with each light added I noticed the Network Graph became multiple-times slower. After adding about 10~12 lamps the graph no longer would show, but instead it gives a message "Homey offline".

**What was the result?**

Generating the Network Graph timed-out and I received the message "Homey offline", while it was still accessible but the graph fails to load.

**What did you expect as result?**

A working Network Graph

**Any other remarks**

The time-out for generating the graph seems to be 120 seconds and it might be that it just needs more time with many devices added or perhaps generate the graph in the background and show a cached version.

**Please attach a Homey System log (Settings -> System -> Send Log)**

849DB33651

**Comment by bsnellen** [comment]
I have the same issue, With only 6 lamps and 2 plugs. I seem not to be able to add a new Ikea lamp anymore. I am not sure it is related, but seems to be.

**Comment by Dijker** [comment]
@jeroenvollenbrock this one looks like the Issue you found on my Homey in one of the first 1.5.0 rc's

**Comment by bvdbos** [comment]
Well, first of all: which app did you guys use for adding HUE-lights? There's no app in store and there's multiple HUE-Zigbee-apps on GH. @bsnellen Which plugs? There's nog Ikea-Zigbee-plugs?

**Comment by bsnellen** [comment]
I am having a problem with adding one IKEA lamp (e27 1000lm). I am relating this to a issue I had with my other IKEA e14 lamp. It did not turn on or of anymore right after the update to 1.5.2 5days ago. I tried rebooting homey (not working) and when trying to remove the IKEA e14 I ran into the timeout issue.. after a few homey reboots, the e14 lamp started working again. I forgot about the timeout issue until I tried to add the ikea E27 lamp .. I stil have the zigbee timeout issue. 
I use two Osram lightify plugs (no real issues) I have 5 lightify e14 lamps, they work sometimes.
The  lightify e14 lamps a seem to have a mind of their own .. they sometimes dont turn on when a flow should trigger them. And some are turned on after a upgrade. I notice in the morning!!

**Comment by rogro82** [comment]
@bvdbos My own but i can't see this being app related as all ZigBee lights basically just extend ZigBeeLightDevice.

I don't have any problems adding additional lights so if you have a problem I would suggest to create your own issue as this is only about the Network Graph giving time-outs... Adding lights and turning them on/off is no issue for me.

As for @bsnellen  I would suggest turning your lights on/off separately with a delay because turning on/off multiple lights at the same time using ZigBee often causes too much ZigBee network traffic... This is not Homey related as the Hue-bridge suffers from the same problem. The only real solution to this problem is ZigBee-groups/scenes which has not been implemented yet.

**Comment by RobinBol** [comment]
Thanks for reporting this issue! The ZigBee network graph will be removed from the Homey desktop app and moved to the developer tools (in which this issue is fixed). Therefore I will close this issue.
