### ISSUE TITLE
Location not workin iOS11

### ISSUE THREAD

**Issue by gldrenthe89** [athombv/homey#1824]
After installing iOS 11 and having the latest Homey app (TestFlight version) location is stil not working. 
Any update on a fix. Almost al flows rely on this. Homey is now a nice multi color LED light and not a smart system anymore

**Comment by bvdbos** [comment]
Dupe of #1683 ?

**Comment by gldrenthe89** [comment]
Yes, Correct. 
This issue can be closed/deleted

**Comment by Inversion-NL** [comment]
Only the guys from Athom and you can close the issue @gldrenthe89 ;-)
