### ISSUE TITLE
Homey picks up speech input, but no resulting feedback given

### ISSUE THREAD

**Issue by flipflopsandrice** [athombv/homey#1825]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
Use the speech input. I will say 'Okay homey, <xxxx>' where `xxx` is any arbitrary builtin or flow command.

**What was the result?**

The ring turns yellow, indicating homey is listening to me. After speech input the ring turns white (loading) and then .. nothing. No input in `/speech-input`. Not even a response from Homey that it didn't understand me.

**What did you expect as result?**

I expect one of two things after the ring turns white to indicate loading

1. To have my command/flow to execute
2. Homey telling me that it didnt understand the input

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

`BA7926EE85`

**Comment by maaikekaasenbrood** [comment]
I have the same issue

**Comment by flipflopsandrice** [comment]
Still not working after several reboots, nor after a PTP.

**Comment by robertraaijmakers** [comment]
I've got the same issue. But it depends on which 'app' gets triggered by speech. If I say a command that is not related to any app nor Homey internal function (e.g. "what is something going to happen"). I get the "i am sorry but I do not know what you would like me to do". 

But if I say something like "When is the paper trash collected", it just keeps quite. (like described in the issue). I think it has something to do if an app implemented the App SDK v2 or not and the speech not handled correctly.

See also: https://github.com/athombv/homey/issues/1779

**Comment by flipflopsandrice** [comment]
Is there any way I can help debug this? The speech input is quite unusable at the moment.

**Comment by flipflopsandrice** [comment]
Installed [Homey logger](https://apps.athom.com/app/gov.nsa.logger) and enabled all logs, Homey seems to be able to pick up I've given a speech command, but it only triggers these two events immidiatly afterwards. I see `"priority":"FEEDBACK"` in the first event, so I'm assuming it does recognize it is supposed to give feedback and something misfires during this.


**Event 1**

```
017 9:43:48 AM.300 | Ledring | Animate | <JSON below>
```

```json
 {
 	"options": {
 		"color": "#FFCC55",
 		"tfps": 60,
 		"fps": 10,
 		"rpm": 25
 	},
 	"frames": [
 		[{
 			"r": 255,
 			"g": 204,
 			"b": 85
 		}, {
			....snip...
 		}, {
 			"r": 255,
 			"g": 204,
 			"b": 85
 		}]
 	],
 	"priority": "FEEDBACK",
 	"duration": false,
 	"transition": 300
 }
```

**Event 2**

```
10/4/2017 9:43:50 AM.961 | Ledring | Animate | <JSON below>
```
```json
{
	"options": {
		"tfps": 60,
		"fps": 1,
		"rpm": 0
	},
	"frames": [
		[{
			"r": 0,
			"g": 0,
			"b": 0
		}, {
			....snip...
		}, {
			"r": 0,
			"g": 0,
			"b": 0
		}]
	],
	"priority": "SCREENSAVER",
	"duration": false,
	"transition": 300
}
```

**Comment by Tweake** [comment]
Hi, sorry to hear you are having issues. Thanks for providing a log. The log shows that Homey did not respond several times because it did not hear any text. A few commands to operate the radio were heard and responded to by Homey. 

If the  "OK Homey" trigger was heard but no text was detected, Homey stays quiet and does not do anything. It's set up like this to prevent Homey from saying "I'm sorry but I'm not sure what you would like me to do" when the voice trigger was accidentally fired, for example by noise coming from the tv. That's why it also did not show up in the `<IP address>/manager/speech-input` screen.  You can also type your command here to verify what Homey will do when a command was heard correctly.

**Comment by flipflopsandrice** [comment]
Thanks for the update. 

I understand homey does not hear any text and that this is the reason why it's not showing up in the `/speech-input` screen. The issue, however, is that I am indeed speaking to Homey. In fact, I am right next to Homey, speaking in a clear voice without much of an accent. 

So while I understand that input is not processed correctly because no of incorrect input, **the issue is that Homey is quite deaf**. There is an issue in the "text-detection", not in the processing of said text. 

Some way to debug this would be to expose the sample that Homey records after "OK Homey" is triggered (which, _is_ properly detected).

**Comment by Tweake** [comment]
We're aware of the issues that Homey does not always "hear" you correctly. An issue has already been created for it in the past: #498. The issue is still open so any updates will be posted there.
