### ISSUE TITLE
Homey presence not correct

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1826]
**What is your Homey version (Settings → System)?**
1.5.2 

**What did you try to achieve?**
Homey just shutsdown at 23:00 while he thinks we are on holiday

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://user-images.githubusercontent.com/23163409/30564601-d1e44644-9cc5-11e7-8c70-97170f8be476.png)

**What was the result?**
We are all at home ! and even with this homey shuts down (start the flow)

**What did you expect as result?**
No action in flow due to the fact that everybody is at home see picture

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
9051A4BA3A
...

**Comment by Dijker** [comment]
Ik heb even op je plaatje zitten turen, Weet je zeker dat het deze flow was? kan het ook door een andere flow zijn geweest dat Sonos Slapen is uitgevoerd? 
Als je op de Test knop drukt zie je of de conditie waar is voor de huidige stand van aan en afwezigheid. 
Dat is verreweg de makkelijkste manier om een conditie te testen. desnoods met een dummy in de Dan kolom.

**Comment by chrisboer** [comment]
Ik had hem al geclosed dus is geen issue !
