### ISSUE TITLE
Weird looking stripes within device settings

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#1827]
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.5.2

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*
I wanted to check out some settings for a couple of devices (in Google Chrome):
![image](https://user-images.githubusercontent.com/20989897/30639743-668d6f06-9e00-11e7-8593-0a73e3456db4.png)

**What was the result?**
![image](https://user-images.githubusercontent.com/20989897/30639351-c50c4004-9dfe-11e7-88cb-024960a58608.png)

**Any other remarks**
Whats going on here?

**Comment by Tweaqer** [comment]
Update: Still present in Homey Firmware Versie: 1.5.3

**Comment by WeeJeWel** [comment]
Umm, this actually looks like a graphics card issue... :-)

**Comment by Tweaqer** [comment]
I tested it on a laptop from a friend and you are right: no stripes! Weird stuff, so far I only have this issue with Homey site :(  Sorry for raising this without double checking
