### ISSUE TITLE
No more speech recognize on smartphone after update

### ISSUE THREAD

**Issue by zwaardemaker** [athombv/homey#1829]
What is your Homey version (Settings → System)?
**1.5.3**

What did you try to achieve?

**start a flow by speechcommand**

*ok homey verlichting aan*

What was the result?

**none**

...
What did you expect as result?

**lights set on**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
works for me...

**Comment by zwaardemaker** [comment]
do you have experimental update 1.5.3?

**Comment by bvdbos** [comment]
👍 Off course...

**Comment by bvdbos** [comment]
try a reboot or better, to be sure, a PTP (pull the plug). You didn't add a log? (settings-system-send log) and don't give any hints to what you tried to solve this issue?

**Comment by Dijker** [comment]
Working here on both Homey on 1.5.3  Dutch nd English

**Comment by zwaardemaker** [comment]
Strange,  speechrecognation in settings was turned off, although i wasn't there for a while. Back on track!!! Sorry guys!
