### ISSUE TITLE
Time and date is wrong

### ISSUE THREAD

**Issue by Barbados02** [athombv/homey#1832]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
The time and date on my homey is incorrect. 

*Please include detailed steps how we can reproduce the issue*
System -> stuff for geeks

**What was the result?**
The date and time is wrong

date | 2017-09-18T08:22:21.110Z
-- | --
date_dst | true
date_human | Monday 18th September 2017 10:22:21
devmode | false

...

**What did you expect as result?**
The correct time
...

**Any other remarks**

To resolve the issue i made a (soft) reset.
Changed the location of the homey, saved, set back to automatic
made a new reboot

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
D5915941C3
...

**Comment by Barbados02** [comment]
So, last night i turned off homey, and let it off all night. This morning i start it up again.
This is my current time and date:

date_human | maandag 18de september 2017 11:44:49

It seems my homey is re-living the same day.

**Comment by bvdbos** [comment]
Does your ISP or router block connections to time-servers?

**Comment by Barbados02** [comment]
No, I held Homey up-side-down and reloaded the settings.
Now the time and date are correct. I hope now all will be fine again.

**Comment by HomeyRichy** [comment]
Same problem here after an auto update to 1.5.3
Softreset helped.
Yesterday after some powerlosses: same problem raised again.

**Comment by jeroenvollenbrock** [comment]
This problem can have 2 (kind of technical) causes:
1. Either your router/firewall/ISP blocks NTP time synchronisation traffic
2. Your DHCP server supplies a custom NTP server that does not work in extension DHCP extension 42

Running the setup wizard syncs the time from your computer to homey, so this may only temporarily resolve the problem.

**Comment by HomeyRichy** [comment]
Thank you for the answer.
I have a Fritzbox 7390 router.
It is the only router in my network. It synchronizes with 0.europe.pool.ntp.org
The timeserver is available for the internal network. I have no other issues within the network after a power failure. The problem was first discovered after an auto update.

What can I do to check if Homey uses this NTP correctly?

Thank you in adavance.

**Comment by jeroenvollenbrock** [comment]
Can you try to disable the "Making FRITZ!Box available as a time server in the home network" option (home network -> network settings), then rebooting the router and then rebooting homey by pulling the plug for a few seconds?

**Comment by HomeyRichy** [comment]
I disabled the option. After power off and reboot the date/time is right.

 

I wonder why Homey has a problem with this setting. What is the technical explanation for it?

Anyway, thank you for the solution! Hope it is not a coincidence ;-)

 

Best regards

 

Van: Jeroen Vollenbrock [mailto:notifications@github.com] 
Verzonden: maandag 23 oktober 2017 19:05
Aan: athombv/homey
CC: HomeyRichy; Comment
Onderwerp: Re: [athombv/homey] Time and date is wrong (#1832)

 

Can you try to disable the "Making FRITZ!Box available as a time server in the home network" option (home network -> network settings), then rebooting the router and then rebooting homey by pulling the plug for a few seconds?

**Comment by jeroenvollenbrock** [comment]
It seems like the fritzbox is somehow blocking our NTP traffic when this option is enabled. I'll let our support team know about this problem, so we can suggest it if we encounter more users with the same problem. 
\cc @Moszkowizz
