### ISSUE TITLE
System - Settings MAC address incorrect. 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1837]
**What is your Homey version (Settings → System)?**
1.5.3 

**What did you try to achieve?**
Review Network settings

*Please include detailed steps how we can reproduce the issue*
Open Settings - System - Stuff for geeks
JSON.parse( network)

**What was the result?**
Reading network | 
{"lo":[{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4", "mac":"00:00:00:00:00:00","internal":true},"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","scopeid":0,"internal":true}],"wlan0":[{"address":"10.1.13.202","netmask":"255.255.255.0","family":"IPv4",**"mac":"00:00:00:00:6e:ad"**,"internal":false},"address":"fe80::6ead:f8ff:fe1d:976d","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6",
**"mac":"00:00:00:00:6e:ad"**,"scopeid":10,"internal":false}]}

My reaction was: Strange MAC addres starting with so many 0's

**What did you expect as result?**
The same result as my Arp -a, a valid MAC adres.

**Any other remarks**
Both Homeys have the same, Guess you don't need Logs ;-)

**Comment by bvdbos** [comment]
confirmed.

**Comment by jeroenvollenbrock** [comment]
Regression of https://github.com/nodejs/node/issues/13581. Will be fixed in a future update, The system info also contains a seperate wifi_mac property that should still be correct.

**Comment by jeroenvollenbrock** [comment]
Fixed in 1.5.4

**Comment by Dijker** [comment]
Confirmed fixed I  1.5.4 rc 1

**Comment by Dijker** [comment]
Confirmed fixed in experimental and closed
