### ISSUE TITLE
Read notification details when pressing notise

### ISSUE THREAD

**Issue by warting** [athombv/homey#1839]
When sending a notification to a phone and when pressing the notification i would like to go to some kind of notification details in the homey app to read the full message. If the notification is grouped i would like to go to some "inbox" view.

It's not possible to se the full text in the notificationbar

**Comment by Inversion-NL** [comment]
Duplicate of https://github.com/athombv/homey/issues/1094 ?

**Comment by jeroenvollenbrock** [comment]
Closed as duplicate of #1094,
