### ISSUE TITLE
ledring off between x and y

### ISSUE THREAD

**Issue by newmedia** [athombv/homey#184]
It would be nice if your could turn of the led ring between 2 times (i.e. 23.00 - 7.00). When i'm asleep i don't need/want a blinking/rotating light in my room.

**Comment by nattlip** [comment]
and the voice also, especially if the servers are offline saterdaynight.

**Comment by bvdbos** [comment]
volume #106 #134 and https://forum.athom.com/discussion/comment/9522/#Comment_9522
brightness #82 and https://forum.athom.com/discussion/comment/6346/#Comment_6346

**Comment by WeeJeWel** [comment]
Already fixed in 0.8.18
