### ISSUE TITLE
Not possible to swipe down in alarm screen in iOS app

### ISSUE THREAD

**Issue by runderkm** [athombv/homey#1841]
**What is your Homey version (Settings → System)?**

1.5.2

**What did you try to achieve?**

I have created more than four alarms (wekkers) in the iPhone app (iOS 11) and I tried to change one of the alarms.

**What was the result?**

It is not possible to swipe down in the app. So I can only change the first four alarms.

**What did you expect as result?**

I would expect it to be possible to swipe down in alarms screen in the app.

**Comment by WeeJeWel** [comment]
This should be fixed in the new Homey Smartphone App
