### ISSUE TITLE
Missing Flow cards light_(temperature/hue/saturation)_changed

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#1842]
**What is your Homey version (Settings → System)?**

1.5.3

As the title says, there is no way to create a trigger when the temperature changes (of a RGBW bulb). I can only find on, off and dim triggers.

Created from: https://github.com/athombv/com.ikea.tradfri/issues/20

**Comment by jeroenvollenbrock** [comment]
Closed as duplicate of #1833
