### ISSUE TITLE
[Feature request] Better flow cards for changing lights.

### ISSUE THREAD

**Issue by toAndreas** [athombv/homey#1843]
To be able to reduce the amount of cards in light flows a do card for changing all lights parameters for a light in a single card would be a nice feature.

**Comment by WeeJeWel** [comment]
Have you seen the card 'Devices' in the Flow Editor's sidebar? That contains several actions such as 'Turn on all lights'.

**Comment by toAndreas** [comment]
Yes i have seen the devices card but that won't solve my issue.

I would like to set all my individual Hue and IKEA lights with there own setting for dim level, temperature color etc, or maybe make small groups in say two or three lights and do the same.
Change dim level, color etc for that lights or group without having to set a card for each "variable".

I have at least 9 lights i want to individually control in my livingroom and with 3 cards for each light it's becoming a mess. 
Anny ideas of a better way to do it would be appreciated.

**Comment by WeeJeWel** [comment]
Maybe the app https://apps.athom.com/app/com.swttt.devicegroups is something you'd be interested in!

I'm closing this issue for now as there are no plans to support it directly, but maybe we'll add functionality like this eventually.

**Comment by toAndreas** [comment]
Tnx for the tip,  i will check out the device groups some more to night.
I actually use the groups app to turn off a bunch of Hue lights but i haven't seen that you can set collor/hue/dimlevel etc in the groups app when you turn on lights.
Maybe i added some lights that are only on/off in the group and the option didn't show.

"On the next page you will see all the capabilities supported by this class, now chose the ones you need. (e.g. onoff and dim)."
