### ISSUE TITLE
Homey -> Smart Alarm connectivity

### ISSUE THREAD

**Issue by vk900** [athombv/homey#1848]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Tried to add Smart Alarm to Homey 

*Please include detailed steps how we can reproduce the issue*
I've created this Github following thread:
https://forum.athom.com/discussion/comment/59272#Comment_59272
When I try to add Smart Alarm, I get a pop-up box asking me to login. After that I get a screen to approve connectivity to Smart Alarm and after confirming that, nothing happens.
Tried several times, also after reboot.
For troubleshooting purposes I tried it at 11.45am and immediately after that send the Homey Log to Athom via the interface. 

**What was the result?**
Nothing seems to happen and no device or anything is added to Homey.

**What did you expect as result?**
Smart Alarm to be available in the Interface to get status from.

**Any other remarks**
I'm available for beta testing if needed with regards to this Smart Alarm issue

**Please attach a Homey System log (Settings -> System -> Send Log)**
93BE0709FD

**Comment by BasKiers** [comment]
Hi,

Thank you for reporting this issue! I've just released a update in the appstore fixing this problem. If you are still experiencing problems please re-open this issue or create a new one.

Regards,
Bas

**Comment by vk900** [comment]
Thanks Bas, adding Smart Alarm now indeed works
