### ISSUE TITLE
Location map zoom function not working in automatic mode

### ISSUE THREAD

**Issue by Tvandongen** [athombv/homey#1849]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
Check the location of my phone

*Please include detailed steps how we can reproduce the issue*
Go to Settings --> Location; put setting on "Vind mijn locatie automatisch"; try to zoom into the location

**What was the result?**
Zoom is not possible

**What did you expect as result?**
Zoom function should also be possible on automatic mode
**Any other remarks**
If setting is changed to "Laat mij zelf locatie kiezen" then zoom is possible

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
@tvandongen I really don't understand you bug 1849? Find your phone? Settings-location, you mean in the Homey-interface? That's the location of your Homey, not of your phone... When it's automatic you can't zoom but that's not a bug...

**Comment by Tvandongen** [comment]
@bvdbos i understand that it was the location of the phone because @jeroenvollenbrock has asked to check the location due to a problem with geofencing in the beta ios, but it could also be the location of the homey.
That you can't zoom I still consider it as a bug (you could also argue that it is an enhancement) because if you can't zoom you can't check the location. In my case it was somewhere in the Netherlands and if you want to know if the position is more as 100 meters wrong a map of all of Europe is not detailed enough.

**Comment by bvdbos** [comment]
this one is not fixed. Zooming sets location to manual and re-sets the location of Homey to your zoompoint.

**Comment by WeeJeWel** [comment]
The update with this fix is not yet distributed
