### ISSUE TITLE
Developer: Flow card arguments passed with markup

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#185]
Text type arguments can contain markup:

![image](https://cloud.githubusercontent.com/assets/15232724/13033264/460ea4fa-d310-11e5-9c5d-3a2c70ae8a6f.png)

Suggestion: Never pass markup in a text type argument. Add a 'richtext' argument type if you want it.

**Comment by WeeJeWel** [comment]
I assume this happens when you paste some text?

**Comment by irritanterik** [comment]
Correct. I copy-pasted it from a Chrome console

**Comment by WeeJeWel** [comment]
Alright, it's a good suggestion. Thanks!

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
