### ISSUE TITLE
Play local sound files in SDK2

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#1850]
**What is your Homey version (Settings → System)?**

1.5 SDK 2

**What did you try to achieve?**

Play local mp3, as in soundboard app

**What was the result?**

SDK 2 does not have playMp3

see https://github.com/matjaz/homey-youtube/issues/19

**Comment by WeeJeWel** [comment]
Have you seen these docs? https://apps.developer.athom.com/ManagerAudio.html

**Comment by matjaz** [comment]
kinda overlooked this. been searching in speaker manager as in v1.
Thanks!

Are there any plans for node streams support?

**Comment by WeeJeWel** [comment]
No, there are the music apis for that. These sounds are meant to be short and non-intrusive to the user.
