### ISSUE TITLE
[Feature request] KNX-support

### ISSUE THREAD

**Issue by cbho** [athombv/homey#1853]
Will KNX be supported in the future?

**Comment by nattlip** [comment]
if some writes an app for it

**Comment by lurendrejer** [comment]
Is that all it takes, an app? I thought knx was some high end, mesh enabled, proprietary encrypted, 868 mhz thing.

**Comment by cbho** [comment]
Is this the officiel Athom reply?
Or just som quick "do it yourself" reply?

As wrote in https://forum.athom.com/discussion/3869/supporting-schueco-building-skin-control-also-will-homey-support-knx-or-not
Emile wrote In september 2014 "KNX is on our to-do list for after the launch of Homey!" (https://forum.athom.com/discussion/comment/245/#Comment_245)

No comments on the question in the forum and remembering the many times people are told to put it on GitHub, I did...

**Comment by nattlip** [comment]
dear chbo,

@cbho 
the answer is short indeed, not from Athom b.v. But from a user who spend a lot of time in making a lot of apps for homey, your reaction is in my humbel opinon based on how little you know about github as a social phenomonen and i believe giving such a reaction is very primitive first investigate who is who before you react in such , everyone in the world with an github account can answer here. By the way did you see how short  your question is, it wastn clear to me you asked this to athom b.v. , the way you put youre question it is addressed to the whole world with a github accountHomey programming app is done by a lot of happy homey users who happens to like to add functionality to homey. did you know there is a large slack community from athom b.v. where github messages from hee are seen . https://athom.slack.com/

**Comment by nattlip** [comment]
@lurendrejer i cant image knx doesnt has a ip interface like philips hue bridge. indeed if you directly want to make contact with knx via 868 it is littlewbit more compicated, but communicating with a socket is more easy. you have 2 hue apps one to communicate with the hue bridge and one which is directly communicating via zigbee with the hue satellites.

**Comment by lurendrejer** [comment]
Ooh.. I guess knx has lots of 'masters'. I just always thought of knx as some magical zwave-superior thing of the future. :)

**Comment by nattlip** [comment]
no knx is the domotica of the rich , if you buy a house like huge hefner knx is build in no klika or zwave, if you buy a boat of 2 milion per meter you get knx in it.

**Comment by lurendrejer** [comment]
Isn't everybody in the homey community a millionaire?

I hate it when all those poor people complaint about not going on summer vacations, why don't they just go down to their yacht like the rest of us. :)

**Comment by lurendrejer** [comment]
Do you know for a fact that Hugh Heffners latest residence has KNX? :-D

**Comment by lurendrejer** [comment]
On a completely unrelated note, there is a hue app that works without the bridge? Where can I find it? I just put my hue devices up for sale to buy trådfri, would really like to know!

**Comment by Heki2017** [comment]
Guys this is not a chat function, please find another channel for that

**Comment by lurendrejer** [comment]
Sorry, I'll hit you up on grinder.

**Comment by nattlip** [comment]
@lurendrejer  https://github.com/rogro82/com.hue.zigbee

**Comment by lurendrejer** [comment]
Thank you very much. /Out.

**Comment by cbho** [comment]
My apologies for asking if a feature mentioned in 2014 will appear, for not being able to make it myself and for wondering why you replied like you did, and for phrasing my question too short, and asking for support to a system that you find too espensive.
And yes, I know messages here are seen on Slack - as well as I have seen how people often direct feature requests to be made on GitHub - and my apologies for for not following some unwritten rule I don't know apparently not honouring those who are able to program enough.

Back to the subject:
KNX is an open standard (https://en.wikipedia.org/wiki/KNX_(standard)) and supported by HomeSeer, Zipato, and Vera, e.g. and considering the post from 2014 I think it is a relevant question.

Adressing @WeeJeWel in specific, I will, underpinning that I do find the work of Athom and the community impressing and fantastic, if there are any plans about integration KNX in the future?

**Comment by nattlip** [comment]
dont shoot the messenger, athom doesnt have the resources to make all the apps possible for Homey so most apps are from users. And indeed a lot of plans are  announced and still laying on the shelf. thats why on Slack the term "soon" has as special meaning in Homyland, it means from now till Christmas 2020, but the eassence is still that until someone from Athom or a user makes an app knx isnt supported by Homey, the reality is harsh

**Comment by bvdbos** [comment]
Looking at the wiki-page I think you might have to be clearer. There's five different communications-protocols used for KNX and I assume there's a bridge with an app?
    Twisted pair wiring (inherited from the BatiBUS and EIB Instabus standards)
    Powerline networking (inherited from EIB and EHS - similar to that used by X10)
    Radio (KNX-RF)
    Infrared
    Ethernet (also known as EIBnet/IP or KNXnet/IP)

**Comment by Dijker** [comment]
@cbho 
Researched for you some things, 
See my reaction on https://forum.athom.com/discussion/3869/supporting-schueco-building-skin-control-also-will-homey-support-knx-or-not

**Comment by jeroenvollenbrock** [comment]
KNX support is scheduled to enter it's research phase in Q1 2018. We won't be able to provide more details at this time.

**Comment by pontusr** [comment]
Hi - understand you're all busy with many things. Would just like to give my support for getting this done eventually.
@jeroenvollenbrock @Moszkowizz Were you able to get started on the research? If yes, let us the community know if there is any information or testing needed that we can help you with. Thanks!

**Comment by WeeJeWel** [comment]
Yes, we are working on KNX support at this moment!

**Comment by KyleAthom** [comment]
So, the moment is finally here. This week we want to start alpha testing the app that will bring support for KNX devices to Homey!

Please let me know if you want to participate in the alpha test.

**Comment by KyleAthom** [comment]
We've decided to release the app as a beta instead of alpha. So no need anymore to signup, just install the app from: https://apps.athom.com/app/org.knx. Feel free to test it out if you have or known someone with a KNX setup.

**Comment by WeeJeWel** [comment]
This issue can now be closed.

https://go.athom.com/knx
