### ISSUE TITLE
Floweditor: Timeselect on else not visible

### ISSUE THREAD

**Issue by Lansuper** [athombv/homey#1855]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Enter a time on an else-statement

**What was the result?**

Had to select the time with the arrows

**What did you expect as result?**

To be able to select though the clock interface

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

![image](https://user-images.githubusercontent.com/32201989/31054260-44cf9094-a6af-11e7-80fc-7d8153efc97e.png)

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #894
