### ISSUE TITLE
[Feature request] Odd/Even week number flow card

### ISSUE THREAD

**Issue by videren** [athombv/homey#1856]
I would like this to include "Odd week numbers" and "Even week numbers", to be able to have specific flows active only during the weeks that my son stays at my place.

![image](https://user-images.githubusercontent.com/32452685/31073769-8d448dac-a76d-11e7-9a7a-86f38de78081.png)

**Comment by klankbart** [comment]
I would appreciate this feature as well, same situation. If odd and even weeknumbers would be available we will have all the Magister messages only in the even weeks. :-)

**Comment by WeeJeWel** [comment]
Added in the next release!

![screen shot 2017-11-20 at 17 28 16](https://user-images.githubusercontent.com/319873/33029205-491c1d26-ce18-11e7-9998-e2b4e56c4b78.png)

**Comment by nieuwton** [comment]
Nice to have: In addition to a tag for 'Weeknumber' also a tag for 'Day of Year number'

**Comment by Dijker** [comment]
The we could alsof ask for the seconds since Unix epoch :-)  
or is $timenow$ still working?

**Comment by WeeJeWel** [comment]
I already see this list growing until infinity, therefore I invite someone to create a community app for this.

**Comment by klankbart** [comment]
When is this new release planned? My Homey is running 1.5.5 and and I can't choose 'the weeknumber is odd' in the And column in flows yet.

**Comment by bvdbos** [comment]
🔜
