### ISSUE TITLE
Sonoff Switch Support [Device Request]

### ISSUE THREAD

**Issue by vaderag** [athombv/homey#1857]
Sonoff Devices are cheap, CE certified and have recently been hacked to work without their own cloud system:
https://blog.ipsumdomus.com/sonoff-switch-complete-hack-without-firmware-upgrade-1b2d6632c01

Supporting these devices would provide a very cheap way for the community to add additional switching to their routines, with each device costing <€5

**Comment by vaderag** [comment]
@jeroenvollenbrock great to see that someone is taking a look at this!! ( @Moszkowizz ) - hoping you will support the wifi only ones along with the 433mhz varieties!

**Comment by WeeJeWel** [comment]
Please contact support@athom.com with your request, or ask someone on the Forum.
