### ISSUE TITLE
Homey 1.5.3 ZigBee Interruptions

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#1859]
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Setting-Up ZigBee-Lightify-Bulbs with Homey-Zigbee (no Bridge) e.g. On/Off or Brightness.

*Please include detailed steps how we can reproduce the issue*
Flow > Then-Column: Put 6 Bulbs here and select e.g. Brightness. Running Flow. 

**What was the result?**
Not all Bulbs are Updated.

**What did you expect as result?**
All Bulbs updated with the Settings given in the Flow.

**Any other remarks**
Tryed also with App Device-Groups after Slack-Chat (thanks there for help) > Seems a little bit better. Also made a Git on ZigBee-Section (https://github.com/athombv/com.osram.lightify.zigbee/issues/10) because i could not find out if this is a Issue from Homeys ZigBee or from the ZigBee-App.

**Please attach a Homey System log (Settings -> System -> Send Log)**
If needed please let me know.

**Comment by CyberSponk** [comment]
tryed also delays with 1, 2 and 3 seconds and got often this error of the bulbs on the then-site in a flow:

af data request fails, status code: 205. no network route. please confirm that the device has (re)joined the network.

and: error261

if i run the flow more than once the bulb will be e.g. turned on after some runs.

**Comment by tompesman** [comment]
@RobinBol Do you need more information or is the bug clear?

**Comment by RobinBol** [comment]
Thanks for reporting this issue. In Homey firmware versions 1.5.4 and 1.5.5 some stability improvements were made to ZigBee, in particular improvements of the command queue (which will now send commands in smaller batches instead of all at once), and it introduces a fix for the possibility that a ZigBee device becomes uncontrollable after Homey reboots.

Please let me know if after updating to 1.5.5 you are still experiencing this issue. If so, please provide a log and some more detailed information.

**Comment by tompesman** [comment]
I've done some tests here with 6 Ikea GU10 Tradfri spots. It is more reliable, I've removed delays to switch the spots on or off. But sometimes one or two spots fail to switch. I've attached a log of a flow in which one spot fails to turn off. `B9EA3AA93D`

**Comment by CyberSponk** [comment]
Tested it today with 7 Bulbs (E27, latest Osram-Firmware 01020510) on Homey 1.5.5 with LF-Beta-App 1.2.1. The Problem is not gone. It's not possible to switch more than 3 Bulbs e.g. On with one Flow.

Made one Flow: 
When > Flow triggered, Then > Turn On Bulb1, Bulb2, Bulb3, Bulb4, Bulb5, Bulb6 and Bulb7. Running Flow (Test). Result > Not all Bulbs turned On. Running Flow again. Result > One more Bulb turned On.

It's not to localize what Homey is doing. Running the Flow sometimes only 2 Bulbs turned On, sometimes 3 Bulbs. In no Time all 7 Bulbs turned On when Flow is Running one time.

Also tested it with delays: Turn On Bulb1, Bulb2 after 3 Seconds, Bulb3 after 6 Seconds and so on. Result > Same as written above > Not all Bulbs turned On.

Log > C4EC435B6D

**Comment by ljsvv** [comment]
I experience the exact same as described above, but the strange thing is, downstairs everything works fine. Upstairs it is not. 2 fixtures with 3 ikea gu10 tradfris sometimes 2 bulbs on, sometimes all 3.

**Comment by johane77** [comment]
Trådfri is not working well.. Please help!!!

**Comment by CyberSponk** [comment]
Couldn't longer Assist/Help here with Lightify > Changed all Bulbs at Home from _Osram Lightify_ to _Philips-Hue_.

**Comment by ljsvv** [comment]
Do you have those directly connected to Homey or with the Hue Bridge?

**Comment by CyberSponk** [comment]
With Hue-Bridge. The Lightify before also have been connected with Hue-Bridge to Homey.

**Comment by RobinBol** [comment]
Merging with: https://github.com/athombv/homey/issues/1956
