### ISSUE TITLE
Flow editor: colorpicker pops under next flow action

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#186]
Picture says it all:

![image](https://cloud.githubusercontent.com/assets/15232724/13033479/0e825556-d318-11e5-9a67-0559ef48dc40.png)

Reproduction path:
 1. add color selector
 2. add next card
 3. edit color in colorpicker

**Comment by bvdbos** [comment]
#173

**Comment by irritanterik** [comment]
duplicate
