### ISSUE TITLE
Unable to pair AWMD-250 (Klikaanklikuit) Device

### ISSUE THREAD

**Issue by Starf0x** [athombv/homey#1860]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Pair the AWMD-250.

**What was the result?**

The Homey acted like it was paired, but during the pairing process you can try it with a switch, nothing happened, I can pair the AWMD-250 to the ICS-1000.
Normally I would be able to pair it with the remote, but that didn't work, so I tried the pairing button, but that didn't also give the required result.

**What did you expect as result?**

Light switching on and off.

**Any other remarks**

N/A

Logfile:

A21E94D409

**Comment by Corneliatt** [comment]
Hi,
I have the exact same problem, trying to pair with Nexa WMR-252 (should be same the product as AWMD-250). No reaction what so ever. Pairing with all other Nexa products worked just perfect.

Please let me know if you've already found a solution!

**Comment by BasKiers** [comment]
Hi,

Could you try to pair your AWMD-250 as a AWMR-230 device in Homey?

Regards,
Bas

**Comment by Starf0x** [comment]
I've fixed it, by unplugging the Homey and powering it on again.
