### ISSUE TITLE
No connection to the athom cloud anymore

### ISSUE THREAD

**Issue by LourensMeek** [athombv/homey#1861]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

... 04AB5F7E83

**Comment by caseda** [comment]
Did you reboot your router yet like I asked you in the forum?

**Comment by LourensMeek** [comment]
Yes is did this 

Verstuurd vanaf mijn iPhone

**Comment by LourensMeek** [comment]
any update on this?

**Comment by LourensMeek** [comment]
any update on this? This is still not solved, do i need to reinstall the homey?

**Comment by LourensMeek** [comment]
its working again. Looks like a dns issue thanks
