### ISSUE TITLE
[AppStore] Contributors and Donation button not visible Tablet and smaller views

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1862]
**What is your Homey version (Settings → System)?**
n.v.t.

**What did you try to achieve?**
Add App to Homey from the App store, and show my appreciation (edit: stupid autocomplete....).
 
*Please include detailed steps how we can reproduce the issue*
With the focus on Mobile devices: Keep your Desktop/Laptop closed ;-) 
Open on the Tablet the App store https://apps.athom.com/
Select a random App and install, and look if they have an Donate button....

![image](https://user-images.githubusercontent.com/12412734/31283640-75b62050-aab6-11e7-9a55-f7f7d6cbd90a.png)
![image](https://user-images.githubusercontent.com/12412734/31283655-80bc7aa8-aab6-11e7-8abc-2ad907f9a5a9.png)

**What was the result?**
This Community member probably didn't add an Donate button! ;-)

**What did you expect as result?**
That this user wanted donations ;-)

**Any other remarks**
I already missed the GitHub link on mobile, but didn't use it on my tablet anyway.....

**Please attach a Homey System log (Settings -> System -> Send Log)**
Nope...

**Comment by Inversion-NL** [comment]
Confirmed. Here's an app with an donate button: https://apps.athom.com/app/com.swttt.homekit
Resizing the window on your laptop will lose the 3rd column with the contributors and donate button

**Comment by WeeJeWel** [comment]
Fixed, should be live in ~30min.

**Comment by Dijker** [comment]
Nice, but maybe you have some time to look at the aspect ratio as a Fixed Height and variable width just look weird in some views.

![image](https://user-images.githubusercontent.com/12412734/38815709-e022f0e2-4194-11e8-8649-1f0e31c0378f.png)

**Comment by WeeJeWel** [comment]
Haha oops, fixed
