### ISSUE TITLE
[AppStore] Mark this comment as inappropriate not working

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1863]
**What is your Homey version (Settings → System)?**
n.v.t. 

**What did you try to achieve?**
Report a inappropriate AppStore  Comment!
Press:
- Mark this comment as inappropriate

*Please include detailed steps how we can reproduce the issue*
Tried in Chrome and IE 11.

**What was the result?**
Nothing!

Viewed the Inspect Developers console:
![image](https://user-images.githubusercontent.com/12412734/31286158-8f86ecf6-aabd-11e7-9806-ccd91506f1ea.png)

**What did you expect as result?**
Confirmation....

**Any other remarks**
Nope.

**Please attach a Homey System log (Settings -> System -> Send Log)**

**Comment by WeeJeWel** [comment]
That is... inappropriate. Fixed!
