### ISSUE TITLE
Security issue (Homey cloud)

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1865]
Hi.

When entering a "wrong" username in the username field, my.athom.com answers with: "A user with this email address does not exist."

You should never give an attacker information by reporting that a user doesn't exist. :)
Answering with "wrong username or password" would in my book, be preferable.

**Comment by RobertMe** [comment]
Same applies to the password reset form: 'A user with this email address does not exist.', this also is an information leak. And the same might apply to the register form if it shows that an email address already is in use.

**Comment by joachimroeleveld** [comment]
Hi, I understand your concern, but we don't think security through obscurity makes make a difference in this case.

In many sophisticated ways a malicious player could obtain the same information through more sophisticated attacks (such as a [timing attack](https://en.wikipedia.org/wiki/Timing_attack))

The detailed confirmation is useful to users as we initially got a lot of support tickets from users that were confused about their account state. Also, next to login and password forgotten views, you could ask what behaviour would be appropriate when a user tries to sign up with an e-mail address that is already in use. How would you communicate that to the user? 

Moreover, please note that many internet services (e.g. Google, Facebook) nowadays do not apply this practice anymore either, for the same reasons I stated before.

**Comment by lurendrejer** [comment]
Hi.

I personally don't think that comparing Athom to companies with billion-dollar security budgets, where billions of people have accounts, is a good idea.

**Comment by joachimroeleveld** [comment]
In my opinion, the main argument in this discussion is that an attacker can obtain the same information in many other ways. Which is why we choose to allocate our efforts to implementing more effective security measures in the future, such as 2 factor authentication.
