### ISSUE TITLE
ZigBee-Bulbs not working and shown as Offline

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#1867]
**What is your Homey version (Settings → System)?**
1.5.3 + Lightify-Bulbs + ZigBee-Lightify-App

**What did you try to achieve?**
Switch Bulb on in the Morning.

*Please include detailed steps how we can reproduce the issue*
Flow: When > Triggered, Then > Switch Bulb1, Bulb2 and Bulb3 On / iOS-App: Tapped On by the Bulb1, Bulb2 and Bulb3

**What was the result?**
Nothing. Standing in the Dark.

**What did you expect as result?**
That the Bulbs turn On.

**Any other remarks**
Looked at this the last Days. It seems Homey is doing something during the Night. This Morning 5 Bulbs of 38 are shown as Offline. Only Ptp helps (didn't checked if only reboot would be helpful). This was not the first Morning with that Issue. Think this is Homey-ZigBee-Problem and not ZigBee-Lightify-App-Problem > The App works as expected till now.

**Please attach a Homey System log (Settings -> System -> Send Log)**
4F8D2C0A65

**Comment by RobinBol** [comment]
Thanks for reporting. Do you reboot Homey during the night?

**Comment by CyberSponk** [comment]
No, didn't boot Homey. Also didn't know if Homey reboots by itself.

**Comment by RobinBol** [comment]
What is the exact error message that is displayed when such a bulb goes offline?

From your logs I can see that the bulbs lose their 'routes' over time, the meshing however is not done by Homey itself. Could you describe the setup of your ZigBee network in more detail? Distances, walls, number of devices in certain area's etc.

Also, could you try to turn off/on the bulb (by switching the mains) when it went offline? Maybe that would restore its mesh routes.

**Comment by RobinBol** [comment]
@CyberSponk could you take a look at my comment above and provide some feedback?

**Comment by CyberSponk** [comment]
@RobinBol 

What is the exact error message that is displayed when such a bulb goes offline?
Sometimes "Error 256 Device Offline" or only the red Triangle with the "!".

From your logs I can see that the bulbs lose their 'routes' over time, the meshing however is not done by Homey itself. Could you describe the setup of your ZigBee network in more detail? Distances, walls, number of devices in certain area's etc.
Got a ZigBee-Network only with Bulbs: Osram Lightify E27, E14 and GU10. The Distance from Homey to the first three Bulbs are 2 Meters in the same Room. The next 21 Bulbs are in the next Room with one Wall between Homey and these Bulbs. The Distance to the first of these Bulbs is round about 2 Meters. 

The Problem only exists if a Flow has to switch more than 3 Bulbs, sometimes more than 4. Switching Bulbs lonley works without Problems. In the first time of using ZigBee-Bulbs i used the Lightify-Gateway. The Gateway was located in a mirrored bathroom Cabinet > No Problems.

Think: Homey has a Problem with Switching more than 3/4 Bulbs at the same time. If Homey should do this the Network crashes and Devices going Offline and Come back some seconds later.

**Comment by CyberSponk** [comment]
@RobinBol 

_What is the exact error message that is displayed when such a bulb goes offline?_
Devices shown as Offline in the Stuff-Section of ZigBee in Settings. Running a Flow the Device has a red Triangle with "!".

_Could you describe the setup of your ZigBee network in more detail?_ 
Got a ZigBee-Network only with Bulbs: Osram Lightify E27, E14 and GU10. The Distance from Homey to the first three Bulbs are 2 Meters in the same Room. The next 21 Bulbs are in the next Room with one Wall between Homey and these Bulbs. The Distance to the first of these Bulbs is round about 2 Meters.

**Comment by RobinBol** [comment]
@CyberSponk thanks for the info. Where exactly do you see the 'offline' label? In the state object in https://developer.athom.com/tools/zigbee? This is not something to take into account, it is a rather useless property.

In the next Homey firmware build I have added some more advanced logging so I will be able to see what the exact error message is when you can not control your devices.

**Comment by CyberSponk** [comment]
@RobinBol 
_Where exactly do you see the 'offline' label?_
On the Device-Card in a Flow in the Then-Column on the Device (Bulb). Running the Flow normally e.g. a Device becomes a green Hook/Glamp. Here sometimes the Device becomes a red Triangle with "!". On Mouse-Over on this Triangle you can see the Message. Sometimes there is a Message while Mouse-Over, sometimes there is a blank Label.

**Comment by CyberSponk** [comment]
Couldn't longer Assist/Help here with Lightify > Changed all Bulbs at Home from _Osram Lightify_ to _Philips-Hue_.

**Comment by RobinBol** [comment]
Merged with: https://github.com/athombv/homey/issues/1956
