### ISSUE TITLE
Developer: Multiple flow card arguments won't fit on card

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#187]
Because arguments/parameters all put on one 'line' they fall of the card on the right side. I would like these parameters presented as a list / under each other. 

![image](https://cloud.githubusercontent.com/assets/15232724/13033537/9181fc48-d31a-11e5-8537-78055587f5c3.png)

**Comment by WeeJeWel** [comment]
Hm, they should resize on hover. I'll investigate.

**Comment by WeeJeWel** [comment]
This is what should happen. What browser are you using?

![untitled](https://cloud.githubusercontent.com/assets/319873/13050069/4d5ed8ce-d3f1-11e5-8d46-05544e0f7909.gif)

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.18. Please re-open if issue persists.
