### ISSUE TITLE
[Toon] Can not set m3 / Wh tag in greater than logic

### ISSUE THREAD

**Issue by DeefK** [athombv/homey#1870]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Place the m3 and/or wh tag in a logic greater than field

**What was the result?**

Tag can not be placed in the logic greater than field

**What did you expect as result?**

Use the m3 or wh tag in the logic greater than field

**Any other remarks**

I like to get notified when energy is greater than X kwh for X minutes than notify. But the tag does not work

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by RobinBol** [comment]
Just fixed this in 1.3.3! Thanks for reporting.
