### ISSUE TITLE
ZigBee Turning Devices On/Off Loadavg High/Homey Slow

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#1872]
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Looked was the Value Loadavg in the settings is doing while switching On/Off ZigBee-Devices because Homey is while switching Devices sometimes slow.

*Please include detailed steps how we can reproduce the issue*
Switch On/Off ZigBee-Devices with Flow or Single-Device.

**What was the result?**
Value Loadavg in setting normal while looking 0.2x/0.3x. Switching On/Off ZigBee-Devices the Value is 2.0x and sometimes 3.0x and Homey is slow for a while.

**What did you expect as result?**
No slow Homey while switch Devices.

**Any other remarks**
No.

**Please attach a Homey System log (Settings -> System -> Send Log)**
If needed please let me know.
...

**Comment by RobinBol** [comment]
Thanks for reporting. If you can reproduce, could you send a system log?

**Comment by CyberSponk** [comment]
Moved all Bulbs back to HueBridge. If Log needed i try to add some TestBulbs to Homey and look if this could be reproduced.

**Comment by CyberSponk** [comment]
Tryed it Today with 7 Bulbs (E27, latest Osram-Firmware 01020510) on Homey 1.5.5 with LF-Beta-App 1.2.1 > No Problems with Loadavg or a slower Homey. Closing this Issue.
