### ISSUE TITLE
[Appv2] Location reported in the Indian Ocean and not able to zoom.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1877]
**What is your Homey version (Settings → System)?**
1.5.3 / Android preview 0.5.0

**What did you try to achieve?**
View the location of Homey

*Please include detailed steps how we can reproduce the issue*
Open Location in the App

**What was the result?**
Blue...... Ocean. 
![image](https://user-images.githubusercontent.com/12412734/31425394-73d8284e-ae5f-11e7-8228-642e92072e3d.png)

Could not zoom. 
Trying to zoom automatically switched Auto location off 

After saving in the App  the Web dashboard showed me near the coast of Somalia.

after playing around something looks to start working now while I write this. 
Strange.

**What did you expect as result?**
Working location view

**Comment by Inversion-NL** [comment]
My best guess is this is the location of Latitude 0 and Longitude 0.

**Comment by Dijker** [comment]
Nop, that's below greewich below Ivoorkust / Gana.

My best guess it was some default in the Netherlands with Lat and Lon exchanged: 
So~ 52 -  5 but then values exchanged!

**Comment by joachimroeleveld** [comment]
Your guess was right. Default lat/lon were indeed inversed! Not sure why you got the default anyway though.

**Comment by Inversion-NL** [comment]
Same for me. Is there anything I (we) can help you with in troubleshooting this issue?

I do have set my location to manual in Homey. Could that be part of the problem?

**Comment by joachimroeleveld** [comment]
I don't think so, but this may be a bug in Homey. We'll look into it. Thanks for the help, appreciated!

**Comment by Inversion-NL** [comment]
See my edited post, above

**Comment by joachimroeleveld** [comment]
This should be fixed in the next release which has just been released. Feel free to reopen if you still encounter issues. Thanks!
