### ISSUE TITLE
Alarm clock app v2

### ISSUE THREAD

**Issue by micha35fey** [athombv/homey#1881]
**What is your Homey version (Settings → System)?**

1.5.3

I'll hope that in the future you can set the alarm and you could choose on which device it goes off on the homey or on the phone or both. Then I could use the alarm flows in a better way.

**Comment by WeeJeWel** [comment]
Alarms will always go off on Homey, unless you create a Flow to make your own functionality!

**Comment by micha35fey** [comment]
Oké this is not possible in the future to add this functionality?



Op 20 nov. 2017 17:34 schreef "Emile Nijssen" <notifications@github.com>:

**Comment by WeeJeWel** [comment]
I think it's already added, just in a somewhat different manner :)

**Comment by micha35fey** [comment]
Dank je voor de snelle reactie

Ik doe het maar even zo, aangezien we beide Nederlanders zijn ;).

Ik begrijp je antwoord niet

Mvg

Micha Kooijman

Op 20 nov. 2017 19:27 schreef "Emile Nijssen" <notifications@github.com>:
