### ISSUE TITLE
Rebooting error

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#189]
When I'm restarting Homey via the WebApp i get  the following message 56 times and have to click Ok every time.

![2016-02-14](https://cloud.githubusercontent.com/assets/17165733/13033960/29e00ce8-d328-11e5-8800-0e11203604cf.png)

**Comment by bvdbos** [comment]
#160 and #126 fixed in next version. Please search before posting issues :+1:

**Comment by JesperJanssen** [comment]
Sorry did a search but only searched on the open issues.Thanks for the heads up. Issue can be closed
