### ISSUE TITLE
unable to pair 6th KAKU

### ISSUE THREAD

**Issue by ArjendR** [athombv/homey#1891]
**Homey version: 1.3.2

**What did you try to achieve?**
I try to pair a 6th KAKUdevice (5 are working fine) but now i'm trying to pair a 6th device: the ACM-2300H. The acm itself is working fine with its own KAKU-remote control. But homey isnt communicating with the acm receiver at all. When i try the pairing process, homey isnt responding to the acm own signal (also tried with homey within 1 meter and with a repeater) and when i try to pair with the remote control signal homey responds to that but the testing of the switch results in switiching an other kaku-receiver (AGDR3500)? I tried restarting homey and reinstalling kaku but with no other results... 

Pairing another 6th receiver (AGDR3500) results in the same communication silence from homey... 
Has anybody successfully paired 6 ore more receivers? Ideas, hunches (and fixes! ;-) are welcome! 

NB log:BF5C101824**

**Comment by BasKiers** [comment]
Hi,

The amount of connected kaku devices should not make any difference for the signal that Homey transmits. Could you confirm this by removing 1 of your 5 working kaku devices and then adding the AGDR3500. When you choose to copy the signal of the remote this should work with your ACM module (or AGDR socket). Could it be that this is a range issue? To test this you could try to locate the AGDR close to Homey and try to pair it with Homey using the "copy remote signal" option.

Regards,
Bas

**Comment by ArjendR** [comment]
solved...
I programmed the ACM to the 5th button on the KAKU-remote control. That is the G-button... The acm is working fine with the G-button but when homey is being paired with the g-button the acm doesn't respond to that. So definitly not a g-spot for homey! ;-)
