### ISSUE TITLE
[Appv2] Adding IKEA Tradfri opens Adding Z-Wave wizard

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1893]
**What is your Homey version (Settings → System)?**
1.5.3 - App v0.5.0.105
**What did you try to achieve?**
Add a IKEA bulb

*Please include detailed steps how we can reproduce the issue*
Open the new Mobile App and Press the big + Right Above in Devices.

**What was the result?**
![image](https://user-images.githubusercontent.com/12412734/31587653-b29101bc-b1e5-11e7-9bdd-d1bc38771e66.png)

**What did you expect as result?**
After Device Choose window  the correct ZigBee wizard.

**Any other remarks**
Tried with 2 devices, GU10 Tunable and RGB E27

Guess not an App issue but an generic issue?

**Comment by joachimroeleveld** [comment]
This should be fixed in the next release which has just been released. Feel free to reopen if you still encounter issues. Thanks!
