### ISSUE TITLE
I added one Fibaro wall plug, but now have 2 in the dropdowns

### ISSUE THREAD

**Issue by athomey** [athombv/homey#19]
I have no reproduction, except that I've seen various errors today, during tests with Homey. However, I added _one_ Fibaro Wall Plug, but in drop-downs I've got 2 of them. If I go to Settings | Z-Wave | Failed | Dropdown I also see two of them. One "New Z-Wave Device (2)", the original name, and a second one "Wall plug (2)" to which I renamed it at one time. 

I selected "New Z-Wave Device (2)" and pressed "Remove Failed Node". The button grays out, and nothing happens. It stays grayed out, until I e.g. go to Users in settings, and then back to Z-Wave. Then it's to be selected again. I press the button again, after a minute or to, an external-to-chrome pop-up appears and shows: "An error occured.true".  Which is very true indeed.

Concluding: I cannot delete this ghost device "New Z-Wave Device (2)". Question: How do I delete it now?

Programming: It seems to me there is a lot of non-atomic/transactional base-settings-of-nodes-and-devices code in Homey, and that's why I'm stuck with 2 devices for the same node? It seems not to be programmed in a defensive way. (Or is it?)  VeraEdge is full of this, and suffers from LOTS of phantom devices and such due to this. This is not coded the way it should I think?  Aside from bugs, multiple changes to data as an atomic transaction should always be taken care of. My 2cts...  :-)

((cosmetic bug: The hint of "Remove Failed Node" says "...to remove nod through..." it is missing the letter 'e'))

**Comment by ocatie** [comment]
My guess is there is somehow a duplicated device made when renaming. However I also cannot reproduce the issue.

If this is the case both devices should be deleted when removing the device with node id 2 from the network using the 'Remove node' button in the Z-Wave settings.

First time I hear about non-atomic/transactional as a student. I'll look up some literature. Thnx.

**Comment by ocatie** [comment]
Please reopen if issue persists.

**Comment by athomey** [comment]
The problem persists in 0.8.9. If I choose Remove node, or REmove Failed Not, I get a snake-eat-tail hoursglass, after a few minutes, I get the external-of-chrome error: "Unhandled error true". I cannot delete this ghost node in any way. Also Homey hangs now for a long time on "Running in another session. Try again later." after I refreshed. "Remove node" is not available anymore. 

((About atomic transactions, see for example; https://en.wikipedia.org/wiki/ACID))

**Comment by ocatie** [comment]
I cannot reproduce the duplicate device. Do you also have 2 devices in your Zone view or only in the dropdown?

If the Remove nod button is grayed out then the state of this process isn't Idle. The state can only be changed by the process itself started by pressing the button. When you start the remove device process and close the window, the process isn't cancelled but awaits the timeout. Please power cycle Homey to reset the process and try again to remove the device with node id 2.

The error: "Unhandled error true" is the callback that is being fired by the browser because the connection has been lost and wont be fired otherwise.

**Comment by ocatie** [comment]
I've managed to reproduce the issue with the Remove node "Running in another session. Try again later." message. The button has been pressed before Homey fully loaded and initialized the Z-Wave module. A power cycle fixes it. Please by wary not to press the buttons too soon for now.

**Comment by ocatie** [comment]
You can remove a device by using the Remove Node above, or try the Remove Failed Node. Otherwise you'll have to reset the Z-Wave network.
