### ISSUE TITLE
Remotes not recognized

### ISSUE THREAD

**Issue by MarcoBannink** [athombv/homey#190]
Tried to add my remotes to Homey, but none of them were recognized.

I tried the following remotes:
- Panasonic TV
- Philips Home Theater System
- Epsilon HTPC 

My Homey is running on version 8.17. Please close if already logged(didn't see it in the list) or included in 8.18.

**Comment by Wimstradamus** [comment]
same here,
Humax cable reciever remote
yamaha audio reciever remote 
LG tv remote

**Comment by bvdbos** [comment]
Remote = IR (Infrared) -> issue #50 #92

**Comment by MarcoBannink** [comment]
Moved my comments to issue 50 and closed this issue.
