### ISSUE TITLE
APPV2 - details of device - turned on since....

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#1901]
**What is your Homey version (Settings → System)?**

1.5.3, APPV2

**What did you try to achieve?**
All my devices show in their detailed screen " Turned on since 13:37" 
![fullsizeoutput_e0e](https://user-images.githubusercontent.com/17315800/31762055-5426e9fc-b4ba-11e7-8bf8-7a6baed64ba4.jpeg)

**Comment by caseda** [comment]
Duplicate https://github.com/athombv/homey/issues/1883

**Comment by laurenssss** [comment]
sharp, indeed duplicate (search let me down :( )
