### ISSUE TITLE
The day between Sunday and {next week} Monday doesn't work (Part 2)

### ISSUE THREAD

**Issue by rexvdb** [athombv/homey#1904]
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.5.3

**What did you try to achieve?**

I want to make a flow and it should work between Sunday and Friday so in the flow I place "De dag is tussen..."  Sunday and Friday. (I have test and made the screendumps on Thursday

**What was the result?**

![zovr](https://user-images.githubusercontent.com/30024883/31777848-5c629334-b4ef-11e7-8921-ecb3185a6484.png)
...

**What did you expect as result?**
The same as I switch the first day to Monday
...
![mavr](https://user-images.githubusercontent.com/30024883/31777900-8097e7cc-b4ef-11e7-976e-79565c38a92b.png)

Here you see that when I change the day from sun to Monday the flow works.

I want also reffer to incident #1684 The day between Sunday and {next week} Monday doesn't work 
...

**Comment by Dijker** [comment]
Same Issue #1684 still exists.... also in 1.5.6-rc8
![image](https://user-images.githubusercontent.com/12412734/35028456-71cfa61e-fb56-11e7-9e9b-f7e078a77e87.png)

**Comment by WeeJeWel** [comment]
Should be fixed in the next release, for real this time.

Relevant educational material: https://www.youtube.com/watch?v=-5wpm-gesOY
