### ISSUE TITLE
 [AppV2] Crash when using with Better Logic NumSlide

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#1906]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

In the new app, I tried opening a Better Logic NumSlide to change its value.

**What was the result?**

The app crashed

**What did you expect as result?**

The app not crashing and being able to change the value :-)

**Any other remarks**

No

**Please attach a Homey System log (Settings -> System -> Send Log)**

I created a log after the app crashed, but I don't know if an appcrash will be visible in the log?
45D4791DD1

**Comment by joachimroeleveld** [comment]
This should be fixed in the next release which has just been released. Feel free to reopen if you still encounter issues. Thanks!
