### ISSUE TITLE
[FEATURE] Shortcut to Notification center

### ISSUE THREAD

**Issue by WesRos** [athombv/homey#1908]
**What is your Homey version (Settings → System)?**

1.5.3.

**What did you try to achieve?**
When I'm into the Homey Desktop app, or web interface, there is a notification with the amount of notification. It's easy when there is a button to go directly to the notification center. 

**What did you expect as result?**
Easier process.

**Comment by jeroenvollenbrock** [comment]
We're currently not accepting any new feature requests for the desktop application, as it is soon going to be replaced with our new smartphone app.
