### ISSUE TITLE
[AppStore] Upgrading to Alpha/beta Channel Updated app not possible if Stabler version available

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#1911]
**What is your Homey version (Settings → System)?**

1.5.3
Appstore 20171021

**What did you try to achieve?**
Update my Alpha App to the latest version through the App store.

*Please include detailed steps how we can reproduce the issue*
Submit a new version as Alpha (fe v0.2.0)
Install on your Homey as Alpha
Find a typo to update the app on the repo. and update the version (mandatory)
Submit an update to the app store (v 0.2.1) as alpha, 
Upgrade to Beta, Submit to Athom for approval

Got to the App store to upgade your Homey to the latest App.
 
**What was the result?**

(the below mentioned beta isn't approved or published yet)
![image](https://user-images.githubusercontent.com/12412734/31853779-f48f6218-b68e-11e7-94d1-b0098d79ef9b.png)

The App store tries to upgrade to a stabler version. 

**What did you expect as result?**

Upgrading to latest Alpha, I wanted to stay in Alpha. 

**Any other remarks**
During installation/upgrade the store should ask if you want to upgrade only the latest version and stay in your less stable channel or upgrade to a stabler channel with purging the settings.

**Comment by joachimroeleveld** [comment]
This is a limitation in the current design of how apps are submitted and upgraded to channels. There is unfortunately no way to prevent this currently. However, this happens only for developers whose app is in submission. You can always install any version via the command line.

**Comment by Dijker** [comment]
@joachimroeleveld If it is a limitation and only hits the developer I will close as everything else is working.
