### ISSUE TITLE
Toon disconnects after every week

### ISSUE THREAD

**Issue by NiKoN33** [athombv/homey#1912]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
A stable functioning Toon

*Please include detailed steps how we can reproduce the issue*

Connect with Toon for longer than a week.

**What was the result?**

Toon disconnects and must first be removed with Apps
and be added again to use it.

...

**What did you expect as result?**
That Toon is stable and has no disconnects.

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment]
This is an issue for the Toon-repo: https://apps.athom.com/app/nl.eneco.toon
But to be sure: you have the latest version installed? There have been a lot of improvements around October the 5th...

**Comment by NiKoN33** [comment]
I have version v1.2.4 - 05.10.17 installed

**Comment by RobinBol** [comment]
Hi! This should not happen anymore after the update to 1.2.4. 

Some questions:
- Can you give some more information? Such as what does the error message say when Toon is 'not connected'?
- Have you tried completely re-installing the Toon app?
- Do you use the same Toon on a different Homey perhaps?

**Comment by NiKoN33** [comment]
The icon of Toon was greyed out with a cross.
Then I deleted the Toon device.
I did not uninstall the Toon app.It was updated as regularly.
Will do the uninstall--reinstall
I have not used the same Toon on a different Homey.

**Comment by RobinBol** [comment]
Ok thanks! I expect it had to do something with the recent Toon API outages, or a migration issue when updating the app to the latest version. Anyhow, after a re-install this should not occur anymore. If it does, let me know!

**Comment by Tiyrell** [comment]
Happened to me again today, after it worked for about a week. Had to reinstall the app to get it working again. Just deleting the device had no effect. So, not yet fully solved in 1.2.4.

**Comment by RobinBol** [comment]
If this happens again could you please send me an application log? (Settings > Apps, hold alt and send the log id).

**Comment by MarcelS1988** [comment]
Here Toon is also gone sometimes. mostly when I restart homey.
Or when homey was offline after restart it [https://github.com/athombv/homey/issues/1944](url)
I have send you the log: `21dcae9d-f980-4245-b189-3e9900b6a220`

**Comment by RobinBol** [comment]
@MarcelS1988 thanks for the log, was Toon offline at the moment you sent me the log? As I see nothing in the log that is malfunctioning, it has a authenticated connection to the Toon API and data is coming in.

**Comment by MarcelS1988** [comment]
@RobinBol he was just reconnect. Maybe I can try to simulate it? Than I will try it this week.
Please let me know.

**Comment by MarcelS1988** [comment]
@RobinBol I have done the update. After this the connection was gone.
I have send you the log before reconnecting.
Log: ` 4f77528b-1d92-4e9c-aad0-cb6e0a330c0c`
![image](https://user-images.githubusercontent.com/30636298/33140723-1fda4bc8-cfb1-11e7-8e40-249329760adf.png)

**Comment by RobinBol** [comment]
Thanks! I found something, it seems a bug in SDKv2 is causing this. I published a possible fix as beta in the app store, you may need to re-add Toon after installing it, then it should not go offline any more. Please keep me up to date on your findings!

**Comment by MarcelS1988** [comment]
Thanks! I have done the update, but I don't need to re-add Toon already so! I will let you know if it is okay or not!

**Comment by MarcelS1988** [comment]
After the last update toon do not working any more.
I looks it works fine, but the temperature was for days the same.
![image](https://user-images.githubusercontent.com/30636298/33518052-178810e6-d78f-11e7-933e-3adbe5594460.png)
Also after restart no change.
I have send you the log: `a2c652cb-383b-4177-ae4c-1e72f0e081db`

So i have re connect Toon again, after this still no data:
![image](https://user-images.githubusercontent.com/30636298/33518258-49694df2-d792-11e7-848f-e289c276d754.png)

**Comment by RobinBol** [comment]
Thanks for the info, from you logs I see that the refresh token was expired. If you remove Toon (and the app to be sure), then re-install Toon, it should work. If this does not work please send me a log from after the re-pair.

**Comment by MarcelS1988** [comment]
@RobinBol Thanks now it is working again!

**Comment by kukel** [comment]
Since the last Toon app update and a homey restart, this has been working 'stable' for over two weeks now... Never had that 'experience' before ;-)

**Comment by RobinBol** [comment]
@kukel thanks for the feedback!

@NiKoN33 since you created this issue, could you confirm that it is fixed for you as well (after a re-pair)?

**Comment by NiKoN33** [comment]
It seems to be fixed now.Toon seems to be stable now.

**Comment by RobinBol** [comment]
Thanks for reporting, if the issue re-occurs, pleas let me know!

**Comment by kukel** [comment]
Toon is **NOT** stable anymore... There has been a Toon update (on the Toon itself) and now the toon app in homey does not work anymore **without** any errors or whatever... It shows old data, telling it to set the temp a little higher does not do anything. If I need to remove and add it again (to be able to re-login if that is the problem, I'll (again!!!!) loose all insight data... Sigh... https://www.athom.com/en/press/#6f530d39-dfc8-478e-b8a5-3c3e60d4af43

**Comment by kukel** [comment]
And could large insights prevent the Toon app from working correctly?

**Comment by kukel** [comment]
@RobinBol: seems it was closed too soon. Homey has no Toon connection for almost two weeks now and I sort of refuse to pair it again. If this keeps going on, I honestly think Toon should be dropped from being supported since the insights become useless (removed) if you need to re-add a device over and over again. Unless there is a way to force a re-login or something... (cannot find that anywhere)

**Comment by MarcelS1988** [comment]
Here it is working still good
