### ISSUE TITLE
Can't find thermostat

### ISSUE THREAD

**Issue by tom1356** [athombv/homey#1916]
**What is your Homey version (Settings → System)? 1.5.3

x.x.x

**What did you try to achieve? Try to ad a new thermostat to my homey with the Honeywell Evohome app.

*Please include detailed steps how we can reproduce the issue*My thermostat was broken after i have bought a new one and installed it. I could ad it to homey, it can't find the new thermostat. even after removing the app in total.

**What was the result?**

...

**What did you expect as result?**
that i can add the new thermostat.
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
82B397F731
...

**Comment by jeroenvollenbrock** [comment]
Hi @tom1356,
The EvoHome app is a community App, maintained by @ralfvd. Therefore Athom cannot provide support on the EvoHome system. You can create an issue in the EvoHome app [repository](https://github.com/ralfvd/nl.bevlogenheid.evohome/issues), so @ralfvd can take a look at the issue. However, are you sure you have deleted the app **_and_** the Thermostat device? I've noticed the line 'Only 1 Evohome system is supported' in the readme of the app, So it might be your old thermostat that is preventing you from adding the new thermostat.
