### ISSUE TITLE
[Feature Request] Add a 'tag' field to devices

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#1917]
I'd like to be able to add 'tags' to devices (Maybe the name tag is not the best because we already have tags in Homey, but I have no better name for it)

I see this tag as a text field in which we can type any text we like. I think this is very usefull in combination with the devices in the flow editor.

Example:
Say I want to make a flow that reacts on a detected motion, but should only trigger on specific motion sensors. Right now this can be done with the flow below, but that would require you to have a unique identifier in either the Zone or the Name of the device which would probably be not very useful or logical in other areas in homey as these fields serve their own purpose.

<img width="958" alt="screenshot" src="https://user-images.githubusercontent.com/16610696/31960709-e40e84d4-b8f8-11e7-8b9c-5678d59ac68c.png">(I've added the 2 cards in the ...and... column as an example, not using both obviously)

If we have a 'tag' field we could virtually group devices for use in a flow as show in the screenshot. And Yes, I do realise the same can be achieved by evaluating on zone and use OR the check all zones, but that would be messy and would miss out on all other smart things we could do with 'tags' on devices.

**Comment by WeeJeWel** [comment]
This is an interesting idea but I'm afraid not many people will understand it. It's probably easier to A) create a Flow per device or B) add a 'tag' in the name or zone of the device.

**Comment by daneedk** [comment]
To bad this is closed because not many people will understand it, they will most likely not use it while it would be a great option for others who work a little longer with homey and start to find the ‘limitations’ of the workarounds you propose.

**Comment by johkin** [comment]
This would be a nice way to incorporate the functionality of the app Device Groups in the Homey system. This app is listed in the most popular section, so it can't be that hard to grasp for the people who installed it?
The openHab system has this functionality, and it's very convenient to be able to group items in a more flexible way, and also add groups in other groups.
