### ISSUE TITLE
make capability icons available for developers

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1919]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

make a custum capability, in this case for a thermostat with three temerature sensors , for the icon to appear in the mobile card you have to add the temeprature.svg icon 
```
 "mobile": {
        "components": [
          {
            "id": "sensor",
            "capabilities": [ "measure_temperature_one", "measure_temperature_two", "measure_temperature_three" ],
            "options": {
              "icons": {
                "measure_temperature_one": "./drivers/nt20/assets/measure_temperature.svg",
                "measure_temperature_two": "./drivers/nt20/assets/measure_temperature.svg",
                "measure_temperature_three": "./drivers/nt20/assets/measure_temperature.svg"
              }
            }
          },
          {
            "id": "picker",
            "capabilities": [ "thermostat_mode" ]
          },
          {
            "id": "thermostat",
            "capabilities": [ "target_temperature" ]
          }
        ]
      },
```

but to ablre to do that you have to dive very deep in the html of the device page of homey to find it. it would be easier if it was more easy available

...

**Comment by WeeJeWel** [comment]
I'm not sure I understand this issue correctly. Adding capability icons is documented here: https://developer.athom.com/docs/apps/tutorial-Drivers-Mobile.html

Closing this issue for now.
