### ISSUE TITLE
Developer: After submitting app, submission status is not visible

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#192]
After submitting an app at https://apps.athom.com/developers/submit-app and closing this page, submission status is no longer visible nor retrievable. 

BTW: In the submission conformation e-mail I received the version number is not shown:
![image](https://cloud.githubusercontent.com/assets/15232724/13036719/64b81846-d36f-11e5-899f-91b8e1d8b920.png)

**Comment by irritanterik** [comment]
Ah. I found it via the app screen on my Homey when debugging my app by CLI again: https://apps.athom.com/app/<app id>. 
Suggestion: put this link in the conformation e-mail.

**Comment by joachimroeleveld** [comment]
Thank you for reporting this. Fixed both of the bugs. Now, if you submit an app, your can still access your app in the overview like this:
![schermafbeelding 2016-02-15 om 20 58 58](https://cloud.githubusercontent.com/assets/5803704/13058964/459a1852-d427-11e5-9088-962c662efd5c.png)

**Comment by irritanterik** [comment]
thnx. Can confirm both fixes now.
