### ISSUE TITLE
APPV2 select zone not working

### ISSUE THREAD

**Issue by Leeuw1960** [athombv/homey#1920]
**What is your Homey version (Settings → System)?**

Homey = 1.5.3 APPV2 =1.0(5)

**What did you try to achieve?**

Try te select a zone in te the new iOS app

**What was the result?**

not possible. previous release APPV2 it worked well

**What did you expect as result?**

That i could choose a zone

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by joachimroeleveld** [comment]
This is now fixed in an OTA update. If you reopen your app twice it should be fixed. Thanks!
