### ISSUE TITLE
[Bug/error] Cant look at insight data

### ISSUE THREAD

**Issue by jtebbens** [athombv/homey#1922]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
Look at insight data

*Please include detailed steps how we can reproduce the issue*
Click on insight via Homey Deskopt app

**What was the result?**

Error message busy_migrating

**What did you expect as result?**

watch at my insight data graphs

**Any other remarks**

Since upgrade to 1.5.3 this is not working anymore.
Tried to removal all data but no result.

**Please attach a Homey System log (Settings -> System -> Send Log)**
DBF511AA28

**Comment by jeroenvollenbrock** [comment]
Can you send us a support ticket by emailing us at support@athom.com, and mentioning this GitHub ticket number (#1922)? Could you also please mention in the ticket if you've used experimental or DP releases?
