### ISSUE TITLE
[AppV2] Alarm days incorrect

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1923]
**What is your Homey version (Settings → System)?**

1.5.3, v0.6.0.106

**What did you try to achieve?**

Change alarm

**What was the result?**

All days are shown as a Sunday, however 3rd day is a wednesday...

**What did you expect as result?**

to see monday to sunday

**Any other remarks**

![screenshot_20171025-121454](https://user-images.githubusercontent.com/18570823/32015053-35881c4a-b9c0-11e7-8847-565c81109af2.jpg)

**Comment by priknr1** [comment]
Confirmed here

**Comment by joachimroeleveld** [comment]
This has been fixed in the next release (0.6.0), currently in the App Store. Thanks for reporting!
