### ISSUE TITLE
[feature request] code for slave devices like zwave has made general available forr all aps

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1924]
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

look how athom developers implement slave devices for eg plugs in kaku and zwave

**What was the result?**

a deep depression

**What did you expect as result?**

some more words on slave devices for amateur developers in sdk2 docs

 a lot of apps use plugs that measure and turn on and off or only pturn on and off , Plugwise already has 3 
...

...

**Comment by WeeJeWel** [comment]
I do not understand this issue. What is it specifically you are hoping we will do?

**Comment by nattlip** [comment]
some more words on slave devices for amateur developers in sdk2 docs or an example.

**Comment by WeeJeWel** [comment]
There is no concept such as 'slave devices' except in Z-Wave. I recommend you to add subcapabilities (e.g. `onoff.1` and `onoff.2`) when needed, but there are various ways - it really depends on the device.
