### ISSUE TITLE
Invalid nodes (Fibaro RGBW and NEO Motion Sensor)

### ISSUE THREAD

**Issue by cbho** [athombv/homey#1926]
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Opened an issue on my Fibaro RGBW Controller FGRGBWM-441 last week, as it was marked "Invalid node" after some time. PTP for other reasons seemed to solve the problem - but now it's back.
Now also a NEO Motion Sensor is marked as "invalid node"

*Please include detailed steps how we can reproduce the issue*
Difficult to say how to reproduce...

**What was the result?**

**What did you expect as result?**
Valid nodes :-)

**Any other remarks**
As it is now two different products, I think it may be due to something else, that just the units or related apps themselves.

**Please attach a Homey System log (Settings -> System -> Send Log)**
3112A6562B

**Comment by cbho** [comment]
Tried adding another NEO Motion Sensor (right out of the box) just a few hours ago - didn't change any settings, use it in any flows or anything, only changed it's name in the device-view - now it's marked as "invalid node".
Homey Firmware updated to 1.5.4 - the two other devices still marked invalid.

**Comment by cbho** [comment]
Added a NEO Door/window sensor - without any problems.
A few hours later, it is marked as "invalid node"...

Seems like something has happened at a certain time and units added since then are "rejected" after a short while...
Have tried PNP again...
New log: B86A6D85F0

**Comment by WeeJeWel** [comment]
We are investigating the issue, thank you for reporting!

**Comment by WeeJeWel** [comment]
Can you share both a screenshot of Zones & Devices, ánd https://developer.athom.com/tools/zwave?

**Comment by WeeJeWel** [comment]
Can you share both a screenshot of Zones & Devices, ánd https://developer.athom.com/tools/zwave?

**Comment by cbho** [comment]
The three Neo Coolcam devices:
![image](https://user-images.githubusercontent.com/29979509/33057751-aaafb8e4-ce8c-11e7-9b0f-8cde450c9e2c.png)

Opening settings on the first:
![image](https://user-images.githubusercontent.com/29979509/33057793-e489efc6-ce8c-11e7-925c-9dff04f9d38c.png)

Trying to change something and save:
![image](https://user-images.githubusercontent.com/29979509/33057946-7fe0ae7e-ce8d-11e7-98ba-3c0a939695bd.png)

Unfortunately, I cannot make a screendump of the Fibaro device now - have disconnected all Fibaro units for fw-update and a complete reset of the z-wave mesh as I didn't see other solutions (the "Invalid node" status was set on another brandnew Fibaro RGBW after a few hours this weekend)...

The map is not shown on the webpage - it keeps saying "Loading" - will try later again...

**Comment by Inversion-NL** [comment]
The map isn't showing for me either (Homey version 1.5.5, Ten z-wave devices).
Tried a reboot of Homey and another browser but no luck.
It did work, some time in the past, however!

Zigbee does work. However I don't have any Zigbee devices other than Homey.

I did allow unsafe scripts in Google Chrome but that doesn't help.

![image](https://user-images.githubusercontent.com/15921016/33136719-3467312e-cfa6-11e7-8ded-6194d4833865.png)

**Comment by WeeJeWel** [comment]
Could you invite me to your Homey on emile+support@athom.nl?

**Comment by cbho** [comment]
Of course.
Unfortunately, I think it will not help you now.
I'm doing a lot of testing on the upcoming SDK2-app by Ted Tolboom for Logic Home Controls ZHC5010 and I didn't like giving feedback based on a system with this type of error - so I ended up doing a factory reset as the error persisted (and I newer got the webpage to show my mesh).
After the reset, I have not seen errors like this.

I didn't close the issue, at the problem isn't really solved - only wiped away - my apologies for not being able to help more now, than with the logs I send to you earlier.

**Comment by WeeJeWel** [comment]
Okay, thank you. I will close the issue until it pops up again.
