### ISSUE TITLE
[Feature request] Have a retry button when adding a device

### ISSUE THREAD

**Issue by camilleversteeg** [athombv/homey#1927]
**What is your Homey version (Settings → System)?**

Latest

**What did you try to achieve?**

Adding a device often goes wrong. It either gives an error, it was too far away or I need to press the buttons on the device quicker. In 80% of the time that I need to add a device. I need to do it more than once. Having a retry button would help enormously. 

**What was the result?**

Spent too much time on adding a device

**What did you expect as result?**

After a device failed to add. Have a retry button.

**Any other remarks**

It would also be nice if the SEARCH would actually search and filter out the list of suggestions of devices. So when you Search specific name 'Tag Reader 500'. That it would only show 1 device and not the complete list of devices that are part of that app. 

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment]
We'd rather work on making adding devices always work :)

The search you're describing should or could be solved in the new Homey Smartphone App.
