### ISSUE TITLE
KAKU dimmer level incorrect

### ISSUE THREAD

**Issue by RemonBerends** [athombv/homey#193]
When i try to use my dimmer type AC-300, the brightness level doesn't match the actual level. 1% is Full on and 0,5% is 50% in real.

**Comment by bvdbos** [comment]
for me, using a ACD-300, when installed as "overig" it works as expected with a straight slider and percentages. Only a visual misconduct, closing and opening the slider-popup corrects this. When installed as a lamp, there's this weird half-circle slider which really isn't my favourite...

**Comment by RemonBerends** [comment]
Well i tried the above, but it doesn't work for me. Cannot pair at all anymore. My KAKU remote i cannot copy (old model YCT-102).

**Comment by Dennishacq** [comment]
The AC-300 and YCT-102 are from the old KaKu series, which is not supported yet.
The visual misconduct is fixed in 1.0.13, which should be up later today.

**Comment by RemonBerends** [comment]
Thank you for the aswer.Any idea when the older series will be supported?

**Comment by Dennishacq** [comment]
@RemonBerends I'm not sure, it depends on the amount of bugs i have to fix for other apps. 
I expect it to be done in about two weeks but i can't promise anything.

**Comment by Dennishacq** [comment]
The old kaku protocol is added in the new KaKu update.

**Comment by Dijker** [comment]
@Dennishacq 
Nice, do you know if the older KAKU is compatibe with older HomeEasy that I mentioned?
(https://github.com/athombv/homey/issues/52#issuecomment-195492904 )
or do they (brands/labels) al use different protocols and encoding?

**Comment by Dennishacq** [comment]
@Dijker See issue 52 :)
