### ISSUE TITLE
[AppV2] Various bugs in Settings

### ISSUE THREAD

**Issue by bm480** [athombv/homey#1930]
The following issues were found in build 5 of the new iOS App:

- Trying to open Led Ring in settings screen makes the app crash. 
- Changing Voice Settings, Playback rate shows "Something went wrong". Trying to change Playback voice immediately shows "Something went wrong". 
- Selecting Insights settings from settings takes a while to load (no spinner) but when its finished and you select Storage usage during scrolling several times "Something went wrong" appears although everything seems to work fine.
- Location screen does not show correct location. After changing, returning back to the main screen and again going to the location screen the location is still incorrect (unchanged from before). Also Find my location automatically switch settings is not saved. See also #1877 
- Opening General settings: An unknown error occurred, Retry appears. Furthermore a message "Connection with Homey lost" and a countdown is shown. After retrying a few times, the screen seems to load just fine.
- Settings for third-party apps only show a static page.

**Comment by joachimroeleveld** [comment]
Could you confirm whether any of the bugs still persist in the latest build (#6)? Many bugs have been fixed in this release. Thanks!

**Comment by bm480** [comment]
Results when retesting fixes in build 6:

- FIXED: Trying to open Led Ring in settings screen makes the app crash
- NOT FIXED: Changing Voice Settings, Playback rate shows "Something went wrong". Trying to change Playback voice immediately shows "Something went wrong".
- FIXED: Selecting Insights settings from settings takes a while to load (no spinner) but when its finished and you select Storage usage during scrolling several times "Something went wrong" appears although everything seems to work fine.
- NOT FIXED: Location screen does not show correct location. After changing, returning back to the main screen and again going to the location screen the location is still incorrect (unchanged from before). Also Find my location automatically switch settings is not saved. See also #1877
- FIXED: Opening General settings: An unknown error occurred, Retry appears. Furthermore a message "Connection with Homey lost" and a countdown is shown. After retrying a few times, the screen seems to load just fine.
- NOT FIXED: Settings for third-party apps only show a static page.

**Comment by joachimroeleveld** [comment]
Thanks for the update! No. 2 is fixed in the current release. No. 4 in the next release. No. 6 is still unresolved.

**Comment by bvdbos** [comment]
#6 works for me (at least for radio-app and podcast-app) through an android-phone (current build but also previous build).

**Comment by joachimroeleveld** [comment]
Some interfaces are indeed working, HomeyKit not yet for example. The app is showing settings screens only for apps with SDKv2, which is why you see less apps then in the current web interface. @WeeJeWel, could you investigate the issue with the HomeyKit settings screen?

**Comment by joachimroeleveld** [comment]
With the latest release, all problems should be solved. Please let me know if you still encounter issues.
