### ISSUE TITLE
[Feature request] Export flows

### ISSUE THREAD

**Issue by MbenzNo** [athombv/homey#1933]
Homey Version 1.5.3

As the number of flows increases, it becomes increasingly difficult to keep track of which flow is doing what, and that different flows does not interfere with each other.

It would have been helpful with an Export (to Excel) function to give an overview of Flow Name, Trigger, conditions and results

**Comment by WeeJeWel** [comment]
We won't add this functionality. Feel free to use the Web API to make such feature yourself!
