### ISSUE TITLE
AppV2: Using the mobile app for firmware updates

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#1934]
Checking for Homey firmware updates through the latest Android app results in a toast message saying that there are no new updates.
However after using the web interface to check for updates, Homey immediately found the newly released update.
Without starting the update on the web interface, going back to the mobile app, the app did show the new update.
After this the mobile app was able to initiate the update process.

Enhancement request:
Would like to receive feedback the update has been started.
Currently there is no feedback and the app is complaining it has lost the connection (which is technically true).

**Comment by joachimroeleveld** [comment]
The app checked for updates only the first time the update view was opened. This will be fixed in the next release.

Update progress/feedback should be already working in the latest version.

Feel free to reopen if you still encounter issues.

**Comment by Inversion-NL** [comment]
No, I've tried several times so only refreshing the view wasn't solving it.
I'll try the next Homey firmware update and report

**Comment by joachimroeleveld** [comment]
To clarify: the app didn't check for updates again until the app was closed and reopened. Did you also try that multiple times?

**Comment by joachimroeleveld** [comment]
Also, with the next release I mean the next smartphone app release.

**Comment by Inversion-NL** [comment]
I'll try again on the next (app and Homey) update with the new info I've got ;-)
