### ISSUE TITLE
media.Failed to decode 

### ISSUE THREAD

**Issue by elosodo** [athombv/homey#1935]
**Metadata**

* **1.5.3**:
* **112C60287C**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**What did you try to achieve?**
play music over youtube or soundcloud

**What did you expect as result?**
playing music

**What was the result?**
error that pops up every time i close it and no music is playing
media.Failed to decode http://127.0.0.1:40507/yt-stream/4ctK1aoWuqY

**Any other remarks**
reinstalled and reconnected both apps

**Comment by bvdbos** [comment]
Which youtube-file did you want to play? Does this also happen in the web-interface for that file? To which device did you want to play the music?

**Comment by elosodo** [comment]
I tried different files with the same result. This happens with YouTube and SoundCloud. The files work over the web interface of the websites.
I tried to play the music over the aux output which worked last week.

**Comment by bvdbos** [comment]
Can confirm for youtube, also on the webinterface. Suspect something with the conversion-service. The soundcloud-thing is just some buffers still in Homey (yt in the URL means it has to do with youtube), Soundcloud works. Better to file this bug on https://github.com/matjaz/homey-youtube

**Comment by WeeJeWel** [comment]
Please report this bug in the YouTube app repository!
