### ISSUE TITLE
[APPv2] App closes down immediately

### ISSUE THREAD

**Issue by cbho** [athombv/homey#1938]
* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: iOS 10.3.3
* **Smartphone App Version**: v2 (1.0 (6))

**What did you try to achieve?**
Open the app

**What did you expect as result?**
That it opens

**What was the result?**
Immediately after opening the app, it closes down again.
Have tried rebooting the phone - same result.

**Any other remarks**
Updated to the newest version of the app via Preflight at 2.11.2017 at 18:15.

**Comment by joachimroeleveld** [comment]
Hi, could you send me you email address via support@athom.com? From there I can help you further.

**Comment by HansDutch62** [comment]
Same issue on my samsung edgeS7 with Android version 7.0 after update last monday 30th. Homey app version 0.7.0

**Comment by cbho** [comment]
Solved after uninstalling and re-installing an extra time...

**Comment by nattlip** [comment]
+!
