### ISSUE TITLE
[com.Somfy] Doesn't work in 1.5.4

### ISSUE THREAD

**Issue by marklajer** [athombv/homey#1942]
**Metadata**

* **Homey Version**: 1.5.4, Somfy RTS Version 2.2.1
* **Homey Log Code**: DDA2D61E1A
* **Smartphone Platform**: iOS
* **Smartphone App Version**:  v2 beta

**What did you try to achieve?**
My Somfy RTS blinds doesn't work anymore after the latest upgrade 1.5.4 :-(  They doesn't respond. Tried to reset the blinds, the remotes and my Homey and add them again without any luck (they doesn't pair).  Please fix!

**What did you expect as result?**
They doesn't pair after upgrading to 1.5.4

**Comment by bvdbos** [comment]
No need to put an issue at multiple places ;-) Do other devices which use 433 Mhz keep working? Did you try a PTP (pull the plug)? Maybe the memory of the device is full, did you reset the device?
https://forum.athom.com/search?q=somfy+rts

**Comment by marklajer** [comment]
Don't have any other devices which use 433 Mhz i think.

tried to uninstall Somfy app from my homey, reboot and then reinstall the Somfy app again.

Tried full reset on Somfy and PTP - the Remotes work just fine.

**Comment by Inversion-NL** [comment]
Somfy RTS blinds are working just fine at my place.

**Comment by marklajer** [comment]
Well other users report the same exact issue. So it's luckily not only me..

https://forum.athom.com/discussion/2438/somfy-rts/p2?

**Comment by marklajer** [comment]
**Workaround found**

After factory restting my Homey the Somfy RTS work again

_I've already did full restart, hard reboot, reset all Somfy RTS motors._

An full factory reset of homey worked!

**Comment by jeroenvollenbrock** [comment]
Should be resolved in 1.5.8
