### ISSUE TITLE
can not ad the Motion Sensor (Z-Wave Plus) stops at exchanging security key[com.fibaro] 

### ISSUE THREAD

**Issue by Turtures** [athombv/homey#1946]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by caseda** [comment]
An issue, without any issue information, the pre made layout is there for a reason 😃

But to help you on your quest for inclusion, try rebooting your homey, just a soft reboot should be enough, but it that isn't sufficient a ptp (pull the plug) for a few minutes should definitely help

**Comment by Turtures** [comment]
Hello
Not so easy to fix. I had to uninstall the Fibaro appliance, run the reset on Z-wave, reinstall the Fibaro appliance, and then it worked again. But after that, Homekit Sprut1 did not work, so I had to do the same procedure with it too. Not so funny ! 
you have to fix so you manually can remove dead z-wave devices

Med vänliga hälsningar!
Tom Danielsson

**Comment by caseda** [comment]
Deleting a "dead" zwave device can be interpreted in 2 ways:
1. Either the device is dead or self, which you then can remove in homey with the X of the device and letting it timeout. 
2. Or the device is working but so needs a reset itself, either how it is described in the manual or via homey's settings -> zwave -> remove device.

There is no need to remove the entire app for both possible cases.

And is an entirely different issue then your titel suggests (especially the homekit one, as that is an community member created app)

The reboot was just for the issue you described in the titel, with that it hangs on exchanging the security key

**Comment by WeeJeWel** [comment]
@Turtures please follow the issue format next time. If the device hangs during inclusion, it's usually better to keep it in closer range.
