### ISSUE TITLE
[Zigbee][Lightify Osram][beta]

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1947]
**Metadata**

* **Homey Version**:           1.5.4
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:  current beta version 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

Lightify Gu 10 RGB spot

**What did you try to achieve?**
pair a spot

error , 

this summer it worked good, reporting this a week ago on slack everebody said no problem adding g10 bulbs, but i wonder if they did that in 1.5.4 ?    i tried 10 bulbs al went wrong, added then with no problem to hue, so no big problem still managble with the hue app

**Comment by Dijker** [comment]
This could be the same problem as #1936 
If it worked before pls send a Log to Athom and if 1.5.5 is out please re-test. 

You could also try a PtP on Homey to see if the problem disapears but I for me it didn't work (only tested once) and I wait a couple of days more to et it on Experimental.

**Comment by nattlip** [comment]
i always ptp with a homey problem

**Comment by nattlip** [comment]
i still have 25 to add no problem

**Comment by RobinBol** [comment]
Could you describe in a bit more detail what error your encountered exactly? Could you also provide a system log from right after you tried to pair a bulb?

**Comment by nattlip** [comment]
it works with homeys firmware 1.5.5 so no extra workneeded
