### ISSUE TITLE
Fibaro RGBW-Controller (FGRGBWM-441)

### ISSUE THREAD

**Issue by RemonBerends** [athombv/homey#195]
Showing for every of 5 dimming channels a device, but dimming levels don't work. Just first device is reacting.

**Comment by ocatie** [comment]
If you add the RGBW as a light. Are you able to control the color?

I'm experiencing the same with the Dimmer2. It presents itself as an multichannel device. Homey creates an device for every endpoint but only the root device reacts to commands. This will be fixed by an app.

**Comment by RemonBerends** [comment]
Well it is how you stated, just the root device reacts. It means that i can adjust the Red color and the GBW values not. Have to say that the dimming level from the slider is not correct: 20% level is full on.

Really looking forward for the app, it will be a general Zwave app or one dedicated to Fibaro modules? Any idea for a release date?

**Comment by ocatie** [comment]
If the root device is added as a light the color can be controlled.
