### ISSUE TITLE
LG Airco IR does not work as previous

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1951]
* **Homey Version**: 1.5.4

**What did you try to achieve?**
Set LG Airco on and off 

**What did you expect as result?**
Working as before v1.5.4 

I have copied my LG Airco remote to Airco ON and Airco OFF previously I had this working before but with 1.5.4 this is not working anymore I think I need to reset and recreate the IR on and IR off switch to get it working as it should.

Just as before not that the airco is on when an off command is given.

**What was the result?**
The airco was running

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Could you please follow the contributing guidelines and include a log code?

**Comment by chrisboer** [comment]
Updated

**Comment by chrisboer** [comment]
With version 1.5.5 it worked again
