### ISSUE TITLE
[com.nest] Feature request setting temp

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#1955]
Would it be possible to add a card where we can put in a numeric value for the temp? And cards to increase / decrease the temp with a fixed number?

Want to use other device to be able to set the temp but at this point there is only a slider in the flowcard so not possible atm.

**Comment by jeroenbos22** [comment]
Just learned that I can drag a numeric value on top of the slider, but think an increase / decrease by amount card would be nice

**Comment by WeeJeWel** [comment]
In that case, duplicate of https://github.com/athombv/homey/issues/1957
