### ISSUE TITLE
missing temperature offset feature - to adjust to actual temp

### ISSUE THREAD

**Issue by elfrigo** [athombv/homey#1957]
I have several temperature sensors in different devices on various places (wall/ceiling etc).
Most of them have no internal code (raw configuration parameters) to adjust the displayed/reported temperature.

Since several devices are off more then 2 degrees it's somewhat inconvenient to remember all differences of the actual temperature.

I know Domoticz has ways to correct this at "device" level. In Homey I can't find any such feature.
Please add the possibility to change (+ and -) the device reported temperature.

* **Homey Version**
1.5.5

**Comment by elfrigo** [comment]
FYI [com.nest] Feature request setting temp #1955 is a different issue. I don't want correction in flows/cards, but on the devices (report) level.

**Comment by WeeJeWel** [comment]
I think this should be an app-specific feature. You can also create a Flow with some math logic, e.g. `{{temperature - 2}}` to show the temperature somewhere else.

**Comment by elfrigo** [comment]
From your reaction and information a cannot deduct if any team-discussion or community feedback has lead to this closure.
> I think this should be an app-specific feature.
I **know** this should not be an app-specific feature ... since it is a central device correction.
All apps should get the right information from the system itself and not rely on different corrections or separate flows.
I also is connected to the "Insights" menu which will be wrong too.
Like I stated in the comment on Nov 30th you don't want flows to correct this level or errors. This should be done on the device (report) level.

Please reopen this issue/enhancement and put some some thoughts in it.

**Comment by bvdbos** [comment]
As this should be done on a device-level like you say, it's up to the app-specific code. After all, we want the temperatures in insights to be the corrected temperatures, not the wrongly reported data from the sensors.

**Comment by elfrigo** [comment]
This gives me the idea that an App is not really an app but more like a device driver?
