### ISSUE TITLE
"Radio" App not working on Sonos speakers due to UPNP problem

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#1959]
**Metadata**
* **Homey Version**:1.5.5
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: Radio Beta v0.0.2
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Via the Audio-Jack, I can play the Radio stations, but when I choose one of my Sonos speakers, the chosen sound is not directed to that speaker, when that speaker was already playing some music, the music is not replaced by the "new radio station" sound. Using the "stop" / "Play" icons, the sound of the chosen Sonos speaker is stopping and starting again, but the source is not changing.

**What did you expect as result?**

**What was the result?**

### **Any other remarks**
[https://github.com/bvdbos/com.sasteren.radio/issues/2#issuecomment-343756770](url)
bvdbos comented: problem is due to the UPNP-part of Homey, can't do anything about that.
--

**Comment by JPe2** [comment]
Still the same problems with Sonos!
Homey Firmware Versie: 1.5.6-rc.8
Radio v1.1.0 Bas van den Bosch

**Comment by bvdbos** [comment]
It's reported that the new beta of Sonos works great with radio!

**Comment by chrisboer** [comment]
Hi Bas, could you show in a picture how we can select a radio station in a flow because I cannot drag a radio URL I added to the app towards a Homey Music flow

**Comment by bvdbos** [comment]
![2018-02-23 18_36_53- 250 flow - homey3](https://user-images.githubusercontent.com/1064079/36607994-a91ee0e6-18c8-11e8-996a-8358762687e9.png)

**Comment by chrisboer** [comment]
Top Bas... it works...

**Comment by JPe2** [comment]
![clipboarder 2018 02 26-002](https://user-images.githubusercontent.com/3833862/36672462-9e597430-1aff-11e8-85e3-c4a8306d5acd.png)
Type-in Radio and be supprized

**Comment by bvdbos** [comment]
@JPe2 answer already given?

**Comment by bvdbos** [comment]
Then please close this issue and file a new one (but I think you mean #2277 ?)

**Comment by JPe2** [comment]
You are right again, #2277 does describe the problem, thanks reminding to close.
