### ISSUE TITLE
[Enh] Simply cast URL to Homey music

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1962]
**Homey Version**: 1.5.5
**What did you try to achieve?**
With chromecast it's possible to cast a url (for radiostreams, videostreams etc). Would be really helpful to have a simple "cast URL" for all music devices.

**Comment by WeeJeWel** [comment]
This would be possible if an app is created to do just this (maybe https://apps.athom.com/app/com.internet could add this functionality)

**Comment by bvdbos** [comment]
This was solved with the radio-app. One can add an url there and play it from the UI.
