### ISSUE TITLE
[Add function NFC] NFC Flow's

### ISSUE THREAD

**Issue by MarcelS1988** [athombv/homey#1965]
Hello, maybe it is a idea to add a function for the NFC in the flow.
I like to see that you can add the flow's also in the AND column.

**Comment by Dijker** [comment]
Hello MarcelS1988, 
Could you please use the Issue Template and  follow the [Contributing Guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) 

Scanning a Tag is usually a trigger, somthing tha happens in a split second and executes a flow once.
In the AND column are conditions, what condition do you have in mind for NFC?

**Comment by WeeJeWel** [comment]
You could add the most recent scanned ID to a variable using the 'Logic' cards, if that's what you mean.
