### ISSUE TITLE
Suggestion for Ledring; nice to have

### ISSUE THREAD

**Issue by roosbabeth** [athombv/homey#1966]
**Metadata**

* **Homey Version**: Homey Firmware Version: 1.5.5
* **Homey Log Code**:
* **Smartphone Platform**: IOS
* **Smartphone App Version**: 1.3.3 - Build 70

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I have my smartmeter connected to Homey. I wanted to change the color of the ledring based on the energy use from green to red, and blue when power delivery to grid

**What did you expect as result?**

I would like to be able to set the color of the ring dynamically based on a tag-value

**What was the result?**

Now I have to make several flows for several energy use ranges and am more or less limited to a few worklfows and not able to set the color smoothly.

**Any other remarks**
Just a suggestion and a nice to have and realizing that the app 'ledring' as I now use is from 3rd party developer.

**Comment by WeeJeWel** [comment]
Sounds like a feature for the LED Ring screensavers app!

Closing due to this being too 'advanced' for the core of Homey.
