### ISSUE TITLE
[Feature request] HUE features in Homey

### ISSUE THREAD

**Issue by Rickmann** [athombv/homey#1967]
It would be great to have more of the default features that are available in the HUE app also available in Homey / Homey app.

The feature that i am talking about is the following.
In HUE u can click the Room name / icon and u can set four default "Recepten" : Ontspannen, Lezen, Concentreren, Energie.
In the room u can choose some scenes u want to enable "Scenes" :  Ontspannen, Lezen, Concentreren, Energie, Savanna, Tropical

So with one click u can set a moodlighting in the HUE app.
This is at the moment not possible in Homey / app without using flows to automate something.
In Homey app atm u can enable a light or choose a manual color.

Basic features should be implemented in Homey / app if u want your userbase to use your app instead of having to switch between apps

**Comment by jeroenvollenbrock** [comment]
This will be resolved by the introduction of the new smartphone app, the device view and flow view already show "play" buttons for flows that have a "When this flow gets triggerd" trigger card.

**Comment by WeeJeWel** [comment]
And for now, as a workaround, you could use the 'Virtual Devices' app to trigger a Flow from the device overview.
