### ISSUE TITLE
Problems with Fibaro Universal sensor / z-wave

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#1968]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: B6AAA5B72A
* **Smartphone Platform**: Apple
* **Smartphone App Version**: 

**If related to a Homey App:** Fibaro
* **Homey App Version**:v1.5.12
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Fibaro Universal Sensor with four temp sensors attached

**What did you try to achieve?**

I use the temp sensor for my heating system in my house and home office, since the update to 1.5.5 the sensors are not updated with temp information anymore

**What did you expect as result?**

Every 10 sec realtime temp information

**What was the result?**

No information

**Any other remarks**
Only after a restart of Homey i get once actual information about temperature, after it keeps the temp like it was when it gets the first time after restart.

**Comment by caseda** [comment]
Please also note that insights _did_ update (as stated on slack by OP), just not the capability value.

**Comment by caseda** [comment]
Hows the device behaving now? Is it sending the measurements still?

**Comment by fvhuizen** [comment]
It seems stable for the time being

**Comment by WeeJeWel** [comment]
Great! Let me know if it still persists.
