### ISSUE TITLE
[Feature Request] New mobile app has more capabilities space

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1974]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: null
* **Smartphone Platform**: Android
* **Smartphone App Version**: 0.7.1.109

**If related to a Homey App:**
* **Homey App Version**: null
* **Homey App Log Code**: null
* **Affected Devices (preferably product codes)**: see remarks

**What did you try to achieve?**

Display all capabilities (or even be able to extend it with for example animations) of a device in the new mobile app, as it has more real estate then the (old) mobile cards to put them in.

**What did you expect as result?**

An added key/value/tag, so that there can be more capabilities displayed.
For example `"hideFromCard": true` tag to hide the capability from the mobile card.
Or a complete new object, for capabilities in the new app.

**What was the result?**

The size of the (old) mobile card restricted certain cases to display information.

Example: the fibaro rgbw controller, that can dim, and change color, but also measure_power and meter_power. 
In the old card we can't display the measurements as the dim slider would become too small.
In the new app, this is no longer the case, as the size is practically unlimited, but not possible to show them as there is no way to differentiate.

**Any other remarks**
Current devices (for me) that would benefit from this:
(* = needs to be hidden due to size limitations)
Fibaro RGBW controller. (dim, hue/saturation/light-temperature, measure_power*, meter_power*, animation*(picker, extension))
Eurotronic Spirit (target_temperature, thermostat_mode, measure_temperature, (child)protection (picker)*, manual_valve(dim)*)
Eurotronic comet && Eurotronic stella (target_temperature, thermostat_mode, measure_temperature, manual_valve(dim)*)

**Comment by WeeJeWel** [comment]
Thank you for the suggestion. Have you seen the screenshot in the Software Update?

![](https://gifyu.com/images/lightf09f4dd9b282700f.gif)

We are most likely moving toward a 'one component visible at once' design.

I'm closing this issue as it cannot be 'solved', but the idea is heard and noted!

**Comment by caseda** [comment]
I have seen the screenshots, but that will still leave the hidden capabilities hidden, atleast until the mobile cards are fully fased out.
Please do keep it into consideration 😃

**Comment by WeeJeWel** [comment]
We will still leave the developer in control how to use the device's capabilities. If they do not specify a 'mobile' component, an automatic selection is made.
