### ISSUE TITLE
Something went wrong accessing devices (LIFX/Milight/Ikea Tradfri/others?)

### ISSUE THREAD

**Issue by Mecallie** [athombv/homey#1978]
**Metadata**

* **Homey Version**:
1.5.3
* **Homey Log Code**:
???
* **Smartphone Platform**:
Android 7.1.1
* **Smartphone App Version**:
0.7.1.109 (beta)

**If related to a Homey App:**
LIFX
* **Homey App Version**:
LIFX 2.0.6
* **Homey App Log Code**:
???
* **Affected Devices (preferably product codes)**:
LIFX lightbulb (E27)

**What did you try to achieve?**
When trying to do any action on my kitchen LIFX light I get the error "Something went wrong accessing device". On the production Homey app it works fine. Also: all other LIFX bulbs work fine in the beta app!

**What did you expect as result?**
I expect to be able to take actions on my LIFX bulb. Eg: turning it on/off, change the colour, dim the light, etc..

**What was the result?**
I received an error "Something went wrong accessing device".

I have 2 more identical lights, they work fine. Firmware level of the lights is the same. The one light I cannot operate from the beta app works fine in the normal app...

**Comment by RobinBol** [comment]
Note: this seems to happen for more devices, I encountered it myself with Milight and Ikea Tradfri devices. Needs further investigation.

**Comment by RobinBol** [comment]
This does not seem to happen anymore, can you confirm @Mecallie ?

**Comment by Mecallie** [comment]
@RobinBol : just tested. I can now control the light with the beta app.

To be honest: I still think Athom should use the local lan API. I use that with HomeAssistant and it is ten times quicker, never gives me any issues...

**Comment by RobinBol** [comment]
Thank your for your answer! Then I'll consider this issue closed for now, if the problem returns please let us know.

Regarding the LIFX api, we chose to drop the local lan API as it was less reliable in our experiences.
