### ISSUE TITLE
LIFX lightbulb dim level or 

### ISSUE THREAD

**Issue by Mecallie** [athombv/homey#1979]
**Metadata**

Homey Version:
1.5.3
Homey Log Code:
???
Smartphone Platform:
Android 7.1.1
Smartphone App Version:
0.7.1.109 (beta)
If related to a Homey App:
LIFX

Homey App Version:
LIFX 2.0.6
Homey App Log Code:
???
Affected Devices (preferably product codes):
LIFX lightbulb (E27)
**What did you try to achieve?**
Change the dimming level or saturation of my LIFX light bulbs.

**What did you expect as result?**
The bightness or the colour saturation of my bulb should change, without changing the base colour.

**What was the result?**
The colour of my light is reset to the most white (blue-ish). Sometimes when I dim the light it is fine, most of the time the light is dimmed but also reset to the base white colour. This is not good for my pale European complexion, it makes me look sick 🤒 

You have three sliders:
Brightness
Saturation/colour
White colour temperature

The last one works as expected: setting the white colour temperature.
The other two often make the light revert to the most white (6000K?) and you have to set the white temperature using the other slider again.

Works the same in the webinterface, the official and the beta apps...

**Comment by Mecallie** [comment]
Update:
Now using App version 3.0.1 I cannot see any of my lights anymore.

I have granted permissions to Athom to control my lights, but none are found.

This might have something to do with my cloud.lifx.com and the LIFX account not beeing linked? I can control the lights using the LIFX app just fine.

And is this the proper place to request using the lan protocol instead of the cloud api? I really do not like having yet another dependency on a third party. This is one of the main reasons for my to have bought Homey :(

**Comment by WeeJeWel** [comment]
You should connect your LIFX bulbs to your LIFX Account in the app, then Homey will find them.

We have dropped support for the Local API because it was _very_ unreliable!

**Comment by bvdbos** [comment]
I don't like to use an 3rd party cloud either so:
https://github.com/bvdbos/com.sasteren.lifx-local

**Comment by Mecallie** [comment]
This was already known. I am sure they have their reasons for dropping local lan support. Although I do not agree with the stability part: I never had any stability issues, not using the Homey App nor using local lan support on Domotics for over a year.

I still hope you will reconsider folks. Now my lights are dependent on an internet connection and the existence and goodwill of the LIFX service. If LIFX goes belly up I can no longer turn on my lights.

The main reason for me to buy Homey for me was that it supports a lot of devices _directly_. Thus safeguarding my privacy and the above reasons. Otherwise I could have bought a SmartThings or Vera Plus.
