### ISSUE TITLE
Change philips hue color doesn't fit with multiple device in flow

### ISSUE THREAD

**Issue by jeroenk50** [athombv/homey#198]
When adding mulptiple philips hue lights(color selection card) to the flow output. The selection window is behide the card underneath. The ok button is under the delete button from the 2nd card down .

The selection window should be on top of the other cards or the cards should move down to make room for the selection window.

Also the collor setting will go outside of the screen (with smaller screens). There should be a scroll bar in the case.

Using google chrome.

**Comment by bvdbos** [comment]
#173 already fixed for next version
