### ISSUE TITLE
FlowCardTriggerDevice - cannot send token of type Number

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#1986]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Send a device trigger with a token value of type Number. This results in an error.

E.g.
`handlers.override = new Homey.FlowCardTriggerDevice('override')
handlers.override.trigger(this, { temp: 0 }, {})`

**What did you expect as result?**

Be able to send tokens of type Number without an error.

**What was the result?**

`Error: missing_tokens
    at Object.<anonymous> (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:1040)
    at JSON.parse (<anonymous>)
    at Object.jsonToObject (/opt/homey-client/system/manager/ManagerApps/jsonfns.js:1:938)
    at function.e.apply.s.args.map.s (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1345)
    at Array.map (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1330)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11) message: 'missing_tokens' }`

**Any other remarks**
Changing the type to String removes the error.
E.g.
`handlers.override.trigger(this, { temp: '0' }, {})`

**Comment by bvdbos** [comment]
Just to be sure: in your apps.json you defined the token as a number and not a string?

**Comment by nlrb** [comment]
The token has no type.
`  				"tokens": [
  					{
  						"name": "temp",
  						"title": {
  							"en": "Temperature",
  							"nl": "Temperatuur"
  						}
  					}
  				]
`
Same as in the [Athom example](https://developer.athom.com/docs/apps/tutorial-Flow-State.html). Note that in the documentation in the JSON an example value of "5" is set, while in the code the token is given a number value of 3.

**Comment by bvdbos** [comment]
Think if no type is set, it's automatically a string... The documentation might be wrong, there's other places with typo's ;-)

**Comment by caseda** [comment]
No you are correct, no type set will default back to string, otherwise it might change the type on boot for example, when no value was set yet, breaking lots flows

**Comment by nlrb** [comment]
@bvdbos Thanks for the hint, adding `"type": "number"` does resolve it.

However, there are still 3 issues that exist IMHO.

1. Documentation example is wrong and should be updated
2. Error message is wrong, the token is not missing, but has a wrong type
3. Better to enforce that the JSON always has the type or clearly document the type is string if omitted

**Comment by caseda** [comment]
1. The example in the developer documentation sports a nice `"type": "number"` tag.
https://developer.athom.com/docs/apps/tutorial-Flow-Tokens.html
2. True
3. En forcing is not possible, because the type before was always string (you couldn't define a type), and there are still apps using the no type token, even new ones (cause why add the type of you need string anyway), breaking all those apps.

**Comment by bvdbos** [comment]
![](https://media.giphy.com/media/l0MYtC6N9bJ7I6Zvq/giphy.gif)

**Comment by nlrb** [comment]
1. Reference was to the '[State](https://developer.athom.com/docs/apps/tutorial-Flow-State.html)' documentation, where the code now throws an error as the argument is of type Number and the token of type String.
3. Enforcing for SDK v2 should be possible. According to the 'Token' page documentation @caseda references, the type is not optional.

**Comment by WeeJeWel** [comment]
Thanks @nlrb, that specific page has been fixed. I have also added a sentence on the Tokens page that `string` is indeed the default token type.

Enforcing the type will break some apps, so this is good enough.
