### ISSUE TITLE
Missing global tag for `Weeknumber`

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#1987]
**Metadata**

* **Homey Version**:Homey Firmware Versie: 1.5.5
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Like to have the WeekNumber as a Global Tag

**What did you expect as result?**

The Tag weekNr in the Global tags under Date-Time

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
I wouldn't like my UI cluttered with things I don't use....
but related : #1465 and #1856

**Comment by WeeJeWel** [comment]
What would be the usecase for this?

**Comment by JPe2** [comment]
For me, for now, mainly for logging purpose.

**Comment by WeeJeWel** [comment]
Kind-of duplicate of #1856 :)
