### ISSUE TITLE
Please re-open #1975

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1988]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by WeeJeWel** [comment]
Please do not create an issue, but reply in the original issue and be patient.
