### ISSUE TITLE
[com.home-connect] App crashes on loading

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1989]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: 0707142508
* **Smartphone Platform**: not relevant
* **Smartphone App Version**: not relevant

**If related to a Homey App:**
* **Homey App Version**: 0.1.1
* **Homey App Log Code**: 71d49565-ced4-49c2-b0e1-6b57cfb7c4f0
* **Affected Devices (preferably product codes)**: none installed yet

**What did you try to achieve?**
Install the home connect app and have it run.

**What did you expect as result?**
app to work :)

**What was the result?**
Installed the app, crashes instantly on startup. Rebooted homey, app was last to finish loading and crashed instantly.

**Any other remarks**
Please add the dryer next.

**Comment by WeeJeWel** [comment]
Fixed in v1.0.0.

**Comment by cjvs** [comment]
Confirmed, not crashing anymore. Waiting for the dryer, and able to assist.
