### ISSUE TITLE
ZWAVE STATUS DONT UPDATE

### ISSUE THREAD

**Issue by filoor** [athombv/homey#199]
When i switch one of my zwave switches manuel it never updates on home it only change status if i switch it from homey

**Comment by freemann** [comment]
Which Brand/type is the module and did you check the Zwave associations?

**Comment by filoor** [comment]
mostly fibaro bult in switches and dimmers i have associations for groep 1 2 3 all on 1

**Comment by filoor** [comment]
it works now after restart of homey

**Comment by ocatie** [comment]
Please turn caps lock off ;)

You probably didn't set the correct association. For Fibaro Non-Z-Wave Plus devices make an association on group 3.
