### ISSUE TITLE
[docs][developer][sdk2][Driver]

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#1990]
![capture](https://user-images.githubusercontent.com/7040452/33096378-0c585a7c-cf07-11e7-928a-409fce987168.PNG)

**Comment by bvdbos** [comment]
cryptic 🤣 
copy-paste error in description?

**Comment by WeeJeWel** [comment]
Fixed

**Comment by nattlip** [comment]
in your dreams maybe

**Comment by bvdbos** [comment]
https://apps.developer.athom.com/Device.html#hasCapability
![2017-11-22 18_06_56-device - documentation](https://user-images.githubusercontent.com/1064079/33140345-f7ada5e2-cfaf-11e7-845e-5f4b9279bbaa.png)
😗 Or do you see that at another place still?

**Comment by nattlip** [comment]
you are correct , i deleted the message
