### ISSUE TITLE
Smart Presence / Homey states that guest comes 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1991]
* **Homey Version**:
1.5.5 

* **Homey Log Code**:
6B3E0B64AE

* **Smartphone Platform**:
Android (for the guest phone)

* **Smartphone App Version**:
No app installed

**If related to a Homey App:**
* **Homey App Version**:
Smart Presence v0.2.8
* **Homey App Log Code**: NA
* **Affected Devices (preferably product codes)**: Phones

**What did you try to achieve?**
Nothing was good before the new update of smart presence.

**What did you expect as result?**
To have the entering guest actionflow only ones 

**What was the result?**
Every delay setting in smart presence gives a new trigger that a guest has entered. 

**Any other remarks**
Resolved it this way but this is not the way it should work of course
![afbeelding](https://user-images.githubusercontent.com/23163409/33164345-9910dfa8-d032-11e7-803b-cd5e228b4dbe.png)

**Comment by bvdbos** [comment]
This is an issue for smart presence, not for Homey? 
https://bitbucket.org/terryhendrix/homey-smartpresence/src

**Comment by WeeJeWel** [comment]
Smart Presence is a community app, please create an issue there.
