### ISSUE TITLE
Slow network reported in Chrome console, but seems unlikely

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1992]
**Metadata**

* **Homey Version**: v1.5.5
* **Homey Log Code**: 
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

In order to solve issue #1975 I was asked to open the Chrome console. It shows slow connection...However, speed test via my phone at the Homey location, is excellent.

<img width="644" alt="schermafbeelding 2017-11-23 om 13 22 14" src="https://user-images.githubusercontent.com/10754229/33172668-5a95215c-d051-11e7-8d22-db0048b9a09c.png">

**What did you expect as result?**

Homey and my router have had the same location for over a year. The slow connection issue seems unlikely. To check, I placed Homey next to the router and re-checked the console again.

<img width="917" alt="schermafbeelding 2017-11-23 om 13 24 17" src="https://user-images.githubusercontent.com/10754229/33172740-a3f34ec8-d051-11e7-8e89-fcc8c162d899.png">

**What was the result?**

Chrome console still reports a slow network.

**Any other remarks**

**Comment by WeeJeWel** [comment]
Apart from the logs, do any Homey web related functions not work as expected?

**Comment by Eternity-again** [comment]
The 'slow network' notification does not seem to interfere with any functions. Z-wave inclusion can be tricky, but I  do not know if this is related to this issue. 

I have difficulties including a Spirit radiator valve, and this might be related to the slow network. But, again, it could be a z-wave hick-up.

**Comment by WeeJeWel** [comment]
That is definitely not an issue. Closing this as there's no problem.
