### ISSUE TITLE
Not possible to open flows anymore

### ISSUE THREAD

**Issue by dbonsaksen** [athombv/homey#1993]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: B10ED806C6
* **Smartphone Platform**: 
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Editing flows

**What did you expect as result?**
Being able to see and edit my flows

**What was the result?**
When I open my flow editor in the Homey desktop app its completely blank, not able to see any of my flows, not showing devices. If I go to devices I have a lot of them. I have tried osx High sierra, Windows 7, google chrome. Same with all of them.

**Any other remarks**
![skjermbilde 2017-11-23 kl 20 26 15](https://user-images.githubusercontent.com/28441083/33187198-637ccbc8-d090-11e7-86ef-459da11627d0.png)

**Comment by jeroenvollenbrock** [comment]
Your log shows a zigbee device with invalid flow card data called OVH, could you try to unpair it and check if it resolves the issue?

**Comment by dbonsaksen** [comment]
That fixed it. Thank you!

**Comment by RobinBol** [comment]
This issue should be fixed in 1.5.6, thanks for reporting!
