### ISSUE TITLE
Domitech / ZwaveDevice: Trigger gets filtered when lamp is already on according to Homey

### ISSUE THREAD

**Issue by timkouters** [athombv/homey#1994]
** Steps to recreate **
Shared setup:
Create a flow with a Domitech lamp with trigger "Lamp turned on".
Let Homey say something when the trigger is triggered.

Setup for OK-scenario:
Physically turn on the domitech lamp by powering on with physical light switch
[Trigger might occur, but not part of reproduction steps]
Turn off the Domitech lamp with the Homey-app
Physically turn off the lamp with the physical light switch
Wait 5 seconds
Physically turn on the domitech lamp by powering on with physical light switch
Homey will say something because the trigger of the created flow is fired

Setup for NOK-scenario:
Physically turn on the domitech lamp by powering on with physical light switch
[Trigger might occur, but not part of reproduction steps]
Do NOT turn off the Domitech lamp with the Homey-app
Physically turn off the lamp with the physical light switch
Wait 5 seconds
Physically turn on the domitech lamp by powering on with physical light switch
Homey will NOT say something because the trigger of the created flow is skipped since the lamp was already on according to Homey.

**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**What did you try to achieve?**
Trigger lamp turned on when powering on a Domitech light independent whether the lamp was on or off according to internal state of Homey

**What did you expect as result?**
Trigger gets triggered; which it only does if lamp is turned off by Homey previously

**What was the result?**
No trigger is fired 

**Any other remarks**
I verified that the Domitech app is firing the trigger and is receiving the initial message of the Domitech lamp on the Z-Wave network.

**Comment by WeeJeWel** [comment]
This is how the Apps SDK works. It is the responsibility of the app to keep the device's state in sync with Homey. That also means setting `onoff` to `false` when the light is turned off remotely.
