### ISSUE TITLE
com.osram.lightify.zigbee slow /no response

### ISSUE THREAD

**Issue by VincentWRX** [athombv/homey#1995]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: Android
* **Smartphone App Version**:

**If related to a Homey App:** Osram lightify zigbee beta app
* **Homey App Version**:  1.2.0
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
Lightify GU10 rgbw 

**What did you try to achieve?**

Connect and turn on the lightify bulbs. 

**What did you expect as result?**

Normal connection and quick respons on turning them on

**What was the result?**

The GU10 bulbs are connecting. But They're not all the time responding. Sometimes only 1 of the 3 turn on. Sometimes they won't turn off. did this by flow, smartphone app and by voice control. All the times they were responding slow or not.

**Any other remarks**

**Comment by caseda** [comment]
You have a typo in your product ID, needs to be accurate, even all capital letters should be capital

**Comment by VincentWRX** [comment]
Changed the Product ID of it to the naming it gets in Homey.

**Comment by RobinBol** [comment]
Thanks for reporting this issue, it was already mentioned here (https://github.com/athombv/homey/issues/1956), let's continue the discussion there.
