### ISSUE TITLE
ZWave network diagram picture too small in ZWave developer tools

### ISSUE THREAD

**Issue by bm480** [athombv/homey#1996]
I have a lot of ZWave devices but the labels for these devices as shown in the network diagram of the ZWave developer tools disappear along the edge of the diagram. Picture speaks for itself.

[
![knipsel](https://user-images.githubusercontent.com/23471238/33203443-4fd63594-d100-11e7-8f29-7efea1dfa075.PNG)
](url)

**Comment by WeeJeWel** [comment]
Look at the nodeId and the table below :) This can't be fixed because device names can be very long.
