### ISSUE TITLE
[Enhancement] Logic: Missing (standard) calculation functions

### ISSUE THREAD

**Issue by caseda** [athombv/homey#1997]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: null
* **Smartphone Platform**: android
* **Smartphone App Version**: null

**What did you try to achieve?**

Needed a random number between 0 and 4 for animation purposes. 
And wanted to calculate something with floor() to round the value down.

**What did you expect as result?**

That I could use the normal Javascript options
`random([min], [max])` to calculate a random number.
`floor(value)` to round the value down
`ceil(value)` to round the value up

**What was the result?**

There is no way by default in homey that I can create a random number.
And the round() function is in my situation not the best choice, cause I always need the lowest number when rounding it off.

**Any other remarks**
Round is implemented, why not floor, ceiling and random?
They are default Javascript calculation functions.

**Comment by WeeJeWel** [comment]
Added:

```
random()
math.random(max)
random(min,max)
```

`ceil()` and `floor()` should already work!
