### ISSUE TITLE
[com.lg.webos] missing author in app.json

### ISSUE THREAD

**Issue by bclevering** [athombv/homey#1998]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Install the app to my Homey

**What did you expect as result?**

The app being installed

**What was the result?**

Error stating that 'author' is missing in de app.json

**Comment by WeeJeWel** [comment]
Fixed!
