### ISSUE TITLE
Unzip the development kit

### ISSUE THREAD

**Issue by Omemanti** [athombv/homey#2]
Hey Emile,
Dont know if this is the right place, but when i unzip the development kit, I get 2 errors. One for  a json file and the other for a folder called "test"
 (dont know if it my own fault, just want to mention it.)
https://drive.google.com/file/d/0B_83T7CVQhQMYUlMeGZFN2w2UHM/view?usp=sharing

- brand new windows 8.1 install
- Folder is user/download (so nothing fancy)

**Comment by WeeJeWel** [comment]
Thanks for mentioning. It's a windows quirk. Also see https://github.com/joyent/node/issues/6960
