### ISSUE TITLE
Shuffle toggles in stead of set state

### ISSUE THREAD

**Issue by Alseenrodelap** [athombv/homey#2002]
* **Homey Version**:
1.5.5

**If related to a Homey App:**
* **Homey App Version**:
Spotify voor Spotify Connect versie 1.1.5

* **Affected Devices (preferably product codes)**:
Sonos Play and Play:5

**What did you try to achieve?**
In a flow, I want to play a playlist and set 'Shuffle' to yes. I expected shuffle to be set to yes and the first time it does that right, but when the flow is ran the next time, shuffle gets set to no. If the flow is ran again, shuffle gets set to yes again. So every second time the flow is ran, the playlist plays without shuffle.
Apparently the 'Set shuffle to yes' action doesn't really set it to yes but toggles it from yes to no or from no to yes. The same thing goes for the 'Set shuffle to no' action. It doesn't set a state but toggles.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
