### ISSUE TITLE
[com.samsung.ir] After installing this app homey gets offline

### ISSUE THREAD

**Issue by Brendvm** [athombv/homey#2003]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:  7709D0EE98
* **Smartphone Platform**: Android
* **Smartphone App Version**: 2.4.7 build 77

**If related to a Homey App:**
* **Homey App Version**: v1.0.3 - 31.07.17
* **Homey App Log Code**: Not available
* **Affected Devices (preferably product codes)**: Samsung UE46D8000 and Homey

**What did you try to achieve?**
I would like to use the Samsung TV IR app from the homey app store.
Installed it through the app store and trying to make flows wicht triggers my tv to do things (power on, power off, switch to HDMI 3, switch channels, etc ... )

**What did you expect as result?**
I know the version available is still a beta version. But several users are using this app with success.
I expect it to work at least for the basic stuff.

**What was the result?**
With this app installed my homey gets offline. Sometimes i have time to create a flow using this app and start testing. Some other time i installed it, add a device and it directly goes offline. 
When i get some time to do some tests the app works fine but eventually homey will get offline.

When homey is offline it still reacts to a ping (so it did not completely crashed).
Homey stays offline untill i pull the power plug.
When i deïnstall the app homey works perfectly again.

**Any other remarks**
To add a device i use the option to press the arrow up button on my remote control.
I do not have the original remote control anymore. It is a remote control from the brand "One for All".

**Comment by WeeJeWel** [comment]
Should be fixed by now!
