### ISSUE TITLE
The Tags menu in the flow editor does not update instantly 

### ISSUE THREAD

**Issue by kslinger** [athombv/homey#2004]
When I add a boolean in a flow I would expect it to be visible in the Tags menu right after I save the flow. This way I can use the boolean in a flow as a condition straight away.
Also it would be handy for test purposes if the values in the Tags menu would be updated upon opening the menu item.

**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**:

* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I tried saving the flow, switched between sections, reopen the desktop app and restart Homey.

**What did you expect as result?**

If I add a boolean to a flow and I save this flow, I would expect to see this boolean straight away in the tags menu. Also I would expect the values of the tags in the tags menu to be updated when I click the menu item.

**What was the result?**

Only if I restarted homey the tags menu would be updated.

**Any other remarks**

**Comment by WeeJeWel** [comment]
This should happen. Is the variable created already? Because the Flow must run at least once for the variable tag to appear.

**Comment by Inversion-NL** [comment]
I guess it would be more user friendly if the tag is created after saving the flow?
Else you might think you did something wrong because the tag is missing.

**Comment by WeeJeWel** [comment]
Maybe, but the tag name can be dynamic as well, so it's impossible to predict the variable's name.

**Comment by Inversion-NL** [comment]
If you create a flow using a tag, isn't the name then always fixed?

**Comment by kslinger** [comment]
WeeJeWel is right that the tag appears as soon as the flow run. When I save the flow the tag has a name, so I'm puzzled why this name cannot be used.
Still the values of the tags in the menu are not updated instantly.

**Comment by Dijker** [comment]
@kslinger 
The (existing) Tags auto update here, 
Did you test it? How? The Athom Homey Desktop app or a browser?

I opened and typed Time (Tijd)  waited till the next minute and:
![image](https://user-images.githubusercontent.com/12412734/33454265-9b3fe986-d618-11e7-8ce6-6e4a6acb492c.png)
it works here on latest Chrome browser.

**Comment by kslinger** [comment]
I tested thought the Homey Desktop app and tested specifically on the self created tags

**Comment by Dijker** [comment]
Can you test it on a Chrome browser and/or other variables that you can trigger to change.
Would be nice if we know if it  is only in the DesktopApp or maybe an specific HomeyApp.

**Comment by kslinger** [comment]
I'll do some testing this weekend. I didn't succeed logging in with the browser.

**Comment by kslinger** [comment]
I just tested but could not replicate the second part of my message. Tags where just updating fine.
