### ISSUE TITLE
433 issues

### ISSUE THREAD

**Issue by Rob-Houweling** [athombv/homey#2007]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: 05ADCBD96B
* **Smartphone Platform**:nvt
* **Smartphone App Version**:nvt

Alecto app v3.1.0
Elro app v2.4.0

**What did you try to achieve?**
433 apparaat aansturen, zowel deurbel als schakelaar

**What did you expect as result?**
Dat de deurbel gaat en de schakelaar schakelt.

**What was the result?**
Er gebeurt niets. Ook niet na reset van microcontroller of Honey zelf.

**Any other remarks**

**Comment by WeeJeWel** [comment]
Please provide some more information, what you are experiencing and what you have tried.

**Comment by Rob-Houweling** [comment]
I have a couple of flows that are triggered by my 433MHz doorbell but these have stopped working.
A flow that is triggered by the hue dimmer remote is not sending the 433MHz signal.
So sending and receiving of 433MHz seems to have stopped working after months of working perfectly.

I reset the 433 microcontroller in the stuff for geeks section and restarted Homey multiple times but it still doesn't work.

What else would you like to know?

**Comment by bvdbos** [comment]
Probably one of these two things:
* did you try to pull the plug on Homey and leave it unplugged for two minutes?
* maybe a device runs out of battery and starts flooding the 433 waveband with rubbish. Did you try putting in new batteries in your devices?

**Comment by Rob-Houweling** [comment]
No, I did not do a PTP. Will try today.
No, didn't change the batteries in the doorbell button. That is the only device sending 433 (besides Homey). Will try that today as well.
Thanks for the suggestions. Will report the results of above here.

**Comment by jeroenvollenbrock** [comment]
Closing to combine under #2023.
