### ISSUE TITLE
com.osram.lightify led strip

### ISSUE THREAD

**Issue by VincentWRX** [athombv/homey#2008]
**Metadata**

* **Homey Version**:1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: Android
* **Smartphone App Version**: 

**If related to a Homey App:**Osram Lightify Zigbee beta app
* **Homey App Version**: 1.5.3
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
The Lightify Flex RGBW 3p led strip is connecting as an unknow zigbee
Fabrikant ID OSRAM
Product ID LIGHTIFY Indoor Flex RGBW
Apparaat ID 528
Profiel ID 49246
So i can only switch it on or of and no colour changes.

**What did you try to achieve?**

**What did you expect as result?**

A device that i also could colour change.

**What was the result?**

unknown zigbee device.

**Any other remarks**

**Comment by RobinBol** [comment]
I updated the beta app to include the product id you provided, please try again and let me know if that solves your issue!

**Comment by VincentWRX** [comment]
Yes it's working now. Thank you!

**Comment by RobinBol** [comment]
Great, thanks!
