### ISSUE TITLE
Homey downloading voice never completes/Voice tab is empty/Apps don't install/System time incorrect

### ISSUE THREAD

**Issue by matthijsvdr** [athombv/homey#201]
I tried to do a reset on Homey because it did not respond anymore.
When resting the following happened:
- Honey's led ring would just burn green > nothing happens (browser said checking for updates)
- Or homey would blink orange (trying to boot) ->  nothing happens

Un plugging homey and plugging back in would result in going back how homey was before trying to reset.

Then decided to download the software and do a reset via my computer -> worked, homey got reset and i could follow a normal setup again.

Now:
- When starting homey i get the "I'm downloading my voice, you can still use homey in the mean time", but homey never finish its voice download. When going to the voice tab in settings its only showing "select a voice" but other wise just a white page
- When doing a reset now, homey can't do a count down from 10-1
- I can no longer install apps, always get the "Someting went wrong, please try again."
- System time is incorrect, its an hour behind (tried manual location and automatic, nothing changes). When the location to somewhere else in the world (korea) the system time still shows the same (also after reboot).
When using a flow with a time constraint it uses the time shown in settings

**Comment by ralfvd** [comment]
Regarding System Time, do you look at the 'show stuff for geeks', because that time is in "Z"-time (Zulu), which is GMT/UTC  ; At the end of the time, you'll see it marked "Z". 

If you e.g. live in the Netherlands, this Zulu-time is indeed one hour before your local time. 
The correct time for your timezone is calculated based on Zulu-time and your timezone, which is a couple of lines below the time in the 'show-stuff-for-geeks' section.

**Comment by matthijsvdr** [comment]
@ralfvd Sorry i missed the Z in the time :) still does not explain why homey uses that time to act, instead of the local time 
I created a flow: you say anything -> time is later then ... 17:00 (currently its 17:35) -> led ring should go solid blue

But its not going blue, when changing 17:00 to 16:00 it does

**Comment by matthijsvdr** [comment]
Ok something just happened (server side update?)

- Homey just started downloading its voice, and the voice tab now shows all the voices again.
- I can install apps again

But the time used by homey is still incorrect when asking for the time

**Comment by bvdbos** [comment]
the last part is #169 ...

**Comment by matthijsvdr** [comment]
In that case the issue could be closed, tho ill let it be closed by someone at Athom maybe they can explain this behaviour.

**Comment by matjaz** [comment]
I had the same issue. While downloading voice I couldn't install other apps. (app store returning 500). Some feedback would be welcome here!

As for time same issue here. date/time is correct (UTC), timezone is correct. But time flow reports one hour behind. Currently we're not in DST, but let's prepare for that.

Also time dependent triggers should be in local timezone.

**Comment by matjaz** [comment]
After a restart of Homey, time flow reports time correctly. It looks like system restart properly set timezone.

**Comment by matthijsvdr** [comment]
Homey, apparently needed a night to think about the time here, 19 hours later and it know uses the correct time
