### ISSUE TITLE
[nl.philips.ir] App now sends to many request to TV

### ISSUE THREAD

**Issue by Denn1992** [athombv/homey#2010]
After the last update the app is now sending 5 request to the TV.

If you want to put the TV on it registers:
On
Off
On
Off
On

When one request is not handeld correctly  the tv will turn it self off again :(

Can you please reduce it back to one because 5 times clicking on a button is not the option.

**Comment by BasKiers** [comment]
Hi, 

Sorry for the inconvenience, I've fixed reverted the repetitions back to 1 for now.

Regards,
Bas
