### ISSUE TITLE
Wireless weather sensors disconnect and disappear after a while

### ISSUE THREAD

**Issue by rhannink** [athombv/homey#2012]
I am using 2 temp/hum sensors Ventus W044 (Alecto v1 protocol) in combination with the wireless weather sensor app. 

Since I use 1.5.6RC3 I keep losing all my sensors after about a day or so.
Restarting the app does not solve this. Rebooting or PTP Homey does.

The app has not been updated for a while

App version V1.2.1
Homey firmware 1.5.6-RC3
![schermafbeelding 2017-12-01 om 18 38 34](https://user-images.githubusercontent.com/1661824/33495503-f9bdd8a2-d6c6-11e7-9286-5166f877e20f.png)

With kind regards,

Remco Hannink

**Comment by jeroenvollenbrock** [comment]
Closing to combine under #2023.
