### ISSUE TITLE
Thermosmart stops working

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#2018]
**Metadata**

* **Homey Version**: v1.5.5
* **Homey Log Code**: 
* **Smartphone Platform**:
* **Smartphone App Version**: 

**If related to a Homey App:**Thermosmart
* **Homey App Version**: v2.0.2
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**: Thermosmart

**What did you try to achieve?**

The connection to the ThermoSmart stops randomly
<img width="146" alt="schermafbeelding 2017-12-04 om 10 05 20" src="https://user-images.githubusercontent.com/10754229/33544614-c08685f4-d8db-11e7-9f70-367528e335c9.png">
After restarting the App, connection is restored.

**What did you expect as result?**

The App has worked flawlessly for months. It seems that these errors and connection problems have started after an App update.

**What was the result?**

**Any other remarks**

**Comment by camilleversteeg** [comment]
Same issue here.

**Comment by Eternity-again** [comment]
As a work around I have installed Candy App and made this flow, which restarts the Thermosmart App daily at noon: 
<img width="1112" alt="schermafbeelding 2017-12-05 om 10 10 45" src="https://user-images.githubusercontent.com/10754229/33598864-945046cc-d9a4-11e7-95a5-cfb951cb0283.png">

Hopefully a solution will be available soon.

**Comment by WeeJeWel** [comment]
Fixed in v2.0.3 that the warning disappears when the thermostat is reachable again.

It could be that the error persists, but then Thermosmart is simply offline.
