### ISSUE TITLE
Fibaro Binary sensor

### ISSUE THREAD

**Issue by Wimstradamus** [athombv/homey#202]
while including my Fibaro binary sensor Homey is interviewing 3 nodes and says 2nd en 3rd node fails.
After node 1 is added i removed this first node but now it is still in my devices but it "can't be reached" remove failed nodes gives a error and does not removes the device.
i see know it is similar as #167

**Comment by ocatie** [comment]
Fixed in 0.8.19.

Remove the device using the Remove Node button.

**Comment by Wimstradamus** [comment]
unable to remove the binary sensor with Remove Node button.
![schermafbeelding 2016-02-16 om 21 28 08](https://cloud.githubusercontent.com/assets/16623555/13090183/96a7689e-d4f4-11e5-96aa-a19f9835615e.png)

Factory reset the binary sensor, reboot Homey, Refresh Node button, Remove Failed Node button.
"an error occured, true" 
![schermafbeelding 2016-02-16 om 21 36 20](https://cloud.githubusercontent.com/assets/16623555/13090344/84f55074-d4f5-11e5-8fa2-a954900aab0b.png)

am i doing anything wrong?

**Comment by ocatie** [comment]
The driver probably crashed. Please report back at 0.8.19.

**Comment by Wimstradamus** [comment]
Now got 3 nodes with 0.8.20 but non general alarm reacts.

**Comment by ocatie** [comment]
3 devices in Homey is correct, the device presents itself as a multichannel device. You probably need to setup an association and/or configure a configuration parameter to let the device correctly report status.

If issues on the settings page persist please refer to #146

**Comment by Wimstradamus** [comment]
I did the parameters like the manual says (if understand It correctly) , but it does not respond at all. 

I associated  the first device (input1)  to group 1 and group 3.
Second device (input2) only to group 2
Third device no association, because it is not in use. 

Did you test a binary sensor with homey? If yes can you show how to associate?

**Comment by ocatie** [comment]
When making an association add homeys node id in the text field of the group that is reserved for the main controller.

I don't have an binary sensor at the office. I've tested with the Motion sensor, door/window sensor, Dimmer 2 and other sensors. I all got them working.

**Comment by Wimstradamus** [comment]
Did that, added  1 (homey)  in the text field, but it doesn't work when inputs are triggerd. 
Door/window sensor is working correct with me also.
