### ISSUE TITLE
Adding zigbee device opens zwave adding screen in Homey preview app

### ISSUE THREAD

**Issue by AllG123** [athombv/homey#2022]
* **Homey Version**:1.5.5
* **Homey Log Code**:
* **Smartphone Platform**: Android 8.0
* **Smartphone App Version**: 0.7.1.109

**What did you try to achieve?**
Add Zigbee device with the preview app, Philips Hue app , Xiaomi mii zigbee app.

**What did you expect as result?**
After selecting the device you want to add, the add a zigbee device screen opens up.
(same as in the web interface)

**What was the result?**
instead of add a zigbee device, you get an add zwave device screen.

**Any other remarks**

**Comment by TedTolboom** [comment]
@joachimroeleveld still present in latest App release version 1.0 (100) on DP 1.5.6-RC4...

Although https://developer.athom.com/tools/pair shows the Zigbee inclusion information:
![image](https://user-images.githubusercontent.com/17163431/33684141-880afa04-dacd-11e7-901b-5439292b9d24.png)
The mobile app indeed shows (an empty) "Add a Z-wave device" screen..

**Comment by joachimroeleveld** [comment]
@WeeJeWel
