### ISSUE TITLE
[AppV2 iOS] Changing device settings makes the app to crash

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/homey#2030]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: iOS 
* **Smartphone App Version**: 1.0

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I tried to change the configuration settings of a Neo coolcam motion sensor.

**What did you expect as result?**

That I can change settings, in this case lux threshold of a Neo motion sensor.

**What was the result?**

When I select a device and go to the configuration settings of this device, I choose a specific setting to change. When I change the setting (lux threshold) the app crashes.

**Any other remarks**

**Comment by joachimroeleveld** [comment]
This has been fixed in the latest release. Please let me know if you still encounter issues.
