### ISSUE TITLE
[App V2, iOS] Paper Trails window only partially visible

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2032]
iOS app V2 (101 - and previous versions) on iPhone SE
The lowermost part of the window is not visible in the app - when trying to scroll, the screen is blank:

![2017-12-07 12 11 20](https://user-images.githubusercontent.com/29979509/33758295-f352f902-dbfd-11e7-87bf-5af0c0c0abc9.png)

![2017-12-07 12 11 09](https://user-images.githubusercontent.com/29979509/33758301-f6394fa4-dbfd-11e7-8060-deb39e8febb5.png)

**Comment by jeroenvollenbrock** [comment]
This is an app-specific issue, i've created https://github.com/Dijker/nu.dijker.PaperTrails/issues/16 for you.
