### ISSUE TITLE
[ Homey app V2 ] Else / Then cards not functioning propperly 

### ISSUE THREAD

**Issue by enbach** [athombv/homey#2033]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: iOS 11.2
* **Smartphone App Version**: Homey App V2 Beta 1.0

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I tried to test a flow in the mobile app, it did the test but the else / then cards are both executed, as you can see in the screenshots below, both cards get the status passed.

![img-2870](https://user-images.githubusercontent.com/34342230/33758363-3d52274e-dbfe-11e7-9e25-4effed517383.JPG)
![img-2871](https://user-images.githubusercontent.com/34342230/33758370-427a1e5c-dbfe-11e7-8657-d7f6b6122857.JPG)

**What did you expect as result?**

That either one of them both would be executed as like the desktop app

<img width="1277" alt="schermafbeelding 2017-12-07 om 18 35 28" src="https://user-images.githubusercontent.com/34342230/33758381-5002e72a-dbfe-11e7-9216-c3955eb993ea.png">

**What was the result?**

Instead of one of the cards being executed both got executed ( and thus the variable is not being set correctly )

**Any other remarks**

**Comment by joachimroeleveld** [comment]
This should have been fixed in the latest version. Please reopen if you still encounter issues.
