### ISSUE TITLE
Flow not triggered

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2034]
* **Homey Version**: 1.5.5
* **Homey Log Code**: 7C537098B1

**What did you try to achieve?**
Flow 1: "Then"-column includes flowcard "Start this flow"
Flow 2: "If"-column includes flowcard "This flow is started"

Previously working without problems, other flows can trigger each other, now "Flow 2" is not triggered as supposed to. Name of flow is correct (chosen from the list), have tried removing the flowcard, saving the flow, and adding the card again, same result.
Testing "Flow 1" by "Test" in desktop app leads to triggering the flow - error only present when it should run unattended.

**What did you expect as result?**
That the flow was triggered as usually.

**What was the result?**
Nothing happens.

**Any other remarks**
~~Testing the flow now results in some sort of self-oscillation - will make another issue.~~
Edit: Found error in "Flow 2" leading to a feedback loop - this is solved.
Main problem still persists.

**Comment by WeeJeWel** [comment]
I cannot reproduce. Does the 2nd Flow have 'This Flow is started' as trigger?

**Comment by cbho** [comment]
Yes:

1st flow:
![image](https://user-images.githubusercontent.com/29979509/33769674-5eb34dc8-dc2b-11e7-84a1-d2bc31fd1428.png)

2nd flow:
![image](https://user-images.githubusercontent.com/29979509/33769647-47d2ec1c-dc2b-11e7-8c27-cfde696420e6.png)

**Comment by WeeJeWel** [comment]
If testing works, then the first Flow is simply not triggered. It does not seem to be a Homey issue.

**Comment by cbho** [comment]
I have a Paper Trails flow card in the 1st flow adding to the log when the flow is triggered (in the "Then"-column, just above the "Start this flow") - and that remark is shown in the log.
I think that will not be possible, unless the flow is actually triggered?

**Comment by Dijker** [comment]
can you show both flows complete?

**Comment by cbho** [comment]
@Dijker: The problem disappeared and I cannot not find anything to explain why - so I'll keep the issue closed and return if it reappears :-)
