### ISSUE TITLE
[App V2 (101)] No info about which flow is triggered - feature request / error?

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2035]
App V2 (101), iOS 11.1.2

When editing an existing flow in the app, opening a "Start this flow"-card in the "Then" section does not include information about which flow it points to.
Would be somewhat more useful, if it is possible to see which flow is supposed to be triggered :-)

**Comment by joachimroeleveld** [comment]
This has been fixed in the latest release (1.1 - 103, which has just been rolled out). Feel free to reopen if you still encounter issues.
