### ISSUE TITLE
[App V2, iOS] "0" shown as "-" in device settings

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2036]
* **Homey Version**: 1.5.5
* **Smartphone Platform**: iOS 11.1.2
* **Smartphone App Version**: V2 (101 and previous versions)

**What did you try to achieve?**
In settings (in example below the "Motion detection command" in a Fibaro Motion Sensor, but the same is seen in e.g. NEO Coolcam Motion sensor) the value "0" is shown as "-".

**What did you expect as result?**
Suggest the correct value is shown - using "-" is ambiguous in terms of the value is missing or zero.

**What was the result?**
Changing the value to "0" doesn't change the value shown afterwards.

![2017-12-08 10 34 42](https://user-images.githubusercontent.com/29979509/33759948-691e2d90-dc04-11e7-9bd6-b7559e236bbe.png)

**Comment by joachimroeleveld** [comment]
This has been fixed in the latest release (1.1 - 104, which is being rolled out). Feel free to reopen if you still encounter issues.
