### ISSUE TITLE
[App V2 (101)] Setting "False" shown as "Yes"

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2037]
* **Homey Version**: 1.5.5
* **Smartphone Platform**: iOS 11.1.2
* **Smartphone App Version**: V2 (101 and previous versions)

**What did you try to achieve?**
In settings a value (in this example "LED indicating tamper alarm" for a Fibaro Motion Sensor, but same is seen for other devices) is shown as "Yes", although the setting is in fact "False".

![2017-12-08 10 35 19](https://user-images.githubusercontent.com/29979509/33760174-1b52e1ea-dc05-11e7-8d26-03a1d925efd7.png)

![2017-12-08 10 35 30](https://user-images.githubusercontent.com/29979509/33760185-1ef23c56-dc05-11e7-8bc5-cbabb00c5373.png)

**What did you expect as result?**
That the actual value is shown ("False" as "No", "True" as "Yes")

**Comment by joachimroeleveld** [comment]
This has been fixed in the latest release (1.1 - 104, which is being rolled out). Feel free to reopen if you still encounter issues.
