### ISSUE TITLE
[ Homey app V2 ] Virtuale devices - mode / modus button not showing the correct state when toggled.

### ISSUE THREAD

**Issue by enbach** [athombv/homey#2039]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: iOS
* **Smartphone App Version**: Homey APP v2 Beta 1.0

**If related to a Homey App:**
* **Homey App Version**: 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Switching the sate of the predefined modus ( through the virtual devices app ) in the homey beta app. ( this functions in the non beta homey app )

The same problem seems to appear with my via the smartwares added flamingo sf-501 ( it even has two on/off switches, the first one works properly but the second one seems to have the same problem as mentioned above.

![0db242d3-9879-4cac-bf24-0ebf98390397](https://user-images.githubusercontent.com/34342230/33766489-f48579ec-dc1d-11e7-9207-8cfac3df1da9.png)

**What did you expect as result?**

The  " turned on / off " switch showing the correct value when toggled.

**What was the result?**

The modus status was changed but the icon didn't ( flipped back to previous shown state for example; when it was on and you want to switch it to off it does actually change but the icon reverts back to the on state.  ).

When you return to the main list with devices etc, and go back to the modus switch the state icon is correctly shown as set in the previous step.

**Any other remarks**

**Comment by joachimroeleveld** [comment]
Closing in favour of #2092
