### ISSUE TITLE
[Homey App V2] Time error in new Alarm

### ISSUE THREAD

**Issue by nieuwton** [athombv/homey#2043]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: 
* **Smartphone Platform**: Android
* **Smartphone App Version**: v0.8.3.113

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

In the smartphone app I created a new Alarm, entered a new time and tried to save the new created Alarm.

**What did you expect as result?**

I expected the Alarm to save.

**What was the result?**

An error message: "The alarm could not be saved (Expected time to be a string)".

**Any other remarks**

**Comment by joachimroeleveld** [comment]
This has been fixed in the latest release (0.8.4, which has just been rolled out). Feel free to reopen if you still encounter issues.
