### ISSUE TITLE
Condition-card has wrong value when flow is triggered with same onoff-device

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/homey#2045]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: 8CE5C43630
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.3.3 Build 70
(also via desktop app on MacOS)

**If related to a Homey App:** Virtual Devices
* **Homey App Version**: 0.6.6
* **Homey App Log Code**: ???
* **Affected Devices (preferably product codes)**:
virtual_switch with name 'test-device' and id '9744945f-37c2-9065-97f4-4648c097871b'

**What did you try to achieve?**
- I have a virtual switch from the Virtual Devices app with capability 'onoff'
- I have a flow where the virtual switch is used as trigger when it is changed
- In the same flow I use the virtual switch as condition to check if the switch is 'on'
- As action, I turn on a real light and in the else part, I turn it off. 
- Then when I turn **on** the switch, the light is turned **off** and viceversa

**What did you expect as result?**
When I turn **on** the switch, the light is turned **on** and viceversa

**What was the result?**
I think the Condition is checked before the actual value is updated. When the flow is triggered with a different device, the condition is functioning OK.

I did not check if different capabilities have similar issues

**Any other remarks**
This issue is reported by a few users of Virtual Devices, a.o.:
> Volgens mij zit er een ernstige bug in de beta versie van de app (v0.66). Wanneer je een flow maakt die reageert op een ingedrukt/veranderd trigger van een aan/uit knop en een 'is aan' card in de when dan is het resultaat true wanneer hij false moet zijn en andersom 

Since the Condition-card is the default one coming with the 'onoff'-capability, I forwarded this issue here. I also did not add special code for setting the state.

Here is the code where only code is implemented for the 'changed' device:
https://github.com/ArjanKranenburg/virtual-devices/blob/sdk2/drivers/virtual_switch/device.js

**Comment by WeeJeWel** [comment]
Do I understand correctly you have a Flow like this?

![screen shot 2017-12-13 at 12 27 59](https://user-images.githubusercontent.com/319873/33936804-1a4fe1d0-e001-11e7-841b-6804a7ef9fd0.png)

Because when I test this by turning the device ON, Homeys says 'Yep', which seems correct to me.

**Comment by ArjanKranenburg** [comment]
Almost. The trigger is a 'changed'-trigger, defined by:
      {
        "id": "press",
        "title": {
          "en": "Pressed / changed",
          "nl": "Ingedrukt / veranderd"
        },
        "args": [
          {
            "name": "device",
            "type": "device",
            "filter": "driver_id=virtual_switch"
          }
        ]
      },

and in the device.js handled by:

  onInit() {
    let triggerDevice = new Homey.FlowCardTriggerDevice('press');
    triggerDevice.register();

    // When capability is changed
    this.registerMultipleCapabilityListener(this.getCapabilities(), (valueObj, optsObj) => {
      this.log(this.getName() + ' -> Capability changed: ' + JSON.stringify(valueObj));

      triggerDevice.trigger( this, {}, valueObj ) // Fire and forget
        .catch( this.error )

      return Promise.resolve();
    }, 500);
  }

I can see that the flow is triggered, but it seems that then the value is not yet updated, at least not in the valueObj. Or should I use it differently?

**Comment by WeeJeWel** [comment]
Right. After you return the promise of the capability listener, the app sends the new capability value to Homey. So your Flow is triggered before the capability is actually updated (Homey waits for a confirmation before the state is changed).

What you can do is very simple. For every `number` capability, Homey fires a Flow event `capabilityid_changed`, e.g. `measure_something_changed`.

If you create a Flow trigger with that as ID in your `app.json`, you don't have to trigger the Flow yourself. 

As a solution for now, you can trigger the Flow in a `process.nextTick`. This makes it fire after the capability set confirmation.
