### ISSUE TITLE
Firmware 1.5.5: state is not saved in Homey Reboot

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/homey#2046]
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** VIrtual Devices
* **Homey App Version**: 0.6.6
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Reboot Homey

**What did you expect as result?**
State of an Virtual Device (alarm) saved

**What was the result?**
State was not saved

**Any other remarks**
See issue on Virtual Devices:
https://github.com/ArjanKranenburg/virtual-devices/issues/30

These users are using Homey Firmware 1.5.5., but this works fine on 1.5.3.

**Comment by StraDijk** [comment]
Looks like the state is saved again after 1.5.6 rc6 update
