### ISSUE TITLE
Voice recognition unexpectedly activated

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2047]
* **Homey Version**:  1.5.5

Not sure if this is a bug - but I would really like to know...
Just this evening, Homey suddenly asked what I meant - as it didn't understand what I asked it to do.

However:
I'm certain I have NOT enabled the microphone in Homey to enable voice recognition.
I cannot promise I have not made a mistake somewhere - as there are no guarantees in the world.

However, by principle, I do not use voice recognition in my devices - and I know for sure, that I have specifically checked that it was not enabled - just as I take care of doing this on my phone, in my car etc.

It can be my error - and I have no problem with that - but I would really, really like to know, that it is checked, that there is not a setting somewhere in the updates from Athom that by accident enables the microphone per default - without notice...
The desktop app was updated recently - could the setting have been changed during that?

Regards,
Chr.

**Comment by jeroenvollenbrock** [comment]
There was a bug that got introduced in 1.5.5 (experimental) that could cause settings corruption. Homey resolves this by reverting to factory defaults for the corrupted settings. The bug has been resolved in 1.5.6 (experimental)
