### ISSUE TITLE
Homey Apps - add link to Homey Community forum topic (to the app manifest and Homey apps)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#2049]
Please add a link to the Homey Community forum topic of the corresponding app to the app store and app manifest. 

Ie. similar implementation as the donation object...

**Comment by ArjanKranenburg** [comment]
While at it, also add a link to github-pages. Or should I create a separate request for that?

**Comment by bvdbos** [comment]
![2018-01-02 21_12_22-klikaanklikuit _ homey apps](https://user-images.githubusercontent.com/1064079/34498385-b76d8868-f001-11e7-878b-33fceafa7b42.png)
?

**Comment by WeeJeWel** [comment]
This has been implemented some time ago. Use the `athomForumDiscussionId` property.
