### ISSUE TITLE
[Homey App V2] [Feature Request] - View Homey Log

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2050]
Although currently not available in the Desktop App either, it would be nice if you could view Homey's log file.

Currently, when something doesn't work, I just reboot Homey without actually knowing what the problem is and it would therefore be useful if we could actually view the log to see what the problem may be.

**Comment by bvdbos** [comment]
There is no "Homey's logfile", see #1185 and #1847...

**Comment by WeeJeWel** [comment]
There is indeed no 'log' (if there would be, it would be huge).

We are planning on a sort of 'Timeline' feature though, which might help debugging.
