### ISSUE TITLE
Can we get `preventTag` to hide capabilities from the Tags-menu?

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#2053]
**Metadata**

* **Homey Version**: 1.5.6 rc6
* **Homey Log Code**: Does not apply
* **Smartphone Platform**: Does not apply
* **Smartphone App Version**: Does not apply

**If related to a Homey App:**
* **Homey App Version**: Does not apply
* **Homey App Log Code**:Does not apply
* **Affected Devices (preferably product codes)**: Does not apply

**What did you try to achieve?**

We can hide capabilities from Insights by using `"preventInsights": true`.
Would be great if we could use `"preventTag": true` to hide capabilities from the Tags-menu in a similar way.

Example: tado-app: `const capabilitiesOptionsMap = {...}` in `driver.js`

**Comment by WeeJeWel** [comment]
Fixed
