### ISSUE TITLE
AppV2: Start a flow action is wrong

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#2057]
**Metadata**

* **Homey Version**: 1.5.6 RC6
* **Homey Log Code**: NA
* **Smartphone Platform**: Android 8.0
* **Smartphone App Version**: 0.8.3.113

**What did you try to achieve?**
Edit a flow with an action to start another flow

**What did you expect as result?**
The right description

**What was the result?**
Wrong description on the start a flow action card on the smartphone app

**Any other remarks**
Smartphone app
![screenshot_20171211-230158](https://user-images.githubusercontent.com/15921016/33856651-1227da96-dec9-11e7-8ccf-7c325975f015.png)

Web browser
![screenshot_20171211-230416](https://user-images.githubusercontent.com/15921016/33856659-1860fde8-dec9-11e7-96b8-bd8ef852cd6b.png)

**Comment by bvdbos** [comment]
#2035 ?

**Comment by Inversion-NL** [comment]
Oeps
