### ISSUE TITLE
AppV2: Homey firmware version wrong

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#2058]
**Metadata**

* **Homey Version**: 1.5.6 RC6
* **Homey Log Code**: na
* **Smartphone Platform**: Android 8.0
* **Smartphone App Version**: 0.8.3.113

**What did you try to achieve?**

See Homey version in the smartphone app

**What did you expect as result?**
Correct Homey version

**What was the result?**
Wrong Homey version ( probably latest stable version of Homey?)

**Any other remarks**
![screenshot_20171211-232009](https://user-images.githubusercontent.com/15921016/33856941-0fdec99c-deca-11e7-8494-d07cf40a5544.png)

![screenshot_20171211-232228](https://user-images.githubusercontent.com/15921016/33857011-4a5f2d3c-deca-11e7-9936-bca277943cba.png)

**Comment by joachimroeleveld** [comment]
Homey's version has been removed from the sidebar in the latest release. Please refer to settings to view Homey's version.

**Comment by Inversion-NL** [comment]
Ok
