### ISSUE TITLE
[App V2] - HomeKit App Settings are blank or don’t allow scrolling

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2060]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: N/A
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.1.104

**If related to a Homey App:**
* **Homey App Version**: HomeKit 1.2.4
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Open The HomeKit Settings

**What did you expect as result?**
Settings shown as expected as is on the Desktop version

**What was the result?**
When you open the settings, it flashes as if there were devices, and then it all turns blank.
Initial Flash:
![33810445-e5166154-de04-11e7-95fe-f086b82f39ae](https://user-images.githubusercontent.com/10297361/33902548-a033ee5e-df75-11e7-8159-442f679c5417.jpeg)

Blank Devices:
![33810452-f27d9498-de04-11e7-9ca6-48a245104019](https://user-images.githubusercontent.com/10297361/33902549-a069bb6a-df75-11e7-91f4-fc550e31c0a8.jpeg)

Blank Log:
![33810453-f29bcfb2-de04-11e7-9b69-9eb0d05ec579](https://user-images.githubusercontent.com/10297361/33902550-a09b9cac-df75-11e7-816a-b88c4a86ead6.jpeg)

However, while writing this issue, I see that the app had updated to 1.1.104. Now, after this update It now shows the devices and log, BUT:
1. The devices doesn’t let you scroll, so I can only see the first 3/4 devices.
2. The log is sort of “zoomed in” and not really readable.

Can't scroll down, although there are about 20 more devices.
![33902719-3378c126-df76-11e7-90d7-7a335bc75e9c](https://user-images.githubusercontent.com/10297361/33902750-519431e0-df76-11e7-98c4-57527be5479b.jpeg)

Log is way too big and not in proportion, also doesn’t allow scrolling. Up, down, left or right...
![33902720-33adcd4e-df76-11e7-83ad-63cbae808080](https://user-images.githubusercontent.com/10297361/33902751-51cc2212-df76-11e7-80cf-c5502d7708c4.jpeg)

**Comment by joachimroeleveld** [comment]
Closing in favour of #2070
