### ISSUE TITLE
[com.sonos] Unable to select a specific Sonos speaker

### ISSUE THREAD

**Issue by JohanBendz** [athombv/homey#2061]
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: 
* **Smartphone Platform**: IOS
* **Smartphone App Version**: 1.3.3 Build 70

**If related to a Homey App:** https://apps.athom.com/app/com.sonos
* **Homey App Version**:  v2.3.0 - 21.04.17 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Sonos Play:5 and Sonos Connect AMP

**What did you try to achieve?**

I have tried using Homey Music and flows with the same result.

**What did you expect as result?**

I expect the music to be played in the Sonos speaker of my choice,

**What was the result?**

The music is played from the last added Sonos speaker.

**Any other remarks**
Changing speaker in Homey Music stops the currently played music in a flow.

**Comment by ferrydl** [comment]
I have the exact problem. @jeroenvollenbrock , can you give us an eta when we can expect the fix?

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
