### ISSUE TITLE
[App v2] Device (& Capability?) icons do not update when changed after an app update.

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#2062]
**Metadata**

* **Homey Version**: 1.5.6 rc6 and before
* **Homey Log Code**: Does not apply
* **Smartphone Platform**: Android 5.0
* **Smartphone App Version**: v0.8.4.114

**If related to a Homey App:**
* **Homey App Version**: Does not apply
* **Homey App Log Code**: Does not apply
* **Affected Devices (preferably product codes)**: Does not apply

**What did you try to achieve?**

Update some icons (the svg-files, not the code) in an app I develop (tado)

**What did you expect as result?**

To see the updated icons for devices and capabilities

**What was the result?**

The previous version of the device icons was still visible in the Mobile app. This does not change after closing and restarting the mobile app. Did not change after removing and re-adding the device either.

UPDATE: When I open the device, the icon on top of the page is the updated one... Only the one in the device list is still the old one. 😁 

I noticed the same for some capability icons about two weeks ago. Meanwhile those icons have been updated in my phone display, but meanwhile I also re-added the devices. Can not check if they still have the 'wont update' problem now.

**Any other remarks**

The icons DO update in the 'old' mobile app/desktop app without having to re-add a device. Only when some related code changes also, they may need a re-add.

**Comment by joachimroeleveld** [comment]
This is indeed something that has not been implemented yet. Images are until now cached indefinitely.

**Comment by Jamie-Peake** [comment]
This is still occurring in Homey (v2) 1.1

App is showing the device icon from when the app was being developed, has not been updated after re-installing, adding new device. 

Oddly, the Homey (v1) is showing the correct device Icon, however I simply may not have opened the v1 app during application testing.

**Comment by WeeJeWel** [comment]
This is fixed in the final release of the new smartphone app, that'll rollout shortly.
