### ISSUE TITLE
[App v2] Toggle function for device icon on top of capability page does not work

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#2063]
**Metadata**

* **Homey Version**: 1.5.6 rc6 and before
* **Homey Log Code**: Does not apply
* **Smartphone Platform**: Android 5.0
* **Smartphone App Version**:  v0.8.4.114

**If related to a Homey App:**
* **Homey App Version**: Does not apply
* **Homey App Log Code**: Does not apply
* **Affected Devices (preferably product codes)**: Does not apply

**What did you try to achieve?**

Switch a tado heating zone to `Smart schedule` by tapping the device icon

**What did you expect as result?**

The heating zone to be set to `Smart schedule`

**What was the result?**

The mobile app stared at me like it didn't understand what it should do.

**Any other remarks**
The 'old' mobile app and desktop app know what to do when I tap the device icon in a mobile card.

**Comment by joachimroeleveld** [comment]
The new app does not have the option to toggle a device by tapping its icon. Some capabilities do have a toggle next to its title as a quick action. I will add an on/off toggle for the heater device class.

**Comment by OpenMindNL** [comment]
OK, I'll keep it in mind for when app v2 gets stable :)
