### ISSUE TITLE
[com.irobot.roomba980] App keeps crashing on Homey and needs to be restarted once every day.

### ISSUE THREAD

**Issue by wthans** [athombv/homey#2064]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
? please fill in the info asked for... not just a title..

**Comment by jeroenvollenbrock** [comment]
Please open a new issue and follow the contributing guidelines.
