### ISSUE TITLE
[com.aeotec] ZW139 support

### ISSUE THREAD

**Issue by pohomey** [athombv/homey#2069]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
Aeotek 1.6.0
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
ZW139 nano switch (single switch without power meter)
Manufacturer ID 134 
ProductType ID 3 
Product ID 139

**What did you try to achieve?**

Including the ZW139 nano switch (single switch without power meter). 

**What did you expect as result?**

To be able to include the device without errors.

**What was the result?**

Get a invalid_commandClass_COMMAND_CLASS_METER.
Can't use it at all, not from a flow and not directly from the device in the desktop app. 

**Any other remarks**

**Comment by RobinBol** [comment]
This should currently be resolved, there was a driver with wrong device ids which caused this issue. Please update the Aeotec app to the latest version to confirm. Will close this issue for now, please let us know if it was not resolved for you.
