### ISSUE TITLE
user route is not authorized

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#207]
I can access user's data if I know his id, without credentials. https://api.athom.com/user/{id}/profile

**Comment by joachimroeleveld** [comment]
Yes, this is by design. This route is used to show public user information on pages such as the app store. No sensitive information is shown. While thinking about it though, the email address maybe shouldn't be accessible through this endpoint. I will remove this field.

**Comment by joachimroeleveld** [comment]
Fixed. Thanks for reporting!
