### ISSUE TITLE
[nl.klikaanklikuit] ACM-3500-3 not supported

### ISSUE THREAD

**Issue by jduinen** [athombv/homey#2071]
**Metadata**

* **Homey Version: 1.5.3**:
* **Homey Log Code**:
* **Smartphone Platform: android **:
* **Smartphone App Version: 2.4.7 Build 77**:

**What did you try to achieve?**
I wanted to add a klikaanklikuit device ACM-3500-3 towards the homey but it is not in the list

**What did you expect as result?**
Device visible in the klikaanklikuit device list.

**What was the result?**
Device was not in the list of klikaanklikuit

**Any other remarks**
Fix as soon as possible.

**Comment by jduinen** [comment]
I hope this can be fixed very fast.

**Comment by Dijker** [comment]
Add it 3 times as a ACD-1000 or other normal KAKU switch. that should work as stated in the forum.

**Comment by KyleAthom** [comment]
Please see https://github.com/athombv/homey/issues/2718
