### ISSUE TITLE
All Z-Wave devices missing after each reboot

### ISSUE THREAD

**Issue by nimsim** [athombv/homey#2073]
**Metadata**

* **Homey Version**: 1.5.6 RC6, most likely unrelated as this issue came while on 1.5.3
* **Homey Log Code**:A852971A25
* **Smartphone Platform**: Android, iOS
* **Smartphone App Version**: Latest Preview on Android, 1.3.3 on iOS

**If related to a Homey App:** Not sure, I only have Fibaro devices on Z-wave at the moment
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Fibaro Motion Sensor, Window/Door sensor 2, Roller Shutter 2, Wall plug

**What did you try to achieve?**

Use any Fibaro Z-Wave Device

**What did you expect as result?**

Z-wave working as intended, i.e lights turning on

**What was the result?**

No Z-wave devices available, no flows working on Z-wave devices. 
Checked the Z-wave settings in Homey and saw "Z-wave busy, try to reboot". Tried taking the power manually to no avail.
Saw a guide where you disable Z-wave apps, reboot, and then turn on apps one by one (I have installed Aeotec app as well). Tried this 4-5 times and it didn't help.

Finally I opted to download experimental firmware, and after installation I couldn't see my devices still, but I could remove them.
Started removing them one by one, and re-adding them. Finished first floor and though to myself, maybe I should reboot to see if they stay?

Can't see my Z-wave devices again. 

**Any other remarks**
Yes. I'm annoyed, The tape on the damn Fibaro Door-sensors are a bitch to get off.

**Comment by epjjansen** [comment]
Z-wave network is failing after a day or so. Had to reboot Homey to reset de Z-wave network

**Comment by nimsim** [comment]
Homey gets stuck at booting now.

**Comment by mruiter** [comment]
Guess youre Homey has become corrupt.
Well at least its settings. You should contact support@athom.com for help
