### ISSUE TITLE
Homey only remotely offline, but has a working internet connection

### ISSUE THREAD

**Issue by rogierhofboer** [athombv/homey#2076]
*Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: B0C9C81E79
* **Smartphone Platform**: Android
* **Smartphone App Version**: 2.4.7 - Build 77

**What did you try to achieve?**
I was looking to see if I could get some logging out of the homey. 
So pressed the Upload log button in the (not-supported, I know) web interface, using Chrome.
It didn't output log, just sent it to Athom and gave a code (I did not note down). But that's not the point.

A short while after that the Homey went off-line. It was not remotely reachable anymore.
A few hours later when I arrived home, the homey was still working, on-line in my local network, usable via the App and it also was able to respond to voice commands and tell me the current weather.
But remotely (turned my Wifi off on the smartphone) it was still offline.

**What did you expect as result?**
Homey staying remotely online all the time.

**What was the result?**
It stayed offline (but had an internet connection, only not remotely accessible.)

**Any other remarks**
After a restart (via the Desktop app) it was also remotely online again :)

**Comment by bvdbos** [comment]
See also #1944

**Comment by rogierhofboer** [comment]
@bvdbos I think it is not the same issue. 
My Homey was fully responsive, it did run flows, speech worked, asking for the weather worked. 
Locally reachable. Only remotely not reachable (so via Wifi it worked, turning Wifi off on 4G it was said to be offline, but it had internet connection because the speech recognition worked)

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
