### ISSUE TITLE
After a couple Hours  Ikea Zigbee devices Broken

### ISSUE THREAD

**Issue by CliffBroeren** [athombv/homey#2077]
**Metadata**

* **Homey Version**:         Since Homey 1.5.6-rc.6  With 1.5.5 No problems
* **Homey Log Code**:     9627CC399E
* **Smartphone Platform**: 
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

 all the zigbee ikea lights Can no longer be operated on / off

**What did you expect as result?**

switch the lights on/off

**What was the result?**

Nothing the lights they were on stays on and the lights where off  stays off 

**Any other remarks**
Strange Mesh Network 
<img width="813" alt="schermafbeelding 2017-12-16 om 13 18 47" src="https://user-images.githubusercontent.com/28061478/34070333-ed330658-e264-11e7-8cc0-be5c58191bc3.png">

When i restart homey this ^ Looks normal  again

**Comment by bvdbos** [comment]
Then you might close this one...
