### ISSUE TITLE
Feature request Netatmo battery status

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2079]
Would it be possible to add the battery status of wireless devices like the rainmeter as well as the windmeter as well as the separated temp/humidity meter.

**Comment by Dijker** [comment]
Already implemented since 20 jun, 
https://github.com/athombv/com.netatmo/commit/4335d0c8107279e40b83b285a66baf5b571af8dc

2.0.6: (re-pair is needed for the extra capabilities)
- Added battery levels

**Comment by chrisboer** [comment]
Ok thanks
