### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#208]
Limiting access to device should be as strict as possible.
Having `*` is quite dangeroues, especialy similar to #207 

I recommend replacing `*` with stricter hostname (whitelist of Origin request header).

**Comment by WeeJeWel** [comment]
On Homey or the API?

**Comment by matjaz** [comment]
Both.

I know some services requires CORS. But `*` is too open.

With WebRTC I could get your LAN IP and scan subnet IPs for known (vulnerable) endpoints..

**Comment by joachimroeleveld** [comment]
api.athom.com is a public API and will be used by more parties in the future. Therefore allowing CORS from all domains is no vulnerability and is a common practice.

**Comment by joachimroeleveld** [comment]
I think this issue can be closed. Please reopen it if you have additional remarks.
