### ISSUE TITLE
TRANSMIT_COMPLETE_ACK_UNKNOWN over time for previously working zwave device

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#2083]
* **Homey Version**: 1.5.6-rc7
* **Homey Log Code**: DCBD4FD503

**If related to a Homey App:**
* **Homey App Version**: Greenwave Systems 1.1.2
* **Affected Devices (preferably product codes)**:  Greenwave Powernode 6 ("manufacturerId": 153, "productTypeId": 3,	"productId": 4)

**What did you try to achieve?**
My Greenwave Powernode 6 has been operating perfectly for over a year now but since firmware 1.5.6 I'm experiencing "TRANSMIT_COMPLETE_ACK_UNKNOWN" errors when Homey is running for some hours. A reboot fixes the it but the issues returns again after a couple of hours requiring another reboot. The PowerNode is not close to Homey but is part of the Zwave mesh with some other nodes nearby. Here is some extra information.
![network](https://user-images.githubusercontent.com/4710062/34080422-eee88700-e33d-11e7-862f-3d6c23500670.png)

`
2017-12-17T13:28:12.699Z
Command[3269] start: sendData
2017-12-17T13:28:12.699Z
ProcessSendData[3269]: To node: 39 with data: 0x600d2702320110 and txOptions: AUTO_ROUTE
22017-12-17T13:28:12.862Z
Node[39]: [COMMAND_CLASS_MULTI_CHANNEL] [MULTI_CHANNEL_CMD_ENCAP] {"type":"Buffer","data":[39,6,50,1,16]}
2017-12-17T13:28:12.862Z
Node[39]: sendData to COMMAND_CLASS_MULTI_CHANNEL, params 0x0d2706320110
2017-12-17T13:28:13.218Z
ProcessSendData[3269]: Error: TRANSMIT_COMPLETE_ACK_UNKNOWN
2017-12-17T13:28:13.219Z
Command[3269] end: sendData
2017-12-17T13:28:13.219Z
Command[3270] start: sendData
2017-12-17T13:28:13.219Z
ProcessSendData[3270]: To node: 39 with data: 0x600d2703320110 and txOptions: AUTO_ROUTE
2017-12-17T13:28:13.229Z
ProcessSendData[3270]: Error: TRANSMIT_COMPLETE_ACK_UNKNOWN
2017-12-17T13:28:13.229Z
Command[3270] end: sendData
2017-12-17T13:28:13.229Z
Command[3271] start: sendData
2017-12-17T13:28:13.229Z
ProcessSendData[3271]: To node: 39 with data: 0x600d2704320110 and txOptions: AUTO_ROUTE
2017-12-17T13:28:13.246Z
ProcessSendData[3271]: Error: TRANSMIT_COMPLETE_ACK_UNKNOWN
2017-12-17T13:28:13.247Z
Command[3271] end: sendData
2017-12-17T13:28:13.247Z
Command[3272] start: sendData
2017-12-17T13:28:13.247Z
ProcessSendData[3272]: To node: 39 with data: 0x600d2705320110 and txOptions: AUTO_ROUTE
2017-12-17T13:28:13.257Z
ProcessSendData[3272]: Error: TRANSMIT_COMPLETE_ACK_UNKNOWN
2017-12-17T13:28:13.257Z
Command[3272] end: sendData
`

**Comment by SkorpionNL** [comment]
I also have this on RC7 with different devices. It jumps from device to device over time.

**Comment by mruiter** [comment]
Lots of peeps are reporting this on slack. I get numerous reports on the NEO app. But also peeps on Fibaro etc are reporting it

**Comment by TonD83** [comment]
I have the same. Wether it's coincidence or not, for me it only happens on one device (a Neo Coolcam device) I added after installing RC7. Other Z-Wave devices don't seem to have this problem (so far).

**Comment by djeskoswe** [comment]
got it jumping around here , NEO , TKB ... my log : CFBFDBE9B6

**Comment by AllG123** [comment]
Same here after rc7 update. Zwave network had a lot of problematiek devices are Neo and fibaro. Lot of time Out errors also and long delays before switching 5-6 seconds.

**Comment by philsniff** [comment]
one neo coolcam motion sensor is since rc7 grappy. it reacts slow or not. before it works great. i have a second neo motion sensor that works without problems.

**Comment by magtimmermans** [comment]
Same here with all neo coolcam power plugins

**Comment by djeskoswe** [comment]
![2018-01-03 16_50_51-athom developer](https://user-images.githubusercontent.com/17300121/34527625-660f5320-f0a6-11e7-9131-e23f83e46c58.png)

99%   :)

**Comment by jghaanstra** [comment]
I have not been experiencing this issue anymore since the upgrade to RC8. My Greenwave Powernode is responding like it should and I dont see any TRANSMIT_COMPLETE_ACK_UNKNOWN error in the zwave log.

 Can anyone confirm that this is also solved for them so I can close the issue.

**Comment by djeskoswe** [comment]
sorry to say.. bit still got it

**Comment by magtimmermans** [comment]
I have still the error.

**Comment by jghaanstra** [comment]
I do indeed still have the error but I also notice a difference with RC8. On RC7 the device would become completely unreachable when the error occured and the only way to resolve it was to reboot Homey. Now it seems the error still occurs but under certain circumstances the device does become controllable again by Homey.

I'm unsure if this is just a time thing or that it is triggered by manually controlling the device (or doing a PTP on the device) which restores the communication with Homey.

**Comment by djeskoswe** [comment]
any update on this bug ? need to remove the bat / socket every day to get all light to work 100%

**Comment by bvdbos** [comment]
statement today in bug #1899 https://github.com/athombv/homey/issues/1899#issuecomment-358363607

**Comment by jeroenvollenbrock** [comment]
Closed to combine under #1899
