### ISSUE TITLE
Lock Title bar in developer tools z-wave list

### ISSUE THREAD

**Issue by priknr1** [athombv/homey#2088]
In the developer tools, at z-wave,  the chapter "nodes"  has a list of nodes,  When scrolling, the title bar disappears.

Please lock this title bar, so when scrolling down, it still shows the column titles (rx, tx, and so on)

**Comment by SixFive7** [comment]
I would prefer not scrolling at all as it makes it considerably more difficult to get the lay of the lands routing wise with >20 nodes.

**Comment by WeeJeWel** [comment]
List doesn't scroll anymore now.
