### ISSUE TITLE
when i came home from my work, my homys ledring was totally white (which i not programmed). i only have 433 mhz actors and senders, but nothing was working. i put of the power supply and put it back on. the homey does very long to startup. after startup the ring again totaly white. then i grab my laptop and look in the homey, nothing strange. then i go to settings and did a official startup, now the ring is breathing which i programmed. but stil nothing on the 433 mhz is working.

### ISSUE THREAD

**Issue by nickyzoontjens** [athombv/homey#2090]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Wow what a story.....
But I guess to long as title for a best seller book....  ;-) 

Can you create a short to the point one line title and past your current title somewhere in the body, 

Please look at some other Issues and take a look at https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

Fill in your Homey firmware version, send a Log From Homey to Athom and past the code in your issue above, 

Also interesting to mention, 
How long do you have your Homey?
Was it working all the time? 
What Apps for 433 do you have?
Any other possible causes (anything changed recently)

Please pull the Plug for a couple of minutes (~10) before starting Homey. 
Check all your battery 433 senders if the battery is still OK, 
(also check other senders....)

eventually unplug all senders and just test Homey with a simple Flow with one sender (witch you preferably test with one receiver that it is working) to verify if that still works. (is Homey maybe defect or maybe something else)
