### ISSUE TITLE
[com.osram.lightify.zigbee] Add Osram Lightify Switch

### ISSUE THREAD

**Issue by dvanp** [athombv/homey#2093]
Please add the Osram Lightify Switch (4 buttons) to the Osram Zigbee app. It's currently not included in the app and I can't get it to pair as a generic device either.

For reference:
https://community.smartthings.com/t/osram-lightify-4-button-switch-dth-binder-alpha/99877
https://github.com/andyjenkinson/SmartThingsPublic/blob/master/devicetypes/andyjenkinson/osram-4-button-switch.src/osram-4-button-switch.groovy

**Comment by RobinBol** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
