### ISSUE TITLE
RGB(W) Bulbs do not have hue/saturation changed Flow Card Triggers

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2095]
The light devices with capabilities `onoff`, `dim`, `light_hue`, `light_saturation`, `light_mode`, (etc.) only have Flow Card Triggers for turned on/off and dim-level changed.

**Comment by bvdbos** [comment]
Then you may also merge #1842 in this one 😃

**Comment by RobinBol** [comment]
Haha thanks, will add it to that issue!
