### ISSUE TITLE
[com.nest] Cannot set Nest temperature through speech

### ISSUE THREAD

**Issue by ChrisBrandhorst** [athombv/homey#2099]
**Metadata**

* **Homey Version**: 1.5.6-rc.7
* **Homey Log Code**: E270C0DE66
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.3.3 - Build 70

**If related to a Homey App:**
* **Homey App Version**: 2.4.2
* **Homey App Log Code**: 70def3f7-e938-459a-8fae-01bf6b8a4297
* **Affected Devices (preferably product codes)**: Nest Thermostat V3

**What did you try to achieve?**
I'm trying to set the temperature of my Nest thermostat through Homey speech.
1. Installed Nest Homey App
2. Added Nest thermostat to devices
3. Say (in Dutch) "set temperature to X degrees" or use /manager/speech-input to fire this command

**What did you expect as result?**
Homey sets the Nest thermostat to the spoken / typed temperature.

**What was the result?**
Homey says (in Dutch): "The temperature is set to NaN degrees". The Nest Homey App log shows:
`(Living Room Thermostat) Kon doeltemperatuur niet aanpassen naar 0, error: Error: TEMPERATURE C VALUE IS TOO LOW: %S: {"error":"Temperature C value is too low: 0.0","type":"https://developer.nest.com/documentation/cloud/error-messages#low-c-value","message":"Temperature C value is too low: 0.0","instance":"afc64ff5-47df-4f3e-8e81-bf4603c705ec","details":{"tempC":"0.0"}}`

**Comment by maparicio** [comment]
I'm experiencing the same problem. I don't have a nest, but I have a temperature sensor and two radiator thermostats(Danfoss). Turning the heat up and down by one degree at a time works ("OK homey, increase/decrease temperature). I'm running Homey 1.5.8
