### ISSUE TITLE
Webhook default parser

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#210]
The default parser is `return false;` which I assume will never trigger the webhook in the app that registered using `Homey.manager('cloud').registerWebhook`.

So it needs to return true? Do I need to explain to my users that they need to create a webhook, copy the secret, url, ID. AND explain them that they need to change the parser to something?

Isn't the secret checked by default on post data or headers?

**Comment by WeeJeWel** [comment]
You should write your own logic there, so the webhook is forwarded to the correct Homey. For example for the [Thermosmart](https://github.com/athombv/nl.thermosmart) app:

![screen shot 2016-02-18 at 14 33 27](https://cloud.githubusercontent.com/assets/319873/13144726/9fdce4a8-d64c-11e5-8ebf-de7b6ac7637d.png)

**Comment by RuudBurger** [comment]
So the secrete is purely for the registerWebhook side? I was thinking is was needed for the request part of the external app part to.
Then I'll add some other key that can be compared, thanks.

**Comment by WeeJeWel** [comment]
Yes! The secret is used, so not everyone can listen to a user's webhook data.
