### ISSUE TITLE
[nl.klikaanklikuit] Second KAKU PAR-1000 switch will not work on seperate channel

### ISSUE THREAD

**Issue by ChrisBrandhorst** [athombv/homey#2100]
**Metadata**

* **Homey Version**: 1.5.6-rc.7
* **Homey Log Code**: E270C0DE66
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.3.3 - Build 70

**If related to a Homey App:**
* **Homey App Version**: 3.1.5
* **Homey App Log Code**: 4b44bf5a-be22-481f-97a4-641249f66e50
* **Affected Devices (preferably product codes)**: PAR-1000

**What did you try to achieve?**
1. Have one PAR-1000 switch linked to Homey on channel A1. This works;
2. Follow the wizard to add another PAR-1000 device for another channel, say, B1;

**What did you expect as result?**
When I follow the add device wizard and the screen comes up to test the connection by switching it off and on, I expect the device to switch off and on.

**What was the result?**
The device does not respond.

**Any other remarks**
If I set the new device to channel A1, it works flawlessly together with the existing PAR-1000 switch.

**Comment by KyleAthom** [comment]
This is fixed since the release of version 4.
