### ISSUE TITLE
App V2 - When using Chat the keyboard falls over the chat

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#2101]
**Metadata**

* **Homey Version**:
Latest experimental
* **Homey Log Code**:
* **Smartphone Platform**:
Android 7.0, Samsung Galaxy S7
* **Smartphone App Version**:
Latest Homey Preview

**What did you try to achieve?**
When using Chat the keyboard (swiftkey) it falls over the chat so I cant see what Im typing

**Any other remarks**
Please fix it :)

**Comment by kukel** [comment]
Already reported: If you'd have searched on 'keyboard' in github you'd have found it:

https://github.com/athombv/homey/issues/1931
