### ISSUE TITLE
issue with controlling stereo paired speakers in sonos app. only volume seems to work.

### ISSUE THREAD

**Issue by RolfJan** [athombv/homey#2103]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi RlfJan, 
Can you create a short to the point one line title starting with the App name (fe [com.sonos] ) and the problem (what doesn't work) or feature request (what you want to do but isn't possible at the moment).

Please look at some other Issues and take a look at https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

Fill in your Homey firmware version and App version, the product type you paired, 
send a Log From Homey to Athom (if necesary) and past the code in your issue above,

pls answer all questions above that are appropriate: 
What did you try to achieve?
What did you expect as result?
What was the result?

or come to the forum and ask help from one of the members with an Sonos there for help.

**Comment by bvdbos** [comment]
Think this is fixed with the latest app?

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
