### ISSUE TITLE
flows for zwave not working reliable

### ISSUE THREAD

**Issue by sjackver** [athombv/homey#2106]
<!--
**Metadata**

* **Homey Version**:
Homey Firmware Versie: 1.5.6-rc.7

**What did you try to achieve?**
Some flows in which i switch several zwave lights with one switch does not work reliable anymore. Flows which worked before stopped to work reliable. I can still control each light via the homey app. Also other flows which are triggered by voice or motion sensors work fine. I use fibaro switches.

**What did you expect as result?**
I expect the flow to work as it has done for the last year.

**Any other remarks**
I tried to rebuild the flow under another name and this worked for several hours and then stopped working again???

**Comment by bvdbos** [comment]
Well that's not descriptive, this is not a shoutbox... Please follow the guidelines and supply the information asked.

**Comment by jeroenvollenbrock** [comment]
Closing due to missing information. Please open a new issue and follow the contribution guidelines. Alternatively, if you require support and do not wish to report a bug, please contact support@athom.com
