### ISSUE TITLE
[AppStore] Link to Bugtracker from App.JSON is not  respected 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#2115]
**Metadata**

* **Homey Version**: na

**What did you try to achieve?**
Adding a Link to the Bugtracker as proposed in the App manifest.
Like Here: https://github.com/jghaanstra/android.ipwebcam/blob/0c5c2c93bcbb2054e90ca1e1aec43af9f76928aa/app.json#L27 (but also seen on own not yet pulished App. as Alpha)

**What did you expect as result?**
The correct Link in the App Store.....

**What was the result?**
The "Athom" link appears in the App store 
https://github.com/athombv/homey/issues/new?title=%5Bandroid.ipwebcam%5D%20Describe%20your%20issue%20here&

**Any other remarks**
This gives Athom A lot work extra like #2113  that was probably ment for @jghaanstra
removing the Link also fixes it as the Default Repository is Followed by the App store then.

**Comment by joachimroeleveld** [comment]
You're right; a fix is currently being deployed!
