### ISSUE TITLE
[nl.philips.hue] Set brightness of bulb by variable

### ISSUE THREAD

**Issue by StefanSimon** [athombv/homey#2117]
**Metadata**

* **Homey Version**: 1.5.6-rc.7
* **Homey Log Code**: B37C133F5D

**If related to a Homey App:**
* **Homey App Version**: 3.0.4

**What did you try to achieve?**
Integer logic variable on change set brightness of lights.
In my flow I have as trigger the onchange of my logic variable kitchen_brightness and as actions I have all my kitchen lights with the "set brightness" card. In the brightness I have the kitchen_brightness tag placed.

**What did you expect as result?**
The lights should be set to the brightness level provided by the logic variable. 

**What was the result?**
I'm able to set/change the variable and the flow triggers because other cards are activated but the lights don't change any brightness.

**Any other remarks**
The lights do change brightness when setting the brightness level by hand, so my guess is the problem is in providing the brightness from the variable tag.

![afbeelding](https://user-images.githubusercontent.com/8612992/34456923-02fba05a-eda3-11e7-94ff-06009a593b6a.png)

**Comment by bvdbos** [comment]
What value is your variable?

**Comment by StefanSimon** [comment]
the variable is between 0 and 100, it never gets below 0 or above 100.

**Comment by bvdbos** [comment]
If you set it between 0 and 1 it will work I guess

**Comment by Dijker** [comment]
Look at the Tag for the #Dim level in the Flow editor after setting the Dim level to fe 45% by hand it will be 0.45 . That works (for me) for all bulbs this way.

**Comment by StefanSimon** [comment]
Issue is solved. It is indeed between 0 and 1. Didn't know about the option to view the properties of items in the flow editor. Thanks for the help guys!

**Comment by Dijker** [comment]
No problem, 
Will you close your own Issue below here? Thanks!
