### ISSUE TITLE
[new functional add] 

### ISSUE THREAD

**Issue by vlasinus** [athombv/homey#2119]
add function enable/disable controllers. (z-wave, zigbee, 433, etc)
i am not using 433 and zigbee. only use z-wave. why i not disable other controllers.

**Comment by Dijker** [comment]
Can you describe what the advantage would be?

afaik rf (433/868) already never send unless you add devices and trigger them. Effectively they are already disabled if you don't use them. 

Maybe Homey as  Zigbee Coordinator now and then sends an sort of beacon signal it it there, 
but does that bother you?

**Comment by jeroenvollenbrock** [comment]
Unused controller are already suspended while they are not in use. As for zigbee, the chip does boot, but then enters an idle state. When you visit the zigbee settings or developer tools, the chip is resumed to provide information to the settings page, and is then re-suspended.
