### ISSUE TITLE
ThermoSmart App - Insigths graph drawing wrong

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#212]
Insights graph of Temperature shows strage data. like the temperature goes back in time ;-)
Downloaded data file shows  [NUL] values at that point during the log. 
 
![image](https://cloud.githubusercontent.com/assets/12412734/13135413/a12c087a-d610-11e5-800a-b0d46f1dd379.png)

![image](https://cloud.githubusercontent.com/assets/12412734/13135485/39d613d6-d611-11e5-9396-7da26eb1dd8b.png)

**Comment by Muyz** [comment]
This is a duplicate of https://github.com/athombv/homey/issues/139

@Dijker: a simple search for the word 'graph' would have revealed that this is a known issue.

**Comment by Dijker** [comment]
ok, sorry, expected it to be an ThermoSmart issue
didn't search for Graph ;-)
Thanks, wil clear the log and wait for the update
Closed.
