### ISSUE TITLE
Make Homey 'smarter' when I tell it "I'm cold"

### ISSUE THREAD

**Issue by kukel** [athombv/homey#2122]
* **Homey Version**: 1.5.6RC7

**What was I doing**
The current temperature in the livingroom was 19°C today and the Toon thermostat was on the 'away' setting (15°C) when I told Homey I was cold.

**What did I expect as result?**
I expected the heating to be set at a higher temperature than the current 19°C

**What was the result?**
The temperature was set on 16°C, only one degree higher (as Homey mentioned it would do)

**Comment by kukel** [comment]
@jeroenvollenbrock: Would not directly call it a bug, but it is not a featurerequest either. Somewhere in between... And unfortunately I cannot override the "Ik heb het koud" speech to trigger my own flow

**Comment by bvdbos** [comment]
You can make flows:
If "preset temperature" is increased and "actual temperature" is higher then "preset temperature" then set variable "temp preset temperature" to "actual temperature + 1". 
If  "temp preset temperature" is changed then set "set temperature" on thermostate to "temp preset temperature"

**Comment by kukel** [comment]
I know how to make flows etc. In my previous comment I stated that I can
not override the speech command since it conflicts with an existing Homey
one. And no I do not want to use a different speech command

Op 11 jan. 2018 22:57 schreef "Bas van den Bosch" <notifications@github.com

**Comment by Tweake** [comment]
The suggestion by @bvdbos Works great to enhance the built-in speech without causing a conflict. The idea of checking the temperature as part of the built-in speech has been listed as an enhancement idea, thank you for submitting it.

**Comment by kukel** [comment]
You mean it uses/overrides built in variables? Then I am very plesantly
surprises, have to complement @bvdbos  and 'retract' my previous comment

>

**Comment by WeeJeWel** [comment]
I am closing this issue because if we change it from 1 degree to a few more, other people might not like it. I suggest you to set the temperature directly by saying 'Set the thermostat to {x} degrees'
