### ISSUE TITLE
[Alarms] Alarms Disabled every day trigger unexpectedly

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#2123]
**Metadata**

* **Homey Version**: 1.5.6.-rc7
* **Homey Log Code**: na
* **Smartphone Platform**: na
* **Smartphone App Version**: na

**If related to a Homey App:** na
* **Homey App Version**: na
* **Homey App Log Code**: na
* **Affected Devices (preferably product codes)**:
Homey, 

**What did you try to achieve?**
I have two Alarms BlindsUp at set times (6h00 and 8h00) that I toggle for the Days of the week according to our working schedule. 

![image](https://user-images.githubusercontent.com/12412734/34476466-3e24fdbc-ef91-11e7-86fc-a0c47979b724.png)

I just toggle the selected days leaving the alarm on to execute the trigger on 6, on 8 or both off (When I want to operate manual) . 
Yesterday I toggled all selected day's off for the 6h as This week it should not trigger. (but leaving it enabled)

**What did you expect as result?**
Although enabled that it should not trigger as the day is not selected...

**What was the result?**
it triggered at 6 ....
[2018-01-02T05:00:00.655Z] Wekker RolluikenOmhoog 
[2018-01-02T05:00:00.691Z] AL! Then - ScreenUp2a
[2018-01-02T05:00:00.725Z] Rolluik omhoog

(Times are Zulu So Count + 1 )

**Any other remarks**
6 is to early......
But Homey knowing it was wrong disabled the alarm to fool me...
![image](https://user-images.githubusercontent.com/12412734/34476739-affb43ae-ef93-11e7-8e23-9d97249d1e42.png)

(also reproduced on second Homey with new Alarm and Flow )

**Comment by caseda** [comment]
don't have this issue with the 3 disabled alarms i have, so weird behaviour indeed

**Comment by jeroenvollenbrock** [comment]
An enabled alarm with no enabled days will trigger once, on the next moment the scheduled time hits. This is by design. We do however acknowledge that this is a bit difficult to see in the current interface, so we'll make two changes:

- When deselecting the last selected date on an enabled alarm, we'll toggle the alarm to off.
- We'll show a "Next due: tomorrow at 6:00 AM" label in the card when it is enabled.

**Comment by Dijker** [comment]
@jeroenvollenbrock 
nothing to discus, (except  in interface thing it should show it will trigger once next [time] )
but please add a Save of the Disabled state after an Alarm disabled all days and triggered once! 
;-)

**Comment by Dijker** [comment]
Fixed
