### ISSUE TITLE
Smartpresence card in "AND" column give wrong name

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#2125]
**Metadata**

* **Homey Version**: 1.5.6 rc7
* **Homey Log Code**: E04B38051B
* **Smartphone Platform**: Apple
* **Smartphone App Version**: 1.3. and 2.0

**If related to a Homey App:**
* **Homey App Version**: v0.2.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Creating a new flow for presence detection

**What did you expect as result?**

Correct name for the card in the AND column

**What was the result?**

In my opinion there is text missing when you mark the checkbox from the
<img width="1124" alt="schermafbeelding 2018-01-02 om 17 34 03" src="https://user-images.githubusercontent.com/25953849/34491549-2e065e0a-efe4-11e7-882d-cd0dc6b23d8f.png">
 card "Someone is at home" to make it not at home it only show "at Home" see screen dump 

**Any other remarks**

**Comment by bvdbos** [comment]
This is an issue for the smart-presence app but you were send here because of #2115 
https://bitbucket.org/terryhendrix/homey-smartpresence/issues

**Comment by jeroenvollenbrock** [comment]
I've took the liberty to report this issue for you on your behalf at https://bitbucket.org/terryhendrix/homey-smartpresence/issues/29/smartpresence-card-in-and-column-gives . I'm closing this issue for now, as it is indeed reported in the wrong issue tracker due to #2115
