### ISSUE TITLE
App settings, translated strings have random opacity

### ISSUE THREAD

**Issue by RuudBurger** [athombv/homey#213]
When I use `<h1 data-i18n="settings.title"></h1>` in my settings html, the elements get a random opacity.
Like it has stopped in the middle of an animation. Maybe the `Homey.ready()` has something to do with this?
The file with issue can be found at https://github.com/CouchPotato/Homey-App/blob/master/settings/index.html (note that I force `opacity: 1` at the top now, so to test disable that).

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by WeeJeWel** [comment]
This functionality has been removed a while ago so I'm closing this issue.
