### ISSUE TITLE
No Battery-Level-Report Philio PST02-A 

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#2131]
**Metadata**

* **Homey Version**: 1.5.6-RC6
* **Homey Log Code**: -
* **Smartphone Platform**: Android Oreo
* **Smartphone App Version**: 2.4.7 B77 / Beta 0.8.5.115

**If related to a Homey App: Philio (https://apps.athom.com/app/com.philio)**
* **Homey App Version**: 0.0.22
* **Homey App Log Code**: -
* **Affected Devices (preferably product codes)**: PST02-A 4:1 (Manufacturer 316, ProductType 2, ProductID 12)

**What did you try to achieve?**
Checking Battery-Level of Device: Webbrowser, AndroidApp, Android-Beta-App > Select Devices, Select Device-Card, Looking Information Battery-Level

**What did you expect as result?**
Correct Battery-Level-Information

**What was the result?**
All Sensors showing 100%

**Any other remarks**
See Attachment (Battery of this Device changed two Weeks ago). Insights showing other Informations about the Battery-Level with the same Battery in the Device. Device-Card shows 100%. Before 1.5.6 this works fine.

![chart](https://user-images.githubusercontent.com/26149030/34515168-24e388d8-f071-11e7-85b9-23df3a52d642.png)
  
Reported this also here because didn't know if this is a Homey Issue or one of the Philip-App: https://github.com/Inversion-NL/com.philio/issues/37.

**Comment by CyberSponk** [comment]
Updated Homey to 1.5.6-RC11. Device-Card shows 100% or an "-". On Insights nothing to see with Battery.

**Comment by CyberSponk** [comment]
Not resolved in Homey 1.5.6-RC13.

**Comment by CyberSponk** [comment]
Updated to 1.5.7. Not Resolved.

**Comment by RobinBol** [comment]
Seems like an app and/or device issue, not much Homey can do here. Since the main issue (https://github.com/Inversion-NL/com.philio/issues/37) was closed, will also close this one.
