### ISSUE TITLE
Zigbee is (totally) broken, controller crash?

### ISSUE THREAD

**Issue by cautje** [athombv/homey#2132]
**Metadata**

* **Homey Version**:1.5.6-rc.7
* **Homey Log Code**:750DF0481F
* **Smartphone Platform**:android
* **Smartphone App Version**:2.4.9

**If related to a Homey App:**All zigbee (general zigbee, Ikea and MI)
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:All zigbee devices are down, it looks the zigbee controller is broken. All zigbee is not working anymore. See screenshots.

**What did you try to achieve?**

I noticed the ikea lamps where not responding, also it was not possible to ad new zigbee devices.
In settings the zigbee part is not opening and it is not possible to open the ad zigby devices section.

**What did you expect as result?**

Zigbee to work as before. Till today  zigbee works ok, not perfect but ok.

**What was the result?**

Not one working zigbee device and not possible to at new.

**Any other remarks**
I restarted the MI and ikea app, restarted the homey and pull the plug, noting helped.
![2018-01-03 20_22_24- 135 zones devices - helbeekonline nl](https://user-images.githubusercontent.com/19371264/34536665-305d703e-f0c6-11e7-8083-65542d5f6313.png)
![2018-01-03 20_22_53- 135 zones devices - helbeekonline nl](https://user-images.githubusercontent.com/19371264/34536666-307d028c-f0c6-11e7-8d07-4a9660e5da2b.png)
![2018-01-03 20_23_18- 135 zones devices - helbeekonline nl](https://user-images.githubusercontent.com/19371264/34536667-3099aeb4-f0c6-11e7-9e57-c1786a994fbf.png)
![2018-01-03 20_24_50- 135 settings - helbeekonline nl](https://user-images.githubusercontent.com/19371264/34536669-30b7f888-f0c6-11e7-9bb0-c308d96c9dfa.png)
![2018-01-03 20_26_56- 135 settings - helbeekonline nl](https://user-images.githubusercontent.com/19371264/34536670-30d76a60-f0c6-11e7-9845-e49ee125718d.png)

**Comment by cautje** [comment]
![2018-01-03 20_40_38-athom developer](https://user-images.githubusercontent.com/19371264/34536743-747d0590-f0c6-11e7-9e95-dc34e58219fe.png)

**Comment by RobinBol** [comment]
Could you send a log? Settings > System -> 'send a log'

**Comment by cautje** [comment]
Hi @RobinBol ,
Thx for your reaction!
Yes i even ptp for 30 minutes, this advice i got from the slack guys, although is cant image why a 30 minute ptp would be beter than a 5 minute.
How can i update to RC8?
Yesterday i have sent an email to Bram from support but had no reaction, maybe he is bussy.
THX! Rutger

**Comment by bvdbos** [comment]
The zwave-devices have a memory in them, so will Zigbee devices have probably. If you reconnect too soon they will start sending the same messages again. RC8 is in DP now, not in experimental yet.

**Comment by epjjansen** [comment]
see also: [https://github.com/athombv/homey/issues/2074](url)

**Comment by cautje** [comment]
Yep, i see.
The difference is that mine does not do anything at all.
Even a PTP from one hour works.
THX!

**Comment by jeroenvollenbrock** [comment]
@cautje Did 1.5.6-rc.8 resolve the issue?

**Comment by cautje** [comment]
Nope, exact the same. PtP dit not work. Zigbee is not working at all, also not right afther the update.
Do you neet a new log?
THX!

**Comment by jeroenvollenbrock** [comment]
Could you send me a new log about 10 minutes after homey booted?

**Comment by cautje** [comment]
@jeroenvollenbrock i made a new commentaar buy forgot to mention you

**Comment by cautje** [comment]
Yes, i Will do that

**Comment by jeroenvollenbrock** [comment]
@cautje I received a notification anyway, don't worry :)

**Comment by cautje** [comment]
Hi Jeroen, I dit an PtP and waited 10 minutes. Zigbee is not ok. This is the log 05AB2B3750
Everything else workes fine.
THX!!!

**Comment by cautje** [comment]
![image](https://user-images.githubusercontent.com/19371264/34790984-ded54b64-f643-11e7-8f80-6049479fe488.png)

**Comment by cautje** [comment]
![image](https://user-images.githubusercontent.com/19371264/34791020-fb3a5cae-f643-11e7-96e6-b59f90ac748a.png)

**Comment by cautje** [comment]
![image](https://user-images.githubusercontent.com/19371264/34791059-1a0c02ea-f644-11e7-9bee-90f475e54fcf.png)

**Comment by cautje** [comment]
@jeroenvollenbrock 
Hi Jeroen, i see you are waiting for me, i already made the log 8 days ago.
Dit you not find it?
05AB2B3750
THX!
Rutger

**Comment by cautje** [comment]
Hi @jeroenvollenbrock 
20B4C37A9A afther 15 minutes PtP.
Hope you can find something.
THX!

**Comment by jeroenvollenbrock** [comment]
Hi @cautje, This should be resolved in 1.5.6-r.10

**Comment by cautje** [comment]
That would be great!!! Do you have an estimate date?
THX!!!

**Comment by cautje** [comment]
@jeroenvollenbrock 
It works! Zigbee is rocking again!!!
THX!
