### ISSUE TITLE
[com.fibaro] motion sensor are not working anymore

### ISSUE THREAD

**Issue by rvanwijngaarden** [athombv/homey#2136]
**Metadata**

* **Homey Version**:
1.5.3
* **Homey Log Code**:
4283355FAE
* **Smartphone Platform**:
IOS
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

A working solutions, non of my motion sensor are working anymore (no light is triggered with the flow in my homey)

**What did you expect as result?**

Light go on (motion  detected -> homey ->homey flow -> lights on

**What was the result?**

No light are going on

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
This issue is most likely resolved in Homey version 1.5.6-rc.8

**Comment by jeroenvollenbrock** [comment]
Closing to combine under #2267
