### ISSUE TITLE
App settings lost and don't store anymore

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#214]
I'm busy developing an OpenTherm Gateway app (id: com.tclcode.otgw) and when starting a new test run yesterday the settings were lost. The IP address and port are stored in the application settings.

On investigation it looks like the calls Homey.set doesn't seem to return. But also a function like client.connect (from require('net')) does not work anymore. So I cannot proceed any further. The app is broken without making any code change.

A Homey recovery did not help to resolve it.

**Comment by WeeJeWel** [comment]
I fixed this in 0.8.19. It happened when you were writing settings too fast concurrently.

**Comment by nlrb** [comment]
Thanks for looking at it, but that would be strange. Settings are only written after the user presses a button. I don't believe I've done that in the last days. The settings have only been read.

Also, how do I get Homey in a usable state again? And why can the app not create communicate via the network anymore? How is that related to the app settings?

**Comment by WeeJeWel** [comment]
That's odd indeed. To reset your Homey, follow the instructions here:

https://forum.athom.com/discussion/528/received-your-homey-getting-started-guide/p1
Factory Reset your Homey, or Changing Wi-Fi networks

**Comment by nlrb** [comment]
That is what I meantioned initially: A Homey recovery did not help to resolve it.

So I followed that procedure, but it makes no difference.

**Comment by WeeJeWel** [comment]
Could you provide a code example that doesn't work like it should?

**Comment by nlrb** [comment]
Yes, will do that this evening (currently @work).

**Comment by nlrb** [comment]
I've found this issue. It was caused by a driver sending
`self.realtime(device, 'measure_temperature', null)`
which halted the execution of all other app code.

**Comment by nlrb** [comment]
One a related note, please check the inputs of API functions. For the 'realtime' function I was also able to pass the device.id (type string) instead of the device info (type object). The result was that the realtime updates did happen, but sometime on the wrong device.

**Comment by nlrb** [comment]
@WeeJeWel: I guess you prefer me not to submit issues anymore? Consider it done.

**Comment by WeeJeWel** [comment]
Of course not, but the issue has been closed. Your suggestion is a good one.

**Comment by nlrb** [comment]
Ah, ok, I thought nothing had changed. Would be good to indicate what has changed when closing a ticket.

**Comment by WeeJeWel** [comment]
I'm sorry. It's been a long day already :)

**Comment by nlrb** [comment]
For all of us I guess...
