### ISSUE TITLE
Fibaro Wall Plug F can not be switched off anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2150]
* **Homey Version**: 1.5.6 rc8
* **Homey Log Code**: 5337577AB3
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
Fibaro smart wall plug F

**What did you try to achieve?**
Switch off wall plug when going to bed

**What did you expect as result?**
That no power is on the wall plug when switched off

**What was the result?**
Only the Watt meter and wall plug led light is switched off the power is still on the plug.

**Any other remarks**
I don't know since when this issue started as this is the first time I used these switches since a long time

**Comment by chrisboer** [comment]
Tried to see if it was fixed with fibaro 1.5.14 software update but still the same issue wall plug can not be switched off

**Comment by WeeJeWel** [comment]
Can you paste a Z-Wave log, found on https://developer.athom.com/tools/zwave ?

**Comment by OlafSchippers** [comment]
I have a similar problem with the same type wallplug.
I can switch it off, but it switches on again after a couple of minutes.
I added the zwave log as txt file
[Fibaro wall plug.txt](https://github.com/athombv/homey/files/1639416/Fibaro.wall.plug.txt)
also version 1.5.6rc8
In the log it is node 2

**Comment by WeeJeWel** [comment]
@chrisboer How do you switch the plug? By Flow or manually, and does it differ?

@OlafSchippers I see incoming reports that the plug has switched itself on. Maybe you have an association somewhere, this does not seem to be a Homey bug.

**Comment by chrisboer** [comment]
@WeeJeWel  first question 

[2018-01-17T16:33:43.358Z] Command[670] start: sendData
[2018-01-17T16:33:43.361Z] ProcessSendData[650]: To node: 56 with data: 0x200100 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-17T16:33:43.420Z] Command[670] end: sendData
[2018-01-17T16:33:43.559Z] Command[671] start: sendData
[2018-01-17T16:33:43.559Z] ProcessSendData[651]: To node: 56 with data: 0x2001ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-17T16:33:43.614Z] Command[671] end: sendData
[2018-01-17T16:33:49.143Z] Command[672] start: sendData
[2018-01-17T16:33:49.145Z] ProcessSendData[652]: To node: 56 with data: 0x2001ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-17T16:33:49.201Z] Command[672] end: sendData
[2018-01-17T16:33:49.856Z] Command[673] start: sendData
[2018-01-17T16:33:49.856Z] ProcessSendData[653]: To node: 56 with data: 0x2001ff and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2018-01-17T16:33:49.911Z] Command[673] end: sendData

**Comment by WeeJeWel** [comment]
@chrisboer I see that the command 'OFF' is sent first, and then 'ON' is sent three times. You might have some interfering Flow somewhere.

Closing this issue as it's unlikely to be a Homey bug. If you're able to isolate the issue and share some test results I'd be happy to open it again!

**Comment by chrisboer** [comment]
@WeeJeWel Second question How do you switch the plug? By Flow or manually, and does it differ?

That does not differ, so I have wall plugs which are installed the same time and they still work ok. But for some reason this one does not work anymore. 

I switch it off manually the power remains online. 
I switch it off via a flow the power remains online.

**Comment by chrisboer** [comment]
@WeeJeWel I did this on and off multiple times to generate log because log was not enabled.

**Comment by chrisboer** [comment]
When I completely reset the power wall device I can switch it on and off again (when not connected/paired) to homey. 

At the moment I pair it with homey the power wall does not function anymore ergo it does not power off anymore

**Comment by WeeJeWel** [comment]
Is 'Always On' checked in the device settings? Fibaro plugs have this feature. If not, try enabling it, save, disabling it, save, and try again.

**Comment by chrisboer** [comment]
![afbeelding](https://user-images.githubusercontent.com/23163409/35054874-00b41034-fbae-11e7-9058-9565f1a2218c.png)

I have no flow installed with it currently so conflicting flow is also impossible

**Comment by chrisboer** [comment]
Still does not work with Fibaro Update
