### ISSUE TITLE
 .. [com.aeotec] Add doorsensor?

### ISSUE THREAD

**Issue by Tuinsmurf** [athombv/homey#2152]
i want to try connect a ZW089-c to homey. but someting go wrong. I open the installed app and press on the icon. than he says to press on the Z-wave button. he is only saying: Security key is exchanged,but it didn't work and i can't see the sensor in homey. Do you know what the problem is?

**Comment by WeeJeWel** [comment]
Try removing the device via Settings > Z-Wave, and then add it again, but this time keep it closer to Homey.

**Comment by Tuinsmurf** [comment]
Hi,
Thats not working. I tried it Manny times. It’s strange because it’s very
easy to delete a device, but verry hard to connect with homey. All the
times I try to ADD the device with homey nearby (1 meter). I try to ADD it
with the aeotec app and also with the quick Z-wave ADD button...

Any other ideas?

Bye bye

Op wo 17 jan. 2018 om 13:36 schreef Emile Nijssen <notifications@github.com>
