### ISSUE TITLE
Request: Add Homematic (app) to Homey

### ISSUE THREAD

**Issue by SjaakKoning** [athombv/homey#2155]
Please consider to add Homematic to work with Homey.

http://www.homematic.com/

Is is been requested several times in https://forum.athom.com/discussion/comment/64912/

> Summary Week 34 & 35 (August 21 - September 1)

Homey v1.5
We didn't quite make August to release Homey v1.5.0 to the Stable channel, but the plan is to do so upcoming Monday. Then finally everyone can enjoy the newest version of Homey.

Shortly after we will release Homey v1.5.1 v1.5.2 which includes Z-Wave MultiChannel Association and several other improvements.

Athom Developer Portal
Today we have also launched the Athom Developer Portal, which is made for developers to improve the development process. Read the announcement here.

Homey Apps
We have released, or are about to release: Dyson, KlikAanKlikUit ZigBee, NetAtmo Welcome, Bosch-Siemens Home-Connect, Nest Cam, Smarter.am, **_# eQ-3/HomeMatic_** and Honeywell Lyric.

Backup & Restore
We have silently started working on Backup & Restore functionality, which will make life easier when migrating between Homeys, or to restore a backup in case of data loss.

Homey Smartphone App
The new app is getting better, and we think that it's ready within two weeks to be released to Developer Preview users. There's still a long road to go, but it's already much faster and more user friendly than the current app!

> ****

**Comment by philsniff** [comment]
+1
Yes indeed, several times promised!

**Comment by BasKiers** [comment]
Hi,

We've created the Homematic app and are now testing the stability of the app. 

Regards,
Bas

**Comment by philsniff** [comment]
geat news!!

**Comment by SjaakKoning** [comment]
Thank You!

**Comment by mveck** [comment]
Gents, that’s awesome. I was mistakenly adding a new feature req. I will start testing as soon as I have installed. With respect to stability Homematic is far superior to Zigbee, I am using it all over my house and never got connection problems.

**Comment by SjaakKoning** [comment]
When will it be released?

**Comment by gooooba** [comment]
I have homematic already and bought homey becouse it promised support more than I year ago when I checked.

**Comment by roelhendr** [comment]
Any updates on supporting Homematic?

**Comment by elisaado** [comment]
Hi, we are currently testing a HomeMatic app which supports a couple of devices.

**Comment by roelhendr** [comment]
Which devices will be supported?

https://www.homematic-ip.com/en/products/all-products-at-a-glance.html

I'm interested in:
- Access Point
- Radiator Thermostat
- Multi IO Box
- Wall Thermostat
- Floor Heating Actuator
- Pluggable Switch (and Meter)

**Comment by elisaado** [comment]
@roelhendr For this release we plan on supporting
* HomeMatic Button (not IP)
* HomeMatic Socket (with or without power meter) (not IP)
* HomeMatic IP Water Sensor (IP)

*Also, anyone who wants to test the app once it is in Alpha, please send me your email on slack (@elisaado) or put it here.*

**Comment by roelhendr** [comment]
Thx for the feedback! Will the other devices be supported also (after first release)?

**Comment by elisaado** [comment]
@roelhendr We hope to.

**Comment by gooooba** [comment]
Is there any timeline for general release? Or at least beta app so it can be installed via CLI?

**Comment by mveck** [comment]
I am interested for Alpha, but is this the similar app as done by Timo? Getting a bit confused. Happily using homematic switches and radiator thermostats and relais in my house. Until now using Qivicon to run these.

**Comment by WillooWisp** [comment]
@elisaado I would like to test the HomeMatic app, if it supports products like HM-LC-Sw4-SM and its remote HM-RC-12-B?

**Comment by WillooWisp** [comment]
Does anyone know how to get this HomeMatic app, alpha or not?
