### ISSUE TITLE
Screensaver Register: undefined is not a function

### ISSUE THREAD

**Issue by stefanwitkamp** [athombv/homey#216]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Create an app with screensaver

*Please include detailed steps how we can reproduce the issue*

include Homey.manager('ledring').registerScreensaver('name', screensaver); in code.

**What was the result?**
TypeError: undefined is not a function
    at Object.self.public.registerScreensaver (/opt/homey-client/system/types/manager/apps/bootstrap/homey-app/manager/ledring.js:1:1115)
    at null._onTimeout (/app.js:109:28)
    at Timer.listOnTimeout (timers.js:119:15)

**What did you expect as result?**
Screensaver registered

**Any other remarks**
Followed the docs
...

**Comment by matjaz** [comment]
similar to #205

**Comment by WeeJeWel** [comment]
This error is caused if you don't supply a callback function. Fixed in 0.8.19
