### ISSUE TITLE
Multiple triggers for one flow, not using tags.

### ISSUE THREAD

**Issue by Mecallie** [athombv/homey#2163]
Let any motion detection sensor trigger a flow when no one is at home.

**What did you expect as result?**

One flow with multiple triggers.

**What was the result?**

One flow per motion detector...

**Any other remarks**
Scenario:
I have several motion detectors.
I use the SmartPresence app to see if anyone is home.
When no one is home, I set a variable "Alarm status" to "ARMED".

If any of my motion detectors detect movement when the alarm status us set to "ARMED" I want to send a push message and sound a siren.

Right now I have to create one flow for every device :(

If app tokens are still a problem: would it be possible to add a trigger along the lines of "any movement" has been detected globally?

**Comment by djeskoswe** [comment]
use the build in devices card or the app Heimdall ( alarm app) as trigger

**Comment by Dijker** [comment]
I guess a Duplicate of #1628 #444 and many other discussions 
But you could Use this, 

![image](https://user-images.githubusercontent.com/12412734/35015215-a2da185e-fb13-11e7-957c-1dfb909835fa.png)

as this is what Athom's answer was.

**Comment by Mecallie** [comment]
I actually read #444 and did not find the answer there. I missed #1628 . It still means having multiple triggers for multiple device classes, but I don't see that as an issue. (And as far as I can tell the Heimdall app fixes event that. Sorry: I thought it was just for "Heimdall" sensors :) ).

Thanks for your quick replies. Hopefully more people will find these threads and not create duplicate reports anymore. 👍
