### ISSUE TITLE
[nl.eneco.toon] Changing password without re-adding device

### ISSUE THREAD

**Issue by kukel** [athombv/homey#2164]
**Metadata**

* **Homey Version**: 1.5.8RC2
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A (Android)
* **Smartphone App Version**: N/A (V2, build 0.8.5.115)

**If related to a Homey App:** Toon
* **Homey App Version**:  1.3.6 (Beta)
* **Homey App Log Code**: N/S
* **Affected Devices (preferably product codes)**: Toon, (firmware 4.10.6)

**What did you try to achieve?**
Nothing yet but I'd like to change the password of the Eneco account both for Eneco and hence also for the Toon App in Homey

**What did you expect as result?**
Being able to change my password in Homey for the Toon app without the need for removing the device and add it again (and loosing history insights)

**What was the result?**
Not being able to just change my password

**Any other remarks**
Being able to **not** loose any insights while doing so (or removing and adding the same device since it  (or the related app) is not stable in Homey (or Homey itself))

**Comment by WeeJeWel** [comment]
I think you don't have to re-add Toon, because Homey does not store your Toon's password, as we use OAuth2 for authentication. Maybe @RobinBol can shed some more light on this.

Closing for now.
