### ISSUE TITLE
Enhancement request: Confirm leaving flow editor without saving

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#217]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Change an existing flow.

_Please include detailed steps how we can reproduce the issue_

Open an existing flow.
Make a modificatie.
Leave the flow editor.

**What was the result?**

The changes made wereld lost.

**What did you expect as result?**

A confirmation message: "do you want to leave the flow editor without saving" OK/cancel

**Any other remarks**

You guys are awesome!

**Comment by WeeJeWel** [comment]
Added in v1.3.0
