### ISSUE TITLE
[feature request][athom-api][com.athom.homeyscript] missing function updateToken

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#2171]
**Metadata**

* **Homey Version**: 1.5.6.rc8
* **Homey Log Code**: na
* **Smartphone Platform**: na
* **Smartphone App Version**: na

**If related to a Homey App:** HomeyScript 1.0.2 / athom-api 2.0.94
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
update a token from fe HomeyScript

**What did you expect as result?**
find it in the documentation below this one 
 https://developer.athom.com/docs/api/HomeyAPI.ManagerFlow.html#getToken

**What was the result?**
nothing found to create/update/delete a Tag/Token 
like there are createFlow/ getFlows/getFlow/updateFlow / deleteFlow ...

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Tokens are always updated by apps. It is not possible to update a token through the API.

**Comment by Dijker** [comment]
@jeroenvollenbrock 
Hmmm... I do not agree....
https://photos.app.goo.gl/eKG7hiILoDr9PfpT2
Users can set tags from flows. 
But for a forum member requesting some calculation it would be nice to run a HomeyScript and return the value  from the script. 
Do you have any other option from HomeyScript to return a numeric or text value? 
As fare as I know atm only a true or false can be returned by running as condition.

**Comment by jeroenvollenbrock** [comment]
HomeyScript version 1.0.3 adds the setTagValue function. This function can be used to create, update and delete HomeyScript Flow tags. https://apps.athom.com/app/com.athom.homeyscript

**Comment by Dijker** [comment]
@jeroenvollenbrock Thanks for the update, 

Altough after testing it, it isn't exactly what I expected as the HomeyScript Tags and Flow Tags are different "classes" or Apps.

fe I I already created a dayOfYear Bettere Logic for the Demo, 
to update to Homey Logic I created a DayOfYear numeric Tag from the Flow 
After running the updated HomeyScript with the line:

```js
await setTagValue(BLVarName, {type: "number", title: BLVarName}, dayOfYear );
```
I see a third tag with the same name, from the App HomeyScript.

![image](https://user-images.githubusercontent.com/12412734/35467110-1cd1aa7e-030b-11e8-9938-fdd44480c2b8.png)

Not yet a problem as the Tag is usable as droptoken, 
but creating a Flow with the trigger "A Variable Changed" doesn't trigger on the changed HomeyScript Variable / Tag .

![image](https://user-images.githubusercontent.com/12412734/35467201-e9f95556-030b-11e8-8c9a-6b774d48fdab.png)

We can create a HomeyScript Variable has Changed card in the HomeyScript App as trigger but I guess that would also be confusing .....

just my thoughts and 2ct...

(Also Confusing, what we call a Variable in the FlowCard is a Tag in the current Desktop Menu and if we code JS the API asks for Tokens..... Except when it is done in HomeyScript, then it is accessed as a setTagValue )
