### ISSUE TITLE
[com.athom.homeyscript] Homey.flow.getToken is not a function 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#2172]
**Metadata**

* **Homey Version**: 1.5.6.rc8
* **Homey Log Code**: 62B1C2DB9B
* **Smartphone Platform**: na
* **Smartphone App Version**: na

**If related to a Homey App:**
* **Homey App Version**: 1.0.2
* **Homey App Log Code**: 8eb6f1cc-cfbc-453d-8e71-11e2c30e945c
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
get one Tag (token):

let allTokens = await Homey.flow.getTokens(); // this works
let oneToken = await Homey.flow.getToken( {id: 'ExampleNTag', uri: 'homey:manager:logic' } );

Homey.flow.getToken is not a function  

**What did you expect as result?**
that itworked to get one token 
(as documented https://developer.athom.com/docs/api/HomeyAPI.ManagerFlow.html#getToken)

**What was the result?**
error / popup: Homey.flow.getToken is not a function  

**Any other remarks**
probably due to module  athom-api@2.0.34 not up to date .... ??

**Comment by jeroenvollenbrock** [comment]
athom-api is indeed not up to date, we'll release an updated version soon.

**Comment by jeroenvollenbrock** [comment]
Resolved in Homeyscript 1.0.4
