### ISSUE TITLE
Fibaro Wall Plug Z-wave plus issues

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2174]
Homey Version: 1.5.6 rc8
    Homey Log Code: C38BD7BA75
    Smartphone Platform: IOS
    Smartphone App Version:

If related to a Homey App: Fibaro

    Homey App Version: 1.5.17
    Homey App Log Code:
    Affected Devices (preferably product codes):
    Fibaro smart wall plug F Z-wave plus

What did you try to achieve?
Switch off wall plug when going to bed

What did you expect as result?
That no power is on the wall plug when switched off

What was the result?
With the update of fibaro it has become worse to #2150 now also the energy meter is not working anymore. And when trying to remove the wall plug via the normal way I get this message but still not removed.

![afbeelding](https://user-images.githubusercontent.com/23163409/35220818-0aa58d2a-ff78-11e7-8226-4b5b1dbca197.png)

Via Z-wave removed I get an ok removed

![afbeelding](https://user-images.githubusercontent.com/23163409/35220861-3b91a216-ff78-11e7-8f8b-d3c2953369cb.png)

Repaired again as Fibaro wall plug z-wave plus and came up again but still the device does not shut off nor gives power status anymore.

![afbeelding](https://user-images.githubusercontent.com/23163409/35221016-e48a6218-ff78-11e7-980a-79cb81431809.png)

![afbeelding](https://user-images.githubusercontent.com/23163409/35221195-92e204f6-ff79-11e7-8629-c21ffe375f0f.png)

Any other remarks
I don't know since when this issue started as this is the first time I used a flow again on this switch since a long time.

**Comment by jeroenvollenbrock** [comment]
@WeeJeWel It looks like the node did not get a secure node flag?

**Comment by chrisboer** [comment]
Is it alive ... .it works again ... after the upgrade to 1.5.6 rc11 the power wall outlet works as before, I did not do anything else then only upgrade towards 1.5.6 rc11
