### ISSUE TITLE
[com.e-domotica] EM6550 not recognised 

### ISSUE THREAD

**Issue by relshout85** [athombv/homey#2175]
Log code Homey:

**Metadata**

* **Homey Version**:
Homey Firmware Versie: 1.5.3
* **Homey Log Code**:
1D144EF6B0
* **Smartphone Platform**:
MacOS X
* **Smartphone App Version**:
Used old desktop app

**If related to a Homey App:**
* **Homey App Version**:
v 1.0.1
* **Homey App Log Code**:
Cannot generate Homey App log code (option to seen 'Send Log' doesn't work)
* **Affected Devices (preferably product codes)**:
EM6550:
![image](https://user-images.githubusercontent.com/33072118/35241865-391e96b6-ffb8-11e7-8f7b-3a7be62bf253.png)

**What did you try to achieve?**

Tried to add EM6550 wall plug to homey. 
First installed e-domotica app, tried to install but recognised as 'Default Z-wave device'.
After that saw that everspring app was needed so installed that also :o).
Removed registered "Default Z-wave device", tried again. Does not recognise EM6550 plug, reinstalled and tried again. Still not recognised.

**What did you expect as result?**

I would expect the device to be recognised and installed.

**What was the result?**

Default Z-wave device

**Any other remarks**
If you need any other information please let me know!

**Comment by RobinBol** [comment]
App was just updated with the additional product type id 260, thanks for reporting!
