### ISSUE TITLE
If Homey is disconnected from the cloud it stays disconnected from the cloud until reboot

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#2182]
**Metadata**

* **Homey Version**:      1.5.6-rc8
* **Homey Log Code**:  does not apply
* **Smartphone Platform**:  does not apply
* **Smartphone App Version**:  does not apply

**What did you try to achieve?**

nothing , i see in my app and in my.athom.nl that Homey is disconnected from the cloud one a day now .
Apps on Homey trying to make ip  connections doesnt work

**What did you expect as result?**

that if Homey disconnects from the Wifi , it can creestablish the wifi connection like most other devices connected to a router via wifi. Now i have to reboot Homey everytime it is disconnected from the cloud or wifi.

**Comment by Dijker** [comment]
I read differend possible issues, can you be more specific? 
Does it not re-connect to Wifi if the wifi briefly disappeared? (I don't recognise this!)
Is your Homey reachable on the lan ip?
Fe try if it Does re-connect on a restart of your accespoint?
The apps on your Homey,  do they try to connect to local ip addresses or on  internet? 
Does Homey still function local? Fe receive a 433 button and show the ledring as response? 
Can you try to send a log for Athom to investigate?  (When this happens or  a couple of minutes after a ptp / restart)

**Comment by nattlip** [comment]
Please give this code to the Athom employee:

592F0B4397

to start with i still have connection with the usb network via my computer because i have a usb connection to homey to debug, that network works well thats why i can see there is non cloud connection, and no wifi connection because as i stated in the first message apps cant make ip connections. homey functions normal withoud clud connection my debug log reports of my apps keep coming in via the usb network.

**Comment by Dijker** [comment]
Can you try using the normal power adapter? Does it also happen then?
Maybe your computer can't provide enough power that causes the problem....

**Comment by nattlip** [comment]
it happens also when i am not at home and the computer is off , and it worked some months well .

**Comment by nattlip** [comment]
i use a usb cable with two ends one oneside and the other end in homey

**Comment by Dijker** [comment]
Does it also happen with the original USB cable?

**Comment by nattlip** [comment]
well this happens no more after 1,5.6   close it ?
