### ISSUE TITLE
UI bugs: One vertical scrollbar missing + one horizontal scroll too many in devices section [0.8.17]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#219]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Use 50+ devices in Homey.

*Please include detailed steps how we can reproduce the issue*

Add 55 devices, want to show and use them all in the Devices section of Homey.

**What was the result?**

There was a horizontal scrollbar which shouldn't be there, and I needed a vertical scrollbar to use/see all devices, which was missing. So I couldn't use/show the devices, but only half of them!

**What did you expect as result?**

The opposite exactly from what the result was, and now I can't use all devices.

**Any other remarks**

Screenshot of the problem:

![image](https://cloud.githubusercontent.com/assets/16608801/13184698/ab6644da-d73d-11e5-94d2-123349159a9c.png)

**Comment by ralfvd** [comment]
Might be similar to issue #200 ?

**Comment by athomey** [comment]
Thx for the addition. Maybe it's the same, but is another section of the application.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.21
