### ISSUE TITLE
z-wave (network) heal does not work on 1.5.6-rc.8

### ISSUE THREAD

**Issue by mickem** [athombv/homey#2193]
**Metadata**

* **Homey Version**: 1.5.6-rc.8
* **Homey Log Code**: DC65D65F06
* **Smartphone Platform**: N/A
* **Smartphone App Version**:N/A

**What did you try to achieve?**
I wanted to initiate a network heal as many z-wave devices have far to many hops.

**What did you expect as result?**
Fewer hops (hopefully)

**What was the result?**
invalid_command

**Any other remarks**
There seems to be no network heal so I had to click heal on a device in the homey developer "stugf for geeks"

**Side note**

Any idea why there are so many hops?
The lamp is <3 meters (clear air) from homey yet it hops via a wall switch (same distance) to my hallways (the wrong way some 3 meters) then to the lamp...

```
-----+
L  S |
     + ------
           X
     + ------
    H|
```

Route: H (Homey) -> S (Wall switch) -> X (hallway) -> L (Lamp)

**Comment by lubbertkramer** [comment]
Not an issue is added in RC9

**Comment by jeroenvollenbrock** [comment]
Heal got added in 1.5.6-rc.9, we're not distinguising between rc releases for version compatibility checks, so it currently shows for all rc releases.
