### ISSUE TITLE
[com.e-domotica] Physical button not registered in homey EM6550

### ISSUE THREAD

**Issue by relshout85** [athombv/homey#2194]
**Metadata**

* **Homey Version**:
1.5.3.
* **Homey Log Code**:
AD7A121545
* **Smartphone Platform**:
iOS
* **Smartphone App Version**:
not applicable (using desktop app)

**If related to a Homey App:**
e-domotica
* **Homey App Version**:
v 1.0.2
* **Homey App Log Code**:
Not available

* **Affected Devices (preferably product codes)**:
EM6550
Fabrikant ID96
Product Type ID 260
Product ID 1

**What did you try to achieve?**

Added the EM6550, now recognesed after new version of e-domotica app.
Flipping the digital switch changes the device status e.g. from off to on turns the device on (+red light on). But when flipping the physical switch on the wall plug (also turning the red light on) this is not registered in Homey, the app & dashboard still think the devices os off.

**What did you expect as result?**

I expect that Homey can also detect flipping the physical switch on the wall plug. This way it can register if the device is turned off manually

**What was the result?**

Physical button does not work.

**Any other remarks**
There is data received via z-wave:
[2018-02-01T20:37:12.912Z] Node[58]: Received application update: 0x1001252772867573
[2018-02-01T20:37:14.927Z] Node[58]: Received application update: 0x1001252772867573 
But that doesn't seem to be processed.

If you have any additional questions, please let me know!

**Comment by RobinBol** [comment]
Thanks for reporting! The E-Domotica app has been taken over by Domotica-Shop, they did not update the app yet so it still points to our repository. It would be best to contact Domotica-Shop with your issue directly.
