### ISSUE TITLE
[Bug] no lights found in a zone (voice)

### ISSUE THREAD

**Issue by jaimevisser** [athombv/homey#2197]
Homey Firmware Versie: 1.5.3
Athom Cloud ID: 582d63754d7bff777d8a5665

**What did you try to achieve?**
Turn on all lights in a zone by saying "Zet alle lichten aan in de woonkamer".

**What did you expect as result?**
All lights to turn on.

**What was the result?**
"Sorry, ik kan geen lichten vinden in de woonkamer". There are three Fibaro dimmers and a Neo Coolcam plug marked as "light" in this zone.

**Comment by jeroenvollenbrock** [comment]
Are the lights placed directly in the zone "woonkamer", or are they placed in sub-zones?

**Comment by jaimevisser** [comment]
Directly in the zone, see screenshot. The first 4 devices are lights.
![screen shot 2018-02-05 at 18 39 58](https://user-images.githubusercontent.com/3132806/35819803-090214a2-0aa4-11e8-8475-b26cfa786360.png)

**Comment by bvdbos** [comment]
You don't have a device with "woonkamer" in its name?

**Comment by jaimevisser** [comment]
CRAP. @bvdbos was right. Named my chromecast "Woonkamer". Really easy to overlook this kind of shit. Renamed the chromecast and it works now. Can be closed. PEBKAC.

**Comment by jaimevisser** [comment]
Can we turn this into a feature request to give some sort of warning if you rename a device to a zone or the other way around?

**Comment by Dijker** [comment]
something like 
![image](https://user-images.githubusercontent.com/12412734/35833617-3c6cf040-0ad2-11e8-9b2d-bb9e2f341d34.png)
(from 1.5.6-rc10)

**Comment by jaimevisser** [comment]
Ah, nice! Yes, exactly that!

**Comment by Dijker** [comment]
than you can close this Issue, will come to your  Homey => soon(tm) ;-)
