### ISSUE TITLE
KAKU - Blinds cards not visible in flow

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#220]
**What is your Homey version (Settings → System)?**
Homey 0.8.17
KAKU v1.0.13

**What did you try to achieve?**
Play with virtual blinds because I want to test a flow and buy a ASUN 650 tomorrow.
Add Device, ( /manager/zones/ )
KAKU, Blinds - Copy a remote - press button / test working - Next (like Finish)
Rename Blinds to Blinds2 Test remote with device (in Zones & devices) Works OK! Homey receives the Remote.
Create a new flow ( /manager/flow/ )

**What was the result?**
Blinds cards not visible in the devices column (scrolled to the end)
Search finds all my (renamed) devices on 1 or 2 characters, still no blinds 
Other devices (KAKU and other) are visible in the lest column in the flow editor.

**What did you expect as result?**
See the Blinds Card for each device I added to devices.

**Any other remarks**
Created a socket named BlindSocket (to test) and that shows up as expected. 

![image](https://cloud.githubusercontent.com/assets/12412734/13190562/2793a352-d75e-11e5-9cfa-e19578e32e99.png)

**Comment by Dijker** [comment]
Discussions on the Forum please 
https://forum.athom.com/discussion/comment/11148

**Comment by Dennishacq** [comment]
Thanks for reporting your issue.
The blinds don't show up because they do not have any Flowcards yet, i will add them in the next update.

**Comment by Jovink** [comment]
@Dennishacq After the app update V1.0.14 nothing is working.
I can't turn on or off the lights, or close the curtains.

**Comment by Dijker** [comment]
@Dennishacq 
Thanks for adding this flowcard in v1.0.15, 
tested it this evening and it works!

Although I have a feature request for two extra flowcards for the blinds: (for KAKU ASUN650)

I like my sunscreen approx. 7 seconds down. Default the ASUN650 switches on "ON/Down" the power for 120 seconds on. 
To stop I have to re-transmit the same signal again with a minimum of 2 seconds silence in between. 
So: 3 seconds down is possible, 2 or less NOT! (Tested that here several times. 3 seconds worked every time!) 

If I want that now I create this:
![image](https://cloud.githubusercontent.com/assets/12412734/13717303/eeb8cdb2-e7e0-11e5-836e-25962e247d9b.png)

Is it  possible for you te create two other cards (Up & Down)  for the blinds that have the option to choose for a re-transmit between 3 and approx. 119 seconds.

**Comment by Dennishacq** [comment]
@Dijker 
This feauture will be added in the future.

**Comment by Dijker** [comment]
@Dennishacq 
As the problem is fixed, 
maybe close this bug and add Timed-Blinds Up/Down KAKU Fowcard to Trello with Link to mu comment above. You will remember when Future has arrived;-)
