### ISSUE TITLE
Homey keeps rebooting by itself

### ISSUE THREAD

**Issue by btwvince** [athombv/homey#2206]
**Metadata**

* **Homey Version**: 1.5.6-rc.8
* **Homey Log Code**: FCBFEC9F62

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Reboot Homey
Get KAKU back to work
Get Somfy back to work
Tried to pairing devices again but it look like Homey isn't receiving any 433Mhz signal

**What did you expect as result?**
All of my KAKU and Somfy devices stopped responding on Sunday. From then on I tried to reboot Homey but that didn't helped. Then I tried to pull the plug for over 15min and then rebooted Homey. I can log on to it but once I think all apps are started (it takes pretty long) then all of a sudden it starts rebooting by itself and from that moment it seems Homey's in a reboot loop. 
_Edit: after more than an hour on rebooting it seems Homey has stopped rebooting and stays online. But still nothing from the 433Mhz devices seems to work_

Before all apps are started I've send a log file
I've already tried to fast disable all apps when Homey is starting but this doesn't made any difference.
I think it has something to do with the 433Mhz controller

**What was the result?**
Rebootloop

**Any other remarks**
A video of the reboot loop can be found at: https://youtu.be/KHBUnKVO5UE

**Comment by btwvince** [comment]
Seems to be solved with new version  1.5.6-rc.11
Only Milight keeps crashing constantly (bridge not responding error)

**Comment by btwvince** [comment]
Still the same, Homey keeps rebooting after update to 1.5.6-rc.11...

**Comment by nilsaw11** [comment]
hello, I also experience problems with kaku. since this week, I also suspect this release. i restart the micro controller, took a very long time, then it was possible to send two jobs and kaku no longer reacts.

1.5.6-rc.11


I have no problems with a reboot loop

**Comment by btwvince** [comment]
The KAKU and the Milight problem seems to be fixed with the rc11 but the rebooting is still there. My Homey starts rebooting a few times a day now.
New log: F132BB9A2F

**Comment by jeroenvollenbrock** [comment]
This issue is focussed on the reboot issue, please open a different issue for the kaku problem, or refer to issue #2023 

@btwvince I don't see any reboots occuring in your last log, can you update to rc13 and check if it resolves the issue?

**Comment by btwvince** [comment]
@jeroenvollenbrock the problem seems to be solved. The rebooting isn't occuring any more since rc13 and my kaku and milight problem seems to work again

**Comment by CliffBroeren** [comment]
@jeroenvollenbrock  Is the problem above already solved in 1.5.6 I have the last 2 weeks that when I do something with 433mhz the homey spontaneously reboot. I have Homey on 1.5.6

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as the original issue has been resolved. Could you please open a new issue if you experience new issues?
