### ISSUE TITLE
Z-wave configuration limited to two configuration settings

### ISSUE THREAD

**Issue by WernerHel** [athombv/homey#221]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**
Set 3 configurations in the data field. Example: 4,1,1;5,1,1;6,1,0
I can set two settings, but when I fill in the 3th, the field stay's red. So the "correct data" check is limited to two settings.
*Please include detailed steps how we can reproduce the issue*
Just try to set 3 configurations.

**What was the result?**
Not possible to save.
...

**What did you expect as result?**
That it is possible to set als many configuration as needed.
...

**Any other remarks**

...

**Comment by ocatie** [comment]
Bug in the regex. Fixed in 0.8.19
