### ISSUE TITLE
Time is hour early in Homey Firmware Versie: 1.5.6-rc.11

### ISSUE THREAD

**Issue by cautje** [athombv/homey#2211]
**Metadata**

* **Homey Version**:
Homey Firmware Versie: 1.5.6-rc.11
* **Homey Log Code**:
B5D0958C8A
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Time is wrong after update to 1.5.6-rc.11

**What did you expect as result?**

Homey time:
2018-02-08T19:56:59.366Z
Real time: 20:56

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
This has been this way from the beginning. Z = Zulu time.
if you want the real time look at date_human

**Comment by Dijker** [comment]
you could ask Homey the time, (Voice, /manager/speech-input/, Messenger etc.) it will respond with the date_human. if incorrect check the location of Homey.

**Comment by cautje** [comment]
Solved!
just change at settings the location from manual to auto or vica versa
THX!!!
