### ISSUE TITLE
System time seems incorrect after update to rc11

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#2213]
**Metadata**

* **Homey Version**: 1..5.6 rc11
* **Homey Log Code**: 00FDCB71B3
* **Smartphone Platform**: iOs
* **Smartphone App Version**: 2.0

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Wake up with a trigger

**What did you expect as result?**

That flows run on time

**What was the result?**

Flows didn't get triggered on time

**Any other remarks**

**Comment by arthurpoortman** [comment]
A reboot or changing the location settings to another location and back again solves it (workaround).

**Comment by fvhuizen** [comment]
I know that workaround but better to avoid that kind of workarounds :-)

**Comment by arthurpoortman** [comment]
Agree!

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________

**Comment by jeroenvollenbrock** [comment]
fixed in rc12
