### ISSUE TITLE
Z-wave Heal devices has no cue or to fast time out

### ISSUE THREAD

**Issue by sjaakie33** [athombv/homey#2214]
* **Homey Version**: 
1.5.6.rc11

**What did you try to achieve?**

heal battery powered device

**What did you expect as result?**

heal the device when it's online
healing has no cue 
wake up has to be done before heal and you have to be fast or it fails

**What was the result?**

healing failure
and frustration  

**Any other remarks**

**Comment by sjaakie33** [comment]
thanks for the info
except for some devices like sirens
also on other systems like Zipato there is update of routing but requires a wake up. and this is cue'd

**Comment by sjaakie33** [comment]
Just to have some more info: from https://github.com/cdjackson/HABmin/wiki/Z-Wave-Network-Healing

The heal performs the following steps.

Ping the node to see if it's awake
Update all the neighbours so that all nodes know who is around them
Update the associations so that we know which nodes need to talk to others
Update the routes between devices that have associations set
Retrieve the neighbour list so that the binding knows who's out there
Ping the node to see if it's awake
Save the device files

For mains nodes the heal function simply runs each node in turn, however for battery nodes, the heal function waits until it receives a wakeup from the device and then attempts to continue the heal. Battery nodes in zWave are difficult to manage, and the heal is not always successful. However, this should not be a big issue since battery nodes do not participate in routing.

**Comment by caseda** [comment]
Yeah, cause homey and openHab are one and the same...
Oh wait they are not! This is not the way it is currently implemented in homey, homey only asks the device to renew its neighbouring table. 

The way openhab is doing is a full network heal, which will lower your entire networks speed for some networks for several hours. (mine would take at least 4 hours)

Homey does it one device at a time, as it is **not"" necessary to do the full network every single time.
1 device can is _useally_ enough.
Also why it was not as button before in homey but "automatic" based on a timeout, as it would not lower your networks speed that much.

**Comment by sjaakie33** [comment]
maybe it's different brands but all are registered z-wave alliance products. or not.
if yes than all work the same

**Comment by caseda** [comment]
"all work the same" I wish that was the case :wink: but not everything developers implement has to be the same, just like how homey handels the device's themselves is different then what openhab does.
There are a lot of things being done different, some for the better, some not.

Even though there are specifications, there are **no hard rules** how to implement certain things, like the heal command.

**Comment by sjaakie33** [comment]
programming wish is different yes,
but hardware wish is all same except for version 300 and 500 and to be release 700
command classes are intergrated
only how to use it is up to the brand maker
or i am missing something

**Comment by caseda** [comment]
No, that is indeed not how it works, you get a chip that can send a receive data (hexadecimal).
As I can show you that I had an [issue](https://github.com/athombv/homey/issues/1480) where a command class was not parsed, you could only see the hex data.

How you handle that data is up to the developer/manufacturer, and that goes a long way, even the handeling of security tokens has to be done by the developer (only the encryption/decryption is done in the chip itself, but it still needs that token handeling), 
to even appropriately assigning the node id's (as proof, there is/was a bug that a device gets flagged "unknown" as soon as the id got to 200 until the 233 mark where it round Robins to the start, and that's not the first bug there was with node id's)

You are completely confusing the controller chip that is in homey vs what can be in for example a sensor.
As there are not just 300/500/700 there are 7 different types of 500 series chips currently, not sure about the 300 series, but that has seen multiple aswell.
And now with the upcoming 700 series, there will also have 3 different types.

**Comment by sjaakie33** [comment]
so homey has not build-in the standard command classes as specified by  Sigma Designs?
but anyhow bug stays the same

**Comment by caseda** [comment]
About 95% is parsed now in homey, the other 5% are not used by any device. But as I stated before, it is handeld different then all the other controllers

**Comment by WeeJeWel** [comment]
Nodes are marked online for 10s after waking them up.
