### ISSUE TITLE
Adding Zigbee-devices after upgrade r.11

### ISSUE THREAD

**Issue by Maxwell70** [athombv/homey#2220]
After upgrade r.11 not add Zigbee-devices (Aqara and Xiaomi).

**Comment by bvdbos** [comment]
Do you have a log? Did you install the Xiaomi-app? Can you be a bit more descriptive, where does it stop working? Do "unknown devices" appear?

**Comment by Maxwell70** [comment]
I have the plugin. And I already have a Homey in several Zigbee devices. Homey says "Device not found".

**Comment by Maxwell70** [comment]
<img width="586" alt="2018-02-11 16 47 57" src="https://user-images.githubusercontent.com/33258356/36072066-a0e80334-0f4b-11e8-9ff7-bb21accbd6ab.png">
<img width="588" alt="2018-02-11 16 49 29" src="https://user-images.githubusercontent.com/33258356/36072067-a10ea304-0f4b-11e8-9b05-2787bbb21248.png">

**Comment by jeroenvollenbrock** [comment]
Please take another good look at the [Contributing Guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue. The main goal of this issue tracker is to keep a centralized list of all uniquely known bugs so Athom can try to resolve them, and we will require a lot more information to actually help out than the information you've given so far. I'm closing this issue for now. For regular support, you can contact us at support@athom.com.
