### ISSUE TITLE
Since rc11 - Homey is constantly going offline - disconecting from the Wi-Fi network. 

### ISSUE THREAD

**Issue by VioDimi** [athombv/homey#2221]
**Metadata**

* **Homey Version**: 1.5.6.-RC11
* **Homey Log Code**:1D2D061D4A
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**
Loosing Wi-Fi connection, in my case means loosing connection with Sonoff = cant control my lights

**Comment by bvdbos** [comment]
I understand you can't control your Sonoff devices? Is Homey loosing its wifi-connection or are the Sonoff devices losing their connection? Or is the app not working?

**Comment by VioDimi** [comment]
Hi, Bas,

Homey is loosing the wi-fi connection, I restart it by unplugging it, and
after that every thing is working normal.
In the last 2 days, after RC11 it was happening at least 2 times a day.

The Sonoff devices and app is working great.

I would be great full it you would help me to set Homey back to rc10.

Thanks
Viorel


On Feb 12, 2018 09:19, "Bas van den Bosch" <notifications@github.com> wrote:

I understand you can't control your Sonoff devices? Is Homey loosing its
wifi-connection or are the Sonoff devices losing their connection? Or is
the app not working?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/homey/issues/2221#issuecomment-364853335>, or mute
the thread

**Comment by jeroenvollenbrock** [comment]
Reverting to previous release candidates is not possible. It is possible to do a complete factory reset to the stable software channel by following the steps described here: https://www.athom.com/support/KB000041/

As for the wifi connection, it is a bit unclear to me what makes you conclude the Wifi connection is gone. Can you please take another good look at the [Contributing Guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and extend your bug report a bit with traces or more information about the problem?

**Comment by VioDimi** [comment]
Hi Jeroen,

This is absolutely not possible.
It is a full automated house, and I am 2000 km away. My wife is there with
my kid's. Reset Homey like this means repairing all the devices = lamps,
thermostat, switches.... Ist 2 days work with a lot of hardware.

I cold not believe that you are not abel to upload an older firmware on
Homey. We can make an appointment to assist you hardware.

Please let me know.

Thanks

**Comment by VioDimi** [comment]
P.s. it seems that it is a total system failure, the z-wave thermostat are
also in error mode when Homey is offline.
After restarting it, everything is running normal for a while.

On Feb 12, 2018 20:08, "Jeroen Vollenbrock" <notifications@github.com>
wrote:

Reverting to previous release candidates is not possible. It is possible to
do a complete factory reset to the stable software channel by following the
steps described here: https://www.athom.com/support/KB000041/

As for the wifi connection, it is a bit unclear to me what makes you
conclude the Wifi connection is gone. Can you please take another good look
at the Contributing Guidelines
<https://github.com/athombv/homey/blob/master/CONTRIBUTING.md> and extend
your bug report a bit with traces or more information about the problem?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/homey/issues/2221#issuecomment-365028816>, or mute
the thread

**Comment by jeroenvollenbrock** [comment]
There is a clear warning when you enable experimental updates that states reverting to stable is impossible without a settings-loss, so i am not able to assist you with that. Could you let me know if this problem is still present in 1.5.6 (non-rc)?

**Comment by VioDimi** [comment]
Hi,

Know everything is working good, after 1.5.6. without RC and a factory
reset.

So the issue is gone.

Thanks for the support!



On Feb 26, 2018 15:29, "Jeroen Vollenbrock" <notifications@github.com>
wrote:

There is a clear warning when you enable experimental updates that states
reverting to stable is impossible without a settings-loss, so i am not able
to assist you with that. Could you let me know if this problem is still
present in 1.5.6 (non-rc)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/athombv/homey/issues/2221#issuecomment-368520747>, or mute
the thread
