### ISSUE TITLE
[nl.alecto] sa 33 koppelt niet met homey

### ISSUE THREAD

**Issue by aldotromp** [athombv/homey#2224]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by aldotromp** [comment]
Ik heb vandaag de Sa 33 gekocht om te koppelen aan de homey,
De Homey ziet ze niet , wat doe ik fout

**Comment by jdh009** [comment]
Tried to connect six SA-33 to my Homey but could not get it working. Restart of the homey (latest stable version firmware), the app (also reinstalled), PTP Homey and restart of the Microcontroller (stuff for geeks) did not work. Is there something else I can do to connect them?

**Comment by aldotromp** [comment]
Ondanks dat de SA-33 rookmelder vermeld staat dat dit product samen zou moeten werken met de Homey,
Is het mij ook niet gelukt om te koppelen.

Ik heb de moet opgegeven , hoop ooit dat de app ontwerper er nog eens goed naar kijkt

Aldo
