### ISSUE TITLE
Date() returns Zulu time in 1.5.6-rc.11

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#2226]
**Metadata**

* **Homey Version**: 1.5.6-rc.11
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:** Heimdall, probably others to that use _Date()_
* **Homey App Version**: any
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**: N/A

**What did you try to achieve?**
In Heimdall _Date()_ is used as the timestamp for writing log lines to the history, it used to return the _date_human_ but it seems that in rc.11 that has been changed to the system _date_ (Zulu)

**What did you expect as result?**
The _date_human_ returned as it was in previous versions. There is no changelog indicating this change was made in the software.

**What was the result?**
Logs are 1 hour off, user reporting a bug on the Heimdall github: https://github.com/daneedk/com.uc.heimdall/issues/11

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Fixed in rc13

**Comment by daneedk** [comment]
Great, thanks!
