### ISSUE TITLE
Battery status with two fibaro smoke detectors

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2229]
* **Homey Version**: 1.5.6 RC11
* **Homey Log Code**: NA
* **Smartphone Platform**: NA
* **Smartphone App Version**: NA

**What did you try to achieve?**
I checked the battery status, these devices are identical and installed at exactly the same time. 
One stated 5 % in the living room almost next to homey, and the other one states 100 % in the kitchen more often used but installed at exactly the same day ?

How is this possible ?

**What did you expect as result?**
To be the battery status to be around the same percentage !

**What was the result?**
One almost empty one full !
![afbeelding](https://user-images.githubusercontent.com/23163409/36172617-b912b2c6-1106-11e8-87cc-b33d13ea0cf2.png)

**Any other remarks**
The livingroom was on interval 600 and the kitchen on 1 ? So I am completely flabergasted
![afbeelding](https://user-images.githubusercontent.com/23163409/36172574-9d246a96-1106-11e8-950d-8d58b224a56d.png)

**Comment by Inversion-NL** [comment]
Defective battery?
Maybe change the 'empty' one for a new one and see if happens again?

**Comment by chrisboer** [comment]
Smoke detector is broken
