### ISSUE TITLE
Flow editor: token of trigger card can used within same trigger card

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#223]
Version: 0.8.17

**What did you try to achieve?**
Find a bug before MarcoF does.

*Please include detailed steps how we can reproduce the issue*
Drag a token to an input field on its own card

**What was the result?**
Its possible.
![image](https://cloud.githubusercontent.com/assets/15232724/13197275/2df3232c-d7e9-11e5-8b41-4ad5bbb85532.png)

**What did you expect as result?**
Token only droppable in fields of cards that will be executed after the card where the token comes from. With the reported way you create circular reasoning.

**Comment by Dijker** [comment]
LOL, think they did it to create the if-never workflow ;-)

**Comment by freemann** [comment]
What did in not find?

**Comment by WeeJeWel** [comment]
While this is unlogical for the Microphone trigger, it can be useful in some scenarios :)
