### ISSUE TITLE
[com.lg.webos] Describe your issue here

### ISSUE THREAD

**Issue by aniballopez** [athombv/homey#2230]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
This is fairly non-descriptive? @aniballopez : could you fill in a title and answer the requested data?

**Comment by jeroenvollenbrock** [comment]
Please open a new issue and follow the contributing guidelines.
