### ISSUE TITLE
FEATURE REQUEST: add nest as a datasource

### ISSUE THREAD

**Issue by reneknuvers** [athombv/homey#2234]
* **Homey Version**: 1.5.3
* **Homey Log Code**: n.a.
* **Smartphone Platform**: n.a. 
* **Smartphone App Version**: n.a.

**What did you try to achieve?**
Use data from Nest thermostat (room temperature, relative humidity) in an "insights" graph

**What did you expect as result?**
Nest data available for selection in the left-hand list of data sources

**What was the result?**
None of the Nest variables (and non of the Nest devices) are listed in de data source column. 

**Any other remarks**
Analysing outside temperature, actual and set room temperature may help reducing costs for heating and predicting savings when installing for example a heat pump or new boiler system. The data is available as tags to Homey, so most likely logging it for later use is also possible.

**Comment by reneknuvers** [comment]
Okay, I'll dive into the tags to see what I can accomplish. I think I should make a flow that triggers every x minutes to store a value?

Maybe some 'howto' or tutorial would be helpful to many new users.

**Comment by jeroenvollenbrock** [comment]
This is not allowed by the Nest Partner Contract
