### ISSUE TITLE
FEATURE REQUEST: add mobile app buttons as flow triggers

### ISSUE THREAD

**Issue by reneknuvers** [athombv/homey#2235]
* **Homey Version**: 1.5.3
* **Homey Log Code**: n.a.
* **Smartphone Platform**: iOS (but feature is relevant to all platforms)
* **Smartphone App Version**: 1.3.3

**What did you try to achieve?**
As a user I want to be able to trigger flows by ticking a button in the mobile app. Alternatively I would want to trigger the flow with a spoken keyword. The latter seems possible already.

**What did you expect as result?**
A flow should run on the users command.

**What was the result?**
Functionality to trigger flows now is either induced by indirect action of the user (i.e. arriving home), spoken word from the user, a sensor trigger (i.e. user presses a zwave-switch button), or from datasources outside of the circle of influence of the user.

**Any other remarks**
Domoticz has a simple implementation of these kind of triggers. The app could also spawn a widget for use in the 'swipe right' menu of the home screen of iOS.

**Comment by bvdbos** [comment]
Homey is not Domoticz :) But there's a solution for you:
https://apps.athom.com/app/com.arjankranenburg.virtual

**Comment by reneknuvers** [comment]
Thank you. I found out that "better logic" also offers some kind of trigger functionality. Seems beta though. I'll try both options. Hope this will some day be 'core'. I know that some people prefer the OpenHAB angle on the user interface and the way a dashboard can be compiled. Hopefully one day I can plaster my old iPad 1 on the wall and control my home through Homey! ;-)

**Comment by bvdbos** [comment]
Then you might want to look at https://homeyda.sh

**Comment by jeroenvollenbrock** [comment]
Our new smartphone app contains flow trigger functionality.
