### ISSUE TITLE
Z-Wave and 433 is not working - RC13

### ISSUE THREAD

**Issue by VioDimi** [athombv/homey#2236]
**Metadata**

* **Homey Version**:1.5.6-rc.13
* **Homey Log Code**:
Fibaro 88872dd4-20ae-4ce3-956f-d955665766d2
POPP  cf6280b3-655f-48d4-9c3e-2998282b2c3c
Danffos  cf6280b3-655f-48d4-9c3e-2998282b2c3c
Smartwares 6877b3d1-9b01-4f3d-88b2-7028a2b26be0
Philio e5a73a53-a180-42da-af9a-a77228fdd9a1

* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**: AAA52D5E21
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

After Update to RC13The Zigbee Network and the WiFi is working well.

The Z-Wave Network is blocked an give this Message:

Error: stream.push() after EOF
Try restarting Homey.

The POPP and Danffos Thermostats are mentioned unreachebel, also the Fibaro roller shutter 2
The Philio sensors are just gone....
After Restarting it Yesterday, for the same message, Homey was completely blocked, therefor I do not risk another restart till you tell me that an Update is Ready.

The 433 Network is sending messages but not receiving.

I could test all these things because:

I have lights with Smartwares 433 switches and I can turn them on/off remotely.
I have lights with Sonoff WiFi switches and I can turn them on/off remotely and from the Zigbee Taster.

The 433 Smartwares Taster turn on/off the direct paired lights, but not the lights commanded trough Homey. 

So Homey is Sending 433, but not received (Battery failure is excluded since the same taster is commanding the direct paired light but not the  others)

**Comment by bvdbos** [comment]
Pulling the plug for over ten minutes would be a first thing to try. Could you report whether that changes things?

**Comment by VioDimi** [comment]
I have disconnected Homey for more then 10 minutes.

Know it's Offline!

**Comment by VioDimi** [comment]
Know Homey is back online and working good.

Will constantly update you.

**Comment by WeeJeWel** [comment]
Please let me know if this issue persists.
