### ISSUE TITLE
[BUG:] After update 1.5.6 Philio SP05 not detecting any more

### ISSUE THREAD

**Issue by canedje** [athombv/homey#2238]
**Metadata**

* **Homey Version**: 1.5.6

**If related to a Homey App:**
* **Homey App Version**: Philio v0.0.22
* **Homey App Log Code**: ? How to generate?
* **Affected Devices (preferably product codes)**: PSP05

**What did you try to achieve?**

A philio PSP05 outsite sensor to detect movement and connect to Homey to activate flows

**What did you expect as result?**

A flow started at Homey activated by the Philio sensor to switch on the light

**What was the result?**

Homey is not detecting the movement (checked at devices), so no flow wil start

**Any other remarks**
This worked fine until version 1.5.6-rc11
I unpaired and paired the philio sensor agian under 1.5.6.
Herefor I did bring in the sensor in the neighbourhood off Homey It paired (more difficult to pair in 1.5.6 then before also with other devices, needed severall attemps)
Testing with Homey on the "pair location" Homey is detecting movement and activating the flows.
Bring it outsite on the using spot as before, Homey is not activated by the sensor anymore. There is a fibaro double switch in the neigbourhood (3 meters) so  there is a meshnetwork available. (It did alway work fine before)

**_Some toughts in relation with trouble mentioned above:_**
I also have trouble with actual detecting the second switch of a fibaro double Switch, by switching manually. (see: https://github.com/athombv/homey/issues/2118) Switch one off all fibaro double switches (I have 5 of them) are always just working fine, the second switch not always. I do see a relation with the Philio sensor, see comment below

I did pair this new fibaro switch by bringing Homey in the neighborhood off the switch. After pairing and not moving Homey . Testing the second switch manualy did work **fine** at that moment and was detected by Homey.
An older switch on an other spot off the same type did not work any more with the moved Homey switch. (It worked fine before moving Homey)
After replacing Homey to his usual spot (with a PTP). The second switch off the latest paired fibaro switch suddenly didn't work anymore and is not detected by Homey, but the earlier paired switch did work again??? Which didn't work when pairing the new switch and Homey on the other location!

So I have the feeling that the used meshnetworkpath off the devices if they change, by moving Homey (or moving the device itself to an other location) is effecting the devices to work yes or no.
Because if I bring in the Philio sensor to the location I paired it, it is working normally again.
Do I bring it outsite to its use location( an other messpath used). It is working not anymore.

Edit:

To be sure about my theory above I did move Homey once more (with a PtP) to the location where I did pair the fibaro switch before, as mentioned above. Then the second switch of the fibaro switch is working again and detected by Homey, If I replace Homey to its usual loaction not. So I can reproduce the error.

**Comment by canedje** [comment]
I did an pair and unpair bringing Homey to the garage and pair using the philio app instead of the standard z-wave button.
After returning Homey to his usual spot.
The sensor is working and activating flows

**Comment by Dijker** [comment]
If this is fixed for you you can close with the button  below :-)

**Comment by canedje** [comment]
It is not fixed. The problem is still there.
I only did found a kind of work around to get it working.

**Comment by bvdbos** [comment]
It;s generally advised to take Homey to the spot where a sensor is installed for including, then the mesh gets more reliable. For the rest it seems like the Philio won't rebuild it's mesh so seems a device-issue more then a Homey-issue.

**Comment by canedje** [comment]
It did working fine at versions before.
So for me it is hard to understand the origin of the problem.
For the Fibaro double switch I did also bring in Homey. That device still is not working for S2.
I agree it looks like it has something to do with building up the meshnetwork.
I do not believe (yet) it is the device.
Is there a method to test this?

**Comment by canedje** [comment]
Tonight the sensor is not working anymore.
So it only worked for one night

**Comment by jeroenvollenbrock** [comment]
Closed to combine under #2267
