### ISSUE TITLE
Can't Change name on Zone´s after last update. 

### ISSUE THREAD

**Issue by Pehbor** [athombv/homey#2239]
**Metadata**

* **Homey Version**: Version: 1.5.6
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?** Change name of a zone, 

**What did you expect as result?** that the name would change

**What was the result?** the name dint change. 

**Any other remarks** When setting up the Homey I made changes to Zone names without any faults. Now when I change a name or an Icon and click "somewhere else" to auto save it. Going to another page and back and the zone is back to its original name. This occurred after the last update. I have tried to reboot it with out any success.

**Comment by canedje** [comment]
Idem here

**Comment by pakacom** [comment]
I can confirm this to.

**Comment by Dijker** [comment]
I guess somewhere they decided to return the Zones hierarchical (sub-zones as children of the parent object.) with the ?recursive=1 
Don't know if they did that before or it was a flat array of all zones and subzones!  (now ?recursive=0 )

https://developer.athom.com/docs/api/HomeyAPI.ManagerZones.Zone.html

![image](https://user-images.githubusercontent.com/12412734/36281897-9f7c2f96-129f-11e8-9aa6-1786d51dd762.png)

Whatever I try i get Error: recursive_zone in HomeyScript  / {status: 500, result: "recursive_zone"} in the Chrome Console.
Even for New Zones.....

**Comment by WeeJeWel** [comment]
Thanks for reporting, this should be fixed in the next version.

**Comment by bvdbos** [comment]
confirmed fixed for 1.5.7
