### ISSUE TITLE
Media controller not working when playing music

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#224]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Stop music from playing

**What was the result?**

Both the android app and http://192.168.1.xxx/manager/media/ did not respond, so I was unable to pause the music. In the end, I had to pull the power cable 

**What did you expect as result?**

To load the media manager.

**Any other remarks**

My girlfriend though it was hilarious as I tried frantically to stop the unexpected rave party ^.^

**Comment by WeeJeWel** [comment]
Closing this issue because Media has been removed since 0.10, to prepare for it's comeback.
