### ISSUE TITLE
Roller shutter DC doesnt seem to be supported?

### ISSUE THREAD

**Issue by krillehbg** [athombv/homey#2240]
Roller shutter DC doesnt seem to be supported?

Do you have any timeplan for this?

Thanks!

**Comment by bvdbos** [comment]
Do you have a brand and link etc?

**Comment by krillehbg** [comment]
Sorry, my mistake
I thougt i posted to Qubino project.

It's a Qubino Roller Shutter (ZMNHDD1)

Regards Kristian

**Comment by alexraberg** [comment]
Any news on this one @RobinBol @jeroenvollenbrock ?! Is there a workaround until official support is added? I’ve tried to add as a generic device, but with limited success.

**Comment by RobinBol** [comment]
Thanks for reporting. The Qubino Roller Shutter DC has been added to the beta version of the Qubino app.
