### ISSUE TITLE
Homey version missing after 1.5.6 RC13 (I expect)

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2242]
* **Homey Version**: 1.5.6 rc13 ?
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
I don't see the RC version anymore in the last update so I expect rc13 ?
![afbeelding](https://user-images.githubusercontent.com/23163409/36308147-ab9ea0b2-131f-11e8-838c-19485a199c39.png)

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by swttt** [comment]
auto updates enabled?

**Comment by chrisboer** [comment]
Never mind this is the 1.5.6 version ;-)
