### ISSUE TITLE
Zwave devices not responding, motion alarm always on, etc...

### ISSUE THREAD

**Issue by gajdur** [athombv/homey#2243]
Homey Version: 1.5.6 exp.
Log: 1119A932B3
Android
2.0 Preview

**What did you try to achieve?**
Almost all my zwave devices are unreachable, not all together and not always the same.
Fibaro Relais not responding, fibaro motion sensor with alarm always on, fibaro door sensors with tamper or not triggering/responding, neo coolcam motion not triggering and draining one battery per day, couple fibaro roller shutter 2 with venetians not going horisontal anymore when 2% dim.

**What did you expect as result?**
Nothing from the above

**What was the result?**
PTP not helping, must deactivate heimdall app, floor heating not working while relais and sensors not working.

**Any other remarks**
not atm

**Comment by pakacom** [comment]
I have the same problem as you have.
My zigbee motion sensors alarm are always on.
I must deactivate heimdall app also.
#2231

**Comment by bvdbos** [comment]
Is this related to the Heimdall-app? If not : could you look at https://developer.athom.com/tools and see what happens with your zwave-devices (are there many tx-errors, non-working routes etc). Could you heal your powered devices? What happens if you wake up a device (push button once probably...)

**Comment by gajdur** [comment]
Heimdall is working, is zwave or 1.5.6 in general Problem. Reseting and readding not helping. Heal not working. Also with devices at 30cm from Homey.

**Comment by TonD83** [comment]
I have what appears to be the same or similar problem(s). Heal is not working for any nodes. Not even those very close and in line of sight. Adding NEO Coolcam plugs gives a lot of missing device classes, metering is not working only on/off. Re-adding a couple of times gives different results every time.

**Comment by jeroenvollenbrock** [comment]
Closed to combine under #2267
