### ISSUE TITLE
SDK2: Signal - mismatch between docs & implementation

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#2244]
**Metadata**

* **Homey Version**: 1.5.6-rc.13
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Register a new signal via SDK2.

**What did you expect as result?**

According to the docs (https://developer.athom.com/docs/apps/Signal.html) a new signal can be created via: `new Homey.Signal(frequency, id)`. However, using the code `new Signal('433', 'SomeName')` threw an error (signal not defined).

It turned out that the arguments are reversed in the implementation. Using `new Signal('SomeName', '433')` does work.

**What was the result?**

**Any other remarks**
Probably easiest to update the docs.

**Comment by WeeJeWel** [comment]
Thank you, fixed.
