### ISSUE TITLE
[Request] Facebook Messenger Speech control

### ISSUE THREAD

**Issue by orecus** [athombv/homey#2253]
It would be great if you could control the Messenger functionality a bit more within flows, and distinguish if the speech command came from Messenger or if it was spoken to Homey.

Additionally also be able to control if a speech action should be spoken out by Homey, or returned in text in the Messenger bot.

An Example
- WHEN Card
  - [Messenger] Something was said... (Same options/event as [Microphone] but only triggered from the Messenger message)
- Then Card
  - [Voice] Same as today, but always spoken out by Homey even if triggered from an Messenger event
  - [Messenger] Text Response,Tags (Returned by the Bot in Messenger)

This would be perfect as a simple broadcast on-the-go through Homey (And playfully annoy your SO).

**Comment by WeeJeWel** [comment]
This is functionality that's a little bit too complicated to add, but as a workaround you could add a virtual device (e.g. a KlikAanKlikUit of from the Virtual Devices app), and trigger a new Flow. This will break the 'state', i.e. the origin of the speech. By default, Homey will always respond using the built-in speaker.

**Comment by orecus** [comment]
@WeeJeWel That's a shame, but I understand the complexity of the problem. 

Being able to distinguish between Speech and a message to the Messenger Bot would be pretty awesome though, even if we can't route the reply in the way I mentioned above. Would that be something that could be considered for a future feature?

**Comment by WeeJeWel** [comment]
Maybe we will add a token to the speech with the 'Origin' or so. I'll think about it!

**Comment by bvdbos** [comment]
see #1305 for related issue, also don't forget #613 then...
