### ISSUE TITLE
Incorrect time, 1 hour to late

### ISSUE THREAD

**Issue by Ruudje007** [athombv/homey#2257]
**Metadata**

* **Homey Version**:
1.5.6

* **Homey Log Code**:
2F230707D5

**What did you try to achieve?**
Get the right time

**What did you expect as result?**
The right time

**What was the result?**
1 hour later

**Any other remarks**
See print screens, i was testing how many times there was a false motion alarm. as you can see quite a lot...

![schermafbeelding 2018-02-23 om 11 50 45](https://user-images.githubusercontent.com/36369009/36591672-0a1273c6-1893-11e8-9e8e-4d502f904993.png)
<img width="1440" alt="schermafbeelding 2018-02-23 om 11 53 15" src="https://user-images.githubusercontent.com/36369009/36591673-0a3b3f72-1893-11e8-80a6-5198e1e4b386.png">
![img_2757](https://user-images.githubusercontent.com/36369009/36591759-4bd9c3b8-1893-11e8-9f5f-9da274a4aaf3.PNG)

**Comment by bvdbos** [comment]
should be fixed in #2213

**Comment by WeeJeWel** [comment]
Your timezone is UTC, and I suppose you live in The Netherlands (+1 hour). Please set your location correctly and the time will adjust after a reboot.

**Comment by Ruudje007** [comment]
@WeeJeWel 
If that was the case i could fix that one by my self........ I have setup this correctly... 

I changed this setting from Manually to automatic, rebooted homey. After the reboot it worked. 

A normal reboot without changing any thing did not solve the issue
