### ISSUE TITLE
On tablet floweditor does not restore content after keybord input

### ISSUE THREAD

**Issue by rboeije1** [athombv/homey#226]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

On tablet (Samsung GT-P5210) when you open the flow editor in chrome and drag microphone in, you can type a text, so the on screen keyboard pops up. Type in some text. 

**What was the result?**
When you are finished, the keyboard disapears, but the list of devices in the left colum is not refreshed. So all items that were behind the keyboard are gone.

**What did you expect as result?**
To have the complete list.

**Any other remarks**

You can still scroll in the top part and as such get the item visible in the top part of the screen.
But even if you succeed, you are not able to drag the label to the input field of the action. (The label flips a bit, but does not detach.) I guess that is anothe bug.

**Comment by Dijker** [comment]
I confirm this bug on a Samsung SM-T710 Tablet.

**Comment by WeeJeWel** [comment]
Thanks for mentioning. However tablets are not supported (as of now), so I am going to close this issue.
