### ISSUE TITLE
[com.athom.homeyscript] Creating a new Zone with custom icon returns a zone with Default icon

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#2260]
**Metadata**

* **Homey Version**: 1.5.6
* **Homey Log Code**: na
* **Smartphone Platform**: na 
* **Smartphone App Version**: na 

**If related to a Homey App:** HomeyScript
* **Homey App Version**: 1.0.4
* **Homey App Log Code**: na
* **Affected Devices (preferably product codes)**: na

**What did you try to achieve?**
Create a new Zone with custom Icon

```
var newZone  = {};
    newZone.name = 'My Awesome Garden';
    newZone.parent = 'b840a982-a3a7-4513-9d96-902d81128f5c';
    newZone.icon = 'garden'
log (JSON.stringify(newZone));
// {"name":"My123456Zone2","parent":"b840a982-a3a7-4513-9d96-902d81128f5c","icon":"garden"}
var result  =  await Homey.zones.createZone( {zone: newZone} )
log (result )
{ id: '7986cce1-6500-4c72-838b-93e5aef643e1',
  name: 'My Awesome Garden',
  icon: 'default',
  index: 4,
  parent: 'b840a982-a3a7-4513-9d96-902d81128f5c' }
```
Tested some variants by specifying or copying .... ;-)

**What did you expect as result?**
a Zone with a custom icon

**What was the result?**
a Zone with the default icon

**Any other remarks**
maybe related to #2239 but please test it before you release ;-)

**Comment by WeeJeWel** [comment]
Correct, the icon can only be changed afterwards.

**Comment by Dijker** [comment]
But in the 1.5.7 creating with a pre-defined icon is possible ;-) 
Thanks for the new Feature!

**Comment by WeeJeWel** [comment]
😘
