### ISSUE TITLE
Sonos / Spotify

### ISSUE THREAD

**Issue by fkooten** [athombv/homey#2262]
After installing Sonos and Spotify for Sonos (both Beta) I logged in on my Spotify account as required and tried to play a Spotify playlist on one of my Sonos speakers and got the following error message
"Error: media.Got status 500 when invoking /MediaRenderer/AVTransport/Control"

My Homey version is 1.5.6

**Comment by fvanbeenen** [comment]
Same here... Is something wrong? or did I?

**Comment by bvdbos** [comment]
for starters: Does playing Spotify to others devices work? And does playing other music to Sonos work?

**Comment by fkooten** [comment]
Bas

Both Sonos and Spotify work fine

Met een vriendelijke groet



Fred van Kooten

**Comment by fvanbeenen** [comment]
Okai.. Pleas tel me what I do wrong then. It does not play the titles or it
random plays 1 second (without sound) and recurring error loop : "media:
Failed to open audio output"


2018-02-25 13:39 GMT+01:00 fkooten <notifications@github.com>:

**Comment by bvdbos** [comment]
For "Failed to open output" see #2263 . Reboot worked for me.

**Comment by fvanbeenen** [comment]
Reboot Homey... I go and try. Thanks

2018-02-25 15:10 GMT+01:00 Bas van den Bosch <notifications@github.com>:

**Comment by fvanbeenen** [comment]
What does this mean?



2018-02-25 15:13 GMT+01:00 Freek B <fvanbeenen@gmail.com>:

**Comment by fvanbeenen** [comment]
Hoi Bas. 
Ik denk zo dat je Nederlander bent? Heb je dit bericht vaker gehoord? Of komt dat alleen bij mij voor??


Verstuurd vanaf mijn iPhone

**Comment by bvdbos** [comment]
On github we use English as a large part of Homey-users doesn't speak dutch... It seems this is an issue with the node-sonos-http-api. If you want to debug, please start the sonos-app and the spotify-app from the commandline and see what leads to this error...
https://www.google.nl/search?q=%22Error%3A+Got+status+500+when+invoking+%2FMediaRenderer%2FAVTransport%2FControl%22

**Comment by fvanbeenen** [comment]
Oké. Thanks. How can I start the sonos-app and the spotify-app from the commandline? It may be a stupid question? 

Verstuurd vanaf mijn iPhone

> Op 25 feb. 2018 om 18:02 heeft Bas van den Bosch <notifications@github.com> het volgende geschreven:
> 
> start the sonos-app and the spotify-app from the commandline

**Comment by fkooten** [comment]
Reboot Homey did not the trock. Same error. When I go to music I can see the Spotifiy playlists. After selecting a playlist and a sonos speaker the playbutton remains gray-out.

**Comment by chrisboer** [comment]
Any update on this ? because I also get this issue when playing Radio Streams  
media.Got status 500 when invoking /MediaRenderer/AVTransport/Control

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
