### ISSUE TITLE
[APPSTORE] Cancel submission does not work

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#2265]
**Metadata**

* **Homey Version**: N/A
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:** Heimdall
* **Homey App Version**: 1.0.3
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**: N/A

**What did you try to achieve?**
I tried to promote the published Beta 1.0.2 to stable while a Beta 1.0.3 was waiting for approval.
Steps taken:

Approved 1.0.2 as Beta
Submitted 1.0.3 to Beta
Promoted 1.0.2 to stable

After the last step Heimdall was no longer visible in the categories (Recently Updated, Tools, Security etc.) and can not be found using search. The versions show this:
![image](https://user-images.githubusercontent.com/16610696/36659991-b5acd3f8-1ad6-11e8-9164-7a94a38628c4.png)
Which is incorrect as I promoted 1.0.2 to stable but somehow the (waiting for approval) 1.0.3 was promoted instead.

Next I tried to cancel the submission of 1.0.3:
![image](https://user-images.githubusercontent.com/16610696/36660319-0ea5200e-1ad8-11e8-9c64-3dbc180fe435.png)
 to revert back to 1.0.2 but this does not work as the version still shows:

![image](https://user-images.githubusercontent.com/16610696/36660075-08edc888-1ad7-11e8-9a9f-10588767de98.png)

**What did you expect as result?**
First of all I expected to be able to Promote the approved Beta (1.0.2) to stable while a separate submission (Beta 1.0.3) was active, but that not being possible isn't a big issue to me. The fact that however that the unapproved Beta (1.0.3) was promoted instead is an issue.
Lastly not being able to cancel the submission of Beta 1.0.3 is also not expected, this way I can not correct the problem myself to get my app easily found again and I need your help to get it fixed.

**What was the result?**
Beta 1.0.2 promoted to Stable
Beta 1.0.3 stay in the normal submission - approval - publish path.

**Any other remarks**
Can you please either remove the submission of Beta 1.0.3 so all versions (Alpha, Beta and Stable) wil revert back to 1.0.2 or approve Beta 1.0.3 so I can publish that version.

**Comment by joachimroeleveld** [comment]
This was a bug that occurred in your upgrade path. I reverted your app to version 1.0.2. It will be fixed by permitting upgrading a channel if an unpublished revision for that channel exists. Does this resolve your issues?

**Comment by daneedk** [comment]
Yes, the app can be found again by searching or browsing the different categories, thanks.
I'll resubmit the new 1.0.3 to the appstore.

**Comment by joachimroeleveld** [comment]
👍
