### ISSUE TITLE
Homey is 1 hour too late

### ISSUE THREAD

**Issue by Vortjong** [athombv/homey#2268]
**Metadata**

* **Homey Version**:
1.5.6, experimental updates enabled
* **Homey Log Code**:
NA
* **Smartphone Platform**:
NA
* **Smartphone App Version**:
NA

**If related to a Homey App:**
* **Homey App Version**:
NA
* **Homey App Log Code**:
NA
* **Affected Devices (preferably product codes)**:
NA

**What did you try to achieve?**

Trigger a rule at 23:30

**What did you expect as result?**

The rule triggered at 23:30

**What was the result?**

The rule trigger at 0:30

**Any other remarks**
Reboot did solve the issue

**Comment by Bagaboo** [comment]
+1 on this issue. Except it was supposed to go off at 20:00, but it went off at 21:00.  

1.5.6, experimental updates enabled

Will try and reboot and see if the same thing happens tomorrow.

**Comment by Vortjong** [comment]
Oeps, you’re richt, I have the time confused. I have updated the ticket to make it correct. Also when asking homey “hoe laat is het” at 21:15, the answer is 20:15

**Comment by jeroenvollenbrock** [comment]
Can you check your timezone at settings->system->stuff for geeks->timezone?

**Comment by Bagaboo** [comment]
It shows the correct timezone: Europe/Stockholm on manual location mode.

**Comment by Vortjong** [comment]
For me :
timezone : Etc/UTC

**Comment by jeroenvollenbrock** [comment]
@Vortjong @Bagaboo Can you create a homey log ID? (settings->system->send log)

**Comment by Bagaboo** [comment]
Yes mate, here is my Log ID: F63771ED0F

**Comment by Vortjong** [comment]
Sure, id is : 7176AED082

**Comment by Bagaboo** [comment]
Today, it went off at the right time. So, the restart i did yesterday helped, which conforms with @Vortjong experience.

**Comment by Vortjong** [comment]
Ehhh, i was very tired when I created the issue, sorry. A reboot did NOT help for me, as homey is still on hour wrong.

**Comment by Bagaboo** [comment]
Oh ok. Got it. Well, something helped. I will try creating new flows and see if there is a difference between pre-reboot flows and post-reboot flows.

**Comment by json81** [comment]
I had the same issue. I went to settings -> location and moved my location to a different position on the map and then back. Now my time is correct again.

**Comment by Bagaboo** [comment]
@json81 Yes, for me a reboot helped apparently. It is a bug nonetheless and is quite annoying for new owners.

**Comment by jeroenvollenbrock** [comment]
Closing to combine this one under #2375
