### ISSUE TITLE
Homey interfering with Sonos speakers and controller/App

### ISSUE THREAD

**Issue by RT744** [athombv/homey#2277]
**Metadata**

* **Homey Version**: 1.5.7
* **Homey Log Code**: 
* **Smartphone Platform**: 
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: Sonos 3.0.1
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: sonos speakers (3xPlay1) and IPad-App from Sonos

**What did you try to achieve?**

Control Sonos speakers with the IPad-App from Sonos (Not the Homey-Sonos-App)

**What did you expect as result?**

**What was the result?**

For a couple of days the IPad-App from Sonos does not work, though the App was not updated recently. The Play/Stop-button in the App remains grey/inactive, volume control lags some seconds behind, boxes can only be switched off with volume control, speakers turn on again by themselves after beeing turned off with the on/off buttons of the speakers. The on/off buttons are not  working most of the time. I asked the Sonos Support for help. They told me, the problem is not the speakers. They say the Sonos log points to my networks IP of Homey (all IPs are static), „all transport and rendering controls via UPnP are blocked by this IP and It keeps interfering with the speakers“.  Therefore I tried first to disable only the Homey-Sonos-App and leave Homey turned on. The problems renained. After turning Homey off the problems with speakers and IPad-Sonos-App were gone.

**Any other remarks**

**Comment by cbho** [comment]
Can confirm this behaviour - have been strugling with the connection to my Sonos units - after disabling Homey's Sonos App (SDK2) and rebooting Homey the problem disappears...

**Comment by JPe2** [comment]
Also having problems when on Android, when Homey has started to play a radio station on a speaker, and after that, an Android app tries to change the station, the command seems to fail and the speaker plays a repeated array of tones, indicating the radio-station is not found.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
