### ISSUE TITLE
Add option to manually fill KaKu code when adding a KaKu device

### ISSUE THREAD

**Issue by BDV77** [athombv/homey#228]
Homey version 0.8.17

Please add the option to manually add the KaKu code when adding a device.
I have several Kaku devices build into the wall sockets which I control by my HomeWizard.
There I have manually added the switching codes.

I do not have a remote whit the specific codes, so only option now would be to open up all wall sockets and trigger the device codes :(.

P.S. i also tried to teach the on/off code by sending it through the Homewizard but with no succes.
This should have worked as an intermediate solution since this sends a similar signal as a KaKu remote

This issue is pretty urgent for me since this is blocking for me to integrate all devices into the Homey device.

**Comment by Dijker** [comment]
What type of devices do you have? 
are they the new or older type KAKU? 
http://www.klikaanklikuit.nl/advies/productwijzer/ 

Learning with Sending the codes from the Homewizard should work afaik.
If Homey could receive the signal (not to far away) and devices are already supported it probably works.  Also don't place the Homewizard and Homey side by side, place them at a minimum of 50 cm apart because of interference.

**Comment by BDV77** [comment]
Type of device: KaKu AWS-3500 Mini inbouw schakelaar stopcontact

After fiddling around for a while I discovered that the second channel of my remote has the linked code to one of the build in switched outlets and I was able to add the device by teaching it with the remote.

**Comment by Dennishacq** [comment]
Hi @BDV77 
Thank you for your suggestion,
I will add this function in the future.

**Comment by BasKiers** [comment]
Since I am assigned to the KaKu apps and the UI for such a feature would create more issues than it will solve (in my opinion) I will not fix this issue. 

It is possible to copy the signal from your homewizard during pairing (in the same way you can copy a remote) which should be sufficient.

**Comment by nattlip** [comment]
i use @BasKiers method with rfxcom and homeseer it works.

@BasKiers why istn homeeasy devices mentioned in klika app ? is it right that in the earlier versions the old arc signal devices could be paired from klika ?. if zo could yo you publish the homey arc signal defintion, i am a dino in domotica land and have a lot of arc devices

**Comment by nattlip** [comment]
elro uses the arc signal, so the elro app should work with old klika sockets which are depreciated in the klika app.
