### ISSUE TITLE
[com.dyson] Dyson Pure Cool™ Link tafel luchtreiniger wit/zilver not working with app

### ISSUE THREAD

**Issue by sjaakie33** [athombv/homey#2284]
* **Homey Version**:1.5.7
* **Homey Log Code**:
* **Smartphone Platform**: android
* **Smartphone App Version**: 0.8.115

**If related to a Homey App:**
* **Homey App Version**: v1.0.0 - 28.08.17
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:Dyson Pure Cool™ Link tafel luchtreiniger wit/zilver

**What did you try to achieve?**

switch it on or off with homey

**What did you expect as result?**

Dyson Pure Cool™ Link tafel luchtreiniger wit/zilver to switch on or off

**What was the result?**

nothing happens

**Any other remarks**

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
