### ISSUE TITLE
Error in Notification message when text is paste in the text field

### ISSUE THREAD

**Issue by Wimstradamus** [athombv/homey#229]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

paste text in text field of flow editor to send notification to mobile

**What was the result?**

![schermafbeelding 2016-02-21 om 14 25 11](https://cloud.githubusercontent.com/assets/16623555/13202764/0cdf16e6-d8a7-11e5-8b71-4689bc9857d7.png)

**What did you expect as result?**

non paste text is ok 
![schermafbeelding 2016-02-21 om 14 27 57](https://cloud.githubusercontent.com/assets/16623555/13202775/651a2eae-d8a7-11e5-89d4-9d1b656f11b4.png)

**Any other remarks**
Reproduce in flow editor by pasting text in text field mobile notification
...

**Comment by WeeJeWel** [comment]
This is fixed in 0.8.19
