### ISSUE TITLE
[1.5.7] All flows stopped to work

### ISSUE THREAD

**Issue by jonwal8** [athombv/homey#2294]
**Metadata**

* **Homey Version**: 1.5.7
* **Homey Log Code**: 087E95470A
* **Smartphone Platform**: does not apply
* **Smartphone App Version**: does not apply

**If related to a Homey App:**
* **Homey App Version**: does not apply
* **Homey App Log Code**: does not apply
* **Affected Devices (preferably product codes)**: does not apply

**What did you try to achieve?**
All my flows stopped to work suddenly

**What did you expect as result?**
That my flows would work

**Any other remarks**
All my flows stopped to work. They worked fine if i manually tested them. I rebooted the homey a few times without any success. After I pulled the plug for about 5-10minuts they started to work again.

**Comment by bvdbos** [comment]
Homey Log Code : does not apply ???
How could someone from Athom start investigating without this?

**Comment by jonwal8** [comment]
@bvdbos sorry, updated the issue report

**Comment by WeeJeWel** [comment]
So if I understand correctly, your flows stopped working but now they work again?

**Comment by jonwal8** [comment]
Yepp, thats correct. I just pulled the plug for a while and then they started to work again.

**Comment by WeeJeWel** [comment]
OK.  Homey was probably still starting up. Let me know if it happens again.
