### ISSUE TITLE
Missing device class description

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2297]
**Metadata**
https://apps.developer.athom.com/tutorial-Drivers-Reference.html

**What did you try to achieve?**
**What did you expect as result?**
**What was the result?**

Until recently, when choosing a class in the window "Device Classes" the capabilities native to the class was shown - now it says "No description" for all.

**Comment by WeeJeWel** [comment]
The capabilities are indeed not linked anymore (as preparation for Homey v2.0.0). I'll add descriptions in the future.

**Comment by cbho** [comment]
Meaning that using classes as they are now, will not automatically include certain capabilities per se?
Removing this kind of documentation - rather than updating it - makes it quite difficult for rookies to get on...
My suggestion is, that it is made available again and leave it until the new info is available :-)

**Comment by robertklep** [comment]
Wouldn't it be really easy to point to the previous file for the time being?

https://raw.githubusercontent.com/athombv/node-homey-lib/6217fcc46fb45cb0a830b5efc0236e46b259f258/lib/deviceclasses/deviceclasses.json

**Comment by WeeJeWel** [comment]
Fixed!
