### ISSUE TITLE
Speech command, only the last created will work

### ISSUE THREAD

**Issue by BeJaKl** [athombv/homey#23]
Created a speech commando to turn a Philips living colors light on and off.

Flow on:
If:        You said something card. (with a text label)
And:    logic (contains) drag the black Text-token from the Microphone-card to the Logic-card,  
           and typed "turn the lights on".
Then:  Light card and selected the Living colors light.

Tested it and it works.

Flow off:
If:        You said something card. (with a text label)
And:    logic (contains) drag the black Text-token from the Microphone-card to the Logic-card,
           and typed "turn the lights off".
Then:  Light card and selected the Living colors light.

Tested it and it works. 

However after that i tried several times to get the light's back on and it did not work.
Homeys led turns first yellow and next spinning white but nothing happens.

When i replaced the And: in the on flow (logic (contains) drag the black Text-token from the Microphone-card to the Logic-card, and typed "turn the lights on". the light worked again with speech on but now the speech off commando does not work anymore.

**Comment by WeeJeWel** [comment]
Sounds like the commands wasn't heard properly. Try to send the heard speech to your smartphone to check if that was correct.

**Comment by BeJaKl** [comment]
Smart Phone heard / translated both spoken commando's correct.
still doesnt work correct

**Comment by BeJaKl** [comment]
This morning there are suddenly some changes (On and Off flow not changed):
When spoken command "light on" the two programmed lights go on and Homey confirms it by speech "turning the lights on". 
However almost all my 13 Philips hue and living Colour lights went on?? instead of the two programmed to go on.

When spoken command "light off" the programmed lights sometimes go off and Homey confirms it by speech "turning the lights off". 
However  all my 13 Philips hue and living Colour lights are responding now to the spoken command?? instead of the two programmed who must go off. 

Glad homey confirms the spoken commando because I know that the given speech commando is okay.
For Homey to give the right signal to the right lamp needs some work guys.

**Comment by WeeJeWel** [comment]
I am pretty sure that Homey's pre-programmed speech commands for light are interfering with your flows. You should delete the flows regaring lights + speech, and just talk to Homey.

Example phrases:

OK Homey, turn on the lights (turns on all lights)
OK Homey, turn on the lights in the Living Room (turns on all lights in the living room)
OK Homey, turn on Kitchen light (turns on a light called 'kitchen light')

**Comment by freemann** [comment]
Very strange situation.

So its not possible to make a flow like;
"OK Homey, we are home"

and homey turns on the Hue lights in the livingroom?

**Comment by WeeJeWel** [comment]
That's definitely possible! Just don't try to trigger on words like
'light', because Homey itself also does that.

**Comment by BeJaKl** [comment]
Maybe a good idea too release the pre-programmed phrases so that self made flows by Homey owners can't conflict with it?
I'm still testing so I don't know if your last tip is the solution of this issue.

**Comment by WeeJeWel** [comment]
That's a very good suggestion, I definitely will do that!

**Comment by freemann** [comment]
Or warn uses when the uses pre-programmed words in there flow.

**Comment by BeJaKl** [comment]
Eh, tried too delete the flows light on and off (removed all tags) but this it is not possible.
When saving it says "no trigger difined!".
Is there another way too delete>

**Comment by WeeJeWel** [comment]
Press the (x) button in the list of all your flows.

**Comment by BeJaKl** [comment]
didn't see that icon since i use the flow manager, maybe ude a little darker gray voor the icon or black ?

**Comment by WeeJeWel** [comment]
The new Homey update has a larger ‘Delete’ button next to ‘Save’ and ‘Cancel’ :-)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by BeJaKl** [comment]
Well, removed all light flows with speech and it still isn't working correct.
When given command OK Homey, turn off the lights in the Living Room (turns off all lights in the living room) homey confirms "Turning the lights off" but 6 from the 9 lamps stay on.

Also light on or off  commands for kitchen, master bedroom, bedroom and turn on or off all the lights works half or not at all.
For Homey to give the right signal to the right lamp needs some work guys.

**Comment by BeJaKl** [comment]
Still non of the 14 lamps will go on or off with voice control. new is message Oops could not reach the server, try again later (is standing on the same desk as Homey) the standard AB,s and Hue app geve no problems at all at the same time.

learning <Ok Homey> to Homey with my low voice is not possible (old firmware no problem at all), when I higher my voice it learns in one time when repeating 5 times ok homey?

**Comment by WeeJeWel** [comment]
Do you always get that error message (oops)  back after you said something? Shouldn't happen more than once on a few times.

**Comment by BeJaKl** [comment]
No, just once
