### ISSUE TITLE
Where is the Sunday?

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#230]
0.8.17
**To get a trigger on Sunday you have to exclude the hole week.**

![not a week day](https://cloud.githubusercontent.com/assets/5736105/13204103/65391196-d8c7-11e5-944d-9ce1efc50e06.png)

![_sunday_](https://cloud.githubusercontent.com/assets/5736105/13204104/67eccef0-d8c7-11e5-9836-e82887d31cdf.png)

**Comment by Wimstradamus** [comment]
indeed Homey does not recognize today is Sunday. (explanation mark in card)
Date in system is correct.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.19
