### ISSUE TITLE
[com.fibaro] Can't add Fibaro Motion Sensor FGMS-001 ZW5

### ISSUE THREAD

**Issue by Andi2k11** [athombv/homey#2300]
Hello

On the list of supported units the Fibaro Motion Sensors FGMS-001 and FGMS-001-Plus is listen. I have a Fibaro Motion Sensor FGMS-001 ZW5. I can't connect this device. Is the unit supported and I may have a defected device or is it not supported?

Best regards
Andreas

**Comment by bvdbos** [comment]
Of course these are supported. You'd better perform a reset through Homey first and then reset the devices (look in the manual for a howto) before including these.

**Comment by Andi2k11** [comment]
Well I did a reset of the Z-wave device but It said it coulnt find a device to exclude. And I have reset the motions sensor as stated in the manual for the device.

**Comment by Andi2k11** [comment]
It's  the FGMS-001 ZW5 v3.2. I have read that many have issues with this, but it was an old firmware and it should be fixed

**Comment by RobinBol** [comment]
Hi @Andi2k11 sorry for the late response, if you also can not reset the device then it seems that is does not communicate anything to Homey and might be faulty. Please ensure the maximum distance during inclusion/exclusion is 0.5m.

**Comment by RobinBol** [comment]
@Andi2k11 if all above fails it would be best to contact Fibaro support, it seems that your device is not responding. I will close this issue as it does not seem to be a Homey bug.
