### ISSUE TITLE
only first button reacts to general voice commands on zigbee "Double wall switch" 

### ISSUE THREAD

**Issue by mauritsivs** [athombv/homey#2303]
**Metadata**

* **Homey Version**: 1.5.7
* **Homey Log Code**: 1D2AF37386

**If related to a Homey App:** xiaomi mi zigbee
* **Homey App Version**: 0.2.3
* **Homey App Log Code**: 15e826ff-be41-4c9b-ad7c-20887d542751
* **Affected Devices (preferably product codes)**:
![screenshot 2018-03-07 09 04 44](https://user-images.githubusercontent.com/9398318/37080483-b1a4e6bc-21e6-11e8-911f-81745f7a5540.png)

**What did you try to achieve?**
use general (voice) command to turn off all kitchen lights.
"OK homey, turn off all kitchen lights"
to turn off all three lights connected to zigbee devices including xiaomi double wall switch

**What did you expect as result?**
that homey turns off all the lights in the kitchen

**What was the result?**
all lights turned off, EXCEPT for the SECOND switch/button on the double wall switch.

**Any other remarks**
the second switch on the device can be programmed individually using trigger cards etc. but it does not react to general (voice) commands that do not specifically target that button. 
also using an action card with "turn off lights in zone X" does not work.

**Comment by jeroenvollenbrock** [comment]
@mauritsivs This is a community app, could you please reopen this ticket in the app repo? https://github.com/TedTolboom/com.xiaomi-mi-zigbee/issues

**Comment by mauritsivs** [comment]
as @Tedtolboom stated:

> This is a current limitation(s) within Homey...
> 
> The lack of a multichannel option for Zigbee does not allow a second (virtual) device with the onoff capability.
> Within one device, it is not possible to use two times the same capability, so I had to re-use the onoff capability for the right switch
> Apperantly, re-using a default capability does not make the flow cards available (fixed in the app) and also not the speech options...
> 
> Athom is aware, just made the issue for reference: athombv/homey#2327

hope this gets fixed/added in a future firmware update
