### ISSUE TITLE
[1.5.8] After update there is suddenly an unknown node

### ISSUE THREAD

**Issue by canedje** [athombv/homey#2305]
**Metadata**

* **Homey Version**:1.5.8
* **Homey Log Code**: 4C88DFF647
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I did an update to 1.5.8

**What did you expect as result?**

A good update

**What was the result?**

After the update there was suddenly an unknown node as latest ID, not there before.
(How to remove?)
It is not shown up at devices, so I'm not able to remove!

**Any other remarks**

![knipsel](https://user-images.githubusercontent.com/23150947/37157326-6e928708-22e0-11e8-883b-62ca64e3bfc5.PNG)

**Comment by Veldkornet** [comment]
I have a similar issue, I removed a device, it was confirmed as removed (also don't see it within homey anymore), but still shows on developer tools as _Unknown Node_

![image](https://user-images.githubusercontent.com/10297361/37515938-d57bddac-290c-11e8-9e46-cd3a854ade54.png)

Maybe related to #2326 ?

**Comment by SixFive7** [comment]
Same here. Got 4 homes with homeys. 3 of them show unknown nodes in the developer tools.

**Comment by Inversion-NL** [comment]
Got one also

**Comment by tboudri** [comment]
#metoo

**Comment by bm480** [comment]
I have seen this behaviour in earlier Homey versions as well. I'm sure it is not introduced by 1.5.8.

**Comment by elfrigo** [comment]
In [this thread Jeroen Vollenbrock](https://forum.athom.com/discussion/2709/how-to-remove-unknown-z-wave-devices) said that they will be removed automagically in a future update.
Any update on when this magic is planned to be added?

**Comment by WeeJeWel** [comment]
See https://github.com/athombv/homey/issues/1772#issuecomment-401672363
