### ISSUE TITLE
Kaku broken in 1.5.8? 

### ISSUE THREAD

**Issue by thezahir1** [athombv/homey#2311]
As of today, after installing 1.5.8, all my KaKu (klikaanklikuit) devices won't work anymore with Homey ..
Do more people experience the same problem? 
Or does anyone know perhaps how to solve it ? 
Thanks in advance!

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
Did you try a PTP (Pull The Plug) of Homey?

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #2023
