### ISSUE TITLE
[com.lg.webos] several commands not working

### ISSUE THREAD

**Issue by Roephoed** [athombv/homey#2312]
* **Homey Version **: 1.5.3

**Homey App: LG webOS**
* **Homey App Version**: v2.2.0 -  09.12.17  
* **Affected Devices (preferably product codes)**: my TV -> LG OLED55C7 

**What did you try to achieve?**
I tried to connect my TV to homey, so that i could make flows based on the status of my tv (E.g. TV is turned on, so lights will go into movie mode).

**What did you expect as result?**
The above

**What was the result?**
The TV and homey seemed to be connected. If I send messages with this app in a flow, my tv shows this message on the screen. However, when I would like to trigger flows based on when my tv turns on/off Homey does nothing. 

**Any other remarks**
I tried to turn it on/off everything several times and (un-)installed the app several times. Also tried to connect everything multiple times for both via WiFi and via wired connections.
Furthermore this is the first time i issued a Github message. Please be gentle if I do something incorrectly.

**Comment by Roephoed** [comment]
@WeeJeWel Emile, is this bug on your radar? I really hate that this is not working for me.. :(

**Comment by WeeJeWel** [comment]
Did you try to turn on the tv with Homey, or by using a regular IR remote? The latter won't trigger the Flow.

**Comment by Roephoed** [comment]
Emile, thank you for your response! However, I am not sure what you mean? I turn on the TV with my normal IR remote, which should also trigger a flow. However, the flow is not triggered? 

Or is this not suppose to work this way? Because in the flow editor you can add a "when-trigger" that states specifically "Turned on" and/or "Turned off"? Both do not seem to work.

**Comment by WeeJeWel** [comment]
This does indeed not work. Homey does not capture the Infrared signal of your remote. However, if you turn on the TV from the Homey Smartphone App, or from a Homey Flow, the Flow 'when turned on' will be triggered!

**Comment by Roephoed** [comment]
ah, ok, thanks for the clarification!
