### ISSUE TITLE
Ping external IP addresses

### ISSUE THREAD

**Issue by rvliege** [athombv/homey#2313]
Homey is preventing me to ping external IP addresses. Could this be enabled or is this considered as a security thing?

This can be useful to determine if the internet connection is alive.

**Comment by lubbertkramer** [comment]
@rvliege GitHub is not a place for questions but for issues or feature request where when you make on it has to be filled with all kind of information. Also first use the search on the forum, GitHub and the app store where you could have find this app that uses external check/ping to check if your internet is up and running -> https://apps.athom.com/app/nl.deskweb.netcheck

**Comment by rvliege** [comment]
@lubbertkramer thanks for your answer. 
My goal was achieving this without installing an additional app. I'm already running 27 apps which slows down Homey. Tried it with the already installed Net Scan app but that fails.
Did search for it on the forum and on Github without exact results so created an issue.
But followed your advice and installed Net Check. Doesn't give the user full controle on which ip/site is pinged but will do the trick. Issue can be closed.
