### ISSUE TITLE
Update 1.5.8

### ISSUE THREAD

**Issue by bitjes** [athombv/homey#2314]
**Metadata**

* **Homey Version**:1.5.8
* **Homey Log Code**:na
* **Smartphone Platform**:na
* **Smartphone App Version**:na

**If related to a Homey App:**
* **Homey App Version**:na
* **Homey App Log Code**:na
* **Affected Devices (preferably product codes)**:na

**What did you try to achieve?**

Get network topo for Z-Wave in Homey developer

**What did you expect as result?**

se network topology for Z-Wave
**What was the result?**

only nodes information
**Any other remarks**

**Comment by lubbertkramer** [comment]
Not a bug and has nothing to do with the 1.5.8 update, it's removed by Athom https://github.com/athombv/homey/issues/2148#issuecomment-371768266 As requested please use the search before posting an issue next time

**Comment by bitjes** [comment]
Sorry ik wist niet dat je zo snel gepikeerd was

**Comment by kukel** [comment]
@bitjes: The comment has nothing to do with being 'gepikeerd'. All that is stated is that using the search before posting is a good thing to do (and maybe using the forum first). Think about it. If **everybody** would just post things here, Athom would need to hire a FTE to sift through all 'false/invalid/...' posts.
