### ISSUE TITLE
[com.osram.lightify.zigbee] Osram Classic added as unknown zigbee device

### ISSUE THREAD

**Issue by cevin8** [athombv/homey#2316]
**Metadata**

* **Homey Version**:
Homey Firmware Version: 1.5.8

* **Homey Log Code**:
39CD445D95
* **Smartphone Platform**:
Latest IOS

* **Smartphone App Version**:
Latest

**If related to a Homey App:**
Osram Lightify (ZigBee)

* **Homey App Version**:
v1.0.4

* **Homey App Log Code**:
306a4aea-c2a4-49a0-aa9a-1be470acba17

* **Affected Devices (preferably product codes)**:
Osram Classic E27 Multicolor ZigBee 10W 800lm
Osram Classic Tunable White E27 ZigBee 8.5W 810lm
Osram Classic Dimmable E27 ZigBee 8.5W 810lm

**What did you try to achieve?**
Trying to add Osram RGBW/tunable white/dimmable- bulb to Homey..
Tried both the Osram Lightify app and the homey-Zigbee

**What did you expect as result?**

To Work in Homey whiteout the Osram Gateway.

**What was the result?**

When added it was as Unknown Zigbee Device. 
Only able to switch on and off

**Any other remarks**

**Comment by cevin8** [comment]
[cid:C52A4482-3E7C-42D9-B5B0-389E9D541F0F]
13 mars 2018 kl. 16:53 skrev Jeroen Vollenbrock <notifications@github.com<mailto:notifications@github.com>>:


Could you provide a screenshot of the device info in the settings?

**Comment by cevin8** [comment]
Hello

Did I provide the right screenshots?

**Comment by RobinBol** [comment]
Yes, thank you!

**Comment by cevin8** [comment]
I still have the same problem. how is it going?

**Comment by RobinBol** [comment]
Thank you for your patience, the app has just got a beta update which adds support for the devices you requested. Please let us know if you encounter any further issues!
