### ISSUE TITLE
[Toon] Current power usage card missing 

### ISSUE THREAD

**Issue by mveck** [athombv/homey#2317]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** Toon (Athom)
* **Homey App Version**: 1.3.3
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
Toon Thermostat

**What did you try to achieve?**

Trying to use current power consumption in a flow. This parameter is available in the overview, but not in a card.

**What did you expect as result?**

A card is available where power (not power meter) can be used in a trigger. E.g. power greater then ... Watts.

**What was the result?**

The mentioned card is not available. 

**Any other remarks**
As a workaround I am using Olisto now. Would like to use Homey for all aspects.

**Comment by RobinBol** [comment]
Thanks for reporting your issue. This problem will be automatically resolved when updating to Homey v2.0.0. This update will add the missing flow cards for all capabilities of the device. I will close this issue for now, if you are still experiencing this issue after updating to Homey v2.0.0 in the future please let us know!
