### ISSUE TITLE
[Request]Homey support for NICE products

### ISSUE THREAD

**Issue by Freddydeyucca** [athombv/homey#2319]
https://www.niceforyou.com/nl-be/zonwering

433Hz pair-able rollershutters, sunscreens, relay, ...
cfr somfyRTS app; quick win I suppose?

**Comment by Moszkowizz** [comment]
I will put it on our list of interesting products for future implementation.

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
