### ISSUE TITLE
Only 3 flows that can contain a logic tag

### ISSUE THREAD

**Issue by Jo-Rien** [athombv/homey#232]
Homey Version 0.8.17

Making a fourth flow with a logic tag

Made 3 flows with 2 logic tags in it, then the fourth flow will show an exclamation mark on the left upper corner and the flow will not work.
It seems that there is a maximum in flows with logic in them.

...

**Comment by WeeJeWel** [comment]
Can you provide screenshots?

**Comment by Jo-Rien** [comment]
![homey-exlamation](https://cloud.githubusercontent.com/assets/11969163/13221335/4003f3c8-d97b-11e5-9e6c-9955186fbd60.jpg)

I tried all different kind of triggerwords but that did not seem to matter. Even making an excact copy of a working flow gave the same result.

**Comment by WeeJeWel** [comment]
You are sure that the text actually contains that sentence? You can debug by creating another flow that sends a push notification with the text

**Comment by Jo-Rien** [comment]
Ahhh i see what the problem is now, when clicking the test button it shows the exclamation marks on the logic cards in the flow and it does not execute the flow. You could just execute the action in the flow when testing flows with logic maybe?

**Comment by WeeJeWel** [comment]
I am going to add a dialog when testing where you can fill in the tokens for yourself :)

**Comment by Jo-Rien** [comment]
Super, problem solved.
