### ISSUE TITLE
[com.sonos] Plays on other speaker

### ISSUE THREAD

**Issue by jsm198** [athombv/homey#2321]
**Metadata**

* **Homey Version**:1.5.6
* **Affected Devices (preferably product codes)**: 
PLAY:3
PLAY:1
CONNECT:AMP
sw version: 8.4

**What did you try to achieve?**

Try to start music via music interface on PLAY:3
1. Opened Music in desktop app
2. Opened playlist
3. Selected PLAY:3 speaker (down right corner)
4. Pushed play (top right on playlist)
... Music start on PLAY:1...

**Any other remarks**
Tried the same on CONNECT:AMP, same issue. Music start on PLAY:1.

**Comment by JPe2** [comment]
did you try the Sonos-Beta-App
Sonos Athom B.V.  v3.0.1 - 22.02.18
See the line : "You are currently viewing the **beta** version of this app. _Stable version_"

**Comment by jsm198** [comment]
Ok I have the production version (v2.3.0 - 21.04.17). I will try and install the Beta.

**Comment by jsm198** [comment]
Tested Beta. Works much better! thx!

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
