### ISSUE TITLE
[com.lg.webos] Can't find LG TV

### ISSUE THREAD

**Issue by jsm198** [athombv/homey#2322]
* **Homey Version**: 1.5.6
**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: 42LB580V-ZM SW version: 04.04.27

Unable to pair TV w Homey by adding Device. 

Error message:
"No TVs have been found. Please make sure your TV is powered on and connected to Wi-Fi or Ethernet."

**Comment by Dijker** [comment]
according to the LG site your TV has no WebOS

http://www.lg.com/nl/televisies/lg-42LB580V-smart-tv

from the App store: 
This app supports webOS 2 & webOS 3 TVs made by LG.

So imho it would have been strange if you were able to connect ;-) 

You could try a community app https://apps.athom.com/app/com.lg.smarttv 
But it has no info on supported models!

Else you could try to use the IR App for LG from Athom https://apps.athom.com/app/com.lg.ir

**Comment by jsm198** [comment]
@Dijker :D 
no wonder I had issues ;) 

Started with the other LG Smart TV app but it's not working at all. It's even stated in that he/she has stopped developing the app referring to this app... 

Might try the IR workaround (however Homey is not in the same room so then I need a IR device...), or just wait until the TV breaks so I can get a new :D
