### ISSUE TITLE
[com.dyson] Need app to work with newer dyson models

### ISSUE THREAD

**Issue by viixxiiv** [athombv/homey#2324]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:1.5.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Add dyson TP03 air purifier to a flow

**What did you expect as result?**

TO work

**What was the result?**

not compatible

**Any other remarks**

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
