### ISSUE TITLE
ZigBee network becomes unresponsive on a regular interval

### ISSUE THREAD

**Issue by moment77** [athombv/homey#2325]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: D58631EEF9
* **Smartphone Platform**: IOS
* **Smartphone App Version**: 1.3.3

**What did you try to achieve?**
Zigbee network die once every 24h or so. I think it has to do with Xiaomi Aqara motion sensors. 

On normal days, I have to reboot my Homey atleast once every day to reset zigbee and have my devices working again. But now I was away for 4 days and when I came home all zigbee devices was still functional and reachable, until I have been home for about 30 minutes, then all zigbee devices were unreachable / do not react to commands neither through flows or homey app. So my only guess it that it has to do with motion sensors somehow.

**Comment by arthurpoortman** [comment]
I have the same issues since 1.5.8 (i came from 1.5.7) with Ikea Tradfi bulbs.
The motion sensors are Zwave and still working at that moment but i cannot manual turn off or on the zigbee lights.

**Comment by jeroenvollenbrock** [comment]
This might be some insightful info for #2141. Let's try to get some of these sensors into our QA process and attempt to reproduce the problem. @stefanwitkamp @Moszkowizz @RobinBol

**Comment by TedTolboom** [comment]
@moment77 which type of motion sensors are you using? 

The "Aqara Human Body Sensor" (incl. luminance) or the "Occupancy sensor" (without luminance)?
Can you share your Zigbee nodes overview as shown on: https://developer.athom.com/tools/zigbee?

**Comment by moment77** [comment]
It's the Human body sensor I use... 

0 | 0x00124b0004f6f4b0 | Homey | Athom B.V. | Coordinator | Homey | 260 |  
-- | -- | -- | -- | -- | -- | -- | --
1 | 0x0017880102dde345 | Hörnlampa | Philips | Router | LCT010 | 49246 | 1
2 | 0x0017880102e23dd5 | Hue dimmer switch | Philips | EndDevice | RWL021 | 49246 | 2
3 | 0x00178801029ad69b | Fönster 2 | Philips | Router | LTW012 | 49246 | 3
4 | 0x00178801029b6683 | Fönsterlampa | Philips | Router | LTW012 | 49246 | 4
5 | 0x0017880102dde635 | Sänglampa vänster | Philips | Router | LCT010 | 49246 | 5
6 | 0x0017880102925111 | Sänglampa höger | Philips | Router | LCT010 | 49246 | 6
7 | 0x0017880103409649 | Fönster 1 | Philips | Router | LTW012 | 49246 | 7
8 | 0x00158d000171128c | Aqara Wireless Remote Switch Double | LUMI | EndDevice | lumi.sensor_86sw2Un | 260 | 8
9 | 0x00158d0001e453d8 | Ytterdörr | LUMI | EndDevice | lumi.sensor_magnet.aq2 | 260 | 9
10 | 0x00158d00016db7bb | Rörelsesensor | LUMI | EndDevice | lumi.sensor_motion.aq2 | 260 | 10
11 | 0x00158d0001ab1d08 | Balkongdörr | LUMI | EndDevice | lumi.sensor_magnet.aq2 | 260 | 11
12 | 0x00158d0001b9246d | Temperatur | LUMI | EndDevice | lumi.weather | 260 | 12
13 | 0x00158d0001b920f4 | Uterummet | LUMI | EndDevice | lumi.weather | 260 | 13
14 | 0x00158d000215a995 | Aqara Wireless switch | LUMI | EndDevice | lumi.sensor_switch.aq2 | 260 | 14
15 | 0x00158d0001b95cdb | Termometer | LUMI | EndDevice | lumi.weather | 260 | 15
16 | 0x00158d0001f3541b | Wireless switch | LUMI | EndDevice | lumi.sensor_switch | 260 | 16
17 | 0x000b57fffeb2db1f | Städlampa | IKEA of Sweden | Router | TRADFRI bulb E27 WS opal 980lm | 49246 | 17
18 | 0x00158d000164461c | Städsensor | LUMI | EndDevice | lumi.sensor_motion.aq2 | 260 | 18
19 | 0x0017880103409618 | Lilla fönstret | Philips | Router | LTW012 | 49246 | 19

**Comment by TedTolboom** [comment]
Thanks for the fast response.

What flows are the human body sensors triggering? I suspect that these sensors will trigger one or multiple flows to switch on or off the Zigbee (Hue / Tradfri) lights...

**Comment by moment77** [comment]
#10 triggers a flow that turns on a z-wave device (if conditions is met)
#18 triggers a flow where I turn on #17 when motion is detected

**Comment by Jozzle** [comment]
I'm having the same issue... once every couple of days, homey loses its Zibgee network and the graph looks like this:
![capture](https://user-images.githubusercontent.com/2930363/37911120-7ef1e296-310f-11e8-855a-99633865d874.PNG)

A Homey Reboot temporarily fixes things...

**Comment by brtwrs** [comment]
Im having the same problems. I have some xiaomi motion devices (both aqara and non aqara) and some IKEA lights. I took a good look at my insights to see if im able to pinpoint the device or flow that crashes the zigbee network but there is no clear connection between any of the the crashes and a specific device/flow. If I can be of any debug-assistance let me know!

**Comment by mversluis** [comment]
Just take a look at the other ZigBee devices and seems like ( not be only  a Innr light ) problem.
But all the devices are stop working at the same time. Reboot homey and this will solve the problem for 1 or 2 days.

Seems like ZigBee lost the connection or hang-up after couple of time.

**Comment by KenFri** [comment]
I can also confirm problem with ZigBee network. I have tradfri bulbs controlled by Xiaomi Aqara Human Body sensors. The bulbs are 1m apart from each other. Sometimes only one off them will be turned on. Sometimes they don't turn off.
But I also have tradfri bulbs that are only controlled by time flows and the same problem with them. A restart of Homey solves the problem for approx 2 Days and then it starts again.

**Comment by RobinBol** [comment]
Merging with https://github.com/athombv/homey/issues/2141
