### ISSUE TITLE
[1.5.8] Re-using default capability (onoff.1) does not provide same options as original capability (speech / flow cards)

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#2327]
**Metadata**
* **Homey Version**: 1.5.8

**What did you try to achieve?**

For the Xiaomi double switch, I needed to add a second onoff capability. 
Due to the lack of multiChannel devices for ZigBee, I added the right switch as onoff.1
see: https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/config/drivers/ctrl_neutral2.json#L11

**What did you expect as result?**
All options available as for default onoff capability

**What was the result?**

Default flow cards and speech is not available for the re-used capability (onoff.1)

Please make them available

**Comment by WeeJeWel** [comment]
It's by design that we don't add these because it's very vague what should happen. I suggest you create an issue, if you didn't already, to add support for multi-channel devices for zigbee.

**Comment by bvdbos** [comment]
@WeeJeWel : that #2137

**Comment by TedTolboom** [comment]
@bvdbos ❤️
