### ISSUE TITLE
[com.qubino] Add support for ZMNHLD1 (Flush PWM Thermostat)

### ISSUE THREAD

**Issue by EmilRingborg** [athombv/homey#2328]
Please add support for ZMNHLD1 (Flush PWM Thermostat)

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
