### ISSUE TITLE
Homey died on me again

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#233]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Nothing special. Working on app development though.

**What was the result?**

Homey became slower and in the end died (note: web server dies, device can still be reached via ping and/or SSH). This is now the 3th time that this has happened.

**What did you expect as result?**

Homey to run rock solid & stable.

**Any other remarks**

Have not figured out a way to consistently reproduce it. After a reboot it works again, but this should not be needed.

**Comment by nlrb** [comment]
Make that 4 times... It happened again today.

**Comment by nlrb** [comment]
Make that 5 times... Any progress on this?

**Comment by jghaanstra** [comment]
I have seen this happen a couple of times as well on 0.8.20. I see that Homey is still connected to my router but the management dashboard is unreachable, not by browser or app and no flows are getting triggered. Something is causing a software failure it seems. Does logging survive a power cycle? If so I'll send it and post the token here so it can be looked into once this happens to me again.

**Comment by nlrb** [comment]
Yes, also happened to me again on 0.8.20.

**Comment by bvdbos** [comment]
I'm at 3 days uptime now and everything still works, load-avg about 0.68 but freemem back 6 MB to 4 MB since this morning. Can't send log as "stdout maxBuffer exceeded"

**Comment by nlrb** [comment]
And again. Is anybody looking into this?

**Comment by nlrb** [comment]
And again. Anybody home?

**Comment by nlrb** [comment]
Please close this. Apparently it is acceptable that Homey stops working and needs to be re-booted each day.

**Comment by bvdbos** [comment]
Are you still on 0.8.20 ? Were you able to send a log ? Do you see freemem going down, do you see loadavg goging up above 2 ? Without this information it's not possible to know what's going on...

**Comment by nlrb** [comment]
I am on 0.8.22 since it was released. So it happens with 0.8.17-0.8.22. It just happened again tonight. Clearly Homey was executing an action this time as the LED ring is still red.

As far as I understand the log gets empty on a reboot. An it is impossible to send a log before the crash as it is unclear when it will happen.

I am not watching freemem or loadavg all the time. Usually Homey is dead when I come home from work.

What I propose is that you guys add the option to log the freemem & loadavg values to Insights. Maybe that gives a clue.

**Comment by bvdbos** [comment]
Might this be voice-related? There were improvements with voice-commands in 0.8.24 so does this still happen?

**Comment by nlrb** [comment]
It happened again today on 0.8.24.

**Comment by bvdbos** [comment]
If it's not because of an app you have been playing with then it would be something for Athom I guess. Perhaps give them access to your Homey (SSL or webinterface) to figure this out?

**Comment by nlrb** [comment]
I've offered them all access (even TeamViewer session/ssh if needed), but they say there is no way to have remote access and find out.

**Comment by nlrb** [comment]
My suspect would be z-wave. After a reboot the Fibaro Wall Plug (which doesn't include well, see #240) gives an error 'I can't reach your device; Error: timeout waiting for a report'. Before 0.8.24 it would never create a visible/usable device, so also issues with the device were not visible.

**Comment by jghaanstra** [comment]
I also experience this issue a lot on 0.8.24. Homey just becomes unreachable after a period of time although it looks like it is still triggering time based flows. So my guess is that the WiFi module crashes. I also have the time out zwave issues mentioned above but I have has those since the start (0.8.17 for me) and Homey did not disconnect every couple of hours at that time.

**Comment by Muyz** [comment]
same issue again today

**Comment by bvdbos** [comment]
@jghaanstra : That's a good way to find out what happens. Multiple time-based flows, one doing something with 433, one with wifi, one zwave etc etc. and see which happen after a crash...

**Comment by Muyz** [comment]
Just happened again. Homey still executes flow: input KAKU sensor, output Fibaro zwave dimmer. Maybe only WiFi died?

**Comment by nlrb** [comment]
@Muyz : can you still ping Homey? For me that always remains possible (so wifi works).

**Comment by Dijker** [comment]
Same here, Check-KAKU still works but a I don't see Homey''s IP  on the network anymore.

**Comment by jghaanstra** [comment]
My Homey just died after restarting the z-wave chip, something that I have experienced before. It takes a long time to restart the zwave chip which eventually results in a pop-up saying "true". I did catch the console errors but was of course unable to catch a log. Perhaps the console errors are useful for the Athom employee that eventually gets assigned to this issue.

![restart-zwave](https://cloud.githubusercontent.com/assets/4710062/13962685/69d32c98-f062-11e5-88af-8868d41a4198.png)

**Comment by HackAzz** [comment]
Is this still happening with the latest firmware?

**Comment by nlrb** [comment]
With 0.8.27 it has become more frequent that the front-end becomes unresponsive and a reboot is needed. Now often need to reboot multiple times a day.

**Comment by bvdbos** [comment]
I guess you didn't try a full wipe yet, did you? Could you try to wipe and keep the previous settings, see of this changes anything?

**Comment by nlrb** [comment]
Please explain why a full wipe would fix it.

**Comment by bvdbos** [comment]
past experiences, for instance:
https://forum.athom.com/discussion/comment/15436/#Comment_15436

**Comment by freemann** [comment]
I think the question is more;
Why is Athom releasing FW updates which need a full factory wipe to get a Homey back on his feet again....

**Comment by HackAzz** [comment]
Sometimes there it is necessary, because there is no choice ;-)

**Comment by freemann** [comment]
@HackAzz;
That's so not true! 

A reboot, OK, but a complete wipe....
When was the last time you did a complete wipe on your workstation because of a OS/Software update?

Allmost all FW's "needed" a wipe to get the whole system working properly again because one or more functions/modules were crashing or totally not working.

**Comment by HackAzz** [comment]
Because homey fw is still beta and unstable, meaning experimental.

**Comment by freemann** [comment]
The "Experimental" tag..... I'm :heart: ing it

**Comment by HackAzz** [comment]
That's the downside as a pioneer ;-)

**Comment by HackAzz** [comment]
And getting frustrated because of unstable fw versions does not tag you as a good "tester" ;-D

**Comment by freemann** [comment]
This has nothing to do with pioneering 
Experimental, Alpha, Beta, Stable, LTS release, Athom should prevent this at all(!) costs.

**Comment by HackAzz** [comment]
Athom is doing the best they can, complaining about it doesn't help them..:-)

**Comment by freemann** [comment]
Ok, lets accept is :+1:

**Comment by HackAzz** [comment]
This is what kickstarter projects are all about..:-)

**Comment by HackAzz** [comment]
At the end it'll work, just be patient! :-)

**Comment by jghaanstra** [comment]
Just to chip in. I have not had Homey die on me anymore since the 0.8.27 firmware update which is a huge improvement for me. Too bad to see others still experiencing this issue, I had hoped it was solved now.

(And by the way, I have never done a factory reset. As far as I can tell from other users this causes more issues then it fixes them)

**Comment by jghaanstra** [comment]
@nlrb does your Homey really still die on you on firmware version 0.8.29? Even after a couple of days with no reboot my Homey did not die on me at all. It really seems solved to me.

**Comment by nlrb** [comment]
@jghaanstra yes: it still happens.

**Comment by nlrb** [comment]
Homey is now already very slow for a number of days and hard to reach - but some flows still seem to work.

![image](https://cloud.githubusercontent.com/assets/11725674/14552835/dce4f9dc-02e1-11e6-83c0-f92d08d40dc5.png)

**Comment by nlrb** [comment]
Unfortunately issue still exists with 0.8.30. After less than a day of running the web UI is unresponsive, an also pings are often not successful. Hence also getting "Oops, I couldn't reach the server".
![image](https://cloud.githubusercontent.com/assets/11725674/14580180/546cd2c0-03c5-11e6-864e-7b10fc11e277.png)

**Comment by jghaanstra** [comment]
Ok, this has happened twice today now. This issue is indeed not resolved on firmware 0.8.30.

**Comment by Arjanvde** [comment]
I must say i have had the same experience running 0.8.30. 

The last 2 days the website my.ahtom.com has encountered some issues and as soon as the website was offline my Homey didn't respond to any more actions, couldn't ping it either. Only way to  reconnect was to pull the plug from Homey.This be the cause of some actions that if the internet connection fails on a beta version, homey becomes unresponsive, 433MHZ etc didn't work anymore... 

Yesterday I had the issue that i couldn't connect to my Homey (my.athom or local ip), at the same time i had a colleague on the phone who was able to access his (non beta) Homey just fine.I have had this experience twice now (Monday and Tuesday).

**Comment by Arjanvde** [comment]
To add a little bit, this issue was the same issue I've experienced on Monday evening.

https://forum.athom.com/discussion/comment/17570/#Comment_17570

Homey became unresponsive to any input, a reboot fixed the issue.

**Comment by nlrb** [comment]
Closing this one as Homey is quite stable since 0.8.32. It has been running for more than a week without an issue. It did crash today when uploading an app through the CLI (led ring stayed blue, web UI dead), but propose we use separate issues for specific crashes we run into.
