### ISSUE TITLE
Homey can't connect to Athom Cloud - DHCP protocol issue

### ISSUE THREAD

**Issue by lenwar** [athombv/homey#2331]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**What did you try to achieve?**
Since the 1.5.8 update Homey can not connect to the Athom Cloud. The my.homey.com says it is offline and the homey-desktop application says it cannot connect to the Athom Cloud.

**What did you expect as result?**
I expect Homey to be able to connect to it's cloud service

**What was the result?**
It can't connect to it's cloud service

**Any other remarks**
I tried rebooting it via the Desktop Application, and also pulled the plug. I only use the original powersupply and cable. All non-internet-related apps work properly.

Update:

I did some research myself and found that Homey doesn't properly follow a part of the DHCP-protocol as defined in RFC 3442 (Classless static routes)

My DHCP-server provides Classess Static Routes along with other options. Homey appears to lose it's way when it recieves those:

> dnsmasq-dhcp[23498]: 1603982087 available DHCP range: 192.168.0.210 -- 192.168.0.250
dnsmasq-dhcp[23498]: 1603982087 client provides name: Homey
dnsmasq-dhcp[23498]: 1603982087 DHCPDISCOVER(eth0) 192.168.0.248 3c:a3:08:xx:xx:xx
dnsmasq-dhcp[23498]: 1603982087 tags: homey, known, eth0
dnsmasq-dhcp[23498]: 1603982087 DHCPOFFER(eth0) 192.168.0.248 3c:a3:08:xx:xx:xx
dnsmasq-dhcp[23498]: 1603982087 requested options: 1:netmask, 28:broadcast, 2:time-offset, 3:router,
dnsmasq-dhcp[23498]: 1603982087 requested options: 15:domain-name, 6:dns-server, 119:domain-search,
dnsmasq-dhcp[23498]: 1603982087 requested options: 12:hostname, 44:netbios-ns, 47:netbios-scope,
dnsmasq-dhcp[23498]: 1603982087 requested options: 26:mtu, 121:classless-static-route, 42:ntp-server
dnsmasq-dhcp[23498]: 1603982087 next server: 192.168.0.121
dnsmasq-dhcp[23498]: 1603982087 sent size:  1 option: 53 message-type  2
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 54 server-identifier  192.168.0.XXX
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 51 lease-time  1d
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 58 T1  12h
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 59 T2  21h
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  1 netmask  255.255.255.0
dnsmasq-dhcp[23498]: 1603982087 sent size:  8 option:121 classless-static-route  18:0a:03:00:xx:xx:xx:xx
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  3 router  192.168.0.1
dnsmasq-dhcp[23498]: 1603982087 sent size:  0 option: 47 netbios-scope
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 42 ntp-server  192.168.0.XXX
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 28 broadcast  192.168.0.255
dnsmasq-dhcp[23498]: 1603982087 sent size: 16 option: 15 domain-name  dhcp.localnetwork
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  6 dns-server  192.168.0.XXX
dnsmasq-dhcp[23498]: 1603982087 available DHCP range: 192.168.0.210 -- 192.168.0.250
dnsmasq-dhcp[23498]: 1603982087 client provides name: Homey
dnsmasq-dhcp[23498]: 1603982087 DHCPREQUEST(eth0) 192.168.0.248 3c:a3:08:xx:xx:xx
dnsmasq-dhcp[23498]: 1603982087 tags: homey, known, eth0
dnsmasq-dhcp[23498]: 1603982087 DHCPACK(eth0) 192.168.0.248 3c:a3:08:xx:xx:xx Homey
dnsmasq-dhcp[23498]: 1603982087 requested options: 1:netmask, 28:broadcast, 2:time-offset, 3:router,
dnsmasq-dhcp[23498]: 1603982087 requested options: 15:domain-name, 6:dns-server, 119:domain-search,
dnsmasq-dhcp[23498]: 1603982087 requested options: 12:hostname, 44:netbios-ns, 47:netbios-scope,
dnsmasq-dhcp[23498]: 1603982087 requested options: 26:mtu, 121:classless-static-route, 42:ntp-server
dnsmasq-dhcp[23498]: 1603982087 next server: 192.168.0.121
dnsmasq-dhcp[23498]: 1603982087 sent size:  1 option: 53 message-type  5
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 54 server-identifier  192.168.0.XXX
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 51 lease-time  1d
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 58 T1  12h
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 59 T2  21h
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  1 netmask  255.255.255.0
dnsmasq-dhcp[23498]: 1603982087 sent size:  5 option: 12 hostname  Homey
dnsmasq-dhcp[23498]: 1603982087 sent size:  8 option:121 classless-static-route  18:0a:03:00:xx:xx:xx:xx
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  3 router  192.168.0.1
dnsmasq-dhcp[23498]: 1603982087 sent size:  0 option: 47 netbios-scope
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 42 ntp-server  192.168.0.XXX
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option: 28 broadcast  192.168.0.255
dnsmasq-dhcp[23498]: 1603982087 sent size: 16 option: 15 domain-name  dhcp.localnetwork
dnsmasq-dhcp[23498]: 1603982087 sent size:  4 option:  6 dns-server  192.168.0.XXX

The Classless static routes that are sent are:
0.0.0.0/0 --> 192.168.0.1    (replacing the default gateway as specified in the RFC)
10.0.0.0/24 --> 192.168.0.100     (which is a requirement for other devices on my LAN)

**Comment by Dijker** [comment]
Is Homey Accessible from the local network on its local IP adres?
If yes, 
Could  you Send an LOG to Athom and update the Issue with the Code for Athom to investigate?

Please also Check the local Time and Date on Homey (both date  (GMT) and date_human (Your time Zone)) and the Timezone. 
Please Check also the Location on Settings. 
(just change location to manual and back to automatic to update the Timezone if not correct and let Homey do a quick Restart to update )

If all are OK and Homey still is not connected is suppose you update this issue and send an email to Athom  support referring to this issue and your Log code.

**Comment by Dijker** [comment]
I See Your update, 
Great finding, 
I guess you  are a network guy  and can create a workaround for now ;-) 
Please send an Log for Athom (Guess that still works) ^
I know there where some low level changes between last updates,

@jeroenvollenbrock  ^^

**Comment by lenwar** [comment]
Thanks for the quick responses.

I have created a workaround for myself by making an exception for the Homey to not sending the Classless Static Routes to it. (Homey doesn't need to access that part of my network), so now it'll only recieve the default gateway.

I pushed the "Send Log" button which provided    9F13BD23F2

The time zone stuff looks okay.
Is this sufficient for now? Or do you need more information? (( I'm not sure what information is being sent in the logs, but you may notice that I have anonymised some of the information in my initial post ))

**Comment by lyster76** [comment]
My homey also suddenly not connected to athom cloud but is accessible from local lan. 

log: D5612B11D4

**Comment by Inversion-NL** [comment]
@lyster76 Why do you think your issue is the same as the issue creator?
When Homey is accessible from local LAN but not connected to the cloud it could be firewall, DNS etc but unlikely due to DHCP issues.
Unles you use some advanced DHCP server in your local network?

**Comment by jeroenvollenbrock** [comment]
Hi @lenwar, I think you are running into issues because your classless routes do not contain a default route. If you specify classless static routes, those will be used, but the default route will not be set along with it. This is implemented as per RFC3442 and therefore not a bug. I do however understand this may confuse users of classless static routes, as many implementations actually break the RFC by setting a default route along with the static routes, which obviously creates another set of bugs and issues, and some even decided to remove this behaviour later because of it, again creating another set of [issues](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835986). 

FYI: You're missing the following static route:
192.168.0.0/24 -->  0.0.0.0
