### ISSUE TITLE
cannot update parameters of Fibaro motion sensor 

### ISSUE THREAD

**Issue by JoopBanaan** [athombv/homey#2335]
**Metadata**

* **Homey Version**:1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**: Fibaro 1.5.17

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Fibaro FGMS-001 motion detector V3.2

**What did you try to achieve?**

Update settings of the motion detector, specifically the "Bewegingsalarm annuleringsperiode". Entered the new value in the popup screen, pressed "instellingen opslaan", pressed the button on the back of the motion sensor to wake it up.

**What did you expect as result?**

That the value changed from 30seconds to the entered 151seconds

**What was the result?**

No update of the parameter, it remained at 30seconds

**Any other remarks**
When the motion sensor is in direct reach of Homey, and a heal is performed so that the routing from homey to detector is without a hub within the mesh network, an update can be successfully performed.

**Comment by caseda** [comment]
Just as a small remark, wakeup is **triple** press of the b button in fast succession, not just a single click.

**Comment by JoopBanaan** [comment]
Caseda, I tried 3x press as well. Same result no update of the parameters

**Comment by JoopBanaan** [comment]
I have reached a new insight:
Updating the motion detector takes multiple trials: it was just coincidence that it did succeed when the motion detector was connected directly to Homey, without any hubs in between that it succeeded.

Main issue is as described in #2368; ConfigurationSet is only send directly not when the motion detector wakes up. 
Propose to close this ticket and reopen #2368
