### ISSUE TITLE
dyson app: add support for dyson pure HP02

### ISSUE THREAD

**Issue by robertmitter** [athombv/homey#2336]
**Metadata**

* **Homey Version**:1.58
* **Homey Log Code**:not applicable
* **Smartphone Platform**:not applicable
* **Smartphone App Version**:not applicable

**If related to a Homey App:**
* **Homey App Version**:Dyson app v.1.0.0
* **Homey App Log Code**:not applicable
* **Affected Devices (preferably product codes)**:HP02

**What did you try to achieve?**
add one of dysons new line of devices : duson pure Hot+cold to homey 

**What did you expect as result?**

i hope to be able to control the HP02 and add it to workflows using homey

**What was the result?**

This dyson device is not yet supported ,  so could not add it.

**Any other remarks**
I would appreciate it if ths device could be added, it is a very nice cooler/heater/ air purifyer, and the abbility to use it in homey workflows would make it just about perfect

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
