### ISSUE TITLE
[com.qubino] My Flush 2 relay do not report temperature changes, it seams to be locked on the first temperature when I installed it

### ISSUE THREAD

**Issue by onne1951** [athombv/homey#2340]
**Metadata**

* **Homey Version**:  1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**Qubino
* **Homey App Version**:v1.1.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:ZMNHBD1 Flush 2 Relays

**What did you try to achieve?**

se the temperature

**What did you expect as result?**

I removed it first then added  the temp probe and installed it again, Only the temperature when I added the ZMNHBD1 Flush 2 Relays is showing
Temperature change for report is default 5 ( 0.5 degrees celsius)

**What was the result?**

no change in the readouts, it is locket on 21.2 C and it is about 3.6 C now in that room

**Any other remarks**

**Comment by RobinBol** [comment]
Thanks for reporting. Did you change some of the settings or associations? Please attach screenshots of your device settings.

**Comment by RobinBol** [comment]
We recently updated the Qubino app to SDKv2 (it has been rebuilt from the ground up), could you please upgrade to the beta version of the Qubino app to see if this resolves your issue? It might be needed to re-pair your device after you installed the beta version of the Qubino app.

**Comment by RobinBol** [comment]
Will close this issue since the reporter seems te be inactive. Also, it seems that there are ZMNHBD's in circulation with out-dated firmware (https://github.com/athombv/homey/issues/2558), this might be the cause of your issue.
