### ISSUE TITLE
Alexa integration doesn't work (Customer xxx does not have any devices that supports home automation)

### ISSUE THREAD

**Issue by dolfje** [athombv/homey#2341]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: 1.5.8
* **Homey App Log Code**: 7F7FB436A5
* **Affected Devices (preferably product codes)**: Athom Homey

**What did you try to achieve?**
I'm trying to test the new Alexa integration skill. To use that instead of the 'ok homey' as the speech recognition is better. I tried with the "ok google, tell homey", but got tired when homey was always misunderstood (homie, home, ...). So I need a solution without the 'homey' part.

Apparently the Alexa integration skill should solve this. But my decives aren't synchronised with alexa. It says that there aren't devices.

I have a 1 min video (https://www.useloom.com/share/0682f406f0d44376b40642d5e22e42a1) showing the problem. From the moment of Alexa skill installation, till the error code of Alexa: 
"Customer xxx does not have any devices that supports home automation"

**What did you expect as result?**
That my devices were synchronized with Alexa, so I can use the Alexa speech integration

**What was the result?**
The devices weren't synchronized with Alexa

**Any other remarks**

**Comment by fvhuizen** [comment]
Which device do you use to listen ? 
Can you see this device in you're amazon account ?

I use Sonos One and i can see the Sonos One in my Amazon account. It worked for a couple of weeks but now Homey doesn't seems to interact with Alexa anymore.

**Comment by dolfje** [comment]
Thank you for the assistance, but this is my fault. I don't have any alexa device and I thought I could use it the app to access homey directly. This isn't correct, you have to have at least one device of alexa (echo, dot, ...). So that is also the error message. It expect one device (echo, dot), but I interpreted that it didn't found devices on homey. You can circumvent this by linking the echosim device (https://echosim.io/welcome). From the moment I linked that, I could synchronise homey. Strange from Amazon.

I still have an issue that one of the devices in homey doesn't show up on the alexa smart home devices tab, but I will first investigate further.
