### ISSUE TITLE
[AppStore] [Feature request] Add (searchable) info on SDK-version, connection type etc.

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2343]
An idea to improving the App Store:
Could it be possible to make basic info about the apps visible - and searchable.
It would be nice if the app info included "technical" info like SDK-version and technology (z-wave, zigbee, wifi, ir, bluetooth, 433).
Further, it would be nice if it was possible to add this to the search criteria making it possible to only get results including SDK2-apps, e.g.

**Comment by WeeJeWel** [comment]
This is not something we will add in the front-end (too technical for most users) but using the API you can get the SDK version and Permissions (used for wireless access).
