### ISSUE TITLE
Osram app have oneOf validation error

### ISSUE THREAD

**Issue by JohanBendz** [athombv/homey#2346]
**Metadata**

* **Homey Version**: N/A
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

The Github versions of the Osram app have a oneOf Validation error using CLI v2. Both 1.2.0 and 1.2.1 have same problem.

**What did you expect as result?**

Validation without errors

**What was the result?**

Validation error

**Any other remarks**
I fixed it by removing the "speech" section in the app.json file

**Comment by RobinBol** [comment]
Thanks, this has been updated in the beta release of the app!
