### ISSUE TITLE
[com.google.chromecast] Do not see Chromecast symbol in apps section of flow builder

### ISSUE THREAD

**Issue by Talens-E** [athombv/homey#2348]
Hello,

After installing the Chromecast app (v. 3.1.4), the Chromecast symbol does not appear in the flow builder  (it does appear in the overview of installed apps and indicates that is has been installed) . I have tried reinstalling several times, restarting Homey, but this did not help. 

Kind regards,
Erik

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by lubbertkramer** [comment]
Did you add a chromecast device on the devices page after installing the app?

**Comment by Talens-E** [comment]
Op ma 19 mrt. 2018 om 12:28 schreef lubbertkramer <notifications@github.com>

**Comment by Talens-E** [comment]
Ok, had expected automatic detection (do not know why). Explains a lot.
Will try that tonight. Thanks.

Op ma 19 mrt. 2018 om 12:29 schreef Talens Zakelijk <
talenszakelijk@gmail.com>
