### ISSUE TITLE
Athom Chat link

### ISSUE THREAD

**Issue by itsamaik** [athombv/homey#235]
There's no clear link to the Slack chat on the website. There's a link on https://developers.athom.com/ named "Chat", but it will only show the invite form. Please add a link to https://athomcommunity.slack.com somewhere.

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by bvdbos** [comment]
Bad gateway is the respons now, please re-open...

**Comment by WeeJeWel** [comment]
Yup. Pretty weird that our simplest cloud server seems to be the hardest to update.

**Comment by joachimroeleveld** [comment]
Solved.
