### ISSUE TITLE
[com.neatorobotics] Sourcecode?

### ISSUE THREAD

**Issue by rnldnkp** [athombv/homey#2350]
I'm missing the sourcecode for this app, https://apps.athom.com/app/com.neatorobotics 
It's not linked, and not on https://github.com/athombv/com.neatorobotics

I was looking for the features of the App which I can't seem to find anywhere. Reading the sourcecode sometimes fixes this issue ;)

Thanks for sharing

**Comment by rnldnkp** [comment]
Hmm, might have answered my own issue
https://github.com/athombv/com.neatorobotics/tree/beta 

So far I can't seem to find any finished features in de the code. But the driver assumes it's will be able to

- tell if it's cleaning, spot cleaning, docked, stopped, charging
- see how full the battery is
- start (spot) cleaning

The API code suggests more features might be possible, like normal/turbo mode.

**Comment by MatthewWaanders** [comment]
Hey there @rnldnkp,

Indeed the code is on the beta branch as the Neato API is still in beta, so anything built on top of it may potentially lose stability when changes are made to the API.
As for the features the driver assumes available, they are implemented and functional. The API does indeed have a few extra settings that one can use, but we've decided to not do this (for now)
