### ISSUE TITLE
[Feature Request] Developer Tools Mobile View

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2352]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: N/A
* **Smartphone Platform**: iOS
* **Smartphone App Version**: N/A

**If related to a Homey App:** N/A
* **Homey App Version**: N/A
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Browse to https://developer.athom.com from my iPhone 

**What did you expect as result?**

1. Mobile View was available
2. Setting “Request Desktop Site” shows the screen the same as it would show on a PC

**What was the result?**

There is no mobile view and requesting the desktop site does nothing. 
Additionally, the site is pretty much unusable, the ZWave tools for example are all squashed into a tiny column, making everything unreadable. 

**Any other remarks**
I mostly do everything from a tablet / smartphone. Since Homey is moving in the same direction (ie, the new app); can we ensure that the website works properly from mobile devices?

![93755fda-eb5a-4b60-9b2d-fb73cd7eb8e4](https://user-images.githubusercontent.com/10297361/37638440-3a874b98-2c0d-11e8-8447-325087a44d89.jpeg)

**Comment by WeeJeWel** [comment]
The 'Tools' section will not be made available for mobile (It's a developer portal after all). I'll look into the other pages and see what works.

**Comment by Veldkornet** [comment]
Fine, but then can you at least consider adding some of the functionality to the 2.0 app?

I’m not a developer, but I often need to have a look through the ZWave tools section.  This is literally the only thing I do on the site. 

My preference would of course be to include it in the new app so that I don’t need to visit the site at all. 
But at worst case, I at least want to be able to see what’s happening on the page without having to switch on a pc.

**Comment by WeeJeWel** [comment]
I've made it (somewhat) mobile friendly. Should be live within 30 minutes.

**Comment by cbho** [comment]
Better - but with emphasis on _(somewhat)_ ;-)


![2018-03-27 12 50 07](https://user-images.githubusercontent.com/29979509/37963265-0b8a4a32-31be-11e8-9019-169b7d9c0d35.png)

![2018-03-27 12 56 20](https://user-images.githubusercontent.com/29979509/37963378-5e26728e-31be-11e8-83e9-643fa57e37d5.png)

![2018-03-27 12 55 42](https://user-images.githubusercontent.com/29979509/37963387-62bdb19a-31be-11e8-95ca-688454789807.png)

**Comment by cbho** [comment]
Better - but with emphasis on _(somewhat)_ ;-)

![mobile](https://user-images.githubusercontent.com/29979509/37963531-d85ee4c8-31be-11e8-861b-99bf12136268.jpg)

**Comment by lubbertkramer** [comment]
+1 for that

**Comment by mruiter** [comment]
Why wont iT fit in mobile ? Thats the future isnt iT... i can do everything in mobile so why not the zigbee and zwave map.
