### ISSUE TITLE
[com.spotify] v1.0.6 with Homey beta 1.5.8 interferes with SonosPlay1

### ISSUE THREAD

**Issue by TallguyNL** [athombv/homey#2356]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: 7F0AFB011A
* **Smartphone Platform**: Iphone
* **Smartphone App Version**: 11.2.6

**If related to a Homey App:**
* **Homey App Version**: 1.0.6
* **Homey App Log Code**: b032cda4-5cc8-4307-b6f9-af461df4102f
* **Affected Devices (preferably product codes)**: SonosPlay1

**What did you try to achieve?**

Since last Sunday March 19th, I was unable to send music to my SonosPlay1. No matter where I tried to send music from (e.g. the Sonos app itself, Homey or Alexa), the music would either not start at all or give me about 1 seconds worth of music (at most). It did however still all work fine on Friday March 17th. See "Any other remarks"below for detailed troubleshooting info.

**What did you expect as result?**

Hear music

**What was the result?**

Silence

**Any other remarks**
I contacted Sonos support today since I was under the impression that it was a Sonos issue, but after trying lots of things (even resetting the Sonos), it turned out that as soon as I powered off my Homey, the Sonos started working again! Further investigation proved that it was enough to disable the Spotify app in Homey to get things working. By turning it on again, the issue returned at once.
Logging off and back in again in the Spotify app on my Homey did nothing as to the results. Therefore it looks like there's an unwanted interaction between the Spotify app and any random device that can stream music to my Sonos.

**Comment by cbho** [comment]
The same as https://github.com/athombv/com.sonos/issues/22?

**Comment by bvdbos** [comment]
yep

**Comment by TallguyNL** [comment]
My issue  seems to be fairly simular, however in my case only disabling the Spotify app fixed the issue. I did nothing with the Sonos app within Homey since, like I stated, also Alexa had issues connecting to the Sonos as long as the Spotify app on my Homey was active.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
