### ISSUE TITLE
[com.aeotec] Keyfob Association to Fibaro Multichannel relay 

### ISSUE THREAD

**Issue by jcastrol07** [athombv/homey#2357]
Hello
I cannot seem to find a way to make an association between the Aeotec keyfob included in Homey and the two channels available in my Fibaro relay
I am trying to do it through settings, group associations or even through raw configuration parameter but I cannot find a way to make the buttons to control the relay
Is it posible to control a multichannel fibaro relay with the Aeotec Keyfob?..how?

**Comment by jeroenvollenbrock** [comment]
The keyfob has two modes, scene mode and controller mode. For a direct association, you need the controller mode, but for using homey flows, you'll need the scene mode
