### ISSUE TITLE
UI & Flow: thermostat_mode and thermostat_state missing

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#236]
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

Open a thermostat device and see the thermostat_mode and thermostat_state and/or change the thermostat mode. Also within a flow, make a flow which changes the mode or acts on mode or state changes.

**What was the result?**

When opening a device the get function is called, but the returned information is not visible in the UI.

**What did you expect as result?**

To see the thermostat mode and thermostat state and to set a thermostat mode.

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by nlrb** [comment]
thermostat_mode has been re-instated, thermostat_state has been removed. See https://developers.athom.com/library/drivers/capabilities/
