### ISSUE TITLE
[Feature Request] Add a Empty Flow Card that we can use for comments

### ISSUE THREAD

**Issue by michelkamp** [athombv/homey#2364]
Metadata
Homey Version:
1.5.8
What did you try to achieve?
To make the flows more readable it would be nice to have a possibility to add comments to the cards. Or just a simple empty card that we can put our comments in and drag it anywhere in the flow.

What did you expect as result?
not possible 

What was the result?
NOP

**Comment by jeroenvollenbrock** [comment]
This is not a feature for the flow editor. If you want complex flows with code-like comments, you could check out [homeyscript](https://apps.athom.com/app/com.athom.homeyscript).
