### ISSUE TITLE
Feature request: Propose to update KPN remote to also support Arris VIP 2952

### ISSUE THREAD

**Issue by mveck** [athombv/homey#2367]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** KPN (Motorola) settopbox IR
* **Homey App Version**: 1.1.0
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Try to use the IR app in combination with KPN Arris VIP 2952

**What did you expect as result?**

App would be usable for Arris

**What was the result?**

App is only usable for Motorola

**Any other remarks**
This is a feature request, please accept the fact that Motorola is pretty old and is replaced more and more by Arris.

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
