### ISSUE TITLE
Flow marked as broken without missing devices + "ghost" trigger card 

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2371]
* **Homey Version**: 1.5.8
* **Homey Log Code**: A6A9DB9AF1
* **Smartphone Platform**: iOS 11.2.6 (15D100)
* **Smartphone App Version**: V2 (1.1.107)

**What was the result?**
The flow below is marked as broken.
Looking at the flow, nothing is wrong: no devices are missing, no cards are marked as failed.

![broken flow](https://user-images.githubusercontent.com/29979509/37873373-eb720b7a-301b-11e8-9a26-3d9d1d218baa.JPG)
(Picture is edited, titles on other flows are erased for clarity)

Trying to save the flow results in an error message: _Only one trigger per Flow is allowed_

![ghost trigger](https://user-images.githubusercontent.com/29979509/37873424-f1c477fa-301c-11e8-818a-ea059fef8180.JPG)

However, without changing anything in the flow, using "Test" (desktop app) , the flow runs and all actions are executed and all cards marked as "correct".

![success](https://user-images.githubusercontent.com/29979509/37873426-fd8803f4-301c-11e8-9268-a560b63171eb.JPG)

**Any other remarks**

The last time the flow was edited, it was done using the V2 iOS app.
Comparing the flow in desktop app and iOS app, they are identical.

After running the flow with the test function as described, but without changing anything in the flow, it was not marked as broken anymore and it is possible to save it again without getting an error message.

**Comment by WeeJeWel** [comment]
Could you invite me to your Homey? emile+support@athom.nl

**Comment by cbho** [comment]
Done - although flows have been edited manually (otherwise it was impossible to have the lights on on the stairs)...

**Comment by WeeJeWel** [comment]
I cannot reproduce anymore, probably because it has been saved already. We'll check the Homey Smartphone App code, thanks!
