### ISSUE TITLE
DSB45 It's almost completely impossible to add and not working

### ISSUE THREAD

**Issue by tranceblast** [athombv/homey#2372]
It's almost completely impossible to add DSB45, I finally managed but it only shows battery and "no water" it does not respond to water, even though I change the wake up time. also does not help to press the z-wave button

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
What's your log-code, Homey version etc etc? What's a DSB45? Is there an app in store? What version of the app etc etc? Does it work through Zigbee, Zwave, HTTP, Bluetooth? Where does is stop adding?

**Comment by tranceblast** [comment]
Log-code? Homey runs 1.5.8. DSB45 is a water sensor. Aeotec app shows that it is supported

**Comment by bvdbos** [comment]
When you entered the issue the following was asked:

> 
> Thank you for reporting an issue. Please take some time to
> review the contributing guidelines if you haven't done so.
> 
> This issue tracker is for bugs and issues found within Homey.
> If you require more general support contact our support team
> at: support@athom.com
> 
> Please fill out as much of the fields below as you're able.
> The Homey log code can be generated at Settings -> System -> Send Log.
> The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).
> 
> If possible, please provide examples that demonstrates the problem,
> keeping it as simple and clear as you are able to.

**Comment by jeroenvollenbrock** [comment]
Could you please take another look at our [contributing guidelines](https://github.com/athombv/homey/blob/master/CONTRIBUTING.md) and open a new issue? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through [support@athom.com](mailto:support@athom.com) instead of using the bug tracker.
