### ISSUE TITLE
Somfy Github?

### ISSUE THREAD

**Issue by JohanBendz** [athombv/homey#2376]
**Metadata**

* **Homey Version**: N/A
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:**
* **Homey App Version**: N/A
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**: N/A

**What did you try to achieve?**

I can't find Athom Somfy app on Github, would it be possible for you guys to upload it to a repository?

**What did you expect as result?**

Finding Somfy App on Github.

**What was the result?**

No where to be found..

**Any other remarks**

**Comment by bvdbos** [comment]
If the app is not on Github then the developer (in this case Athom) isn't allowed to disclose its code...
