### ISSUE TITLE
Status and Firmware page has the same tab-name and the wrong one update every minute.

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#238]
0.8.17

https://status.athom.com/ 
https://firmware.athom.com/
Both give 'Athom Status' on there tab instead of Status and Firmware.

Further is it the **wrong** site that's refresh every 30 seconds* namely https://firmware.athom.com/.

This has to be **https://status.athom.com/** because you like to know if something has go wrong while you are making flows or be testing something else.   

*noticed later that is was 30 seconds.

**Comment by WeeJeWel** [comment]
Fixed :-)
