### ISSUE TITLE
[nl.klikaanklikuit] APC2-2300R support

### ISSUE THREAD

**Issue by joopvandemerwe** [athombv/homey#2380]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by joopvandemerwe** [comment]
Will support for the new small socket and remote control APC2-2300R be included?

**Comment by bvdbos** [comment]
Could you edit your original issue (especially title but also Homey app version) and add a link to the device-description?

**Comment by ps-nl** [comment]
@joopvandemerwe, I have the same plugs and for me the already existing APA2-2300R device in Homey works to control them. You can have Homey generate a code, or copy a code from the remote. 

Functionality is already there, but it would of course be nice if the (internal) device name and icon match the physical plug.

**Comment by joopvandemerwe** [comment]
Thanks for the information. They work fine now!
