### ISSUE TITLE
[com.plugwise] Can not find my Stretch 3.1.11

### ISSUE THREAD

**Issue by andrede** [athombv/homey#2387]
I can not find the plugwise scratch 3.0 

**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: n.a
* **Smartphone Platform**: n.a.
* **Smartphone App Version**: n.a.

**If related to a Homey App:**
* **Homey App Version**: n.a.
* **Homey App Log Code**:n.a.
* **Affected Devices (preferably product codes)**:n.a.

**What did you try to achieve?**

try to connect to my stretch

**What did you expect as result?**

connection

**What was the result?**

no connection

**Any other remarks**
bought a scratch 3.0 from Plugwise, already had a stick

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
