### ISSUE TITLE
[com.aeotec] No support for 3 clamp Gen2 energy meter

### ISSUE THREAD

**Issue by gooooba** [athombv/homey#2388]
Please include support for 3 clamp Gen2 energy meter. 3 clamp meter is detected from Aeotec version from 1.6.2 but only shows one clamp.

**Comment by WeeJeWel** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
