### ISSUE TITLE
No volume slider

### ISSUE THREAD

**Issue by mvunen** [athombv/homey#239]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
Speaker volume

*Please include detailed steps how we can reproduce the issue*
There is no slider, can't reproduce :)

**What was the result?**

Nope, nakkes nada.

**What did you expect as result?**

A slider to control the volume of Homey

**Any other remarks**

**Comment by harmstellinga** [comment]
You must make a flow, there the volumeslider is availble.

**Comment by mvunen** [comment]
Thats makes no sense! I want to configure Homey's basic volume, not only for a flow.
Maybe I don't understand the reason, I only can think of set Homey's volume to a specific level at a specific timeframe...

**Comment by Dijker** [comment]
I Agree, but you can use it on aflow with an event card [on restart Homey]
(This card has to be added later in new Firmware also ;-) )

**Comment by harmstellinga** [comment]
You can connect it with , microfoon and in the when field, when you said anything.

**Comment by Fire69** [comment]
I made 2 flows now to set the volume low or high, but I would also prefer a simple slider in the settings somewhere...

**Comment by matjaz** [comment]
maybe voice settings rename to sound and add volume slider. :+1:

**Comment by WeeJeWel** [comment]
This will be added in both the mobile media view and the desktop media view.
