### ISSUE TITLE
Voice recognition reacts on random speech very often

### ISSUE THREAD

**Issue by KennethLavrsen** [athombv/homey#2390]
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**: 7F9FE4E575
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**What did you try to achieve?**
Nothing.
I was speaking to my wife in our living room not talking about Homey or anything related. In 30 minutes we experience twice that the Homey reacted on what it thought was the OK Homey command
It seems more work is needed to make this feature more robust and I have personally turned it off now.
I suggest you try and test it with random speech (find an English language talk radio channel and let is listen to it for hours)

**What did you expect as result?**
Quiet moment

**What was the result?**
Speech coming from the Homey when it was not supposed to. I have seen it happen 3-4 times now in just the first 24 hours of owning the device

**Any other remarks**

**Comment by JPe2** [comment]
Have had the same problem, did pull the power plug for ten minutes, insert the plug again and wait till Homey is started up again, then the problem was solved.

**Comment by WeeJeWel** [comment]
Hi! Thank you for reporting this issue regarding speech.

We have decided to move away from speech recognition, and will not work on issues related to the quality of this recognition as such.
Why we made this choice has been extensively described in this blog post: https://blog.athom.com/take-speech-music/

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.

**Comment by KennethLavrsen** [comment]
I agree with your strategy. It is better to let Amazon, Google, and Apple do this resource intensive task. What you should do is disable the eksperimental microphone feature by default in future releases (if you decide not to remove it). That will give new users a better out of box experience.

**Comment by chrisboer** [comment]
Of course not disable this feature by default ! let users decide for themselves. I have never experienced the issues you describe above.

**Comment by bvdbos** [comment]
I agree with you but Athom decided, due to the many comments on GH mainly:
_To be clear; we are not abandoning speech completely. Homey still has a brilliant speech interpretation engine, which is used when using Chat in the new Homey Smartphone App, when saying “Alexa, ask Homey to …” and “OK Google, tell Homey to …”. Talking to Homey itself will also still work, but as of Homey v2.0.0 this experimental feature must be enabled manually for new users, to emphasise that it isn’t fully stable._
