### ISSUE TITLE
[App V2 ] Sorting/inserting  cards not possible 

### ISSUE THREAD

**Issue by Radiotechniman** [athombv/homey#2392]
**What did you try to achieve?**
With the webapp it's possible to insert a card in between existing cards, this is not possible in the App,
and requires somone to re-do all the cards in that column 

**What did you expect as result?**
Being able to either change the cards order or insert a card in between cards

**Comment by bvdbos** [comment]
Which cards? For actions, they are executed simultanuously no matter where the card is in the list...

**Comment by WeeJeWel** [comment]
This will be added in the upcoming release!
