### ISSUE TITLE
[com.ifttt] Add numeric variable tokens

### ISSUE THREAD

**Issue by blokj** [athombv/homey#2393]
**Metadata**

arch | arm
-- | --
boot_id | 951db1bb-b842-46a1-bd6c-309aeae2f24e
cloud_id | 5aa77ff8973aff2c0d89624e
cpus | [{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":16499700,"nice":1257300,"sys":55738600,"idle":885486200,"irq":0}}]
date | 2018-04-01T16:48:53.309Z
date_dst | true
date_human | Sunday 1st April 2018 18:48:53
devmode | false
freemem | 17530880
freemem_human | 3%
homey_version | 1.5.8
hostname | Homey

Version IFTTT = 2.2.7 (beta) same issue in 2.2.5

**What did you try to achieve?**
The variable are only a(text) not #(numbers) A lot of home automation is working with % and this is nog possible.

![image](https://user-images.githubusercontent.com/37982719/38175526-e9228ba2-35dd-11e8-8a9e-835be922dbc9.png)

**What did you expect as result?**
To use numbers as variables. 

**What was the result?**
That I cannot use these variables.

**Any other remarks**

I hope you can fix this.

kind regards.

**Comment by RobinBol** [comment]
Sorry, this will not be added. I looked into it but IFTTT does not allow users to enter numbers, only text (strings), therefore it is not possible for Homey to parse the strings as numbers.
