### ISSUE TITLE
[App Store] App View On Github Missing in Mobile View

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2394]
**What did you try to achieve?**

From an app on the App Store (from my iPhone), use the “View on Github” link for the app in order to log an issue. 

**What did you expect as result?**

The link was available. 

**What was the result?**

The link was not available. You need to use a pc browser in order to see the link. 

**Any other remarks**
I tried the “View Desktop Version” option as well, but it still showed the mobile version of the site, hence still no Githubblink.

**Comment by WeeJeWel** [comment]
Fixed, should be live in ~30min.
