### ISSUE TITLE
Today is a .... not working in a flow

### ISSUE THREAD

**Issue by Luukvis** [athombv/homey#24]
When I use "Today is a..." in a flow nothing happens. 
E.g. When time is 07:30 and Today is a monday then Turn on a light Bedroom. 
When I use The month is... in stead of Today is a ... in the same flow the flow works fine. But I want to make seperate flows for the weekend and for week days.

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue, can you post a screenshot?

**Comment by WeeJeWel** [comment]
I made it easier for you though :)

![screen shot 2016-01-12 at 11 51 49](https://cloud.githubusercontent.com/assets/319873/12261677/e483acdc-b922-11e5-89bb-aa23f399a672.png)

**Comment by Luukvis** [comment]
This is my (test)flow: 
![homey-day-flow](https://cloud.githubusercontent.com/assets/16554361/12271572/1466eaac-b95c-11e5-9913-5853da516bb9.JPG)
It seems to work now, maybe thanks to the updates of Homey. In the next week I will test every day. 
But I appreciate the new item "Weekend day". Now it is easy to make only 2 flows.  
Thanks. :-)

**Comment by WeeJeWel** [comment]
Great!
