### ISSUE TITLE
[AppStore] Can’t write or edit reviews from mobile view

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2403]
**Metadata**

* **Homey Version**: N/A
* **Homey Log Code**: N/A
* **Smartphone Platform**: iOS
* **Smartphone App Version**: N/A

**If related to a Homey App:** N/A
* **Homey App Version**: N/A
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**: N/A

**What did you try to achieve?**

Go to the AppStore from your mobile (iOS 11.3, Safari in my case), go to an app and leave a review. 

**What did you expect as result?**

Clicking in the stars, shows the stars and review show, allowing you to leave a review. 

**What was the result?**

Clicking the stars does absolutely nothing...

**Any other remarks**

**Comment by Dijker** [comment]
Don't know if this is only  an case for iOS 11.3, Safari, For me on Android both Tablet as Galaxy S7 it works without problems
Did you log on to the store and install the App from that account on your Homey?
This is a change since the last Appstore Review change, a couple of days ago,
Only the Apps you installed on a Homey can be reviewed. 
Also you can't star your own Apps anymore as Developer.

**Comment by Veldkornet** [comment]
It is for an app that’s installed. I actually already did a review on the pc, so I assume it’s just the mobile view. Haven’t tried editing it via the pc.

**Comment by Dijker** [comment]
you could try to verify you are correct logged on (with an Homey Owner account) by installing an app and reviewing it from the phone. 
Would be nice to know if it is an incident it didn't work,  or something else like maybe you where not loged on from the phone or working with another fe user account.

**Comment by Veldkornet** [comment]
I only have 1 account and 1 Homey, I’ve tried on multiple apps that I have installed. Tried on WiFi and on 4G. Tried Safari, Chrome, FireFox, Brave. 

She’s not working captain.

**Comment by Rocodamelshe** [comment]
Is working here on IOS 11.2.6

**Comment by Veldkornet** [comment]
Is it possible that it could be account related?

**Comment by Rocodamelshe** [comment]
More possible that one is not logged in or app says install instead of installed.

**Comment by Veldkornet** [comment]
Hmm, for me, all of my apps say Install instead of Installed. 

I just tried on the PC now, not working there either anymore :-/
I guess then it’s not specific to mobile view. 

Still don’t know how to fix it though...

**Comment by Veldkornet** [comment]
Hmm, I just installed an app again, and it seems to have fixed itself for all of them. 

Oh well....
