### ISSUE TITLE
Toon continue program after change does not work 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2405]
* **Homey Version**: 1.5.8
* **Homey Log Code**:  
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** Toon
* **Homey App Version**: 2.0.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
![afbeelding](https://user-images.githubusercontent.com/23163409/38391031-5c97b9e8-3923-11e8-8383-cd9b28ed585d.png)

Put Toon on "Weg" and then continu progam after change does not work it remains of program off when program is off. If I read it correctly it should put the mode in "Weg" and should put the program mode to "ON" again.

**What did you expect as result?**
To have mode on "Weg"  and program mode turned "ON"

**What was the result?**
Mode turned to "Weg" but program mode remained "OFF"

**Any other remarks**
I am glad that this version works again with Toon, so ... this is something I can manage otherwise ;-) ... keep up the good work

**Comment by RobinBol** [comment]
Thanks for the feedback! As far as I understand, your program is turned off, then you execute the Flow in the screenshot, and you expect that the temperature state is set to 'Weg' and that the program is enabled?

This is not how the Flow card action is implemented currently, the dropdown is merely meant to 'resume' or 'abort' the program afterwards, not restart it. Maybe the text is a bit confusing right now. However, you could always use the 'enable program' Flow card action, and with a small delay the 'set temperature state to "weg"' (with resuming the program as dropdown option).

**Comment by chrisboer** [comment]
Changed it but I now understand the remarks
