### ISSUE TITLE
Toon device not added/visible

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#2407]
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: 366F9CEB30
* **Smartphone Platform**: Android
* **Smartphone App Version**: 0.8.5.115

**If related to a Homey App:**
* **Homey App Version**: 2.0.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Eneco Toon

**What did you try to achieve?**
Include Toon thermostat as device

**What did you expect as result?**
Toon thermostat added to device list

**What was the result?**
I did de-install old Toon device and app and updated Homey to version 1.5.9. Did install new Toon app 2.0.4 and added Toon again, but the Toon device is not added. Trying to add again gives the message "No new device found".
Toon is also not added to my device list in the flow manager.

**Any other remarks**
none

**Comment by PeterBox** [comment]
I have the same problem. I have the same versions HansieNL has

**Comment by PeterBox** [comment]
Problem solved, i don't know how just tried adding toon  this morging again en it works

**Comment by chrisboer** [comment]
Because of new version maybe ;-)

**Comment by HansieNL** [comment]
Don't know what happened, but Toon thermostat is  finally added to devices again.

**Comment by HansieNL** [comment]
Don't know what happened, but Toon thermostat is  finally added to devices again

**Comment by HansieNL** [comment]
Don't know what happened, but Toon thermostat is  finally added to devices again
