### ISSUE TITLE
[com.osram.lightify.zigbee] Gardenpole RGBW

### ISSUE THREAD

**Issue by rogerjak** [athombv/homey#2409]
Please add support for the Osram Gardenpole RGBW (not the mini one).
Fork that already implemented it is here:
https://github.com/JohanBendz/com.osram.lightify.zigbee

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
