### ISSUE TITLE
Cannot voice activate a flow

### ISSUE THREAD

**Issue by coldshivery** [athombv/homey#241]
Homey version: 0.8.20

**Tried to activate a flow to turn off the led ring** and say let homey say "goodnight".
I wanted to activate the flow by saying "goodnight".

I tried to change my activated "microphone" text to "good night" and even "shut up" but homey does not want to trigger the flow by voice. Only when i manually click "test" the flow it fires.

**What was the result?**
Nothing.

**What did you expect as result?**
Homey to turn off the led ring by my voice command.

**Any other remarks**
Seems voice activated flows do not work yet?

**Comment by matthijsvdr** [comment]
I think https://github.com/athombv/homey/issues/128 might be the same problem your having :)

**Comment by coldshivery** [comment]
Thanks for pointing that out searching for "voice flow" or similar did not find any results so i opened this issue.
