### ISSUE TITLE
Will Athom release a Samsung Smartthings app?

### ISSUE THREAD

**Issue by JohanBendz** [athombv/homey#2411]
Hi.
Are there any plans from Athom to release a Samsung SmartThings app?

**Comment by Radiotechniman** [comment]
I think you might get more response through the forum, this git is only for issues not questions..

**Comment by lubbertkramer** [comment]
Git is for issues and feature requests but maybe indeed in this case it's better to ask support@athom.com. I know the hardest part of Samsung is they don't open up their eco (API) for other players at this moment so maybe Athom can find a way in

**Comment by JohanBendz** [comment]
Yeah, I would surely get a faster reply directly from someone at Athom but then all else would still not know :)

**Comment by JohanBendz** [comment]
Answer from Athom via email was "not planned". Case closed. :)
