### ISSUE TITLE
Brel motor does not respond / homey does not pair

### ISSUE THREAD

**Issue by Goort** [athombv/homey#2412]
**Metadata**
Brel, rf, homey, pairing, copying signal from remote

* **Homey Version**:
1.5.8
* **Homey Log Code**:
B56895C881
* **Smartphone Platform**:
N/A (IOS)
* **Smartphone App Version**:
N/A (1.3.3)

**What did you try to achieve?**

Opening/closing my curtains. This worked for around a month perfectly until this week when it stopped working without me changing any settings or flows.

Then, I tried restarting homey, rebooting homey, restarting the Brel app several times. This did not resolve the issue.

Sequentially I have deleted and re-installed the Brel app which I used before. Now, the remote does not pair anymore. **I know this has been an issue before and that this was resolved with a new firmware update, however, it seems that the issue has returned**. And yes, I have tried pairing the remote several times, have pressed the buttons repeatedly and have tried holding it for minutes. I have killed any surrounding signals etc.

**What did you expect as result?**

My curtains opening/closing as they did before.

**What was the result?**

Nothing has happened, now I can't even pair the remote with Homey

**Any other remarks**
Please solve this asap :).

**Comment by BasKiers** [comment]
Hi,

We expect this issue is caused by the same issue explained here #2023 
We are currently working on solving this issue as soon as possible.

If this issue still persists after the above issue is resolved please don't hesitate to open a new issue.

Regards,
Bas
