### ISSUE TITLE
Lightwave RF devices stopped working with version 1.5.9

### ISSUE THREAD

**Issue by FrankBakermans** [athombv/homey#2415]
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**:
* **Smartphone Platform**: Android
* **Smartphone App Version**: v0.8.5.11

**If related to a Homey App:** Lightwave RF
* **Homey App Version**:v0.0.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: handheld remote, plug-in On/Off

**What did you try to achieve?**

Switch lights on with Lightwave RF devices

**What did you expect as result?**

The Lightwave RF devices to respond to Homey and switch on the lights

**What was the result?**

Since Homey update 1.5.9 all Lightwave RF devices stopped responding to homey 

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Can you help us by confirming if the issue persists through a power-cycle of Homey (Unplug Homey for at least 10 seconds and try to reproduce the issue)? You may also want to take a look at the following [support article](https://www.athom.com/en/support/KB000039/).

**Comment by FrankBakermans** [comment]
Hi Jeroen,

 

That did the trick, all lightwave RF devices are working again.

 

Thanks,

Frank

**Comment by FrankBakermans** [comment]
A power-cycle of Homey (Unplug Homey for at least 10 seconds and try to reproduce the issue) fixed the issue.
