### ISSUE TITLE
Cannot re-pair / Re-add Toon after upgrade to 1.5.9

### ISSUE THREAD

**Issue by epjjansen** [athombv/homey#2416]
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: D8FF7AD2F8
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App: Toon
* **Homey App Version**: Toon® v2.0.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Toon

**What did you try to achieve?**
Re-pair Toon to Homey. Is not possible
Removed Toon
Add Toon to Homey. 
Popup with email and password for Toon

**What did you expect as result?**
Toon added to Homey

**What was the result?**
No new device found

**Any other remarks**
Removed Toon App.
Reinstalled App
Repeated same steps to Add Toon to Homey
Same result

**Comment by bvdbos** [comment]
https://github.com/athombv/homey/issues/2271#issuecomment-379465012
better to continue in #2271 ?

**Comment by kukel** [comment]
Reboot Homey (PTP, remove power for > 10 seconds)... I needed to do that before I could add Toon again after 15.8... Homey and Toon integration sucks.

**Comment by epjjansen** [comment]
I did the same to fix the problem.
I will close this issue and wait when the solution is provided for the integration of Homey with Toon again
