### ISSUE TITLE
Icon to popup for flipping a socket from the device card dissapears and generates a #500 error

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#242]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
Flip a socket from the devices menu

**Please include detailed steps how we can reproduce the issue**
Add a socket to a room. Go to the device card in the devices menu and try to open the pop up where you can flip the socket. On hovering the card the icon to open the pop up is shown but when trying to click the icon the icon dissapears and I'm unable to open te popup.

**What was the result?**
Upon clicking the location where the icon for flipping the socket should be the settings popup for the device is opened. Upon clicking the device card in the upper top left corner (with offset to where the icon for flipping the switch used to be) a 500 error is generated:
GET http://<<ip>>/api/device/decf7fd7-...-11deeb24d1f0/?_=1456437682440 500 (Internal Server Error)

**What did you expect as result?**
Open the popup where I could flip the socket.

**Any other remarks**
At first I thought it was related to zwave issue which persist in 0.8.20 but this also happens with a kaku socket.

**Comment by Dennishacq** [comment]
Hi @jghaanstra 
With what app and device are you experiencing this problem?

**Comment by jghaanstra** [comment]
It happens on any device card unrelated to apps or devices but I mostly have z-wave devices. If I run into the issue where I can not get to the device status popup I move the device card around in the room view and by changing the order of the device cards in a room eventually the device status option of the device I want to control become available to click on. It's a strange issue, I'm not at home right now but if needed I can make a screencast that will show the issue after the weekend. Let me know if this would help.

**Comment by Dennishacq** [comment]
@jghaanstra That would definitely help me find the problem because i haven't seen this bug before.

**Comment by jghaanstra** [comment]
@Dennishacq and @ocatie 

Just thought I'd mentioned you both as I found out this UI bug is related to the z-wave time-outs of devices which is reported in this issue: https://github.com/athombv/homey/issues/346. If I do a power cycle and directly refresh all zwave nodes so all zwave devices are at the time manageble, this issue does not occur. But when there are z-wave devices that have timed out (as shown in the video below) this UI bug appears. When this happens some z-wave device that do not display the time out message can not be controlled either because they are greyed out and do not show consumption (this can be seen in the video as well).

As I cant refresh zwave nodes without a power cycle because of this issue https://github.com/athombv/homey/issues/351 (which can be seen in the video as well) I'm kinda running in loops and having a hard time managing my zwave devices as I need to reboot every 5 minutes or so.

I hope this video helps in troubleshooting at least this UI issue although I'd rather see the z-wave network more stable so this UI bug would not appear at all and I would not have to refresh the nodes all the time. Let me know if I can do anything else (like giving access to my Homey).

https://www.youtube.com/watch?v=sGfZ5UW0HTk

**Comment by jghaanstra** [comment]
This issue still persists in 0.8.27. Did my screen recording give enough insight into the issue or do you need more info @Dennishacq ?

**Comment by jghaanstra** [comment]
This issues seems to be solved in at least 0.8.34. Issue closed.
