### ISSUE TITLE
Missing functionality in the Homewizard App (e.g the Windmeter)

### ISSUE THREAD

**Issue by hlvdzande** [athombv/homey#2420]
**Metadata**

* **Homey Version**:1.5.9
* **Homey Log Code**:
* **Smartphone Platform**: Android 7.1.1
* **Smartphone App Version**:0.8.5.115

**If related to a Homey App:** Homewizard
* **Homey App Version**:v0.1.7
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**
Please add Windmeter functionality to current Homewizard app.

**Comment by Dijker** [comment]
Hi hlvdzande, 
The Homewizard App is a Community App, 
this issue tracker is for Homey and Athom Apps.

Please create Issue's for the HomeWizard App here: https://github.com/jeroenbos22/com.homewizard/issues
or contact @jeroenbos22 at Slack or the Forum https://forum.athom.com/discussion/1640/homewizard/p1

**Comment by hlvdzande** [comment]
I just did :-)

2018-04-10 21:47 GMT+02:00 Dijker <notifications@github.com>:

**Comment by Inversion-NL** [comment]
Then you'd could close this issue 😉
