### ISSUE TITLE
[Device Request] Yale Keyfree Connected lock 

### ISSUE THREAD

**Issue by ks2018ks** [athombv/homey#2421]
Hi I have a Yale Keyfree Connected lock (https://products.z-wavealliance.org/products/1358), which seems is not on the list of devices supported by either of the two apps in the store.  One of the developers says in his product description:
"It may work with other locks from the same range, but I haven't tested that. Would likely require additional productIds to be added to the app.json."

Not being a developer I've no idea what this involves.  Could somebody help?

Thanks

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
