### ISSUE TITLE
Fibaro wall plug not recognized - Unknown Z-Wave device

### ISSUE THREAD

**Issue by PitVM** [athombv/homey#2422]
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).

* **Homey Version**:
1.5.8

* **Homey Log Code**:
A071A6B222

* **Fibaro App Version**:
1.5.17

* **Affected Devices (preferably product codes)**:
Manufacturer ID 271
Product Type ID 1538
Product ID 4099
Firmware 1554

**What did you try to achieve?**
Tried to include a new wall plug which resulted in an "Unknown Z-Wave device"

**What did you expect as result?**
An operable wall plug
![unknownzwavedevice](https://user-images.githubusercontent.com/34789557/38637762-6a4104fc-3dcc-11e8-937e-c568eaabd043.png)

**Comment by bvdbos** [comment]
https://github.com/athombv/com.fibaro/blob/7a556c4d66d540514fdb4b68134ff9168fa965cb/config/drivers/FGWPx-102-PLUS.json#L9
https://github.com/athombv/com.fibaro/blob/6a7130c67df36dc9f16cf23526cf1b5b3b686c54/app.json#L11736

**Comment by MatthewWaanders** [comment]
I've noticed that the productID is not listed as one of the Z-Wave plus plugs, and of course I've added it in.

You should see an update coming your way soon!

**Comment by PitVM** [comment]
Thank you so much for the prompt follow up and feedback!!

**Comment by MatthewWaanders** [comment]
The update has since been released, so I'm closing this issue. Might you still have problems adding the device please re-open this issue.
