### ISSUE TITLE
[nl.klikaanklikuit] ACC-2300 add support

### ISSUE THREAD

**Issue by Gizwarrior** [athombv/homey#2429]
Can you please add support for the simple 433mhz powerplug receiver from KAKU?
Name: ACC-2300

**Comment by Dijker** [comment]
Hi! 
KAKU uses one standard signaling and almost all their 433 devices function the same. 
as reported by an other user here https://github.com/athombv/homey/issues/2380#issuecomment-379232729 you can use them as one of the other devices, like the APA2-2300R

Athom use GitHub for issue tracking in existing software only. 
Request for support of new devices can be done in a new Form: https://go.athom.com/request-device-support

Please continue to report any bugs you may encounter in the future here.

(if it works, please report back and close this issue yourself ;-) )

**Comment by Gizwarrior** [comment]
Wow, it works! Perfect, thank you very much!
