### ISSUE TITLE
Javascript issue with jquery.nicescroll.js

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#243]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
Browse the GUI from my Homey.

**Please include detailed steps how we can reproduce the issue**
Just browse the GUI with the console open.

**What was the result?**
A javascript error:
```
Uncaught TypeError: Cannot create property 'scrollable' on boolean 'false'onResize @ jquery.nicescroll.js:2(anonymous function) @ jquery.nicescroll.js:1
jquery.nicescroll.js:2 Uncaught TypeError: Cannot create property 'scrollable' on boolean 'false'onResize @ jquery.nicescroll.js:2(anonymous function) @ jquery.nicescroll.js:1
```

**What did you expect as result?**
Well, browsing the GUI works just fine but it seems some resize function is not working the way it should.

**Any other remarks**
Nope, but doesnt seem like a high priority bug unless it causes other javascript issues.

**Comment by WeeJeWel** [comment]
Thanks, fixed in 0.8.21
