### ISSUE TITLE
[com.sonos] Suggest adding ability route homey speech to sonos 

### ISSUE THREAD

**Issue by pohomey** [athombv/homey#2431]
**Metadata**

* **Homey Version**:
1.5.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Tried to select Sonos as speaker when making homey speak

**What did you expect as result?**

Get homey speak through sonos

**What was the result?**

Nothing happened.

**Any other remarks**
This might be an issue with the feature set on the homey speak side

**Comment by jeroenvollenbrock** [comment]
Unfortunately, due to the delays on the sonos side when sending a command to play audio, the quality of such a solution was deemed too low to actually be useful. It is however possible to use the alexa integration to talk to homey on a sonos one.

**Comment by pohomey** [comment]
Not sure I follow, or perhaps I was not clear. What I was talking about was sendin a one-way voice spoken message from Homey to Sonos, not he other way around. Thus delay of a few seconds would not be an issue, as not return interaction is expected. However a minute delay would be too much. Third party iOS apps such as Sonos speak, Intercom have one/a few seconds delay but still work quite well.
