### ISSUE TITLE
[com.fibaro] Describe your issue here

### ISSUE THREAD

**Issue by vantilight** [athombv/homey#2432]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment]
This is an empty issue ?

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #2267
