### ISSUE TITLE
Homey Crashed!

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#2433]
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: N/A

**What did you try to achieve?**
Tried to download the some insights (9 months old). Suddenly unresponsive page and now homey is offline, probably need a PTP.

**What did you expect as result?**
Donwload the CSV file/

**What was the result?**
Offline Homey.

**Comment by Arjanvde** [comment]
Not sure how, came back online, log AA9E06FC22

**Comment by Dijker** [comment]
I guess related to #2110 and other comparable  issues.....

**Comment by jeroenvollenbrock** [comment]
Closing as duplicate of #2110
