### ISSUE TITLE
[com.milight] iBOX v6 RGBWW turn off night mode not possible in flows

### ISSUE THREAD

**Issue by eelco2k** [athombv/homey#2434]
Is there a possibility to "turn off" night mode in the flow editor for RBBWW bulbs with the iBox. There is a flow card "turn on" night mode, but for some reason the flow card "turn off" doesn't turn off the night mode.

**Comment by RobinBol** [comment]
There is no command to turn off the night mode for the iBox v6. You could however just increase the brightness or set a different color!

Closing this issue, since it is a device limitation. Thanks for the feedback though!
