### ISSUE TITLE
[Request] Add the Smartwares curtain/sunscreen receiver SH5-RBU-04A

### ISSUE THREAD

**Issue by AlainBijl** [athombv/homey#2436]
Hi,

I have the SH5-RBU-04A curtain/sunscreen receiver. I can pair it with the SH5-RPS-XXX in the Homey and than it works. But when pressing On my sunscreen goes out fully and when pressing Off it completely shuts. So there is no way to stop it. Can I help somehow to add the SH5-RBU-04A to the Homey so that it works correctly?

I also tried to use it as a Klik Aan Klik Uit ASUN650, but then it goes out a little and than stops when pressing Up and pressing Down it goes in a little and than stops.

Best regards,
Alain

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.

**Comment by AlainBijl** [comment]
I filled in the request form almost 4 months ago and haven't heard anything back yet. :(
