### ISSUE TITLE
'Extreme' colors cannot be selected in App V2 due to color seletor limitation

### ISSUE THREAD

**Issue by kukel** [athombv/homey#2437]
**Metadata**

* **Homey Version**: N/A
* **Homey Log Code**: N/A
* **Smartphone Platform** Android
* **Smartphone App Version**: 0.8.5.115

**What did you try to achieve?**

Select colors to the extreme left/right/bottom (not related to 'bottom' happens in the middle of the color selector too at the left and right

**What did you expect as result?**
Being able to select the most 'extreme' colors.

**What was the result?**
The center of the color selector circle is not at the most extreme points since the circle border 'collides' with the right/left/bottom (does not happen at the top)

**Any other remarks**
You can see that if you choose the red color in the bottom/right in the Homey App (is not that easy, sometimes it ends up being a purple variant) and then switch to the Hue app (in my case) you can select more vibrant colors.

**Comment by WeeJeWel** [comment]
Thank you for reporting, but the color picker will be changed in the upcoming version, so this issue won't be applicable then.
