### ISSUE TITLE
[com.somfy] Currently experiencing issues with blinds that don't respond in flows or somethimes even with 1 manual cmd. second command does work.

### ISSUE THREAD

**Issue by leroyneels** [athombv/homey#2438]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by JPe2** [comment]
one hour before you wrote this, there was an update on the Somfy App, do you still have the same problems? Did you experiment with the different time-settings?
![image](https://user-images.githubusercontent.com/3833862/38944025-18b0da92-4333-11e8-89b5-76dba4130232.png)

**Comment by leroyneels** [comment]
I'll check what the update will bring.
i've adjusted times after i got some issues. in the beginning i could set
all the settings for every blind to korste (shortest) signal and whey would
work fine..
Currently there is some error but not sure if it's homey (hardware) or a
software issue.

kind regards,
met vriendelijke groet,

Leroy Neels

2018-04-18 18:05 GMT+02:00 Jan <notifications@github.com>:

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by leroyneels** [comment]
The Issue seems to be resolved.

kind regards,

Leroy Neels

2018-04-30 11:57 GMT+02:00 Jeroen Vollenbrock <notifications@github.com>:
