### ISSUE TITLE
KAKU - Homeys RF433 dies after pairing/learning (fe Blinds , Contact Sensor, etc.)

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#244]
**What is your Homey version (Settings → System)?**
0.8.20
KAKU 1.0.14
**What did you try to achieve?**
Add a a Blinds (ASUN650)
**Please include detailed steps how we can reproduce the issue**
Booted Homey
Tried KAKU Code Checker (AYCT-102) Buttons work as expected - Cancel.
Add Device - Blinds  - Create New Signal 
The Switch doesn't react on this - finish adding this dummy Blinds.
Tried KAKU Code Checker (AYCT-102) => Homey doesn't react on keys pressed.
After Powercycle Homey KAKU Code Checker works again. 
Repeated -> Homeys RF433 dies again.
Recovered Homey to defaults (wipe data) Re-tested it, same again. 

**What was the result?**
Pairing ASUN650 does not work
KAKU Code Checker does not work after that either.

**What did you expect as result?**
That paring and the Code Checker just work as expected

**Any other remarks**
Doorbell (Pushbutton ACDB-7000A) still doesnt work either. (Not recogniced in Code checker)
Contact Sensor (AMST-606) worked in Code Checker, tried to add, Homeys RF433 dies again.
Powercycle Homey
Motion Sensor - MDT-1219 Learned -Worked as expected.
again: Contact Sensor (AMST-606) worked in Code Checker, tried to add, Homeys RF433 dies again.
3rd time Contact Sensor added  successful, 
Added remote (AYCT-102) 
Tried to add Socket - Create New Signal -> Not working 
Homeys RF433 dies again. - Restart Homey
Tried to add Socket again - Copy Signal - (AYCT-102 - Ch1 But 1) OK - Plugged in Kettle => Empty Device card, no  option to test device (like the other type Socket)
No Flow card for Socket type Kettle in Flows!
![image](https://cloud.githubusercontent.com/assets/12412734/13338067/63b97922-dc1f-11e5-8f89-7acb039e8f34.png)
Now Doorbell (Pushbutton ACDB-7000A) recognized in Code checker (picture)
![image](https://cloud.githubusercontent.com/assets/12412734/13338174/f7a861b6-dc1f-11e5-9e2d-6acd793fd733.png)
but still not able to pair the doorbell.
etc. etc.

**Comment by Dijker** [comment]
Tried to reanimate the RF433 with reboot, this doesn't work. a Power-cycle is necessary to get things working again.

**Comment by Qx5** [comment]
I had the same problem of KAKU devices not working shortly after adding (0.8.20 and 1.0.14). power-cycle did the trick. Would be nice if at least the software reboot would fix this since fiddling with the power cord always takes me a minute or so.

**Comment by Dijker** [comment]
Version 0.8.22 / KAKU v1.0.14
Today after testing and learning KAKU switch KAKU/RF433 died again on firmware 0.8.22
Tested several things receiving and sending KAKU.
Soft Reboot triggered a KAKU switch that I tried before but didn't work
After reboot tried again and triggered it within 10 minutes.
Send log: 
48CDE3342F

**Comment by ReinierH** [comment]
@Dijker 
Was it only kaku that stopped working?

**Comment by Dijker** [comment]
I only have KAKU on 433 and no other 433/868  devices (beside the nonsupported older HomeEasy and others). 
NFC Worked, Speech worked, Flows triggered on NFC and LED Ring still gives feedback on actions.
Learning a IR Remote still works...
Also the http interface still responds normal (Flow, Insight, Settings, etc.)
Again after sending and pressing reboot a test-flow to trigger an asun650 triggers the switch in the reboot and after reboot 433 works normal again.
Tried again this moning: 0E367B4BC5
