### ISSUE TITLE
Speech overview not correctly visible

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2443]
* **Homey Version**: 1.5.9
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Select speach command 

![afbeelding](https://user-images.githubusercontent.com/23163409/38991540-64d1888a-43de-11e8-974a-98c00ea65efd.png)

**What did you expect as result?**
Clear overview

**What was the result?**
That I don't see what is installed etc. see screendump

**Any other remarks**

**Comment by JPe2** [comment]
Hover over the lines, and you will see some choice-windows
![clipboarder 2018 04 25](https://user-images.githubusercontent.com/3833862/39258177-a65bef82-48b3-11e8-8e49-2ef459c5ea0a.png)
For a different language look at the tab "Taal". There are only 4 choices: English/Dutch /\ man/woman

**Comment by jeroenvollenbrock** [comment]
It seems like the installed voices are not visible while a voice is being downloaded.

We are no longer taking enhancement requests and minor bugfixes for the desktop interface, due to it's incoming deprecation. The problem will be resolved in the new smartphone app.
