### ISSUE TITLE
[nl.philips.hue] Can't pair after firmware update of bridge

### ISSUE THREAD

**Issue by Strike2001** [athombv/homey#2444]
i can t pair my hue bridge s (3pcs ) with the new firmware ? can you correct this asap ?

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by WeeJeWel** [comment]
Please provide more information, like the error you are receiving and create a new issue.
