### ISSUE TITLE
[nl.philips.hue] Card 'Blink the card (short)' does not use parameter 'turned on'

### ISSUE THREAD

**Issue by yemoH** [athombv/homey#2446]
**Metadata**

* **Homey Version**:
 1.5.9
* **Homey Log Code**:
C8CEA115AC
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I created a flow to 'blink the light (short)' for a Hue E27 color bulb, when there is a certain 'when' and 'if' condition.

**What did you expect as result?**

I expect the light bulb to return to the original state after the blink is completed. 

**What was the result?**

The light bulb returns to all the original conditions, like dim level, hue, saturation, temperature and light mode, except for 'turned on'.  As a result when I activate a blink when the light bulb is on, everything works as expected, since the light bulb is already on, however when I activate a blink when the light bulb is off, the light bulb stays on after the blink at the settings stored in dim level, hue, saturation, temperature and light mode. I feel the parameter 'turned on' is not used to determine the status of the light bulb after the blink.

**Any other remarks**
I was able to reproduce this situation multiple times with different parameters for the light bulb.

**Comment by yemoH** [comment]
I forgot to mention that I use the Hue bridge and the Hue app from Athom. https://apps.athom.com/app/nl.philips.hue

**Comment by Rocodamelshe** [comment]
Can confirm this.

**Comment by WeeJeWel** [comment]
We cannot really fix this, as this is how Philips Hue behaves. The only solution would be to add a timeout, however, we do not know how long a blink is (as it's not officially specified).

**Comment by yemoH** [comment]
Thank you for your help. It is working on my end!
