### ISSUE TITLE
[com.qubino] Describe your issue here

### ISSUE THREAD

**Issue by jan-siesjo** [athombv/homey#2447]
Using Homey with the Qubino app it does not recognise the ZMNHID1 Flush mount thermostat. That exact part no is not in the supported lit but the Flush mount thermostat is. Is this something that can be fixed or is there some workaround?

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** Qubino
* **Homey App Version**: 1.1.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Include a new device, device is included but only as generic device.

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
