### ISSUE TITLE
[nl.alecto] could we add ws 4500

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#2455]
Hi,

Could we add the device ws 4500, the part of the wind meter and direction and temperature. Thanks!

Information about the protocol:

http://www.nodo-domotica.nl/Download/Stable/Plugins/Plugin_008.c

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
