### ISSUE TITLE
[Feature] Introduce proper Google Assistant Home Automation skill

### ISSUE THREAD

**Issue by synegic** [athombv/homey#2457]
I'd like to request allowing direct integration of Homey's linked devices into Google Assistant. This way we can use Google Assistant's built-in default speech logic (such as turn off all lights in room x) without having to prefix all our commands with 'Ask homey' or shortcutting every single room/default action.

As far as I can see, this is pretty much very possible; https://developers.google.com/actions/smarthome/create-app. I hope Athom can take a look and consider introducing support for this, like they did with Alexa. Especially now voice will not be further developed.

Thanks in advance.

**Comment by lubbertkramer** [comment]
Using the search sound give you this request -> https://github.com/athombv/homey/issues/2159

**Comment by synegic** [comment]
Ah, my bad. I did search before posting, but not on that terminology. Google Assistant != Google Home, as Google Home would be the product (and app to manage the devices), Google Assistant the actual service (skills, etc.). At least, that's how I understood it.

Closed.
