### ISSUE TITLE
[app store] install count is 0

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#246]

**Comment by hilvarenbeek** [comment]
I noticed this as well. As the submitter of an app you can see the installed count of your app in the Athom App Store but it stays at 0 (both versions of the Marantz app in my case)

**Comment by Zwoops** [comment]
I'm having this issue as well

**Comment by joachimroeleveld** [comment]
Yes, this is a known issue and it will be fixed in the near future.

**Comment by joachimroeleveld** [comment]
I can confirm that this is fixed in the latest (just deployed) release.
