### ISSUE TITLE
[com.aeotec] Support req for Nanoswitch Dual ZW140

### ISSUE THREAD

**Issue by westd05** [athombv/homey#2463]
* **Homey Version**:  1.5.11-rc.1
* **Homey Log Code**: D510CD1D14
* **Smartphone Platform**:
* **Smartphone App Version**:

* **Homey App Version**: 1.6.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Aeotec Nanoswitch Dual ZW140-C
Info: 
https://aeotec.freshdesk.com/helpdesk/attachments/6052990282
https://aeotec.freshdesk.com/support/solutions/folders/6000229883

**What did you try to achieve?**
Adding the Aeotec Nanoswitch Dual Zwave device ZW140

**What did you expect as result?**
A device added.

**What was the result?**
It didn't recognise the device.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
