### ISSUE TITLE
[eu.elro.flamingo] Please add support for device SF-501WD/2

### ISSUE THREAD

**Issue by efriethoff** [athombv/homey#2466]
Thank you for supporting the brand Flamingo and its devices!

Unfortunately for me, the outdoor powersocket is (not) yet supported and I would like to take this opportunity to ask to support this device too: Set SF-501WD2  | 10.100.87

It is the outdoor powersocket sold as a set by Action and would be more than welcome for usage in the garden to switch on/off some lights and other stuff :)

I hope you can add this device,

Cheers,
Eric

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
