### ISSUE TITLE
Need support for Qubino Flush Shutter DC ZMNHOD1

### ISSUE THREAD

**Issue by DavidDjerf** [athombv/homey#2468]
Qubino Flush Shutter DC ZMNHOD1 is not supported by the Qubino App.
I have several of these devices to control my bilnds.
Please add support asap! :)

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.

**Comment by DavidDjerf** [comment]
Ok. I just clicked the "Report an issue"-button in the "apps" store.
