### ISSUE TITLE
[app store] app rating on home and details is not the same

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#247]
it looks like on home `average` is used , but on details I see `currentUser ` rating.

**Comment by matjaz** [comment]
I guess this is expected. But I have a problem with my apps. I can't change rating.

**Comment by joachimroeleveld** [comment]
Your first remark is intended behavior. On the overview, you see the average rating and on the detail page you see your own vote. Once you come back at the page, it's not very clear that you voted, I admit. I may change that in the future. Can you describe in more detail why you can't change the rating?

**Comment by matjaz** [comment]
This happens only with own apps. I was able to disable star hover and click handlers when changing versions of app. Hovering start and clicking on it does not react.
After refreshing whole page it works again as expected, so actually not a high priority.

**Comment by joachimroeleveld** [comment]
For now, I cannot reproduce this. Will keep it in mind though; thanks.
