### ISSUE TITLE
Voice trainer goes bezerk

### ISSUE THREAD

**Issue by edtst** [athombv/homey#248]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
I tried to use the voice trainer

*Please include detailed steps how we can reproduce the issue*
Train your voice in a room with, for example, a pc.

**What was the result?**
Homey is so sensitive that the buzz of my pc makes the red ring go bezerk. This also happens if a car drives by, the cat walks etc. 

Effectively, I cannot train my voice....

**What did you expect as result?**
Homey starts recognizing my voice.

...

**Any other remarks**

...

**Comment by ralfvd** [comment]
I have the same result in 0.8.20 ; it will constantly "blink" a red ring when trying to train the voice

**Comment by hilvarenbeek** [comment]
Same here. A reboot, poweroff/poweron, upside-down reset without wipe all didn't help. It gets stuck in learning mode and even after navigating away from the settings page, it still shows a red ring every few seconds.

**Comment by harmstellinga** [comment]
Same here, i did even a reset with full erase, nothing helped, though exactly above the same story.
The red ring shows here already for 20 min, with no hit.

**Comment by TedTolboom** [comment]
Same issue here..
Voice recognition worked ok on 0.8.17 (after initial voice training), except for the issue with multiple flows with voice trigger (other issue)

After updating to 0.8.20 I noticed that not all flows responded on my voice.
Removed all voice triggered flows (did not resolve the issue).
Homey was not reacting to the basic voice commands (time / how are you)

So I decided to do a reset with full erase...

Now if I start the voice training, continuous red rings even if I say nothing.
If I disable (clear checkmark) of the option "use microphone", the red rings stop.
If I re-enable the "use microphone" option, Homey provides error message that Homey already is in the learning mode. Only option is to reboot Homey.

Full erase performed multiple times.. including re-installation of voices. No joy..

**Comment by TedTolboom** [comment]
Based on a suggestion of Panda on the Athom forum ([Version 0.8.20 topic](https://forum.athom.com/discussion/875/version-0-8-20#)), I tried the following:

Directly after a full reset (without voice training), Homey was not listening to me (reacting on "ok homey" or " hey homey"...

So I switched to the Dutch language (with recommended reboot)... still not listening...
Switched back to English language (with reboot)... still not listening

Started voice training and was expecting multiple red rings... 
but Homey recognised my "hey Homey" pretty good... I think I only saw 2 red rings...

Now Homey is listening again!   :)  Switching back and forth the language might have done the trick for me... I will check if I can reproduce this evening..

**Comment by TedTolboom** [comment]
I tried to reproduce above mention steps... partly successful  :p 

It's not the switching of languages (and thus the possible update of the corresponding settings), but the reboot after the full reset (part of the change of language routine) that solved my issue (unable to complete voice training).

I'm able to get good response if the following steps are taken:

1. Full reset (clear all data) by turning Homey up-side-down
2. Wait until the voice has been downloaded (blue ring is off and verify in settings)
3. Reboot Homey (Settings > system > stuff for geeks > reboot).
4. Then do the voice training... I only needed 6 attempts to complete the training with "Hey Homey"  :) 

So in addition to the suggestion @Panda  made also apply a reboot after the full reset.

In the first attempt, I also reproduced the fact that directly after a full reset (clear all data), voice recognition is not (yet) working and voice training cannot be completed (red rings)

Hope this is solving more issues with voice training / recognition.

**Comment by TedTolboom** [comment]
I don't know if this problem could have been avoided if after the software update (0.8.17 to 0.8.20) Homey would have been rebooted. I don't recall if this was part of the SW update routine.

**Comment by vogon1** [comment]
I had same problem. Please check your LED ring, if it is below 100% brightness, this problem occurs. Setting it to 100% restored voice recognition for me. A developer posted a comment about this bug somewhere.

**Comment by TedTolboom** [comment]
I also noticed the same remark on the forum.. And recognize that after successful passing the voice training and first tests, after playing with some flows (adjusting the brightness of the LED ring), voice recognition is lost...
I will give it a try this evening.

It does raise my concern that this might not be only a SW bug...

**Comment by ralfvd** [comment]
I did some tests:

Voice training started with LED < 100 % : training going bezerk (red LEDs with the slighest of sound)
During training, switching to LED 100 % (in settings) : training goes OK ( still reds, but based on my voice, not on background noise)
Then switching back to < 100 % : bezerk again
back to 100 % : training OK ( as in: not bezerk , getting green lights still difficult )

**Comment by bvdbos** [comment]
can be closed...
