### ISSUE TITLE
No login possible in the Siemens Home Connect App, rejects credentials.

### ISSUE THREAD

**Issue by CBR1100xx** [athombv/homey#2480]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I'm trying to enter the login and password for Siemens Connect to connect homey to my Siemens dryer.
Both the beta and the stable version app wont get connected in Homey to Siemens Connect.
The  password reset link doesn't work in Homey either.
Online in the web I've reset my password but the Homey app  keeps on having login problems to Siemens, no valid connection on given credentials.

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by WeeJeWel** [comment]
Could you post a screenshot of the error message?

**Comment by CBR1100xx** [comment]
I wanted to make some screen-dumps and to my surprise it works.
So no screenshots. Don't know why but it seems solved.

Close.

Harald
