### ISSUE TITLE
[com.somfy] Describe your issue here

### ISSUE THREAD

**Issue by prenger** [athombv/homey#2482]
**Metadata**

* **Homey Version**:1.5.11
* **Homey Log Code**:78E17B4BB2
* **Smartphone Platform**: Apple
* **Smartphone App Version**: 11.4

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

while installing the app it shows on the install page a picture of a blinds remote control SOMFY 74300,
after installing it shows only the use for 1 blind screen not for four like the remote 74300 can be used,
when will this remote add to the software, now my screens go all at once up or down in stead of to chose which one of the four.  

**What did you expect as result?**

**What was the result?**

**Any other remarks**
please add the other remote

**Comment by jeroenvollenbrock** [comment]
You need to add to pair every blind screen separately to homey, after which they should be controllable separately as well, instead of pairing by group address. For further support regarding this please refer to support@athom.com instead of using the bug tracker.
