### ISSUE TITLE
Zigbee mesh not created

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#2491]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:1F4307254B
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** Xiaomi Mi Zigbee App
* **Homey App Version**: v0.40 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Xiaomi Zigbee Aqara

**What did you try to achieve?**

I have added 8 Zigbee devices to Homey, both battery devices and mains powered versions. The mains powered are recognized as 'routers', however all devices are routed directly to Homey. A mesh is not created.

**What did you expect as result?**

A Zigbee mesh, using the routers to create a stable mesh and extending the Zigbee range.

**What was the result?**

No Zigmee mesh.

**Any other remarks**
![schermafbeelding 2018-05-28 om 10 30 12](https://user-images.githubusercontent.com/10754229/40606083-8a434d66-6264-11e8-9ce4-539ae1c275e6.jpg)

**Comment by jeroenvollenbrock** [comment]
The direct route to the cooordinator is always preferred in the zigbee mesh network. As soon as a direct connection is unstable or not possible, the mesh network will automatically pick a meshed route.
