### ISSUE TITLE
[nl.nefit.easy] After serverside nefit update, the app doesnt work anymore

### ISSUE THREAD

**Issue by HennieLeermans** [athombv/homey#2494]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:2E0DD0487D
* **Smartphone Platform**:ios
* **Smartphone App Version**: 1.3.3 build 70

**If related to a Homey App:**
* **Homey App Version**: Nefit Easy 1.0.7

**What did you try to achieve?**
Any contact with the nefit easy thermostat is not working anymore after an update on their side.

**Any other remarks**
There is a update of the nefit easy http server, i asume you can use this information to update your app. https://github.com/robertklep/nefit-easy-http-server

**Comment by jeroenvano** [comment]
Experiencing the same issue. Re-adding the device does also not work

**Comment by jeroenvollenbrock** [comment]
Nefit changed their api without notification to us, which causes the Homey app to crash. The beta version in the app store should work, and has been promoted to stable, but requires a re-pair of the thermostat.

**Comment by RobinBol** [comment]
Small correction, has not uet been promoted to stable. This will likely happen tomorrow!

**Comment by RobinBol** [comment]
The update has been pushed to stable, after a re-pair everything should work as expected.
