### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by mstrunk101** [athombv/homey#2495]
When this message comes I have to restart the device and then it will do it again.
I have to restart the device every day.

![screenshot_20180529-170341](https://user-images.githubusercontent.com/39377658/40772479-5ad58180-64c0-11e8-80bf-56118d865dd4.jpg)
![screenshot_20180530-223243](https://user-images.githubusercontent.com/39377658/40772481-5af1fef0-64c0-11e8-98e4-ee7e3e2c2c39.jpg)

Is there a way to fix this?

**Comment by RobinBol** [comment]
Merging with: https://github.com/athombv/homey/issues/1956
