### ISSUE TITLE
Sonos volume setting not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2496]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: 0D3F0CD989
* **Smartphone Platform**: IOS
* **Smartphone App Version**: Latest

**If related to a Homey App:** Sonos 
* **Homey App Version**: Beta 3.0.1
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**: Sonos 

**What did you try to achieve?**
Reduce the volume of the Sonos to 5 % 

![afbeelding](https://user-images.githubusercontent.com/23163409/40806019-76503800-6520-11e8-88d0-818cc0aa5640.png)

**What did you expect as result?**
That volume would go to 5 %

**What was the result?**
No decrease in volume, remains on 50 % as previous setting

**Any other remarks**

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
