### ISSUE TITLE
[com.somfy] Describe your issue here

### ISSUE THREAD

**Issue by Colijntje** [athombv/homey#2497]
metadata

Homey versie : 1.5.11
Homey log code : 3A8C87A5A3
Smartphone Platform :
Smartphone-appversie :
Indien gerelateerd aan een Homey-app: Somfy RTS

Homey-appversie : Homey-app v3.0.4
Homey App Log Code : ff7865fe-cc21-4adb-920b-163689862bd1
Betrokken apparaten (bij voorkeur productcodes) :
Wat heb je geprobeerd te bereiken?
Ik probeerde 4 kanalen te pairen van een
Somfy Telis RTs Pure
1810631A05
Made in Tunis
GX162

Wat verwachtte je als resultaat?
Dat alle kanalen gepaired kunnen worden

Wat was het resultaat?
Alleen kanaal 2 werd door Homey overgenomen. De andere kanalen niet.

Eventuele andere opmerkingen
Ik heb meerdere zenders (dezelfde kenmerken) die deze rolluiken aansturen, deze zijn echter ook niet te pairen. 
Ik heb andere rolluiken van somfy over andere zenders en die werken feilloos. 
Vallen kanalen buiten het bereik?

**Comment by JPe2** [comment]
Doesn't @Colijntje have issues?

**Comment by Colijntje** [comment]
<!--
metadata

Homey versie : 1.5.11
Homey log code : ?
Smartphone Platform :
Smartphone-appversie :
Indien gerelateerd aan een Homey-app: Somfy RTS

Homey-appversie : Homey-app v3.0.4
Homey App Log Code : ?
Betrokken apparaten (bij voorkeur productcodes) :
Wat heb je geprobeerd te bereiken?
Ik probeerde 4 kanalen te pairen van een
Somfy Telis RTs Pure
1810631A05
Made in Tunis
GX162

Wat verwachtte je als resultaat?
Dat alle kanalen gepaired kunnen worden

Wat was het resultaat?
Alleen kanaal 2 werd door Homey overgenomen. De andere kanalen niet.

Eventuele andere opmerkingen
Ik heb meerdere zenders (dezelfde kenmerken) die deze rolluiken aansturen, deze zijn echter ook niet te pairen. 
Ik heb andere rolluiken van somfy over andere zenders en die werken feilloos. 
Vallen kanalen buiten het bereik?

Thank you for reporting an issue. Please take some time to
review the contributing guidelines if you haven't done so.

This issue tracker is for bugs and issues found within Homey.
If you require more general support contact our support team
at: support@athom.com

Please fill out as much of the fields below as you're able.
The Homey log code can be generated at Settings -> System -> Send Log.
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).

If possible, please provide examples that demonstrates the problem,
keeping it as simple and clear as you are able to.

**Comment by Colijntje** [comment]
I pasted text in the issue field and comment field in Dutch but is not visible. Must this be in English?

**Comment by Dijker** [comment]
Yes it must bee English, but that is not your problem. 
Text between < ! - - and  - - > is a Remark and not visible on the Issue. 
If you want regular support from Athom, also in Dutch  just email them

This issue tracker is for bugs and issues found within Homey.
If you require more general support contact our support team
at: support@athom.com

**Comment by jeroenvollenbrock** [comment]
Aangezien dit geen bug betreft maar er hulp bij het koppellen nodig is, is het wellicht beter om support@athom.com hiervoor te contacteren.
