### ISSUE TITLE
Unable to add LIFX light

### ISSUE THREAD

**Issue by dangnamhai** [athombv/homey#2499]
**Metadata**

* **Homey Version**: 1.0.4
* **Homey Log Code**:  FF8C44A3F4
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: 3.1.4
* **Homey App Log Code**: 149d24e0-43b7-40a0-aa3f-59f98229f60d
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Add Lifx light by open Homey app on Window device
1. Go to device
2. Add > Select Lifx

**What did you expect as result?**

Light should be added

**What was the result?**

I got this error message: Cannot GET /oauth2/%20https://cloud.lifx.com/oauth/authorize

**Any other remarks**
Try to restart Homey, uninstall and reinstall Lifx, Go to Lifx cloud to revoke previour access ... all fail with the same result

**Comment by Hoggipoggi** [comment]
I have the same issue. Did at factory reset on Homey, but same result: 
Cannot GET /oauth2/%20https://cloud.lifx.com/oauth/authorize

**Comment by WeeJeWel** [comment]
This has been fixed in the most recent version!
