### ISSUE TITLE
[com.osram.lightify.zigbee] Add Osram Smart+ Spot GU5.3 TW

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#2500]
Please add support for Osram Smart+ Spot GU5.3 TW.

Reference: https://www.osram-lamps.com/ecatalog/smart-home/smart-home-lamps/led-reflector-lamps/smart-spot-gu5-3-tw/index.jsp

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
