### ISSUE TITLE
KaKu contact sensor not recognized

### ISSUE THREAD

**Issue by edtst** [athombv/homey#251]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Pair several KaKu contact sensors

*Please include detailed steps how we can reproduce the issue*
Use tha pair wizard to connect a KaKu sensor

**What was the result?**
The sensor is not recognized. It worked in the previous version.
...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by Dijker** [comment]
could you try the working of 433 before? 
had to cycle power to homey before 433 worked again after other tests. See #244 
I added a test button (on Test button on remote Glow Ring) to test if 433 is working before I add new KAKU devices. Also check the Code Checker is the contact sensors are visible.

**Comment by edtst** [comment]
Yes you are right. After adding several KaKu devices, it seemed to stop recognizing. After a reboot I can add a bunch and then I have to reboot again.

**Comment by Dijker** [comment]
@edtst 
Do you still have this problem? 
Reading the forum and my personal experience most stability issues are solved in the latest firmware 0.8.35 and/or KAKU App 1.1.3.
If this is still a problem please report your problem. 
else pls close this issue to keep the bugtracker clean :smile:

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
