### ISSUE TITLE
[com.osram.lightify.zigbee] Add Support for Gardenspot Mini Warm White

### ISSUE THREAD

**Issue by tomasrylander** [athombv/homey#2510]
Can you please add support for the Gardenspot Mini Warm White?

Have added it, but it is missing the dim functionality

I have submitted the log
b2c371d8-9c63-45ab-bcf6-7e4ae44638f3

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
