### ISSUE TITLE
[nl.nefit.easy] fout tijdens syns: MAX_RETRIES_REACHED

### ISSUE THREAD

**Issue by ferrydl** [athombv/homey#2511]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: 
* **Smartphone Platform**: 
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: 3.0.2
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Nefit Easy

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

The app is disconnected, with the message: 
fout tijdens syns: MAX_RETRIES_REACHED

**Any other remarks**

**Comment by RobinBol** [comment]
Thank you for reporting, this App was transferred to one of our community developer's. Since this developer also wrote the code that resulted in your error it is best to file an issue with the [developer himself](https://github.com/robertklep/nl.nefit.easy.git).
