### ISSUE TITLE
Order of the flows in list is unclear and changes.

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#252]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Just activate some Flows

*Please include detailed steps how we can reproduce the issue*

I enabled some flows that I already had defined.

**What was the result?**

Some flows seem te be put at the bottom of the list and others were not. I don't se any logic in the sort and I wonder if it will influence Homey's behaviour. 

**What did you expect as result?**

The order in the list should not change. I believe there is no order at the moment which is not ok.

**Any other remarks**

If the order is important then it should be possible to re-order the flows.

**Comment by Dijker** [comment]
Sorting is on Least Recently Save, see #245
I would prefer a alphabetical sort with search option also, [LRU](https://en.wikipedia.org/wiki/Cache_algorithms#LRU) doesn't make sense imho.
(like the search on the flow cards while you type some characters)

**Comment by matjaz** [comment]
+1 for alphabetical

**Comment by irritanterik** [comment]
+1 for alphabetical. 

![image](https://cloud.githubusercontent.com/assets/15232724/13373121/9732716a-dd5e-11e5-8e7b-7f2810d23e9b.png)

**Comment by kerkenit** [comment]
I would prefer my own sort lists. I've created flows based on my timespan's during the day.
Alphabetic could be, but i'm more fan of drag and drop in the right order.
The name of the flow can't be that long, so I won't prefer a prefix

**Comment by Dijker** [comment]
@JohanKuster 
I guess this is fixed now  in. 0.8.39 
Or didn't you update¿

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by JohanKuster** [comment]
Hi Jeroen,

This issue is solved, thank you.

Groeten,
Johan

Van: Jeroen Vollenbrock [mailto:notifications@github.com]
Verzonden: woensdag 27 juli 2016 13:49
Aan: athombv/homey <homey@noreply.github.com>
CC: JohanKuster <j_kuster@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [athombv/homey] Order of the flows in list is unclear and changes. (#252)


Can you please let me know whether this issue persists or not?
