### ISSUE TITLE
[org.knx] Upload link is outside the screen

### ISSUE THREAD

**Issue by KRiZ-R** [athombv/homey#2520]
**Metadata**

* **Homey Version**: 1.5.11
* **KNX App Version**: v0.1.1 

**What did you try to achieve?**
Try to upload the *.knxproj file.
Go to device, add new device, choose KNX, choose type of KNX device.
Press next.
There you see the text: "Upload een ETS configuratie bestand (*.knxproj) om de KNX groepadressen op te halen en te bewaren in...", but the link is outside of the screen.

**What did you expect as result?**
See the button or link to upload the *.knxproj file.

**What was the result?**
The upload link is outside of the screen.

**Any other remarks**
Please make the text auto wrap to next line. And make the link visible or make a button.
I used the developer toolbox to shorten the text, then the link became visible.

![no link](https://user-images.githubusercontent.com/11397063/41718441-43565130-755d-11e8-8369-20e15126a8bd.JPG)
![after edit](https://user-images.githubusercontent.com/11397063/41718442-437049fa-755d-11e8-9f25-6b588d0ab61f.JPG)

**Comment by KyleAthom** [comment]
Good spotted. This will be fixed in the upcoming version of the KNX app.
