### ISSUE TITLE
Heiman HS1SA-Z Smoke detector

### ISSUE THREAD

**Issue by gijsje** [athombv/homey#2524]
* **Homey Version**:1.5.11
* **Homey Log Code**:A8187FACD8

* **Affected Devices (preferably product codes)**:Heiman HS1SA-Z

**What did you try to achieve?**
Include the Heiman HS1SA-Z Smoke detector

**What did you expect as result?**
To be added as a smoke detector

**What was the result?**
Not working

**Any other remarks**
I think it should be possible as the zwave info is available here 
https://products.z-wavealliance.org/products/1936

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
