### ISSUE TITLE
[nl.woonveilig] Woonveilig app not working

### ISSUE THREAD

**Issue by Alert1977** [athombv/homey#2525]
Since a couple of weeks I noticed that the Woonveilig app for homey is not responding.
It used to work just fine. The Woonveilig app still works normally. 

I tried to restart the app a couple of times but I am still not able to turn the alarm system on/off.
Also all flows where the Woonveilig device is used shows the broken symbol in the Homey client.

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Unfortunately, this is an issue that resides at the woonveilig side of things. They have been notified of this issue a while ago and are working on a solution.
