### ISSUE TITLE
KAKU 2 channel remote APA2-2300R does not work in the flow.

### ISSUE THREAD

**Issue by Petervanoos** [athombv/homey#253]
I can add the 2 channel remote APA2-2300R as a device but only per channel under a different device.
In the flow it does not work.
Did someone found a solution?

**Comment by Dennishacq** [comment]
@Petervanoos 
You could run the code checker to see what codes the remote transmits.
Your remote should work if you enter these values in the Flow editor.

**Comment by Petervanoos** [comment]
Thanks for your answer. I have the code.
But it is not clear to me where to enter the code.
There is no option to enter the code. I can only choose the channel and the button in the 'when' columm.

![kaku flow](https://cloud.githubusercontent.com/assets/17181127/13362179/1a05c908-dcc3-11e5-8c97-6902cfc0426b.JPG)

**Comment by soler2000** [comment]
I thin kI have also found this same issue that when adding a second device of the same type Homey only reports the last device added.   Can you try to remove both devices and add one device and check.  Then add a second device and see if the first or second one works in a flow.   My guess is that the second device works and the first no longer works.

**Comment by laurenssss** [comment]
for me the apa2-2300r also not working

**Comment by Dijker** [comment]
@Petervanoos and @laurenssss 
Do you still have this problem? is your issue about adding the 2-channel remote in Homey or about adding the sockets? I hope it is possible to add the 2 channel remote to Homey as a standard 16-channel (new) remote, but I am not sure it that works.
 
Reading the forum and my personal experience most stability issues are solved in the latest firmware 0.8.35 and/or KAKU App 1.1.3.
If this is still a problem please report your problem. 
else pls close this issue to keep the bug-tracker clean :smile: 

If it doesn't work pls report the here the code checker info, i think Athom then should fix something in the App.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Petervanoos** [comment]
Jeroen,

 

Sluit de call maar.

 

Heb geen tijd om verder mee aan de slag te gaan.

 

Groet, Peter van Oosterhoudt.

 

Van: Jeroen Vollenbrock [mailto:notifications@github.com] 
Verzonden: woensdag 27 juli 2016 13:50
Aan: athombv/homey <homey@noreply.github.com>
CC: Peter van Oosterhoudt <peter@vanoosterhoudt.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [athombv/homey] KAKU 2 channel remote APA2-2300R does not work in the flow. (#253)

 

Can you please let me know whether this issue persists or not?
