### ISSUE TITLE
[nl.klikaanklikuit] missing products  ACC-2300

### ISSUE THREAD

**Issue by JameyMijling** [athombv/homey#2530]
**Metadata**

* **Homey Version**:
Homey Firmware Versie: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
IOS
* **Smartphone App Version**:
newest
**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Ad klik aan klik uit product

**What did you expect as result?**
to find following product ACC-2300

**What was the result?**
Pruduct wasn't listed

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
