### ISSUE TITLE
Built-in voice commands are not working, voice Nicole not working at all

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#254]
**What is your Homey version (Settings → System)?**

0.8.20  
(issue was already present in 0.8.17)

**What did you try to achieve?**

Built-in voice commands are not working. Flow-triggered commands are working. 

**What was the result?**

Built-in commands are not processed.  ( e.g. what's the weather, what is the time ). Commands used in flow are working

(all tested via 'speech-input' ) 

**What did you expect as result?**

Built-in commands working, voice Nicole working

**Any other remarks**

When using voice "Nicole", there is no voice at all, not even via the 'speech-output' page. Other voices work fine. I uninstalled all voices including Nicole and redownloaded them.

When running 0.8.17, Homey crashed once during the download of a voice, might be Nicole.  Maybe something got stuck, causing Nicole to be silent and built-in commands not to be processed.
...

**Comment by WeeJeWel** [comment]
Nicole was corrupt and is removed from the list of downloadable voices.

If you make a flow with an action 'Say something', does it error with the message 'voice is undefined'?

**Comment by ralfvd** [comment]
I've removed Nicole and installed Russell ; voice works inside flows and with my own commands. But the built-in commands (turn lights on etc) don't work, even when the voice input is via 'speech-input'. 
A reboot didn't help

**Comment by WeeJeWel** [comment]
Can you try this? https://github.com/athombv/homey/issues/31#issuecomment-172112831

**Comment by ralfvd** [comment]
I am not sure I am doing it correct, but I get a response
"POST http://192.168.89.25/api/manager/speech-input/?_=1456811258761 500 (Internal Server Error)"
when typing anything in the speech-input page. 
Pasting the API command in the developer console, gives me "undefined".

The voice commands that I use in a flow are working correctly; e.g. in a "parrot flow", it will repeat what I type in into the speech-input page. It is just the built-in commands that do not work.

**Comment by bvdbos** [comment]
I noticed (but haven't got it confirmed by anyone yet) that turning flows with more then three actions off works for me getting the build-in commands back to work.
https://forum.athom.com/discussion/931/2-actions-in-one-flow-break-0-8-20#latest

**Comment by ralfvd** [comment]
bvdbos ; I've tested this just now; disabling flows with more than three actions ( three actions = still enabled ). And indeed, this enabled the build-in voice commands. The developer console also gives a 'null' response instead of 'internal server error'

![screen shot 2016-03-01 at 07 02 27](https://cloud.githubusercontent.com/assets/17275712/13419046/96b17884-df7b-11e5-845a-88325a7b476e.png)

**Comment by ralfvd** [comment]
After one by one re-enabling the > 3 action card flows, I continued to work until I enabled the 4th flow that has more than > 3 action cards.  Then built-in voice commands stopped. Disabling that flow, re-enabled that flow again.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
