### ISSUE TITLE
[com.neatorobotics] Change the polling frequency from the default 10 seconds

### ISSUE THREAD

**Issue by mickem** [athombv/homey#2541]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:** Neato BotVac
* **Homey App Version**: 1.0.0
* **Homey App Log Code**: N/A
* **Affected Devices (preferably product codes)**: Neato Botvac D7

**What did you try to achieve?**
Use the robot from the regular Neato Robotics app while having the Neato app installed on my homey.

**What did you expect as result?**
The robot be usable from the regular Neato Robotics app.

**What was the result?**
The Neato Robotics App says "disconnected" every 10 seconds (when Homey polls the API).

**Any other remarks**
Seems rather aggressive to poll the API every 10 seconds (I think).
Especially since I only use it for scheduling cleanings meaning the polling is not required at all.
A better option would be to either poll on demand or at least allow me to se the polling frequency through the config dialog.

And I know that technically this is a fault with the Neato API which (presumably) does not support long polling but setting the polling frequency would be a simple workaround.

**Comment by MatthewWaanders** [comment]
I'll pick this up as soon as I can! 

That's a weird limitation indeed, user determined polling frequency it is then. I'll let you know when it's released.

**Comment by MatthewWaanders** [comment]
There is an update in the App Store for you! The default will still be 10 seconds, however you can change it manually.
