### ISSUE TITLE
[com.aeotec] App cannot add my DSC27103-ZWEU

### ISSUE THREAD

**Issue by pln8421** [athombv/homey#2543]
**Metadata**

* **Homey Version**:1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:1.6.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:DSC27103-ZWEU

**What did you try to achieve?**

**What did you expect as result?**

Device added. 
**What was the result?**

Insted Homey choose installation as basic type and then I can only turn off and on the LEDs.
Tried to exclude and include 3 times.

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
