### ISSUE TITLE
homey won't send signal after speech

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#255]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
tried to switch eurodomest by voice this didn't work.
in test mode it worked
i can see that homey is activated turns yellow
then flashing white but nothing happend
![schermafbeelding 2016-02-26 om 19 24 16](https://cloud.githubusercontent.com/assets/17185881/13361419/d8e9a86c-dcbe-11e5-8859-842aadf9df8a.png)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by kingdong78** [comment]
i think there is still some finetuning of the voice recognizing

**Comment by WeeJeWel** [comment]
Please don't use built-in voice commands such as 'lights on' in flows.

To make sure the text is heard correctly, input it manually in `http://yourhomeyip/manager/speech-input/`

**Comment by bvdbos** [comment]
If this is still a problem, please create a parrot-flow (outputting what Homey heard to mobile or loudspeaker) to see what's the problem.

**Comment by CootNL** [comment]
I have the same problem in version 0.8.27.
He is not recognizing what I am seeing.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
