### ISSUE TITLE
[com.qubino] Flush 2 Relays (ZMNHBD) switching input 1 and 2 does not trigger Flows

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2558]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Qubino Relay 2 switch z-wave plus
Added as an issue to track progress and possibilities.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.qubino/issues/14

**Comment by RobinBol** [comment]
Note: this is not reproducible with the Flush 2 Relays we have at our disposal.

**Comment by JPe2** [comment]
Had contact with Qubino, their reaction was:

> Thank you very much for reaching out to us and my apology for keeping you wait with my reply. 
> I can confirm that Flush 2 Relay device is currently not fully supored by homey gateway, we are working with homey on integaration of Qubino devices within this gateway.
> Best regards/Lep pozdrav,
> Aleš Humar

@WeeJeWel   Strange that I have to hear this from Qubino and not from Athom??

**Comment by RobinBol** [comment]
@JPe2 , what did you hear from Qubino that you did not hear from us?

**Comment by JPe2** [comment]
@RobinBol Sorry Robin, I don't want to be negative, I appreciate your effort to solve the problem, but I find it a bit strange that you direct me to Qubino while Athom is already in contact with Qubino and you did not tell me, it is a known issue that not all functions of the 2 Relay device are fully supported (yet), that's the reason for my remark. Also, you tagged it as an enhancement, while I see it as a missing basic function.

Further, the second problem with this device, the not showing of the power, is not mentioned at all anymore, should I open a new Issue for this?

Again, sorry for getting a bit frustrated, this has already taken so long, I had bought some of these devices for purposes where I need these functions, but I can't use them and so I had to buy other devices for this task. 

> Note: this is not reproducible with the Flush 2 Relays we have at our disposal.
Does this mean that your device acts well for all the functions, I1 and I2 can be used in flows an power is shown and can be used in flows? Where can I buy this device?

**Comment by RobinBol** [comment]
Well, the fact that not all functions of the Flush 2 Relays are implemented is no secret, it was always documented in the Homey Apps store description of the app, hence this 'enhancement' issue to keep working on adding the missing functionality.

I directed you to Qubino since I mentioned that we have a Flush 2 Relays at the office that in combination with the latest beta of the Qubino app works flawlessly (power metering, and I1/I2 in flows). Therefore, I assume that there is a firmware difference between your version and ours (maybe yours contains a bug of some sort).

We are always collaborating with manufacturers of smart home devices to add/improve the integration with Homey, so that should be no surprise either.

**Comment by JPe2** [comment]
Well, finally, I got a confirmation from Qubino that my devices have old firmware, I rest my case:

> Thank you very much for this information. 
Indeed I can confirm that you have older version since it is confirmed that newer version works as you desire.
You may return the older one back to distirubtor so he can return it back to us for firmware upgrade, 
which is free of charge but we do not cover shipping costs.
Best regards/Lep pozdrav,
Aleš Humar

**Comment by RobinBol** [comment]
Thank you for the update, I consider this issue fixed. If someone experiences otherwise please let us know!
