### ISSUE TITLE
Z-wave: battery powered ghost device cannot be removed

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#257]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Remove a ghost device. (with older version I added a aeotec recessed door sensor gen 5, but it wasn't send any updates, even with the right association set, so I tried to remove it then, but node-removal failed. Also failed removal of this device with the .17 version was not possible. I decided to try it again after updating to 0.8.20.)

*Please include detailed steps how we can reproduce the issue*
1. Open z-wave settings screen.
2. No remove button available:
![image](https://cloud.githubusercontent.com/assets/15232724/13373229/c5a692e4-dd61-11e5-90d5-be11aed1f649.png)

3. Select the ghost device and click on refresh node. Pop-up appears:
![image](https://cloud.githubusercontent.com/assets/15232724/13373233/e45aef1e-dd61-11e5-81d7-0d72bb7bbf1e.png)

4. Well, waking up the device is not possible, because the device is not on Homey's network anymore. And deleting is also not possible now. There is still no remove node or replace node button available:
![image](https://cloud.githubusercontent.com/assets/15232724/13373238/15b30f38-dd62-11e5-8ab3-9ee8c1dab171.png)

...

**Comment by ocatie** [comment]
The Remove/Replace Failed Node buttons only appears when the device is on the failed node list on the zwave chip. Always remove devices using the Remove Node Button (only reset your devices as last resort because you will create ghost nodes)

Will look into how to put the ghost battery devices on failed node list.

**Comment by ralfvd** [comment]
I have the same problem; this is after the 'remove node button' failed to successfully remove the battery device.

**Comment by ocatie** [comment]
The Z-Wave page not loading is fixed in 0.8.21

**Comment by ocatie** [comment]
Please try again on 0.8.24

**Comment by ocatie** [comment]
Battery devices can also be placed on the failed node list
