### ISSUE TITLE
philio tech multi sensors

### ISSUE THREAD

**Issue by Wimstradamus** [athombv/homey#259]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

pir general alarm keeps flashing red, no rest
PSM02 4-in-1 (seems to be in rest for know, manually added node to group 1 again,after i added them with new pairing wizard)
PSP01 3-in-1 (also manually added to group 1, still not in rest alarm keeps flashing)

**What did you expect as result?**

pir sensor status in rest when no theres motion

**Any other remarks**

unable to set any (pir sensitivity) parameters.

**Comment by ocatie** [comment]
You probably have to set a specific configuration value in order to have the sensor report its status.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
