### ISSUE TITLE
Fibaro Door/Window sensor, must-have feature missing or hidden to get/set/use the armed/unarmed state? (Zwave)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#26]
I cannot find the essential set/read of the  "Armed" state of the Fibaro Door/Window sesnror, and how I can respond to the 4 situations: armed+firing, unarmd+firing, armed+not firing, unarmed+not firing. I use these in flows in VeraEdge, and want to move those to Homey, but I can't because I can't find the armed/unarmed feature in Homey?  Is the feature missing forever(I think this will be a big problem for anyone moving from Vera/HC to Homey, or hidden, or still to be build? Thx in advance.

**Comment by ocatie** [comment]
There is nothing mentioned in the device manual about arming or disarming the sensor so I think this is a software feature where alarms are ignored. In Homey you can realize (dis)arming by dis-/enabling flows. Please let me know if that covers it otherwise I'll need to think about it a little deeper.

**Comment by athomey** [comment]
Ah, this might very well be truely a Vera and HomeCenter software feature. It's not at all the same thing that you can enable/disable a flow. That is in those systems a seperate thing. For obvious reasons, to simplify flows/devices, etc..  I'll try to get around it in Homey, but it MIGHT be quite troublesome. I'm curious how other migrators are going to experience this.

**Comment by freemann** [comment]
I also use the (dis)arm "feature" of getVera. 
When we both left the house, all sensor go in Arm mode and if the trigger i get an email/notification.
If we are at home, the sensors are disarmed and will not trigger an email/notification.

This is, for now, not possible with Homey?

**Comment by ocatie** [comment]
This can very easy be done with the floweditor. You can make a flow:

"Generic alarm turned on -> send mail" named Door sensor

"When I leave -> enable flow 'Door sensor'"

**Comment by freemann** [comment]
OK! Do I need 10 flows for my 5 door/window sensors and 2 statuses (home/away) or is it possible with only 1 flow?

**Comment by athomey** [comment]
@freemann : I think YES as I read responses.

**Comment by freemann** [comment]
Yes on 10 flows of yes on 1 flow? I hope the last option :)

**Comment by domey** [comment]
Isn't it possible to declare a global variable (boolean Armed) that is evaluated when the trigger is fired?

bArmed = true
When (trigger and Armed) send Alert --> results in a alert

bArmed = false
When (trigger and Armed) send Alert --> does nothing

You just need a method to set bArmed

**Comment by WeeJeWel** [comment]
You can simulate 'armed'-behavior by enabling/disabling flows from another flow, e.g. when you leave the home.

Grouping devices will be added later, so then you only need 1 flow to trigger when ANY alarm went off.

**Comment by freemann** [comment]
Same for motion detection? :|

**Comment by ocatie** [comment]
If you assign them to the Sensor class, yes. If a Z-Wave app is used it depends on the app.
