### ISSUE TITLE
Documentation: Driver image sizes incorrect

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#260]
Documented image sizes for drivers ar incorrect:
![image](https://cloud.githubusercontent.com/assets/15232724/13375706/32479868-dda7-11e5-9637-94e6e5076f00.png)

Large: 500 x 350
Small: 250 x 175

With cli athom project --validate-app-store these errors appears:
![image](https://cloud.githubusercontent.com/assets/15232724/13375713/496d9092-dda7-11e5-90e8-249070312eef.png)

Large: 500 x 500
Small: 75 x 75

**Comment by nlrb** [comment]
Yes, very annoying. Cost me a lot of time to create new images again.

**Comment by matjaz** [comment]
same here https://developers.athom.com/library/appstore

**Comment by WeeJeWel** [comment]
Fixed!
