### ISSUE TITLE
[com.rituals] Virtual device support

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2605]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
When creating a vd to simply turn on perfume diffuser through flow i get an error message when testing the flow, am i doing something wrong ?

Actually i can only turn it on or off through the device in homey itself, when i add it ass part of flows (e.g. Leave or arrive at home) it doesn’t work :-(

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.rituals/issues/2

**Comment by WeeJeWel** [comment]
Closed due to inactivity.
