### ISSUE TITLE
Kaku Doorbell ACDB-7000AC

### ISSUE THREAD

**Issue by Wimstradamus** [athombv/homey#261]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

add KAKU doorbell ACDB-7000AC

**What was the result?**

unable to add doorbell to homey

**What did you expect as result?**

To add doorbell to homey

**Any other remarks**

code checker sees the doorbell.

**Comment by Dijker** [comment]
See #52 and #244 
Beside stability of the RF433, the doorbell are also often a problem.

**Comment by Wimstradamus** [comment]
ok, i do not have any stabilty problems also added multiple door contacts and they keep working.

**Comment by Dijker** [comment]
Version 0.8.22 / KAKU v1.0.14
My  KAKU doorbell ACDB-7000A still doesn't pair although it is seen by the code checker:
![image](https://cloud.githubusercontent.com/assets/12412734/13648893/548b1c64-e63b-11e5-9c07-05b7a9cd3964.png)

**Comment by Dennishacq** [comment]
Hi guys, sorry for the late reaction.
Are you still experiencing this issue?

**Comment by Dijker** [comment]
For me the same as 9 days ago. noting changed.

**Comment by jghaanstra** [comment]
Same here, with 0.8.24 and KAKU app 1.0.15 my ACDB-7000B is not recognized by either the code checker or doorbell device wizard.

**Comment by Dijker** [comment]
just tested again after updates:
Version 0.8.24 / KAKU v1.0.16
My KAKU doorbell ACDB-7000A still doesn't pair although it is seen by the code checker: See post above.

**Comment by Dennishacq** [comment]
Hi guys,

A new version of the KaKu app is ready to be downloaded from the App store.
You should now be able to pair your doorbells.

**Comment by jghaanstra** [comment]
I just tried this with 0.8.29 and the KAKU 1.1.0 app but was unable to pair my ACDB-7000B doorbell. Either the doorbell device and the code checker did not recognise anything. I do have a specific setup where the ACDB-7000B is behind a relay in the normal doorbell circuit but I can switch on a regular KAKU socket with it, so it should work. I'm interested to see the results from others.

**Comment by laurenssss** [comment]
same here, and my ACDB-7000 is not connected to a relay, just 1 on 1 to the doorbell unit of KaKu
also not recognized anymore in the code checker, where it previously was

**Comment by bvdbos** [comment]
Do you also have to ACDB-7000B ? @Dijker mentioned his ACDB-7000A works now:
https://github.com/athombv/homey/issues/52#issuecomment-210150140

**Comment by laurenssss** [comment]
just see I have a ACDB-6600AC, so the wireless version with a battery operated bell unit as well (no outlet plugin)

**Comment by laurenssss** [comment]
update.....just shortened the distance between doorbell and homey, now it get´s recognized and works, will check if changing battery will help with reaching longer distances

**Comment by Wimstradamus** [comment]
Doorbell works for me now.

**Comment by Dennishacq** [comment]
@jghaanstra 
Did you manage to pair your doorbell with Homey in the meantime?
If not: are you able to pair any other 433MHz devices to Homey?

**Comment by jghaanstra** [comment]
Unfortunately no, the doorbell device wont pair and the code checker does not recognize it. Even tried placing the Homey in the hallway but this did not make a difference.

**Comment by Dennishacq** [comment]
@jghaanstra 
Are you able to pair any other KaKu or 433MHz devices?

**Comment by jghaanstra** [comment]
Yup, I have some KAKU sockets paired which have been working flawlessly since day one.

**Comment by Dennishacq** [comment]
@jghaanstra 
That's very odd.
What is the distance between Homey and the doorbell?

**Comment by jghaanstra** [comment]
Homey is about 10 meters away from the doorbell but I actually tried moving Homey into the hallway where it's only 2 meters away from the transmitter but still to no avail. I'm away for a week on holidays but I will do some further testing once in back and again make sure the doorbell is able to switch a kaku socket so I'm sure it's not an issue with the transmitter.

Has everybody else been able to pair their kaku doorbell?

**Comment by jghaanstra** [comment]
I can confirm that the ACDB-7000B works with firmware 0.8.32 and KAKU app v1.1.2. Turns out the battery of my sender was empty (after only having it used a couple of times). Anyway, it paired just fine now. As @Wimstradamus  mentioned it also worked for him as well this issue should be closed now.
