### ISSUE TITLE
IR devices not able to identify, they all have the same name

### ISSUE THREAD

**Issue by adveldt** [athombv/homey#262]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
After adding multiple IR devices in the devices, section it is not possible to recognize which is which in the flow section.
A simple solution as giving them a different name while adding them would work.
*Please include detailed steps how we can reproduce the issue*

Add a IR device
**What was the result?**
IR device created.
...

**What did you expect as result?**
Possibility to give each IR device a different name, in order to identify them in the flow section.
...

**Any other remarks**

...

**Comment by Dijker** [comment]
You have to rename each device in the zones and device's view by clicking on the name after adding it.

**Comment by Qx5** [comment]
Indeed. Would make sense though to give an "initital" device name in the add device procedure (not only IR).

**Comment by goldenice** [comment]
As mentioned by @Dijker you can rename devices in the Zones & Devices overview.

Would taking the brand and model names of your remote as default name when pairing with automatic detection, and 'Custom IR-device' for manually paired devices, solve your issue initially? Afterwards you can always rename them ofcourse, but I think this would be enough to distinguish them initially.

**Comment by adveldt** [comment]
Goldenice, I would think that your suggested solution would work. We need to think ahead, when other users (maybe less driven as our community) will be using it in a later stage as well. In the end Homey needs to be a commercial hit as well.
Thank you all for the feedback!
