### ISSUE TITLE
[com.athom.soundboard] Add sorted autocomplete

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2621]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Simple question.

Could you make the list of uploaded files alphabetical? Or sortable in some way?

I like a nice overview and when you remove and re-add files they end up at the bottom, instead of together with the other files they belong to (if you use a group of files, ex. my doorbell sounds)

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/10

**Comment by WeeJeWel** [comment]
wontfix
