### ISSUE TITLE
[com.athom.soundboard] Set active speaker

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2622]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
In addition to the request "Soundboard to media" it would be really nice to stream sound to a speaker of my choice (Sonos or Heos speaker for example). I tried using the feature "Set active speaker" in an flow to Alarm me with sound upstairs. No luck.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/9

**Comment by Veldkornet** [comment]
+1 for this in a flow. Would be handy if I could play my doorbell over my Sonos.

Perhaps just an extra field in the "then" card would be sufficient where you select the speaker. 
Ie: Homey itself, a specific Sonos speaker, etc

![image](https://user-images.githubusercontent.com/10297361/44569475-c94e4a00-a77a-11e8-9f1a-84cf66f4d8d3.png)

**Comment by WeeJeWel** [comment]
We won't add support for this in the soundboard app itself.

**Comment by WeeJeWel** [comment]
Sonos v4.0.13 now supports sending sounds from the Soundboard app (v2.0.2 and up) to Sonos speakers.

**Comment by jahnkenneth** [comment]
Can’t seem to get this to work. 
Have updated both apps to the version specified. When adding sonos in 
then-column I get the option to play a file from soundboard... I choose a file, and test the flow. The test status is «running», but the speaker doesn’t play the file... Have checked the volume...

**Comment by Veldkornet** [comment]
Same for me. 

I have noticed that, if I trigger it to play from a URL, then while it’s playing, trigger the sound from soundboard, the sound will play. 

But just a normal flow with play sound from sound board... dead silence...
