### ISSUE TITLE
[com.athom.soundboard] Global tag support

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2623]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hi,

I think it would be nice to have tag support for this app.
Now you always have to explicitly select the file you want to play.
But it would be a nice feature if you could use tags to easily play different sounds with tags.

Example for my doorbell: https://forum.athom.com/discussion/3929/randomize-doorbell-sound
I could use to randomize the sound at every press of the doorbell.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/8

**Comment by WeeJeWel** [comment]
wontfix
