### ISSUE TITLE
[com.athom.soundboard] Stop sounds currently playing

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2624]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
I use several cards to keep an alarm sound playing in a loop. The sound lasts for 25 seconds, it would be nice to be able to stop the sound when the alarm is turned off again.

Right now I just mute the speaker by turning the volume to zero. But when an event that involves sound occurs within max. 25 seconds, the siren is still playing.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/5

**Comment by WeeJeWel** [comment]
wontfix, this is not supported in Homey's core
