### ISSUE TITLE
[com.athom.soundboard] Soundboard to media

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2625]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Now media is out, it would be really nice if we could send sounds from the dsoundboard to our devices.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/4

**Comment by WeeJeWel** [comment]
Sonos v4.0.13 now supports sending sounds from the Soundboard app (v2.0.2 and up) to Sonos speakers.

**Comment by chrisboer** [comment]
Does not work 
Sonos v4.0.13
Soundboard v2.0.2 beta 

![afbeelding](https://user-images.githubusercontent.com/23163409/46299325-6766d880-c5a1-11e8-89d3-cac5e69203a2.png)

**Comment by JPe2** [comment]
08-002

![clipboarder 2018 10 08-005](https://user-images.githubusercontent.com/3833862/46623523-34d35780-cb2e-11e8-9941-6d3f564d0bd2.png)

replaced Soundboard with Beta version, same result.
08-003


![clipboarder 2018 10 08-004](https://user-images.githubusercontent.com/3833862/46623481-0e152100-cb2e-11e8-9018-6ff1d69e71f4.png)

edit: The sound is still not played, but now the time that the sound should play, the speaker is silent! This is after a reset of Homey. Circle stops turning also now.
