### ISSUE TITLE
[com.athom.soundboard] Loop card?

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2626]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Would it be possible to make a card to loop a sound? That would be handy to use in an alarm flow.
I use several cards with a delay now to play an sirene several times but that's not a very nice solution...

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.athom.soundboard/issues/2

**Comment by WeeJeWel** [comment]
wontfix, use a Flow for this.

**Comment by daneedk** [comment]
@WeeJeWel  Could you please show us an example flow on how to achieve the desired result?
