### ISSUE TITLE
[com.spotify] Spotify Sonos doesn't work as expected (Having Left/Right channel speakers and Boost)

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2629]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
When attempting to play music using Spotify Connect (For Sonos), the music from Spotify cannot run. All nr's scroll (don't play). Only option I have is activating an existing Sonos stream (selected by Sonos app e.g. Intune).

Homey Core: 1.5.8

Spotify Connect version 2.0.1
Sonos 2.3.1

Sonos Config:
Boost 8.4
Play:1 8.4
Play:1 8.4

Both play:1's are combined as left-right pair in a single group

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.spotify/issues/9

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
