### ISSUE TITLE
[nl.klikaanklikuit] Par-1000 not working anymore

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2647]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
I try to add som KlikAanKlikUit par-1000 sockets to Homey. The codes are set to b3 or C2 and I add a device to Homey. I enter the fixed code but the socket does not respond. I tried 2 different sockets and different codes but it does’t work.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/nl.klikaanklikuit/issues/28

**Comment by KyleAthom** [comment]
This is fixed in the v4.0.7 release for the KlikAanKlikUit app.
