### ISSUE TITLE
Incorrect text in Smartwaves App

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#265]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Text in the Smartwaves app Pair a new Socket says inncorrect text

*Please include detailed steps how we can reproduce the issue*
Go to the pair wizard, select generate new remote and underneath the false text appears.

![schermafbeelding 2016-02-28 om 11 30 09](https://cloud.githubusercontent.com/assets/17526110/13378701/c16cf7d8-de0e-11e5-9ab1-650c182f601a.png)

**What was the result?**

Not sure what the meaning of the text is.

**What did you expect as result?**

Appriopate text

**Comment by Dennishacq** [comment]
Oops, will be fixed in Smartwares 1.0.6.
Thank you for reporting!

**Comment by Arjanvde** [comment]
Stil no sign of 1.0.6.

As soon as the new app is released i will close this bug.

**Comment by Arjanvde** [comment]
Fixed
