### ISSUE TITLE
[nl.klikaanklikuit] Only update the status of KAKU lights without send the on signal

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2653]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hello,

All my KAKU lights are directly paired to the KAKU wall switches. This is because of the non-decency of Homey/Internet etc. to turn the lights on. Also the WAF is important here ;-)

Problem now is that the status in Homey of the lights is not updated when I turn them on with a wall switch.

Off course I can create a flow, when pressing the wall switch I turn on the lights, but when I do this with dimmable switches or lights, they start dimming up and down because they have received two on signals sequentially (on from the paired wall switch and one from Homey).

I want to be able to update the light status when a switch is turned on without sending the actual on signal through Homey.

In Domoticz this is possible to make a master/slave connection between a switch and a light.

Gr. Remco

I tried to fix my situation with the current functionality, but I did not succeed:

I have three dimmable KAKU lamps in the living (ALED-2009)
I need to be able to dim them separately (not as a group)
I can control them from two wall switches in the living
I have paired the switches directly the the lamps. I don't want to be dependent on Homey or the internet to turn on my lamps.
I have created 3 separate ALED-2009 lamps in Homey (Homey generates own on/off signal per lamp), I can set the dim level from the Homey app
When I switch the lights on with a wall switch, everything works, but Homey does not know the lights are on (wrong status)
If I copy the signal from the wall switches for the lights instead of having Homey generate a own signal, I can no longer dim the lamps separately. Also I can only copy the signal of one off the two wall switches, not both...
This issue can be fixed by adding a master/slave feature as it exists in Domoticz, or we could have to add a "set status" action to all KAKU receivers. This would only change the status of the receivers without actually sending the signal.

Gr. Remco

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/nl.klikaanklikuit/issues/13

**Comment by KyleAthom** [comment]
Hi @rhannink Flows should be the best way to handle this issue.
You can workarround the dimmer issue by only turning them on (or off) in the flows.
