### ISSUE TITLE
[nl.klikaanklikuit] ACDB 7000AC receiver is not working

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2655]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hi Guys,

I bought myself a ACDB-7000AC doorbel receiver and sender.

The sender is working fine! But the receiver isn't working. If i want to make a flow when a button is pushed...

It also won't learn the receiver...

It's not a world problem, but maybe you can do something about it in the future :)

Cheers,

Joost

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/nl.klikaanklikuit/issues/5

**Comment by KyleAthom** [comment]
This should be fixed in beta version 4.0.9.

**Comment by KyleAthom** [comment]
Version 4.0.10 is now stable and fixes this issue.
