### ISSUE TITLE
[com.sonos] Flow -> Using "Turn On" feature

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2657]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Would be nice not only to select start playing at a Curtain time.
I use the Playbar with the Sub combined... So if I watch tv and go to bed then the playbar remembers the last playback "TV MODE" and if i use the FLOW -> Turn On at 7:30 feature it will not start playing a Radio Station.
So it would be great if i can select the Sonos Fovorite Radio Station so it will not stick to it's TV mode

For the rest you guys doing a great job thank you

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/24

**Comment by WeeJeWel** [comment]
Use `play` for this functionality.
