### ISSUE TITLE
[com.sonos] Need trigger play/pause/stop

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2658]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Please add trigger function on app.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/23

**Comment by WeeJeWel** [comment]
This is added in Homey v2.0.
