### ISSUE TITLE
[com.sonos] Athom's Sonos App conflicting with Sonos' own app

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2659]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
In addition to https://github.com/athombv/homey/issues/2277:

Homey:
FW 1.5.7
Sonos app: 3.0.1

Sonos:
Controller for PC/iPhone/iPad (Alpha, v. 8.6, build: 43050151mainline_integ_ext_release)
Physical devices: Sonos Playbar, Play:1, and Play:5 in different setups (stand alone Play:1, stand alone Play:5, stereo pair of two Play:1, Playbar paired with two Play:1).

Yesterday:
Can see all units in app (iOS), often it takes several tries to start music/radio - and devices then marked with "No music" - and consequently not possible to stop them from playing...

Today:
Coming home today, Sonos devices were unreachable when using Sonos controller for PC as well as on iPhone and iPad.
Disabling the Sonos App at Homey doesn't change a thing - until after a reboot of Homey.

However, while writing this (as I wanted to replicate the issue) things are somehow different than expected: I have some kind of partial or conflicting control:
Sonos devices can be grouped/ungrouped and controlled in groups and/or individually by Sonos' software on both PC and iPhone/iPad.
At the same time, I have partial control over Sonos devices via Homey's interface, that is, when restarting the Sonos app on Homey, all were grouped in "Party mode" - and no matter if devices were ungrouped using Sonos software, all manipulation done using Homey's Sonos app infer changes on the speakers "left" as the active speaker when devices were ungrouped (did that make sense?)

Seems like Homey take some kind of control of the speakers, that may result in locking out the native Sonos app.

Correspondance with Sonos support is in a non-public forum that I can't share as a link, but a copy of the correspondance can be e-mailed if you want it.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/22

**Comment by noll8an** [comment]
I an experiencing the same thing after the latest Sonos update. 
When i updated Sonos, the Sonos app Within homey kept crashing. I then installed the sonos beta app for homey. Everything seemed to be working again. Then i discovered the problems that Robinboy is Talking about.

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
