### ISSUE TITLE
Realtime trigger problem

### ISSUE THREAD

**Issue by denniedegroot** [athombv/homey#266]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Send a trigger from app.js and trying to catch it in the front-end.
```
Homey.manager('api').realtime('settings_changed', settings);
```
Front-end
 ```
Homey.on('settings_changed', function(settings) { 
    console.log(settings);
});
```

When I send the trigger from the app.js init() function with a setInterval I can always catch the event in the front-end so I know the code is working. However when I try to send the trigger with the following code it does not work at all.

```
Homey.manager('settings').on('set', function(settings) {
    Homey.manager('api').realtime('settings_changed', settings);
});
```

**What was the result?**

No event on the front-end.

**What did you expect as result?**

An event on the front-end.

**Comment by WeeJeWel** [comment]
is `Homey.manager('settings').on('set', function(settings) {` ever called, and if yes, what value is `settings`?

**Comment by denniedegroot** [comment]
Yes the function is called, all the code inside this function is also executed.
The settings object contains the following:
`{ host: '127.0.0.1', paircode: '0xAABBCCDDEEFFGGHH' }`

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue using the following code.

`settings/index.html`
```
<html>
	<head>
		
	</head>
	<body>
		
		<script type="text/javascript">
		function onHomeyReady(){
            Homey.ready()
            
            document.getElementById('button').addEventListener('click', function(){
	            Homey.set('foo', { host: '127.0.0.1', paircode: '0xAABBCCDDEEFFGGHH' }, function(){
		            console.log(arguments)
	            })
            });
            
            Homey.on('settings_changed', function(){
	            console.log(arguments)
            })
        }
		</script>
		
		<button id="button">Button</button>
		
	</body>
</html>
```

`app.js`
```
var self = module.exports = {
	init: function(){
		Homey.manager('settings').on('set', function(settings) {
			console.log('settings_changed', settings);
			Homey.manager('api').realtime('settings_changed', settings);
		});
        }
}
```

**Comment by denniedegroot** [comment]
Hmm...I did some more testing and found out that the code is just not working when I integrate it into my app.js. With a clean app.js the code works. So it seems I have some bad code somewhere. I'm going to to test some more and close this issue for now. Thanks for your support :)
