### ISSUE TITLE
[com.sonos] Sound comes from the wrong speaker when having more than one Sonos speaker

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2660]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
When I add more than one Sonos speaker to Homey I am no longer able to make music play in a specific speaker. Music rather plays from the last added speaker no matter what speaker I choose.

I guess this is a well known issue but the problem is still there months later and I can't find any information about it or solutions to it here or in the forum.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/19

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
