### ISSUE TITLE
[com.sonos] Stereo pair

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2661]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
At this time, it is not possible to operate a stereo pair. It would be fantastic if this is possible

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/17

**Comment by stofferr** [comment]
Me2 - please allow to control stereo pairs as one device

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
