### ISSUE TITLE
[com.sonos] Sonos won't play anymore (1.5.0 RC6)

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2662]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Using the Sonos App, I can't play any music from my favourites anymore.
This or a similar error comes up:
<img width="516" alt="bildschirmfoto 2017-08-18 um 12 41 22" src="https://user-images.githubusercontent.com/29104690/29455764-b8928f96-8412-11e7-93ed-dc9d3e539f10.png">

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/16

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
