### ISSUE TITLE
[com.sonos] SONOS ZP80 Shows up as Play 1

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2663]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hello developers,

In version v2.3.0 - 21.04.17 the older SONOS ZP80 which resembles the currently available in store SONOS Connect design (and is slightly smaller than the SONOS connect AMP), does show itself within the Homey GUI with a Play1 device icon.
![sonos_connect](https://user-images.githubusercontent.com/30018954/29233759-11deea24-7ef3-11e7-9da1-97956acab5c3.jpg)
![sonos homey](https://user-images.githubusercontent.com/30018954/29234215-bda02966-7ef5-11e7-902b-534efb30be97.png)

It would be nice if this icon could be corrected/added in a future release.

_**Some info from the ZP80 device in my system setup:**_
Hardwareversion: 1.1.16.3-2
WM: 0
r8: 16.0-7

If you would like me to provide more info, please let me know

Keep up the good work. 

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/15

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
