### ISSUE TITLE
[com.sonos] Speaker Groups

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2664]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hi,
Would be brilliant if you could add a feature that can group different rooms.
Although Sonos' products are not consuming a lot of power when in standby, home automation makes it possible to turn off power to them completely when leaving the house and on again when returning - however, that breaks groups that was made - and it would be really cool if a flow could re-group different rooms when turning the system on again.
Regards,
Chr.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/14

**Comment by WeeJeWel** [comment]
Sorry, but we won't add managing groups in the Sonos app.
