### ISSUE TITLE
[com.sonos] Stop function not available

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2665]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Hello ,

Sonos STOP function is not available and this is an important function to stop radio or TV.
(Pause function is not working with radio or TV)

Regards,
Charles

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/13

**Comment by WeeJeWel** [comment]
Added in v4.0.12.

**Comment by CharleyDoe** [comment]
Keep UP the good work!
