### ISSUE TITLE
[com.sonos] text to speech

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2666]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
In my Vera system I have some triggers that sends a text to speech message to my Sonos speakers. This is done by an additional plugin - VeraAlerts, but the TTS settings is configured in the Sonos app on Vera.
I would like to have a flow card to Say something trough Sonos.
I guess it will require some settings for the Sonos app to choose and configure the TTS server URL.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/12

**Comment by Veldkornet** [comment]
This would be handy if it’s possible. Currently, my Homey itself says a number of things (ie, it announces when someone comes home) and I have a doorbell chime that plays when someone rings the doorbell. 
It would be great if this could be played over the Sonos instead. If the Sonos are spread throughout the house, it will be a sort of PA system ;) At least I will always hear the doorbell ;)

**Comment by WeeJeWel** [comment]
If someone finds a free, commercially-allowed public API which can return an .mp3 URL with spoken text I'll implement this.

Example: `https://company.com/text-to-speech?text=Hello world`

**Comment by Rocodamelshe** [comment]
Why not let us add the service? I have a free account for TTS which i can add.

**Comment by WeeJeWel** [comment]
Then what about a 'Play URL' Flow card?

**Comment by Rocodamelshe** [comment]
That would solve it for 92% me guess yes. Then peeps are also able to sound the alarm on any speaker they want with the sound they want.

**Comment by WeeJeWel** [comment]
Added in the next release

![screen shot 2018-09-26 at 16 53 55](https://user-images.githubusercontent.com/319873/46088484-c6e17480-c1ac-11e8-9252-7cf762bae25a.png)

It even works if you're playing music, the music just resumes afterwards.

**Comment by WeeJeWel** [comment]
Added in v4.0.11 and released to the appstore as beta. Have fun!
