### ISSUE TITLE
[com.sonos] homey mediaplayer and sonos

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2668]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
homey 1.2.2 and 1.3.0.rc7 with latest sonos app
sonos playlists are running fine with the sonos app on my phone
in homey music i can see the sonos playlists but it runs only one song and then stops
perhaps this is the reason,i have also soundcloud playlists and with every number there is a duration of the song in minutes and seconds
the soundcloud playlists runs all the songs
in the sonos playlist there is none duration of the songs,only on the right 00
How is that possible
Further it is not possible to work with the homey media player and sonos if you have two sonos play1's
and you have configured them in pair
you can select the player but it swappes to the internal homey from which you can not play songs

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/10

**Comment by WeeJeWel** [comment]
Playlists are not supported anymore.
