### ISSUE TITLE
[com.sonos] Sonos SUB Icon shows as a Play 1

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2669]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Please add the Sonos Sub icon so this also reflects like all the other models i have.
Cosmetics counts :) And i love a correct and good looking icon

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/9

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
