### ISSUE TITLE
[com.sonos] sonos is not responding to commands

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2670]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
If I want to pauze SONOS from a flow I get an error. See image.

![schermafdruk 2017-04-12 15 10 46](https://cloud.githubusercontent.com/assets/5961917/24959299/add6da56-1f92-11e7-9323-d688a0f610d7.png)

Homey version: 1.2.0 (experimental)
SONOS app version: 2.0.3

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/7

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
