### ISSUE TITLE
[com.sonos] Homey:Sonos is not aware if music was started by other tools/apps

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2671]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
If we start Music on our Sonos speakers via e.g. the Sonos mobile app and not via Homey, then Homey is not aware that music is playing on any of the Sonos speakers.
The result is that if I ask Homey to stop playing music on my Sonos speakers, it keeps on playing, because according to Homey nothing is playing, so no action is taken.

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/6

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
