### ISSUE TITLE
[com.sonos] Request: add local library to SONOS app

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2672]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Yes, old school... but there are still people that have a local library included at the Sonos system, which I would like to use for Homey.

Please add the local library support to the Sonos app

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/5

**Comment by elfrigo** [comment]
would love to see that implemented too

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
