### ISSUE TITLE
[com.sonos] Request: add Tunein radio

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#2673]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Please add the Tunein radio stations to the Sonos app

**Any other remarks**
Moved issue from app repository issue tracker to main issue tracker. See original issue: https://github.com/athombv/com.sonos/issues/4

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
