### ISSUE TITLE
[Cosmetic] Dim level toke VERY accurate.

### ISSUE THREAD

**Issue by Qx5** [athombv/homey#268]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Report dimmer values when light changed.

**What was the result?**

![image](https://cloud.githubusercontent.com/assets/17162373/13379419/8d380b6c-de25-11e5-9a10-4e74e2402561.png)

**What did you expect as result?**

Rounded dimmer values.

**Any other remarks**

none

**Comment by nattlip** [comment]
thats also with temp , but that will come in the future i think , first homey must function.
![temp](https://cloud.githubusercontent.com/assets/7040452/13379708/7ac80646-de2d-11e5-86cd-f8033a2fb379.PNG)
 values,
