### ISSUE TITLE
[feature request][athom-api][HomeyAPI.ManagerApps] disable/enable apps trough API

### ISSUE THREAD

**Issue by rnldnkp** [athombv/homey#2694]
Homey Firmware Versie: 1.5.11

Scenario
Apps like PostNL app, Somfy RTS, Brel, Aggregated Insights, Buienradar, Weather Underground, etc. run 24/7 while some don't have to. Disabling them, when not in use for a longer period of time, would save me over 15% of Homey's RAM at times.

Request
I would like a API call which could enable/disable apps, which could be used to develop an App (or extend Candy) Currently, you can only reboot apps.

Goal
This would free up precious memory when needed by disabling app's that don't need to run 24/7.

Could even be a built in feature, 'Scheduled Apps'

**Comment by Dijker** [comment]
just works as expected and documented here https://developer.athom.com/docs/api/HomeyAPI.ManagerApps.html

from HomeyScript tested with this:
Homey.apps.updateApp( {id: 'nl.postnl', enabled:false} ) 
Homey.apps.updateApp( {id: 'nl.postnl', enabled:true} )

**Comment by rnldnkp** [comment]
really 😬
I did check documentation but overlooked this feature within this method! 

Thanks! Will try it right away, go go faster Homey!

**Comment by rnldnkp** [comment]
This works great. "problem" solved!

**Comment by chrisboer** [comment]
Mmmm already found how it works... ;-)
