### ISSUE TITLE
[Suggestion] Give Homey a device control card on the devices page

### ISSUE THREAD

**Issue by Qx5** [athombv/homey#270]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Quickly change Homey's volume

**What was the result?**

Had to make a flow for changing the volume of Homeys output

**What did you expect as result?**

I expected to be able to click Homey on the devices page and get a control card like I do with my dimmable lights. On this page it would be nice to make some quick changes to Homey like output volume and maybe brightness.

**Any other remarks**

just a suggestion

**Comment by Dijker** [comment]
+1, if it  would also work from the mobile app!

**Comment by irritanterik** [comment]
existing discussing in #239

**Comment by jeroenvollenbrock** [comment]
duplicate of #239
