### ISSUE TITLE
If one of the token values is 'null', there is no trigger

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#271]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Fire a trigger, while (by accident) one of the token values was null.
`Homey.manager('flow').trigger('my_trigger', { type: null });`

**What was the result?**

Trigger was not fired.

**What did you expect as result?**

There should always be a trigger, even if a token value is null.
> Homey.manager('flow').on('trigger.my_trigger', function(callback, args, state) {
> 	Homey.log("Yes!');
> }

**Any other remarks**

Please check the arguments in your API functions.

**Comment by WeeJeWel** [comment]
You should get an 'Not all tokens provided' error. Does this happen?

A trigger should never fire when a token == null

**Comment by nlrb** [comment]
There is no error - nothing happens.

Why should the trigger not fire? There is a valid transition that the user needs to be notified of. Recipients should check the token value to make sure it makes sense IMHO.

**Comment by WeeJeWel** [comment]
To check if the trigger fired succesfully:

```
 Homey.manager('flow').trigger('my_trigger', { type: null }, { /* state */ }, function( err, success ){
    Homey.log(err, success);
});
```

And I don't agree with you. I cannot think of a usecase where a token can be empty. Please provide an example that will change my mind :-)

**Comment by nlrb** [comment]
Of course the caller could do a ' value || "" ', but it would be much more robust if this was done centrally.

Use case where I ran into it is the OEM fault code of a boiler. It is nice to have it as token, but not all boilers support it. If the boiler does not support that value, null was passed.

Unfortunately token definitions are static. If they could be added programmatically, I could add it only if the boiler supports it. But currently you have to define it static in the json.

**Comment by WeeJeWel** [comment]
It's static for a reason, because a user creating the flow would not know when a token was provided or not.

In your case, I advice to supply 'Unknown OEM code' or such as value.

**Comment by nlrb** [comment]
The user would always know, as his boiler either supports it or not. Always the same from a user perspective.

As it is closed, I guess code is now fixed?

**Comment by WeeJeWel** [comment]
No code has been changed, this is still intended behavior :) It is the developer's responsibility to provide a meaningful replacement.

**Comment by nlrb** [comment]
It should at least throw an error if a token value is null. A number of developers have already spent quite some time figuring out what is going wrong in such a case as there is zero feedback.

**Comment by WeeJeWel** [comment]
Doesn't it? The callback's first argument should be an error.

**Comment by nlrb** [comment]
Could be, need to check. Most people don't use the callback as it is optional.

Examples of people that ran into it:
https://github.com/athombv/homey/issues/237
https://forum.athom.com/discussion/929/issue-triggering-flows-from-app

**Comment by matjaz** [comment]
I guess same behaviour applies for undefined?

**Comment by nlrb** [comment]
@matjaz: actually, 'undefined' makes that the tigger does not fire and gives the error 'Error: not all tokens are provided'. With an explicit value 'null' the trigger does fire successfully!
Also note that on errors the callback boolean 'success' is not set to false, but is null.
