### ISSUE TITLE
eTiger devices are not supported

### ISSUE THREAD

**Issue by depeej** [athombv/homey#2710]
* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**: iOS
* **Smartphone App Version**: Latest

**What did you try to achieve?**

Create a complete home alarm system with a variety of sensors, 433 Mhz aswell as z-wave sensors.

**What did you expect as result?**

A working system.

**What was the result?**

Unfortunately I can't add my eTiger sensors. The following products are not supported:
eTiger SAC-03 doorsensor
eTiger ES-D1A Wireless Motion Detector
eTiger ES-D2A Wireless Pet-Immune Motion Detector
eTiger S-D5B Wireless Smoke Detector
eTiger ES-S7A Outdoor Siren

It would be great if it's made possible that I can connect to my existing sensors. I'd like to call a request to create an eTiger app. Thanks!

**Any other remarks**

**Comment by Dijker** [comment]
Hi! Thank you for requesting support for a device.

Athom uses GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? Athom will then consider to support it! https://go.athom.com/request-device-support

Can you close this issue? Please continue to report any bugs you may encounter in the future here.
