### ISSUE TITLE
add new model ds04

### ISSUE THREAD

**Issue by Michel72018** [athombv/homey#2712]
Hi there,

Can you add support for the dyson ds04 edition for homey, i see there is about 1 year nothing happend on the app, can i help?

Sincere,
Michel

**Comment by Dijker** [comment]
Hi! Thank you for requesting support for a device.

Athom uses GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? Athom will then consider to support it! https://go.athom.com/request-device-support

Can you close this issue? Please continue to report any bugs you may encounter in the future here.
