### ISSUE TITLE
Not working when speaker is grouped

### ISSUE THREAD

**Issue by YD85** [athombv/homey#2715]
* **Homey Version**: 1.5.11
* **Homey Log Code**: 5093FB24C8
* **Smartphone Platform**: IOS
* **Smartphone App Version**:

**What did you try to achieve?**
Start flow when i arrive home; sonos to start playing.

**What did you expect as result?**
Speaker start playing in group. Homey should be able to anticipate on groups.
Functionality in homey to be available to create/reset groups based on trigger. for example:
- when i arrive home i want a particular group to be created; e.g. living room, kitchen and dining room.
- when i wake up i want a particular group to be created; e.g. bedroom, bathroom and kitchen.

**What was the result?**
When speaker is grouped, nothing happens. If speaker is not grouped it works fine.

**Any other remarks**

**Comment by WeeJeWel** [comment]
This has been added in Sonos v4.0, which will be released together with Homey v2.0
