### ISSUE TITLE
Virtual buttons aren't working anymore after latest update 4.0.0

### ISSUE THREAD

**Issue by glijie** [athombv/homey#2716]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
 klik aan klik uit v4.0.2
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
 Virual buttons which i made

**What did you try to achieve?**

klik on the Virtual Button which I use for scenes for ages nowe

**What did you expect as result?**

That i would act like a button and works in a normal flow like it used to work lige ages ( before latest update.

**What was the result?**

an error like : Invalid_device-data and after that the button changes in broken sign

**Any other remarks**

please fix, my homey is now not of any use any more

**Comment by meck** [comment]
Same for me all Klikaanklikuit 433 devices stoped working, and also with 4.0.1 and 4.0.2 that it decided to install.

**Comment by glijie** [comment]
updated to 4.02 and issue is still there.

**Comment by glijie** [comment]
spent my evenig for re-adding the virtual buttons, So it works again. 
still it shouldn't be happening after an update
