### ISSUE TITLE
[nl.klikaanklikuit] Doorbell keeps ringing

### ISSUE THREAD

**Issue by Tim-Brass** [athombv/homey#2725]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**: Apple
* **Smartphone App Version**: Version 2

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

I have a flow that triggers when the doorbell is pushed. Now the flow keeps triggering.

**What did you expect as result?**

a flow to run once

**What was the result?**

I have a flow that triggers when the doorbell is pushed. Now the flow keeps triggering.

**Any other remarks**

**Comment by KyleAthom** [comment]
Can you please try to remove the powerplug from Homey for a short time (e.g. 10 seconds) and then try if the devices respond correctly again?

**Comment by Dijker** [comment]
@KyleAthom 
Added a ACDB-7000A to two Homeys  
App 3.15 - > one Trigger each time 
App 4.0.2  - Two triggers each time  I press once!

[2018-08-01T09:19:51.785Z]		AL! Then - Deurbel ACDB-7000A
[2018-08-01T09:19:52.968Z]		AL! Then - Deurbel ACDB-7000A

Also the Devices Card Triggers for A Device Alarm on 2x and off 1x

[2018-08-01T09:19:52.005Z]	Log	Alarm Aan Thuis - ACDB-7000A
[2018-08-01T09:19:52.123Z]	Log	Alarm Aan Thuis - ACDB-7000A
[2018-08-01T09:19:57.072Z]	Log	Alarm uit Thuis - ACDB-7000A

Paired as ACDB-6600  on 4.0.2 the same.

**Comment by KyleAthom** [comment]
This should be fixed in version 4.0.9 which is currently in beta. You're free to test it, let me know if the issues persists.

**Comment by zee-eend** [comment]
Same problem here, my KiKu doorbell keeps ringing. My phone freaks out because of the many push notifications from the doorbell.

I run all the latest firmware.

Saterday 18 aug it first happend, then I restart homey from the desktop app. Problem solved.

Yesterday 20 aug same problem again, same solution again.

Can someone solve this please?

**Comment by KyleAthom** [comment]
@zee-eend have you re-paired the device with Homey? Since the changes that are made in the app it might require a re-pair to renew the device data in Homey.

**Comment by zee-eend** [comment]
No I have not, so I am gonna try that ;)

Thanks for the quick response!

**Comment by zee-eend** [comment]
@KyleAthom the problem seems to be solved now, using your solution. Thanks
