### ISSUE TITLE
[nl.klikaanklikuit] Sockets not responding

### ISSUE THREAD

**Issue by aldotromp** [athombv/homey#2728]
Beste klik aan klik uit , ik merkte tijdens mijn vakantie dat er een update geplaatst is , en zie nu een aantal ontvangers niet meer online,
daarvoor werkte alles prima,

Kan ik de oude app terug krijgen of is dit op te lossen !
Mijn verlichting schakelt nu niet meer automatische !

Graag een oplossing want al mijn flows lopen nu niet meer zoals bedoeld

Aldo Tromp

Please fill out as much of the fields below as you're able.
The Homey log code can be generated at Settings -> System -> Send Log.
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).

If possible, please provide examples that demonstrates the problem,
keeping it as simple and clear as you are able to.

-->

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by KyleAthom** [comment]
Hello,

First off all are issues are in English, so please keep with that.
Can you please provide the detailed information stated in bold? Like your Homey software version, app version and which exact sockets you're trying to use.

If you aren't able to provide these or just looking for regular support please send an e-mail to support@athom.com.

Thanks in advance!

**Comment by aldotromp** [comment]
Best...

 

My homey version is 1.5.11

The problem is that my click to click out receivers (for in the socket always worked, this week there is an update from click to click off and these people no longer work.

 

How do I get this working again?

or can I update the old app for the homey somewhere

Aldo

 



 

Aldo

 

Van: Kyle [mailto:notifications@github.com] 
Verzonden: donderdag 2 augustus 2018 06:54
Aan: athombv/homey <homey@noreply.github.com>
CC: aldotromp <aldo@aldotromp.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] [nl.klikaanklikuit] Sockets not responding (#2728)

 

Hello,

First off all are issues are in English, so please keep with that.
Can you please provide the detailed information stated in bold? Like your Homey software version, app version and which exact sockets you're trying to use.

If you aren't able to provide these or just looking for regular support please send an e-mail to support@athom.com <mailto:support@athom.com> .

Thanks in advance!

**Comment by terrycjones** [comment]
Hi @KyleAthom ,

I'm having a similar issue to @aldotromp ... My homey recently updated the KlikAanKlikUit package, to version 4.0.2 (via version 4.0.1). I'm also on homey version 1.5.11.

It caused what appeared to be all sorts of random problems with some lights not responding to the remote control commands any more. For reference, I've created flows that turn several lights on and off to create scenes in my rooms - so a flow might turn on, off or dim four separate lights. Then pressing a button on a remote control will trigger that flow and hence the light settings that I want.

Further, a different button on the remote control might trigger flows (/scenes) for multiple rooms at the same time. So it might be that pressing a button could trigger somewhere like ten separate lights to change.

It all kind of ground to a halt, and so I started digging. To me it looked like there was a threshold of about three lamp state changes in a flow before things started acting up. I scratched my head, and then saw also that the update states "This update contains a rewrite using new Homey codebases for RF. The update replaces almost 100% of the old app, so there could be some bugs. If you experience a bug you can report it using the button in the appstore."

I added (manually on the "...then" cards) a different time delay on each light state change, so they were staggered over several seconds. This cracked it and things started working again. This is quite a pain of a task when there could be multiple flows starting other flows to set scenes in different rooms...

I wonder if maybe the "new Homey codebases for RF" (or the klikaanklikuit app) might not be queueing up changes in such a way so as to stop commands clashing with each other?

Thanks for any thoughts :-) And thanks for a great product!

**Comment by KyleAthom** [comment]
Thanks for your constructive and detailed reply!

We have worked the whole day trying to figure it out, but it's hasn't been easy. We tried with a lot off different sockets and even combined all of them to test the flows, but in all our scenario's we have not been able to reproduce the issue that the sockets are not responding.

Nevertheless, we have made some small changes and a new beta version with a few potential fixes has been deployed (v4.0.3)
Please report issues very detailed because we cannot reproduce any of the problems stated.

**Comment by jostie123** [comment]
Hi! I had a small similar problem where 1 of my sockets (when switching 2) some times misses the command of turning light on / off i will switch to the beta version and check if this will fix it for me to

**Comment by aldotromp** [comment]
For me is the beta versie not better,

I have also the problems

 

Aldo

 

Van: jostie123 [mailto:notifications@github.com] 
Verzonden: vrijdag 3 augustus 2018 18:24
Aan: athombv/homey <homey@noreply.github.com>
CC: aldotromp <aldo@aldotromp.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [athombv/homey] [nl.klikaanklikuit] Sockets not responding (#2728)

 

Hi! I had a small similar problem where 1 of my sockets (when switching 2) some times misses the command of turning light on / off i will switch to the beta version and check if this will fix it for me to

**Comment by Dijker** [comment]
@aldotromp pls notice your email reply published  your email on the github site!

**Comment by jhutjens** [comment]
All my kaku devices don't work anymore on V4.0.2... I deleted all my devices and wanted to reconnect but can't reconnect any of them... Restarting homey didnt work either...

**Comment by aldotromp** [comment]
Hoi bram ,

Ik heb ook nog steeds een isiue open staan m.b.t mijn rookmelders
Jullie geven nog steeds aan dat homey ze ondersteunen , mijn collega heeft er ook 3 gekocht en werken dus ook niet,
Lijkt me handig dat jullie dit dan ook aangeven !
Zit er al een verbetering in? Met de brandmelders

Met vriendelijke groeten

Aldo Tromp.

**Comment by Dijker** [comment]
Hi @aldotromp 
Could you please take another look at Athom's contributing guidelines? As already mentioned This is an international community so please use English here on GitHub.

The more information Athom has, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact Athom through support@athom.com instead of using the bug tracker

Support can be e-mailed in Dutch also,

Keep it with one issue in each GitHub issue, mentioning all your problems in the issues here doesn't help solving them faster.

**Comment by KyleAthom** [comment]
@aldotromp Please stick to one issues per openend issue. If you' experience other issues with devices, please create a new ticket for them. In that way, it's easier for us to pin down the issues, which makes bug fixing easier for us!
For your other problems, checkout the links from @Dijker .

**Comment by arthurpoortman** [comment]
I've also issues with kaku version 4.0.2
I have the problem with the APC3-2300R switches but also with older switches of kaku, but the strange thing is, some are working well.
The ones witch are not working is in flows where I use Zones.
For example, I have the following flow: If the sun goes down, turn on all devices of all types in the zone Living Room.
Tried everything, created a new flow, delete and add the device, nothing helps.
When I change the flow: If the sun goes down, turn on device1, device2, device3, etc.  then I have no problems at all.

For now that's my workaround.
The same problems I have with turning devices off.

Homey is running on 1.5.12
Kaku app is running on 4.0.2

Hopefully everything is clear, if you need more information please let met know.

Best regards,

Arthur Poortman

**Comment by terrycjones** [comment]
Hi again @KyleAthom ... I'm liking 4.0.6 beta 😄 . I noticed my homey had updated to it during the day, so thought I'd take the manual delays out of one of my flows and give it a go. Works perfectly! I know there are potentially a couple of threads running through this issue (and it wasn't mine anyway, I jumped on the back of @aldotromp 's) but my issue is resolved (assuming 4.0.6 makes its way cleanly into a production release!).

Could you throw any light onto the delta from 4.0.3 to 4.0.6, just out of interest?

**Comment by aldotromp** [comment]
Its working in the whith de new update

**Comment by arthurpoortman** [comment]
Also here it is working again, and the response of the devices is also better.
