### ISSUE TITLE
The Test function give the warning triangle on cards that are right.

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#273]
0.8.17

![test fout](https://cloud.githubusercontent.com/assets/5736105/13388687/5b9fafc2-dec2-11e5-8b40-487cc0af9f24.png)

When you like to know witch card make the flow don't work **only** that card needs the warning.
Otherwise you are makes changes that make the flow not working on the other days.

(This example came as a working around for missing the Sunday.)

**Comment by WeeJeWel** [comment]
This is fixed in 0.8.20 :D
