### ISSUE TITLE
[com.dyson] Dyson app crashes.

### ISSUE THREAD

**Issue by lenwar** [athombv/homey#2730]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: 48037DC2E5
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:**
* **Homey App Version**: 2.0.0
* **Homey App Log Code**: 3d27a934-3c16-4f4b-aba8-a5c576386f49
* **Affected Devices (preferably product codes)**: Dyson Pure Cool Link Tower

**What did you try to achieve?**

Install the app

**What did you expect as result?**

To be able to use the app :-)

**What was the result?**

The app crashes.

**Any other remarks**
When I click the red triangle which gives the mouse-over remark that the app crashed, it gives the following info:

```
module.js:540
throw err;
^

Error: Cannot find module 'debug'
at Function.Module._resolveFilename (module.js:538:15)
at Function.Module._load (module.js:468:25)
at Module.require (module.js:587:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)
at Object.<anonymous> (/node_modules/dyson-purelink/device.js:4:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)

Exit code: 1
Exit signal: null
```

Not sure if relevant information:
Before I began I had the previous version of the app installed. When I found out that that version did not work with my air purifiyer, I disabled the app. It got updated to version 2.0.0 in the background. When I tried to activate it, it crashed. I removed the app and reinstalled it. The same result. I also tried rebooting my Homey, but the app still crashes.

**Comment by Dijker** [comment]
Confirmed, same here!

**Comment by WeeJeWel** [comment]
This is fixed in v2.0.1!

**Comment by Renevanhugten** [comment]
hello the version 2.01 gives (Je mag dit venster sluiten) and close de app with any result.
What do I wrong?

**Comment by WeeJeWel** [comment]
Are you adding the Infrared device, or the Dyson Link?

**Comment by Renevanhugten** [comment]
Dyson Link

**Comment by WeeJeWel** [comment]
Then you either have no devices connected to that Dyson account, or have already included the device you have.

**Comment by Renevanhugten** [comment]
That's weird. I enter my account email and pw from Dyson and thus come with this message.
I give a wrong pw that I get another error message. Invalid connection

**Comment by lenwar** [comment]
I have the same issue.
But I think the issue lies with Dyson. If I log on to their site and look at 'my devices' it doesn't show anything. I already sent an email to Dyson to check it everything is okay. But they haven't replied yet.

I also asked the question on the Athom forum, but no-one replied there.
I have a 2018 model. Is there anything I can do to check?

**Comment by lenwar** [comment]
I did some research on this and appearently Dyson in it's glorious line of thought has created a whole new API for the 2018 models (it looks quite the same to me as a non-programmer at least :) )

I installed the following Pyton module on a raspberry pi and through this I can simply control my 2018 purifyer:
https://github.com/etheralm/libpurecoollink

```
from libpurecoollink.dyson import DysonAccount
from libpurecoollink.const import FanSpeed, FanMode, NightMode, Oscillation, \
    FanState, StandbyMonitoring, QualityTarget, ResetFilter, HeatMode, \
    FocusMode, HeatTarget

# Log to Dyson account
# Language is a two characters code (eg: NL or GB)
dyson_account = DysonAccount("my@email.com","topsecretpasswordthatnoonewillguess","NL")
logged = dyson_account.login()

if not logged:
    print('Unable to login to Dyson account')
    exit(1)

# List devices available on the Dyson account
devices = dyson_account.devices()
print(dyson_account)
print(devices)

# Connect using discovery to the first device
connected = devices[0].connect("172.0.0.2")

# connected == device available, state values are available, sensor values are available
print(devices[0].state)
print(devices[0].environmental_state)

# Disconnect
devices[0].disconnect()
```
spits out
```
myuser@mypi:~# python3.5 coolertest.py
<libpurecoollink.dyson.DysonAccount object at 0x00000000>
[DysonPureCool(serial=XX0-EU-XXX0000X,active=None,name=Myfan,version=ECG2PF.02.05.001.0006,auto_update=True,new_version_available=False,product_type=438,network_device=None)]
DysonPureCoolV2State(fan_power=ON,front_direction=ON,auto_mode=OFF,oscillation_status=ON,oscillation=ON,night_mode=OFF,continuous_monitoring=ON,fan_state=FAN,night_mode_speed=0004,speed=0008,carbon_filter_state=0097,hepa_filter_state=0097,sleep_timer=OFF,oscillation_angle_low=0115,oscillation_angle_high=0160)
DysonEnvironmentalSensorV2State(temperature=304.5,humidity=33,particulate_matter_25=5,particulate_matter_10=3,volatile_organic_compounds=4,nitrogen_dioxide=2,p25r=6,p10r=5,sleep_timer=0)
```

So now it's up to the smart programmers to either use this code or bend this to something that Homey understands/can use :)
