### ISSUE TITLE
invalid_device_data

### ISSUE THREAD

**Issue by PeetersJan** [athombv/homey#2732]
After the last update 4,0,2, several devices are no longer active and showing 'Invalid_device_data'.
Another reason to not update.
"If it ain't broken, don't fix it."

**Comment by PeetersJan** [comment]
Kort samengevat; alle "stekkerschakelaars" werken niet meer.
De inbouwschakelaars vertonen geen enkel probleem.
Kapitale fout in de laatste update! Wordt dit eigenlijk getest vóór release? Ik denk het niet...


arch | arm
-- | --
boot_id | b91593d4-d6b7-4d2a-a92b-f5b97df38ce7
cloud_id | 5abca14542b2c4296e1348e6
cpus | [{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":31278300,"nice":7220600,"sys":52479400,"idle":426483900,"irq":0}}]
date | 2018-08-02T10:43:54.800Z
date_dst | true
date_human | donderdag 2de augustus 2018 12:43:54
devmode | false
freemem | 27930624
freemem_human | 5%
homey_version | 1.5.11
hostname | Homey
loadavg | [0.34130859375,0.39794921875,0.3564453125]
network | {"lo":[{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true,"cidr":"127.0.0.1/8"},{"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","scopeid":0,"internal":true,"cidr":"::1/128"}],"wlan0":[{"address":"192.168.0.114","netmask":"255.255.255.0","family":"IPv4","mac":"2c:6b:7d:11:d5:6a","internal":false,"cidr":"192.168.0.114/24"},{"address":"2a02:1811:2c1b:4e00:2e6b:7dff:fe11:d56a","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2c:6b:7d:11:d5:6a","scopeid":0,"internal":false,"cidr":"2a02:1811:2c1b:4e00:2e6b:7dff:fe11:d56a/64"},{"address":"fe80::2e6b:7dff:fe11:d56a","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"2c:6b:7d:11:d5:6a","scopeid":3,"internal":false,"cidr":"fe80::2e6b:7dff:fe11:d56a/64"}]}
node_version | v8.9.4
platform | linux
release | 4.14.15-g81f15bab94
timezone | Europe/Brussels
totalmem | 511922176
uptime | 52448

**Comment by KyleAthom** [comment]
Duplicate from https://github.com/athombv/homey/issues/2722
