### ISSUE TITLE
APC3-2300R pairing issue, device is not available in the KAKU app. But bought via "Works with Homey" site.

### ISSUE THREAD

**Issue by Starf0x** [athombv/homey#2736]
Pair an KAKU device that is supported according thr "Works with Homey" site.
I also ordered it via the site, but it is not available in the KAKU app.
The APC3-2300R is available via your site, but not in Homey as device, also not via the common search.

**What did you expect as result?**

Connection

**What was the result?**

Not available

**Any other remarks**

**Comment by KyleAthom** [comment]
The driver is available in the KlikaanKlikuit app, so this is not a code issue. Therefor this issue will be closed. If you need further support adding your device to Homey, please contact support at support@athom.com.
