### ISSUE TITLE
Somfy RTS and KaKu not responding since update 1.5.12

### ISSUE THREAD

**Issue by kslinger** [athombv/homey#2737]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**: 0F86224FDC
* **Smartphone Platform**: Android
* **Smartphone App Version**: 0.8.5.115

**What did you try to achieve?**

Tried using the normal flows as before ... no result
Tried removing and adding a device .... no result
Tried switching lights and sunscreens directly from the apps part in the Homey desktop app

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Hi, 
it could happen that the microcontroller for RF hangs, 
Athom is working in a solution but at this moment only workaroud is to Pull the Plug of homey,  (PtP)  and power up a minute later again it should work. 
It happens more often after a firmware update. (but can happen on other times.)


Athom has this issue combined in Issue #2023, 
If it works again after powerdown please close this issue and follow 2023

**Comment by kslinger** [comment]
Thanks Dijker,
I tried rebooting, but that didn't work.
Disconnecting power did work and everything is working now.

**Comment by Dijker** [comment]
Is a known issue for a long time, but probably the final fix is around the corner.
