### ISSUE TITLE
[com.somfy] Describe your issue here

### ISSUE THREAD

**Issue by AdyRock** [athombv/homey#2739]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** Somfy RTS
* **Homey App Version**: 3.0.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Any RTS device

**What did you try to achieve?**

Open a cover with it's remote, Homey still shows the blind as closed.

**What did you expect as result?**

Homey to know if a cover was open or closed

**What was the result?**

Homey gets out of sync when a remote is used.

**Any other remarks**
I know this is a limitation of the RTS being one way communications so Homey can't request the current position from the cover. However if the RTS module could listen for remote commands and update the internal state as if it where the cover that would help.
Is there any possibility that could be added to the Somfy RTS module?
Even Tahoma can't do that so it would give homey a big advantage.

**Comment by MatthewWaanders** [comment]
Hey there!

I'm sorry you're experiencing this issue, I'm also sorry that I can't do anything for you on this one. The Somfy RTS protocol uses a signal range which is outside of the range that Homey listens on. So we can't make Homey respond to the commands sent by the remote.
