### ISSUE TITLE
Scrolling in flow bar is not possible.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#274]
**What is your Homey version (Settings → System)?**

0.8.20
**What did you try to achieve?**

Scrolling of the flow bar is not possible, at work i do have a 21" screen, but with my 13" Macbook it is impossible to scroll to the flow bar. Only option is to re-save the oldest flow so these move down and the flow you want to adjust moves up.

![scrolling flow s not possible](https://cloud.githubusercontent.com/assets/17526110/13392104/972c8e8c-ded8-11e5-9788-c3e6ecf68b3d.png)

**What did you expect as result?**

Scrolling to be possible.

**Comment by Arjanvde** [comment]
Small addition to this bug.

On my iPad, if i want to select a created flow the first 17 flows are displayed correctly, but the next ones are showed outside the GUI.

![schermafbeelding 2016-03-10 om 22 09 40](https://cloud.githubusercontent.com/assets/17526110/13684619/dca403dc-e70c-11e5-9123-885d7b07e81e.png)

**Comment by kerkenit** [comment]
I've installed [stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) in Chrome and added this style. This fixed it temporary. I don't have to zoom out to 25% of the page. That was very small.
`#flows-dialog {
    overflow-y: scroll;
    height: 695px;
}`

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35. (Remember to remove your userstyles)
