### ISSUE TITLE
Com.brel

### ISSUE THREAD

**Issue by viixxiiv** [athombv/homey#2741]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**: 
* **Smartphone Platform**: IOS
* **Smartphone App Version**: (v2)

**If related to a Homey App:**
* **Homey App Version**: 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Brel RF commands no longer working since the homey update. I have flows opening and closing my curtains daily but now they no longer work since the homey firmware was updated to 1.5.12.

Restarted both the app and Homey same issue. I also went into the individual divice to try opening the blinds and doesn’t work.

It was working flawlessly before the update.

**What did you expect as result?**

Work as usual before the update. 

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
it could happen that the microcontroller for RF hangs,
Athom is working in a solution but at this moment only workaroud is to Pull the Plug of homey, (PtP) and power up a minute later again it should work.
It happens more often after a firmware update. (but can happen on other times.)

Athom has this issue combined in Issue #2023,
If it works again after powerdown please close this issue and follow 2023

**Comment by viixxiiv** [comment]
Ok. Closing and following 2023

**Comment by viixxiiv** [comment]
Update: PTP worked for a day or so.. after that, same issue. 433 rf stops working. Can’t possibly be ptp every day just to get 433 working. 
Just a reference, before homey 1.5.12 update, it was working flawlessly for many months daily on 1.5.11.. This happened only after 1.5.12.

**Comment by viixxiiv** [comment]
uninstalled reinstalled the app and repaired the remotes seemed to work.. working 3 days now.. will report again if it results in error.
