### ISSUE TITLE
[nl.klikaanklikuit] Describe your issue here

### ISSUE THREAD

**Issue by corkorten** [athombv/homey#2746]
**Metadata**

* **Homey Version**:latest
* **Homey Log Code**:The unique log ID is: e7785f38-ef20-46c3-ad06-bca9c6b2fb78
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**4.06
* **Homey App Log Code**:The unique log ID is: e7785f38-ef20-46c3-ad06-bca9c6b2fb78
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

the more you progrogramm the more it sucks i got myn acm 3500 working again with 4.03 know the party starts again everything worked perfect sinds update every thing sucks

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by KyleAthom** [comment]
You already had an GitHub issue opened for this problem with this device. Please be patient as we are working on the problems occurring with KlikAaanKlikUit app. We expect to have a new stable version soon where those issues are fixed.
