### ISSUE TITLE
Bug: not possible to exclude 1 date

### ISSUE THREAD

**Issue by fkey3** [athombv/homey#2747]
**Metadata** ??

* **Homey Version**: 1.5.11
* **Homey Log Code**:no log code
* **Smartphone Platform**: ios (not applicable formthis issue)
* **Smartphone App Version**:1.3.3 (not applicable for this issue)

**If related to a Homey App:** no its the homey code itself
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
I want to create a flow that does NOT trigger at a specific day (31 dec) of every year
I expected to be able to do that with the “date” function, but it did not work.
I found a workaround that, which makes me think it is a bug

What I did(see also attachement):
1 Drag the “date” into the “AND” column and select the “date is” function.
2 tick the box to change it to “date is not”
3 select a date (this results in a date including a year in the box)(for testing purpose I used the current date 02-08-2018, final should ofcourse be 31-12-2018)
4 delete the year so it displays: 02-08
(Ps: it did take some time to figure out this was possible...)

**What did you expect as result?**
5 test the flow, it shouls show a red tick

**What was the result?**
6 the flow shows a green tick

I found a workaround that does work and makes me think the above is a bug
1 Drag the “date” into the “AND” column and select the “date is btween” function.
2 tick the box to change it to “date is not between”
3 select a two dates the same!
 02-08-2018 and 02-08-2018
4 delete the year so it displays: 02-08 and 02-08
Intested this in the flow and it worked fine!!
![58cc836e-4c99-4c43-b8f3-af8a293ea8d2](https://user-images.githubusercontent.com/42219340/43860017-b0473a5a-9b52-11e8-9b72-4ae03e8e98cb.jpeg)

**Comment by WeeJeWel** [comment]
Manually deleting the year is not supported (and should've been disabled). You can use the 'It's not the 31st' and 'It's not december' cards together.

**Comment by fkey3** [comment]
@WeeJeWel
Sorry but your suggested solution does not give the desired result. (That was the 1st way I implemented it.)
The combined THEN cards will result in a FALSE for all 31 of every month and all days of december...
Or is the a way to have the THEN column cards act as an “AND” i.s.o “OR” that I missed.

I only want to have a false on the 31 december of every year.

Can you advice on another solution? (or open the ticket to provide a fix that solves this)

**Comment by WeeJeWel** [comment]
I found a way. It surely doesn't win a prize for elegancy.

![screen shot 2018-08-29 at 16 08 12](https://user-images.githubusercontent.com/319873/44793108-c651c000-aba5-11e8-891d-a9a9e52cf2ac.png)

**Comment by fkey3** [comment]
it is indeed ugly, especially since I also have some “lux” checks in the OR area.
I would need to invert these to “false” too, making it really complex
@WeeJeWel reason enough to reopen the issue and have a proper solution sometime??. (Option to select a date without a year)

**Comment by WeeJeWel** [comment]
I've added this to Homey v2.0. 👍
