### ISSUE TITLE
[nl.klikaanklikuit] V 4.0.7 No longer works

### ISSUE THREAD

**Issue by maartenver** [athombv/homey#2750]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:1F15506803
* **Smartphone Platform**: Android 8.0.0 (Samsung S8)
* **Smartphone App Version**: Homey Preview

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Switch on Klik Aan Klik Uit devices.

**What did you expect as result?**
No KlikAanKlikUit devices respond, I can see the "switch" flip on and off, but no signal gets send successfully. 

**What was the result?**
Lights no longer work.

**Any other remarks**
I haven't tried the beta app.

**Comment by Dijker** [comment]
Hi Maarten,
With Kaku there are always several possible issues, it could be the update of the Kaku app. Did it work for you with 4.0.2 ? Or with the version 3.x before.... 

2nd if the RF microcontroller hangs only one solution definitely works....  Pull the Plug from Homey and get a fress start,  after plugging Homey in again and starting all apps please retry if the device responds. 

Please test and report the device type that didn't work and send a log from settings apps by holding the alt while kliking behind the app name.
@KyleAthom  another one for you....

**Comment by maartenver** [comment]
Hello Dijker,
I had restarted the app a few time, and rebooted homey a couple of times as well. Following your advice I have unplugged Homey and let is sit like that for 10 minutes and plugged it back in. This did resolve my issues. As far as I can tell everything is working again.
Thanks for your quick response and helpful advice, it's greatly appreciated!
With kind regards,
Maarten Verbunt
-------- Oorspronkelijk bericht --------Van: Dijker <notifications@github.com> Datum: 10-08-18  22:44  (GMT+01:00) Aan: athombv/homey <homey@noreply.github.com> Cc: maartenver <registratie@ferrarimodelcars.nl>, Author <author@noreply.github.com> Onderwerp: Re: [athombv/homey] [nl.klikaanklikuit] V 4.0.7 No longer works (#2750) 
Hi Maarten,

With Kaku there are always several possible issues, it could be the update of the Kaku app. Did it work for you with 4.0.2 ? Or with the version 3.x before....
2nd if the RF microcontroller hangs only one solution definitely works....  Pull the Plug from Homey and get a fress start,  after plugging Homey in again and starting all apps please retry if the device responds.
Please test and report the device type that didn't work and send a log from settings apps by holding the alt while kliking behind the app name.

@KyleAthom  another one for you....

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/athombv/homey","title":"athombv/homey","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/athombv/homey"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Dijker in #2750: Hi Maarten,\r\nWith Kaku there are always several possible issues, it could be the update of the Kaku app. Did it work for you with 4.0.2 ? Or with the version 3.x before.... \r\n\r\n2nd if the RF microcontroller hangs only one solution definitely works....  Pull the Plug from Homey and get a fress start,  after plugging Homey in again and starting all apps please retry if the device responds. \r\n\r\nPlease test and report the device type that didn't work and send a log from settings apps by holding the alt while kliking behind the app name.\r\n@KyleAthom  another one for you...."}],"action":{"name":"View Issue","url":"https://github.com/athombv/homey/issues/2750#issuecomment-412200880"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/athombv/homey/issues/2750#issuecomment-412200880",
"url": "https://github.com/athombv/homey/issues/2750#issuecomment-412200880",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [athombv/homey] [nl.klikaanklikuit] V 4.0.7 No longer works (#2750)",
"sections": [
{
"text": "",
"activityTitle": "**Dijker**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Dijker",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"athombv/homey\",\n\"issueId\": 2750,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"athombv/homey\",\n\"issueId\": 2750\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/athombv/homey/issues/2750#issuecomment-412200880"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 367205175\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Dijker** [comment]
Hi Maarten,  
Pks see that a email reply exposes you email address. Pls go online to your issue and remove your email address by editing your email response above. Please follow #2023 as this is the issue  you experienced  and close your issue with the button bellow.
