### ISSUE TITLE
[nl.klikaanklikuit] Describe your issue here

### ISSUE THREAD

**Issue by aldotromp** [athombv/homey#2751]
Please go back to versie 3.1.5 

everyting was oke !

versie 4.07 4.08 and 4.09  are not working 

Aldo Tromp

**Comment by KyleAthom** [comment]
Aldo,

Please keep it to a single ticket per issue, or just contact the regular support.
Regularly opening a new ticket on GitHub will not speed up development. In fact it will cost us more time that we cannot spent on development.
I hope you will understand, and will wait patiently until we have resolved all issues with the KlikAanKlikUit app.

Thanks in advance!
