### ISSUE TITLE
[nl.klikaanklikuit] AYCT-202 dim channel not responding

### ISSUE THREAD

**Issue by KyleAthom** [athombv/homey#2755]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Send a dimming command to Homey to trigger a flow.

**What did you expect as result?**
That Homey recognizes the dimming commands from the remote.

**What was the result?**
Nothing, Homey doens't respond.

**Comment by MarcelS1988** [comment]
Here the same, all my KAKU device's not responding. re-install the app, restart homey… still not working. Can't pair the device! I have a ACD-3500 and a ACD-200.
Also with installing the app again, stable of beta I get the following message:
![image](https://user-images.githubusercontent.com/30636298/44049462-7c517a7c-9f34-11e8-9e3d-3b8d5b5fd1eb.png)
Log code: `bc580dc0-a015-4dfe-8ee7-7d4c5346d2b4`

**Comment by KyleAthom** [comment]
Hello @MarcelS1988 ,

This issue is specific for problems with the AYCT-202 device, so I've moved your issues to another ticket. Have a look at https://github.com/athombv/homey/issues/2757.
Could you complement that issue with some more details? Like the Homey software version you're using and the installed version of the KlikAanKlikUit app.

**Comment by KyleAthom** [comment]
This has been fixed in version 4.0.10 which is currently in beta.
