### ISSUE TITLE
[com.qubino] Add support for 3-phase energy meter (ZMNHXD1)

### ISSUE THREAD

**Issue by attiks** [athombv/homey#2756]
Product: http://qubino.com/products/3phase-smart-meter/

Checked the code of the master branch at https://github.com/athombv/com.qubino, but no reference found.

Feature Request

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
