### ISSUE TITLE
Device moved to a different room, let's it dissapear in the home overview

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#276]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Dragging a device from "home" moves it completely out of home and let the device only been seen in the selected zone.

**What was the result?**

In overview the light in the bedroom is missing.
![overview](https://cloud.githubusercontent.com/assets/17526110/13392388/6cfe2b1e-deda-11e5-83d0-50a69822ae70.png)

In the bedroom overview the light is shown.
![overview bedroom](https://cloud.githubusercontent.com/assets/17526110/13392406/8e96d596-deda-11e5-971a-ef3da3f6b240.png)

**What did you expect as result?**

I my opinion "home" should show all devices (12 devices), it doesn't matter if they are linked in a room. If a device is moved to the bedroom on the ground floor, the device should (in my case) be displayed as follows: Home (12 devices), Ground floor (1 device) and the selected bedroom (1 device).

**Comment by WeeJeWel** [comment]
Sorry, but this is intended behavior. If you have many devices, the interface will become too slow to handle.

**Comment by Arjanvde** [comment]
@WeeJeWel 

Ok, makes sense. Please see if there is another lightweight solution in the future For now i won't put devices in other rooms as it makes them disappear in the "home" overview. I can understand this at the  is at the bottom of the list of things to do.

**Comment by WeeJeWel** [comment]
I'll have a good think about it!

**Comment by Joolee** [comment]
Just show X devices and an elipsis indicating there are more devices or arrow buttons to scroll through a list of devices...
