### ISSUE TITLE
[com.qubino] ZMNHODx: Setttings: Invert shutter movement... - Doesn't work

### ISSUE THREAD

**Issue by Krisstenswe** [athombv/homey#2760]
Hi!
When I check the box for "Invert shutter movement direction" it doesn't change direction. The only thing that's happening is that there are no movement at all. If I change back (unbox), the shutter is moving again. It's like that setting would be labeled "Disable shutter movement"...

**Metadata**

* **Homey Version**: 1.5.11
* **Homey App Version**: 2.0.4
* **Affected Devices (preferably product codes)**: ZMNHOD1

**What did you try to achieve?**
I tried to invert the shutter movement by checking the box for "Invert shutter movement direction" under the devices Settings.

**What did you expect as result?**
The shutter movement was inverted.

**What was the result?**
No movement at all.

**Comment by RobinBol** [comment]
Thank you for reporting your issue, I have just updated the beta version of the Qubino App to 2.0.5 which includes a possible fix for your problem. Could you update the App (or wait for it to be auto updated) and let me know if that resolves your issue?

**Comment by Krisstenswe** [comment]
Sorry, but there is no change. No difference in behavior nor resolved the problem.
I have Qubino 2.0.5 and Homey 1.5.12.

**Comment by RobinBol** [comment]
Sorry, I see what is causing it. I have a fix, will be released soon!

**Comment by Krisstenswe** [comment]
2.0.6 fixed the problem! - Thnx!

**Comment by RobinBol** [comment]
Thanks!
