### ISSUE TITLE
[com.ikea.tradfri] Describe your issue here

### ISSUE THREAD

**Issue by Lifewaver** [athombv/homey#2761]
Hi if its possible please integrate IKEAs hub to Homey, that would be great :)

Thank you for reporting an issue. Please take some time to
review the contributing guidelines if you haven't done so.

This issue tracker is for bugs and issues found within Homey.
If you require more general support contact our support team
at: support@athom.com

Please fill out as much of the fields below as you're able.
The Homey log code can be generated at Settings -> System -> Send Log.
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).

If possible, please provide examples that demonstrates the problem,
keeping it as simple and clear as you are able to.

-->

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
