### ISSUE TITLE
[am.smarter] Repository gone

### ISSUE THREAD

**Issue by alydersen** [athombv/homey#2762]
The repository for the Smarter.am Coffee maker and iKettle seems to be gone. The link on your apps page is reported to be 
https://github.com/athombv/am.smarter.ikettle/tree/8ab7e34c6d6b2b38e884dbed4c80754dffd7e995, but there is nothing there. A search amongst your repositories does not return anything either.

**Comment by jeroenvollenbrock** [comment]
This is correct and intended, the upcoming integration of the iKettle v3 and smarter coffee machine V2 required us to move the app into a closed source one.
