### ISSUE TITLE
[com.spotify] Error: media.HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Pause"

### ISSUE THREAD

**Issue by kyote73** [athombv/homey#2763]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: Spotify for Sonos
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Cannot play music.

**What did you expect as result?**

Play music

**What was the result?**

I receive an error: media.HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Pause"

**Any other remarks**

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.
