### ISSUE TITLE
Aeotec Heavy Duty Smart Switch not supported

### ISSUE THREAD

**Issue by pshotton** [athombv/homey#2769]
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: BA894AB5E4

**If related to a Homey App:**
* **Homey App Version**: Aeotec 1.6.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: ZW078-B/C

**What did you try to achieve?**

Tried to pair with the device. There's no icon for it in the Aeotec app. I tried several of the smart switch ones but it always pairs as a generic switch. This allows on/off operation but not access to the power monitoring functions (which was my main reason for purchasing the switch).

**What did you expect as result?**

I expect this product to be fully supported

**What was the result?**

It pairs only as a generic z-wave switch

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
