### ISSUE TITLE
Flows are empty after deleting a device that is used in the flow.

### ISSUE THREAD

**Issue by kkuyper** [athombv/homey#277]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Delete a (IR) device (to create an new one, see [#267](https://github.com/athombv/homey/issues/267)) that is used in a flow.

*Please include detailed steps how we can reproduce the issue*

- In devices: delete a device that is used in a flow.
- Under flows: open the flow which use this deleted device 
 
**What was the result?**

The flows that use this device is empty now.

**What did you expect as result?**

Only the deleted device is removed from the flow.

**Comment by matjaz** [comment]
IMO, ONLY cards that are referring to deleted device should be removed.

Similar happens with cards of removed app.

**Comment by WeeJeWel** [comment]
All other cards should still be visible. Is this not the case?

**Comment by kkuyper** [comment]
No: all cards are removed in the "then" column.

**Comment by WeeJeWel** [comment]
Hm I cannot reproduce. Can you post before and after screenshots maybe?

**Comment by kkuyper** [comment]
Of course, here a small (test) flow to turn television and receiver on. After deleting de "denon" device, all cards are removed in the last column.

![before](https://cloud.githubusercontent.com/assets/17176374/13409361/f67c174a-df32-11e5-8ff2-37b80ba0a4aa.PNG)
![after](https://cloud.githubusercontent.com/assets/17176374/13409372/00b11aa8-df33-11e5-890f-98184416518e.PNG)

**Comment by WeeJeWel** [comment]
Ah, I thought the trigger was deleted as well. Will investigate, thanks!

**Comment by bvdbos** [comment]
I can't confirm this (but I don't have the denon-device)

**Comment by WeeJeWel** [comment]
Fixed a long time ago :)
