### ISSUE TITLE
[Feature request] Renaming a flow should not break chained flows

### ISSUE THREAD

**Issue by vdneut** [athombv/homey#2774]
** How it works now **
The flow action 'Start a flow' holds the name of the flow to start.
When the flow to start is renamed, the connection is broken.

** How it should work **
Flows are referred to by reference, independent of the flows name.

**Comment by WeeJeWel** [comment]
Flows are referenced by ID, however the name doesn't update (that's a known issue, but only visual).

Something else must have happened for this to break.
