### ISSUE TITLE
[nl.klikaanklikuit] Ik mis de ACM-3000.

### ISSUE THREAD

**Issue by Thyzzer** [athombv/homey#2777]
Ik mis de ACM-3000.
Kan deze toegevoegd worden?

**Comment by Dijker** [comment]
See the link Request support for a Device here:
https://github.com/athombv/homey

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
