### ISSUE TITLE
Unable to remove device

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#278]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Installed OpenTherm Gateway app (in development by Ramon Baas, [https://github.com/nlrb/com.tclcode.otgw](archive). When I want to remove a device, there's one device that I cannot remove. I wanted to remove the device, since I have issues accessing its settings. Whenever I want to open them, I get some z-wave page, but the device has nothing to do with z-wave: it's connected via Ethernet.

**What was the result?**
Device is still installed.

**What did you expect as result?**
Device removed and no z-wave settings page for a non-zwave device.

OTG thermostat:
![schermafbeelding 2016-02-29 om 21 03 36](https://cloud.githubusercontent.com/assets/17163901/13407386/7d3712c2-df28-11e5-9c81-0759f174b022.png)

Page that opens when I click top left of thermostat device:
![schermafbeelding 2016-02-29 om 21 03 48](https://cloud.githubusercontent.com/assets/17163901/13407404/8b04fbb2-df28-11e5-87cf-eef30af2661b.png)

Removal not possible; pressing check mark has no effect:
![schermafbeelding 2016-02-29 om 21 04 04](https://cloud.githubusercontent.com/assets/17163901/13407411/9a7cbcec-df28-11e5-8ed6-1dee07158640.png)

**Comment by Muyz** [comment]
Additional info: if I drag the Thermostat to another location on the device grid, I can access its settings and remove it. Now the new device on the left top has the same issue: cannot access settings (Z-wave page pops up) and cannot remove it.

**Comment by ocatie** [comment]
Did you previously had a Z-Wave Greenwave powernode 6 connected to Homey?

**Comment by Muyz** [comment]
Yes, I still have the devices present, but the powernode is not powered so these devices are disconnected for now.
