### ISSUE TITLE
[nl.klikaanklikuit] Devices disappear after one day (invalid_device_data)

### ISSUE THREAD

**Issue by behgez** [athombv/homey#2780]
* **Homey Version**: 1.5.12
* **Homey App Version**: 4.0.11

After coming back from holiday most of my KAKU devices disappeared and showed invalid_device_data. I have reprogrammed them all, but half of them disappear again after one day. I have re-programmed them for three days now and the problem returns every time.

in the flow they still show ok, but in the devices view they show as corrupt

**Comment by KyleAthom** [comment]
Hi @behgez 
How did you add the devices? By cloning the remote signal or did you generate a signal with Homey?

**Comment by behgez** [comment]
@KyleAthom ; I re-added the device through cloning/learning the remote signal from the KAKU remote. It works fine for a few hours before the 'invalid_device-data' appears. Restarting the KAKU app fixes it for a few hours before they get the error message again.

From what I read in other threads and also in all the 1-star app ratings that have been given since the last release, it seems to mainly impact Kaku ACM-1000 and Kaku ASUN-650 (at least for me). It seems that reinstalling an old release through CLI (I don't know how to do that) fixed it for others, but that doesn't sound like a proper solution :-)

**Comment by KyleAthom** [comment]
Could try to pair a device with the generate option? I'm trying to find out if the bug is related to the remote.
What type of remote do you use?

**Comment by KyleAthom** [comment]
@behgez Could try to pair a device with the generate option? I'm trying to find out if the bug is related to the remote.
What type of remote do you use?

**Comment by behgez** [comment]
@KyleAthom I'm using a AYCT-102 remote. I have used the generate option now and will let you know if it stays now.

**Comment by behgez** [comment]
@KyleAthom It is still active, so it must be the learning from the remote that isn't working properly. I'll pair the other ones with the generate option as well and let you know if that gives problems. Thanks!
