### ISSUE TITLE
Nest hello video doorbell not supported

### ISSUE THREAD

**Issue by wdkreek** [athombv/homey#2781]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment]
Thank you for reporting an issue. Please take some time to
review the contributing guidelines if you haven't done so.

This issue tracker is for bugs and issues found within Homey.
If you require more general support contact our support team
at: support@athom.com

https://go.athom.com/request-device-support

via https://github.com/athombv/homey/blob/master/README.md
