### ISSUE TITLE
All sonos devices disconnected!

### ISSUE THREAD

**Issue by YD85** [athombv/homey#2786]
Non of the devices are connected; yesterday sonos has been updated, might be related.
All flows are broken; please provide fix

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by WeeJeWel** [comment]
This has been fixed in the v3.0.1 Sonos App.
