### ISSUE TITLE
[com.ikea.tradfri] Changing color of the RGB bulb in a flow turns the lamp to 100% brightness

### ISSUE THREAD

**Issue by KRiZ-R** [athombv/homey#2787]
**Metadata**

* **Homey Version**: 1.5.12

**IKEA App: com.ikea.tradfri**
* **IKEA App Version**:1.2.2
* **Affected Devices (preferably product codes)**:  RGB Trådfri lamps

**What did you try to achieve?**
I made a flow to turn on the light dimmed to 10%, after that I want to change the color to red. The light then turns to red, but also turns to 100% brightness.

**What did you expect as result?**
I expect the light to keep the already set brightness and only change the color.

**What was the result?**
The result is; When changing color with a flow, the brightness turns up to 100% instead of the already set brightness.

**Any other remarks**
This only happens in a flow. When going to devices and manually set the color, there is no problem.

**Comment by WeeJeWel** [comment]
The color you picked contains a dim value (every RGB color does).

In Homey v2.0 we've changed this behavior to only change the Hue and Saturation.
