### ISSUE TITLE
'NPM install' not executed for published apps (allow node_modules to be ignored in GitHub)

### ISSUE THREAD

**Issue by harriedegroot** [athombv/homey#2789]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
All apps using external packages (Novy Intouch V2 as a specific case, but also klikaanklikuit for example).

* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Publish an app to the app store. App installs fine by using athom-cli, but crashes when installed via app store. All publication checks are passed. App crashed because the node_modules folder was missing. The node_modules folder should not be included in source control, but added to the .gitignore file.

**What did you expect as result?**

NPM install to be executed by Athom when adding an app to the store or when installing the app. At least do not get passed the publication checks when the folder is missing (for now...).

**What was the result?**

App crashed when installed via store

**Any other remarks**

Issue is resolved by adding the node_modules folder to source control, but this should not be necessary...

**Comment by jeroenvollenbrock** [comment]
This would open up the possibility for code injections in production apps. Homey apps require node modules to be checked in into git as mentioned in the [developer documentation](https://developer.athom.com/docs/apps/tutorial-App%20Store.html).
