### ISSUE TITLE
After resetting Z-wave network unable to add a device

### ISSUE THREAD

**Issue by RemonBerends** [athombv/homey#279]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
Because there were still some problems with Zwave nodes, i decided to reset the Zwave network, to delete all attached nodes and start over again.

**What was the result?**
Well after resetting network all nodes were gone in the network. When i tried to connect my Fibaro FGFS-101 (smokedetector v2) and my FGSD-002 (floodsensor), Homey didn't find any device. Rebooted my Homey and tried again multiple times, but no result. 

**What did you expect as result?**
That my Fibaro devices would work finally as expected. and that i coud finally start to play around with my Homey and a few Zwave devices. Somethng what was promoted from the start.

**Any other remarks**
Problems with the FGRGBWM-441 (RGBW controller) still exist in 0.8.20. Just the main node is visible and usable.
...

**Comment by ocatie** [comment]
When you reset your controller the old network data still exist in the other devices. You'll have to clear the network data from then by using the Remove Node processing in Homey or reset the devices.
