### ISSUE TITLE
Tag for changed meter_power capability trigger card shows Wh. Should be KWh or named energymeter.

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#2791]
**Homey Version**: 1.15.2

The flow card tag for meter_power capability trigger card is named Wh. This is confusing. Either because meter_power is calculated in KWh but also because the similar trigger card for changes in measure_power capability has a flow card tag which is called Energy. I would expect this flow card tag to be called energymeter for sake of uniformity.

**Comment by WeeJeWel** [comment]
This has been fixed in Homey v2: https://github.com/athombv/node-homey-lib/blob/master/assets/capability/capabilities/meter_power.json
