### ISSUE TITLE
Add support for IKEA Tradfri Drivers

### ISSUE THREAD

**Issue by fresim** [athombv/homey#2792]
Hi

Any plans to add IKEA Tradfri drivers for light in the kitchen cabinet etc..

BR F

**Comment by magnuslagerberg** [comment]
They are based on the zigbee protocol aren't they? Then shouldn't just work by add them as a zigbee object?

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
