### ISSUE TITLE
Sonos app crashes after update Sonos software to version 9.1

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#2796]
**Metadata**

* **Homey Version**:1.5.12
* **Homey Log Code**:9B2FBA2D3A
* **Smartphone Platform**:iOS
* **Smartphone App Version**:V2 beta

**If related to a Homey App:**
* **Homey App Version**:v4.0.3 Alpha (even tried beta and standard app)
* **Homey App Log Code**:9851c2c2-f2e0-416f-b5b6-a636769b90e3
* **Affected Devices (preferably product codes)**: All Sonos speakers (Sonos One, Sonos Play 1, Sonos Play 3, Sonos Subwoofer, Sonos Playbar)

**What did you try to achieve?**

Manage Sonos speakers after updating the Sonos software to version 9.1

**What did you expect as result?**

That the app on Homey was not affected

**What was the result?**

Sonos app crashes all the time and Sonos speakers are not manageable/reachable by Homey anymore

**Any other remarks**
I restarted Homey and afterwards PTP without results

**Comment by Rocodamelshe** [comment]
#https://github.com/athombv/homey/issues/2786

**Comment by fvhuizen** [comment]
I managed to get Sonos partly working again. I installed the beta version, restarted the Sonos Bridges and speakers and now the Sonos app in Homey works again. But there is something changed, mute and unmute doesn’t seem to work and instead of that i use play and pause. For now a workaround but it think something in the app is changed in combination with the Sonos SW update 9.1

**Comment by fvanbeenen** [comment]
Same here. I tried to get a downgrade from Sonos, but they seem not able to get me a downgrade unfortunately. Everything worked fine until now. Hope there will be a solution soon.

**Comment by fvhuizen** [comment]
Problem is solved in the new Alpha and the beta version, so for me it's a closed issue
