### ISSUE TITLE
off command not working with RF

### ISSUE THREAD

**Issue by madtraxx18** [athombv/homey#28]
seems that the off command (voice) is not correctly interpreted.

**Comment by WeeJeWel** [comment]
Could you elaborate what you're trying to achieve?

**Comment by madtraxx18** [comment]
pair a KAKU wallsocket with the homey, give at a name and add it to a location. Then give the simple command;

OK homey, turn lights off..... Homey responds with; Turning lights on

**Comment by freemann** [comment]
@madtraxx18 any news on this issue?

**Comment by WeeJeWel** [comment]
distinguishing between on and off is pretty hard when at the end of a sentence. It usually helps to say 'Turn on the lights' instead of 'Turn the lights on'

**Comment by freemann** [comment]
@WeeJeWel please create a list with commands that work and advice about how to formulate sentences, words not to use, etc.

**Comment by WeeJeWel** [comment]
I will in time @freemann !

**Comment by freemann** [comment]
I hope for Athom before the big shipment of the Geeks, else you can expect a ****load of complains/issues.

**Comment by madtraxx18** [comment]
Seems to be solved now. If I say; homey turn off all lights everything turns off. Including zwave and RF
