### ISSUE TITLE
IR wizzard doesn't find correct remote.

### ISSUE THREAD

**Issue by RemonBerends** [athombv/homey#280]
**What is your Homey version (Settings → System)?**
0.8.20

**What did you try to achieve?**
Tried to autodetect a recent Samsung remote control. Used the automatic wizzard and tried this with different buttons on the remote. Every time it came with the same but different type remote control.
A lot of buttons were marked as 'unknown'. (Samsung AA59-00786A) delivered with two of my 2 yr old smarttv's).

**What was the result?**
That a lot of buttons are marked as unknown button.

**What did you expect as result?**
That the correct remote would be found with all buttons predefined.

**Any other remarks**
Would be nice if you could search the IR databank by typenr. of remote control and add it that way.
...

**Comment by bvdbos** [comment]
Did you type "samsung" in the wizard? You can add devices by model but I didn't see the 00786A...

**Comment by RemonBerends** [comment]
@bvdbos Thx for the tip, but i also could'nt find my remotes.

**Comment by goldenice** [comment]
@RemonBerends Sadly our remote database is incomplete. If however, you get to the stage where you can verify the buttons on your remote, you can rename them as well. Just give the unknown buttons another name, and you're good to go. While I agree that ideally the remote would just work out of the box, we deem this an acceptable solution to the problem of not having all remotes in our database.

By the way: you can search the database by type number. The searchfield in the pairing wizard applies both to the brand and model number of remotes in the database :wink:

**Comment by kitkat14** [comment]
Homey didn't recognize my remote (dream multimedia). After searching for it manually I could find it in the DB so yeah. This shouldn't be seen as a bug because its just impossible to have the complete DB. Best thing would be to make the DB extendable for community additions later on and if nothing is found you just have to put it in manually :)

**Comment by mvunen** [comment]
When learning the IR codes manually 40% of the buttons aren't recognized. Homey doesn't react or highlight a previous entry. I have a Sony Bravia remote RM-ED060

**Comment by jordenc** [comment]
RM-TX100D also not in the database. If I enter all codes for 1 to 9, no remotes matching can be found.

**Comment by imtt1980** [comment]
@mvunen Got the same issue. Also with Sony remote RM-ED060.

**Comment by freemann** [comment]
Please see of this can help you;
https://forum.athom.com/discussion/comment/16008/#Comment_16008

**Comment by bvdbos** [comment]
I think this bug is obsolete as the IR-interface (and backend afaik) was rewritten...

**Comment by bvdbos** [comment]
closeme
