### ISSUE TITLE
[com.athom.soundboard] Describe your issue here

### ISSUE THREAD

**Issue by fantomnotabene** [athombv/homey#2804]
**Metadata**

* **Homey Version**: 1.5.12

* **App Version**: v2.0.1 - 04.08.18

**What did you try to achieve?**

Add 40kb mp3 file to Soundboard app

**What did you expect as result?**

Adding

**What was the result?**

Got the "Invalid file type! Supported types are .mp3 or .wav" error

**Comment by fantomnotabene** [comment]
Figured it out, but, I think, must not be closed. 
The behavior described above was on the macOS Mojave's Safari. 
Chrome works like a charm.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as using safari is not officially supported
