### ISSUE TITLE
[nl.klikaanklikuit] No response on my CoCo AYST102 or Elro AB440-R. Since this morning.

### ISSUE THREAD

**Issue by larahoun** [athombv/homey#2805]
I have restarted Homey, checked batteries, re-saved flows that handles AB knobs and Z-wave switches and lamps. Homey Version 1.0.4 

The only CoCo switch I use doesn't work either.
An Action Doorbelle doesn't work either.

Restarted the elro and CoCo apps. 

Seems to be e hardware/firmware issue

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by KyleAthom** [comment]
Hi @larahoun ,
Which version of the KlikAanKlikUit app do you use? And are you sure about Homey version 1.0.4? Becasue that is a very old version, the current stable version is 1.5.12.

**Comment by larahoun** [comment]
Information Update: Now I performed a hardware reset (pulled out the plug) : Now the first orange restart led ring was shown (didn't show on the software reset): after the restart when i view the only 433 switch i use ( the CoCo) it sais :"unavailable" 
5 minutes later it is available again and the 433 seems to be working.

I'm using CoCo app version  4.0.11

**Comment by larahoun** [comment]
I wondered about the Homey version too. In the menu item on the Homey startscreen it says 1.0.4.

When I go to system it says 1.5.12

**Comment by larahoun** [comment]
![image](https://user-images.githubusercontent.com/40468193/45417588-d1671e80-b682-11e8-8f54-c9c60bbc2bae.png)
This is the version-info on the startscreen. It seems to show the wrong version.

**Comment by KyleAthom** [comment]
That is the version of the Homey desktop application, not the software on Homey itself. That is in your case a correct 1.5.12.
Can you try and re-pair your remote to see if it will work again?

**Comment by larahoun** [comment]
After the hard reset (unplug the Homey) i've got everything going again.

It seems the 433Mhz needed a hard reset. (later I notices a hardware reset in the developers-environment)

Thanks for your assistance: it works again.
