### ISSUE TITLE
KAKU stopped working

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#281]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Use open-close sensor. Worked for a long time, but now even after several reboots it does not.

**What was the result?**

Nothing. No indication sensor works. Cannot pair new devices.

**What did you expect as result?**

See open close sensor work in UI.

**Any other remarks**

Log 71772D348C

**Comment by Muyz** [comment]
Power-cycle Homey fixed it. Multiple reboots did not.

**Comment by KroontjesPen** [comment]
This is also happened here twice. 
Because I am still afraid that Homey can be bricked again after a reboot not looking further in to it.

Conclusion here: Reboot button is not working like a power-cycle reboot.

**Comment by markvandeven** [comment]
same issue, pairing new device doesn't work.

**Comment by bvdbos** [comment]
works for me, AMST-606 still works after three days...

**Comment by TedTolboom** [comment]
@ReinierH 
Same issue here (almost on daily / multiple times per day), KAKU stops working (on 0.8.24) but does not block my Homewizard to control the KaKu devices. Has to power-cycle Homey to get resolved (rebooting does not).

Log: B7AD2F464C

**Comment by ReinierH** [comment]
@TedTolboom 
Found nothing in the logs. Is it only kaku or? Can you try to disable all the apps and look if this solves the problem? Let me know.

**Comment by TedTolboom** [comment]
@ReinierH I'm starting to become unsure if issue is originating from KAKU not working any more or Z-wave stability issues #381  

I'm using a KAKU wall switch in combination with KAKU switches (either via HomeWizard or Homey) and via Homey with Z-wave devices (testing for now). I frequently have Z-wave loss of connection issues similar to #381. But in above case, I lost the ability to control KAKU devices from Homey.

I will try to reproduce / troubleshoot (disabling all the apps) further if it re-occurs again.

**Comment by Dijker** [comment]
Today after a restart last night (uptime les than 12h) KAKU stopped working. 
Other things still work (Like NFC, The idle LED ring, web interface, speech) 
Logs Send: 2016-05-06 13:13:20 3D89FC6BE3 
After restart (soft, no powercycle) it was working again. 
tested it and created logs again (maybe the problem is visible in the post reboot logs )
2016-05-06T11:29:06.390Z	SpeechOutput: speech	"LogSend 603E8CBFC5"

**Comment by Dijker** [comment]
Same again yesterday morning and this morning: 
This morning I had to Power Cycle to fix it. 
Yesterdays logs: 2016-05-07  08:15:?? 8C07293713
todays logs:         2016-05-08 08:47:26 12F20CBFDC

**Comment by ReinierH** [comment]
Looks like we fixed the kaku bug aswell as issues when performing a reboot. Will do some more testing this week to make sure this fix solved the kaku problems.

**Comment by Dijker** [comment]
Reading the forum and my personal experience most stability issues are solved in the latest firmware 0.8.35 and/or KAKU App 1.1.3.
Does anyone still have this problem since 0.8.34 ?
