### ISSUE TITLE
[nl.klikaanklikuit] After automatic upgrade to 1.5.12 firmware KAKU not working

### ISSUE THREAD

**Issue by gizmodok** [athombv/homey#2810]
**Metadata**

* **Homey Version**:1.5.12
* **Homey Log Code**: 403A2E9427
* **Smartphone Platform**: NA
* **Smartphone App Version**:NA

As described in the topic after automatic update of homey firmware klik aan klik uit nothing is working.
Ive rebooted the app no change, Ive rebooted  Homey no change.

KAKU app ver: v4.0.11

Please correct the issue.

**Comment by KyleAthom** [comment]
Hi @gizmodok,

Please unplug the power from your Homey and leave it unplugged for at least 5 minutes.
After that KlikAanKlikUit and other apps using 433 should work fine again.
If not, please contact support by sending an e-mail to support@athom.com.. Note that this however is a bug tracker and not a regular support channel. Therefor this issue will be closed.
