### ISSUE TITLE
[nl.klikaanklikuit] Describe your issue here

### ISSUE THREAD

**Issue by fhmattsson** [athombv/homey#2813]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:KlikAanKlikUit v4.0.11
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Have added a number of NEXA MYC-2300 devices

**What did you expect as result?**

**What was the result?**

After a day or two devices are appearing as "invalid_device_data"
. The problem can be reproduced

**Any other remarks**

**Comment by Dijker** [comment]
There are small differences between the KlikaanKlikuit devices and Nexa devices, 
as these differences produced a lot of issues in the KAKU version 4.x  app update Athom created a Nexa App specific for these devices. 

Please install the Nexa App and pair your Nexa devices with this driver/App
https://apps.athom.com/app/se.nexa

**Comment by KyleAthom** [comment]
Hi @fhmattsson ,

Please use the dedicated Nexa app as @Dijker pointed out.
If the problem persists in that app, please create a new issue for the Nexa app. If you do so, please explain some details how to reproduce the issue. For examplce if you cloned a remote and when the error shows up.

**Comment by fhmattsson** [comment]
The same problem occurs on both Nexa and KlikAanKlikUit
