### ISSUE TITLE
No "speaker_track" capability? No "media" mobile-ui-component-id?

### ISSUE THREAD

**Issue by fantomnotabene** [athombv/homey#2819]
**Metadata**

* **Homey Version**: 1.5.12

**What did you try to achieve?**

Add, e.g., capability "speaker_track" to my own app

**What did you expect as result?**

Working app

**What was the result?**

The 'invalid_capability' error

**Any other remarks**
Also, when I try to create my own capabilities, I can't apply "media" mobile-ui-component-id to them (trying because such type specified in the "speaker_track" capability's description). But it is not listed in allowedValues, so I can't use it.

**Comment by WeeJeWel** [comment]
speaker_track is a Homey v2.0 capability :)
