### ISSUE TITLE
[com.fibaro] Support for [FGBS-222] Smart Implant 

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#2820]
The Fibaro Binary Sensor 2 has just been launched, now call the Smart Implant (FGBS-222). 

Could you please add support for it? 

Adding support for devices seems to take for ever, so I thought I’d better get a head start.

**Comment by jeroenvollenbrock** [comment]
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.
