### ISSUE TITLE
[nl.action] Eurodomest devices stopped working after homey update 1.5.13 rc.11 

### ISSUE THREAD

**Issue by arjanmanders** [athombv/homey#2821]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Button presses don't work anymore after update. Can't add te device again.

**What did you expect as result?**

See above

**What was the result?**

Nothing happens, homey doesn't react to button presses on the eurodomest devives. Also the eurodomest switch doesn't work aswell. 

**Any other remarks**

**Comment by arjanmanders** [comment]
Unexpectedly started working again... Strange, because I did reboot the app en homey before, and now it just started working again..

**Comment by hanek004** [comment]
My Homey has the problem as described with Eurodomest devices and PtP / reboot doesn't change this. See also [this issue](https://github.com/athombv/homey/issues/2843#issuecomment-423740618).
