### ISSUE TITLE
[com.sonos] Mute does not work with the playbar

### ISSUE THREAD

**Issue by CharleyDoe** [athombv/homey#2827]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**: 112FB1C2C3
* **Smartphone Platform**:iOS
* **Smartphone App Version**:1.3.3 -B 70

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
mute the sound when homey listened

**What did you expect as result?**
mute the sound 

**What was the result?**
it does not mute (only playbar, this playbar is in d.surround mode) other speakers can be mute like play 1 and 3 in stand alone mode.

**Any other remarks**
when testing the mute function in a test flow you see the Spinning wheel endless spinning

**Comment by WeeJeWel** [comment]
Fixed in v4.0.9.

**Comment by CharleyDoe** [comment]
It is working!!
Keep UP the good work!!
thnx
