### ISSUE TITLE
bitbucket apps

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#283]
Can we get access to bitbucket apps source code?
It looks like most 433 apps are on bitbucket?
Any good reason not to disclose source?

**Comment by WeeJeWel** [comment]
Some apps are closed-source, because they contain lots of hard work of analyzing (mostly 433) protocols. We wouldn't want competitors to steal our hard work.

**Comment by matjaz** [comment]
OK. fair enough. In that case can we get more documentation about wireless managers, 433 & Signal class?
I am trying to figure it out how to use it for https://forum.athom.com/discussion/802/quigg-draadloze-contactdozenset-aldi/p1
Thanks.

**Comment by WeeJeWel** [comment]
433 & 868 docs are in the making, as well as the dev tools (capture packets and stuff, awesome!)

@Dennishacq please migrate nl.klikaanklikuit to https://github.com/athombv as well
