### ISSUE TITLE
Sonos devices stop working after Homey 1.5.12 update - not com.sonos related

### ISSUE THREAD

**Issue by stofferr** [athombv/homey#2830]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: not relevant
* **Smartphone App Version**: not relevant

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Use SONOS app to control sonos speakers

**What did you expect as result?**

Be able to play music, stop and pause music et cetera

**What was the result?**

SONOS app indicates "no music selected"; music plays but cannot be stopped. Only physical SONOS device buttons work after that.

**Any other remarks**
Contacted SONOS support and they indicate the most recent update 1.5.12 causes issues with uPNP leading to SONOS speakers not working properly anymore. They recommend restart of the Homey and that temporarily solves the issue.

Please make sure that an update occurs in which the uPNP changes are reverted so my SONOS speakers work again.

**Comment by stofferr** [comment]
From SONOS Nederland support:
> Voor iedereen die ervaart dat het systeem 'geen muziek' zegt maar wel speelt, kijk of je Homey in je huis hebt. Deze blokkeren sinds hun laatste update upnp in het netwerk. Het opnieuw opstarten van de Homey zou dit probleem op moeten lossen. <

**Helaas dit lost het probleem slechts tijdelijk op.**
Gelieve dit issue z.s.m. op te lossen in de firmware.

**Comment by WeeJeWel** [comment]
This should be fixed in the latest Sonos app (v4.0.6).
