### ISSUE TITLE
[com.ifttt] Describe your issue here

### ISSUE THREAD

**Issue by GitHubLuigi** [athombv/homey#2836]
After the latest update none of the IFTTT flows are working anymore.
Restarted Homey, restarted the IFTTT app, checked IFTTT, nothing worked.

**Comment by kallewahlback** [comment]
I have the same problem, get the error message, "502 bad gateway".

**Comment by RobinBol** [comment]
@GitHubLuigi could you provide more information? There is an issue template available when you create an issue (for a reason).

Specifically, what update are you referring to?

@kallewahlback where do you see this message? Could you also provide some more information?

**Comment by GitHubLuigi** [comment]
It has been solved with the update from this afternoon. IFTTT is working again.

**Comment by RobinBol** [comment]
@GitHubLuigi @kallewahlback we noticed something regarding the ifttt service, I just pushed an update (after your last comment @GitHubLuigi ) of the ifttt app for Homey. Could you both verify that everything is functional for you again?

**Comment by kallewahlback** [comment]
I will check and verify after 11pm. Thanks for quick support :)

**Comment by GitHubLuigi** [comment]
Hi Robin, I can confirm everything is working as intended. IFTTT get’s triggered by the flows again. Thx!

**Comment by kallewahlback** [comment]
Hey, Everything works fine again now! Thanks again @RobinBol Good work!

**Comment by RobinBol** [comment]
Thanks for the update! I will close this issue now, if you have any further issues in the future please let us know.
