### ISSUE TITLE
[com.sonos] After updating/clean install to 4.0.5 stereopairs and sub are no longer shown, only individual speakers

### ISSUE THREAD

**Issue by raymondwigmore** [athombv/homey#2838]
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Rocodamelshe** [comment]
Good point! Shame u did not fill in the issue like u supposed to. 
But yes, even the bridge is showing as seperate device while in the "old" app it was better imo.

**Comment by WeeJeWel** [comment]
In the new app all devices are shown separately, and this is intended behaviour. Stereo pairs and groups might change over time, and Homey has the philosophy of 'every physical device a Homey device'.

In the new app, their state is synchronised so you shouldn't have any problem controlling them.

**Comment by raymondwigmore** [comment]
Dear WeeJeWel, I do understand that the Groupon of devices is something that is mores fluid in daily use.... However, stereopairs / surround setups / and SUBs and Playbars are something entirely different, both from a user perspective as from a Sonos perspective.... So please reconsider implementing this. It feels you have no idea of the Sonos concept to be frank

**Comment by raymondwigmore** [comment]
As stereo pairs, subs and playbar (dolby surround setups) are really different levels / freq’s send to the individual speakers

**Comment by raymondwigmore** [comment]
Please re-open

**Comment by WeeJeWel** [comment]
I'm missing the point as to why this is a real problem, and not just an aesthetic one?
