### ISSUE TITLE
[com.sonos] No TuneIn stations available

### ISSUE THREAD

**Issue by cbho** [athombv/homey#2839]
* **Homey Version**: 1.5.13-rc.11
* **Homey App Version**: Sonos Beta v4.0.7

**What did you try to achieve?**
Play a TuneIn radio station using the provided flow card

**What did you expect as result?**
That stations available at my Sonos system would appear

**What was the result?**
No stations appear - the list says "No results" no matter what I do...

**Comment by DickvanderMaal** [comment]
There was an issue with TuneIn it didn't work on the Sonos app as well but today it works again.But TuneIn worked with 4.05 but after the two updates it don't work any it reports a Sonos unknown Media Request

**Comment by cbho** [comment]
PTP didn't solve it - but after re-installing the app, stations now appear when typing in the station name (more than three characters)
