### ISSUE TITLE
playing music/sound

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#284]
Looking into soundcloud app I have added following code to test playing sound on homey.

```
Homey.manager('media').setTrack({...}) // same as soundcloud app
```

The issue is, sound is not played calling `setTrack` directly.
Doing a full search/play/setTrack cycle is working. 
You can find source here https://github.com/matjaz/homey-youtube/blob/master/lib/media.js

**Comment by WeeJeWel** [comment]
The user must still invoke the play command to actually start the song.

**Comment by matjaz** [comment]
you mean on /manager/media? How can we play music directly from action?

**Comment by matjaz** [comment]
another use case is wolfram alpha app https://github.com/matjaz/com.wolframalpha/blob/master/app.js#L48

**Comment by WeeJeWel** [comment]
Ah. Starting music playback automatically is explicitly forbidden for apps. However, with a future update it's possible to play small sounds at any time.

**Comment by matjaz** [comment]
can you elaborate why this limitation? I think wolfram app use case is a good one. If user wants an app which can play directly I don't see an issue.
There is no similar limitation for speech output (also sound).
Maybe new permission could be added (play directly).

**Comment by WeeJeWel** [comment]
This will be added with a rewrite of the media manager :)

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by matjaz** [comment]
yeah. looking into soundboard app it uses speaker manager and supports only local wav & mp3.
wolfram alpha and youtube requires http streaming mp3..

**Comment by bvdbos** [comment]
Chiming in: https://apps.athom.com/app/nl.santor.vradio
streams icecast mp3-streams...

**Comment by matjaz** [comment]
Code looks similar to Youtube, which uses `media.setTrack()`. The problem is, user must still explicitly click play in media manager.
