### ISSUE TITLE
[com.spotify] The Spotify Connect speaker list is not complete

### ISSUE THREAD

**Issue by HuiPri** [athombv/homey#2842]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: iOS
* **Smartphone App Version**: n/a

**If related to a Homey App:**
* **Homey App Version**: 3.1.0 beta
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Add a Spotify Connect speaker

**What did you expect as result?**

A list with all my Spotify Connect speakers

**What was the result?**

Only 1 Spotify Connect speaker appears in the list (I have 5)

**Any other remarks**
When I open Spotify app on iOS, I see all my speakers
I have to select them 1 by 1 to make them appear in the Homey Spotify app list to be able to add them to my devices. This was the same in the previous version of Spotify for Sonos app

**Comment by WeeJeWel** [comment]
What brand and model are the unlisted devices?

**Comment by HuiPri** [comment]
The brand is Teufel, three different models: 

 

  3x Raumfeld Connector (2x WiFi, 1x cabled), 

  1x Raumfeld One S (WiFi), 

  1x Raumfeld Stereo Cubes (WiFi)

**Comment by WeeJeWel** [comment]
Unfortunately we have no control over this list, as it's provided by Spotify's cloud service.
