### ISSUE TITLE
[nl.brel-motors] Connecting to Remote does not work

### ISSUE THREAD

**Issue by svm85** [athombv/homey#2845]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:  2.0.1
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Control Brel curtain motor 

**What did you expect as result?**

Up/Down

**What was the result?**

Brel used to work fine with homey, not not responding anymore. Brel remote works fine. Restarted Homey, removed brel app, reinstalled, restart again. When installing, app hangs on "Copy signal Remote" and installation does not finish. 

**Any other remarks**

**Comment by svm85** [comment]
Tested again, and also restarted microcontroller. Homey seems to to receive signal of remote, installation cannot be finished.

**Comment by Dijker** [comment]
Did you PtP?
