### ISSUE TITLE
resetting 433 microcontroller on https://developer.athom.com/tools/signals gives fault

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#2851]
homey firmware 1.5.13-rc11

wevbsite version i dont know

but pushing the reset 433 controller button gives fault

![signal reset homey](https://user-images.githubusercontent.com/7040452/45966467-84445e80-c02b-11e8-8f3f-5dde8edbc351.png)

**Comment by Dijker** [comment]
The reset isn't necesary with firmware > .13 
it is in the interface for the users running < .13 firmware and will be removed when that version is stable. 
(not sure they will implement a check on Homey FW version for it. )

**Comment by nattlip** [comment]
but i have 0.5.13 which nor < nor > 13 ? how to do it with 13 ?

**Comment by Dijker** [comment]
Sorry first should have been >= .13 or > .12  ;-)

**Comment by nattlip** [comment]
but how to reset microcontroller ?

**Comment by Dijker** [comment]
It didn't work with that button in many times before an the we all say PtP .....

**Comment by nattlip** [comment]
but htat button was to prevent ptp

**Comment by WeeJeWel** [comment]
The button has been removed in the upcoming developer tools version.
