### ISSUE TITLE
[nl.klikaanklikuit] ACDB-7000C doorbel cannot add to "als" in flow with beta 4.0.14

### ISSUE THREAD

**Issue by gratjetost** [athombv/homey#2853]
**Metadata**

* **Homey Version**:1.5.13rc11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:4.0.14
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:ACDB-7000C

**What did you try to achieve?**
after updating to the beta 4.0.14 I cannot add my doorbell ACDB-7000C to the "als" part of a flow.
This did and still works with the stable 4.0.11 version.

**What did you expect as result?**
that I could add my ACDB-7000C to the "als" flow 

**What was the result?**
It greys out. I only can add it the the "Dan" part of the flow

**Any other remarks**
I added the doorbell pusher to the homey when I added it to the homey.

**Comment by KyleAthom** [comment]
Hi @gratjetost,

Have you added the doorbell button separately? This is required in the new app version due to some bugs and unintended behavior when the doorbell button and gong are coupled in a single device.

**Comment by gratjetost** [comment]
when I added the device I selected the doorbell pusher to copy the doorbell. left icon when you add it.
I didn't select the generate signal.

**Comment by KyleAthom** [comment]
That is how it worked in previous versions. Since the new version, the doorbell remote is a seperate device. If you add it again through the pairing wizard it should be working fine again.

**Comment by gratjetost** [comment]
I don't get it. normally I had a flow that says when the doorbell is pressed. do.......
I did add the doorbell pusher. but you say I also have to add the "ringer" and then it works? that makes no sense to me.

**Comment by KyleAthom** [comment]
Like I said, the button and gong are separted. They are two separate devices so they should be added seperate now. This is due to some unintended behavior with the combined device, and the doorbell gong is sold without a button. If you open the pairing wizard again, you"ll find the doorbell button as a device.

**Comment by gratjetost** [comment]
now I get it. the button is a separate device now. instead of selecting ACDB-7000C I have to select the remote......

**Comment by tfreriks** [comment]
>           now I get it. the button is a separate device now. instead of selecting ACDB-7000C I have to select the remote......
> can you rename the device and Icon then to the correct KAKU name then? the gong is the regular ACDB-7000C, but comes in 2 sets ACDB-7000AC and 7000BC. the A and B stand for the remote that is delivered.
> I have a ACDB-7000B (the one where you connect your original pusher)
> the ACDB-7000A is the remote varaint of it.
> at the moment there is only one remote in the app called ACDB-7000C remote. this should be split up to 2 devices. the ACDB-7000A and ACDB-7000B.
> see also the kaku website

+1 !

This also took me 2 hours to figure out...

These 3 devices should be available in the KAKU app:

[ACDB-7000A](https://www.klikaanklikuit.nl/nl/acdb-7000a-draadloze-drukknop.html)
[ACDB-7000B](https://www.klikaanklikuit.nl/nl/acdb-7000b-drukknopzender.html) (**Missing!**)
[ACDB-7000C](https://www.klikaanklikuit.nl/nl/acdb-7000c-draadloze-deurbel.html)

These are just bundles of the three items above and should be ignored in the App:

[ACDB-7000AC](https://www.klikaanklikuit.nl/nl/acdb-7000ac-draadloze-deurbel-set.html)
[ACDB-7000BC](https://www.klikaanklikuit.nl/nl/acdb-7000bc-draadloze-deurbel-set-voor-bestaande-drukknop.html)

**Comment by KyleAthom** [comment]
Hi @tfreriks ,

You are in deed right. No idea why it was this weird in our app, but it's corrected from version 4.0.15 and onwards!
Thanks for clearing this up.
