### ISSUE TITLE
SONOS - I can't find my own Spotify Playlist

### ISSUE THREAD

**Issue by coenboomkamp** [athombv/homey#2854]
* **Homey Version**: 1.5.12
* **Homey Log Code**: 3246851A43

**If related to a Homey App:**
* **Homey App Version**: Sonos 4.0.9
* **Homey App Log Code**: 8b98d689-16dd-4b3d-b877-ae60659a26a5

**What did you try to achieve?**
Play my own Spotify Playlist on SONOS

**What did you expect as result?**
To find and play my own Spotify Playlist on my SONOS

**What was the result?**
I can't find my own Spotify Playlist with the SONOS app

For testing, this is the playlist i'm trying to find and play:
https://open.spotify.com/user/coenboomkamp/playlist/6FqQNd516ul9dgqJNs9EeV?si=QuKDd3Y5RTCJpCG8rOAGiA

**Comment by WeeJeWel** [comment]
![screen shot 2018-09-26 at 16 39 34](https://user-images.githubusercontent.com/319873/46087505-c647de80-c1aa-11e8-8eb0-9b70363e93b6.png)

Fixed in the upcoming release. Search by playlist ID.
