### ISSUE TITLE
usb cli connection not working on windows 10

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#2855]
<!--

* **Homey Version**:   1.5.13-rc11

**What did you try to achieve?**
run an app for developing through usb with athom cli the newest windows the newst homey firmware the newest

in the tools section of the developers website of homey homey has a windows connection choosen 

**What did you expect as result?**
to see a usb homey ip in the cli 

**What was the result?**
no usb network precent rnids driver doesnt load 

Windows 10 Insider Preview 17763.1 (rs5_release)

![aantekening 1](https://user-images.githubusercontent.com/7040452/46094020-29407200-c1b9-11e8-9b4a-0a7931e0d51a.png)

**Comment by Dijker** [comment]
Not very descriptive, 
it works for me!

What have you tested? 
Did it work before?  and What changed that it doesn't?
Looks like a Windows Issue! 
What have you tested?

Have the NDIS drivers loaded? is sometimes an issue with Windows 10, I guess Microsoft has decided not to install some things by default.

**Comment by WeeJeWel** [comment]
Please provide more details.

**Comment by nattlip** [comment]
even on windows 8 it doesnt work here., i have tried 5 computers now i will try a new cable . but ifv that doesnt work @Dijker has a magic computer

**Comment by Dijker** [comment]
Sorry,. But GitHub isn't a complaint channel.
Pls read the contributing guidelines and use the issue template
Or email support for customer support

**Comment by nattlip** [comment]
so dont complain about my github issues.
