### ISSUE TITLE
[com.ikea.tradfri] Missing support for Trådfri electrical plug

### ISSUE THREAD

**Issue by proisland** [athombv/homey#2859]
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.3.3

**What did you try to achieve?**

Trying to add IKEA Trådfri electrical plug to the Homey setup using IKEA Trådfri app version v1.2.4

**What did you expect as result?**

it would be possible to add the IKEA Trådfri Plug to be able to control it using Homey

**What was the result?**

Not possible to add the device as its not supported by the IKEA Trådfri app for Homey.

**Comment by KyleAthom** [comment]
Hi @proisland ,

Since the device is not listed on the app page for IKEA Trådfri it is not working with the app.
However, we are already working on integrating the sockets into the Trådfri app.
