### ISSUE TITLE
Setting color and brightness require 2 flow cards

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#286]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

I tried to achieve to dim a chose color of a Philips LED Strip. Not sure if it was intended, but if you want to dim a specific set color you first have to select the color and then add another card with the dimming percentage. Id would be preferable to have it selected within the flow card, if a color is selected than the percentage is adjusted automatically.

![schermafbeelding 2016-03-02 om 20 39 32](https://cloud.githubusercontent.com/assets/17526110/13472923/51b9ee86-e0b7-11e5-9d2b-8f8b664ba00c.png)

**What was the result?**

The need to add 2 different flow cards for just 1 light seems unnecessary. 

**What did you expect as result?**

Expected was to have it adjusted within the first flow card. 

**Any other remarks**

If 2 cards per light are needed (Color and Percentage) scrolling for the "then" in the flow bar is a must!

**Comment by WeeJeWel** [comment]
The color card sets the dim value as well since an update released long ago.
