### ISSUE TITLE
Aqara double switch Tags

### ISSUE THREAD

**Issue by simusimu** [athombv/homey#2863]
metadata

Homey versie : 1.0.4
Homey log code :
Smartphone Platform : Android
Smartphone-appversie :
Indien gerelateerd aan een Homey-app: Xiaomi / Aqara

Homey- appversie: V042
Homey App Log Code :
Betrokken apparaten (bij voorkeur productcodes) : QBKG12LM

Wat heb je geprobeerd te bereiken?
Nadat kort geleden de depriciated driver niet meer werkte de driver met tags
geprobeerd actief te maken in een flow
Helaas is nergens te vinden Welke tags gedetineerd zijn voor L/R single / double clicks
In Tags menu staat schakelaar niet vermeld

Eventuele andere opmerkingen
Flow wordt gebruikt in combinatie met Better Logic

Is er een weg hoe ik kan bepalen welke Buttons tags bestaan ?

**Comment by TedTolboom** [comment]
@simusimu I just stumbled upon this issue... and am not checking Athom's issue repository for issues regarding my apps... so for next time, please make an issue by following the "report an issue" button at the apps app store section.

I'm trying to understand your issue. But the product code you added does not match the problem description you provide; for the (wired) switch of which you added the product code, there was no DEPRECATED flow card.

I guess you are referring to one of the wireless switches, for which the DEPRECATED flow card (with drop down lists) was removed and replaced by the "A scene has been triggered" with autocomplete fields...

There is no need to use tags in these fields; simply click on the field and it will show a list of applicable options: 

For the button:
<img width="287" alt="schermafbeelding 2018-10-14 om 08 51 43" src="https://user-images.githubusercontent.com/17163431/46913505-80528f00-cf8e-11e8-8d58-c37b40521d2e.png">

For the scene: 

<img width="286" alt="schermafbeelding 2018-10-14 om 08 51 55" src="https://user-images.githubusercontent.com/17163431/46913511-8c3e5100-cf8e-11e8-9c03-40037c47a5d3.png">

Hope this solves your issue.

**Comment by simusimu** [comment]
Goede morgen,
Bedankt voor je oplossing, niet ver genoeg gekeken en blijven steken bij de verkeerde card

Het werkt goed nu.
John
