### ISSUE TITLE
[App V2] Cosmetics

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#2865]
**Metadata**

* **Homey Version**:1.5.13 RC11
* **Homey Log Code**:
* **Smartphone Platform**:IOS
* **Smartphone App Version**:1.1.118
* **Phone model**:Xs Max

Maybe u guys can adjust the app a bit so the settings will be in sight on a Xs Max.
![xs-max](https://user-images.githubusercontent.com/19249884/46556963-8b4f5480-c8e8-11e8-9fe8-4508d568a86f.jpg)

**Comment by jeroenvollenbrock** [comment]
This problem is resolved in the final version of the smartphone app.
