### ISSUE TITLE
Color card from top devices are moved to the background

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#287]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Changing colors on different devices. First changed the color on the first light, than the second and finally on the third light. When i wanted to adjust the color on the first light again, the card to change the color moves to the background so it is impossible to change the color once again.

![schermafbeelding 2016-03-02 om 20 59 15](https://cloud.githubusercontent.com/assets/17526110/13473609/59d0b980-e0ba-11e5-92cf-89c4b9b7fef8.png)

**What was the result?**

The color picking card moved to the background.

**What did you expect as result?**

That the last openend color card would be closed (forced closed) and the opened card appeared in the correct manner.

**Any other remarks**

When scrolled through the card to adjust the brightness and going back to the color fixes the bug temporarily.

**Comment by WeeJeWel** [comment]
Fixed some time ago :)

**Comment by Arjanvde** [comment]
@WeeJeWel Sorry to say, not on 0.10.7:

![cards moved to the background](https://cloud.githubusercontent.com/assets/17526110/19888913/01501d4a-a032-11e6-941e-e4d7c09ea898.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.10.8

**Comment by Arjanvde** [comment]
Solved.
