### ISSUE TITLE
KlikaanKlikUit all virtual buttons are not reconized anymore after update 4.0.14

### ISSUE THREAD

**Issue by glijie** [athombv/homey#2870]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** KlikaanKlikUit
* **Homey App Version**: 4.0.14
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: virtual bottons stopped working from klikaanklikuit

**What did you try to achieve?**

after today's automaticly update of the klikaanklikuit app to version 4.0.14 all virtual buttons stopped working. When I use them it says"invalid_device_data"

**What did you expect as result?**

Normal usage of an Virtal button made with klikaanklikuit as alway's

**What was the result?**

the VT-button craches with the sign "invalid_device_data

**Any other remarks**
This is the second time that my homey is useless after an update from klikaanklikuit app

**Comment by KyleAthom** [comment]
Hi @glijie ,

Which virtual buttons do you mean?
The KlikAanKlikUit app does not support any other devices then the devices listed, and those are all hardware devices.
If you're looking for virtual buttons or other device I suggest that you want to try the "Virtual Devices" app: https://apps.athom.com/app/com.arjankranenburg.virtual.

**Comment by glijie** [comment]
to create a VT Button is nu just adding a socket , in my case the ac-1000 and create a signal...the socket is added. Hoe you can use that ons as a virtual button.

@kyleathom you closed the issue...can you yell me what you did to avoid a not working Homey after a new update from the KAKU app?
