### ISSUE TITLE
[TADO] Support for Homey Logger

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [athombv/homey#2878]
* **Homey Version**: 1.5.12
* **App version**: 2.0.1

Support for Homey Logger App for the Tado App.

> 7:25.199 | tado° | Not connected | This app does not support realtime logging
> -- | -- | -- | --

**Comment by jeroenvollenbrock** [comment]
The Tado app does not use realtime events, the logger app does already log device events though, so the tado changes should still be visible.
