### ISSUE TITLE
KAKU device can't be used anymore after app update

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#2879]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**: B1DBC7E221
* **Smartphone Platform**: NA
* **Smartphone App Version**: NA

**If related to a Homey App:** KlikAanKlikUit
* **Homey App Version**:  v4.0.14 - 24.09.18
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: ACDB-7000B

**What did you try to achieve?**

Updated app to app to v4.0.14 - 24.09.18

**What did you expect as result?**

Device was still usable in flows

**What was the result?**

Can't use device in flows anymore. Device is still in devices list.

**Any other remarks**
I had to remove device and add it again to get it working.

**Comment by Dijker** [comment]
I guess the answer is in this post on the forum: 
https://community.athom.com/t/klikaanklikuit-by-athom/81/57
Please remove that doesn't work and re-pair. then check your flows and repair.

**Comment by KyleAthom** [comment]
Hi @HansieNL ,

The post @Dijker metioned is the correct solution.
There was some unintended behavior by having both the button and gong in one device so we have seperated them.
If you re-add the device it should be working fine again. If the gong is still available in Homey you only have to pair the remote.
