### ISSUE TITLE
custom http response code in api.js callback

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#288]
In `api.js` I want to respond with custom http response code.

Here is simple api definition
```
{
  path: '/err',
  method: 'GET',
  description: 'err',
  fn: function (callback, args) {
    if (args.query.err === 'num') {
        callback(400)
    } else if (args.query.err === 'e') {
        var e = new Error('error')
        e.code = 400
        callback(e)
    } else if (args.query.err === 'o') {
        callback({
          status: 400,
          message: 'error'
        })
    } else {
        callback('missing err')
    }
  }
}
```

`?err=num` should respond with 400 http code
`?err=e` should respond with 400 code and `result` should be an object `{message, status}`
`?err=o` should respond with 400 code and `result` should be an object `{message, status}` 
else should return 500 with string result

**Comment by WeeJeWel** [comment]
Fixed in 0.8.21:

`callback( err, result, statusCode )`

**Comment by matjaz** [comment]
and err could also be an object?

**Comment by WeeJeWel** [comment]
No, errors can only be an Error object, to keep the API consistent.

If you want to return an object:

```
callback( null, { foo: 'bar' }, 400);
```

**Comment by matjaz** [comment]
I would suggest to create third parameter an object.
For starter it could handle `{status:400, headers:{'content-type': 'text/xml'}}` And it's future proof.
