### ISSUE TITLE
Red ring and keeps rebooting FW 1.5.13-rc.11

### ISSUE THREAD

**Issue by btwvince** [athombv/homey#2880]
**Metadata**

* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**:7C675DCCE2
* **Smartphone Platform**: Android/iOS

**What did you try to achieve?**
Keep Homey alive and that he boots normally

**What did you expect as result?**
That Homey can boot normal

**What was the result?**
Red ring and after a few minutes red ring he does a reboot and keeps doing this over and over

**Any other remarks**
Homey comes online a few seconds after the reboot so I tried to disable all apps but that doesn't affect anything.
Tried already a few times to unplug Homey for an hour and then do a reboot but also nothing has changed

**Comment by btwvince** [comment]
I know, last month I received a new one from Athom Support. I've tried today with 2 other power adapters 2A but still the same issue. Keeps rebooting and then red ring and reboots by itself after a few minutes red ring. The problem is started a few days after the experimental update.

**Comment by Dijker** [comment]
Ok, Good you tried and could send a Log code.! 
Thanks for your Answer, Hope Athom will help you soon.

**Comment by KyleAthom** [comment]
Hi @btwvince ,

For this kind of issues GitHub is not the right tool/place to help you. Would you please be so kind to email support: support@athom.com? Our support team will handle it then!
