### ISSUE TITLE
433 microcontroller issue

### ISSUE THREAD

**Issue by sleutelsnet** [athombv/homey#2882]
As my 433 signals are not getting through, I tried resetting the controller via:
https://developer.athom.com/tools/signals

Which yielded the error:
invalid_manager_id: microcontroller

Homey Firmware Versie: 1.5.13-rc.11

**Comment by Dijker** [comment]
duplicate of #2851 and expected as the button will be removed when .13 is stable.
(it often didn't work anyway and needed a PtP)

**Comment by KyleAthom** [comment]
Exactly like mentioned in #2851 , this is intended and the button will be removed in the future.
