### ISSUE TITLE
[AppStore] cannot scroll at the submission page

### ISSUE THREAD

**Issue by koktaildotcom** [athombv/homey#2886]
At https://apps.athom.com/app/{appSlug}/submission

**What did you try to achieve?**
Add a new app submission by clicking `update`.

**What did you expect as result?**
The popup is open, but the container is scrollable to the content so i can click on the `update` button.

**What was the result?**
The popup is open, but the container isn't scrollable to the content so i cannot click on the `update` button.

Tested on Chrome And Firefox. If the viewport is set to 30%.  I can click on the button as workaround.

**Comment by WeeJeWel** [comment]
Can you post a screenshot? I don't experience this problem.

**Comment by WeeJeWel** [comment]
I'm sorry but we do not support smartphones in the developer section of the appstore.
