### ISSUE TITLE
4 Remarks with setting a color in a flow

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#289]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

**1.** When selecting a color the Ok button could be hard to read. First of all it took me a few try's to see i needed to confirm the color change. Not sure whether it would be needed to have the color be previewed in the "Ok" box. My suggestion would be to merge the "cancel" and the "ok" box to display the color and add a separate box for "cancel" and "ok" underneath this box.

**2.** The word "Cancel" should be written in White as it is displayed in a black box.

**3.**  A code is written in light grey #000000 which doesn't do anything nor does it change. It could either be removed or should have a function.

**4.** The code #0013ff is the color code. It's almost impossible to match this exact code with a second light or a third light. Is it possible to have the code inserted manually in this box? If not possible, i don't think it should be displayed this exactly.

![schermafbeelding 2016-03-02 om 21 12 03](https://cloud.githubusercontent.com/assets/17526110/13474389/18a50c8c-e0be-11e5-90db-24f9f412e0e9.png)

**Any other remarks**

Questions, please ask.

**Comment by PandaNL** [comment]
And to add another problem, when you want to change the color of a hue light which is on the bottom of the flow, you are unable to see the OK button at all.

![schermafbeelding 2016-03-02 om 23 52 11](https://cloud.githubusercontent.com/assets/17313216/13478607/159ad288-e0d2-11e5-8e5f-4c661a06fcc9.png)

**Comment by Arjanvde** [comment]
@PandaNL totally agree that scrolling is a must! Did also mention that in the other remarks off #286

**Comment by Arjanvde** [comment]
This is with 1.1.2 solved as far as I can test.
