### ISSUE TITLE
Flow card "then" option for thermostat devices

### ISSUE THREAD

**Issue by maja2020** [athombv/homey#2896]
**Metadata**

* **Homey Version**:1.5.13-rc.11
* **Homey Log Code**: N/A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:**
* **Homey App Version**:
Eurotronic Z-Wave v1.2.1
Fibaro v1.5.18
Virtual Devices v0.7.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
FGT-001
Spirit Z-Wave Thermostat
Virtual Devices app thermostat

**What did you try to achieve?**
There is no way to input temperature as a variable or tag in de set point "temperature" fields, only a slider (which is a manual input) is available.

**What did you expect as result?**
To input a tag or a viariable in the "Then" (dan) column in a flow in addition to the slider option flow card that is already present.  

![afbeelding](https://user-images.githubusercontent.com/32190313/47614797-ac4d3480-daa5-11e8-9c30-76c7ab5a41b9.png)

**Any other remarks**
Not a bug but a feature request
I think this is general (SDK) related since all three apps I use for thermostat devices have a slider, no variable input function.

**Comment by caseda** [comment]
you can place a (number) tag on top of the slider

**Comment by maja2020** [comment]
Nice!
