### ISSUE TITLE
Flow with timed action doesn't start at time XX:XX

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#290]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

I'm trying to achieve that Homey switches it's LED ring to brightness 0 when the times 21:49.  I've waited until the time was 21:49 and no action, looking at the geek log i did see it switched at 21:49:58. 

![schermafbeelding 2016-03-02 om 21 50 06](https://cloud.githubusercontent.com/assets/17526110/13475067/1f6230a6-e0c1-11e5-98bc-189a1240fd84.png)

**What was the result?**
I was impatiently waiting on an action at 21:49 and nothing happend. When i cam e back with a cup of tea i saw that the LED ring was off and was surprised it was off and it needed a few attempts to find out that it was switched on at 21:49:58. I seriously thought that i did something wrong at my first attempts.

**What did you expect as result?**
The light ring to turn to brightness 0 at exactly 21:49:00. It would be wishful that it would be switched on at the exact time as that could be easily checked with the computer time.

**Comment by KroontjesPen** [comment]
Conformation on this behavior. 
If you are testing and for a 2 minutes window is this too much. 
Let well, the switch time can be xx:xx:02.

**Comment by KroontjesPen** [comment]
For the record.
It is the **flow** time and not the voice time that is good.

Delay now 29 sec.

**Comment by WeeJeWel** [comment]
Is your system time correct?

**Comment by Arjanvde** [comment]
At the "Stuff for geeks" screen the system time is one hour behind (Currently showing 11:45). Even though it is one hour behind when i set the timer in a flow in 12:45 it activates the flow somewhere at 12:45.

It would be preferable to have it switched at 12:45:00 exactly, not somewhere within the 12:45 minute range.

**Comment by KroontjesPen** [comment]
System time is synchronized every hour and there are no strange noticed in the log there.

 Delay now 46 sec,

**Comment by KroontjesPen** [comment]
With some practice I could Homey say the time on xx:xx:58, xx:xx:59 and xx:xx:00 and it was the right one.

**Comment by bvdbos** [comment]
same for me...

**Comment by WeeJeWel** [comment]
Does this still occur on Homey v0.10.7?

**Comment by bvdbos** [comment]
For me it doesn't. Always firing within a few seconds of the exact time....

**Comment by WeeJeWel** [comment]
Alright great! I'll close this issue until someone still experiences problems.

**Comment by Arjanvde** [comment]
Just created a test flow which whould fire on 12:42 it did fire on 12:42:24. See also my screenshot for a flow which should fire on 12:45  (I expect it to fire on exactly e 12:45:00)

![flow 1](https://cloud.githubusercontent.com/assets/17526110/19888802/44716e90-a031-11e6-9e31-999ca377a703.png)

![flow 2](https://cloud.githubusercontent.com/assets/17526110/19888803/4474c586-a031-11e6-8a1d-e11ff6d40cd3.png)

So the issue still persists.

**Comment by bvdbos** [comment]
@Arjanvde does this still happen for you?

**Comment by Arjanvde** [comment]
@bvdbos Jup still striggers somewhere within the set minute.

**Comment by bvdbos** [comment]
24-2-2017 07:00:50.748	Speech-output	Speech	{"text":"het is 06:59 ","type":"say","session":"homey"} with this flow:
![schermafdruk_2017-02-24_07-02-32](https://cloud.githubusercontent.com/assets/1064079/23292321/4a55f6a4-fa5f-11e6-9442-88396a96c938.png)
but to be honest, the flow doesn't declare the time has to be told at the exact hour... As for the time it's saying, that's #1315

**Comment by Arjanvde** [comment]
Did some research myself.

The issue is that Homey's Cron is rolling and it only is able to trigger a flow around 40 times at exactly 09:00:00. From there on, it triggers the flow on 09:00:01 for around 40 times etc. In the attached file I did some monitoring and  it has 41 triggers between 09:56:45 and 10:37:45, and has 38 triggers between  10:38:46 and 11:18:46. 

A flow with a timed action starts when Homey's cron has passed. This also applies for Sunset/Sunrise, this does start somewhere within the minute.

@WeeJeWel can you say whether this is able to be resolved or is this Homey's behaviour.

[Rolling.txt](https://github.com/athombv/homey/files/970009/Rolling.txt)

**Comment by WeeJeWel** [comment]
I've changed some behavior in the upcoming 1.5.0-rc.6 release. Please let me know whether this issue still persist.

**Comment by Arjanvde** [comment]
Did some tests (today and yesterday) and it looks like this is solved correctly. Thanks!
