### ISSUE TITLE
Homey ledring not responding

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2903]
* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**: A59C1B6C1B
* **Smartphone Platform**: NA
* **Smartphone App Version**: NA

**If related to a Homey App:** Led Ring
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Change color of led ring of homey

**What did you expect as result?**
A change of color

**What was the result?**
Nothing happened color stayed the same

**Any other remarks**
I see an decrease in stability and an increase in bug's which were no bugs in the past, how are you performing your regression tests ?
When can we expect all the current bugs to be resolved ?

**Comment by bvdbos** [comment]
Works for me...

**Comment by chrisboer** [comment]
Works again here, must have been a hickup
