### ISSUE TITLE
Zigbee netwerk reset error

### ISSUE THREAD

**Issue by Etienne1954** [athombv/homey#2912]
* **Homey Version**: 1.5.13-rc.11
* **Homey Log Code**: 13BA8C5A57

**If related to a Homey App:** Zigbee netwerk reset

**What did you try to achieve?** to add Zigbee devices to my Homey

Add Zigbee diveces not possible, restart Homey, try to reset Zigbee network gives error 
**"Someting went wrong when resetting the Zigbee chip: EBADF: bad file descriptor, close"**

**What did you expect as result?**

hope to reset Zigbee network so that I can add new Zigbee diveces

**What was the result?**

**Any other remarks**
![image](https://user-images.githubusercontent.com/32998309/48204530-519bbe80-e36a-11e8-8351-0123909ab8c4.png)
<img width="302" alt="2018-11-08 15_15_55-settings - homey" src="https://user-images.githubusercontent.com/32998309/48204559-5e201700-e36a-11e8-805c-2c2d314a17a3.png">

**Comment by Etienne1954** [comment]
Opgelost na installatie van update 1.5.13-rc.14

**Comment by ddegoede** [comment]
Lijkt niet opgelost, want ik draai nu release 1.5.13 en kan niets koppelen met ZigBee, en als ik het netwerk probeer te resetten krijg ik bovenstaande foutmelding. Graag heropenen.

**Comment by ddegoede** [comment]
hi @bvdbos I had not, so I just did that, unfortunately it gives the same result. I powered off Homey, I think I waited around 45 minutes, then powered on Homey. Tried to reset the network and got the same error.
