### ISSUE TITLE
KNX seems to be broken in 1.5.13-rc.14

### ISSUE THREAD

**Issue by RobertHerter** [athombv/homey#2916]
* **Homey Version**:
1.5.13-rc.14
* **Homey Log Code**:

**What did you try to achieve?**
Adding KNX Switch

**What did you expect as result?**
Switching on/off

**What was the result?**
KNX Telegram is not sent

**Any other remarks**

**Comment by chrisboer** [comment]
@WeeJeWel I think you should focus on giving basic functionality more priority then to add exotic KNX systems towards Homey.

**Comment by KyleAthom** [comment]
Hi @RobertHerter ,

SInce we already received your support ticket we would like to handle your problem through support.
This issue will be closed because it is duplicate with your support ticket and missing information.
