### ISSUE TITLE
Unpublished step skipped on app submission

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#292]
**What is your Homey version (Settings → System)?**

n/a (app store)

**What did you try to achieve?**

Submit a new app. According to the flow there are 5 steps.
1 Import
2 Concept
3 Pending
4 Unpublished
5 Published

**What was the result?**

Got a notification of step 3 (Pending) and no further notifications. Noticed yesterday that the app was already in the app store (step 5), without the developer being informed and moving it from unpublished to published.

**What did you expect as result?**

Notification of review approval (moving from step 3->4) and be able to determine whether the app should be published (step 4->5).

**Any other remarks**

Would be good if in step 4 private invites (or something) could be sent to people such that they can test the pre-released app before actually releasing it in the app store (step 5).

**Comment by WeeJeWel** [comment]
Sorry about that. The choice to publish an App will now be handed over to the dveloper.

**Comment by nlrb** [comment]
We currently still don't get a notification after review: Notification of review approval (moving from step 3->4).

Can that be added as well? Now we have to poll continuously to see if the application was approved.

**Comment by joachimroeleveld** [comment]
You should actually get an email about that. The problem in this case is that yesterday, when Emile approved your app, there were some problems with the app store, including emails that weren't sent. These problems are solved now.

**Comment by nlrb** [comment]
@joachimroeleveld: thanks for the feedback. Was this also the case already last Friday? This was posted on Slack Mar. 11:
pandanl [11:52 PM] 
I see updates that gets passed validation now needs to be published by the user. However no notification by email is given that validation passed in the app store. @weejewel

**Comment by joachimroeleveld** [comment]
No, by then there should have been no problems. It's very strange that you don't receive notifications for step 3, because these emails are sent in exactly the same manner as for the other steps. I actually submitted your app locally and did receive an email. Are you sure the email doesn't land in your spam folder?

**Comment by nlrb** [comment]
I'm sure it doesn't end up in my spam box (get a daily digest of that). Also, the other emails come through fine (submitted & published). I'll keep an eye on it next time.

**Comment by joachimroeleveld** [comment]
You were right! The email did get sent, but to the currently logged in user, which was in this case @WeeJeWel. He pointed this out to me. I fixed the problem. Thanks!

**Comment by nlrb** [comment]
Great! Nice teamwork :-).

**Comment by matjaz** [comment]
@joachimroeleveld  I haven't receive an email app was approved (step 4).
I guess I should. However, I did receive an email for step 3 and 5.

**Comment by joachimroeleveld** [comment]
@matjaz, that's very strange. I analyzed the process step by step and could verify that it is sending an email to the app author. Could you send me more details? Maybe over Slack?

**Comment by nlrb** [comment]
Unfortunately still did not get an email after the review step.

**Comment by nlrb** [comment]
Got the email, it works now!

**Comment by matjaz** [comment]
@joachimroeleveld again I haven't received and email for step 4, for last update of presence & youtube app.
However I've received an email for published step.

**Comment by Inversion-NL** [comment]
I checked for my app and I also did not receive any mail...

**Comment by bvdbos** [comment]
I did on the 23rd of May...
1) email : submitted for approval
2) email : approved waiting for published
3) email : is published

**Comment by matjaz** [comment]
again, no email. :'(

**Comment by nlrb** [comment]
Did not even get an email on app submission now (Sunday Jun 25).

**Comment by joachimroeleveld** [comment]
Alright guys, I am going to look into this problem again. For now, I have very little time available so please bear with me. I will come back to this soon.

**Comment by nlrb** [comment]
The no email on submission is more likely related to this issue: https://github.com/athombv/homey/issues/717

**Comment by matjaz** [comment]
no email again.

**Comment by Inversion-NL** [comment]
I did receive an e-mail.

**Comment by joachimroeleveld** [comment]
I am curious whether this issue persists in the new App Store.

**Comment by matjaz** [comment]
Received all emails today.. will notify here if issue arise again.

**Comment by WeeJeWel** [comment]
This seems to be closed. Please report back if it still goes wrong.
