### ISSUE TITLE
Cannot restart 433 Microcontroller anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2923]
**Metadata**

* **Homey Version**: 1.5.13
* **Homey Log Code**: na
* **Smartphone Platform**: na
* **Smartphone App Version**: na

**What did you try to achieve?**

As my KAKU did not work again due to latest update to 1.5.13 I wanted to restart the 433 microcontroler under develop mode on the website. This possibility is not there anymore ?

**What did you expect as result?**

To be able to restart my 433 Mhz microcontroler

**What was the result?**

**Any other remarks**
We should have less problems moving forward in releases but I encounter the opposite. Also functionality which was there before is being removed ?

**Comment by Rocodamelshe** [comment]
I know this is not the solution to ur issue but just a work-around.
With the Candy app u can still restart the controller.
![firefox_2018-11-25_20-11-49](https://user-images.githubusercontent.com/19249884/48984708-a166dd80-f0ff-11e8-8752-42be598de4e0.png)

**Comment by nattlip** [comment]
# 2882

**Comment by nattlip** [comment]
#2882

**Comment by WeeJeWel** [comment]
This is intended behaviour. Resetting the microcontroller doesn't solve anything anymore since 1.5.13.
