### ISSUE TITLE
Rainbow with Led Ring not able to be selected in Flow. 

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#295]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

To turn the Led Ring back in a Rainbow after it has been changed to a solid color.

**What was the result?**

The option to select rainbow is missing in the flow card

![geen rainbow](https://cloud.githubusercontent.com/assets/17526110/13521035/b2b17b3a-e1e5-11e5-9fda-870a6d172568.png)

**What did you expect as result?**

That the rainbow would be an option to be selected.

**Comment by WeeJeWel** [comment]
The rainbow is only a screensaver. This card makes the LED ring change for a few seconds, so it's intended behavior :)
