### ISSUE TITLE
Manual speech input doesn't work anymore

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#296]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

On the  /manager/speech-input/ screen i'm unable to input any more manual speech inputs. I've been giving Homey a lot of manual speech input on Saturday and Sunday and suddenly it stopped working. I tried to reboot the device 2 times and even had the power disconnected to relocate Homey but i couldn't get the input manager working again.

If I enter text in the input manager and press enter to submit, the text disappears completely, even the windows stays completely empty. This is the input manager just before pressing the enter button.

![df80a5ec-e17b-11e5-889d-8609107f2bf2](https://cloud.githubusercontent.com/assets/17526110/13521771/5afa6900-e1eb-11e5-9afc-ce5722bb3d6d.png)

**What was the result?**

It is not possible any more to have manual speech input.

**What did you expect as result?**

When the text has been entered to show up at least as been send to Homey, it now stays completely blank. When I look at the output manager 

**Any other remarks**

Since it stopped working I've switched off the microphone. It doesn't make a difference whether the microphone is on or off.

My system time is 1 hour off compared to the actual time.

In case a developer wants to view with teamviewer or have the credentials to log in please ask.

**Comment by ralfvd** [comment]
Are you sure system time is one hour off?  System time displays in "Zulu"-time  which is GMT.  That is noted by the "Z" trailing the time.

**Comment by Arjanvde** [comment]
@ralfvd According to System --> stuff for Geeks screen it is one hour off.

**Comment by ralfvd** [comment]
@Arjanvde that is Zulu time, noted by the Z trailing in the time. So time is correct if you are in CET timezone (the Netherlands)

**Comment by Arjanvde** [comment]
@ralfvd Thanks for the explanation, had to do a little more research to understand it correctly but you are absolutely right :)

**Comment by Arjanvde** [comment]
Still a problem on 0.8.22.

**Comment by Arjanvde** [comment]
Still a problem on 0.8.24, can't get it working. 

Speech training went fine, calibrated my voice 2 times, Homey listens to Ok Homey, if i say something, i can see that Homey starts listening, circle is yellow, than it starts processing, circle turns white and then back to the rainbow without any feedback. manager/speech-input/ stays empty as well, still the same screen as above.

**Comment by Arjanvde** [comment]
And a little addition,

![schermafbeelding 2016-03-16 om 21 17 22](https://cloud.githubusercontent.com/assets/17526110/13827465/f0556cd6-ebbc-11e5-8d4d-0a33803ad333.png)

Speaking to this test flow doesn't matter, but if i type yes/no in the speech input the flow reacts with either positive (a message is send) or negative result.

The text does not appear in the /manager/speech-input/ screen but did get send to the test flow.

**Comment by Arjanvde** [comment]
I did remove some flows, got back to 19 and now able to enter text in the /manager/speech-input/ screen. Will have to test tonight if it "really" works.

**Comment by Arjanvde** [comment]
Wil create a new bug,
