### ISSUE TITLE
Insights graphs only shows whole integers, no decimals

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#297]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Looking at temperature and stock price, with N amount of decimals

**What was the result?**

When having e.g. temperature or stock price in a graph, it only displays the whole number, not the decimals.  When you download the logfile, the complete input with decimals is shown.

Also, the round-up/round-down doesn't work. e.g. stock-price was 85.92 ; insight graph showed it as 85. 

**What did you expect as result?**

Display also decimals in the graph, so you get a better picture of the current situation.

**Any other remarks**

**Comment by ralfvd** [comment]
Update: with stocks, only the first logged stock price doesn't show decimals, the second logged price (5minutes later) shows decimals.
For temperature, it is always without decimals.

**Comment by nlrb** [comment]
I've also never seen decimals with temperatures, just integer values. So curious to know how to log decimal values. Does it have have to do with the type that is passed (e.g. string of '85.92' or number)?

**Comment by ralfvd** [comment]
Another update: after I logged in again to Homey, also the stock prices are again whole integers only, with the incorrect round-up/round-down. Just the decimals are chopped.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.23

**Comment by ralfvd** [comment]
Confirmed to be fixed in 0.8.24
