### ISSUE TITLE
After switched one KaKu device on no other devices can be on or off.

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#298]
0.8.20.
Included the one that was switched on.
That switched on can be done by a flow or Device page.
To find this I have power reboot 5 time and also remove and reinstall the KaKu app.
For now I can shutdown Homey because the few thing it could are now also gone. :-1: 

Edit.
**It blocks my wall switch also. Homey has to disconnected to be able to get my device off.**

**Comment by KroontjesPen** [comment]
Homey is and stays now off. That means also no testing to confirm problems from others.
It is very, very difficult for me now to stay positive.
Why can things that works perfectly be broken in the next update.

**Comment by markvandeven** [comment]
having the same issue. After a reboot, sometimes the KaKu remotes get 'unblocked' and you can at least manually trigger the devices again.

**Comment by bvdbos** [comment]
Works for me, perhaps  combination of apps which playc havoc? Which apps do you have installed?

**Comment by markvandeven** [comment]
I have just KaKu and Wikipedia installed. 

Wiki doesn't work by the way..

**Comment by bvdbos** [comment]
works for me, two different remotes, both keep working as usual...

**Comment by KroontjesPen** [comment]
Seem to working on.
