### ISSUE TITLE
full example to run ledring animation from node.js athom cli :    athom ledring --run [path]working 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#299]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

run an animation from athom cli 

**What was the result?**

...nothing

**What did you expect as result?**

a green blinking ledring
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed in 0.8.23.

`athom ledring --run path_to_my_anim.js`

Docs: https://developers.athom.com/library/ledring/#cli

**Comment by nattlip** [comment]
thank you very much

**Comment by nattlip** [comment]
example doesn't work. debugging an app on my homey i have to choose a homey , but not with ledring run, is that the issue ?  athom cli 1.0.16.

**Comment by WeeJeWel** [comment]
try updating athom-cli  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by nattlip** [comment]
see #360  i cant login then

**Comment by nattlip** [comment]
i added an other email adres without dots before the @ , that works fine

thank you
