### ISSUE TITLE
zwave dimmer not working (dim-function)

### ISSUE THREAD

**Issue by madtraxx18** [athombv/homey#30]
Using an AD142 dimmerswitch the dim function does not work when used in a Flow. the dimming function works in the device screen.

Following not working flow:

If time is: xxxx then dim light

other not working flow:

If microphone and speech command full btrightness then full 100% light intensity.

**Comment by madtraxx18** [comment]
in addition to previous, if I leave the last described flow in place and give the voice command:

Homey, turn kitchen lights of, homey responds with full brightness......

Seems like home mis-reads the flows and mixes up commands.

**Comment by ocatie** [comment]
"Turn the lights on" is a command build into Homey itself. You don't need to make a flow for that. In the current version there is a bug with the time trigger, were working on it.

**Comment by madtraxx18** [comment]
thanks for your answer, I noticed it is a default command but try the following;

setup a flow to switch on any of the lights using voice commands (but not turn the lights on)
Now tell homey turn the lights on.... notice he'll repeat the predefined voice command (e.g. dim, sleep whatever). So he mixes up the predefined voice command with the flows that were defined.

**Comment by madtraxx18** [comment]
![schermafbeelding 2016-01-12 om 00 23 53](https://cloud.githubusercontent.com/assets/16655593/12249849/d1de15f0-b8c2-11e5-9394-994829d81795.png)

Here is the exact example if this Flow is active all voice commands whether they are on/off related to lights will be answered with "DIM"  by Homey. 

Disable the flow and homey responds correctly to on/off commands. e.g. homey turn the lights on.

**Comment by freemann** [comment]
@madtraxx18 any news on this issue?

**Comment by madtraxx18** [comment]
Seems to work using timers, haven't got it working yet with any speech command. Whether I use; dim, soft or mood. None of these commands result in a dimming light. Using the exactly or contains logic card doesn't make a difference

**Comment by WeeJeWel** [comment]
This should be fixed in 0.8.11
