### ISSUE TITLE
MCO Home

### ISSUE THREAD

**Issue by justjom** [athombv/homey#300]
**What is your Homey version (Settings → System)?**

8.20

**What did you try to achieve?**

Add a MCO Home 4-button Touch Panel and Cubino Flush Dimmer

*Please include detailed steps how we can reproduce the issue*

Add to Z-wave, after trying several times (not really smooth) and reboots the MCO Home was included.Then the Cubino dimmer could not be included anymore and Homey is stuck when adding Cubino into "paring already active".

**What was the result?**

The pairing with Cubino was stuck with message 'already pairing session active'. No Cubino Dimmer was showed in the device overview. I have done a reset of the Z-wave chip. The Z-wave menu did not show anymore while stuck in paring.  Then rebooted where I feel you have to wait a while until the Z-wave chip is initialized well (maybe show this as visible 'all ready with initializing' mark above in the menu to avoid confusion). After reboot and adding again, again 'already a paring session active'
<img width="730" alt="schermafbeelding 2016-03-04 om 22 51 29" src="https://cloud.githubusercontent.com/assets/17655941/13541297/bbcc30a4-e25b-11e5-9ea7-3cf4b9b3f37f.png">

**What did you expect as result?**

Simply add one device, and then the next one. 

**Any other remarks**

It would be great if my MCO Home button, could be animated when pushed in the Device Overview. Also the settings of devices, are shown slow (takes 5 sec's to load) which is not expected.

**Comment by bvdbos** [comment]
See #240

**Comment by ocatie** [comment]
Could you please reboot, reproduce the error, send the log using Settings -> System -> Send log and past the code in #300.

Closed because duplicate #300.
