### ISSUE TITLE
oops i couldn't reach the server

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#302]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

enjoy my rest 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

is quite often each day . cant that message be put off
...

**Comment by bvdbos** [comment]
I would also suggest a setting in which you can choose what to do, ie flash red four times....

**Comment by Refl0w** [comment]
Agree with alternative options. Red led ring or push notification (my network isn't down at that moment)

**Comment by evad1st** [comment]
Ha that's about the only thing homey says sadly ...

**Comment by jeroenvollenbrock** [comment]
Can anyone confirm if this problem still persists?

**Comment by djeskoswe** [comment]
Sunday one opps

**Comment by matjaz** [comment]
Also noticed last one on Sunday. Maybe 5 last week.

**Comment by jeroenvollenbrock** [comment]
Anyone with oopses since yesterday? (april 4th)

**Comment by nattlip** [comment]
it dont know , it appears when you use voice commands  i havent used them a long time until .27 , after .27 i have had it 3 times

**Comment by Refl0w** [comment]
@jeroenvollenbrock seems the got solved, didn't had a oops since the test from yesterday 1pm till now, good work!

**Comment by WeeJeWel** [comment]
@jeroenvollenbrock it's your honor to close this issue <3
