### ISSUE TITLE
KAKU motion sensor always ok

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#303]
Version 0.8.20

The KAKU motion sensor is shown to always detect motion after it is triggered once. Other systems the sensor is connected to show the sensor is not triggered anymore, so the device works as expected.

Steps how we to reproduce the issue:
Add a KAKU motion sensor.
Create a flow which is triggered by motion.
Trigger the sensor. The flow is triggered as expected.
After some time, try to trigger the sensor again. The flow is not triggered.
Check the status of the motion sensor after a few hours om not triggering the sensor. Notice Homey still shows the device to detect motion.

I would expect the motion sensor to turn off after a short while.

**Any other remarks**

I love my Homey

**Comment by AJediIAm** [comment]
Fixed in version 0.8.22.

Homey was so happy to see ik kept paying my "welcome home theme" over and over, but that was a mistake on my part. :)

**Comment by Dennishacq** [comment]
Good to hear that your problem has been solved :)
