### ISSUE TITLE
Remove node, unclear what to do.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#304]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

I added a Fibaro Relay and i think i did something wrong in the pairing process. Where i wanted to have just 1 device in the overview window I now have 3. I think these are for the device itself and the 2 possible switches you can connect.

As i thought i did something wrong, i just wanted to remove the device and add it again.

**What was the result?**

In the remove node screen when i press remove node i have to present the node but i really don't now how, what should i do in this step.

![schermafbeelding 2016-03-05 om 10 51 50](https://cloud.githubusercontent.com/assets/17526110/13547031/d5f864d8-e2c0-11e5-9b63-4a9b48d8f0ff.png)

**What did you expect as result?**

To either have a short clear instruction what to do, or have a drop down list to be able to remove the node.

**Comment by Arjanvde** [comment]
Solved by myself

**Comment by nattlip** [comment]
maybe interesting for others with z-wave problems how ?

**Comment by Arjanvde** [comment]
@nattlip it's more or less reading the manual how you can exclude you Z-Wave device from the network.

With the Fibaro Relay you should switch circuit 1 on, to set the controller in inclusion/exclusion mode and it should work. It's more or less good reading of the manual.

In my case i was also able to reset te entire Z-Wave network since just 1 device was added.
