### ISSUE TITLE
Remove node with Failed option

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#305]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

When the normal option to remove the node didn't work out as planned i wanted to force remove the node with the failed option (Made a testing setup and simply disconnected the power). Selected the device and clicked the remove failed node button. The system then try's to remove the node, it was thinking about it around 3-5 minutes.

**What was the result?**

Result is that the system was trying to remove the node (at least that is what i'm thinking) for 3-5 minutes when it finally give me this error message.

![schermafbeelding 2016-03-05 om 10 58 26](https://cloud.githubusercontent.com/assets/17526110/13547054/d73062c8-e2c1-11e5-86b2-7b6176b67054.png)

After this the Z-Wave screen can't be reached again. The Z-Wave screen it keeps on loading until you reboot the device. I've send the log (9862BF7D8A) to the team so hopefully you are able to see what is the issue.

**What did you expect as result?**

That the node was removed.

**Comment by ocatie** [comment]
Thanks.

On an error in the process another call is made too soon which causes a crash. Have to do some debugging to find which call. Working on it.

**Comment by ocatie** [comment]
Fixed in 0.8.22
