### ISSUE TITLE
Cannot delete log with object as name

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#306]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Delete an insights log that has an object as name.

Steps to reproduce:
1. Create a log (.createLog) with as name an object
2. Get the list of logs (.getLog)
3. Delete the log (.deleteLog) with the name from .getLog

**What was the result?**

Doesn't get deleted. Error: Unknown log

**What did you expect as result?**

The log gets deleted.

**Any other remarks**

1. .createLog should check that the name is of type 'string'
2. How can I remove these wrong log entries Insights without a full reset?

**Comment by WeeJeWel** [comment]
Added check in 0.8.23.

Added an endpoint in 0.8.23 to delete all logs by uri: `DELETE /api/manager/insights/log/:uri`

**Comment by nlrb** [comment]
Was able to delete invalid log.
