### ISSUE TITLE
Deleting an app should purge all app data

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#307]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Remove an application from Homey.

**What was the result?**

The application was removed and (since 0.8.19) the settings were purged. Howver, Insights data still remains and also the devices still remain.

**What did you expect as result?**

- App settings to be purged (works)
- App devices to be purged (they now return when re-installing the app)
- App Insights data to be purged (returns when re-installing the app)

**Any other remarks**

Did not check what happens to flows related to the app.

**Comment by KroontjesPen** [comment]
Warning. 
Make it 'on request' to purged devices ect.

The KaKu app needs sometimes to be removed and install again after power reboot or version upgrade.
If all my devices, 20+,  would be removed than is it for me 'game over'.

**Comment by 4tetra4** [comment]
Than offer some options what data to be deleted when uninstalling the app.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.23, deleting an app removes all data after a warning.

@KroontjesPen, re-installing an app doesn't do anything, actually. You could try to disable it and then enable it, same effect as re-install but you'll keep your settings this way.

**Comment by KroontjesPen** [comment]
@WeeJeWel 

That is not what I experiences. Sometimes I really have to remove and install the KaKu app,

**Comment by WeeJeWel** [comment]
@KroontjesPen In that case, please decribe a scenario which we can reproduce :)

**Comment by KroontjesPen** [comment]
On this moment no Homey on line but this is whats mostly happens.

Power reboot - KaKu don't work - disable/enable don't help -  remove/install do.
