### ISSUE TITLE
Color of the switch on mobile phone is wrong.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#308]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Trying to switch the lights on and off with my phone when is stumbled on 2 of my 433mhz switches which looked like they where switched on but in fact they are off.

Wrong scenario, 
Black switch when the lights are off.
![schermafbeelding 2016-03-05 om 15 35 25](https://cloud.githubusercontent.com/assets/17526110/13548107/500368a0-e2e8-11e5-9b62-a9b0bf2bc4a5.png)

**What did you expect as result?**

That the switches are exactly displayed as the Z-Wave switches.

Soft grey switch when light is off
![schermafbeelding 2016-03-05 om 15 35 47](https://cloud.githubusercontent.com/assets/17526110/13548108/5004495a-e2e8-11e5-9095-1c00b54065ae.png)

Correct scenario when the light is on, the switch has become black

![schermafbeelding 2016-03-05 om 15 36 41](https://cloud.githubusercontent.com/assets/17526110/13548109/5005193e-e2e8-11e5-8c50-0a24791f222f.png)

Turning the light on and off didn't change the color of the switch.

**Comment by bvdbos** [comment]
The plugs in the first picture aren't "lamps" but plugs. However, it would be nice to be able to see the state of the plugs reflected in the app too. Also KaKu is one-way only, you can't read out KaKu as far as I know. That's one of the advantages of Z-wave over KaKu...

**Comment by Arjanvde** [comment]
@bvdbos my mistake to mention it where lights instead of plugs. But the colour of the switches should reflect the same colours as the Z-Wave switches do. At least it should remember it's last state and should display the corresponding colours.

**Comment by Arjanvde** [comment]
Looks like this issue has been solved, Nice work!

**Comment by WeeJeWel** [comment]
Thx!
