### ISSUE TITLE
Z-wave status change not initiated by Homey is not triggering flow

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#310]
**What is your Homey version (Settings → System)?**

0.8.20
**What did you try to achieve?**

Trigger a flow when a Z-wave switch (Fibaro relay switch) is turned on

**What was the result?**

The flow with action card "NNN turned on" is not triggered
 
**What did you expect as result?**

Flow is triggered

**Any other remarks**

The status change is noted in the "Devices" tab, so the update is received and processed by Homey.

When using the action card 'is turned on' in the AND flow, the status is recognised. So as a workaround I can make a flow WHEN "every 5 seconds"  AND NNN is turned on , THEN <execute> . But this will give a delay and when used a lot, might impact cpu load on Homey.

**Comment by WeeJeWel** [comment]
Can you post a screenshot of your flow?

**Comment by ralfvd** [comment]
I am unable to reproduce for now. See my remarks at issue #315 , the device was twice in the list (2 devices, same node-id), so that might not have helped.

Another Z-Wave device did work as expected with the NNN turned on as the trigger card for the flow. 

So my guess is that this issue was caused by the double-entry of the device during pairing. I'll close it for now, if it re-appears with single id devices (as it should be), I'll open a new issue.
