### ISSUE TITLE
Time issue with sunrise and sunset starts/ends

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#313]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
I'd like to switch some lights on when sunset starts/sunset ends so made a little set-up that when sunset starts the following light would be switched on.

![schermafbeelding 2016-03-07 om 18 57 04](https://cloud.githubusercontent.com/assets/17526110/13578278/469436cc-e497-11e5-9ebd-018531c99cc6.png)

**What was the result?**

The result was that nothing did happen, i looked up the sunrise/sunset times see attached at noticed that today the sunset should be at 18:31. At 18:35 still nothing happend. 

![schermafbeelding 2016-03-07 om 19 00 50](https://cloud.githubusercontent.com/assets/17526110/13578302/7cef2fb0-e497-11e5-91d9-3854b0092db3.png)

Eventually i did a little investigation myself my dragging the time into the slack notification bar (which actually works perfectly) and got a message that sunset would  start at 21:23. Could be that i broke it or did something wrong, but sunrise starts/sunrise ends, sunset starts and sunset ends did all gave me a time back from 21:23.

![schermafbeelding 2016-03-07 om 19 07 13](https://cloud.githubusercontent.com/assets/17526110/13578364/d51fb7e0-e497-11e5-9b47-236fa361675e.png)

**What did you expect as result?**

The lights to be switched on at 18:31

**Comment by bvdbos** [comment]
#182

**Comment by Arjanvde** [comment]
Thanks!

**Comment by dkruyt** [comment]
Got same problems with sunset/sunrise times are way off...

**Comment by Dijker** [comment]
@dkruyt  
What do you mean with way off? 
Wat did you test, what did you expect and what was the result?

**Comment by dkruyt** [comment]
First it went like 3 hourse before sunset. Then I rebooted homey, and it work on the expected time. But one day later It didn't work on the time.

When I run the flow in test mode and let homey say the sunset time, it say 21:23 but expected is 20:24. The strange thing is it is the same time at the topic starter. Is 21:23 somewhere hardcoded?

**Comment by freemann** [comment]
Tests uses random data. Probably if you run the test multiple times, homey says different times.

**Comment by freemann** [comment]
I now see above scenarios also has the result/output of 21:23.

Can't imagine how that sun time is hardcoded. If something is hardcoded, I hope it are only some test parameters.

**Comment by Dijker** [comment]
If you read the #182 thread, you could know tests always report 21:23 .
Afaik only the sunsets work mostly.... Dependent on location it triggers.

**Comment by freemann** [comment]
My apologies.
