### ISSUE TITLE
Fibaro dimmer 2

### ISSUE THREAD

**Issue by justjom** [athombv/homey#318]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

Pair a Fibaro Dimmer 2 http://www.fibaro.com/manuals/en/FGD-212/FGD-212-EN-T-v1.0.pdf

*Please include detailed steps how we can reproduce the issue*

I did a clean install/wipe all data and reboot after it. Then went to add Z-wave -> add device and pushed the B-button to connect. Homey did not sense the Z-wave dimmer

**What was the result?**

No connection with the dimmer
...

**What did you expect as result?**

A connection with the dimmer

**Any other remarks**

The storage window shows nothing. This seems strange to, maybe connected to the Z-wave issue.
<img width="1156" alt="schermafbeelding 2016-03-08 om 20 35 53" src="https://cloud.githubusercontent.com/assets/17655941/13613689/7dd3ab46-e56d-11e5-8eda-ef0f99d7da0e.png">

**Comment by ocatie** [comment]
You have te clear the network data of the device also. Preform a Remove Node process from the Z-Wave settings page, or factory reset your device. Then you can add the device to a new network.

**Comment by justjom** [comment]
Hi Taco, this was all done including a factory reset of Homey. So closing is unfortunately a little to early.. Can you re-open this case? Please let me know what I can do to test.
