### ISSUE TITLE
homey keeps speaking gibberish (oeps can't ip server something)

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#319]
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
nothing homey keeps on speaking gibberish
about 3 or 4 times in a hour

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by bvdbos** [comment]
I think you have set language to Dutch while English text is fed to the speech output, at least that was the case over here :-)

**Comment by kingdong78** [comment]
yes thats right i changed it to english again but is keeps on saying oeps can't reach server what could be wrong

**Comment by bvdbos** [comment]
#99 
#133 
#132

**Comment by WeeJeWel** [comment]
Fixed in 0.8.23
