### ISSUE TITLE
unable to install 0.8.11 update

### ISSUE THREAD

**Issue by madtraxx18** [athombv/homey#32]
0.8.11 has been released but I am unable to install it, it does not do it automatically, if I disable automatic updates I get a notification that there is a new FW version, when clicking install it comes up with a new dialog saying:

Error: already_updating

If I click ok, and click update again the update bar shows on the page but nothing happens.
Rebooting homey doesn't work either....

**Comment by WeeJeWel** [comment]
That's odd! So after a reboot, you get the same error?

You can always put Homey in Recovery Mode (turn it upside down while running), re-connect it to Wi-Fi and install the update from there.

**Comment by madtraxx18** [comment]
i'll try that :)

**Comment by freemann** [comment]
@madtraxx18 and did it work?

**Comment by madtraxx18** [comment]
seems to be installed now, thanks guys!

**Comment by WeeJeWel** [comment]
Which method did work, recovery or from Homey itself?

I've upgraded the updater software. Will test is heavily, and ship it asap, to make sure this never happens again.

**Comment by madtraxx18** [comment]
Recovery was the only to get it working, had to turn it off and on again after the update because the led ring kept on flashing yellow indefinitely.

**Comment by WeeJeWel** [comment]
OK thanks!
