### ISSUE TITLE
If Homey Speaks Led ring flashes red for a short time during speach

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#320]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

If Homey speaks, the LED ring turns quickly red before turning back to the normal orange speaking color.
https://youtu.be/4ftztebOa2A

**What was the result?**

Led Ring turns red for very short time.

**What did you expect as result?**

The led ring to stay orange and no red to appear.

**Comment by WeeJeWel** [comment]
This is because of the brightness is too low. Fixed in 0.8.23.

**Comment by bvdbos** [comment]
I wonder what the source-code of this bug looked like :-)
