### ISSUE TITLE
speech input breaks homey

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#321]
**What is your Homey version (Settings → System)?**
0.8.22

**What did you try to achieve?**
Turn on speech input after having installed Dutch. It breaks Homey, hangs with a light orange ring...
https://forum.athom.com/discussion/comment/13550/#Comment_13550

I set Homey back to English, deleted the downloaded Dutch voice, restarted and turned the microphone on. It hangs after the first input (not only voice hangs but Homey as a whole). Probably related to #316 but different usecase and effect. Only way to get back into Homey is to power down and after powering up be quick to disable microphone before it receives any input.
log: 608F2B4259

**Comment by Arjanvde** [comment]
Same happend to me with English voice, the LED ring started to flicker/pulse quickly between orange and red and then stalled at orange. For now, the microphone is off once again.

**Comment by justjom** [comment]
https://pypi.python.org/pypi/SpeechRecognition/

Maybe change the Homey Speech engine to this?

**Comment by WeeJeWel** [comment]
We've just isolated the issue and are on it!

**Comment by bvdbos** [comment]
Great, didn't reset yet so I can run a test tonight if you want to test the
upgrade-process.

2016-03-10 12:15 GMT+01:00 Emile Nijssen <notifications@github.com>:

**Comment by bvdbos** [comment]
This works in 0.8.24 but I had to do a system-reset with deleting all settings to get this to work...

**Comment by bvdbos** [comment]
This works now...
