### ISSUE TITLE
No image shown on device card

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#322]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**
Switch state of a Z-Wave relais

*Please include detailed steps how we can reproduce the issue*
Try and switch state of a Z-Wave relais

**What was the result?**
Device card showed no device image. Was able to switch device state, though.
...

**What did you expect as result?**
Device should have shown image.
...

**Any other remarks**
See attached image.
...
![image](https://cloud.githubusercontent.com/assets/17163901/13628729/ebad6820-e5d4-11e5-9ae8-f3c2ff3bdd08.png)

**Comment by bvdbos** [comment]
Confirmed, I have this with a kaku-lamp. Is this only for the first device, then it could be css-related?

**Comment by Arjanvde** [comment]
@Muyz, I don't think the device is not shown, if you switch the device cards it is suddenly there. There is an error where the card is shown for 60/70%, the other 40/30% is shown under the device tab.

![card shown](https://cloud.githubusercontent.com/assets/17526110/13629590/54c908d2-e5da-11e5-9fc9-aa8f853e96e1.png)

**Comment by Muyz** [comment]
@Arjanvde To be honest: I don't care what the underlying root-cause is. Might be a stacking orde issue indeed. The issue was and is that I expect a device image to show up and it does not...

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Muyz** [comment]
Since I sold my Homey today, I am not able to tell.
