### ISSUE TITLE
Sundown / SunRise

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#323]
0.8.22

**What did you try to achieve?**
Flows for switching lights on sundown and of for Sunrise and other tasks 

*Please include detailed steps how we can reproduce the issue*
Just create a sundown / Sunrise flow

**What was the result?**
No activation of the flow on sundown or sunrise

**What did you expect as result?**
Switch on or off of flow on sundown and same for sunrise

...

**Comment by bvdbos** [comment]
@182 ?

**Comment by mruiter** [comment]
Did a search and did not popup. But now its also logged again for 8.22 :)

**Comment by MdeRhoter** [comment]
Confirmed, neither sunrise nor sunset cards work.

**Comment by KroontjesPen** [comment]
It looks like difficult to make to see by the first ticket: #8

**Comment by WeeJeWel** [comment]
Duplicate of #182
