### ISSUE TITLE
Time is stuck after testing a flow.

### ISSUE THREAD

**Issue by AJediIAm** [athombv/homey#327]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

I was trying to switch the language from English to Dutch.
I translated my time flow and pressed the test button. 

**What was the result?**

Homey said it was 21:23 instead of 22:23
When I switched back to English, the time said to be 21:23, but in the meantime, it was 22:25. 
Even after rebooting (unplugging the power), the time was still said to be 21:23 instead of 22:31

**What did you expect as result?**

I expected the English and dutch voice to both say the correct time.

**Any other remarks**

Thank you for the huge number of bug-fixes. Keep up the good work!

**Comment by Dijker** [comment]
If you test te TEST button it is ALWAYS 21:23 and the TEST with NFC cards ALWAYS result in a Card with ID 01:23:45:67 scanned. These are some defaults / dummy's Homey uses with tests.

**Comment by AJediIAm** [comment]
I didn't know that. Very coincidental that I tested it exactly an hour later. I really thought I broke Something. 

Anothe mystery solved. Thanks!
