### ISSUE TITLE
No speak but heavy noise 

### ISSUE THREAD

**Issue by harmstellinga** [athombv/homey#329]
**What is your Homey version (Settings → System)?**
0.8.22

**What did you try to achieve?**
Hear a voice

*Please include detailed steps how we can reproduce the issue*
Let HOMEY Said something, via manager/speech-input

**What was the result?**
No speech, but heavy noise out HOMEY 

**What did you expect as result?**
Hear a clear voice

...

**Any other remarks**
This happens sometimes.

...

**Comment by WeeJeWel** [comment]
Auch. Sounds like a hardware issue. What happens when you play music?

**Comment by harmstellinga** [comment]
It also happens when playing music via soundcloud, and via flow programmed,
It is not always, but 50/50 , when music starts good it stays good till the and of the song.
The very first time i started HOMEY, the first voice announcement whas overwelmed with noise.
It looks like in the latest firmware 0.8.22 it get worse, we see if it gets better with new update.

**Comment by harmstellinga** [comment]
Since the last update 0.8.24 the speech is good here, no nois on the speech.
