### ISSUE TITLE
RF sockets cannot be added or toggled

### ISSUE THREAD

**Issue by jonathanjuursema** [athombv/homey#33]
The interface doesn't respond when trying to add a socket, and it also does not respond when trying to toggle an existing socket.

**Comment by WeeJeWel** [comment]
Which brand of socket?

**Comment by freemann** [comment]
@jonathanjuursema could you share some more information so this issue can be closed or even better solved?

**Comment by jonathanjuursema** [comment]
Via devices, when trying to add a device via the [+] button, the menu opens. However, I can't select either one of the sockets (and neither the Bluetooth speaker as I find out now). I can select IR and ZWave. Clicking on the button fires the buton flashing, but no screen pops up.

I had an existing socket in one of the zones, and trying to toggle it manually via the interface also yielded nothing.

**Comment by WeeJeWel** [comment]
Which app did you install?

**Comment by freemann** [comment]
Very efficient bug fixing.... :heart:

**Comment by jonathanjuursema** [comment]
I'm sorry for the late comment, but last few days I've been working around the clock to finish my courses. ;)

I'm using the Athom Action app from the Athom App store.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.16
