### ISSUE TITLE
Z-wave SIS

### ISSUE THREAD

**Issue by filoor** [athombv/homey#331]
I have homey as a second controller with  SIS id after setting it up it worked after an hour or so homey dident show up my zwave devices (see image) after reboot i see my devices again but som are double now  (see image) and after some minutes they disappear again 

![homeysis](https://cloud.githubusercontent.com/assets/3647638/13697572/83d9fac4-e76e-11e5-8e7b-f49690be5995.jpg)
![homeysis2](https://cloud.githubusercontent.com/assets/3647638/13697573/83e19252-e76e-11e5-89ac-c4917871d653.jpg)
![homeysis3](https://cloud.githubusercontent.com/assets/3647638/13697574/83e24b16-e76e-11e5-9adb-cdbd4f7ad0ec.jpg)

homey version 0.8.22

**Comment by ocatie** [comment]
Do the double devices in the zone overview have a different node id? You can find the node id by pressing the wrench. Multichannel endpoint have a dot in their node id.

If you reload the setting page, is the dropdown filled again?

**Comment by filoor** [comment]
No the have the same node id ("see image")
no the don't only after a reboot and also if i klik on request a network update the disappear 

![zwave1](https://cloud.githubusercontent.com/assets/3647638/13722503/382376b6-e848-11e5-836c-69dc3547b268.jpg)
![zwave2](https://cloud.githubusercontent.com/assets/3647638/13722500/38220aec-e848-11e5-8538-2f1265025285.jpg)
![zwave3](https://cloud.githubusercontent.com/assets/3647638/13722501/38220da8-e848-11e5-976c-30cfa8ffe8ae.jpg)
![zwave4](https://cloud.githubusercontent.com/assets/3647638/13722502/382353ca-e848-11e5-8285-a11675bef00a.jpg)
![zwave5](https://cloud.githubusercontent.com/assets/3647638/13722504/3824ad42-e848-11e5-9136-582b1a6729de.jpg)

**Comment by ocatie** [comment]
The message that a node was added by another controller is send multiple times. Building a debouncer in that function.
