### ISSUE TITLE
Spacing of my.athom is off when zoom is <100%

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#332]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

When the zoom of your browser is lower then 100% the setting icon moves to a place underneath the devices icon

![start screen icons](https://cloud.githubusercontent.com/assets/17526110/13700062/d93374fe-e77e-11e5-8662-65ec24a6bbf4.png)

**What did you expect as result?**

That the spacing of the icons is fixed and are always in a row of 4.

**Comment by WeeJeWel** [comment]
Zooming is not officially supported because we will launch the Athom desktop app soon :)
