### ISSUE TITLE
Homey crashes after a reboot and led ring stays orange

### ISSUE THREAD

**Issue by edtst** [athombv/homey#335]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

Nothing, my Homey suddenly shows a steady orange ring and I cannot reach it anymore.

*Please include detailed steps how we can reproduce the issue*

This happened suddenly.

**What was the result?**

After I reboot, the ring becomes normal, but after a few minutes, it turns steady organge.
...

**What did you expect as result?**

Normal workings
...

**Any other remarks**

...

**Comment by bvdbos** [comment]
probably #316 ? Can you turn your microphone off and see if it still hangs?

**Comment by bvdbos** [comment]
or #321 ...

**Comment by edtst** [comment]
#316 seems close, except I only got this yesterday after 1,5 week of using 0.8.22. Turning off the mic fixes it.

**Comment by bvdbos** [comment]
The fix will be rolled out in the next FW, probably Monday...
