### ISSUE TITLE
Support for ACM-LV10 Mini 0-10V LED Controller

### ISSUE THREAD

**Issue by damylen** [athombv/homey#337]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

Control the ACM-LV10 Mini 0-10V LED Controller
http://www.klikaanklikuit.nl/shop/nl/acm-lv10/

*Please include detailed steps how we can reproduce the issue*
I tried the KAKU dimmer, Without any results

**What did you expect as result?**
I would like to have a device that can receive a 0-10 number as an input and will set the dimmer accordingly...

**Any other remarks**
I want to use it to control gas fire and my air ventilation system (Buva) . 
...

**Comment by Dennishacq** [comment]
Hi @damylen 
Thank you for submitting your issue.
Are you able to pair the ACM-LV10 with the KaKu dimmer driver?
If not: are you able to pair any other 433MHz device?
