### ISSUE TITLE
suddenly coldplay is played through homey speaker without command

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#338]
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**
nothing

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...is somebody hacking homey

**Comment by kingdong78** [comment]
i have set no flow in place for this how is this possible

**Comment by Fire69** [comment]
Your Homey probably just triggered incorrectly to something it heard you say...

**Comment by WeeJeWel** [comment]
This is part of our new 'Music Discovery' service. Big Music Labels pay us to get feedback from users about new songs.

Haha, no, just kidding. Homey might have heard 'play coldplay' or so. I'll add a log of heard commands to debug easier!

**Comment by kingdong78** [comment]
Emile 

Hahaha thanks 

Van:  Emile Nijssen <notifications@github.com>
Beantwoorden - Aan:  athombv/homey
<reply+01063c59a3ee1f2154ed43adb59065efc9c57d10b31c675c92cf0000000112fe59c19
2a169ce085f9035@reply.github.com>
Datum:  maandag 14 maart 2016 11:51
Aan:  athombv/homey <homey@noreply.github.com>
CC:  Wd Overloop <b.ketelaar19@upcmail.nl>
Onderwerp:  Re: [homey] suddenly coldplay is played through homey speaker
without command (#338)


This is part of our new 'Music Discovery' service. Big Music Labels pay us
to get feedback from users about new songs.

Haha, no, just kidding. Homey might have heard 'play coldplay' or so. I'll
add a log of heard commands to debug easier!


Reply to this email directly or view it on GitHub
<https://github.com/athombv/homey/issues/338#issuecomment-196254532> .

**Comment by jeroenvollenbrock** [comment]
Speech log is visible at http://<homey-ip>/manager/speech-input/
