### ISSUE TITLE
unable to install soundcloud plugin

### ISSUE THREAD

**Issue by madtraxx18** [athombv/homey#34]
Since update 0.8.11 souncloud can't be installed. the installation says;

Something went wrong..... the app is listed as installed but there is no way to use it (doesn't show up as buitenradar and IFTTT)

**Comment by WeeJeWel** [comment]
Is it listen in Settings -> Apps?

**Comment by madtraxx18** [comment]
Yes it is...

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment]
Should be working then. Can you find music on `/manager/media/`, or in the Flow editor under Music (action).

**Comment by madtraxx18** [comment]
Found it, but nothing to select / configure 

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment]
Flow editor seems to be a bug indeed - fixed that, will ship in next update.

/manager/media/ should look like this:

![screen shot 2016-01-22 at 21 12 56](https://cloud.githubusercontent.com/assets/319873/12521830/436313fa-c14d-11e5-82ed-d48784a52843.png)

Is this not the case?

**Comment by madtraxx18** [comment]
I'll check later on, no access to the homey atm (iPhone)

Verstuurd vanaf mijn iPhone

**Comment by freemann** [comment]
And?

**Comment by madtraxx18** [comment]
![image](https://cloud.githubusercontent.com/assets/16655593/12647863/a89f4b92-c5d7-11e5-9aaa-d18dae6198aa.png)
 Nope not working....

**Comment by WeeJeWel** [comment]
Add a trailing slash (/manager/media/)

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
hmmm page seems to be a bit crippled

![image](https://cloud.githubusercontent.com/assets/16655593/12648067/7299e92a-c5d8-11e5-9ce4-20570b1e4f4f.png)

**Comment by WeeJeWel** [comment]
It's made for mobile display, resize your window  horizontally:-)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
keeps on searching but nothing found

![image](https://cloud.githubusercontent.com/assets/16655593/12648258/5a44f454-c5d9-11e5-8ed9-3a8e862bae88.png)

**Comment by WeeJeWel** [comment]
Weird. Can you show me your console output? Please make a screenshot (right click -> Inspector with tab Console open)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
![image](https://cloud.githubusercontent.com/assets/16655593/12648552/cdc85bd6-c5da-11e5-95fb-9298d1379d1a.png)

**Comment by WeeJeWel** [comment]
We're getting close. Can you click the url homey-568.. and select the tab Response?  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
getting a different one now:

![image](https://cloud.githubusercontent.com/assets/16655593/12649349/8489a21e-c5de-11e5-8ef7-9cd7c32dd4b8.png)

![image](https://cloud.githubusercontent.com/assets/16655593/12649365/98aa4eec-c5de-11e5-85c7-4f0a73d24896.png)

**Comment by WeeJeWel** [comment]
Almost got it! What is the full text 'TypeError: undefined is not a function<br'?  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
TypeError: undefined is not a function<br> &nbsp; &nbsp;at Object._.contains.e.search (/opt/homey-client/system/types/manager/apps/manager.js:1:6881)<br> &nbsp; &nbsp;at /opt/homey-client/system/types/manager/media/manager.js:1:2867<br> &nbsp; &nbsp;at /opt/homey-client/node_modules/async/lib/async.js:567:21<br> &nbsp; &nbsp;at /opt/homey-client/node_modules/async/lib/async.js:246:17<br> &nbsp; &nbsp;at /opt/homey-client/node_modules/async/lib/async.js:122:13<br> &nbsp; &nbsp;at _each (/opt/homey-client/node_modules/async/lib/async.js:46:13)<br> &nbsp; &nbsp;at async.each (/opt/homey-client/node_modules/async/lib/async.js:121:9)<br> &nbsp; &nbsp;at _asyncMap (/opt/homey-client/node_modules/async/lib/async.js:245:13)<br> &nbsp; &nbsp;at Object.map (/opt/homey-client/node_modules/async/lib/async.js:216:23)<br> &nbsp; &nbsp;at _parallel (/opt/homey-client/node_modules/async/lib/async.js:565:20)

**Comment by freemann** [comment]
TeamViewer?

**Comment by WeeJeWel** [comment]
Awesome, I got enough info, will look into it!  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by madtraxx18** [comment]
Ok perfect thanks!
