### ISSUE TITLE
Speech broken

### ISSUE THREAD

**Issue by edtst** [athombv/homey#341]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Tried the normal commands like time, how are you, etc.

*Please include detailed steps how we can reproduce the issue*

Update Homey to 0.8.24 and voice is broken again, but now totally.

**What was the result?**

Nothing

...

**What did you expect as result?**

That homey would talk back
...

**Any other remarks**

I tried a power cycle, retrain OK Homey. 

...

**Comment by WeeJeWel** [comment]
Does issue #352 apply to you?

**Comment by Arjanvde** [comment]
Simple way to test is go to http://Homey's-ip/manager/speech-input and then type in a sentence like "What is the time" Homey should give you the correct time. If no time appears, it is possible the same issue as #352

**Comment by edtst** [comment]
No, this did not solve the problem. I can type, but on speech output there is no answer, even not for time. I worked around it by changing the voice, uninstalling it and then download it and change it back. Now it works.

**Comment by hellhond** [comment]
Had a similar issue, no idea if it is related. But, was trying out other voices, and suddenly Homey crashed (red LED), and used homey_recovery to recover.After that the default voice (Brian I think) was not working anymore. Switched voices, and then the following error appeared in a popup,

 Unable to load voice:/opt/user/manager/speech-output/voices/en-gb-brian/vox.so: cannot open shared object file: No such file or directory

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
