### ISSUE TITLE
Have to speak very soft

### ISSUE THREAD

**Issue by edtst** [athombv/homey#342]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

OK Homey

*Please include detailed steps how we can reproduce the issue*

Retrain OK Homey

**What was the result?**

While traioning I have to speak loud, but afte rthe training I almost need to whisper.
...

**What did you expect as result?**

Normal speaking would be fine
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
We're working on this. I'll close this issue for now, as it cannot be 'solved'.
