### ISSUE TITLE
setup.athom.com doesn't find my Homey

### ISSUE THREAD

**Issue by edtst** [athombv/homey#343]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Recover procedure

*Please include detailed steps how we can reproduce the issue*

Afte rthe update I tried to reset homey using the outlined procedure, but setup.athom.com won't find Homey after my laptop connects to Homey's WiFi. I tried this several times before and it used to work ok.

**What was the result?**

Spinning circle on the page and a red/orange spinning Homey.

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
What is your PC's IP Address when connected to HomeySetup? Can you ping 10.199.198.1?

**Comment by edtst** [comment]
I did some testing and both my android Phone and windows laptop do not get an ip address. I have done a reset before, so it used to work.

I manually entered 10.199.198.2 as ip address with subnet masks 8, 16 and 24, but none allow me to ping the given address.

**Comment by WeeJeWel** [comment]
Is Homey plugged in to a power socket and not a computer?

**Comment by edtst** [comment]
Yes a regular socket using the supplied cable. I discovered that am able to us ethe setup if I first power down Homey and then boot, turn it up side down and setup immediately. If I wait for say 15 mins it doesn't work anymore.

**Comment by edtst** [comment]
I tested some more and it seems random. When you connect homey sometimes dies and disconnects. On other occasions it will work. Tried it +/- 10 times and succeeded twice.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
