### ISSUE TITLE
Help text when learning voice not visable

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#344]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

When calibrating a voice, speech suggestions are given on my macbook they are given behind the circles.

![schermafbeelding 2016-03-16 om 17 50 24](https://cloud.githubusercontent.com/assets/17526110/13821190/dd28b6ac-eba0-11e5-8749-2c9e14111967.png)

**What was the result?**

Needed to go full screen or adjusted the zoom size to get the text visable.

**What did you expect as result?**

Text in the correct space.

**Comment by WeeJeWel** [comment]
Voice training is removed in v0.8.34.
