### ISSUE TITLE
zwave cant reach device

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#346]
**What is your Homey version (Settings → System)?**

0.8.24

*

What did you try to achieve?
Add a device , fibaro wallplug 

*Please include detailed steps how we can reproduce the issue*
Add device and wait ...

**What was the result?**
Device cant reach after some time.
...

**What did you expect as result?**
socket to work

**Any other remarks**

99B30F1C45

refresh and restart zwave dont help

![zwave](https://cloud.githubusercontent.com/assets/17300121/13825932/488b1e6c-ebb5-11e5-8333-a7829b6a2244.JPG)

**Comment by jghaanstra** [comment]
I have had this issue since I recieved my Homey with 0.8.17 but it seem to have gotten worse from 0.8.20 and higher. It only happes on z-wave sockets that are quite far from the controller (Homey) but there is a route to it using other sockets. It looks like the explorer frames or routing in general are not doing a good job.

**Comment by djeskoswe** [comment]
my 2 sockets are 2 m from homey , my fibaro (did add as on/off switch when interview fail) is dead but my TKB that got included OK works and my fibaro sensor.

**Comment by ralfvd** [comment]
I've seen this as well on a Z-Wave 230V powered device (Fibaro relais switch), 3 meters reach to Homey. If it is not used for N amount of hours, it will become unresponsive.

As soon as you manually change it (via the manual switch), it will report 'alive' again. Also a 'refresh node' in the z-wave settings page will get it back in order.

This is currently my only 230V powered Z-wave device, so I don't think it is routing. The other z-wave devices are battery powered .

**Comment by djeskoswe** [comment]
update : 5 days without reboot and fibaro socket works OK as on/off switch ..but now after a reboot Homey cant reach device.  its not marked as dead device and refresh / restart zwave does not help

**Comment by athomey** [comment]
Is there a problem with range of Homey? Or with z-wave devices relaying commands from Homey? I've seen this issue when getting at ~5 meters distance and 1 door between Homey and the device. With Vera/HC2 I notice after a while the network "knows" all z-wave devices and reaches all of them very well. With Homey it seems like range is very small and IF you get out of range, whole z-wave stack on Homey gets unstable.... Maybe relation with #381

**Comment by freemann** [comment]
Here also;
![new](https://cloud.githubusercontent.com/assets/601053/14949216/4fc67f48-1048-11e6-8fc5-49802821de32.png)

By removing the Unavailable layer i found its ID 30 and here's a systemlog;
C6E1FB6552
