### ISSUE TITLE
Zwave connection state logging

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#347]
Cant you add transfer fail/ok when sending zwave commands ?

![home_send](https://cloud.githubusercontent.com/assets/17300121/13827356/5423f710-ebbc-11e5-84f4-9e096b20f046.JPG)

![fiaro](https://cloud.githubusercontent.com/assets/17300121/13827369/632bba90-ebbc-11e5-9750-7e0c5f6d8fbf.JPG)

**Comment by athomey** [comment]
See also: https://forum.athom.com/discussion/1045/please-show-more-z-wave-state-logging-to-keep-user-informed#latest  for comparison with Vera Edge/Fibaro HC2.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
