### ISSUE TITLE
location-map is missing

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#348]
**What is your Homey version (Settings → System)?**
0.8.24

**What did you try to achieve?**
Set location

**What was the result?**
No map, console:

`getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
util.js:218 
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js:218 
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required`

**Any other remarks**
Also after a complete reset

**Comment by Arjanvde** [comment]
I'm having the same issue on 0.8.24

**Comment by CootNL** [comment]
I have also the same issue on 0.8.24

**Comment by WeeJeWel** [comment]
Fixed in 0.8.25

**Comment by Dijker** [comment]
Map is working again, Thanks!
Should the pin be on the correct position when "Automatic detect my location" is selected?
After reboot it defaults on the grey map to coördinate 0, 0 (Gulf of Guinea) 
After switching once it is on the correct location until the next reboot.

**Comment by bvdbos** [comment]
closed, works now...
