### ISSUE TITLE
Insights Error: invalud value type : null

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#349]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Log a value to Insights.
A call to Homey.manager('insights').createEntry results in the error: "Insights Error: invalud value type : null" (note the typo as well).
The value passed is definitely not null.
Log was created with type 'number' and 'decimals: 2'. Log creation succeeded without errors.

**What was the result?**

Logging is broken.

**What did you expect as result?**

Value to be logged.

**Any other remarks**

My app is broken now.

**Comment by nlrb** [comment]
Apparently all values now need to be numbers for:
- Insights (type 'number')
- .realtime
- get functions (i.e. measure_temperature)

Adding Number(x) before calling the functions make it to work. It would be better if this was in the core code. I.e. `if (type == 'number') { value = Number(value); }`.
The error message does not represent what the problem is. Get functions don't even give an error.

**Comment by WeeJeWel** [comment]
Have you seen the changed docs @ https://developers.athom.com/api/?

createLog() has been changed to accept an object, instead of multiple parameters.

**Comment by WeeJeWel** [comment]
Next to that, you must supply a value that is the same type as your log. So if you create a log with type Number, you must supply a Number, same for Boolean.

**Comment by nlrb** [comment]
Yes, I use the new .createLog API as indicated. However, javascript is dynamically typed language. So to force such strong typing does not make a lot of sense. A string with '12.34' should also be interpreted as a number (like it was before).

**Comment by WeeJeWel** [comment]
imho the app developer is responsible for providing the correct variables, otherwise strange things might happen :-)

https://xkcd.com/1537/
