### ISSUE TITLE
Zwave node list says "loading ids" but does not load ids

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#351]
**What is your Homey version (Settings → System)?**
0.8.24

**What did you try to achieve?**
I wanted to refresh a node because from time to time they are timing out as reported here: https://github.com/athombv/homey/issues/346 . So I browse to the z-wave settings page to do so. But when I go to the zwave settings page I often have the issue where the list with node ids only shows the message "loading ids". No matter how long I wait, it does not show the list. Hard refreshing the page makes no difference, restarting the z-wave chip makes no difference. The only way to get the list to show again is rebooting.

**What was the result?**
Not being able to refresh the node but having to reboot to show the zwave node list again.

**What did you expect as result?**
A list with my zwave nodes so I could refresh any of them,

**Any other remarks**
My Log ID: **766C927EE3**

While wating for the list to refresh itself (which did not happen) I got a popup saying "True" with an OK button. No hints on what was true and why this popup appeared. The zwave node list did not refresh and I still had to reboot. And when I restarted the z-wave chip to see if this would bring back my z-wave node list I also got the same pop-up. Restarting the z-wave chip takes forever and the spinner inside the button does not end. You need to reload the page and then the spinner is gone. And while restarting the z-wave chip I also got this console error:

`api.js:1 GET http://192.168.0.120/api/wireless/zwave/allDevices/?_=1458198140424 net::ERR_EMPTY_RESPONSEwindow.Homey.api @ api.js:1o.contentWindow.Homey.api @ settings.js:1onHomeyReady @ (index):1s.onload @ settings.js:1`

**Comment by jghaanstra** [comment]
This issue might actually be an effect of an underlaying problem where z-wave completely crashes after some hours of use. All z-wave devices become unmanageble at some point. Restarting the z-wave chip brings it back up and it appears Homey is then handling all queued events since it went down.

Log: 5DF070DBDD

**Comment by ralfvd** [comment]
I have the same issue; after 24+ hours of use, the Z-wave devices cannot be controlled anymore, or used as input. I've had this a couple of times now since running 0.8.24. Reset of Z-wave chip sometimes helps, but most of the time I have to do a reboot. And many of those times, I need to do the power-reboot in order to get Homey booting again.

Log: 0F2ED11E5E

**Comment by athomey** [comment]
Maybe a relation with: #381   which also shows this problem as a result of my semi-reproduction of some other z-wave problems.  I get z-wave unstable within half an hour, when playing with making z-wave devices unreachable by moving them out of range of Homey.

**Comment by jghaanstra** [comment]
This issue still persists in 0.8.27 although it does not show "loading id's" anymore but a completely empy list. When this happens (which is pretty much within an hour of a fresh reboot) all zwave communication stops. Another odd thing I have noticed that when this happens all z-wave commands which are triggered through flows get queued. When I restart the zwave network chip all queued z-wave events are fired at once.

Log: 403567DBC1

**Comment by jghaanstra** [comment]
There are other bug reports for this same issue now (zwave instability), closed this one in favor of https://github.com/athombv/homey/issues/557
