### ISSUE TITLE
Manual speech input does not work when more then 1 flow with microphone is created

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#352]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Wanted to create a flow in which i was able to switch the TV off with a voice command and a command to switch the TV on with a voice command. As soon as I created the second flow, the  http://ip/manager/speech-input stops working, you can enter text but this text does not show up in the window in Google Chrome.

Recreating is simple, just make more than 1 flow with the given example.

![voice](https://cloud.githubusercontent.com/assets/17526110/13842809/86f36d00-ec30-11e5-8791-a7f90c0ee3ed.png)

**What was the result?**

Speech input doesn't work any more, entered text doesn't come through.

![5afa6900-e1eb-11e5-9afc-ce5722bb3d6d](https://cloud.githubusercontent.com/assets/17526110/13842849/a928bcd6-ec30-11e5-955c-065ec3bdb093.png)

**What did you expect as result?**

To have the possibility to create multiple triggers with voice commands.
...

**Any other remarks**

See bug #296 for more info.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.25

**Comment by Arjanvde** [comment]
Nice job!

**Comment by Arjanvde** [comment]
Tested, got multiple voice flows working.
