### ISSUE TITLE
Thermosmart App - Insights Temperature vs TargetTemperature 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#354]
**What is your Homey version (Settings → System)?**
Homey Version 0.8.24 / ThermoSmart App v1.0.4
**What did you try to achieve?**
View Set temperature vs Measured Temperature
*Please include detailed steps how we can reproduce the issue*
View Insights and select the two values 
**What was the result?**
The old app (Version 1.0.3 ? until 11 March 2016 around 5:02 PM ?) Logged the Measured Temperature, but no Target Temperature. 
The New app (Version 1.0.4 from 11 March 2016-now) Logs the Measured Temperature AS Target Temperature, except once the Program Switches to Basic SET-temperature (12,5 gr. C) Spikes Down
![image](https://cloud.githubusercontent.com/assets/12412734/13859537/37a1205e-ec84-11e5-816f-e91e1667f793.png)

**What did you expect as result?**
Two graphs: the measured temperature and Flat lines for the Target / Set  Temperature 
**Any other remarks**
1) Since 0.8.24 I see temperature with 1 decimal, before it where integers. Nice Thanks!!
2) At Athom:  Do you want further App [Thermosmart] Issues Logged at the App Github ? or keep everything here in the Homey IssueLog?
[https://github.com/athombv/nl.thermosmart/issues](https://github.com/athombv/nl.thermosmart/issues )

**Comment by WeeJeWel** [comment]
Fixed in 1.0.5. And yes, please report app-specific issues in their repository :+1:
