### ISSUE TITLE
Cannot install apps from the app store

### ISSUE THREAD

**Issue by denniedegroot** [athombv/homey#355]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Install a app from the app store.

**What was the result?**

"Something went wrong. Try again."

**What did you expect as result?**

The app installed on my Homey.

**Any other remarks**

After the failed installation of the app the Homey seems to reboot and then shows the app in the settings menu, but the app cannot be used.

This problem is also reported on the forum:
https://forum.athom.com/discussion/1009/cant-install-apps/p1

**Comment by denniedegroot** [comment]
I just tried to install the Harmony app and send a crash report (D0B9E1771C).

**Comment by WeeJeWel** [comment]
According to your logs the app is actually installed. What does `Settings -> Apps` show?

**Comment by denniedegroot** [comment]
After a reboot I can see the app installed but I can reproduce the problem with the Harmony app.

1. Go to the App store website and install the app
2. Blue led ring starts flashing
3. After about 2 minutes the App store webpage tells me "Something went wrong. Try again."
4. The Homey continues the blue led ring for about 1 minute
5. The rainbow led ring comes back but I cannot reach the Homey for about 2 minutes.
6. It becomes reachable again and the app seems installed.

**Comment by denniedegroot** [comment]
I cannot reproduce this for any other apps anymore.

**Comment by Fire69** [comment]
I have the same error but no reboot after that. 
The app is installed and fully functional. 
Same problem with the email app.

**Comment by filoor** [comment]
i stil have this problem with multiple apps

**Comment by WeeJeWel** [comment]
@filoor also that Homey reboots after installing an app?

**Comment by filoor** [comment]
no it dont reboot

**Comment by edtst** [comment]
This is still a problem in 0.8.27

**Comment by bvdbos** [comment]
Did one of you try a system-restore (holding Homey upside-down and reinstall)?

**Comment by denniedegroot** [comment]
0.8.32 solves this issue for me.
