### ISSUE TITLE
Action app cannot select "What is plugged in"

### ISSUE THREAD

**Issue by PandaNL** [athombv/homey#357]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Adding action impulse switch

**What was the result?**

The What is plugged in page is blank.

**What did you expect as result?**

Be able to select if the switch is a lamp or fan.

**Comment by Dennishacq** [comment]
Hi PandaNL,
Thank you for submitting your issue. This bug should be fixed in v1.0.12.

**Comment by PandaNL** [comment]
Works again, thank you.
