### ISSUE TITLE
Ask for confirmation won't listen for yes/no

### ISSUE THREAD

**Issue by PandaNL** [athombv/homey#358]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

When a flow gets trigered and asking for confirmation Homey won't listen for yes or no but goes right back to rainbow ring

**What was the result?**

Homey doesn't wait for yes or no

**What did you expect as result?**

Waiting for yes or no.

**Any other remarks**

Last version in worked in was 0.8.20 for me.

![schermafbeelding 2016-03-17 om 22 56 41]
(https://cloud.githubusercontent.com/assets/17313216/13862463/bdddbefc-ec93-11e5-8b3e-820b2d7075ba.png)

**Comment by jordenc** [comment]
I noticed the same. Worked on 0.8.20.
Might be related to multiple 'and' cards, but haven't tested that.

My flow:

![flow](https://cloud.githubusercontent.com/assets/17727803/13876990/37b39c00-ed08-11e5-8092-4ae4b6965718.png)

**Comment by Arjanvde** [comment]
Do you guys see the given answer showing up in the http://ip/manager/speech-input screen? You can also give the answer to the question (Which would be "yes") to check if the flow runs. A green check mark appears if the answer was correct.

**Comment by jordenc** [comment]
I can't test it at this time, will do that after the weekend. But for as far as I remember, it didn't show it.

However, the LED ring goes to rainbow mode directly after the question is asked. So it (at least) appears not to be listening.

**Comment by PandaNL** [comment]
Yes you can type "yes" and it will trigger the flow.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.25
