### ISSUE TITLE
can't login node athom -cli 1.0.22 64 bit node version 5.7.

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#360]
**What is your Homey version (Settings → System)?**

0.8.24          node athom cli 1.0.22

**What did you try to achieve?**
log in with new login method node athom cli where you type your emailadress and pasword on the commandline of node. 
*Please include detailed steps how we can reproduce the issue*
try to login with emailadress and login in version 1.0.22 of the  node athom cli 

**What was the result?**
user credentials invalid . if i use the same credentials in my.athom.com they work
...

**What did you expect as result?**

...to be logged in

**Any other remarks**

...

**Comment by nattlip** [comment]
1.0.16 works , it is with the old webbrowser login. npm install athom-cli@1.0.16

**Comment by WeeJeWel** [comment]
Do you have any special characters in your password? If you'd like, you could send me your password, but with changed letters and numbers, so I can try to reproduce.

**Comment by nattlip** [comment]
i use master.jilles.gp@gmail.com as email adress that is the problem, the dots i think , in homey my email is shown without dots in users screen . i added a user with this email  nattelip adress  that works in 1.0.22

Date: Sat, 19 Mar 2016 13:57:11 -0700

**Comment by joachimroeleveld** [comment]
This should be [fixed](https://github.com/athombv/homey/issues/70#issuecomment-198787564) now.

**Comment by nattlip** [comment]
email adres with dots in n ame master.jilles.gp@gmail.com still gives user  credentials are invalid.

**Comment by nattlip** [comment]
i cant reopen the issue

[http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github](url)

**Comment by joachimroeleveld** [comment]
Yes, I should have been clearer on that. Since you created your e-mail address with dots, and normalization was applied on that, you can now only login with your email addresses _without_ dots. If you value to use your email addresses with dots, I can edit it for you, if you like.

**Comment by nattlip** [comment]
i can use the athom-cli now but there could come others with in there emailadress

**Comment by joachimroeleveld** [comment]
From now on, that shouldn't be a problem anymore. Please refer to [this issue](https://github.com/athombv/homey/issues/70#issuecomment-198787564) for more information.

**Comment by nattlip** [comment]
okay , now i get it , normalization is removing the dots from your emailadress, indeed without dots the same emailadress works. this wasn't clear to me. Is a little-bit confusing that you can login on http://my.athm.com with dots and in athom-cli without. You can use the same normalization as google but i can login in google with dots.

**Comment by nattlip** [comment]
sorry i read my email of today just now.
