### ISSUE TITLE
Homey push notification send unintentional to multiple users instead of only 1

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#361]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Send a push notification to **only** my telephone using a Homey Flow.

**What was the result?**

I get the push notification on my telephone but my girlfriend also gets the same push notification on her telephone. My girlfriend is logged in on the Homey app on het telephone with her own username and password.

**What did you expect as result?**

That only the person who is mentioned in the send push notifcation card in the Homey flow editior get's the push notification.

**Any other remarks**

When I adjust the flow so that only my grilfriend should receive the push notification it works like it should. So she gets a push notification and I don't.

I'm the Homey Owner (in the Homey user settings tab) and my telephone is a Samsung S6
My girlfriend is a User (in the Homey user settings tab) and her telephone is a Samsung S4 mini

**Comment by goldenice** [comment]
Hey @JesperJanssen, sorry to hear this, sounds like a mix-up in our push notification service. We're currently working on improving push notifications by doing a partial rewrite and adding a few badass new features, but for it to be integrated we'd have to update the Android app, My Athom and the Athom API as well. As you probably can imagine, coordinating this all is pretty tricky, so deployment of the new version might take a while.

Anyway, we're actively working on this, so when 'push notifications 2.0' is deployed, it should work as expected again :smile:

**Comment by freemann** [comment]
@goldenice 
Is "push notifications 2.0" already deployed? 

I testing this flow and only my Wife is occasionally receiving notifications and i'm receiving non;
![screenshot - 25-4-2016 22_53_04](https://cloud.githubusercontent.com/assets/601053/14798686/1ff15f90-0b39-11e6-83b0-a691d76aa850.png)

**Comment by goldenice** [comment]
Not yet, I'm still working on it. I think it might be in the next Android beta ;)

**Comment by btwvince** [comment]
@goldenice 
Is there already some news about this  because since the new beta i don't receive any notification not with my phone or my girlfriends phone.

**Comment by goldenice** [comment]
Yes, there is! We're just figuring out the last bits here; the only thing left to do is to write a migration script for the device data from notifications version 1.0 to notifications version 2.0, so we don't break all 1.x Android devices and older Homey versions. That's not entirely straightforward because there are loads of different services involved (to name a few: Google, Apple, Athom API, My Athom, Athom Notifications, Homey itself and of course the Android and iOS devices).

Anyway, we're hoping to roll out a new version of the Android beta somewhere next week, and the new notifications service alongside it :)

**Comment by goldenice** [comment]
Little update; I might have been too soon with the good news that we're not going to break Android 1.x app installations. We can't fit our old model properly in the new model, and migrating it properly would take pretty long to develop, and we can't justify that much time being spent on devices that get updated to 2.x within days. When the Android 2.x branch ships, we encourage everyone to update quickly.

**Comment by goldenice** [comment]
Push notifications on Android have been deployed for quite some time now, so I'm closing this issue.

**Comment by freemann** [comment]
Push notifications is still a big issue! Here both the android phones not receiving proper/intended notifications.

**Comment by goldenice** [comment]
@freemann Yeah, I agree, but #672 describes the current issues much better, and this issue was initially for problems in the 1.x versions of the app, so it probably makes more sense to continue the conversation in #672

**Comment by freemann** [comment]
OK!
