### ISSUE TITLE
Unable to choose device type for Dimmer klikaanklikuit

### ISSUE THREAD

**Issue by rikpost** [athombv/homey#364]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

When adding new klikaanklikuit dimmers it's not possible to choose what is plugged in, only a blank screen is visible.

**What was the result?**

If you press next the dimmer will work in Homey. Adding the dimmer to a flow will work normal.
The only thing that isn't working is asking Homey to switch on the lights.

**What did you expect as result?**

Be able to choose what type of dimmer device is added.

Adding a 'normal' socket is still working as before, you are able to select the device.

**Comment by soler2000** [comment]
I think something has changed in the virtualDeviceClass I am see this across other apps.

**Comment by Dennishacq** [comment]
@rikpost this issue should be fixed in KaKu v1.0.16

**Comment by rikpost** [comment]
@Dennishacq I've tried it tonight and it's working as before, thanks!
