### ISSUE TITLE
Insights missing presence log

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#365]
**What is your Homey version (Settings → System)?**
0.8.24

**What did you try to achieve?**
View presence Insights

*Please include detailed steps how we can reproduce the issue*
I created a flows with "mark as home/away".

**What was the result?**
There is no log in insights.

**What did you expect as result?**
Graph of presence.

**Any other remarks**
Querying `/api/manager/insights/log` returns only presence log and left sidebar is empty. There is some data in log (fetched using api).

**Comment by WeeJeWel** [comment]
Homey v.0.8.25 supports boolean logs
