### ISSUE TITLE
voice brian download gives checksum no match error 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#366]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
download voice brian after reset and wiping homey . russel downloads perfect 
*Please include detailed steps how we can reproduce the issue*
see above : in 0.8.24 do factory reset with wiping of settings. 

**What was the result?**
no voice in homey on command he says "i havent downloaed my voice yet'
...

**What did you expect as result?**
a downloaded voice and talking homey
...

**Any other remarks**
it is the default voice and i am used to it, i dont like russel so much
...

**Comment by WeeJeWel** [comment]
Fixed in 0.8.25
