### ISSUE TITLE
Homey has the wrong time and we cannot adjust this in the settings.

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#367]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
Try to get the right time
*Please include detailed steps how we can reproduce the issue*
There is no posibility to enter the right time in homey.

**What was the result?**
Wrong time and the sunset End trigger was not send.
...

**What did you expect as result?**
That the trigger of the sunset is done on the right time.
...

**Any other remarks**

...

**Comment by Fire69** [comment]
So what time do you have and what should it be?
eg.  you have 10pm and it should be 11pm? or you have 10pm and it should be 6.25pm?

**Comment by bvdbos** [comment]
Also: is the time off or is the sunset trigger off?

**Comment by Dijker** [comment]
You mention multiple problems, 
Sunset /sunrise triggers don't work : #182  so no need to look at that it is a duplicate. 
Time and Timezone are discussed in #169, pay attention to the time displayed in Z (GMT?)
You can't set time directly, that's correct  afaik
I guess timezone is set according to location, but unfortunate that is broken also in .24 see: #348 

So be concrete and tell us what is new in you question?

**Comment by CootNL** [comment]
Hello all,
Yes I have a problem that the Sunset trigger is not working.
Yes the time zone is ending with Z, so that must be correct.
Yes I cannot set the right location of I cannot check the location.

**Comment by WeeJeWel** [comment]
Could you paste your 'Stuff for geeks'?

**Comment by CootNL** [comment]
arch	arm
cpus	[{"model":"ARMv7 Processor rev 10 (v7l)","speed":792,"times":{"user":239859100,"nice":0,"sys":285989700,"idle":1079555800,"irq":67900}}]
date	2016-03-22T21:36:15.248Z
devmode	false
freemem	40390656
hostname	Thuis
loadavg	[1.21435546875,1.27783203125,1.20654296875]
network	{"lo":[{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true},{"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","scopeid":0,"internal":true}],"wlan0":[{"address":"192.168.1.100","netmask":"255.255.255.0","family":"IPv4","mac":"6c:ad:f8:05:10:05","internal":false},{"address":"fe80::6ead:f8ff:fe05:1005","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"6c:ad:f8:05:10:05","scopeid":3,"internal":false}]}
platform	linux
timezone	Europe/Amsterdam
totalmem	513794048
uptime	185567
version	0.8.24

**Comment by CootNL** [comment]
I restarted homey and now the time looks oke to me.

**Comment by bvdbos** [comment]
It looked ok in your previous comment, Zulu-time (The Z on the end) is one hour off due to the timezone. What is it now?

**Comment by bvdbos** [comment]
The system-menu has a date_human now with the local time. This can be closed?
