### ISSUE TITLE
homey crashed once in the two days.

### ISSUE THREAD

**Issue by kingdong78** [athombv/homey#369]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
nothing
*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

after update 0.8.24 homey sometimes freezes interval is about once in the two days.
i noticed it when i saw that the ledring doesn't spin any more
i also can't connect with homey
after unplugging de power cord and power it up it restarts and he works again

...

**Comment by WeeJeWel** [comment]
Can you ping Homey when that happens?

**Comment by kingdong78** [comment]
Hi emile

i can ping homey.
but on the my homey webpage is says its offline

**Comment by kingdong78** [comment]
by means of pinging it is reachable

**Comment by bvdbos** [comment]
If Homey responds to pings, some processes still work. Do other processes (Kaku, Zwave, Timer etc) still work?

**Comment by MdeRhoter** [comment]
I have the same issue (I'm not using any Zwave devices) - Homey does not respond to ping, but Kaku still works, LED ring still does it's normal routine. Happens on average once every two days, since 0.8.24. If I can help with logs or scenarios, let me know!

**Comment by moekdegroot** [comment]
Same here, after a day or 2 unable to ping/reach homey's webpage.
However my flow containing a fibaro motion sensors that triggers a kaku light is still operational.

**Comment by bvdbos** [comment]
Perhaps it´s an specific app which causes the crashing of wifi. What apps do you have installed?

**Comment by moekdegroot** [comment]
Good idea, let's compare. 
iKettle (works)
Email (also broken)
Klikaanklikuit (works)
Pushover (works)
Harmony Hub (can't check right now if it works)
Hue (broke today after upgrading to 0.9.12)
Better Logic (works)
Wikipedia (voice is disabled but guess it works)
Buienradar (works)
MiLight (works)
Http request (works)
Netatmo (works)
Chromecast (haven't used yet)
YouLess (haven't used yet)
Wake on Lan (haven't used yet)
IFTTT (works)
Ical to voice (works)
Itunes (works)

**Comment by MdeRhoter** [comment]
KlikAanKlikUit
Logitech Harmony Hub
Philips Hue
Better Logic
HTTP Request Flow Charts
IFTTT
iCalendar To Voice

date	2016-03-29T20:48:53.844Z
devmode	false
freemem	21028864
loadavg	[1.11865234375,1.2841796875,1.1533203125]
uptime	129837
version	0.8.24

It's been fine for two days now - it could be a coincidence, but the freemem seems higher than usual (it normally levels out at 6-8 MB - is that normal?)

**Comment by MdeRhoter** [comment]
Ah, unreachable again.

**Comment by MdeRhoter** [comment]
And again. Grr.

**Comment by bvdbos** [comment]
@MdeRhoter : From the apps you installed, I think Kaku is not the problem as a lot of people have this app and the problem you're describing doesn't occur a lot. Also Kaku didn't crash you told above. Then it could be one of the other apps, @moekdegroot has all these apps too. For him Zwave (fibaro) and Kaku keep working. **Q1 : Did one of the other apps crash at the same time?** You stated you have the same problem as @kingdong78 but your problem is different as pinging doesn't work for you... **Q2 : On your wifi-router, do you still see the ip-adress of Homey as on-line?**

**Comment by MdeRhoter** [comment]
As far as I can tell the apps still run, I can still control my Kaku devices - without IR support I can't do much with the Logitech Harmony, so I can't test that without clicking on the action flow.

Next time it hangs I'll log into the access point and see if it still lists Homey as an active connection, good point!

**Comment by bvdbos** [comment]
Going to be a pain in the ass but I think you know what will be my next question(s) : could you disable the apps one by one and see if it still happens? Perhaps it's one of the flows?

**Comment by MdeRhoter** [comment]
Sure - any particular order you want or at random?

**Comment by bvdbos** [comment]
No, the order doesn't matter. As long as you can reproduce the conditions.
Perhaps, to make testing not too invasive, start with turning off some
flows or some apps you don't use for now...

**Comment by MdeRhoter** [comment]
Okay - I've disabled the Harmony app, since that was the last addition. If Homey stays up for three days I'll consider it a big improvement.

**Comment by Dijker** [comment]
My Homey died today also, (as already done a couple of times last weeks) receiving KAKU was working with response to the LED ring.
No Ping reply. (and I didn't install the Harmony App afaik.)
I Powercycled but it didn't come up.
So today is different :(
I Powercycled again and after approx 2m30sec  orange ring it turns RED for approx. 30 seconds. then it switches off. 
Tried a couple of times, (more power-off time)  
I feel I have a Brick and will first try the soft reset.

**Comment by MdeRhoter** [comment]
Best of luck with that! Let us know how it goes :)

**Comment by Dijker** [comment]
Thanks, 
was not realy bricked... 
See #386

**Comment by MdeRhoter** [comment]
Still running, with 4MB of freemem - is that okay?

arch	arm
cpus	[{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":46376600,"nice":0,"sys":72750300,"idle":542343300,"irq":51100}}]
date	2016-03-31T14:59:23.455Z
devmode	false
freemem	4677632
hostname	Homey
loadavg	[1.21826171875,1.099609375,1.0634765625]
totalmem	513794048
uptime	79889
version	0.8.24

**Comment by WeeJeWel** [comment]
@MdeRhoter That's definitely not OK. There's a memory leak which causes the freezes.

What are your apps doing for memory usage?

**Comment by MdeRhoter** [comment]
This:

Kaku: 		26MB
Hue:			79MB
BetterLogic:	33MB
com.internet:	32MB
IFTTT:		31MB
iCAL2Voice:	73MB

**Comment by WeeJeWel** [comment]
That makes sense then :) Homey 0.8.26 fixes an issue where apps would not decrease their memory usage over time. Please report back how that goes when it's out!

**Comment by Dijker** [comment]
@WeeJeWel 
Nice if you already know what the problem is, I hope it is fixed!
I already thought  about if it was possible for you (Athom) to create some " Developer/Debug" FlowCards 
(Maybe not for the endusers but only enabled if... fe make show stuff for Developers a Checkbox) .

Action Card:
- DoDumpLocal2SendLater
- SendLocalDump
- RestartHomey
and Triggers: 
- LowOnFreeMemory
- NoWiFiGateWayOrInternet

For the next time we experience hangs etc. we can create a flow (If NFC Card #X1 Then: DoDumpLocal2SendLater, RestartHomey(Delay15Sec.))

With the triggers they can even do their job automatically.
can we expect .26 soon?

**Comment by MdeRhoter** [comment]
Those debug options would help I guess! Maybe make those available as an app?

Good to hear memory management has been tweaked in .26.

**Comment by athomey** [comment]
Some extra information: I had Homey hang after 2 days. The LED ring also hangs. I have ONLY the Hue app installed and only ONE active flow. Every 6 seconds it fires, switches on 2 bulbs on brightness 5% and green, and after 3 seconds switch them off again. So ONLY running that, disabled microphone and all, Homey hangs, LED ring hangs. Haven't tried ping. Will try that later.

**Comment by MdeRhoter** [comment]
Could you keep an eye on the amount of freemem your Homey has? See above for why :o)

**Comment by MdeRhoter** [comment]
Memory usage seems to be better with 0.8.27:

arch	arm
cloud_connected	true
cpus	[{"model":"ARMv7 Processor rev 10 (v7l)","speed":792,"times":{"user":59016300,"nice":0,"sys":43247800,"idle":297764600,"irq":7900}}]
date	2016-04-02T09:22:50.944Z
devmode	false
freemem	17764352
homey_version	0.8.27
hostname	Homey
loadavg	[0.52685546875,0.5439453125,0.56494140625]
node_version	v0.12.9
platform	linux
timezone	Europe/Amsterdam
totalmem	513794048
uptime	46364

**Comment by bvdbos** [comment]
The memory-problems should be solved with 0.8.32 ?
