### ISSUE TITLE
Weird multiline message that Athom account already exists

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#37]
When I try to create a new Athom account during setup, the message that the account already exists is displayed over several lines. Each line a Character proceeded by a number.

**Comment by newmedia** [comment]
same problem here:

![screen shot 2016-02-10 at 15 34 04](https://cloud.githubusercontent.com/assets/731226/12951911/d3b6cb2e-d014-11e5-8958-c9eda71b9bcf.png)

**Comment by WeeJeWel** [comment]
Fixed in the newest version (will be deployed any time)
