### ISSUE TITLE
Homey locks up when trying to reboot

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#371]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Reboot Homey from the Settings menu

*Please include detailed steps how we can reproduce the issue*

Click the Reboot button :-)

**What was the result?**

Homey doesn't reboot, web-interface not working anymore.  No response to ping.

**What did you expect as result?**

Normal reboot :-)

**Any other remarks**

I put a LivingWhites plug in between to 'solve' the problem.

**Comment by peaoo** [comment]
Same here.
LED Ring Rainbow stuck and stops moving.

**Comment by peaoo** [comment]
After .27 rebooting works for me again. Thanks!
