### ISSUE TITLE
"Node id not in network", but Homey doesn't mention WHAT node-Id (z-wave)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#373]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Find out what broken-link device I should delete by reading the information available by Homey. I have multiple "New Z-Wave devices" in Homey, but it only shows the first letters, so I cannot see WHICH New Z-Wave device.

**What was the result?**

There is almost no available information in Homey. You cannot open the details, nor the settings, cannot even rename the device, cause it is unreachable.

**What did you expect as result?**

That in addition to the "Node id not in network", Homey would provide extra information, just like Fibaro HC2 and Vera Edge, showing WHAT node we are talking about.

**Any other remarks**

![image](https://cloud.githubusercontent.com/assets/16608801/14076636/d79baafe-f4e3-11e5-9608-25a8be662894.png)

**Comment by ocatie** [comment]
This means this device is a ghost device. The node id mapped to the device does not exist in the network. You can delete the device using the X in the right corner.

**Comment by ocatie** [comment]
I've added the node id to the error.

**Comment by athomey** [comment]
Nice, that helped. Little counter-intuitively that you DO find the node/device also in the zwave settings dropdown, but you can't delete it there.  :-)  Deleted it. Know it for next time. Thx!
