### ISSUE TITLE
Still "Unhandled error: Unknown device" in 0.8.24 when wanting to remove ghost-device (z-wave)

### ISSUE THREAD

**Issue by athomey** [athombv/homey#374]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Remove New Z-Wave device (7)

![image](https://cloud.githubusercontent.com/assets/16608801/14076744/fc6fb7c0-f4e4-11e5-8507-95e1eb7519de.png)

then

![image](https://cloud.githubusercontent.com/assets/16608801/14076750/0ea89042-f4e5-11e5-9b7b-c2fa9ae9d5ca.png)

**What was the result?**

I get an error:

![image](https://cloud.githubusercontent.com/assets/16608801/14076757/16624544-f4e5-11e5-9e8f-0abadffb96b2.png)

**What did you expect as result?**

The "Remove node" button to appear, so I can remove it.

**Any other remarks**

It seems like there is an orphan/ghost device hanging around in some DB, thus showing up as a z-wave devices, but not available for a refresh in some other list/DB in Homey. Something is not coded defensively it seems, and thus guaranteeing data-integrity in Homey.

**Comment by ocatie** [comment]
Is the device with node id 7 listed in the zone overview? Could you please reboot, wait 2 minutes after the rainbow starts spinning (to finish the z-wave booting), open the settings page after a few minutes and send a system log.

**Comment by athomey** [comment]
When I deleted with the X the other ghost device, this one disappeared too! See https://github.com/athombv/homey/issues/373  So case closed?  Still unintuitively and strange, but HEY, got my Homey cleaned-up now...

**Comment by ocatie** [comment]
The dropdown is generated by the Z-Wave devices in Homey and filled with node id's in the network for which no device is found (these are listed as "Unknown device"). This was a device that should have been deleted long time ago but wasn't due a bug. It should not be possible to have devices with non-existing node id's but when you do end up with one you can delete it from the zone overview.
