### ISSUE TITLE
Adding multiple Z-wave devices brings Homey to permanent error state "AddNode already running", "just a sec", " z-wave not ready", which rebooting solves [0.8.24]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#376]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Add 2 Fibaro wallplugs, before adding 15 Fibaro RGBW devices. First wallplug goes perfectly. Second fails.

**What was the result?**

Adding second wallplug shows "Just a sec" for minutes, so I close the window and try again. Then I get:

![image](https://cloud.githubusercontent.com/assets/16608801/14102816/271d3584-f59d-11e5-8282-f79d2b4d0a43.png)

Second wallplug shows error "Z-wave not ready yet".

![image](https://cloud.githubusercontent.com/assets/16608801/14102798/11a831cc-f59d-11e5-833d-4c7ac07c1827.png)

So I try again, and get:

![image](https://cloud.githubusercontent.com/assets/16608801/14102832/410c25c2-f59d-11e5-85a0-b54578a037bc.png)

addNode already running...

**What did you expect as result?**

That the second plug would also add correctly. Homey however gets in an errorcondition which it never comes out off. After 10 minutes or so I rebooted Homey to get it working again.

**Any other remarks**

Z-wave is still unusably unstable for me. I want to manually transfer ~70 devices from Vera/Fibaro HC2 to Homey, but for months now I get serious showstoppers. Every time I wait a few weeks and versions before I try again, but it doesn't really seem to get to a stable point. Is there anything I can do to help you progress in development for Z-wave on Homey?

**Comment by ocatie** [comment]
Could you please reproduce the error, send the log and past the code here?

I've made some changes and fixes to the pairing wizard in 0.8.25 so possibly this is already fixed. Could you try to reproduce it on 0.8.25 when available and also send the log.

**Comment by athomey** [comment]
Do you have instructions on "sending the log", that would be useful. :-)  Thx!

**Comment by ocatie** [comment]
Settings -> System -> Send Log
