### ISSUE TITLE
Homey can not find my Plugwise devices

### ISSUE THREAD

**Issue by Rovvie** [athombv/homey#377]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
By finding my devices i tried to find all my Plugwise devices(11 plugs) . I used the Stretch search method.

*Please include detailed steps how we can reproduce the issue*
Just letting Homey find my devices.

**What was the result?**
I tried it several times. Most of the times it just found 1 devices, always the same. Sometimes no device at all was found. 
When found I could connect and use this device. But after some time (days), I got the message from Homey that it couldn't find it and reported that there was no Anna connected.
...

**What did you expect as result?**

...

**Any other remarks**
I have an XML list of my devices from the Stretch.
...

**Comment by freekwebdesign** [comment]
Which version of the Plugwise app did you use?
In the newest version (v1.0.6) the pairing functionality is improved.

Can you send the XML list to freek@athom.nl?

**Comment by freekwebdesign** [comment]
Thanks for sending the XML file.
Using this file I was able to detect and solve the problem.
The newest version (v1.0.7) is released now.
