### ISSUE TITLE
Various stability issues with z-wave in Homey 0.8.24 with semi-reproduction

### ISSUE THREAD

**Issue by athomey** [athombv/homey#381]
**What is your Homey version (Settings → System)?**

0.8.24

**Reproduction**

Add two Fibaro wall-plugs, when Homey is 5 meters away from the plugs, and has one cheap wooden door between them and Homey. Everything goes well. Play around with the two plug's until you get one unreachable. The other one stays reachable.

![image](https://cloud.githubusercontent.com/assets/16608801/14104396/4d90a22a-f5a5-11e5-84a2-678dda73eced.png)

Unplug and replug the wallplug, but within 1 meter from Homey, so it can be reached. Now it didn't get reached, not even when waiting 10+ minutes. How long does it normally take before Homey re-reaches/retries to reach devices?

Now z-wave sames to become totally unstable. In the drop-down from "Failed" of the z-wave settings, it keeps saying "Loading id's":

![image](https://cloud.githubusercontent.com/assets/16608801/14104439/81cc8e8c-f5a5-11e5-9671-8a42fba42706.png)

Now very soon all z-wave devices become unreachable:

They show as reachable at "Devices" of Homey, but when opening the card, you cannot do anything and they stay grayed out:

![image](https://cloud.githubusercontent.com/assets/16608801/14104464/a79ffa18-f5a5-11e5-9930-d5b796b4773c.png)

Now I restart the z-wave chip:

![image](https://cloud.githubusercontent.com/assets/16608801/14104477/b66e23d0-f5a5-11e5-88f7-7462a95c7d4e.png)

After that the drop-down does work again:

![image](https://cloud.githubusercontent.com/assets/16608801/14104494/c28db2a2-f5a5-11e5-9af7-e555b1408573.png)

But all the devices show broken link in Homey, and it doesn't auto-correct:

![image](https://cloud.githubusercontent.com/assets/16608801/14104443/8cdebd2c-f5a5-11e5-8f69-05ec95a4868a.png)

Now I reboot whole of Homey, and everything works again.

**What was the result?**

Instability of z-wave usage within Homey, which doesn't auto-correct and also shows much less feedback (read: NO feedback) to the user (me), when compared to Fibaro HC2 and Vera Edge, which both show a LOT of feedback, which really helps and even when there is a problem, doesn't cause me/the user to get really agitated/angry with the device.

**What did you expect as result?**

The opposite of the result. ;-)

**Extra information**

_**It seems like if you have one or more z-wave devices which are not 100% reachable or within range, this causes Homey to became instable with usage of ALL z-wave devices.**_

**Comment by TedTolboom** [comment]
Same issue as @athomey here... at SW v0.8.24

Z-wave hardware connected: 
3x Powernode-6 (~ 3-4 meters distance from Homey)
1x Fibaro motion sensor (~2 meters distance from Homey)

Z-wave becomes unstable (loosing connection) about 2-3 times per day.
- Lamps / devices not switching on or off
- Insights not updated, power consumption by Powernode and Luminance, Temp and motion by motion sensor

During the first restart of the Z-wave chip, Homey got in contact with on of the Powernodes (with commonly used lamps) and apperantly send the remaining queue of commands to the Powernode (switching on or off the lamps multiple times). Afterwards, the node selection list still showed "Loading Id's". 
Second restart of the Z-wave chip made the node selection available again.. Still no restart of Homey.

Now, on almost all main sub-nodes (e.g. 2.1 or 3.4) I'm able to get communication running again, showing power consumption and being able to switch again. Same for  the motion sensor.

On all the main-nodes of the Powernodes (e.g. 2, 3, 4) and 1 sub-node, I'm no longer able to open the switch / data window. It only shows the parameter window. 

In addition, one of the main-nodes is showing unable to connect:
<img width="906" alt="schermafbeelding 2016-03-31 om 21 31 11" src="https://cloud.githubusercontent.com/assets/17163431/14188336/fd7d70bc-f787-11e5-82f3-662ee1a4ccfe.png">

Log file: 07DF4845A4

After restarting Homey, all communication is restored and switch / data window on the main-nodes is available again:
<img width="1029" alt="schermafbeelding 2016-03-31 om 21 39 28" src="https://cloud.githubusercontent.com/assets/17163431/14188493/1c5fe09a-f789-11e5-83d5-3936333163b3.png">
