### ISSUE TITLE
Philips Hue Lightstrip Plus (the new lightstrip) shows as bulb instead of ledstrip

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#385]
**What is your Homey version (Settings → System)?**
0.8.24

Philips Hue Lightstrip Plus (the new lightstrip) shows as bulb instead of ledstrip.

The normal lightstrips (the old versions) show correct as a ledstrip. See picture:

<img width="176" alt="schermafbeelding 2016-03-29 om 22 12 20" src="https://cloud.githubusercontent.com/assets/17727803/14122319/90998734-f5fb-11e5-9778-adf2363845a7.png">

**Comment by WeeJeWel** [comment]
Fixed in nl.philips.hue@0.9.13
