### ISSUE TITLE
Humidity percentage not reported

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#387]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

I have an Everspring ST814 device which can report Temperature & Humidity.  Humidity is not reported.

**What was the result?**

I see a multi-channel device added, but the channel that seems to have humidity is 'empty', no reports coming in.  Temperature & Battery status are reported correctly. 

**What did you expect as result?**

Humidity reporting including cards so I can use them in flows

**Any other remarks**

In forum: https://forum.athom.com/discussion/1015/z-wave-everspring-st-814-temperature-humidity-sensor-humidity-not-reported/p1   ; it seems it is not specific to st-814 device

**Comment by ocatie** [comment]
Fixed in 0.8.28

**Comment by ralfvd** [comment]
Please re-open, at least for Everspring ST-814 it is not working yet.

Issue-log:  931D2AE2FD

Console out-put when opening the sub-device that should have humidity reported:

GET https://homey-static.athom.com/manager/webserver/assets/font/roboto/roboto.css ;
api.js:1 
GET https://NNN.homey.athom.com/api/device/7b7fe6ba-2292-4e96-8fac-6f0fc9ecf48c/?_=1460038344351 500 (Internal Server Error)
window.Homey.api	@	api.js:1
i.Homey.get	@	mobile.js:1
onHomeyReady	@	VM351 about:srcdoc:1
d.(anonymous function).onload	@	mobile.js:1

**Comment by ocatie** [comment]
I see the fixes isn't shipped with 0.8.28. Please try to re-add the device on 0.8.30. Sorry for the inconvenience.
