### ISSUE TITLE
State of devices is not remembered after reboot

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#388]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

I have 433 Mhz sockets (e.g. KaKu, Action). Some are turned on via Homey. After a reboot, Homey thinks the socket is off, while the socket is on. 

**What was the result?**

In 'devices', the device is shown as 'off'.  Flows that turn the device off, will still send an 'off' command, so flow-wise, it is not an issue

**What did you expect as result?**

When rebooting, remember the state of a device, so the Devices-screen shows the correct state of a device

**Any other remarks**

**Comment by Dennishacq** [comment]
Hi @ralfvd 
Thank you for submitting this issue.
I've already fixed this in the new KaKu app and i'll implement this in the other apps as well.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by ralfvd** [comment]
Tested with 0.9.1 and Action, device state not remember correctly;

On + Reboot  => Device state On ( OK)
Off + Reboot => Device state On ( Not OK )

**Comment by BasKiers** [comment]
Should be fixed as of v2.0.0 of the action app
