### ISSUE TITLE
Homey non-responsive on actions, slow webpage

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#389]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Flows and actions were not working any more.  The Homey webpage was almost completely unresponsive, I had to reload the pages many times to get a working page.

**What was the result?**

I had to reboot the Homey to get it working again. I lost my Internet connection for about 1 hour ; before the outage Homey worked fine, after that, it stopped responding to input and the webpages were loading not or very slowly.

**What did you expect as result?**

A functioning Homey during and after the Internet outage. 

**Any other remarks**

Logfile when it was slow: 4346F71A49.

I am not sure if the Homey unresponsiveness is related to the outage, but it was the only major event. I wasn't doing other activities with the Homey or other parts of the network.

**Comment by WeeJeWel** [comment]
@ocatie check the log

**Comment by ocatie** [comment]
@WeeJeWel capability onoff get called every 15 seconds.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
