### ISSUE TITLE
[Apps] Philips Hue: non-responsive when Internet is not working

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#390]
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Switch on a light while the Internet was down

**What was the result?**

Light didn't switch on

**What did you expect as result?**

Light switches on, even when Internet is down.  Local switches should work independently from the Internet.

**Any other remarks**

I guess this is due to using the meethue.com-api website, which resolves the local Bridge IP.  But this should be cached. 

I also have the idea that since a couple of versions, switching the Hue lights has an increased delay. Maybe this is related due to checking the local Bridge IP via a external website every time a light is switched  ( haven't investigated in the source code to verify )

**Comment by athomey** [comment]
I agree this should be cached. Internet should not be a prerequisit to Hue's working. This would be a showstopper for my clients, and also damaging to my own WAF. But I assume they'll fix it.

**Comment by ralfvd** [comment]
Not sure if it is related; but after Internet came back up, Philips Hue continued to be unresponsive. Upgrade to 0.8.27 didn't help, I had to uninstall the Hue app and re-install it ( and fixing all flows that contain a Hue action).

A couple of weeks ago when Internet dropped and Hue was unresponsive during the outage, Hue came back up after the network connection was restored.

**Comment by bvdbos** [comment]
Does this still happen with the latest HUE-app?

**Comment by bvdbos** [comment]
Again does this still happen with the latest app? Also, could you file this then in :
https://github.com/athombv/nl.philips.hue/issues

**Comment by WeeJeWel** [comment]
This should long be fixed by now :)
