### ISSUE TITLE
KAKU stops working in 0.8.27 after using Contact Alarm AMST-606

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#392]
**What is your Homey version (Settings → System)?**
Homey 0.8.27
KAKU 1.0.16

**What did you try to achieve?**
Test Contact alarm switch AMST-606

*Please include detailed steps how we can reproduce the issue*
Open the contact (door) switch.

**What was the result?**
KAKU isn't working anymore. Code Checker gives no responses anymore on different remotes. 

**What did you expect as result?**
Contact alarm working normal triggering two flows (open-door an close-door).

**Any other remarks**
Tested several times, rebooted several times. 
KAKU AMST-606 read once with Code Checker after reboot. (On or Off) then Codechecker stops. 
Could check other remote AYCT-102 more than once. 

![image](https://cloud.githubusercontent.com/assets/12412734/14217269/52d6b7ba-f84d-11e5-8622-a395f2287a57.png)
Removed Contact Switch device, could not pair again. 
(Switch/battery verified to work with Socked also paired and switching correct)

Send Log :
(Reboot, tested only the AMST-606)
6C7B981E80 On Checked once
D7C59452C8 On Checked once
EE55C4A316 Off & On checked both one or two times, then stops.
This device was working stable in 0.8.24

**Comment by Dijker** [comment]
Removed the Contact alarm AMST-606 and all other KAKU devices. 
Now after adding the AMST-606 the Contact alarm works again as normal.

Checking and adding the AYCT-102  also worked but the trigger cards for the AYCT-102  (fe If ON is pressed Channel 1 - Button 1) doesn't work anymore. 

That was working before the update and didn't work after the update to 0.8.27. 

Removed the AYCT-102, checked code and added the AYCT-102. (That worked.)
Re-created the Flow to Pulse Ring on Button press. This doesn't work anymore. (tested different buttons.)

**Comment by denniedegroot** [comment]
My AGD2-3500R remote also stopped working after updating to 0.8.27. The code checker works but the triggers don't do anything.

**Comment by MdeRhoter** [comment]
My AYCT-102 does not trigger any flows - it does get paired fine, in the pairing wizard all the buttons respond. I'm now triggering the flows using IR. With the LED ring off.

You win some, you lose some!

**Comment by TedTolboom** [comment]
My wallswitch also does not trigger a flow anymore (was working with 0.8.24).
Homey is able to send KAKU commands successfully and codechecker shows the right signal; only flow is not triggering

**Comment by MdeRhoter** [comment]
Yup, controlling dimmers and switches still works. So sending is fine, receiving not so much.

**Comment by Dijker** [comment]
although the AYCT-102 paired but flows never trigger, The APIR-2150 Motion Sensor works normal after pairing again. I have triggered a TestFlow multiple times with this Sensor to test RF433 is still working.

**Comment by Arjanvde** [comment]
My smartwares remote doesn't trigger any flows on 0.8.27 so i suppose it is related to 433mhz and not on KakU in particular.

**Comment by rikpost** [comment]
Same problem over here. APA2-2300R remote doesn't trigger flows.
Tried to remove and add the remote but still nothing.
When adding the remote the KaKu wizard is detecting the remote as it should

**Comment by TedTolboom** [comment]
Does anybody have a non 433mhz remote / wallswitch (like z-wave) to test if it is a generic triggering issue or specific to 433mhz?

**Comment by MdeRhoter** [comment]
I can trigger things fine with an IR remote, I have no other radio types.

**Comment by bvdbos** [comment]
My AMST606 doesn't trigger a flow. A time-flow does trigger a kaku-device. I added a non-existing kaku-soocket through a remote. I managed to trigger a flow with this socket (socket on) once but after that kaku stopped working, the flow wouldn't trigger, I couldn't add a new remote and I can't switch my lamps through the devices or through the android-app. LOG: CA811B71F1

**Comment by Dijker** [comment]
as I wrote in my second comment yesterday evening: 
my APIR-2150 Motion Sensor works and still triggers the testflows (now) with approx. 13 hours uptime on Homey.
So there are are (1) maybe different  stability problems on 433 and certain devices (Contact Alarm AMST-606) , (2) other devices that pair but don't trigger (10 button/4 channel remote AYCT-102) but (3) some other KAKU still work.

**Comment by Dennishacq** [comment]
This is a bug in the KaKu app. I found the cause of this bug but it's a bit of work to fix it. 
I will upload a fix asap.

**Comment by MdeRhoter** [comment]
Yay!

**Comment by MdeRhoter** [comment]
How's the fix coming along? My Homey just forgot all its variables so I can test whatever you want.

**Comment by antigreja** [comment]
@Dennishacq Have you been able to fix the bug or do you know hen it will be fixed? Using the KAKU-remote to trigger flows is used very much in my household.

**Comment by Dennishacq** [comment]
The update is being tested today so it shouldn't be long untill it's up :)

**Comment by Dennishacq** [comment]
Hi Guys, 
The new KaKu update is now available in the App store.
Unfortunately you'll have to re-pair your devices to get them working again.
Please let me know if you find any bugs :)

**Comment by TedTolboom** [comment]
Dennishacq,

Seems to be working!

Installed KaKu 1.1.0… deleted the wall switch, setup new wall switch and tested it… not working…
Rebooted Homey, deleted the wall switch again, setup new wall switch and tested it… working ok!

So after installation of KaKu 1.1.0… reboot Homey

**Comment by Dijker** [comment]
Thanks!, 
Did a reboot on forehand and almost every problem look lik it is solved ;-) 
al least everything with the new KAKU device I have work now. (Pairing etc. )
I will close this for now.
