### ISSUE TITLE
Preview voice can be played with an echo. 

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#397]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**

While i wanted to preview the selected voice i accidentally tapped the preview button twice and the voice preview started a second time without the first preview tryout was stopped. In this case an echo is hearable.

![schermafbeelding 2016-04-02 om 17 24 54](https://cloud.githubusercontent.com/assets/17526110/14227227/f6d69ca8-f8f8-11e5-8895-0ac564dc4d46.png)

Reproducing is easy, tap the preview button twice.

**What was the result?**

An ego being played.

**What did you expect as result?**

The first preview to be stopped and started all over again.

**Comment by jeroenvollenbrock** [comment]
This is intended behaviour
