### ISSUE TITLE
HUE Lux Lights don't show an icon.

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#398]
**What is your Homey version (Settings → System)?**

0.8.27 , HUE v.0.9.13

**What did you try to achieve?**

The icon for the Philips HUE Lux lights is missing, no icon is being displayed. In earlier versions this was not a problem. In my case i have 2 LUX lights without any icons.

![schermafbeelding 2016-04-02 om 17 25 58](https://cloud.githubusercontent.com/assets/17526110/14227249/794e4154-f8f9-11e5-91ec-13f7db4ebb21.png)

**What did you expect as result?**

Correct icon to be displayed.

**Comment by WeeJeWel** [comment]
Please remove and add your devices. It's because of a rewrite, and I didn't want to support legacy code while still unstable :-)

**Comment by Arjanvde** [comment]
Reinstalling the app fixed the issue, not really happy to recreate all flow's again. Please consider to give users the opportunity to update apps manually (same with firmware versions). For now it are "only" 20 flows, but i can imagine this is a bigger issue for some other people.
