### ISSUE TITLE
Philips HUE uncontrollable from zones and devices if switched on

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#399]
**What is your Homey version (Settings → System)?**

0.8.27 , HUE v.0.9.13

**What did you try to achieve?**

I was wondering whether polling had been worked so far with the Philips HUE lights but as far as i can see this isn't working really smoothly.

1. As soon as my HUE lights are switched on (third party app or with Homey) i can't control the lights anymore from the Zones and Devices screen, not even switching them off one by one. In addition to this, polling doesn't seem to work correctly as none of the colors in which the Hue lights which where switched on are displayed in the overview screen. 

I have 3 sets of HUE lightstrips , 2 LUX lights and a HUE Bloom, on all these devices polling doesn't seem to work! On my FLS PP IP (third party Zigbee Light Link) polling works. Does this mean that these official Philips devices are not supported, if so, no problem but please mention this in the app!

In this case the light has been switched on, but the status isn't updated nor can i turn of this specific light since it seems to be blocked.

![schermafbeelding 2016-04-02 om 17 26 57](https://cloud.githubusercontent.com/assets/17526110/14227400/ee46cc26-f8fc-11e5-9ee4-eb001244878b.png)

On my FLS PP IP polling seems to work, i can even switch the lights on/off so polling seems to work correctly.

![schermafbeelding 2016-04-02 om 17 27 18](https://cloud.githubusercontent.com/assets/17526110/14227412/36ea3346-f8fd-11e5-927e-417e2affc639.png)

**What did you expect as result?**

1. To be able control all the Philips HUE lights form the Zones and Devices screen. Switching an Individual light of is not possible at the moment, you have to switch them on individually!
2. That the right colors are displayed if the HUE lights are switched on or off.

**Comment by ralfvd** [comment]
I have the E27 lightbulbs (coloured and white ones) and polling works on both types. I did a uninstall and re-install of the HUE app after upgrade to 0.8.27 (due to some other problems I had with the app for a long time).

**Comment by Refl0w** [comment]
I have 3 coloured E27 bulbs, 4 E27 White bulbs and 1 light strip and my Homey is on .27 but everything works fine. Didn't reinstalled the app. Can control them in zone & devices and on speech trigger with a flow.

**Comment by Arjanvde** [comment]
@Refl0w Once the lights are switched on through a flow/third party app, are you able to switch them on/off, Change the colour or brightness through the Zones and Devices screen?

**Comment by WeeJeWel** [comment]
It's a known issue that the mobile card doesn't show the correct color on opening, that'll be fixed in a newer Homey version.

**Comment by Arjanvde** [comment]
@WeeJeWel I'm not able to make any changes to the lights via the Zones and Devices screen once the lights are switched on, so i have the feeling that polling doesn't work/blocks communication. Will revert tonight once I've reinstalled the app if the problem has been solved.

**Comment by Arjanvde** [comment]
Reinstalling the app fixed the polling issue. If it's known that the colour when opening the card could be wrong and will be fixed, I will close this issue.
