### ISSUE TITLE
Fibaro Motion Sensor FGMS-001 with firmware version V3.2 not possible to include!

### ISSUE THREAD

**Issue by WernerHel** [athombv/homey#400]
**What is your Homey version (Settings → System)?**

0.8.27 (but also tested with 0.8.24 and earlier)

**What did you try to achieve?**

Adding the Fibaro Motion Sensor FGMS-001 with firmware V3.2 is not possible.
![screen shot 2016-04-02 at 09 11 43](https://cloud.githubusercontent.com/assets/17176360/14228397/e4730ba8-f913-11e5-901a-5201fb63c97c.png)
![screen shot 2016-04-02 at 09 10 22](https://cloud.githubusercontent.com/assets/17176360/14228396/e4730518-f913-11e5-9782-5ec57010aaf5.png)
![screen shot 2016-04-02 at 09 11 17](https://cloud.githubusercontent.com/assets/17176360/14228398/e4736698-f913-11e5-8831-3e7b54778eea.png)

**What was the result?**
Interviewing device always failes. 
...

**What did you expect as result?**
working sensor ;-)
...

**Any other remarks**
Older versions seems so succeed, ask @Wurzel21.  He has 2 different firmware versions. V2.7 is working, but the V3.2 not.
...

**Comment by ocatie** [comment]
The interview went ok according to the log, but then suddenly stops. Looking into it.

**Comment by WernerHel** [comment]
Older versions are working but V3.2 not.  I only have the V3.2 version. (2x). But Wurzel21 has both. The V2.7 is working, but the V3.2 not.

**Comment by ocatie** [comment]
Please try again on 0.8.28. We've added more logging to identify the issue.

**Comment by WernerHel** [comment]
![screen shot 2016-04-06 at 19 26 38](https://cloud.githubusercontent.com/assets/17176360/14326311/a396588e-fc2d-11e5-82ba-e3ba6db4a66f.png)
tested with 0.8.29. the same result.

**Comment by ocatie** [comment]
Please try again on 0.8.30

**Comment by ocatie** [comment]
I had to temporary disabled the notification command class because of a bug so motion won't register yet. You should be able to pair it no problem.

**Comment by daneedk** [comment]
@ocatie is the disabling of the notification command class specific to this device, or to others as well? (like the Aeotec MultiSensor 6)

**Comment by WernerHel** [comment]
@ocatie Can I already test? Or with firmware 0.8.30?

**Comment by ocatie** [comment]
It's not specific for this device. But this device doesn't use the notification command class for movement reporting.

You'll have to wait for 0.8.30

**Comment by ocatie** [comment]
Notification command class is be re-enabled on the release after 0.8.30. Here the V3.2 motion sensor works great!

**Comment by WernerHel** [comment]
Still not working on 0.8.30 ;-(
![screen shot 2016-04-15 at 21 56 59](https://cloud.githubusercontent.com/assets/17176360/14573395/1cf8b8f6-0355-11e6-8774-fea6382d4e08.png)
![screen shot 2016-04-15 at 21 56 20](https://cloud.githubusercontent.com/assets/17176360/14573396/1cfafd00-0355-11e6-93e3-9106eb1df22f.png)

**Comment by WernerHel** [comment]
@ocatie Do you really have the sensor with V3.2 firmware? 
What am I doing wrong?

**Comment by WernerHel** [comment]
Yes, tried it again and succeed! Place the sensor next to homey when adding! ;-)

**Comment by WernerHel** [comment]
So now the sensor can be added, but the Generic alarm sensor is alway's on. ;-(

**Comment by ocatie** [comment]
I'll enable the notification command class in 0.8.30. Not all get functions are implemented but the motion sensor works.

**Comment by ruudonline** [comment]
I just received my Homey and was not able to pair my Fibaro Motion Sensor Gen5 with the .29 upgrading to .30 solved the issue although I can only see the following triggers: temp change, light change and battery change. Motion is not present, but maybe I am doing something wrong?

**Comment by WernerHel** [comment]
The generic Alarm is motion!

**Comment by WernerHel** [comment]
The sensor is working now. I had some problem's with the generic alarm, that it was alway's on. After adding 1 to group 1 to 5.  (only 1.4 and 5 where remembered) The motion was also working.
