### ISSUE TITLE
array properties get lost in communication to front-end

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#402]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**

Communicate information from the driver (back-end) to the pairing screen (front-end).
_driver_:
```
var show = [10];
show.door = { name: 'door', val: 'open' };
show.window = { name: 'window', val: 'closed' };
socket.emit('download', show);

```
_paring html/javascript_:
```
Homey.on('download', function(data) {
   console.log(data);
   console.log(data.door);
   console.log(data.window);
}
```

**What was the result?**

[10]
undefined
undefined

**What did you expect as result?**

[10]
{ name: 'door', val: 'open' }
{ name: 'window', val: 'closed' }

**Any other remarks**

Nope.

**Comment by WeeJeWel** [comment]
Only valid JSON JavaScript objects can be transfered from a back-end to a front-end. This will not be fixed, as it conflicts with the web standards.

**Comment by nlrb** [comment]
Thanks, can understand the statement. However, it would be good to add this to the documentation, as it might not be obvious to developers that this translation is going on behind the scenes.

**Comment by matjaz** [comment]
`JSON.stringify(data)` is what gets send to FE.
You should send an object with three properties (show, door, window).

**Comment by WeeJeWel** [comment]
Thanks, will add it to the docs.
