### ISSUE TITLE
Z-Wave issues after .27 (Z-Wave not ready yet / no Data-feed)

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#403]
**What is your Homey version (Settings → System)?**

.27

**What did you try to achieve?**

I don't know how this error exactly occured. It might be right after the update to .27.

**What was the result?**

None of my Z-Wave sensors (fibaro multisensor) are showing their data, its only the Icons of "Generic Alarm", "Lumiance" and "Temperature" visible but with now data under the Icon. My Danalock is also displaying as connected but does not react. The same is with my Danfoss LC-13 thermostats: no data and no reaction on commands. And it displayed the E5 error, which stands for "no communication with the hub is possible"

To fix this I removed a sensor (removing worked as expected) but when I tried to add it a "Error: Z-Wave not ready yet" popped. I waited 10 minutes , rebooted, restarted the z-wave chip and did a recovery (whithout data wipe) and it was always the same result.

**What did you expect as result?**

Working Z-Wave

**Any other remarks**

Log-Code: 
5F7695621A

**Comment by peaoo** [comment]
I did a full recovery (including wipe) now everything works. But still no idea what the problem was.

**Comment by ocatie** [comment]
Did you try a power cycle before full recovery?

**Comment by peaoo** [comment]
Yes, had homey off the cable for 5 minutes.

**Comment by ocatie** [comment]
Did you have an aeotec multisensor 6 added to Homey?

**Comment by peaoo** [comment]
No only 3 fibaro motion Sensors , 3 danfoss thermostats auf a danalock. All
of them not responding, but removeable.
And as soon as i clicked on devices, add new zwave the error occoured.

Taco <notifications@github.com> schrieb am Mo., 4. Apr. 2016, 17:00:

**Comment by rlijkendijk86** [comment]
I also notice that I have to "Restart"  the z-wave interface all the time because it stops working. No errors to be seen, just Homey not receiving / sending any data. Then when I restart the z-wave Homey starts sending commands (to my roller shutters for example).

**Comment by ocatie** [comment]
@rlijkendijk86 Could you define "stops working"? Does your device in the zone overview becomes unavailable with an error? Have you tried selecting the device in the dropdown and using the Refresh Node button?
