### ISSUE TITLE
TX data, should be an array of odd length

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#404]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**
send 433

*Please include detailed steps how we can reproduce the issue*
```
  var data = [0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1]
  console.log('send', data.length, data)
  var frame = new Buffer(data)
  signal.tx(frame, function(err, result) {
    console.log('GT9000 tx:', err, result)
  })
```

**What was the result?**
Error: Invalid TX data, should be an array of odd length

**Any other remarks**
Signal object is one from https://forum.athom.com/discussion/comment/15461/#Comment_15461

**Comment by ReinierH** [comment]
You have to add your last eof interval to the 'interval' field. The signal level is toggled on each interval starting with a high level interval. An even array of intervals + the 'interval field' which is added later on results in a odd array of time-intervals. This means the the signal ends high which causes the carrier to stay active the rest of the time.

**Comment by matjaz** [comment]
Not sure I understand this. Can you please post signal and `signal.tx()` which would send above `data`.

**Comment by ReinierH** [comment]
i will. Can you provide me the signal-definition you are using?

**Comment by matjaz** [comment]
forum https://forum.athom.com/discussion/comment/15461/#Comment_15461
code https://github.com/matjaz/homey-quigg-gt9000

thank you

**Comment by ReinierH** [comment]
`    signal = new Homey.wireless('433').Signal({   
        sof: [],
        eof: [3000],
        words: [
            [400, 1100], // 0
            [1100, 400]  // 1
        ],
        interval: 20000,
        repetitions: 4,
        sensitivity: 0.9,
        minimalLength: 24,
        maximalLength: 24
    }) `

I removed the last interval from the eof and added it to the "interval" attribute. When a signal is converted to time-intervals it will consists out of a even number of intervals. Because the signal state (high/low) is toggled on every interval it is important that the signal ends with a "low-state" interval. Using a even number of time-interval prevents the last interval from being a high-state one.

**Comment by matjaz** [comment]
Thank you!
I've managed to get working sending signal. Now just need to decode it :)
