### ISSUE TITLE
Can't trigger actions with Smartwares Remote 

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#405]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**

Since 0.8.27 i can't use a Smartwares Remote anymore to trigger any actions given in Flows. Repairing the remote did not made a difference.

**What was the result?**

No flows were triggered by the action if the "on button" is pressed . Removing the previous remote removed all data in the flows in which the previous remote was used :-(.

**What did you expect as result?**

That i could trigger an action with a simple remote, that was the main purpose for buying Homey. This is really a showstopper, this worked since day 1.

Not a duplicate of #392 according to @Dennishacq .

**Comment by bvdbos** [comment]
It really looks like a dupe of #392 :-) see also:
https://forum.athom.com/discussion/comment/15554/#Comment_15554

**Comment by Arjanvde** [comment]
@bvdbos, @Dennishacq mentions that #392 is caused by a bug in the KaKu app, see his reaction on 20:27.

**Comment by Dennishacq** [comment]
@Arjanvde The smartwares app contains the same bug as the KaKu app, i'll fix it in the Smartwares app later this week.

**Comment by Arjanvde** [comment]
Okidoki, i will wait patiently. 

Please do also take a look at #265 when updating the app.

Thanks!

**Comment by Arjanvde** [comment]
Fixed! Thanks.
