### ISSUE TITLE
Built-In "Set Temperature"-Command does not work

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#406]
**What is your Homey version (Settings → System)?**

.29
**What did you try to achieve?**
I tried to set the temperature via my voice to 15 degrees.

**What was the result?**
No reaction from Homey
Through /speech-input I saw that the command was recognized as "fifteen" and not as integer.
I tried it as integer through the /speech-input and it worked.

**What did you expect as result?**
Converting the spoken fifteen to an integer

**Any other remarks**

https://youtu.be/qSIp2ns42lA

**Comment by WeeJeWel** [comment]
That actually happens server-side. When typing speech (which is mainly used for debugging), type integers, not names of integers.

**Comment by peaoo** [comment]
I used the Speech site only for debugging, because my Spoken Commands
haven't had any impact. There I saw that the commands not triggered because
it was no integer.

Emile Nijssen <notifications@github.com> schrieb am Di., 5. Apr. 2016,
20:22:

**Comment by peaoo** [comment]
It seems that there is a problem on the server-side, because it did not convert my spoken number into an integer, instead it showed as "fifteen".

**Comment by peaoo** [comment]
Here a short clip to clarify the problem

https://youtu.be/qSIp2ns42lA

Sorry that my issue description was misunderstandable.

**Comment by peaoo** [comment]
I just reupdated the issue description, because this issue still exsists.

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by peaoo** [comment]
Perfect! Works like a charm! Thanks!
