### ISSUE TITLE
Built-In "cold/warm"-command has problems with numbers like X,666...

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#407]
.27

x.x.x

**What did you try to achieve?**

Triggered the built-in command "warm" and get homey saying numbers for a few seconds.

https://youtu.be/NNZdrGmXOnQ

**What was the result?**

...

**What did you expect as result?**

Homey rounding up or down to shorten the digit.

**Any other remarks**

...

**Comment by Tweake** [comment]
Thanks for reporting, the issue has been fixed and should no longer occur as of version 0.8.33
