### ISSUE TITLE
[Suggestion] flow conditions: execute in order

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#408]
**What is your Homey version (Settings → System)?**

0.8.27

**What did you try to achieve?**

<img width="989" alt="multiconditions" src="https://cloud.githubusercontent.com/assets/17727803/14287726/34245ca0-fb54-11e5-8214-9292606fe7a5.png">

In the column 'and', I use 3 different conditions:
1- If the time is later than 15:00
2- If boolean 'askformusic' is true
3- Ask for confirmation

It would be much more useful, if these were executed in order (at least for the confirmation card). And if any of them is false, Homey should know not to continue.
This way, I can make Homey ask for this only once a day.

However, even though askformusic is not true right now, Homey still asks me for confirmation. This is kinda annoying, because Homey will not / should not continue even if I reply with 'yes'.

**Comment by WeeJeWel** [comment]
Great suggestion!

**Comment by peaoo** [comment]
I like this idea! It would be nice if you could make the flow cards movable once you placed them. So its easier to change the order.

@jordenc : You could use Homeys built-in "Flow"-Category Cards to get your flow working. No need for better logic cards.
Just add a Card: "Flow" to "then" and choose "disable a flow" and select this flow itself. So you just need to enable the flow once a day (I guess you have already a similar flow to set the better logic variable to true).

![image](https://cloud.githubusercontent.com/assets/17235241/14302202/bfaba5d6-fb9e-11e5-8978-145c864972e5.png)

**Comment by jordenc** [comment]
@peaoo: I did that as well, that indeed is a smarter solution than using the Better Logic.

**Comment by bvdbos** [comment]
This one is fixed, isn't it?

**Comment by WeeJeWel** [comment]
Yep!
