### ISSUE TITLE
Brightness not always adjusted to the set value

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#411]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Adjusting the brightness in a flow doesn't work when the signal is send for the second time. In my case, as soon as Homey receives Yellow for the second time, the brightness is switched to 100% instead of the given 50%.

![schermafbeelding 2016-04-05 om 22 51 49](https://cloud.githubusercontent.com/assets/17526110/14298133/6fb0a8bc-fb83-11e5-9f78-df9d8942908d.png)

These false triggers do happen quite a lot. With my Smartwares remote I had the same issue but was unable to reproduce, now that I have the only working input device in parrot mode, it was easy to find.

**What was the result?**

Brightness to be 100% instead of the 50%

**What did you expect as result?**

Brightness of 50%, Workaround for the time being is to add a delay of 5 seconds. #408 could also be an option for this issue.

**Comment by WeeJeWel** [comment]
Does this happen for both the led ring as the lights?

**Comment by Arjanvde** [comment]
Just the lights, the LED Ring stays unaffected. In my case the LED Ring is switched off during daytime but I want it to be switched on when i turn some lights on and off when i'm going to sleep.

Reproducing should be easy, just create a flow something like above and trigger it twice.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Arjanvde** [comment]
Seems to be solved.
