### ISSUE TITLE
Homey bricked

### ISSUE THREAD

**Issue by Moque8** [athombv/homey#413]
**What is your Homey version (Settings → System)?**

brand new out of the box (received today)

**What did you try to achieve?**
I connected my Homey to my WiFi, but my telephone froze while it was updating the Homey for the first time. Now I get a red led ring. I cannot connect to my Homey from my telephone.

Tried to reset both when the homey was turned on and off (turning it after 10 seconds) but it still shows the red ring.

**What was the result?**

Homey is bricked.

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by rlijkendijk86** [comment]
I don't think this behavior is due to your phone freezing during update. My Homey updated for the last step in the setup and then my.athom.com was showing the Homey was going for a reboot. My Homey does not come online, led spinning orange and eventually becomes solid red. Flipping the Homey over doesn't work.

**Comment by Moque8** [comment]
You're right, I just wanted to point out that the initial update didn't go as planned and was probably broken off.

**Comment by nattlip** [comment]
https://forum.athom.com/discussion/528/received-your-homey-getting-started-guide

for a rest procedure read this.

**Comment by Moque8** [comment]
Tried these procedures, didn't work..

**Comment by rlijkendijk86** [comment]
Same here. Jeroen asked me to send an email to support at athom dot com so I did to request support. Perhaps you should do the same :)

**Comment by jeroenvollenbrock** [comment]
I'm suspecting this behavior is caused by Homey being upside-down while Homey is installing an update (purple ledring) before Homey reached version 0.8.27.

**Comment by rlijkendijk86** [comment]
I managed to recover my Homey with the instructions I received from Stefan :+1:
