### ISSUE TITLE
Feature request: simple stop command for all audio

### ISSUE THREAD

**Issue by bliekp** [athombv/homey#414]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Trying to stop any audio. 
I tried:
"stop"
"stop audio"
"stop all audio"
"stop the music"
"stop talking"
and many more variations.

**What was the result?**

None

**What did you expect as result?**

A simple command to stop Homey from talking, playing music etc.

**Any other remarks**

...

**Comment by jordenc** [comment]
"stop" works.

Example;
"Play Armin van Buuren"
Homey starts playing after a few sconds.

"Stop"
Homey stops playing almost inmediately.

Possibly Homey understood 'stop' wrong. See http://<localip>/manager/speech-input/ for more info on what was heard.

**Comment by WeeJeWel** [comment]
'Stop' should work like @jordenc says.

**Comment by bvdbos** [comment]
As most of the controlling works with the web-interface we need a stop-button on the webpage (or preferably something like the audio-player in the android-app). I have some flows which start audio but they get triggered by external noise. To be able to stop the music, I have to remember which page to load (the speech-input page) and type a manual command as Homey won't listen to me while playing music.

**Comment by WeeJeWel** [comment]
The music control will be imporved drastically in the 'Media Manager' update. :)

**Comment by bvdbos** [comment]
Thanks....

**Comment by bliekp** [comment]
Thanks. After a Homey reboot it worked btw.
