### ISSUE TITLE
After Reboot, no data anymore from z-wave sensor

### ISSUE THREAD

**Issue by sossienl** [athombv/homey#415]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

I've paired my 4-1 sensor from AEON labs to Homey. All went reasonably ok. It has light, temperature and humidity sensor as well as movement. So far I could only see temperature and light in the Homey GUI, but without any values showing.  I think these issues are already tracked in other issue reports.

After updating the polling variable to 61 seconds, I get the updated values each minute and I used a flow to let Homey "speak" the values.  So that's an expected behaviour. Then I reboot my Homey manually, because it gets slow after a while or for any reason for that matter.

**What was the result?**

The flow is not triggered anymore and I don't get any new values. I need to manually wake up my z-wave sensor to kickstart the flow again

**What did you expect as result?**

I would expect that my flow is triggered again because it should poll my device again every 61 seconds.

**Comment by djeskoswe** [comment]
Don't use poll it slows down the zwave network,  set wake-up intervall on device instead.

**Comment by sossienl** [comment]
Thanks, I only have 2 z-wave devices connected at this moment. And both poll and wake-up are set. So even if setting poll slows down the network, the behavior I'm seeing is still wrong.

Btw; I have 15+ other z-wave devices not yet connected due to the buggy state of Homey

**Comment by freemann** [comment]
On my Vera3 I have 15 GreenWave powernodes. All these nodes are configured to be polled at a rate of 30-90 sec. and it works great.
So 2 devices shouldn't be a problem for Homey..

**Comment by sossienl** [comment]
In addition if I set the polling interval back to 0, and keep the wake-up to 60 second, no data is transferred anymore. Only when I put back the polling interval data is shown... The reboot issue remains btw

**Comment by djeskoswe** [comment]
i have 0 polling and gets data ,  strange !

**Comment by ocatie** [comment]
The values in Homey are only updated if a report is received AND the value is different than the current value.

Also you shouldn't poll a battery powered device because it wont anwser the poll and the device will become unavailable.

**Comment by sossienl** [comment]
It's not battery powered, but USB powered so that's that. Plus the values do change. It happened during sunset, so the Lux value is different every minute...
