### ISSUE TITLE
Make Hex zwave node info humanly readable

### ISSUE THREAD

**Issue by freemann** [athombv/homey#417]
**What is your Homey version (Settings → System)?**

0.8.29 (have no homey, stole a screenshot)

**What did you try to achieve?**

Try to read the "Manufacturer id", "Product type" and "product id" and see which device a user is using;
![screenshot - 7-4-2016 08_08_33](https://cloud.githubusercontent.com/assets/601053/14342194/439c8910-fc98-11e5-8a19-d72d2df9c3b8.png)
 
**What was the result?**

"Unreadable" or un logic manufacturer id 0x86 which doesn't make sense.

**What did you expect as result?**

 That manufacturer id 0x86 would read "AEON Labs"
![screenshot---7-4-2016- -08_08_33](https://cloud.githubusercontent.com/assets/601053/14342617/2ec32ca8-fc9b-11e5-8726-25fd560336b8.png)

**Any other remarks**

**Comment by daneedk** [comment]
+1 
https://www.google.nl/#q=site:www.pepper1.net+0x0086+0x0002+0x0059

**Comment by ocatie** [comment]
Will look if I can implement that using Z-Wave apps.

**Comment by daneedk** [comment]
Great! Some neighbours have it implemented ;)
https://github.com/OpenZWave/open-zwave/tree/master/config
https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml

**Comment by bkockx** [comment]
I have actually been writing just such an app.
There is still work to do, but showing information about the device and the parameters already works.

I am willing to already share to code if somebody wants to help.
![screen shot 2016-04-27 at 16 40 40](https://cloud.githubusercontent.com/assets/6672864/14856153/3df960aa-0c97-11e6-954f-80b4e0310738.png)
