### ISSUE TITLE
KAKU Remote (AYCT-102) doesn't trigger a flow

### ISSUE THREAD

**Issue by colligro** [athombv/homey#418]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Added a KAKU remote AYCT-102. Pairing went perfect. Adding sockets with the remote was also perfect. I tried triggering the remote (Channel 2, Button 2, off (other buttons did not work either)
to switch the lights off via Homey and switching off the nest thermostat.

**What was the result?**

Nothing happened

**What did you expect as result?**

Lights off, thermostat off

**Any other remarks**

Triggering the flow with voice works like a charm!

**Comment by Arjanvde** [comment]
Looks like #392

**Comment by Dennishacq** [comment]
This is indeed caused by the same issue as #392. 
See #392 for more info.
