### ISSUE TITLE
Weird English/Dutch speech feedback in a flow

### ISSUE THREAD

**Issue by colligro** [athombv/homey#419]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Turning the lights off via speech. Homey will say "Lampen zijn uit". Using homey in Dutch

**What was the result?**

The lights do go out. But Homey says in crappy Dutch/English "Turning lights off" and right after this "lampen zijn uit". When I started using homey I used some English flows (and language). Resetted homey and reinstalled it to Dutch. I got the feeling some flows are still somewhere in the code...

**What did you expect as result?**

Homey turning the lights off and only saying "Lampen zijn uit"

**Any other remarks**

...

**Comment by Arjanvde** [comment]
It somehow say's not fully translated when you select Dutch doesn't it?

![nl](https://cloud.githubusercontent.com/assets/17526110/14346122/03a605c0-fcb1-11e5-94fb-a6cb91dc08a1.png)

**Comment by colligro** [comment]
The only speech in flow is this
![image](https://cloud.githubusercontent.com/assets/10434327/14347595/39566da2-fcb8-11e5-9866-9928f4ad77f2.png)

(Says: Lampen uit) but it actualy says "Lights of lampen uit" lights with a dutch g because I use the dutch Homey

**Comment by freemann** [comment]
Athom recommend(ed) to **only(!) use English** and not(!) use the Dutch language because its still in a (early) Beta.

**Comment by bvdbos** [comment]
It understands "lampen uit" and thus turns the lights off and says "turning
ligths off".

Also, as you created a flow which also reacts, it says "lampen uit". The
part "turning lights off" isn't translated yet apparantly...

**Comment by jordenc** [comment]
It says "Turning lights off" because 'Lampen uit' is recognized as a builtin command.

It says "Lampen uit" because 'Lampen uit' is recognized as your flow. If you disable the flow it will work but will only say it once (in English for now)

**Comment by Tweake** [comment]
The situation described by @bvdbos and @jordenc is what was causing this issue. I have added the translations for all spoken feedback related to lights, so this will be fixed as of version 0.8.31. Once your Homey is updated to v0.8.31 you can also delete your "lampen uit" flow, since Homey's built-in speech control will already notify you that the lights have been switched on/off (this time in Dutch)

**Comment by bvdbos** [comment]
this doesn't work through the phone yet, when I say "Lampen aan" the phone responds "ik zet het licht on" and also "ik zet het licht off". 
0.8.35 and android 2.1 build 45
