### ISSUE TITLE
Unable to remove/reposition zones

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#42]
I Don't know how to remove existing zones that I don't want (like study on the first floor). I can add new zones but I am unable to create them in the right context/tree level. The existing tree structure seem to suggest that I can do so. 
A delete button would be nice and drag and drop also. 
During delete all devices can be moved to the 1st (home) node

**Comment by JohanKuster** [comment]
Ok, I found it. Dragging and dropping using the right side of the label. Also the Add becomes delete. Nice but I wonder if this is too much average user. Perhaps a pair move up or down buttons and a delete button is more obvious to use.

**Comment by WeeJeWel** [comment]
Will reconsider, thanks!

**Comment by kaspel** [comment]
Same here, not obvious how to remove zones... :-)
/Mats

**Comment by bvdbos** [comment]
The current web-interface will be deprecated if a "short" while so don't count on it this will be changed for now...
