### ISSUE TITLE
Can't set infra red on manually

### ISSUE THREAD

**Issue by willem138** [athombv/homey#421]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.29
Athom Cloud ID: 56c5e3a61bf7da0e1eddc95e

x.x.x

**What did you try to achieve?**

Add my (Yahama) Receiver and 
my digital convertor box (Horizon) to devices

*Please include detailed steps how we can reproduce the issue*

Tried to add device automatic, didn't work, tried manual but the circle keeps turning but he doesn't see the signal after I push a button on my remote.

**What was the result?**

Nothing:) I think he doesn't see the signal..

...

**What did you expect as result?**
He saw the signal and i could tell what button i pushed to set it op.
...

**Any other remarks**

...

**Comment by Qx5** [comment]
What helps for me in manually adding  buttons is to hold the buttons for approx 2 seconds and then release it. a single press is often indeed not recognized.

**Comment by willem138** [comment]
Thanks, but I already tried this, did't work. 
He does recognize it when i try this with my (already added) remote of my Panasonic TV
But when I push buttons on the other two remotes it gives nothing..

**Comment by Qx5** [comment]
Join the club at #249 :wink:

**Comment by jordenc** [comment]
I think that the Horizon remote control might not be infrared. If it works if you point it the other way, it's not using infrared. Mine works if I point it in the opposite direction.

The new remote controls of Horizon use a different method than infrared. However, the old remotes are infrared so if you have one of them you might be able to train.

**Comment by willem138** [comment]
Thanks guys for support but I am impatient and bought Logitec Harmony Hub and now everything works perfect:)

**Comment by Keverjeroen** [comment]
The remote for the Ziggo Horizon box does only use IR for the TV-buttons, not for the box-buttons. You can check this by opening the camera-app on your phone, pointing the remote at your camera and push a button. Your camera shows the infrared.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
