### ISSUE TITLE
Cannot connect to open WiFi network

### ISSUE THREAD

**Issue by olafz** [athombv/homey#422]
**What is your Homey version (Settings → System)?**

?

**What did you try to achieve?**

I have a lot of trouble connecting to WiFi network(s). So, in an attempt to rule out all possible problems, I created an open WiFi network. However, the setup of Homey cannot continue the wizard when you select an open network. See screenshot.

<img width="621" alt="screen shot 2016-04-06 at 20 00 54" src="https://cloud.githubusercontent.com/assets/80709/14349630/90fb007a-fcc4-11e5-84fd-cd3c77d99eea.png">

**Please include detailed steps how we can reproduce the issue**

Select an open WiFi network in the setup wizard

**What was the result?**

Cannot continue in setup wizard

**What did you expect as result?**

Be able to continue in setup wizard

**Comment by freemann** [comment]
Open network without password and the wizard requires password?!

If so;
nice/funny/great real world catch!

**Comment by olafz** [comment]
> Open network without password and the wizard requires password?!

Yes, that's exactly what's happening :)

**Comment by WeeJeWel** [comment]
Fixed!

**Comment by RoadXY** [comment]
@WeeJeWel You forgot to assign an Milestone :+1:

**Comment by WeeJeWel** [comment]
There's not a milestone for everything ;)

**Comment by WeeJeWel** [comment]
This is a cloud problem anyway, so a Homey version was not applicable. It's already live!

**Comment by RoadXY** [comment]
Lol, sorry.
