### ISSUE TITLE
Plugwise Circle

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#423]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

I am trying to add the Plugwise Circle. But I am also not 100% sure this is supported

**What was the result?**

Homey does not sees teh Plugwise Circle adapters

**What did you expect as result?**

That homey could add them

**Comment by bvdbos** [comment]
Do you use a stick to get to your circle's? This isn't supported unfortunately. Or do you use the stretch?

**Comment by magtimmermans** [comment]
Stick indeed, But the app is saying All Plugwise devices :)

**Comment by freekwebdesign** [comment]
I think I was a little overexcited when I wrote down 'ALL plugwise devices'. ;)
The description in the app store will be changed in the next version too 'our Plugwise (Stretch) and Anna (Smile) devices'

**Comment by bvdbos** [comment]
Still I hope at some time we can receive plugwise-data through the Homey-radio directly :+1: http://blog.hekkers.net/2015/12/12/adding-a-plugwise-smile-to-the-fibaro-hc2/

**Comment by magtimmermans** [comment]
Me, too It is of course very easy to limit it. In theory this must be possible

**Comment by nattlip** [comment]
it would be nice if the plugwise app would be published on github. i have  the plugwise source not the stretch. all domotica fans which are a little longer using domotica at home as the young boys from homey  use the the source . it would be nice to implement that to on homey . the plugwise api is as open as the hue api and the hue app is published why not the plugwise ? the code to get plugwise info is not top secret anymore for a very very long time. i think the stretch has an xml file to read just as the source has.

**Comment by freemann** [comment]
The community could build a own open source app?!

**Comment by freekwebdesign** [comment]
We understand that it would be nice if we could publish the source code to Github. But unfortunately we can not do this because we got an agreement with Plugwise to not release the source code.

In the short time we are not planning to implement 'Plugwise Source', so if someone in the community would build its own open source app that would be awesome ofcourse.

**Comment by nattlip** [comment]
okay, that is beyond your power. i dont understand plugwise, their api is all open see:

[http://domoticx.com/plugwise-stretch-2-0-links-en-bestanden/](url)

[http://domoticx.com/plugwise-smile-p1-links-en-bestanden/](url)

[http://domoticx.com/plugwise-software/](url)

**Comment by bvdbos** [comment]
I understand, also I don´t understand the people off Plugwise. They could broaden their userbase (and sales) a lot. The Smile should be easy, Stretch is already supported. Most difficult will be "normal" plugs. We have to connect one of the Homey radio's to the circle+..

**Comment by nattlip** [comment]
theo source is just like the hue bridge , you dont have to get all devices by it self, you import the data from the source which i think is not so different fro the stretch, but i dont have a stretch so i dont know.

**Comment by nattlip** [comment]
i have the skeleton for the plugwise source app build , i can import the circles in homey. it is a lot easier as a homeseer plugin. I must say the programmers from athomhave made  the app development quite easy especially with the build in socket.io in the pair and settings section. 
![plugwisehomey](https://cloud.githubusercontent.com/assets/7040452/14589595/fa044c10-04e5-11e6-9046-7dec7ef8f6c2.PNG)

**Comment by bvdbos** [comment]
How do you connect to the network, through the stretch or do you connect to a ps with the stick which is running the plugwise-server software?

**Comment by nattlip** [comment]
i connect to the plugwise source server which runs on a windows 10 computer with a plugwise usb stick , My source can use 2 sticks , one remote stick is in a second location connected with a digi serial server.

**Comment by magtimmermans** [comment]
Mmh, busy with the same thing. Would you be able to share your code. Would be silly to work on the same thing...

**Comment by nattlip** [comment]
it will be published when it is ready, it is the joy of programming what gives the fun not the result. indeed it is silly to work both on the same app but i mentioned it here on github you didnt ,maybe 20 people are working on it, so publish you own code on github then people can contribute if you want  or want to work together in a group.

**Comment by magtimmermans** [comment]
Hi, Sure no problem. I also started just for fun and because I was not sure if I understand everything and I maybe could not fnished it, I did not mention. But I will try to continue just to get experience. Overall it is not very hard.

**Comment by freekwebdesign** [comment]
Amazing to hear you guys are working on the Plugwise app!
If we can assist in anyway, please let us know, we are looking forward to see the result! :)

**Comment by magtimmermans** [comment]
Currently I am testing. The webserver of the Plugwise source app is sometimes unstable. But in general it works.
