### ISSUE TITLE
Somfy remote cannot be added

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#424]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Try to add the Somfy remote Screens

**What was the result?**

It did not recognize the somfy remote control 
additional info. My screens are not going up and down for a second. So I think my protocol is older.

**What did you expect as result?**

That is will recognize this

**Any other remarks**

See picture for remote info
![img_2554](https://cloud.githubusercontent.com/assets/17949840/14359247/dfc5a8f0-fcf0-11e5-8fba-7e8aae3fcaaf.JPG)
![img_2553](https://cloud.githubusercontent.com/assets/17949840/14359250/e3ba1acc-fcf0-11e5-81a0-6e3af76c5691.JPG)

**Comment by jordenc** [comment]
Did you press the button on the back for a second when pairing? (With a pen or paperclip)

**Comment by magtimmermans** [comment]
Yes. Multiple tries. No result.

**Comment by Dennishacq** [comment]
@magtimmermans 
Are you able to control your blinds using this remote?
Did your screens react when you press the pair button on your remote?

**Comment by magtimmermans** [comment]
No, unfortunately not.

**Comment by Dennishacq** [comment]
@magtimmermans 
Then it sounds like your remote is not paired with your blinds.
You can try one of the following options:
-Adding the remote to your blinds (See user manual of your screens) and than add the blinds to Homey.
-Adding the screens to Homey by using the program button on your blinds instead of the program button on your remote.

**Comment by magtimmermans** [comment]
The remote works just fine with the blinds. But the app does not recognize the remote control. I have done both but the app does not see the blinds.

**Comment by RoadXY** [comment]
But the blind are in a programmable state for Homey to connect after the go up and down quick.
Then, and only then, Homey is able to connect to your blinds

**Comment by magtimmermans** [comment]
This version does not work like this. You press the button and the light goes on when synced.

**Comment by RoadXY** [comment]
But you'll have to program it.

**Comment by magtimmermans** [comment]
Yes, and this is not working. I will attach the Dutch manual.
[printer-brother_000647.pdf](https://github.com/athombv/homey/files/245186/printer-brother_000647.pdf)

**Comment by Dennishacq** [comment]
@magtimmermans 
Are you still experiencing this problem with Somfy v1.0.13?

**Comment by magtimmermans** [comment]
Yes, Same problem :(

**Comment by magtimmermans** [comment]
Any news?

**Comment by Dennishacq** [comment]
@magtimmermans 
![image](https://cloud.githubusercontent.com/assets/15836768/15891733/458e904c-2d76-11e6-9690-78737860322a.png)
Do the blinds jogg when you perform one of these actions?

**Comment by magtimmermans** [comment]
No, it won't

**Comment by jordenc** [comment]
Make sure you press the correct pair button. I managed to press the wrong button on my remote, which turned on / off the automatic open/close on sun-detection.

**Comment by magtimmermans** [comment]
This is not the case, I follow exactly the manual. It just won't work!

**Comment by magtimmermans** [comment]
Any news with this. I would really like to use it.

**Comment by magtimmermans** [comment]
Version 0.9.x solved the problem!??
