### ISSUE TITLE
KAKU/ZWave flow stopped working

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#425]
**What is your Homey version (Settings → System)?**
0.8.29

**What did you try to achieve?**
Ever since I installed Homey, I have two flows using a KAKU open/close sensor and a Fibaro dimmer. One flow switches on a light when the contact sensor opens. The other switches the light off when the sensor is closed. These flows provide an easy check to check whether Homey is still alive, KAKU is still working and ZWave is still ok. Unfortunately, the flow stopped working since upgrade to 0.8.27. Re-creating flow does not help. Sensor device status shows sensor opening/closing. Switching on/off light works okay, so ZWave ok. Something unknown broke the flows...

**Please include detailed steps how we can reproduce the issue**
Create flows as described above.

**What was the result?**
See above

**What did you expect as result?**
Flow working.

**Any other remarks**
Nope

**Comment by bvdbos** [comment]
Which open-close kaku-sensor do you use?
>
>

**Comment by Muyz** [comment]
AMST-606

**Comment by bvdbos** [comment]
#392 I guess

**Comment by Muyz** [comment]
Not so sure, I *do* see the device status change when I open/close the sensor on the Homey UI.

**Comment by Muyz** [comment]
Flows that are triggered by Z-Wave Fibaro sensor also stopped working. Essentially, this means that none of my flows work now.

**Comment by Dennishacq** [comment]
Hi @Muyz 
I just uploaded an update for the KaKu app which should make your devices work again after you re-pair them.
Please let me know if your problem is solved :)

**Comment by Muyz** [comment]
Good news. The KAKU based flow works again. Z-Wave flow also works (PEBKAC), so issue closed. Thanks.
