### ISSUE TITLE
Can't add some Fibaro dimmers

### ISSUE THREAD

**Issue by Muyz** [athombv/homey#426]
**What is your Homey version (Settings → System)?**
0.8.27

**What did you try to achieve?**
With 0.8.27 the interviewing process for the Fibaro Dimmer 2 still fails. It does add one or three devices, but these do not work. Devices show a broken connection link with error_timeout_waiting_for_report
The 'broken link' makes that you cannot even delete the device, as that button is blocked (same as for device settings).

**Please include detailed steps how we can reproduce the issue**
Try to add a few Fibaro dimmers. Some will work flawlessly, some just do not.

**What was the result?**
See above.

**What did you expect as result?**
Proper pairing of Fibaro Z-Wave devices; in this case the Dimmer 2.

**Any other remarks**
Nope

**Comment by ocatie** [comment]
The removal of a Z-Wave device is always done through the Settings page.

Could you post a screenshot of the devices (zone overview) immediately after the pairing wizard is closed?

**Comment by luccie007** [comment]
Still having the same issue with 0.8.30

Not a Fibaro dimmer but a DUWI dimmer.
The interview process hangs forever. Then times out and the device is added is a standard switch.
But the insights show the dim level, but no slider is possible.

Let me know what you need for debugging.

See topic:
https://forum.athom.com/discussion/1221/cannot-interview-z-wave-dimmer

**Comment by luccie007** [comment]
Mine is solved now,
Interviewing continues. 
Then i can choose the option Lamp.
And i get the brightness setting available. 
Which is not a slider, but a weird round slider. 
But at least it works now :)

**Comment by ocatie** [comment]
@Muyz Still experiencing the issue on 0.8.32?

**Comment by Muyz** [comment]
@ocatie: dunno; I am in China until May 16th

**Comment by Muyz** [comment]
Just returned from China. Performed factory reset. Tried to bind a Fibaro Dimmer 2. Unfortunately, the interviewing fails and the dimmer is added as a basic device. Log 9B77C0B3D2.

![schermafbeelding 2016-05-15 om 11 59 07](https://cloud.githubusercontent.com/assets/17163901/15273321/01ed392c-1a95-11e6-9847-0ee7976d4511.png)

**Comment by mglat** [comment]
same error here, when trying to add a ZWave mini plug AD147 (Everspring tussenschakelaar). 
I'm using build 0.8.32
