### ISSUE TITLE
adding somfy rollershutter produces zwave device

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#428]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
after downloading somfy app , add a rollershutter
*Please include detailed steps how we can reproduce the issue*

**What was the result?**
the device was added, but trying to press the down or up button zwave device screen appears
...

**What did you expect as result?**
to shut en open my rollershutter from webinterface
...

**Any other remarks**

...
![somfy](https://cloud.githubusercontent.com/assets/7040452/14365111/404d43d4-fd0c-11e5-9291-ea94004c939e.PNG)

**Comment by nattlip** [comment]
although the manual control doesn't work , the flows works with blinds

**Comment by nattlip** [comment]
now it works i dont know what did it, making a flow or controlling it from android

**Comment by WeeJeWel** [comment]
Does the device have a wrench icon in Zones & Devices?

**Comment by nattlip** [comment]
no a rollershutter or blind  icon

**Comment by WeeJeWel** [comment]
Should be fixed in 0.8.31, please report back if it isn't.
