### ISSUE TITLE
Ordering of devices in flows case sensitive

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#429]
version 0.8.29
ordering of devices in flow page is case sensitive. 
I expect it to be case insensitive.

![image](https://cloud.githubusercontent.com/assets/15232724/14368224/ca361a0c-fd1c-11e5-9225-f348990a44d7.png)

**Comment by WeeJeWel** [comment]
Fixed some time ago :)

**Comment by irritanterik** [comment]
@WeeJeWel Please reopen. Case sensitive ordering persists in version 0.10.9:
![image](https://cloud.githubusercontent.com/assets/15232724/20049164/a9849b74-a4c1-11e6-8512-7e3b51b058b0.png)

**Comment by WeeJeWel** [comment]
Whoops, indeed. Fixed in 0.11.0!
