### ISSUE TITLE
Adding device Thinking Cleaner result in an Invalid Token

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#43]
I get this message when trying to add the Roomba cleaner. No instructions visible after removing the popup message, only a spinning icon.

**Comment by WeeJeWel** [comment]
This app hasn't been updated in ages, so it's probably broken. Will look into it asap :)

**Comment by Jovink** [comment]
The same problem has the Ikettle

**Comment by matjaz** [comment]
Same for chromecast app. @WeeJeWel can you point us what has changed? Thanks.

**Comment by WeeJeWel** [comment]
These apps are outdated and need some revision before they'll work again :)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by matjaz** [comment]
yeah.. I am working on fixin' chromecast app. Fixed youtube playback using DefaultMediaReceiver, needs only device pairing to get fixed. I was looking into other apps, but can't find out the difference.

**Comment by WeeJeWel** [comment]
If you create a node.js example where you can play a YouTube video I'll update the chromecast app this weekend ;)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by Jovink** [comment]
Only Youtube? Not a custom url? (like 538TV)

**Comment by WeeJeWel** [comment]
That's also cool, but I think YouTube is a better usercase for most people.  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by Jovink** [comment]
Do it both ;)

**Comment by matjaz** [comment]
That's what I'm doing. :)

**Comment by Jovink** [comment]
Great! But is it a new app or the one Athom has made

**Comment by matjaz** [comment]
Fixed existing app athombv/com.google.chromecast#1

For You @WeeJeWel please take time and update docs over the weekend. Since this is very important, to creating apps. ;)

**Comment by WeeJeWel** [comment]
@matjaz I saw it! Will test this weekend and merge. Awesome work!!

What would you like to see changed in the docs?

**Comment by matjaz** [comment]
aha. for invalid token error `app.pair` is now `function(socket)`.

**Comment by WeeJeWel** [comment]
The docs already reflect this: https://developers.athom.com/library/drivers. Am I missing something?

**Comment by matjaz** [comment]
I meant in general. More docs for managers. I wan't to do some stuff with 433, but don't quite understand `Signal` object. I am looking into https://github.com/athombv/nl.action

**Comment by WeeJeWel** [comment]
Ah! Those docs are following pretty soon, cause they're a little bit more complicated :)
