### ISSUE TITLE
Z-wave protocolFailed error when Remove Node is pressed

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#430]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Stable Z-wave environment

*Please include detailed steps how we can reproduce the issue*

Rebooted. Waited 30 minutes with minimal Z-wave actions ( 5 active Z-wave devices) 

In Settings->Z-wave , overview of devices is unavailable and Z-wave actions are not processed.

Logfile: 8A0A7BE5B6

**What was the result?**

I have to reboot Homey. Restart Z-wave chip seems to help, but then I am unable to remove a node:

![screen shot 2016-04-08 at 09 40 15](https://cloud.githubusercontent.com/assets/17275712/14377072/023c6d4c-fd6e-11e5-9d8a-a9be4381a315.png)

**What did you expect as result?**

Stable Z-wave

**Any other remarks**

Up until 0.8.24 Z-wave was fairly stable. Unstability started in 0.8.27.

**Comment by ocatie** [comment]
You have described multiple issues in 1. I've made this issue the protocolFailed. Please check if there is already an issue for any other issue you have. If not feel free to create a new issue per problem.

The protocol failed error is an error thrown by the Z-Wave chip. I've encountered it one time randomly myself and a Restart Z-Wave Chip fixed it then. Could you try that?

**Comment by ralfvd** [comment]
I encountered this error after I did a "restart Z-wave chip" (after Z-wave failed completely).  After the restart Z-wave was back, but I had the protocolFailed error.  Only a complete reboot brought back Z-wave and 'remove node' functionality

**Comment by ocatie** [comment]
Did you have Homey included in another network?

**Comment by ralfvd** [comment]
No, Homey is my only (and first) controller device.
