### ISSUE TITLE
[Z-wave] Fibaro Dimmer 2 sometimes in status 'txstatus undefined'

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#431]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

After reboot, my Fibaro Dimmer 2 device is sometimes erroring with 'txstatus undefined', which results in not being able to control the device via Homey

![screen shot 2016-04-08 at 09 55 41](https://cloud.githubusercontent.com/assets/17275712/14377509/452b7d62-fd70-11e5-827d-bcf72562dd65.png)

I can correct this state by refreshing the node.

I've never seen it re-occur then, until the next reboot. Not every reboot will give 'txstatus undefined' error, it is about 50 % of the time.

**Comment by dvanp** [comment]
Had the same last night with a Fibaro Wall plug after a reboot. Refresh node fixed it and haven't had issues since.

**Comment by ralfvd** [comment]
@dvanp  Once I solve it, it will continue working correctly, until the next reboot.

**Comment by ralfvd** [comment]
After many reboots today it now also occurs sometimes on a Fibaro 2x1.5K relay switch:
![screen shot 2016-04-08 at 16 10 51](https://cloud.githubusercontent.com/assets/17275712/14386321/8144a452-fda4-11e5-9b5f-f99568839792.png)

**Comment by ocatie** [comment]
This is a known issue caused by an issue with the serial communication with the zwave chip. We're working on it.

**Comment by laurenssss** [comment]
it also happens with Greenwave NP-310 outlets

**Comment by laurenssss** [comment]
![image](https://cloud.githubusercontent.com/assets/17315800/14453321/67f89c5e-0094-11e6-9715-0d78e2d027a7.png)

**Comment by freemann** [comment]
Its not a device issue, its a homey/z-wave chip issue and every Zwave device can be effected to this issue.

**Comment by laurenssss** [comment]
even more reason to have it fixed very soon hahaha

**Comment by ocatie** [comment]
txStatus undefined should not occur anymore on 0.8.30.

**Comment by ralfvd** [comment]
I have again have one on 0.8.30: 

![screen shot 2016-04-16 at 14 37 40](https://cloud.githubusercontent.com/assets/17275712/14581004/1d543302-03e1-11e6-94e8-9d0b17496c32.png)

Node-id: 7  Log: FACDF2AB75
