### ISSUE TITLE
IR not responding at all

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#432]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

recognize remote control

*Please include detailed steps how we can reproduce the issue*

started the pairing wizard, automatic recognition and manual
when pointing the remote to the homey, pressing buttons, homey doesn´t react at all

**What was the result?**
homey didn´t react on remote control button pushes
...

**What did you expect as result?**
ability to pair remotes
...

**Any other remarks**

...

**Comment by Qx5** [comment]
#249 

But this is probably related to the remarks about carrier frequency issues by @goldenice

**Comment by laurenssss** [comment]
correct, well spotted Qx5, it is recognized when i do press press press press ...... and so on
not yet smooth, but ok, let´s track de rest in 249

**Comment by posthok** [comment]
Try to turn off the led ring in system settings and give it another try.
