### ISSUE TITLE
KAKU ventilator can not be controlled

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#433]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

added a KAKU switch, which switches on/off my central ventilating system
device is succesfully added
selected the ´ventilator´ option

**What was the result?**
device is in the list, however I cannot switch it on or off
...

**What did you expect as result?**
be able to switch on and off
...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
In Flow?

**Comment by laurenssss** [comment]
not available in list of devices to select in a flow

**Comment by WeeJeWel** [comment]
Thanks, Fan support will be added later. A workaround for now is to not select the 'Fan' option.

**Comment by laurenssss** [comment]
ok, tnx, maybe for now remove the option to choose from in the list?

**Comment by DieterKoblenz** [comment]
#759 
Same issue actually. Workaround still applies, not use kettle but undefined.

**Comment by DieterKoblenz** [comment]
Status quo in 0.10.0

**Comment by laurenssss** [comment]
Status quo for a few months.... @jeroenvollenbrock any news or expectation?

**Comment by Dijker** [comment]
As we are on Homey 1.x and KAKU App  v3.0.1 a few months .....
As far as I can see this one is fixed? 
@laurenssss  can you test, confirm if fixed, and maybe close?

**Comment by jeroenvollenbrock** [comment]
This issue is supposed to be fixed in Homey version 1.2.0. Can you please let me know whether this issue persists or not?
