### ISSUE TITLE
Somfy; closing the blinds input ,with verbally reaction that he closes the blinds doesn't do anything

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#434]
**What is your Homey version (Settings → System)?**
0.8.29
what did you try to achieve?**

close or open my somfy blinds verbally or with speech input webscreen

*Please include detailed steps how we can reproduce the issue*
say : "okay homey, close (0r open) the blinds"

**What was the result?**
homey answers "closing (or open) the blinds"' but no real blind does anything
...

**What did you expect as result?**
that the blind will open or close 
...

**Any other remarks**

...

**Comment by ReinierH** [comment]
Can you still control your blinds using the homey interface?

**Comment by nattlip** [comment]
yes

**Comment by Dennizz** [comment]
I am experiencing the same issue. I am on 0.8.30. Somfy is working fine, both through the device settings, and through flows that trigger on other conditions.

**Comment by cjvs** [comment]
**What is your Homey version (Settings → System)?**
0.8.30
**what did you try to achieve?**
close or open my somfy blinds verbally (Somfy RTS window covering)
Please include detailed steps how we can reproduce the issue
say : "ok homey, close the shutters"

**What was the result?**
homey answers "closing shutters"' but nothing happens

**What did you expect as result?**
that the blind will close 

**Any other remarks**
opening, closing and stopping Somfy RTS window covering with app & webmanager works.

**Comment by JPe2** [comment]
![image](https://cloud.githubusercontent.com/assets/3833862/14822473/27f4a74c-0bcf-11e6-8c1c-856149122c79.png)

Works fine for me !!!  Do you use "Close"  for "DOWN"  and  "Open"  for  "UP" ?

**Comment by Tweake** [comment]
@JPe2 you have created your own flow here, while @nattlip and @cjvs are talking about an issue with Homey's buit-in speech command. I have figured out where the issue originated and am aiming to have a fix shipped with version 0.8.33.

Thank you all for pointing out the issue!

**Comment by cjvs** [comment]
@WeeJeWel Could you please specify what I should say to open or close my somfy sunscreen? Neither of the following voice commands works:
- please open (or close) the (blinds, sunscreen, shutters, window covering)
![screen shot 2016-05-17 at 20 45 34](https://cloud.githubusercontent.com/assets/18570823/15334898/65b3d74a-1c70-11e6-91bb-cf0d97a5d994.png)
- "blinds" and "shutters" are provided with voice feedback from homey. However, still no action is taken with my sunscreen...

**What is your Homey version (Settings → System)?**
0.8.34
**what did you try to achieve?**
close or open my somfy blinds verbally (Somfy RTS sunscreen)
Please include detailed steps how we can reproduce the issue
say : "ok homey, close the shutters"

**What was the result?**
homey answers "closing shutters"' but nothing happens

**What did you expect as result?**
that the sunscreen will close

**Any other remarks**
opening, closing and stopping Somfy RTS window covering with app & webmanager works. (speechinput worked perfectly though...)
Log: 4247FA5D2C
