### ISSUE TITLE
Suggestion: NEST thermostat trigger heating on/off

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#436]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

I would like to have a trigger when nest sends a signal to the heating system is on or off.
When heating = off --> Kaku socket = off 
Bidirectional, so: heating = on --> Kaku socket = on

In that way the waterpump of the central heating is only on when the heater is on

*Please include detailed steps how we can reproduce the issue

Add a trigger card: when nest is heating:

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

Great job so far!

...

**Comment by RobinBol** [comment]
Added two flow cards to the app:

1. Trigger: when HVAC mode changes to..
2. Condition: and HVAC mode is..

This will be the best guess regarding the heating/cooling state of your heating system. If this is not the functionality you desired, please let me know.

Will be included in next release of the app v1.0.3.

**Comment by Starf0x** [comment]
I seem to notice that I'm not able to change the temperature?? Is this a new issue and should I add it to the list? I tried to drag the nest action to the 3rd flow column, but it will not stick. I'm only able to use the Home and Away option, Firmware 0.9.1.

**Comment by RobinBol** [comment]
You need to drag the Nest Thermostat device (not the app) to the third column (it is placed below the app, in the devices section)!
