### ISSUE TITLE
Testing a flow does not apply "then card" timeouts

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#437]
**What is your Homey version (Settings → System)?**
0.8.29

**What did you try to achieve?**
Turn on TV through IR -> wait 35 seconds -> Set channel to 9 through IR

*Please include detailed steps how we can reproduce the issue*
While executing this flow through the test-button both actions execute at the same time. When used with a trigger these execute fine. Also, when creating a duplicate remote and using that to select the channel it runs as it should with the test-button.

Also see:
https://forum.athom.com/discussion/comment/16367/#Comment_16367

**Comment by WeeJeWel** [comment]
So... when using 'Test' the delay is ignored, and when Homey runs the Flow 'normally' the delay is used? Or am I reading this wrong?

**Comment by bvdbos** [comment]
yes, that's what I meant. This works with the new IR in 0.10.1 though...
