### ISSUE TITLE
devkit cant be Get anymore

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#438]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
to open devkit with homeyip/manager/devkit/
*Please include detailed steps how we can reproduce the issue*
see above

**What was the result?**
Cannot GET /manager/devkit/
...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by matjaz** [comment]
Looks like it was removed. You can see same result with `athom project --run`

It looks like api method was also removed
https://github.com/athombv/node-athom-cli/blob/e4819859499294163a51f396a5b78efb54b96702/lib/project.js#L269
`api('GET', '/manager/devkit/log/')` returns 404.

**Comment by WeeJeWel** [comment]
Yes, it's removed. Logs are streamed from stdour and stderr now, works a lot better :)
