### ISSUE TITLE
fail to login

### ISSUE THREAD

**Issue by mirakels** [athombv/homey#44]
After entering details for userid/password I cannot logon to homey.
Using  its ipiaddress  to directly connect allows me to select the userid but then I get the message

     This user does not have access to this Homey.

Login on to my.athom.com shows me:

      You don't have access to any Homeys. Buy one »
     
Teh homeysetup wifi network is go one so I cannot resetup. So seems I'm stuck while homey shows its dancing rainbow.

**Comment by WeeJeWel** [comment]
Are you sure you connected the same account during setup.athom.com?

You can always setup again, see the forum's Getting Started Guide for instructions.

**Comment by mirakels** [comment]
Yes, managed to get things going after 2nd factory reset...
Thanks.

**Comment by WeeJeWel** [comment]
Great!
