### ISSUE TITLE
Flows with apps from the store, stop working after a while

### ISSUE THREAD

**Issue by scanno** [athombv/homey#441]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

I have some apps installed and included them in a few flows. After a while the flow stops working. When looking at the flows the apps included are not shown. This is with the Marantz App. In fact the whole Apps section in the flow editor is gone.

**What was the result?**

Flows with apps in them work not as intended after a while (memory issues?)

**What did you expect as result?**

That the flows would keep working correctly.

**Any other remarks**

After rebooting, Apps are shown again in the flow editor and also in the flows. The flows are also working again as intended.

**Comment by jabroersen** [comment]
I'm having the same issue!

**Comment by imtt1980** [comment]
Me 2

**Comment by WeeJeWel** [comment]
The app has then crashed. Please report the issue per app on the App's github page (can be found on the App Store).

**Comment by scanno** [comment]
@WeeJeWel If an app crashes, does it also take down the whole app section in the flow editor? 

The whole app section is now visible anymore. All apps are gone

**Comment by WeeJeWel** [comment]
No it shouldn't. You can check which apps are crashed in Settings -> Apps

**Comment by jabroersen** [comment]
No crashed apps are visible in the app section, but all apps don't respond anymore to the build in commands. Rebooting solves this every time...

In my case the apps are: iCalendar to voice, Buienradar and Wikipedia. All three with the same symptoms. With iCalendar, also the settings are gone. When rebooting, those are back.
