### ISSUE TITLE
Homey freezes with white light

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#442]
0.8.29

x.x.x

**What did you try to achieve?**

Nothing
Probably "false positive" triggered Homey, because the white light looks like the "speech processing"-Indicator.

**What was the result?**

Homey freezes with white (slightly dimmed) light.

**What did you expect as result?**

...

**Any other remarks**

Logfile after a reboot: 56A2E06FC9

**Comment by peaoo** [comment]
Just happened again. (0.8.30)
I asking the (multisensor-messured) temperature with the built-in command. It worked a few times, but suddently...
Error-Log: 9D9CC516EC

Anyway, this error seems to be very rare.

**Comment by peaoo** [comment]
And again :(


9459CD13D0

**Comment by bvdbos** [comment]
It just did a recovery with full wipe with the radio on. Before there were 250 false-positives an hour, after a recovery with keeping settings nothing changed. After a recovery without keeping settings there were no false positives at all...

**Comment by peaoo** [comment]
I did this aswell. But the error remains. Just happened again, and it was not a false positive. Something freezes when homey proceeds the spoken words or is going to speak by itself. I have my homey in english.

60E016BD84

**Comment by Yamahaa** [comment]
I have also the white turning ring after speech. And will not react on voice again

**Comment by RoadXY** [comment]
Then it's waiting for response from the speech-to-text servers.
Wifi is stable and fast enough on the place where Homey's at?

**Comment by Yamahaa** [comment]
Its a bug. It is not waiting. Its an error. It has a blilliant wifi connection and internet connection. A reboot will not help also not (de)installing apps ONLY a total new setup (with erease data) will help....for some time.

**Comment by peaoo** [comment]
Happened again with .34. After a voice command ("What is the time?") Homey freezed white.

**Comment by WeeJeWel** [comment]
@peaoo I suppose this log is from after a reboot?

**Comment by peaoo** [comment]
Yep, when homey freezes with the white light i am having no access to it via my.athom or local ip.

**Comment by Yamahaa** [comment]
Today with my homey also agin The different is that i can reach homey with own ip and myathom but speech is broken. It works only for 15 minutes than suddenly after a ok homey no orange red listening ring but 5 seconds nothing than a spinning white led thet never stops. I still can ise homey with internet. Bet speech is broken. Only a full new setup will fix it for copple of minutes. Grrr

**Comment by Yamahaa** [comment]
Seems like it is solved in .34 have nou uptime 370000 with no problems...

**Comment by peaoo** [comment]
Unfortunately the white light freeze occured yesterday again. (.34). But since the update i had a lot of other freezes (static rainbow) they seem to be gone now.

**Comment by peaoo** [comment]
This Issue seems to be solved, but I've got the "same difference" now rainbow-colored. #690
