### ISSUE TITLE
SUGGESTION: Enable copying of flows

### ISSUE THREAD

**Issue by bliekp** [athombv/homey#443]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Sometimes several flows are very similar. 
It would be great to have an option in the flow editor: copy flow. You can then use the current flow as a template for a new one.

**Comment by WeeJeWel** [comment]
This is going to be added in 'Better Flow Management'

**Comment by bliekp** [comment]
Thanks Emile. Very eagerly awaiting that improvement. Any idea when? :)

**Comment by freemann** [comment]
Maybe its an idea to keep tickets open until the feature is launched so we can keep track?

**Comment by WeeJeWel** [comment]
Fixed in 1.1.2
