### ISSUE TITLE
Suggestion : More complex flows

### ISSUE THREAD

**Issue by jaxc0402** [athombv/homey#444]
Homey version 0.8.29

x.x.x

**What did you try to achieve?**

Make more complex flows

_Please include detailed steps how we can reproduce the issue_

Is it possible to make a flow working with an 'or' or an 'else' function?
I would like to trigger my sunscreens by voice if wanted 'or' by time (or sun down)? 
How can i manage this ??
Or do i need to make 2 (or more) different flows?

**What did you expect as result?**
Flows are more stream lined, less flows needed

**Comment by WeeJeWel** [comment]
`else` is going to be introduced in Better Flow Management

**Comment by jaxc0402** [comment]
What about multiple starts for the flow 'or' function?
Not limited to only 1 flow starter...

**Comment by WeeJeWel** [comment]
That would interfere with the tokens (the black draggable thingies). Suggestions?

**Comment by jaxc0402** [comment]
You now have (If - And - Then)
Cant you add an extra colom (If - Or - And - Then) ?
In stead of multiple inputs in the ' If '  colom ?

**Comment by MartijnHarte** [comment]
Why would this interfere with the tokens Emile? Every card has it's own tokens and can be dragged independently?

**Comment by WeeJeWel** [comment]
Imagine this flow:

When
- Someone came home {who}
- It's sunset {time}

Then
- Say {who}

What will happen here when sunset triggered, and {who} is undefined?

**Comment by rlijkendijk86** [comment]
IF | OR | AND | THEN | ELSE
--------
ELSEIF 

Would be nice if you ask me, would enable a lot of possibilities creating flows :+1: 
Or create some sort of Fibaro like solution: Flow editor for basics flow, advanced section with some LUA like scripting possibilities for the advanced users.

**Comment by MartijnHarte** [comment]
I see the problem. That's a tricky one.

Perhaps it's the easiest to let the flow test fail if there's a possibility that a token isn't defined? An addition might be the ability to set default values for tokens per flow?

Another option might be to ignore cards with undefined tokens, but that might become very confusing.

I don't know a silver bullet solution at this moment though..

**Comment by jaxc0402** [comment]
> 
Imagine this flow:

When
•Someone came home {who}
•It's sunset {time}

Then
•Say {who}

What will happen here when sunset triggered, and {who} is undefined?
> 

The flow should start running on both triggers seperatly, if i woulf use 10 'if' triggers, then if 1 trigger is activated, the flow should start. (my opinion.....) 
meening a flow can be triggerd in different ways, in stead of having to make 10 different flows.

**Comment by Dijker** [comment]
@jaxc0402 
I Like your idea but how do you see it for the following flow? 
What should the software engineer put in the <Time] and <Who] tokens ? 
![image](https://cloud.githubusercontent.com/assets/12412734/14474053/57332c10-00fb-11e6-9565-1eeed2d34530.png)

When I come home:  Homey says "Hello Geurt, it is undefined" ?   
or when sunrise starts Homey Says: "Hello Undefined it is 06:25" ?
This will make defining logical flows  difficult.

But I like it when it would be possible: 
fe If SunriseStarts OR AlarmXYZ then ... 
Because both produce a  token <Time]  I think it would be possible. 
Also if in the example above the Someone Came home trigger would produce a  token <Time]  it would be possible to trigger something (fe say the time)  but the <Who] token would be unavailable because the Sunrise doesn't provide this token (so you are stuck to the "common divisor" of tokens)

**Comment by freemann** [comment]
In most cases the "Who" isn't important. In the cases of sunset its _not important who_ is home, its important that someone is (not) home and the light need to go on.

We both like Q-music, so if someone is coming home, we would like the radio to turned on to Q-music.

If one of us comes home AND (sunset OR dark (thundercloud)) THEN lights on.

So the tags are great fun and could in some cases add value to the speech, but in a lot of cases the tags are not really important of necessary.

Maybe its an idea to let the user decide if (s)he wants to use a card or make a flow with or without tags.

**Comment by Dijker** [comment]
@freemann 
Nice Example, 
>> If one of us comes home AND (sunset OR dark (thundercloud)) THEN lights on.

but this uses one trigger, and an OR between two conditions in the And ... Column.
I think that is also a nice enhancement to flows!

@jaxc0402 and @WeeJeWel  where discussing the multiple triggers (if...) in one flow. 

it isn't about if Tokens are not really important or necessary for you.
they are often important and part of the syntax, as log as Homey dosn't hav an IQ of 180 it cant decide if it is not important. I don't like to lose tokens!. 

But can you create a syntax for that while it is still consistent to work with? 
If a token is availabel in the first optional trigger but not defined by the second or third trigger can you use it while making these simple flows consistent?

**Comment by jaxc0402** [comment]
@Dijker Why would i make a flow like :
if
•Someone came home {who}
•It's sunset {time}

I could better use 'and' for this case.

i wouild like to see : 

If 
* something is said ###
* it's sunset
* other flow is triggered (like watch TV)

Then
* lower sunscreens

Now i would need 3 flows for this.

**Comment by BartOtten** [comment]
Thinking about this and writing examples...I think LUA support would do :P Some things just can't be done in a GUI but advanced users really want to make use of variables, arrays etc etc

**Comment by freemann** [comment]
Homey is build around (node)JS, so JS would be a more "natural" choice.
But I agree, some more flexibility for the advanced users would be very great and in my eyes necessary to (keep) bind Advanced users.

**Comment by Bumblez** [comment]
How about 'or' functionality just on the second column, then? Then you will at least know for sure, that the triggers from the first column are always available...

**Comment by bvdbos** [comment]
That's two steps ahead :-)
The first column could be used as an "and" and the second column as an "or" as a first step:
If ( [condition A] and [condition B] ) or [condition C] or [condition D] then [action]

**Comment by Dijker** [comment]
@bvdbos 
I tried coming home exactly at sunrise but that didn't work although I was only seconds to late or to early  ;-)

The first column can't be an AND. The cards in the first column are triggers (they trigger at something that happened) All conditions come in the second column and are all AND to each other and the trigger (or if you want AND NOT if you check the box....)

So the syntax is:
On  ( _exacly_One_ Trigger_Event_in_Column_A )  
AND 
          ( [NOT] Condition1_in_ColumnB  
          [AND [NOT] Condition2_in_ColumnB ] 
          ... 
          [AND [NOT] ConditionN_in_ColumnB ]  )
THEN DO
          [Delayed n sec/min] Action1_in_ColumnC 
          [Delayed n sec/min] Action2_in_ColumnC 
              ....
          [Delayed n sec/min] ActionN_in_ColumnC 

I would like multiple Triggers in Column A, they are "OR-ed"  - Example:
ON  I_LeaveHome OR MyGFLeavesHome
AND
       NobodyATHome
THEN DO
      TurnHeating Off

But alle Triggers need the same Tokens (See Comment @WeeJeWel  https://github.com/athombv/homey/issues/444#issuecomment-208309049 )

and I would like an OR "Line" and (parenthesis) to put between Conditions in ColumnB - Example:
ON  I_LeaveHome OR MyGFLeavesHome
AND
       NobodyATHome AND (Dark OR (AfterSunSet AND BeforeMidNight) )
THEN DO
      TurnBurglarMisleadingTVSimulator  ON

 (I know it isn't the best example as in this case I can do the same without.... but you get the idea? )

**Comment by matthijsvdr** [comment]
Any update on the Better Flow Management ?

**Comment by sjome** [comment]
They can introduce some error checking before the user can save the flow by forcing him/her to push  "Test" button before they can save the flow.
By this testing the system can show the error by placing a red triangle in the card where the error occurs and give an explanaiton of this error when the user  hovers whith his mouse  over this triangle.

This kind of error handling is common in most programmering languages and is not so difficult to understand.

**Comment by Gand41f** [comment]
> That would interfere with the tokens (the black draggable thingies). Suggestions?

With the global tags multiple triggers should be possible now, because the tokens should be always defined now, right?

**Comment by WeeJeWel** [comment]
For actions, 'else' has been added as of v1.3.0

**Comment by madela** [comment]
And "OR" is going to be included?

**Comment by mruiter** [comment]
All in good time I guess...

**Comment by goyaweb** [comment]
Multiple flow triggers. 
I read above that this won't be made possible because it would result in tags being undefined.
I just checked my flows but in 95% of the flows the tag is not used or a card without tag is used.
So in 95% of the flows (in my case at least) allowing multiple triggers would not be a problem.
Hope you can reconsider.

**Comment by robiebab** [comment]
Or you check if the "if" has a card/token attached to it and check if other cards in other flows need it, if sow make a exclamation mark on save. User can still save except it is warned about possible dead code

**Comment by jaimevisser** [comment]
When adding a second trigger, remove all trigger based tags and only allow using global tags. User will have the choice to either make flows with trigger based tags or flows with multiple triggers. You could add warnings when trigger based tags are already in use in the flow when adding a second trigger.
