### ISSUE TITLE
Suggestion: Card to switch all type of devices in a specific room

### ISSUE THREAD

**Issue by Rido** [athombv/homey#445]
**What is your Homey version (Settings → System)?**
0.8.29

**What did you try to achieve?**
A card to switch all type of devices in a specific room.

Example flow: 

> If the sunset starts then turn all lights on in the living room.

**What did you expect as result?**
Less work in creating flows.
This is much better then adding all lights individually from the living room to your flow.

**Comment by Arjanvde** [comment]
#275 :-)

**Comment by freemann** [comment]
275 = selecting a zone to do some magic with
445 = a card on which a device type in a zone can be selected to do some magic with.

To me(!) that's a (big) difference.
