### ISSUE TITLE
Installed app with debug logging stops working

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#446]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Run an app in regular (non-debug) mode, which still outputs debug logging.
Example app attached. When the function calls to 'debug' (in driver.js) are removed, the app does continue to run. App installed with `athom project --install stress.app`.
[stress.app.zip](https://github.com/athombv/homey/files/213583/stress.app.zip)

**What was the result?**

App stops working after some time.

**What did you expect as result?**

App just continues running.

**Any other remarks**

Maybe related to /manager/devkit being removed?

**Comment by WeeJeWel** [comment]
Does this still happen on 0.8.30?

**Comment by nlrb** [comment]
Can try this again later. Have you not been able to reproduce it with the attached app?

**Comment by nlrb** [comment]
For what I understood on Slack you found the bug and it is solved in 0.8.31, right?

**Comment by WeeJeWel** [comment]
Should be!

**Comment by nlrb** [comment]
Confirmed fixed.
