### ISSUE TITLE
Custom capabilities should also be supported from app.json.

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#447]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Add a device custom capability in the app.json, as described on https://developers.athom.com/library/drivers/capabilities/

**What was the result?**

None. No error, no effect.

**What did you expect as result?**

That the custom capability is added to the device.

**Any other remarks**

Can apparently only be done from the code, not from the app.json. For consistency, it should also be possible from the app.json.

**Comment by DiedB** [comment]
I can't seem to get this working from the code either, however I am not using the list_devices template.

**Comment by nlrb** [comment]
@DiedB Maybe it does work, but you don't see it. The custom capability does not show up in the UI. I.e. it is not visible on the mobile card or in Insights. But e.g. the 'get' function should get triggered when opening a mobile device card.

**Comment by DiedB** [comment]
@nlrb That might be the case, it does indeed not show up in the card or in Insights, but I don't get any errors either. I'll use predefined capabilities for now (with slightly wrong titles and units).

**Comment by WeeJeWel** [comment]
I agree. Will add this later.

**Comment by markaswift** [comment]
Any news on this issue guys?

**Comment by markaswift** [comment]
@WeeJeWel We really need this, any ideas when you can squeeze it in?

**Comment by WeeJeWel** [comment]
Why is the need so high? Just load them somewhere in your driver.js :-)

I'm still going to add them, don't worry though!

**Comment by gruijter** [comment]
@WeeJeWel : Any news on this? I'm also waiting on being able to add custom capabilities to a device, especially where it will also automagically log for insights. Since also manually logging for insights is not possible for a device (see https://github.com/athombv/homey/issues/706 ), I have no means of handling and logging a custom capability in a way that is useful in the real world.

**Comment by WeeJeWel** [comment]
Expect it within a few weeks :-) Currently I'm fulltime on Z-Wave, after that I can (finally) continue working on Homey's core.
