### ISSUE TITLE
Homey couldn't interview Fibaro FGK-101 Door/Window sensor v2.1

### ISSUE THREAD

**Issue by dvanp** [athombv/homey#448]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Include Fibaro Door/Window Sensor FGK-101 v2.1

**What was the result?**

Your Z-Wave device could not be interviewed. The device has been added as a basic device.

**What did you expect as result?**

The sensor added as a Alarm/Generic alarm device

**Any other remarks**

Log: 46AFD60C3A

**Comment by ocatie** [comment]
Same cause as #410, working on it.

**Comment by freemann** [comment]
Here the same issue. 
See system log: 5818CEE72F

**Comment by dvanp** [comment]
Just updated to 0.8.32, but issue persists.
Log: CBFEA4248C
