### ISSUE TITLE
Homey dead after update

### ISSUE THREAD

**Issue by matthijsvdr** [athombv/homey#449]
**What is your Homey version (Settings → System)?**

8.24 trying to update to 8.29

**What did you try to achieve?**

8.24 trying to update to 8.29
Manual update (automatic update didn't do anything)

**What was the result?**

Homey is dead, led ring is burning red

**What did you expect as result?**

working update

**Any other remarks**

No

**Comment by bvdbos** [comment]
How did you try to do a "manual" update? commandline?

**Comment by matthijsvdr** [comment]
@bvdbos disable automatic update, if an update is available you get an update now button (or something like that)

**Comment by matthijsvdr** [comment]
Some extra info, i was on the regal stable updates and not the experimental one.

After an hours and 30 min i unplugged homey, when plugging the power back in, homey spins orange, but does nothing else until it goes burning red again

Trying to recover by holding it upside down does not work it goes red again.

Also the forum topic for usb recovery seems to be removed? :( :-1: 
When powering homey on while holding it upside down homey goes into the spinning purple mode, if i remember the usb recovery.

**Comment by freemann** [comment]
you need to power homey on while its on his legs and after a few seconds turn it upside down.

**Comment by stefanwitkamp** [comment]
Hi @matthijsvdr, you can redirect your questions to support@athom.com, so we can help you get your Homey up and running again :).

Best,

Stefan
Athom

**Comment by matthijsvdr** [comment]
@freemann yes i know
@stefanwitkamp done

**Comment by freemann** [comment]
@matthijsvdr 
I said it because you wrote:
**When powering homey on while holding it upside down**

Thats not the procedure.

Please follow Stefan's instructions, its the best way of support when you having serious Homey troubles!

**Comment by matthijsvdr** [comment]
@freemann i also wrote 

> Trying to recover by holding it upside down does not work it goes red again.

And if you quote then do the whole sentence

**Comment by freemann** [comment]
Dear @matthijsvdr

I can't help it that you homey show a red ring. I try to help and i quote that part of your sentence because thats not the way to start the recovery procedure. 

Your post/sentence indicates you power homey up when it's already upside down. 

Homey needs to stand on his legs when you powered it up. Then wait a few seconds and then turn homey upside down. Then homey should start the countdown.

**Comment by WeeJeWel** [comment]
Please contact [support@athom.com](support@athom.com).
