### ISSUE TITLE
Setup screen has no option to reset password

### ISSUE THREAD

**Issue by hilvarenbeek** [athombv/homey#45]
When you run Homey's first-time setup, you are prompted to log in or create a new account. When you already have an Athom account but enter the wrong password, there is no option to reset the password like there is at https://accounts.athom.com and no further help.

**Comment by kimror** [comment]
Are you sure you have an Athom-account. Keep in mind that this is a separate account from the forum-account.

What is you error message when you try to log in at [](https://accounts.athom.com)?

If you have a account already, the error message should be; **The entered password is not correct. Forgot your password?** (And a link to a password forgotten page).

If you do not have an account, the error message should be; **A user with this email address does not exist.**

**Comment by WeeJeWel** [comment]
Will be added
