### ISSUE TITLE
Zwave / KAKU weirdness

### ISSUE THREAD

**Issue by scanno** [athombv/homey#450]
**What is your Homey version (Settings → System)?**
0.8.29
**What did you try to achieve?**

A KAKU switch being a KAKU switch and not a ZWave device.
I have 1 KAKU build in lightswitch and one dimmer.
I have 2 Greenwave powernode 6 

All was working pretty ok until yesterday. The powernodes stopped being recognized with the messages:
- PRIOR_TANSMIT_NO_ACK
- TRANSMIT_COMPLETE_NO_ACK

I have reset the zwave chip many times.
I have tried to refresh the nodes many times, but no luck.
I have tried rebooting, but no effect.

**What was the result?**

Not able to control the powernodes from homey.
Not able to control the KAKU lightswitch. Whe trying to swith the light on or off, i get a zwave settings screen from one of the powernode 6 sockets.

![screenshot from 2016-04-13 21 38 14](https://cloud.githubusercontent.com/assets/637981/14507014/00f29a18-01c1-11e6-8e4e-6c6c7c853774.png)

**What did you expect as result?**

Being able to control my KAKU switches and Zwave powernodes

**Any other remarks**

...

**Comment by ocatie** [comment]
Could you explain what you mean by "A KAKU switch being a KAKU switch and not a ZWave device."?

If a device becomes unreachable with the message TRANSMIT_COMPLETE_NO_ACK or PRIOR_TANSMIT_NO_ACK, Homey tried to send data to your device but the device couldn't be reached. There are several ways to make your device available again. The most common are selecting it in the dropdown and pressing the Refresh Node button or rebooting. On startup Homey tries to fetch the state of all connected Z-Wave devices.

If the device becomes unavailable after a reboot and the device still can't be reached. You could try moving the device closer to Homey.

**Comment by scanno** [comment]
@ocatie 
The zwave device is one meter away from homey. As I mentioned all known methods do not work. Rebooting does not work,  refreshing the nodes does not work. 
The Kaku device shown in the picture,  when  trying to use it,  is showing g the zwave settings of one of the zwave sockets.

**Comment by scanno** [comment]
Perhaps some more clarification. When trying to switch the light on/off by using the device picture, instead of showing the on/off switch, it is showing the zwave settings page of another device (in this case socket 6 of my not working Greenwave power node 6)

**Comment by jghaanstra** [comment]
@scanno ,  could you check the video in [this issue](https://github.com/athombv/homey/issues/242) and confirm it's the same bug?

**Comment by scanno** [comment]
@jghaanstra 
Looks very simular. It also seems to get worse and worse. Now i cannot react anymore with my KaKu/CoCo devices.

![image](https://cloud.githubusercontent.com/assets/637981/14553693/3c6e434e-02e8-11e6-9453-38fbe5bd817f.png)

**Comment by Dijker** [comment]
@scanno 
I think you missed this one?
https://github.com/athombv/homey/issues/392#issuecomment-210084719
there was a mayor update! I think it impacts your configuration too

@Dennishacq 
Mabey inform users of the app about the update?

**Comment by freemann** [comment]
Maybe a closed announcement topic where this kind of new can be shared?

Also push notifications in Homey GUI about major news/fixed/changes in Homey or Apps?

**Comment by scanno** [comment]
@Dijker Thanks for the headsup. So i need to readd them. 
It is a bit hard to see if this was related to my original issue, since it is ui related.

**Comment by Dijker** [comment]
@scanno 
I am not sure, I think the KAKU App update affects everyone with the KAKU app, 
Lets Ask @Dennishacq to confirm this... Think he will know ;-)

**Comment by Dennishacq** [comment]
The Update does indeed affect everyone that has the app installed. I've made a lot of changes in how the app works which unfortunately makes it incompatible with the previous versions.

**Comment by jaxc0402** [comment]
Kaku stopped working with 0.8.30 update?

**Comment by Dennishacq** [comment]
@jaxc0402 Could you describe what's not working anymore?

**Comment by jaxc0402** [comment]
Yesterday nothing was working anymore. After a hard reboot (pull power plug) everything seemed to be working OK, but after couple of min/hours all 434 and 868 Mhz seems to be down (chip crashed according to athom, they inspected the crashlog) They will investigate this next week.

@ 0.8.29 i could pair : APA3-1500R power plug
@ 0.8.30 i first have to pair the plug with my remote, and then i can teach the remote channel to Homey..
takes some extra effort.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jaxc0402** [comment]
@jeroenvollenbrock First time (yust tested) after trying to install APA3-1500R homey crashed and KAKU was unaivaible.. After a hard reboot. PTP (Pull the plug) everything worked OK, and pairing APA3-1500R worked OK.

**Comment by scanno** [comment]
@jeroenvollenbrock The original issue has been solved as that had to do with the fact that settings could not be reached any more in the Web interface and the wrong interface. 

Sadly I cannot test anything right now because of the zwave problems and my Kaku issues. My homey is switched off until I can get something working again.
