### ISSUE TITLE
KAKU - Button's 2 & 3 and Channels II & III - AYCT-102 Flowcards exchanged 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#452]
**What is your Homey version (Settings → System)?**

0.8.29 / KAKU app v1.1.0

**What did you try to achieve?**
Trigger on push button of Remote

*Please include detailed steps how we can reproduce the issue*
Add AYCT-102 (and test while pairing =  OK!) and create test flow.
![image](https://cloud.githubusercontent.com/assets/12412734/14543480/982680ec-0294-11e6-8506-ad27840125ff.png)

**What was the result?**
Button 2 did not react, flow for button 2 triggered on Button 3 and vv.
Tested the channels also, and same, Channel II  triggers on the Switch/buttons  of III and vv

**What did you expect as result?**
I already expected the channels also exchanged after discovering the exchanged buttons ;-) 

**Any other remarks**
@Dennishacq 
At least a consequent mistake ;-)

**Comment by Dennishacq** [comment]
Oh wow, that's embarrassing. 
I'll fix this tomorrow.

**Comment by Dennishacq** [comment]
The new update is online :)
