### ISSUE TITLE
speech recognition distance

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#453]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Dutch voice recognition enabled

voice recognition is working quite well when I am in 1m distance from the homey, when I move further, 3 m distance, it is not recognizing what I say anymore

nothing is shown in the speech-input screen

**What was the result?**

see above

**What did you expect as result?**

voice recognition in the whole living room

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
We're working on improving the speech. I'm closing this issue as it can't be 'solved' :)
