### ISSUE TITLE
Fibaro Wall plug

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#454]
**What is your Homey version (Settings → System)?**

0.30

**What did you try to achieve?**
Add fibaro wall plug

*Please include detailed steps how we can reproduce the issue*
Add plug and reboot 

**What was the result?**
Timeout on fibaro wall plug
...

**What did you expect as result?**
Working fibaro plug 
...

**Any other remarks**
log : 5F1A078197
The TKB / fibaro pir works after reboot and are added OK (choice device type) not as on/off device as the fibaro wall plug that fail.
...

**Comment by ocatie** [comment]
Same cause as #410, working on it.

**Comment by ocatie** [comment]
I'm contacting Fibaro about this one. I'll let you know when I know more.

**Comment by djeskoswe** [comment]
No go after update to 0.35 reboot !  , did you get any response from fibaro ?  @ocatie 

log : 200E72043F

**Comment by ocatie** [comment]
Yes I did, in some firmware versions the Sensor Alarm Supported Get command isn't answered. This causes the interview to fail with certain Fibaro devices. We're looking how to work around this with the new driver.

**Comment by djeskoswe** [comment]
@ocatie 

Any update o need to wait for the new zwave build ?   reason im asking is that some people get it to work : https://forum.athom.com/discussion/1126/fibaro-wallplug-fgwpe-f-101#latest

My plug always get added as generic and then die after reboot as before.

Thanks
