### ISSUE TITLE
KAKU is not responding after update to 0.8.30

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#455]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
Light on via a flow
*Please include detailed steps how we can reproduce the issue*
sunset trigger, but lights are not responding via KAKU

**What was the result?**

.Light stays out.

**What did you expect as result?**
Lights ons.
...

**Any other remarks**
Also via the website and directly kaku is not responding

...

**Comment by bvdbos** [comment]
did you re-pair the kaku-devices?

**Comment by CootNL** [comment]
After rebooting several times, reinstall and new paring the KAKU is working again.
