### ISSUE TITLE
Unable to pair Z-wave multisensor device

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#457]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Pairing a Z-wave multisensor device (Everspring ST-814)

*Please include detailed steps how we can reproduce the issue*

Initiate pairing on Homey
Initiate pairing on device

**What was the result?**

Device found, Interview 1/3

And then in most cases, it stops and adds the device as a  generic on/off switch & crashes the Z-wave chip.  Sometimes, after a 1-2 minute wait, it goes to Interview 2/3, but then same result: generic on/off switch & crashing of the Z-wave chip. 

Log: 1BDD13EE66

**What did you expect as result?**

Successful pairing of the multisensor device. Pairing succeeded in 0.8.29 . 

**Any other remarks**

A Fibaro motionsensor (with motion, lumen and temperature sensing) was added successfully in 0.8.30 ; this is recognized as one device, not with sub-nodes.

**Comment by ralfvd** [comment]
Update: on 0.8.32 pairing is possible, although one subdevice gives: "Sensor type not found": 

Log 5EE4C572DB

And in the console log of Chrome: api.js:1 GET http://192.168.89.25/api/device/7bc48565-da94-4011-8176-3ebe65fc707c/?_=1461744800927 500 (Internal Server Error)

![screen shot 2016-04-27 at 10 11 30](https://cloud.githubusercontent.com/assets/17275712/14846146/72b068aa-0c62-11e6-8a23-79dcae348979.png)

**Comment by djefmo** [comment]
Same problem here. Pairing works, however the humidity sensor gives the same error as described by @ralfvd

**Comment by ocatie** [comment]
Found issue, working on fix.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
