### ISSUE TITLE
Fibaro FGK001 z-wave door/window sensor not found

### ISSUE THREAD

**Issue by Blusser** [athombv/homey#458]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
Add Fibaro window/door sensor

*Please include detailed steps how we can reproduce the issue*

Follow the including procedure from the manual with 2 different sensors
It did not make a difference if I tried to add the sensor close to Homey (< 1 mtr)

**What was the result?**

No device was found

**What did you expect as result?**

A new z-wave device (window/door sensor) found

**Any other remarks**

FGK001 which had just worked fine with Fibaro HCL lite running 4.080 before excluding it en attempt to add it to Homey

**Comment by ocatie** [comment]
Did you clear the network data from the device? You can do this by running a Remove Node process prior to adding the device to Homey.

**Comment by Blusser** [comment]
I succesfully reset the network configuration following procedure at https://www.youtube.com/watch?v=9TmCgXEhEtY

but with multiple sensors still the same problem, no device found

by the way adding fibaro wall switches and motion sensors without a problem

**Comment by ocatie** [comment]
Does the pairing wizard hangs during the interview or does it wait for a device to be presented? If the wizard hangs during the interview please send a log, otherwise first run the Remove Node process.

**Comment by Blusser** [comment]
upgraded to 0.8.32 and still the same issue, it hangs during the interview.
uploaded log F1BB53BC35
