### ISSUE TITLE
Eurotronic Comet Z-wave valve not found

### ISSUE THREAD

**Issue by Blusser** [athombv/homey#459]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Add a Eurotronic Comet Z-wave valve to the system

*Please include detailed steps how we can reproduce the issue*

following the including procedure from the manual

**What was the result?**

No device found

**What did you expect as result?**

New z-wave device found 

**Any other remarks**

including fibaro wall switches is going fine
...

**Comment by ocatie** [comment]
Did you clear the network data from the device? You can do this by running a Remove Node process prior to adding the device to Homey.

**Comment by Blusser** [comment]
Please close this ticket, the reset procedure was not clear to me so I though I had reset it (but I didn't), but after try 13532 I finally understand it right, managed to reset it the right way (by using the exclusion mode of homey first), and then add it to homey successfull.
Now figuring out if all is working, if not I'll open a seperate ticket.
Thanks for helping.
