### ISSUE TITLE
Danfoss LC-13 connection loss

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#463]
**What is your Homey version (Settings → System)?**

.30

**What did you try to achieve?**

Every morning I realise that my Danfoss-LC13 valves seemed to lost connection to Homey. They are displaying the E5-Error.
![lc13](https://cloud.githubusercontent.com/assets/17235241/14586991/c10ffb70-04a9-11e6-902d-03ec10ad2c00.png)

I tested it again and after 2 hours the E5 error popped. During this time I did nothing with homey. After going to Settings -> Z-Wave I realised that the drop-down menue in the "Failed section" dissapeared ( Issue #396  ) but I don't know if there is a relation to it.
![dropdown](https://cloud.githubusercontent.com/assets/17235241/14587002/1405ede4-04aa-11e6-923a-ac96c8a31e44.png)

After resetting the z-wave the error disappeared and the dropdown menu is back.

**What was the result?**

Thermostat seems to lose connection after ~2 hours. With a reset I could've fix it

**What did you expect as result?**

Stable connection

**Any other remarks**
Log:
0C12EA09E3

11:45 = After a reboot everything is working
~14:00 = Connection loss was noticed and restarting z-wave fixed it.

**Comment by mruiter** [comment]
Same for Danfoss LC-12n. loosing connection over time.

**Comment by peaoo** [comment]
I realised something a minute ago:

When I "freshly" resetted the z-wave network, there is almost no delay between pushing a button at the thermostat and the wakeup of the display, including displaying the temperature.

When some time passed by and I try this again it takes a little bit longer to show the digits (light switches on instantly). 
An when it is time for the E5-Error I am waiting ~10 seconds until it is displayed.

I guess the time between the button-press + display-light switches on and the temperature displayed   is caused by the thermostat connecting to Homey. And when it finally gets no answer it displays the E5.

If this is correct then the increasing delay is something to investigate aswell.

Hope that helped.

**Comment by peaoo** [comment]
Seems to work for me after .32 . No more connection loss.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
