### ISSUE TITLE
Homey not able to receive (multi) sensor data, only with polling or wakeup

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#464]
**What is your Homey version (Settings → System)?**

0.8.30
Fibaro FGMS-001 Motion Sensor, v2.7

**What did you try to achieve?**
More frequent update (initiated by the motion sensor itself) on Luminance (and Temperature) to be able to define a flow switching on the lights once luminance is below a certain limit.

Modified the following parameters for the Fibaro Motion sensor
<img width="626" alt="schermafbeelding 2016-04-17 om 20 35 52" src="https://cloud.githubusercontent.com/assets/17163431/14589213/92331e8a-04dc-11e6-8b9d-75c4fced9633.png">
The behavior of the motionsensor on the 8x parameters shows that the parameter update is successfull

**What was the result?**
Only updates shown / downloadable in Insights based on the Z-Wave wakeup interval (once every 7200 seconds)

**What did you expect as result?**
According to the parameters set, Homey should (be able to recieve) data from the motion sensor:
By a change of 2 lux (parameter 42: The parameter determines the change in light intensity level resulting in illumination report being sent to the main controller)
In any case (even in case there are no changes in the light intensity), once every 600 seconds (parameter 42: Time interval between consecutive illumination reports. The reports are sent even if there are no changes in the light intensity)

**Any other remarks**
Modifying the Z-wave wakeup interval would also continuously update the parameters (require more bandwith)
I also see similar behavior with other brands of motion sensors on the forum.

**Comment by ocatie** [comment]
It seems you don't have an association set. Without an association the device doesn't know where to send it's reports to. Type Homey's node id at group 3, press save, and manually wake up your device to push the setting to you device.

**Comment by TedTolboom** [comment]
@ocatie I tried multiple times to add Homey's node id (1) at group 3.
But if I save the parameters and manually wake up the motion sensor (to push the settings to my device) the setting in group 3 is gone. Any idea why this occurs?

**Comment by peaoo** [comment]
@TedTolboom
My fibaro sensors are working without any problems.
But I can confirm this. Saving the association to 3 (Value: 1) and triple-tap at the sensor results in an empty textfield. If you look at the info-icon in that textfield it states "The maximum number of nodes for this group is 0." maybe it has something to do with this.

**Comment by TedTolboom** [comment]
@ocatie I added node 1 to association group 3 as indicated and since I'm offsite, waited for the z-wave wakeup interval... and again the node 1 is removed as @peaoo indicated

Indeeed, the info-icon of the z-wave settings indicate that "the maximum number of nodes for this groupd is 0"

![homey_screenshot](https://cloud.githubusercontent.com/assets/17163431/14603858/8a2eaf6c-0570-11e6-8376-08784c2abca2.png)

@peaoo, what is the update interval rate for your fibaro sensors? With current SW (0.8.30), I only get updates either by Z-wave wakeup interval or manually triggered. Both are insufficient to get a descent luminance triggering.

**Comment by TedTolboom** [comment]
While setting-up the device, I did select "none" with the "Report to association group"...

On the forum, I now saw the remark: "Set "Report to association group" to 3 when setting the device up." 

Would this cause the blocking of adding Node 1 to Group 3? 
If so, I might remove the motion sensor and re-add it with this particular setting...

**Comment by peaoo** [comment]
@TedTolboom  I've got 3 Fibaro FGMS-001 Sensors, all with 7200s Z-Wave Wakeup interval.

When I did include the sensors to Homey I selected "Report to association group 3". That could be the reason why it is working for me. In your case I would try to readd it. But anyways it is buggy that the association disappears in the settings screen. Wasn't like this before.

**Comment by TedTolboom** [comment]
@peaoo once you selected "Report to association group 3", did you also add Homey's ID (1) to one of the Z-wave associations groups in the settings window?
I just re-added the motion sensor and selected "Report to association group 3"... Let's see if this helps...

**Comment by peaoo** [comment]
@TedTolboom  no, I did not change the settings after the initial inclusion. Just checked it, there are still no numbers in any of the fields.

**Comment by TedTolboom** [comment]
So next steps taken:
- removed (once more) the motion sensor
- reset motion sensor to default settings
   - LED's is blinking on motion (green) and tamper alarm is activated = default behavior
- added the motion sensor to Homey, with "Report to association group 3"
- Updated settings of the motion sensor
   - Add homey ID (1) to group 3
   - Add following parameters: 80,1,0;89,1,0;40,2,5;42,2,300 (according to [FGMS-001-EN-A-v1.01.pdf](http://manuals.fibaro.com/content/manuals/en/FGMS-001/FGMS-001-EN-A-v1.01.pdf))
   - Manually updated the motion sensor (3x click)
- LED behavior indicates that parameters has been updated (no blinking led upon motion, no tamper alarm)

Yet, group 3 remains empty and Homey is only recording data upon Z-wave wakeup interval (7200 seconds).... note: I rebooted Homey around 8:00 this morning based on a note on the forum that the motion sensor got working again after a reboot
![capture2](https://cloud.githubusercontent.com/assets/17163431/14636743/a39e4abc-062d-11e6-8572-f4ff2a88258a.PNG)

In addition, while awaiting the next (~12:30) wakeup cycle... 
I now see that the Z-wave network crashed: Log ID: DFE3A0F2D1
![capture](https://cloud.githubusercontent.com/assets/17163431/14636746/a7a72e30-062d-11e6-89ac-42e092537427.PNG)

Questions @ocatie 
1) How can I verify that "report to association group 3" was successfull? 
2) Is it possible that this is related or impacted by the "read-only bug of the temporary storage"? See my comment #462 
3) What are the settings you / Athom is using with this popular motion sensor?
4) What other tests can I perform to find the cause of this issue?

**Comment by TedTolboom** [comment]
Decided yesterday evening to a higher illumination update interval: 42: 300 -> 1800 sec.
Based on good experience as indicated by other users on the forum.

Now Illumination data is received by Homey and displayed into Insights:

`**Z-wave Configuration Data: 80,1,0;89,1,0;40,2,5;42,2,300**
Mon Apr 18 2016 19:25:49 GMT+0200 (CEST),36
Mon Apr 18 2016 21:26:45 GMT+0200 (CEST),4
Mon Apr 18 2016 23:27:37 GMT+0200 (CEST),2
Tue Apr 19 2016 00:35:52 GMT+0200 (CEST),4
Tue Apr 19 2016 01:28:37 GMT+0200 (CEST),0
Tue Apr 19 2016 07:31:14 GMT+0200 (CEST),14
Tue Apr 19 2016 07:57:49 GMT+0200 (CEST),14
Tue Apr 19 2016 09:31:57 GMT+0200 (CEST),258
Tue Apr 19 2016 10:03:08 GMT+0200 (CEST),161
Tue Apr 19 2016 12:59:49 GMT+0200 (CEST),161
Tue Apr 19 2016 13:12:06 GMT+0200 (CEST),220
Tue Apr 19 2016 13:33:33 GMT+0200 (CEST),206
Tue Apr 19 2016 15:34:21 GMT+0200 (CEST),83
Tue Apr 19 2016 16:21:07 GMT+0200 (CEST),186
Tue Apr 19 2016 17:35:11 GMT+0200 (CEST),290

**Z-wave Configuration Data: 80,1,0;89,1,0;40,2,5;42,2,1800**
Tue Apr 19 2016 19:08:28 GMT+0200 (CEST),91
Tue Apr 19 2016 19:42:50 GMT+0200 (CEST),33
Tue Apr 19 2016 20:17:11 GMT+0200 (CEST),13
Tue Apr 19 2016 20:51:32 GMT+0200 (CEST),1
Tue Apr 19 2016 21:09:21 GMT+0200 (CEST),4
Tue Apr 19 2016 23:09:04 GMT+0200 (CEST),0
Wed Apr 20 2016 07:10:37 GMT+0200 (CEST),15
Wed Apr 20 2016 07:14:05 GMT+0200 (CEST),16
Wed Apr 20 2016 07:45:01 GMT+0200 (CEST),34
Wed Apr 20 2016 08:19:25 GMT+0200 (CEST),83
Wed Apr 20 2016 08:53:50 GMT+0200 (CEST),133
Wed Apr 20 2016 09:28:11 GMT+0200 (CEST),246
Wed Apr 20 2016 10:02:35 GMT+0200 (CEST),336
Wed Apr 20 2016 10:36:58 GMT+0200 (CEST),294`

With 300 seconds interval, data every 7200 seconds = Z-wave wakeup interval 
With 1800 seconds interval, data every 2062 seconds (15% offset compared to actual settings)

@ocatie are there any limits (to the interval) within Homey to receive data? 
42:300 should be possible from Fibaro manual perspective and is a commonly used parameter setting with other domotica controllers (based on internet feedback)

I will lower the 42 parameter (-300 steps) for the next days to see if there is a turning point where data will no longer be received....

**Comment by peaoo** [comment]
I am having the same / similar issue with my D-Link Door/Window-Sensors. They are only sending their data if I wake them up manually. It's a Z-Wave Plus device.

**Comment by TedTolboom** [comment]
Conclusion after some days of testing (trying to optimize the reporting frequency):
1) motion sensor settings as entered in the settings window are updated (at least 80 and 89 provide a recognizable response)
2) Only with the report interval (parameter 42) at 1800, I get additional illum. data reports at an interval of on average 2062 seconds
3) any (!) other setpoint (e.g. 300, 600, 900, 1200 and 1500) will not provide any additional data reports; only at the Z-wave wakeup interval of 7200 seconds

For me, an illumination report once every half an hour is not good enough to trigger my lights to switch on.

Since at other fora / domotica controller it is possible (achieved) to get more frequent reports with the same sensor, it should lead to either an issue within Homey or in the communication between Homey and the sensor.

Below graphs show my illumination reports over the last 3.2 days... 

![homey_capture](https://cloud.githubusercontent.com/assets/17163431/14733922/099dff8e-0867-11e6-82b4-b9668aeb2a39.PNG)

As of yesterday evening, I did set parameter 42 back to 1800... and you see additional data points compared to the temperature logging. Note, it also is including 3x crash of Z-wave network / Homey (horizontal lines)

@ocatie Please provide your feedback. If relevant, I'm willing to do more experiments to further understand this issue.

@WeeJeWel Considering above and also the statement of @peaoo, please remove the "Zwave - device specific" label and assign this issue to one of your engineers

**Comment by ocatie** [comment]
The Fibaro multisensor supporting 0 devices on group 3 results in your association not being displayed. After you wake up the sensor the association is made. After that Homey fetches the state of the device. This includes the current associations. Because the sensor says it supports 0 devices Homey reads back no devices on group 3, so no devices are displayed. The association has been made though if the number dissapears.

The multisensor supports Wake Up command class version 1 so I can't read a minimum or maximum wakeup interval. The may however be a minimum or maximum.

**Comment by TedTolboom** [comment]
Update:
I've reduced the Z-wave wake-up time to 1200 seconds to get more frequent data points..

I do get quite a lot of times a "failed" message; where also the temperature and lux measurement points do not show in Insights

See below Insights curve for illumination, temperature and motion:
<img width="1157" alt="schermafbeelding 2016-04-26 om 16 43 38" src="https://cloud.githubusercontent.com/assets/17163431/14822356/a834c6c2-0bce-11e6-9db4-281c9ef9aa8a.png">

And in settings the sensor shows as "failed"
<img width="277" alt="schermafbeelding 2016-04-26 om 16 44 07" src="https://cloud.githubusercontent.com/assets/17163431/14822374/bb57a29c-0bce-11e6-95f2-7253963b3cbf.png">

This now happens 2-3 times a day... @ocatie any clue on what is causing this
Log file:
<img width="356" alt="schermafbeelding 2016-04-26 om 16 44 39" src="https://cloud.githubusercontent.com/assets/17163431/14822395/d63cfb52-0bce-11e6-892f-bcb47aafa876.png">

**Comment by TedTolboom** [comment]
Next Z-wave crash... now on 0.8.32

In below Insights overview, you clearly see that first Temperature fails, then Illumination... and now the device shows (failed) again...

<img width="1128" alt="schermafbeelding 2016-04-27 om 21 14 35" src="https://cloud.githubusercontent.com/assets/17163431/14865207/d7591cd8-0cbd-11e6-8f25-2ac41343711f.png">

Log file: 9CAFD8F708

@ocatie can you look at the log to see what actually failed?

**Comment by Robinyoh** [comment]
I think that you need for the moment parameter 42 in default mode = 0 . You need to reset your motion device for it to work, because editing parameter 42 wil give the same timer problems, like i tested in #492
the timer settings arend sent correctly from homey to the fibaro motion detecter. With setting 40,2,5 you will have every change of 5 lux an report to homey.

40 ILLUMINATION REPORT THRESHOLD
The parameter determines the change in light intensity level resulting in illumination report being sent to the main controller.
Available settings: 0 - 65535 (1 - 65535 lux; 0 = reports are not sent)
Default setting: 200 (200 lux) Parameter size: 2 [byte]

42 ILLUMINATION REPORTS INTERVAL
Time interval between consecutive illumination reports. The reports are sent even if there are no changes in the light intensity.
Available settings: 0 - 65535 (1 - 65535 seconds; 0 = reports are not sent)
Default setting: 0 (no reports) Parameter size: 2 [bytes]

**Comment by TedTolboom** [comment]
I do not have good experience with setting parameter 42 to 0..

I’m still running the tests on both motion sensors…. The factor of ~257x comes back also in parameter 42…
So if I set parameter 42 to 1… I do get illumination reports once every 257 seconds (4.3 minutes) = 257x
If I set parameter 42 to 5… I get illumination reports once every 1280 seconds (21.2 minutes) = 255x

So if I would like to have a report every 10 minutes… I would need to set it to 2 (8.5 minutes) or 3 (12.75 minutes)

It is not correct behavior, but if we know it, we can make use of it...

**Comment by TedTolboom** [comment]
Secondly... I do think that also parameter 40 has the same offset factor...

I've set in all cases the motion sensors with parameter 40 to a 2 lux difference... but I never observed an additional illumination report outside the reporting interval set by 42.. even though the differences are bigger then the 2 lux as defined by 40.

Only exception is the 2x that the motion sensor fell on the ground (adhesive tape issue).. where the window in front of the sensor was removed (had to be repositioned)... where the illumination spiked by around 700 lux (which is bigger the 2x 255 lux) ;)

Test now running with 42,2,2 and 42,2,3..

I still do not understand why setting the sensor to 42,2,1800 gives a smaller offset (~2062 seconds interval)

**Comment by Robinyoh** [comment]
Thats true, but hoping the guys from athom can find why this is happening.
I think that with default setting parameter 42, you've got a working setup for the moment. I tested it and it gave me a lot of readings:
![chart](https://cloud.githubusercontent.com/assets/18645811/15092443/7a434c3a-146a-11e6-9454-935ac17b2756.png)


To reset your motion device follow next list:
- remove the node in zwave setting by pressing 3 times the B-button
- reset the motion detector with long press on B-button untill color change to yellow and then press 1 times short, color changes to red.
- add it again in devices and chose group 3.
- Now it works again with default settings after waking him up by pressing 3 times the B-button
- Reboot homey for seeing all parameters in Insights.

**Comment by TedTolboom** [comment]
Hi Robin,

Thanks for the advice.. 
I have used the reset routine dozens of times to test the motion sensors functioning and understand the issue (see my contributions to Github and forum)...

The reason that the default settings are working quite well for you is that your sensor is situated outside or in a sunny position (based on the sensor data)... The fluctuations are bigger than the default 200 lux... And therefore recorded.

As you can see in my data (shown above), my sensors are positions in shady corners of the living room and seldom exceed 300 lux as maximum value... Therefore, I need to make adjustments to the parameters to increase sensitivity... 

Once I'm back home, I will add the data..

**Comment by Robinyoh** [comment]
indeed i was outside, but i meant setting all parameters to default and edit 40 to 5 or 1, leave 42 untouched.

**Comment by TedTolboom** [comment]
It should not matter... both parameters (40 and 42) should operate complementary to each other.. meaning that an illumination report should take place if either the interval is due or the change in illumination exceeds it's setting..

As mentioned, I already set by default parameter 40 to 40,2,2... 
and have never seen an illumination report outside the reporting interval set by parameter 42... (except for the drops where the illumination change was bigger than 600 lux (> 2x255)..

But the test is running ;-P

**Comment by Robinyoh** [comment]
ok i understand it now, thats why it worked for me outside.

**Comment by TedTolboom** [comment]
Just for reference... my illumination graph for both sensors.. 

<img width="1160" alt="schermafbeelding 2016-05-07 om 17 35 42" src="https://cloud.githubusercontent.com/assets/17163431/15092997/421ad9a8-147a-11e6-8948-81d1091c5a6e.png">

The one positioned in the darkest corner... dropped on the floor, causing the big spike (>2x 255 lux)...
You also nicely see the changes in the interval between measurements.

For reference, over the last 7 days, the light intensity never exceeded the 500 lux.

To make my point that also parameter 40 has the same offset factor... my data of May 5th... again with 40,2,2 as setting.
<img width="1162" alt="schermafbeelding 2016-05-07 om 17 40 26" src="https://cloud.githubusercontent.com/assets/17163431/15093027/028dfb66-147b-11e6-9e1c-793d8845715f.png">

Here you clearly see a drop from 434 lux to 148 lux (- 286 lux)... but only recorded on the timing interval of 1800 seconds (42,2,1800, aka 2062 seconds as mentioned above)...

**Comment by TedTolboom** [comment]
Summary of today's experiments:
- Parameters as transferred to the Fibaro Motion Sensor have an off set of ~255x
- Reproduced for parameter 6 by @Robinyoh in #492 
- Reproduced for parameter 42 and 64 (see above data and below summary)
- Expected to also be applicable for parameter 40 (due to absence of data report while parameter 42 has been set to 0).
- Expected to be also applicable for other parameters (with parameter size 2); which would also explain that the updating of the wakeup interval has no effect on the data reporting... 

Settings applied (parameter 42 and 64) and average interval (out of Insights)
0	         No update (> 3 hrs)
1	         258 seconds (258x)
2	         508 seconds (254x)
3 	         773 seconds (257x)
10	        2543 seconds (254x)
30	        7650 seconds (255x)
1800	2036 seconds (1.13x)

@ocatie @WeeJeWel This would explain a number of issues with the parameter updates of at least the Fibaro Motion sensors (but expected more); I would guess this points towards a decimal to hex conversion error...

In the mean time, I set parameter 42 to 3... and get every 12 minutes my illumination report

**Comment by caseda** [comment]
Ok, so i was thinking...
It is getting multiplied by ~255, or rather, with 1 byte.
except for the 1800 seconds one, what if we try a parameter that is just above the 1 byte marker, so 256 seconds.
so homey NEEDS to send 2 bytes.

because my guess is that homey thinks it is sending 2 bytes,
but only needs te send 1 byte so it sends 1 empty byte extra.
(with bad configuration, also known as NULL, which is 11111111 = 255).

for the people that don't quite understand what i mean:
a **bit** is either a 1 or 0
this makes with **8 bits** (= 1 byte)** 256 possibilities** of 1's and 0's.
Computer language always start from 0, so the range is **0 - 255**
which comes to my answer of 256 seconds.

**Comment by TedTolboom** [comment]
I already thought 255 was not a random number.. didn't make the link to bytes (yet)... Thanks..
Setting updated to 42,2,256... and running ;-P

**Comment by bvdbos** [comment]
Regarding 1800: three bits more : 256+512+1024 = 1792. If you add 256 then it's 2048, about 2036. But it's a binary communication so the values should be precise?
1 258 seconds = 00000001 -> 00000001 00000010
2 508 seconds =  00000010 -> 00000001 11111100
3 773 seconds = 00000011 ->  00000011 00000101
10 2543 seconds = 00001010 -> 00001001 11101111
30 7650 seconds = 00011110 -> 00011101 11100010
1800 2036 seconds = 00000111 00001000 -> 00000111 11110100

can't detect any patern, also when working with the decimal values...

**Comment by caseda** [comment]
actually it does seem i was wrong, cause doesn't send an empty byte, it duplicates the byte.
even though it is not exactly the duplicate, this could be a homey timing error.
homey is _definitely_ not on the point with seconds...

1 = 0000 0001 -> 257 = 0000 0001 0000 0001
2 = 0000 0010 -> 514 = 0000 0010 0000 0010
3 = 0000 0011 -> 771 = 0000 0011 0000 0011
10 = 0000 1010 -> 2570 = 0000 1010 0000 1010
30 = 0001 1110 -> 7710 = 0001 1110 0001 1110
1800 = not able to duplicate in 2 bytes though.

**Comment by TedTolboom** [comment]
@caseda cool!
Just checked the results of the test with 256 and 257 as value... 
Doesn't seem to be updating based on these values.. (updated at 08:20 and 10:45)

<img width="1163" alt="schermafbeelding 2016-05-08 om 13 41 14" src="https://cloud.githubusercontent.com/assets/17163431/15097657/9551df38-1522-11e6-96f5-309246c30768.png">

And the stability of my Z-wave network never exceeded the 12 hrs to keep it running for 18 hrs or so...

As with my previous experiments (early part of this issue), it showed that also updating the wakeup interval to 300, 600, 900, 1200 and 1500 does not seem to have any impact on the reporting interval.. again a 2-byte parameter.

Looking forward to:
- someone testing this on a Aeon multisensor, where the interval is defined as a 4-byte parameter...
- @ocatie's feedback / solution for this issue ;-P

**Comment by caseda** [comment]
I might have figured it out with the 1800 second one..
the 2 bytes get flipped around:
1800 = 0000 0111 0000 1000
2055 = 0000 1000 0000 0111

and like i suggested before with 256 seconds, it becomes when flipped, 1 second which again this states in the manual:

> NOTE
> Frequent reports will shorten the battery life.
> Parameter value under 5 may result in blocking the illumination reports.

trying it out now with parameter 42 on **15360 seconds**
(sounds wierd but this flipped around should be 1 minute,
i don't wanna send too much information to homey while i'm gone for a few hours)

**Comment by TedTolboom** [comment]
@caseda Good catch!

So this would suggest that there is an issue with byte conversion.. 
Either by flipping or by Most Significant Bit (MSB) first; both giving the same results for 1800 and also for 15360. It doesn't explain the replication for decimals up to 255.

So it would be interesting to see the results of your experiment...

So to extent the reasoning your gave above...
For a 2-byte size parameter (e.g. Fibaro Motion Sensor)
5 = 00000101 -> 1285 = 00000101 00000101

If the same applies for a 4-byte size parameter (e.g. Aeon Multisensor 6)
5 = 00000101 -> 84215045 = 00000101 00000101 00000101 00000101

This would also explain why some experiments as users on the forum did with setting the Aeon Multisensor 6 to a 5 second interval (parameter 111, which is a 4-byte size) were not successful..

**Comment by bvdbos** [comment]
Great find, either two 8-bits get switched:
(a=1) -> 0000 0000 0000 0001 -> 0000 0001 0000 0000 = 256 (258 -> +2)
(a=2) -> 0000 0000 0000 0010 -> 0000 0010 0000 0000 = 512 (508 -> -4)
(a=3) -> 0000 0000 0000 0011 -> 0000 0011 0000 0000 = 768 (771 -> +3)
(a=10) -> 0000 0000 0000 1010 -> 0000 1010 0000 0000 = 2560 (2543 -> -17) 
(a=30) -> 0000 0000 0001 1110 -> 0001 1110 0000 0000 = 7680 (7650 -> -30)
(a=1800) -> 00000111 00001000 -> 0000 1000 0000 0111 = 2055 (2036 -> -14)

or the same 8-bit gets send again
(a=1) -> 0000 0000 0000 0001 -> 0000 0001 0000 0001 = 257 (258 -> +1)
(a=2) -> 0000 0000 0000 0010 -> 0000 0010 0000 0010 = 514 (508 -> -6)
(a=3) -> 0000 0000 0000 0011 -> 0000 0011 0000 0011 = 771 (771 -> 0)
(a=10) -> 0000 0000 0000 1010 -> 0000 1010 0000 1010 = 2570 (2543 -> -27) 
(a=30) -> 0000 0000 0001 1110 -> 0001 1110 0001 1110 = 7710 (7650 -> -60)
(a=1800) -> 00000111 00001000 -> 0000 1000 0000 1000 = 2056 (2036 -> -20)

Without taking a random factor (like respons-time) I can't see the solution yet...

**Comment by caseda** [comment]
i think that only @ocatie can answer this for real. i don't think we will be allowed to see the source code for this.

Test Results though:
The 1 minute test has been "suspended", it did not work
homey received no data for 6 hours straight.
Now trying it out with 5 minutes span (300 seconds, or configured like 11265s) now running for an hour, the first 10 minutes were good (3 measurements), but this also could have been thanks to the lux threshold that i changed to 1 (40,2,1).
but than nothing for like 15 minutes (then the lights turned on so there was a lux change).
will let it run in this configuration for another hour or so, without letting the lux change.

but i think it is save to say it is the duplication thing.

which could be a javascript/jquery thing.. i was messing about with a small side project (for with homey) that contains javascript.
and got duplication results thanks to: if the function wants 2 values but only gets 1, it will just duplicate the 1st value for the 2nd one.

**Comment by TedTolboom** [comment]
Nice to see also other people enjoying the sport to crack the code...

I think with the effort we put into solving / understanding this issue we at least deserve a peak into the code. And I think @ocatie will have sufficient leads to squash this bug in the next SW release. ;-P

For reference, my Insights of today.
<img width="1157" alt="schermafbeelding 2016-05-08 om 20 55 24" src="https://cloud.githubusercontent.com/assets/17163431/15100216/1e4fa678-156c-11e6-86ca-fe4b9e2c4a60.png">
Please mind that I changed the values of the 2nd (light green) sensor 3 times (8:20, 10:45 and 14:00), including reboots. As of 14:00 also the 2nd sensor reported based on the 42,2,3 setting every 12 minutes.

Although I also have set parameter 40,2,2 I did not see any additional illumination reports; which is logical because the light intensity did not change by 512 / 514 lux for my indoor positioned sensors.

**Comment by bvdbos** [comment]
With 64,2,22530:
600 sec : 0000001001011000 -> 0101100000000010 : 22530
actual results: 510/511 seconds...

**Comment by caseda** [comment]
This definitely confirms the duplication of 1 byte:
00000010 00000010 = 514

**Comment by TedTolboom** [comment]
@caseda So that would mean that the first byte is ignored, and second byte is duplicated..

Input as @bvdbos used: 
22530 = 01011000 00000010 > 00000010 00000010 = 514
But the following input (and any specific other first byte) will yield the same result: 
258 = 00000001 00000010 > 00000010 00000010 = 514

So that would mean that the lowest value that can be set (outside 0) with the current conversion issue is 0000000100000001 = 257

Meaning that for indoor usage, we cannot modify the sensitivity of the illumination threshold (parameter 40) below the default 200 lux

**Comment by bvdbos** [comment]
https://github.com/athombv/homey/issues/492#issuecomment-217839193

**Comment by ocatie** [comment]
Fixed in 0.8.33. Thnx guys! Swapped the value bytes for size 2 and 4.

**Comment by caseda** [comment]
Wonderfull that it is getting fixxed in the next update.!

but until the next update is there, if people want to have it working already, i am using these parameters:
40,2,1;42,2,11265 (flipped -> 5 minutes or 300 seconds)
And the update timing is very stable, since 1 AM (it only started to work after this time, maybe a sensor thing?) to 18:00 i had 131 Result!

To post the entire log is a bit too much but i added up te timings:
255 seconds - 46x
256 seconds - 51x
510 seconds - 2x
511 seconds - 15x
512 seconds - 1x
766 seconds - 5x
767 seconds - 2x
1021 seconds - 2x
1022 seconds - 3x
1044 seconds - 1x

the higher "second" counts are probably because of the lux not being different then the previous one, but does trigger when atleast 1 lux was different. i don't know if parameter 40 had any effect on this.

![chart](https://cloud.githubusercontent.com/assets/2565450/15119553/bfa634ce-1611-11e6-8b94-06680bd76840.jpeg)

**Comment by TedTolboom** [comment]
Confirmed to be solved in 0.8.34; 
even though in this release the parameters can not be updated via the device card: see #607 

@weejewel please add the 0.8.34 milestone
