### ISSUE TITLE
Power consumption not reported for lamp type of Z-wave devices

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#465]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**
Before doing a full reset of Homey, all three Powernode 6 blocks were used for various appliances (including lamps) all showing the cummulative powerconsumption per connection. All connections were of the type "non of the above / generic socket"

When I reconnected my three Powernode 6 blocks, I chose on the applicable sockets the Lamp type to become better recognizable within Devices.

**What was the result?**
I now notice that for the Lamp type, not power consumption is reported..
within Devices:
<img width="326" alt="schermafbeelding 2016-04-17 om 22 59 20" src="https://cloud.githubusercontent.com/assets/17163431/14590005/3998194c-04f0-11e6-86ad-8fd410df3c8b.png">
as well as at Insights:
<img width="238" alt="schermafbeelding 2016-04-17 om 23 01 52" src="https://cloud.githubusercontent.com/assets/17163431/14590015/6e7a9dc4-04f0-11e6-8742-fa746be45a09.png">
 
**What did you expect as result?**
Whereas in previous setup the power consumption of all sockets/sub-nodes as reported
<img width="323" alt="schermafbeelding 2016-04-17 om 22 59 46" src="https://cloud.githubusercontent.com/assets/17163431/14590006/44a4d366-04f0-11e6-9743-db0978d797f2.png">

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
