### ISSUE TITLE
433 Mhz suddenly unavailable

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#467]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Switching sockets (Kaku & Action) on/off and using Kaku remote. 

*Please include detailed steps how we can reproduce the issue*

In 0.8.30 switching sockets on/off was working. Suddenly, it didn't work anymore. Also the Kaku remote didn't work anymore. 

**What was the result?**

Non responsive sockets and no input from remote.   New pairing both sockets and remote wasn't successful. Re-installing App succeeded, but still not communication.

Logfile: E592F3AF22   ( after reboot and some pairing actions)

**What did you expect as result?**

Continued working Kaku + Action interface.

**Any other remarks**

...

**Comment by ReinierH** [comment]
Have you tried turning it off and on again?

**Comment by ralfvd** [comment]
Yes, multiple reboots and also power off/power on. 

Logfile just after power on and trying to switch Action light multiple times: 7D3802D826

**Comment by ralfvd** [comment]
@ReinierH I did a power off again, and now waited longer before powering back on. That did the trick, Kaku and Action are now working again. 

I now probably waited for a minute before putting the power back on instead of 'instantly'. I guess there might be some capacitors that keep the 433 part alive briefly after cutting the power. So cased closed for me, lesson to be learned: request the power to be off for a minute to be sure that all systems are 'dead'.

**Comment by ralfvd** [comment]
Again, 433 communication broke down . Reboots and power off (5+ minutes) didn't work. Sending & receiving is completely dead. 

Logfile: 7A576ED651

**Comment by kaandorp** [comment]
For me as well. Resetting, reinstalling. Nothing works.

**Comment by Willieku** [comment]
for me too.
nothing from kaku works. reboot ,  power off  has no effect.
trying to ad a new sensor is not possible

**Comment by ReinierH** [comment]
I found the issue and currently working on a fix.

**Comment by ReinierH** [comment]
@kaandorp @Willieku 

Can you send me a log of your homey? You can find the report log button in Homey settings->System.

**Comment by Willieku** [comment]
@ReinierH    did you received it?

**Comment by Willieku** [comment]
Sorry reinier,  i did send it right away, but did not realaes must give you this code.
54B6C1188D

**Comment by Willieku** [comment]
@ReinierH   received an update to 0.8.32      looks like 433 is working again,  thx in advance, i will test as soon as possible

**Comment by Willieku** [comment]
@ReinierH Hi, It seem to be working along the day, but suddenly it stopt again....   no clue why
only 433 is not working now

**Comment by bvdbos** [comment]
Happened to me too, i disabled the kaku-app and re-enabled it and now 433 works..

**Comment by pbaan93** [comment]
Same as @ReinierH, 0.8.32 still has a bug in 433. For me, only reset bij removing power worked.

**Comment by Willieku** [comment]
Kun je mij in Nederlands zeggen wat je nu precies gedaan hebt?
Een volledige app verwijderen ofzo?
Op 27 apr. 2016 22:00 schreef "Bas van den Bosch" <notifications@github.com

**Comment by bvdbos** [comment]
Op het instellingen-scherm KlikAanKlikUit uitgeschakeld en opnieuw ingeschakeld. Daarna is 433 niet meer uitgevallen...

**Comment by Willieku** [comment]
Thx for your answer. I try in my best english now.
I did nog found that Button yet.
I tryed but No reaction .  now i rebooted, also No reaction.
I try tommorow and then unplug for a while.  IT seem to me its a sort of
overflow....
Op 27 apr. 2016 22:12 schreef "Bas van den Bosch" <notifications@github.com

**Comment by bvdbos** [comment]
![2016-04-27 22_45_19-homey settings](https://cloud.githubusercontent.com/assets/1064079/14867649/c736e766-0cc9-11e6-88cc-5c4417db76fe.png)
If you hoover over the app-name the button appears...
Als je met je muis boven de app gaat staan dan verschijnt die knop...

**Comment by Willieku** [comment]
@ReinierH    Whit thx to @pbaan93 and @bvdbos 
resetting by deactevate kaku did not do the trick, but unplugging homey, wait for 15 minutes and pluged in,     now homey 433 works again.
Also want to report @ReinierH ;  I have also a HomeWizard running.
Now, (i must say this is a longshot) would it be posseble that the signals (whit the same codes) send by homewizard can make a sort of overflow stack in Homey.
At first sight i say No, not possible, but still.......  (sometimes a stupid remark does the trick)
Good luck by surging.

**Comment by ReinierH** [comment]
Are there people that dont use zwave and also experiencing problems with 433?

**Comment by Willieku** [comment]
yes me,  i doint use zwave yet.   
Only kaku sensors, buienradar, infra red, nfc, countdown(only installed, not in flow), NOS headlines, soundboard
