### ISSUE TITLE
Homey doesn't know what firmware it's running

### ISSUE THREAD

**Issue by novaflash** [athombv/homey#469]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**
I wanted to know what firmware version was running in Homey, by asking it.

*Please include detailed steps how we can reproduce the issue*
Simply ask the Homey: "OK Homey, what version are you running?"

**What was the result?**
"I am currently running version _undefined_"

**What did you expect as result?**
"I am currently running version 0.8.30"

**Any other remarks**
An ocean is very wet.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.31

**Comment by novaflash** [comment]
Is the ocean wetness solved as well? Just kidding, thanks for the quick fix.

**Comment by irritanterik** [comment]
It is! Issue can be closed:
![image](https://cloud.githubusercontent.com/assets/15232724/15262465/d01a54ee-1962-11e6-9b25-bbf327fd369f.png)

**Comment by RoadXY** [comment]
Checked and working like expected
