### ISSUE TITLE
System time

### ISSUE THREAD

**Issue by 6Blok** [athombv/homey#47]
System time on Homey seems to be one hour behind, timezone (Europe/Amsterdam) setting in Homey is correct. 
Current version V 0.8.14
Thx,

Stephan

**Comment by WeeJeWel** [comment]
Try rebooting once!

**Comment by 6Blok** [comment]
I did (just now), disconnected power and reconnected. Under system information it says 17:31, while the time is 18:31.

**Comment by WeeJeWel** [comment]
And your location is correct for your timezone?

**Comment by 6Blok** [comment]
Yep, but when asked, Homey does say the correct time, i.e. not the system time, 

Solved for now I think

**Comment by WeeJeWel** [comment]
Ah! Yeah, the time is correct then, but when used, it adjusts for timezone :)

**Comment by nlrb** [comment]
I had the same thing before I visited the Location page. Time was 1 hour off. Although it was on automatic, could it be that visiting the page triggers setting the time zone?
