### ISSUE TITLE
Setup issue: wifi connect fails

### ISSUE THREAD

**Issue by jtebbens** [athombv/homey#470]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
Initial setup and configure wifi nework

*Please include detailed steps how we can reproduce the issue*

Upon wifi setup it tries to get an ip address from the DHCP server of the wifi router/internet.
Logfile showed:

Apr 19 15:56:12 dnsmasq-dhcp[375]: DHCPACK(br0) 192.168.1.115
6c:ad:f8:05:xx:xx localhost
Apr 19 15:56:12 dnsmasq-dhcp[375]: not giving name localhost.xxxx.net
to the DHCP lease of 192.168.1.115 because the name exists in /etc/hosts
with address 127.0.0.1
Apr 19 15:56:12 dnsmasq-dhcp[375]: not giving name localhost to the DHCP
lease of 192.168.1.115 because the name exists in /etc/hosts with
address 127.0.0.1

So homey tries to get an ipaddress with the name localhost. DHCP server deny due conflict localhost.

**What was the result?**

Setup fails and Homey says cant connect.

**What did you expect as result?**

**Any other remarks**
I resolved/bypass/workaround this by setting the ipaddress in the DHCP server based on its MAC address and also preset a name for it like "homey". Now you need to reboot Homey again, go through the setup process, set the wifi and its password and now the DHCP server will overrule the localhost name request and use the preset one from DHCPserver config.
...

**Comment by WeeJeWel** [comment]
Fixed in a new setup.athom.com. Please retry and report back!

**Comment by jtebbens** [comment]
Thanks Emile. Not sure how I can verify this. Due my workaround with reserving the IP address into the DHCP Server I managed to get through the setup process yesterday and have a working Homey with some devices and flows running.
