### ISSUE TITLE
Red ring, no response.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#471]
**What is your Homey version (Settings → System)?**

unable to get to settings because Homey is not responding.

**What did you try to achieve?**

Took homey out of the package, connected it to power. Got startup rings and the voice telling me to go to the website. Missed the adres that the voice was telling me, so I disconnected the power and reconnected it hoping that the setup would restart. Then I got the orange circling light, then it turned solid red. Tried to find the homey wifi but it was gone. Tried again to restart, disconnected the power. reconnected same problem. Got on the chat and got the recommendation to hold it upside down after 1 minute for 20 sec. No result. light stays red.

**What was the result?**

Solid red ring, no movement, no homey wifi network. no way to connect to it.

**What did you expect as result?**

after disconnected power i expected the setup procedure to restart.

**Any other remarks**

no.

**Comment by freemann** [comment]
support@athom.com will solve this issue much faster :smiley:

**Comment by spawnreaper** [comment]
mailed.

**Comment by bvdbos** [comment]
On Slack someone posted a way to solve this:
https://athomcommunity.slack.com/archives/general/p1461097151000551

22:19 acekrystal For people with the red ring... please try the following:
1. Unplug your homey;
2. Hold you homey upside down;
3. Plug in power while holding upside down, it should go into a purple/pink rotating ring;
4. wait 10 sec.
5. Unplug the power, wait again 5 sec;
6. Power it normally again upright. For me this seemed they way to reset it without the countdown setting/voice available yet (out of the box state);

**Comment by spawnreaper** [comment]
I've tried it 3 times, no change. I'll keep trying it, hoping i'll get lucky.

**Comment by spawnreaper** [comment]
I've tried it 3 times, no change. I'll keep trying it, hoping i'll get lucky.

**Comment by spawnreaper** [comment]
I've tried it 3 times, no change. I'll keep trying it, hoping i'll get lucky.

**Comment by spawnreaper** [comment]
doing the procedure back to back but no luck i'm afraid. 
But thanks for the info.

**Comment by WeeJeWel** [comment]
Please contact [support@athom.com](support@athom.com).
