### ISSUE TITLE
Setup with hidden network

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#472]
**What is your Homey version (Settings → System)?**

Don't know. It's out of the box. (Shipped on 18 april 2016)

**What did you try to achieve?**

Trying to connect to a hidden network (Airport Extreme)
After i made my network visible it's connected.

**What was the result?**

After a long timeout, Homey says he is unable to connect

**What did you expect as result?**

Connecting to a hidden network...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed in the new setup.
