### ISSUE TITLE
Wrong name on welcome home

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#473]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

I tried to welcome me home when back from work. I used the who label from arriving home in the flow editor

**What was the result?**

It's says: 'Hallo Jan Jansen. Welkom thuis'

**What did you expect as result?**

Say my real name instead of a dummy dutch name.

**Any other remarks**

...

**Comment by Dijker** [comment]
How did  you trigger the Flow?
Did you push the test button? 
Or did you leave and return home?
For a test with the test button on top of the flow designer it is expected as Homey doesn't know who is arriving.

**Comment by kerkenit** [comment]
I've pushed the test button. But my name was selected. So when I enter home. 
I should expect that the name of the card was spoken.
I didn't test with real entering home because the iPhone app isn't yet there.
For now this issue can be closed.

**Comment by WeeJeWel** [comment]
If you push the test button, a 'random' value will be used for the token.
