### ISSUE TITLE
Set flow name Safari

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#474]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Set a name for a flow or rename it.

**What was the result?**

Unable to set name of the flow

**What did you expect as result?**

Set the name of the flow

**Any other remarks**

...

**Comment by freemann** [comment]
Safari is unsupported so probably not be fixed and closed.
Use Chrome on a Windows of Android system. Chrome on Apple is Safari with a Chrome like skin, so you still use Safari.

**Comment by dvanp** [comment]
> Chrome on Apple is Safari with a Chrome like skin, so you still use Safari.
Not entirely true, Chrome for iOS is, but on a Mac Chrome is Chrome.

**Comment by freemann** [comment]
To avoid confusion and/or mistakes and/or .... Its very preferable to avoid Safari when you use homey or atleast on setup.

**Comment by WeeJeWel** [comment]
Safari is unsupported.
