### ISSUE TITLE
Woonveilig can't login

### ISSUE THREAD

**Issue by bierre** [athombv/homey#475]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**
I tried to create a new device Woonveilig

*Please include detailed steps how we can reproduce the issue*
- Added the woonveilig app
- Selected living room to add Woonveilig device
- Filled in credentials (checked on woonveilig site to make sure, caps lock is off)

**What was the result?**
- Could not logon due to incorrect credentials (exact password was copied to woonveilig site, so it is correct

**What did you expect as result?**
Create a woonveilig device

**Any other remarks**

...

**Comment by freekwebdesign** [comment]
Does your password contain any special characters? (like @,;&()#)

**Comment by freekwebdesign** [comment]
Are these the same credentials which you use to login at this webpage: https://mijn.woonveilig.nl/login.aspx

**Comment by bierre** [comment]
No special chars and the login at the webpage works Well.

**Comment by freekwebdesign** [comment]
Hmm that is strange, I tried to login with my own credentials and everything seems to work correctly on 0.8.30.

Did you already try to reboot Homey and reinstall the app?
Do you get the pop-up message with the text 'You entered a wrong username or password, please try again'? Or no message at all?

**Comment by bierre** [comment]
The meassge was You entered a wrong username or password, please try again'

**Comment by freekwebdesign** [comment]
Maybe a bit of a strange question, but can you temporary change your password and send your username and new password to freek@athom.com?

In this way I can try to login with your account details in developers mode to exactly see what is happening during the validation process.

**Comment by bierre** [comment]
@freekwebdesign I don't think that is such a good idea ;-). Can't I send you my logfile from Homey?

**Comment by bierre** [comment]
@freekwebdesign haven't heard from you, anyhting else I can do?

**Comment by freekwebdesign** [comment]
@bierre sorry for the slow response.
It could indeed by helpful if you are able to send your log-file from Homey.

**Comment by bierre** [comment]
@freekwebdesign Logfile 379CEC06EA

**Comment by freekwebdesign** [comment]
@bierre thanks for generating the logfile.
Nothing strange there either.

I will get in contact with Woonveilig to check if they might know what is causing this issue.
Can you send me your username? So I can tell the people at Woonveilig which account is having issues.

**Comment by bierre** [comment]
@freekwebdesign heb je gemaild

**Comment by freekwebdesign** [comment]
@bierre due to some changes at Engardia, your account does not yet work with Homey.
I send you an e-mail on how to change your account so it will work with Homey.
