### ISSUE TITLE
Cannot add Z-wave device to zone

### ISSUE THREAD

**Issue by novaflash** [athombv/homey#476]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**
Add a Z-wave device to the zone "Office" under Zones & Devices.

*Please include detailed steps how we can reproduce the issue*
I click the zone "Office" and click the [+] button. I choose Z-wave.

**What was the result?**
I see the line "Follow the instructions" and "Please wait". There is a loading icon in the middle that keeps rotating. This has been going on for a few minutes now. Then I see the error message: "Error: true".

**What did you expect as result?**
The option to select one of my Z-wave devices that already shows up under Settings > Z-wave, and add it to the zone. Or at the very least something other than "error: true".

**Any other remarks**
I posted a log right after this problem came up. Code 1207B7CDB2.

**Comment by TedTolboom** [comment]
@novaflash if your device is showing up under settings > Z-wave... it should also be visible in the devices screen... perhaps not on the desired place, but you can simply drag it to the correct zone

**Comment by novaflash** [comment]
Hi TedTolboom. I saw a lot of "unknown node" listed under Settings > Z-wave. Apparently 143 of them. When I selected one and clicked refresh node, after a short while, it would list them differently, with different names. Regrettably I have no idea which devices these nodes are, so I would have to do trial and error. Once it got refreshed, I had some devices in the Zones & Devices screen. But the error as described in this issue report still occurs. I should be seeing something other than "Error: true". Also, even though I now see a few Z-wave devices, the overview under Settings > Z-wave has stopped functioning - it now lists nothing at all. A power cycle doesn't fix this. After being on the Settings > Z-wave page for a few minutes, a popup with just an error occurred in it.

So at the moment, I have no useful method of working with Z-wave on the Homey. But that's a separate problem from what I made this issue for. But thank you for your information.

**Comment by ocatie** [comment]
Do you have Homey included in another network? Could you tell me what node id Homey has and the SIS id? You can find those on the settings page.

**Comment by novaflash** [comment]
Yes, I have it included in my existing HC2 Z-wave network. Homey itself has ID 144 and SIS 0.

I know that I won't have FULL functionality, because the Z-wave devices will report to the primary controller. This limitation is known to me.

**Comment by ocatie** [comment]
The SIS/SUC id being zero means there is no SIS in the network. This results in Homey not being able to include nodes in the network. Only the HC2 can do this because it is the primary controller.

**Comment by novaflash** [comment]
I understand that the Homey, as a secondary controller, cannot include nodes. But that was not my intention.

There were nodes already in my network, attached to the primary controller. I added the Homey as a secondary controller. I was expecting, over time, to see Z-wave devices pop up. And they did; a whole shit load of them. But they were only visible as unknown devices under Settings > Z-Wave. I gave it a whole day; none of the nodes ever resolved to a working device on their own. I had to go to Settings > Z-wave and manually select a node and click refresh. And with some nodes, I then got lucky, and got it recognized as a Z-wave device and the corresponding devices became visible in Zones & Devices.

But, I have since given up on this approach. Now, I have excluded the Homey, and reset the entire Z-wave chip in the Homey, and now have it running as a primary node.

I have taken an unpaired device, and paired it to the Homey. That works.

**Comment by ocatie** [comment]
We always recommend to add devices using the pairing wizard. Because adding devices already in the network happens in the background you can't receive any feedback of the process yet. If something goes wrong the process is cancelled.

Can you reproduce the error: true popup on 0.8.32?

**Comment by novaflash** [comment]
I think perhaps we'd better close this issue for now. I have removed the Homey as secondary controller, and am just using it as a primary controller in a new network now. I don't think using Homey as a secondary controller is much of a success right now, and probably not your biggest focus either at the moment.

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/19192/#Comment_19192
Here this works well...

**Comment by novaflash** [comment]
Well, here it didn't.

**Comment by bvdbos** [comment]
What devices (sensors/plugs/dimmers) do you have?

**Comment by novaflash** [comment]
Danfoss valves, Fibaro 3KWh switches, Fibaro 1.5KWh dual switches, Fibaro multi-sensors, Aeotec door/window breach detectors, Fibaro door/window sensors, Fibaro dimmers, Vitrum 4-button touchpanels, Vitrum 3-button satellite touchpanels, Vitrum 1 button satellite touchpanel, Fibaro RGBW controllers, Z-wave.me keyfobs, among others.

**Comment by bvdbos** [comment]
That's a lot for troubleshooting if it's a specific device...
