### ISSUE TITLE
Enhanced flow creation

### ISSUE THREAD

**Issue by JimGMitchell** [athombv/homey#478]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
Enhanced flow creation. I can't find a way to add a large number of devices to a flow in a single operation. You must drag and drop each device individually. Also there is no way to copy an existing flow which means if you have multiple flows that talk to many devices, you soon become tired of dragging & dropping.

_Please include detailed steps how we can reproduce the issue_
Try creating 5 flows that each talk to over 30 devices.

**What was the result?**
I got RSI ;-)

**What did you expect as result?**
An easier way to add groups of devices and the ability to copy existing flows to new flows.

**Any other remarks**
I would suggest the ability to add devices by zone and to be able to create groups of devices independently of zones. A device can be a member of more than one group but only 1 zone. A group is not related to a zone.

**Comment by bvdbos** [comment]
Second part of this is done, copy flow... First part still remains open: grouping devices...

**Comment by bvdbos** [comment]
grouping devices by zone/type is now part of FW 1.3:
![2017-06-24 16_05_54- 835 flow - homey](https://user-images.githubusercontent.com/1064079/28031975-4507c5f0-65a9-11e7-9209-187cacee7bf6.png)
also, we can make sets of devices:
https://apps.athom.com/app/org.scheffers.homey.sets
And check for multiple battery-devices and lights on:
https://forum.athom.com/discussion/3470/app-blowfish-check-battery-levels-last-updates-capabilities-and-condition-for-lights-in-a-zone

So this can de considered fixed?

**Comment by WeeJeWel** [comment]
I'll mark this issue as fixed for now!
