### ISSUE TITLE
Klikanklikuit - fan not showing in floweditor

### ISSUE THREAD

**Issue by svenove** [athombv/homey#479]
**What is your Homey version (Settings → System)?**
0.8.29

**What did you try to achieve?**
Add a new socket

*Please include detailed steps how we can reproduce the issue*
Add a new KlikAnKlikUit socket and set the type to "fan". 
Go to floweditor, the device is not there. 

**What was the result?**
Device not in floweditor 
...

**What did you expect as result?**
Device in floweditor
...

**Any other remarks**

...

**Comment by freemann** [comment]
Duplicate of #433

**Comment by Dijker** [comment]
Running 0.8.35 / KAKU 1.1.3 
I think this is still a problem?

**Comment by jeroenvollenbrock** [comment]
Duplicate of #433
