### ISSUE TITLE
Setting up Homey fails: connecting to "HomeySetup" SSID is succesful, but client can't open any web pages

### ISSUE THREAD

**Issue by JeroenvIS** [athombv/homey#48]
As per instruction:

- I first opened the website https://setup.athom.com
- It said to connect my client to the "HomeySetup" SSID, which I did
- Connecting to the SSID was successful, my client got an IP address
- However the browser connection seems dead: it won't open any page, so I don't see any steps how to continue after connecting to the HomeySetup SSID.

My client is an Asus Transformer tablet running Android 4.<something>, it got IP 10.199.198.10 from the Homey. I also tried opening http://10.199.198.1/ in my browser which I guessed would be the IP address for Homey; then at least the HTTP request succeeds, but the result page only says "Cannot GET /".

What URL should I open (or be redirected to), after connecting to the HomeySetup SSID?

**Comment by WeeJeWel** [comment]
Switch back to the same network that you connected Homey to, and the browser should find your Homey after it pulses green, and resume setup.

**Comment by JeroenvIS** [comment]
Right, looks like the browser tried a full refresh when changing SSIDs; I tried again a few times and managed to keep the browser running while changing the SSID. Now I'm at step 2.

**Comment by JeroenvIS** [comment]
One step further, but it seems that Homey doesn't connect to my home SSID... I'm not sure about the PSK though, what happens when the wrong PSK is given to Homey?

By the way, wouldn't it be possible for the WLAN hardware in Homey to provide the HomeySetup while trying to connect to the users' wireless? Then the user could be informed by Homey whether Homey was successful in connecting to the users' wireless *before* the user switches from HomeySetup to his/her own network.

Lots of WLAN hardware supports virtualization nowadays; is Homey running hostapd?

**Comment by WeeJeWel** [comment]
If the wrong password is entered, Homey will start over, and so will your browser.

**Comment by JeroenvIS** [comment]
My browser only says that it's taking exceptionally long... I have restarted the procedure manually each time.
I think I've tried ~ 20 times, finally I managed to get Homey connected and with a green LED ring.

Aaarggh, and now my Athom account isn't accepted... Is it not the same as the forum.athom.nl account?

**Comment by JeroenvIS** [comment]
Right, creating a new account works.

**Comment by WeeJeWel** [comment]
No, your forum account is not the same :)

Please close this issue if you've got it working!

**Comment by JeroenvIS** [comment]
So to summarize, it took about 20 attempts to get my Homey succesfully connected to my home wifi and only after all those attempts the LED ring went green for the first time.
It's probably hard to reproduce with a Windows or Linux client, but the procedure was a real PITA with my Android tablet (and that's my only wireless device with a web browser).

Maybe mine is a corner case; better connectivity and feedback during the setup procedure would be an improvement, bug you probably have more pressing issues at the moment. I'll close this one.

**Comment by WeeJeWel** [comment]
Alright, we will investigate, thank you for notifying us!
