### ISSUE TITLE
sfsUdtSaveToFile failed: failed to write search to file

### ISSUE THREAD

**Issue by nklerk** [athombv/homey#480]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Train voice recognition,
Gone to Settings, Microphone, Start.

Say'd ok homey 5 times, the leds turn whitish and i got this message in the browser (Chrome)

**What was the result?**

Got an error in the browser.
Homey stayed having a white ring.

**What did you expect as result?**

getting a more positive message

**Any other remarks**

in the next try i was unable to say ok homey correct once tried like 30 times.

Disabeling the microphone and restarted, then the training went fine.

**Comment by WeeJeWel** [comment]
Voice training is removed in v0.8.34.
