### ISSUE TITLE
Module version mismatch. Expected 46, got 14

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#481]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

I am trying to develop an app and get the following error during debugging:
Module version mismatch. Expected 46, got 14.

I just upgraded my node version on the Rapberry to V4.4.3 and according to this link https://nodejs.org/en/download/releases/ it corresponds with Module version 46. I am running 0.8.30 on the Homey and Node JS should be upgraded to version 4.4.7. I hope this is a typo and that the version is V4.4.3. But since de debugger is complaining about the wrong version : 14, I guess de Node JS version on (my) Homey is still in the V0.12.xx range since that corresponds with Module version 14.

Also see : 
https://nodejs.org/en/download/releases/

What is wrong here and how to solve this?

**Comment by WeeJeWel** [comment]
Try running:

```
npm uninstall -g athom-cli
npm install -g athom-cli
```
