### ISSUE TITLE
connection problems Enginius accespoint

### ISSUE THREAD

**Issue by RicardovanE** [athombv/homey#482]
version 0.8.29

during setup create connection to Engenius wifi accespoint, Homey say connection succesful.

but when switch computer back to accespoint the webpage say homey is updating. this is not so 
Homey did get a ip number from router . but homey is neither pingable or access by browser.
tried setting accesspoint in B only, G only and N only. no change. 
Connection to a Ubee WiFi Router works perfect.

( notice if you set your WPA password by a Android tablet the first character is in Capitol)

**Comment by WeeJeWel** [comment]
Should be fixed in the new setup.
