### ISSUE TITLE
Setting to improve OK Homey detection, actually makes it worse. 

### ISSUE THREAD

**Issue by JosVinke** [athombv/homey#483]
**What is your Homey version (Settings → System)?**

 0.8.29

**What did you try to achieve?**

Improve 'OK Homey'  detection using the microphone menu setting. 

**What was the result?**

A LOT of false triggers and Homey responding to almost everything.

**What did you expect as result?**

Improvement of the OK Homey detection based on my voice.

**Any other remarks**

Resetting the Homey solved the problem and improved 'OK Homey' detection a lot.

**Comment by WeeJeWel** [comment]
Voice training is removed in v0.8.34.
