### ISSUE TITLE
First Homey in different location is offline when adding a second Homey

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#484]
**What is your Homey version (Settings → System)?**
0.8.30

**What did you try to achieve?**
My first Homey is in my home location (Amsterdam). I have received my second Homey, which I added at my office. The network of my office is completely separated.

**What was the result?**
First Homey (Amsterdam) shows 'offline' when I am at the office

![schermafbeelding 2016-04-21 om 15 15 26](https://cloud.githubusercontent.com/assets/17727803/14710080/428a141a-07d4-11e6-96c6-c43442f0a183.png)

**What did you expect as result?**
To be able to control both.

**Comment by jordenc** [comment]
More info: 
It tries to load the first Homey over the internal network, it uses the correct IP (192.168.1.77 for Amsterdam) but ofcourse, on the other location that doesn't work.

![schermafbeelding 2016-04-21 om 17 05 07](https://cloud.githubusercontent.com/assets/17727803/14713941/718d22b6-07e3-11e6-8706-f4e240c51288.png)

**Comment by WeeJeWel** [comment]
Can you reach your 'Amsterdam' Homey by going to https://your_homey_id.homey.athom.com ?

**Comment by jordenc** [comment]
If my browser history URL is correct: No. It shows:

"Sorry, this Homey is not connected...

Automatically trying to reconnect..."

It worked when I left though, and I can still reach my Synology on the correct IP-address.

> jquery-2.2.0.min.js:4 GET https://56a74eaf7d0797126e0685c7.homey.athom.com/api/manager/webserver/ping 500 (Internal Server Error)
> l.cors.b.crossDomain.send @ jquery-2.2.0.min.js:4
> n.extend.ajax @ jquery-2.2.0.min.js:4
> (anonymous function) @ (index):14

**Comment by WeeJeWel** [comment]
Then probably Homey has disconnected or crashed somehow.. using multiple Homeys works fine here, so I am closing this issue for now. If it persists, let me know!

**Comment by jordenc** [comment]
It was indeed crashed (rainbow on, but no more animation). I have sent a log 191616E828 in case that's helpful, but ofcourse a reboot solved this issue.
