### ISSUE TITLE
Homey could not connect to your Wi-Fi network. Please try again

### ISSUE THREAD

**Issue by Krukkie** [athombv/homey#486]
**What is your Homey version (Settings → System)?**

Pre-order, not able to log-on 

**What did you try to achieve?**
Log-in

_Please include detailed steps how we can reproduce the issue_
see issue #386 
Response is: Homey could not connect to your Wi-Fi network. Please try again.
However Homey is connected to wifi network
Ping does work
[Homey could not connect to your Wi.docx](https://github.com/athombv/homey/files/230615/Homey.could.not.connect.to.your.Wi.docx)
Router is KPN Experia box 9 with WPA2 and DHCP on

**What was the result?**

Not able to proceed with log-in procedure

**What did you expect as result?**

Access Homey via https://my.athom.com/#/

**Any other remarks**

...

**Comment by Yamahaa** [comment]
I had the same problem for me it helpt to change  my ssd name wit NO capitals and spatie en no numbers...

**Comment by bvdbos** [comment]
This if fixed now?

**Comment by WeeJeWel** [comment]
Yep
