### ISSUE TITLE
speech-recognition

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#488]
Homey now sends speech to the athom cloud-service where the sound is distributed to several services and one is picked. Some people say google-recognition works better, some people say Siri works better. I wouldn't know, guess it also has to do with licensing costs...

Wouldn't it be helpful if you can choose which service to use:
Homey cloud (free, standard option), google, apple, some other third party

If licensing cost is involved, it's a choice people can make. Also, it more durable/sustainable: Suppose Athom has to stop the speech service for some reason, this part of Homey may stay functional. And of course, it may proof Athom has the best recognition for a device like this...

**Comment by westd05** [comment]
I agree. 
Google works best for me if it works like on my other devices...

No problem for me to pay for that service. It's not that much...

**Comment by freemann** [comment]
Very curious to known where people read that Athom uses Siri and/or Google servers/services for speech recognition.

**Comment by WeeJeWel** [comment]
Nope, we won't make an option where you can choose. You're free to build your own speech recognition device that sends a POST request to Homey with the text.
