### ISSUE TITLE
source code repository

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#489]
The source-code of Homey is closed which is understandable from a competition point of view. Apart from the question whether it's allowed (isn't a lot of GPL-code used???) this means if for some reason the Athom-company goes bankrupt after some time Homey becomes useless as no more bugs can be fixed (also, the root password is a secret). It would be a good thing to deposit the source-code and root password in an escrow-service and release it after Athom has to stop... (not hoping it has to, still think it's the greatest product in it's kind and I still have full confidence in Athom being a company which is here to stay).

**Comment by jordenc** [comment]
I partially agree. There should be taken 'measures' to assure we all can continue to use our Homey, even if Athom doesn't exist anymore.

**Comment by WeeJeWel** [comment]
This is of course not an 'issue' :-)
