### ISSUE TITLE
can't get simple flow to work using logic condition

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#49]
![image](https://cloud.githubusercontent.com/assets/17158826/12957424/daebca08-d02c-11e5-9181-58c71940f52d.png)

No response when pushing the test button. 
In fact I was using the flux reading from my Fibaro sensor but it didn't work so I tried this simple test.

**Comment by WeeJeWel** [comment]
That's because the Test button fills in a random value for the token.

**Comment by freemann** [comment]
So for logical flows the test button should not be used? Is there a other way to test?

**Comment by WeeJeWel** [comment]
Well, you shouldn't test anything with conditions that depend on those black tokens :-)

**Comment by freemann** [comment]
ok. To me the tokens makes the floweditor very powerful. But if its not possible to check/test flows with tokens, maybe its a idea to remove the test options completely or in flow where tokens are used.

**Comment by WeeJeWel** [comment]
I'm planning to add a popup below 'Test' where you can fill them in :)

**Comment by freemann** [comment]
Great! 

was also thinking about such a "solution", makes the test button much more useful :)
