### ISSUE TITLE
Different Kaku devices impossible to pair

### ISSUE THREAD

**Issue by tjeerdsmam** [athombv/homey#490]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
I want to pair the following devices from KAKU

ACM-3500-3 3-in-1 
AWMR-210 Mini dimmer
ACDB-6600AC Doorbell

*Please include detailed steps how we can reproduce the issue*
ACM 3500 no possibility to pair in homey
AWMR-210 no possibility to pair in homey
The doorbell is nog recognized by homey

**What was the result?**
Nothing happend
...

**What did you expect as result?**
I hoped they worked because I have an "KAKU home" :-)
...

**Any other remarks**
eee
...

**Comment by Willieku** [comment]
hello,
me also.
i have a ACDB-6500A    also in a kaku home. (now managed by a homewizard)

**Comment by tjeerdsmam** [comment]
After a recovery and a full reinstall I can pair with:

ACM-3500-3 3-in-1 
ACDB-6600AC Doorbell

The doorbell is not recognized in the flow

I cannot pair with AWMR-210 Mini dimmer 

Greetz,
Michel

**Comment by spoelly** [comment]
I can pair the AMC-3500-3 3-in1 but can't control it. I don't know if its a support problem or a signal problem..

**Comment by Willieku** [comment]
Hi, i also Have a 3500.  Worked whit No problem. Till yesterday.  My
distance is abbout 15 meters. Sending never been a problem for me but
receiving from sensors is very poor.
For now the problem is No Response of any kind.
Athom is working on IT as we speak.
Seems hè did find the problem and looking for a solution.
Op 25 apr. 2016 12:20 schreef "spoelly" <notifications@github.com>:

**Comment by spoelly** [comment]
Ok thougt so.. because my homewizard wich is further away does work.. with the 3500 (20 meter). homey is at 15 meters

**Comment by spoelly** [comment]
Ok the 3500 is working now. Bought a signaal range extender and it is working now

**Comment by Willieku** [comment]
Axe701?
Op 29 apr. 2016 21:05 schreef "spoelly" <notifications@github.com>:

**Comment by spoelly** [comment]
Indeed!
