### ISSUE TITLE
KAKU button G doesn't work in card

### ISSUE THREAD

**Issue by patrick138** [athombv/homey#491]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Create an action based on pressing the G button of the remote.

**What was the result?**

Doesn't work. When pairing the remote it does register it when I press the G button.

**What did you expect as result?**

Pressing the G button should work

**Any other remarks**

Maybe it's a card issue? I have to specify a channel and configure on/off in the card. But afaik button G is always off for all channels.

**Comment by patrick138** [comment]
Ah I might be because I have the APA3-1500R?

**Comment by Dennishacq** [comment]
@patrick138 
Thank you for posting your issue.
Could you post a screenshot of your flow?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
