### ISSUE TITLE
After reboot storage indicator not updated

### ISSUE THREAD

**Issue by hekstman** [athombv/homey#493]
After a reboot the storage indicator keeps saying "Loading ..." for hours at least. 

 - Henk

System Information
Homey Firmware Version: 0.8.29
Athom Cloud ID: 56cb277e1a658d9b579e553e

Storage
Loading...

**Comment by WeeJeWel** [comment]
Do you have any Apps installed?

**Comment by hekstman** [comment]
At the moment when I submitted I had not.

 - Henk

**Comment by WeeJeWel** [comment]
It's a known bug fixed in 0.8.32. I'll close this issue. Thanks for reporting!
