### ISSUE TITLE
Cannot authenticate my Nest Protect

### ISSUE THREAD

**Issue by RichardAben** [athombv/homey#494]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

When I click on authenticate with Nest, I'm forwarded to the nest website. There I click on accept, but then I get an error message: "An error occured. Verbinding maken met Athom Homey is momenteel niet mogelijk. Neem contact op met Athom voor meer informatie."

**What was the result?**

See error message above.

**What did you expect as result?**

Screen to authenticate.

**Any other remarks**

...

**Comment by RobinBol** [comment]
Fixed in next release of app.
