### ISSUE TITLE
Setup issue: "could not connect to that Wi-Fi network" (on brand new Homey)

### ISSUE THREAD

**Issue by Bumblez** [athombv/homey#495]
**What is your Homey version (Settings → System)?**
? (first time setup, brand new Homey)

**What did you try to achieve?**

For the past 3 days (ever since I received my new Homey), I have been trying to get Homey to connect to my Wi-Fi network. See also email request #187 to Athom support and this thread on the forum:
https://forum.athom.com/discussion/1090/homey-unable-to-connect-to-wifi

What I do:
- I plug in the power cord
- Homey starts up.
- "Hi, I'm Homey. Please use your computer to go to setup.athom.com."
- I see that HomeySetup is present in the WiFi connection options of my phone/tablet/PC.
- I start up Chrome (on my phone/tablet/PC) and go to setup.athom.com
- when it tells me to connect to HomeySetup, I switch to the HomeySetup WiFi network
- the very first time I try this (after I powered up Homey), it doesn't work (the browser page does not continue), so I refresh the browser page (setup.athom.com) (it then fails to connect to the internet, so I switch back to my WiFi network, then refresh the setup.athom.com web page again).
  When the page has loaded, I switch WiFi to HomeySetup again
  This time, it shows me the "Select your home Wi-Fi network" page.
  I select the SSID, click Continue, enter the password, click Continue.
- The web page says "Please wait...  Homey is connecting to..." and Homey's led ring is spinning.
- After about 20 seconds, my phone/PC has lost the WiFi connection to HomeySetup, and automatically switches back to my own WiFi network (that same SSID).
- Around that same time, I see a line in my router logs:
   "[DHCP IP: (192.168.1.20)] to MAC address 6C:**\* (etc)"
   (note: .20 is the IP address I assigned to Homey's MAC address in my router. So that part works)
- After about 45 seconds, Homey replies
   "Sorry, but I could not connect to that Wi-Fi network"
- In my network logs, I see that it never actually connects to my network with the .20 IP address... the only IP address I ever see in the network (in connection with Homey's MAC address), starts with 10.199.

This happens no matter how often I try, and no matter which changes I made in my router setup.

Apparently I am not the only one having problems with this... there are quite a few other people reporting issues with this in that same forum thread. For some it works after changing certain settings in their router, for some it suddenly works after trying a number of times... for some (like me) all that doesn't work, and I still can't connect Homey to the internet.
This needs to be improved (definitely before the next batch goes out), so that connecting Homey to the Wi-Fi network is as easy and as fool proof as with any other device (I have over 15 different devices that are able to connect to my Wi-Fi network, none of them ever had any problems with it. Homey is the first one.

**Comment by bvdbos** [comment]
I'm getting the feeling that some sort of sanitizing strings is done on the Password and perhaps. Did you try a lower-case password?

**Comment by Bumblez** [comment]
@bvdbos  Yes, I tried setting both my SSID and my password to lowercase strings without any special characters in them... didn't make any difference.

**Comment by bvdbos** [comment]
Did you do a full reset to recovery? 
https://www.athom.com/nl/ondersteuning/KB000026/

**Comment by Bumblez** [comment]
I did... didn't work either. Also, I believe (as Stefan explained in a post on the forum thread I linked) that that recovery option is only useful if Homey was ever able to complete setup... which, in my case, it never has.

**Comment by TedTolboom** [comment]
@bvdbos lower case or special characters should not make a difference... 

see issue #41 

I'm currently able to connect to an SSID with capitals and special characters and with a password which resembles: \nlFOfWz]7r4IP0gZO_t9R&V<=ddH8I7zuR#G1hEaM;\x&=laydAcu?Aw=ly2.-

**Comment by harmstellinga** [comment]
Have you tried to type in your wifi network, not just select ?.

**Comment by Bumblez** [comment]
Yes, tried that too.

**Comment by freemann** [comment]
You could try to setup a Hotspot on another device and see if homey wants to connect to it?
Android supports it or else software like "Connectify" can be options.

**Comment by Bumblez** [comment]
@freemann - thanks, that's actually not a bad idea at all. I'll give it a try tonight..

**Comment by Bumblez** [comment]
@freemann Awesome, that actually worked. My homey is connected now. This definitely proves that this is a software issue... something they absolutely need to fix (and make sure that fixed firmware is installed in all new Homeys) before the next batch goes out the door.

**Comment by freemann** [comment]
Awesome! :smiley:

Glad that I could help and totally agree with you!
Have big time fun with your Homey!

**Comment by Bumblez** [comment]
> What did you do and/or which "solution" did you use?

Well, I don't really consider it a solution... it was a workaround. The real solution to this problem should be a software fix. But this is the workaround (based on your comment, and on the post by fredsky on the forum):

1. First I shut down all the WiFi accesspoints of my router.
2. Then I created a mobile hotspot on one of my Android phones (4G), made name en password of the hotspot the same as they are on my accesspoints.
3. Rebooted Homey
4. Used a second Android phone (connected to the hotspot) to connect to setup.athom.com (and to HomeySetup), to make the connection between Homey and the hotspot.
5. Waited for Homey to finish updating/installing its firmware.
6. Once Homey was completely finished, I took the plug out of Homey, turned the mobile hotspot off and restarted the accesspoints.
7. Replugged Homey

Now Homey got its IP address from the router, and I was able to connect to it from Chrome on my PC.

**Comment by bvdbos** [comment]
If 8.8.8.8 as DNS is hardcoded for Homey-setup, wouldn't that be an explanation for most of these problems?

**Comment by Bumblez** [comment]
Not necessarily... the DNS should only be used for mapping web address names to IP addresses, it should never influence the (internal) IP address that Homey receives from the router's DHCP. So it shouldn't matter all that much if you use 8.8.8.8 or the provider's (in my case Ziggo's) DNS servers.

I get the feeling that, when Homey has verified the SSID and password (and has obtained its IP address from the router), it shuts down its own web server and after that it tries to rebuild the connection in a not completely standard way. And then suddenly it can't connect to the router anymore... that's what Athom will need to look into and fix.

**Comment by WeeJeWel** [comment]
Should be fixed in the new setup.
