### ISSUE TITLE
Cannot add "Thinking Cleaner" roomba as device

### ISSUE THREAD

**Issue by RichardAben** [athombv/homey#496]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

When I select the Thinking Cleaner device to add this, I receive the message: "There where no devices found! You may close this window" 
Off course the device is turned on and in the same room as Homey.

**What was the result?**

See message above.

**What did you expect as result?**

I would expect a screen to add my roomba to Homey.

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Can you please specify your product number of your roomba and the thinking cleaner shield?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
