### ISSUE TITLE
Chrome uses a ton of CPU

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#499]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Setting flows without excessive CPU usage.

**What was the result?**

It wasn't possible.

**What did you expect as result?**

A normal experience, with a silent macbook.

**Any other remarks**

Nup!

**Comment by WeeJeWel** [comment]
What were you doing in Homey?

**Comment by WeeJeWel** [comment]
Is this still happening?
