### ISSUE TITLE
Can't add NEST Smoke detector

### ISSUE THREAD

**Issue by bierre** [athombv/homey#501]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Add NEST smoke detector.
Tried to add add it
Logged on
Clicked on authenticate

**What was the result?**
After logon I get an error:  
An error occured.
Verbinding maken met Athom Homey is momenteel niet mogelijk. Neem contact op met Athom voor meer informatie.

**What did you expect as result?**

NEST protect added as device
**Any other remarks**

...

**Comment by RichardAben** [comment]
same problem in ticket #494

**Comment by RobinBol** [comment]
Fixed in next release of the app.
