### ISSUE TITLE
Setting LED to 'fixed color' in a flow does not work properly.

### ISSUE THREAD

**Issue by thezahir1** [athombv/homey#502]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

After a certain hour I want my Homey to show a certain LED color and animation. Somehow this does not work. Pressing 'test' does the thing but only for a second or so, after which the LED goes to the situation it was before running the flow.
However, when setting luminance to 0%, and running the flow, the LED (correctly) stays on 0%.

*Please include detailed steps how we can reproduce the issue*
See my created flow here.

**What was the result?**

See above.

**What did you expect as result?**

I'd expect that the LED stays in the situation that I've described in my flow.
![4ye9qf98si71](https://cloud.githubusercontent.com/assets/15107075/14763373/249106b4-0994-11e6-84a9-4c0c7de902f5.png)

**Any other remarks**

...

**Comment by ruudonline** [comment]
Similar Issue. I would like to be able to set a fixed color of the LED ring.

**Comment by thuijbers** [comment]
Same here, also version .29. You can select the color to change the LED ring, but it always stays orange.

**Comment by JPe2** [comment]
Same here, version: 0.8.29. 
The color of the LED-ring is changing for 1 or 2 seconds, but then the previous setting returns.

@thuijbers  , did you press "OK" when changing color (bottom right where the choosen collor is shown)
the OK text is hardly readable, as many texts are in the flow editor, maybe a darker letter color could be used?

**Comment by thuijbers** [comment]
@JPe2 haha thank! Didn't see the "OK" button. It works indeed :+1:

**Comment by WeeJeWel** [comment]
This is intended behavior, as the card is called 'animate'.

In the future, flow actions will have a 'duration' property. There you can then set the duration of this animation.

**Comment by thezahir1** [comment]
Aha. A bit unclear if you ask me. 
I would then add an extra option 'set color to' which changes the color until further notice (read: another flow changes it again).

**Comment by WeeJeWel** [comment]
I think that'd be too confusing. How to 'remove' it again, for example..

I'm more a fan of a 'set screensaver' card, with a color option.

**Comment by thezahir1** [comment]
Yes that would do it too. 
"More roads leading to Rome".

**Comment by WeeJeWel** [comment]
0.8.34 added a card 'set screensaver'.
