### ISSUE TITLE
Time not recognized with "tomorrow" at the end

### ISSUE THREAD

**Issue by tmsns** [athombv/homey#503]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Within my app, I tried to get a "time" object for my trigger. The phrase was:
"What do we do tomorrow?" So the time object was at the end.

**What was the result?**

There was no time object.
```
parseThis() { transcript: 'what should we do tomorrow',
  language: 'en',
  triggers: [ { id: 'test-do-something', position: 15, text: 'do' } ],
  zones: [],
  time: false,
  devices: [] }
```

**What did you expect as result?**

I expected a time object.

**Any other remarks**

If I reverse the phrase, I get a time object:
```
parseThis() { transcript: 'tomorrow what should we do',
  language: 'en',
  triggers: [ { id: 'test-do-something', position: 24, text: 'do' } ],
  zones: [],
  time: [ { transcript: 'tomorrow', index: 0, time: [Object] } ],
  devices: [] }
```

**Comment by Tweake** [comment]
Already fixed in pull request #75
