### ISSUE TITLE
homey deaf when led ring turned off via flow

### ISSUE THREAD

**Issue by greatpetie83** [athombv/homey#505]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

Flow:
At 23:00 set Led ring brightness to 0% (at 7:00 it goes back to pulsing and when I test that Homey listens to voice commands again)

![image](https://cloud.githubusercontent.com/assets/18635955/14764360/3fb9cd92-09b5-11e6-82af-10c33984ce7b.png)

**What was the result?**

Homey does not respond to the voice trigger any more after the brightness has been set to 0 for the night.

**What did you expect as result?**

Not a deaf Homey just a dark Homey

**Any other remarks**

...

**Comment by kerkenit** [comment]
+1

**Comment by luccie007** [comment]
I have 0.8.30 (experimental) and can confirm this now works okay.

Mine still listens when I set the LED ring to 0%.

**Comment by greatpetie83** [comment]
@luccie007 thanks for the info. I'll wait till 0.8.30 is a 'normal' update and not an experimental one.

**Comment by WeeJeWel** [comment]
It does still listen, but you probably don't see the feedback because, well, you dimmed the led ring.

Use a screensaver called 'Off' in this case.

**Comment by greatpetie83** [comment]
What do you mean with the screensaver or the Dutch name for this setting?

**Comment by Dijker** [comment]
When you dim to 0% you dont see the ring pulsing on OK-Homey,

There is no flow action-card at this moment to set the screensaver, 

You can set it in Settings:
![image](https://cloud.githubusercontent.com/assets/12412734/14930995/58f5d956-0e68-11e6-8976-fb2eddddc3a6.png)

Set it OFF with at least some Brightness for the feedback on your OK-Homey's

(You can probably create it yourself with a PUT to the api with:  {"uri":"homey:manager:ledring","name":"off","options":{}}  )

**Comment by Dijker** [comment]
@greatpetie83 
use this card / instruction to disable the screensaver / set the idle option: 
https://forum.athom.com/discussion/comment/20667/#Comment_20667
