### ISSUE TITLE
Homey trigger's on wrong weeknumber

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#507]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Making a flow that trigger's on specific weeknumber.

*Please include detailed steps how we can reproduce the issue*

I'll make a flow that trigger's (in the AND column) when weeknumber is 16. (building block: date&time) 

**What was the result?**

Nothing, after a little bit testing with the weeknumbers i see homey thinks it's weeknumber 18. 

**What did you expect as result?**

Homey trigger's on the correct weeknumber (this week is number 16 in case of 18)

**Any other remarks**

Nope.... o yes! i like homey :-)
...

**Comment by WeeJeWel** [comment]
Fixed in 0.8.33, now uses ISO week numbers.
