### ISSUE TITLE
Variable in reminder reply

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#508]
**What is your Homey version?**
0.8.30

**What did you try to achieve?**

Set a reminder for pizza in 11 minutes

**What was the result?**

Me: Remind me in eleven minutes of pizza
Homey: I have set the underscore underscore type underscore underscore reminder (i have set the \_\_type\_\_ reminder)

**What did you expect as result?**

Don't know what \_\_type\_\_ should be but I don't think this is it

**Any other remarks**

The timer was set for 7 minutes, ate cold pizza :(

**Comment by DieterKoblenz** [comment]
Same issue with 0.8.34 and __type__. Seems the reminders fires at the right moment though.

**Comment by Tweake** [comment]
Is this still an open issue? Just tested it with "Set a reminder for pizza in 11 minutes" and 11 minutes later Homey said "I just want to make sure the you remember pizza"

**Comment by Joolee** [comment]
Seems to be solved :)
