### ISSUE TITLE
Netatmo outdoor unit, rain gauge and wind gauge data

### ISSUE THREAD

**Issue by BasPost** [athombv/homey#509]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Install Netatmo app

**What was the result?**

Only base station/indoor unit data is used

**What did you expect as result?**

Use also data from outside unit, extra indoor unit, rain gauge and wind gauge.

**Any other remarks**

Please add the extra units data please

**Comment by Dijker** [comment]
Duplicate ¿https://github.com/athombv/com.netatmo/issues/4

**Comment by BasPost** [comment]
I'm closing this issue regarding issue #4
