### ISSUE TITLE
Change 'Power Usage' to 'Power Meter'

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#511]
**What is your Homey version (Settings → System)?**

0.8.30

**Change request?**

Change the display name of the power meter from 'Power Usage' to 'Power Meter'.
![image](https://cloud.githubusercontent.com/assets/11725674/14768525/292afad4-0a45-11e6-983f-cb6f650dd64e.png)

**Reason?**

1. The power meter can be used for a consumer as well as a producer. For a producer 'Usage' does not make sense.
2. In the flow card the conditions also refer to 'power meter'

**Comment by Dijker** [comment]
+1

**Comment by denniedegroot** [comment]
I think this also applies to "Gas Usage".

**Comment by WeeJeWel** [comment]
Fixed in 0.8.33
