### ISSUE TITLE
Add Homey.manager('app')

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#512]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Let 2 apps communicate with each other.

**What was the result?**

Unable to determine from app A whether app B is present, running and what version it is.

**Change request?**

Add Homey.manager('app') to get app status and info.

**Proposal?**

> Homey.manager('app')

The 'app' manager is a convenient way to determine the presence and status of an app.
This is useful when two or more apps want to communicate with each other.

Methods

```
// Get information on the status of an app
   .state(
      string id, // e.g. 'nl.philips.hue'
      function (optional) callback(
         mixed err,
         object status  // { state: [unavailable, starting, running, disabled], string version }
      )
   )

// Fired on app state changes
   .on(string id, // e.g. 'nl.philips.hue'
      object new_status // { state: [unavailable, starting, running, disabled], string version }
   )
```

_or something along these lines._

**Comment by WeeJeWel** [comment]
This has been added in v0.8.34. See https://developers.athom.com/library/api/ for documentation.

**Comment by nlrb** [comment]
Thanks for the (partial) implementation. The crucial part is unfortunately missing. An app is not informed (can not register on an event) of when another app is being installed/de-installed/disabled/enabled.

Also, you cannot get the properties of an app, like the version.

Can you please add these 2 capabilities as well?

**Comment by matjaz** [comment]
app state change event would simplify `getYouTubeApp` and need to pooling state of the app. app version is a must to build good user experience apps without pooling.
https://github.com/matjaz/com.google.chromecast/blob/670f139f368dc036a1e94cdf93b586e940212019/app.js#L93

**Comment by nlrb** [comment]
Any progress on  this? Is there a chance it will be implemented before the 1 year anniversary?

**Comment by WeeJeWel** [comment]
Yes, this will be added in the Homey Apps SDK v2, which is scheduled to be released within a few months.

**Comment by WeeJeWel** [comment]
Sneak preview of Apps SDK v2 concerning App to App communication:

```javascript
	let app1 = new HomeyApiApp('com.athom.app1');
	app1
		.register()
		.on('realtime', this.log.bind(this, 'app1.onRealtime'))
		.on('install', this.log.bind(this, 'app1.onInstall'))
		.on('uninstall', this.log.bind(this, 'app1.onUninstall'))
		.get('/')
			.then( this.log.bind( this, 'app1.get') )
			.catch( this.error.bind( this, 'app1.get') )
			
	app1.getInstalled()
		.then( this.log.bind( this, 'app1.getInstalled') )
		.catch( this.error.bind( this, 'app1.getInstalled') )
			
	app1.getVersion()
		.then( this.log.bind( this, 'app1.getVersion') )
		.catch( this.error.bind( this, 'app1.getVersion') )
```

**Comment by nlrb** [comment]
Thanks for the info. I've been looking at the docs, but it doesn't really state when 'getInstalled' is true.
E.g. if the app is installed, but not yet initialized - does it return true (i.e. during startup)?
If the app is installed, but it has crashed (is not running) - does it return true or false?

How can you check if an app is up and running?

**Comment by WeeJeWel** [comment]
The `ApiApp.getInstalled()` state is only true when the app is installed, enabled and running. For the developer point of view, all other states are irrelevant. So you should read `installed` as `online` or so.

**Comment by WeeJeWel** [comment]
I have updated the docs accordingly (not yet online).

**Comment by nlrb** [comment]
Thanks for clarifying. Indeed `online` would then be a better name for the function. One final question on this one: 'running' - does this mean the init function (or v2: onInit) has _completed_?

**Comment by WeeJeWel** [comment]
App#onInit is synchronous so it is by definition completed before an API call can be received :-)

**Comment by nlrb** [comment]
Yes, asynchronous, however you could still set the flag to true before entering  the call ;-). But this is excellent, thanks for confirming!
