### ISSUE TITLE
KaKu AWMT-230 can be added, but no response in flows

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#513]
**What is your Homey version (Settings → System)?**

0.8.30
**What did you try to achieve?**

paired the AWMT-230 switch from KaKu, which succeeded succesfully
add the switch to a flow, but nothing happens when the switch is used

created the flow ' if switch is switched to on, speak ' het werkt' '
homey says nothing

**What was the result?**

no action as result of switch usage

**What did you expect as result?**

working switch

**Any other remarks**

...

**Comment by laurenssss** [comment]
better results now once I switch off the homewizard, probably they interfered

however every flip of the switch results in 3 times the flow being triggered

**Comment by Dennishacq** [comment]
@laurenssss 
Good to hear that your is solved.
I'm testing a new debouncer at this moment. This debouncer should fix the flow triggering multiple times.

**Comment by Dennishacq** [comment]
KaKu v1.1.12 is ready to be downloaded!
This version includes the new debouncer.
Please let me know how It Works.
