### ISSUE TITLE
Somfy My command

### ISSUE THREAD

**Issue by zperx** [athombv/homey#514]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Close the blinds by using Somfy`s My command.

**What was the result?**

There is no such operation as My. Can`t close the blinds.

**What did you expect as result?**

Close the blind using the flow

**Any other remarks**

Some cases the the end position of the blind is not equal with the closed position. I have such blind. In order to close the blind a preset position is needed.

...

**Comment by JPe2** [comment]
In my case (a sunscreen) on the remote there is a button "My" that can be used to stop the UP or DOWN movement (probably also possible to use to, and start to goto, a preprogrammed position between fully UP and fully DOWN).,
In the Homey App the "stop" button is visible and also working, but when creating a flow, the "Stop" command is not available. 
Can this be added as a choise please? 
If so, also with the delay option please.

**Comment by zperx** [comment]
Or like in Zipato to be able to set %. (If i remember well the user must measure the time it needs between the two end points)

**Comment by JPe2** [comment]
Therefore i asked for the delay option, so start closing, and after te delay, stop closing in the same flow.
If totaly closing takes 20 seconds, you can stop with a delay of 10 seconds, to close 50%.

**Comment by Dennishacq** [comment]
Hi guys,
Thank you for reporting this issue.
I have implemented the My command in the new Somfy update.
This updated is waiting to get tested and should be up somewhere next week.

**Comment by zperx** [comment]
Thanks a lot. Indeed the new version has that function.

**Comment by zperx** [comment]
Yes it has the function but it does not work.
I have two blinds. Both on the same remote. One is battery powered 3 meters away from homey. The other one is mains powered and one floor above.
Strangely only the one further away reacts on the MY or Idle command. And even this one does not work properly the MY command. It moves the blind with 1 cm than stops. I suspect the signal is sent out couple of times so first it takes it as a my command and the second time as stop command thats why it moves just a little. It works properly with the idle command (but only the mains powered blind).

**Comment by Dennishacq** [comment]
@zperx 
I have just released v1.0.13 of the Somfy app which sends the signal with a smaller amount of repititions. Please let me know if this fixes the problem.

**Comment by zperx** [comment]
Sorry mate it does not work (Homey 0.8.35, Somfy 1.0.13, the Somfy system is about a year old). It took three hours to reset everything, reprogram the blinds, test them separately and try every scenario (I did these couple of times). The end result is the same. This one does not work at all:
![somfy my](https://cloud.githubusercontent.com/assets/18647800/15454246/df78555c-202a-11e6-8f95-aa90adfe91cf.jpg)

And this one only works with one blind:
![somfy my2](https://cloud.githubusercontent.com/assets/18647800/15454248/15576ece-202b-11e6-9fda-0dde3ced9c68.jpg)

**Comment by Dennishacq** [comment]
@zperx
Are both blinds reacting when your are sending the up or down command?

**Comment by zperx** [comment]
Apology. I have been away. Yes they both react on up or down command when I use the device card or the `set state` flow card.

**Comment by BasKiers** [comment]
I will close this issue due to lack of activity and because the app is no longer maintained by Dennishacq for quite some time now. If you still experience this issue please open a new one.

Regards,
Bas

**Comment by zperx** [comment]
Can make it work by using different signal lengths in the settings and use the "Idle" as "MY"
