### ISSUE TITLE
5th Gen. Fibaro multisensor (v3.2) does not communicate with Homey after the pairing

### ISSUE THREAD

**Issue by zperx** [athombv/homey#515]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

To use the 5th Generation Fibaro multisensors (v3.2).

**What was the result?**

There is no communication between homey and the sensor after the pairing. Homey cant send setting data to the sensor and the sensor cant send temp, alert, illumination and battery level to homey. Flows are never triggered. Insight and the device card has only the initial measurements.

**What did you expect as result?**

Receiving data from the sensor and triggering flows.

**Any other remarks**

I know that there is a closed issue (#400) but that is about the pairing. There is no issue with that in this case. After pairing the sensor had been reseted, homey rebooted and sensor manually woken up.

**Comment by zperx** [comment]
The 0.8.32 firmware havent fixed this. Although the secure option is not forced any more there is still no communication either way.

**Comment by ocatie** [comment]
Could you try to manually make an association on group 1, save device settings, wake up the sensor manually. If you leave the sensor for a minute facing a wall the tamper and motion alarms will be reset. Then if you pick it up the motion and tamper alarm will trigger which you should see in the device card.

**Comment by zperx** [comment]
Definitely not working. The ambulance and the sedative is on its way they are taking me back to metal care.<br><br>So first try: No security option but the issue was the same: Homey was not receiving values, sensor not receiving settings.<br><br>2nd try: Security option selected by default (and beyond this point it was always selected a grayed out). However homey was receiving values. Alerts were cancelled in due time. Had some figures in the insight, though not everything. So I have restarted homey. After that no response.<br><br>3rd, 4th, 5th, ......Nth try. Various issues every time:<br><br><img alt="" src="http://i.imgur.com/Ri3HZ47.jpg"><br><img alt="" src="http://i.imgur.com/5hEnoqk.jpg"><br><br><img alt="" src="http://i.imgur.com/aEEVnFy.jpg"><br><img alt="" src="http://i.imgur.com/A4KEcLp.jpg"><br><br>Homey has been been restarted after every un-pair, Z-wave network reset. Sensor was also reseted, battery removed. The distance between the Homey and sensor is still the same. And I have 3 sensors, so it is not a product fault.<br><br>So what is it?&nbsp;Is it a conspiracy or a solar flare?<br><br>The ambulance is here.

**Comment by ocatie** [comment]
Could you please send me a log after you've completed the pairing wizard?

**Comment by zperx** [comment]
Sorry ocatie. I have missed your message. There is communication but it is limited. So I am closing this issue. The real issue is this:
https://github.com/athombv/homey/issues/583

This is the cause for most misbehaviour.
