### ISSUE TITLE
Week number is not working

### ISSUE THREAD

**Issue by zperx** [athombv/homey#517]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Set up a flow triggered on certain weeks only. In this particular case week 16.

**What was the result?**

The flow is not executed.

**What did you expect as result?**

Working number of week condition.

**Any other remarks**

I have also tried with weeks 17 and 15 as well but no luck. Without the week condition the flow was executed.

**Comment by dhanstede** [comment]
Hello i have already report this issue #507

**Comment by zperx** [comment]
Yes indeed.
