### ISSUE TITLE
[Time] Does not say the hour

### ISSUE THREAD

**Issue by jdh009** [athombv/homey#519]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.30

**What did you try to achieve?**

Asking the time in Dutch. Both by voice and typing it in manager/speech-input/

"Wat is de tijd?" or "wat is de tijd"

**What was the result?**

de time is nul acht (de time is 08)

**What did you expect as result?**

"De tijd is 12:08", "Het is nu 12:08" or "Het is nu  acht over twaalf" or something like this

**Any other remarks**

De output at manager/speech-output/ says it should say "The time is 12:08"

**Comment by irritanterik** [comment]
@jdh009 It works ok for me on 0.8.34 now.

**Comment by RoadXY** [comment]
Same for me. It even seems like Homey is reading the time in better/perfect Dutch!

**Comment by RicardovanE** [comment]
same to mi but in my case it untherstands  "Tijd" as Date so reeds me the date.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
