### ISSUE TITLE
Toshiba AC remote not recognized - manual function not working right

### ISSUE THREAD

**Issue by novaflash** [athombv/homey#520]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
Add infrared remote control signals to Homey, so I can have the homey blast that same signal out, so that it can start/stop my AC, and hopefully set temperature too.

**What was the result?**
With great difficulty, Homey recognized a IR signal from my remote in manual control. But only one signal, no matter what buttons I press (temp up, temp down, power, quiet mode, etc..). As a result, the Homey sees only the one signal it did recognize, and thinks this is the same as all the other buttons on the remote. Whatever button I press, the Homey now thinks that I pressed the one signal it did recognize.

In 'automatic' mode it didn't recognize what remote control I have. In 'manual' mode, it only ever recognizes 1 signal.

Using a remote from my TV, IR works fine. But not this IR remote.

**What did you expect as result?**
That it would recognize different signals from my remote control, and that I could have the Homey repeat those signals in a flow. I just wanted the Homey to learn the signals from my AC remote, and to have the Homey repeat those signals by triggering it from a flow.

**Any other remarks**
It's a Toshiba remote control for a Toshiba AC. The Toshiba remote has this written on the back:
WH-TA04NE 40523C

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
