### ISSUE TITLE
Z-Wave Philio 4-1 PSM02-1 partly added

### ISSUE THREAD

**Issue by freemann** [athombv/homey#521]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Adding the Philio 4-1 PSM02-1 with all sensor active;
- PIR (alarm)
- Door/Window (Alarm)
- Lumination (LUX)
- Temperature (F/°C)
- Battery status (%)

*Please include detailed steps how we can reproduce the issue*

Go to Settings>Zwave and reset node
Go to devices>add>zwave and trigger Sensor to go into inclusion mode

**What was the result?**

Homey adds 2 nodes:
1. This device had 4 sub-sensors (generic alarm, temperature, lux, battery)
2. This device had 3 sub-sensors  (generic alarm, lux, battery)

Strange thing is that device 1 became "False" within a few minutes.
By using the Chrome Dev Tool I was able to remove the "unavailable" DIV and look at the device.
Looks like all settings between the 2 devices where the same;
Device 1 with 4 sub-sensors (left is the Generic alarm and so not shown):
![screenshot - 25-4-2016 20_11_27](https://cloud.githubusercontent.com/assets/601053/14793999/0ea3d3ce-0b22-11e6-9fbd-c38841245405.png)
Device 2 with 3 sub-sensors:
![screenshot - 25-4-2016 20_11_46](https://cloud.githubusercontent.com/assets/601053/14793998/0ea3b8ee-0b22-11e6-9b7b-c7cc14b11e7d.png)

**What did you expect as result?**

Only 1 Zwave device added with all sub-sensor available.

**Any other remarks**

**Comment by ocatie** [comment]
If a new Z-Wave node is a multichannel node, in Homey a root device will be made and 1 device for all endpoints. This will be made one device by an app.

If you could send a log I can take a look why the device became unavailable.

**Comment by freemann** [comment]
Reading my issue back I see I'm not really clear :smile:

I only have 1 PSM02 sensor and after including Homey created 2 devices, so both devices from the screenshots where created on my Homey.

To make things (hopefully) more clear;
After adding this one(!) PSM sensor Homey showed;
Device 1: Generic Alarm
Device 1: Luminance
Device 1: Temperature
Device 1: Battery

Device 2: Generic Alarm
Device 2: Luminance
Device 2: Battery

So after adding the one sensor I had 2 devices with in total 7 endpoints.

Does a System log help, this because its 2 days ago and I already deleted the device.

**Comment by ocatie** [comment]
What were the node id's of those devices as listed in the device settings? If you could add the sensor again and send a log that would indeed help.

**Comment by freemann** [comment]
I have no idea what the node id's where. Is it the n useful to keep this open and/or send a system log?

**Comment by ocatie** [comment]
If you could reproduce the issue and send a log, that would help big time.
