### ISSUE TITLE
Not able to scroll in Z-Wave settings page

### ISSUE THREAD

**Issue by freemann** [athombv/homey#522]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Set polling for Z-wave device

*Please include detailed steps how we can reproduce the issue*

Add Fibaro 2 x 1,5 kW V2.2 device
Go to device>settings and try to scroll to Polling input field
![screenshot - 25-4-2016 20_21_14](https://cloud.githubusercontent.com/assets/601053/14794317/ab164646-0b23-11e6-8770-3f5bfbab63ac.png)

**What was the result?**

Not able to scroll down

**What did you expect as result?**

A scrollbar to scroll down

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed in 0.8.33
