### ISSUE TITLE
Kaku APA3-1500R not working after reboot homey

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#523]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**

Try to turn on the light

*Please include detailed steps how we can reproduce the issue*

After pairing the kaku apa3-1500r socket it works and the lights turn on and off. But after a reboot of homey, the socket is not reacting anymore. I have to pair the socket again.

**What was the result?**

apa3-1500r not working after the reboot 

**What did you expect as result?**

apa3-1500r also works after a reboot

**Any other remarks**

**Comment by dhanstede** [comment]
After i have updated to 0,8,32 and disconnect te power plug for about 5 minutes, kaku works and i can add devices. Also after a reboot, the kaku devices still works :-)

If kaku still works the coming days and reboots, i will close this issue.

**Comment by dhanstede** [comment]
After the second reboot, kaku devices are nog responding on on/off. But after that, i disconnect the power plug for 1 minute. And now all the kaku devices are work again. It looks like it's a bug in the reboot process ?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not in version 0.9.2?

**Comment by dhanstede** [comment]
After updating to firmware 0.9.2 and rebooting homey  my kaku socket APA3-1500R is still working.

Many thanks. I'll close this issue.
