### ISSUE TITLE
KAKU is stopt working

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#524]
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
put the lights on via KAKU
*Please include detailed steps how we can reproduce the issue*

Click via the mobile website  the light on but no responce from the KAKU
several times reboot homey, but no responce any more on the KAKU.
**What was the result?**
Light are not on
...

**What did you expect as result?**

...Lights must go on.

**Any other remarks**

...

**Comment by dhanstede** [comment]
Hi, look at issue #523. Maybe you can try to disconnect the power plug for 1 minute.

**Comment by ReinierH** [comment]
Looks like we found and solved the issue. More testing needs to be done to ensure this fix solved the problem. I will keep you posted.

**Comment by CootNL** [comment]
With 0.8.34 the problem is solved for me and in the 0.8.35 it is still working
