### ISSUE TITLE
Rebooting Homey results in "Error: true"

### ISSUE THREAD

**Issue by freemann** [athombv/homey#525]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Relaxed rebooting Homey without errors thrown at me :smile: 

*Please include detailed steps how we can reproduce the issue*

Go to Settings>System>Reboot

**What was the result?**

"Black" screen with a message that Homey is rebooting and all of a sudden it shows an error:
"Error: true"

**What did you expect as result?**

Just a screen/message that Homey is rebooting and not showing an error.

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Please try again on 0.8.30
