### ISSUE TITLE
Feature request; Some sort of small shortcuts to devices/flows/settings/insights

### ISSUE THREAD

**Issue by freemann** [athombv/homey#526]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Instinctively switch between devices/flows/settings/insights
 
**What was the result?**

Looking at the left top corner to switch between devices/flows/settings/insights

**What did you expect as result?**

Some sort of small icons set for devices/flows/settings/insights on the top left corner

**Any other remarks**

Some sort of mock-up;
![homeysmalltopleveicons](https://cloud.githubusercontent.com/assets/601053/14809337/a785b73c-0b8c-11e6-813b-1c7426b22399.jpg)

**Comment by RoadXY** [comment]
What's wrong with the menu button on the top right then?

**Comment by freemann** [comment]
Nothing!

**Comment by RoadXY** [comment]
Lol, why would you like to have these small icons on the top then?

**Comment by freemann** [comment]
Mos of the "action(s)" are located on the left side of the screen and that's on all "pages" (devices/flows/insights/settings). 
Changing between these screens needs 2/3 "actions";

1. - move mouse "all the way" to rights top corner
2. - wait a XXX millisecs
3. - move mouse to overlay (carefully to no go out of overlay because else it disappears)
4. - click on the icon of the desired page

By adding shortcut icons on the Top Left corner its only;
1. - move mouse to icon set
2. - click on the icon of the desired page

**Comment by WeeJeWel** [comment]
Hm, sorry, won't change this for now.
