### ISSUE TITLE
Create new device in the zone where the adding is initiated.

### ISSUE THREAD

**Issue by freemann** [athombv/homey#528]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Adding a new device to zone "Bla"

**Please include detailed steps how we can reproduce the issue**

Go to zone "Bla", click the "add/+" button and walk through the pair wizard.

**What was the result?**

New device added to "Home" zone.

**What did you expect as result?**

Device being created in the zone "Bla" where i pushed the "Add/+" button.

**Any other remarks**
none.

**Comment by nattlip** [comment]
in 0.8.31 experimental  the new device is added in the bla zone

**Comment by freemann** [comment]
OK! for now pause/close :+1:

**Comment by daneedk** [comment]
Just tried on 0.8.32, Added to Aeotec MultiSensors 6 to 'sub' zones but the devices showed up in the (top) Home zone. 
This was after a full reset and wipe, no idea if it helps, but this is the crash log: 7F3B2BDE0C

**Comment by freemann** [comment]
@daneedk 
Thanx for testing!

**Comment by bvdbos** [comment]
Works for me with a kaku-light on 0.8.32.
