### ISSUE TITLE
Problem with Homey user presence state

### ISSUE THREAD

**Issue by BSWG** [athombv/homey#530]
Hi,

I have the following flow:
If 'Every 1 minutes'
And 'Nobody is at home'
Then 'Led ring brightness 0%'

(And one that activates the led ring when at home and before night)

The Homey Android App says I'm home. Which is very clever ;) and true.
But still it will automatically shut down the led ring. Probably because Homey thinks I'm not at home.
Somehow presence is not properly tracked by Homey?

Homey version 0.8.30

**Comment by BSWG** [comment]
Also, but that is a separate improvement, it would be nice to have the 'Nobody at home' trigger available in the If lane. It is now only available as condition in the And lane

**Comment by BSWG** [comment]
I think this is caused by a restart of Homey, due to switching from English to Dutch. It won't detect current users that are currently at home. They might be redetected when leaving and then coming back home.

**Comment by WeeJeWel** [comment]
As of Homey v1.1.4 the presence state will be persisted for maximum 30 minutes during reboots.

**Comment by dvanp** [comment]
> As of Homey v1.1.4 the presence state will be persisted for maximum 30 minutes during reboots.

The presence state doens't seem to persist on reboot for me, on 1.2.0-rc.10. Each reboot sets presence to unknown/not present.

**Comment by chrisboer** [comment]
Same here, after reboot all presence goes to NO
