### ISSUE TITLE
Flow UI input autocomplete broken

### ISSUE THREAD

**Issue by BSWG** [athombv/homey#531]
I'm trying to select an IR command from the IR device card. But the list is long and scrolling only sometimes works on Chrome with the typical Mac OS X auto disappearing scroll bars. Scrolling with the touchpad does not work with the dropdown list that is shown.
Also searching seems to work somewhat buggy. I'm searching for 'On' and 'Off'. But the results seem to be a little random. And commands that do not match the type ahead search are still shown.

Homey version 0.8.30

**Comment by goldenice** [comment]
This was actually fix quite some time ago. However, if you still deem this an issue, please wait for the upcoming IR release (not in 0.9 yet, but one or two updates after that) before reopening.
