### ISSUE TITLE
Can not enter text in the flowmanager

### ISSUE THREAD

**Issue by HuubNabben** [athombv/homey#533]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
I wantend to Ad à vioce in the when part of the flow. NeXT I wantend to ender tekst. Thuis was not positie.
I wantend  to give the flow à name. I can not enter the name.
I dragen à vioce to the than-part of the flow and wanten to enter text. Thuis is not posible.

I did add divices and zones. In that part is was posible to enter namen.

Please include detailed steps how we can reproduce the issue*
I use safari (Apple) latenst version 9.1 (11601.5.17.1) on the latest version of iOS (OS X EI Capitan version 10.11.4)

**What was the result?**
I can not use the voice function because u can not enter text in the box.

**What did you expect as result?**
I expediteur that I can enter text like " hello"

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Please use Google Chrome, it's the only browser supported as of now.

**Comment by HuubNabben** [comment]
Hoi Emile.

I will do so. Thanks for the swift responce👍

Kind regards 
Huub Nabben
