### ISSUE TITLE
Sporadic success with IR commands

### ISSUE THREAD

**Issue by BSWG** [athombv/homey#535]
I'm trying to send power and mute commands to my Samsung TV automatically and correctly detected as S-25M6HNQ. But sending commands only works on certain angles (I have to rotate Homey or place it higerh/lower) and even then sporadicly. Therefore it is currently mostly useless for toggling commands (like power and mute)

Homey version 0.8.30

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
