### ISSUE TITLE
Long lists of flows and cards

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#536]
**What is your Homey version (Settings → System)?**

0.8.2

**What did you try to achieve?**

I want to see all my flows and cards from the long list. I can't scroll through the list.

**What was the result?**

Hidden objects.

**What did you expect as result?**

See a scrollbar in the flow list, and incase of lot's of cards.

**Any other remarks**
I zoom out to solve this issue. But right now I've 30 flows, and the list is growing. So right now my interface is zoomed out to 50 percent. My eye's are getting nuts.
But hé. I got a lovely Homey to talk with.

**Comment by irritanterik** [comment]
#245
#383
#274
#200
