### ISSUE TITLE
IR database only works with 3 letters

### ISSUE THREAD

**Issue by bclevering** [athombv/homey#537]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
Search in the IR database but the search only triggers when you typ 3 letters; There are brands who only contain 2 letters (eg. LG)

**What was the result?**
No database hits on LG

**What did you expect as result?**
A nice database result with lots of remotes of LG so my IR is working with my TV/Soundbar etc.

**Comment by goldenice** [comment]
Good point! 3 characters is pretty standard, I haven't thought of the fact that in this case there are ofcourse valid queries consisting of only 2 characters. Not sure when I'll get around to it, but I will fix it.

**Comment by goldenice** [comment]
This was fixed in either 0.8.38 or 0.8.39
