### ISSUE TITLE
Trigger a flow from within another flow not working

### ISSUE THREAD

**Issue by bierre** [athombv/homey#539]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

- I have one flow which turns all lights in the living room on. This flow is triggered by a button press on a KAKU remote
- In another flow I also want to turn everything on when motion is detected. I want to do this by triggering the other flow. For testing purposes I've changed the motion trigger to NFC tag detected as  a trigger. And the flow also writes a confirmation to Slack.

**What was the result?**

- The second flow is triggered by an NFC card
- A confirmation of this triggered flow is written to Slack
- The "woonkamer alles aan"  flow is not triggered

**What did you expect as result?**
- The lights in the living room are turned on.
...

**Any other remarks**

...

**Comment by Dijker** [comment]
How do you want to trigger the other flow? what action card are you using?

**Comment by bierre** [comment]
I'm using the Flow action card.

**Comment by Dijker** [comment]
akaik it is only possible to enable or disable a flow. 
![image](https://cloud.githubusercontent.com/assets/12412734/14854941/fbf568a2-0c91-11e6-92d5-6a388206350c.png)
(so it isn't triggered...)

If you want you can use 3 flows, 
When [Kaku-Button-On] => Then Set Variable LightsLivingRoom =True
When [MotionDetected] => Then Set Variable LightsLivingRoom =True
When [Variable Changed LightsLivingRoom] => AND LightsLivingRoom = True => Then Switch all Kaku's  ON ...

and repeat 3 flows to turn off if you want ....

**Comment by bierre** [comment]
Thanx @dijker, I thought it could be used to trigger a flow. Then again, that would-be a nice feature in the future :-).

**Comment by bvdbos** [comment]
Actually I thought that too... Didn't a lot of people use this already? There's a strong use-case for the two cards turning on and off though...

**Comment by WeeJeWel** [comment]
Triggering flows from other flows is unsupported for now. As a workaround, download the KlikAanKlikUit app, add a socket by generating a signal, and use those cards.
