### ISSUE TITLE
KaKu Doorbell repeats

### ISSUE THREAD

**Issue by edtst** [athombv/homey#540]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Pressed the doorbell. 

*Please include detailed steps how we can reproduce the issue*

Add a 7000 series KaKu doorbell with support for an existing button (BC version)

**What was the result?**

Homey repeats the flow several times.
...

**What did you expect as result?**

Just execute the flow once
...

**Any other remarks**

Please build in some delay before a doorbell can trigger again. 5 seconds seems enough.
...

**Comment by Dennishacq** [comment]
@edtst 
Thank you for reporting your issue.
I'm working on a debouncer, which should be added in v1.1.12. this should fix your issue.

**Comment by Dennishacq** [comment]
V1.1.12 is online!
Please let me know how It works

**Comment by edtst** [comment]
KaKu is still at 1.1.2 in the app store

**Comment by MdeRhoter** [comment]
Pretty sure that is the new one, it was at 1.1.1 before :)

**Comment by Dennishacq** [comment]
Oops my bad, 1.1.2 is the one

**Comment by edtst** [comment]
Tested and it works now, thnx

**Comment by freemann** [comment]
This is not fixed.

**Comment by Dennishacq** [comment]
See #589
