### ISSUE TITLE
No warning when deleting zone with devices / devices still listed in settings and flows, not in devices tab.

### ISSUE THREAD

**Issue by heretic1988** [athombv/homey#542]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you do**

Accidentely removed a zone with two zwave devices in it.

**What was the result?**

No devices listed in overview, but they are still listed in the zwave settings, and in the flows.
The flows still work as well.

**What did you expect as result?**

A warning that I was deleting a zone with devices in it.
Abilty to import the devices in the overview again.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by WeeJeWel** [comment]
Fixed in the update áfter 0.9.0

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
