### ISSUE TITLE
KAKU stopped working after 0.8.32

### ISSUE THREAD

**Issue by bierre** [athombv/homey#543]
**What is your Homey version (Settings → System)?**

0.8.32
**What did you try to achieve?**

- KAKU were working on 0.8.30 and after the update to 0.8.32 two days ago.
- Now no new device can't be added and no response on switching on and off
- KAKU app version 1.1.1

**What was the result?**

KAKU device not recognized when trying to pair
Already created devices not responding to on/off from Appliances screen

**What did you expect as result?**

KAKU works
**Any other remarks**

...

**Comment by dhanstede** [comment]
Hi, i've got also this problem. But after i disconnect the power plug for about 5 minutes and restart homey, kaku works and i can add new devices.

**Comment by kruimel0** [comment]
Strangely, for me the reverse is true; kaku didnt work at 0.8.30, but 0.8.32 fixed it.

**Comment by mruiter** [comment]
Had this to. reboot or power down did not help. uninstall and reinstall neither.

What did:
Deinstall kaku
reboot
reinstall kaku

Works again.

**Comment by bierre** [comment]
Thanks after a full power reset everythibg seems to be working.

**Comment by mruiter** [comment]
@bierre You can close this ticket then i guess or is it still a problem

**Comment by Dennishacq** [comment]
Hi guys,
Were you able to pair or control any other 433MHz devices when you were experiencing this problem?

**Comment by mruiter** [comment]
nope all was death at kaku city


Verzonden vanuit Outlook Mobile






On Fri, Apr 29, 2016 at 8:19 AM -0700, "Dennishacq" <notifications@github.com> wrote:












Hi guys,

Were you able to pair or control any other 433MHz devices when you were experiencing this problem?

**Comment by freemann** [comment]
433 MHz on 0.8.29 is still relatively stable. Maybe Athom could look at the code differences?

**Comment by mruiter** [comment]
after the deinstall and reinstall all is as stable as can bee again. so it looks like .32 is also stable after this little hickup


Verzonden vanuit Outlook Mobile






On Fri, Apr 29, 2016 at 9:10 AM -0700, "Marco" <notifications@github.com> wrote:












433 MHz on 0.8.29 is still relatively stable. Maybe Athom could look at the code differences?

**Comment by Dennishacq** [comment]
Good to hear that your issue has been solved.
Let me know if any new issues arise.

**Comment by BasPost** [comment]
I have a problem with KaKu. After 2-3 days KaKu or Somfy is not working anymore, it seems the 433MHz radio is stopped working. Within the settings, pressing reboot seems to solve it sometimes, sometime I need to unplug the power for a reboot.
This happens 3 times now last week.
I didn't uninstall and reinstall the KaKu app, because I'm afraid to re-add all my KaKu modules again.

**Comment by RoadXY** [comment]
Also on 0.8.32 and using Somfy without issues.
Don't use Kaku and also no Kaku app installed

**Comment by ReinierH** [comment]
Looks like we found and solved the issue. More testing needs to be done to ensure this fix solved the problem. I will keep you guys posted.

**Comment by kruimel0** [comment]
Nice Reinier! On a side note, kaku stopped working for me on 0.8.30, started working on the 0.8.32 update, and stopped working immediately after a reboot of Homey, still on the 0.8.32 firmware.
