### ISSUE TITLE
[0.8.32] Data polling on Z-wave device no longer working

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#545]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Upgrade 0.8.29 > 0.8.32

**What was the result?**

Polling of Greenwave powernode-6's is not working anymore... 
nothing changed to these devices... only data points during every reboot
<img width="1162" alt="schermafbeelding 2016-04-28 om 09 19 31" src="https://cloud.githubusercontent.com/assets/17163431/14903647/c86ee6ae-0da2-11e6-899c-f4075d7de036.png">

**What did you expect as result?**

Polling of Greenwave powernode-6 once every 300 seconds... never led to issues over weeks

**Any other remarks**
Log: 0E146DB463
...

**Comment by ocatie** [comment]
I see in the log that the polling still happens as you've set up. If you physically change the state of the device, is a datapoint made after ~10 minutes? It's important you don't open the device card in the meantime.

**Comment by TedTolboom** [comment]
@ocatie I don't understand your feedback / question in relation to the issue (most likely an issue at my side ;))

Let me try to clarify...

Before upgrading to 0.8.32, I set the polling on the main node to e.g. 300 and I received in Insights every 300 seconds a data point for the cumulative power consumed...

During and after the upgrade to 0.8.32, I made NO changes to the physical state (position) of the 3 power nodes... Nor to the polling interval / settings of them...

Now I do not see the data points updated on regular basis; only during Homey reboots... which can be considered regular, but not even close to the 300 sec polling interval... ;)

If the polling takes place (according to the log), but no data points are shown at insights.. Does this point towards an issue at Insights?

What do you mean with:
> If you physically change the state of the device, is a datapoint made after ~10 minutes?
> 

Disconnecting and reconnecting the entire powernode?

> It's important you don't open the device card in the meantime.
> 
This sounds strange to me... So if I would have the device card open (just at a random moment, which happens to be just at the same time the polling would take place), the datapoint would not be stored?

**Comment by ocatie** [comment]
I didn't mentioned Disconnecting and reconnecting the entire powernode.

I'd like to know if any state change will be logged by polling. The easiest is the onoff state. If you manually disable the 6 sockets by pressing the on/off button on the powerstrip I'd like to know if the change is detected by polling. Therefore don't open the device card because it will fetch the state before the polling can.

Turn the powerstrip on, open each device card to sync the state, turn the powerstrip off using the button on the powerstrip. Now it's important not to open the device cards. If you could send a log 10 minutes after you have switched the powerstrip off (again don't use the device cards in the meantime) and tell if a datapoint for the onoff capability has been made in the Insights.

**Comment by TedTolboom** [comment]
@ocatie No no datapoint has been made in Insights after switching ON the powernode (were switched off in our holiday absence)

Timing wise:
- Disconnected power of Homey at 16:30, reconnected again (due to freeze in during our holiday period)
- Switched on the powernode (Speelhoek) at 17:00
- First data point at 18:10

See data:
Wed May 04 2016 16:31:51 GMT+0200 (CEST),8.17
Wed May 04 2016 18:10:45 GMT+0200 (CEST),8.17
Wed May 04 2016 21:30:36 GMT+0200 (CEST),8.19
Wed May 04 2016 21:31:39 GMT+0200 (CEST),8.19

Same holds for the powernode (Vitrinekast)... switched on around 17:30... no datapoint made
Fri Apr 29 2016 12:28:32 GMT+0200 (CEST),1.15
Wed May 04 2016 16:31:38 GMT+0200 (CEST),1.15

LOG: 9FBE60BD5E

For comparison (same settings before 0.8.32):
Wed Apr 20 2016 18:42:51 GMT+0200 (CEST),0.7008
Wed Apr 20 2016 18:47:52 GMT+0200 (CEST),0.7016
Wed Apr 20 2016 18:52:51 GMT+0200 (CEST),0.7023
Wed Apr 20 2016 18:57:51 GMT+0200 (CEST),0.7031
Wed Apr 20 2016 19:02:51 GMT+0200 (CEST),0.7039
Wed Apr 20 2016 19:07:51 GMT+0200 (CEST),0.7046
Wed Apr 20 2016 19:12:52 GMT+0200 (CEST),0.7054
Wed Apr 20 2016 19:17:51 GMT+0200 (CEST),0.7062
Wed Apr 20 2016 19:22:51 GMT+0200 (CEST),0.7069
Wed Apr 20 2016 19:27:51 GMT+0200 (CEST),0.7077
Wed Apr 20 2016 19:32:51 GMT+0200 (CEST),0.7085
Wed Apr 20 2016 19:37:51 GMT+0200 (CEST),0.7092

Polling and datapoints every 5 minutes

**Comment by TedTolboom** [comment]
And before replying that the original request was to power-off the powernode...
Powered off the powernode at 21:43... and still not datapoint (after 10 minutes)..

Wed May 04 2016 21:30:36 GMT+0200 (CEST),8.19
Wed May 04 2016 21:31:39 GMT+0200 (CEST),8.19

LOG: 877DA82669
