### ISSUE TITLE
Error message stays on screen

### ISSUE THREAD

**Issue by freemann** [athombv/homey#546]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Clicking OK to get rid of Error message.

**Please include detailed steps how we can reproduce the issue**

Get into the error, let Homey stay for 4-5 hours and the click the OK button

**What was the result?**

Error message stays on the screen;
![screenshot - 29-4-2016 14_50_33](https://cloud.githubusercontent.com/assets/601053/14916456/1513d614-0e1a-11e6-806d-a89f27144554.png)
![screenshot - 29-4-2016 14_51_07](https://cloud.githubusercontent.com/assets/601053/14916543/814f169a-0e1a-11e6-9465-78047ef64af0.png)

**What did you expect as result?**

The error message to disappear.

**Any other remarks**

...

**Comment by RoadXY** [comment]
It might help Athom to have your log file.
Could you add the log number here?

**Comment by freemann** [comment]
[screenshot - 29-4-2016 15_50_37](https://cloud.githubusercontent.com/assets/601053/14918048/354a4154-0e22-11e6-9e5c-3d31a137e913.png)
