### ISSUE TITLE
[KaKu] Dimming the lights spread

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#547]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Creating a simple flow so I can dim the lights in 15 minutes from current state smoothly to off when the the sunrise is done
Also another simple flow to dim the light from off smoothly to 40% in 30 minutes when the sunset is started

**What was the result?**

Creating a long list with cards to dim the light every 30 seconds with 1 procent.
![schermafbeelding 2016-04-29 om 21 44 00](https://cloud.githubusercontent.com/assets/13370203/14928273/2868f266-0e57-11e6-8a69-fc089f6165e1.png)

**What did you expect as result?**

One card where is say to level in x minutes. The card should calculate how much seconds there are between each percentage and dim the light.

**Any other remarks**

I want to do this so I don't see a lux difference between the light outside, and my lights inside.
In the screenshot i'm triggering the flow with sunset, but I'm gonna use this with my twilightsensor.

**Comment by gkroone** [comment]
I cant really make out what is or is not working with this flow and cant really help you with it, but every 30 seconds 1 percent would probably not be the best or most efficient way to achieve this with kaku as i beleive the kaku dimmers internally only have like 16 dimming levels (the percentage gives you a false idea it would allow for 100 levels, which is not true)

**Comment by kerkenit** [comment]
I knew this limit on Domoticz, but it's working here. It's moving smoothly right now

**Comment by bvdbos** [comment]
Athom could create an extra card for this or someone could make a sepreate addon. 
start dimming level
end dimming level
dimming time

**Comment by bvdbos** [comment]
This is possible now with HUE but also with other dimmers using variables and dragging tags to the dimmer-action-card...

**Comment by kerkenit** [comment]
@bvdbos How ca I do this?
Can you send me a screenshot of an example flow(s)?
Don't hurry, it works for months. Right now u use 40 actions. A little mess, but:
> If it ain't broke, don't try to fix it

**Comment by bvdbos** [comment]
see bug #1122 with global tags...
But bug #934 is still present so I don't guarantee everything will work out correctly...

**Comment by bvdbos** [comment]
As #934 and @1122 are fixed this should work now?

**Comment by bvdbos** [comment]
closeme ?

**Comment by WeeJeWel** [comment]
A duration option is actually still on the roadmap!

**Comment by bvdbos** [comment]
meanwhile this works. Set the time-spread in the "increment number value" delay:
![2017-09-01 07_23_04- 249 flow - homey](https://user-images.githubusercontent.com/1064079/29956623-87fbc506-8ee8-11e7-84a1-f2e990c826dd.png)
I turned the light off after 20 steps of 0.05:
![2017-09-01 07_33_31- 249 flow - homey](https://user-images.githubusercontent.com/1064079/29956641-981655e6-8ee8-11e7-9a04-614365ab50d6.png)

**Comment by WeeJeWel** [comment]
As of v1.5.1 a 'dim relative' card is available for lights.

![](https://files.slack.com/files-pri/T02GJ8RC3-F6W5YUA07/screen_shot_2017-08-29_at_11.28.35.png)

**Comment by jeroenvollenbrock** [comment]
As of 1.5.2 a 'dim over time card is available for lights'. Please note that the card requires app support.

**Comment by jghaanstra** [comment]
@jeroenvollenbrock is there any documentation on how to add this? I use the light class for the Yeelights but this card is not available by default.

**Comment by jeroenvollenbrock** [comment]
I've just noticed there is indeed no documentation on this subject. I've put a task for this on the backlog so it'll get added asap. For now you can look at the implementation in the Philips Hue app:
https://github.com/athombv/nl.philips.hue/blob/master/drivers/bulb/device.js#L66
https://github.com/athombv/nl.philips.hue/blob/master/app.json#L40

**Comment by canedje** [comment]
I do have the same problem. Slowing down Homey huge by using multiple timers in one flow.
I now did build a solution with the standard Logic tool (using less timers) and it is working more or less. Slowing down Homey is less then using all the timers, but still more slow as not running this flow.
For the Fibaro RGBW switch (SKU: FIB_FGRGBWM-441) I also like to opt for an extra card with dim start and end value and time to reach that.
Other devices do have this card already!
