### ISSUE TITLE
Android App Hue Card Hue and Sat not selectable

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#55]
On Android Phone I cannot select Hue and Saturnion of Philips Hue bulbs. It flips to the start (Brightness) or end (Temperature) of the list when swiping on the card.
On Android Tablet Hue Cards are not loaded fully. Only light bulb icon and white background is shown. Restart of app has no result.

**Comment by elgenioNL** [comment]
Same issue on the webinterface with scrolling on a windows tablet and laptop with touchpad.

**Comment by goldenice** [comment]
@WeeJeWel This seems to be an issue in the windows tablet / laptop browser as well...

**Comment by WeeJeWel** [comment]
@elgenioNL Which Windows version and browser are you using?

**Comment by elgenioNL** [comment]
Windows 10, Chrome Versie 48.0.2564.109 m

**Comment by WeeJeWel** [comment]
Fixed in 0.8.34
