### ISSUE TITLE
devices_data should be realtime accessible in a driver not only in driver init at start

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#551]
**What is your Homey version (Settings → System)?**

0.8.32

**Any other remarks**

homey updates the devices_data when a device is added or deleted. it would be nice to use this devices_data as a device enumerator in an app. i think this would prevent every app coder to code its own realtime device enumerator and save memory and disk space.

**Comment by WeeJeWel** [comment]
Well.. you can't get the device_data dynamically because you need the device_data... ;)

Please just keep track of the object in your driver. It's really intended behavior.
