### ISSUE TITLE
Fibaro binary sensor will not finish inclusion

### ISSUE THREAD

**Issue by JacobJAD** [athombv/homey#552]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Include Fibaro binary sensor

Same as in the closed issue #202 during the inclusion page 2/3 the inclusion freezes

![image](https://cloud.githubusercontent.com/assets/18900005/14941598/60f07b40-0fa1-11e6-90ee-67c4f4e65715.png)

After a 10 min wait Exit via the x and try again

![image](https://cloud.githubusercontent.com/assets/18900005/14941600/6bf8a526-0fa1-11e6-83aa-bd332212db4d.png)

Exit via the [ok] and go to System/ZWave and restart Zwave chip

![image](https://cloud.githubusercontent.com/assets/18900005/14941601/719ff5b0-0fa1-11e6-81b4-02a2d4dbb6c8.png)

**What did you expect as result?**

An included Fibaro Binary sensor

**Any other remarks**

After a reboot of Homey a new pair session could be started.
No other effects observed

**Comment by ocatie** [comment]
Could you reproduce the error and then send us a system log by pressing the Send Log button in Settings -> System. With the code that will popup I can acces the log.

**Comment by JacobJAD** [comment]
Done, 
Started inclusion, same response, wait appr. 10 min and stopped the process manually.
Log nr: 316FC73F26

**Comment by ocatie** [comment]
I suspect an invalid frame is returned. I've added code that prevents the crash. Could you try again on 0.8.33?

**Comment by JacobJAD** [comment]
Waiting for version .35 but in .34 the same issue

**Comment by JacobJAD** [comment]
Tried again in version 0.8.35. Same result as described
Log: 9FB1A9936D

**Comment by JacobJAD** [comment]
An other inclusion try in 0.8.38
The inclusion process will not pass the message, closed and send log.
![fibaro binary sensor](https://cloud.githubusercontent.com/assets/18900005/15990935/ea5b0ffe-30a2-11e6-8e99-afbada01bbec.jpg)

Log 6B3C6F87DF
