### ISSUE TITLE
Impossible to set a negative parameter in z-wave device settings

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#553]
**What is your Homey version (Settings → System)?**
0.8.32

**What did you try to achieve?**
I tried to correct a difference in the reported temperature from a Aeotec MultiSensor 6. On USB power this sensor reports a temperature that is to high: https://forum.athom.com/discussion/comment/19873/#Comment_19873

*Please include detailed steps how we can reproduce the issue*
Add 201,2,-42 to the data field in the sensors settings.

According to the sensors engineering sheet I have to enter the following parameter: 201,2,-42
(http://www.vesternet.com/downloads/dl/file/id/764/product/1545/z_wave_aeon_labs_multisensor_6_gen5.pdf page 20)

**What was the result?**
Not possible to save the settings, the button is grayed out and the input field border is red
![no negative value](https://cloud.githubusercontent.com/assets/16610696/14943419/3f22debc-0fd9-11e6-8b5c-df606c09c826.png)

**What did you expect as result?**
To be able to save the setting and correct the wrong temperature

**Any other remarks**

**Comment by ocatie** [comment]
You have to enter the signed integer value. Like the example in the manual:  -2.1℃ (0xFFEB)

**Comment by daneedk** [comment]
Ok, but what actual value would I put in the data field then if I want to lower by 4.2 degrees?

**Comment by ocatie** [comment]
You take the maximum value (depends on the size, 1, 2 or 4 bytes) and subtract your calibration value.

**Comment by daneedk** [comment]
Ok thanks, I think I get it now, it's 1 byte so it would be 255-42=213
