### ISSUE TITLE
KAKU Doorbell seems to trigger about 20 times

### ISSUE THREAD

**Issue by bierre** [athombv/homey#554]
**What is your Homey version (Settings → System)?**

0.8.32
**What did you try to achieve?**
- I succesfully linked my KAKU doorbell sensor
- Also included it with Homewizard for testing purposes
- Added the doorbell to a flow which is triggered by the bell and then sends notifications to slack and pushover.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
- If someone presses the doorbell, I see around 20 notiifcations in Slack and Pushover
- Homewizard only shows 1 ring.

**What did you expect as result?**

- 1 notification

**Any other remarks**

...

**Comment by Dennishacq** [comment]
See #589
