### ISSUE TITLE
Lifx app issues

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#556]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.29

**What did you try to achieve?**

I made a flow that would dim and change the color of my lifx bulb (in the future all of m) 
Since voice triggers are still very buggy I did test the flow. 
I added the same bulb twice, 1 to dim and 2 for changing color. seems you can't set both.
Color set to a greyish blue and the brightness to 12%
The result was:
100% flash of light and the color changed to red.
Then it dim level of 12%
If I keep re-trigger (testing) the flow, the result changed to a different brightens and some times even a different color.

**What did you expect as result?**

The light would fade into a light greyish blue with a dim level of 12%

**Any other remarks**

Voice commend "Time to dim the lights" just tells me what time it is. Ill make a separate topic for voice command problems. At the moment its a mess.

**Comment by craftedpixelz** [comment]
FYI: I believe voice commands for LIFX are natively supported. I initially set up flows to turn the lights on/off but read on the forums that there is a list of in-built commands. I removed my lighting flows and can still use lights on/off, dim and change color voice commands.

Although, like you, I struggle with voice control right now. There is another bug open regarding it and multiple posts on the forums. Hopefully it'll improve over time.

For now you can test these commands by typing them into the speech manager interface, to see what light commands are natively supported.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by RobinBol** [comment]
This issue is most likely fixed in LIFX app version 1.1.1.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen if the problem persists.
