### ISSUE TITLE
Hue Card pops-under Thermosmart Card

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#56]
I first installed the Thermosmart app, after that I added the Hue app. 
The Hue Card now pops under the Thermosmart Card.

*Red Flag Alert*
I suspect it has to do with -not- saving the device order per room. When I change the order of devices in a room, after reloading ../manager/zones/ the old order is shown.

**Comment by WeeJeWel** [comment]
Yes, it's a known issue that devices re-ordering is not being saved. Thanks!

**Comment by irritanterik** [comment]
![2016-02-10 20 16 57](https://cloud.githubusercontent.com/assets/15232724/12959312/359046b0-d036-11e5-83d1-24ff110ec86f.jpg)

**Comment by WeeJeWel** [comment]
Auch! Thanks, will fix that.

**Comment by Fire69** [comment]
Don't know if this needs a new issue but I have a cosmetic problem with the Hues also.

![2016-02-10](https://cloud.githubusercontent.com/assets/1757287/12961043/c2cd9bb0-d03e-11e5-9722-73b2ca8a2394.png)

I hope it's visible like this?

**Comment by WeeJeWel** [comment]
@Fire69 that should be fixed in 0.8.17.

@irritanterik Do you have a path how I can reproduce the card popping under?

**Comment by Fire69** [comment]
@WeeJeWel, i see the way of creating the flow has changed, now you have to select a separate card per device. Is that the fix you meant?

**Comment by WeeJeWel** [comment]
@Fire69 yep

**Comment by irritanterik** [comment]
Video of popunders

[video.zip](https://github.com/athombv/homey/files/128021/video.zip)

**Comment by WeeJeWel** [comment]
I see, thanks! Will fix it :)  

---

Emile Nijssen

M: emilenijssen@gmail.com (mailto:emilenijssen@gmail.com)
T: 06 409 23 136W: http://www.emilenijssen.nl

**Comment by Fire69** [comment]
Just noticed another popunder problem.  Not specific to Hues.
Don't know if I have to make a new issue for this?

![image](https://cloud.githubusercontent.com/assets/1757287/13649193/b9141464-e63c-11e5-9650-073e28e91891.png)

**Comment by irritanterik** [comment]
Make a new issue, the original is solved and closed (and confirmed).
