### ISSUE TITLE
Fibaro Motion Sensor not included properly

### ISSUE THREAD

**Issue by HuubNabben** [athombv/homey#560]
**What is your Homey version (Settings → System)?**
MacBook Pro
IOS: OS X 10.11.4
Kernel version: Darwin 15.4.0
Homey IOS: 0.8.29
Chrome version: 50.0.2661.94 (64-bit)

**What did you try to achieve?**
I want to include the fibaro Motion Sensor (the little ball z-wave plus version)

*Please include detailed steps how we can reproduce the issue*
I started by clicking on the + icon to add a new device and selected Z-wave.
Next the question is shown to put the device in learning mode.
Next the device is detected and interviewed.
Than a message is shown that the type of the device is unknown and it will be added as a standard Z-wave product. This results in he inclusion of a smart-socket.

**What was the result?**
The inclusion od a smart socket.

**What did you expect as result?**
The inclusion of a motion detector

**Any other remarks**
Not applicable

**Comment by ocatie** [comment]
This issue is fixed in 0.8.32. Please reopen if it persists.

**Comment by HuubNabben** [comment]
Thanks for your help.
Do you have any idea when this version is being released?

**Comment by ocatie** [comment]
It is in experimental now
