### ISSUE TITLE
Dismissing pop-ups

### ISSUE THREAD

**Issue by Joolee** [athombv/homey#561]
**What is your Homey version (Settings → System)?**
0.8.32

**What did you try to achieve?**
Dismiss any of the following pop-ups:
- Flow selection dialog
- Zone icon selection dialog on devices page

**What was the result?**
Pop-ups stay open

**What did you expect as result?**
Clicking outside of a menu popup should always close that pop-up
The icon popup should just keep the already selected icon
The flows pop-up should keep the currently selected flow in the editor or, when no flow is selected, add a new flow with default title (different behaviour that the "create new flow" option!) that will be discarded when nothing is done to it.

**Any other remarks**
The flow selection menu/pop-up only responds to a mouseout when the flow has been loaded. Click on a flow and move your mouse out of the pop-up before the flow is loaded, the pop-up will remain.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35!
