### ISSUE TITLE
Adding Fibaro Dimmers to homey makes the physical momentary switch unusable

### ISSUE THREAD

**Issue by jpernot** [athombv/homey#564]
Homey Firmware Version: 0.8.29

Added multiple Fibaro Dimmer modules (FIB_FGD-211) which are behind momentary switches. Afterwards the physical switches do not work anymore. Controlling them through the Homey web interface works fine but. Obviously I still want to be able to use the physical switches for controlling (switching/dimming) the lights (not just the homey interface or flows).

**Comment by Robinyoh** [comment]
did you use a puls switch instead of a normal switch?

http://www.elektrototaalmarkt.nl/gira/basiselement/impulsdrukker-015100-4145557/015100/?gclid=Cj0KEQjw09C5BRDy972s6q2y4egBEiQA5_guv6iiGHbxVnDUawpX9o_E3URk9nepmZC98PHj0IOop-kaAqxp8P8HAQ

**Comment by jpernot** [comment]
Correct, I use the following switches from Jung: https://www.elektrobode.nl/products/jung-impulsdrukker-531eu

Sent from my mobile device

**Comment by irritanterik** [comment]
@jpernot Have you (re)set parameter 14 to value 0 ? ([source](http://www.fibaro.com/manuals/en/FGD-211/FGD-211-EN-A-v1.03.pdf))

**Comment by jpernot** [comment]
Yes, I've (re)set parameter 14 to 0 (see attached screenshot) even though this is the default parameter. I noticed that sometimes the physical switches work (but then after a few minutes they are not responsive anymore). Controlling the light through Homey works fine.

The switches work perfect when I remove them from the Homey z-wave network so the switches are not broken.

![screenshot](https://cloud.githubusercontent.com/assets/19155794/15300522/690e8128-1ba9-11e6-8767-9e2a6d56e780.png)

**Comment by jpernot** [comment]
Maybe this helps... 

I figured out that the switches work (while be connected to Homey) after first pressing the switch for ca 3 seconds. Afterwards the switch will work again (switching and dimming). However after very short time (10's of seconds) the switch does not work anymore. You need to press if again for ca 3 seconds first before it responds....

For now I leave the z-wave dimmers disconnected from Homey since without being able to use the switches the connection to Homey is pointless.

**Comment by jpernot** [comment]
Any update with regards to this issue? When do you expect this to be solved? thanks!

**Comment by jpernot** [comment]
Unfortunately the problem is not solved with version 0.9.1..
After adding the Fibaro Dimmer modules (FIB_FGD-211) the system adds an unknown Z-Wave device (See screenshot) and the earlier reported problem remains. Homey does not recognize this dimmer. 

![image](https://cloud.githubusercontent.com/assets/19155794/17275765/575ff7d6-5713-11e6-9b52-d75145b3252f.png)

**Comment by swttt** [comment]
The dimmer v1 is merged to the fibaro app on github. Appstore app isn't updated yet, but it works as it should.

Couldn't find a way to add scene activation, and only a few settings(parameters) are added.

**Comment by jpernot** [comment]
Ah ok, my mistake. I forgot to install the Fibaro app… I just installed the app but as you already mentioned the dimmer device is not yet available. I will wait for the new version of the Fibaro app on the appstore.

**Comment by irritanterik** [comment]
@jpernot Just a warning, your e-mail address visible is in your response message.

**Comment by jpernot** [comment]
Issue is solved with the z-wave implementation in combination with new fibaro app! thanks!
