### ISSUE TITLE
Homey.manager( 'settings' )on('set') fires on every setting

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#566]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
[https://developers.athom.com/api/](url)

to code next function in app js described on    Homey.manager( 'settings' )
...// Fired when a setting has been changed]
.on( 'set', function( 
string name   // name of the setting 
) )

when setting something changed invoke this function,
but it was invoked an all changed setting and making something a string didn't work at all

Homey.manager('settings').on('set', function (something) {}

this works 

Homey.manager('settings').on('set', function () {}

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...// Fired when a setting has been changed
.on( 'set', function( 
string name   // name of the setting 
) )

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by RoadXY** [comment]
It also fires on all settings/vars, regardless of what changed

**Comment by irritanterik** [comment]
@nattlip @RoadXY 
I have code like this in my app.js or driver.js. It's fired when expected (settings created or changed): What's the bug according to you?

```
    Homey.manager('settings').on('set', function (setting) {
      if (setting === 'gpsaccount') {
        initiateTracking()
      }
      if (setting === 'geofences') {
        geofences = Homey.manager('settings').get('geofences')
        checkGeofences()
      }
    })
```

**Comment by nattlip** [comment]
i made of the description on https://developers.athom.com/api/ that you could invoke it like this;

Homey.manager('settings').on('set', function ('gpsaccount) {
    do something
    })

so one trigger per setting, like saving or creating a setting. but your implementation is correct.
