### ISSUE TITLE
Flow editor: Start one flow from another

### ISSUE THREAD

**Issue by Weezul** [athombv/homey#568]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
Trigger one flow from another

_Please include detailed steps how we can reproduce the issue_
Create a flow that will turn all lights off. Have this flow triggered both when I go to bed, or when I leave the house.

**What was the result?**
Not possible to create flow without a trigger, and not possible to start one flow from another

**What did you expect as result?**
That there would be a way to either create a flow without a trigger, or that there would be a dummy "Triggered manually" card to use.

**Any other remarks**
A work around is to trigger a flow by changing a variable, but this is a messy solution. Should it be possible to create flows like this, it will replace the need to create "Scenes" any more, so the change to the current UI is limited

**Comment by bvdbos** [comment]
you get the same problem as with #444 . Using a variable or dummy device like in
https://forum.athom.com/discussion/comment/20461/#Comment_20461

**Comment by bvdbos** [comment]
With 0.10.1 you can mimick something that is said with the "Emulate Speech" card:
https://athomcommunity.slack.com/files/weejewel/F2GG5HU2C/screen_shot_2016-09-27_at_16.45.55.png

**Comment by bvdbos** [comment]
This is fixed now...
