### ISSUE TITLE
Very strange Zwave behaviour

### ISSUE THREAD

**Issue by freemann** [athombv/homey#569]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Get 4 Zwave device work

**Please include detailed steps how we can reproduce the issue**

Add 4 zwave devices;
1. AEOTEC Smartplug (AEO_SES2_EU)
2. Fibaro 2x1.5kW relay V2
3. Greenwave Single socket 
4. Fibaro wallplug

**What was the result?**

After some time this was the result;
![screenshot - 4-5-2016 08_49_45](https://cloud.githubusercontent.com/assets/601053/15006980/315056cc-11d5-11e6-91d5-7e85d26f48e9.png)

Here's a system log;
2F858549D8

**What did you expect as result?**

All working like a charm.

**Any other remarks**
See;
https://forum.athom.com/discussion/1322/is-the-range-of-433mhz-better-than-z-wave

**Comment by bvdbos** [comment]
This is a valid issue :+1: Do they fail in a particular order?
