### ISSUE TITLE
Various minor layout issues with initial config on Android Chrome Browser

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#57]
See red lines in attachments
![2016-02-10 18 44 03](https://cloud.githubusercontent.com/assets/15232724/12959384/78ab07f0-d036-11e5-83df-d50c12c71ef2.png)
![2016-02-10 18 44 26](https://cloud.githubusercontent.com/assets/15232724/12959387/7be20888-d036-11e5-8ea2-8e7bdcbfaa75.png)
![2016-02-10 18 46 31](https://cloud.githubusercontent.com/assets/15232724/12959401/855f39d0-d036-11e5-9d96-bda313389101.png)
![2016-02-10 18 47 03](https://cloud.githubusercontent.com/assets/15232724/12959403/88573494-d036-11e5-91e9-7cd7d857e22b.png)
![2016-02-10 18 47 36](https://cloud.githubusercontent.com/assets/15232724/12959409/8c7d7dda-d036-11e5-8d49-4b37d26d31de.png)

**Comment by Fire69** [comment]
Was about to open an issue about this too.
Had the same cosmetic problems.

Also, in the end screen, when I clicked the 'My Athom' link, I got a popup saying the setup wasn't finished yet. I cancelled and tried again, same message.  Waited 10 seconds, tried again and it worked.

**Comment by freemann** [comment]
Maybe its an idea to close this one?

**Comment by irritanterik** [comment]
@freemann Why? Is it fixed? Or decided it will never be?

**Comment by freemann** [comment]
5 month say enough?

**Comment by WeeJeWel** [comment]
We'll still fix it eventually :) It's just so minor that it doesn't get priority

**Comment by WeeJeWel** [comment]
Fixed in the new setup.
