### ISSUE TITLE
Milight RGBW group not functioning properly after adding

### ISSUE THREAD

**Issue by Nreall** [athombv/homey#570]
**What is your Homey version (Settings → System)?**

0.8.32
Milight App version: 1.1.2

**What did you try to achieve?**
Add and control Milight RGBW Light group

*Please include detailed steps how we can reproduce the issue*

Add a RGBW group and then try to edit the Color in the devices tab.

**What was the result?**

Not able to change color/brightness, can i how ever seem to change the Temperature and turn the light on/off.

**What did you expect as result?**

Ability to change the color and brightness.

---
Ive added a second group which works like it should.

Tryed removing and adding the light several times, no change.
Tryed rebooting, no change.
Tryed reinstalling the app, no change.

Error light:
![image](https://cloud.githubusercontent.com/assets/18572509/15008415/6e2390a4-11e0-11e6-91ac-3d038199b5d8.png)

Correct working light:
![image](https://cloud.githubusercontent.com/assets/18572509/15008438/93114834-11e0-11e6-83f3-b016c8423db6.png)

Thanks for your help in advance.

**Comment by Nreall** [comment]
Just in case, i send the log: 8F9B5C6E78

**Comment by RobinBol** [comment]
Thanks for reporting, fixed in 1.1.3.
