### ISSUE TITLE
[Insights] Also save date/day/period selection in template

### ISSUE THREAD

**Issue by freemann** [athombv/homey#571]
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Saving the selected date/day/period within the insight template

**Please include detailed steps how we can reproduce the issue**

Create a device selection, click the date range picker, select "today" then save the template.

**What was the result?**

After saving and reloading/selecting the template again, insights shows the default X days few.

**What did you expect as result?**

After selectiing the template i expected to see the device graphs with the saved date range.

**Any other remarks**

...

**Comment by bvdbos** [comment]
valid issue, please re-open :+1:
