### ISSUE TITLE
Flow editor: checkbox isn't unchecked in UI after disabling flow

### ISSUE THREAD

**Issue by ThaYoung1** [athombv/homey#572]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Disable a flow from within another flow by using the 'Test' button and representing the flow state in the checkbox left of the (disabled) flow. 

![image](https://cloud.githubusercontent.com/assets/5597548/15013371/85b7f9f2-11ff-11e6-80fd-b8e43838638f.png)

**What was the result?**

First part (disable a flow from within another flow) works. After doing so by using the 'Test'-button, the checkbox left of the flow isn't unchecked. I need to do a refresh / full server round trip to get the box unchecked. 

Same behaviour counts for enabling a flow from within another...

**What did you expect as result?**

An unchecked checkbox, without me doing a refresh

**Any other remarks**

Nope

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35
