### ISSUE TITLE
Homey freezes with orange ring 

### ISSUE THREAD

**Issue by posthok** [athombv/homey#573]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
Running Homey longer than 24 hours

*Please include detailed steps how we can reproduce the issue*
once in 24 hours Homey freezes and shows orange led ring

**What was the result?**
Homey not reachable. Had to pull the plug

...

**What did you expect as result?**
Stable 8.32
...

**Any other remarks**
I'm happy with 8.32 everything works great. But this is the third time it get's stuck.

...

**Comment by WeeJeWel** [comment]
Which apps do you have installed?

**Comment by posthok** [comment]
PLex - Synology Surveillance station - Kaku - Pushover - NOS - Better logic -  Action and google chromecast.
I turned off the microphone to see if that makes any difference.
yesterday afternoon for the last restartet and is still running. I did this because I saw that the ledring was regular yellow, then white, while rarely having a hit in speech-input.

**Comment by WeeJeWel** [comment]
Try without Better Logic, so far that's the only app I've seen correlate with crashes.

**Comment by bvdbos** [comment]
I don't think that's the issue. Desciption looks like the known issue with the voice-trigger...

**Comment by posthok** [comment]
I'll try it anyway. Nothing to lose. First i'll wait to see if the microphone makes any difference.

**Comment by posthok** [comment]
Ok this morning i've got a froze homey, this time with static rainbow led.
Next step turn the microphone on and uninstall Better Logic.

**Comment by posthok** [comment]
Just went away for a couple of hours. When i came home, Homey frozen again with orange led ring.

**Comment by posthok** [comment]
This morning again a frozen orange led ring. I don't know what else to do.

**Comment by posthok** [comment]
deleted all flows with sunset. it's running now for 2 day

**Comment by posthok** [comment]
Still no freezes anymore.

**Comment by posthok** [comment]
updating to 8.34 no freezes anymore

**Comment by RoadXY** [comment]
You should close this issue then? :)

**Comment by posthok** [comment]
I can't WeetJeWel has the rights to do that.

**Comment by WeeJeWel** [comment]
Seriously? I should change that :p

**Comment by Inversion-NL** [comment]
The person creating the issue can close them.
Standard setting for Github and I've seen people other than Athom team members closing their issues...

**Comment by posthok** [comment]
Yes I know. Thanx
