### ISSUE TITLE
LIFX colour showly flashes new colour when requested via voice

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#574]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

added a LIFX lamp to my living room, colour changing via the app/web interface works well
colour changing via voice was not succeeding

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

when I ask homey to change the colour to red, it flashes instantly shortly red and them back to it's original colour again
...

**What did you expect as result?**

homey stays on the colour I requested
...

**Any other remarks**

...

**Comment by RobinBol** [comment]
Thanks for reporting, is fixed is 1.1.0.
