### ISSUE TITLE
Full heap will give a stack error

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#576]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Ordering all my flows by opening the flow and save them without any change. Because that is aved is moved to the bottom, i can order the flows that way.

**What was the result?**

After a lot of flows it's getting slow. A couple of edits more i got the messes `true`. When i look in the console I got a lot of Maximum call stack size exceeded. And homey's js Heap is using 20 mb.
After al those edit's the homey is frozen. The ledring is not changing anymore, and i have to unplug it.
![schermafbeelding 2016-05-05 om 21 15 42](https://cloud.githubusercontent.com/assets/13370203/15054494/138868e4-1308-11e6-941f-38fd28bf8270.png)
![schermafbeelding 2016-05-05 om 21 20 38](https://cloud.githubusercontent.com/assets/13370203/15054493/1385be3c-1308-11e6-90dd-9cec8a31ffbf.png)

**What did you expect as result?**

Be able to edit a lot of flows quickly after each other

**Any other remarks**

Log code E097287ED4

**Comment by WeeJeWel** [comment]
Please report back when 0.8.35 is released if this still happens.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by kerkenit** [comment]
Not anymore, because the upper issue is fixed
