### ISSUE TITLE
Elro Sockets stop working after some time because of KAKU conflict?

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#577]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Using 2 Elro sockets with the Elro app.

First I include the 2 sockets using my remote. One is channel A, One is channel D. 
I include these sockets in a few flows wich trigger on voice.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

They first worked for a longer period. But when I also added the KAKU doorbell ACDB-7000C the Elro stops working after sometime. The KAKu doorbell keeps working, so not all 433mhz communication stops.

**What did you expect as result?**

The Elro sockets keep working even when there are other 433 mhz devices.

**Any other remarks**

When I remove the Kaku app and I reinstall the Elro app the sockets start working again. When I only reinstall the Elro app they won't work. 

Seems to be a problem involving two 433mhz apps.

**Comment by RamSom8** [comment]
I have the same issues however i don't use any Elro devices only KaKu. Seems like there is no actual 433mhz communication going outbound. I flip the switch in homey but nothing happens.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
