### ISSUE TITLE
Elro sockets can't be set to another categorie. Fi. Light.

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#578]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

I wanted to set my Elro socket to categorie light (bulb) in stead of socket.

**What was the result?**

I couldn't change the categorie of the device. It stays a socket.

**What did you expect as result?**

Changing the socket to a light (bulb) categorie so they would trigger on the standard lights on/off commands.

**Any other remarks**

Keep up the good work!

**Comment by Dennishacq** [comment]
@2benl 
Thank you for submitting this issue,
It will be fixed in the next Elro Update :)

**Comment by 2benl** [comment]
You're welcome off course. Is there a estimate on the release?

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by 2benl** [comment]
This is fixed. Thnx.
