### ISSUE TITLE
No rounding of measurement results

### ISSUE THREAD

**Issue by JacobJAD** [athombv/homey#579]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
Request the temperature via voice

**What was the result?**
e.g. The temperature is 22.9999999999991 degC

**What did you expect as result?**
A result with maximal 2 digits

**Any other remarks**

...

**Comment by Dijker** [comment]
Same as #407 And #440 ¿

**Comment by JacobJAD** [comment]
Yes you are right. Couldn't find it. Ill close the issue
