### ISSUE TITLE
Homey.manager('flow').on not called when no arguments

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#581]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Catch a device trigger.
`Homey.manager('flow').triggerDevice('status', ...`
should result in an event for
`Homey.manager('flow').on('status', ...`

This only happens when the device json has arguments (next to name/type: device).

**What was the result?**

`Homey.manager('flow').on('status', ...` is never called. According to the docs it should be.

> // this is fired when a flow with this trigger has been found

**What did you expect as result?**

`Homey.manager('flow').on('status', ...` would always get triggered.

**Any other remarks**

Adding arguments to the app.json device does cause it to be called.

**Comment by WeeJeWel** [comment]
This is actually intended behavior, because the event is only fired to verify if the arguments are correct. If you don't have any arguments, they are, well correct :-)

I'll update the docs accordingly.

**Comment by nlrb** [comment]
Yup, makes sense. But good to make it clear in the docs indeed. Otherwise you can spend a long time pulling your hair out trying to figure out why it doesn't fire (and get bald)...
