### ISSUE TITLE
Over night time period conditions are not working

### ISSUE THREAD

**Issue by zperx** [athombv/homey#582]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

To enable an action only in a given time period.

**What was the result?**

Over night time periods are not working. 
![untitled-1](https://cloud.githubusercontent.com/assets/18647800/15130818/1da1f5a0-1643-11e6-857b-485ed8bc5eb0.png)

**What did you expect as result?**

Working condition.

**Any other remarks**

I am aware that there is a workaround if I create two flows but it is already hard manage the large number of flows.

**Comment by zperx** [comment]
The 0.10.9 firmware has fixed it with the new flow card: Time between

**Comment by zperx** [comment]
No it haven`t fixed this issue. The flow is active till midnight.

**Comment by WeeJeWel** [comment]
Could you please elaborate what you're trying to achieve and post a screenshot of your new flow?

**Comment by jjtbsomhorst** [comment]
I think that its clear. If its night enable the motion sensor until the next morning. ?

**Comment by Dijker** [comment]
I tink it is clear wat you want but Emile want to verify that you two speak about doing it the same way....
I guess he is happy with the new Time Between card and tested everything...

I have to confirm it is not working at least the way I expect. 
it was around 15u45 I tested, and I expect the Test button verifies the condition correct. 
(So i didn't test for real, only in the editor with the Test button)

I guess it is now between 0u01 and 16u00 so verified it:
![image](https://cloud.githubusercontent.com/assets/12412734/20030943/cf8eb0b4-a36f-11e6-9ab9-3d570045a319.png)
Correct!
Then it must be also between 23u58 and 16u00 
![image](https://cloud.githubusercontent.com/assets/12412734/20030961/35ac7336-a370-11e6-93ba-39b7b0f31051.png)

And that test failed....

**Comment by zperx** [comment]
This works only till midnight after that the flow is not triggered:
![untitled-3](https://cloud.githubusercontent.com/assets/18647800/20177710/053f7da4-a746-11e6-9b9c-163354fd625f.jpg)

As a workaround I use this:
![untitled-4](https://cloud.githubusercontent.com/assets/18647800/20177716/0e2315b6-a746-11e6-9500-761ca1da6936.jpg)

**Comment by WeeJeWel** [comment]
Fixed!
