### ISSUE TITLE
Heater virtual device is not working

### ISSUE THREAD

**Issue by zperx** [athombv/homey#584]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Turn on and off a heater virtual device plugged into a Lightwaverf socket.

**What was the result?**

It is not possible to turn it on off. Even on the devices pages the little fa slider button is missing.

**What did you expect as result?**

Working virtual devices.

**Any other remarks**

Others told that the fan virtual device is not working either.

**Comment by WeeJeWel** [comment]
This is already fixed in 0.8.34 :)
