### ISSUE TITLE
Virtual device icon

### ISSUE THREAD

**Issue by zperx** [athombv/homey#585]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

The same what I could achieve with the 0.8.30 firmware. When I add a socket (LightwaveRF) than use the icon that belongs to that device.

**What was the result?**

When not selecting any specific virtual device but going with the default generic device icon than device gets a generic device icon.

**What did you expect as result?**

To get the icon that belongs to that device instead of the generic icon. The generic icon is Schuko EU socket, here in UK we have UK socket so would prefer to see the icon set in app. Also this would help to distinguish devices easily, visually. 

**Any other remarks**

To be fair choosing virtual devices were not possible with 0.8.30 (at least in my case).

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35. (I love these oneliner fixes)

**Comment by zperx** [comment]
It has been fixed. Thank you.
