### ISSUE TITLE
Wrong text in action app v1.0.15

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#587]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Wrong title text is displayed in the Action app 1.0.15 when trying to add the promax devices (minor issue).

![schermafbeelding 2016-05-10 om 18 07 50](https://cloud.githubusercontent.com/assets/17526110/15153689/7ae509d6-16da-11e6-9a76-2a2e4a82001a.png)

**Comment by freemann** [comment]
App issue?

if yes, then (re)create issue in this Repo:
https://github.com/athombv/nl.action

**Comment by Dennishacq** [comment]
Thank You for submitting this issue.
This is fixed in the update that should come out next week.

**Comment by uNiiek** [comment]
Is the update coming today?

**Comment by uNiiek** [comment]
Fixed for me!
