### ISSUE TITLE
Fibaro smoke sensor V2 interview fails

### ISSUE THREAD

**Issue by Thorarin** [athombv/homey#588]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

I'm trying to add my Fibaro Smoke Sensor V2 (FIB-FGSD-002) to Homey. This is a battery operated Z-Wave+ device. The device firmware is supposedly v3.3 (the sticker on the box has a V3/3 on it)

*Please include detailed steps how we can reproduce the issue*

* Reset Z-Wave network on Homey to start clean
* Reboot Homey
* Add new Z-Wave device to enter learning mode
* Triple click button on smoke sensor

**What was the result?**

The learning mode dialog stays open and nothing appears to happen for a long time (waited 5+ minutes). If I close the dialog and go to the Z-Wave page, there will (usually) be one or more new devices. In my last attempts "2 - Unknown node" and "3 - New Z-Wave device (failed)".

Regardless of the devices Homey may or may not have added, the smoke sensor is now convinced it has joined a Z-Wave network. I have to reset the device completely to try again.

Under the devices page, there is a generic on-off device which I cannot do anything with. Clicking the sliders icon will show a progress animation forever while a HTTP 500 error is returned in the background:

```
Request:
GET /api/device/e531b8e4-d777-4b53-82f7-763a0b60d172/?_=1462905111894

Response (HTTP 500):
{"status":500,"result":"invalid_type_for_capability_onoff"}
```

The wrench icon shows a rather empty dialog.

Homey log code: 8A8ED5DA94 (taken some minutes after an attempt to add the device)

**What did you expect as result?**

A working Z-Wave device on Homey, with smoke alarm and heat sensor.

**Any other remarks**

I do not have any other Z-Wave controllers to verify the firmware version, but I assume the sticker is correct.

Screenshot of learning mode dialog staying open:
![image](https://cloud.githubusercontent.com/assets/1827726/15158461/6283a0c6-16f0-11e6-9f66-a82f4f857223.png)

Screenshot of dialog under wrench icon:
![image](https://cloud.githubusercontent.com/assets/1827726/15158545/b86bbe9c-16f0-11e6-8a4a-28e2c0385efe.png)

Screenshot of Z-Wave page after attempt to add device:
![image](https://cloud.githubusercontent.com/assets/1827726/15158581/e27f2282-16f0-11e6-90b4-9df2310059a1.png)

**Comment by ocatie** [comment]
Look like a security frame was dropped. Can you reproduce the problem or did it happen once?

**Comment by Thorarin** [comment]
It goes wrong consistently, also with 0.8.34. I haven't been able to get the device to work at all yet.

However, sometimes I end up with a single on-off device, instead of the two devices in my original report. Perhaps it depends on which frame gets dropped or something.

**Comment by ocatie** [comment]
Could you send a log after the pairing and paste the code here?

**Comment by Thorarin** [comment]
Other than the one in the original report? (8A8ED5DA94)
Here's one with 0.8.34: F99A86B240

I should note that for the first time ever, in my many attempts, I actually got some kind of response from Homey. "Interviewing device (1/1)". Some time after that "Interviewing failed. Adding as a basic device." The prompts are from memory, but I guess you get the point.

The end result is the same regardless.

**Comment by Thorarin** [comment]
Log made with 0.8.35: F9EB4E313C
Resulted in a single unknown node this time. Never got past "Device found. Processing..."
