### ISSUE TITLE
Homey repeats voice three times instead of one with KaKu doorbell.

### ISSUE THREAD

**Issue by kaandorp** [athombv/homey#589]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**
Homey should animate the LED ring and say "There is somebody at the door" when my KaKu doorbell has been pushed.

*Please include detailed steps how we can reproduce the issue*
Use the KaKu ACDB-7000BC
Create a flow:
*When*
    The doorbell is pressed
*Then*
    Animate: Pulse
    Say something: There is somebody at the door.

**What was the result?**
When the doorbell is pressed Homey says "There is somebody at the door" three times in a row instead of just one.

**What did you expect as result?**
I expect Homey to just say it once.

**Comment by kaandorp** [comment]
It might be related to [https://github.com/athombv/homey/issues/554](url)

**Comment by Dijker** [comment]
has to do with the debouncer #540 
Which version KAKU App do you use?

@Dennishacq  it look like this is not fully fixed... 
Have seen it in my doorbell also after removing the debouncer workaround in the flow.

**Comment by freemann** [comment]
not fixed. here the same issue with the doorbell.

**Comment by kaandorp** [comment]
I'm using version 1.1.2.

**Comment by cautje** [comment]
Hi,
How dit you connect this device?
Has it a codeweel inside?
For me it is impossible to connect.

THX!
Rutger

**Comment by Refl0w** [comment]
This problem also occurs on 0.8.34, the only difference is that it repeats about 10-20 times :) doesn't matter what i use in the "then" column, push message, mp3 sounds, everything gets repeated.

Tried to power off homey for 1 hr, restarting not working.

**Comment by freemann** [comment]
This is happening with all our "remotes"/senders;
- ACDB-7000BC sender
- and both our AYCT-102

Have a doorbell flow which start a MP3 and after a doorbell push the MP3 plays 3-5times and this also happens with the 102's.

**Comment by Refl0w** [comment]
Still not fixed in 8.35. Please fix this as my doorbell is now working with Homey all the time and not want to go back :(

**Comment by Dennishacq** [comment]
Hi guys,
I just released KlikAanKlikUit v1.1.3. 
I raised the debouncer timeout which should fix this problem.
Let me know if it works :)

**Comment by freemann** [comment]
Just installed the new app.
It works OK now, but the previous versions also worked OK for a few hours after a reboot and/or new version installed. So I will test some more for the upcoming hours/days.

Thanx for the update!

**Comment by freemann** [comment]
Everything is still working as expected; 1 push == 1 flow run :+1:

**Comment by Dijker** [comment]
Tested it this evening with a new flow with a Better Logic counter more than 60 times. 
For me this one is fixed!
I guess you can close this and  #540 and #554 
Thanks!

**Comment by Refl0w** [comment]
Works great now! Thanks for releasing this fix!
