### ISSUE TITLE
MiLight does not work (0.8.17)

### ISSUE THREAD

**Issue by coldshivery** [athombv/homey#59]
Adding a MiLight device will add it as a device. But it will not let me choose any options other then choosing groups 1 to 4. Pressing next after that just adds the MiLight as device. But it does not work.

Judging from the code its suposed to pair with a bridge for the MiLight but it does not seem to do this.

Asking homey to turn off the lights after that will not turn off the MiLights.

#### Reproduce:
* Add a MiLight device

**Comment by stealthblade** [comment]
Same issue here, seems like a step as "pairing with the bridge" is missing?

**Comment by freekwebdesign** [comment]
Thanks for reporting this issue.

The app is at the moment broadcasting to all bridges, but this does not work with certain routers.
A newer version of the app, which actively searches for bridges and connects to them will be published to the app store within a couple of days.
This should solve this problem.

As soon as it is available I will let you know.

**Comment by stealthblade** [comment]
Update 0.8.17 solved my problem, it works now when the bridge is connected.

**Comment by coldshivery** [comment]
I do not have a bridge but homey will still add all the MiLights as devices. This is not wanted behaviour correct?  Otherwise we can close the issue.

**Comment by freekwebdesign** [comment]
@stealthblade glad that 'Update 0.8.17' solved your problem.

@coldshivery because Homey can not detect if there is any bridge, it will act as if there is one. (because this is most of the time the case)
In the newer version of the app this issue is solved because Homey can identify separate bridges.

**Comment by coldshivery** [comment]
Ok thanks for the info. Then i beleive its solved for now :) (Y)

**Comment by freekwebdesign** [comment]
@coldshivery @stealthblade 
A new version of the MiLight app (1.1.0) is now available in the app store.
This should solve your problems.

**Comment by stealthblade** [comment]
Thanks @freekwebdesign for letting us know.
Now it scans indeed for a bridge but it keeps appending the same entries to the list every 5 seconds.
I attached a screenshot that shows all the entries. 

![schermafbeelding 2016-02-11 om 17 01 05](https://cloud.githubusercontent.com/assets/662966/12981610/b2ed715e-d0e1-11e5-8e20-7baabe41851a.png)

**Comment by freekwebdesign** [comment]
@stealthblade thanks for showing this issue.
I will look into that!
