### ISSUE TITLE
Add Homey version to crash report

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#590]
Having app version is sometimes not enough. Adding Homey version would explain some crashes.

**Comment by joachimroeleveld** [comment]
From now on, you should see the Homey software version in e-mailed crash logs.

**Comment by matjaz** [comment]
Just received crash report for com.youtube app, but I don't see Homey version in crash report.

Also I noticed time in report is in UTC but it's not mentioned anywhere and stack trace should be rendered each call in own line (using `<pre>`).

**Comment by joachimroeleveld** [comment]
Oh, I see. Something went wrong with the commit, which it didn't get deployed. I also added a remark of the UTC timezone and wrapped the stack in `<pre>`. Thank you!
