### ISSUE TITLE
UI & Flow: thermostat 'then' flow card with tag & 'then' heating on/off

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#592]
**What is your Homey version (Settings → System)?**

0.832

**What did you try to achieve?**

To store a variable with the original temperature before changing it, and turning it back to the original temperature. Could this be done with tags?

To create a 'then' flow card for a nest thermostat and turning the heating on or off

_Please include detailed steps how we can reproduce the issue_

It's a request for 'then' flow options. If you drag a thermostat flow card to the 'then' column, its not possible.

**What was the result?**

...

**What did you expect as result?**

Tags and be able to drag a thermostat to the 'then' column.

**Any other remarks**

Thx for the support so far!

**Comment by bvdbos** [comment]
+1, please get rid of the slider on the flow-cards and just make it a number-field (or is the risk of blowing up our heating-systems too big?) so we cab use variables or labels. Perhaps set an input-range between 5 en 30 degrees on the input-field (40, like it is now seems way to high)?

**Comment by WeeJeWel** [comment]
Fixed in 1.1.0

**Comment by pimviergever** [comment]
@WeeJeWel this is an improvement but not a complete fix for the enhancement. 

With Nest it is possible to save the new target temperature as a textual value.
1. How do you restore the Nest target temperature from a textual value
2. How do you control the Nest target temperature as a textual value instead of a slider?

Thx!

**Comment by bvdbos** [comment]
Like in #1122 , does that work?

**Comment by pimviergever** [comment]
@bvdbos that does work!  Thanks for the tip!
But there is no tag for the 'eco temperature' or 'outside temperature' ?

**Comment by bvdbos** [comment]
Well, that's a new issue / RFE then :-)
