### ISSUE TITLE
UI & Flow: delay in 'and' column

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#593]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

To trigger a flow (by a contact sensor turning on), and to check if the contact sensor is still on after * seconds.

Laymen terms: if the door is opened for more than * seconds, then ......

*Please include detailed steps how we can reproduce the issue*

Add a delay timer to the flow card in the 'and' column

**Any other remarks**

Keep up the good work!

**Comment by bvdbos** [comment]
You could do this with the countdown-app already...
https://apps.athom.com/app/nl.bevlogenheid.countdown

**Comment by pimviergever** [comment]
ok, thx for the support!
