### ISSUE TITLE
Nest protect needs to be re-added / re-authorised after update

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#595]
**What is your Homey version (Settings → System)?**
going from 0.3.32 to 0.8.34 (and now on 0.8.34)

**What did you try to achieve?**
Update homey to 0.8.34

**What was the result?**
Homey was updated. However, the nest protects were showing a broken link with the message "This device seems to be removed externally"

**What did you expect as result?**
No devices being "broken" after an update

**Any other remarks**
After re-autorising the Nest app in the settings, I could add the Nest protect again.

**Comment by kaandorp** [comment]
Same here

**Comment by RobinBol** [comment]
Thanks for reporting this issue. This could have two causes, one of which I reported internally (needs further examination), and one which is caused by the Nest API and the fact that we do not have unlimited clients as of yet, therefore this can not be solved at the moment.
