### ISSUE TITLE
"Ok Homey"-Indicator has a huge delay.

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#597]
**What is your Homey version (Settings → System)?**
.34

**What did you try to achieve?**

When I say "ok homey" it seems to be a delay in 50% of all attempts. The yellow ring listening indicator appears 2-4 seconds too late.
https://youtu.be/9lDL4W2Qm40

But when i continue speaking right after the trigger homey gets the command, but skips the listening indicator.

You can see this in the 2nd try in this video. If I would have waited with my question, the yellow indicator would've appeared after 2-4 sec.
https://youtu.be/GSp3ZNnO6Vw

**Any other remarks**
A reboot didn't help.
Apps installed:
Soundboard, Plex, Harmony, Hue, Better Logic, HTTP request, Synology, WOL, WU, Email Sender, IFTTT, ical, News Headlines.

**Comment by WeeJeWel** [comment]
That's a pretty long delay indeed! Thank you for making a video.

What are your cpu loads after running for 15 minutes? Settings -> System -> Show stuff for geeks

**Comment by peaoo** [comment]
"cpus	[{"model":"ARMv7 Processor rev 10 (v7l)","speed":792,"times":{"user":66477900,"nice":0,"sys":18376700,"idle":60456800,"irq":3200}}]
date	2016-05-13T19:09:44.364Z
date_dst	true
date_human	Friday 13th May 2016 21:09:44
devmode	false
freemem	35139584
homey_version	0.8.34
hostname	Homey
loadavg	[1.15673828125,1.12451171875,1.10595703125]
network	{"lo":[{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true},{"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","scopeid":0,"internal":true}],"wlan0":

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by peaoo** [comment]
It's still there. I am going to wipe homey when 0.9 is there. Maybe this helps. 
I am wondering because it seems I am the only one suffering to this issue.

**Comment by jeroenvollenbrock** [comment]
Okay, looking forward to your findings!

**Comment by peaoo** [comment]
Seems to be solved with 0.9. Great job, Thanks!
