### ISSUE TITLE
see no devices on android app only GUI

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#598]
**What is your Homey version (Settings → System)?**

0.8.34 homey
android app 1,32, even removed and reinstalled app

see my devices on android app 

*Please include detailed steps how we can reproduce the issue*
 speaks for itself

**What was the result?**
i only see one room a globally unique identifier

**What did you expect as result?**

the device

**Any other remarks**
no

**Comment by Robinyoh** [comment]
in IOS app zones also empty. I can see the the zones, but no devices in it.

**Comment by WeeJeWel** [comment]
This happens when one or more of your devices is unavailable and/or its driver does not respond to a get request. 

This is already fixed in 0.8.35 :)

**Comment by Robinyoh** [comment]
Is there a way to get it working on .34? In the webapp on local ip are there also no devices anymore...

**Comment by WeeJeWel** [comment]
Remove your devices that stay unavailable. Or wait for 0.8.35, it'll be released this week :)

**Comment by Robinyoh** [comment]
all my devices all unavailable, but will wait for the release

**Comment by Robinyoh** [comment]
Cards are available now on ios app.

**Comment by nattlip** [comment]
with the new android app and homey version 0.8.35 worked a few days correct , now all my diveces scroll very quickly over the screen and then i see a blank screen, when there are a lot of devices in a room , with 2 devices no problem

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
