### ISSUE TITLE
Meshed up flows

### ISSUE THREAD

**Issue by posthok** [athombv/homey#599]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**
create a flow

*Please include detailed steps how we can reproduce the issue*
After adding some flows and saving them in some of the flows apearing tags from other flows.
First i create some flows. Later i want to check these flows and they contain tags in the then section i never wrote.
It happens not in every flow though.

**What was the result?**

The flow is not excecuted as entered.

**What did you expect as result?**
a working flow.

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Can you post screenshots?

**Comment by posthok** [comment]
I just got rid the unwanted tags. As soon it apears again i'll make a screenshot

**Comment by caseda** [comment]
I have seen this once as well. 
It seems like the session isn't being unset completely/propperly after the flow has been saved and then going to another flow short after the save, and then appends the new flow cards with it still in session flows cards.

At first I thought it was a chrome error. But know maybe not. 

Fix could be to just make sure the particular session is being unset/emptied (again) when loading a flow

**Comment by posthok** [comment]
![homey flow](https://cloud.githubusercontent.com/assets/6661318/15269029/a37fdf9a-19f2-11e6-89fb-310bfd18e200.png)

**Comment by Dijker** [comment]
I have seen this one trigger per flow also in 0.8.32 last week.  I will look if I can reproduce.

**Comment by posthok** [comment]
This is only one example. The other errors ocurring in the then section.

**Comment by RT744** [comment]
I can confirm it's ocurring in 0.8.32.
