### ISSUE TITLE
Apps: settings not saved on first call

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#600]
**What is your Homey version (Settings → System)?**

0.8.34

**Wht did you try to achieve?**

Save app settings from an apps settings page.

**What was the result?**

Settings saved, but callback function not called.

**Any other remarks**
This breaks every app with a settings page that waits for this callback.

First Homey.set call from a settings page after pageload does not save settings and execute callback.
step 1: Load a settings page and execute this in console: 
`Homey.set('test', 3, function (error, result) { console.log(error, result) } )`
result: setting saved, no callback executed
step 2: Execute command again (without reloading settings page)
result: setting saved, callback executed

**Comment by irritanterik** [comment]
Updated this issue: settings are saved, but callback is not executed on first save (after a settings page load)

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35. Also renamed `Homey.getAll(cb)` to `Homey.get(cb)` (when no name found, return all)

**Comment by daneedk** [comment]
@WeeJeWel will 0.8.35 be released asap as a fix firmware for the problems introduced in 0.8.34 or will it be the planned 0.8.35 (with the new flow editor etc.) includings these fixes?

**Comment by WeeJeWel** [comment]
0.8.35 will be released within a few days as hotfix release, with the Flow folders as bonus ;)

**Comment by daneedk** [comment]
That's good news, great! Thank you!

**Comment by irritanterik** [comment]
Confirmed fixed with 0.8.35
