### ISSUE TITLE
[Request] Add a Favicon

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#601]
**What is your Homey version (Settings → System)?**
0.8.34

**What did you try to achieve?**
Try and take over the world

**Please include detailed steps how we can reproduce the issue**
Just browse any page of your Homey.

**What was the result?**
That either no favicon image was displayed at all or on previous firmware version a 404 error was given where it actually was trying to load a favicon but which wasnt there.

**What did you expect as result?**
An nice looking favicon of a white sphere. Please give us a favicon.

**Any other remarks**
This was submitted as a request / bug before but both are closed now. See https://github.com/athombv/homey/issues/71 and https://github.com/athombv/homey/issues/370 .

**Comment by irritanterik** [comment]
#71 is still open

**Comment by jghaanstra** [comment]
Right, dont drink and report issues on GitHub  ... closed this one again.

**Comment by nattlip** [comment]
in vino veritas
