### ISSUE TITLE
Philips HUE broken in 0.8.34

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#603]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**
Connecting to Philps Hue after full reset and data erase of Homey

*Please include detailed steps how we can reproduce the issue*
Add Philps Hue device and try to connect to bridge by pressing the button on the bridge

**What was the result?**
nothing happens
...

**What did you expect as result?**
connection to the Hue bridge
...

**Any other remarks**

...

**Comment by gkroone** [comment]
I have the same problem, but need to mention I had this problem already after a full reset and data erase on 0.8.32 so it might be something going back further.

**Comment by Fiek1** [comment]
Tried adding the sockets and remotes with another laptop of mine and this worked. Apparently there is something fishy in the browser of the laptop I normally use

**Comment by Fiek1** [comment]
I have reset my browser settings and it still doesn't work in my laptop I normally use but I have added my Hoe bridge with my other laptop so I will close this issue

**Comment by bvdbos** [comment]
It kinda looks like you have a proxy set on your normal laptop, at least that what I make from googling... If it's not set on purpose maybe some spyware-thing perhaps?

**Comment by Fiek1** [comment]
Thnx for the suggestions. I will scan my laptop for spyware just to be sure
