### ISSUE TITLE
Apps are broken (Somfy, LightwaveRF, WU...)

### ISSUE THREAD

**Issue by zperx** [athombv/homey#604]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**

Use my Homey as before.

**What was the result?**

None of my 433MHz devices are responsive.

**What did you expect as result?**

To use my Homey as before.

**Any other remarks**

Reboots, app removals-reinstalls, re added devices has not sorted the issue.

**Comment by jaxc0402** [comment]
did you try u full clean install? that made kaku working for me. Somfy still no-go

**Comment by zperx** [comment]
Yes I did that, and got the same result as you. The Somfy is still broken.

**Comment by Dennishacq** [comment]
@zperx 
What 433MHz devices are you using?

**Comment by Dennishacq** [comment]
Oops, missed the title of this issue.
I've fix this bug in the Somfy update that should come out later this week.

**Comment by Dennishacq** [comment]
Somfy v1.0.12 is now available in the appstore.

**Comment by Deentje** [comment]
For me it works again, thanks!!

**Comment by RoadXY** [comment]
Somfy working again!

**Comment by zperx** [comment]
Yes it works again and it seems to have the My command as well.
