### ISSUE TITLE
[0.8.34] Z-wave error "Error: Timeout waiting for report"

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#606]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**
Installed 0.8.34 with full reset
Was running for 10 hrs 'stable'
Installed KaKu app this morning

**What was the result?**
Get an error on three of the Z-wave devices: "Error: Timeout waiting for report"
<img width="1012" alt="schermafbeelding 2016-05-14 om 10 53 02" src="https://cloud.githubusercontent.com/assets/17163431/15267425/17539ece-19c2-11e6-81be-f783fecc8105.png">

Z-wave list (in settings) does not show an error for these devices... but only show that the motion sensors have failed

**What did you expect as result?**
No timeout error

**Any other remarks**

LOG: BB94EE1FA2
Restart of Z-wave chip does not resolve issue
LOG: E85D749B27 (after Z-wave chip restart)

Possible link with #605 but different error code

**Comment by Muyz** [comment]
Same problem here: added Fibaro Dimmer 2. Interview fails, so it is added as a basic device. After rebooting Homey, I get the error as reported.
