### ISSUE TITLE
[0.8.34] Z-wave unable to set parameters / wakeup interval / polling - "Cannot read property 'id' of undefined"

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#607]
**What is your Homey version (Settings → System)?**
0.8.34

**What did you try to achieve?**
Installed 0.8.34 with full reset
Was running for 10 hrs 'stable'
Installed KaKu app this morning
Update the settings of several Z-wave devices (e.g. parameters or polling interval) via the device settings card

**What was the result?**
Error message: "Cannot read property 'id' of undefined"
<img width="714" alt="schermafbeelding 2016-05-14 om 10 59 49" src="https://cloud.githubusercontent.com/assets/17163431/15267477/a3e38dbc-19c3-11e6-960e-39d0e8bb150f.png">

Not being able to set the parameters via the device card
It is possible to set these parameters via a flow as containment; but I'm not able to set the polling interval / wakeup interval via the flow

**What did you expect as result?**

working update

**Any other remarks**

LOG: 345B702579

**Comment by bvdbos** [comment]
Did this only happen after installing KaKu?

**Comment by TedTolboom** [comment]
No, this issue I already had after full reset and before KaKu was installed

**Comment by ocatie** [comment]
I'm having trouble reproducing the bug. Is there any additional logging in the chrome console?

**Comment by bvdbos** [comment]
![2016-05-18 13_44_16-homey zones devices](https://cloud.githubusercontent.com/assets/1064079/15357378/b37c9154-1cfe-11e6-8c0c-7469d9ee5bde.png)

it can't be hard. Just set a parameter through the GUI or alter the interval. Then press "save". Afaik everyone has this problem... As it's about saving, it could be related to #600

**Comment by ocatie** [comment]
Fixed in 0.8.35
