### ISSUE TITLE
Android app not listening to speech on samsung galaxy s6edge

### ISSUE THREAD

**Issue by gkroone** [athombv/homey#610]
**What is your Homey version (Settings → System)?**

0.8.32 with android app 1.1.6 build 32
(Same happens when homey is on 0.8.34)

**What did you try to achieve?**
Use mobile app to send voice commands to homey

*Please include detailed steps how we can reproduce the issue*
Open homey app and talk to it.

**What was the result?**
I see no waveform at the bottom of the screen indicating the audio received. On another mobile phone this does show (sony xperia z3compact works as expected)
...

**What did you expect as result?**
Have the app respond to voice and show the  waveforms for the audio received. 
...

**Any other remarks**

...

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/16504/#Comment_16504

Is it just the white line and is voice coming through to android (you can check on http://<ip>/manager/speech-input/

**Comment by gkroone** [comment]
The problem seems to have changed. Now i do see the white line where it did not show up before. But the response to "laatste nieuws" still came from homey and not from the app, and only stated "recente nieuwsberichten" without any of the expected news items. I cant find the settings menu in the app anymore to see if this is a setting? I suggest to close this issue for now and I'll post a new one once i have investigated more.

**Comment by bvdbos** [comment]
Speech though the phone doesn't work yet (at least, not more then one article), see #613
