### ISSUE TITLE
Everspring SP103 Wireless Z-Wave PIR Detector cannot be included

### ISSUE THREAD

**Issue by JacobJAD** [athombv/homey#611]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**

Include Everspring SP103 Wireless Z-Wave PIR Detector

**What was the result?**

No result at all

**What did you expect as result?**

Inclusion of the Z-wave motion detector

**Any other remarks**

none

**Comment by ocatie** [comment]
Try removing the node from the network first to clear the network data of the device. Press the Remove Node button at Settings -> Z-Wave and put your device in learnmode. Then try including it again.

**Comment by JacobJAD** [comment]
Upgraded to 0.8.35
Removed node, reboot and include. Only choise association group 1 or none possible
Everspring included and working issue closed
I do have to find out how it will alarm
