### ISSUE TITLE
Unable to update app on the app store

### ISSUE THREAD

**Issue by soler2000** [athombv/homey#612]
**What is your Homey version (Settings → System)?**

NA

**What did you try to achieve?**

Update an existing app in the app store

**What was the result?**

App store returned 

Oops! Your app did not pass our validation process. The following errors occurred:
The repository does not exist or is private.

**What did you expect as result?**

The app to be submitted for approval

**Any other remarks**

app trying to update is

https://github.com/soler2000/com.lightwaverf

**Comment by joachimroeleveld** [comment]
Closing this issue (for now) based on our conversation over Slack and the inability to reproduce.

**Comment by IcarusProject** [comment]
I currently have the same isue. Any tips on how I can solve this?

**Comment by freemann** [comment]
@IcarusProject
Is the app, you try to update, crashed (red exclamation mark)? If so, disable the app, reboot homey, the update the app.

**Comment by IcarusProject** [comment]
@freemann
Nope. I'm actually trying to add a new app to the appstore using the following URL https://github.com/IcarusProject/me.zwave.git

**Comment by freemann** [comment]
Ah ok, developer tries to update app :)
