### ISSUE TITLE
asynch speech output to android app

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#613]
**What is your Homey version (Settings → System)?**
0.8.34 exp. / android 2.0-build40

**What did you try to achieve?**
Direct speech output to phone-app

*Please include detailed steps how we can reproduce the issue*
Have five headlines send to phone by 
Homey.manager('speech-output').say(__(NewsItem[i]),{ session: speech.session });

**What was the result?**
Asynch sending to phone isn't queued, see
https://athomcommunity.slack.com/archives/developers/p1463307001000880

**What did you expect as result?**
speech output is queued

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35. However this will also require an update in the app.

@goldenice, the `speech` event now also contains a `count` property, which is a Number that is incremented each time when a speech item is generated for that session.

**Comment by RoadXY** [comment]
Lol, missing milestone here :-p

**Comment by WeeJeWel** [comment]
Because it's also dependent on the mobile app ;-)
