### ISSUE TITLE
speech output to android-app too long

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#614]
**What is your Homey version (Settings → System)?**
0.8.34 exp. / android 2.0-build40

**What did you try to achieve?**
Direct speech output to phone-app

*Please include detailed steps how we can reproduce the issue*
Also see #613 
Have five headlines send to phone by creating one longer string
Homey.manager('speech-output').say(__(totalnews),{ session: speech.session });

**What was the result?**
No ouput to phone but, judging the white line, data is send
https://athomcommunity.slack.com/archives/developers/p1463334830000885

**What did you expect as result?**
speech output also for longer string

**Comment by bvdbos** [comment]
replacing `say(__(totalnews)` with `say(__(newsHeadlines[1]+","+newsHeadlines[2]+","+newsHeadlines[3])` works but adding a fourth doesn't work...

**Comment by WeeJeWel** [comment]
Sorry, but there's a new character limit of 255 characters since 0.8.34. You should've seen that as Error in the callback :-)

I'll update the docs accordingly.
