### ISSUE TITLE
Homey bricked after update

### ISSUE THREAD

**Issue by edwinv** [athombv/homey#616]
**What is your Homey version (Settings → System)?**

0.0.0-update.inc

**What did you try to achieve?**

Tried to update from an older version using the beta channel. Which version was the previous is unknown to me. 

**What was the result?**

Red leds, Homey not responding. After hard restart (power disconnected), same issue.

**What did you expect as result?**

An updated Homey :)

**Any other remarks**

Tried sending logs to you, but this feature is also broken.

**Comment by WeeJeWel** [comment]
Auch! Sorry to hear that. Please contact support@athom.com for how to proceed.
