### ISSUE TITLE
enable flow not translated and ambiguous

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#617]
In Dutch we have a condition-card "Een flow staat aan" and action-cards "Enable a flow"/"Disable a flow". The action cards are not translated and the condition-card is not clear. Does this mean "a flow is running" or does this mean "a flow is enabled"? If it's the first this would be very handy for creating sequential actions... 
![2016-05-18 07_25_58-homey flow](https://cloud.githubusercontent.com/assets/1064079/15348348/42ae1ec2-1cca-11e6-9c6a-2615253824a3.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.8.35

**Comment by WeeJeWel** [comment]
![screen shot 2016-05-18 at 12 40 24](https://cloud.githubusercontent.com/assets/319873/15355886/b6eee390-1cf5-11e6-9a8f-36315ebfb965.png)

Suggestions for translations are always welcome

**Comment by RoadXY** [comment]
Jay, an milestone, lol, j/k

**Comment by bvdbos** [comment]
"Aanzetten" / "Uitzetten" in the action-card like you had in the condition-card? "Activeren"/"Deactiveren" are good therms for the action-card but somehow "Een Flow is geactiveerd" feels like it's running for me... Perhaps "Een Flow staat geactiveerd"? But, in the end more important is that it is consistent.
