### ISSUE TITLE
Flow editor: when playing around, removed cards return in flow 

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#62]
Some strange behavior. Reproduction path:
- Create new flow
- Drag speech card to 'then'
- Drag second speech card to 'then'
- Drag first speech card to 'and' (it disappears)
- Drag second speech card to 'when'
- Drag second speech card back to 'then'

Now the second speech card seems to be 'cloned'.

**Comment by WeeJeWel** [comment]
Woah, now this is how I like bug reports! Will fix this :)

**Comment by irritanterik** [comment]
Still exists in 0.8.20

**Comment by bvdbos** [comment]
This still exists on 1.0.3. Furthermore, after the last step you can't move the speech card away from the action-column anymore...

**Comment by irritanterik** [comment]
Still exists on 1.1.2

**Comment by irritanterik** [comment]
Its fixed in 1.3.0-rc1! :beers:
