### ISSUE TITLE
Missing scrawl in "...Then" field flow selection.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#620]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

In “…Then” field there is no scrawl option to select another flow. You have to type in the name.

**What was the result?**

I had to try and remember part of the name in order to reach the other flow

**What did you expect as result?**

Scrawl bar that lets you select from your flow list.

**Any other remarks**

...

**Comment by bvdbos** [comment]
Works for me (at least in 0.8.34 but afaik this works some versions already). Just click in the textbox once more. Beware however, you don't "start" the flow-actions. You enable is so it will react to the trigger in the first column.

**Comment by bvdbos** [comment]
![2016-05-18 22_00_41-homey flow](https://cloud.githubusercontent.com/assets/1064079/15373057/fcec27ec-1d43-11e6-8f9a-fcab92f5a58b.png)

**Comment by Dijker** [comment]
What do you mean? I think #383 ?
or give a screenshot what you try to achieve?
I have a SCROLLBAR in 0.8.34 
![image](https://cloud.githubusercontent.com/assets/12412734/15373031/c7d2f360-1d43-11e6-976c-88ec619fa56c.png)
and one selecting the slow names:
![image](https://cloud.githubusercontent.com/assets/12412734/15373058/fd31eeb2-1d43-11e6-9f1e-f41a42ee3efd.png)

**Comment by spawnreaper** [comment]
mine is updated now. I see the bars. thanks
