### ISSUE TITLE
Lifx bulb flash when making transitions. color and dim.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#621]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

Using a flow I am trying to make changes to color or dim level the lifx bulbs

**What was the result?**

Bulb will flash to 100% elimination for a second before changing a value. 

**What did you expect as result?**

smooth transition from color to color and a smooth dim up and down.

**Any other remarks**

value is 80% the time wrong. but will make a separate report for that.

**Comment by RobinBol** [comment]
Thanks for reporting, fixed in next release of the LIFX app (you probably need to re-add your LIFX devices though, sorry for that).
