### ISSUE TITLE
Voice stutter on voice feedback.

### ISSUE THREAD

**Issue by spawnreaper** [athombv/homey#623]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.8.32

**What did you try to achieve?**

Homey giving custom voice feedback.

**What was the result?**

Several "voice" feedback homey struggles to get the sentence out. 

**What did you expect as result?**

Smooth voice feedback. No stuttering.

**Any other remarks**

Is this a hardware processing struggling thing?

**Comment by Dijker** [comment]
#550  ?

**Comment by spawnreaper** [comment]
oeps.
