### ISSUE TITLE
UV capability not available

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey#624]
**What is your Homey version (Settings → System)?**

0.8.34

**What did you try to achieve?**

Try to ad a uv sensor as a sensor device in Homey.

**Please include detailed steps how we can reproduce the issue**

The uv capability isn't available in Homey. It could be something like measure_ultraviolet.
The value is a index value, that is it has no unit. The value can be 0.00 - 12.00. In theory the value can be higher, but most sensors don't go beyond that.
I want this capability for my arduino uv sensor device (mysensors.org) but also available in the Aeon labs multisensor 6 (z-wave).

**What was the result?**

Device is not recognized by Homey

**What did you expect as result?**

Device can be used in Homey to report measurement

**Any other remarks**

https://www.mysensors.org/uv/skinchart.jpg

http://www.knmi.nl/nederland-nu/weer/waarschuwingen-en-verwachtingen/zonkracht

**Comment by matjaz** [comment]
https://github.com/athombv/node-homey-lib/pull/20
