### ISSUE TITLE
Philio (PHI_PAN06) dual relay adds 4 devices? - Z-WAVE

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#625]
**What is your Homey version (Settings → System)?**

.34

**What did you try to achieve?**

Adding new device.

**What was the result?**

The device is added, but 4 devices show up...?

**What did you expect as result?**

I'm not sure as it's my first relay, perhaps just 2 devices ;-)

**Any other remarks**

3 of them appear to work (2 control 1 relay, 1 controls the other). 1 seems useless?

Can this be fixed, pretty please?

<img width="517" alt="screen shot 2016-05-19 at 22 52 16" src="https://cloud.githubusercontent.com/assets/1001877/15410911/5cb8bac0-1e14-11e6-80af-af9f96a0d840.png">

<img width="318" alt="screen shot 2016-05-19 at 22 54 41" src="https://cloud.githubusercontent.com/assets/1001877/15410970/b48cb0b2-1e14-11e6-9f60-a1af1d3d87c4.png">

**Comment by caseda** [comment]
It should work like this at the moment:
2 = The overall/main device, this one is needed to be able to send parameters inside a flow.
2.1 Endpoint 1 = Relay 1 & Relay 2 (Switching both relays at the same time)
2.2 Endpoint 2 = Relay 1
2.3 Endpoint 3 = Relay 2

**Comment by markaswift** [comment]
@caseda Good to know, I had no clue what all the devices were! Looks right then!

**Comment by markaswift** [comment]
@caseda This is how it appears to work for me...

<img width="208" alt="screen shot 2016-05-21 at 11 04 16" src="https://cloud.githubusercontent.com/assets/1001877/15447744/d1bb5cc6-1f43-11e6-8187-593e1cc13787.png">

**Comment by caseda** [comment]
The endpoints are switched, that is kinda strange (endpoint 1 is supposed to be both relays).

I guess that's the reason they are called "endpoints" by default, and not the name you gave them now.
Good for future reference though.

**Comment by ocatie** [comment]
Wil be fixed with an app.

**Comment by markaswift** [comment]
@ocatie Tell me more?

**Comment by ocatie** [comment]
With the current driver a device is created for the root node and one for every endpoint. With an app you can specify the device(s) created.

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to the Z-Wave rewrite. Please reopen if the problem persists in 0.9.3+.
