### ISSUE TITLE
Capabilities with text

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#626]
**What is your Homey version (Settings → System)?**
0.8.32

**What did you try to achieve?**
Add to a sensor to se my messages i send to a display.

**Please include detailed steps how we can reproduce the issue**
There is no capability that can handle and display text.
It will help if you can add a capability for text with getable and setable true.
You can set the maximum chars to 255 then it can handle multiply lines of text for bigger displays.

**What was the result?**
Device don't show up. And will not present the text.

**What did you expect as result?**
To see the text message in the device

**Any other remarks**
Not yet

**Comment by WeeJeWel** [comment]
Can you share a use case?

**Comment by ewikner** [comment]
For the mysensors app we need a capability that can be diffrent things. 
Only text for a LCD Display or it can be just numbers as the last timestamp.

I can do this with a custom capability then it worked to show the data in the device cards for custom capabilities.

**Comment by matjaz** [comment]
@WeeJeWel is the type text/string supported?

**Comment by WeeJeWel** [comment]
Capability with type string is already supported. As of 0.8.39 this is also shows in the sensor mobile card.
