### ISSUE TITLE
Update Hue app to use rooms (Hue update).

### ISSUE THREAD

**Issue by Swiftnesses** [athombv/homey#627]
Some of my flows currently require 20+ hue actions. This could be decreased to 3 or 4 if the app was updated to take advantage of the new rooms feature.

**Comment by nattlip** [comment]
but the bridge isnt saving the rooms

**Comment by bvdbos** [comment]
Rooms are in Homey now, aren't they?

**Comment by WeeJeWel** [comment]
The Hue app supports Rooms from a Flow now.

**Comment by Swiftnesses** [comment]
@WeeJeWel It would be REALLY good if it showed the room when selecting a scene on the hue card(s), we have a ton of hues and about 10+ rooms setup, currently it's impossible to see what room is what when choosing a scene (i.e. 'set a scene' card). I workedaround this by renaming the savanna scene to included the room name as it's the first scene for each room, not really a good workaround though!

**Comment by WeeJeWel** [comment]
I've looked into this but a Scene does not seem to be connected to a Group in the bridge. I cannot find how they're linked together to be honest.

**Comment by griff** [comment]
@WeeJeWel You can kind of reverse engineer the group for a scene by comparing the scene lights array with the group light array.
