### ISSUE TITLE
Saving flow results in flow at the bottom

### ISSUE THREAD

**Issue by fn002449** [athombv/homey#629]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Saving flow wich was in a folder.

*Please include detailed steps how we can reproduce the issue*
Put some flow in a folder (in the flows list)
Try to change the flow and save

**What was the result?**
Flow is not in the folder anymore but at the bottom of the list

**What did you expect as result?**

Flow stays in the folder

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Fixed in 0.8.36
