### ISSUE TITLE
klikaanklikuit yct-100 remote and yc-1000 socket

### ISSUE THREAD

**Issue by mirakels** [athombv/homey#63]
I have a bit of older klikaanklikuit set using a YCT-100 remote and YC-1000 socket. 
Unfortunately this combination this not seem to be recognised by homey.
When adding a controller as device I click on a on button, but homey does not respond to it.
The remote specs are 433.92 MHz.

**Comment by kkuyper** [comment]
I have the same problem!

**Comment by Dennishacq** [comment]
See reference above
