### ISSUE TITLE
Error 500 HTTP PUT Request /api/manager/flow/order

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#630]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

Ordering flows witch is new in 0.8.35

**What was the result?**

Homey that hangs and not handle the PUT request

**What did you expect as result?**

Orderd items

**Any other remarks**

This command

`curl 'http://192.168.1.10/api/manager/flow/order' -X PUT -H 'Accept: application/json' -H 'Authorization:Bearer c10b78a3e7da4b0cb45155bd90b631ff01850920' --data-binary '[{"id":"236262f2-b0d9-48bc-80dd-cf28d803154e","type":"flow","folder":false,"order":0},{"id":"98ce1809-2032-46fc-807b-40a8e5242e27","type":"folder","folder":false,"order":1},{"id":"c250c21c-c261-4f5b-ba78-2e01082dbb2b","type":"folder","folder":false,"order":2},{"id":"ca45f2b9-ab18-4952-81f0-ff5784cb29ed","type":"folder","folder":false,"order":3},{"id":"2fe4088e-3509-4907-953d-d19668c4e561","type":"folder","folder":false,"order":4},{"id":"10d2d6b2-ed20-4551-95bb-415be4f4efb4","type":"folder","folder":false,"order":5},{"id":"3192e559-4039-4f04-82ec-d9701d717a7d","type":"folder","folder":false,"order":6},{"id":"ff131906-8ed9-4f06-9249-283eca3f414e","type":"folder","folder":false,"order":7},{"id":"32d19fa9-fc6d-43fd-b847-a33ce6d045d9","type":"folder","folder":false,"order":8},{"id":"27d55726-0195-47af-aafe-c2402b0f1b73","type":"folder","folder":false,"order":9},{"id":"7a7e8e61-caf8-4b82-a01f-182e5b07b5b1","type":"flow","folder":false,"order":10},{"id":"929f06eb-ff7a-43f1-b195-89c84694d6b8","type":"flow","folder":false,"order":11},{"id":"8cfbd14c-9f93-4675-83cc-f627fc274340","type":"flow","folder":false,"order":12},{"id":"c784f5fc-5468-4725-8d70-d82055628e83","type":"flow","folder":false,"order":13},{"id":"5244060c-b188-4c89-8e15-dab61ee33bed","type":"flow","folder":false,"order":14},{"id":"da12ef8c-5bfc-4c90-b9a9-041d621d3814","type":"flow","folder":false,"order":15},{"id":"d43c9033-28a8-4eff-8db5-5b1a30105654","type":"flow","folder":false,"order":16},{"id":"5ae238da-03f1-4112-b722-0e7b09a8d650","type":"flow","folder":false,"order":17},{"id":"6051e9e5-6983-4168-9d46-e9bb0a76ddf6","type":"flow","folder":false,"order":18},{"id":"b925e66a-0ced-4846-8a07-caa3bc67db33","type":"flow","folder":false,"order":19},{"id":"e7fda93f-b5e1-49b9-b202-6da449aca18a","type":"flow","folder":false,"order":20},{"id":"c5698ef4-b465-4b33-a4ba-c0c42ec67407","type":"flow","folder":false,"order":21},{"id":"5172f9fb-41b7-4bf9-909e-9bfd5a0e66db","type":"flow","folder":false,"order":22},{"id":"4d168c22-04af-4fe4-98ce-eb94d74367b6","type":"flow","folder":false,"order":23},{"id":"110fbdd6-7832-4828-8faf-67925ceae827","type":"flow","folder":false,"order":24},{"id":"8af62c1a-7a52-4ff8-8149-81dca12d463c","type":"flow","folder":false,"order":25},{"id":"25ca2980-3cf8-41a7-92ee-b641fd434af3","type":"flow","folder":false,"order":26},{"id":"8a6ae5df-181d-4975-b510-7824f781a821","type":"flow","folder":false,"order":27},{"id":"db7f6e63-def0-4187-9128-d54bc4982c79","type":"flow","folder":false,"order":28},{"id":"720d305a-579d-4159-9d53-7bc842e8cef3","type":"flow","folder":false,"order":29},{"id":"318600cf-4c0f-4a50-a6d1-8c71d9bcd4e1","type":"flow","folder":false,"order":30},{"id":"44ff6746-9ac3-4527-9a29-9c73e138cfb4","type":"flow","folder":false,"order":31},{"id":"ac0d9dbe-9144-47ba-b42b-d2ab90652484","type":"flow","folder":false,"order":32},{"id":"a42f94ac-233d-473a-ac0f-262f27c6878d","type":"flow","folder":false,"order":33},{"id":"06c9e150-43a9-49bd-ae59-e33fa781a7e0","type":"flow","folder":false,"order":34},{"id":"be16cbde-843f-4a2c-96ad-dc26120b060a","type":"flow","folder":false,"order":35},{"id":"be10e72f-e7b0-4960-a0e8-d7c1e5e1607d","type":"flow","folder":false,"order":36},{"id":"786d2861-0745-4a55-aa88-92c0b6ab2cce","type":"flow","folder":false,"order":37},{"id":"f244c85e-090d-448c-9154-4791b0c7a717","type":"flow","folder":false,"order":38},{"id":"311d8e6a-046d-4b1d-b176-5d44f904fc29","type":"flow","folder":false,"order":39},{"id":"8074a9f7-efa5-4540-a980-24f8f441b7bb","type":"flow","folder":false,"order":40},{"id":"70a26990-2491-407d-b9f4-dcce21e5848d","type":"flow","folder":false,"order":41},{"id":"a7472cda-8757-4cf5-b510-aec83502736c","type":"flow","folder":false,"order":42},{"id":"fbdf1a37-f420-45be-b0bf-360fb30de1d8","type":"flow","folder":false,"order":43},{"id":"bb2a904c-f6c4-4028-8875-3aa2baf91fc6","type":"flow","folder":false,"order":44},{"id":"dc924a64-1768-4b6a-9a16-d30f961573d0","type":"flow","folder":false,"order":45},{"id":"9249191b-c890-4a53-9467-3745415fa0fd","type":"flow","folder":false,"order":46},{"id":"2d776b3f-46fa-48c5-be3e-a424a79895f0","type":"flow","folder":false,"order":47},{"id":"1c7a3e78-75c1-4266-b2dd-7cd750d21a7c","type":"flow","folder":false,"order":48},{"id":"cf74595e-f484-40b9-adf9-b91e88e84998","type":"flow","folder":false,"order":49},{"id":"59ccac38-e0e1-49e4-97b0-8e635e6925c7","type":"flow","folder":false,"order":50},{"id":"67c93224-c8f5-4a20-84c9-3d55241264da","type":"flow","folder":false,"order":51},{"id":"4fb7f318-26c4-45c0-b4ba-3c24ec81cc46","type":"flow","folder":false,"order":52},{"id":"6f3c92e3-fc3d-4b71-8ba7-817f3af116aa","type":"flow","folder":false,"order":53},{"id":"32a46ebc-192a-4316-b808-a75d3be1743e","type":"flow","folder":false,"order":54},{"id":"64c57292-1e0e-4152-a928-02e130dca6d0","type":"flow","folder":false,"order":55},{"id":"0a130009-312c-43c4-b822-e43f244f9c05","type":"flow","folder":false,"order":56},{"id":"72238542-4f25-4f5c-b27b-e56f0d3a2b8c","type":"flow","folder":false,"order":57},{"id":"3f12018a-7646-4a61-bf5e-c05d285e4212","type":"flow","folder":false,"order":58},{"id":"261a27bb-9464-44e9-a5f1-f04904dc9d1e","type":"flow","folder":false,"order":59},{"id":"b4c90054-45e4-445e-8dc6-ac7add47396b","type":"flow","folder":false,"order":60},{"id":"611b3230-f16c-4184-9f18-b028c1b0e053","type":"flow","folder":false,"order":61},{"id":"7d9268d2-d156-4611-889c-4f3cb4720f1f","type":"flow","folder":false,"order":62},{"id":"344f9e58-1bff-4098-ab69-508d5961cd78","type":"flow","folder":false,"order":63},{"id":"c29c544b-c1b0-416c-835f-046b5d305619","type":"flow","folder":false,"order":64},{"id":"18f012cb-6b58-424a-8c4a-64960dba9c16","type":"flow","folder":false,"order":65},{"id":"fef8ac6c-469d-4ac2-bff6-fd6577377d83","type":"flow","folder":false,"order":66},{"id":"caa84320-855a-441c-b8ed-c2ba03bc5851","type":"flow","folder":false,"order":67},{"id":"0b60a12b-224a-42a1-ba00-2616084f0218","type":"flow","folder":false,"order":68},{"id":"1ad65e9f-be95-4f8b-b337-306aba005371","type":"flow","folder":false,"order":69},{"id":"79ff4241-314e-4981-aad6-4684cc2371e4","type":"flow","folder":false,"order":70},{"id":"54c33c65-e180-48a7-bf13-fa0a1af91e6d","type":"flow","folder":false,"order":71},{"id":"18ab2d3e-79c3-45fe-bfb9-6ced575e1391","type":"flow","folder":false,"order":72},{"id":"8a3a48fe-431c-435a-b2fd-4b8aff943e7f","type":"flow","folder":false,"order":73},{"id":"77616165-82c4-4db3-b985-6f308c06ad2c","type":"flow","folder":false,"order":74},{"id":"e4a1b419-e6b1-48a0-bb9e-2339e334d25c","type":"flow","folder":false,"order":75},{"id":"7a4ea59e-8b65-4782-ac7d-65b51d8bdb84","type":"flow","folder":false,"order":76},{"id":"fd74451a-39f4-4273-a6d8-263f318472a9","type":"flow","folder":false,"order":77},{"id":"3ea3cb46-a7ff-47cf-bd3d-8d38ad4034a6","type":"flow","folder":false,"order":78},{"id":"1fda00fd-08db-43e5-8ce7-aae41e8eb34a","type":"folder","folder":false,"order":79},{"id":"57ba4080-6c6f-4569-9786-9a88cb71065b","type":"flow","folder":false,"order":80},{"id":"bea13f8b-d41d-49cb-b94f-51284d85a11a","type":"flow","folder":false,"order":81}]' --compressed -vvv > curl_log.txt`
will give me this error

`{"status":500,"result":"e.forEach is not a function"}`

P.s. the Bearer is anonymized

**Comment by bvdbos** [comment]
It looks like the same problem as with #635 and #631 ...

**Comment by WeeJeWel** [comment]
Does this only happen when doing a curl request, or also in the browser?

**Comment by WeeJeWel** [comment]
(Error fixed in 0.8.36)

**Comment by kerkenit** [comment]
The browser hangs on the same request. The curl command I copied from the inspector, gives me a error 500. See message at the bottom

**Comment by kerkenit** [comment]
Chrome say that the PUT request is pending

**Comment by kerkenit** [comment]
![schermafbeelding 2016-05-23 om 21 04 53](https://cloud.githubusercontent.com/assets/13370203/15481301/15b1180c-212a-11e6-88a9-f7bd7dd223cd.png)
![schermafbeelding 2016-05-23 om 21 04 45](https://cloud.githubusercontent.com/assets/13370203/15481302/15b29a24-212a-11e6-9d2e-d0cddaadcc8b.png)

**Comment by kerkenit** [comment]
Issue issn't fixed in 0.8.36.
I'm getting right no another error message. Issues is still the same.
`{"status":500,"result":"callback is not defined"}`
I've hoped I can change flows again after two weeks. I'm addict to Homey.

**Comment by WeeJeWel** [comment]
Can you invite me to your Homey on emile@athom.nl so I can see for myself?

**Comment by kerkenit** [comment]
I've fixed this issue myself. I've hacked the original JSON object witch was a lof of work.
I saw that the original JSON set was 9175 byes big. After I'm Googled I found out that a GET request [8192 bytes](http://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request) (8KB).
I couldn't found a correct answer, but I'm guess a PUT request is a POST request without returning data. A PUT request length can be (I guess again) every length, but default it 8KB (The same length of a GET request)  
The solution was removing a whole bunch of flows that I can mis. Right now I've 7673 bytes instead of the original of 9175 bytes.
When I'm execute this from the command line (With the same headers like Chrome does) it took me 6 minutes and 53 seconds to complete the request.
When I look in Homey al flows are ordered in the correct folder.

**Comment by kerkenit** [comment]
For the record: I've got in the original JSON 73 flows and 9 folders. Right now I've 60 flows and still 9 folders

**Comment by bvdbos** [comment]
Great find... stress-testing over the limit :+1: But your fix is only temporarily as you did have to delete flows. Hope Athom can adjust the http-server. Might be enough to add the "Transfer-Encoding: chunked" header?
https://www.jmarshall.com/easy/http/#http1.1c2

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by kerkenit** [comment]
Problem is fixed
