### ISSUE TITLE
Saving flow in flow, flow goes out of folder

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#632]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Save a flow in a folder, giving it a new name

*Please include detailed steps how we can reproduce the issue*
Create a folder. Add an existing flow to the folder.

Open the flow and change the name of the flow.

**What was the result?**
The flow is now out of the folder again.

**What did you expect as result?**
The flow to stay in the folder.

**Comment by fn002449** [comment]
same as this one: https://github.com/athombv/homey/issues/629

**Comment by dhanstede** [comment]
I have also this problem....

**Comment by WeeJeWel** [comment]
Fixed in 0.8.36
