### ISSUE TITLE
Flow folder name not save correctly

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#634]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Create a flow folder with a specific name

*Please include detailed steps how we can reproduce the issue*
[recording.zip](https://github.com/athombv/homey/files/275846/recording.zip)
Create a flow folder, name it, place flows in it. See the attachement.

**What was the result?**
After moving away from the floweditor and opening it again the folder name was 'new folder'

**What did you expect as result?**
See the name I gave the folder.

**Any other remarks**
When I first created flow folders immediatly after the update to 0.8.35 it worked as desired. Only after a full reset with wipe the behaviour mentioned above started. (Did a full wipe twice, the first thing I tried after the second full wipe was the procedure above)

**Comment by dhanstede** [comment]
Same here... but immediate after the update to 0.8.35 not after a full reset.

**Comment by daneedk** [comment]
Found out you need to press the enter key after editing the name. 
This is not really clear and doesn't feel logical, I'd expect it to save after navigating away from the textbox either by using the Tab key or clicking somewhere.

**Comment by Arjanvde** [comment]
@daneedk Thanks for letting everybody know that you should press the "enter" button, now i'm finally able to set folder names :)

**Comment by WeeJeWel** [comment]
Fixed in 0.8.36

**Comment by daneedk** [comment]
Confirmed fixed in 0.8.36.
