### ISSUE TITLE
Push msg to andoid work on one device, not on an other device.

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#637]
**What is your Homey version (Settings → System)?**

Homey 0.8.35
App 2.1 build 45 on both devices.
 
**What did you try to achieve?**
Send Push msg to two android devices for one user

*Please include detailed steps how we can reproduce the issue*

Create a flow: Every minute

logged out and singed in again on both Android devices (as that was the first time it didn't work the solution)
![image](https://cloud.githubusercontent.com/assets/12412734/15451175/93470e8c-1fb5-11e6-940b-80669a9461b3.png)

**What was the result?**
I receive Push msg on my Galaxy S7 Edge, but not on the Galaxy TAB tablet. (shown without device name as "Android device" I guess)

**What did you expect as result?**
receiving on both devices like I was used before 2.x (but nice we now can choose to what device...)

**Any other remarks**

**Comment by bvdbos** [comment]
I would disagree. I´d prefer the option where you can choose which device you want it send to, if you want to send to both devices you can add a second card. Either that or there should be a third option, sending to the user instead of the device...

**Comment by Dijker** [comment]
To choose between a specific device or all device's the user is logged on to would be nice, but at this moment the second card doesn't work for me as notification on the Galaxy Tab doesn't work.

**Comment by fn002449** [comment]
I have also two options in the 'send a push notification' tag. But I have only one device, so wich device is listed as first (does nothing if I run the flow), the second is my phone (gives me the notification). Is there a way to remove one device from the list in the 'send a push notification' tag?

**Comment by jeroenvollenbrock** [comment]
Duplicate devices have been removed. Android 2.2.7 and iOS version 1.2.1 containing stability improvements for these issues have been submitted for approval.

**Comment by fn002449** [comment]
Yes it's working now much better. But is there a way to manually delete a phone?

**Comment by jeroenvollenbrock** [comment]
Hi @fn002449,

There is no official way to do that yet, but we might add a "Delete all devices except this one" button to the settings screen of the mobile app in the future. 

(One unsupported workaround that seems to work is to rename your device to the device you want to remove, kill and restart the Homey app, rename the device back to its original name, kill and restart the Homey app.)
