### ISSUE TITLE
Removal of Homey from Account

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#639]
**What is your Homey version (Settings → System)?**

0.35

**What did you try to achieve?**

Delete one of two homeys from my account on my.athom.com

*Please include detailed steps how we can reproduce the issue*

go to my.athom.com -> login
I see two Homeys..... No delete button or way to delete

**What was the result?**

Still have two homeys under one account.

...

**What did you expect as result?**

A nice delete homey from account button or something under profile maybee. 
Helaas pindakaas, nothing i can find

...

**Any other remarks**

Would be nice to be able to rename the Homeys.
I now have two or more devices al called Homey. When jou have more then one you need to keep track wich homey is homey.

...

**Comment by WeeJeWel** [comment]
They will be automatically removed when another account is connected to them as owner.

Renaming Homeys can be done from the Zones & Devices interface, by renaming the device called 'Homey'.

**Comment by goldenice** [comment]
> Would be nice to be able to rename the Homeys.
> I now have two or more devices al called Homey. When jou have more then 
> one you need to keep track 
> wich homey is homey.

This is already possible. Go to Zones & Devices through Homeys' webinterface, and find Homey (probably in the root zone if you haven't moved it). When you click on the name, you can rename Homey to anything you like, just like any other device 👍

**Comment by elcovb** [comment]
What about a Homey that has been returned to Athom because it was broken? It still keeps showing up and I can't remove it.

**Comment by Mikro007** [comment]
I also returned my broken homey, but still showed in my account???

**Comment by bvdbos** [comment]
You can send an email to support@athom.com
