### ISSUE TITLE
Iphone app understands only Enlish

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#640]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
I talk to the Iphone app, but understands only English
*Please include detailed steps how we can reproduce the issue*
See Oke Homey to the Iphone app in dutch and check what homey understand in the manager/speech-input/.
You see only translation of English and you see that the app = android(number) : then the enlighs text

**What was the result?**
homey did not responce
...

**What did you expect as result?**
after the "slaap lekker" that he will turn off the lights
...

**Any other remarks**

...

**Comment by goldenice** [comment]
You're right sir! This issue is already fixed in the codebase, and already shipped on Android. It'll be in the very next iOS update :)

I'll close this issue for now, as this is already fixed in our codebase.
