### ISSUE TITLE
Android app - Does not try to reconnect

### ISSUE THREAD

**Issue by zperx** [athombv/homey#641]
**What is your Homey version (Settings → System)?**

Homey: 0.8.35
Phone: LG G2
App: 2.1 build 45
Android:4.4.2

**What did you try to achieve?**

Opened the app without internet connection
Than turn on the wifi

**What was the result?**

Nothing. The app does not try to reconnect to homey.
![homey reconnect issue](https://cloud.githubusercontent.com/assets/18647800/15454409/d48925ea-202f-11e6-83ba-bb151f7dc11b.png)

**What did you expect as result?**

The app try to reconnect to homey when internet connection becomes available.

**Any other remarks**

Only solution is to close/kill the app and re-start it while the internet connection is on.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
