### ISSUE TITLE
Android app - Overlay issue

### ISSUE THREAD

**Issue by zperx** [athombv/homey#643]
**What is your Homey version (Settings → System)?**

Homey: 0.8.35
Phone: LG G2
App: 2.1 build 45
Android:4.4.2

**What did you try to achieve?**

To see the top device card.

**What was the result?**

The background bubble of the zones does not disappear but overlay the device cards.
![2](https://cloud.githubusercontent.com/assets/18647800/15455149/9c3d3c9e-2043-11e6-8a95-e80448b2570d.png)

**What did you expect as result?**

To see the all the device cards.

**Comment by goldenice** [comment]
See #646
