### ISSUE TITLE
Android app - Rendering

### ISSUE THREAD

**Issue by zperx** [athombv/homey#644]
**What is your Homey version (Settings → System)?**

Homey: 0.8.35
Phone: LG G2
App: 2.1 build 45
Android:4.4.2

**What did you try to achieve?**

To see a nice clean GUI.

**What was the result?**

Many of the icons (not all) and texts are pixelated. The sliders have graphical issues as well (see on the image). By the way what has happened with the original "slider" (Ivo Derksen kind)?

Native resolution:
![2](https://cloud.githubusercontent.com/assets/18647800/15455195/92ed335e-2045-11e6-8457-8234abc53f6c.png)

**What did you expect as result?**

To see a nice clean GUI.

**Note**
In the moment when I tap on the device it renders correctly but few milliseconds later it goes back to the low res rendering.

**Comment by goldenice** [comment]
@WeeJeWel Looks like some additional testing on the 4.x default Android browser :/ WebView doesn't get auto updated on < 5.0.

**Comment by zperx** [comment]
Not all icons have this issue. So surely there is a fix for it.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?
