### ISSUE TITLE
Android app - This zone does not contain devices

### ISSUE THREAD

**Issue by zperx** [athombv/homey#646]
**What is your Homey version (Settings → System)?**

Homey: 0.8.35
Phone: LG G2
App: 2.1 build 45
Android:4.4.2

**What did you try to achieve?**

I wanted to see my devices in the kitchen zone.
I have taped on a the zone which has an RGBW controller (6 devices).

**What was the result?**

This error message:
![x](https://cloud.githubusercontent.com/assets/18647800/15455242/9c798f70-2046-11e6-8beb-dbb51e24f15e.png)

**What did you expect as result?**

To see my devices.

**Comment by bvdbos** [comment]
This is on purpose as stated by Athom. Otherwise, if you'd start the app all your devices would be in one screen which brings a huge load on Homey and the app. However, I propose to have this not for "home" (root-node) but to do this for the subnodes anyway. It feels contour-intuitive.

**Comment by freemann** [comment]
I think this is a whole different problem, and a problem i'm also experiencing.

Some device(cards) are not showing up in the mobile apps. So I have 6 devices in the root zone and only 2 are displayed. 
From that experience I think @zperx's RGBW controller is in the selected/taped kitchen zone, but Mobile app isn't showing it.

**Comment by 4tetra4** [comment]
Well doing this on purpose is not a step toward the retail experience. Explain this to an average user, they won`t care. This is what I tried to explain couple of times that they will need need a native app not a web browser frame type of thing (although they deny it). Than after the first load icons could be stored locally (and maybe even converted to the appropriate raster version).

**Comment by zperx** [comment]
6 devices are not much. A living-dining room can easily have 40+ devices: 15 sockets (dual gang sockets are two devices), 4 dimmers, 2 RGBW (12 cards), 3-4 motion sensors, 3-4 Somfy, Sonos or other audio system, Chromecast, Harmony, smart TV, thermostat, 3-4 TRV, ventilation, door/window sensors.
Yes a instead of loading the devices card from the server they could be generated locally, more fit for purpose solution. That could allow to use a cache as well. Of course that requires more developer time.

**Comment by goldenice** [comment]
Sorry it took so long. I just found the bug with the not disappearing zone overlay and fixed it, so it should be shipped in the next release of the app. If this issue reappears in the next version, please feel free to reopen this issue :)
