### ISSUE TITLE
KAKU Fails after a while, since update to .32

### ISSUE THREAD

**Issue by RamSom8** [athombv/homey#648]
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

To turn a kaku switch on using the KlikAanKlikUit 1.1.2.

**What was the result?**

At first it works and i am able to turn the device on/off. However after a while (aprox. 6h) it fails to switch the device. It seems as if all 433Mhz communication stops working. 

**What did you expect as result?**

It to switch the device on/off.

**Any other remarks**

Had this issue since .32. Tried the following to solve the problem without any luck:
- Reinstall my homey completely
- Uninstall the plugin, reboot and reinstall the plug in. 

Log id: 387DB4E8C2

**Comment by ReinierH** [comment]
Are you still able to pair 433 devices? Do you have any other 433 devices which you can use to test if 433 works?

**Comment by bvdbos** [comment]
You might have to re-power your Homey (pull the plug, wait for a couple of seconds or minutes) and put the plug back in. That worked for me all the time.

**Comment by ReinierH** [comment]
@bvdbos, are you still experiencing that kind of issues?

**Comment by bvdbos** [comment]
I didn't experience this for a couple of days. I did happen with KaKu 1.1.2 and Homey 0.8.35 last week. After a few times powering up and down it seems solved. Either it's just a coincidence or there might be something fishy in the order Homey if powering up different radio's... Guess there's nothing we can debug ourselves on that?

**Comment by RamSom8** [comment]
Pairing does not work as well, seems the 433 transmitter is offline. Only a cold restart solves the problem for a couple of hours but issue keeps returning.

**Comment by RamSom8** [comment]
Seems more people have similar issues (https://github.com/athombv/homey/issues/665) is there anything i can do to help debug?

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0
