### ISSUE TITLE
Homey on 0.8.35 is not responding anymore.

### ISSUE THREAD

**Issue by sossienl** [athombv/homey#649]
**Version**: 0.8.35

**Problem**
- I'm trying to use the web GUI via my local IP address. but it doesn't load, or loads very slow; over 8 minutes now and bit's and pieces are showing up. In some cased it fails with the voice message 'oops ik kon de server niet bereiken'.

- **Reproduce**: No idea. I have not been able to see why this is happening. Also not able to solve it.

- **Result**: I cannot use Homey. It doesn't respond to voice, the (iOS) app says my Homey is offline. 

**Any other remarks**

- I have checked the local IP several times via my NAT table in my router. 192.168.3.86 is still the confirmed local IP address. 

- I have pulled the power twices, and one time (after waiting for 10+ minutes) I could reach the reboot button in the Web GUI.

**Comment by sossienl** [comment]
It's accessible again. Weird; I have not been able to understand the reason. Closed

**Comment by sossienl** [comment]
And we're back to the original issue. I have not access to my Homey anymore. Not via the app and not via the web. I find it stuck (led's are not moving) every x hours.

**Comment by rlijkendijk86** [comment]
Same issue here sinds 0.8.34 and 0.8.35: Homey seems to crash every day and I have to unplug the power and plug the power back in just to get it going again. Very annoying 👎

**Comment by sossienl** [comment]
0.8.36 available, but Homey doesn't upgrade. I still cannot access the device!

**Comment by bvdbos** [comment]
0.8.36 is not available yet.... 

You'll have to provide more information if you want this to be fixed. What apps and devices do you have installed?

As a workaround you might reboot your Homey in the night:
https://forum.athom.com/discussion/comment/21223/#Comment_21223

**Comment by sossienl** [comment]
Ah I thought I read it was available, but my mistake! Anyway, impossible to give a complete list because I can't access it for the last few days. ATM it's a nice looking brick.

- about 9 Z-wave devices connected
- Kodi app
- Calendar app
- Buienradar app
- Pushover app
- Headlines app
- Hue app

I might be missing something, but this happened after 0.8.35 was installed. Before that it ran perfectly.
I'll try to reboot at night; I did it yesterday (around 3:00 AM), no success

**Comment by sossienl** [comment]
I have been able to get in for the first time in days after trying for the 20th time after reboot. I disabled some of my flows and send my log (85642E5EB3). Maybe someone can take a look what the reason was / is. I'll check and see for how long Homey is keep responding, and if it freezes again

**Comment by sossienl** [comment]
and not available again.... the led ring is still moving, but web / app and voice give no response.

**Comment by Robinyoh** [comment]
will it be stable if you disable some of your apps? My homey crashes if i'm editing flows and place them in folders. Led ring stops moving. When i disable the most of my apps it will be more stable. It's maybe a memory leak? like in #635

**Comment by bvdbos** [comment]
HUE seems to be a cause of crashing too... But I can imagine you don't want to disconnect your lights. So maybe restart twice a day until this is fixed?

**Comment by freemann** [comment]
Here totally no issues with Hue (3 hue, 2 bloom) and restating fixes anything.

**Comment by sossienl** [comment]
Restarting the Homey will only keep it working for about 10min. After that it freezes again. So not a real solution. I guess it waiting until this is fixed.

**Comment by sossienl** [comment]
So I've figured out that Homey starts working the second after I unplug my HUE Bridge from the home network. And as soon as I put the UTP cable back in the HUE bridge, Homey is unresponsive...

**Comment by WeeJeWel** [comment]
I think I've found the issue and fixed it. It's pretty hard to be sure though, so we'll see what happens in 0.8.36 :)

**Comment by freemann** [comment]
Today my Homey became 2 times unresponsive and here's a log short after the second time;
205E457517

Don't know if its still needed, if its the some or another problem, but hopefully it can help @WeeJeWel solve these issues.

**Comment by sossienl** [comment]
Same problems with 0.8.36. 
Is anyone reading this Athom team?

**Comment by bvdbos** [comment]
@sossienl : I see others for who 0.8.36 seems to have improved a lot. And @WeeJeWel took this bug and hoped to have fixed it four days ago... 

Did you reboot after the update? If that didn't work you might try
https://www.athom.com/nl/ondersteuning/KB000026/

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0
