### ISSUE TITLE
No stop playing in media action

### ISSUE THREAD

**Issue by JohanKuster** [athombv/homey#65]
I would be nice to be able to stop the music, I can't find it. Could pause it indefinitely though.

**Comment by Fire69** [comment]
And a volume control would be nice also, this thing is way too loud by default! :)

**Comment by denelan** [comment]
+1 +1
Especially the volume control is needed.

**Comment by WeeJeWel** [comment]
Volume control is added in 0.8.18. I don't really see the need for a dedicated Stop action. Any arguments?

**Comment by denelan** [comment]
Being able to stop the sound fairly quickly helps when you are in a conversation or have to answer the phone. So the need for Stop depends on the way Volume control is added. 
If I'm testing flows with media (especially at the current volume) it's annoying I can't stop it and have to listen to the whole song.

**Comment by JohanKuster** [comment]
when I mute the sound I cannot listen to something else untill the song has stopped. I want to stop the music using a flow and immediately like to use the Homey and I don't like/want to wait for the music to stop. I still think there should be a stop

**Comment by Fire69** [comment]
@denelan, having a stop or a pause function shouldn't really make a difference for that.

@JohanKuster, how do you mute the sound??

@WeeJeWel, is there a voice command to stop the music?  And will Homey understand it when the music is playing?

**Comment by JohanKuster** [comment]
According to Emile the new voice control would let you mute the sound but it will probably mute all the sound and that's what I do not want. I only want the music to stop.

I wonder if Homey is able to hear anything when it is playing music ;-). You probably need a remote control to stop it. ;-)

**Comment by WeeJeWel** [comment]
Oh I get it. Just to go http://{yourhomeyip}/manager/media/ to control your music, and pause the music as well.

**Comment by denelan** [comment]
@WeeJeWel Hoi Emile. I did ifnd the media manager already, but there is no way to manipulate anything about the media playing (see attachments)
![schermafbeelding_021216_122953_pm](https://cloud.githubusercontent.com/assets/16791740/13005750/49166f1c-d184-11e5-893b-386bb0588ae4.jpg)
The pop up when clicking the volume button doesn't work.
![schermafbeelding_021216_123510_pm](https://cloud.githubusercontent.com/assets/16791740/13005834/06734e22-d185-11e5-84fa-6684d690ad34.jpg)
I use my smartphone to pauze the media
![screenshot_2016-02-12-12-30-55](https://cloud.githubusercontent.com/assets/16791740/13005840/157a3840-d185-11e5-88f1-a4bdcda97a5b.png)
Unfortunately the mobile app crashes a lot at the moment.

**Comment by JohanKuster** [comment]
so, will the STOP be available in the flow?

**Comment by WeeJeWel** [comment]
@denelan Just resize your browser :) What does crash, exactly?

**Comment by WeeJeWel** [comment]
@JohanKuster I still don't see a reason to implement both Pause AND Stop. Do you?

**Comment by JohanKuster** [comment]
Even I as a geek find it hard to use a pause as a stop when I want to stop the music. What about those non geeks, will they understand? Do you use the pause in stead off the stop in any other device you use?

**Comment by WeeJeWel** [comment]
Spotify doesn't have a stop button ;)

**Comment by JohanKuster** [comment]
Ah that's probably why I don't use it ;-)

**Comment by JohanKuster** [comment]
Too much effort to add the stop?

**Comment by denelan** [comment]
@WeeJeWel ok, it seems size does matter..... ;)  But you have to make it smaller, nog bigger (adjust the width.
No idea what crashed the app; it stops working (is the message) fairly often. I've send in feedback through the app a couple of times. (LG G2)

**Comment by WeeJeWel** [comment]
@JohanKuster If it doesn't add functionality, it shouldn't be there. Maybe when playlists are working I'll add something similar.
