### ISSUE TITLE
Lights switch on and switch off automatically 

### ISSUE THREAD

**Issue by bierre** [athombv/homey#651]
**What is your Homey version (Settings → System)?**

0.35

**What did you try to achieve?**

- use flow to switch on hue and 2 kaku lights based on motion detection by fibaro if time is between x and y

**What was the result?**

- lights switch on on motion
- after 2 secs they switch off again

**What did you expect as result?**

Light switch on on motion
Lights stay on

**Any other remarks**

I've done a complete honey reset in the morning.

**Comment by caseda** [comment]
Show is how you configured your flows. Without that information it is very hard to help, either by screenshot or written.

**Comment by bierre** [comment]
@caseda here's the screenshot.
![schermafbeelding 2016-05-27 om 13 22 10](https://cloud.githubusercontent.com/assets/18561525/15606678/099d0a58-240e-11e6-8693-bb1c29d202a2.png)

**Comment by caseda** [comment]
Do you got any other flows that involve these lights? Like for turning off the lights again.

**Comment by bierre** [comment]
No

**Comment by jeroenvollenbrock** [comment]
Do all the lights turn off again, or only the KaKu or Hue lights?

**Comment by bierre** [comment]
@jeroen this issue seems solved in 0.9.1

**Comment by nattlip** [comment]
then you can close it.
