### ISSUE TITLE
Switching to Dutch: Homey says 'I am Homey'

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#652]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Set the Homey to Dutch

*Please include detailed steps how we can reproduce the issue*
Change the language from English to Dutch. Or when it is in Dutch already, download a new Dutch voice.

**What was the result?**
Homey downloads the voice and then says 'i am Homey' (in Dutch)

**What did you expect as result?**
Homey to say 'Ik ben Homey'

**Comment by caseda** [comment]
Did you read what is stated behind the language selection: Dutch. 
I think it was something like, "Nog niet volledig vertaald".

**Comment by Tweake** [comment]
Just checked this with version 0.9.2 and Homey will say "Hallo, ik ben Homey" after a new Dutch voice has been added. If you are still experiencing the issue it will be fixed with an update soon.
