### ISSUE TITLE
Flow Card "Flow" Label's are in Dutch (with english setting)

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#653]
**What is your Homey version (Settings → System)?**

.35

The label of the Flow Card "Flow" is labeled in dutch.

![unbenannt](https://cloud.githubusercontent.com/assets/17235241/15524280/493f3f76-2221-11e6-896b-08d1567c54ff.png)

**Comment by Dijker** [comment]
Confirmed, strange.....

**Comment by WeeJeWel** [comment]
Oops. Fixed in 0.8.36
