### ISSUE TITLE
Feature request: serve static files

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#655]
**What did you try to achieve?**
Serve static files (html, images) from app.

It would be nice to be able to serve files from app folder or user data.

I suggest to serve following folders
`GET /app/appId` would serve app's `/app/public` folder
`GET /app/appId/userdata` would serve  `/userdata`folder

It would be also great if API would be able to server any content type (without writing it to disk).

References:
https://athomcommunity.slack.com/archives/apps/p1464114595000056
https://github.com/athombv/homey/issues/288#issuecomment-191924348

**Comment by WeeJeWel** [comment]
`/assets/` is mounted on `/app/com.app.id/assets/`, so that's already possible :-)

For server any content type, spawn your own `http` server. It's actually more resource-friendly than proxying the data through Homey.

**Comment by matjaz** [comment]
Cool!

I think there should be some authority for assigning ports. Or simply `process.env.HOMEY_HTTP_PORT`

**Comment by WeeJeWel** [comment]
https://www.npmjs.com/package/freeport will work fine. I can imagine using multiple ports :)

**Comment by matjaz** [comment]
What about static ports? If I need fixed address my server can be reached..

**Comment by WeeJeWel** [comment]
Because it's a shared environment we can't guarantee it'll work, but the chance that another app uses the same port it pretty small if you use a port >60000

**Comment by matjaz** [comment]
well.. Homey could reserve one port per app which would be always guaranteed to be the same. (app id)

**Comment by Dijker** [comment]
I already serve the homey-realtime-logpage from my Settings Page on a small development App. 

/app/[appname]/settings/homey-realtime-logpage.html

So I have the page always available if I want, regardless the development workstation ;-)

https://github.com/irritanterik/homey-realtime-logpage

**Comment by matjaz** [comment]
Cool. Wouldn't it be nicer to have just http://homey.local/app/realtime-logpage :)
