### ISSUE TITLE
Can not delete folder

### ISSUE THREAD

**Issue by Deentje** [athombv/homey#656]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

I want to delete a created folder named "flow" but this is not possible, there is no cross to delete it

![can not delete folder](https://cloud.githubusercontent.com/assets/19371484/15554902/8be408c0-22c6-11e6-98c2-d017a625d3ba.jpg)

I added a new folder through "add folder" button at the bottom, but afterwards it can not be deleted anymore

**What did you expect as result?**

Possibility to delete the folder

**Comment by freemann** [comment]
It's impossible to delete folders with child flows. 
Delete/move the flows from the folder and then you will be able to delete the folder.

**Comment by bvdbos** [comment]
If there's no flows or subfolders in the folder you can refresh the page. After that the delete-cross will appear.

**Comment by Deentje** [comment]
Nope there is no subflow in, see picture above. When subflow is in they are more to the right side shifted (as you can see under Woonkamer Licht)

**Comment by Deentje** [comment]
mmmm just noticed when you leave the flow tab and go to the settings or insights tab and then back to flow tab then the cross appeared again. So issue looks to be solved again. May bee minor bug somewhere in the code

**Comment by Deentje** [comment]
Just found out how the error occurs. 
When you create a new folder and create another new folder in that one. Next you move the 2nd created new folder back to the main folder list. When you do that the 1st created new folder does not contain a cross which can be removed. When you then go to another tab (for example devices or insights) and go back to flow you can remove it again.

**Comment by Arjanvde** [comment]
This is an old one, but it still persists on 0.10.3. (think some people are going to mention this.)

If you remove all flows from the folder and refresh the page you should be able to do so.

**Comment by WeeJeWel** [comment]
Fixed in 1.3.0
