### ISSUE TITLE
Second invited user can't log in on the app

### ISSUE THREAD

**Issue by btwvince** [athombv/homey#657]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

I made a second user to log in on the app
![naamloos](https://cloud.githubusercontent.com/assets/19223618/15589294/81d61fe0-2392-11e6-9429-c0ce2535a715.png)

**What was the result?**
This user can log in on my.athom.com but get invalid credentials in the Homey app on Android
![knipsel](https://cloud.githubusercontent.com/assets/19223618/15589308/96a54e00-2392-11e6-95f8-5de8256035c4.PNG)

![screenshot_20160526-223845](https://cloud.githubusercontent.com/assets/19223618/15589385/e9beeab0-2392-11e6-817c-ae365f335e50.png)

...

**What did you expect as result?**
That all users I add will be able to log in on the app so I can use "that user came home" for example
...

**Any other remarks**

...

**Comment by Dijker** [comment]
There was some normalization on gmail accounts. 
(https://github.com/athombv/homey/search?q=gmail+&type=Issues&utf8=%E2%9C%93 )
they removed that, but my Login working on the myAthom website  my.athom.com with capitals doesn't work on the mobile. Just type it in the app as lower case. That works for me.

**Comment by btwvince** [comment]
My account (owner) is Gmail and works like charm but the second account is Hotmail (user).
It all works when I log in on my.athom but not in the app, I tried everything with and without capitals.
I think there is something going wrong with the query that checks the second user in the app

**Comment by btwvince** [comment]
Still having the same problem, is there already anyone who's working on this?

**Comment by goldenice** [comment]
@btwvince I think this might have something to do with special characters in e-mail addresses. Does the e-mail address of Jessica contain special characters (anything other than letters or numbers, like dots, plusses or dashes?). If it does, that issue should be fixed from 2.2.4 on Android and 1.1 on iOS. If not, we'll have to investigate further.

**Comment by btwvince** [comment]
@goldenice Thanks for the answer. Her emailadres is zissica85@hotmail.com so nothing special I guess

**Comment by goldenice** [comment]
Hey @btwvince, does this issue still occur with the latest app version? Should've been fixed some time ago, and I'd love to be able to close this issue ofcourse ;)

**Comment by btwvince** [comment]
Yes :D i've just tried it again and it works! Thank you :-)
