### ISSUE TITLE
[Suggestion] More extensive search in flows

### ISSUE THREAD

**Issue by kruimel0** [athombv/homey#658]
I would like a more extensive search in flows, most importantly an option to search for a (Better Logic) variable, and let it show all flows with that variable, or for a certain device, and let it show all flows with that device.

**Comment by WeeJeWel** [comment]
As of 1.3.0, searching in Flows will include Flow's device names, argument values and card App/Manager names.

Tokens are not supported as searching them is a too much performance loss.
