### ISSUE TITLE
LED Ring color wheel unclickable (0.8.17) on Windows Chrome 48.0.2564.109m

### ISSUE THREAD

**Issue by coldshivery** [athombv/homey#66]
Cannot change the color using the color wheel, clicking on the wheel does nothing.
Using Windows 8.1 and **Chrome v48.0.2564.109m**

##### Reproduce:
* Create a flow
* Drag LED Ring to 'then'
* Click the color block to change color
* Click anywhere in the color wheel. It does not respond to any clicks.

**Comment by Qx5** [comment]
Same here with windows 10 and same chrome version.

**Comment by Dijker** [comment]
Same her on Windows 10 / Chrome 48.0.2564.103 m (First try, did not see it working before...)

**Comment by petergab94** [comment]
Same her on Windows 10 / Chrome 48.0.2564.103 m

**Comment by sjefke39** [comment]
- Cancel button does not work.
- Icon in the upper left corner (color wheel / form) is almost invisible.
- Color wheel does work with Firefox 45.0b8 and Edge 25.10586.0.0 on Windows 10 (unsupported browsers).

**Comment by WeeJeWel** [comment]
Fixed in 0.8.19
