### ISSUE TITLE
Android app at Samsung tablet P3110

### ISSUE THREAD

**Issue by Posbank** [athombv/homey#661]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

Was able to install Homey Android app (v 2.1 build 45) at Samsung tablet P3110 (Android v4.2.2).
The app is going to start up and shows all the zones and devices for a few seconds. Then the app spontaneously stops running and shows "Homey stops, send reporting?"

**What did you expect as result?**

According to different issues at Forum it should be possible to have the app Android working at v4.2.2

**Any other remarks**

the app is working fine at different phones and my ipad
the tablet is installed at the same WiFi-network as Homey (and the other devices)

**Comment by freemann** [comment]
Tablets are not officially supported (yet).

App crashing is a known issue;
https://forum.athom.com/discussion/558/official-homey-android-app-discussion-topic#latest

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by Posbank** [comment]
I didnot try again recently.
I'll check in a few days and let you know the results.

Greetz, Jan

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen this issue if the problem persists.
