### ISSUE TITLE
Send a push notification to iOS app doesn't work

### ISSUE THREAD

**Issue by Robinyoh** [athombv/homey#662]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Send a push notification to my iPhone. 

*Please include detailed steps how we can reproduce the issue*
Make a flow to send a push notification.

**What was the result?**
Couldn't find my device.

**What did you expect as result?**
To find my device.

**Any other remarks**
![schermafbeelding 2016-05-28 om 15 51 41](https://cloud.githubusercontent.com/assets/18645811/15627699/7d3e7030-24ec-11e6-8c30-fb5dbfec5960.png)

...

**Comment by 2benl** [comment]
It is confirmed that messages on iOS don't work yet. See the forum on forum.athom.com

**Comment by markaswift** [comment]
Hoping for this and geofencing / presence to be added ASAP.

**Comment by jeroenvollenbrock** [comment]
iOS 1.2.1 has been submitted to apple for review containing a fix.

**Comment by jeroenvollenbrock** [comment]
@Robinyoh: Can you confirm Homey App version 1.2.1 fixes this issue?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen this issue if the problem persists.
