### ISSUE TITLE
[KAKU][FeatureRequest] Separate Devices Doorbell Button, Doorbell and combination

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#663]
**What is your Homey version (Settings → System)?**
0.8.35 / KAKU App 1.1.3

**What did you try to achieve?**
Add the doorbell Button and the Doorbell self as separate devices

*Please include detailed steps how we can reproduce the issue*
I want Homey to generate a new (random) signal to signal the Doorbell
and use the pushbutton to trigger something else...

**What was the result?**
Current you add a doorbell by learning Homey the signal of the pushbutton, .
So the setup I want is not possible or only by workaround (learning the Doorbell to react on Homey Socket Card and adding te doorbell separately.)

**What did you expect as result?**
Add  KAKU - DoorBell -> 
Choose: 
- Pushbutton (ACDB-7000 A/B)
- Doorbel (ADCB-6600C / 7000C)
- Combination (Current Situation)

http://www.klikaanklikuit.nl/shop/nl/producten/draadloze-deurbellen/ 

**Any other remarks**
nope.

**Comment by BasKiers** [comment]
Doorbell can now be assigned to a random signal (as of KaKu v2.x). For now there are no plans to add the doorbell as a individual device, but you can pair the button as a second doorbell and name it "button" which you can then use in your flows.
