### ISSUE TITLE
feature request , if 433 chip is offline some bubbling up of his state to the frontend of homey.

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#665]
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

sending 433 signals with 433 chip. Homey gives no notice at all if chip works. 

*Please include detailed steps how we can reproduce the issue*

speaks for itself 

**What was the result?**

no sending 433 signals . 
...

**What did you expect as result?**

some fault code in the homey log that the chip is offline in cli athom.
...

**Any other remarks**

it would be nice if the chip could be reset without homey cold reboot
...

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0

**Comment by nattlip** [comment]
Outlook voor Android downloaden






On Fri, Jul 29, 2016 at 4:31 PM +0200, "Jeroen Vollenbrock" <notifications@github.com> wrote:





Closed #665.

---
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/athombv/homey/issues/665#event-739264268
