### ISSUE TITLE
Homey is offline (or crashes) several times a day 

### ISSUE THREAD

**Issue by djefmo** [athombv/homey#666]
**What is your Homey version (Settings → System)?**

**0.8.35**

**What did you try to achieve?**

Just work with Homey

*Please include detailed steps how we can reproduce the issue*

Homey is offline (or crashes) a few times a day. It became worse after updating to 0.8.32 and is not solved in 0.8.35. I can't tell at which moments Homey goes offline. 

**What was the result?**

Only Z-wave modules (Fibaro Relay Switch, Fibaro Dimmer, Wall Plug, and two motion sensors) and Philips HUE lights are installed. 

**What did you expect as result?**

Not so many crashes. Isnt't it possible that Homey restarts automatically when it crashes? 

**Any other remarks**

It's both offline within my own Wifi network and from an external computer

**Comment by freemann** [comment]
Did you do a search on open issues? 
Wild guess is that there are 5+ tickets open which covers this issue.
