### ISSUE TITLE
Figaro motion sensor loses connection

### ISSUE THREAD

**Issue by HuubNabben** [athombv/homey#667]
Hi 

Information:
Homey Firmware Version: 0.8.35
Athom Cloud ID: 56d83b7fa112c5565bd97177

**What did you try to achieve?**
Connecting the fibaro motion sensor

*Please include detailed steps how we can reproduce the issue*

Step one: 
   - including the sensor by adding a device, selecting z-wave, interview takes place.
     After the message appears that the device in secured linked to the netwerk the screen appears
     to change the name of the sensor. Than I change the name.
  - next i test the sensor by selecting the sensor and it chows the details.
       * lux
       * temparture
 - next time i select the device, all contact is lost and it is not possible to check the details again.

The steps above can be repeated and the same happens time and time again.

**Comment by caseda** [comment]
Have you tried to reboot homey? (by disconnecting the power and then connecting the power again)
