### ISSUE TITLE
reboot loses apps in 0.8.36

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#669]
**What is your Homey version (Settings → System)?**
0.8.36

**What did you try to achieve?**
reboot Homey

*Please include detailed steps how we can reproduce the issue*
Install app through CLI, save settings (i.e. WU). Make sure everything works. Reboot Homey : app is not showing anymore. 

After a reinstall settings are lost (WU) but device-settings (smile-master in my case) are preserved after a reinstall.

**Comment by nattlip** [comment]
indeed very bad new feature. devices ain't deleted but app settings are.

**Comment by RoadXY** [comment]
When debugging an app I like to have my app run for several days in order to test.
If an reboot means I have to start over again...

**Comment by irritanterik** [comment]
this applies to both `athom project --run` and `athom project --install` 
Very bad! Only apps from the app store will survive a reboot.

**Comment by markaswift** [comment]
Yes, hopefully they can hotfix this? It's very annoying. That said, generally 0.36 is much BETTER!

**Comment by WeeJeWel** [comment]
Yep, this is a bug. Will be fixed in 0.8.37!
