### ISSUE TITLE
reboot duplicates apps in settings

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#670]
**What is your Homey version (Settings → System)?**
0.8.36

**What did you try to achieve?**
reboot Homey with apps installed through CLI

*Please include detailed steps how we can reproduce the issue*
Install app through CLI. Reboot Homey : entry app-settings are duplicated in menu
![2016-06-04 08_54_53-homey settings](https://cloud.githubusercontent.com/assets/1064079/15798236/0b1b999c-2a32-11e6-95b2-8fd842630e4b.png)

After another reboot the settings-menu shows fine.

**Comment by bvdbos** [comment]
Doesn't happen all the time but when this happens Lifx (which is the last app on the screen) always shows a crash. As said, a reboot solves this.

**Comment by bvdbos** [comment]
This is reproducible with installing two apps from CLI for me. The error thrown by Lifx / last installed app:
```Stack trace:
RangeError: Port should be > 0 and < 65536
at Socket.send (dgram.js:278:11)
at Client.sendingProcess (/node_modules/node-lifx/lib/lifx/client.js:183:19)
at wrapper [as _onTimeout] (timers.js:275:11)
at Timer.listOnTimeout (timers.js:92:15)```

**Comment by WeeJeWel** [comment]
I cannot seem to reproduce this. Does anyone have steps that can?

**Comment by Arjanvde** [comment]
I had this after the update! A reboot fixed the issue.

I had 2 apps installed through the CLI (Action app and my own App). After updating from 0.8.35 to 0.8.36 the apps installed throught the CLI where gone and the Apps Slack and Soundboard where duplicated. A Reboot fixed the duplicated settings.

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/24487/#Comment_24487
https://forum.athom.com/discussion/comment/24508/#Comment_24508

Duplication is easily reproducible, except perhaps for the error in the last app...

**Comment by RoadXY** [comment]
Not happening to me since 0.8.39
