### ISSUE TITLE
it isnt documented which plug to use for other power inlet on Homey

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#671]
**What is your Homey version (Settings → System)?**

0.8.36

**What did you try to achieve?**

use the other power plug of homey

*Please include detailed steps how we can reproduce the issue*

i have a lot of power supplies lying around with 5 volt dc but they don't fit. What i have as male plug is hollow in the middle.

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by bvdbos** [comment]
Other power-inlet? That's a line-out....

**Comment by nattlip** [comment]
could be ,it looks like a audio plug inlet, but can homey get enough power from a computer, if i remem ber right, in the beginning athom said you shoudnt use the usb power of a computer ?

**Comment by bvdbos** [comment]
about 2,5-3,5 watt according to plugwise source. With USB2 the specs are 5V - 900 mA -> 4,5 W for superspeed devices : https://en.wikipedia.org/wiki/USB#Power

**Comment by nattlip** [comment]
but my homey uses 7 watt with ledring on according to plugwise.

**Comment by bvdbos** [comment]
5 W when booting for me. It'll probably adjust speed when there's low power?

**Comment by nattlip** [comment]
or my plugwise circle isnt correct, i will test it.  i saw your 2 watt in the past , i only have to watt with ledring off.

**Comment by bvdbos** [comment]
My ledring is off too...

**Comment by nattlip** [comment]
okey, but i love led and moving led rings

**Comment by bvdbos** [comment]
I tried with a headphone but it didn't have a straight plug-cable so couldn't plug in in far enough. I noticed Homey's voice went silent but didn't hear Homey counting down to zero. Going to do a reinstall now :-)

**Comment by WeeJeWel** [comment]
Sorry, but using an alternative power supply is not supported.
