### ISSUE TITLE
Updating to 0.8.36 brakes elro devices

### ISSUE THREAD

**Issue by fn002449** [athombv/homey#673]
**What is your Homey version (Settings → System)?**
0.8.36

**What did you try to achieve?**
Update from 0.8.35. After that the ELRO (sockets) devices do not work.

I'm in version 0.8.36. Added a ELRO socket. If I want to switch on the socket it doesn't go on.

*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The gui shows that the socket went on but it wasn't.

**What did you expect as result?**

The socket to go on.

**Any other remarks**

I tried to remove the app and re-add. But now I cannot pair any socket. It will not recognise it when I push a button on the remote while pairing.

**Comment by nattlip** [comment]
i added two elro sockets in 0.8.36. old ones no problem.

**Comment by fn002449** [comment]
I pulled the power cord and it is fixed :S

**Comment by nattlip** [comment]
of homey i think. but still in 0.8.36 if it is true you say , all the apps have problems with devices they already should have.

**Comment by fn002449** [comment]
@nattlip Jep of homey (changed my post)

**Comment by WeeJeWel** [comment]
Pretty odd. Can you close this issue if it's fixed now?

**Comment by bvdbos** [comment]
probably the 433 radio crashed, a cold reboot works for this.

**Comment by Arjanvde** [comment]
Had the same issue that after all 433mhz communication was blocked, did a check with the Code Checker in the KaKu app and no code's where displayed when I pressed a button on me KaKu remote. A cold reboot (pulled the plug) fixed this issue.

**Comment by Inversion-NL** [comment]
Yes, the Somfy app also stopped working. Had to power cycle Homey to get 433MHz working again.
Also on firmware v0.8.36

**Comment by bvdbos** [comment]
looking at the scheme in [the blog-post](https://blog.athom.com/2016/04/17/a-technical-introduction-homey/#more-25), perhaps a cold reboot won't be necessary, restart Z-wave could also work?
