### ISSUE TITLE
Fibaro Relay doesn't work any more

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#675]
**What is your Homey version (Settings → System)?**

0.8.36

**What did you try to achieve?**

My Fibaro Relay doesn''t work any more since 0.8.36, It worked a little bit on 0.8.35 but is completely non-functional on 0.8.36. I've used the relay since 0.8.20 without any issues but it doesn't work any more. (i've got no polling settings entered, not sure what those values would be).

Could this issue be related to the Custom Flow Cards?

This is the error message given.

![image1](https://cloud.githubusercontent.com/assets/17526110/15816210/10789362-2bd2-11e6-8676-7e34fd4f58aa.jpg)

**What was the result?**

Non working Z-Wave device.

**What did you expect as result?**

The Z-Wave device to work.

**Comment by Fire69** [comment]
Have you tried removing/adding it?
I have this relay also, and no problems with .36

**Comment by Arjanvde** [comment]
Fixed with repairing.
