### ISSUE TITLE
Wemo Insight stops reporting power usage

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#678]
**What is your Homey version (Settings → System)?**

.36

**What did you try to achieve?**

Recording of Wemo Insight data.

**What was the result?**

Data stops being reported after sometime... Switch still responds to on off commands throughout.

**What did you expect as result?**

Constant data!

**Comment by BasKiers** [comment]
This issue should be fixed along with issue #985. Please comment in that issue if you still experience problems. Thank you for the bug report!
