### ISSUE TITLE
Error removing app

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#679]
**What is your Homey version (Settings → System)?**

0.8.36

**What did you try to achieve?**
I tried removing the Wheater Underground app in order to re install it

*Please include detailed steps how we can reproduce the issue*
Go to System - Apps and clicked the Remove button.

**What was the result?**
An error:
![removeapperror](https://cloud.githubusercontent.com/assets/16610696/15961122/5c744b56-2f03-11e6-8548-fa85717f6829.png)

I've send in a log: 02C2B2CA81

**What did you expect as result?**
No error, the app to be removed

**Any other remarks**

After clicking Ok in the error dialog the app was still there, it took a minute or so to disappear

**Comment by WeeJeWel** [comment]
That dialog only appears when clicking the red triangle. Maybe you mis-clicked?
