### ISSUE TITLE
Bluetooth pair: undefined is not a function

### ISSUE THREAD

**Issue by edwinv** [athombv/homey#68]
- On http://192.168.2.11/manager/zones/ click the plus button
- Choose "Homey" > "Bluetooth"
- Error message "Undefined is not a function" is displayed

![homey_zones___devices](https://cloud.githubusercontent.com/assets/563294/12962129/5c2bcc50-d044-11e5-8b04-1a4906e7e950.png)

- JS console reports a 500 error from an AJAX call:

```
POST http://192.168.2.11/api/manager/drivers/pair/start?_=1455139140952 500 (Internal Server Error)
```

**Comment by lvanderree** [comment]
+1

**Comment by Fire69** [comment]
+1

**Comment by denelan** [comment]
+1

**Comment by WernerHel** [comment]
+1

**Comment by goldenice** [comment]
Oops, we forgot to disable that. We're actually still working on proper bluetooth audio support. We have an experimental version working, but @jeroenvollenbrock is currently writing a badass audio driver which makes audio management way better. (Allows for readjusting the volume of Homeys voice, sound 'ducking, so when you play music, the sound dims when Homey talks etc.)

Sorry this is currently broken, we're working on it...

**Comment by WeeJeWel** [comment]
Bluetooth support will be enabled later. 0.8.18 hides bluetooth.
