### ISSUE TITLE
Speech gps-trace not through phone

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#681]
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**

Get speech back through my phone

*Please include detailed steps how we can reproduce the issue*

I have a flow that uses the gps-trace app.  I can ask "where is my car" and it says the address.

**What was the result?**

When I use my phone to ask the gps-trace app where my car is, the answer comes through Homey instead of my phone.

**What did you expect as result?**

Speech through the app instead of Homey

**Any other remarks**

...

**Comment by bvdbos** [comment]
This is an issue for the GPS-trace app. On line 394 it should add the speech-session:
Homey.manager('speech-output').say(result,{ session: speech.session });

**Comment by Fire69** [comment]
I figured it could be something like that right after opening the issue :/
I'll contact the dev about this.

Thanks
