### ISSUE TITLE
Homey's white ring of silence leads to freeze up

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#684]
**What is your Homey version (Settings → System)?**
0.8.38

**What did you try to achieve?**
Execute a flow with a voice command and see if the issue of the white ring of silence was solved with 0.8.38. This issue is described here: https://github.com/athombv/homey/issues/498#issuecomment-221568934

**Please include detailed steps how we can reproduce the issue**
Find a Homey that has trouble with the speech to text recognition service and which does not do any speech to text (not even misinterpretation) and try some voice commands. And wait until the issue as described below occurs.

**What was the result?**
Usually with the white ring of silence issue Homey just shows the white ring for 10 seconds and then goes on as if nothing has happened (no speech-input). This time the white ring of silence spinned for about a minute. During this time Homey was not reachable trough the webinterface. After the white ring had ended I could reach Homey again but it was sluggish and loadavg was around 1.8 (which usually is below 1). I tried sending a log but the request kept pending until it timed out and a pop-up with the message TRUE was shown instead of a log id. Also the notification icon that Homey was not connected to the Athom cloud appeared during this time but I was able to reach my Homey through my.athom.com though.

**What did you expect as result?**
A result of the speech to text would be the best result but as long as this is not fixed I would at least expect Homey not to freeze up after a voice command. 

**Any other remarks**
-
...

**Comment by bvdbos** [comment]
This seems to point at a bad connection to the athom servers (but you know that already). I wonder, if you alter your login or password, would that refresh credentials among the servers? Perhaps it's even enough to logout and login? Wild guess, I can also imagine you might lose contact with your Homey?

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0
