### ISSUE TITLE
Aldi app recognizes only button 1

### ISSUE THREAD

**Issue by matjaz** [athombv/homey#685]
When I start pairing/add new device I can add only button 1 (on/off). other buttons are not recognised by wizard.
I have modified action app and using following signal all 5 buttons are working flawlessly.

```
signal = new Signal({
    sof: [],
    eof: [3000],
    words: [
        [300, 1100], // 0
        [1100, 300]  // 1
    ],
    interval: 7000,
    repetitions: 4,
    sensitivity: 0.2,
    minimalLength: 24,
    maximalLength: 24
})
```

This is for remote GT-9000. I suggest to rename driver in Aldi app.

@Dennishacq 
Quigg GT-1000 (and many others) protocol can be found here: 
https://github.com/pilight/pilight/blob/master/libs/pilight/protocols/433.92/quigg_gt1000.c

**Comment by DieterKoblenz** [comment]
Same issue here with the GT-1000 remote.

**Comment by bvdbos** [comment]
Does this still happen?

**Comment by BasKiers** [comment]
Hi,

We do no longer have the hardware at the office. This is why this issue was never picked up. I've changed the signal to the one you mentioned and deployed it in v1.1.2. I hope this fixes your problem but I am unable to test this. Could your verify that this fix works?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
