### ISSUE TITLE
Homey Api changes and apps crash in 0.8.38

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#687]
**What is your Homey version (Settings → System)?**

0.8.38

Summary Week 23 (June 6 - June 10)  : api changes but no info or documentation off what changes. 

mentioned is all athom apps are being converted but how must the other developers convert their apps ?

**Comment by matjaz** [comment]
It says "our apps". maybe some internal api.

**Comment by nattlip** [comment]
https://athomcommunity.slack.com/archives/developers/p1465848728000049

**Comment by nattlip** [comment]
https://athomcommunity.slack.com/archives/developers/p1465848728000049


from @WeeJeWel  :Basically the docs didn't change

[10:12]  
It's just that the device_data object must be passed completely

[10:12]  
Some of our own apps only passed { id: ... }

**Comment by bvdbos** [comment]
It's "just that....". I suggest not to throw any API-changes over the fence and then leave for the weekend... At least let us know what changed so we know where to fix this....

**Comment by WeeJeWel** [comment]
It's not an api change as it has been documented that way since the
beginning :)

**Comment by matjaz** [comment]
https://developers.athom.com/library/flow/devices/
so should device_data be **the same** object or equal/like?

**Comment by WeeJeWel** [comment]
@matjaz, exactly the same, everywhere
