### ISSUE TITLE
Kaku dead after update app to 1.1.4

### ISSUE THREAD

**Issue by dhanstede** [athombv/homey#688]
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**

Turn lights on and off with kaku socket

**What was the result?**

nothing.

**What did you expect as result?**

kaku socket switch lights on and off

**Any other remarks**

Also dead after power cycle homey.

**Comment by posthok** [comment]
I needed a reboot after updating. But then again kaku still don't trigger in a flow.
Think this is a duplicate a issue 682

**Comment by BasPost** [comment]
Same here,
All my KaKu modules stopped working after the update 1.1.4 on 0.8.38 last night. I can't send any on/off commands.
Everything worked fine before update. I disabled and enabled the app, reboot and powercycle, but issue remains

**Comment by dhanstede** [comment]
Woooohoow! After kaku app updated to 1.1.5 my kaku sockets works again. Thank you for the quick fix.
