### ISSUE TITLE
Android App: Push message has no audible signal

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#69]
The receival of a Homey push message on android has no audible signal, so it's only noticed when the screen is active.

**Comment by lvanderree** [comment]
+1

**Comment by goldenice** [comment]
Wow, and I had thought of everything. I always put my phone on silent, so I never noticed this before. Good point! Will put this in the app, although I'm not sure yet when I'll get around to it.

**Comment by irritanterik** [comment]
Thanks and no problem. Can you also add vibration as an option?
Realy supercool would be to set these options flow-side (sound, vibrate) like is possible with the Pushover API. So I hear a 'gong' when someone is at the door and a 'sirene' when a smoke detector reports an alarm.

**Comment by goldenice** [comment]
Was implemented, will improve further on version 2+ of the app. Closing this one for now.
