### ISSUE TITLE
Homey freeze with rainbow light

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#690]
**What is your Homey version (Settings → System)?**

.34 - .38

**What did you try to achieve?**

Similar to my previous issue #442 Homey freezes from time to time (usaually once a day).
If this happens I am not able to connect nor do voice commands. After a powercycle everything works again.

This issue occurs when homey is not in use. I never saw the moment when homey freezes.

Because issue #442 is gone for me, but this seems to fill the same "spot" I guess it could have the same reason and only changed its symptoms.

I saw other users complaining about this issue on patch .34 but I haven't seen any complaints after that patch. For me this issue is still persistent.

**Comment by WeeJeWel** [comment]
Well, damnit. Can you post a screenshot of Settings -> System with 'Show stuff for geeks' open, and the data usage visible?

**Comment by peaoo** [comment]
![image](https://cloud.githubusercontent.com/assets/17235241/16114101/c51c2726-33bf-11e6-9685-064f678070bf.png)


No freeze today. Maybe when I am back home.

**Comment by btwvince** [comment]
I have the same problem that Homey freezes everytime i press the reboot button on my.athom

**Comment by peaoo** [comment]
My Homey just freeze. I took 2 screenshots, the last one 1 hour before the freeze.

16.6. 17:06
![1706](https://cloud.githubusercontent.com/assets/17235241/16137872/038b66fc-3438-11e6-88e4-227ee90853a5.png)

17.6. 2:17
![217 17 06](https://cloud.githubusercontent.com/assets/17235241/16137874/17a81162-3438-11e6-9385-b99410971c76.png)

3:00 Freeze

**Comment by peaoo** [comment]
I realised that some Z-Wave devices are losing connection before the last freeze this night. One of my fibaro plugs displayed an Error 20 mins before the static rainbow occured.

**Comment by peaoo** [comment]
I had Homey running without any freeze for about 3 days. Then I used my android Homey app to check my sensors. After 3-4 hours homey froze with the static rainbow.
I don't know if there is a relation between using the App and the freeze, but I will test it again.

**Comment by peaoo** [comment]
A brief update:
My theory that the android app is related to this problem has been proven wrong.
Even better: I had no freeze since 5 days.
But I can remember this situation with my #442 error the last time. I had nearly a daily freeze but suddently it was all good the last few days (week) before the update. 

I will wait for the next update and share my experiences.

**Comment by peaoo** [comment]
Just freezed again with static rainbow, after 5 days without any issue.

**Comment by jeroenvollenbrock** [comment]
Duplicate of #439

**Comment by jeroenvollenbrock** [comment]
Fixed in 0.9.0

**Comment by peaoo** [comment]
Thanks, haven't had a freeze yet. The system seems a lot more stable now, and I am confident that there will no freezes again. if i am wrong I will report it here.
Thanks for this great update!
