### ISSUE TITLE
Avatar missing once setup

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#693]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

I've set up an avatar at the my.athom site under my profile. Once I login on my page the avatar is shown correctly. When i click the image, to continue the avatar disseapears and the default avatar is shown.

Avatar is Shown
![avatar](https://cloud.githubusercontent.com/assets/17526110/16232802/3ad75d04-37cc-11e6-8e07-2de98ef3a8cb.jpg)

Avatar is gone.
![avatar missing](https://cloud.githubusercontent.com/assets/17526110/16232803/3adb5b98-37cc-11e6-9abb-241bb7a5391f.jpg)

**What was the result?**

Avatar is missing.

**Comment by philsniff** [comment]
indeed! same here

**Comment by Arjanvde** [comment]
Little update, fiddled a bit around with the code in Chrome, the idea is this:

![untitled](https://cloud.githubusercontent.com/assets/17526110/16233510/ec02b428-37ce-11e6-8584-e32b63253ae3.jpg)

Should be fairly easy to fix, has something to do with this part of the code i guess.

<img class="icon ng-scope" ng-if="user.athom_id" ng-src="https://avatars.athom.com/default/medium.jpg" src="https://avatars.athom.com/default/medium.jpg">

**Comment by jeroenvollenbrock** [comment]
@weejewel This issue occurs when the user had no avatar set during setup and changes the avatar later. The url is not synced properly.

**Comment by philsniff** [comment]
will this be fixed soon? because that is my problem and it is not fixed now in 0 .10.1!

**Comment by WeeJeWel** [comment]
Fixed in 0.10.2

**Comment by Arjanvde** [comment]
Nice! Can't test it myself unfortunately, hopefully @philsniff can confirm if this is solved 😄

**Comment by philsniff** [comment]
I will let you know guys! Thank you again!

**Comment by Dijker** [comment]
I had this problem also, it is fixed in 0.10.2 for my welcome screen and in the notification center !

**Comment by philsniff** [comment]
cool, i will update in the evening! thx for feedback

**Comment by Arjanvde** [comment]
Since @Dijker says it is solved I will close this issue for now. If it still persists I will open it again.
