### ISSUE TITLE
Custom capability not working in (mobile) device card

### ISSUE THREAD

**Issue by swttt** [athombv/homey#698]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Display my custom capability info in the (mobile) device card.

**What was the result?**

Nothing is being displayed except the app icon on the left side.

**What did you expect as result?**

Custom capability title, data (in my case download_speed) and units (MB/s) on the right side of the device card.

**Any other remarks**

No documentation or not possible to add an icon for the custom capability (like download speed icon), see https://github.com/athombv/homey/issues/699

**Comment by WeeJeWel** [comment]
Fixed in 0.9.0
