### ISSUE TITLE
Not able to set an icon for custom capability

### ISSUE THREAD

**Issue by swttt** [athombv/homey#699]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Add an icon to my custom capability for the device card.
Like the thunder icon on a card with the capability power_usage.

**What was the result?**

Not possible? No documention. (Did found some code in the Hue app, but couldn't get it to work)

**What did you expect as result?**

Add icon to custom capability during device pair.

**Any other remarks**

None

**Comment by WeeJeWel** [comment]
Fixed in 0.9.2.

```
"mobile": [
	{
		"id": "sensor",
		"capabilities": [ "my_capability" ],
		"options": {
			"icons": {
				"my_capability": "/path/to/my/icon/relative/to/app/root.svg"
			}
		}
	}
]
```

**Comment by swttt** [comment]
Great job <33

**Comment by gruijter** [comment]
Damn, This took me a long time to find out that @weejewel made a mistake (or was incomplete) with his code example! He forgot to put "components" in there. Below the code that finally worked for me:

```      "mobile": {
        "components": [
        {
            "id": "sensor",
            "capabilities": [
              "measure_power",
              "meter_offPeak",
              "measure_gas",
              "meter_power",
              "meter_gas"
            ],
            "options": {
              "icons": {
                  "measure_gas": "./drivers/smilep1/assets/images/gas_icon.svg",
                  "meter_offPeak": "./drivers/smilep1/assets/images/offPeak_icon.svg"
              }
            }
          }
        ]
      },
```

**Comment by WeeJeWel** [comment]
Whoops, sorry!
