### ISSUE TITLE
Sometimes Homey freezes just before talking, led ring keeps yellow/orange

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/homey#7]

**Comment by athomey** [comment]
This morning Homey was hanging, the ring was full-rainbow, but not moving. Going to browserpage of Homey I get: This webpage is not available ERR_CONNECTION_REFUSED   It was 100% sure not talking, for I do not use that and it was at night. (Few days ago I had a full orange ring, same hanging, also during the night.)  Is it the same bug als your freeze-orange-ring-talk bug, or do you want me to create a new issue in Github?

**Comment by WeeJeWel** [comment]
That's probably the same; thanks for reporting!

**Comment by jeroenvollenbrock** [comment]
I've traced the origins of this issue to a deadlock in a kernel driver. It may take a while before i can push out a fix though, due to the huge set of tests i'll have to conduct before i can ship a new kernel.

**Comment by freemann** [comment]
@jeroenvollenbrock;
Whoops! Sounds like a big delay! 

"It may take a while", is that;
8 hours, 2 days, 1 (working) week, 1 month or ?

**Comment by jeroenvollenbrock** [comment]
That depends entirely on the approach. We use this kernel driver to control the ledring, but the ledring can also be controlled from userspace. I've created a temporary fix that uses this approach, while i work on a newer kernel driver. The temporary fix should be included in one of the next updates.

**Comment by freemann** [comment]
It's not a answer to my question. But if there's a temp. fix, then it doesn't matter :smile:

**Comment by WeeJeWel** [comment]
Fixed in 0.8.11
