### ISSUE TITLE
Signup on accounts.athom.com: create extra user on variant of e-mail address is not possible

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#70]
I would like to create an extra user for use on our tablet. This way i can send push messages to this specific user (and thus tablet). Using a gmail alias for this is not possible:
My primary gmail account is like myname@gmail.com. But registrating with alias myname+tablet@gmail.com is not allowed. This message appears:

> A user with the email address myname+tablet@gmail.com already exist.

**Comment by goldenice** [comment]
So, if I understand correctly, this problem is solved when you have the ability to not only send a push notification to a specific user, but also to a specific device?

**Comment by irritanterik** [comment]
Deels. Mijn oorspronkelijke doel kan ik dan bereiken. Maar het blijft dan
onmogelijk om alias accounts aan te maken voor bijvoorbeeld huisgenoten of
kinderen.

**Comment by goldenice** [comment]
True, however, they can use their own e-mailaddresses right? 

Anyhow, for the issue of creating multiple account with e-mail aliases, @WeeJeWel or @joachimroeleveld can probably tell you more ;)

**Comment by joachimroeleveld** [comment]
That is correct and by design unfortunately; we do this to prevent spammers from creating lots of account by using email aliases, which is possible for, among others, Gmail addresses. I'm afraid you will have to use different email addresses for that.

**Comment by Dijker** [comment]
@joachimroeleveld 
Today I was surprised by an variant of this:
I invited my girlfriend F.Lastname at gmail dot com to my Homey. 
She registered at https://my.athom.com with het email address, 
without notification the registration process removed the dot from her email name. 
(First I expected a typo during the registration: 
GF upset: No I KNOW how to type my email !!!)

and then:
![image](https://cloud.githubusercontent.com/assets/12412734/13156154/603f2aba-d681-11e5-83e5-e7c528a448ff.png)

I guess you removed the dot for the same reason, but I like the name the way I (we) type it F.Lastname@   not flastname@ 

(and yes, I also sometimes use the moving dot to test with different accounts ;-) )

Anyway, if Athom thinks they have to remove it, 
pls display a warning what/why you change anything, and be consequent:  
Sent the invitation also to the modified address to prevent that invitations send wil not work.

And I would realy like it the way I see it in the Users panel on the Homey: 
Case (and DOT) preserving but case-insensitive (and dot insensitive on gmail to prevent multiple accounts on one mailbox )

Regards, Geurt

**Comment by Dijker** [comment]
Strange, 
for my GF on the Homey flastname@ is registered with F.Lastname@  (with dot) "Waiting for confirmation...." 
I tested it again and had both pending but now F.Lastname2@ (with dot) is registered with  FLastname2@ "Waiting for confirmation...." 
Maybe teh way you logon at the my.athom site when clicking the confirmation link in second email is dependent on this ;-(

**Comment by joachimroeleveld** [comment]
Hi Geurt, actually, this behavior already only applies to Gmail addresses. Any address from another provider will have no normalization applied. Note that you can login with any variant (with/without dots/capitals) you like and it will just treat it as the same email address. 
Please note that we apply exactly the same normalization that Google applies. Therefore, email should have no trouble arriving at your mailbox with the normalization applied.

**Comment by joachimroeleveld** [comment]
As an update on this issue: from today, email addresses are not normalized anymore. It appeared that the costs (confusion) did not outweigh the benefits (spam account creation prevention) and therefore I decided to remove it altogether.
