### ISSUE TITLE
Disable auto app updates

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#701]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Would it be possible to disable the auto-updates for apps installed on Homey like the current option to disable and instal the firmware updates automatically to Homey? In that case, the user can wait field feedback and decide themselve to instal the latest available update?

**Why Asking?**

Why asking? With that procedure the user can decide themselve if they want to update right after this has been released. If I want Homey to control my lights at home while I'm on a vacation I'd much rather have a stable system from which i know it has worked stable for weeks instead of being up to date with the latest firmware and risk an app is not working after installation.

**Comment by swttt** [comment]
Or automate it, and have a beta and stable channel.
Let users decide on install if they want a beta app (bleeding edge, new functionality) or stable.
Give devs the option to push beta apps to stable (after review).

**Comment by daneedk** [comment]
I'd rather see Alpha (Experimental, Bleeding Edge, new functionality) Beta (more stable after Alpha, but not rock solid) and Stable.

**Comment by swttt** [comment]
@daneedk One step at a time :D but i do agree.

**Comment by Dijker** [comment]
Today I saw the old NetAtmo device wasn't compatible with the 2.x update of the NetAtmo App.
If things (possibly) break with an updat I dont want them automaticaly installed. 
If I am for a week from home things break this isn't good for WAF and dont like my Sunscreen juggling up and down or stopping working the way they dit correct before...

**Comment by Dijker** [comment]
I think this is already posible, I still Have HTTP request flow cards 1.2.1 while 1.3.1 is already weeks out. My Homey Apps still shows Update available!
The Elro app yesterday automatically updated to 2.0 as Athom is pushing these new generated 433 sockets apps.
Of course I have disabled updating in Homey.
I guess the developer or release manager can force it or leave it to the Homey owner.

**Comment by Inversion-NL** [comment]
Can be closed since implemented in 0.10.0?

**Comment by Arjanvde** [comment]
@WeeJeWel Awsome addition!
