### ISSUE TITLE
[Insights] New Templates / Settings not saved. 

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#705]
**What is your Homey version (Settings → System)?**
0.8.39 [Dutch]

**What did you try to achieve?**
Create new Saved settings / template in Insihgts.
_Please include detailed steps how we can reproduce the issue_
Create new Template, 
Give name and press enter, select one or more  checkbox to draw a graph. 
Klik Save. 
Switch to other settings, (previous created a month ago still work.)
Switch back to the newly created template... 

**What was the result?**
Notning !
Settings not saved, even the renamed name is not visible\*  in the upper left corner although it was available as name in the drop-down selecting the Intights template to load.

*\* only for the LAST new created template, Creating a new 2nd / 3rd new template fixes the displayed name for the for-last saved template.  

**What did you expect as result?**
working as before.

**Any other remarks**
minor "Various improvements" thing: 
Loading a saved template removes the background tip "Select logs on the left ...."
Loading an other template after that, again displays the background tip "Select...."  through the graphs.

A switch English with restart look like some tings saved now, but still same issue creating and naming new templates.

**Comment by Dijker** [comment]
Still a problem in 0.10.1, 
found out that the NewTemplate is saved but not available to load before a refresh from the browser window. After a refresh of the browser tab the NewTemplate is available!

also the **Any other remarks** point is still a minor thing ...

**Comment by WeeJeWel** [comment]
Fixed in 1.3.0
