### ISSUE TITLE
[0.8.39] [Insights] createLog not working for devices

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#706]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Create a log for insights for a device

*Please include detailed steps how we can reproduce the issue*

```
function createLog (device_data) {
    Homey.manager('insights').createLog( 'offPeak', {
        label: { en: 'Off-peak' , nl: 'Daltarief' },
        type: 'boolean',
        chart: 'stepLine'
      },
      function callback(err , success){
        if( err ) return Homey.error(err);
        Homey.manager('insights').createEntry( 'offPeak',
        devices[device_data.id].last_offPeak,
        new Date(), function(err, success){
          if( err ) return Homey.error(err);
        })
      });
    };
```

**What was the result?**

The log is created and presented in insights, but on the app level

**What did you expect as result?**

The log to be created on the device level

**Any other remarks**

https://athomcommunity.slack.com/files/gruijter/F1G2DFN30/2016-06-11.png

**Comment by swttt** [comment]
Noticed the same.
Work-around could be creating a log with device name as a label, still not the best solution tho.

**Comment by swttt** [comment]
Noticed you should use module.exports.realtime for known capabilities (so custom capabilities won't work as far as i know). Then it created the device name under insight with his graphs.

**Comment by gruijter** [comment]
https://github.com/athombv/homey/issues/447

**Comment by WeeJeWel** [comment]
This will be fixed in an upcoming update. All device's capabilities will automatically be logged, so no need to do it manually :-)
