### ISSUE TITLE
Motionsensors not working (Kaku and Smartwares)

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#708]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Get motion-sensors working (both kaku and smartwares)

**What was the result?**

They don't work, once the sensors detect motion the sensors wont go back off so no new motion is detected

**What did you expect as result?**

That the motion sensors would turn off at the set off-time (switch on the back) and trigger again with new motion.

**Any other remarks**

I think its an easy fix. I added them as contact-sensor and it works like a charm. They tigger when there is motion and turn off again at the set off-time. I think if you just copy the behavior of the contact sensor and change the symbol it's working.

**Comment by posthok** [comment]
Having the same issue

**Comment by posthok** [comment]
Uninstall KaKu app reboot and reinstall KaKu app. Readding device's. And homey does the job again.
Don't know for how long.

**Comment by jeroenbos22** [comment]
Nope, this was a clean install. Its not working at the moment

**Comment by posthok** [comment]
It looks like Kaku is in slowmotion mode now. After a trigger, 10 seconds later it reacts, or totally forgot what's on his grocery list. Is it ever going to work?

**Comment by BasKiers** [comment]
Does the same issue still occur in the 2.x versions of smartwares/kaku?

**Comment by jeroenbos22** [comment]
Yesterday the motion-sesnor seems to work again, don't know if you changed anything this weekend but it seems to work now. If not it might have been a signal-strength problem. Did you also take the off signal now with motion sensors?

**Comment by BasKiers** [comment]
I've tested the AWST-6000 motion sensor this week and it worked without changing anything. I suspect your problem is because of range issues which should be improved in 0.9. If not please open this issue again.
