### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#71]
Chrome console contains this error:

> GET http://192.168.0.10/app//assets/icon.svg 404 (Not Found)

Browser tab does not have a favicon shown. 
![schermafdruk 2016-02-10 22 44 41](https://cloud.githubusercontent.com/assets/15232724/12962928/1ebc212c-d048-11e5-81eb-13bfc85575b0.png)

**Comment by athomey** [comment]
+1-end, see multiple responses: https://forum.athom.com/discussion/714/request-give-the-ui-an-icon-like-other-websites-and-like-competitor-vera-athom-forgot-it#latest

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/1528/fav-icon-for-my-athom-com#latest

**Comment by bvdbos** [comment]
bump, just to get this on the rail again... See accompanied files, created with a free generator out of 1024.png...
[homey favicons.zip](https://github.com/athombv/homey/files/459006/homey.favicons.zip)

**Comment by WeeJeWel** [comment]
Hahaha <3

They're added in the next release :)

**Comment by Arjanvde** [comment]
Finally :)
