### ISSUE TITLE
z-wave devices not triggering flows

### ISSUE THREAD

**Issue by sossienl** [athombv/homey#713]
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Under 0.8.35 (other versions I skipped) opening a door triggered a flow that initiated speech "Schuifdeur open". The trigger is the "Generic alarm" is ON. This is just one of the examples I had defined as a flow based on similar triggers (door or window open / closed etc).

**What was the result?**

When opening the door nothing happens. Also defining other actions (different from speech) on the same trigger doesn't work. The "Insights" for all my z-wave devices are also empty.

**What did you expect as result?**

My flows being triggered. And my insights to show up the correct data

**Any other remarks**

Interesting enough when I look at the state of the generic alarm under the device itself. It does reflect a correct state. So when opening the door it shows a red alarm bell, and black when the door is closed. I do need to close the pop-up and open it again to see the change reflecting.

**Comment by WeeJeWel** [comment]
Have you tried recreating the Flow with the new Z-Wave device?

**Comment by WeeJeWel** [comment]
Whoops - I just saw that this issue is pretty old. This should definitely be fixed with the Z-Wave rewrite in 0.9.1!

**Comment by sossienl** [comment]
Fixed
