### ISSUE TITLE
Developer docs: app-to-app example failing

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#715]
**What did you try to achieve?**
Reuse the app-to-app example from https://developers.athom.com/library/api/

**What was the result?**
App killed because of syntax error

**Any other remarks**
line `app.isInstalled( err, installed ) {` should be 'app.isInstalled(function (err, installed) {`

![image](https://cloud.githubusercontent.com/assets/15232724/16539148/437046a8-403a-11e6-8c1b-6a43fc0e70f6.png)

...

**Comment by WeeJeWel** [comment]
Whoops, fixed, thanks!
