### ISSUE TITLE
Cannot move app to 'pending' state in app store

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#717]
**What is your Homey version (Settings → System)?**

n/a

**What did you try to achieve?**

Submit an update of the OTG app.

**What was the result?**

Process in app-store is stuck in the 'concept' stage. When pressing the submit button, it does show to go to the 'pending' state. However, when refreshing the page it becomes apparent that it is still in the 'concept' stage.
After pressing 'submit' a strange empty pop-up appears on top the button:
![image](https://cloud.githubusercontent.com/assets/11725674/16540941/a9ad9286-4076-11e6-9d55-333fe93fa2a2.png)

**What did you expect as result?**

That the app goes to the next stage for review.

**Any other remarks**

Was under the impression the app was submitted for update a week ago!

**Comment by joachimroeleveld** [comment]
This bug has been fixed in the latest release. Thank you for reporting!
