### ISSUE TITLE
App store: Other app permissions does not show icon

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#718]
**What did you try to achieve?**

Install HTTP App.

**What was the result?**
The dialog with permissions shows the better logic app, but with a invalid/unavailable icon:
![image](https://cloud.githubusercontent.com/assets/15232724/16542632/739442be-40b0-11e6-8726-378a7fdb8cb5.png)
...

**What did you expect as result?**
Better Logic icon
...

**Comment by joachimroeleveld** [comment]
Thanks. This has been fixed in code and will be pushed with the next release.
