### ISSUE TITLE
Zwave all on trigggers an off action 

### ISSUE THREAD

**Issue by lvanderree** [athombv/homey#72]
I have multiple Fibaro Dimmer2 modules.

On some modules, I have attached 2 buttons (S1 and S2).
In the flow editor I created an "all on" flow, In which I have the following:

```
if "hal virtual button" on
then say "all on" and zwave send all on
```

I have another created an other flow, to turn everything off:
```
if "hal virtual button" off
then say "all off" and zwave send all off
```

When I remove the zwave send all on/off commands, the speech functions as expected.
However when I add the zwave send all on command, It probably triggers and off value for the "hal virtual button" since the speech immediately gets followed by an "all off" sentence.

**Comment by ocatie** [comment]
Currently there is an issue with the Fibaro Dimmer 2. Looking into it.

**Comment by ocatie** [comment]
Fibaro 2 Dimmer works in 0.8.20. Does the error persist in 0.8.20?
