### ISSUE TITLE
how do i get an app working

### ISSUE THREAD

**Issue by annekrist** [athombv/homey#723]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

I downloaded an app and installed it. Howerer how can i get it to work?
Do i have to make a flow?
And when i do make a flow and i want to test it, it says "please check your cards for errors" Which errors? Couldn't find a manual on the site. 

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by RoadXY** [comment]
Depends on what the app does.
Sometimes a flow, sometimes it only logs in Insights.

Which app are we talking about?

P.s. make your way through the forum.
You'll learn a lot

**Comment by Dijker** [comment]
For the Support and  how-to's from Athom

https://www.athom.com/en/support/
And please only report software problems here. There are way more users active on the forum to answer your questions 
https://forum.athom.com 

Knowledge base Also in Dutch
https://www.athom.com/nl/support/

**Comment by annekrist** [comment]
Hi Robin, i'm talking about the Onkyo app.

After installation how do i use it?


Wich commands can i give homey, and do they include Dutch commands?

gr

Anne



________________________________
Van: Robin van Kekem <notifications@github.com>
Verzonden: dinsdag 19 juli 2016 13:53
Aan: athombv/homey
CC: annekrist; Author
Onderwerp: Re: [athombv/homey] how do i get an app working (#723)


Depends on what the app does.
Sometimes a flow, sometimes it only logs in Insights.

Which app are we talking about?

P.s. make your way through the forum.
You'll learn a lot

-

**Comment by swttt** [comment]
Hello Anne,

Like they said above, github is only used for bugs/problems/flaws in their software. The forum is meant for issues you are having. So if my steps below don't work, i suggest you open a forum topic.

Nevertheless, you need to add the devices first (in the devices overview click the plus sign).
After that you should be able to find your newly added device in the flows.

**Comment by annekrist** [comment]
Aha so i do need to do something with flows. The basics of a Homey are not known to me yet. Just got the box but no manual. 
Its not a harmony remote. So i have to develop a new way of thinking. 
And I still dont know what a github is. 
Remember not everybody has got the same knowledge as you have. Giving me three links to find things doesn't give me much confidence in the product. Same with te multiple users and passwords i need for this device.
Thx for the fast reply, ill have a look at the links you provided.

**Comment by Dijker** [comment]
@annekrist ,
github is the place where developers share code to make programs and users, or testers report issues.
I had the same or less info to start with only I am almost 6 months using the Homey and have an IT background.
I agree the different community platforms they use at Athom don't make it easier for new users.
Start with reading the Athom.com Support. If it isn't there create an account on the forum.
You will find plenty discussions and can start new ones, but look if there is already an discussion about that topic to join. 
As the searches of the forum are not that good use Google's and add site:athom.com
For example: Google for " site:athom.com change variables "
When you find a bug in the software and hopefully you can reproduce it create an issue on the github. 
There are some apps that have there own github, so report app specific bugs or problems there.

**Comment by annekrist** [comment]
Dijker (thx) bedankt voor je uitgebreide en snelle reactie. Het is mij nu een stuk duidelijker.

**Comment by Dijker** [comment]
@annekrist  
As you now probably know the difference between the Forum where you can ask all kind of questions and the github where software Issue's are registered to help the developers to reproduce the bugs and fix them (ans sometime register new feature requests) 
please close this issue by pressing the Close Issue below your comment box. (I can only close my own Issues, if you wait long enough someone from Athom probably will see it and close it, )

(guess you can read English, or try some dutch in the Off topic Area or the Caffe.
Someone will answer there....
Athom relay want to keep all communication centralized and therefor English for the relative small group of Homey users ;-))
