### ISSUE TITLE
LED ring partial failure

### ISSUE THREAD

**Issue by elcovb** [athombv/homey#724]
On my brand new Homey, when I first unpacked it, the ring was fully functional. Then the Homey went through an update and downloaded voices. Then suddenly 3 quarters of the LED ring stopped moving, it staid orange while 1 quarter of the ring kept 'moving' orange. The Homey was unresponsive for minutes so I pulled the plug. Now when the Homey restarts only 1 quarters of the LED ring lights up, 3 quarters of the LED ring stay off. The rest seems to function well. See picture.

No apps were installed, the Homey was only updated automaticly.

P.S. I already did a reset by flipping the Homey and erasing the data.

![20160720_131720](https://cloud.githubusercontent.com/assets/20556899/16985000/f4b4ad22-4e7d-11e6-8b13-4cbddf157dbd.jpg)

arch	arm
cloud_connected	true
cpus	[{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":495600,"nice":0,"sys":606000,"idle":179600,"irq":100}}]
date	2016-07-20T11:23:40.124Z
date_dst	true
date_human	Wednesday 20th July 2016 13:23:40
devmode	false
freemem	67002368
homey_version	0.8.39
hostname	Homey
loadavg	[2.453125,1.109375,0.4248046875]
network	{"lo":[{"address":"127.0.0.1","netmask":"255.0.0.0","family":"IPv4","mac":"00:00:00:00:00:00","internal":true},{"address":"::1","netmask":"ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff","family":"IPv6","mac":"00:00:00:00:00:00","scopeid":0,"internal":true}],"wlan0":[{"address":"192.168.1.17","netmask":"255.255.255.0","family":"IPv4","mac":"6c:ad:f8:1d:0b:ed","internal":false},{"address":"fe80::6ead:f8ff:fe1d:bed","netmask":"ffff:ffff:ffff:ffff::","family":"IPv6","mac":"6c:ad:f8:1d:0b:ed","scopeid":3,"internal":false}]}
node_version	v4.4.2
platform	linux
timezone	Europe/Amsterdam
totalmem	513794048
uptime

**Comment by jeroenvollenbrock** [comment]
Please contact support@athom.com for an RMA procedure.
