### ISSUE TITLE
[KAKU][0.8.39][App v2.0.2 ] Blinds ASUN650 is missing Inverse option

### ISSUE THREAD

**Issue by Dijker** [athombv/homey#726]
**What is your Homey version (Settings → System)?**
0.8.39 / KAKU 2.0.2 automatically upgraded from 1.1.6

**What did you try to achieve?**
Replace old driver device with new as instructed by email

*Please include detailed steps how we can reproduce the issue*
My old device is reversed. this was an option in the asun 650 from 1.1.6

**What was the result?**
I could copy the device , but I can't revers it.
so the new devise is useless at this moment for me. (or I have to rewire and reverse all switches)

**What did you expect as result?**
The same option "invert directions" as in the previous KAKU app.

**Any other remarks**
at first sight the bug from #703. is fixed, will test tomorrow but with the old device/driver.
Pls keep the old driver alive during the first updates ( as I can't transition to the new device if it doesn't function and during hollidays... )

**Comment by Marc1979** [comment]
Same problem over here...

**Comment by Dijker** [comment]
Is this fixed in 2.0.4?
