### ISSUE TITLE
Insights: z-wave and klikaanklikuit sensor values not available

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#73]
I added a Fibaro Multisensor and KAKU contact sensor. 
In the Insight screen I cannot select these devices for analyzing values like lux, temperature, motion detection, open/close contanct, vibrations.
Hue Bulb dim value and Thermosmart set and room temperatures are working fine.

**Comment by WeeJeWel** [comment]
The KAKU contact sensor reports no numeric value, which is on the todo list.

For the Fibaro sensor, I assign @ocatie

**Comment by irritanterik** [comment]
Ok, I see numeric sensor values like lux, battery level and temperatures now. So it's ok for numeric z-wave as well.
