### ISSUE TITLE
tamper-alarm missing in fibaro app

### ISSUE THREAD

**Issue by philsniff** [athombv/homey#730]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Fibaro Motion Sensor z-wave+ misses tamper-alarm i think.
before in .8.38 it was there.
![schnappschuss_072916_071833_pm](https://cloud.githubusercontent.com/assets/7848863/17257250/8e44b762-55c1-11e6-9a36-f04b98eb0991.jpg)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Can you please resubmit this issue in the fibaro app repo?
https://github.com/athombv/com.fibaro
