### ISSUE TITLE
Adding device while in a specific zone will add device in top level

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#731]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**
Adding a device in the correct zone right away

**Please include detailed steps how we can reproduce the issue**
Select a zone, i.e. the attic
Click "Add device"
Perform the ad device procedure
Find the device not being added to the attic but in the to most level instead

**Any other remarks**
Great work on the z wave rewrite!
Adding my Fibaro smoke detector was a real pleasure, well done!

**Comment by WeeJeWel** [comment]
Ha, nice find! Fixed in 0.9.2

**Comment by Inversion-NL** [comment]
Is indeed fixed in 0.9.2
