### ISSUE TITLE
homey freezes after reboot via system menu

### ISSUE THREAD

**Issue by mara2008** [athombv/homey#732]
**What is your Homey version (Settings → System)?**
0.9.1

**What did you try to achieve?**
I was trying to reboot my homey with the reboot button within the system menu. unfortunatelly homey freezes and I have to pull the plug. it occured once that I noticed it was freezing because the rainbow ledring stoped working and all the other times I had a solid orange ledring

*Please include detailed steps how we can reproduce the issue*
press the reboot button within the system menu

**What was the result?**

homey freezes

**What did you expect as result?**

homey was rebooting

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Can you verify if this issue still persists in 0.9.2?

**Comment by jeroenvollenbrock** [comment]
This issue is being closed due to inactivity. Please reopen this issue if the problem persists.

**Comment by mara2008** [comment]
Hallo,

Zojuist nog even gechecked en met 0.9.2 is dit issue inderdaad opgelost.

Op 16 aug. 2016 17:18 schreef "Jeroen Vollenbrock" <notifications@github.com
