### ISSUE TITLE
Z-wave loading regions

### ISSUE THREAD

**Issue by PeterBox** [athombv/homey#735]
**What is your Homey version (Settings → System) 0.9.1

**What did you try to achieve?** connect a fibaro sensor to homey

*Please include detailed steps how we can reproduce the issue .Looked what options there are beside European  Regions ,after that z-wave is continuing loading  regions

**What was the result?**

...see above

**What did you expect as result?**

Select right region en continue  connecting  fibaro sensors

**Any other remarks**

Completely reinstalled  Homey twice nothing  changed

**Comment by WeeJeWel** [comment]
Can you send a Crash log, right after rebooting your Homey?

**Comment by PeterBox** [comment]
26FB083F91

Crash log send

**Comment by jeroenvollenbrock** [comment]
@PeterBox Unfortunately, your log file does not contain any zwave related information. Can you perhaps reboot homey once more, trigger the bug, and then send a new log file?

**Comment by PeterBox** [comment]
Send log again E3648891E0

**Comment by PeterBox** [comment]
I have attached  a screen pic

Op 1 aug. 2016 14:24 schreef "Jeroen Vollenbrock" <notifications@github.com

**Comment by PeterBox** [comment]
Still the same error .  Z-wave Regions choice is looking for the right region in my case Western-Europe

**Comment by WeeJeWel** [comment]
All buttons are disabled I assume, and pairing shows 'Waiting for Z-Wave to be ready'?

**Comment by PeterBox** [comment]
Yes, I also can't  pair z-wave  devices

**Comment by WeeJeWel** [comment]
Alright, thanks. Did Z-Wave work before 0.9.1?

**Comment by PeterBox** [comment]
Yes 👌

**Comment by jeroenvollenbrock** [comment]
@WeeJeWel Switching regions caused a firmware corruption on the zwave module. I've got a repair script available.

**Comment by soler2000** [comment]
I have this same issue,  after selecting the region it continues to spin,  even after a reboot

**Comment by WeeJeWel** [comment]
As of 0.9.3 I've added the option to always re-flash the z-wave chip, even if the previous flash went wrong (what you guys are most probably experiencing). So that should fix it!

**Comment by priknr1** [comment]
I am having the same issue I guess.
Showing: loading regions all the time. Keeps circeling
log: 864069653A

**Comment by HansieNL** [comment]
I only get "Wacht tot z-wave klaar is..." Rebooted Homey several times, pulled power for more than half an hour.
Factory reset and Other Z-wave Networks are greyed out.
Running Homey firmware 0.9.3.
Any suggestion?
