### ISSUE TITLE
Z-Wave implemented command class version is sometimes V1 instead of actual version supported by device

### ISSUE THREAD

**Issue by Thorarin** [athombv/homey#736]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

I'm trying to write a driver for the Sensative Strips. I'm having issues with the alarm/notification command class. Sometimes Homey correctly detects it supports version 4 of the command class, sometimes it detects version 1. Due to the rename in version 3, this is especially annoying.

**What was the result?**

Sometimes when I add the device, it will appear in Homey as supporting COMMAND_CLASS_ALARM (v1), instead of COMMAND_CLASS_NOTIFICATION (v4) which the device actually supports. This makes my driver unreliable, because I can't define the right capabilities for the device if they keep changing.

**What did you expect as result?**

For the device to be added with the same capabilities each time.

**Any other remarks**

Apart from solving the capabilities not being consistent, perhaps COMMAND_CLASS_ALARM and COMMAND_CLASS_NOTIFICATION could be treated as aliases of each other? The way I understand it, it's just a rename that was done in v3 of the spec.

**Comment by WeeJeWel** [comment]
Are you 100% sure that the command class on that device is of another version than Homey reports?

Different device versions usually require different drivers, so if above is not the case, then I think it seems fine.

**Comment by Thorarin** [comment]
It happened at least 3 times that COMMAND_CLASS_ALARM was reported.
Up until today I only had one Strips, so it's not a case of different hardware/firmware versions.

I've been trying to make a log of it happening, but I must say that the last 5 or so attempts have all worked correctly. Just after upgrading it went wrong more often than not, but I did not make any logs, sorry :(

**Comment by WeeJeWel** [comment]
I've fixed this bug in 0.9.2. Some versions got mixed up during pairing due to some devices sending multiple reports for some godforsaken reason.

**Comment by jeroenvollenbrock** [comment]
@Thorarin Can you verify if this issue has been resolved now?

**Comment by Thorarin** [comment]
@jeroenvollenbrock I've tried about 8 times with 0.9.2 so far, most of them with the driver in debug mode. So far, all of them have reported the correct command class versions, but after the pairing the device does not work at all now. Sensor reports a communication error

Different bug I guess, but perhaps related to this change? Not an improvement for me personally :stuck_out_tongue:

**Comment by jeroenvollenbrock** [comment]
@Thorarin I think that is a different bug. Could you please file another issue? Also, if you are able to consistently reproduce the issue, would you mind sending me a PM on slack (https://slack.athom.com, @jeroenvollenbrock) so we can try to debug this? I've seen multiple reports of this although none on github, and would like to find out the cause, since i'm unable to reproduce it.
