### ISSUE TITLE
Somfy sunscreens don

### ISSUE THREAD

**Issue by rogiervanwijk** [athombv/homey#737]
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by RoadXY** [comment]
@jeroenvollenbrock Close?

**Comment by WeeJeWel** [comment]
Duplicate of #738
