### ISSUE TITLE
Somfy sunscreens don't function anymore

### ISSUE THREAD

**Issue by rogiervanwijk** [athombv/homey#738]
**What is your Homey version (Settings → System)?**

9.0.1

**What did you try to achieve?**

After update to v 9.0.1 Somfy sunscreen did not function anymore. Neither voice command nor via device control using the android app worked. Deleted devices and tried to add them again. Message: Homey not able to recognise signal and report to GitHub.

**What was the result?**

Homey did not add the Somfy devices

**What did you expect as result?**

Devices added and operational

**Any other remarks**

...

**Comment by jeroenbos22** [comment]
After 2 powercycles I got them to work again but sometimes they respond very slow. I click up for example and after 10 - 15 secs they go up. Pairing a new one is not working anymore.

**Comment by RoadXY** [comment]
Weird, all working fine here.
Maybe weird conclusion but do you have any KaKu devices?
I don't have any connected to Homey and since they share frequency, who knows...

**Comment by ReinierH** [comment]
@jeroenbos22 
Can you send me your homey logs?

**Comment by ReinierH** [comment]
@rogiervanwijk 
i've created an internal bugreport for this issue. Thanks!

**Comment by jeroenbos22** [comment]
Did do a reboot, Hope it still works: 4E0D9BF36A

2016-08-01 10:16 GMT+02:00 ReinierH <notifications@github.com>:

**Comment by edtst** [comment]
Same here, I can no longer control my shutters after this update.

**Comment by Inversion-NL** [comment]
No problem here...

**Comment by BasKiers** [comment]
Hi,

I've tried resolving problems by rewriting the somfy app (as of v2.0.0). If you still experience issues please report in #912 or open a new issue.

Regards,
Bas
