### ISSUE TITLE
Somfy pairing broke on 0.9.1

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#739]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Pair a new somfy rts

**What was the result?**

The pairing process ask me to produce a RTS signal. With older version it went straight to a confirmation screen after pressing it. Now I have to click the button to continue and it asks me if the screens move. Offcourse they moved because I just send the learning signal from the remote. It asks me if the curtain moved so I click yes but have the feeling the signal was not registered within Homey. After adding it doens't respond.

**What did you expect as result?**

A succesful pair like with older versions

**Any other remarks**

I need my curtains to move!!! 😄

**Comment by jeroenbos22** [comment]
Aha, got it working again if I keep the remote 10cm from Homey, so a mega drop in signal receiving (worked on 10 meters before). Sending (and reaching the curtains) at approx 4 meters is no problem.

**Comment by ReinierH** [comment]
@jeroenbos22 
Thanks for your bugreport.
i have created an internal bugreport for this.

**Comment by jeroenvollenbrock** [comment]
Somfy operates on 433.42Mhz instead of 433.92Mhz. Homey listens on 433.92Mhz by default. The pairing wizard needs to temporarily listen on 433.42, which is currently not possible. @BasKiers Could you add a warning when pairing by remote that the range needs to be as small as possible. (about 10 cm)

**Comment by bvdbos** [comment]
Was this fixed?

**Comment by jeroenbos22** [comment]
Didnt had problems here since, so think so

**Comment by bvdbos** [comment]
Was this fixed?

**Comment by jeroenbos22** [comment]
Yes fixed
