### ISSUE TITLE
Install athom-cli in Node.js failes

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#740]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Installed Node.js 4.4.7 x64 on Windows 7
Ran "npm install -g athom-cli"

**What was the result?**
C:\Windows\System32>npm install -g athom-clinpm WARN addRemoteGit Error: not found: gitnpm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)npm WARN addRemoteGit  git+https://github.com/athombv/node-homey-signal-validator.git#production resetting remote C:\Users\Kees\AppData\Roaming\npm-cache\_git-remotes\https-github-com-athombv-node-homey-signal-validator-git-1289a831 because of error: { [Error: not found: git] code: 'ENOGIT' }npm ERR! git clone --template=C:\Users\Kees\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/athombv/node-homey-signal-validator.git C:\Users\Kees\AppData\Roaming\npm-cache\_git-remotes\https-github-com-athombv-node-homey-signal-validator-git-1289a831: undefinednpm ERR! git clone --template=C:\Users\Kees\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/athombv/node-homey-signal-validator.git C:\Users\Kees\AppData\Roaming\npm-cache\_git-remotes\https-github-com-athombv-node-homey-signal-validator-git-1289a831: undefinednpm ERR! Windows_NT 6.1.7601npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "athom-cli"npm ERR! node v4.4.7npm ERR! npm  v2.15.8npm ERR! code ENOGIT
npm ERR! not found: gitnpm ERR!npm ERR! Failed using git.npm ERR! This is most likely not a problem with npm itself.npm ERR! Please check if you have git installed and in your PATH.
npm ERR! Please include the following file with any support request:npm ERR!     C:\Windows\System32\npm-debug.log
C:\Windows\System32>

**What did you expect as result?**

installed o.k.

**Any other remarks**

athom login doesn't work

**Comment by nattlip** [comment]
installling git on the indoes computer didnt help ?

**Comment by nattlip** [comment]
https://git-scm.com/downloads

**Comment by nattlip** [comment]
or doe you have  "." in your email

**Comment by WeeJeWel** [comment]
Fixed, try reinstalling
