### ISSUE TITLE
[Feature request] When clicking a device card item, go to Insights

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#741]
**What would you like to achieve?**
When clicking on a device item, like temperature, directly go to the item in Insights, like temperature.

**Comment by WeeJeWel** [comment]
Nice suggestion, I'll think about it - thanks!

**Comment by Inversion-NL** [comment]
Could the request be changed to:
When clicking the device, open mobile card.
Add another icon, like the wrench, for a short link to Insights of that specific device.

**Comment by WeeJeWel** [comment]
This is added in the new Homey Smartphone App. Insights isn't implemented yet, but the view is already there.
