### ISSUE TITLE
Sunrise and sunset not working proper after upgrade to 0.9.1

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#742]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**
Create flows with sunset and sunrise card.

*Please include detailed steps how we can reproduce the issue*
I created two flows with each on of the cards in in the IF collum and that it sends a pushover message with the time the sun went up or down.

**What was the result?**
at sunrise nothing happens
at sunset i get a pushover message but about one hour and one kwarter to early. (on 31-1-2016 the sunset was 21:30 i goed a message on 20:11) 

**What did you expect as result?**
I expeted to receive two messages with and on the correct time.

**Any other remarks**
My homey is set to Dutch

**Comment by spoelly** [comment]
when i test the flows i receive 21:23 on both flows when i expected 21:23 only for sunset and 5:40 or something for sunrise.

**Comment by Dijker** [comment]
The returned values ant times on pressing the test button are by design. 

If you searched the issues or forum and read the #182 thread, or #313 or #323  you could know all tests always report 21:23 .
Afaik only the sunsets work mostly.... Dependent on location it triggers.

**Comment by spoelly** [comment]
Okay my bad i only searched the open issues. And the forum is terrible to search things.. But will see if it does something at sunset and tomorow at sunrise. I reapplied the cards and will do a power cycle when i get home. See if that helps.

**Comment by spoelly** [comment]
And again not working 20:11 sunset triggered, when it should have been 21:xx

**Comment by spoelly** [comment]
And found the issue my location setting was set to automatic. Currentley my internet provider has an issue with setting my location to my ip adress. Set it to manual so i think this is ok now
