### ISSUE TITLE
Submit request for appstore returns error message: The repository does not exist or is private

### ISSUE THREAD

**Issue by IcarusProject** [athombv/homey#745]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Add a new app so it can be released in the appstore

**What was the result?**

App store returned:

Oops! Your app did not pass our validation process. The following errors occurred:
The repository does not exist or is private.
![image](https://cloud.githubusercontent.com/assets/20789533/17324424/c61b3610-58a6-11e6-944f-099163825085.png)

**What did you expect as result?**

For the app validation process to proceed

**Any other remarks**

- I checked the security settings of the GIT repo;
- Same error message as #612 but different starting position (#612 is an update request. I'm trying to add a new app). I added some comments to #612 but realized that creating a new issue might be the right call;
- App source: https://github.com/IcarusProject/me.zwave.git;
- I did a validation of the app before publishing it on GIT.

**Comment by joachimroeleveld** [comment]
This issue has been resolved. Thanks!
