### ISSUE TITLE
Update request for appstore returns error message: The repository does not exist or is private

### ISSUE THREAD

**Issue by IcarusProject** [athombv/homey#746]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Update an existing app in the appstore

**What was the result?**

App store returned:

Oops! Your app did not pass our validation process. The following errors occurred:
The repository does not exist or is private.

![image](https://cloud.githubusercontent.com/assets/20789533/17357487/1701e964-595d-11e6-93dd-1a0199b97a56.png)

**What did you expect as result?**

For the app validation process to proceed

**Any other remarks**

- Had the same message yesterday when I tried to add a new app (#745). Might be related?

**Comment by joachimroeleveld** [comment]
Hi @IcarusProject, I must admit that the error is not very explanatory at this point. However, the App Store fails on your submodule config. The clone of your app fails with `No submodule mapping found in .gitmodules for path 'node_modules/homey-zwavedriver`. @WeeJeWel maybe has suggestions on how to solve this.

**Comment by IcarusProject** [comment]
Yesterday I removed the submodule function to test if I could upload a changed app. Unfortunately I got the same result (_App store returned:

Oops! Your app did not pass our validation process. The following errors occurred:
The repository does not exist or is private._). I'm looking forward to year from you. Thanks in advance!

**Comment by joachimroeleveld** [comment]
The server crashed on the error that I mentioned in the previous comment. Therefore, some server logic was interrupted which caused a state that prevented your consequent submissions. This should now be fixed an not be an issue anymore. Feel free to reopen if this doesn't help you.
