### ISSUE TITLE
Website to big for iPad

### ISSUE THREAD

**Issue by Sillyjan** [athombv/homey#750]
When i open the buy now page on the iPad the page will not fit.
I need to scroll to see the complete page. Don't now if this is a issue but it looks a bit strange.
The invoice page also has this.

![img_0077](https://cloud.githubusercontent.com/assets/20732728/17405391/939e2fde-5a5f-11e6-9245-bed38a2be7f8.PNG)
![img_0078](https://cloud.githubusercontent.com/assets/20732728/17405392/94b2ae04-5a5f-11e6-857b-cab270f9b005.PNG)

**Comment by joachimroeleveld** [comment]
A responsive version of the webshop is on the planning. This will fix the issue.

**Comment by joachimroeleveld** [comment]
This is fixed now.
