### ISSUE TITLE
manager( 'api' ) seems not to return anything

### ISSUE THREAD

**Issue by swttt** [athombv/homey#751]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Get manager( 'api' ) to give some useful output as result.

**What was the result?**

Whatever i tried, it gives undefined (probably wrong api url) or no_result.

**What did you expect as result?**

Some output 😄 

**Any other remarks**
Only tried GET.

**Comment by swttt** [comment]
@jeroenvollenbrock @WeeJeWel 
Not sure if Emile fixed this yesterday. I tested the documented code, wich didn't work.
I asumed it was possible to query devices (isn't it a permissions option in the app.json?), that didn't worked as well but seems designed this way ;)

So i guess if the geolocation call is fixed, the rest isn't a bug but is a feature :smile:

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
