### ISSUE TITLE
Fibaro Motion Sensors (FGMS-001) not working properly  

### ISSUE THREAD

**Issue by sossienl** [athombv/homey#752]
**What is your Homey version (Settings → System)?**

Homey 0.9.1
Firbaro app 1.0.6

**What did you try to achieve?**

Today I received 2 Fibaro Motion Sensors (FGMS-001). Including them to the network, worked like a charm. I installed one in the living room and the other one in the kitchen.  For both I added a small flow that triggers speech on movement.

**What was the result?**

Living room seemed to work ok for 5 minutes, until it suddenly didn't report any changes or movement. I'm not sure about the lux / temperature. It was showing a value.
Kitchen shows same result as Living room

I rebooted Homey and that triggered the one in the Living room again. Meaning the flow was initiated a few times , but temperature is empty (no value). Lux is showing a value. And after 10 minutes also the flow is not triggered anymore.
Kitchen has same behaviour

**What did you expect as result?**

Obviously that after including them, they would work as expected, showing all values. trigger each time on motion etc.

**Any other remarks**

My other Fibaro devices (door&windows sensors 10x) are working perfectly. 

...

**Comment by philsniff** [comment]
my motion sensor (zwave+) worked for two days. then suddenly i noticed that the motion detection was keeping always on and didn't stop anymore.
also at the start after inclusion all reports of tamperalarm, battery, lightning and temperature worked, but now some were missing in the insights. 

the zwave settingspage under settings was unavailble, so all buttons (remove device, reset zwave etc) were greyed out and flickered evers 5 seconds. waiting for minutes, but only a reboot of homey brought the buttons back.

i have the feeling, that the zwave network is unstable and crashes often. the motion sensor must be reset and include from the beginning to work like it has to

**Comment by ThaYoung1** [comment]
@sossienl Do you have the Z-Wave+ Fibaro Multi Sensor? Still experiencing this problem?

I am with my Z-Wave+ Fibaro Multi Sensor..

**Comment by gruijter** [comment]
Same behaviour for my fibaro zw+ motion sensor. Every few days I have to do a ptp to get zwave working again. I'm on 0.9.3 fw rigth now, but same happened also for previous fw versions.

**Comment by scanno** [comment]
what is the status in this issue? on 0.10.5 this is still present. Temp and lux are reported regulary, but movement will not trigger anything in a flow (if movememt detected, switch on kaku dimmer).

**Comment by jghaanstra** [comment]
I have re-paired the Fibaro FGMS-001 ZW5 Motion sensor on Homey firmware 1.0.2 and Fibaro app version 1.1.0 and this issue is still present. There was a time where cancelling the motion alarm worked properly but now it's once again not cancelled and re-pairing the device does not fix it.

Sometimes it's says on indefinitely, and some time I see it switching back and forth between alarm and no alarm while there is no actual movement.

**Comment by RobinBol** [comment]
Since this issue is extremely old and inactive I will close it, if any of you still encounter these issues please create an updated issue at https://github.com/athombv/homey/issues.
