### ISSUE TITLE
Android app notification

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#755]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Making a flow with sending a push message to my Sony Z5 running Android 6.0.1

*Please include detailed steps how we can reproduce the issue*
Make any flow and put in the 'then' column a push message card

**What was the result?**
no push message being received. Because my mobile is listed more than once I chose the last entry. Also tried every entry

**What did you expect as result?**

receiving a push message. 

**Any other remarks**

Running app version 2.2.6 build 54. According to the homey forum push notification should have been fixed in the latest version of the app.

**Comment by Fiek1** [comment]
I also own a iPhone 6. push notification is working on this device

**Comment by swttt** [comment]
@Fiek1 Push is working here on ios as well. But found out it has the same issues as on android, multiple phone devices entries. Have to pick the last one as well to get it to work.

**Comment by irritanterik** [comment]
Also on android app version 2.2.6 build 54. 
Only one device selectable in flows. 
But push messages *never* received on the device. 
Recreate flows or app logout / login  has no result.

**Comment by jeroenvollenbrock** [comment]
Double entries have been removed. Android 2.2.7 & iOS 1.2.1 have been submitted for approval. These versions contain stability improvements for registering push notification devices.
