### ISSUE TITLE
My Android Mobile is listed five times in flows Homey

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#757]
**What is your Homey version (Settings → System)?**

9.2  was in 8.x also

send a push notification to my mobile  , choose o

**What was the result?**
in the flows 5 clones of my android is available in a list. after trying al 5 a few times a push notification is send then it stops for weeks or months.
...

**What did you expect as result?**
one android mobilein list and Homey keeping focus on my mobile.

...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
The double listed devices have been removed. Android version 2.2.7 should avoid adding double entries and will be released tomorrow.
