### ISSUE TITLE
measure_temperature i not available in insights

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#758]
**What is your Homey version (Settings → System)?**

0.9.2 and 0.9.1

make an insight with temperature variable, temperature is in format XX.X Number

**What was the result?**

only humidity and pressure are available in  insights

**What did you expect as result?**
make an insight with temperature variable, temperature is in format XX.X Number
...

**Any other remarks**

...

**Comment by Inversion-NL** [comment]
Can be closed now you found out is was a space in your code? :)

**Comment by nattlip** [comment]
yes indeed
