### ISSUE TITLE
Thermosmart app: Pause / Resume thermostat

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#76]
It is not possible to pause or resume the Thermosmart program by flow actions nor use the pause-state as a trigger or condition.
It is supported by the Thermosmart API thou.

Pausing and resuming are nice in flows like 
- 'someone left home and nobody is home then pause thermostat'
- 'someone came home and thermostat is paused then resume thermostat'

**Comment by WeeJeWel** [comment]
Fixed in ThermoSmart 1.0.4, now in the App Store!

Setting the outdoor temperature is now also possible :-)
