### ISSUE TITLE
Settings Type "label" not working

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#760]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Use the "label" type in settings.

*Please include detailed steps how we can reproduce the issue*

In app.json used:
```
  "children": [
            {
              "id": "smileId",
              "type": "label",
              "label": {
                "en": "Smile ID",
                "nl": "Smile ID"
              },
              "value": "bcdfghjk"
            },
```

**What was the result?**

```invalid type for `driver[0].settings[0].children[0].value` in app.json, expected type undefined```

**What did you expect as result?**

The label type to work

**Any other remarks**

When changing "label" to "text" in above snippet It does work, but then the setting can be changed by the user. This is what I want to avoid and therefore need to use "label"

**Comment by nlrb** [comment]
Type `label` is missing from `lib/node_modules/athom-cli/node_modules/homey-lib/lib/app/index.js`:

`// allowed types for driver settings
const allowedDriverSettingsTypes = {
	'text'		: 'string',
	'password'	: 'string',
	'textarea'	: 'string',
	'number'	: 'number',
	'radio'		: 'string',
	'checkbox'	: 'boolean',
	'dropdown'	: 'string'
}`

**Comment by WeeJeWel** [comment]
Fixed! This will be shipped in 0.9.3

**Comment by caseda** [comment]
and how will it work officially?

add the text (and languages) to the value.
Or will the "Label" be the only thing to be displayed, because the value is a tag that must be added.

**Comment by WeeJeWel** [comment]
`value` is what will be shown as simple text, similar to a textfield, but without it being editable.

**Comment by nlrb** [comment]
Confirmed working in 0.9.3. Can something be done about the ridiculous line spacing for type label? Since there are no borders like with text, lines can be closer together.

**Comment by gruijter** [comment]
But when I try to validate for app store release I get an error. Not sure if this is an error on my side or not.

```"children": [
            {
              "id": "studentName",
              "type": "label",
              "label": {
                "en": "Studentname",
                "nl": "Studentnaam"
              },
              "value": "student" ```
App failed to validate!
Error: invalid type for `driver[0].settings[0].children[0].value` in app.json, expected type undefined

**Comment by freemann** [comment]
Here also;
```
C:\Users\.....>athom project --validate-app-store
Validating C:\Users\m\Documents\GitHub\uk.co.robot-electronics for App Store use...
App failed to validate!
Error: invalid type for `driver[0].settings[0].children[0].value` in app.json, expected type undefined
Error: invalid type for `driver[0].settings[0].children[4].value` in app.json, expected type undefined
```

@gruijter; The issue is addressed here, so maybe its a bit overkill to create a new issue for this?

**Comment by nlrb** [comment]
As local workaround you can add `label` to `allowedDriverSettingsTypes ` in `lib/node_modules/athom-cli/node_modules/homey-lib/lib/app/index.js`. It needs a new release of the cli (as already stated above) to fix.

**Comment by gruijter** [comment]
@freemann; I opened a new issue since imo it is a new (related) issue. I was thinking that making it a seperate issue makes it easier for Athom to track and prioritize issues. But I'm new to this coding business, so if this is not good practice please let me know so I can learn :)

**Comment by freemann** [comment]
@nlrb 
where is said that there's a new CLI needed ? (i'm probably totally missing something...)

@gruijter 
The error you posted 35min. ago is "the same" as in the description of 25 days ago. To me that's not a new issue. But you can keep both Issues open and wait/see what Athom things about it :+1:

**Comment by gruijter** [comment]
@freemann: Ahh, now I see what you mean. But when looking at both titles, the issue from 25 days ago is solved since the label-type works fine when installing over the cli. And the new issue is that the appstore validation is not able to correctly handle the new label type. Anyhow, enough said about this. 👍
