### ISSUE TITLE
[Insights] logs not automagically working for custom capabilities

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#763]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

I want a custom capability to be logged/shown in insights.

*Please include detailed steps how we can reproduce the issue*

In driver used:
```
    module.exports.realtime(devices[device_data.id].homey_device, "measure_gas", gas_interval_meter);
```

**What was the result?**

nothing, no insights are available for this custom capability

**What did you expect as result?**

Insights to be automagically produced

**Any other remarks**

for standard capabilities insights are produced as expected.

**Comment by swttt** [comment]
Same here :(
Thought it was in the last fw update tho (not sure why, think i read it somewhere)

**Comment by WeeJeWel** [comment]
This will be added soon!

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
