### ISSUE TITLE
App store: Send notification to dev on comment in app store

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#764]
No notification / indication is visible for a developer of an app on new comments in the app store. 
I would like to request this feature. 
This feature would enable me to support users and answer questions quickly.

**Comment by joachimroeleveld** [comment]
This is indeed a good suggestion and on my to-do list for a while. This will be implemented in the future.

**Comment by joachimroeleveld** [comment]
I just deployed this feature to production! Please let me know if you run into issues.
