### ISSUE TITLE
[Insights] Changing graph 

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#768]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Zoom after changing different graph values

**Steps to reproduce**
1. Click a value to view an graph
2. Select a pre-saved template

It's important, for the reproduction, to have a graph on display and after that change to a pre-saved template or else the 'bug' doesn't show.
It doesn't matter if you switch between templates or only select 1 value and switch to a pre-saved template.

**What was the result?**

The text appears stating you have to open a log on the left side for the graph to show (see attached picture below)
Also your unable to zoom with your mouse on a specific area in the graph.

![insights-bug](https://cloud.githubusercontent.com/assets/15921016/17462338/f684fcd0-5ca9-11e6-894f-c29bd06887ec.png)

**Comment by WeeJeWel** [comment]
I cannot reproduce this issue, so I assume it has been fixed sometime last year :)
