### ISSUE TITLE
[Insights] [Feature request] Clear current graph button

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#769]
**What is your Homey version (Settings → System)?**
0.9.2

**What do you want to achive?**
Switch to different log items (without using pre-saved logs), without having to manually de-select all previously selected log items.

**What is the current procedure to archive the result?**
1. Select multiple logs on the left side
2. Deselect multiple logs on the left side
3. Select other multiple logs on the left side

**What is the desired procedure to archive the result?**
1. Select multiple logs on the left side
2. Click clear graph button
3. Select other multiple logs on the left side

**Comment by WeeJeWel** [comment]
This won't be added. As a shortcut, click the Log group to select/deselect all at once.
