### ISSUE TITLE
No documentation for setting the units of custom capabilities in mobile card

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#770]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

I made two custom capabilities, but am unable to set a unit for it (m3 for gas usage capability)

_Please include detailed steps how we can reproduce the issue_

How/where can I set the unit? It is either not possible or undocumented.

**What was the result?**

The custom capability is shown without a unit (m3 in this case)

**What did you expect as result?**

Be able to set a unit as is displayed for standard capabilities

**Any other remarks**

I also made a boolean custom capability (off-peak tariff). When this is true (yes) the icon and text is shown in red and is blinking. Although this seems right for intrusion alarms or similar, I would like to be able to set it always to be non-blinking. Preferably also be able to set the colour myself (green for true, red or black for not true)

**Comment by gruijter** [comment]
I tried some stuff and foud out I can set the unit, iti s just not documented afaik.

`"measure_gas": {
      "type": "number",
      "title": {
        "en": "Gas",
        "nl": "Gas"
      },
      "desc": {
        "en": "Gas usage (previous hour)",
        "nl": "Gasverbruik (vorige uur)"
      },
      "units": {
        "en": "m\u00B3",
        "nl": "m\u00B3"
      },
      "getable": true,
      "setable": false
    }`

**Comment by caseda** [comment]
Then they changed it very recently, it was documented before in the custom capabilities example. 

But it's not that hard to press "see raw" and see how athom did it in the standard capabilities

**Comment by WeeJeWel** [comment]
Updated the docs! :)

**Comment by gruijter** [comment]
Thx!
