### ISSUE TITLE
Unable to set color or non-blinking for custom boolean capability icon in Mobile card

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#771]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

I made a boolean custom capability (off-peak tariff) and made a Mobile device card for it.

*Please include detailed steps how we can reproduce the issue*
^^

**What was the result?**

When the value is "true" (yes) the icon and text is shown in red and is blinking.

**What did you expect as result?**

Although blinking red seems right for alarms, I would like to be able to set it always to be non-blinking (since off-peak is a non-alarm state). Preferably also be able to set the colour myself (green for true, red or black for not true)

**Any other remarks**

**Comment by swttt** [comment]
Would be indeed nice if it could be implemented. A special type for alarm maybe?
For now you could use a string, but then you can only see if its offpeak by reading te text and not looking at the icon.

**Comment by nlrb** [comment]
Additionally, it would be nice if the blinking could be inverted if needed (i.e. when the value is false).

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

```
             "mobile": {
	            "components": [
				    {
					    "id": "sensor",
					    "capabilities": [ "my_alarm" ],
					    "options": {
						    "my_alarm": {
							    "noblink": true,
							"invert": true
						    }
					    }
				    }
	            ]
            }
```

**Comment by nlrb** [comment]
![Love](http://icons.iconarchive.com/icons/designbolts/free-valentine-heart/128/Heart-icon.png)

**Comment by gruijter** [comment]
Can't wait to see this working in 0.10.1 :) :+1:
