### ISSUE TITLE
[insights] Edited standard capability units not changing in Insights

### ISSUE THREAD

**Issue by swttt** [athombv/homey#772]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Standard capability to report in insights with "custom" units. Now the power_meter displays wh, but i want it to report kwh.

I have changed the standard capability in the app.json.

**What was the result?**

It reports the standard Wh.

**What did you expect as result?**

To report it as the custom set unit Kwh.

**Any other remarks**

...

**Comment by gruijter** [comment]
Same for me. I want/need the unit of power to be kWh in stead of wH since kWh is commonly used in households. I'm fine with being able to change the units myself in app.json but It should then also change the unit in Insights

**Comment by gruijter** [comment]
I found another problem with overriding the units in app.json. This only works right after pairing. If the app resets (e.g. stop/start, reboot) the changed values will reset to default. Thus it will show Wh again also in the device card. You have to delete the device and pair it again to change it to the value defined in app.json, (and lose all device logs in the process).

**Comment by swttt** [comment]
Did you test a reboot? It might reset on reboot as well then, since that stops and starts the app.

**Comment by WeeJeWel** [comment]
What's the name of your custom capability?

**Comment by swttt** [comment]
In this case i edited the power_meter with kwh instead of the standard wh.

**Comment by WeeJeWel** [comment]
So the id of the capability is also `meter_power`? I think that might be the issue.

**Comment by swttt** [comment]
So it isn't possible to edit parts of standard capabilities?

**Comment by WeeJeWel** [comment]
No, but you can create a custom capability that is very similar of course :)

I'll add to the validator a check for conflicting capability names.

**Comment by swttt** [comment]
The reason i used the standard capabilities because it supports automagic logging to insights 😀

It is working on the device card btw, just not in the insights logging.
Still feels strange tho, if i want power_measure for a device with hight power usage i need to create a custom capability with the units set to kwh. Instead of just edit the capability with the correct units 😀

Not that it makes any difference tho, just feels strange.
Just don't add the validator before adding to automatic logging to insights for custom capabilities. Else i need to change my code twice :D

**Comment by WeeJeWel** [comment]
In 0.9.3 the system capability `meter_power` has been updated to kWh instead of Wh, and in an upcoming update custom capabilities will also be logged 👍

**Comment by gruijter** [comment]
In 0.9.3 the custom capability is still not logged for insights.....

**Comment by WeeJeWel** [comment]
Correct, will be fixed in 'core upgrade'

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
