### ISSUE TITLE
[Z-Wave] Multi instance devices, reporting not working for second endpoint

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#773]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Receive reports for 2nd node on my multi node device 
(Z-Wave.Me dual load switch)

**What was the result?**
No reports are being received for node 2.
Node 1/main device is receiving reports as expected.

**Comment by RobinBol** [comment]
Do you see incoming reports in the logging (when debug is enabled)? 

Could you post a link to your repo?

**Comment by Inversion-NL** [comment]
Yes, Node1/main device reports are received and the device status is always up to date.

Github repo:
https://github.com/inversion-nl/me.zwave

Have been talking with Jeroen Vollenbrock about this (so you guys don't go and do stuff in duplicate).

**Comment by RobinBol** [comment]
Is there a reason you start counting your multi-channel nodes at 2?

```	"multiChannelNodes": {
				    "2": {
					    "class": "light",
					    "capabilities": [ "onoff" ],
					    "icon": "/drivers/ZME_05461/assets/channel2.svg",
					    "name": {
						    "en": "Z-Wave.Me channel 2",
							"nl": "Z-Wave.Me Kanaal 2"
						}
				    }
				}```

Might be related to that, have you tried it starting at 1? If that doesn't work I think we'll have to wait for Emile.

**Comment by Inversion-NL** [comment]
Yes, tried that. 
Device 1 is the same device as the main.
Switching the main device and node 1 has the same effect only node 1 isn't updated through reports (when using the physical device).

And up until yesterday evening I had both node 1 and node 2 but then I read Caseda's reply that it might not be implemented yet bij Athom, I started cleaning up my code, lol.

Forum post here:
https://forum.athom.com/discussion/1816/homey-light-switch-not-updated-although-reports-are-being-received#latest

**Comment by swttt** [comment]
Not looked into your code. But it just popped up to ask, device count doesn't start with 0? That happend to me once in a different situation tho :)

**Comment by Inversion-NL** [comment]
All my nodes are working and I'm able to switch the device. Only reporting isn't working.
I know that doesn't have to mean anything but just saying. 
I can test tonight.

**Comment by RobinBol** [comment]
Did some debugging here with the greenwave node 6, and it seems that I can not handle the: node.MultiChannelNodes['X'].CommandClass['COMMAND_CLASS_METER'].on('report'), reports either. Only the node.CommandClass['COMMAND_CLASS_METER'].on('report') comes in. Not sure if intended, will assign Emile to this.

**Comment by Inversion-NL** [comment]
Great!
Thanks.

Let me know when I should test again.

**Comment by jeroenvollenbrock** [comment]
@WeeJeWel Error seems to be caused by: 
```TypeError: Cannot read property 'CommandClassSupportedByValue' of undefined
at CommandClassMultiChannel.<anonymous> (node_modules/zwave/lib/Node/Node.js:158:9)
(full log at abrt/0.0.0/1471605930427)
```
Cannot reproduce with greenwave node 6. I suspect @RobinBol had invalid associations

**Comment by WeeJeWel** [comment]
Well, I fixed the crash, but the incoming data simply was corrupt.. or are there maybe some sort of dynamic endpoints?

**Comment by jeroenvollenbrock** [comment]
@Inversion-NL Could you send us the console output after pairing one of these devices with zwave debugging turned on

**Comment by Inversion-NL** [comment]
Hope to do this tonight @jeroenvollenbrock

**Comment by Inversion-NL** [comment]
Console output with debugging enabled:
https://gist.github.com/Inversion-NL/d803f268d88876a4e892ba50498243bf

**Comment by WeeJeWel** [comment]
I get the feeling that those devices don't completely follow the spec. Reports on multichannel nodes should work, and they do on many devices. What might happen is that your device sends an invalid multichannel node id with it's report.

Do you have a link to a webshop selling the device? I'll investigate using the Z-Wave sniffer what actually happens.

**Comment by Inversion-NL** [comment]
https://www.robbshop.nl/z-wave-schakelaar-duro-2000-met-2-uitgangen-2x1700watt-622

**Comment by WeeJeWel** [comment]
@stefanwitkamp can you order this device for testing?

**Comment by WeeJeWel** [comment]
@Inversion-NL we can't seem to buy it, because it's out of stock everywhere.

If you send it to us we could take a look at it! Maybe that's an option?

**Comment by Inversion-NL** [comment]
Oh, I'll have to get it out of the wall.
I'll think about it

**Comment by Inversion-NL** [comment]
I've managed to find one. I'll send it over to you guys.

**Comment by Inversion-NL** [comment]
Did you receive the device? The mail app stated it has been fetched last Monday.

**Comment by Inversion-NL** [comment]
@RobinBol Did you receive the device?

**Comment by jeroenvollenbrock** [comment]
@Inversion-NL: Thanks for sending it over! I've just checked the desk of @RobinBol, and it's there waiting for him. :)

**Comment by RobinBol** [comment]
Thanks for sending in the device! We have traced the issue and will try to fix the bug causing it. Will let you know once its fixed!

**Comment by Inversion-NL** [comment]
Great! Have fun 😁

**Comment by WeeJeWel** [comment]
Seems to be fixed :-) I don't really 'get' the Z-Wave.me device, but I see reports coming in ;)

**Comment by StraDijk** [comment]
Does this fix also this?
https://github.com/athombv/node-homey-zwavedriver/issues/12

**Comment by RobinBol** [comment]
@StraDijk not sure, might be, perhaps Emile could shed some light on this.

@Inversion-NL thanks for lending us the device to debug! Assuming that this is indeed fixed in 0.11.0 could you send me an email with the necessary information so that we can return the device to you?:)

**Comment by WeeJeWel** [comment]
@StraDijk most likely!

**Comment by Inversion-NL** [comment]
I'll leave it with you guys until version 0.11 is rolled out and I can confirm the fix :-)

**Comment by RobinBol** [comment]
@Inversion-NL do you have more of the same devices which you can use to verify the fix?

**Comment by Inversion-NL** [comment]
Yes.
Should the driver be updated for this to work?

**Comment by RobinBol** [comment]
As far as I know not, at least if the app/driver was built to support all channels.

**Comment by Inversion-NL** [comment]
Status reporting isn't working at all.
No changes are being visualized when using the first or second node (switch).
Anything I should or could do?

**Comment by RobinBol** [comment]
Just tested with your device, and the current state of the me.zwave app, and it works. I re-added the device, and pressed the grey buttons once (for the first channel) and these changes were updated in the mobile card, and pressed the grey buttons twice (for the second channel) and these changes were updated in the mobile card as well.

**Comment by Inversion-NL** [comment]
I'll pair the device again this evening.

**Comment by Inversion-NL** [comment]
Removed and paired the device again and reporting is now as it should!
Thanks guys!

Could you send it back to me?
I'm roadxy @ slack if you need my address details.
