### ISSUE TITLE
No border for password field in device settings

### ISSUE THREAD

**Issue by Sillyjan** [athombv/homey#778]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Change device settings

*Please include detailed steps how we can reproduce the issue*
Create a device with settings type 'password'
The editing the settings from the device

**What was the result?**
Password field is not visible but editable

**What did you expect as result?**
Password field that is visible

**Any other remarks**
Not sure if its by design or a bug

**Image**
![screen shot 2016-08-10 at 00 20 09](https://cloud.githubusercontent.com/assets/20732728/17535805/19298ee8-5e91-11e6-9529-500e3c2a1cd9.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.9.3

**Comment by nlrb** [comment]
Confirmed fixed.

**Comment by Sillyjan** [comment]
Indeed fixed in 0.9.3. I'll close the issue.
