### ISSUE TITLE
End of setup: empty error pop-up

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#78]
Add the end of the setup procedure the following pop-up occurred.

![error1](https://cloud.githubusercontent.com/assets/11725674/12963675/4c0a6518-d04c-11e5-9630-08e9e39d8b5a.jpg)

**Comment by YoupHulsebos** [comment]
My popup wasn't empty. But stil unexpected. The page said done...

![homey exit setup](https://cloud.githubusercontent.com/assets/425959/12980361/726f72e4-d0dc-11e5-9527-1fddb8d8a239.PNG)

**Comment by nlrb** [comment]
@WeeJeWel : did you fix this? If so please close the issue. I'm not planning to test it by doing a new install 😄 .

**Comment by bvdbos** [comment]
I did a few re-installs and didn;t see this message :-)

**Comment by uNiiek** [comment]
I did a fresh install. The empty error pop-up did not come back with me.
