### ISSUE TITLE
[KaKu] ACM-300 support and fix ACD-300

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#780]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Dim my Klik Aan Klik Uit ACM-300 and ACD-XXX like it was before the big 433Mhz update
Both have the same problem of dimming

**What was the result?**

After my holiday my Homey was updated, all my KaKu devices where gone. Oké so be it.
I've added my ACM-300 as ACD-XXX because it has the dim functionality. Devices where added successfully.
The dim levels are very awkward. I'm started with a demo flow and set the lights on 0% all off = OK
Then the first 3% are the same = Very low = OK
Then 4% till 9% are the same = Very Bright = NOT OK
From 10% there is a random brightness level. Not random every time, but they have a consistent random level.
For the rest i didn't test. But yesterday there was a big difference when it was dark. 16% very bright (No relax mode) 15% was almost dark the same as 1%.

**What did you expect as result?**

Dimming a percentage higher will result in a little bit brighter, dimming lower less brighter. But consistent and homogeneous.

**Any other remarks**

For Domoticz it worked perfect. Before I've got my Homey the dimmers worked perfect. I created an excel sheet with the dim levels according to the percentages. The result that every 6,64285714285714% the dimmer have a step brighter.

But before the big KaKu and other 433Mhz updates my dimmer was added correctly and I could dim homogeneous

Both my 2 ACM-300 and my ACD-300 have the same problem

**Comment by jeroenvollenbrock** [comment]
Hi There, I've just published KaKu version 2.1.2 in the app store, which solves this issue.
