### ISSUE TITLE
[KaKu] ACM-300 and ACD-300 fix level reset

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#781]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Conform #780 there is another issue. After update the KaKu app everything worked well.
Richt now I want to dim homogeneously.
I've have a flow with 30 cards to dim from 0% till 30%
In #547 is mentioned this can be done without 30 cards, but right now I'm deal with 30 ore more cards

**What was the result?**
After every step the light is reset. Before KaKu 2.x.x the lights went smoothly up or down.
The first percentages it's reset to dark, when it's higher its very brightness. 

**What did you expect as result?**

After the dimmer in- or decrease the power it's should not reset the light and go to the given level.
So I've a flow with 30 cards that trigger every minute, so in 30 minutes (average twighlight time) my lamps are from 0% to 30% so I don't recognize it's dark.

**Any other remarks**

Thanks for your great work!

**Comment by jeroenvollenbrock** [comment]
Can you confirm if this has been fixed in 2.1.2? I don't really understand the issue you're describing, is this a different issue than #547? Currently, dimming with a time interval is not possible, except by creating multiple cards. One flow card to dim over a certain time interval is scheduled for a future update of homey (not the KaKu app).

**Comment by caseda** [comment]
For the time being you could use the same principle I showed on the forum for a different, but reoccurring thing as well:

https://forum.athom.com/discussion/comment/29179/#Comment_29179

You will only need 2 flows,
1 to set the amount (a counter/number) you want to dim;
The other for looping through a flow to lower that counter by one and dim also
If you want the diming to go slower just use a longer delay when lowering the counter

**Comment by kerkenit** [comment]
The issue in #780 is fixed. 
My flow is as following. On my conditions (dusksensor turn on) this flow is triggerd. Every 1 minute the percentage of the dimmer goes 1% up.
The issue is that every minuten when it's triggerd to incerease the lamp goes off and than goes to the correct level. The level issue in 2.1.2 is fixed. But when I compare it before 2.x.x the lamps goes smoothly 1 % up. Right now it's first dark and than back to the correct level. After a couple of percentages it's not first dark anymore but verry bright and than the correct level.
When I'm home a can create a movie of my lamps
![dimmer](https://cloud.githubusercontent.com/assets/13370203/17588698/ec0d0070-5fd0-11e6-8da4-e333af989681.PNG)

**Comment by jeroenvollenbrock** [comment]
@BasKiers Kaku (new) dimmer driver always sends a regular on followed by a dimmer on.

**Comment by BasKiers** [comment]
Fixed in 2.2.1, Thank you for the bug report!

**Comment by kerkenit** [comment]
During the 0.10.0 update it worked perfect, but right now in v2.6 this issue is again there. I hope you can fix it again.
