### ISSUE TITLE
[Enhancement] Default notification high priority events

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#784]
**What is your Homey version (Settings → System)?**
0.9.2

**What would you like to achieve?**
I have 5 smoke sensors and 2 motion sensors.
For every device I have to create flows for smoke, heat, tamper and motion.

Wouldn't it be nice to have one place, somewhere in the core system, where you could specify the type of notification.
On every device there is a check mark which includes it.

**Comment by robertraaijmakers** [comment]
Any progress on this? My batteries drain within 3 months of all my Fibaro devices (and my Philiotech 4:1 sensor within two weeks) so notifications on when my battery devices get < 10% would be lovely. Instead of creating 20+ flows for this.

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/3470/app-blowfish-check-battery-levels-last-updates-capabilities-and-condition-for-lights-in-a-zone so this exists now?

**Comment by Inversion-NL** [comment]
Let's first create an user friendly version of it, have it in the store, test it and then close this issue :-)

**Comment by bvdbos** [comment]
fixed for 1.5?

**Comment by WeeJeWel** [comment]
Yep!
