### ISSUE TITLE
measure_temperature for socket device

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey#785]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Show temperature sensor from my Qubino Flush dimmers in a socket device as a capability

**What was the result?**

The temperature is shown in insights, but not visible in the device card in Chrome or mobile device

**What did you expect as result?**

Temperature value displayed in device card

**Any other remarks**

The Qubino z-wave flush devices can have a temperature sensor attached with a small jst-z to monitor temperature

**Comment by WeeJeWel** [comment]
wontfix, instead use class=other and define your own mobile card. Usually sockets don't have temperature sensors ;-)
