### ISSUE TITLE
No measure_battery displayed in thermostat device

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey#786]
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

I'm writing a z-wave app for the Dannfos Living Connect thermostat. It is a battery powerd radiator thermostat so battery status is required

**What was the result?**

The capability is shown in insights, but not visible in the device card within Chrome or mobile card

**What did you expect as result?**

Show battery status

**Any other remarks**

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
