### ISSUE TITLE
[Enhancement] Add sirene capability

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#787]
**What is your Homey version (Settings → System)?**
v0.9.2

**What did you try to achieve?**
Add a driver for a siren but there is no siren class.

**What was the result?**
Had to use the class 'other' since there is no siren device class.

**Any other remarks**
@jeroenvollenbrock suggested I should create a issue for this.

**Comment by WeeJeWel** [comment]
It's not a very common device so the `other` class is a pretty good solution :-)
