### ISSUE TITLE
Font used is hard to read

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#79]
The font in the default layout does not always render well. See below screenshot from a Windows 10 machine with Chrome Version 48.0.2564.103 m (zoom level 100%, Full HD screen). Letters like 'F', 'H' and 'Z' are not complete.
![rendering](https://cloud.githubusercontent.com/assets/11725674/12963782/e8a6d87a-d04c-11e5-8473-8d3cd2c4292a.jpg)

**Comment by 4tetra4** [comment]
I love it like this. Sharp modern, minimal. Don`t change it just add an option of larger fonts/elements for those who needs it.

**Comment by AndreSomers** [comment]
Seriously? You like seeing incomplete letters liek the H from "Home" and "Hallway" missing the horizontal bar, and the Z in "New Z Wave" being incomplete?

**Comment by goldenice** [comment]
@nlrb Could try and tell us if cleartype is turned off or on, and try switching it? Here is a guide on how to do this on Windows 10: http://www.isunshare.com/windows-10/turn-off-or-on-clear-type-text-in-windows-10.html

**Comment by nlrb** [comment]
ClearType was turned on. Also turning it off makes no difference.
Problem is related to the chrome flag 'Disable DirectWrite Windows', which was set to disabled. Setting it to enabled makes the font readable (but still a bit vague sometimes). It would be good to have a font that works with both settings if possible.

**Comment by WeeJeWel** [comment]
Should be no problem anymore. If anyone experiences this, please let me know.
