### ISSUE TITLE
[Suggestion] Patchnote section for AppStore Pages

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#790]
It would be nice to have a patchnote section for each App in the Appstore. Some already have one in the regular description field but some not. If there would be a section for this purpose I think more Devs would use it.

It's kinda hard to search for those informations for retail users (forums,github) and it would be nice if they are displayed.

**Comment by matjaz** [comment]
A simple `CHANGELOG.md` file would do the trick for starters, which can be rendered in app store.

**Comment by Inversion-NL** [comment]
That would be nice!

**Comment by bvdbos** [comment]
Since #1002 introduced appstore.md, isn't the rest up to the developers?

**Comment by TheMSB** [comment]
@jeroenvollenbrock I believe this issue can be closed since #1002, please confirm.
