### ISSUE TITLE
Feature Request meter_rain meter_gas as capability 

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#791]
**What is your Homey version (Settings → System)?**

0.9.2

add capabilities as developer to a rain meter from Oregon Scientific which has a rainrate and raintotal sensor output 

*Please include detailed steps how we can reproduce the issue*
'nan

**What was the result?**
null
...

**What did you expect as result?**

that in accordance with electricity (Power)capabilities there is a measure_gas And a meter_gas , a measure_rain AND a meter_rain. the same issue is valid for  water .
...

**Any other remarks**

...

**Comment by swttt** [comment]
As far as I know the custom capabilities are able to function just as standard capabilities in the future. For now the custom capabilities work but don't report to insights or create automatic flow cards. 

I would just add a custom capability with a custom mobile card and wait for future updates to support logging to insights.

**Comment by nattlip** [comment]
i discussed with some developers a lot of problems with the custum capabilities which costed them a lot of time. The Athom guys are nice but they stretchto infinity the word soon and i read today also the word shortly https://developers.athom.com/library/vectors/ : "Icon guidelines will follow shortly."

**Comment by swttt** [comment]
Still you could ask them in Slack (and other issues on github give the solution to the icon problem). I am using custom capabilities myself in the sabnzbd app without problems. The only downside at the moment is that it's not reporting to insights and i have to create the flow cards myself.

In short: I think custom capabilities are the way to go in your situation, it does work as it should.

And on a note: Custom capabilities got expanded big time lately and are finally useable. It's not that that text in the docs are standing there for a few months, but got added 2 weeks ago or so. I am glad how they are working now and can only give a thumbs up to Athom.

**Comment by nlrb** [comment]
I also use the custom capabilities for now, but do support the request! The set of default capabilities is 'a bit strange'. These ones should indeed be default for a home automation platform.

**Comment by WeeJeWel** [comment]
I've added meter_rain as of 0.9.3

**Comment by nattlip** [comment]
@WeeJeWel great
