### ISSUE TITLE
Inactive devices in pull down menu in the flow editor (due to name changes of the mobile device)

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#793]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

See only the mobile devices in the flow editor which are actually active

**What was the result?**

I changed my phone name a few times during previous Homey flow editor testing. Mostly because I was not able to see which was the active device because of all the duplicate names in the pull down menu. However, the duplicate names issue is now fixed but I still have three inactive devices because of the name changes I did which I'm not able to get rid off. 

See figure below for the devices in my pull down menu
![image](https://cloud.githubusercontent.com/assets/17165733/17752096/8dfe32e8-64ca-11e6-8500-a5f48e07a7e5.png)

**What did you expect as result?**

Only have the mobile device "Galaxy S6 Jesper" in the pull down menu because that's the only active device.

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Try removing your old devices here: https://my.athom.com/#/phones
Add your new device by logging out & in on your phone in the Homey app.
