### ISSUE TITLE
Device settings need Dutch translation

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#794]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Update device settings while the language is set to Dutch.

**What was the result?**

Generic text strings are still displayed in English.

**What did you expect as result?**

All text in Dutch.

**Any other remarks**

- Title ('- Settings')
- Button 'Save settings'
- Message 'Device settings have been saved.'

**Comment by Tweake** [comment]
Fixed, translations will be included as of v0.9.3. Thanks for reporting the issue :)

**Comment by nlrb** [comment]
Confirmed, thanks!
