### ISSUE TITLE
Mobile card horizontal scroll bar should be across all components

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#795]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Create a mobile card with an icon, ternary, picker and 4 sensors.

**What was the result?**

The horizontal scroll bar is only used for the 4 sensor values. However, there was already no space left for the sensor values.
![silly_mobile_card](https://cloud.githubusercontent.com/assets/11725674/17769901/43c9ebb0-653b-11e6-8a7b-9b8c647ca1b6.png)

**What did you expect as result?**

That all elements on the mobile card can be viewed.

**Any other remarks**

In the mobile app the picker is smaller (text is shortened & becomes unreadable). In the web browser the whole picker text is show, which leaves less space for the rest.

**Comment by WeeJeWel** [comment]
Fixed in 0.9.3

**Comment by WeeJeWel** [comment]
You're pushing the limit here though ;-)

**Comment by nlrb** [comment]
Actually, I was thinking about adding another sensor or two ;-). Looking forward to 0.9.3!

**Comment by WeeJeWel** [comment]
Haha! Sensors are scrollable within one component so that's fine. Just more
components would make it really cluttered!

**Comment by nlrb** [comment]
Helaas is het er niet beter op geworden met 0.9.3 :-1: . Eerst was er nog iets te scrollen - nu zijn de sensors totaal niet meer zichtbaar...

![image](https://cloud.githubusercontent.com/assets/11725674/18008899/3e4b97ae-6baa-11e6-9f5d-d8062bc5f809.png)

**Comment by WeeJeWel** [comment]
Is this still happening? Should've been fixed somewhere in 1.0.5.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.
