### ISSUE TITLE
Introduce a propper/reliable UX for removing "dead/orphan" devices

### ISSUE THREAD

**Issue by freemann** [athombv/homey#796]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Remove a "dead/orphan" device from Homey.

**Please include detailed steps how we can reproduce the issue**
One of my Z-Wave module paired as "unknown Z-wave device", while there's a installed App for it. So i tried to remove it, Homey returned:
_The node has been reset, but was not in this Z-Wave network.
No Homey devices have been removed._

**What was the result?**
Now 2 "dead/orphan" device which I can't remove from Homey.
...

**What did you expect as result?**
When I click on "remove device", the device actually will be remove and so a proper/reliable UX on this point.

**Any other remarks**
![screenshot - 19_08_2016 10_31_22](https://cloud.githubusercontent.com/assets/601053/17803685/3102f590-65f8-11e6-8e5a-64b02c77a4bf.png)

**Comment by WeeJeWel** [comment]
Multichannel endnodes can now be removed seperately

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
