### ISSUE TITLE
(re-)introduce the X time before sunset/sunrise time card

### ISSUE THREAD

**Issue by freemann** [athombv/homey#797]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Turn lights on/off 15min. before sunset/sunrie

_Please include detailed steps how we can reproduce the issue_
looked for a flowcard which made this possible.

**What was the result?**
didn't find a card, where it was available on 8.X.X firmwares.

**What did you expect as result?**
Find a Flowcard again to switch lights more before sunset/sunrise.
Or another way to start thing XX minutes/hours before .... 

**Any other remarks**
there are more use cases such as a warning 15min. before an appointment, an push message 10min. before a favorite TV program, etc.

**Comment by acefed** [comment]
As a (ugly but functional) workaround until this is possible, you can set a delay of (24h - requested time interval) on the action card, using the sun rise/set of the previous day.
