### ISSUE TITLE
Make power usage available for all Z-Wave virtual device types.

### ISSUE THREAD

**Issue by freemann** [athombv/homey#798]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Act on the power usage of a Z-Wave kettle/light/fan/heater/etc module.

*Please include detailed steps how we can reproduce the issue*
Add a Z-Wave module, set it as a kettle, go to Flow Editor, search for a card which makes it possible to act on power usage.

**What was the result?**
Can't find a card like that.

**What did you expect as result?**
find a card to act on power usage.

**Any other remarks**

**Comment by WeeJeWel** [comment]
Added for most virtual device classes. Kettle is still 'todo'.
