### ISSUE TITLE
[Enhancement] Change error message when unable to send log while not connected to Athom Cloud

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#800]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Send log to Athom while not connected to Athom Cloud

**What was the result?**
Unable to send log.
But the issue here is the message that appears after a very long period of time.

![image](https://cloud.githubusercontent.com/assets/15921016/17808234/5b9efeae-660f-11e6-81f0-6ba2a5bbd62d.png)

**What did you expect as result?**
More user friendly message other then 'true'

**Any other remarks**
Nope.

**Comment by WeeJeWel** [comment]
Fixed in 0.9.3 - logs are not sent through Athom Cloud anymore

**Comment by Inversion-NL** [comment]
@WeeJeWel 
Did you change the error message as well?

**Comment by WeeJeWel** [comment]
yes
