### ISSUE TITLE
Z-Wave Tamper capability on deviceCard not updating properly

### ISSUE THREAD

**Issue by freemann** [athombv/homey#801]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Tamper alarm on device card go automagicly off after triggering tamper alarm.

**Please include detailed steps how we can reproduce the issue**
Open device card of the Philio PSM02, Trigger a tamper alarm on a Philio PSM02, on the device card Tamper Alarm will flash red, leave device card open and wait 5min. 

**What was the result?**
After the 5 min. Tamper alarm is still flashing red, but after closing and re-opening the device card Tamper alarm is "off" (marked with "-").
So looks like Tamper alarm is not auto updating, while temp/lux/motion are doing things right.

**What did you expect as result?**
Tamper alarm stops flashing red after XX min/secs.

**Any other remarks**

**Comment by WeeJeWel** [comment]
Which app are you using for this device?

**Comment by freemann** [comment]
My own app.

**Comment by WeeJeWel** [comment]
Which of mine posts are you refering to?

In case you need help with App development, please refer to Slack. This does not seem to be a Homey problem, more a (I guess) missing realtime event :-)

**Comment by freemann** [comment]
Edited a wrong comment.

Its a Z-Wave app, does the support Realtime?

**Comment by WeeJeWel** [comment]
Yes of course :-) That's what the REPORT parser is for.

I'll close this issue, please refer to Slack of the Forum for development talk.

**Comment by freemann** [comment]
Totally no help and/or knowledge about this matter on slack. Asked it multiple times and even Athom is silence. Very disappointing that there's no help, docs, knowledge on this issue.

**Comment by freemann** [comment]
Issue solved after the update to 0.9.3.
Thanks for all the help!

**(its a big shame that it's being closed as not being a issue and after an firmware update its spontaneously fixed).**
