### ISSUE TITLE
Switch dead/orphan device results in locking Z-Wave chip

### ISSUE THREAD

**Issue by freemann** [athombv/homey#802]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
-

*Please include detailed steps how we can reproduce the issue*
Create a dead/orphan device (add a Z-Wave device and reset the module manually).
Now Homey things the device is still there, open the device card, click the switch on the Device Card and after that try to switch a known working Z-Wave device.

**What was the result?**
After clicking the switching on the dead device, other device also not react on interaction. Take a look at the Z-Wave settings page and all buttons are gray (disabled).

**What did you expect as result?**
A lock Z-Wave chip.

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Does the setting page remain grayed out, or does it become available again after a while? I think Homey is trying to talk to your dead device, which locks the zwave chip until the device responds or a timeout occurs.

**Comment by freemann** [comment]
Chip/buttons come available after XX seconds. And it indeed looks like Homey is trying to talk to the dead device.

**Comment by WeeJeWel** [comment]
In that case, this can be closed. It's simply how Z-Wave behaves :)
