### ISSUE TITLE
Random time in flowcards not working

### ISSUE THREAD

**Issue by freemann** [athombv/homey#803]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Lights go on randomly 

**Please include detailed steps how we can reproduce the issue**
Create a flow, add some light related flow cards to turn on the lights and followed Emile's instructions (https://forum.athom.com/discussion/comment/25832/#Comment_25832) with the idea the light turn on randomly between "3,15"min.

**What was the result?**
The lights go on exactly on the trigger and not taking the randomly settings in account. 

**What did you expect as result?**
The lights go randomly on. 

**Any other remarks**
Here I created a test flow;
![screenshot - 20_08_2016 00_09_01](https://cloud.githubusercontent.com/assets/601053/17825683/6ba00e28-666a-11e6-8b3b-e6707ebd7997.png)
The light go on,time after time, 3secs sharp after pressing the KaKu trigger button. It never takes longer then 3 secs for the light to go on.

**Comment by WeeJeWel** [comment]
Use a `-` not `,` :-)

**Comment by freemann** [comment]
will try.
