### ISSUE TITLE
Search in "Add device" doesn't work with uppercase

### ISSUE THREAD

**Issue by freemann** [athombv/homey#805]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Search for "Aeotec" and get the App "Aeotec" as result.

**Please include detailed steps how we can reproduce the issue**
Type "Aeotec" and "aeotec"

**What was the result?**
No search results for "Aeotec" where "aeotec" show the app.
So the search with Capitals doesn't work.

**What did you expect as result?**
"Pairing Wizard"/"Add device" showing the app "Aeotec" when user search for "Aeotec" and "aeotec"

**Any other remarks**

**Comment by joachimroeleveld** [comment]
This happens when doing a local search (Installed on Homey).

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
