### ISSUE TITLE
add mute/unmute card for media

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#809]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Stop radio playing when I say "OK Homey" so it can start listening. After listening unmute media

**What was the result?**
There's a card "when Homey starts listening" and "when Homey stops listening" and I can set the volume with an action-card. Mute/Unmute is missing so no way to get back to your old volume-setting.

**Comment by TheMSB** [comment]
@bvdbos Could you post a screenshot of the flow(s) that you are using? It might illustrate your problem better.

Am I wrong in assuming that the `Pause` and `Resume Playing` cards cannot satisfy your need?

**Comment by bvdbos** [comment]
Ah, was looking in the "loudspeaker" cards but it's the media-cards where pause/resume (better then mute/unmute) are...
