### ISSUE TITLE
Homey does not remember Z-Wave state

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#810]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

I've added my Fibaro Relay as a basic device in Homey (not app related). I've noticed yesterday evening that Homey does not remember it's device state, not sure if this is intended behaviour?

Uptime on 0.9.2 is 813653, could this play a role?

**What was the result?**

Device state is wrong in Homey, the device could be on while the given status is off.

**Comment by jeroenvollenbrock** [comment]
Does this occur across reboots?

**Comment by WeeJeWel** [comment]
So when you open/close/open the mobile card the state differs?

**Comment by Arjanvde** [comment]
Yes it does.

**Comment by jeroenvollenbrock** [comment]
Could be related to #811

**Comment by WeeJeWel** [comment]
Fixed in 0.9.3

**Comment by Arjanvde** [comment]
Thanks, nice job!

**Comment by WeeJeWel** [comment]
Thanks for reporting :)

**Comment by Arjanvde** [comment]
Fixed
