### ISSUE TITLE
Add "hint" to driver>settings page through app.json

### ISSUE THREAD

**Issue by freemann** [athombv/homey#814]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**
Add a hint to Device Settings page, just like the hint for Z-Wave settings/parameters.

**Please include detailed steps how we can reproduce the issue**
Add "hint" to driver>settings in app.json

**What was the result?**
The hint doesn't appear in the Settings page of the device.

**What did you expect as result?**
the small exclamation mark on the right of the settings input field.

**Any other remarks**

**Comment by WeeJeWel** [comment]
You can add this yourself as well! :-)

```
"id": "my_setting",
"type": "text",
"hint": { "en": "My hint" }
```

**Comment by freemann** [comment]
At first it didn't work, now its working :+1: 
thanx for helping and closing :)

:heart:

**Comment by freemann** [comment]
Should I create a issue to update these docs or is this comment also doing it?
