### ISSUE TITLE
Set rate limit for Insights from devices

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#816]
0.9.2

save nummerical device capabilities like temperature humidity  watt kwatt with realtime in the driver

i get new values each 15 seconds from ie plugwise server or oregon weather sensors. 

ik looks to me that the dbase size of homey has a limit and that limit will be reached before a year . i have 56 circles and 4 thermometers to store for now. 

with all the api changes and broken apps after updates this is not an issue now. Insights can show the data for 365 days at most and it will be a problem in the near future i hope for athom. 

i suggest not to use X%y == 0  but to use the average of 15 minutes

...

**Comment by WeeJeWel** [comment]
This won't be implemented because missing values will result in unreliable charts, but more selective Insights removal and data persistence has been added some time ago.
