### ISSUE TITLE
Settings get lost at random moments.

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/homey#817]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**
Having information saved in settings 
*Please include detailed steps how we can reproduce the issue*
For some reason settings get lost in V0.9.2 (and maybe also 0.9.1). This happens with Better Logic and also with the count down app

**What was the result?**
Settings get lost

**What did you expect as result?**
Stored Settings

**Any other remarks**
Not sure what happened. But for some reason settings get lost at random moments.
...

**Comment by nattlip** [comment]
are they device settings or app settings ? Homey has 2 kind of settings.

**Comment by PatrickSannes** [comment]
I think app settings. I use this call: Homey.manager("settings").get('variables');

**Comment by nattlip** [comment]
yes that are app settings. i know for the settings of the plugwisesource  app that they work in 0.9.2 .  9.1 i dont know, but i had to reinstall the app , reinstall devices to get it to work after 0.9.2 but i can still use the setings but had to fill them in again because of the fresh reinstall.  in 0.9.2 i got a traffic sign before my app in homey settings apps which means it crashed.

**Comment by MdeRhoter** [comment]
Cold reboot: all variables gone
Recreated them, twelve hours later at least one has disappeared again.

Weird, since I remember they were saved to disk when this last happened (0.8.3x I think).

**Comment by MdeRhoter** [comment]
Variables still disappear, not only Better Logic but also Countdown timers.

Funny thing, when a variable disappears and I re-create it, that seems to revive the old one. I then have two variables of the same name. If I edit their values in the settings page, both settings edit at the same time (so if you increase a number value with the little arrow up, you see the numbers increase for two variables simultaneously).

**Comment by MdeRhoter** [comment]
PTP -> all my Countdown timers gone

**Comment by WeeJeWel** [comment]
I've reinforced the settings storage in the upcoming Homey update. Should be fixed, but don't expect Homey to rememver all settings if you keep pulling the plug. There's always a delay between setting a variable and writing them to the flash memory.

**Comment by MdeRhoter** [comment]
These were not just settings that disappeared, but *all* variables. If unflushed data hasn't made it to flash yet when power is lost, I can understand a single variable may not have the correct value, but losing all 50+ variables?

**Comment by WeeJeWel** [comment]
They're stored in 1 json file, so that's why :)

**Comment by MdeRhoter** [comment]
How would that get wiped? Does it re-create the file each time? Is it application specific or would every app potentially be subject to this due to power loss?

**Comment by PatrickSannes** [comment]
Do all settings of all apps get stored in 1 json file or is it a file per
application?

**Comment by bvdbos** [comment]
I guess the latter? Or else all settings would have been lost, not just the settings of the BL-app and countdown-app?

**Comment by freemann** [comment]
Apps are sandboxed, would be strange if the use a shared "space".

**Comment by jeroenvollenbrock** [comment]
Can anyone confirm if this issue is resolved in 0.10.1?

**Comment by MdeRhoter** [comment]
I've pulled the plug many times yesterday (0.10.0) and today (0.10.1) and as far as I can tell zero BL variables or Countdown settings disappeared.

**Comment by MdeRhoter** [comment]
Nope, just had at least 2 BetterLogic variables gone missing - I can't quite pinpoint when they went, but yesterday was a lot of PTP, so my best guess would be then.

**Comment by WeeJeWel** [comment]
Should be fixed in 0.10.2. It was a combination of bugs working together :) Now the settings management is really, really robust

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
