### ISSUE TITLE
Newly added devices won't show up automatically in Android App

### ISSUE THREAD

**Issue by freemann** [athombv/homey#818]
**What is your Homey version (Settings → System)?**
0.9.2/2.2.7-55

**What did you try to achieve?**
Add a new device to Homey and see it appear in the Android App automatically.

**Please include detailed steps how we can reproduce the issue**
Open Android App, go to the zone where you're going to add the new device(s).
Go to Homey and pair the new devices in that zone.

**What was the result?**
Device(s) paired, but not showing up in the Android app. Switching zone(s) wont help, the new device(s) wont show up.
Only after killing/stopping and launching the App again, make the device appear.

**What did you expect as result?**
The device show up automatically in the Android app after the been paired successfully with Homey.

**Any other remarks**
Ask on Slack for other with this issue; no result.
Search Git for (open) issues related to this one, but couldn't find one.

**Comment by joachimroeleveld** [comment]
Has been fixed in the new release (2.4.7)
