### ISSUE TITLE
Device order changes to last updated app

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#819]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

The way devices are sorted in the Zones & Devices screen is based Alphabetically by the last updated app.  In my Case KaKu is updated the last and therefore the KaKu remote is positioned at the last position. As soon as I reorder the devices and refresh the screen, the device order is back to the way Homey sorts the devices (alphabetically by the last updated app)

![device order](https://cloud.githubusercontent.com/assets/17526110/17935754/b9bf1bfc-6a1c-11e6-8265-7950343e259c.png)

If the Fibaro app is updated again, all wall plugs will be moved to the last position and sorted alphabetically.

**What was the result?**

Devices are now changing from position.

**What did you expect as result?**

Devices not to be resorted after an app update.

**Comment by WeeJeWel** [comment]
Fixed in 0.11.0!
