### ISSUE TITLE
Ledring too bright

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#82]
The ledring on the Homey is very bright, which is not good for the WAF. Please make the level adjustable, just like the pattern is.

**Comment by Omemanti** [comment]
yeah, though I let the lights on downstairs, so I went looking, it was homey that lid up the whole room.

It would be nice to put homey to sleep when you ask him to. "good night homey" => LED ring turns off/dims down.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18. Led ring brightness is adjustable from Settings, and Flow
