### ISSUE TITLE
Have a "device_add_titel" tag

### ISSUE THREAD

**Issue by caseda** [athombv/homey#820]
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Have a "device_add_titel" tag in the devices driver (app.json).
That way you can specify a titel/name that gets shown in the "Add Device Popup" but have alternate (by a little) device names on the added devices.
Example: for Fibaro FGS-222:
device_add_titel: Fibaro Double Relay.
name: Fibaro Double Relay, Main Device/Relay 1 (for device 1)
MultiChannelNode[2].name: Fibaro Double Relay, Relay 2 (for device 2)
And leave away the MultiChannelNode[1]'s device completely

**What was the result?**
Now you need 3 devices to have the most "less" confusing situation.
IE: if main device is already called "Fibaro Double Relay, Main Device/Relay 1" people can mis-interpreted that only 1 relay is being able to be used.
... 

**What did you expect as result?**
see example above
...

**Any other remarks**
This is just one option on how to get better user experience with multichannelnodes, rather have a different option for just the z-wave driver?, then you can close this one.
...

**Comment by WeeJeWel** [comment]
Simply specify a `name` during pairing. For Z-Wave using ZwaveDriver, this does not work, but you could fork ZwaveDriver to add support for it!
