### ISSUE TITLE
Don't try to get a capability value without getter 

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#821]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Add a capability to a device that has no getter.

**What was the result?**

Opening the mobile card gives the error '{capability}:not_getable'.

**What did you expect as result?**

No error. Only capabilities with a getter should be displayed. Capabilities without a getter should make a custom mobile card if it needs to be displayed.

**Any other remarks**

The full mobile card is now not displayed due to one capability not being able to show a value.

**Comment by WeeJeWel** [comment]
Which mobile component are you using?

**Comment by nlrb** [comment]
Didn't specify one - it is independent of that. Later defined a mobile card with ternary component, same result.

**Comment by WeeJeWel** [comment]
It's not independent. A ternary *needs* a getter, otherwise it can't show a state.

What's your use case?

**Comment by nlrb** [comment]
As I said, I did not specify a mobile card yet.

`		"dim_oneway": {
			"type": "enum",
			"title": { "en": "X10 control", "nl": "X10 controle" },
			"values": [
				{ "id": "0", "title": { "en": "Brighten", "nl": "Feller" } }, 
				{ "id": "1", "title": { "en": "On/off", "nl": "Aan/uit" } },
				{ "id": "2", "title": { "en": "Dim", "nl": "Zwakker" } }
			],
			"getable": false,
			"setable": true
		}
`

Next to that, I'll need a ternary component that doesn't show any state :-).

Use case, e.g.
- controlling the heat of the fire place (flame up, down), but no way to get the state (one-way comms)
- controlling an X10 dimmer (dim, bright), but no way to get the state (one-way comms)

-

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
