### ISSUE TITLE
Greenwave Powernode only one Power reading, no instant power reading

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey#823]
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Installed zwave driver voor Greenwave Powernode 6

*Please include detailed steps how we can reproduce the issue*

After including the device within Homey, only kWh readings are visible. I tried to alter the driver because documentation of the greenwave device (http://cdn-reichelt.de/documents/datenblatt/R800/GREENWAVEPOWERTTECHNICALNOTE_2012_09_04_V4.28.pdf) states that both readings are possible and within the command class meter. 

**What was the result?**

No instant power reading

**What did you expect as result?**

Both values are possible, because other z-wave controllers are also able to do this.

**Any other remarks**

I know that in order to get the readings, polling the greenwave device is required!

...

**Comment by jghaanstra** [comment]
This is also reported in the repo of the Greenwave app: https://github.com/athombv/com.greenwavesystems/issues/3

**Comment by kasteleman** [comment]
Made some progress thx to WeeJeWel and Robin.
Modified driver.js Unfortunately not that stabile yet, needs some further testing. Perhaps to intensive polling?
[driver.js.txt](https://github.com/athombv/homey/files/460310/driver.js.txt)

**Comment by kasteleman** [comment]
Added additional errorhandling (THX Robin) and did a pull request for the greenwavesystems app.
Issue is thereby tackled!

**Comment by RobinBol** [comment]
Thanks for your contribution, updated app can be found in the app store!

**Comment by jghaanstra** [comment]
@RobinBol : why wasnt this pull request reviewed with this update: https://github.com/athombv/com.greenwavesystems/pull/4 

It's been pending for a month now and some (if not most) people now use a locally installed version of the app to have support for the Greenwave Powernode 1. It would be nice if this was merged as well.

**Comment by RobinBol** [comment]
Because this PR was a quick review, and automagically mergable. If will look at your PR probably coming week.
