### ISSUE TITLE
Red ring after unplugging from power source

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#825]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.9.2

**What did you try to achieve?**
I tried to move the Homey to another spot in the room.

*Please include detailed steps how we can reproduce the issue*
Unplug the device and plug it back in again

**What was the result?**
The Red Ring (of horror). After booting (which takes approx. 5 min.) you will get the red ring.
...

**What did you expect as result?**
The normal Homey-be-nice ring
...

**Any other remarks**
I moved it earlier and plugged it back in and did not encounter any problems but my hitrate is about 70/30 in favor of the red-ring. I unplugged it and tried again several times with the same result. Most of the time it worked after I kept it unplugged from power for about an hour and plugged it back in again, but another time this also didn't work. Then I plugged it in and plugged it out during the booting sequence. And after say 15 minutes I plugged it back in and it worked fine. It seems very random but I would really like to know how to handle this because I can see myself moving Homey somewere in the future and get really frustrated with the red ring.
...

**Comment by Inversion-NL** [comment]
You should create an issue for this but mail support@athom.com to have them help you with this.

**Comment by jeroenvollenbrock** [comment]
Please open a support incident by contacting support@athom.com.

**Comment by scanno** [comment]
@jeroenvollenbrock same problem here. had a red ring on .92. after pulling the plug again and rebooting it seems fine again.
