### ISSUE TITLE
Multiple device classes on a device

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#828]
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
I'm trying to add a device that have multiple capabilities from different device classes but it won't work.

**Please include detailed steps how we can reproduce the issue**
Add a device that looks like this
data: { id: '1' },
name: 'Test with multiply classes',
class: ['light', 'sensor'],
capabilities: ['dim', 'measure_humidity']

**What was the result?**
The device is added i get the result Error: invalid_device

**What did you expect as result?**
...

**Any other remarks**
...

**Comment by markaswift** [comment]
I hope this can be resolved, MySensors rocks!

**Comment by WeeJeWel** [comment]
Won't be fixed, please use the deviceclass 'other' :-)

Deviceclasses only provide default mobile components and speech input anyway, so when you're doing things this custom you're better off implementing them yourself.
