### ISSUE TITLE
Homey is too loud

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#83]
When Homey speaks, the voice is very loud. Please make that adjustable. At least as a setting, but preferably a bit more advanced as well, like based on ambient sound level.

**Comment by RuudBurger** [comment]
Agreed. Scared the hell out of me :D

**Comment by RuudBurger** [comment]
#106 assume this answers it

**Comment by WeeJeWel** [comment]
Fixed in 0.8.18
