### ISSUE TITLE
Add OS locale support (for Dutch)

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#830]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Get date/time information in users locale. I.e. `new Date().toLocaleString('nl')`.

**What was the result?**

Date/time information was returned in English, i.e. '8/28/2016, 12:53:00 PM'

**What did you expect as result?**

Result in Dutch locale, i.e. '28-8-2016 12:53:00'

**Any other remarks**

Expecting this to be part of the OS layer, hence the title.

**Comment by WeeJeWel** [comment]
Wontfix because Homey should always behave to the language the user has set. A workaround library could be used to achieve the same result for non-appstore projects :)

**Comment by daneedk** [comment]
That's not a very user friendly way of thinking. I have my language set to English but prefer to use dutch date/time/number notations. It's pretty normal to have regional settings next (and possibly different) to language settings

**Comment by WeeJeWel** [comment]
I agree with that. But that should best be fixed by a Homey-global option, so the app developer shouldn't worry about that. I'll add it to the list!

**Comment by daneedk** [comment]
Thanks for putting it on the list!

**Comment by magtimmermans** [comment]
What is the status for this?
