### ISSUE TITLE
Relative value control for lights

### ISSUE THREAD

**Issue by arnodeclercq** [athombv/homey#833]
**What is your Homey version (Settings → System)?**
0.8.39

**What did you try to achieve?**
I would like the possibility to change the value of hue, saturation, brightness and temperature relative to its current value. For example; add 5 % brightness, etc.
So it's possible to dim and increase lighting.

**What was the result?**
/

**What did you expect as result?**
/

**Any other remarks**
- Add the possibility to do this over a selected period of time; add 5% over period of 10 seconds. This option would be useful for sunset/sunrise stuff.

**Comment by jaimevisser** [comment]
You can manage this with better variables by keeping a set of variables (one for +5% and one for -5%) and have those be calculated whenever the value you want to adjust changes. You can then set the value to the +/-5% variable value. I'm doing this with a remote which can now increase or decrease the light level of a dimmer. Roundabout way until this is implemented with your suggestion but does work.

**Comment by bvdbos** [comment]
Close me, we have this now?

**Comment by WeeJeWel** [comment]
Yep!
