### ISSUE TITLE
Can't retrieve previous set colour in flow's

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#834]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

I've been adding a Fibaro RGBW to my existing flows. However, i cannot find the previous set colours anymore, once i click the colour picker, it opens at the default colour. I expected that it opened on the colour i've set previously.

![schermafbeelding 2016-08-29 om 21 01 16](https://cloud.githubusercontent.com/assets/17526110/18063717/71a515ba-6e2c-11e6-87d3-d02ee027b5d7.png)

**Reproducing.**

Simple, create a flow with a different colour than the Orange colour, save the flow and refresh the page. The selected colour is forgotten and you have to estimate the previous value.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.18!

**Comment by Arjanvde** [comment]
Solved.
