### ISSUE TITLE
Homey.get not throwing an error

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#836]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

in settings HTML to retrieve settings that do not exist (in below case 'data' is not defined)

_Please include detailed steps how we can reproduce the issue_

``````
      ```Homey.get('data', function(err, storedData) {
        if (err) {   ```
``````

**What was the result?**

App 'hangs', the function never gets executed, and no error is thrown.
...

**What did you expect as result?**

I expected to get an error
...

**Any other remarks**

Documentation on getters and setters is not consistent (or at least unclear) between Library (https://developers.athom.com/library/appsettings/) and API reference (https://developers.athom.com/api/). 

In library it states to use `Homey.get('data', function(err, storedData) {`
In API it states to use `.get( string name  // name of the setting )` So without function
...

**Comment by WeeJeWel** [comment]
What does the console say? You are running this in the browser (settings page html), right? :-)

**Comment by gruijter** [comment]
I don't know anymore. I made a workaround in the meantime.

I guess it's probably a documentations thing. From the documentation I simply don't understand how to use the callback function in the Homey.get. Where is the callback fired? And what type of error information can I expect to receive. Same for Homey.set. Also there the documentation is very unclear to me.

**Comment by WeeJeWel** [comment]
Updated the docs! :)

**Comment by gruijter** [comment]
Thx!
