### ISSUE TITLE
Z-Wave does not respond after (cold) reboot

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#837]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

It looks like that Z-Wave chip needs some additional time once Homey has started. If you give a Z-Wave a command during the time it starts Z-Wave, Z-Wave becomes unresponsive.

In my case, as soon as i saw the LED Ring in the Rainbow I gave Homey the command to turn my RGBW off with the given flow as an example. After that Z-Wave was unavailable, no error messages what so ever.

![schermafbeelding 2016-08-30 om 22 30 14](https://cloud.githubusercontent.com/assets/17526110/18105935/b6ac6ffc-6f01-11e6-9e66-da97c01a1f25.png)

**What was the result?**

Z-Wave sort of crashed, it doesn't want to listen to any triggers nor does it send out any given comands, not even if switched from the devices screen.

**What did you expect as result?**

Z-Wave to be working.

**Comment by WeeJeWel** [comment]
Can you do this while in Settings -> Z-Wave while the chip is unresponsive?

Open the Chrome console:

```
api('GET', '/wireless/zwave/state/', null, function( err, result ) { console.log( JSON.stringify(result, false, 4) ); });
```

And post a screenshot.

**Comment by Arjanvde** [comment]
@WeeJeWel I will try to replicate this bug tonight again and do as requested.

**Comment by Arjanvde** [comment]
Can't seem to reproduce this issue at the moment.

Closed for now.
