### ISSUE TITLE
Power cable makes Homey not set on its legs

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#84]
The power cable connector is quite stiff and straight. After plugging it in, Homey no longer can rest on its own legs. Instead, it rests on the power plug. This really detracted from the good feeling I got when unboxing Homey. It makes it feel cheap all of sudden. Please supply a power cable with an angle or one where this issue is otherwise solved.

**Comment by RuudBurger** [comment]
Came here to say this. As a hardware issue you need to fix this during packaging. 
![image](https://cloud.githubusercontent.com/assets/38136/12970912/b3e396e4-d094-11e5-8908-beb9c4e70828.jpeg)
![image](https://cloud.githubusercontent.com/assets/38136/12970913/b3e63aa2-d094-11e5-9a7f-ebd71996a555.jpeg)

**Comment by RuudBurger** [comment]
I'm on mobile so sorry for not editing my comment. 
This is more a quality issue maybe. It's a mini usb in staid of a micro usb. Making it feel like something from 10 years ago. If you compare it to the cable that comes with every phone the cable is thick has 2 of these coils on it. Overall it just feels shitty. And it's the first feeling when setting up homey which isn't what you want. 

So change to micro usb and get a modern cable.

**Comment by freemann** [comment]
Mini-USB is just so more robust then Micro, but a more flexible cable would be very nice and welcome.

(a lot of other, also very modern devices, are still shipped with Micro)

**Comment by Sateprikkert** [comment]
I don't care if it's mini-usb, micro-usb, more robust, or anything else; Athom should've noticed this. The fact that Homey can't stand on it's own legs because of the length of the cable is unacceptable for the final product.

**Comment by freemann** [comment]
What a :heart: :smile: 

You noticed the second part of my first sentence?
I'm on your side concerning the cable :smile:

**Comment by Sateprikkert** [comment]
To be clear, I'm not poking you :smile: No offence. 
I'm poking Athom for supplying a cable (no matter what kind of cable) that simply doesn't work for Homey's design. I had a major _"WTF-moment"_ after connecting the cable and putting Homey on our table.

**Comment by newmedia** [comment]
+1

**Comment by KrielkipNL** [comment]
+1

**Comment by hschenkelaars** [comment]
+1

**Comment by MuadDib007** [comment]
+1

**Comment by pkonings** [comment]
As my friend said yesterday (IT guy too and curious about homey): " I don't want to have my housecleaning person knock down this to easily". So :+1: please review a better solution/experience

**Comment by RemonBerends** [comment]
+1

**Comment by imtt1980** [comment]
+1

**Comment by westd05** [comment]
Same issue here. Only stable on the side of a table.
Something like this would be better I guess:
http://www.allekabels.nl/usb-20-kabel/172/1294395/usb-micro-b-kabel-haaks.html

**Comment by annekrist** [comment]
@Westd05 this is the wrong cable. Works for a android Phone but not a Homey. Try bending the cable next to the plug a bit works great

**Comment by WeeJeWel** [comment]
Closing this issue because we cannot 'solve' this by pushing an update ;-)

**Comment by Priyantha** [comment]
The 'update' could be supply a new improved cable to all the buyers of the Athom Homey.
Bending the cable is not something I like to do, and this had to be sorted out before shipping.

Currently it is a Retail product, for a Retail product it is quite bad.

Also I am sure that his will be a negative point for every reviewer out there who is going to publish a review on this device when they receive their "review-kit".

So closing the issue without stating a further action is quite harsh I think?
