### ISSUE TITLE
Add "select all" option to "Select the devices you want to add" view of pairing

### ISSUE THREAD

**Issue by freemann** [athombv/homey#841]
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
Check a box which selects all available device in the view "Select the devices you want to add";
![screenshot - 01_09_2016 20_42_11](https://cloud.githubusercontent.com/assets/601053/18179917/ed492ae4-7084-11e6-8af6-2fc6baa0a382.png)
This is a relayboard with 8 relays, there are boards with 20 relays ;)

**Please include detailed steps how we can reproduce the issue**
--

**What was the result?**
No option to select all devices

**What did you expect as result?**
Checkbox to select all device

**Any other remarks**

**Comment by nlrb** [comment]
:+1:

**Comment by WeeJeWel** [comment]
Hold shift while checking a checkbox.

Okay it's not the most obvious design... ;-)

**Comment by freemann** [comment]
I really(!) love your guys! 

Just one "vinkje"........

**Comment by nlrb** [comment]
Can't you at least add some help text to the page that people know they need to hold SHIFT? It works great, but nobody will think of it...
