### ISSUE TITLE
Label field not accepting plain integers.

### ISSUE THREAD

**Issue by freemann** [athombv/homey#845]
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
Put a integer in the settings field type "Label"

**Please include detailed steps how we can reproduce the issue**
Create a Label field, add a integer

Here's the json part:
```
{
	"id": "pairedRelayNumber",
	"type": "label",
	"label": {
		"en": "Device pair #",
		"nl": "Apparaat koppel #"
	},
	"hint": {
		"en": "This is the original Relay-number the Device is paired with.",
		"nl": "Dit is het originele Relais-nummer waarmee dit apparaat gekoppeld is."
	},
	"value": 0
}
```
This is the pairing code;
```

devices.push({
    data: {
        id: deviceData.serial + "-" + (i + 1),
        ip: deviceData.ip,
        port: deviceData.port,
        serial: deviceData.serial,
        firmware: deviceData.firmware,
        hardware: deviceData.hardware,
        module: deviceData.module
    },
    settings: {'mainDeviceText': thisDeviceText, 'ip': deviceData.ip, 'port': deviceData.port, 'togglePoints': 0, 'pairedRelayNumber': (i + 1)},
    state: {onoff: false},
    name: deviceData.name + " relay " + (i + 1)
});
```

**What was the result?**
Label field not showed and if defined in JSON with integer it doesn't  generate:
`invalid type for `driver[0].settings[0].children[1].value` in app.json, expected type string`

**What did you expect as result?**
seeing a label field with integer.

**Any other remarks**
please see:
https://github.com/athombv/homey/issues/840

**Comment by jeroenvollenbrock** [comment]
This is intended behavior.
