### ISSUE TITLE
Homey becomes unresponsive

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#846]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Let Homey run - nothing else.

**What was the result?**

Homey becomes unresponsive.

![image](https://cloud.githubusercontent.com/assets/11725674/18223850/5981454e-71c4-11e6-9751-db4cf36283ad.png)

![image](https://cloud.githubusercontent.com/assets/11725674/18223840/0ab74d14-71c4-11e6-9a49-20c8fc3b542b.png)

**What did you expect as result?**

Smooth, fast reacting Homey.

**Any other remarks**

- One app running in debug mode.
- Homey still responds to 'OK Homey', triggers etc.
- Looks like a networking issue (seen 'EPIPE' messages in debug logs)

**Comment by bvdbos** [comment]
What did the app do to kill the http-server?

**Comment by freemann** [comment]
Seeing this behavior multiple times a day.

**Comment by nlrb** [comment]
The http-server is not killed, it is still running (after minutes I got a black page). Things just get >really< slow.

**Comment by jeroenvollenbrock** [comment]
Can you send me a log after this happens? (settings -> system-> send log)

**Comment by WeeJeWel** [comment]
That Chrome error actually seems to be a hanging Javascript. What were you doing when it occured?

**Comment by nlrb** [comment]
@WeeJeWel it was just loading the devices pages from scratch. So don't expect it to be client side.
@jeroenvollenbrock will send a log when it happens again.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in version 0.10.5. If the problem still persists, please reopen this issue.
