### ISSUE TITLE
[Enhancement] More info on offline devices

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#849]
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
I'm writing a (not Z-wave!) driver.
My devices have multiple capabilities.

(1)
When I set a device to offline (in code), when the next capability is called, I would like to ask Homey if the device is set to offline rather than having to keep a list of offline devices myself.
This should/could save some resources on Homey rather than setting the device offline every time I came to the conclusion when receiving 'undefined' from the server I'm communicating with.

(2)
In order to have the device back online again, I have to start polling the server (in my case) periodically because the user is unable to set the device online again.
It would be nice if the user could request the driver to check the device again.
Something like a button below the offline text?
![image](https://cloud.githubusercontent.com/assets/15921016/18224871/afbb3c92-71e4-11e6-9354-1bf6e52f95b8.png)

(3)
Even though a device is set to offline, it will still start a flow of that device?
Is that a bug or a feature :)

(4) 
After stopping/killing the app (through CLI) the device is online again.

**Comment by WeeJeWel** [comment]
Sorry, wontfix. It's the driver's responsibility to keep track of devices. The user doesn't always have the option to 'reconnect'. Imagine Flows not triggering, for example.

Polling every minute or so isn't that bad, so that's fine!

**Comment by Inversion-NL** [comment]
OK. And what about number 2?

**Comment by WeeJeWel** [comment]
Won't be added :) If we do add it, developers won't automatically reconnect, and behavior would become inconsistent.

About 3, that's a bug that's already fixed in a future version. 4 makes sense, but is a problem of the app :)

**Comment by Inversion-NL** [comment]
Okay chef, thanks
