### ISSUE TITLE
First instructions unclear and missing welcome

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#85]
When following the first instructions you get when going to the URL listed on the box, I would think that you would begin with a warm welcome at Athom, and an instruction to connect your Homey to power to turn it on. 

Also, I was at that site using my iPad. It instructed me to go connect to the Homeysetup wifi LAN using my computer or phone, and so I did on my computer. After which, nothing happened there of course. It would be nice if other devices would get some generic page if they connect to homey that way telling them how to do it instead. I should have connected to that network from the device I was currently using, but the instruction did not tell me that. 

Last: later on in the process it became clear that the setup would not work completely using the iPad. It would be better to warn ahead of time: detect the device and browser, and just _tell_ people to use Chrome on a non-iOS device.

**Comment by pkonings** [comment]
Same here, I was also using a Ipad/Safari initally and besides this didn't work the flow screen wasn't readable at the left top due to the scheme used. Had to reset Homey and switched over to Chrome discovering it showed more information.

**Comment by WeeJeWel** [comment]
We'll improve our set-up process a lot, and release a Desktop Application as well, which should take away most difficulties.
