### ISSUE TITLE
Kaku Doorbel with two push messages in a flow repeats the flow

### ISSUE THREAD

**Issue by edtst** [athombv/homey#850]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**
Create adoorbell flow that triggers once.

*Please include detailed steps how we can reproduce the issue*
I have a ACDB-7000BC doorbell. I added it by copying the pushbutton action. When I create a flow that tiggers on the pushbutton and as an action enter a sound from the soundboard, a spoken sentence and 1 push message, it fires just once. When I add another pushmessage to another phone, it Always fires twice.

**What was the result?**
see above
...

**What did you expect as result?**
That it would trigger just once

...

**Any other remarks**
This behaviour is intorduced since 0.9.2.
...

**Comment by WeeJeWel** [comment]
Can you post a screenshot of the Flow?

**Comment by jeroenvollenbrock** [comment]
What is the actual version of your Homey? version 0.8.x93 does not exists.

**Comment by edtst** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/17183305/18271869/ddcdd548-7434-11e6-8550-0cb65807c328.JPG)

Here it is. I created this flow and it worked. After a while (say a day) suddenly it rings twice instead of once.

**Comment by edtst** [comment]
Version is 0.9.3 sorry

**Comment by BasKiers** [comment]
I've updated the KaKu app to discard duplicate signals for 4 seconds (instead of 3). Could you check if this fixed the issue?

**Comment by edtst** [comment]
It rang once just now. Let's see how it goes.

**Comment by BasKiers** [comment]
Ok, I will close this issue now. Please re-open or open a new ticket if this issue reoccures.

**Comment by edtst** [comment]
This problem is back after updating to 0.10.3
