### ISSUE TITLE
Android App won't load mobilecards if there's a Hotspot invitation

### ISSUE THREAD

**Issue by freemann** [athombv/homey#852]
**What is your Homey version (Settings → System)?**
0.9.3/2.2.7b55

**What did you try to achieve?**
Control my sunscreen when I'm in the mall

**Please include detailed steps how we can reproduce the issue**
Go to a mall with a Open Hotspot which requires to agree terms of use and don't agree the with the terms. The result is that the wifi is "connected without internet" and then the app won't load data.  My normal 4G connection was alive and I were able to use other apps like Nu.nl/Chrome/Buienradar.

**What was the result?**
Android App Mobile cards won't load and the spinning circle stays in the cards.
I waited about 2-3minutes before taking this screenshot:
![0](https://cloud.githubusercontent.com/assets/601053/18312509/68a045ae-750a-11e6-8863-6b9a78f7ce3d.png)

**What did you expect as result?**
Mobile cards so I can control my sunscreen.

**Any other remarks**

**Comment by Inversion-NL** [comment]
Could be firewall

**Comment by freemann** [comment]
Firewall??

**Comment by freemann** [comment]
@Inversion-NL firewall?

**Comment by Inversion-NL** [comment]
In the HotSpot. Not really uncommon.

**Comment by bvdbos** [comment]
I'd say a firewall which blocks uncommon ports or ip's too....

**Comment by freemann** [comment]
Ah I didn't mention in the issue that the phone was not(!) connected with the Hotspot. There was only a invitation and from that point the app didn't load mobile card.

**Comment by bvdbos** [comment]
The phone was connected with wifi to the hotspot if I understand you right. Apparently you don't have to agree to the terms to use port 80... Or was wifi disconnected (which is different from disagreeing with the terms)?

**Comment by freemann** [comment]
For me it was a known network, so my phone connects automagicly to it. For this time I didn't open the Hotspot message/invitation and so didn't accept or refuse it, had no interactions with the network/Hotspot/invitation. 

So the phone is "connected" to the network and because I didn't accept the terms, I didn't get internet access. 4G was working and all my others apps were able to receive/send data (received/send email, nu.nl, live stream to my ip-cam(same network as Homey). But the android app wasn't loading data. Also ImperiHome of my Vera3 was working.

**Comment by jeroenvollenbrock** [comment]
This is probably due to a firewall configuration that blocks websockets.
