### ISSUE TITLE
appstore experimental versions of apps

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#853]
Currently the app-store serves 2.3.1 of KaKu, this version doesn't work on FW0.8.39 so people who install Homey for the first time (or after the release of 0.9.x at the end of july with the accompanied KaKu-app) don't have KaKu..
https://forum.athom.com/discussion/1937/cant-install-kaku-this-app-is-incompatible-with-your-homey-software-version#latest

**Comment by joachimroeleveld** [comment]
This should be fixed now, as the App store serves the most recent, compatible version. In your described case, users with firmware version 0.8.39 would get version 2.0.6 which _is_ compatible.
