### ISSUE TITLE
Different range concerning receiving and transmitting z-wave protocol

### ISSUE THREAD

**Issue by kasteleman** [athombv/homey#854]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Use a node within the z-wave network

_Please include detailed steps how we can reproduce the issue_

I was testing my Qubino device within 3 meters of Homey and decided it worked just fine. Therefore decided to move the device to it's intended usecase upstairs and run the Qubino app in debug mode.
Temperature reports came in, but the get command off the dimmer status timed out. First checked my app, but same result. Then i decided to move Homey towards the device upstairs. Now the get command did not time out and temperatur reports came in.

**What was the result?**

Different range concerning receiving and transmitting z-wave protocol

**What did you expect as result?**

Same range for both. Would expect that after the get command timed out, there wouldn't come any temperature reports in for the same device.

**Any other remarks**

Jeroen asked me to make a issue on github, because he wants to investigate it further.

**Comment by WeeJeWel** [comment]
I'm closing this issue as it's not something we can fix, because the range depends on various factors, and we have no influence on the Z-Wave module range whatsoever unfortunately.

**Comment by kasteleman** [comment]
Emile, on request i made this issue after asking Jeroen. I know the mesh
network is important, but Jeroen also found it strange that there is a
difference between the 2 and wanted to investigate if it can be adjusted.
So you are saying that the sending level can not be adjusted?

Regards,

Martin

Op dinsdag 1 november 2016 heeft Emile Nijssen <notifications@github.com>
het volgende geschreven:

**Comment by WeeJeWel** [comment]
We've looked into it and the sending level is already at maximum strength, so there's indeed nothing we can do :)
