### ISSUE TITLE
Orphaned sub-nodes after removing z-wave device

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#855]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

I tried removing a z-wave device (Fibaro dual relay, 1 main node and 2 child nodes) by clicking the X on the device.
Triple clicking the B-button didn't do anything, the dialog screen kept waiting for the device.
I closed the dialog, tried removing the device through the z-wave settings, didn't work either.
Tried the other method again, but let the screen time-out this time.

**What was the result?**

Result was that the main node was removed but the 2 child nodes were still there.

**What did you expect as result?**

I expected all 3 nodes to disappear.

**Any other remarks**

I'm now stuck with 2 ghost devices and no way to remove them except by doing a full reset of my z-wave network (I think?)

I think that when you're allowing to remove devices this way, you should also check for sub-nodes otherwise users will eventually get stuck with lots of ghost devices...

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
