### ISSUE TITLE
[Z-Wave] Multichannel nodes should not have device settings

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#857]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Multichannel nodes (which are added as separate devices) also have a device settings page. Only the main node should have that in most (known) cases. An option (or automatically if applicable to all multichannel nodes) should be provided to disable the device settings for the multichannel nodes, as for now it can crash the app if used.

**What was the result?**

Z-wave app crashed

**What did you expect as result?**

Nothing, option should not be there.

**Any other remarks**

This issue is created from https://github.com/athombv/com.fibaro/issues/50, and placed here as it is a generic issue (not specific to the Fibaro app).

**Comment by jghaanstra** [comment]
Just a heads up that there is also a use case where the main node does indeed have settings that are not applicable for the multichannel nodes but can also contain settings that are applicable for the multichannel nodes as well.

For instance the Greenwave powernode 6 has a parameter for polling frequency that is applicable for the main AND the multichannel nodes but also has a parameter called keep alive time that is only applicable for the main node (and trying to edit it on a multichannel node does indeed cause a crash).

**Comment by WeeJeWel** [comment]
The default settings (association group, raw config data, node info) are not displayed on multichannel nodes. An app can add their own settings. Isn't that right behavior?

**Comment by jghaanstra** [comment]
That is the right behavior for that use case. But I'm talking about the use case where an app for a multichannel device adds their own settings where a setting only applies to either the main node or the multichannel node (and not both).

As far as I'm aware it's impossible to configure the app in such a way that a device specific setting is only available for either the main node or the multichannel nodes.

**Comment by WeeJeWel** [comment]
That is possible, just override the 'settings' object in app.json. (Docs will follow, but for now check the Greenwave repo)

**Comment by jghaanstra** [comment]
Docs will help. It's exactly the Greenwave repo that has this issue (it was my own pull request).

In the Greenwave app there is a setting called "keep alive time" which can only be set at the main node level. But in the current version of the app this setting is also available for all multichannel nodes. Trying to change it at multichannel level will result in a crash as the Greenwave devices can't handle it.

Seeing your answer I guess the settings object will have to be overridden for every multichannel node to avoid this setting (which is only intended for the main node) from showing there as well. But i guess I'll wait for the docs ...

**Comment by WeeJeWel** [comment]
Updated the docs :)

**Comment by jghaanstra** [comment]
Perhaps it's me but I could not find any explanation in the documentation on how to add a setting **only** to a main node of a multichannel device. As mentioned earlier, the Greenwave systems app has a driver for the Greenwave Powernode-6 where a setting should only be available on the main node (keep alive time). Currently it's available for all multichannel nodes and changing it on a multichannel node results in an app crash. I'd like to make a pull request to fix this but I still dont understand how to do it.
