### ISSUE TITLE
[Z-Wave] Battery vs AC/DC devices cause app crashes

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#858]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Use a Z-Wave device in both battery mode, as in ac/dc mode (via usb connected to power source for example).

**What was the result?**

App can crash, or measure_battery capability can display a dash (instead of disappearing when not running on battery).

**What did you expect as result?**

That a device can both be used as a battery node, as well as connected to a power source.

**Any other remarks**

To make it a bit clearer. When a battery device runs on battery, it advertises the Battery CC. But the same device can also be used connected to a power source. It will then either still advertise the Battery CC or not (depending on the device). The former will cause invalid values from being displayed by the measure_battery capability (no value to display), the latter will sometimes crash the app, as the driver implements the measure_battery capability which is hooked up to the Battery CC, but when the device does not advertise it anymore due to the power connection, the driver can not be used as it generates a warning that is uses a CC that is not supported by the device.

Proposed solution:

Part 1: Make the check on whether or not the device supports Battery CC less strict, so that drivers can implement the measure_battery capability with the Battery CC, even though the device might stop advertising the support for this CC.

Part 2: Dynamically add/remove the measure_battery capability, depending on the setting of "battery:true" in the node. If it is true, it should add the device with the measure_battery capability, if it says false, it should drop that capability.

This issue is created from https://github.com/athombv/com.fibaro/issues/21, and placed here as it is a generic issue (not specific to the Fibaro app).

**Comment by kasteleman** [comment]
I have a simmular usecase for the Qubino Flush Dimmers.  If a Temperature sensor is attached to the TS connector, only then the Sensor Multilevel V7 Command class is advertised. Therefore when using the measure_temperature capability in the driver but the sensor is not attached, the app crashes during inclusion of the device. Therefore i also "need" one of the proposed solutions.

**Comment by RobinBol** [comment]
This issue was fixed a while back by providing the `'optional':true` flag in a zwave-driver capability object.
