### ISSUE TITLE
Have to use Chrome, but not on iOS

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#86]
Users of iOS are left in the cold. They cannot use Homey's interface, as elements are not working here and there. Sure, technical people will realize that Chrome on iOS is not using the same engine as on the other platforms, but... It is just not very friendly. You want an Apple-like experience, so make sure that you can use Apple devices as well.

**Comment by freemann** [comment]
Why do you want and(!) expect an Apple-like (no idea what that is) experience?

And the "getting started" post on the forum says;
https://forum.athom.com/discussion/528/received-your-homey-getting-started-guide/p1

> Google Chrome (A Homey desktop app will be released in the upcoming weeks, so you won't need Google Chrome anymore)
No idea if this desktop app will work on ios.

**Comment by AndreSomers** [comment]
Because that's the kind of presentation they make. I know what the "Getting started" post tells me, but that post is not part of the instructions you get when you just unbox the device. Then you get pointed to a setup URL. Nothing more. For a smooth experience, I should **not** have to read though forum posts as well.

I know Homey is still in beta. That's _why_ I am reporting it, so users who bought it in the store get a better experience. I can handle it. Your average MediaMarkt buyer will not.

**Comment by Sateprikkert** [comment]
> Why do you want and(!) expect an Apple-like (no idea what that is) experience? 
This is a Athom and not Apple product.

What Athom should aim for is the UI being self-explanatory, so the user doesn't need to examin the user manual most of the time. I think that's what @AndreSomers is trying to emphasize here.

**Comment by freemann** [comment]
Apple has (by numbers sold) the most customer-care questions of the market. So i don't think Apple is a good example (just my opinion).

Of course it should be self-explanatory and therefore I suggested the "question mark" help options.
Just place on every page, next to important parts of the GUI/system small question marks with help/info text.

And the product is still under development and I also think its a big missed opportunity the not included a proper getting started guide and also the install process seems a bit lose.

For as far I get it, the Desktop(!) app will run outside the browser on a normal (windows?!) computer and it has nothing to do with a mobile (Android/IOS/WindowsMobile etc.) OS.

**Comment by AndreSomers** [comment]
Perhaps you are right, and perhaps not. I don't have such numbers. I do know that I did not file a single issue after first unwrapping my iPad, while I filed 15 after unwrapping Homey yesterday. There is work to be done. Part of that work is, I think, that it should be possible to configure Homey from something else than a Chrome browser, including using an iPad to do so. And while it is not, the setup page should warn me that I should use a different browser and not silently fail somewhere in the middle.

A lot of people do not even have a laptop anymore these days. What if all I have was an iPhone and an iPad to work with here?

**Comment by RuudBurger** [comment]
Wasn't the idea to have an app (on both desktop and mobile/tablet?) This way they have control on the render engine used for the interface.

Looking at the interface they use a lot of webkit (chrome and safari render engine) specific css. But only for "eye candy", blurring things etc. I feel the web interface should be easily converted to work on all modern browsers, but I understand them wanting to focus on other things first and thus forcing us on Chrome for now.

**Comment by freemann** [comment]
Homey is a newly developed Kickstart Beta product thats release to a bunch of geeks. 
Apple only release "high quality" products that are, in most cases, evolved from previous products.
So, not discussing Homeys software state, its not fair to compare Athom with Apple or an Iphone with Homey. Maybe its fair to compare HomeyV2(or3) to a Iphone experience.

And i'm with you about the choice for Chrome and big public. For now I believe most Geeks will atleast have a Laptop/Workstation and/or Android device in there homes.

Lets see where homey stands after 6 months :smile:

**Comment by AndreSomers** [comment]
Let's put it like this: for Geeks, it is indeed not a major issue, though the feedback in the process itself could be better. Once you start sending it out to pre-orders and selling it in Media Markt, it is no longer acceptable.

**Comment by WeeJeWel** [comment]
Please note that iOS is not yet officially supported for the Homey interface, except the mobile interface.

**Comment by Sateprikkert** [comment]
@WeeJeWel and with mobile interface on iOS you mean Chrome only?

**Comment by WeeJeWel** [comment]
No, Safari should work fine for http://{your homey ip}/manager/mobile/

**Comment by AndreSomers** [comment]
Chrome on iOS has the same engine as safari does, so no difference there.

**Comment by Sateprikkert** [comment]
That's odd, because when I tried to run the intial setup on my homey all I got was the colorful background, but no items. I'll restore the homey tonight and try to replicate it.

**Comment by FrankTeusink** [comment]
Tried crome on ios. Did initial setup using it. But textbox cant get focus for typing, so you cant go far with flow editor.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.34 for the mobile interface. The desktop interface remains desktop-only as of now.
