### ISSUE TITLE
[Z-Wave] Secure inclusion times out very often

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#860]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

Include a z-wave plus device.

**What was the result?**

Pairing takes long and finally times out.

**What did you expect as result?**

Pairing to succeed.

**Any other remarks**

To reproduce take an Aeotec Smart Switch (or a different Z-Wave+ device, but I tested with this one), double press action button (within one second) to perform a secure include. Without any other zwave traffic nearby, the inclusion often times out (5/6). Most of the times it times out, it hangs at 'Setting default association groups'.

This issue is created from https://github.com/athombv/com.fibaro/issues/31, and placed here as it is a generic issue (not specific to the Fibaro app)

**Comment by WeeJeWel** [comment]
Fixed in 0.10.6!
