### ISSUE TITLE
[Z-Wave] Make multichannel nodes removable

### ISSUE THREAD

**Issue by RobinBol** [athombv/homey#862]
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

I tried to remove a multichannel node (which was added as extra device).

**What was the result?**

The device does not have the option to remove.

**What did you expect as result?**

Being able to remove the multichannel node, or select which multichannel nodes I want to add during pairing.

**Any other remarks**

This is especially annoying when adding a Fibaro Relay which adds the S2 as an additional device, but the user does not necessarily has something connected to S2, leaving an unused device in the Homey interface (which can get annoying in the mobile interface).

This issue is an enhancement as it currently does not pose any problem concerning the functionality of the z-wave devices.

Created from https://github.com/athombv/com.fibaro/issues/45 as this is a generic issue that affects more than solely Fibaro devices.

**Comment by Arjanvde** [comment]
I was able to remove the S2 so this is solved :)
