### ISSUE TITLE
Time 08:05 not pronounced correctly with speech output

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#867]
**What is your Homey version (Settings → System)?**

x0.9.3

**What did you try to achieve?**

Have homey say a time 08:05

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

Only 'nul vijf' is pronounced, not the hour
...

**What did you expect as result?**

Acht uur vijf

**Any other remarks**

08:15 works fine!
...

**Comment by bvdbos** [comment]
Also on 0.10.0 this happens with every time which has less ten minutes...

**Comment by WeeJeWel** [comment]
From where does it say this? Flow, 'What time is it'?

**Comment by bvdbos** [comment]
Happens on manager/speech-output/ in Dutch. English works correctly...

**Comment by gruijter** [comment]
Also happens from speech api when used in an app. This was already the case in previous fw versions.

**Comment by Tweake** [comment]
Indeed this was an issue which had already been fixed in a previous version. With the latest rewrite the fix was omitted by accident. It's back in place again, so as of version 0.10.1 this is fixed.

**Comment by bvdbos** [comment]
Can't try as there's a new message now:
```
POST http://10.0.3.35/api/manager/speech-input/?_=1475268277572 404 (Not Found)window.Homey.api @ api.js:1(anonymous function) @ (index):1dispatch @ jquery.js:2m.handle @ jquery.js:2
(index):1 no_agents
```
when inputting time like 08:20 in /manager/speech-input. Other inputs work as expected...

**Comment by bvdbos** [comment]
I should have inputted this on /manager/speech-output. This works for me now on 0.10.1.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
