### ISSUE TITLE
Enable/Disable microphone setting isn't applied until after reboot

### ISSUE THREAD

**Issue by WeeJeWel** [athombv/homey#868]
On Homey v0.10.0, when enabling the microphone, it isn't directly activated. A reboot solves this.

**Comment by bvdbos** [comment]
Why is speech-recognition experimental now?

**Comment by WeeJeWel** [comment]
Actually this issue didn't exist.

@bvdbos because we're still working on it, and it's not good enough for us to mark as stable yet!
