### ISSUE TITLE
Volume / Afspeelvolume

### ISSUE THREAD

**Issue by alledijkstra** [athombv/homey#869]
What is your Homey version (Settings → System)?**
0.10

What did you try to achieve?**
Changed volume from 50 to 100

*Please include detailed steps how we can reproduce the issue*
Change volume from anything lower then 100 and than slide it to 100

What was the result?**
Homey says 800%

What did you expect as result?**
Homey would say 100%

Any other remarks
None

**Comment by WeeJeWel** [comment]
What does the speech-output log say? /manager/speech-output/

**Comment by Inversion-NL** [comment]
Homey's voice says 800% but voice output states 100 percent

![image](https://cloud.githubusercontent.com/assets/15921016/18797309/b5def980-81cd-11e6-9d30-631af2bf949b.png)

**Comment by WeeJeWel** [comment]
Then it's probably just a difference in how it's perceived :-) I'll check asap

**Comment by Inversion-NL** [comment]
Updated my previous comment with: "All seems fine but the 100% announcement"

**Comment by bvdbos** [comment]
definitely 800%

**Comment by BasKiers** [comment]
This issue is fixed in 0.10.1

**Comment by bvdbos** [comment]
confirmed fixed...
