### ISSUE TITLE
Z-Wave does not respond after (cold) reboot

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#870]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

I've got the feeling that Z-Wave crashed after this reboot. Log send E22435139E.

Hope there is some info in there.

Couldn't control Any of the Z-Wave devices anymore.

After a Reboot Z-Wave seems to work again.

**Comment by WeeJeWel** [comment]
What does the 'Stuff for geeks' in Settings > Z-Wave say?

**Comment by Arjanvde** [comment]
@WeeJeWel can't tell anymore, restarted Homey and the issue is now solved for now, had hope the log contained some info. Will close this for now, will reopen if this reappears.
