### ISSUE TITLE
All Philips HUE Lights are unreachable

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#871]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

After installation of 0.10.0 I had to reinstall the Philips HUE app. Since the reinstallation and a reboot all Philips HUE lights are unreachable.

![schermafbeelding 2016-09-23 om 19 44 54](https://cloud.githubusercontent.com/assets/17526110/18795755/5908986c-81c6-11e6-955f-fcac52c8baab.png)

**What was the result?**

No working Philips HUE Lights.

**What did you expect as result?**

Working HUE Lights.

**Any other remarks**

When updating/bug solving the app, please consider that an internet connection is not necessary for the HUE Lights as they are always in the Network available. In addition, even if there is a unreachable in the network Homey should still give the commando to the HUE lights.

**Comment by Arjanvde** [comment]
Little update, if you repair the HUE lights after a reboot by going to the pair and touch the connection button on the HUE Bridge Homey can suddenly contact all lights again.

Log after Reboot: B32F65D703
Log after button press: 3D960B016A

**Comment by elcovb** [comment]
Same issue here.

**Comment by Arjanvde** [comment]
Solved with 10.2, looks like this was related to the storing variables issue.
