### ISSUE TITLE
[Enhancement] Add 'broken icon' to folder if one or more flows in it are broken

### ISSUE THREAD

**Issue by Inversion-NL** [athombv/homey#872]
**What is your Homey version (Settings → System)?**
0.10.0

**What would you like te enhance?**
Would it be possible to add a 'broken icon' somewhere around the folder name to state one or more flows in it are broken?

Example images. See the muziek folder contains several broken flows.
You'd only know that when opening the folder.

![2016-09-23 20_33_52-homey flow](https://cloud.githubusercontent.com/assets/15921016/18797484/6a4c6c40-81ce-11e6-8475-f555b32677f0.png)
![2016-09-23 20_34_20-homey flow](https://cloud.githubusercontent.com/assets/15921016/18797488/6e6d5e38-81ce-11e6-995f-b6ec3287b839.png)

**Comment by WeeJeWel** [comment]
As of v1.3.0, searching for `broken` will display all broken flows.

**Comment by Inversion-NL** [comment]
Now a dutch translation for `broken` and a hint somewhere for new users to enhance UX?
