### ISSUE TITLE
speech-input page error

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#873]
**What is your Homey version (Settings → System)?
0.10.0

**What did you try to achieve?**
start a speech flow through speech-input http://<ip>/manager/speech-input

**What was the result?**
Error on page : http://10.0.3.35/api/manager/speech-input/?_=1474656223803 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by bvdbos** [comment]
Also:
api.js:1 POST http://10.0.3.35/api/manager/speech-input/?_=1474659818578 500 (Internal Server Error)window.Homey.api @ api.js:1(anonymous function) @ (index):1dispatch @ jquery.js:2m.handle @ jquery.js:2
(index):1 action.run is not a function

**Comment by bvdbos** [comment]
After a reset with restore this bug persists.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1

**Comment by bvdbos** [comment]
confirmed fixed... Only a debug line now:
null -> (index):1
