### ISSUE TITLE
IR will not work for LG smart TV 55LB674V (2014)

### ISSUE THREAD

**Issue by philsniff** [athombv/homey#874]
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

try to ad lg ir-device

**What was the result?**

first lg is not listed (search funtion must have 3 and more letters)
second if i try "lg most models" in the selection after these steps none of the buttons worked in testflows ("Invalid data pulse length...")

**What did you expect as result?**

that ir ist working ;-)

**Any other remarks**

that is the only bug i can see after upgrade to 0.10 sofar

**Comment by DieterKoblenz** [comment]
Same here for a Denon DRA-275 (antique amp)

**Comment by philsniff** [comment]
now it works with "LG most models" (0.10.3)
