### ISSUE TITLE
 capabilities: target_temperature","measure_temperature" not updated!?!

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#875]
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

I have a number of apps where the temperature should be displayed. But none of them does?

**What was the result?**

No temperature is displayed

**What did you expect as result?**

Temperature is displayed

**Any other remarks**

Is the way that the devices will be updated differently? Is this is problem in the app or Homey OS?

![2016-09-23 21_35_47-microsoft edge](https://cloud.githubusercontent.com/assets/17949840/18799135/567921f6-81d6-11e6-9f36-8b4599a7858d.png)
![2016-09-23 21_35_05-microsoft edge](https://cloud.githubusercontent.com/assets/17949840/18799147/642bce7a-81d6-11e6-93ed-1e076b43a87d.png)

**Comment by bvdbos** [comment]
works for me with Fibaro FGMS-001 and Thermosmart...

**Comment by magtimmermans** [comment]
I see someone else (on the forum) has the same problem:
https://forum.athom.com/discussion/comment/32090/#Comment_32090

**Comment by philsniff** [comment]
i can underline the issue @magtimmermans discripes. my tado thermostat has no temperature display since the 0.10 update AND my fibaro motionsensor either:
![schnappschuss_092316_091844_pm](https://cloud.githubusercontent.com/assets/7848863/18800743/e770f758-81de-11e6-9d5a-bb8a72762248.jpg)
![schnappschuss_092316_104133_pm](https://cloud.githubusercontent.com/assets/7848863/18800742/e76f3a58-81de-11e6-8379-b8dc7f2ef651.jpg)

**Comment by DieterKoblenz** [comment]
Same here, using the OTGW app.. Using my phone it seems to work though..

**Comment by simmer1974** [comment]
Had same problem with evohome. After a few hours the temp was back. Only thing that doesn't work is the slider to set temp. Alway starts at zero and not remembered.

**Comment by magtimmermans** [comment]
I really hope this will be fixed in the 0.10.1 release.

**Comment by WeeJeWel** [comment]
Does this still occur?

**Comment by magtimmermans** [comment]
Fixed

**Comment by alledijkstra** [comment]
![flood](https://cloud.githubusercontent.com/assets/2519741/19891608/2d326030-a041-11e6-93ac-689392b656ab.png)

The floodsensor still has the problem.. re-added the device.

**Comment by caseda** [comment]
could it be that the temperature hasn't changed yet for 0.5 (half) degree celcius?

it will only report the temperature when the measured temperature (every 5 minutes) is more then 0.5 degrees celcius from the previous measurement, and it only "get-able" when the sensor is awake (if in battery mode)

**Comment by RobinBol** [comment]
@StraDijk that is a separate issue and will be fixed with the coming Fibaro app update!
