### ISSUE TITLE
Ordering and grouping flows doesn't work properly

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#877]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Sorting and grouping flows doesn't work in the correct way. Somehow you can't select a new flow and add this to a folder. In addition it seems to be impossible to reorder flows in a folder as if you select a single flow the complete folder is selected. Tried to capture some in the attached screenshot.

![schermafbeelding 2016-09-23 om 22 02 52](https://cloud.githubusercontent.com/assets/17526110/18799782/d567361c-81d9-11e6-8620-813400e3cc34.png)

**What was the result?**

Ordering flows not possible.

**Comment by DieterKoblenz** [comment]
With some effort I can make flow folders and put flows in them but only on the first level. So can't make use of subfolders.

**Comment by Arjanvde** [comment]
Little update, the issue consists out of 2 issue's.

1. The first issue is that it is very hard to put a flow in a folder, seems that there is no border defined. In the process of pick and dropping the flow you are able to move it quite a lot to the right and the folder you want to put the flow in is not visible anymore. Therefore the process to get a flow in a folder is very difficult.

2. The second problem that arises is that once a flow is put in a folder, the order of the flows can't be changed anymore. In this case it seems that the flow has become part of the folder. If you than try to oder flows the whole folder moves.

**Comment by Dijker** [comment]
I have not the problem creating folders and moving the flows inside, 
2nd point is anoying, once placed in a folder the flow cant be moved within or out of the folder...
tested on Homey Version 0.10.1

**Comment by Arjanvde** [comment]
Putting a flow in a folder is much tougher on my Macbook than on a Windows pc at work.

Still both existing.

**Comment by Dijker** [comment]
placing a flow in a folder, that Flow can be removed direct after that. when you refresh the browser tab the dropdown list of flows is reloaded and the just placed flow is locked in the folder.

afaik nothing to do with flows from before 0.10.1 or after just the loaded dropdown list...
tested also with NewFolder and two new flows...

**Comment by jeroenbos22** [comment]
Placing a flow in a floder is damn hard to do if not impossible. It should just move in when hovering it on the folder.

**Comment by Arjanvde** [comment]
Solved (works different than it used to work!!!)
