### ISSUE TITLE
IR can not handle two devices?

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey#878]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

First added Samsung TV to IR using the wizard and pre-registered remote settings. After that added the Denon DRA-275 using my phone as IR remote. It registered the key's and added around 10.. 

Then I tried any of the IR buttons inside a test flow.

**What was the result?**

"Too many devices" error

**What did you expect as result?**

Working IR output 

**Any other remarks**

I removed the Samsung and the Denon gave "Invalid data pulse length". Deleted that one either and re-added the Samsung, that works now.

**Comment by bvdbos** [comment]
Yep, same for me (without pulse-length)...

**Comment by bvdbos** [comment]
This works for me on 0.10.1...

**Comment by DieterKoblenz** [comment]
No longer an error but it still does not work for me.
