### ISSUE TITLE
User rights/notifications are wrong in Notifications

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#879]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

I've added my girlfriend tonight to Homey. It does seem however that she gets the same notifications as the admin users does in the Notification screen.

Let me briefly explain, this is my user screen:

![schermafbeelding 2016-09-23 om 22 15 28](https://cloud.githubusercontent.com/assets/17526110/18800288/7bda5590-81dc-11e6-8af9-9772eb96e4f1.png)

This is the notification center of my girlfriend:

![schermafbeelding 2016-09-23 om 22 12 30](https://cloud.githubusercontent.com/assets/17526110/18800368/da12a4dc-81dc-11e6-8677-cb48d3f03e78.png)

The issue here is that they are identical. For instance, she gets a notification that she has accepted your Homey invitation. Uuh, why should she gets that notification? This should be part of the user rights/roles overview. For example, the main user should decide if a users gets all notifications (update's etc) or just a few. Most important notifications should be role specific. In this case the notification should have said something different (or nothing).

**What was the result?**

irrelevant but mostly a wrong notification.

**Any other remarks**

In case you want any suggestions, I've been involved in a project with different role/rights users and might can help you with this case.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

**Comment by Arjanvde** [comment]
Sort of solved. We could have a small discussion about user rights in the future.

Thanks.
