### ISSUE TITLE
Hue - scenes support missing

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#88]
When interacting with my Hue setup, I really really missed having access to my scenes. I want Homey to be able to turn on a scene I have defined. Having to do that lamp by lamp just sucks.

**Comment by WeeJeWel** [comment]
Good idea! Please report this here: https://github.com/athombv/nl.philips.hue

**Comment by AndreSomers** [comment]
Oh dear... a different github per app, so I have to re-report the isues.

**Comment by WeeJeWel** [comment]
Makes it a factor 10 easier for us to solve them. It's worth it! :+1:

**Comment by AndreSomers** [comment]
Added as https://github.com/athombv/nl.philips.hue/issues/1
