### ISSUE TITLE
Ledring screensaver not rotating anymore after fw 0.10.0 update

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#880]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Updated homey to fw 0.10.0
*Please include detailed steps how we can reproduce the issue*

**What was the result?**
The ledring screensaver for the plugwise p1 app stopped rotating. The colors seem to get updated correctly
...

**What did you expect as result?**
The ledring to keep rotating as with previous fw versions
...

**Any other remarks**

https://athomcommunity.slack.com/archives/developers/p1474662675000247
...

**Comment by bvdbos** [comment]
The default spectrum and pulsating work as they should... All other from Koen Martens don't...

**Comment by goldenice** [comment]
Sorry to get your hopes up, confused this one with another issue. I am going to look into it now though ;)

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1! (All `options` were not passed)

**Comment by bvdbos** [comment]
confirmed for 0.10.1

**Comment by WeeJeWel** [comment]
Do you mean it's fixed? :)

**Comment by bvdbos** [comment]
ye, confirmed your fix :+1:
