### ISSUE TITLE
Zwave-status doesn't work anymore

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#881]
**What is your Homey version (Settings → System)?**
0.10

**What did you try to achieve?**
See Z-wave status with json:
`api('GET', '/wireless/zwave/state/', null, function( err, result ) { console.log( JSON.stringify(result, false, 4) ); }); `

*Please include detailed steps how we can reproduce the issue*
paste in console

**What was the result?**
api.js:1 GET http://10.0.3.35/api/wireless/zwave/state/?_=1474700473115 404 (Not Found)window.Homey.api @ api.js:1(anonymous function) @ VM374:1
VM374:1 null

**Comment by WeeJeWel** [comment]
It has been replaced with a box on the settings screen.

**Comment by WeeJeWel** [comment]
(or change wireless to manager, then it'll work again ;))

**Comment by bvdbos** [comment]
:+1:

**Comment by Inversion-NL** [comment]
It's under Settings -> Z-wave -> stuff for geeks 

![image](https://cloud.githubusercontent.com/assets/15921016/18830925/4788e80c-83e3-11e6-9219-4506737fe03b.png)
