### ISSUE TITLE
433 can only send/receive once

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#882]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
use KaKu

*Please include detailed steps how we can reproduce the issue*
https://forum.athom.com/discussion/comment/32133/#Comment_32133

**Comment by bvdbos** [comment]
After a PTP sending works... But receiving is a one time operation. Tried resetting the 433 but that doesn't work...

**Comment by bvdbos** [comment]
Reset with keeping settings got my doorsensor back to life

**Comment by sleutelsnet** [comment]
This bug was also present in 0.9.3 and has been discussed and narrowed here:
https://forum.athom.com/discussion/comment/31022/#Comment_31022

Battery powered 433 devices can be connectec to homey, but homey goes death (after receiving 1 or 2 signals) from the 433 device.

**Comment by bobenoni** [comment]
The description bvdbos is linking to is my forum post, which has its own github: https://github.com/athombv/homey/issues/831

**Comment by bvdbos** [comment]
In 0.10.1 I can't reproduce this anymore. For others, battery-powered, it's probably in bug #831
