### ISSUE TITLE
Dutch language doesn't work

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#883]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
Talk Dutch to Homey

*Please include detailed steps how we can reproduce the issue*
https://athomcommunity.slack.com/archives/general/p1474678490003855

**What was the result?**
Dutch isn't understood, switching to English is...

**Comment by PeterBox** [comment]
Same problem here

**Comment by Inversion-NL** [comment]
Also on Dutch language and it seems that the voice question in the 'and' column doesn't wait for an answer.
Don't if it relates to this issue though.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1

**Comment by bvdbos** [comment]
original bug confirmed fixed in 0.10.1. I think what @Inversion-NL means is bug #923 ?

**Comment by Inversion-NL** [comment]
Yes
