### ISSUE TITLE
Flow Folders do not work

### ISSUE THREAD

**Issue by ajterpstra** [athombv/homey#884]
**What is your Homey version (Settings → System)?**

0.8.36 - 0.10.0

**What did you try to achieve?**
All folders removed and then restart homey, folders recreated.
I can create them, modify and delete, but can not put flow in the folders

**Comment by bvdbos** [comment]
same as #877 ?

**Comment by ajterpstra** [comment]
It looks a lot like me problem. but I can not do even the flow in the First level subfolder

**Comment by WeeJeWel** [comment]
Duplicate of #877
