### ISSUE TITLE
media manager is gone

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#886]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
Stop media playing

_Please include detailed steps how we can reproduce the issue_
https://forum.athom.com/discussion/1965/media-removed-at-0-10-0

**What was the result?**
No media, no warning or mention...

**Any other remarks**
probably the cause of https://github.com/santornl/nl.santor.vradio.homey/issues/3 too

**Comment by WeeJeWel** [comment]
The media manager is indeed removed in 0.10, as a preparation for the next update. Does Homey start media upon boot?

**Comment by bvdbos** [comment]
fixed in 1.2.0
