### ISSUE TITLE
433 callback error

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#887]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
try sending KaKu

*Please include detailed steps how we can reproduce the issue*
In the devices-tab, try to select the settings of a KaKu-device. The card appears but console gives error:
mobile.js:1 Uncaught TypeError: Cannot read property 'availableCallback' of undefined

**What was the result?**
Switching 433 is possible after a while but the error keeps appearing...

**Comment by nattlip** [comment]
in my oregon scientific app , all devices went undefined and not present after update, but in the log they were there, i reinstalled the app and gepaired the devices.

**Comment by nattlip** [comment]
my kaku sunscreen works

**Comment by WeeJeWel** [comment]
The mobile.js error has been fixed, but is unrelated to Kaku not working.

**Comment by bvdbos** [comment]
confirmed fixed in 0.10.1
