### ISSUE TITLE
Deprecation warning: moment().subtract(period, number) is deprecated

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#888]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
open insights

_Please include detailed steps how we can reproduce the issue_
watch console:
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).

**What was the result?**
works for now

**Comment by WeeJeWel** [comment]
Not really an issue :)
