### ISSUE TITLE
Homey does not respond to voice command "hey Homey"

### ISSUE THREAD

**Issue by backslashgithub** [athombv/homey#889]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

 give a voice command "hey Homey"

Homey did not respond in any way

...

That homey was waiting for a command like what is the time or wat is de tijd
...

**Any other remarks**

...

**Comment by backslashgithub** [comment]
Help

**Comment by DieterKoblenz** [comment]
Trigger is "OK Homey" not "Hey Homey"

**Comment by backslashgithub** [comment]
I know :-) but dos not respond on wat is de tijd en of what is the time.

**Comment by DieterKoblenz** [comment]
Probeer duidelijk te beschrijven wat je doet en wat het probleem is. Je gebruikt versie 0.10.0 toch? Dan zijn er grote problemen met de ingebouwde Nederlandse commando's. Zet Homey op Engels en dan zul je zien dat "Ok Homey, what is the time" wel de tijd geeft. 

In chrome kan je zien via http://HOMEYIP/manager/speech-input/ wat Homey denkt te ontvangen.

**Comment by DieterKoblenz** [comment]
In elk geval kijk even op Github/Forum rond of je probleem al bekend is:

https://github.com/athombv/homey/issues/883

**Comment by jeroenvollenbrock** [comment]
Duplicate of #883
