### ISSUE TITLE
Cannot select action on more than one lamp at a time

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#89]
When creating a flow that is to control lights, why do I need to drag every light separately into the Then column? I'd like to turn off all lights in the living room. Homey knows which lights those are, so make that an option to select. Make it possible to just check a series of lights for an action too, so so you don't have to set  up every light individually (quite a number of clicks if you want to turn them off with a delay)...

**Comment by freemann** [comment]
Grouping devices is on the feature list.

**Comment by AndreSomers** [comment]
Nice. But note that you already have a level of grouping when you put them into a specific room. Also, I'd still like to select more than one light from an action directly.

**Comment by bvdbos** [comment]
See also #275
