### ISSUE TITLE
IFTTT not working after .10

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#891]
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**
IFTTT Events are not triggered on Homey.
On IFTTT I can see that the recipe has been triggered but the IFTTT-Flowcard seems not to be triggered.
Haven't test if it works the other way around (Homey triggers IFTTT Recipe).

**Comment by WeeJeWel** [comment]
This is due to broken webhooks in 0.10. Will be fixed in 0.10.1!

**Comment by peaoo** [comment]
It is fixed now with 0.10.1! Thanks for the fast fix!
