### ISSUE TITLE
Timedate card "the time is earlier then.." behaves wrong

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#895]
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

Build a flow with this time card

*Please include detailed steps how we can reproduce the issue*

Use the time card and check when it should be true it is false.

**What was the result?**

Wrong result

**What did you expect as result?**

A correct result. Then it is earlier then the card should be give a positive value

...
![timedate](https://cloud.githubusercontent.com/assets/17949840/18815983/8351a08a-833f-11e6-8140-de611e63460c.png)

**Comment by jghaanstra** [comment]
I can confirm this. All my flows that have this card have stopped working with the 0.10.0 update.

**Comment by henkbb36org** [comment]
1. Homey system time is wrong since the update. 2. Time card "if time is later than.." works but "if time is earlier than..." is not working. Example: The time of a test  10:10, but the system time is 21:23. Time card "earlier than 23:00" results in a 'false'. Time card "later than 07:00" works correctly.

**Comment by bvdbos** [comment]
1) What is your system-time and your human time?

**Comment by henkbb36org** [comment]
As stated: human time 10:10, system time homey 21:23. I changed my location back manually, the location setting was changed after the upgrade but it was roughly in the same time zone (Afrika).

**Comment by magtimmermans** [comment]
For me the times are correct. 
![2016-09-26 10_29_33](https://cloud.githubusercontent.com/assets/17949840/18827658/426a46cc-83d4-11e6-9d26-62e69adc35a7.png)

**Comment by henkbb36org** [comment]
Double checked, I assume the system time is time that is said when using a time card. The human date/time under "System" is correct just as posting above magtimmermans . But the time pronounced by a time card is incorrect.

**Comment by goldenice** [comment]
This seems to be a tiny fault, introduced in the rewrite of Homey core. I've just submitted a fix, so this shouldn't occur starting from the next release.

**Comment by bvdbos** [comment]
@magtimmermans : I've seen reports this is fixed now?

**Comment by magtimmermans** [comment]
fixed
