### ISSUE TITLE
Badwords

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#896]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**
Give a demo of the iOS app to promote Homey

*Please include detailed steps how we can reproduce the issue*
I say in Dutch: "Ik kan er tegen praten ja"

**What was the result?**

Nothing happened. When I got home i'm a little bit shocked of the result:
<img width="388" alt="schermafbeelding 2016-09-25 om 19 01 53" src="https://cloud.githubusercontent.com/assets/13370203/18816897/349246f2-8353-11e6-852f-cfd7351b84b4.png">

**What did you expect as result?**

Nothing, but also no bad words in the result

**Any other remarks**

It's fun to promote Homey in parties. It's an interesting topic

**Comment by bvdbos** [comment]
Really? You want to sensor Homey? For misunderstanding? And for the name of an unfortunately common disease???

**Comment by kerkenit** [comment]
Not censuring Homey. But give the speech recognition a better library.

**Comment by WeeJeWel** [comment]
Haha, I guess that happens :) We're not going to 'fix' it by removing certain words anyhow. Thanks for reporting though!
