### ISSUE TITLE
Flow triggers daily instead of on a set day

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#897]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.10.0

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*

I want to use a flow:
     IF     |            AND       |           THEN
10:30hr | It's Wednesday | Say: Go to the Gym

**What was the result?**
It triggers daily
...

**What did you expect as result?**
Only on Wednesday
...

**Any other remarks**
Worked well before the last update
...

**Comment by philsniff** [comment]
same here

**Comment by Tweaqer** [comment]
Possibly related to #895

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
