### ISSUE TITLE
ASUN-650 status change doesn't trigger flow

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#898]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Trigger flow when status of ASUN-650 changes

*Please include detailed steps how we can reproduce the issue*

Make a flow with a status change card for ASUN-650 as IF trigger

**What was the result?**

Flow not executed

**What did you expect as result?**

Flow executed

**Any other remarks**

Status is correctly identified in both device 'set-up' page as well as using it as a condition in the AND column

**Comment by sleutelsnet** [comment]
Have you checked whether the KaKu apps has crashed?

**Comment by BasKiers** [comment]
Hi, thanks for your bug report. We found this to be a bug in 0.10.0 and this will be fixed in 0.10.1.

**Comment by BasKiers** [comment]
This bug was not resolved in v0.10.1, This affects all window_coverings.

**Comment by Dijker** [comment]
Homey Version 0.10.1 , KAKU v2.6.0 
Still a problem, 
an virtual ASUN650 can be switched with a remote or from the Homey Device. 
in both cases a flow with a status change card for ASUN-650 as IF trigger wil not trigger. 
Replacing the ASUN650 with  the virtual AC-300 socket is a workaround for me ....

**Comment by BasKiers** [comment]
I've found the issue, fixed and tested it. This should be fixed in 0.10.2

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
