### ISSUE TITLE
List of available lights drops out of screen when you have multiple items in the Then column

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#90]
If you put enough items in the Then column (as you need to because of lack of support for Hue scenes or multiple lights per lamp action), then you will find that the list of lights to select from will drop out of the available screen space, making it even harder to select the right lamp.

**Comment by WeeJeWel** [comment]
Fixed in 0.8.17

**Comment by AndreSomers** [comment]
Well, not exactly. The list way to select a device has changed from a generic lamp to a the actual lamps in the devices list (that could grow rather big...), but the interaction in the Flow screen if there are many items in a column still isn't good. Had to zoom out in Chrome to setup the Then for all the lights.

**Comment by WeeJeWel** [comment]
A scrollbar will be added, but that's a different issue :)
