### ISSUE TITLE
Newly added device always ends up in HOME zone

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#901]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Add a device to a zone (other than HOME)

*Please include detailed steps how we can reproduce the issue*

Added a device by clicking + in the respective zone

**What was the result?**

Device gets added to the HOME zone

**What did you expect as result?**

Device is added to zone you create it in

**Comment by goldenice** [comment]
Is this an issue with EVERY type of device, or just a few specific types (for example infrared devices)

**Comment by goldenice** [comment]
I have submitted a fix for the IR device that suffered this issue. If there are more device types that seem to have the same issue, please let me know.

**Comment by alledijkstra** [comment]
Z-wave devices also gets added to Home.

**Comment by Phunkay** [comment]
Sorry for the delayed answer... I noticed it when adding an IR device and confirmed it by adding a (random) IR device. Just tried with a KaKu device and that ended up in the zone I created it in.

**Comment by Inversion-NL** [comment]
Adding a device of my own app works as expected

**Comment by bvdbos** [comment]
Adding both IR, KaKu and Bitflip works for me...

**Comment by alledijkstra** [comment]
Z-wave devices are added to the correct zone.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
