### ISSUE TITLE
Presence in conditions

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#903]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Trigger actions when I'm getting home.
I've a kaku button in the hallway, a NFC card, GPS location on my iPhone and the Better Presence app. 
They all trigger me home or away based on conditions.
I've also a extra user "Bezoek van Marco"

In my flows I check if I'm home and mostly by visits are not at home. After auto upgrade to 0.10.0 the conditions are not working any more. 

**What was the result?**

I can set home or away, I can trigger home or away, but the conditions to check if I'm home or away are not triggerd. When I'm testing the flow, I'm getting the red exclamation mark, so something went wrong in the source code

**What did you expect as result?**

I can trigger geeky actions when I'm home and not when I've got visits

**Any other remarks**

Don't make a fool of me in front of my friends :-)

**Comment by jghaanstra** [comment]
Just noticed this as well. Strange thing is that in some cases flows do trigger. I do sometimes get messages from a flow that is triggered with the "a user got home" card. But it does not seem consistently. Will troubleshoot a little further and let it know here.

It seems the notification center reports the status correctly so it's easy to compare the received message with the messages in the notification center.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

**Comment by bvdbos** [comment]
https://forum.athom.com/discussion/comment/32985/#Comment_32985
Missing listener in presence-card.. Don't know if it's the same issue but it seems like it...

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
