### ISSUE TITLE
KaKu: AWMT-003 pairing not working, works as APA2-2300R 

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#904]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

To add an AWMT-003 via the Wizard

*Please include detailed steps how we can reproduce the issue*

Tried to add AWMT-003 as an AWMT-003 results in a button pressed, but after that the buttons cannot be checked. The rotate function is cool but has no function because the test buttons are not working.

Adding the AWMT-003 as an APA2-2300R has the perfect result. All concerned flows work.
Shortest solution: handle the AWMT-003 as a APA2-2300R and you're done! :)

**What was the result?**

Tried to add AWMT-003 as an AWMT-003 results in a button pressed, but after that the buttons cannot be checked. The rotate function is cool but has no function because the test buttons are not working.

**What did you expect as result?**

Tried to add AWMT-003 as an AWMT-003

**Any other remarks**

Adding the AWMT-003 as an APA2-2300R has the perfect result. All concerned flows work.
Shortest solution: handle the AWMT-003 as a APA2-2300R and you're done! :)

**Comment by BasKiers** [comment]
Hi,

I do not have an AWMT-003 to test with but I think the issue is fixed as of kaku 2.6.0. Could you try to pair your AWMT-003 as an AWMT-003 with kaku 2.6.0 installed and reply if the fix worked?

Thanks in advance,
Bas

**Comment by pimviergever** [comment]
The KaKu app stopped working after the 2.60 update. Had to disable the app, reboot and enable.
Added an AWMT-003 as an AWMT-003: works!
In my opinion the issue can be closed
