### ISSUE TITLE
Z-wave errors: serialport_not_open and driver_not_ready

### ISSUE THREAD

**Issue by HansieNL** [athombv/homey#905]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Connect z-wave device  (Fibaro Push Button via Fibaro app) to Homey.

**What was the result?**

I can't add a z-wave device, because I get always the error driver_not_ready.
I did try to save my region to Europen Union and get the message Error: serialport_not_open.

**What did you expect as result?**

Connection with Push Button

**Any other remarks**

Several resets and pulling power didn't solve the problem. Even deinstalled all apps except Fibaro one.
Reset with keeping date didn't solve the problem either.

[https://forum.athom.com/discussion/1964/z-wave-errors-serialport-not-open-and-driver-not-ready#latest]

**Comment by WeeJeWel** [comment]
Can you post a crashlog (Settings -> System -> Send log)?

**Comment by HansieNL** [comment]
Crashlog sent: 061D7F6866

**Comment by WeeJeWel** [comment]
Thanks! Will look into it after 0.10.1, then I'm gonna give Z-Wave some attention :)

**Comment by uNiiek** [comment]
Same Error for me. 
Crashlog: 0DEF3A3F19

**Comment by HansieNL** [comment]
@WeeJeWel: Any news on this problem?

**Comment by WeeJeWel** [comment]
Most likely fixed in the next update!

**Comment by uNiiek** [comment]
0.10.5 dit not fix this for me yet. 

I get now for more than 30 min: 
![z-wave](https://cloud.githubusercontent.com/assets/18580351/19349278/7fed317c-9152-11e6-94d4-b8bdcc2a46e3.png)

When i'm home i'll try PTP

**Comment by WeeJeWel** [comment]
Can you send a crashlog? And did Z-Wave ever work for you after >0.9.x?

**Comment by uNiiek** [comment]
Yes, till 0.10.x was z-wave no problem.
Log: 864FCC8929

**Comment by HansieNL** [comment]
I updated to 0.10.5, but zwave doesn't work at all. I get a message: Error getting version. And a pop-up shows: -------->ZM5304 FLASHING PROGRAM<--------
Starting programming sequence
sig: 7F 7F 7F 7F 1F 04 01
Signature valid.
State: 0
Reading NVR.
SAW frequency 0xFFFFFFFF
Fetched CRC16: FFFF
Calculated CRC16: C564
NVR CRC16 verified
Ereasing chip.
Writing NVR.
byte 0xBF did'nt pass verification! got BF expected FF
Error writing nvr, can't continue
stopping

When I try to save region I get: 
-------->ZM5304 FLASHING PROGRAM<--------
Starting programming sequence
sig: 00 00 00 00 00 00 00
Signature not valid!
Invalid signature, can't continue.
stopping

**Comment by uNiiek** [comment]
Same eroor after PTP: 
Z-Wave is loading, please wait...

Log after PTP: 502A0C4DD6

**Comment by HansieNL** [comment]
Crashlog: 466A066033

**Comment by jeroenvollenbrock** [comment]
@uNiiek: Your log does not show any z-wave errors or even an attempt to change the region, and even shows a loaded chip. Are you sure you are still getting the same error?

@HansieNL: Would you perhaps be willing to message me on slack (https://slack.athom.com, @jeroenvollenbrock) for some additional debugging? Your log shows some things that should definitely not be happening...

Thanks in advance!

**Comment by uNiiek** [comment]
@jeroenvollenbrock Uptime of my Homey after the 0.10.5 updat is: uptime	10546.
If i go in the setting screen to Z-Wave it says: Z-Wave is loading, please wait...
![z-wave](https://cloud.githubusercontent.com/assets/18580351/19363373/78b2eff4-918a-11e6-8a58-eee451a5af11.png)

If i go to add new device, i see this:

![zwave in gebruik](https://cloud.githubusercontent.com/assets/18580351/19363465/e604a944-918a-11e6-90ef-ce5815b0b480.png)

If i want to add my Greenwave powernode i get this:

![driver not ready](https://cloud.githubusercontent.com/assets/18580351/19363493/041d217c-918b-11e6-91b5-a9ddb3598837.png)


Thanks for the reply!

**Comment by WeeJeWel** [comment]
This bug is a pretty tough one. We expect to have it fixed within 2 weeks. If that's too long, please contact support@athom.com to get a replacement Homey. Note that when you do this your user settings will be lost.

**Comment by kingdong78** [comment]
i Have the same issues.
 i can't add any fibero or z-wave items because of the same issues unlike has

**Comment by kingdong78** [comment]
see here my screen prints
![schermafbeelding 2016-10-15 om 11 37 45](https://cloud.githubusercontent.com/assets/17185881/19409051/179ed55a-92cc-11e6-8197-49f37931ea6e.png)
![schermafbeelding 2016-10-15 om 11 38 39](https://cloud.githubusercontent.com/assets/17185881/19409053/1f794b70-92cc-11e6-95a5-d0a745e46995.png)
![schermafbeelding 2016-10-15 om 11 38 49](https://cloud.githubusercontent.com/assets/17185881/19409054/2b0033fa-92cc-11e6-9884-81195b1ad23e.png)

**Comment by uNiiek** [comment]
@WeeJeWel i can wait for another 2 weeks. 
Hope you fix them within 2 the weeks!
otherwise I going to need a replacement Homey.

**Comment by uNiiek** [comment]
@WeeJeWel Any idea of problem would be fixed in 0.10.16?

**Comment by bvdbos** [comment]
Think your mixing up some bugs....

@WeeJeWel commented 4 days ago : This bug is a pretty tough one. We expect to have it fixed within 2 weeks

uNiiek commented a day ago : @WeeJeWel i can wait for another 2 weeks. Hope you fix them within 2 the weeks! otherwise I going to need a replacement Homey.

uNiiek commented 2 hours ago : @WeeJeWel Any idea of problem would be fixed in 0.10.16?

**Comment by uNiiek** [comment]
nope just curious....

**Comment by HansieNL** [comment]
Any news about solving this bug? I hope I can use my Fibaro Push Button soon.

**Comment by jeroenvollenbrock** [comment]
The calibration data of the affected Z-wave modules has been lost, and requires re-calibration before the Z-wave module is able to operate again. We have taken steps to assure the calibration data of the Z-wave module is properly backed up in the future, and attempted to make a tool to recalibrate the Z-wave modules remotely using the other 868MHz transceiver on Homey. 

Unfortunately, this approach is not accurate enough to maintain the Z-wave range, and therefore we have decided to replace all Homeys that are affected by this bug. Please contact support at support@athom.com, mention this ticket (#905) and include the following information:
- Your Athom Cloud ID (Settings->system)
- A screenshot of your zwave settings page including the "stuff for geeks" section.
- A log ID (system->send log)
Our support staff will then further guide you through the replacement process.

We sincerely apologize for any inconveniences this issue may have caused.

**Comment by uNiiek** [comment]
Received my new Homey. Problem is solved for me.
