### ISSUE TITLE
Avatar is missing in Notification Center

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#906]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

I've asked my girlfriend to join Homey. I've created an account, set up an avatar before adding her. I just noticed that the avatar showing in the notification center is incorrect, this is the default avatar while it should display the one i've created. 

![schermafbeelding 2016-09-26 om 22 19 57](https://cloud.githubusercontent.com/assets/17526110/18850487/0decaea8-8438-11e6-80c1-0a8ed7bcb866.png)

**What did you expect as result?**

Correct avatar to be set-up

**Any other remarks**

Sort of related to: #693

**Comment by Arjanvde** [comment]
I know it sounds stupid, but I based this on a post from @WeeJeWel 

![screen_shot_2016-09-17_at_00 34 13](https://cloud.githubusercontent.com/assets/17526110/18850915/dfd4bf0e-8439-11e6-9660-fca3f9a43cf4.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

**Comment by philsniff** [comment]
Sorry, but my avatar isn't shown! Singe the beginning i think from 0.8 
I made my account without Avatar. When my homey arrived i loaded up a picture. Now my Account Shows my correct Avatar. But in homeys startpage and in the upper right of my screen in the notification center there is still the default grey avatar

**Comment by Arjanvde** [comment]
@philsniff that's a different issue #693, which is still outstanding.

If you set up everything correctly before adding the account to Homey the Avatar is shown.

**Comment by philsniff** [comment]
ok, thx @Arjanvde ! but #693 is old and closed. so is ther anybody fixing this now or is it forgotten?

**Comment by Arjanvde** [comment]
@philsniff, #693 is still open. It's an old one, I know.

**Comment by WeeJeWel** [comment]
It's probably fixed but if you came from an old Homey version the settings still have your old avatar URL. I think that when you wipe it it's correct, but that might not be totally worth it ;)

**Comment by Arjanvde** [comment]
@Weejewel as soon as no avatar is setted and the avatar is setted after the account is synced, the avatar never shows.

You can try this also if you add a new user. @jeroenvollenbrock fixed this with a repair script.

**Comment by Arjanvde** [comment]
The repairscript was for #693.

**Comment by philsniff** [comment]
Ok, a repair script would be fine to have. Is it possible @weejewel ? When not so easy than it is okay. But it there would be a Little was to fix it ...

**Comment by WeeJeWel** [comment]
0.10.2 will fix your avatars :-)

**Comment by philsniff** [comment]
Thumb up @WeeJeWel!
