### ISSUE TITLE
[Enhancement] Delete notifications

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#908]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

It seems to be impossible to delete any notifications. Would be convenient to have a button to remove all notifications and to remove some notifications.

**What was the result?**

A lot of notifications.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

**Comment by Arjanvde** [comment]
Solved
