### ISSUE TITLE
Can't add 433 switch as lamp

### ISSUE THREAD

**Issue by Trustme2** [athombv/homey#909]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Add an Action switch device(Promax 55010x10) as a lamp

*Please include detailed steps how we can reproduce the issue*

1. Add an Action switch device(Promax 55010x10)
2. Assign it as a lamp

**What was the result?**

Homey does not recognise it as a lamp. 
It's just a switch and if you tell homey to turn on the lights it says: No lights were found.

**What did you expect as result?**

To add the  Action switch device(Promax 55010x10) as a lamp (like it was able to before 0.10.0

**Any other remarks**

Sometime Adding a switch takes a long time, many presses (>50) or even a reboot to add a device.

**Comment by WeeJeWel** [comment]
Can you make a screenshot of the device in the Zones & Devices screen?

**Comment by Trustme2** [comment]
I can do you one better: https://www.youtube.com/watch?v=pGlAXjDgctU

**Comment by BasKiers** [comment]
Thanks for your video, it helped explain the problem you were having. I've fixed this issue in the action app v2.1.1.
