### ISSUE TITLE
Unclear how to respond to specific spoken command

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#91]
When creating a flow, I'd like Homey to respond to a command like "Ok Homey, going to bed". So, I drag the Microphone to the When column, and then... what? No idea. Can't configure anywhere when to respond, there only is a tag available with what I said. This is not clear at all.

**Comment by freemann** [comment]
So the video for more info:
https://youtu.be/pztkJfZO2u0

A lot of things are indeed very unclear for "new" users and i think thats a big point the should look at.
Maybe its an idea to put some sort of "question mark icon" with a help popup.

**Comment by AndreSomers** [comment]
Strange. In the video (at around 14:30) you see Emile adding a microphone item to the When. I did the same, but I do not have the option to type anything in that box  or to flip to a card that does allow that. 

I just noticed, that now I _can_ flip to a card that allows me to enter something.

**Comment by WeeJeWel** [comment]
Please update to 0.8.17 to get that card.

**Comment by AndreSomers** [comment]
Solved in a newer version of the software than I was using when reporting this issue.
