### ISSUE TITLE
Cron jobs persist after app removal

### ISSUE THREAD

**Issue by DiedB** [athombv/homey#910]
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
Added a cron job, removed an app, re-installed the same app.

**What was the result?**
The cron job persists through app removal.

**What did you expect as result?**
The cron job should be deleted when the corresponding app is removed from Homey.

**Comment by WeeJeWel** [comment]
Fixed in 0.10.1!

**Comment by DiedB** [comment]
Thanks so much!

**Comment by DiedB** [comment]
Can confirm that this has been resolved.
