### ISSUE TITLE
Soundcloud app not present in flow page

### ISSUE THREAD

**Issue by bobenoni** [athombv/homey#911]
**What is your Homey version (Settings → System)?**

0.10.0 (was like this in previous fw also)

**What did you try to achieve?**

Using a flow with soundcloud. Under "apps" in the flow section, soundcloud is nowhere to be found.

*Please include detailed steps how we can reproduce the issue*

Not sure you can. Install soundcloud - app's not there under "apps" in the flow page. App shows in settings page.

**What was the result?**

Can't use soundcloud app
...

**What did you expect as result?**

Be able to use app
...

**Any other remarks**
Tried disabling/uninstall/reinstalling app. PTP.

Haven't tried resetting Homey yet, with/without settings.

**Comment by WeeJeWel** [comment]
The soundcloud app works using the Media manager, and has no Flow cards on its own, but that has been removed temporarily in 0.10. It'll be back!
