### ISSUE TITLE
getCapabilities return undefined 

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#915]
**What is your Homey version (Settings → System)?**
0.10

**What did you try to achieve?**
The function module.exports.getCapabilities callback undefined in data for devices that is added and did get a result back before 0.10.

**Comment by WeeJeWel** [comment]
What is your code? It seems to work here.

**Comment by ewikner** [comment]
You can see the code at [GitHub](https://github.com/ewikner/org.mysensors.homey)

**Comment by WeeJeWel** [comment]
Hm, seems fine. Please report back after 0.10.1, it might've been an concurrency thing.

**Comment by ewikner** [comment]
Ok, i will report back after 0.10.1

**Comment by ewikner** [comment]
We get the same error in 0.10.1.
After some digging I think I have find what have changed.
Before 0.10 the result from the module.exports.getCapabilities was an array with objects like this  [{id:'measure_temperature'}, {id:'measure_humidity'}] and now it is just an array ['measure_temperature', 'measure_humidity']
So the problem is when I use the result in a loop we get the value from obj.id but now it's just obj.
I got the structure from WeeJeWel on Slack when I requested this function to be added.

That is why the mysensors app is crashing.

Can you explain why you have changed this and how will it be from now?
Then I can change in the app and make an update.

**Comment by markaswift** [comment]
Sucks... The MySensors app is my most used app... Subscribed.

**Comment by WeeJeWel** [comment]
What you get now is the right array. So simply an array of strings!
