### ISSUE TITLE
Very Limited Z-wave range

### ISSUE THREAD

**Issue by zperx** [athombv/homey#918]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Use my Fibaro Multisensors (ZW+) on ground floor connected directly to homey without range extender. The floor area is 35m2, all internal walls are platerboard. The house has no steal beams or concrete walls or slabs. It is a quiet suburb, with no real signal interference. Homey sits in the centre line of the house. 

**What was the result?**

The max range what Homey can provide is 4-5m with direct view, or less then 3 meters if the sensor behind a plasterboard wall.

**What did you expect as result?**

To have a range of a Bluetooth (what works on a higher frequency and in a band with more interference). (BT can cover my whole house and garden) Or even with decreased expectation to cover at least the ground floor area. 

**Any other remarks**

Last weekend I took homey out in the garden to measure the range in a true open space and to be able to compare it with maximum ZW+ range of 150 meters. However the max range I could receive outdoor was only a mere 7 meters.

**Comment by sossienl** [comment]
same issue here.

**Comment by Fiek1** [comment]
I have installed neo plugs. The one that is < 4metres from homey works ok. The other one is further away about 6 metres on the same floor with no walls and that one cannot be switched on and off most of the time. I see in the z-wave log that the plug sends data to Homey. So there must be something with sending range of homey I think

**Comment by djeskoswe** [comment]
Same problem here with an AEO_ZW075 , slow response and sometimes no response , 4 m max and open space.

log file after on/off switch with slow response :  CC8F76B692

**Comment by WeeJeWel** [comment]
I'm closing this issue as all range problems should have been resolved by now. If there are still issues that are debug-able, please let me know.

**Comment by Fiek1** [comment]
I bought Neo plugs to have coverage on the first floor, but the Neo plugs dont receive the signal from Homey. I have two Neo plugs on the lower level and two on the first Floor. The ones on the lower level work, but in the first Floor they dont work. Still A range problem. The distance between the Neo plugs is maybe 5 metres

Can you please advice? I can give you access to my homey.
