### ISSUE TITLE
Unclear how to couple IR remote

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#92]
Homey can learn my IR remotes it sais, but in the interface it is very unclear how to do that. In the flow editor I can add an IR device, but there are no devices yet. But in the Zones and Devices section, I can't find how to add one. It does not appear as an already available app, nor does something turn up if I look for an app for that. 

So it is unclear how to train Homey to my remotes.

**Comment by freemann** [comment]
https://youtu.be/pztkJfZO2u0?t=5m30s

Here's some more info from Emile

**Comment by AndreSomers** [comment]
Ah, right. Thanks for that link. I did remember seeing Emile doing it in the video, but in the interface, it is not clear to me. So, perhaps something can be done to make it more obvous that you can actually open up the Homey device and do more there. Or, add a link from the Flows screen directly to add a new device. Something like that.

**Comment by Sateprikkert** [comment]
I second that. The interface does not provide enough hints on how to add an IR remote.

**Comment by freemann** [comment]
I'm with you on the unclear subject. 

On Git and the forum there are a lot of questions about things are unclear. Maybe its an idea that Athom creates "page/function/feature help icons" next to most complicated functions.

If Geeks has these troubles, the "normal" user will definitely experiences it to.

**Comment by hschenkelaars** [comment]
I tried to add2 different Remotes, after viewing the video, but it just doesn't work ?
When I try to add a remote the ring is switched of like it is processing something but nothing happens. Even when holding down a button more than 3 seconds or continuously switching a button for more than 3 seconds.....
I'd like to know how I could check if the IR is working on homey ?

Anybody an idea

**Comment by Sateprikkert** [comment]
@hschenkelaars maybe you should add your problem in issue #96

**Comment by goldenice** [comment]
@AndreSomers Adding a device is always done through the pairing wizard in Zones & Devices. Just press the + button, and select 'Homey' in the apps list. The whole of IR can be seen as one device type, which is installed by default. The video mentioned by @freemann shows how to start the IR pairing.

If the IR pairing wizard starts (the blue spinning circly thingy), but doesn't recognize your remote, please continue the discussion in #50. There are more people with the same problem, and I'm already working very hard on a solution, as mentioned earlier in issue #50.

**Comment by AndreSomers** [comment]
I will try doing that later. However, the point of this report is that this workflow is not at all clear to me. It did not occur to me that I need to click a device already in the list of devices in order to add a new device (an IR remote). It is not clear that existing devices can be expanded at all... So, I guess this is a bit of a UX issue.

**Comment by goldenice** [comment]
Maybe it is a bit unclear that those **aren't** devices. They are device **types**. You can see them as the 'blueprint' for a device. For example: I could start the IR pairing wizard to attach a new device. Until a remote has actually been paired, it's not a device as such in Homey.

When you understand it it's actually very logical, but I agree, perhaps it is a bit unclear.

**Comment by AndreSomers** [comment]
If things shown in a Zones & Devices page are not either zones or devices, then it is indeed unclear.

**Comment by goldenice** [comment]
On the left hand they are zones, on the right they are devices, except for when you click the plus and start the process of adding a new device, then they're devicetypes, or more abstractly: "things you can add but are not devices right now". When that process is done, you get back to the overview of zones and devices.

**Comment by AndreSomers** [comment]
Ok, good point. Perhaps it would already help if typing IR in the search box would also show the Add IR device option of Homey. I notice that typing "infrared" will show the Homey device, but it may be clearer if with the Homey device it would specifically find and show the "infrared" option.

**Comment by AndreSomers** [comment]
Did the issue get resolved all of a sudden? Even if I understand it _now_ does not change the fact that it is not obvious in the UI.

**Comment by goldenice** [comment]
Actually yes. A new IR pairing wizard is on the way, we're already fixing this.
