### ISSUE TITLE
Unreliable Speech recognition 

### ISSUE THREAD

**Issue by zperx** [athombv/homey#920]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

To initiate flows and built in commands by speech (on English).

**What was the result?**

Sometimes the speech recognition is flawless and fast for couple of minutes. Then it goes back to the to it`s worse shape when its slow and does not understand anything. It fails to even get the right number of words. And the interpretation of the speech has not even remotely close to the sentence.

**What did you expect as result?**

A **constant** 8-9/10 accuracy. Above result strongly suggest that there is one good, accurate engine and sometimes the speech is processed by that. But most of the time it goes through inferior engines. 

**Any other remarks**
Could you please give an option to the users to disable some of the speech2text services?
It is not just my accent. We get the same (or worse) results when others try.

**Comment by Fire69** [comment]
https://github.com/athombv/homey/issues/1241

**Comment by Joolee** [comment]
_"OK Homey. Remind me at nine 'o clock"_
![OK Homey. Remind me at nine 'o clock](https://joolee.nl/images/remind%20me%20at%20nine%20o%20clock.png)

_"OK Homey. Herinner me over 12 minuten aan de oven"_ (Parrot flow still in English)
![OK Homey. Remind me at nine 'o clock](https://joolee.nl/images/remind%20me%20at%20nine%20o%20clock.png)

These are not worst case examples, it simply doesn't get any better. I think my success rate is ~3-5%

Not included in these screenshots are the times Homey simply doesn't do anything after spinning white and the times Homey keeps spinning orange until a timeout is reached. The "OK Homey" command works okayish though... ~70% hit rate.

**Comment by jabroersen** [comment]
Also speech recognition often just stops. On the iPhone as well as homey itself. A reboot fixes this. Especially on the phone-app this is weird, the app is still running but doesn't react to any voice command.

**Comment by zperx** [comment]
Still no improvement on this. https://youtu.be/UXEOUaf6Nq8

**Comment by Fire69** [comment]
Unfortunately, still the same experience here.
Every day I try to make Homey do something (knowing that it will fail) and every day I'm frustrated that it's not working...

**Comment by Schagalaah** [comment]
Same for me. When will speech get better? Currently it is still unusable.

**Comment by Fire69** [comment]
I'm getting really frustrated here guys, I can't use a single voice command without having to repeat myself 5-6 times.
This is completely useless... I just use the light switch now, or the tv remote, or ...

Is there ANY feedback about this?
If you can't solve it, then just say it's hardware and we just have to accept it.  It's been 2 years now without any real answer from Athom.

Standing right next to Homey, this is the result. Complete rubbish... It's always missing words or just understanding completely wrong ones.
![image](https://user-images.githubusercontent.com/1757287/31627531-e5dcc40c-b2ad-11e7-985f-3388992e58e6.png)

**Comment by fcmodderkak** [comment]
Looks like this is one of the last ones open on this topic, as the rest has been marked "duplicate" and are closed. 

Question to Athom @Tweake @jeroenvollenbrock @BasKiers , are you guys still working on this? Can't use voice command if I'm not within a 1m range of Homey.

**Comment by flipflopsandrice** [comment]
Is this still on Athom's radar?

If not, I would highly recommend not using speech input in Homey marketing at all and being honest with new and existing customers. People expect an Alexa/Google Home experience, but Homey currently does not deliver this at all.

**Comment by jsm198** [comment]
Sorry to say, have the same problem. Voice recognition is very poor. Should be a easy fix?! Why not just just ie Watson Speech to text? https://www.ibm.com/watson/services/speech-to-text/ Understand that it can be a cost issue - make it as a Premium feature or Freemium (with ie a numer of commandes free / day and for more Premium is needed).

**Comment by jabroersen** [comment]
Same here...speech is totally unworkable. I created Virtual Devices (great app by Arjan Kranenburg) for most voice commands. I also would definitely pay for a premium service with working voice service!

**Comment by WeeJeWel** [comment]
Closing this issue because speech will not be actively improved upon anymore. For more details I invite you all to read our explanation why at our blog: https://blog.athom.com/take-speech-music/.
