### ISSUE TITLE
LED Ring goes off in flow

### ISSUE THREAD

**Issue by edtst** [athombv/homey#921]
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

Turn the LED ring on and off by pressing a button on the remote

*Please include detailed steps how we can reproduce the issue*

I created a flow where a KaKu device is turned on, it turns on the LED ring. My default is off.

**What was the result?**

The LED ring turns on in the desired colour, but afte ra few seconds it goes off.
...

**What did you expect as result?**

That it would stay on.
...

**Any other remarks**

...

**Comment by jeroenvollenbrock** [comment]
Are you sure you've used the "change screensaver" card, not the "flash color" card?

**Comment by edtst** [comment]
I am in Ducth and used Animeer/"Vaste Kleur". 
When I use 'Zet Screensaver', I do not see an option to select a colour.

**Comment by jeroenvollenbrock** [comment]
The Animeer/vaste kleur card is meant for short notifications. In the future a duration field will be added to this card. If you want the ledring to stay at a certain color for a longer amount of time, you'll need to use a screensaver. Please note that Homey apps can provide additional screensavers.

**Comment by edtst** [comment]
OK. Not sure if thi sis the right place, but it might be interesting for others. How do I make a flow in which a screensaver lets Homey's stay lit in a certain colour? I don't see such a screensaver

**Comment by caseda** [comment]
Screensavers are added into an app, so if you want a solid color you will need to create an app (an app with just a Screensaver is possible) 
Or ask one of the developers to implement it in their app. 
There was a Screensaver app, but it's development has stopped (was never added to the app store either) 

After that you can specify that specific Screensaver in flows.

**Comment by edtst** [comment]
Thnx
