### ISSUE TITLE
Command specific to a room doesnt work

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#930]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.10.1
Philips Hue v1.0.5

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*
I tried turning on the lights with the command: "doe het licht in de woonkamer aan" where Woonkamer is the roomname. I also tried it for other rooms but with the same result.

**What was the result?**
Homey responds with: I cant find any lights to turn on in that room. However they do display in the devices menu and they can be controlled.
...

**What did you expect as result?**
Turn on the lights specific in the mentioned room ie. woonkamer.
...

**Any other remarks**
When I use the command 'turn on the lights' it turns on all the lights including those in the woonkamer.
...

**Comment by Inversion-NL** [comment]
Yes, tried every possible way but only 'lights on' switches the lights

**Comment by cjvs** [comment]
Same with me. Adding standard locations as kitchen and living room in a request to Homey results in a "I did'nt find lights to turn on" response.

I came from a fresh reinstall of Homey 0.10.1, with kaku 2.6.0 and philips hue 1.0.5.

Log 3D62CF2F8F

**Comment by Tweake** [comment]
This was an issue which snuck in with the 0.10 rewrite. It will be fixed as of 0.10.2. Thanks for reporting!

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
