### ISSUE TITLE
Old z-wave devices popped up?

### ISSUE THREAD

**Issue by Tweaqer** [athombv/homey#931]
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.10.1

**What did you try to achieve?**
*Please include detailed steps how we can reproduce the issue*
I opened the devices tab and I get a lot of old zwave devices that are unreachable/greyed out but I can not delete.

**What was the result?**
Greyed out devices.
...

**What did you expect as result?**
I want to delete them
...

**Any other remarks**

...

**Comment by Inversion-NL** [comment]
I could successfully delete them, including Z-Wave devices

**Comment by jeroenvollenbrock** [comment]
@Tweaqer What happens if you try to delete them?

**Comment by Rocodamelshe** [comment]
There is no way to delete them it seems.

![2016-09-29 20_18_51-homey zones devices](https://cloud.githubusercontent.com/assets/19249884/18966684/6bd4b7d0-8682-11e6-8dc4-20a0214a1928.png)

**Comment by bvdbos** [comment]
yep, same for me...

**Comment by Tweaqer** [comment]
i was going to post the exact screenshot just with a different name and more than one

**Comment by daneedk** [comment]
Same here, no icons appear when I hover my mouse over the image.

**Comment by bliekp** [comment]
Same here. The devices are old Z-Wave devices which I already excluded and excluded since they disappeared because of Z-Wave rewrites in the Homey software and new apps for them.

Very annoying!

**Comment by WeeJeWel** [comment]
Whoops. I'll fix this in the next update :)

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.
