### ISSUE TITLE
Invalid_token on Android

### ISSUE THREAD

**Issue by elcovb** [athombv/homey#932]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

I did a clean install of Homey for Android (Samsung Galaxy S7 edge, Android 6.0.1. I opened the app and it instantly crashed and restarted. After that it asked for permission to find my location and to listen to my voice. After that, it showed a white popup saying 'Invalid_token'. The popup reappeared when I clicked 'Devices'.

**What was the result?**

A white popup saying 'Invalid_token'.

**What did you expect as result?**

To see my devices.

**Comment by elcovb** [comment]
I found out, with help of another user on Slack, that you have to log out and log in to resolve this issue. So the issue is that the app doesn't filter out this error and send the user to the login screen while it should.

**Comment by jeroenvollenbrock** [comment]
This issue is resolved in Android app version 2.3.0
