### ISSUE TITLE
Action cards with dropdowns give error #500 (invalid_device_data or invalid_card)

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#933]
**What is your Homey version (Settings → System)?**
1.10.1

**What did you try to achieve?**
Use a action card from the Harmony Hub and Hyperion app. These cards have a dropdown that is propagated while querying an external device.

**What was the result?**
A 500 internal server error on the query request. Below an example for the card to try and set an effect for Hyperion.

api.js:1 GET http://<<ip>>/api/manager/flow/card/homey:device:<<id>>/action/effect/autocomplete?name=effect&query=&args%5Beffect%5D=&_=1475171753118 500 (Internal Server Error)

The card itself shows "invalid_device_data" of "invalid_card".

**What did you expect as result?**
A dropdown unfolding with the options that you can choose from

**Any other remarks**
The Harmony Hub app also crashes when trying to select a activity from the action dropdown with the following stacktrace. Might be a different issue but it happens when selecting the dropdown.

```
TypeError: Cannot read property 'ipaddress' of undefined
at Object.<anonymous> (/app.js:215:79)
at emitTwo (events.js:87:13)
at Object.emit (events.js:172:7)
at /homey-app/manager/flow.js:1:417
at /homey-app/helpers/client.js:1:1013
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:982)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12

Exit code: 0

```

**Comment by WeeJeWel** [comment]
These are app-specific issues due to a change in the autocomplete API.

For Logitech Harmony, I've notified the developer.

**Comment by WeeJeWel** [comment]
https://github.com/brinkie2004/com.logitech.harmony.hub/issues/1
