### ISSUE TITLE
Set Dimmer brightness level in flow not working

### ISSUE THREAD

**Issue by StraDijk** [athombv/homey#934]
**What is your Homey version (Settings → System)?**

0.10.0/0.10.1

**What did you try to achieve?**
Set dimmer level in flow

**What was the result?**
The level was not set

**What did you expect as result?**
That the level is set on the value given.

![untitled](https://cloud.githubusercontent.com/assets/2519741/18968166/3e83cc7a-8688-11e6-80f2-10b4c2a38f41.png)

**Comment by caseda** [comment]
Did it work before the 0.10 update?
what app version are you using
And What device are you using the FGD-211 or the FGD-212

**Comment by alledijkstra** [comment]
Never had the dimmer paired before 0.10..
FGD-212 with Fibaro 1.0.11

**Comment by caseda** [comment]
I will look into it if it is the app, when I get home this afternoon. (probably not, it worked for me before .10 update) 
can't check it now, don't have it paired at the moment. 

It does turn on and off properly?

**Comment by caseda** [comment]
ah, i know what is wrong,
it does dim,
but it **also** sends the onoff true command afterwards which puts it back into its the old dimming position.
That's something i can't change.

```
[debug] set dim 1
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL ->SWITCH_MULTILEVEL_SET args: { Value: 99, 'Dimming Duration': 1 }
[debug] set onoff true
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL ->SWITCH_MULTILEVEL_SET args: { Value: 'on/enable', 'Dimming Duration': 1 }
```

@RobinBol could you please look at this issue? or assign the capability guy to it.

**Comment by bvdbos** [comment]
I have the same with KaKu on 0.10.3 and KaKu 2.6.0...

**Comment by MdeRhoter** [comment]
Yep, me too

**Comment by bvdbos** [comment]
- bump -

**Comment by jeroenvollenbrock** [comment]
We are aware of the issue and are going to change the behaviour. However, some apps are currently depending on this functionality and will break after such a change. Therefore, we are going to delay this a bit and update our app guidelines to specify how an App should react to brightness changes when the light is switched off. We'll proceed with the implementation and deployment of this change in the next update that has more scheduled api changes.

**Comment by daneedk** [comment]
Is there a relation with this issue: #958 ?

**Comment by goyaweb** [comment]
This issue prevents all [melatonine optimizing](http://www.lifx.com/blogs/light-matters/57749955-can-light-improve-your-sleep-we-think-so) and [waku-up-light](https://forum.athom.com/discussion/1981/wakeup-light) flows together with [this issue](https://github.com/athombv/homey/issues/1122). Any news?

**Comment by ralfvd** [comment]
Since 1.0.2 the behaviour changed, and there is a difference between dimming in the device card (no on/off command is sent) and in a flow ( the on/off command is sent) . Can you give an update?

**Comment by bvdbos** [comment]
ping

**Comment by Arjanvde** [comment]
Hope this issue is fixed soon, with the current function of setting a dimming level by variable it would be fun to create a wake-up light with the fibaro dimmer.

**Comment by PatrickSannes** [comment]
Got the same problem...
What I see happening is:
First this message is send to the dimmer:
017-01-11T17:57:13.201Z    Keuken    ["dim",0.16]
Adn then a little later the original is set
2017-01-11T17:57:13.532Z    Keuken    ["dim",0.76]

**Comment by 2benl** [comment]
Same problem with dimming over here. Would love to see this fixed, especially because it lowers the WAF here at home.

**Comment by ericjanvanputten** [comment]
ditto here

**Comment by Arjanvde** [comment]
Looks like this is fixed, tested this with the Fibaro dimmer. Could somebody else checks this as well?

**Comment by ericjanvanputten** [comment]
on version 1.19 still have the issue

**Comment by Arjanvde** [comment]
Sorry my last comment was incomplete, this is on the latest firmware 1.1.4 (experimental).

**Comment by ericjanvanputten** [comment]
upgrading now from 1.1.2 to 1.1.4 :)

**Comment by ericjanvanputten** [comment]
Nope, still goes up and then down again quickly... no difference.

**Comment by caseda** [comment]
That's because the fix (if it is implemented) needs to be added to all corresponding apps still. Won't be just an homey update

**Comment by PatrickSannes** [comment]
On my homey with the developer preview firmware it is still broken.

**Comment by StraDijk** [comment]
1.1.4 Same issue

**Comment by caseda** [comment]
i'm curious if people even read what i just said:

the **FIX** if it is implemented at all, cause it seems like the fix isn't even in 1.1.4

is **ALSO** needed to be done in **ALL** z-wave dimmable _devices' drivers_ and not just in a homey update.

so even if the fix solution is there in homey's core, every z-wave app needs to update this as well...
no matter how many time everybody tries.

**Comment by ericjanvanputten** [comment]
I do think that people read your post @caseda, but earlier by @Arjanvde it is 'requested' to see if it works properly with others. So I do think more people can give feedback if it works now or not. (probably hear more 'not' then othewise)

**Comment by WeeJeWel** [comment]
As of Homey v1.2.0, for a capability `onoff` a capability option `setOnDim` can be set to `false` to prevent Homey from sending an onoff=true when also setting a dim.
