### ISSUE TITLE
Custom capability value not updated in device card after update to fw 0.10.1

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#935]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**
Updated the firmware to 0.10.1. Then display the Plugwise Smile P1 device card in a webbrowser.

*Please include detailed steps how we can reproduce the issue*
Pair a Smile P1 device, and display the device card in Chrome.

following code is used in the driver:
```
module.exports.capabilities = {
    measure_power: {
      get: function(device_data, callback) {
        var device = devices[device_data.id];
        if (device==undefined){
          callback(null, 0);
          return;
        };
        callback(null, device.last_measure_power);
      }
    },

    meter_offPeak: {
      get: function(device_data, callback) {
        var device = devices[device_data.id];
        if (device==undefined){
          callback(null, false);
          return;
        };
        callback(null, device.last_offPeak);
      }
    },
```

**What was the result?**
The custom capability meter_offPeak is not updated anymore. The value that was present during pairing is always presented.
...

**What did you expect as result?**
The custom capability to be displayed correctly in the device card, just as the default capabilities
...

**Any other remarks**
The standard capability meaure_power does get updated as it should.
The custom capability meter_offPeak also used to get updated correctly in fw 0.9.3
...

**Comment by jghaanstra** [comment]
Seems to be related to https://github.com/athombv/com.greenwavesystems/issues/10

I either see no value or a static value for the measure_power capability on Greenwave powernode-6 devices.

**Comment by JPe2** [comment]
Same for me with Greenwave powernode-6 devices, 

also LaCrosse shows values at start-up but te values are not updated as well in V0.10.1.

**Comment by gruijter** [comment]
Ok, I found the problem. It was a typo in my own code ..........

This is the correct code that updates the value:

```module.exports.realtime(devices[device_data.id].homey_device, "meter_offPeak", offPeak);```

 I misspelled offpeak, and therefore the capability never got updated.

problem solved
