### ISSUE TITLE
IR not working

### ISSUE THREAD

**Issue by ErwinOne** [athombv/homey#937]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

- Add IR remote for Samsung TV UE55H7000 by choosing "Samsung meerdere modellen"
- Build flow to send command 'Power On' or 'Smart Hub'

**What was the result?**

- No response from the TV
- No IR emitted from Homey (verified with camera, but no purple-ish pulses of light)

**What did you expect as result?**

Responding TV

**Any other remarks**

Also when telling Homey to respond to a button on the remote being pushed, it does not respond.

And also the same is the case for when I add the remote by programming the specific buttons so 'Kopieer van afstandsbediening' (not using the predefined remote).

And also the same is the case for when i program a remote for my AXA Remote (Electronic Window opener using IR remote).

And also tried this with the Philips default remote (Philips 6PFL) when adding an IR device. But also no luck.

Also already tried a reboot and before that deleted all IR devices. After reboot added only one IR device and then performed the above tests again, but no luck.

**Comment by bvdbos** [comment]
Does this happen when you only have one IR device?

**Comment by ErwinOne** [comment]
It happens both when I have only one IR device and also when I have 2 or more IR devices.

**Comment by nattlip** [comment]
1+  added horizon ziggo device. flow kees running infinite no fleshes from homey with htc camera.

**Comment by ErwinOne** [comment]
Apparently the IR now does work (after another reboot and clearing all IR devices). 

But when Homey stands 6 meters away and at a 45 degree angle, it's apparently to far to be received by the Samsung TV. The TV remote does work from this distance...
