### ISSUE TITLE
Homey does not stop listening

### ISSUE THREAD

**Issue by zperx** [athombv/homey#939]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

I have set up my first flow after updating and wiping homey. Flow was if I say TV than send IR signal.

**What was the result?**

After the Ok homey trigger Homey did not stop listening. The LED ring was orange and was pulsing as per the ambient noises and speech. I had manually stopped Homey listening by forcing it to speak by adjusting the speaker volume slider.

**What did you expect as result?**

To stop listening after 1-3 sec after the last word.

**Any other remarks**

It happened only once so far. BTH I don`t anymore have flows with speech trigger (because it does not work anyway).

**Comment by DieterKoblenz** [comment]
Happened to me twice. Can't seem to duplicate the scenario now..

**Comment by bvdbos** [comment]
If there's a lot of bg-noise, Homey doesn't know when to stop listening?Didn't see this yet but there should (of course) be a maximum time Homey is listening... i.e. 10 seconds?

**Comment by KroontjesPen** [comment]
On 6 October I found one moment also the orange ring in "microphone" stand.
Now idea what trigger it and I have then PTP.

version 0.10.3

**Comment by DieterKoblenz** [comment]
Yelling stop worked for me ;)

**Comment by mike9011** [comment]
Same issue here on 0.10.3:

1 or 2 times a day my Homey is false triggered, and don't stops listening after that.
Eventhough there is no sound at all at that moment.
