### ISSUE TITLE
Not all Hue lights in group respond

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#94]
When asking Homey to turn off the lights, or turn them on, I noticed that not always all lights respond. Perhaps that is related to sometimes a light being switched off using a hard switch and not being reachable? Does Homey then stop trying to reach the other lights in the group as well?

**Comment by Fire69** [comment]
Same here.
'Turn lights on' resulted in 1 light turning on.
'Turn lights off' resulted in 1 other light turning off...

**Comment by freemann** [comment]
Did you guys configure a Flow for that or using the build-in option? 

Emile mentioned that user created flows are interfering with the build-in options of switching light.

**Comment by Fire69** [comment]
No flow, just trying out the internal commands.

**Comment by freemann** [comment]
OK! 

command like this should work out of the box; "OK homey, turn livingroom light to red"

**Comment by AndreSomers** [comment]
They _should_, but they don't. They sometimes do, but not allways. Sometimes only one or a few lamps in the zone respond, instead of all of them. And because it does not work as it should, I filed this bugreport.

**Comment by freemann** [comment]
I was just pointing to the fact that you should not use/configure/create speech flows for triggering lights on/of.
A few first backers made flows for triggering lights with speech and that didn't work and resulted in the fact Homey last it completely on the point of switching lights.

So if you say you don't configure them, then that's absolutely clear and it can not be the issue in your case.

**Comment by AndreSomers** [comment]
Well, I did create one for turning them off as part of a bigger "Goodnight" flow. Indeed triggered by speech, but not interering with the default command. You say I should not use lights in flows triggered by speech at all?

**Comment by freemann** [comment]
Flows with the word "light(s)" in combination with "on/off" would cause problems.

**Comment by AndreSomers** [comment]
Ok, that is certainly not the case. The trigger I wanted was "bed time". 

Note that if certain terms cause problems in triggers because they interfere with other (build in or not) flows, that should be indicated when creating the flow in the first place.

**Comment by freemann** [comment]
I known and I exactly said that to Emile.
The should warn the user if he tries to create a speech flow with these words and functions.

**Comment by matthijsvdr** [comment]
When adding the hue lights, add them all in one go instead of adding room by room.
Every time you push the button homey gets a new api token from the bridge to access your light.

I guess by default homey will only use the last one requested (and there for uses the wrong key for the "older" lights).

What i did:
Remove all hue lights In devices
(i also removed all of homeys acces tokens from my hue bridge, see http://developers.meethue.com, but this is problem optional)
Select home in devices (or something else if renamed)
Then add a new device
Select Philips hue
Follow the instructions about pushing the button
Add ALL light no matter where they are placed
Once all lights are added, you can drag and drop them from Home to another room

Then try this:
Turn the lights off

**Comment by AndreSomers** [comment]
That is an interesting theory, but not accurate I think. I see some lights that I added in my first round still responding, while others do not (always) respond. Like this morning. I asked Homey to turn the lights on in the livingroom. It turned the lights on (but everywhere, not just in the livingroom). Then, later, I asked it to turn them off again, and Homey turned the lights off except for one lamp. This one lamp was among a group of lamps added the first time. A new lamp (I just added one to my setup) that I added later was turned off just fine.

**Comment by Fire69** [comment]
I don't think that's the reason either.
I added all my lights at once, but still have the problem.
It would not be very logical either to have a new token assigned every time.  When Homey has received access to the Hue bridge, it doesn't have to request a new token again the next time...

**Comment by jordenc** [comment]
Also have issues with Hue lights.
I have 5 bulbs + 2 lightstrips in the livingroom, assigned to the livingroom zone.
I have a bulb and lightstrip in the bedroom, and 2 bulbs in the hall.

All lights are turned on. Then I tell Homey to turn all lights off. All lights except 2 in the living room above my dining table are turned off.
Turn lights on => All lights are back on
Turn lights pink => All lights are turned to pink, except the 2 dining table lights.

Sometimes the lights in the hall don't work, sometimes in the bedroom I have troubles controlling them.... hard to find out what exactly is going wrong.

**Comment by matthijsvdr** [comment]
I have this flow for two weeks now, but it has never worked correctly, every morning i hear "off to work" but the lights stay on
![screen shot 2016-03-14 at 22 14 43](https://cloud.githubusercontent.com/assets/1271035/13760197/2d739bf6-ea32-11e5-9c7c-563c12e48f4e.png)

**Comment by WeeJeWel** [comment]
Please try again with v0.9.10 of the Hue app.

**Comment by jordenc** [comment]
Probably related:

Is there something like a limit to the number of lights on speech-commands 'all lights on' and 'all lights off'?
I have the following situation:
 Off     Staande lamp rechts
 Off     Driepoot
 Off     Booglamp
 Off     Led links
 Off     Gang 2
 Off     Gang 1
 Off     Led rechts
 On     Slaapkamer
 Off	    Badkamer => unreachable (power is off)
 On     Slaapkamer lightstrip
 Off     Eettafel 1
 Off     Eettafel 2
 Off     Bar

In short: Only lights on in the bedroom. I say: OK Homey, all lights on. Situation is now:

 On     Staande lamp rechts
 On     Driepoot
 On     Booglamp
 On     Led links
 On     Gang 2
 On     Gang 1
 On     Led rechts
 On     Slaapkamer
 Off	    Badkamer => unreachable (power is off)
 On     Slaapkamer lightstrip
 Off     Eettafel 1
 Off     Eettafel 2
 Off     Bar

There could be multiple causes, as far as I can think of:
1- Because of the unreachable bulb, it stops
2- Because of the Slaapkamer Lightstrip (Hue Lightstrip plus) something goes wrong (LED-strip with the same capabilities as a normal bulb)
3- Something goes wrong when switching to light 10 (if you count them in order from 0, every light with 2 digits is still off)
4- There is a 10 lights limit

I would guess it's option 3 but ofcourse this is guessing.
If I turn on all lights by hand and then use Homey to turn them off, also Eettafel 1 / Eettafel 2 / Bar don't go off, as well as Slaapkamer + Slaapkamer lightstrip.

If it helps, let me know which email address I can invite to my Homey so you can control it with the speech-input page. I have a page online that you can use to see or influence the light status (light color as well as on/off) so testing is possible. It will not bother me on weekdays between 9:30 and 16:00 :)

**Comment by jordenc** [comment]
Another Hue flow that doesn't work 100%
![schermafbeelding 2016-04-14 om 11 28 17](https://cloud.githubusercontent.com/assets/17727803/14523518/6e2eb350-0234-11e6-8094-eddd7e55a5d1.png)

The first 7 lights respond (that is: Bar, Booglamp, Driepoot, Eettafel 1, Eettafel 2, Led links, Led rechts).

The Slaapkamer Lightstrip (Plus) doesn't go on.
The Slaapkamer bulb doesn't go on.
The Staande mpa doesn't go off.

It seems to be hanging on the Lightstrip Plus again. So perhaps in the message above, option 2 is the problem.

**Comment by freemann** [comment]
What happens when you move the Ledstrip plus to the end of the light sequence?

**Comment by jordenc** [comment]
Ha, I just tested that. Removed the Lightstrip Plus from the flow.

Now my 'Slaapkamer' bulb goes on correctly.
However, Eettafel 1, Eettafel 2, and Bar stay on so that is a new problem.

**Comment by freemann** [comment]
Very very strange and unpredictable behavior.

**Comment by Gand41f** [comment]
I have the same issue. Upon the command "lights on" or "lights off" not all of my 12 Hue lights respond. It depends on the current state of the lamps, which lamps respond. I have no flows containing Hue lights or the command "lights", "on" or "off". 
If I access my lights with the Hue app on my smartphone everything works fine.

**Comment by bvdbos** [comment]
This problem seems to be with Philips as other controllers (at least Toon) seems to act the same:
https://forum.athom.com/discussion/comment/18404/#Comment_18404
This will probably be solved when groups are implemented...

**Comment by freemann** [comment]
I'm with @bvdbos, other controllers on the market also have big issues with switching multiple HUE devices. But no idea if Athom will implement the group (and if the API exposes this) function. And if controllers like Toon still have no group function and have the multiple light issue, then don't expect this function soon in Homey.

**Comment by bvdbos** [comment]
Of course we expect this from Homey (if Philips opened their API), Homey is much better then any other controller. Went to the store today to buy a Fibaro, that controller costs a fortune! Groups API:
https://forum.athom.com/discussion/comment/18404/#Comment_18404

**Comment by freemann** [comment]
Thinking out loud, I think the should not use the group api. This because Homey need CRUD and thats a bit overkill. It should (and i think) could work, to send commands to the hub for individual lights.

But lets wait and see what Athom's plan are to solve this issue.

**Comment by bvdbos** [comment]
Doesn't seem like a problem for the HUE-API:
    ■ Get all groups
    ■ Create group
    ■ Get group attributes
    ■ Set group attributes
    ■ Set group state
    ■ Delete group

**Comment by freemann** [comment]
If you want, everything is always possible. But its the question if the want to use the API. 
Grouping in Homey will be generic and implementing the Hue Groups API need specific coding and that costs more time and money.

**Comment by bvdbos** [comment]
Not only that I now realize: this way the bridge is still needed and goal is to throw all bridges out...

**Comment by Fire69** [comment]
@freemann, what's CRUD exactly?

I don't see why this should be such a big problem to get it working, with or without groups.
Have you seen how many Android apps there are for Hue with all kinds of special functionality?
Look at Hue Disco, that app controls all your lights within milliseconds without (litteraly) skipping a beat...

Just getting the basics of turning the lights on and off shouldn't be a huge task, right?

**Comment by freemann** [comment]
http://lmgtfy.com/?q=crud
That means that Athom needs to write a lot of dedicated code for this AND what @bvdbos mentioned; It means that the Hub can't be ditched..... (i was waiting on that one :wink: )

I totally agree with you all that its should that hard to just switch 10 light "simultaneously". 

Side note;
Funny to see that which side i choose, its always "not good".

**Comment by Fire69** [comment]
Honestly, I hope that in the future, when the bridge won't be needed anymore, they leave the option to choose whether or not you use it or not.
If you ditch the bridge, you won't be able to use any other apps anymore, and like Hue Disco I mentioned before, I do use other apps from time to time.
Can't imagine those will all be replaced by community apps (that work as good as the original apps..)
You'd need a lot of CRUD for that ;)

**Comment by freemann** [comment]
Athom said the will creating device grouping. The already support CRUD for devices/zones/etc. so adding/extending that for HUE grouping should be very easy.
Its a choice to ditch the Hub, here we only use the Official App and in most cases only the 4x1 widget for selecting Scenes.

I think its a big chance for Athom/Community/AppStore to create Homeys apps like Disco.

**Comment by markaswift** [comment]
Also experiencing this. 

Flows fail to turn on or off lights, or fail to set commands. Strange thing is, it's normally the same lights that fail...

The official Hue app works 100% and never fails.

Disappointed as I expected this to work but will need to revert back to the Hue app and timers for now.

**Comment by freemann** [comment]
Here the Hue app is pretty stable and in fact its not crashing at all.
The only strange thing we experience is a sometimes big delay when switching the lights.
For example I create a flow which turns on all the Hue in the livingroom at sunset.
This flow should trigger all lights at once and all light should turn on within lets say 1-2 sec. But in a lot of cases the lights go on with a delay of 1-2 secs between and it takes 5-10 secs to turn on all the lights.

I the flow is done and I use my Android phone with the official Hue app to turn all lights off again, the all go of within 0,5secs.

So it looks like Homey has some troubles on firing the request and/or reaching the Hue hub.

**Comment by bvdbos** [comment]
Is this issue still present with the latest HUE app?

**Comment by WeeJeWel** [comment]
I think this is fixed some time ago. If not, please report so.
