### ISSUE TITLE
heartbeat error and XMLHttpReuest warning while adding KaKu - device

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#942]
**What is your Homey version (Settings → System)?**
0.10.1

**What did you try to achieve?**
Add a KaKu-device

_Please include detailed steps how we can reproduce the issue_
Just add device

**What was the result?**
Device added but errors in console:

`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/. -> jquery.js 3`

`POST http://10.0.3.35/api/manager/drivers/pair/1321afc844422c38aa2cceb425df483c71ae7adc/heartbeat?_=1475266431399 500 (Internal Server Error) -> api.js:1`

**What did you expect as result?**
No errors in console

**Comment by WeeJeWel** [comment]
What's the result body of the POST /heartbeat ?

**Comment by WeeJeWel** [comment]
I'm closing this issue due to inactivitity.
