### ISSUE TITLE
IR: Flow editor messes up when changing command

### ISSUE THREAD

**Issue by DieterKoblenz** [athombv/homey#943]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

Learn a new remote. I added 4 possible in this order: Volume Up, Volume Down, CD, Phono. After this I used it in the flow for testing:

**What was the result?**
1. Volume Up works, however when I keep the card and select Volume Down, save the flow and press test it again outputs the first IR command (Volume Up). Only if I remove the card and add it again with the other IR command it works.
1. The single push button does not seem to work. 10 times works (but usually I onle have to press the button once)

**What did you expect as result?**

**Any other remarks**

**Comment by bvdbos** [comment]
Nope, works for me... This flow walks to my upnp-server and starts the first song...
![eerste nummer starten](https://cloud.githubusercontent.com/assets/1064079/19019326/8a8845e4-8884-11e6-9ff6-ed379b8720ab.png)
