### ISSUE TITLE
LaCrosse sensor values not updating

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#944]
**What is your Homey version (Settings → System)?**
Homey V0.10.1   LaCrosse App V0.1.3

**What did you try to achieve?**
Getting actual values from the sensor (temperature and Humity)

**What was the result?**
Only the first value from the moment of connection, is displayed and stays on the device immage
![lacrosse2016-10-01_120300](https://cloud.githubusercontent.com/assets/3833862/19013375/2bc2f1fe-87cf-11e6-86e4-98a008592e52.png)

**What did you expect as result?**
Values udating as they change, 
I have a Domoticz running where I can see the values are updated every minute

**Any other remarks**
After reset (by menu) the value  of Humidity is "0" the value of Temperature is still the same as before.

On older Homey version (0.9.x) the changed values where shown, but when used in a flow, there was no reaction on value changes.

**Comment by JPe2** [comment]
Homey V0.10.3 & LaCrosseV1.0.2  The values are updated now in the "Zones & Apparaten"
Unfortunaly when I use the LaCrosse sensor card in aflow, it doesn't work, the broken chain is appearing in the menu:
![2016-10-07_151847-lacrossevocht](https://cloud.githubusercontent.com/assets/3833862/19193206/7fb402b0-8ca9-11e6-9f2c-7c16fe7387ca.png)

**Comment by JPe2** [comment]
@BasKiers:   The problem seems to be solved:
I always had the browser open and tabs to the different Homey pages  (like Flow), after refressing the communication tabs, all functions work mutch better (also the flows menu). Thanks.

**Comment by JPe2** [comment]
It works for some time but yhen I get this error:

![image](https://cloud.githubusercontent.com/assets/3833862/19215278/8d104fd6-8d99-11e6-8724-ddcf17a420e9.png)

Disabling and enabling the plugin solves it for several hours, then again error..

**Comment by JPe2** [comment]
@BasKiers  La Crosse v1.0.4 

Stack trace:
TypeError: this.on is not a function
at scanDevices [as _repeat] (/433_generator/drivers/driver.js:43:9)
at wrapper [as _onTimeout] (timers.js:275:11)
at Timer.listOnTimeout (timers.js:92:15)
Exit code: 1

**Comment by BasKiers** [comment]
Hi, 

Sorry for the errors. I did not have time to fully test this app. Thank you for the bug report. It should be fixed in v1.0.5 now (:

Regards,
Bas

**Comment by JPe2** [comment]
Runs for some days now, looks very good, thanks Bas.
![image](https://cloud.githubusercontent.com/assets/3833862/19358119/f3a19410-9174-11e6-9f4b-1b4645c123d0.png)
