### ISSUE TITLE
Delay does not work on IR cards

### ISSUE THREAD

**Issue by jeroenbos22** [athombv/homey#945]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

Use 2 IR cards after eachother in a flow with a delay added to the second card

**What was the result?**

Both cards fire as soon as the flow starts

**What did you expect as result?**

The delay to work

**Any other remarks**

...

**Comment by jeroenbos22** [comment]
It does seem to work actually but in the flow its not visible. The green checkmark shows right away

**Comment by bvdbos** [comment]
Just closed #437 this morning :-) In the past this didn't work, now it does (though you're right about the green checkmarks).

**Comment by bvdbos** [comment]
The green check-marks get set by device. I have a flow with three IR-devices in it. First the stereo gets turned on. After that IR walks through the menu of the stereo with delays but all check-marks for IR get checked. After 30 seconds the tv and blue-ray gets a signal to turn off, the check-mark for the tv and blue-ray only appears after this delay.

**Comment by WeeJeWel** [comment]
This could happen when the same card (but with different) arguments occured more than once. This is fixed in Homey 0.10.4.

**Comment by bvdbos** [comment]
confirmed fixed the checkmarks....
