### ISSUE TITLE
IR-signal gets send three (?) times

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#946]
**What is your Homey version (Settings → System)?**
0.10.1

**What did you try to achieve?**
Turn off my Philips-stereo or mute TV

_Please include detailed steps how we can reproduce the issue_
I have a generic Philips-tv and a custom-learned philips stereo. In one flow I want to turn on the tv and turn off the stereo

**What was the result?**
Somehow the signal send to the stereo is too long. It makes my stereo go to eco-mode from which it will only awake through a physical button-press. I noticed similar things with muting the tv, it seems to get send three times?

**What did you expect as result?**
Signal gets send only one time. I specifically set "press multiple times" to "1"

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by bvdbos** [comment]
I haven't run into this some time... closing...

**Comment by jeroenvollenbrock** [comment]
The 'press a button' card is supposed to have a second field where you can specify the amount of transmissions, did you pair this device using the database, or by learning?

**Comment by caseda** [comment]
There are 2 cards, 1 with just that, and another card where you can select the amount of send signals, which has a default of 10 repeats.

that is for both, learned signals, but also the database signals

**Comment by BasKiers** [comment]
Hi,

We've made some improvements to our Infrared Database. If you are still experiencing issues could you try to add the device again from the IR database pair wizard and check if the problem is now fixed?

Regards,
Bas

**Comment by bvdbos** [comment]
I'll try tonight...

**Comment by bvdbos** [comment]
retested. Worked 95 out of 100 ok (well tbh : 19 out of 20)
