### ISSUE TITLE
[Enhancement] support BL-variables

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#948]
**What is your Homey version (Settings → System)?**
0.10.1

**What did you try to achieve?**
Have Homey tell me the value of a BL-variable

*Please include detailed steps how we can reproduce the issue*
1) Update BL variable "tempinside" with every change

2) when asked, tell the value of "tempinside"

**What was the result?**
Homey said dollar tempinside

**Comment by DieterKoblenz** [comment]
for this :+1: 

Work around which I use is to use built-in vars. (Flow: When BL value changed, change built-in var accordingly) then you can use {{{$varname}}} to read the content. (Don't use "-" in a var name, that will fail)

**Comment by WeeJeWel** [comment]
Use `{{$myvar}}` for Homey 'Logic' variables.

Support for custom variables will be added soon!

**Comment by markaswift** [comment]
+1

**Comment by lubbertkramer** [comment]
+1
