### ISSUE TITLE
Coupling Hue bridge does not work smoothly

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#95]
When first adding Hue, you get a screen to push the central button on the Bridge. First of all: the image is too big for the screen, so scroll bars appear. That looks off.

But then, even after pressing, nothing happens. Trying the whole sequence again will then skip through the same screen and showing the available lights directly. 

The interface should just go to the next screen after pressing the button directly.

**Comment by evad1st** [comment]
a tip for this: add all your Hue lamps at onve, and drag (and drop( them later to the respective rooms.... else you keep on pressing the Hue bridge button.

**Comment by AndreSomers** [comment]
I think this particular issue has been solved. However, I will open other bug on this because having to keep pressing the button is still a bug: https://github.com/athombv/nl.philips.hue/issues/3
