### ISSUE TITLE
KaKu doorbell ACBD-7000C not able to ring

### ISSUE THREAD

**Issue by elcovb** [athombv/homey#950]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

After connecting the ACBD-7000C KaKu doorbell (the doorbell beeps twice to let me know it is connected), trying to make the doorbell ring fails. It does nothing. This is the case when either generating a new signal as when copying the doorbell button signal.

**What was the result?**

Doorbell doesn't ring.

**What did you expect as result?**

Doorbell rings.

**Any other remarks**

Doorbell does receive signals that make it connect, but it won't ring. The doorbell does ring when the KaKu doorbell button is pressed.

**Comment by BasKiers** [comment]
Hi, I've tested an ACDB-7000C with the KaKu app v2.6.0 on Homey v0.10.2 and I was unable to reproduce your issue. Could you check if this is a range issue by placing the doorbell receiver close to Homey and trying to pair again?

**Comment by elcovb** [comment]
Hello Bas,

Thanks for replying. The doorbell is in a wall outlet 3 meters away from the homey so it wasn't the range.

I removed all revices from the doorbell (hold the button for 10 secs) and than retried, that helpen! It's strange, because the memory of the bell couldn't be full, but it worked. The issue can be closed.
