### ISSUE TITLE
Very short 433 listening range

### ISSUE THREAD

**Issue by bobenoni** [athombv/homey#951]
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

Use 433 remote/doorbell button/sensors (battery powered) within the house, but Homey can't receive signals from more than ~4 meters away
Testing the remote with the doorbell receiver shows there is nothing wrong with the signal strength itself.
Please find the graphical description below, or forum thread [here](https://forum.athom.com/discussion/2003/433-range-testing). There are several other users with ~4m range.

NB: Homey **sending** range is working very well for me. My sockets can receive signal from Homey throughout the house.

**What was the result?**

My 433 gear doesn't work with Homey as expected, because of Homeys limited listening range.

**What did you expect as result?**

Homey 433 listening range to be sufficient for home use.

**Comment by bobenoni** [comment]
![](https://forum.athom.com/uploads/editor/aw/z8obsn1x2q4f.jpg)

A: Shelf. Homey and doorbell receiver placed together.

B: Couch. At this point Homey reception starts to degrade. Doorbell OK

C: Front door. No reception from Homey. Doorbell OK

D: Street. Reception on doorbell breaks around here.

**Comment by bobenoni** [comment]
Installed 0.10.3 today. Don't know if I imagine this, but range seems a tiny bit better, if any. 
**But still no doorbell triggering from point C.**

**Comment by bobenoni** [comment]
No change in 0.10.5

**Comment by gajdur** [comment]
@WeeJeWel , can you please comment this issue here? Having same problems with Elro switch and Oregon sensors. After 3m is the signal gone. 0.10.6 Firmware. Tnx

**Comment by Inversion-NL** [comment]
@gajdur I guess you ment firmware 0.10.5?
https://firmware.athom.com/
0.10.6 isn't available as of yet.

**Comment by gajdur** [comment]
He he, only dreaming, corrected, tnx.

**Comment by KroontjesPen** [comment]
**Strange that after 16 days there is no reaction on this case.**
The receiving site of Homey on the 433 is unreliable. Even wall-switches are not seeing by Homey sometimes. That sometimes make it irritating. It's me or it's Homey is flows don't working.

**Comment by philsniff** [comment]
i have only 1 meter range with my kaka awst-8802, tried everything. it was a test for eventually more kaku devices but when this switsh won't work i will not go on the kaku-train

**Comment by KroontjesPen** [comment]
@philsniff 
Look in this tread and you find strange habit's of Homey listening to 433 signals. 
[](https://forum.athom.com/discussion/2003/433-range-testing)

**Comment by philsniff** [comment]
Yes i looked already to that threat. But for somebody it works and for someone else like us Not. Very strange. I can't believe that this is then a software bug.

**Comment by nattlip** [comment]
I still think it is a software problem. I use my oregon app with 2 different sensors one the big one gives reasonable constant input to homey with a lot of misinterpretation. the other one the little , isnt heart sometimes hours by homey, but when i do some testing of other 433 devices via the cli with apps that also runs 24 hours after closing the node.js console, the oregon sensor is a lot more heard as if testing 433 apps awakens the 433 chip or let him better interpret the oregon signal

**Comment by nattlip** [comment]
the sme problem with the speaker , for a few days buienradar says something but now it stopped .  other texts also stopt ore very stuttering after 2 minutes. laodavg 4 !! after a time it drops . now diabling buienradar and enabling it works again.

**Comment by WeeJeWel** [comment]
Hey guys, we hear your problems :) The range is a very tricky subject, as it depends on a thousand factors. The hard part is that Homey must support the complete 433 - 434 MHz band, because 433 Mhz devices are usually very cheap and they don't always send on the frequency they promise. For example a doorbell receiver, must only be able to receive 1/100th of our band, e.g. 433.92 MHz. This makes it a lot easier for a dedicated device to improve its range.

We're continuously working on improving the range. To make it better, we need a lot of data, and you guys can help us here. Tell us which devices work good and which work bad, so we get a clearer overview of what's happening!

**Comment by philsniff** [comment]
ok, i only have just one device so far because of testing for the beginning. and it works only within a range aof really < 1meter. 
I have the Trust (here in germany we haven't kaku) awst-8802 switch

**Comment by nattlip** [comment]
oregon scientific, a lot of misreading,  bthr968 do a lot better as thgr122nx

**Comment by KroontjesPen** [comment]
Sorry @WeeJeWel.
Why is a KaKu socket on a distance from 7.30 meters be able to received the wall-switch signal and Homey on 3.20 meters in almost the same direction **not**.

**Comment by bobenoni** [comment]
@WeeJeWel Isn't it possible to make Homey to learn listening to only the specific bands that the paired devices use? So when pairing it "open its ears", but in daily life only listens to the excact frequencies that it has learned.

**Comment by KroontjesPen** [comment]
For info @WeeJeWel 
All the KaKu remotes such as wall-switches, sensors, handheld remotes, etc are unreliable to use as **remote pairing** white Homey.
A lot of plans where you can only used **remote pairing** you have to set a side them for now. 
That's here for now 2 night-sensors switching 3 devices. One of them in opposite way.

**Comment by KroontjesPen** [comment]
For info @WeeJeWel
Just received the RFXtrx433E USB 433.92MHz Transceiver. It's placed near Homey. 
Test on the 2nd floor with RFXmrgr.

KaKu AMST-606 contact sensor.  Signal level  = 8  -72dBm with nearby -56dBm. 
Homey lost after 5 meters ground-floor.
KaKu AYCT-102  remote.             Signal level  = 7  -64dBm with nearby -56dBm. 
Only KaKu socket did reacted ground-floor.

**Comment by Phunkay** [comment]
We have a AMST-606 door sensor and APIR-2150 motion sensor to check the status of the garage door. Both sensors are only 3-5 meters away from Homey (with a concrete floor in between). Since we were having issues getting reliable feebback from both sensors I thought I'd pair them from their current position instead of right next to Homey to maybe get a more representative signal. Although pairing worked flawlessly right away Homey still misses most sensor changes. Since the pairing works it seems it's not just a range issue....

**Comment by philsniff** [comment]
I can't pair the switch when i am more than one meter away from homey!

**Comment by KroontjesPen** [comment]
If your are lucky to do a remote paring with a wall-switch it's then not sure that Homey sees it every time you used that wall-switch. Look on the device pace and see. So you can't use it in a flow. 

My conclusion about 433 in combination with KaKu ICS-1000: input dreadfully, output terrible.

**Comment by gerjan01** [comment]
Here I have 2 KAKU Motion Sensors AWST-6000 and multiple AMST-606 door sensors.
Range is very poor. Looks like mostly incoming signals Homey does 't "hear"

Sendings singnals do have a better range.

**Comment by gerjan01** [comment]
I dit a sending 433 test with Homey to a Home Easy HE877-HW device 20 meter with 3 walls worked fine!

Problem is receiving signals!

**Comment by tilcoating** [comment]
With KAKU ACDB-7000AC, the doorbell button has to be very close to Homey (<1 mtr) to work. Whereas the doorbell itself works perfectly with the button from a distance well over 8 meter, with two concrete walls in between.

**Comment by bvdbos** [comment]
How does this work with 1.2.x firmware now? Also, did you try to put Homey in another spot and see if that mattered?

**Comment by jeroenvollenbrock** [comment]
Closing to concatinate multiple similar issues as #2023
