### ISSUE TITLE
Extractpath_not_writable when Firmwareupdate

### ISSUE THREAD

**Issue by peaoo** [athombv/homey#952]
**What is your Homey version (Settings → System)?**

The last three updates (since 0.10.0) this error occured.

**What did you try to achieve?**
Updating Homey to the new firmware.

**What was the result?**

On first try the following error poped:
![image](https://cloud.githubusercontent.com/assets/17235241/19072993/bb9ecd78-8a38-11e6-81ec-2230f3709469.png)

After a few reboots (some end with a red ring -> reboot again) and some end with the same error it worked.

**What did you expect as result?**
Installing updates without errors.

**Any other remarks**

Usually the error popped up instantly. Sometimes it takes a few seconds (4-5s) for the error to show up. If this is the case I keep trying to update it and after a few times it worked without rebooting again.

But if the error pops up instantly I have found no other workaround than reboot.

**Comment by jeroenvollenbrock** [comment]
@peaoo How many active homey apps are you running?

**Comment by peaoo** [comment]
This is a list of all my apps running on homey.
![homeyapps](https://cloud.githubusercontent.com/assets/17235241/19075504/6ef355b8-8a45-11e6-9c80-1872308c70f5.png)

**Comment by peaoo** [comment]
I made two screens of the "stuff for geeks" tab.
1. Before reboot
![beforereboot](https://cloud.githubusercontent.com/assets/17235241/19075831/eba8f116-8a46-11e6-80e4-fbe23724df7f.png)

2. After reboot
![afterreboot](https://cloud.githubusercontent.com/assets/17235241/19075837/f3431c3a-8a46-11e6-8b69-a98ba285f509.png)

hope that this can help.

**Comment by WeeJeWel** [comment]
Should be fixed in all updates installed from 0.10.4 or higher. If not, please report back!

**Comment by peaoo** [comment]
This error came up again when updating from 0.10.4 to 0.10.5.

**Comment by WeeJeWel** [comment]
@peaoo 0.10.4 has never been released? :-)

**Comment by peaoo** [comment]
Oh k, then I will wait for the next update :) Sry.

**Comment by jeroenvollenbrock** [comment]
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please reopen this issue.
