### ISSUE TITLE
Can't add a flow to a second layer folder

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#953]
**What is your Homey version (Settings → System)?**

0.10.2

**What did you try to achieve?**

This is a tricky one, but you are only able to add flows/folders to a folder which is on the first layer (see screenshot). I'm not able to add a flow/folder next to the flow which is on the second layer.

![schermafbeelding 2016-10-04 om 18 24 03](https://cloud.githubusercontent.com/assets/17526110/19082755/c9c1af66-8a5f-11e6-8604-38af9a88443d.png)

**What was the result?**

Can't sort exactly all my flows.

**Workaround**

Workaround would be to create the layers first and than add them to the selected flow in order (last first folder first, second to last second etc).

**Comment by bvdbos** [comment]
confirmed.

**Comment by Arjanvde** [comment]
This is with 1.1.2 solved as far as I can test.
