### ISSUE TITLE
removing emailadress of contributor in app.json gives strange contributer name

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#955]
app store bug

**What did you try to achieve?**

remove email adress contributor for privacy reasons in app.json file app

see above

reult
name contributor becomes root toor 

...
expected
the real name of contributor in store

see 
https://github.com/nattlip/com.jilles.oregon     https://apps.athom.com/app/com.jilles.oregon
...

**Any other remarks**

...

**Comment by joachimroeleveld** [comment]
Hi, thanks for reporting! I fixed the cause of the problem and made sure that the name is displayed correctly now.
