### ISSUE TITLE
Problem with level tag on hue 'Dim-level changed' card

### ISSUE THREAD

**Issue by daneedk** [athombv/homey#958]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Execute this flow:

![flow](https://cloud.githubusercontent.com/assets/16610696/19127461/5aad1396-8b3f-11e6-98e6-2d3a9d320fc3.PNG)

These 3 hue lights are on a physical switch and will start at 100% when switched on. This flow automaticaly dims them.

_Please include detailed steps how we can reproduce the issue_

Add hue lamps and recreate my flow.

**What was the result?**

Flow stopped working somewhere after 0.10.0, not sure at what firmare.

**What did you expect as result?**

Lights to be dimmed after homey sees a change in dim level.

**Any other remarks**

On 0.10.3 it seems longer possible to use the level tag from the  hue 'Dim-level changed' card. I can drag it to a card in the AND column, but not to a card in the THEN column. When running a test the card in the AND column always shows the red cross, no matter what value I compare the level against. See the screenshot. I should also mention that the DIM level is logged into insights, but it's a factor 100 off. The dim level in the flows card is ranged 0-100 while in insights it's 0-1. (This gave no problem on earlier firmware versions though)
Test flow:
![flow2](https://cloud.githubusercontent.com/assets/16610696/19127659/33dea9e0-8b40-11e6-9eeb-2f12cb7bddac.PNG)

I've created an issue here and not on the hue app because the last modification on the app was august 3, the problem surfaced after a firmware update.

**Comment by JPe2** [comment]
Also strange, the **tag** in "when" (in dutch) is **Niveau** and draging and dropping this to "then" it changes to **Waarde**

![image](https://cloud.githubusercontent.com/assets/3833862/19222250/6f901b9c-8e54-11e6-8126-7287ab1443b4.png)

**Comment by daneedk** [comment]
@weejewel I did some more testing and think the issue described above consists of 2 seperate problems.
The first problem is that the evaluation in the and column 'Level = 100' does not work any more. I've done several tests and found out when I used the 'is greater than' card that somewhere between the release of 0.10.0 and 0.10.3 the range changed from 0-100 to 0 to 1. Unfortunatly a lamp set to max does not always returns 1, only 2 out 10 'Level = 1' is succesfull in my tests, so I have to use 'Level is greater than 0.99'. That solves the mystery why my flow stopped working, although I think having a 0-100 range on dimming is more user friendly then 0-1.
The second problem is that I can not get any value 'tag' from any card in the when... column to any card in the ...then column. I've made several test flows with standard homey cards and cards from apps but I've not been able to drag any tag into any card in the when... column. (rebooted homey, cleared browser cache, different browsers/computers etc)
Hope this helps, if you need more info or me to test anything just let me know.

**Comment by daneedk** [comment]
Just noticed something, I saved the 'Level is greater than 0.99' and it is displayed as such. When I open another flow and then open te first flow again, it is displayed as 'Level is greater than 0,99' (notice the dot changed to comma) Is this some sort of autocorrection?

**Comment by WeeJeWel** [comment]
Dim goes from 0.0 to 1.0, so that's why `level == 100` doesn't work.

@daneedk Where are you trying to drag the 'tag' to? A 'Say' card?

**Comment by daneedk** [comment]
Ok, but previously it was 0 to 100 when evaluating in a flow, see the flows in the screenshot: they used to work. While I understand the value goes (technically) from 0.0 to 1.0 for non-tech users it would make more sense to use a percentage so 0-100. Furthermore, if I set a brightness in a flow it also in a 0-100 range. 
![brightnesspercentage](https://cloud.githubusercontent.com/assets/16610696/19895278/69db07f8-a050-11e6-92aa-8bd929d6c939.png)

The issue with dragging the tag no longer exists for me, right now I'm on 0.10.7

**Comment by daneedk** [comment]
@WeeJeWel any progress to report on this?

**Comment by bvdbos** [comment]
@daneedk Does this work now with global tags and the possibility to set the dimming-level with a tag?

**Comment by WeeJeWel** [comment]
`dim` values are always 0 to 1 (even if shown 0% - 100%). Use a logic card to convert a 0-100 value to 0-1.

**Comment by daneedk** [comment]
@emile To bad you're closing it like this without considering usability for then non tech users.

**Comment by JPe2** [comment]
Not even Your grandma will understand this! Cheap and lazy way to handle this problem.

**Comment by WeeJeWel** [comment]
Maybe I don't understand the issue correctly - but dim values are all `0-1` between Homey devices. So conversion is only needed when doing advanced things such as speech processing.
