### ISSUE TITLE
Smartwares Contact Sensor Alarm does not go away

### ISSUE THREAD

**Issue by Gand41f** [athombv/homey#959]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

I have a Smartwares contact sensor, whose signal ist not always detected by Homey (low 433 MHz range, see Issue 951). Once Homey misses an "alarm off"-Signal, the contact alarm stays on true independently how many times you open and close the window again. You have to delete the sensor and couple it again to make it work again until Homey misses another signal.

_Please include detailed steps how we can reproduce the issue_

Place a SH5-TSM-A Sensor such that Homey does not always receive the signal. Open and close it a couple of times. At some point the contact alarm will always stay on true.

**What was the result?**

The contact alarm always stays on true.

**What did you expect as result?**

If Homey misses a signal of the sensor it should accept new signals of the sensor.

**Any other remarks**

...

**Comment by Gand41f** [comment]
Somehow the problem seems to be solved. Did anything change in the app?

**Comment by jeroenbos22** [comment]
It was fixed 2 times before but its defenatly back again. Seems to be a re-occuring thing. I'm on 0.10.9 and motion sensors do not go off anymore. Only trigger the first time, stay on and never trigger again. Dont have kaku ones but a lot of people on slack also complain About the kaku's.

Athom please fix!! Maybe posible to add a default time to force go off if off signal was not received (for example after 10 sec). Think this Will solve it once and for all...

**Comment by jeroenbos22** [comment]
OW sorry this is About contact sensors, my problem is with motion sensors.

**Comment by jeroenvollenbrock** [comment]
Closed to combine under #2267
