### ISSUE TITLE
xxx.homeylocal.com doesn't always work

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#960]
https://athomcommunity.slack.com/archives/general/p1475747600007347
and
https://athomcommunity.slack.com/archives/general/p1475612776006926

win10 and linux mint seem unable to get xxx.homeylocal.com local ip's...

So after logging in through my.athom.com there's a fallback to xxx.homey.athom.com (through cloud)

**Comment by Dijker** [comment]
Windows 10 normal gets the local IPs from DNS, and Windows 10 (1607) with Chrome work. 
Only when opening this site and logging on the bearer token misses. (guess Athom is busy with a change and upgrade/transition of the backend)  
so after the not able to access add your bearer_token= to the URL to acces your Homey using the *.homeylocal.com name:

http://5**********************6.homeylocal.com/manager/users/?redirect_uri=http%3A%2F%2F5************************6.homeylocal.com%2F

Add ?bearer_token=3***************************************5 behind the ...%2F

**Comment by WeeJeWel** [comment]
`*.homeylocal.com` is unsupported, as it indeed didn't work for some users.
