### ISSUE TITLE
Dutch voice changes in Brian after reboot

### ISSUE THREAD

**Issue by edtst** [athombv/homey#962]
**What is your Homey version (Settings → System)?**

0.10.3 stable

**What did you try to achieve?**

Reboot Homey

*Please include detailed steps how we can reproduce the issue*

Set voice to Lotte, reboot

**What was the result?**

Voice = Ruben
...

**What did you expect as result?**

Voice remains Lotte
...

**Any other remarks**

...

**Comment by bvdbos** [comment]
confirmed....

**Comment by KroontjesPen** [comment]
Brian kick here Amy

**Comment by HansieNL** [comment]
In 0.10.3 experimental I can't even select a voice, because the voice option is gone. I have only the language option to select English or Dutch?

**Comment by Dijker** [comment]
@HansieNL , 
Ir you miss the voice menu I think you have a serious problem  in the homey core like #890 
I guess  you should contact Athom direct for support.
For me @jeroenvollenbrock did a great job  fixing that problem  and it gives them insights into why sometimes upgrades fail so they include the fixes in next updates.

**Comment by WeeJeWel** [comment]
Thanks for reporting! Fixed in 0.10.4

**Comment by bvdbos** [comment]
confirmed fixed in 0.10.5

**Comment by KroontjesPen** [comment]
Then anxious waiting for the stable version promised yesterday .

**Comment by bvdbos** [comment]
It's not a general rule that FW´s become stable, why else would there be experimental? But these voice-issues are fixed so you could also install the experimental FW if you're anxiously awaiting :+1:

**Comment by KroontjesPen** [comment]
> JeroenVollenbrock said:
Homey v0.10.5 has been released to the experimental channel. This release is scheduled to become the new stable version tomorrow.

**Comment by jeroenvollenbrock** [comment]
Where did i say that? Looks like i've made a copy-paste mistake from the 0.10.3 announcement.

**Comment by KroontjesPen** [comment]
https://forum.athom.com/discussion/2093/homey-v0-10-5/p1
