### ISSUE TITLE
Checkbox auto update automatic checked again after manual update

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#963]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Did a manual update of an app and after that the checkbox for auto-update was checked again.

*Please include detailed steps how we can reproduce the issue*

Put auto update for an app to off, not checked.
After a manual update of the app the checkbox is checked again

**What was the result?**

Checkbox was checked automatic

**What did you expect as result?**

The checkbox back to where it was, unchecked in my case.

![checkbox](https://cloud.githubusercontent.com/assets/19249884/19163403/197411d2-8bfc-11e6-9cbe-5de827505275.png)

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
How did you manually update the app? Using `--install` ?

**Comment by Rocodamelshe** [comment]
There is an option to the right of "automatisch updaten" and thats called "Update beschikbaar".
Clicked it to update.

**Comment by WeeJeWel** [comment]
Ah, I see, you're right!

Fixed in 0.10.4!

**Comment by Rocodamelshe** [comment]
Cheers!
