### ISSUE TITLE
IR signal for KPN iTV not working

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#966]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Add KPN iTV remote manually and to turn the iTV (Arris VIP2952) on or off

_Please include detailed steps how we can reproduce the issue_

Added a IR device
Searched for the model --> no result
Added the remote manually 
The button on the screen switches when the button is pressed
When a flow is triggered, the KPN iTV does not respond

**What was the result?**

KPN iTV does not respond to IR signal from Homey

**What did you expect as result?**

To turn the KPN iTV on or off

**Any other remarks**

**Comment by bvdbos** [comment]
confirmed for the HMB2260 tuner for xs4all, think it's the same as iTV's...

**Comment by pimviergever** [comment]
@bvdbos 
Thank you for the confirmation. 
Strange thing is that the Samsung TV has no problems at all!

**Comment by fn002449** [comment]
Confirmed my HMB2260 from Telfort doesnt work either.

**Comment by bvdbos** [comment]
@pimviergever it's no so strange, it's a completely different device...

**Comment by pimviergever** [comment]
I didn't realize that there were different suppliers for the iTV boxes. (Y)

**Comment by bvdbos** [comment]
? A samsung TV and a iTV box?

**Comment by Tweaqer** [comment]
+1 for Telfort iTV settop box
Model: Arcadyan HMB2260

**Comment by spelbreker** [comment]
i have tried it to. if i hold my hand for the IR sender the remote stil works. it response by radio signal i think

**Comment by TimvanSteenbergen** [comment]
Wtf?!! Tried that on my remote and indeed you can cover it far more than I expected and the settopbox still responds.
Has anyone tried the trick of recording the Homey with their phone to see if any IR-light at all shows up, sent out by the Homey? Mayben we are all having faulty IR-modules in our Homeys.

**Comment by TimvanSteenbergen** [comment]
My Homey's IR does function. So appearently Homey has a problem with replicating KPN's remote. Would be nice if Homey could export recorded IR-remotes and make those available for everyone else to use.

**Comment by pimviergever** [comment]
@TimvanSteenbergen Homey sends IR signals, how can it otherwise control my samsung tv?
It think it's capable of replicating signals but entirely correct.

**Comment by bvdbos** [comment]
see https://github.com/athombv/nl.kpn.ir
