### ISSUE TITLE
Unable to drag-drop flow in a folder in version 0.10.3

### ISSUE THREAD

**Issue by jeroenvano** [athombv/homey#969]
**What is your Homey version (Settings → System)?**

Homey 0.10.3, Google chrome 53.0.2785.143 m

**What did you try to achieve?**
When a new flow is created and saved and you want to place the new flow under an excisting flow folder it is impossible to drag and drop it there. At the end in the flow list you can only see the X for deleting the flow, no bars that you need to select for dragging the flow. Hoovering over the flow line does give you an idea that you are able to dragg the flow at a certain point in the field as the mouse over icon changes. You can reorder the flow its position in the original flow folder but are not able to place it in another folder.

**What was the result?**
Unable to organize newly created flows in new or excisting flow folders.
...

**What did you expect as result?**
Able to organize newly created flows in new or excisting flow folders. 
...

**Any other remarks**
I saw that earlier verions had somewhat the same issue but where all closed and fixed in this version?
BTW on mobile using chrome does not allow to activate/deactivate and edit flows. This was possible in earlier versions. Might be something wrong in the code that also is responsible for this error.
...

**Comment by JPe2** [comment]
It works terrible, but it can be done, first your new folder should not be on the bottom line, then hover over your new flow and see on the right side the 3 stripes, you can drag the flow from there up to your folder, move a bit to the right and drop it there. It's not working good, a placeholder should be opened at the position where it can land, but this is for the future.

**Comment by jeroenvano** [comment]
@JPe2 your workaround works but is far from easy ;)

**Comment by Phunkay** [comment]
Hmm, seems to work here... Just picking up the flow by clicking on the name and then drag it to where you it. It works best when the folder you want to drag in to is open, then you can see where it will be dropped. The only issue I have is that the 'drop zone' is much lower than the actual flow I'm holding so I need to move higher than I normally would to drop it where I want to

**Comment by JPe2** [comment]
Maybe ther is a difference in what brouwser is used, I use Google Chrome, and I have to pick the line at the tree bars where a "move sign" is displayed when my cursor is over it:

![image](https://cloud.githubusercontent.com/assets/3833862/19193965/5d65df96-8cac-11e6-8eeb-5ce54501cc2f.png)

I agree when there is a folder that already contains one or more flows, than it's more easy

**Comment by daneedk** [comment]
@JPe2 what version are you on? I've not seen the three bars on 0.10.3

**Comment by JPe2** [comment]
@daneedk  My system information: **Systeem Informatie Homey Firmware Versie: 0.10.3**
Windows 10 pro,  Google Chrome.

**Comment by bvdbos** [comment]
Strange, I don't have the three bars anymore too. These were omitted with FW 0.10.3...

**Comment by JPe2** [comment]
You're all right, I have now closed and reopened the chrome window to Homey and now it works mutch better and indeed the bars are not there anymore, sorry for the confusing, but now we know the reason.

**Comment by WeeJeWel** [comment]
Haha, caching is always fun :)
