### ISSUE TITLE
Actions disapeared from flow

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#97]
Yesterday, I created and saved a flow that controlled my lights. 

Today I wend back in to change something, and I see the light actions have gone missing. They ar no longer in the Then column. Seeing how much work it is to set them up one by one, that is quite annoying.

**Comment by WeeJeWel** [comment]
You have probably upgraded to 0.8.17. Sorry about that, but it was a
necessary change.

**Comment by AndreSomers** [comment]
Ok, I'll accept that for a beta product. This is **not** an acceptable thing to do in the final product though. Please go through all lengths to preserve the users' data, and if you really can not, notify the user that something has changed.

I did not update myself. I guess it auto-updated, which is fine. What is not fine is that I come back and find things broken after such an update. Perhaps Homey should show something like the led ring in red when it has something to say, and I can ask it "OK Homey, what is the matter?" **DO NOT** use voice unannounced (perhaps in the middle of the night) to send an alert like that. Or, just have it send an email to the registered adress.

**Comment by AndreSomers** [comment]
Did the also cause my whole coupling with Hue to disapear? I wanted to add a Hue light to a different room, and noticed the wizard wanted me to press the bridge again. Then I had a look at my living room where I had added a whole list of hues: all gone.

**Comment by WeeJeWel** [comment]
It was a one-time change, and we weren't planning on doing this when we have shipped more Homeys :)
