### ISSUE TITLE
Cron jobs do not work after app upgrade or Homey reboot

### ISSUE THREAD

**Issue by DiedB** [athombv/homey#971]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Upgrading an app or rebooting Homey

**What was the result?**

When upgrading an app or rebooting Homey, cron jobs stop working.
When trying to add the cron jobs (with the same name) after an app upgrade or reboot, the error task_already_exists is returned (but the jobs are not running).

The cron jobs contain a function call.

**What did you expect as result?**
The cron jobs persist. They only have to be added in module.exports.added, and removed in module.exports.deleted, and don't have to be touched otherwise.

**Comment by DiedB** [comment]
This is how the cron job is registered:

```
Homey.manager("cron").registerTask(device.cron_name, "*/5 * * * *", device_data, function (err, task) {
        if (err === null) {
            Homey.manager("cron").on(device.cron_name, function (device_data) {
                checkProduction(device_data);
            });
        } else {
            Homey.log("[" + device.name + "] Error while creating cron job: " + err);
        }
    });
```

**Comment by WeeJeWel** [comment]
You only register the `.on` listener if there's not an error. But there is an error if it already exists, so after a reboot, you don't have an active listener!

**Comment by DiedB** [comment]
OK, I assumed that the 'on' would be kept after a reboot as well.

I will try to move it out of the registerTask and report back.

**Comment by WeeJeWel** [comment]
Nope, it's just a 'simple' event listener :-)

**Comment by DiedB** [comment]
This issue has been solved, it was indeed my own code. Thanks for the help!
