### ISSUE TITLE
"Missing" Hue lights cannot be controlled

### ISSUE THREAD

**Issue by Gand41f** [athombv/homey#973]
**What is your Homey version (Settings → System)?**

0.10.3 Homey
v1.0.5 Hue App

**What did you try to achieve?**

Some of my Hue lights are always reported "missing" by the bridge, despite they are powered. They are displayed with a broken chain symbol in the Homey interface and cannot be adjusted. These lamps do not react if I include them in a flow. They are also reported missing in the Hue app on my Android phone. However, in the Android app I can still control them and they do react to my commands. They also do react if Homey sets a scene including these "missing" lights.

_Please include detailed steps how we can reproduce the issue_

Most of the "missing" lights are from third party like Osram, but they are included into my Hue system.

**What was the result?**

These lamps do not react if I include them in a flow and cannot be controlled in the "Devices" surface. 

**What did you expect as result?**

To be able to control them and include them in flows even if they are "missing".

**Any other remarks**

...

**Comment by djeskoswe** [comment]
Side note: Did see missing on milight today.

**Comment by jeroenvollenbrock** [comment]
Can you please let me know whether this issue persists or not?

**Comment by jeroenvollenbrock** [comment]
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!
