### ISSUE TITLE
Could not connect brand new homey to wifi 

### ISSUE THREAD

**Issue by ArjendR** [athombv/homey#975]
**What is your Homey version (Settings → System)?**
new.new.new
received it yesterday, Friday 6 okt 2016 ;-(

**What did you try to achieve?**
I try to setup my homey for the first time.
i spend the last 2 day doing all tips/tricks from related issues...
- if have created ssid's on my netgear r7000 router in lower, upper case, simple/short & long (64# hex) passwords (wpa2-psk [aes] or wep)), max 54 Mbps of max 600 Mbps, 2.4Ghz or 5Ghz, co existence 20/40MHz on/off, smart connect on/off... And almost all permutations of the mentioned options...
- i created also other wifi hotspots on 2 different androids 
- unpowering homey after each try
- i tried from windows\ie11 OS X\safari

**What was the result?**
Always the same:
- connecting laptop or phone to setup.athom.com succeeds
- connecting laptop or phone to homey's wifi (homey setup) succeeds
- in homey setup page choosing (selecting but also typing) ssid & password succeeds
- reconnection laptop or phone after that to own wifi succeeds
 but after that it ends always with the setup.atom.com page saying
- "this is taking exceptionally long.." please hold on!
- in the mean time homey did get an ip on my wifi network (I can see it in the router info or in the hotspot info). In wire shark i see some packets coming from homeys ip address and in the 3 minutes homey responds on its http://ipaddress with a simple webpage displaying the 2 fase setup info...
- the ip connection stands for pm 3 minutes and then stops. after 20 sec ip connection stands for an other 3 minutes and stops again. This wil repeat once more, resulting in homey saying "sorry, i can't connect to the wifi..."

**What did you expect as result?**
a slightly smoother setup operation...

**Any other remarks**
any help is welcome, i will also gladly drop by at the assembly place if that is possible...
...

**Comment by blbean07** [comment]
As far as I know you have to use Googles Chrome to setup Homey. I tried different browsers without any luck. Give it go with Chrome, it got me through the setup.

**Comment by bvdbos** [comment]
https://www.athom.com/en/support/KB000001/
step 2.1 and iirc also on the box : you have to use chrome as a browser

**Comment by ArjendR** [comment]
thnnx 4 reply!
Unfortunately using Chrome doesn't do the job for me... same result: "homey could not connect to you wifi network"... I have some ancient wifi routers at work that i will try next monday, perhaps that makes a difference?

**Comment by bvdbos** [comment]
Try turning off your 5Ghz network. A lot of devices have problems with it. After the setup you should be able to turn it on again.

**Comment by ArjendR** [comment]
Unfortunately i already did that (for sure i did it tried it on your advice again) but al with the same result that homey couldn't connect to my wifi (details in first post). I also tried a hotspot with my android phones but that did not work either...

**Comment by dnhaas** [comment]
Did you reconnect your pc to the wifi network when homey is trying to connect your wifi network? Did the trick for me.

**Comment by ArjendR** [comment]
yes, all 25 times... :-)

**Comment by ArjendR** [comment]
2day i've seen the (green) light!
On my work router (exactly the same netgear R7000) it finally succeeded! Although it was on the third setup... 
I'm still uncertain what made the difference... Is it interference of other wifi-networks? Or is it just rolling the (20 sided) dice?

**Comment by KroontjesPen** [comment]
It would practical to split a Homey update and the connecting to your WiFi.
If you want to use Homey temporally in an other building then only changing to that WiFi net is needed.
Updating can be better with USB connecting. Often quicker and less risk to WiFi interferences.
Hopefully is Athom looking in that way.  ;-)

**Comment by WeeJeWel** [comment]
Great you got it working!

We'll release an improved Wi-Fi Setup within two weeks, so hopefully that will solve all problems :-)
