### ISSUE TITLE
24 hour notition in flow

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#976]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Set the time in 24 hour format. When you create a flow time based and choose for example:
23.00 it will be showed as 11.00

![24h homey](https://cloud.githubusercontent.com/assets/18025163/19214101/9249137e-8d7c-11e6-8c0f-b192557784c3.PNG)

*Please include detailed steps how we can reproduce the issue*
Create a flow time based

**What was the result?**
11:00

...

**What did you expect as result?**
23:00
...

**Any other remarks**

...

**Comment by Phunkay** [comment]
Weird, just tried it and it works as expected here...

**Comment by JPe2** [comment]
![image](https://cloud.githubusercontent.com/assets/3833862/19221989/ab22b81e-8e4e-11e6-9d4a-00aa50d06258.png)
try refreshing the page (F5)

**Comment by mike9011** [comment]
Removed cache, tried incognito tab, but still the same issue.

**Comment by robertraaijmakers** [comment]
Probably this is due to your windows time settings. If you have your date and time settings to display AM/PM time values (or any other non 24-hour clock) this will also reflect to time inputs in the browser. Can you verify this?

**Comment by WeeJeWel** [comment]
What @robertraaijmakers says is most likely correct.

**Comment by mike9011** [comment]
Yes correct, changed the Windows settings "Short Time" to HH:MM instead of H:MM.
Solved the issue.
