### ISSUE TITLE
IR: Delay between cards doesn't work.

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#978]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
I tried to send multiple IR commands after each other, with a 10 sec delay between them.

![countdown-homey](https://cloud.githubusercontent.com/assets/18025163/19220910/a4987904-8e38-11e6-8bb4-6c2133c503bc.PNG)

*Please include detailed steps how we can reproduce the issue*
-Create a flow
-Multiple IR Cards to press a buton
-Add delay between them via the stopwatch icon.

**What was the result?**
The actions fire direct after each other, without the delay between them.

**What did you expect as result?**
Wait 10 seconds before the next command is send to the IR device.

**Any other remarks**

**Comment by bvdbos** [comment]
Works for me, see bug #945 ...

**Comment by fn002449** [comment]
This does work for me!

**Comment by JPe2** [comment]
As far as I know the timers of all cards start at the same time, so your second card needs a delay of 20 sec instead of 10 sec. (at least you can try if I'm right). A third card then needs 30 sec. delay.

**Comment by mike9011** [comment]
Thanks for the tips guys, will check this tomorrow en will update this issue.
