### ISSUE TITLE
Homey flow manager 

### ISSUE THREAD

**Issue by PeterBox** [athombv/homey#979]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Try to scroll with Samsung tab 4 tablet

*Please include detailed steps how we can reproduce the issue*

Can't  use scrolling function in the homey Flow manager

**What was the result?**

No scrolling possible 

**What did you expect as result?**

...that I can scroll 

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Sorry, Android browsers are not supported (as of now).

**Comment by PeterBox** [comment]
Beetje kort door de bocht.....

**Comment by WeeJeWel** [comment]
I'm sorry, but we have to prioritize. Next thing we must support Internet Explorer and Opera Mini ;)

**Comment by PeterBox** [comment]
Voortschrijdend inzicht zo te zien
