### ISSUE TITLE
IR learning mostly not working

### ISSUE THREAD

**Issue by ClemensLR** [athombv/homey#980]
Homey Firmware Version: 0.10.3

Adding IR device, 'copy from a remote' up to now only works with Samsung blu-ray player and no other device among which KPN iTV, Sony TV, Panasonic projector. GUI indicates learning stage is complete, but in Flow devices do not work (apart from the Samsung)

**Comment by Tweaqer** [comment]
I also noticed this copying the Telfort On/Off IR remote button :(

**Comment by bvdbos** [comment]
Does the ring on the card keep spinning? That's #929 
As for Itv: #966

**Comment by ClemensLR** [comment]
During IR learning the ring lights are switched off, once the learning stage has finished, the ring starts spinning multicolour again.

**Comment by ClemensLR** [comment]
No, there is a green check mark/tick after pressing the 'test' button. I assume indicating that a IR signal has been sent. Device is not responding though. I made sure angle and distance towards device were ok.

**Comment by bvdbos** [comment]
Could you see if the camera of you mobile phone detects a white light when sending signals. Please try on multiple places around your Homey. If you're curious: you can test this with the original remote too..

**Comment by ClemensLR** [comment]
Yep, I can detect an IR signal send by Homey in all cases: Samsung/Sony/KPN remote. Only the Samsung leads to a working situation.

**Comment by Retrospected** [comment]
i can confirm, having the same issue trying to copy signals to my Sony Bravia TV sent by the RM-ED044 remote. Learning mode succesfully receives signals but sending them out in a test flow doesn't work.

**Comment by bvdbos** [comment]
@Retrospected The same issue as in : you see it's sending out a signal too, using your phone?

**Comment by ClemensLR** [comment]
For me, the IR leds in Homey do light up, but TV does not respond. Not even when Homey is very close.

**Comment by Retrospected** [comment]
@bvdbos Yes, however what fixed it is sending the signal multiple times. If i use the "multiple" card and set it to 2, my TV receives 1 signal. Also tried it with the max of 33 signals sent: my TV receives 6 signals.

This is a constant result and is based on the number of times the green light on my TV blinks :)
Maybe this also works for you and with other brands @ClemensLR ?

**Comment by ClemensLR** [comment]
@Retrospected: thx! Indeed that works for Sony. For KPN iTV so far no success.

**Comment by bvdbos** [comment]
@goldenice I assume you already looked at the iTV remotes (both KPN and Ziggo?). Are these encrypted signals of some sort?

**Comment by ClemensLR** [comment]
My Harmony One is capable of learning KPN iTV.....

**Comment by TimvanSteenbergen** [comment]
Question for ClemensLR: where on the Homey do you see the IRlight coming from? The front, side, back?Where are the IRleds located?

**Comment by ClemensLR** [comment]
You can locate them either by using your phone camera or by showing your phone torch into the gaps. The IR gaps show up as a golden component inside. One of them is located near the USB connection and then three more in an angle of 180 degrees towards the front. So in total four.

**Comment by TimvanSteenbergen** [comment]
Tried your tip torching my Homey, thanks, but I can't really distinguish any gold components. Bummer that ther is no solution for the KPN iTV yet.

**Comment by jeroenvollenbrock** [comment]
Some IR devices use a frequency that Homey cannot receive properly. Therefore a direct fix is not possible. However, Homey version 1.5.4 contains a few fixes to the manual pairing wizard, and IR apps can add send-only support for these devices, such as the [KPN iTV app](https://apps.athom.com/app/nl.kpn.ir)
