### ISSUE TITLE
Nest Thermostat doesn't show within Devices (Flow Editor)

### ISSUE THREAD

**Issue by Starf0x** [athombv/homey#981]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

I've installed, re-installed etc.. Nest App

**What was the result?**

The Nest Device doesn't show within devices (Flows).
It will show up as an app (Flows), but not as device.

**What did you expect as result?**

It will show up as an Device (Flows)

**Any other remarks**

With this failing I'm not able to control the temperature as stated on of the possibilities with the app.

**Comment by bvdbos** [comment]
Some apps are build for only one device, they don't have seperate devices. Can you use the device as a trigger (first column), condition (second column) or can you set parameters in the third column?

**Comment by caseda** [comment]
did you add a device with the nest app?, there are several devices possible (including several thermostats) how would homey otherwise know which thermostat(s) you mean

**Comment by Starf0x** [comment]
I only have 1 thermostat, and I added it as app.
But I suspect that you are right, I did not add it as device.

**Comment by Starf0x** [comment]
I did not, fixed now, thank you for your support.
