### ISSUE TITLE
switching to dutch did not work

### ISSUE THREAD

**Issue by ttje47** [athombv/homey#982]
**What is your Homey version (Settings → System)?**
v0.10.3x

**What did you try to achieve?**
change language from english to dutch, it did not work the second time

*Please include detailed steps how we can reproduce the issue*
changing the first time from english to dutch went ok,  I switched back to englisch, and subsecuently later I tried to switch to dutch again.  That did not work

**What was the result?**
systems stays in english

**What did you expect as result?**
switching to dutch

**Any other remarks**
bypass:
I deleted the dutch voice that was loaded, it was seen in the english list of voices, and that after that I was able to switch  
...

**Comment by WeeJeWel** [comment]
Should be fixed in 0.10.4!

**Comment by bvdbos** [comment]
Switched back and forth a couple of times and no problems for me....
