### ISSUE TITLE
Plugwise-app doesn't provide usage

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#984]
I just bought a Stretch to replace my Source from Plugwise. Didn't install it yet but it's mentioned that the PW-app doesn't log and provide energy-usage? Can't check the code or create pull-requests as the app is closed-source? 

Homey should be able to talk to Plugwise directly through Zigbee(+) but now I need both a Stretch and and Raspberry-PI to get logging into Homey?

**Comment by nhassink** [comment]
Energy-usage would be a very usefull enhancement to the plugwise app. Especially if it can be used as a trigger to for example notify someone that the dryer/dishwasher etc is done if the usage drops below a certain threshold.

**Comment by gruijter** [comment]
If you use the plugwise2py app with the zigbee stick you have what you want😂

**Comment by nhassink** [comment]
I have looked into this option, but I only have a stretch to interface with the circles. Don't have the zigbee stick.

**Comment by nattlip** [comment]
i still dont understand why this app code is not public, the plugwise stretch xml pages decoding is all public over the internet, there is no reason why plugwise should keep this secret becuase it is hacked as hell already for some years

**Comment by nattlip** [comment]
so athom make the code public then can the users help you wth make this app working, like zwave or hue app. half apps dont contribute to the succes of homey

**Comment by nattlip** [comment]
@RobinBol any sight on some love from you for this app

**Comment by RobinBol** [comment]
At the moment the arrangements we've made with Plugwise prohibit us from publishing the app.

We will however get into contact with them to see what we can do!

**Comment by RobinBol** [comment]
The plugwise app has been made public as of yesterday!

**Comment by nhassink** [comment]
Thanks!

**Comment by nattlip** [comment]
very good !!!

**Comment by bvdbos** [comment]
https://github.com/athombv/com.plugwise/blob/master/node_modules/plugwise-stretch/stretch.js#L90
Guess we have to start from here...

**Comment by nhassink** [comment]
Indeed. So far I have managed to add energy measurements (measure_power and meter_power capabilities) to the plugwise app, giving access to insights and flow cards that come with these capabilities. So far its working ok, will test some more though

**Comment by nhassink** [comment]
@RobinBol im kinda new to Git. I have added energy measurements (measure_power and meter_power capabilities) to the plugwise stretch and fixed an available/unavailable bug. How can I submit my changes back to you?

**Comment by RobinBol** [comment]
That is great! I take it you forked the com.plugwise app from github.com/athombv? Then you only have to go to your repo, and create a pull request (button on the top right). 

For more info see https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by RobinBol** [comment]
You can find my comments here: https://github.com/athombv/com.plugwise/pull/1#pullrequestreview-16660439.

I approved the PR, if there are others who would test these changes for you I could update the app in the app store sooner. So let me know:)

**Comment by bvdbos** [comment]
The version on Github works great, I think you can publish it to the appstore, great! Now going to mail Plugwise to get my data from the source...

**Comment by bvdbos** [comment]
Ivo from Plugwise was so kind to give me a temporary key to extract my data from Plugwise source to cvs-files. So finally my PW-network is going to be working with Homey the way it's intended... Thanks all!

**Comment by RobinBol** [comment]
App is updated in the app store!
