### ISSUE TITLE
Belkin Insight stops reporting data

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#985]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Consistent data from my insight plugs.

_Please include detailed steps how we can reproduce the issue_

Wait 1+ day after starting the Belkin app. Data stops being reported and insights stop being logged.

**What did you expect as result?**

Consistent data.

**Comment by markaswift** [comment]
It stopped again today...

**Comment by markaswift** [comment]
Any news?

**Comment by bvdbos** [comment]
Did the app crash? Or did you have to restart Homey? How is memory-usage during this period?

**Comment by markaswift** [comment]
App doesn't crash (albeit it did yesterday, but I forgot to grab the error).

The majority of the time the device simply stops updating power usage, the switch functionality still works however.

**Comment by BasKiers** [comment]
Sorry for the late response,

The Wemo app is on my todo list but I did not yet have time to look into this. I have been working on a fix for the random crashes (Involving ERRCONNTIMEOUT errors) which I am currently testing but I am not sure if this will fix this issue. This issue will be picked up soon.

Regards,
Bas

**Comment by BasKiers** [comment]
This issue should be fixed as of version 2.1.1. Please let me know if you still experience issues.

**Comment by BasKiers** [comment]
Hi, 

By my own testing this issue is fixed now. I will close this issue. If you still experience issues please open a new issue.

Regards,
Bas
