### ISSUE TITLE
Missing_Listener on the "Nobody's home" card.

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#987]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
I've made a flow with the following if/and/than:

**IF:** Someone leaves
**AND:** Nobody's home

**Please include detailed steps how we can reproduce the issue**

Create a flow with the following IF/AND:

**IF:** Someone leaves
**AND:** Nobody's home

**What was the result?**
Missing_Listener on the "Nobody's home" card.

![missing_listener](https://cloud.githubusercontent.com/assets/18025163/19270655/67916c84-8fc1-11e6-9355-783dde6700be.PNG)

**What did you expect as result?**

No missing listener. :smile: 

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
Thanks for reporting! Fixed in 0.10.4

**Comment by mike9011** [comment]
You're welcome! Should it work this way? There was a little bit discussion about it, that this wouldn' t work anyway. 
https://forum.athom.com/discussion/2066/missing-listener-in-flow#latest

**Comment by mike9011** [comment]
Thanks for the fast fix btw! Great work!

**Comment by bvdbos** [comment]
doesn't throw an error for me in 0.10.5 (anymore?)

**Comment by mike9011** [comment]
Issue solved in 0.10.5! Thanks!
