### ISSUE TITLE
Anna thermostat temperature setting is not displayed

### ISSUE THREAD

**Issue by ttje47** [athombv/homey#988]
**What is your Homey version (Settings → System)?**
0.10.3

**What did you try to achieve?**
display Anna thermostat information in Homey web and in Homey app

**What was the result?**
the temperature set is not always displayed.  Sometimes you see it, but mostly it will not be displayed.  It is not clear under what conditions it is not displayed.  The actual tempareture is always displayed correctly.

...

**Comment by RobinBol** [comment]
Hi @ttje47 could you perhaps be a bit more specific? I tried to reproduce your issue today, however I never get to the situation where the target temperature is not displayed.

**Comment by ttje47** [comment]
Hi RobinBol,  On both the desktop as on the Android app I do not see the target temperature.  See attached document.  It does not happen always,  but the attached panel is after a fresh restart of my Homey.  Hope that the panel clariefies what the problem is.
![anna](https://cloud.githubusercontent.com/assets/22756248/20542449/f2ad2f18-b101-11e6-8e02-2bc9e589b7e1.jpg)

**Comment by ttje47** [comment]
...still open,  entered the wrong button....

**Comment by RobinBol** [comment]
Fixed in v2.0.6
