### ISSUE TITLE
Not able to distinguish my two Anna thermostats

### ISSUE THREAD

**Issue by ttje47** [athombv/homey#989]
**What is your Homey version (Settings → System)?**
0.10.3

**What did you try to achieve?**
Use my two anna thermostats

*Please include detailed steps how we can reproduce the issue*
I have two Anna thermostats in two rooms.  At installation time you have to enter the unique code of each Anna.  But after doing that, you cannot view the settings anymore.  The Anna's are also not shown as devices at the settings panels.

Both Anna's are presented in the flow panels but it is not possible to distinguish between the anna's.  Which anna is where? 

Suggestion
There should be a method to give an unique identifier to the Anna's, f.i. giving them a nickname.  Or the unique identifier (filled in at installation) has to be displayed in the anna icon on the panels

**Comment by RobinBol** [comment]
You can give the Anna you are adding a name when going through the pairing process. Just click the name when it is shown and it will let you create a unique name for it.

**Comment by ttje47** [comment]
I missed it, indeed you can change the name in the icon of the anna.  Thanks for this simple solution!
