### ISSUE TITLE
plugwise source will not install

### ISSUE THREAD

**Issue by ttje47** [athombv/homey#990]
**What is your Homey version (Settings → System)?**
0.10.3

**What did you try to achieve?**
Installing Plugwise source circles

*Please include detailed steps how we can reproduce the issue*
-retrieve plugwise source app from appstore
-install the app
-define the variables in the settings panel

* problem 1
- there are two fields: server tested and server connected. Sometimes you are able to get a value 'true' but sometimes you are not able to get it.  The testing function does not seem to react

- I save the settings
- I go to adding equipment
- Plugwise sourrce is not displayed as installed,  I do a search and install the app again

*problem 2
- why I have to install the app again - and again  and again after each try to add a device

- I click on the circle icon
- when try to show circles I get the message:
  first set plugwise source  variables in settings

*problem 3
- settings are not fully saved.  After the first try, only the ip address was saved,  after the second try also the portid was saved, but anyhow not all the fields

-I refilled the variables and saved them
-I tried again to add a device
-same result - again problem 2 and problem 3

I retried to set the variables and I am forced to install the app again
- I tried again to add a device
I now get a popup with invalid driver

* problem 4
- invalid driver problem

-Delete the app and start from scratch

Last week I was - for whatever reason - able to save all fields in the variables.
-when trying to add a circle, no circles where seen

I tried to logon to the plugwise source server from another PC and that is working without any problem

*problem 5
-not able to add a circle

I gave up.  Please can the app developer have a thorough look at the app.  He/she can contact me if that will help

**Comment by bvdbos** [comment]
This bugreport should be put at
https://github.com/nattlip/com.jilles.plugwisesource
It''s not an athom-app

**Comment by ttje47** [comment]
Ok,  I add the issue on that place.
