### ISSUE TITLE
Time triggered flow with (speech) confirmation doesn't get triggered

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#992]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**

Create a flow which tiggers on time which asks for (speech) confirmation. No time trigger seems to work neither a specific time or a time interval. Testing the flow works and also using another trigger (like a Kaku remote) works. 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

Time triggered flow with (speech) confirmation doesn't trigger.

**What did you expect as result?**

Flow to be triggered and confirmation asked.

**Any other remarks**

If you change the confirmation from speech to mobile app the flow works.

**Comment by markaswift** [comment]
+1 also have this issue. Broke a few of my flows :(

**Comment by WeeJeWel** [comment]
Can you post a screenshot of a Flow that doesn't work?

**Comment by Phunkay** [comment]
Wasn't online for a couple days so I don't know if a screenshot is still needed as this is marked as staged for release. But both triggers in the flow in the screenshot below don't trigger the flow.

![naamloos](https://cloud.githubusercontent.com/assets/22442908/19441945/db521ca2-9487-11e6-9208-db3f9b4b29b9.png)

**Comment by WeeJeWel** [comment]
Fixed in 0.10.6!
