### ISSUE TITLE
Userproblem

### ISSUE THREAD

**Issue by Waronder** [athombv/homey#994]
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Make a user (give access) (for Presence)

*Please include detailed steps how we can reproduce the issue*
When I want to give someone access to my Homey via Settings - Users (click on activation mail), I can't change the name, it's given my own name... When I want to use it in Presence, I see two same users...

**What was the result?**
See above

**What did you expect as result?**
Two different usernames

**Any other remarks**

...

**Comment by WeeJeWel** [comment]
The name is the same as the user's Athom Account. Is this not correct?

**Comment by Waronder** [comment]
Dag Emile,

Zie bijlage.
Homey-app op haar telefoon geinstalleerd, maar het enige wat actief is, is
UITLOGGEN.

Ronald Wassink.

2016-10-14 20:00 GMT+02:00 Emile Nijssen <notifications@github.com>:

**Comment by WeeJeWel** [comment]
Hi Waronder,

(Please keep it english, so other users can read and jump in when needed).

I don't see an attachment. Could you re-upload?

**Comment by Waronder** [comment]
I'm sorry, I answered via email. It looks like this:
MyName (you)
Owner | MyEmailaddress

MyName
User | MyWifesEmailaddress

So the email is different, but the name is the same

**Comment by WeeJeWel** [comment]
If your wife logs in at https://accounts.athom.com, does her own name show?

**Comment by Waronder** [comment]
Yes, on the profile page, her name shows right.

**Comment by WeeJeWel** [comment]
Pretty odd, this has never happened before. Can you try revoking her access and invite her again, to make sure it happens again?

**Comment by Waronder** [comment]
I did that 5-10 times...

**Comment by Waronder** [comment]
Rebooted Homey

**Comment by Waronder** [comment]
Now I revoked her again, I rebooted Homey and now it works. Her name showed well. Could it be the last update yesterday?

**Comment by WeeJeWel** [comment]
Maybe! We did some cloud service maintenance :-) Glad it works now!

**Comment by Waronder** [comment]
But on her phone, the Devices, Media and Settings stay greyed out. 
Only Logout is black.

**Comment by Inversion-NL** [comment]
Media is out because of a massive re-write

**Comment by Waronder** [comment]
No problem, but Settings would be handy...
