### ISSUE TITLE
Greenwave Powernode 6 no power-consumption or power-load

### ISSUE THREAD

**Issue by JPe2** [athombv/homey#995]
**What is your Homey version (Settings → System)?**

Homey v0.10.5       Greenwave Systems v1.0.3

**What did you try to achieve?**
reading the power values as they where displayed in earlyer versions (0.9.x)

_Please include detailed steps how we can reproduce the issue_
normal procedure, including, switch on a plug with a load, wait more then 2 minutes, view the device.

**What was the result?**
![image](https://cloud.githubusercontent.com/assets/3833862/19357385/b4eed3e8-9171-11e6-8272-f0b871798378.png)

**What did you expect as result?**
the two values KWh and KW

**Any other remarks**
After including, the "MasterNode" is displayed as Node 6, the "Plug"nodes are numbered 1 to 6,
 so there is twice a node 6.  ( I renamed the Masternode to Node 0 )

In the Insights screen, for some nodes there is 1 parameter shown and some other nodes 2
![image](https://cloud.githubusercontent.com/assets/3833862/19357656/d816e170-9172-11e6-82de-b92a5c34f2f7.png)

In the Insights screen the nodes are not sorted, seems unlogic for me.
In the Devices screen the nodes are automaticaly sorted after refressing, 
I like to have/keep my own order of displaying in this screen.

The term "stroommeter" is incorrect, please use "verbruik" for KWh  and   "vermogen" for KW / Watt.

**Comment by jghaanstra** [comment]
This seems to be the same issue as reported at the Greenwave Systems repo here: https://github.com/athombv/com.greenwavesystems/issues/10

**Comment by RobinBol** [comment]
This is fixed in the latest update of the greenwave app. Make sure to add the sockets as 'None of the above', this will enable the kWh and W meters.

**Comment by JPe2** [comment]
@RobinBol  , thanks for the update, progress is made but not all mentioned points are fixed in the new version Greenwave Systems v1.0.5

![image](https://cloud.githubusercontent.com/assets/3833862/19810317/498029aa-9d2d-11e6-9b86-60a29b1f6900.png)
The term "stroommeter" is incorrect, please use "verbruik" for KWh and "vermogen" for Watt.

After including, the "MasterNode" is displayed as Node 6, the "Plug"nodes are numbered 1 to 6,
so there is twice a node 6. ( I renamed the Masternode to Node 0 )

In the Insights screen the nodes are not sorted, seems unlogic for me.

In the DevicesScreen if a DeviceName is changed, this device is placed at the end of the existing devices-row, very confusing!

And last but not the least: device response on first switch command after a longer time (next day) is very long, sometimes more then 20 seconds.

**Comment by RobinBol** [comment]
All issues you mention are not specific to this app, but are generic throughout Homey. Except for the master node name which I will look at. The last thing you mention doesn't come across as a problem, it might have something to do with the routing of the zwave mesh network (or just a device flaw), not something I can fix in this app though.

If I misunderstood please let me know. Thanks for reporting anyway, feedback is always welcome!

**Comment by JPe2** [comment]
Thanks Robin, great job,

@WeeJeWel   about the items that are not part of this app, f.i.:

_The term "stroommeter" is incorrect, please use "verbruik" for KWh and "vermogen" for Watt.
Used in Devices-screen and in Insights-screen.

In the Insights screen the nodes are not sorted, seems unlogic for me.

In the DevicesScreen if a DeviceName is changed, this device is placed at the end of the existing devices-row, very confusing!_

Are these items taken care of by Athome or do I have to place them in a new Github-Issue?

**Comment by JPe2** [comment]
This morning again the green lamps of both my Greenwave-6 modules were blinking (after 6 days)
I made scren-shots of the Memory-use and I see a big difference for Homey (210.68) before I did a reset and (109.38MB) after reset, looks memory leak?
![2016-11-24_165728-voor reset knipperende greenwave lampen](https://cloud.githubusercontent.com/assets/3833862/20605789/642b3092-b26d-11e6-9bd9-
9fd8fcdd566d.png)
![2016-11-24_172646 na opnieuw-opstarten via menu](https://cloud.githubusercontent.com/assets/3833862/20605804/733be87e-b26d-11e6-83be-30d601f5690b.png)

**Comment by bvdbos** [comment]
That won't matter in itself, Linus caches apps for quicker access. In both cases there's still free memory and if more memory is needed, it's taken from the apps (including Homey). Memory-leaks land in "other" afaik and that part is not big.... 
https://forum.athom.com/discussion/comment/36775/#Comment_36775 for more info...

**Comment by JPe2** [comment]
![2016-11-24_165728-voor reset knipperende greenwave lampen](https://cloud.githubusercontent.com/assets/3833862/20605867/cf5b9dd4-b26d-11e6-8b9e-61ad76f73d9d.png)
![2016-11-24_172646 na opnieuw-opstarten via menu](https://cloud.githubusercontent.com/assets/3833862/20605877/da012a9c-b26d-11e6-8f8e-1124ca1274ea.png

this morning again blinking green lamps on both my Greenwave-6 modules after 6 days of installing Homey V1.0.1,  I had this also in the previous V0.9.x
Above you can see the screenshots of the Memory use before and after restarting Homey by menu.

After the restart the green lamps are not blinking anymore, what can be the reason? @RobinBol 

( sorry @bvdbos for the mix of message and thanks for your contribution )

**Comment by RobinBol** [comment]
Might be related to this issue: https://github.com/athombv/homey/issues/1054

**Comment by RobinBol** [comment]
The green blinking leds issue should be resolved from v1.0.2

**Comment by JPe2** [comment]
@RobinBol  Unfortunately this morning the green lights of the 2 greenwave-6 devices were blinking again after a more then 6 days, not sure how long exactly but probably 10 days (v1.0.2 install). 
After a Homey restart (via menu) both started working again.  My settings for the main-node are:
![image](https://cloud.githubusercontent.com/assets/3833862/20927057/ff2c3ab8-bbbf-11e6-85a9-c67c5535270b.png)
The settings for the device-nodes are unchanged, should I change some settings?

**Comment by RobinBol** [comment]
@JPe2 we've found a minor bug in 1.0.2 that could still cause the blinking lights, this should be fixed in 1.0.3. If it is not, please create a separate issue, I will close this one. 

I have renamed the powernode sockets so there is no confusion anymore between the sockets and the main node. I think for now we will stick with stroommeter. Points 2 and 3 are rather separate and non-app specific issues, for these I created new issues internally which we will look at.

Thanks!
