### ISSUE TITLE
Wifi SSID is set to "unknown"

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#996]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

Wifi SSID is set to "unknown" instead of showing my SSID
![settings-wifi-id](https://cloud.githubusercontent.com/assets/19249884/19358655/f2626d84-9176-11e6-9cd3-adbc76ca1bc6.png)

**Comment by bvdbos** [comment]
wifi_ssid is showing for me on 0.10.5... Don't know if it wasn't before...

**Comment by Rocodamelshe** [comment]
Solved for me, cheers!
