### ISSUE TITLE
After not reacting to "confirmation" Homey does not return in "Homey stops listening" mode

### ISSUE THREAD

**Issue by Rocodamelshe** [athombv/homey#997]
**What is your Homey version (Settings → System)?**

0.10.5

**What did you try to achieve?**

Was trying to make a flow : IF it's 00.30, AND ask confirmtion "Is there somebody still awake?" (and no one is confirming), THEN put all the lights off.

*Please include detailed steps how we can reproduce the issue*

As stated above. I am aware of [#992](https://github.com/athombv/homey/issues/992)
This issue is not about 992 tho

**What was the result?**

Homey goes back to "stand-by" mode instead of "Stops listening" mode.

**What did you expect as result?**

Homey goes back to "Stops listening"

**Any other remarks**

I am muting my Sonos with "When Homey starts listening" and unmute with "When Homey stops listening".
After not giving any confirmation my Sonos will be muted until i manualy unmute it with Sonos app.

**Comment by KroontjesPen** [comment]
And #956 witch if tagged for 0.10.5
