### ISSUE TITLE
[Z-Wave] Display commands when COMMAND_CLASS_MULTI_CMD received

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/homey#999]
**What is your Homey version (Settings → System)?**
0.10.5

**What did you try to achieve?**
I tried to fix a Z-wave device by finding out what kind of information is send to Homey when the door, motion and tamper was triggered. The 'default' commands didn't seem to do the job. So I wanted to figure out what is different in this device to parse it correctly.

**What was the result?**
In the debugger (love the extra information since previous version!!) I get the following result

`[debug] node.CommandClass['COMMAND_CLASS_MULTI_CMD'].on('report') arguments: { '0': { value: 1, name: 'MULTI_CMD_ENCAP' },  '1':    { 'Number of Commands (Raw)': <Buffer 03>,     'Number of Commands': 3,     'Variant Group': [ [Object] ] },  '2': null }
`

**What did you expect as result?**
That I can see what kind of commands are in there. So that I can add these to my command class handler in the driver file.

**Any other remarks**
Keep up the good work 👍

**Comment by caseda** [comment]
you can unfold the "variant group" yourself. it's not that hard

**Comment by WeeJeWel** [comment]
Or use ZwaveDriver to do the MiltiChannel parsing for you, it's a lot easier :)

**Comment by caseda** [comment]
well... Its Multi _Command_, not Multi _Channel_ @WeeJeWel

**Comment by robertraaijmakers** [comment]
Still finding it quite hard to unfold the group via Terminal... I'm probably missing something? Is there anywhere I can find a topic / manual / or someone that can give me instruction on how to find what kind of commands are present in the multi_cmd group?

![screen shot 2016-10-14 at 21 30 20](https://cloud.githubusercontent.com/assets/1773099/19400218/7d3dfa66-9255-11e6-8458-9d2bf7bd62e4.png)

**Comment by WeeJeWel** [comment]
Whoops, indeed!

Try replacing `console.log( ... )` in ZwaveDriver.js by `console.log( JSON.stringify( ..., false, 4) )` and you'll see everything that's in there :-)

**Comment by robertraaijmakers** [comment]
Cool, thanks!
